### ISSUE TITLE
OSPOS 3.0.1 - Unable to load the requested class: encryption

### ISSUE THREAD

**Issue by diganto213** [jekkos/opensourcepos#1000]
Hi ,

I am trying to setup the new version of the software in XAMPP 3.2.1 but I am getting below error
A PHP Error was encountered

Severity: Notice

Message: Undefined variable: mimes

Filename: core/Output.php

Line Number: 107

An Error Was Encountered

Unable to load the requested class: encryption

**Comment by daN4cat** [comment]
If you read the FQA in the README you could read that MCrypt is required. So please make sure it's part of your PHP extensions.

**Comment by daN4cat** [comment]
@diganto213 have you sorted this out?
