### ISSUE TITLE
Item Image not uploading says the

### ISSUE THREAD

**Issue by onyema3** [jekkos/opensourcepos#1002]
### Issue / Question / Bug

Before submitting an issue please make sure you remove the first section of the template and you tick (add a x between the square brakets) and agree with all the following check boxes:

- [X] Checked the current issues database and no similar issue was already discussed
- [X] Read the README, WHATS_NEW and UPGRADE
- [X] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php5-gd, php-intl and sockets installed)
- [X] Reporting an issue of an unmodified OSPOS installation
- [X] PHP version is at least 5.5 and not 7.x
- [X] MySQL version is 5.5 or 5.6 and not 5.7
- [X] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [X] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report (Open Source Point Of Sale Version 3.0.1 - 4f5ad57.)
- [X] Know the name and version of OS, Web server and MySQL and will add to my issue report
Server Name	cloud
cPanel Version	60.0 (build 25)
Apache Version	unknown
PHP Version	5.6.28
MySQL Version	5.6.34
Architecture	x86_64
Operating System	linux

### Installation information
Latest Masters 3.0.1

### Expected behaviour
Update an item, click on select image, browse to the image and submit. The image is uploaded.

### Actual behaviour
Update an item, click on select image, browse to the image and submit. Image is not uploaded and an error message appears saying  upload path does not appear to be valid

### Steps to reproduce the issue
Update an item, click on select image, browse to the image and submit. Image is not uploaded and an error message appears saying  upload path does not appear to be valid
![untitled](https://cloud.githubusercontent.com/assets/12876751/20551829/d05dbf8e-b144-11e6-84db-1e8e28aa5b12.jpg)

**Comment by onyema3** [comment]
I cannot also upload company logo in store config

**Comment by daN4cat** [comment]
Is this with the latest 3.0.1?
Also please make sure the for access right for public, uploads and subdir is correct.
Last thing to check are .htaccess files, are those the ones from master or have you changed something?
I mean the one in ospos dir and ospos/public for.

**Comment by onyema3** [comment]
Yes lastest 3.0.1. Untouched.

**Comment by onyema3** [comment]
The rights for  public, uploads and subdir are set as 755

**Comment by daN4cat** [comment]
I just tested and it's working fine on my side. So there must be something.
What about the .htaccess files?

**Comment by onyema3** [comment]
I've not touched it

**Comment by onyema3** [comment]
Don't even know where to find it

**Comment by daN4cat** [comment]
you should see in your ospos dir a file called .htaccess if you check from a shell console (or Terminal window).
There is another one in public/.htaccess.

At the moment nothing more springs to my mind outside the couple of things I already mentioned.

**Comment by onyema3** [comment]
I'm thinking it has something to do with the items form.
I tried to add a new item, after filling out the form and clicking submit, nothing happens

**Comment by daN4cat** [comment]
Can you please make sure you really have all the code from latest master 3.0.1?
This sounds really strange as it's working here.

**Comment by onyema3** [comment]
It submits without adding an image so its still the image issue i guess

**Comment by onyema3** [comment]
Strange indeed.. working very without issues on my local install

**Comment by daN4cat** [comment]
This sounds some setup story issue.

**Comment by onyema3** [comment]
I just uploaded, changed the parameter in the database.php file. Thats all

**Comment by daN4cat** [comment]
And still the issue or no?

**Comment by onyema3** [comment]
Yes, issue persist

**Comment by daN4cat** [comment]
No idea I'm afraid. Let see if other report it...

same Apache version on both? Is PHP the same, extensions the same?

**Comment by onyema3** [comment]
Yes

**Comment by daN4cat** [comment]
and installation path the same?

**Comment by onyema3** [comment]
I'm not sure what you mean by installation path

**Comment by daN4cat** [comment]
The two servers on different machines point to similar directory path?

**Comment by onyema3** [comment]
yes

**Comment by daN4cat** [comment]
I close this because it's a specific setup issue.
If another similar case opens we reconsider the matter but I really don't have a clue for your case.

**Comment by daN4cat** [comment]
One extra thing, are owner and group correctly assigned to die and subdir? For instance if you created a dir like root might be restricted to web user.

**Comment by onyema3** [comment]
How do i correct this?

**Comment by daN4cat** [comment]
chown use that, man chown or google around for help
