### ISSUE TITLE
Numeric sorting of Summary & Detailed Reports tables not working properly

### ISSUE THREAD

**Issue by daN4cat** [jekkos/opensourcepos#1003]
Just noticed that clicking on any numeric column with currency symbol (in front in my case) does not sort correctly. It seems to follow an alphabetic sorting order instead of a numeric one as you would expect.

However Takings seems to work fine, so something is missing on the report tables side.

@jekkos something for you to fix this time. And we should fix this in 3.0.1.

**Comment by daN4cat** [comment]
@jekkos we are pending on this to release 3.0.1. Any idea if you are able to get it sorted soon?

**Comment by jekkos** [comment]
Ok will check asap.

**Comment by jekkos** [comment]
Ok I had a quick look. It seems that for prices sorting is disabled in item kits module.

**Comment by jekkos** [comment]
For the main tables sorting is done by sending the field to sort on to PHP which then applies it to the current query. This might indeed not have been implemented in reports. I also want to verify if sorting on currency works correctly in eg items.

**Comment by daN4cat** [comment]
Sounds like we missed something during the 3.0.0 testing.
With the Summary reports rework it should be probably easier now to add something common to all of them for the sorting. Detailed reports are separate. Not sure about the Inventory ones, I didn't check those.

By the way, it would be good to have proper pagination support too and avoid creating huge tables on client (web browser) side.

**Comment by jekkos** [comment]
Think that will require quite some rework there.. Might be too big for 3.0.1. I checked the code and remember now that it's not directly possible to add extra attributes to the header unless I change a lot of code. 

Pagination is all done client side now for that reason as well. I'll have to think how to redesign the whole to make it better.

**Comment by jekkos** [comment]
Thing is that detailed reports should use transform_headers instead of transform_headers_readonly.

**Comment by daN4cat** [comment]
Not sure I follow, do you mean that proper sorting is too much work? Or was that about pagination?

**Comment by jekkos** [comment]
Ok .. I've reviewed the report code a bit, found two more bugs in the temp table creation refactoring.

**Comment by jekkos** [comment]
I've tested sorting on reports with uk locale and it seems to work fine by default? I have refactored header generation a bit in case we want to customize  on column behavior.

**Comment by odiea** [comment]
Just did this
![2016-11-25 15_20_05-](https://cloud.githubusercontent.com/assets/10962177/20636009/dc1919e2-b322-11e6-959e-7a39f202d7b9.png)
 pull. Does not look correct to me.

**Comment by jekkos** [comment]
what the heck .. let me check

**Comment by jekkos** [comment]
Ok I don't really understand, works fine here, which browser? This is the detailed sales report I gues? I've tested it with only one line and works fine..

**Comment by odiea** [comment]
Here is the receivings report in chrome.

**Comment by odiea** [comment]
The first was in Firefox.

**Comment by jekkos** [comment]
I'm deploying to an external server to verify if the issue persists

**Comment by jekkos** [comment]
I have just deployed latest master here

http://web-1.opensourcepos.16c7256a.cont.dockerapp.io/

can't reproduce the report works fine?

**Comment by odiea** [comment]
It appears to be confined to just the detailed reports. Here is employee report. Customer looks the same.
![2016-11-25 16_05_52-](https://cloud.githubusercontent.com/assets/10962177/20636377/3a7dfd6c-b329-11e6-9e95-ac948f5b013c.png)

**Comment by jekkos** [comment]
Ok ic employee detailed report is broken let me fix that

**Comment by odiea** [comment]
I reverted this commit and it is back to normal.
![2016-11-25 16_10_43-](https://cloud.githubusercontent.com/assets/10962177/20636418/ced2441e-b329-11e6-8f90-a256e4b0985d.png)

**Comment by jekkos** [comment]
Yes will revert that part and leave the two refresh bug fixes.. sorting on currency seems to work fine anwyay?

**Comment by jekkos** [comment]
Should be back to normal now.. .can you try and see if sorting currency works?

**Comment by odiea** [comment]
This is sorted on subtotal.
![2016-11-25 16_27_58-ugly sweater store _ powered by ospos 3 0 1](https://cloud.githubusercontent.com/assets/10962177/20636565/3a9eafaa-b32c-11e6-9953-2c345ac32c3f.png)

**Comment by jekkos** [comment]
Ok I only tested with two entries, seems to be alphabetically indeed.

**Comment by daN4cat** [comment]
Yes, that's the issue it's sorted in alphabetical order not numeric one... so the problem is still three

**Comment by jekkos** [comment]
Should be fixed now in detailed reports.

**Comment by odiea** [comment]
Back to this again in all detailed reports.
![2016-11-26 04_40_16-wedidit _ powered by ospos 3 0 1](https://cloud.githubusercontent.com/assets/10962177/20640061/8095ea12-b392-11e6-9def-f9c29c7d6eab.png)

**Comment by jekkos** [comment]
Seems to work fine here as always. Might be some data breaking the report? Do you see any error in js console?

**Comment by jekkos** [comment]
I will need to have a look at that page source to see if what's going oni

**Comment by jekkos** [comment]
I've deployed an instance on http://web-1.opensourcepos.d2560148.cont.dockerapp.io/

.. Did one sale + receiving, seems to work fine in both detailed + summary reports

**Comment by jekkos** [comment]
@odiea could you try to reproduce on that environment?

**Comment by daN4cat** [comment]
There is a problem:

```
<h4>A PHP Error was encountered</h4>

<p>Severity: Notice</p>
<p>Message:  Use of undefined constant readonly - assumed 'readonly'</p>
<p>Filename: helpers/table_helper.php</p>
<p>Line Number: 128</p>
```

**Comment by daN4cat** [comment]
It should be:

```
function transform_headers($array, $readonly = FALSE)
{
	$result = array();

	if (!$readonly)
	{
```

@jekkos are you fixing? If not I commit that fix in master

**Comment by daN4cat** [comment]
OK, fixed. @odiea try the latest code from master.
Detailed sales works fine and sorts as expected, now checking the other reports.

**Comment by jekkos** [comment]
@daN4cat Ok thanks for the help there.. think it was a merge problem.

**Comment by daN4cat** [comment]
However, summary reports are still not fine. Also inventory ones are not fine.

It looks like the detail ones are fine.

**Comment by jekkos** [comment]
You mean the sorting? Or the whole report.

**Comment by daN4cat** [comment]
The sorting

**Comment by jekkos** [comment]
Indeed I need to finish those

**Comment by odiea** [comment]
![2016-11-26 04_57_37-program manager](https://cloud.githubusercontent.com/assets/10962177/20640294/f7071c62-b396-11e6-8a92-ff3b948ebbe9.png)
![2016-11-26 04_57_01-program manager](https://cloud.githubusercontent.com/assets/10962177/20640298/fb6cebec-b396-11e6-96f8-a2a01d33c414.png)

**Comment by odiea** [comment]
What all do I need to enable to get php errors showing again?

**Comment by daN4cat** [comment]
Strange, works fine with my installation.

**Comment by daN4cat** [comment]
I test US and different theme and works fine.

**Comment by daN4cat** [comment]
@odiea have you updated all the files, controllers, model, helpers and even the views/tabular_details.php?

**Comment by daN4cat** [comment]
Moreover the issue I fixed should have shown no table at all to you, so I'm afraid the code at the time couldn't have been the right one....

**Comment by odiea** [comment]
I will redownload from master and see what changes.
![2016-11-26 05_27_21-](https://cloud.githubusercontent.com/assets/10962177/20640361/1842d0ea-b399-11e6-89c2-8f5d12b2d916.png)

**Comment by odiea** [comment]
This is from the latest master.

![2016-11-26 05_37_35-](https://cloud.githubusercontent.com/assets/10962177/20640424/a75c152e-b39a-11e6-8204-8a9acbe4573c.png)

**Comment by odiea** [comment]
It now appears that it may be a php 7 issue. Works fine with earlier php.

**Comment by daN4cat** [comment]
Read the README and the FAQ.... ahaha

**Comment by odiea** [comment]
how do I add the debug=true to the page?

**Comment by daN4cat** [comment]
?debug=true at the end of the URL

**Comment by jekkos** [comment]
Ok finished up  the last part.. will push now.

**Comment by jekkos** [comment]
hold your horses

**Comment by odiea** [comment]
So with that enabled no tables show just the totals at the bottom.

**Comment by daN4cat** [comment]
because you need to have all the css and js in public dir, I didn't test that mode since a while, so not sure it works as expected

**Comment by jekkos** [comment]
It should work.. I've used it today to debug some stuff.

**Comment by odiea** [comment]
I guess I will just keep reverting this commit until php 7 is working.

**Comment by daN4cat** [comment]
php 7 is not supported

**Comment by odiea** [comment]
This is what I got.
![2016-11-26 06_25_11-program manager](https://cloud.githubusercontent.com/assets/10962177/20640653/2253cb36-b3a1-11e6-9d2c-c4ce1427fe41.png)

**Comment by odiea** [comment]
If this is a php7 error it is the first.

**Comment by daN4cat** [comment]
no, that's no php7. Sorry but now we are messing up stuff here.
This issue is about the table sorting, let's close that please.

**Comment by jekkos** [comment]
It probably does not  load because bower install wasn't run

**Comment by odiea** [comment]
When 2 different commits are made it is tough to try and figure out which commit is giving the main issue.
So I will not report any table issues here.

**Comment by jekkos** [comment]
Ok commit pushed for currency in summary reports.

**Comment by odiea** [comment]
I will let you 2 test the table sorting because now I have no tables to sort.

**Comment by daN4cat** [comment]
@jekkos almost right. There is a problem with negative numbers:

![image](https://cloud.githubusercontent.com/assets/636048/20640919/47af86de-b3e4-11e6-945c-62cb3276d4ed.png)

as you can see the negative number is sorted as it's a positive one after 0.

**Comment by daN4cat** [comment]
Discount summary, the discount % is not sorted correctly too:

![image](https://cloud.githubusercontent.com/assets/636048/20640944/b2096cb6-b3e4-11e6-8f3a-223fa7d53ac5.png)

**Comment by daN4cat** [comment]
I fixed an issue with Summary_taxes percent column as it was reporting the tax amount not percent.

**Comment by daN4cat** [comment]
@jekkos  the rest seems fine and working properly, just the two issues I reported about.

**Comment by daN4cat** [comment]
The summary discount sorting was an easy fix, using the same as in taxes the current sorting tag.

So it's only a matter of fixing the negative numbers.

**Comment by jekkos** [comment]
I've got a fix for that, adapt the regex to leave minus sign in there

**Comment by daN4cat** [comment]
Negative number still not right.

**Comment by daN4cat** [comment]
I have the currency symbol in front, not sure that makes a difference here as Euro one comes after.

**Comment by daN4cat** [comment]
@jekkos are you looking into the issue?

**Comment by daN4cat** [comment]
Actually, after a refresh I can see that it doesn't work anymore (the sorting)

**Comment by daN4cat** [comment]
All works fine, something went wrong in the pull & code refresh.

**Comment by daN4cat** [comment]
Fixed again the tax_percent column in Summary_taxes

**Comment by daN4cat** [comment]
Tested and it seems fine to me, therefore I close.

**Comment by odiea** [comment]
This is the first php 7 issue. I loaded it into php 5.6 and it works .
