### ISSUE TITLE
I don't know how to install New version, the last version I use is 2.3.2

### ISSUE THREAD

**Issue by Theng** [jekkos/opensourcepos#1004]
An uncaught Exception was encountered

Type: Error

Message: Call to undefined function Racecore\GATracking\Client\Adapter\socket_create()

Filename: G:\xampp\htdocs\opensourcepos-master\vendor\ins0\google-measurement-php-client\src\Racecore\GATracking\Client\Adapter\Socket.php

Line Number: 26

Backtrace:

File: G:\xampp\htdocs\opensourcepos-master\vendor\ins0\google-measurement-php-client\src\Racecore\GATracking\Client\Adapter\Socket.php
Line: 114
Function: createConnection

File: G:\xampp\htdocs\opensourcepos-master\vendor\ins0\google-measurement-php-client\src\Racecore\GATracking\GATracking.php
Line: 339
Function: send

File: G:\xampp\htdocs\opensourcepos-master\vendor\ins0\google-measurement-php-client\src\Racecore\GATracking\GATracking.php
Line: 370
Function: callEndpoint

File: G:\xampp\htdocs\opensourcepos-master\application\libraries\Tracking_lib.php
Line: 87
Function: sendTracking

File: G:\xampp\htdocs\opensourcepos-master\application\controllers\Secure_Controller.php
Line: 68
Function: track_page

File: G:\xampp\htdocs\opensourcepos-master\application\controllers\Secure_Controller.php
Line: 21
Function: track_page

File: G:\xampp\htdocs\opensourcepos-master\application\controllers\Home.php
Line: 9
Function: __construct

File: G:\xampp\htdocs\opensourcepos-master\public\index.php
Line: 315
Function: require_once

**Comment by daN4cat** [comment]
Read the FAQ and README first please.
