### ISSUE TITLE
not show items list

### ISSUE THREAD

**Issue by Yovito** [jekkos/opensourcepos#1005]
###BUG

### Installation information
linux 16.04 with apache, php 7, mysql 14.14, opensourcepos 3.0.0

2. I already create several items wich i confirmed on the DATABASE.
### Expected behaviour

full list of the items stored

### Actual behaviour

when i click items to see my items list it
it show the message "no item to show"

### Steps to reproduce the issue
1.create an item
2. click on items list.

[http://res.cloudinary.com/dm3xjx1bn/image/upload/v1479955860/errror_log_bduhg2.png](url)

**Comment by daN4cat** [comment]
Read the README and FAQ. No PHP7 and never heard of MySQL 14.14.
