### ISSUE TITLE
Modules freezes while try to open... receiving, store config, sales, while all other are opening properly 

### ISSUE THREAD

**Issue by bill-goldberg** [jekkos/opensourcepos#1008]
### IMPORTANT IMPORTANT IMPORTANT

Chose what you want to report: New Feature or Bug.
If you remove the template when submitting a Bug your issue will be closed as we cannot help without basic information.

### New Feature / Enhacement

For New Features or Enhacements please remove all the template text and clearly write your proposal.
It's important to state whether you expect the community to implement it or you will contribute the work.
Please bear in mind that we will implement new features only on the current code, there is no support for old versions.

### Issue / Question / Bug

Before submitting an issue please make sure you remove the first section of the template and you tick (add a x between the square brakets) and agree with all the following check boxes:

- [x] Checked the current issues database and no similar issue was already discussed
- [x] Read the README, WHATS_NEW and UPGRADE
- [x] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php5-gd, php-intl and sockets installed)
- [x] Reporting an issue of an unmodified OSPOS installation
- [x] PHP version is at least 5.5 and not 7.x
- [x] MySQL version is 5.5 or 5.6 and not 5.7
- [x] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [x] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [x] Know the name and version of OS, Web server and MySQL and will add to my issue report

### Installation information
localhost
wampserver2.5 x64
Apache-2.4.9
Mysql-5.6.17
php5.5.12

### Steps to reproduce the issue

**Comment by bill-goldberg** [comment]
![github error_1](https://cloud.githubusercontent.com/assets/23611136/20592155/18ab43f2-b252-11e6-8b06-8be6cb6efa90.jpg)

**Comment by daN4cat** [comment]
Have you installed all the required PHP extensions? Read the FAQ...

**Comment by bill-goldberg** [comment]
Yes I did.

**Comment by bill-goldberg** [comment]
according to you what could be the cause ?

**Comment by odiea** [comment]
Post a screen shot of your wamp server config. Either an extension is not enabled or you have edited the footer. 
![2016-11-24 04_48_37-installing wampserver make wordpress core](https://cloud.githubusercontent.com/assets/10962177/20597516/6cedced6-b201-11e6-8f46-349984172a9b.png)

**Comment by bill-goldberg** [comment]
No I didn't touch the source code. here is the screenshot for extensions
![wamp ext](https://cloud.githubusercontent.com/assets/23611136/20598896/558e09ca-b271-11e6-8fb7-29e2cc593771.jpg)

**Comment by odiea** [comment]
If you read any of the documentation you would see what extension is missing.

**Comment by bill-goldberg** [comment]
I Checked all extensions are enabled like php-gd, php-bcmath, php-intl, php-sockets and php-mcrypt

**Comment by odiea** [comment]
And where do you see intl on the list of enabled extensions?

**Comment by bill-goldberg** [comment]
I checked intl in php.ini file

**Comment by odiea** [comment]
It appears then you will need to find another way to enable it. If it doesn't show on the list then its not enabled.

**Comment by bill-goldberg** [comment]
What i do next ?
![intl](https://cloud.githubusercontent.com/assets/23611136/20599404/01b40fe0-b274-11e6-89c6-c066da85641a.jpg)

**Comment by odiea** [comment]
Google is your friend.
http://cj-ramki.blogspot.com/2015/07/solution-unable-to-load-or-find-php.html#.WDbkh1zFkf0

**Comment by odiea** [comment]
Restart the server when you are finished.

**Comment by daN4cat** [comment]
Before that FAQ helps: https://github.com/jekkos/opensourcepos#faq 

`If the following error is seen in sales module Message: Class 'NumberFormatter' not found then you don't have php5-intl extension installed. Please check the wiki to resolve this issue on your platform. If you use WAMP, please read issue #949`

**Comment by bill-goldberg** [comment]
Thank you @odiea ... it worked .. now running properly...
