### ISSUE TITLE
Custom1 Field in Sales Line item

### ISSUE THREAD

**Issue by Ibnumarjan** [jekkos/opensourcepos#1013]
### IMPORTANT IMPORTANT IMPORTANT

Chose what you want to report: New Feature or Bug.
If you remove the template when submitting a Bug your issue will be closed as we cannot help without basic information.

### New Feature / Enhacement

For New Features or Enhacements please remove all the template text and clearly write your proposal.
It's important to state whether you expect the community to implement it or you will contribute the work.
Please bear in mind that we will implement new features only on the current code, there is no support for old versions.

### Issue / Question / Bug

We want to have Custom1 field in Sales line item area next to item name, how can we have this. This only for view, no need to save

- [X] Checked the current issues database and no similar issue was already discussed
- [X] Read the README, WHATS_NEW and UPGRADE
- [X] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php5-gd, php-intl and sockets installed)
- [X] Reporting an issue of an unmodified OSPOS installation
- [X] PHP version is at least 5.5 and not 7.x
- [X] MySQL version is 5.5 or 5.6 and not 5.7
- [X] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [X] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [X] Know the name and version of OS, Web server and MySQL and will add to my issue report

### Steps to reproduce the issue

**Comment by Ibnumarjan** [comment]
We want to have Custom1 field in Sales line item area next to item name, how can we have this. This only for view, no need to save

**Comment by jekkos** [comment]
@Ibnumarjan this will soon be available, but after you have donated something to the project. WIll announce when it's ready. Hope this is ok for you.

**Comment by daN4cat** [comment]
See #68

**Comment by jekkos** [comment]
Let's stick with #68 to track all this. Currently this feature is available in my test build.
