### ISSUE TITLE
"The upload destination folder does not appear to be writable" when upload images

### ISSUE THREAD

**Issue by williamtran892** [jekkos/opensourcepos#1014]
### Issue / Question / Bug

Before submitting an issue please make sure you remove the first section of the template and you tick (add a x between the square brakets) and agree with all the following check boxes:

- [x] Checked the current issues database and no similar issue was already discussed
- [x] Read the README, WHATS_NEW and UPGRADE
- [] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php5-gd, php-intl and sockets installed)
- [x] Reporting an issue of an unmodified OSPOS installation
- [] PHP version is at least 5.5 and not 7.x
- [] MySQL version is 5.5 or 5.6 and not 5.7
- [] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [x] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [x] Know the name and version of OS, Web server and MySQL and will add to my issue report

### Installation information

Deployed on docker as instructed in Readme file (Running Version 3.0.1 - 4f5ad57) on 1 GB Memory / 30 GB Disk / Ubuntu 14.04.5 x64
### Expected behaviour

Should be able to upload images

### Actual behaviour

Cannot upload images

### Steps to reproduce the issue

- Try to upload an image in store config. 
- Pop up shows "The upload destination folder does not appear to be writable"

**Comment by williamtran892** [comment]
I checked Readme, it requires permission as 755 on output folder which is set in docker script. To me this look like my env got some problems. Do you have any suggestion?

**Comment by daN4cat** [comment]
This went in Release 3.0.1

**Comment by jekkos** [comment]
@williamchanrico can you redeploy your stack and verify if this is working?

**Comment by williamtran892** [comment]
I just redeployed it again. The problem still persists. The service endpoint is [here](http://web.tam-ospos-stack.e4d03f7d.svc.dockerapp.io/)

**Comment by jekkos** [comment]
Did you update the stack file? Or just did a redeploy? Might be easier to adapt the stack file manually in this case, or if you're not up to that remove the stack and readd it using the button in the README

**Comment by williamtran892** [comment]
Yes, I updated stack file and tried to redeployed just now. Problem still persists. Should I try with higher configuration?

**Comment by jekkos** [comment]
Did you chose to recreate the volumes?

**Comment by williamtran892** [comment]
I am not really sure what you mean by recreate the volumes, but I did try to create a new instance and redeployed.

**Comment by williamtran892** [comment]
I also tried to change provider of Docker Cloud from Digital Ocean to Azure but it does not help. Do I need to create additional volumes and attach to VM instance?

**Comment by jekkos** [comment]
I'll try and verify this bug later today

**Comment by daN4cat** [comment]
@jekkos is this sorted?

**Comment by jekkos** [comment]
@daN4cat Did a fix for this issue. Owner of the uploads folder is now the apache user.

**Comment by jekkos** [comment]
Don't know if this fix will work. The issue is that the file permissions are reset after the volume is mounted at runtime. At least this command sets it right for the container that is running at that moment

`docker-cloud container exec web-1 chown -R www-data:www-data /app/public/uploads`

**Comment by jekkos** [comment]
You need to have install dcoker-cloud cli first using `sudo pip install docker-cloud`

**Comment by jekkos** [comment]
Ok I did a short retest and after recreating the volumes all is working now. So either you redeploy the stack and recreate volumes (this means lose all data), or you execute the docker-cloud exec command as noted here.

Can someone verify so I can close? @williamtran892

**Comment by jekkos** [comment]
Permissions now set to 755 instead of 775

**Comment by williamtran892** [comment]
Yes, I have just tried with your changes. It now allows to upload images via docker installation. Thank you so much

**Comment by mchablet** [comment]
root@OsPos:/var/www/html# docker-cloud container exec web-1 chown -R www-data:www-data /app/public/uploads
Not authorized

**Comment by jonathanprieto99** [comment]
Can somebody explain in details how to resolve this problem.
I have exactly the same problem when I try to upload the company logo.
Thank you

**Comment by daN4cat** [comment]
Is that with docker image?
