### ISSUE TITLE
How to track expenses of a shop within pos?

### ISSUE THREAD

**Issue by ishtiaquesarwar** [jekkos/opensourcepos#1015]
Hello

I wanted to add another module or feature (if you can show or guide me to do it) of daily shop expense tracking. For example every shop has few staffs working, their daily lunch, snacks etc has a cost, their monthly salary is also an expenditure. Apart of the sales transaction i can't track all these expenses of daily basis in the system and see a weekly or daily report of it from report section

An entry form for expense input category wise with date and comment
a simple expense report with total amount 

so that i can see how much expense i am doing weekly basis and monthly or daily basis

can you please share how to do it?

thanks
ishtiaque

**Comment by jekkos** [comment]
I think this request is out of scope. There are other solutions on the market that are focused on doing this specifically, see expensify or expenditure.

**Comment by ishtiaquesarwar** [comment]
Its not possible like Item entry and Reports? its just a simple expense
form (entry) category wise and then generating a report from report
section. why do you consider this as out of scope work?

A.M.Ishtiaque Sarwar
Managing Director
*Soft Tech Innovation Ltd*

*Consultant:*
NARRI Consortium (8 International NGO's)
Azadi Technologies, Chittagong.
Sagarika Samaj Unnayan Sangstha,

*Business Concerns*: *MUTHOFUN <http://www.muthofun.com/> |  aamarPay
<https://www.aamarpay.com/> | eBiponon <http://www.ebiponon.com/>* |

*C*: 880-1711-272324 | 880-1611-272324
*E*: ceo@softbd.com | info@softbd.com
*W*: www.softbd.com | www.softbd.net

*Skype*: softbd | *GTalk*: ishtiaque.sarwar | *Linked In*: ishtiaquesarwar
<https://bd.linkedin.com/in/ishtiaquesarwar>

DISCLAIMER: This email (including any attachments) is intended only for use
by the named addressee(s) and may contain private, confidential and/or
privileged material. Any reliance, dissemination, distribution, review,
copy or other use of this email by person(s) who are not the intended
recipient is prohibited. If you have received this email in error, please
notify the sender immediately by email and permanently delete the email and
any copies (including print-outs). E-mail transmission cannot be guaranteed
to be secure or error-free as information could be intercepted, corrupted,
lost, destroyed, arrive late or incomplete, or contain viruses. The sender
therefore does not accept liability for any errors or omissions in the
contents of this message, which arise as a result of e-mail transmission.

**Comment by jekkos** [comment]
I would be able to answer the question on how to add a module, but I think this has probably been asked and answered already in the past. I think the code is self explanatory, just see how it's done for other modules.

Regarding scoping the POS is really a point of sale and not an accounting or expense tracker software.

**Comment by daN4cat** [comment]
Well the petty cash transactions would be useful to keep track of the cash so and end of the day you can easily check what's left.
This was discussed in the past already see #440

**Comment by WebShells** [comment]
any updates regarding this ?

**Comment by ishtiaquesarwar** [comment]
No nothing update

**Comment by daN4cat** [comment]
See #440
