### ISSUE TITLE
## Issue/ Version 3.0.1 redirected too many times 

### ISSUE THREAD

**Issue by beinafuushop** [jekkos/opensourcepos#1016]
### Installation information

--Installed in Personal website hosted by Bluehost
- [] Reporting an issue of an unmodified OSPOS installation
- [] PHP version is  5.5 
- [] MySQL version is 5.6.32
- [] Database upgrade script run successful
- [] OSPOS version 3.0.1
- [] Apache 2.2.31 

### Expected behaviour
 Login screen is displayed, after providing username/password it shhould direct to home page.

### Actual behaviour

 Login screen is displayed, after providing username/password it shows error redirect too much.

### Steps to reproduce the issue
![image](https://cloud.githubusercontent.com/assets/23030848/20713945/492da77e-b65b-11e6-9cb6-4955d33b6d90.png)
![image](https://cloud.githubusercontent.com/assets/23030848/20713996/847e1e76-b65b-11e6-9755-e9b2230ad94c.png)

**Comment by daN4cat** [comment]
It's a problem with your .htaccess configuration in public dir and the fact that you are using a subdir.
Please read the comments in .htaccess.

**Comment by beinafuushop** [comment]
I tried o do the changes as per instruction but now even login page is not displayed.Only too many redirections error occurs.
![image](https://cloud.githubusercontent.com/assets/23030848/20745919/7de8720c-b6f4-11e6-947e-272156f4f165.png)

**Comment by daN4cat** [comment]
remove the https://beinafuuoline.com/ from it an try again

**Comment by beinafuushop** [comment]
Thank you daN4cat for support, I tried the same and now am getting 404 error file not found, after providing username and password.
![image](https://cloud.githubusercontent.com/assets/23030848/20747266/8d2acab6-b6fa-11e6-9369-e4bbf5cba750.png)
![image](https://cloud.githubusercontent.com/assets/23030848/20747307/ab82f1f0-b6fa-11e6-8243-84c9701a9171.png)

**Comment by daN4cat** [comment]
why no space between ^(.*)$ and /~bei...?

**Comment by daN4cat** [comment]
and when you point to your root webpage which path do you user? `~beinafu1` or no?

**Comment by beinafuushop** [comment]
yes i use ~beinafu1

**Comment by beinafuushop** [comment]
When i put the space and try to access the link (https://beinafuuonline.com/~beinafu1/testversionthree/public/)  am getting the error, When i remove the space i can access login page.
![image](https://cloud.githubusercontent.com/assets/23030848/20749613/12561e58-b704-11e6-8520-89f06c4516a5.png)

**Comment by daN4cat** [comment]
So you can access the login page now, right?

**Comment by beinafuushop** [comment]
Yes Login page is accessible, but after providing username and password, am getting 404 file not found error.

**Comment by daN4cat** [comment]
please check if .htaccess path has some issue with the use of ~, you should not be required to remove the space that's not correct.
Maybe try `^(.*)$ /\~beinafu1...`, having the space.

**Comment by daN4cat** [comment]
or /\~\bei... can't remember but google around for a solution.

**Comment by beinafuushop** [comment]
i Tried to remove ~beinafu1 in the ht.access and still am getting same error after providing username and pasword. 

NB: I tried to remove ~beinafu1 in the url as well but it automatically include ~beinafu1 while trying to open the page, Please help.

**Comment by daN4cat** [comment]
and did you do what I said in the earlier comment using \ ?

**Comment by beinafuushop** [comment]
Yes i tried all those options and same error displayed. Only login page is accessible after entering username/pasword, Page not found error.

**Comment by beinafuushop** [comment]
Hello All,

I manage to fix this by uncommenting "# if in web root" option in the .htaccess file and put my url there.

Thanks everyone for support.

**Comment by daN4cat** [comment]
Good to hear, so in the end it was your setup. I thought you were changing the right .htaccess lines but it sounds no.
