### ISSUE TITLE
Sale register error while adding items by id number

### ISSUE THREAD

**Issue by bill-goldberg** [jekkos/opensourcepos#1019]
### IMPORTANT IMPORTANT IMPORTANT

Chose what you want to report: New Feature or Bug.
If you remove the template when submitting a Bug your issue will be closed as we cannot help without basic information.

### New Feature / Enhacement

For New Features or Enhacements please remove all the template text and clearly write your proposal.
It's important to state whether you expect the community to implement it or you will contribute the work.
Please bear in mind that we will implement new features only on the current code, there is no support for old versions.

### Issue / Question / Bug

Before submitting an issue please make sure you remove the first section of the template and you tick (add a x between the square brakets) and agree with all the following check boxes:

- [x] Checked the current issues database and no similar issue was already discussed
- [x] Read the README, WHATS_NEW and UPGRADE
- [x] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php5-gd, php-intl and sockets installed)
- [x] Reporting an issue of an unmodified OSPOS installation
- [x] PHP version is at least 5.5 and not 7.x
- [x] MySQL version is 5.5 or 5.6 and not 5.7
- [x] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [x] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [x] Know the name and version of OS, Web server and MySQL and will add to my issue report

### Installation information
localhost
wampserver2.5 x64
Apache-2.4.9
Mysql-5.6.17
php5.5.12

### Actual behaviour

![github error](https://cloud.githubusercontent.com/assets/23611136/20748360/dc6b35b6-b713-11e6-91f1-54cdf8b69c91.jpg)

### Steps to reproduce the issue

**Comment by daN4cat** [comment]
Which web browser and OS on client side?

I spotted something similar once but I need to test more. And it looks like it happens on Linux and not Windows but I need help to reproduce it systematically

**Comment by bill-goldberg** [comment]
Windows 10
Firefox v50

**Comment by daN4cat** [comment]
Do you have Chrome or another web browser to try to reproduce the same?

**Comment by bill-goldberg** [comment]
Okay I will try in Chrome. and I will update here about chrome experience.

**Comment by bill-goldberg** [comment]
No errors in Google Chrome... then what is wrong with the firefox ?

**Comment by daN4cat** [comment]
I need to repeat my test, but I got the same problem on Linux with Firefox and Chrome scanning twice the same item.
I got once what you reported but I will try to reproduce.

@jekkos anything that springs to your mind about this issue? Maybe a ctrf token issue in ajax call?

**Comment by jekkos** [comment]
The error indeed indicates csrf violation. I think we saw something similar before when using a barcode scanner. Do you manually type the sale id's in this case? 

There might be a problem in the csrf updating mechanism somehow and to tackle that I'll need to be able to reproduce it first

**Comment by daN4cat** [comment]
In my case was with a scanner, in @bill-goldberg is typing the item by id number and adding it.
I got once that one too, I will need to reproduce but @jekkos try with Firefox adding an item by id number like copy & paste and see if you get.
I have vague memory that I could get it like that...

**Comment by daN4cat** [comment]
@jekkos I managed to do a quick test and using Firefox on Windows using copy and paste of item id number entered twice reproduces the problem systematically.
With Chrome it works fine, more to test next days on Linux.

So you don't need a scanner for this. Just do twice with copy&paste of the same item id number.

**Comment by odiea** [comment]
Internet explorer and Edge also have this issue. I do not have to copy and paste just enter an item number press enter. Repeat with the same item number. Sometimes it took 5 tries but most of the time it only took 2 tries.

**Comment by daN4cat** [comment]
@jekkos I would fix this and release a 3.0.2 as it's a problem and now not that difficult to reproduce.

**Comment by daN4cat** [comment]
@jekkos do you think you'll be able to look into this so we release 3.0.2 with two major fixes + translations?

**Comment by jekkos** [comment]
Will have a look on my way to work tomorrow. I just moved house this weekend been sort of busy, but hope to find some time coming week

**Comment by daN4cat** [comment]
Ok, take it easy.

**Comment by jekkos** [comment]
No internet connection yet at home now, the ISP won't be able to come over until next week. Will try to find some alternative solution this week.

**Comment by daN4cat** [comment]
@jekkos we really need to get this ironed out....

**Comment by jekkos** [comment]
The return false in register.php at line 540 might be the culprit. I don't have a full IDE at my disposal now. Can anyone remove this line and see if the issue persists?

**Comment by jekkos** [comment]
Also I need to do an annotate to see why I added that in the first place

**Comment by jekkos** [comment]
I did see that the updated csrf token is sent with the post form. However for some reason the cookie value is not updated. Might be the return false cancelling this behavior.

**Comment by odiea** [comment]
It made things worse. Add item modal shows then the register displays the item but next time it gives the same error.

**Comment by jekkos** [comment]
Ok thanks @odiea for testing this for me.. I need to take a further look but will be off coming days as I'm leaving for holiday to Hamburg til the 30th... so maybe somewhere in between I hope to throw my debugger at this isssue

**Comment by jekkos** [comment]
Ok I did a fix for this issue. I guess the csrf token wasn't refreshed correctly in some situation. Can someone test?

**Comment by odiea** [comment]
Receivings works great but no change at the Register

**Comment by odiea** [comment]
Test procedure. Enter Item id press enter repeat after the second or third time it shows the error.

**Comment by jekkos** [comment]
Ok you're right .. If you do it fast enough it still fails

**Comment by jekkos** [comment]
Ok now the refresh is done before submit.

**Comment by jekkos** [comment]
Any idea if the issue is fixed or not?

**Comment by jekkos** [comment]
Ok I have taken this fix a bit further and made a hook for standard jQuery submit function. It now first refreshes csrf token in the form before submit is done.

**Comment by odiea** [comment]
This issue appears to be fixed.

**Comment by jekkos** [comment]
Ok great! Thanks for the testing. I close.

**Comment by daN4cat** [comment]
Well done @jekkos !
