### ISSUE TITLE
Backup file 'ospos.sql' Error while importing in a new database

### ISSUE THREAD

**Issue by bill-goldberg** [jekkos/opensourcepos#1020]
### IMPORTANT IMPORTANT IMPORTANT

Chose what you want to report: New Feature or Bug.
If you remove the template when submitting a Bug your issue will be closed as we cannot help without basic information.

### New Feature / Enhacement

For New Features or Enhacements please remove all the template text and clearly write your proposal.
It's important to state whether you expect the community to implement it or you will contribute the work.
Please bear in mind that we will implement new features only on the current code, there is no support for old versions.

### Issue / Question / Bug

Before submitting an issue please make sure you remove the first section of the template and you tick (add a x between the square brakets) and agree with all the following check boxes:

- [x] Checked the current issues database and no similar issue was already discussed
- [x] Read the README, WHATS_NEW and UPGRADE
- [x] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php5-gd, php-intl and sockets installed)
- [x] Reporting an issue of an unmodified OSPOS installation
- [x] PHP version is at least 5.5 and not 7.x
- [x] MySQL version is 5.5 or 5.6 and not 5.7
- [x] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [x] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [x] Know the name and version of OS, Web server and MySQL and will add to my issue report

### Installation information
Windows 10 x64
Firefox v50
localhost
wampserver2.5 x64
Apache-2.4.9
Mysql-5.6.17
php5.5.12

### Steps to reproduce the issue

**Comment by bill-goldberg** [comment]
I am unable to restore my items and sales details from the backup file 'ospos.sql'. Please help me about restoring database.

**Comment by odiea** [comment]
I only use phpmyadmin so I hope this helps you out. Extract your backup database. I use notepad++ to add the following line to the top of the page below the 3rd comment. Create a new database.
SET FOREIGN_KEY_CHECKS=0; Then add SET FOREIGN_KEY_CHECKS=1; at the bottom of the page.
With a large database you might get a timed out error but you can then resubmit the same database and it will resume where it left off. You can then change to the new database name in config/ database. If it works you can then delete the old database and rename your new database to the old database if you need to. Test to make sure the new database works first before you rename it.

**Comment by odiea** [comment]
After more testing it appears that you can just import it back into the old database with no issues after making the adjustments.

**Comment by daN4cat** [comment]
Answered? Can we close?

**Comment by bill-goldberg** [comment]
let me try once then you can close this issue.

**Comment by bill-goldberg** [comment]
I tried the steps suggested by @odiea and the database import was successful but a new kind of error occurred during the login
![github back up error](https://cloud.githubusercontent.com/assets/23611136/21049927/99d74556-be3d-11e6-9580-9a5138b7fba4.jpg)

**Comment by jekkos** [comment]
Looks like an issue with selected language, all translations are in fallback mode. You need to have a correct language setting in ospos_app_config table. Check database.sql for the correct value there.

**Comment by bill-goldberg** [comment]
please describe more accurately your step i am unable to understand it.

**Comment by odiea** [comment]
You may be using an old database with the new programming. The app-config table needs to include both of the following fields. You may need to run the correct database upgrade script.
![2016-12-09 16_25_54-localhost _ 127 0 0 1 _ ospos _ ospos_app_config _ phpmyadmin 4 5 1 and 1 more p](https://cloud.githubusercontent.com/assets/10962177/21068032/65d89f22-be2c-11e6-976c-fad59895a346.png)

**Comment by bill-goldberg** [comment]
thank you...  @odiea but after the login it is not showing the old sales + item lists records

**Comment by odiea** [comment]
recheck and make all the required php extensions are enabled.
