### ISSUE TITLE
items_name too long, real info doesn't fit in barcode

### ISSUE THREAD

**Issue by i92guboj** [jekkos/opensourcepos#1025]
### FEATURE REQUEST

Not sure how to categorize this. I guess it's a feature request. 

### New Feature / Enhacement

In the generated barcodes, at least when using the Spanish locale, the product name doesn't fit. Spanish sentences tend to bit quite a bit longer than their English counterparts. The label occupies more than half the space, so the most important and distinctive part of the product name (last half) doesn't fit. 

### Issue / Question / Bug

Not relevant, but checked nonetheless :)

- [x] Checked the current issues database and no similar issue was already discussed
- [x] Read the README, WHATS_NEW and UPGRADE
- [x] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php5-gd, php-intl and sockets installed)
- [x] Reporting an issue of an unmodified OSPOS installation
- [x] PHP version is at least 5.5 and not 7.x
- [x] MySQL version is 5.5 or 5.6 and not 5.7
- [x] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [x] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [x] Know the name and version of OS, Web server and MySQL and will add to my issue report

### Installation information

OSPOS 3.0.1 current git on Gentoo current, some ~amd64 packages. Apache 2.4 and mysql 5.6.34

GIT hash 4f5ad57

### Expected behaviour

Bota Safari borreguito Marrón 36
||||||||||||||||||||||￼
ASAFMA36
Categoría UNISEX

### Actual behaviour

Nombre del Artículo Bota Safari borreguito…
||||||||||||||||||||||||
ASAFMA36
Categoría UNISEX

### Steps to reproduce the issue

Just generate bar codes for "something Spanish with sizes and colors". I guess German would work as well ;) hehe

Let me explain that, since there's no true variant support (with stock support) I am trying to build a system where each real product has like 50 products in OSPOS, because I have to create boots or many colors and sizes. This is another reason why product names are that long.

Using this concrete example, I have more than 80 "bota safari borreguito" in my store, counting 7 different colors and 11 sizes, so that first half of the name truly doesn't tell me anything concrete about what I am selling.

I could probably give this a shot, if you are interested in getting this up-streamed and can give me a few pointers on which would be an acceptable way to implement this (remove all labels with a checkbox, remove only items_name label with a check box, just remove it because it serves no purpose...., or some other option I haven't considered).

If this is not going upstream, I can just patch the file myself, not a big deal really. Just wanted to know if there's any interest in this or it's just me :P 

Cheers :)

**Comment by jekkos** [comment]
See #68. I think this problem should be tackled by using the attribute addition. An extra enhancement would be to use attribute codes in barcode generation. Currently only sales, items, receivings and receipt visibility are foreseen.

**Comment by i92guboj** [comment]
Ok, however that thread talks about things that might be related but are way too complex for my concrete use case. I just wanted to make room for the whole description in the barcode label, so I can just patch the file myself to hide the label and make room for my description, it's a single line of code.  :)

**Comment by jekkos** [comment]
You're usecase will be implemented in a cleaner way thanks to that new feature. You'll be able to separate sizes, colors etc from items and reassign depending on the category you select. I'm currently working on this part and it's almost finished, need to wrap up the migration scripts from the old custom.. fields and then I'll release something for test.

**Comment by i92guboj** [comment]
Nice, thank you so much. Can't wait to test that :)

**Comment by daN4cat** [comment]
Close to keep just #68 open as this is just a use case.
