### ISSUE TITLE
Employee security issue.

### ISSUE THREAD

**Issue by odiea** [jekkos/opensourcepos#1027]
Due to Test employee security I thought it was necessary to change the following lines in controller/Sales.
from	$data['employee'] = $employee_info->first_name . ' ' . $employee_info->last_name;
to	$data['employee'] = $employee_info->person_id;
Now the employee Id shows on the receipt and their names stay confidential.

**Comment by daN4cat** [comment]
Maybe just the first name & Id will do?

**Comment by odiea** [comment]
Ya that would do too. To much info going out on a receipt that a creep could use.

**Comment by daN4cat** [comment]
Agree with you, full name is too much

**Comment by odiea** [comment]
Maybe Employee id followed by employee fist name and last name first letter?
2 Mary z

**Comment by odiea** [comment]
Do you think we need the employee number if it just shows first name and last name first letter?
		$data['employee'] = $employee_info->person_id . ' ' . $employee_info->first_name . ' ' . substr($employee_info->last_name, 0, 1);

**Comment by daN4cat** [comment]
Maybe it's fine like this indeed. If that works and you tested it I will commit to master later.

**Comment by odiea** [comment]
This is how it appears on the receipt. Your wife's business is probably more customer friendly then most business so that's why I kept the first name.
![2016-12-04 03_59_02-wedidit _ powered by ospos 3 0 1](https://cloud.githubusercontent.com/assets/10962177/20865680/28484054-b9d6-11e6-8fda-923ebbbd80c4.png)

**Comment by daN4cat** [comment]
Ok, but the ID is probably not necessary.

**Comment by daN4cat** [comment]
Done
