### ISSUE TITLE
The products are not displayed in the article tab and Earnings at zero

### ISSUE THREAD

**Issue by GePraxa** [jekkos/opensourcepos#1028]
### Installation information
Windows 10 PRO 64 bits 
Chrome Versión 54.0.2840.99 m (64-bit)
PHP 5.6.25
MySQL 5.7.14
Apache 2.4.23
Open Source Point Of Sale Versión 3.0.1 - 4f5ad57

### Expected behaviour
See the products in the article tab.

### Actual behaviour
I am adding products manually but I can not see them in the articles tab.

The products if they are added to the database, if I can make sales with these new products.

Make 5 sales and when I go to reports-> sales, the profit appears to me in zeros.

### Steps to reproduce the issue
Add a product manually using the "new article" form

**Comment by odiea** [comment]
MySQL 5.7.14 is not supported.

**Comment by daN4cat** [comment]
MySQL 5.7 is not supported yet.

**Comment by GePraxa** [comment]
Thank you very much for the quick answer.
