### ISSUE TITLE
store config gray page

### ISSUE THREAD

**Issue by AbanoubMakram** [jekkos/opensourcepos#1029]
### Issue /  Bug
when i open store config it showing gray screen and mouse cursor loading and i can't do anything in page .
check attached image https://drive.google.com/file/d/0Bx3GrYkkJrxoYl9ic3ViMUV2X3M/view?usp=sharing

![capture](https://cloud.githubusercontent.com/assets/16741641/20882530/14982e24-baea-11e6-8f73-bbf48f64d64b.PNG) 

also Sales page 
![sales](https://cloud.githubusercontent.com/assets/16741641/20882704/e0490dc2-baea-11e6-828e-57381475f6b7.PNG)

**Comment by daN4cat** [comment]
Do you have all the php extensions installed?

**Comment by sonilmasi** [comment]
just uncomment "extension=php_intl.dll" in php.ini
it can be done by just removing ; in fornt of it.
go to "xampp/php/php.ini"

**Comment by AbanoubMakram** [comment]
it works, thanks sonilmasi  .

**Comment by msinfologix** [comment]
it is extension=php_intl.dll  in php.ini , But I am getting same problem.
I am using wamp
