### ISSUE TITLE
Explanation

### ISSUE THREAD

**Issue by tenkodoy** [jekkos/opensourcepos#1030]
Please this might seem dumb but i get confused with what  Quantity Stock and Receiving quantity is.
I would appreciate a thorough explanation of these two and what exactly they do.
thank you.

**Comment by daN4cat** [comment]
Quantity stock is what you currently have in stock, receiving quantity is how much you received.
In this way you can know taking into account sold quantity if nothing disappeared from your stock without your knowledge.
