### ISSUE TITLE
Can't use method return value in write context in F:\xampp\htdocs\opensourcepos\application\helpers\locale_helper.php on line 77

### ISSUE THREAD

**Issue by yeshwanthrao** [jekkos/opensourcepos#1034]
### Installation information
Ver 3.0 - Follow the instruction as per the guidelines and typed the URL "http://localhost/opensourcepos/public/"

### Expected behaviour
I should see the OSPOS login form.

### Actual behaviour
A PHP Error was encountered
Severity: Compile Error
Message: Can't use method return value in write context
Filename: helpers/locale_helper.php
Line Number: 77
Backtrace:

### Steps to reproduce the issue

**Comment by odiea** [comment]
No information supplied. Please read the wiki and the readme and the issue template.

**Comment by lescieur** [comment]
[Tue Dec 13 11:04:04.160453 2016] [:error] [pid X] [client X] PHP Fatal error:  Can't use method return value in write context in /var/www/ospos/application/helpers/locale_helper.php on line 77.

What's wrong?

**Comment by odiea** [comment]
No information supplied. Please read the wiki and the readme and the issue template.

**Comment by daN4cat** [comment]
Php7?

**Comment by odiea** [comment]
Neither person wanted to show their current info. Up till the latest update done by @jekkos I had no php 7 issues. May be an earlier version? 5.4?

**Comment by yeshwanthrao** [comment]
Sorry. I was away for a few days hence no reply.

Yes I am using ver 5.4 of php. Do I need to use version 7 rather 5.4?.

Regards

Yeshwanthrao

**Comment by odiea** [comment]
Try 5.5 or 5.6. and make sure all the extensions that are needed are enabled.

**Comment by daN4cat** [comment]
No news, I close.
