### ISSUE TITLE
#New Feature/Enhancent-Filtering inventory reports by category and/or supply

### ISSUE THREAD

**Issue by beinafuushop** [jekkos/opensourcepos#1035]
Hello team,

Can the.community enhance the application by adding inventory report filtering option by supplier and/or.categories?I think this is important for analysis.

**Comment by beinafuushop** [comment]
Hello.All,

Don"t we have any body who is interested in this also?please share your inputs

**Comment by jekkos** [comment]
You mean filtering items  based on supplier / categories? Category search will be there in 3.1.

**Comment by beinafuushop** [comment]
Yes @jekkos , That is good news ever, looking foward for updated version 3.1. Thank you team for your support.

**Comment by daN4cat** [comment]
See #68

**Comment by beinafuushop** [comment]
Hello @jekkos and @daN4cat,

I meant in the inventory reports, we need to add more filters that include filtering by Category, Supplier.

**Comment by jekkos** [comment]
No category search is not foreseen in reports for now.. but the approach will be different ofcourse after #68 is finished. Currently I found a new project (job) so will need to focus a bit and hope to work some more on this change any time soon.
