### ISSUE TITLE
 sales and receiving ,shop config views don't show properly

### ISSUE THREAD

**Issue by eremiter** [jekkos/opensourcepos#1036]
win10+php5.5+apache2.4,in php.ini set bcmath.scale = 1,
but  sales and receiving ,shop config views don't show properly, 
Click on the sales,  receiving, shop config is jammed, why?

**Comment by odiea** [comment]
Post a screen image so we can see what you see.

**Comment by AbanoubMakram** [comment]
just uncomment "extension=php_intl.dll" in php.ini
it can be done by just removing ; in fornt of it.
go to "xampp/php/php.ini"

**Comment by eremiter** [comment]
**win10+php5.5+apache2.4**,in php.ini set bcmath.scale = 1,
but sales and receiving ,shop config views don't show properly,
Displays a small circle has been turned, win10 time format is  (year:month:date H:M:S), but pos3 display the upper left corner of the time format is June (month:date:year H:M:S), is the problem?
Click on the sales, receiving, shop config is jammed, why?

`extension=php_bz2.dll
extension=php_curl.dll
;extension=php_fileinfo.dll
extension=php_gd2.dll
;extension=php_gettext.dll
;extension=php_gmp.dll
;extension=php_intl.dll
;extension=php_imap.dll
;extension=php_interbase.dll
;extension=php_ldap.dll
extension=php_mbstring.dll
;extension=php_exif.dll      ; Must be after mbstring as it depends on it
extension=php_mysql.dll
extension=php_mysqli.dll
;extension=php_oci8.dll      ; Use with Oracle 10gR2 Instant Client
;extension=php_oci8_11g.dll  ; Use with Oracle 11gR2 Instant Client
extension=php_openssl.dll
;extension=php_pdo_firebird.dll
extension=php_pdo_mysql.dll
;extension=php_pdo_oci.dll
extension=php_pdo_odbc.dll
;extension=php_pdo_pgsql.dll
extension=php_pdo_sqlite.dll
;extension=php_pgsql.dll
;extension=php_pspell.dll
;extension=php_shmop.dll
;extension=php_mongo.dl
;extension=php_sqlsrv.dll
;extension=php_pdo_sqlsrv.dll

; The MIBS data available in the PHP distribution must be installed. 
; See http://www.php.net/manual/en/snmp.installation.php 
;extension=php_snmp.dll

;extension=php_soap.dll
extension=php_sockets.dll
extension=php_sqlite3.dll
;extension=php_sybase_ct.dll
;extension=php_tidy.dll
extension=php_xmlrpc.dll
extension=php_xsl.dll
;extension=php_zip.dll
;extension=memcache.dll
extension=php_mcrypt.dll
;;;;;;;;;;;;;;;;;;;
; Module Settings ;
;;;;;;;;;;;;;;;;;;;

[CLI Server]
; Whether the CLI web server uses ANSI color coding in its terminal output.
cli_server.color = On

[Date]
; Defines the default timezone used by the date functions
; http://php.net/date.timezone
date.timezone = PRC`

**Comment by odiea** [comment]
Your first post showed ;extension=php_intl.dll
was not enabled. If you did enable it you need to restart your server.

win10+php5.5+apache2.4,in php.ini set bcmath.scale = 1,
but sales and receiving ,shop config views don't show properly,
Displays a small circle has been turned, win10 time format is (year:month:date H:M:S), but pos3 display the upper left corner of the time format is June (month📅year H:M:S), is the problem?
Click on the sales, receiving, shop config is jammed, why?

`extension=php_bz2.dll
extension=php_curl.dll
;extension=php_fileinfo.dll
extension=php_gd2.dll
;extension=php_gettext.dll
;extension=php_gmp.dll
;extension=php_intl.dll
;extension=php_imap.dll
;extension=php_interbase.dll
;extension=php_ldap.dll
extension=php_mbstring.dll
;extension=php_exif.dll ; Must be after mbstring as it depends on it
extension=php_mysql.dll
extension=php_mysqli.dll
;extension=php_oci8.dll ; Use with Oracle 10gR2 Instant Client
;extension=php_oci8_11g.dll ; Use with Oracle 11gR2 Instant Client
extension=php_openssl.dll
;extension=php_pdo_firebird.dll
extension=php_pdo_mysql.dll
;extension=php_pdo_oci.dll
extension=php_pdo_odbc.dll
;extension=php_pdo_pgsql.dll
extension=php_pdo_sqlite.dll
;extension=php_pgsql.dll
;extension=php_pspell.dll
;extension=php_shmop.dll
;extension=php_mongo.dl
;extension=php_sqlsrv.dll
;extension=php_pdo_sqlsrv.dll

; The MIBS data available in the PHP distribution must be installed.
; See http://www.php.net/manual/en/snmp.installation.php
;extension=php_snmp.dll

;extension=php_soap.dll
extension=php_sockets.dll
extension=php_sqlite3.dll
;extension=php_sybase_ct.dll
;extension=php_tidy.dll
extension=php_xmlrpc.dll
extension=php_xsl.dll
;extension=php_zip.dll
;extension=memcache.dll
extension=php_mcrypt.dll
;;;;;;;;;;;;;;;;;;;
; Module Settings ;
;;;;;;;;;;;;;;;;;;;

[CLI Server]
; Whether the CLI web server uses ANSI color coding in its terminal output.
cli_server.color = On

[Date]
; Defines the default timezone used by the date functions
; http://php.net/date.timezone
date.timezone = PRC`

**Comment by eremiter** [comment]
I remove the semicolon, restart the server , the same error
extension=php_intl.dll

**Comment by odiea** [comment]
;extension=php_exif.dll ; Must be after mbstring as it depends on it. Try uncommenting this and restart.

**Comment by odiea** [comment]
Are you using wamp? If so you will need to read the wiki about the files that need to be transferred.

**Comment by eremiter** [comment]
using separate installation and happen the same problem,Click on the sales, receiving, store config is jammed, why

`extension=php_bz2.dll
extension=php_curl.dll
;extension=php_fileinfo.dll
extension=php_gd2.dll
;extension=php_gettext.dll
;extension=php_gmp.dll
extension=php_intl.dll
;extension=php_imap.dll
;extension=php_interbase.dll
;extension=php_ldap.dll
extension=php_mbstring.dll
extension=php_exif.dll      ; Must be after mbstring as it depends on it
extension=php_mysql.dll
extension=php_mysqli.dll
;extension=php_oci8.dll      ; Use with Oracle 10gR2 Instant Client
;extension=php_oci8_11g.dll  ; Use with Oracle 11gR2 Instant Client
extension=php_openssl.dll
;extension=php_pdo_firebird.dll
extension=php_pdo_mysql.dll
;extension=php_pdo_oci.dll
extension=php_pdo_odbc.dll
;extension=php_pdo_pgsql.dll
extension=php_pdo_sqlite.dll
;extension=php_pgsql.dll
;extension=php_pspell.dll
;extension=php_shmop.dll
;extension=php_mongo.dl
;extension=php_sqlsrv.dll
;extension=php_pdo_sqlsrv.dll

; The MIBS data available in the PHP distribution must be installed. 
; See http://www.php.net/manual/en/snmp.installation.php 
;extension=php_snmp.dll

;extension=php_soap.dll
extension=php_sockets.dll
extension=php_sqlite3.dll
;extension=php_sybase_ct.dll
;extension=php_tidy.dll
extension=php_xmlrpc.dll
extension=php_xsl.dll
;extension=php_zip.dll
;extension=memcache.dll
extension=php_mcrypt.dll
;;;;;;;;;;;;;;;;;;;
; Module Settings ;
;;;;;;;;;;;;;;;;;;;

[CLI Server]
; Whether the CLI web server uses ANSI color coding in its terminal output.
cli_server.color = On

[Date]
; Defines the default timezone used by the date functions
; http://php.net/date.timezone
date.timezone = PRC`

**Comment by odiea** [comment]
Are you using wamp??????

**Comment by eremiter** [comment]
not using wamp,using separate installation

**Comment by odiea** [comment]
Fill out the template as far as we know you are using xp in a virtual machine.

**Comment by eremiter** [comment]
Recommended CI4 development, or use the framework of China thinkphp5(http://www.thinkphp.cn/), compatibility is better,Do you have email, convenient communication

**Comment by Elhy** [comment]
I have the same configuration and version of WAMP you. 
I also had the same problem,I did not find a solution, so I tried to update my WAMP with this
https://sourceforge.net/projects/wampserver/files/WampServer%203/WampServer%203.0.0/wampserver3.0.6_x64_apache2.4.23_mysql5.7.14_php5.6.25-7.0.10.exe/download

And everything is resolved

**Comment by govindarajan69** [comment]
@Elhy : when i used the url shared, it is giving "The /WampServer 3/WampSe..php5.6.25-7.0.10.exe" file could not be found or is not available. please select another file".

Thanks in advance.
