### ISSUE TITLE
item kits explanation 

### ISSUE THREAD

**Issue by ponamakram** [jekkos/opensourcepos#1038]
### IMPORTANT IMPORTANT IMPORTANT

Chose what you want to report: New Feature or Bug.
If you remove the template when submitting a Bug your issue will be closed as we cannot help without basic information.

### New Feature / Enhacement

For New Features or Enhacements please remove all the template text and clearly write your proposal.
It's important to state whether you expect the community to implement it or you will contribute the work.
Please bear in mind that we will implement new features only on the current code, there is no support for old versions.

### Issue / Question / Bug

Before submitting an issue please make sure you remove the first section of the template and you tick (add a x between the square brakets) and agree with all the following check boxes:

- [] Checked the current issues database and no similar issue was already discussed
- [] Read the README, WHATS_NEW and UPGRADE
- [] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php5-gd, php-intl and sockets installed)
- [] Reporting an issue of an unmodified OSPOS installation
- [] PHP version is at least 5.5 and not 7.x
- [] MySQL version is 5.5 or 5.6 and not 5.7
- [] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [] Know the name and version of OS, Web server and MySQL and will add to my issue report

### Steps to reproduce the issue

hi
i don't know what is the befit of item kits, i can't add new receiving for  any item kits or add any prices
so i need more explanation about this module .
thanks :-)

**Comment by jekkos** [comment]
No separate pricing. I don't know about receiving items per kit. Maybe it was never implemented. If it is then I guess it should be able to add the kit once you enter the KIT ID in the register line.

**Comment by ponamakram** [comment]
what is the difference between item category and item kit ?
what is benefit of item kit .. i need more explanation about item kits 
thanks

**Comment by odiea** [comment]
Receivings does not the change of cost of an item.
Item kits is for selling  products which includes multiple items.
Categories are the area in your inventory which needs a common header.
Category Clothing might include pants, shirts, belts.

**Comment by odiea** [comment]
The best use of kits would be #586 if you are not afraid the change the programming.

**Comment by SteveIreland** [comment]
I'm planning on using item kits in the role of a "Service Provided" and the individual tasks as part of that service.  To handle that I'll probably need to add treat the kit as a separate item that is added to the order.  I'm not sure yet whether my client wants the price at the kit level or at the item level.  I suspect it could be either and I suspect I have a bit of work ahead of me to make either option a possibility.

**Comment by odiea** [comment]
Sound like another good use case for kits.

**Comment by jekkos** [comment]
See #1043 for further enhancements
