### ISSUE TITLE
Blocker overlay after login

### ISSUE THREAD

**Issue by besingamkb** [jekkos/opensourcepos#1039]
### IMPORTANT IMPORTANT IMPORTANT

Chose what you want to report: New Feature or Bug.
If you remove the template when submitting a Bug your issue will be closed as we cannot help without basic information.

### New Feature / Enhacement

For New Features or Enhacements please remove all the template text and clearly write your proposal.
It's important to state whether you expect the community to implement it or you will contribute the work.
Please bear in mind that we will implement new features only on the current code, there is no support for old versions.

### Issue / Question / Bug

Before submitting an issue please make sure you remove the first section of the template and you tick (add a x between the square brakets) and agree with all the following check boxes:

- [x] Checked the current issues database and no similar issue was already discussed
- [x] Read the README, WHATS_NEW and UPGRADE
- [x] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php5-gd, php-intl and sockets installed)
- [x] Reporting an issue of an unmodified OSPOS installation
- [x] PHP version is at least 5.5 and not 7.x
- [x] MySQL version is 5.5 or 5.6 and not 5.7
- [] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [] Know the name and version of OS, Web server and MySQL and will add to my issue report

### Installation information
windows 10, xampp

### Expected behaviour
after login i should not able to see this overlay

### Actual behaviour
![ospos](https://cloud.githubusercontent.com/assets/6380139/21278011/e5d0ceb0-c413-11e6-91c1-a2b902a712db.jpg)

### Steps to reproduce the issue
after loging in . i an overlay is blocking the UI

**Comment by odiea** [comment]
Make sure all the needed extensions are enabled. Looks like intl is not enabled. Please read the wiki about installing xampp.

**Comment by besingamkb** [comment]
I'm pretty sure that intl is enabled. I already read the wiki and faq. i make it work on my host. but want to try it locally with xampp

![php_intl](https://cloud.githubusercontent.com/assets/6380139/21284416/4761709e-c455-11e6-9a9f-1985849eee24.jpg)

**Comment by ponamakram** [comment]
after changing in php.ini file restart the xampp in clear browser session and log in again, it will work correctly except you changed in footer div .

**Comment by daN4cat** [comment]
Please see other posts about XAMPP and check even the wiki, I'm sure you'll find the solution there.

**Comment by SteveIreland** [comment]
I know this is closed, but for the record I've had this happen several times when doing a lot of and software updates.  The resolution has been to clear the sessions table.  I just thought I'd add this tidbit of information because it might be helpful to others.

**Comment by vimkaf** [comment]
please i need a solution to this i have tried all suggestions above still nothing, i am still getting the overlay
