### ISSUE TITLE
Feature Request: Improve specific customer search

### ISSUE THREAD

**Issue by waynebr76** [jekkos/opensourcepos#104]
We are currently making great use of the specific report selection when a customer has lost a receipt,  >>Reports>Specific customer. However the current customer selection is sorted by customer I.D. With quite a few customers it is awkward to find the customer quickly.

 Please can this list be updated so it is sorted in alphabetical order or can an option be added to allow us to type in the name and narrow down the search?

**Comment by jekkos** [comment]
I had a quick look in the code and it looks like the dropdown is already sorted alphabetically on the customer's last name?
