### ISSUE TITLE
Blank Page. session_start() error

### ISSUE THREAD

**Issue by eewann** [jekkos/opensourcepos#1042]
### IMPORTANT IMPORTANT IMPORTANT

Chose what you want to report: New Feature or Bug.
If you remove the template when submitting a Bug your issue will be closed as we cannot help without basic information.

### New Feature / Enhacement

For New Features or Enhacements please remove all the template text and clearly write your proposal.
It's important to state whether you expect the community to implement it or you will contribute the work.
Please bear in mind that we will implement new features only on the current code, there is no support for old versions.

### Issue / Question / Bug

Before submitting an issue please make sure you remove the first section of the template and you tick (add a x between the square brakets) and agree with all the following check boxes:

- [] Checked the current issues database and no similar issue was already discussed
- [] Read the README, WHATS_NEW and UPGRADE
- [] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php5-gd, php-intl and sockets installed)
- [] Reporting an issue of an unmodified OSPOS installation
- [] PHP version is at least 5.5 and not 7.x
- [] MySQL version is 5.5 or 5.6 and not 5.7
- [] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [] Know the name and version of OS, Web server and MySQL and will add to my issue report

### Installation information
win 10, xampp

### Expected behaviour
login form displayed.

### Actual behaviour
nothing displayed. just blank white page. 
error.log = PHP Fatal error:  session_start(): Failed to initialize storage module: user (path: sessions) in [***]\\htdocs\\vendor\\codeigniter\\framework\\system\\libraries\\Session\\Session.php on line 143

### Steps to reproduce the issue

**Comment by eewann** [comment]
ok i've solved it..only problem with database privileges..

**Comment by odiea** [comment]
Thanks for the feedback.

**Comment by ravi-shaw** [comment]
Hi eewann,
I am also getting the same problem. Can you please let me know how did you solve the problem of database priviledges. Appreciate your help in advance.
Thanks
 Ravi

**Comment by rmbaba** [comment]
I'm also getting the same error how do I solve it on the database layer?
