### ISSUE TITLE
Enhancement to add sequence to item kit items table 

### ISSUE THREAD

**Issue by SteveIreland** [jekkos/opensourcepos#1043]
## Enhancement

I need item kit items to be added to a sales order in a particular sequence.  In order to accomplish that I need to add a 3 digit sequence number to the item kit items table and slightly change the SQL statement that adds item kit items to the sales order.

I also want the name of the kit added to the sales order first, followed by the kit items. The user can either assign a price at the kit level or for each individual kit item.  Since the name of the kit should be listed first I'll be creating an item for the kit and will include that as the first kit item of the kit.  This approach seems to be the most flexible.

I'll be making the change but wanted to know if there is any interest in this being added here.

**Comment by odiea** [comment]
I think that there would be a lot more interest if Kits actually did something that was more usable then it is now.

**Comment by jekkos** [comment]
Yes I think indeed in it's current form it's not that usable. There were plenty of long standing bugs in that module which shows that it's not frequently used.

**Comment by daN4cat** [comment]
I fixed few bugs around this area but because I don't use it I didn't improve it. There are a number of improvements posted in the past and if my memory is right there is even an Epic. Also some people asked to consider a discount option to the whole set. So more food for thoughts.

**Comment by SteveIreland** [comment]
Would you like me to expand the scope of my changes to include other requests for improvement in the item kit arena?  This is going to be a key component of the system for us so I don't mind at all spending a significant amount of time on this.  (On a side note I'm also going to be developing this using MySQL 5.7 as my development test target so by the time I'm finished my work on MySQL 5.7 should be reasonably debugged.)   Please let me know if you'd like me to contribute here ... until then I'll take a look at the other open issues that I can find involving item kits.

**Comment by SteveIreland** [comment]
Below is a a summary of additional functionality that needs to be added for item kits based on what I see listed on other issues.

**Definitions/Rules**

An Item Kit is an Item that that consists of other items referred to as Kit Items. 

Item Kits can be an inventoried item (for example display items) or non-inventoried item (for example mixed drinks).  

If an Item Kit can be priced and/or inventoried then the Item Kit should be added with a reference to an Item for the kit.is added with a reference to an Item then the

An Item Kit can be flagged to "Show Detail on Receipt" as either Yes or No.  The kit items will still be included on the list of sale items, but only the kit item will be shown on the order.

An Item Kit can be flagged to "Show Kit Item Prices" as either Yes or No.  This will determine whether or not kit items that are listed on an invoice will have prices listed.

A discount percent can be added to an Item Kit that will automatically be added to each item in the kit. If a kit item already has a discount then it will override the kit items discount instead of being a discount multiplier.

**Questions**

Is issue 665 regarding barcodes for kit items resolved?

What are users of OSPOS doing for non-inventory items?  This might be an unrelated issue, but I think I need a flag to distinguish between stocked items and non-stocked items.

**Comment by daN4cat** [comment]
@SteveIreland sounds a good idea to take a bit of ownership of this feature and work on several improvements together. This eve I'll have a look into past issues and let you know which one is the parent holder.
Overall would be probably a good idea to distribute ownership of parts of OSPOS to different people so we get a better chance to improve them considering various use cases.
I'll come back to this past Christmas, I've got busy with personal matters.

**Comment by jekkos** [comment]
@SteveIreland @daN4cat Same for me, been quite busy with personal stuff lately, trying to find a new project as my current one ends this month and had to move house recently as well..

Regarding service items an issue was already created by @odiea earlier which is #200 if I'm not mistaken. For item kits maybe look in #625 for open feature requests.

**Comment by SteveIreland** [comment]
So, assuming that support for service items is still a desired feature and is definitely something I need support for too I'll be happy to assimilate that into this change.  I scheduled a "vacation" for myself next week so I'm going to take advantage of that to kick-start this effort.   I like to prepare documentation as I'm doing the development so that I don't forget stuff and I have a clear idea of what use cases I need to target for development/testing.  Should I use my own wiki or add it to this wiki?

**Comment by daN4cat** [comment]
#625 is the holder of all the Item Kits improvement requests

**Comment by SteveIreland** [comment]
Understood.

**Comment by daN4cat** [comment]
@SteveIreland I assume your work fixed this, right?

**Comment by SteveIreland** [comment]
Yes, this should be flagged as complete.  Thanks.
