### ISSUE TITLE
#New Feature-Movement of items between store locations

### ISSUE THREAD

**Issue by beinafuushop** [jekkos/opensourcepos#1044]
Hello Team,

Can the community consider enhancement of the system by adding stock movement capability?such as it should be possible to move items quantity from one location to another.there should be report generated for trucking stock movements and also this feature should have user access controll.
Thanx.

**Comment by odiea** [comment]
That is already built into receivings.
![2016-12-22 15_13_02-wedidit _ powered by ospos 3 0 2](https://cloud.githubusercontent.com/assets/10962177/21442148/3a56ac0e-c859-11e6-8609-6d68a5ab7ca0.png)

**Comment by odiea** [comment]
Here is a view from Detailed Receiving.
![2016-12-22 15_23_41-wedidit _ powered by ospos 3 0 2](https://cloud.githubusercontent.com/assets/10962177/21442368/bdb8a678-c85a-11e6-9630-6e933982c611.png)

**Comment by odiea** [comment]
Yes. You can set permissions for Receiving.

**Comment by beinafuushop** [comment]
That is great @Odiea,

But what am asking is the capability to move quantity of the items between store, this process need report and permission.

**Comment by jekkos** [comment]
This might already have been covered in another issue. Detailed receivings report should be able to filter for requisitions if I'm not mistaken.

**Comment by jekkos** [comment]
Permissions are normally created per stock location. In this case for sale / receiving a user needs to have a grant to do sales or receivings for that location. This applies to all three modes at once.

**Comment by beinafuushop** [comment]
This is fine, but what am asking is capability to move/shift items
quantities from one location to another.

**Comment by jekkos** [comment]
That should be done using requisitions in item receiving. This modification should be visible in receiving reports anyway.

**Comment by beinafuushop** [comment]
Do you mean in the current version 3.0 it is possible to do item quantity
movement/migration from one location to another?

**Comment by jekkos** [comment]
I think this was already foreseen after the initial stock location implementation. You should be able to select both source and destination locations on the receivings screen.

**Comment by beinafuushop** [comment]
This is great,here is the thing, Suppose we have two locations, location 1
is shop and location 2 is Store,  with the current system is it possible to
move items from store to shop?and reports.generated for this?Without
manually deleting items in store and adding them in shop.

**Comment by odiea** [comment]
This question has been answered . I close this now.
