### ISSUE TITLE
Add Expiry dates

### ISSUE THREAD

**Issue by tenkodoy** [jekkos/opensourcepos#1046]
Hi guys..

I wanted help in add expiry dates. I know this place has been quite small but if anyone could help me i could probably try that before it goes busy again. I would appreciate any assistance. thanks y'all

**Comment by agungwizz** [comment]
hi tenkodoy..
try 	 Custom Field  in configuration

Best regard
Agungwizz

**Comment by tenkodoy** [comment]
@agungwizz I have added to it... but how does it show up in the Items module. if you have a step by step direction i would love it.

**Comment by jekkos** [comment]
See also #68

**Comment by jekkos** [comment]
Should work once configured correctly in the config screen.

**Comment by asakpke** [comment]
@tenkodoy Please check https://github.com/jekkos/opensourcepos/issues/996#issuecomment-266735220
