### ISSUE TITLE
new year 2017 Need scrip reset transaction

### ISSUE THREAD

**Issue by agungwizz** [jekkos/opensourcepos#1047]
### New Feature / Enhacement
hello
please help me
new year 2017 Need scrip reset transaction and zero inventory

Best Regard
A. W.

**Comment by tenkodoy** [comment]
@agungwizz do you mean you want to clear every data from the inventory and start from 1 again?

**Comment by agungwizz** [comment]
@tenkodoy yes clear every data transaction receivings and sales, but i need data items/master

**Comment by tenkodoy** [comment]
@agungwizz you can go into the database (phpmyadmin) and look for the table and empty it

**Comment by jekkos** [comment]
Just run an sql update query against your database and all will be fine. Happy 2017!
