### ISSUE TITLE
how to use barcode scanner 

### ISSUE THREAD

**Issue by lekadornis** [jekkos/opensourcepos#1049]
Can anyone explain if i can use a barcode scanner with this application.?  and how if possible?

**Comment by odiea** [comment]
Yes you should be able to use a usb scanner. Print a barcode then test scan it in notepad or some text editor to make sure it is working. Then just scan the item at the Sales register.

**Comment by jekkos** [comment]
It works just like a keyboard. Pretty simple just configure it correctly according to the manual.
