### ISSUE TITLE
Receipt Template

### ISSUE THREAD

**Issue by bill-goldberg** [jekkos/opensourcepos#1051]
### Issue / Question / Bug

Before submitting an issue please make sure you remove the first section of the template and you tick (add a x between the square brakets) and agree with all the following check boxes:

- [x] Checked the current issues database and no similar issue was already discussed
- [x] Read the README, WHATS_NEW and UPGRADE
- [x] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php5-gd, php-intl and sockets installed)
- [x] Reporting an issue of an unmodified OSPOS installation
- [x] PHP version is at least 5.5 and not 7.x
- [x] MySQL version is 5.5 or 5.6 and not 5.7
- [x] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [x] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [x] Know the name and version of OS, Web server and MySQL and will add to my issue report

### Installation information
OS : Windows 10 x64
WAMP 2.5 x64
Apache 2.4.9
PHP 5.5.12
MySQL 5.6.17

### Steps to reproduce the issue

**Comment by bill-goldberg** [comment]
Short and Default Receipt Templates both are printing same type of receipt. No changes

**Comment by daN4cat** [comment]
Short template was contribute some time ago and targeting 80 mm large receipts.
Are you using the same paper size or else?

**Comment by bill-goldberg** [comment]
![snapcrab_noname_2017-1-7_21-55-9_no-00](https://cloud.githubusercontent.com/assets/23611136/21747695/933afee2-d524-11e6-8d06-bd788c45e4f5.png)
what is the purpose of 'Ticket Printer' dropdown in Store config -> Receipt

**Comment by bill-goldberg** [comment]
I connected my "Epson TM T82"  printer but it is not showing in the dropdown selection

**Comment by daN4cat** [comment]
It's written receipt template not printer driver. Please don't mix up the two. Your web browser sets the printer OSPOS uses what you set in your environment. The template is the formatting of the output.
