### ISSUE TITLE
error 500 when i try install

### ISSUE THREAD

**Issue by andyq11** [jekkos/opensourcepos#1053]
I installed opensourceepos on my XAMPP serrver and after go to public dir via the browser I got error 500.
After that I installed it on hostpapa server but got same issue:  http://hardworkstudio.co.uk/public/ 
I followed Instruction but cant run it. Anyone had same issue?

**Comment by odiea** [comment]
Make sure all the necessary extensions are enabled. Gd might not be.

**Comment by andyq11** [comment]
O got the php_gd2.dll enabled.

**Comment by andyq11** [comment]
error flom log file: 
C:/wamp/www/opensourcepos/public/.htaccess: Invalid command 'RewriteEngine', perhaps misspelled or defined by a module not included in the server configuration

**Comment by IxFail** [comment]
I Think you are missing the mod_rewrite module.

Please see http://www.orchidbox.com/post.php?title=How_to_enable_mod_rewrite_module_in_apache_in_xampp_wamp

Next time please fill out the template

**Comment by daN4cat** [comment]
It's an Apache configuration issue, mod_rewrite is pretty standard. Check your Apache build flags, enable that module, recompile Apache and try again.
