### ISSUE TITLE
Payment Type Priority Change & Total Payment Roundup

### ISSUE THREAD

**Issue by innovaerp** [jekkos/opensourcepos#1054]
Hi
Got two issues 

1) I looked for payment type priority change in sales register controller / view but could not locate where it is located. By default it is showing Debit card but i wanted to have Cash as the first priority of payment type. Please suggest me how to change the priority of payment type

2) In sales register if the customers payable amount is 120.60 in that case i want to round it up to 121. Let me know how to do it 

Thank you in advance for your help

Regards
ishtiaque

**Comment by IxFail** [comment]
I can help you at the first problem but I cannot help you with your second problem.

To solve your first problem go to Store Config->Localisation and then in the middle of the screen there is the option: Payment Options 
Order Here you can change the order.
![image](https://cloud.githubusercontent.com/assets/1544552/21608810/f7249602-d1be-11e6-91a0-a8b31fd01b75.png)

**Comment by innovaerp** [comment]
I am using version 3.0.0
i guess you are using different version. Can you suggest how to upgrade
without loosing data and settings too !

thanks
A.M.Ishtiaque Sarwar
Managing Director
*Soft Tech Innovation Ltd*

*Consultant:*
NARRI Consortium (8 International NGO's)
Azadi Technologies, Chittagong.
Sagarika Samaj Unnayan Sangstha,

*Business Concerns*: *MUTHOFUN <http://www.muthofun.com/> |  aamarPay
<https://www.aamarpay.com/> | eBiponon <http://www.ebiponon.com/>* |

*C*: 880-1711-272324 | 880-1611-272324
*E*: ceo@softbd.com | info@softbd.com
*W*: www.softbd.com | www.softbd.net

*Skype*: softbd | *GTalk*: ishtiaque.sarwar | *Linked In*: ishtiaquesarwar
<https://bd.linkedin.com/in/ishtiaquesarwar>

DISCLAIMER: This email (including any attachments) is intended only for use
by the named addressee(s) and may contain private, confidential and/or
privileged material. Any reliance, dissemination, distribution, review,
copy or other use of this email by person(s) who are not the intended
recipient is prohibited. If you have received this email in error, please
notify the sender immediately by email and permanently delete the email and
any copies (including print-outs). E-mail transmission cannot be guaranteed
to be secure or error-free as information could be intercepted, corrupted,
lost, destroyed, arrive late or incomplete, or contain viruses. The sender
therefore does not accept liability for any errors or omissions in the
contents of this message, which arise as a result of e-mail transmission.

**Comment by IxFail** [comment]
Please read: https://github.com/jekkos/opensourcepos/blob/master/UPGRADE.txt on how to upgrade your OPOS

P.S. I have version 3.0.2 :)

**Comment by innovaerp** [comment]
i got it, what about the second one !

A.M.Ishtiaque Sarwar
Managing Director
*Soft Tech Innovation Ltd*

*Consultant:*
NARRI Consortium (8 International NGO's)
Azadi Technologies, Chittagong.
Sagarika Samaj Unnayan Sangstha,

*Business Concerns*: *MUTHOFUN <http://www.muthofun.com/> |  aamarPay
<https://www.aamarpay.com/> | eBiponon <http://www.ebiponon.com/>* |

*C*: 880-1711-272324 | 880-1611-272324
*E*: ceo@softbd.com | info@softbd.com
*W*: www.softbd.com | www.softbd.net

*Skype*: softbd | *GTalk*: ishtiaque.sarwar | *Linked In*: ishtiaquesarwar
<https://bd.linkedin.com/in/ishtiaquesarwar>

DISCLAIMER: This email (including any attachments) is intended only for use
by the named addressee(s) and may contain private, confidential and/or
privileged material. Any reliance, dissemination, distribution, review,
copy or other use of this email by person(s) who are not the intended
recipient is prohibited. If you have received this email in error, please
notify the sender immediately by email and permanently delete the email and
any copies (including print-outs). E-mail transmission cannot be guaranteed
to be secure or error-free as information could be intercepted, corrupted,
lost, destroyed, arrive late or incomplete, or contain viruses. The sender
therefore does not accept liability for any errors or omissions in the
contents of this message, which arise as a result of e-mail transmission.

**Comment by IxFail** [comment]
As for the second problem. I'm waiting for the same solution, there is an open issue ://github.com/jekkos/opensourcepos/issues/447

**Comment by daN4cat** [comment]
Rounding is done to the last digit. So reduce the number of decimals in the store configuration and you'll get that sorted.
Special cases are indeed covered by the other ticket. Not sure you need that in the NL? ??

**Comment by IxFail** [comment]
Well in the NL we don't pay with 1 and 2 cent any more so €1,98 €1,99 becomes €2,00 and €1,96 becomes €1,95 and €1,91 becomes €1,90 etc.

Most of the time, stores in The Netherlands sale items with a price like €24,99 because it has a psychological effect on the custumers that the item is cheaper (€25,00 looks a lot more expensive than €24,99)
But in the Netherlands we also provide 2 decimals on the receipt. 
OPOS then puts €0,01 change on the receipt.

**Comment by innovaerp** [comment]
Thank you, i don't need NL but BD so here fraction either gets discounted
or charged like this if 19.60 then 20 or 19 and if customer pays 20 Tk he
gets 1tk return.

**Comment by RamkrishnaMondal** [comment]
Well, if you want  'rounded total'  in printed invoice/receipt .. like this

![screenshot from 2017-01-14 22 06 04](https://cloud.githubusercontent.com/assets/14151032/21956456/33d43f58-daa7-11e6-8cef-33d9cd901b91.png)

Add this in invoice/receipt.php file 

![screenshot from 2017-01-14 22 19 00](https://cloud.githubusercontent.com/assets/14151032/21956469/793879a6-daa7-11e6-9054-007ee97a33bb.png)

Please note, this rounded total will not be saved in database.

**Comment by daN4cat** [comment]
@IxFail there is an issue related to cash rounding #447 . Your type of issue should be part of that, but there is no specific work ongoing I'm afraid. So we need an owner to take and contribute the change.
It could be that the locale support @jekkos introduced using PHP libraries can solve this without big changes but for sure needs testing.

**Comment by daN4cat** [comment]
@SteveIreland in the tax rework have you touched upon the point in my comment by any chance?

**Comment by SteveIreland** [comment]
I commented on what I could do on #447 

Let me know if  you want me to proceed.  Of course, this would only be available in 3.1.0 so to take advantage of it an upgrade would be required.

**Comment by daN4cat** [comment]
Duplicated of #447
