### ISSUE TITLE
retail price on barcodes and retail pricing issue

### ISSUE THREAD

**Issue by Pixmyster** [jekkos/opensourcepos#1055]
### Issue / Question
Version 3.0.1 - 4f5ad57
Apache - 2.2.31
PHP-5.6.27
MySQL-5.6.32
This is my first pull request so i hope ive done it right

I found a couple of pricing issues but all are related to each other

1. As retail price should always include tax, there should be an additional column put into the csv/excel import template to "include tax" then "(y/n)" or "1,2,3,4,5" (for tax brackets) so that when importing prices can be converted to "Retail"
so when you tick/untick "tax included" box the prices are shown correctly,
(
![tax rate option](https://cloud.githubusercontent.com/assets/24884367/21599252/091d0a66-d1be-11e6-96eb-041e87cdf415.JPG)
)

2. barcodes show "retail price" but if "include tax" is unticked in then shows retail as list price only, but incorrectly the price is still shown on barcodes regardless as retail price whether excluding tax or including tax or doesn't specify as list for excluding tax instead, (as there is no list price option)

There should be an option to display as "list" (sell price excluding tax) or Retail ( sell price including tax) and specify if it includes tax or not so for eg: 
![barcode display](https://cloud.githubusercontent.com/assets/24884367/21599285/7147d6b6-d1be-11e6-918f-954d4c62f5c6.JPG)

the highlighted area should be:

Retail Price: $2.20 NOT Retail Price: 2.00 <---- this is an issue

in this case "10% tax" so should be list+tax=retail
Further,

should be "Retail Price $2.20 inc tax

if data is imported into the database and prices are specified to include or exclude tax in the import table, then if one was to change to configuration to prices exclude tax or includes tax then have the data could be correctly processed.

further there should be generic tax brackets so you can just tick a box to apply them, 
for example: im in australia so my tax would GST which is 10% & there are tax free items so TAX FREE would also be required, but they should be globally set not individually

- [X] Checked the current issues database and no similar issue was already discussed
- [X] Read the README, WHATS_NEW and UPGRADE
- [X] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php5-gd, php-intl and sockets installed)
- [X] Reporting an issue of an unmodified OSPOS installation
- [X] PHP version is at least 5.5 and not 7.x
- [X] MySQL version is 5.5 or 5.6 and not 5.7
- [] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [X] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [X] Know the name and version of OS, Web server and MySQL and will add to my issue report

Im happy to financially contribute partially to get these fixed and/or added,

**Comment by daN4cat** [comment]
@Pixmyster, thanks for the issue report. This needs investigation indeed.

**Comment by odiea** [comment]
My impression of tax included is you Include the tax in the retail price then at the register it configures the tax properly.

**Comment by odiea** [comment]
So if you have a 2.00 dollar item and figure the tax included is 10% shouldn't the retail price be 2.20 not 2.00.

**Comment by jekkos** [comment]
No tax included renders all prices in items having tax already included. This means that item without tax equals `price - price / ((100+percentage) / 100)`

**Comment by jekkos** [comment]
A more thorough answer on your questions

1. .Currently there's only a global flag to enable tax inclusion. Currently I haven't really found a usecase to make it local for an item. You do have a point saying that when enabling tax inlcusive pricing list price already has tax, while this is not the case when disabling it. In the latter situation tax will be added once an item is added in the registesr.

2. Same logic applies to the barcode generation. There's no tax added once prices are tax exclusive. This could be an improvement request as this might be desired in some cases.

**Comment by daN4cat** [comment]
@Pixmyster could you please fix this and send a PR? I mean point 2. from @jekkos comment. Point 1. is more work.

**Comment by daN4cat** [comment]
@SteveIreland the barcode use case is something to test as well with this tax inluded (VAT) or not included and incremental taxation ("US model").

**Comment by daN4cat** [comment]
@SteveIreland @odiea have you tested this case?
@Pixmyster you may want to take the latest code from master, upgrade the database (a copy of it!) and test if fixed.

**Comment by odiea** [comment]
I believe what he wants here is an enhancement. "should be "Retail Price $2.20 inc tax". But I might be wrong. I have not seen to many retail outlets showing pricing like this.
