### ISSUE TITLE
After login blank page show

### ISSUE THREAD

**Issue by asadjaved63** [jekkos/opensourcepos#1056]
Apache/2.4.23 (Win32) 
    phpmyadmin Version : 4.5.1
    PHP extension: mysqli Documentation
    PHP version: 5.6.28

hi
 hope you will fine with your health and business.  i have issue please help me to resolve i tried it a lot to resolve but no luck.
i follow all step to install

my url is localhost/pos/public
after login blank page show
 then url is 
localhost/pos/public/home

if url is localhost/pos/ then 404 error... 
 help me...

**Comment by odiea** [comment]
1. Make sure you are connecting to a database.
2. Make sure all the necessary php extensions are enabled.
More info about server and sql version.

**Comment by asadjaved63** [comment]
Yes, database connected.. And php_gd2,  php_intl, php bcmath, mcrypt  enable. 
But still after login blank page...

**Comment by daN4cat** [comment]
Check the .htaccess in public and make sure you select the option that includes the subdir pos that you added.

Search the database of issues from the past because this was discussed few times.

**Comment by rashedulislammasum** [comment]
Hello, I was running POS on php version 5.6.15. But afters installing php version 7.1.1 its showing same problem mensioned here.
