### ISSUE TITLE
### Bug-No Profit displayed in version 3.0.2

### ISSUE THREAD

**Issue by beinafuushop** [jekkos/opensourcepos#1057]
### Installation information
-In Blue host with the screen shot attached of my sql information
![image](https://cloud.githubusercontent.com/assets/23030848/21633331/3d482554-d25f-11e6-8e99-e1c43caf9149.png)

I Configure Tax Rate 1 as 0% in Localisation under store configurations.Then i Put 0% Tax in all items.

After Performing sales, and view all reports Profits is displayed as empty as per below screen shot. I use master file for the installation of version 3.0.2

![image](https://cloud.githubusercontent.com/assets/23030848/21633411/1b026454-d260-11e6-9be8-5351905c7dd9.png)

**Comment by daN4cat** [comment]
Leave the tax field empty, don't set to 0.

**Comment by beinafuushop** [comment]
Actually I didn"t do any changes but am totally suprised as its now working and display profit as usual.Thanx.
