### ISSUE TITLE
The localhost page isn’t working  localhost is currently unable to handle this request. HTTP ERROR 500

### ISSUE THREAD

**Issue by userscontroller** [jekkos/opensourcepos#1058]
[Wed Jan 04 14:30:23.815294 2017] [:error] [pid 8336:tid 1864] [client ::1:54908] PHP Fatal error:  Call to undefined function Racecore\\GATracking\\Client\\Adapter\\socket_create() in C:\\server\\htdocs\\vendor\\ins0\\google-measurement-php-client\\src\\Racecore\\GATracking\\Client\\Adapter\\Socket.php on line 26

please help me out. i am new in this

**Comment by daN4cat** [comment]
Make sure you have sockets enabled  in your phone support
