### ISSUE TITLE
Can't print receipts correctly

### ISSUE THREAD

**Issue by i92guboj** [jekkos/opensourcepos#1062]
### IMPORTANT IMPORTANT IMPORTANT

Report: bug

### Issue / Question / Bug

- [x] Checked the current issues database and no similar issue was already discussed
- [x] Read the README, WHATS_NEW and UPGRADE
- [x] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php5-gd, php-intl and sockets installed)
- [x] Reporting an issue of an unmodified OSPOS installation
- [x] PHP version is at least 5.5 and not 7.x
- [x] MySQL version is 5.5 or 5.6 and not 5.7
- [x] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [x] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [x] Know the name and version of OS, Web server and MySQL and will add to my issue report

### Installation information

Current gentoo amd64, current git ospos, mysql 5.6.34 and apache 2.4.23

### Expected behaviour

I should be able to print a correct ticket in ospos, but I can't

### Actual behaviour

Ticket appear with all the contents "compressed" into the top-left corner. So, it prints, but all the ticket text appears in a small region that's not larger than a thumb nail. The rest of the receipt is empty. This happens in current chrome, under linux. I have mixed results in other browsers, none of them resulting in a working configuration.

As you can see in the shot, the page size is 72 x 70 milimetters, which is a common receipt size. The printer is a bixolon srp-350, which has always worked under some other erp system.

Printing a test page from cups web interface works, of course.

Printing from ospos works, if we obviate the fact that it's so damn small.

Any ideas on where to look or what to try would be welcome.

![image](https://cloud.githubusercontent.com/assets/1565651/21814408/7eb03258-d759-11e6-8934-85973479dcfe.png)

### Steps to reproduce the issue

Just try to print a ticket.

**Comment by i92guboj** [comment]
Mmmm, just as always seems to happen. I have been weeks trying to figure a way around this, and just found it. Some web page with instructions to print tickets in mac/chrome suggested using "custom" as size in cups settings for this particular printer, and setting the width in inches instead of the predefined settings in millimeters. So, using 2.83 as width, seems to work.

I have no idea on how to ease this for newcomers, just saying this: it's been a pain for me.

Probably the issue is inaccurate at best (if not completely incorrect), but maybe something should be done regarding printing. In any case, if someone hits this and can't seem to print, maybe this will help him or her: use inches for page width in localhost:631 or your distro's cups configuration center.

**Comment by odiea** [comment]
Thanks for the feed back. This is a free opensource project so not all printers are tested. A lot of this is left up to the user to configure their printers properly.
