### ISSUE TITLE
[Question] License and Footer Change.

### ISSUE THREAD

**Issue by jason-joe** [jekkos/opensourcepos#1063]
@jekkos , @daN4cat 

Dear. Open Source POS Developers. License Question.

Hello.
I'm Jason Joe, working as Web developer.

First of all. I'm really appreciate about this OSPOS open source project.
This is nice solution to common sales and expanding other sales.

Accordingly,  I decide to use this OSPOS as basic frame to make my product.
Then I read license, there are condition, no removable 'Footer signatures'
I understand the reason to show footer. 
But I want change footer. even I know how to change or remove footer without UIblock.

But this removing is violation to License as I know.
So I'm asking about there are some exception of License Condition about change or remove footer by paying the amount or something.

This means not that I'm not following the License.
I will keep the MIT Licence completely.
I just want to change Footer. This is all I want.

Please reply,
Thank you.

Sincerely, Jason.

**Comment by odiea** [comment]
#972 should shed some light on your subject.

**Comment by jason-joe** [comment]
@odiea 
Yes, I read the issue before posting this issue.

The reason why I made issue even I read that article is there are mentioned donate.
So I thought that if I donate or give something, can I change footer?
And if it's possible, how much donate to this project?

This is what I wonder... 

Thank you.

**Comment by jekkos** [comment]
@jason-joe It's perfectly possible to adapt this software and sell it with some modifcations of your own but as we said we want to keep the name as it is so that credit can be given where it is due.

**Comment by jason-joe** [comment]
@jekkos I see. So I don't have option to change. 
Thank you for reply.
