### ISSUE TITLE
fail installation

### ISSUE THREAD

**Issue by gkapaino** [jekkos/opensourcepos#1068]
i tried to login but i failed can u help me what the problem about?
![1](https://cloud.githubusercontent.com/assets/22270296/22047560/d67a8ea4-dd38-11e6-80b0-de294808c4fd.JPG)
![2](https://cloud.githubusercontent.com/assets/22270296/22047582/fd982776-dd38-11e6-9424-022a441386da.JPG)

**Comment by odiea** [comment]
try localhost/opensourcepos/public

**Comment by gkapaino** [comment]
i have already try but i see blank page

**Comment by odiea** [comment]
You will have to read the faqs and the wiki. It is quite helpful.

**Comment by gkapaino** [comment]
ok but u can help if u knew

**Comment by odiea** [comment]
Not tonight. But you must read that info. Good Luck.

**Comment by gkapaino** [comment]
ok i will be back to you soon

**Comment by jekkos** [comment]
Answers for these common problems can be found in FAQ. Cloud install is a quick option as well if you don't succeed in setting up LAMP yourself.
