### ISSUE TITLE
Page not found error

### ISSUE THREAD

**Issue by RamkrishnaMondal** [jekkos/opensourcepos#1069]
### Installation information
![screenshot from 2017-01-18 16 38 52](https://cloud.githubusercontent.com/assets/14151032/22061802/a39c91e4-dd9c-11e6-98e5-25769406414d.png)

![screenshot from 2017-01-18 16 40 22](https://cloud.githubusercontent.com/assets/14151032/22061875/f12e4a2e-dd9c-11e6-9474-f848800e706c.png)

![screenshot from 2017-01-18 17 13 45](https://cloud.githubusercontent.com/assets/14151032/22062784/8f461c4c-dda1-11e6-872f-14e82329665c.png)
![screenshot from 2017-01-18 17 12 53](https://cloud.githubusercontent.com/assets/14151032/22062790/98a8c4ec-dda1-11e6-985b-955c7b601767.png)
![screenshot from 2017-01-18 17 11 58](https://cloud.githubusercontent.com/assets/14151032/22062796/a1208c86-dda1-11e6-9cbd-28d8318d0f11.png)

   
### Actual behaviour
![screenshot from 2017-01-18 16 35 41](https://cloud.githubusercontent.com/assets/14151032/22061882/fab81796-dd9c-11e6-8ab6-df0338c11729.png)
![screenshot from 2017-01-18 16 36 14](https://cloud.githubusercontent.com/assets/14151032/22061889/0259df02-dd9d-11e6-9f8a-9cf0c4225309.png)

Ospos v3.0.0 and older versions running fine from that very same root directory, but in case of the latest master (downloaded today) as soon as I click on "GO" button.... it shows  not found. The same master is working on my 2nd box (with same ubuntu LAMP). 

Just can't figure out what's causing the problem.....

**Comment by RamkrishnaMondal** [comment]
This problem not yet solved. Any idea ?

**Comment by paulg10me** [comment]
I am having this same problem. Have followed all the tutorial information, and was told to check closed issues, which brought me here. Still not having any luck. The server is looking for the public/login file but it does not exist. Is there any other information I can give that would help to find what's wrong?

**Comment by paulg10me** [comment]
The only other difference I can find is that my server is using PHP Version 7.0.15-0ubuntu0.16.04.4. Don't know if this could be affecting it.

**Comment by RamkrishnaMondal** [comment]
After this, i moved to LEMP  server.

https://github.com/jekkos/opensourcepos/wiki/Local-Deployment-using-LEMP
