### ISSUE TITLE
Issues in Mozilla firefox

### ISSUE THREAD

**Issue by bill-goldberg** [jekkos/opensourcepos#1070]
### IMPORTANT IMPORTANT IMPORTANT

Chose what you want to report: New Feature or Bug.
If you remove the template when submitting a Bug your issue will be closed as we cannot help without basic information.

### New Feature / Enhacement

For New Features or Enhacements please remove all the template text and clearly write your proposal.
It's important to state whether you expect the community to implement it or you will contribute the work.
Please bear in mind that we will implement new features only on the current code, there is no support for old versions.

### Issue / Question / Bug

Before submitting an issue please make sure you remove the first section of the template and you tick (add a x between the square brakets) and agree with all the following check boxes:

- [x] Checked the current issues database and no similar issue was already discussed
- [x] Read the README, WHATS_NEW and UPGRADE
- [x] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php5-gd, php-intl and sockets installed)
- [x] Reporting an issue of an unmodified OSPOS installation
- [x] PHP version is at least 5.5 and not 7.x
- [x] MySQL version is 5.5 or 5.6 and not 5.7
- [x] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [x] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [x] Know the name and version of OS, Web server and MySQL and will add to my issue report

### Installation information
Windows 10 x64
Chrome v55
Firefox v50
Wamp 2.5 x64
Apache 2.4
PHP 5.5
MySQL 5.6

### Steps to reproduce the issue

**Comment by bill-goldberg** [comment]
The Short receipt template is working fine in the Google Chrome after removing the browsers header and footer.
But this is not working in firefox even after setting the header and footer to --blank--

Is there any browser compatibility issues with this point of sale?

**Comment by odiea** [comment]
Do you have the JSPrint plugin installed for firefox. That might help.

**Comment by bill-goldberg** [comment]
Yes I have installed jsprint extension but still not able to use short template feature.

**Comment by jekkos** [comment]
OK you're right this is probably a bug. In print_receipt code there is a check for the receipt structure before it is printed. I'm not certain if this still makes sense here as receipt DOM's can be customized and so I'll remove it from the code

**Comment by odiea** [comment]
Glad to see you back again.

**Comment by jekkos** [comment]
Yes been quite busy on the new job + had a recent laptop crash which I had to fix last two days..

**Comment by jekkos** [comment]
I have pushed a fix for this but I don't have a printer here at the moment, @bill-goldberg can you verify if jsprint works now with the other receipt templates?

**Comment by bill-goldberg** [comment]
Thank you for fixing the issue with jsprint setup. I printed some receipt now short template is working properly.

**Comment by bill-goldberg** [comment]
Can you please tell me where to find the font-family and font-size for the receipt, i want to change the font and font-size on receipt

**Comment by bill-goldberg** [comment]
@jekkos we can do this in firefox (the jsprint setup addon) but what about chrome and ie, how to enable those options in these 2 remaining browsers?

**Comment by jekkos** [comment]
jsPrint is a plugin that only exists for FF. Chrome printing was discussed in #717. Currently there is no support for other browsers. I'll add a page to the wiki and reference existing issues there.
