### ISSUE TITLE
How to populate tables data rows with custom field data? 

### ISSUE THREAD

**Issue by RamkrishnaMondal** [jekkos/opensourcepos#1071]
### Installation information

![screenshot from 2017-01-19 13 22 27](https://cloud.githubusercontent.com/assets/14151032/22098183/f932c69c-de4a-11e6-87ef-04ea4182fa7e.png)

### Actual behaviour
Instead of custom field data, only getting small dash. What am I missing?

![screenshot from 2017-01-19 13 23 08](https://cloud.githubusercontent.com/assets/14151032/22098197/07008ec6-de4b-11e6-8328-5e6617ea8f78.png)

### Steps to reproduce the issue

**Comment by odiea** [comment]
You may have to include the custom1 in one of the temp databases.

**Comment by RamkrishnaMondal** [comment]
@odiea   Done!  Thank You.

**Comment by odiea** [comment]
If you want to see the custom1 name in get datacolumns you can replace it with this.
array('custom1_name' => $this->config->item('custom1_name')),

**Comment by RamkrishnaMondal** [comment]
Already done it via reports_lang. Now trying to use custom field as item unit and concatenate that custom field data with item quantity in inventory reports.

**Comment by RamkrishnaMondal** [comment]
Now the last hurdle.....fetching custom field data in  'new item-kit' form, i think some customization needs here........

![screenshot from 2017-01-22 01 54 50](https://cloud.githubusercontent.com/assets/14151032/22177790/4c876a62-e04b-11e6-8edd-e8c0978718c8.png)
