### ISSUE TITLE
Problem using OSPOS v3.0.2 with old database

### ISSUE THREAD

**Issue by RamkrishnaMondal** [jekkos/opensourcepos#1073]
### IMPORTANT IMPORTANT IMPORTANT

Chose what you want to report: New Feature or Bug.
If you remove the template when submitting a Bug your issue will be closed as we cannot help without basic information.

### New Feature / Enhacement

For New Features or Enhacements please remove all the template text and clearly write your proposal.
It's important to state whether you expect the community to implement it or you will contribute the work.
Please bear in mind that we will implement new features only on the current code, there is no support for old versions.

### Issue / Question / Bug

Before submitting an issue please make sure you remove the first section of the template and you tick (add a x between the square brakets) and agree with all the following check boxes:

- [] Checked the current issues database and no similar issue was already discussed
- [] Read the README, WHATS_NEW and UPGRADE
- [] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php5-gd, php-intl and sockets installed)
- [] Reporting an issue of an unmodified OSPOS installation
- [] PHP version is at least 5.5 and not 7.x
- [] MySQL version is 5.5 or 5.6 and not 5.7
- [] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [] Know the name and version of OS, Web server and MySQL and will add to my issue report

### Installation information
![screenshot from 2017-01-20 15 18 12](https://cloud.githubusercontent.com/assets/14151032/22144457/d17a4e2a-df23-11e6-9821-2ff9f8e43803.png)

### Expected behaviour

![screenshot from 2017-01-19 19 52 58](https://cloud.githubusercontent.com/assets/14151032/22110305/3819aa8e-de81-11e6-87b5-8c05b89749d2.png)

### Actual behaviour
![screenshot from 2017-01-19 19 52 19](https://cloud.githubusercontent.com/assets/14151032/22110311/400f3e20-de81-11e6-860d-ba0715867cd7.png)

After clicking "GO" button....

![screenshot from 2017-01-19 20 17 00](https://cloud.githubusercontent.com/assets/14151032/22111173/63b37cb2-de84-11e6-8160-2a6c58c4b481.png)

### Steps to reproduce the issue

I have an old mysql db with ospos3.0.0 running with it. I am trying to use that db with ospos3.0.2 but can't even log-in, even though 2.4_3.0.sql script already applied. ospos3.0.0 with that old db and ospos3.0.2 with newly created db  running smoothly.

**Comment by RamkrishnaMondal** [comment]
Sorted out .... problem was related to language & language_code  entry in app config.... for some strange reason script was failing, so edited manually.

**Comment by jekkos** [comment]
What did you edit to make it work in this case? I think in 3.0 a new language entry was added indeed but it should be in the update script.

**Comment by RamkrishnaMondal** [comment]
Yes added language entry manually.

 Everything works now ...except "Show receipt" in takings / after completing sale, 'show invoice' works without problem. 
As soon as i click on show receipt icon, screen freezes with error. 
Newly created db works fine,  problem occurs only with my old db.
Tried comparing db structures of two databases with https://github.com/dlevsha/compalex tool but can't find anything problematic.

![screenshot from 2017-01-20 13 44 28](https://cloud.githubusercontent.com/assets/14151032/22141186/cd2a087c-df16-11e6-9a50-fe9e372be346.png)


Here is the comparison.  Please have a look and let me know if you find anything wrong in "tm 302" db structure.

[COMPALEX - database schema compare tool.pdf](https://github.com/jekkos/opensourcepos/files/718756/COMPALEX.-.database.schema.compare.tool.pdf)

**Comment by RamkrishnaMondal** [comment]
Solved.

**Comment by aelhofy** [comment]
I have same error , please tell what to be edited to make it works?
