### ISSUE TITLE
Server Problem

### ISSUE THREAD

**Issue by stonecoldsteveAutsin** [jekkos/opensourcepos#1074]
Can i Use Xamp server onbehalf of Wampserver

**Comment by odiea** [comment]
Yes. I have had no problems with xampp. You can read the wiki. Currently 3.0.2 is not php7 compatible so I would suggest using an earlier version of xampp.

**Comment by eozalp** [comment]
Use november 12 compiled version. 

Then here is sweety part.

> install free public wifi { http://www.mypublicwifi.com/publicwifi/de/index.html }

> permit 8080 port on your firewall

> acces your local ospos via any device

> you can even use an android barcode keyboard.

**Comment by stonecoldsteveAutsin** [comment]
i done all set up But When i click Button on login it give error of The localhost page isn’t working..Using Xamp..Any Solution

**Comment by stonecoldsteveAutsin** [comment]
Using Wamp When i click on Sale Module It cann not Perform.please give any suggestion

![image](https://cloud.githubusercontent.com/assets/25225858/22155627/1bf2bbfe-df56-11e6-89d2-16ac342e785b.png)

**Comment by stonecoldsteveAutsin** [comment]
sale,Store config and Receiving feature not working..@eozalp.@odiea.Any solution

**Comment by odiea** [comment]
Verify that all the needed extensions are enabled and that you are using the current version.

**Comment by stonecoldsteveAutsin** [comment]
bcmath ext not found how i can enable?@odiea

**Comment by odiea** [comment]
Do you have it uncommented in the php.ini?

**Comment by stonecoldsteveAutsin** [comment]
@odiea  it not shown in php ini

**Comment by odiea** [comment]
Your using Wamp not Xampp?

**Comment by stonecoldsteveAutsin** [comment]
i m using wamp..2.5

**Comment by odiea** [comment]
About 3/4 of the way down in the php.ini file you should see [bc_math]. See if it is uncommented. This is as far as I can help you with Wamp.

**Comment by odiea** [comment]
Wamp has the same issue as Mamp. You must read the wiki about copying the acu files to apache bin. After that it started working for me.

**Comment by stonecoldsteveAutsin** [comment]
but in php.ini file bcmath extension not showing and i  did that icu file copy from php to apache but still it's not Working

**Comment by stonecoldsteveAutsin** [comment]
PHP Startup: Unable to load dynamic library 'c:/wamp/bin/php/php5.5.12/ext/php_ldap' error

**Comment by daN4cat** [comment]
You don't need ldap for OSPOS. You can comment that out

**Comment by stonecoldsteveAutsin** [comment]
@daN4cat .kk.but that would be fine.but what about php_intl error how could i resolved it.?

**Comment by stonecoldsteveAutsin** [comment]
Done..Thanks to @odiea @daN4cat @eozalp
