### ISSUE TITLE
paid work - takings visible only for location or employee

### ISSUE THREAD

**Issue by kaslak** [jekkos/opensourcepos#1075]
Hi, I'm new here and do not really understand the ways of how to get things done.
I like the program and using it on a test version, running 3.02 on a web server.
I do some php but I'm far away from levels of this.

I just upgraded from 3.01 to 3.02 and implemented all the little changes I like to have.
We have 3 store locations and about 5 users.

However, I would be curious to know how to achieve some implementations in a professional way.
So if there is a way to donate or pay for it I'd like to know how the process is.

As a starter, I think, it would make sense, that once on SALES and I click on "takings" ("sales_takings" -  the overview of sales) it would be good that the employee or the location can only see THEIR sales, not all. In reports this is possible by selecting the location - but the "sales_takings" button is very handy.

So, is there a interest to implement this? And what would be expected?

**Comment by odiea** [comment]
Indeed This would be a nice added filter. The adjust Sales reports to show all employees for that day.

**Comment by jekkos** [comment]
Indeed this could be added, and shouldn't be too hard at first sight. Just a matter of adding the employee_id to the takings queries.

**Comment by kaslak** [comment]
Exactly. It could be depending on the permissions, like in the reports.
BTW, also in Reports, location 1 can see location 2 - cause "all" is preselected :(

**Comment by odiea** [comment]
I would just place it as a non selectable filter in takings for the logged on employee. Then management can see everything from the detailed Sales report at the end of the day. It would be nice if Takings could be built into Sales then there would be no permission issues with Reports.

**Comment by kaslak** [comment]
"a non selectable filter" is cool. How can it be done?
The second part I cannot really follow: "It would be nice if Takings could be built into Sales..."

**Comment by odiea** [comment]
Currently Takings works from the Sales Reports so an Employee must have permission to the Sales Reports. If it were more integrated into Sales then they would not need permissions to any Reports.

**Comment by kaslak** [comment]
I get it.... but the pre-selection should be no big issue, or is it?
Any idea how to individually implement this?

**Comment by odiea** [comment]
No I sure do not. I just test for issues.

**Comment by jekkos** [comment]
Yes so the current situation is that you can configure who can see the takings but once this grant is given you always see all sale records.. If I understand correctly one would just like an extra filter in takings screen to filter on employee ?

**Comment by jekkos** [comment]
The report permission was then done more as a quick fix as there are other requests open for adding permissions more permissions to the modules #204

**Comment by odiea** [comment]
Yes. The only person to see the Takings Sales would be the logged on Individual and they would only see their Sales. No drop down filter.

**Comment by odiea** [comment]
But that would bring up another issue for a single location if the logged in employee needed to reprint a receipt from a logged out employee.

**Comment by kaslak** [comment]
@jekkos "If I understand correctly one would just like an extra filter in takings screen to filter on employee?:

That's what I mean... the logged in employee sees her/his sales and only those...

**Comment by jekkos** [comment]
In case one allows an employee to print out a sale made by another  then I guess he should just be able to see them as well? Otherwise I would suggest to make that behavior a default unless a user is an admin (which means he can give grants to others). In that case all employees should be shown.

**Comment by odiea** [comment]
It appears that this is starting another dilemma.

**Comment by kaslak** [comment]
employee 1 should -IMHO- not have the option to print, delete or whatever a sale of employee 2
The only person who should be allowed is the one with admin rights - just like real life ;)

**Comment by kaslak** [comment]
...and I'm only talking about the button in sales or register (language-file: sales_takings) - NOT reports.
Can you give me a hint how to individually manage this - before the discussion goes into the big, big structure

**Comment by kaslak** [comment]
@jekkos "Otherwise I would suggest to make that behavior a default unless a user is an admin"
...just what I'm talking...

**Comment by odiea** [comment]
I have removed all the delete buttons from sales. You have not had an employee go on break and employee 2 logs in and a previous customer comes back and asks for the receipt employee 1 did not give them?

**Comment by kaslak** [comment]
You got a point here... if trust is not an issue, it's easy (E1 logs in as E2). 
I'm more concerned about mistakes, wrong clicks, stress, etc.
If employee 2 needs someone to alter his/her sales (manager or me) it feels "safer" to me...

**Comment by kaslak** [comment]
as I said in the issue header: if tthere is a solution, and if it's only temporarily or indiviual, I'd like to know how the donation / payment idea works. No offence please. I'm willing to give to get somewhere. Enjoy life!

**Comment by odiea** [comment]
I played around with the code this morning. You can give this a try. It will only show the current logged on employee in Takings. Extract it then rename your old Sale.php and replace it with this one. Hope it works for you.
[Sale.zip](https://github.com/jekkos/opensourcepos/files/720114/Sale.zip)

**Comment by odiea** [comment]
This needs to be placed in application/models

**Comment by kaslak** [comment]
@odiea Thanks! Little time now. Will check later and report...

**Comment by kaslak** [comment]
@odiea well, so far seems to do the job... I saw the 2 WHERE additions in get_info($sale_id) and in get_payments_summary($search, $filters)

What I did not understand is the taking off of the $payments definitions in line 666 of the original Sale.php ... that should not conflict ... or do I miss something?

Anyhow, thanks a lot. This was helpful.

**Comment by odiea** [comment]
I do not see that anything has been removed.

**Comment by kaslak** [comment]
Ups, sorry, my fault ... I added 2 payment methods in my file and had forgotten about it...

**Comment by odiea** [comment]
OK I close this issue now.

**Comment by kaslak** [comment]
To finalize this topic, let me quickly resume. Reading through this thread, I still think, that either employee[x] can only see his/her sales, or everyone can select (from all) where employee[x]'s sales should be pre-selected, would be a great option. Fully integrated with permissions, that would be quite an enhancement.
