### ISSUE TITLE
New Master Quirk?

### ISSUE THREAD

**Issue by odiea** [jekkos/opensourcepos#1076]
Just downloaded the Master and there is a small quirk in the Takings display. A small e in the upper left view.
![2017-01-20 10_32_52-wedidit _ powered by ospos 3 0 2](https://cloud.githubusercontent.com/assets/10962177/22160178/80cb24c6-df01-11e6-9f06-e7ee68c37038.png)

**Comment by RamkrishnaMondal** [comment]
Also see a TBD in short receipt for 'recvs_invoice_number'.

**Comment by odiea** [comment]
Ya that line should be sales_invoice_number.

**Comment by jekkos** [comment]
Ok I removed these quirks sorry about that.

**Comment by odiea** [comment]
Could you also update the table-helper with The reset element. PHP 7 works with this. I think it should be line 140. Thanks
foreach($array as $element)
	{
        reset($element);
		$result[] = array('field' => key($element),

**Comment by jekkos** [comment]
Ok done, does it make ospos fully PHP7 compatible?

**Comment by jekkos** [comment]
I referred issue #591 for this commit
