### ISSUE TITLE
Issue with print - Dotmatrix printer

### ISSUE THREAD

**Issue by asarada** [jekkos/opensourcepos#1078]
### Issue 

- [x] Checked the current issues database and no similar issue was already discussed
- [x] Read the README, WHATS_NEW and UPGRADE
- [x] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php5-gd, php-intl and sockets installed)
- [x] Reporting an issue of an unmodified OSPOS installation
- [x] PHP version is at least 5.5 and not 7.x
- [x] MySQL version is 5.5 or 5.6 and not 5.7
- [] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [] Know the name and version of OS, Web server and MySQL and will add to my issue report

### Expected behaviour
Receipt printed with good quality 

### Actual behaviour
I'm not getting the receipt printed with good quality( fonts are very small and bit distorted) generated through ospos on dot matrix receipt printer. When I give print through the notepad, word it works without any flaw.

Is there any setting to be enabled for getting the quality print?

### Steps to reproduce the issue
Create new sale
Add items to the sale
Complete the sale
print the invoice.

**Comment by daN4cat** [comment]
You can always create your own receipt template and add it to the code.
At the moment there are two examples, check those and see how you can improve it for your needs but don't expect anything about from us. No time for this and it's a special case.
