### ISSUE TITLE
How can i change Discount percentage into value discount

### ISSUE THREAD

**Issue by asadjaved63** [jekkos/opensourcepos#1079]
hey
How can i  change discount in % to discount by value? i don't want percentage discount to my customer. .i want static discount ... how can i change?

`function get_item_discount($quantity, $price, $discount_percentage)
	{
		$total = bcmul($quantity, $price, PRECISION); // ($item['price']*$item['quantity']-$item['discount']); 
		$discount_fraction = bcdiv($discount_percentage, 100, PRECISION);
		return bcmul($total, $discount_fraction, PRECISION);
	}`

**Comment by odiea** [comment]
This looks like #911. Multiple requests for this option.
