### ISSUE TITLE
Has something changed in Takings display.

### ISSUE THREAD

**Issue by odiea** [jekkos/opensourcepos#1081]
### IMPORTANT IMPORTANT IMPORTANT

Chose what you want to report: New Feature or Bug.
If you remove the template when submitting a Bug your issue will be closed as we cannot help without basic information.

### New Feature / Enhacement

For New Features or Enhacements please remove all the template text and clearly write your proposal.
It's important to state whether you expect the community to implement it or you will contribute the work.
Please bear in mind that we will implement new features only on the current code, there is no support for old versions.

### Issue / Question / Bug

Before submitting an issue please make sure you remove the first section of the template and you tick (add a x between the square brakets) and agree with all the following check boxes:

- [x] Checked the current issues database and no similar issue was already discussed
- [x] Read the README, WHATS_NEW and UPGRADE
- [x] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php5-gd, php-intl and sockets installed)
- [x] Reporting an issue of an unmodified OSPOS installation
- [x] PHP version is at least 5.5 and not 7.x
- [x] MySQL version is 5.5 or 5.6 and not 5.7
- [x] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [x] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [x] Know the name and version of OS, Web server and MySQL and will add to my issue report

### Actual behaviour
Has something changed in the Display of Returns in the Takings rows?

### Steps to reproduce the issue
The full display is from my previous version. The empty display is from the current version. This is after making a Return. Also in register when adding a kit it finds it with either kit or KIT where in Return It has to be upper case POS to find the Sale. 
![2017-01-23 05_49_03-wedidit _ powered by ospos 3 0 2](https://cloud.githubusercontent.com/assets/10962177/22204717/aba8a69c-e130-11e6-8926-09ee46c56e48.png)

**Comment by jekkos** [comment]
Which versions are you comparing exactly? The current master HEAD and the commit before?

**Comment by odiea** [comment]
I am comparing the current version with the version I have that has been updated by git.

**Comment by odiea** [comment]
Looking at the db it appears sales_payments does not get updated if the payment is a negative amount.

**Comment by odiea** [comment]
It appears that when you do a Return The payment type or Amount are not set in the Register. Wasn't there a If mode = return  statement in there at one time to cover this situation?
![2017-01-23 14_07_14-wedidit _ powered by ospos 3 0 2](https://cloud.githubusercontent.com/assets/10962177/22222804/83c4ef9c-e175-11e6-9e96-1609fb53ef10.png)

**Comment by odiea** [comment]
The reason my version works is because of the following allowing to add payments.
~~~
                                      <div id="payment_details">
					<?php
					if($mode == 'return' or $invoice_number_enabled)
					{
					$payments_cover_total = $payments_total; 
					}
					if($payments_cover_total)
					{
					?>
~~~

**Comment by odiea** [comment]
In controller sales under _reload I changed the following line to
		$data['payments_cover_total'] = $this->sale_lib->get_amount_due() <= $payments_cover_total;
And it appears to work letting you add the payment in a return.

**Comment by jekkos** [comment]
Is there no other way to find an item kit return beside using KIT in the name? So you mean you can't retrieve it with it's POS ticket number?

**Comment by jekkos** [comment]
Regarding negative payment, do you expect the register to cancel a payment done for a given set of items then? Amount due is negative indeed but that might not be reflected in the payments table

**Comment by odiea** [comment]
I was not very clear.
In Sales and Returns you can use the prefix kit or KIT to look up an Item kit.
In Return the POS prefix must be in uppercase to find a Receipt. Can this be changed to either or?

**Comment by odiea** [comment]
As far as the Returns in the payments. When there was a visible 2 button Add payment or Complete Payment the negative amounts were set in the Payments Table. One could also select the Payment type . Maybe you wanted to credit a card or write a Company a check. Currently there is no audit as far as how the return was reimbursed in the payments table or on the Receipt..

**Comment by odiea** [comment]
After more testing in Returns. After you enter a Pos receipt or a single item the Register goes to Complete Sale. When you enter an Item kit in Returns you will get the add payment button not the Complete button.

**Comment by daN4cat** [comment]
@odiea, is this issue related to Items Kit something @SteveIreland can fix?

**Comment by odiea** [comment]
No it is not. This is normal operation in the master.

**Comment by daN4cat** [comment]
You are correct, I mixed up. KIT or kit is fine, POS or pos is not.

**Comment by RamkrishnaMondal** [comment]
Someone please fix this.

**Comment by daN4cat** [comment]
This is now fixed, please @odiea confirm it's fine or not.

**Comment by odiea** [comment]
Yes. It works great now as far as the POS or pos KIT or kit.

**Comment by daN4cat** [comment]
So I close.

**Comment by RamkrishnaMondal** [comment]
@daN4cat  POS / pos problem is fixed now but still having the payment options `inactive` in case of a return.

**Comment by daN4cat** [comment]
I'm under the impression that this used to work in 3.0.x.
I changed the register and tested different cases and again I'm under the impression it used to be fine.

I need to check if something was changed around this point.

**Comment by daN4cat** [comment]
Can somebody test with 3.0.2 version? I don't have that much time these days...

**Comment by odiea** [comment]
Sorry I deleted all mine.

**Comment by daN4cat** [comment]
Anyway, I will need to fix. So probably no point to go back in time and I need to check what's wrong.

**Comment by RamkrishnaMondal** [comment]
Tested, it's working on V3.0.0 or older. Not working on v3.0.2/ v3.1.0

Hope this helps.

**Comment by daN4cat** [comment]
Great help, many thanks. I need to understand what I broke from 3.0
0 😕😕😕

**Comment by daN4cat** [comment]
@jekkos I suspect this has something to do with the change done in #733.
Basically if the amount is 0 or negative it's marked as ok and shows the complete button.
Before it was ok only if ==0, but because of the precision issue it was set to <=0.
However what's missing here is the fact that in return mode the amount can be negative.

**Comment by daN4cat** [comment]
It should probably be considered ok only if == (0 + rounding error). Thoughts?

**Comment by daN4cat** [comment]
I think I fixed the issue but you now need to test it properly in various conditions (especially with fancy tax break downs), either in sale and return modes.

**Comment by RamkrishnaMondal** [comment]
@daN4cat  Thank You very much, appears to be working. I'll test more with different conditions.

**Comment by daN4cat** [comment]
Yep the tricky bit is with unusual taxation, that's always the problem here and the rounding effect.

**Comment by RamkrishnaMondal** [comment]
@daN4cat  Also manually updated v3.0.2 with these fixes, working nice!

**Comment by daN4cat** [comment]
@odiea do you think you could do a bit of sanity check around this change too?

**Comment by odiea** [comment]
Please check out issue #1144.

**Comment by odiea** [comment]
I just re downloaded and all is ok now.

**Comment by odiea** [comment]
So far working great.
![2017-02-20 12_46_12-wedidit _ powered by ospos 3 1 0](https://cloud.githubusercontent.com/assets/10962177/23139737/1fa8e160-f76b-11e6-96fe-655e4ccb95fd.png)
![2017-02-20 12_48_26-wedidit _ powered by ospos 3 1 0](https://cloud.githubusercontent.com/assets/10962177/23139739/2758439c-f76b-11e6-888a-19781c441162.png)

**Comment by daN4cat** [comment]
OK, this seems sorted.
