### ISSUE TITLE
short cut keys

### ISSUE THREAD

**Issue by asadjaved63** [jekkos/opensourcepos#1083]
hi jekkos sir,
i want to know list of shortcut keys which are using in All project,
thanks

**Comment by odiea** [comment]
There are none that I know of. All Fkey functions were removed .

**Comment by asadjaved63** [comment]
how to Add new hot keys?

**Comment by daN4cat** [comment]
See #425

**Comment by WebShells** [comment]
> A final stable fix was applied to this issue through PR #4532
