### ISSUE TITLE
Question: customer phone number

### ISSUE THREAD

**Issue by jacksz** [jekkos/opensourcepos#1085]
is there a variable for customer phone number?

**Comment by odiea** [comment]
look in controller customer.

**Comment by jacksz** [comment]
ist possible to access it without ospos locking up? tried to echo it and then ospos locked up

**Comment by daN4cat** [comment]
what do you mean with "locked up"?

**Comment by jacksz** [comment]
you know similar to when you change the footer = locks 

i made a script to get the the phone number based on customer name but 

`$sql = "select phone_number from ospos_people where replace(concat(first_name,' ', last_name), ' ', ' ') = '$customer'";`

`$ncustomer= $row["phone_number"];`

**Comment by daN4cat** [comment]
I don't think you need the ' around $customer, that's where it's probably falling over.

**Comment by jacksz** [comment]
no its actually working great but the problem is if someone has a duplicate name  it may bring the wrong result 

`$sql = "select phone_number from ospos_people where replace(concat(first_name,' ', last_name), ' ', ' ') = '$customer'";
$result = mysqli_query($conn, $sql);

if (mysqli_num_rows($result) > 0) {
    // output data of each row
    while($row = mysqli_fetch_assoc($result)) {
       $ncustomer= $row["phone_number"];
    }
} else {
     $ncustomer=  "no phone number";
}`

`<?php echo  $ncustomer;  ?>`

**Comment by daN4cat** [comment]
Not sure I follow, where is that you need this to be added? Customers view or else?

**Comment by RamkrishnaMondal** [comment]
See  #472
