### ISSUE TITLE
Phone number customer lookup

### ISSUE THREAD

**Issue by chris-pilly** [jekkos/opensourcepos#1087]
I'm just new to the software and it looks like its about 90% there for what I need. And since it is free open source software I understand there may be warts, but this POS solution is unreal for for the cost of ownership! I'm totally impressed. now to my question regarding phone numbers:

is it possible to search customers in the "sale" screen based on their phone numbers as opposed to asking their name all the time then asking them to confirm that I have the right "Mr. Smith"? When I tried to use the phone number it just went to add a new customer. and if its not possible could I add a feature request to be able to search based on info other than first or last name?

for the record I'm getting excited to open my store and looking forward to using this software. So please excuse my enthusiasm. 

two other feature requests I have would be adding a loyalty point system. and finally being able to either set a total price for "kits" OR at least being able to add a set discount % to all items within that kit, without having to add an individual discount for the items on the sale screen. 

Upon looking through the issues it seems that the kit pricing is already a popular topic so please just consider this my support for the request.

**Comment by RamkrishnaMondal** [comment]
See #744

**Comment by jekkos** [comment]
Think the solution in that issue isn't valid for current code. Suggest stuff was removed after implementing bootstrap tables.. The real backend search code will need to be adapted to search for the phone number if that's not already the case

**Comment by ashishkaushik** [comment]
Any quick fixes suggested for this ?

**Comment by daN4cat** [comment]
@chris-pilly any progress with this feature?

**Comment by daN4cat** [comment]
To look up by phone number should not be a big deal.

**Comment by ashishkaushik** [comment]
Thanks. Can you share some insights on the same would be helpful. I can
work on the same and submit back.

----------------------------------------------------------------------------------
* Ashish *Kaushik
 SourceFuse Technologies
----------------------------------------------------------------------------------

**Comment by jekkos** [comment]
Also would be useful to add the same autocomplete in SMS sending module.. as it's not really usable having to type phone numbers manually now

**Comment by daN4cat** [comment]
Added the capability to lookup by phone number and email a customer from the sales register.
Please note that the suggestion will pop up people's name and not phone numbers.

@jekkos sms can be sent straight from the list of customers clicking the phone icon, the message view is just to send sms in a generic way, I would not touch that.

**Comment by daN4cat** [comment]
#744 solves the visibility of the phone number in the suggestion list

**Comment by SteveIreland** [comment]
I really like this enhancement.  Thanks!

**Comment by daN4cat** [comment]
Good and it looks like it's working fine, so I close.
