### ISSUE TITLE
Printed receipt is looking in small font 

### ISSUE THREAD

**Issue by prabakar1978** [jekkos/opensourcepos#1091]
###  Question 

Invoice printing recipt is looking very small when i am using default configuration.. Please guide to me how to change printing recipt format to change in a visible format.

Thanks 
Prabahar. T

**Comment by daN4cat** [comment]
in application/views/sales, check receipt_default.php or receipt_short.php.
It would be better to create a new one for your case (e.g. receipt_big.php) based on one of the above listed examples and add it to the list of templates in application/views/config/receipt_config.php

**Comment by ravindug** [comment]
Install you Printer as RAW printer... .https://qz.io/wiki/Setting-Up-A-Raw-Printer-in-Windows
