### ISSUE TITLE
Detailed Receiving Report does not show Supplier

### ISSUE THREAD

**Issue by gerarldlee** [jekkos/opensourcepos#1093]
This is a Bug fix. Sorry I did not have the time to use git because the fix is very simple and have many things to do. So I am posting this fix. Thanks!

### Issue / Question / Bug

- [x] Checked the current issues database and no similar issue was already discussed
- [x] Read the README, WHATS_NEW and UPGRADE
- [x] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php5-gd, php-intl and sockets installed)
- [x] Reporting an issue of an unmodified OSPOS installation
- [x] PHP version is at least 5.5 and not 7.x
- [x] MySQL version is 5.5 or 5.6 and not 5.7
- [x] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [x] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [x] Know the name and version of OS, Web server and MySQL and will add to my issue report

### Installation information
Latest master branch
OS - Ubuntu 16.04
Web server - Apache HTTPD
MySQL - 5.7

### Expected behaviour
![fix-screen-ospos](https://cloud.githubusercontent.com/assets/219808/22404808/3ece9f70-e673-11e6-91fe-a7d3eeb88d33.PNG)

### Actual behaviour
Please see attach
![error-ospos](https://cloud.githubusercontent.com/assets/219808/22404806/3ec6edf2-e673-11e6-82b6-12e6b1f46047.PNG)

### Steps to reproduce the issue
This is a Javascript Bootstrap Table issue that requires table header column name be the same with the retrieved table header column name in the Detailed Receiving reports.
1.  Make a Receiving, with a Supplier
2. Click on Reports -> Detailed Receiving
3. You will not see the entered supplier under the Supplied by column

### Fix
Please change the application/models/reports/Detailed_receivings.php
```
public function getDataColumn()
...
array('supplier' => $this->lang->line('reports_supplied_by')),
...

to 
array('supplier_name' => $this->lang->line('reports_supplied_by')),
```
*Fix attached as shown
![fix_ospos](https://cloud.githubusercontent.com/assets/219808/22404807/3ece1ed8-e673-11e6-82fa-0bd304dd7245.PNG)

![fix-screen-ospos](https://cloud.githubusercontent.com/assets/219808/22404808/3ece9f70-e673-11e6-91fe-a7d3eeb88d33.PNG)

**Comment by daN4cat** [comment]
Thanks for the bug report, I fixed and submitted to master.
