### ISSUE TITLE
Detailed Report not showing correct tax info.

### ISSUE THREAD

**Issue by odiea** [jekkos/opensourcepos#1094]
### Issue / Question / Bug

Before submitting an issue please make sure you remove the first section of the template and you tick (add a x between the square brakets) and agree with all the following check boxes:

- [x] Checked the current issues database and no similar issue was already discussed
- [x] Read the README, WHATS_NEW and UPGRADE
- [x] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php5-gd, php-intl and sockets installed)
- [x] Reporting an issue of an unmodified OSPOS installation
- [x] PHP version is at least 5.5 and not 7.x
- [x] MySQL version is 5.5 or 5.6 and not 5.7
- [x] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [x] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [x] Know the name and version of OS, Web server and MySQL and will add to my issue report

### Installation information
OSPOS on Xampp

### Expected behaviour
Detailed Report should show correct Taxes

### Actual behaviour
It does not show correct taxes.

### Steps to reproduce the issue
Compare Detailed Report to any Summary report that shows tax info.
Minor issue with the way Detailed Sales Report configures tax.
![2017-01-29 06_56_55-wedidit _ powered by ospos 3 0 2](https://cloud.githubusercontent.com/assets/10962177/22404617/ec2b2c2e-e5f1-11e6-94fc-e916917af6d8.png)
![2017-01-29 06_58_01-wedidit _ powered by ospos 3 0 2](https://cloud.githubusercontent.com/assets/10962177/22404619/f8b4f704-e5f1-11e6-974f-4afd5ca748e9.png)

**Comment by odiea** [comment]
In Sales summary if you add up subtotal and tax the amount should be 82.97 not 82.96

**Comment by daN4cat** [comment]
I thought I fixed that issue of the tax calculation not being correct between the two but somehow it's still not right.
When I find the time and inspiration I will look into this again, but it's better to merge some code changes here before changing that part otherwise we keep moving parts and not get to an end.

**Comment by kaslak** [comment]
It might be a question of digits after the decimal... In German with 19% VAT I need to have 19,000 (19.000) to get the right values ... this is the same in a totally different program I'm using in another case. Maybe give it a try. It's a round() issue.

**Comment by daN4cat** [comment]
@kaslak thanks for the hint, something to check properly. It's indeed a rounding issue and it might be better to always do the maths with 3 digits and round the result to avoid the issue of sum of rounded partials. Because that's the issue here...

**Comment by odiea** [comment]
Issue with Takings and Sales tax. Let me know if you want this to be a separate issue.
If an Item with a blank or empty tax is sold the result is 1452. This does not happen when you place a 0 in tax%.
![2017-02-02 07_27_01-wedidit _ powered by ospos 3 1 0](https://cloud.githubusercontent.com/assets/10962177/22553279/5f81992c-e919-11e6-8a32-5dfa203993bc.png)

**Comment by daN4cat** [comment]
Known issue and workaround is set to 0

**Comment by daN4cat** [comment]
I'm currently working on this....

**Comment by daN4cat** [comment]
@odiea see my last commit to master. Please test as I reworked the tax calculation.
Hopefully I managed to fix all was required, but you never know.... it took half day of work!

**Comment by odiea** [comment]
Now the Taxes show the same amount in all Reports. Great job. And they appear to be roundin up correctly.
![2017-02-26 18_42_34-](https://cloud.githubusercontent.com/assets/10962177/23346025/b4c6a47a-fc53-11e6-9e06-d3d110a9b419.png)

**Comment by daN4cat** [comment]
At least this one is fixed 😊
