### ISSUE TITLE
How to access ospos without adding '/public' in url ? 

### ISSUE THREAD

**Issue by RamkrishnaMondal** [jekkos/opensourcepos#1095]
I wish to access ospos without adding '/public' in url ?  How can I do that ? @jekkos  @daN4cat

**Comment by daN4cat** [comment]
@RamkrishnaMondal you can create a subdomain pointing to the public subdir, e.g. pos3.mysite.com, and then you need to check the .htaccess in public folder to be all fine.

**Comment by RamkrishnaMondal** [comment]
But my problem is, in my free hosting server, subdomain creation is not supported. I use that free server as a backup of my ospos installation. It is also handy for testing purpose.
http://www.ospos.pe.hu

**Comment by daN4cat** [comment]
You can see if you can find a way to change .htaccess in opensourcepos dir, and find a way to redirect it to public.
Check composer documentation or forum discussions how to solve that problem.
If you find a solution it would be nice to add it to the code here.

**Comment by RamkrishnaMondal** [comment]
Done via 'redirect' option of Cpanel.
