### ISSUE TITLE
Unable to Install need help

### ISSUE THREAD

**Issue by saikatkoley** [jekkos/opensourcepos#1096]
Unable to install showing

 Access forbidden!

You don't have permission to access the requested directory. There is either no index document or the directory is read-protected.

If you think this is a server error, please contact the webmaster.

Error 403

localhost
Apache/2.4.17 (Win32) OpenSSL/1.0.2d PHP/5.6.20

Help please

**Comment by tenkodoy** [comment]
Have you made your db ready in xampp/wampp? have you made the changes in the config file?

**Comment by daN4cat** [comment]
Point to public dir...

**Comment by odiea** [comment]
If you downloaded it with Internet explorer or Edge. Go back to your original download right click and select properties. Check unblock then extract it again.

**Comment by saikatkoley** [comment]
I downloaded it from Mozilla Firefox . And yes i pointed to public dir but
then showing login page after logging it's showing 500 error.

**Comment by daN4cat** [comment]
Please search the closed issues as you'll find an answer. We keep answering the same questions again and again especially on Windows installations.... to be really honest here I'm a bit tired as a little effort on the issue poster side would save us time to do more productive things for OSPOS.

**Comment by saikatkoley** [comment]
Thanks
