### ISSUE TITLE
Date Time does not work with the default settings.

### ISSUE THREAD

**Issue by odiea** [jekkos/opensourcepos#1098]
### Issue / Question / Bug

Before submitting an issue please make sure you remove the first section of the template and you tick (add a x between the square brakets) and agree with all the following check boxes:

- [x] Checked the current issues database and no similar issue was already discussed
- [x] Read the README, WHATS_NEW and UPGRADE
- [x] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php5-gd, php-intl and sockets installed)
- [x] Reporting an issue of an unmodified OSPOS installation
- [x] PHP version is at least 5.5 and not 7.x
- [x] MySQL version is 5.5 or 5.6 and not 5.7
- [x] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [x] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [x] Know the name and version of OS, Web server and MySQL and will add to my issue report

### Expected behaviour
Date time default should be accepted.

### Actual behaviour
Date time default has to be changed everytime you want to see the totals.

### Steps to reproduce the issue

**Comment by odiea** [comment]
Here is the Default for Date Time - Works fine selecting a previous date.
![2017-01-30 15_07_17-wedidit _ powered by ospos 3 1 0](https://cloud.githubusercontent.com/assets/10962177/22443928/11515bf6-e6fe-11e6-92ec-357df8b21356.png)
Here is what the Report shows as the selected Date and Time. It appears that it is the minute you get the report.
![2017-01-30 15_07_34-wedidit _ powered by ospos 3 1 0](https://cloud.githubusercontent.com/assets/10962177/22443976/439507fc-e6fe-11e6-9889-994243d47086.png)
Can this be fixed to show the current date time using the default setting?

**Comment by daN4cat** [comment]
Is this happening only when you select time with am/pm?
I tried with 24h time format and it seem fine.

**Comment by daN4cat** [comment]
Connected to #932

**Comment by odiea** [comment]
I posted my response to #932

**Comment by daN4cat** [comment]
@jlctmaster to look into this issue.

**Comment by daN4cat** [comment]
This is fixed.
