### ISSUE TITLE
Change Overview from Sale page to be a daily view

### ISSUE THREAD

**Issue by daN4cat** [jekkos/opensourcepos#110]
It would be handy to change the Overview from Sale page to be a daily view reporting even the payment amounts per transaction and a payment total.
This overview could be an handy end of day report that shop keeper can use to countercheck PDQ machine reports and cash drawer amount.

If no objections I would do that change.

**Comment by jekkos** [comment]
You mean like a 'cut Z' report? There are some performance issues in this screen when a large number of rows are present in the database. However I think it's quite handy if you want to search for a customer's sale records in the past.

Maybe we should try to add this daily report to the reports section only? I know that it's not really consistent to have the manage view separated from the regular reports either, but currently I think it's a nice and convenient way to edit/delete sales and regenerate invoices/receipts for customers.

**Comment by daN4cat** [comment]
I find handy to have it from sales because that's what they tend to use in the shop and a click shortcut to see the summary of the day will be appreciated.
A daily report should not have tons of transactions and surely less than what's at the moment. I didn't check if logging out the view is reset or else?

**Comment by jekkos** [comment]
Yes you're right, most of the time we only use the first 1 - 2 pages of this overview. Loading all of the data in that view makes it terribly slow as well. Maybe we can add a couple of filter options (set it to daily by default), while still allowing to search through the whole set of records. 

How exactly would you display the transactions then? Similar as in the report section?

**Comment by daN4cat** [comment]
I can first make it "today" and add the payment amounts and totals.
I can add later a day selection or range on the top bar.

**Comment by jekkos** [comment]
Exactly what I had in mind.

**Comment by daN4cat** [comment]
You can assign this ticket to me if you are fine and mark it as enhancement.

**Comment by jekkos** [comment]
I had to grant push access to be able to assign issues, so now you have access to this repo as well . Howevver I would like to keep the pull request way of working (which allows us to do review on new features and fixes more easily).

**Comment by daN4cat** [comment]
Yes, no worries. Push and pull of code stays the same as I prefer as well. Now I sorted the polluted history issue and I'll keep two branches development and master (for delivery).

**Comment by daN4cat** [comment]
Just checking the code around this sales/manage area and there are mistakes.
In sales.php function manage gets $payment_type as parameter, which is then passed to Sale->get_all. But Sale get_all take $only_invoices as parameter.
This is either all always 0 and always ignored or it's a nonsense.

**Comment by daN4cat** [comment]
I had an initial go but it's taking time on the database search side. I don't know why module doesn't leverage the standard reports models to pull the data and I would like to make that change to avoid re-inventing the wheel. So some refactoring is required first.

**Comment by jekkos** [comment]
Regarding the model, you mean that it would have been better to leverage the sales temp table? I think you're right as I see that the following data

* Payment amounts summed up per sale
* Item prices summed up per sale

is readily available from that table and as. The current query is taking ages once you have >1000 rows in sales table so some refactoring is indeed a good idea.

The payment_type variable is moved in as first param in the manage method in sales.php controller. but maybe the naming is a bit misleading. I guess I should have used  $only_invoices in the controller as well. But as far as I can see this isn't a bug (filtering using the dropdown in the filter section works just fine).

**Comment by daN4cat** [comment]
Yes, the idea is to use sales_temp_table and reuse existing methods or add a new one as an extension.

I just added in a quick prototype the invoice_number field in the temp table.

I'll rename the $payment_type to $only_invoices because reading the code you get puzzled.

**Comment by daN4cat** [comment]
What's the purpose of having the only_invoices and search box if this view becomes a daily report of takings?

**Comment by jekkos** [comment]
I found search really handy to look for a specific customer's sale in the system. The only_invoices will just filter out the receipts that have a invoice number assigned. This is useful as in Belgium only those receipts weren't taxable and so have to be sent to the bookkeeper at the end of the month.

**Comment by daN4cat** [comment]
I understand.

But maybe it's better to make a distinction between what is a report and what is just a daily view of sales for end of the day reporting of takings?

Probably the bookkeeping functionality should go in a report, what do you think?

**Comment by daN4cat** [comment]
Maybe we just need to modify the detailed sales report to have a search and set of checkboxes like in items (one being the invoices point).

**Comment by jekkos** [comment]
Yes indeed maybe it's better then to move this filtering functionality to the detailed report. Most of the time the screen is only used to look for sales the same day.

But what about the search? I know there's already a specific customer report that does the same thing, however at this moment it's not really usable due to the select box without autocomplete

**Comment by jekkos** [comment]
Maybe we can find a way to keep the shortcut in the sales module and have it pull up the detailed report instead? And maybe add some pagination (like a limit and offset parameter on the result set to scroll through results if necessary?)

**Comment by daN4cat** [comment]
I'm at good stage with the Daily takings part and I would like to retain this adding a new button in Sale at this point. I just need to add the summary part and then test it with refresh scenarios.
I will clean the only_invoices, search and etc.

I can link Overview button to Detail sale report, but then we need to add search and checkboxes in that view/report.

**Comment by jekkos** [comment]
Ok I think it's better to consolidate the two sales overviews inside the detailed sale report then.

I wonder how much effort it would take to add a generic pagination to the detailed reports
most of the report results are generated using the same view. In this case I would indeed opt for a limit parameter in the detailed report input screen.

I'd still like to keep some functionality present now in the overview only by adding the following to the sale's detailed report's input

* only_invoices filtering
* edit, receipt and invoice links in the report's table rows itself (for fast access)
* omit sales search (too slow anyway)
* summary shortcut to detailed report in sale module 
* we might want to add a direct link to this specific_customer report in the customers module itself (for quicker access)

**Comment by daN4cat** [comment]
The gift card needs some working because it doesn't appear like one total under GiftCard but as multiple GiftCard payments.

**Comment by odiea** [comment]
If the overview is now Takings shouldn't returns or refunds be included. If your till is short showing refunds would eliminate this shortage?

**Comment by daN4cat** [comment]
You mean receivings are not shown?

**Comment by jekkos** [comment]
I'm doing some further refactor. I would like to keep the search box after all as it comes in handy quite a lot. eg. for creating invoices for a certain customer in the past. My users will be thoroughly disappointed if I make it disappear. If you have objections to this, let me know I'd be happy to discuss further (maybe enable/disable it someway)

Currently I reviewed the following

* search can look for customer name and pos number. I refactored this bit of code and made it cleaner. It's also faster now
* I have corrected a couple of potential sql injection vulns (in this case concatenating posted params without sanitization)
* search would only be active if something is filled in in the search field. In that case a date range is not taken into account
* not really certain if we should create the temp table every time we call the sales controller. I haven't measured performance but currently things seem to work smoothly
* I added back the payment type column in the 'takings' table. Annoying thing is that it wraps over multiple liines which makes the table look bigger, but I'll leave it in there.
* Trying to add a recent jquery ui datepicker now

**Comment by daN4cat** [comment]
No objections for the search box, it might be handy indeed for the invoice use case.
Please take into considerations the changes I made today (cash_only option).

Not sure you have planned that, but when you select one of the filters the summary at the end doesn't update. I guess the ajax part updates just the table not the summary.

**Comment by jekkos** [comment]
yes I noticed that as well. Once you start filtering, the summary will go out of date. I have already done something similar for detailed sales report.

**Comment by daN4cat** [comment]
I just pushed the Print button addition. As said it's a simple window.print() story. That will do for now, maybe later it can be improved.

**Comment by odiea** [comment]
I also downloaded both the gi and the main zip and am getting language file problems

**Comment by daN4cat** [comment]
Yes, but this comes from an early merge...

**Comment by daN4cat** [comment]
I fixed and pushed the change. Not sure how that was introduced, but not the point here.

**Comment by odiea** [comment]
rename the file to salescsv.orig_lang.php

**Comment by daN4cat** [comment]
ok, I'm lost. What's this change?

**Comment by odiea** [comment]
I was able to get the program up and going by changing that file name. All works ok for me . No date picker problems

**Comment by daN4cat** [comment]
Everything is committed to master now.

Thank you very much jekkos for the help and to make this feature far better than I could do.

I close this issue and anything more / else is treated as bug or minor improvement in a different thread.
