### ISSUE TITLE
Two 'line sequence' selector in invoice config & no password in msg config [edited]

### ISSUE THREAD

**Issue by RamkrishnaMondal** [jekkos/opensourcepos#1100]
![screenshot from 2017-01-31 03 21 45](https://cloud.githubusercontent.com/assets/14151032/22443516/1f0b2aa8-e765-11e6-9185-7a35b076a99d.png)

![screenshot from 2017-01-31 03 24 11](https://cloud.githubusercontent.com/assets/14151032/22443521/24c08d3a-e765-11e6-9151-5fb4e4dd3d5a.png)

**Comment by SteveIreland** [comment]
This is resolved in the pull request #1101.  Sorry about that ... I suppose I should change my user profile to  "MergeMangler" or "RandomRebaser" after all of this!

**Comment by RamkrishnaMondal** [comment]
Don't be sorry . You have done a great job. Thank you.

**Comment by daN4cat** [comment]
@SteveIreland you did a great job, no worries. The first time I submitted something to OSPOS I messed up well, @jekkos can confirm.
I preferred to merge things to master to avoid having open PRs with constant rebate issue. Few bugs should be expected and I would say it's business as usual.

**Comment by RamkrishnaMondal** [comment]
Spotted another one 'sms-api password' box in msg config  is not fetching password from db. hence sms not sending.

**Comment by daN4cat** [comment]
@RamkrishnaMondal that's another issue. Let's not mixup things.

**Comment by daN4cat** [comment]
Two line sequence fix is now in master.
