### ISSUE TITLE
The Module Sales, Receivings, Store Config is innaccessible

### ISSUE THREAD

**Issue by Elhy** [jekkos/opensourcepos#1104]
Please, 
someone can help me, I have the error on the capture below when I tried to navigate the following modules
Sales, Receivings, Store Config
![grave](https://cloud.githubusercontent.com/assets/23028792/22455651/ff632c52-e79e-11e6-878a-e1d7466d82db.png)

**Comment by RamkrishnaMondal** [comment]
See #1074

**Comment by Elhy** [comment]
@RamkrishnaMondal   I have already tried all this trick but that still does not work
