### ISSUE TITLE
Item Pics

### ISSUE THREAD

**Issue by odiea** [jekkos/opensourcepos#1108]
So many issues with this pic commit

**Comment by odiea** [comment]
Is ther going to be any fix for this. Place holders constantly show. Slow table loading.
![2017-01-31 19_51_10-](https://cloud.githubusercontent.com/assets/10962177/22493707/fc998f16-e7ee-11e6-9ad6-5189cfd13e8a.png)

**Comment by daN4cat** [comment]
@odiea please use the latest code from master. I remember I fixed that issue.

**Comment by odiea** [comment]
6:05 usa time. I just downloaded the latest Master. My fix is just uncheck the box and don't show avatars in Items.
![2017-02-01 06_04_50-photos](https://cloud.githubusercontent.com/assets/10962177/22507796/6b3ee678-e844-11e6-991c-b954c27f070e.png)

**Comment by odiea** [comment]
After cycling thru all the items about 10 times the placeholder went away.

**Comment by odiea** [comment]
@daN4cat For some reason I had to copy and paste your latest commit. You have an excellent job repairing this commit. No more place holder issues.
