### ISSUE TITLE
Data insertion Issue

### ISSUE THREAD

**Issue by ymscr8912** [jekkos/opensourcepos#1109]
while adding form in Store config.and When i click on submit button data does not insert and update into database .applied with the same logic but it does not shown Error.While debugging i saw that clicking on Submit button it call to body Tag.it would not take any action.Where is the Problem?can you help Me?

**Comment by ymscr8912** [comment]
@odiea @jekkos Help ?

**Comment by odiea** [comment]
Sorry. This is beyond my abilities.

**Comment by daN4cat** [comment]
Have you changed the code?
