### ISSUE TITLE
SMS API password can not be saved

### ISSUE THREAD

**Issue by RamkrishnaMondal** [jekkos/opensourcepos#1110]
### Installation information

Open Source Point Of Sale Version 3.1.0 
### Actual behaviour

SMS API password can not be saved.

### Steps to reproduce the issue

**Comment by daN4cat** [comment]
Make sure mcrypt is enabled in your php installation

**Comment by RamkrishnaMondal** [comment]
v3.0.2 running fine from same localhost.

**Comment by RamkrishnaMondal** [comment]
Tested with a fresh db..... it's a bug.

**Comment by daN4cat** [comment]
@RamkrishnaMondal I tested and the password is saved in my case, of course encrypted.

**Comment by RamkrishnaMondal** [comment]
After watching your comment, i have re-downloaded and installed with a fresh db, it's working. Sorry for wasting your time...... i shall be more careful in future before posting a bug report.

**Comment by daN4cat** [comment]
No worries

**Comment by RamkrishnaMondal** [comment]
Please recheck this issue. Steps to reproduce : 
1. Install latest master and save your uid , pass etc in msg config.
2. Setup your SMS API lib . 
3. Try to send sms.... it's shows unsuccessful.
4. Re-check msg config tab ... no password shown ... field is empty.
5. Check your db msg_pwd field is empty.

**Comment by daN4cat** [comment]
Do you have mcrypt library enabled in PHP?

**Comment by RamkrishnaMondal** [comment]
Yes I have .... v3.0.2 running fine including sms from same htdoc.

**Comment by RamkrishnaMondal** [comment]
I have also tried copying encrypted msg_pwd from 3.0.2 db to 3.1.0 db .... it shows in msg config tab, But as soon as i try to send sms it vanishes from config tab.

**Comment by RamkrishnaMondal** [comment]
This is from my php_info.php:

![screenshot at 2017-02-05 15 18 51](https://cloud.githubusercontent.com/assets/14151032/22625236/a7beea6a-ebb6-11e6-93c2-c1a6503f9108.png)

**Comment by daN4cat** [comment]
Do you have in Sms_lib.php the following:

```
	/*
	 * SMS sending function
	 * Example of use: $response = sendSMS('4477777777', 'My test message');
	 */
	public function sendSMS($phone, $message)
	{
		$username   = $this->CI->config->item('msg_uid');
		$password   = $this->CI->encryption->decrypt($this->CI->config->item('msg_pwd'));
		$originator = $this->CI->config->item('msg_src');
```

**Comment by daN4cat** [comment]
Because I tested again and I don't see how this could not work as I save a password in Store Config, it's in the table under the correct key and after faking a send SMS everything is still there.
So I'm not sure you just have a read of the decrypted password in Sms_lib or you have done something else. I can't help with the "something else".

**Comment by odiea** [comment]
He may be on to something here.
I filled out the form and submitted it. Said ok.
![2017-02-05 06_14_15-wedidit _ powered by ospos 3 1 0](https://cloud.githubusercontent.com/assets/10962177/22626450/a5cc0838-eb6a-11e6-9529-16aef6a06367.png)
I then checked the db and this is what I saw there.
![2017-02-05 06_11_28-localhost _ 127 0 0 1 _ ospos1 _ ospos_app_config _ phpmyadmin 4 5 1 - microsof](https://cloud.githubusercontent.com/assets/10962177/22626452/ba1fd7f6-eb6a-11e6-901f-3f770d08809d.png)
Or am I doing something wrong.

**Comment by daN4cat** [comment]
in application/config/config.php do you have a value written in `$config['encryption_key'] = '';` ?

If not that could be the issue. Please don't copy the value here as that would be your encryption key....

**Comment by daN4cat** [comment]
Also if you have added some silly value in that key then that could be the problem. By default it should be empty as per my comment above.
The key is automatically generated and saved once by OSPOS only if you left it empty.

**Comment by odiea** [comment]
Yes there is a value in it. Should I clear that value then retest to see if it is then saved in the db?

**Comment by RamkrishnaMondal** [comment]
Ah! thanks to both of you. I had nothing in encryption key field in config..... put one and issue gone. But surprisingly up to V3.0.2 sms module was working fine without  encryption key. Btw , can't we have a in-built  auto encryption key generator using the following ?

https://gist.github.com/jeffreybarke/5347572

**Comment by odiea** [comment]
Yes it is saving the info. I forgot I changed to a different db. Was chasing my own tail.

**Comment by RamkrishnaMondal** [comment]
> The key is automatically generated and saved once by OSPOS only if you left it empty.

I think, there lies the  problem..... it is not generating the encryption key.

**Comment by odiea** [comment]
Eventually it would be nice to see in Config the current db in use.

**Comment by RamkrishnaMondal** [comment]
Good Idea! I'll try to put a db config tab in config in my dev repo, so that, one can put dbuser, dbname and dbpass there.

**Comment by daN4cat** [comment]
The CI key generation is broken if mcrypt is not working properly. I still feel you have a problem with that.

**Comment by daN4cat** [comment]
BTW where do you plan to save the db configuration?

**Comment by RamkrishnaMondal** [comment]
> BTW where do you plan to save the db configuration? 

> 

OMG! It's impossible to configure the db from config..... as without a db connection ospos will not run. It can display current db related values though.

> The CI key generation is broken if mcrypt is not working properly. I still feel you have a problem with that. 

> 

But, I have any other encryption related problem, V3.1.0 is using encrypted password for login without issue. With V3.0.2 i don't have any issue at all. If mcrypt is broken, will they work? 

BTW, as ubuntu 16.04 lamp by default comes with php7 and mysql5.7 , i am using bitnami lamp stack with php5 and mysql5.6 ..... if that is the cause. I will test with Xxamp in windows later. What stack are you using for local server?

**Comment by RamkrishnaMondal** [comment]
Or, we have to use sqlite along with mysql just like webzash does. username and password will be on sqlite db... and after login, ospos will bring a db configuration form, taking these data from the form, ospos will create a db with mysql.  Will make things more complex, better stick to current one.

**Comment by odiea** [comment]
I am using the current version of xampp on my local and current Ubuntu Server with maria db installed on a laptop. I also have a vm with current Ubuntu Server using MySQL. Just seeing the current db setup I think would be beneficial for me.

**Comment by daN4cat** [comment]
Ok maybe you found an issue with PHP 7 and MySQL5.7? Please check that because I'm using PHP 5.6 and MySQL 5.6 and do everything is fine.

**Comment by RamkrishnaMondal** [comment]
ok ... I will install lamp on 16.04 then.

**Comment by odiea** [comment]
I copied my current version to the following server. I deleted the key. I went to config and changed the password and the new key showed in config.
![2017-02-05 08_40_29-program manager](https://cloud.githubusercontent.com/assets/10962177/22627384/849a0f2e-eb7f-11e6-914c-d5fae4cdb7ad.png)

**Comment by odiea** [comment]
I did have to change the password a couple of times before it showed in the db. If the password field isn't full of dots the password is not being stored yet.

**Comment by odiea** [comment]
Php 7 with maria db.
Here is what I am finding on a new install of ospos. New db.
configure messages. user-password
The encryption key is filled out in config but the database does not get updated with password.
Go back and reenter the password . then it stores the password.

**Comment by daN4cat** [comment]
Probably something is different in PHP7 with regards to this in `Config.php, private function _check_encryption()`:

```
			$result = FALSE;

			// Verify file permissions
			if(is_writable($config_path))
			{
				// Write the file
				$result = (fwrite($handle, $config) === FALSE) ? FALSE : TRUE;
			}
			
			// Chmod the file
			@chmod($config_path, 0444);
			
			fclose($handle);

			return $result;
```

It might be that the key is indeed successfully written in the file but somehow the fwrite result is FALSE instead of TRUE and therefore it fails the first time. Subsequent times it see the encryption key in the config file and therefore doesn't fail.

We should check the fwrite in php7

**Comment by daN4cat** [comment]
I don't seem to see differences in fwrite between PHP5.6 and PHP7, both return FALSE on error.
The only thing I can think of is change the file permission before opening the file.

@odiea can you change the code from:

```
			// Write the new config.php file
			$handle = fopen($config_path, 'w+');

			// Chmod the file
			@chmod($config_path, 0777);
			
			$result = FALSE;

			// Verify file permissions
			if(is_writable($config_path))
			{
				// Write the file
				$result = (fwrite($handle, $config) === FALSE) ? FALSE : TRUE;
			}
			
			// Chmod the file
			@chmod($config_path, 0444);
			
			fclose($handle);
```

to this please?

```
			// Chmod the file
			@chmod($config_path, 0777);

			// Write the new config.php file
			$handle = fopen($config_path, 'w+');

			$result = FALSE;

			// Verify file permissions
			if(is_writable($config_path))
			{
				// Write the file
				$result = (fwrite($handle, $config) === FALSE) ? FALSE : TRUE;
			}
		
			fclose($handle);

			// Chmod the file
			@chmod($config_path, 0444);
```

and let me know if this works fine with PHP7?

**Comment by odiea** [comment]
I just did the same thing with php 5.6 and it shows the same result.
![2017-02-05 13_13_50-localhost _ 127 0 0 1 _ newmaster _ ospos_app_config _ phpmyadmin 4 5 1 - micro](https://cloud.githubusercontent.com/assets/10962177/22629534/24aad280-eba5-11e6-96d8-c9fa99b0bbd0.png)

**Comment by odiea** [comment]
I tried the fix in php 5.6 and nothing changed as far as the password showing the first time it is entered.

**Comment by daN4cat** [comment]
@odiea can you try the email part and see if you get the same?

**Comment by odiea** [comment]
Email password does not change after encryption key is deleted. You still have to enter the password twice to get it to change

**Comment by odiea** [comment]
Can it just have a generic key installed when the program is first installed?

**Comment by odiea** [comment]
I got the latest code and there seems to be no change. I still have to enter the passwords 2 times if the key has been cleared.

**Comment by daN4cat** [comment]
Yes there was no intention to fix this. I just refactored the code but I need to think about a solution. Well I have one in mind but I would like to understand first why it fails.

**Comment by daN4cat** [comment]
Please check the latest master as this should now be fixed.

**Comment by RamkrishnaMondal** [comment]
Before this fix my passwords are not saving at all, without adding encryption key. It seems to be fixed now.

**Comment by daN4cat** [comment]
Good
