### ISSUE TITLE
List of Items and Takings are not displayed

### ISSUE THREAD

**Issue by Elhy** [jekkos/opensourcepos#1118]
Someone can help me? I have this problem on the list of items and in list of sale (Takings) (see capture attached)

![imp_nw](https://cloud.githubusercontent.com/assets/23028792/22617623/a19e5850-eada-11e6-9461-962a0864f2c4.jpg)
![imp_nw2](https://cloud.githubusercontent.com/assets/23028792/22617624/a1a88f0a-eada-11e6-8f19-ec87b6c71b32.jpg)

**Comment by daN4cat** [comment]
Which version are you testing?

**Comment by daN4cat** [comment]
OK, I see it's 3.0.2.

Have you changed something of the code or is it the standard 3.0.2?
Also try the English version and see if you get the same problem. I just want to exclude any translation issue.

**Comment by Elhy** [comment]
it's the standard 3.0.2.
I did not change anything except the database.php
I also tried the English version but it did not always work.

**Comment by daN4cat** [comment]
Is this a fresh new installation or an upgrade?
Are you using MySQL 5.7 or PHP7 any chance?
