### ISSUE TITLE
Blank graphic bar report

### ISSUE THREAD

**Issue by alponce** [jekkos/opensourcepos#1119]
### Issue / Question / Bug

Before submitting an issue please make sure you remove the first section of the template and you tick (add a x between the square brakets) and agree with all the following check boxes:

- [x] Checked the current issues database and no similar issue was already discussed
- [x] Read the README, WHATS_NEW and UPGRADE
- [x] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php5-gd, php-intl and sockets installed)
- [x] Reporting an issue of an unmodified OSPOS installation
- [x] PHP version is at least 5.5 and not 7.x
- [x] MySQL version is 5.5 or 5.6 and not 5.7
- [] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [x] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [x] Know the name and version of OS, Web server and MySQL and will add to my issue report

### Installation information
Fresh 3.02

### Expected behaviour
See the bar reports like Graphic-> Customer

### Actual behaviour
Blank report

### Steps to reproduce the issue
Using Firefox or Chrome the error can i see is about "TypeError: Chartist.plugins.ctBarLabels is not a function"
![captura de pantalla de 2017-02-04 09-32-08](https://cloud.githubusercontent.com/assets/25548514/22618509/f5e69e9a-eabc-11e6-8cd9-ec520b858c1b.png)

**Comment by daN4cat** [comment]
Just tested and works fine. Please check your installation as it looks like you touched the js to me.

**Comment by alponce** [comment]
Hello THX foro reply all. 
My mistake i was using and old JS 
Now its work THX a lot
