### ISSUE TITLE
Same customer (with the same name) can be entered multiple times

### ISSUE THREAD

**Issue by daN4cat** [jekkos/opensourcepos#112]
There should be at least some simple sanity check to avoid users entering a customer name multiple times. Even a check against same email or phone number would help.

I'm not sure there are reasons to have multiple times the same.

**Comment by jekkos** [comment]
Indeed this is a problem that occurs frequently at our shop as well. However sometimes there genuinely are persons with similar names (but in that case they won't have the same email adress ).

**Comment by daN4cat** [comment]
Indeed, I was just wondering about some simple sanity check and email or phone number should do at least.
You can assign to me if fine with you.

**Comment by jlctmaster** [comment]
Hello @daN4cat , regarding this I wonder why in the information of the customer or supplier, there is no field to register the ID (National Identification Document), Social Security Number, Driver License Number or Passport, a field that identifies person.

This is of great value, for the moment of using the billing system, in my country Venezuela is a mandatory value that must have any invoice.

**Comment by daN4cat** [comment]
@jlctmaster because you don't want to risk your neck in storing that stuff. Considered the security risk and implications if it goes wrong?

**Comment by jlctmaster** [comment]
But at the time of issuing an invoice without that information in my country it is illegal. If the design of the POS allows you to generate an invoice, this should at least be a legal document for the country where it was implemented, it would be great to have configurable attributes such as those of the product but for the invoice and the customer or supplier.

**Comment by daN4cat** [comment]
Maybe you can use Account # for that purpose?

**Comment by jlctmaster** [comment]
Hello, that field is not to save the bank account number of the customer or supplier?

**Comment by daN4cat** [comment]
@jlctmaster free to interpretation I would say :-)
Give a try it's probably already printed in receipts and invoices if filled in. I see like an easier way to have it ready-to-go.

**Comment by daN4cat** [comment]
Done
