### ISSUE TITLE
Item Kit Discount not working

### ISSUE THREAD

**Issue by RamkrishnaMondal** [jekkos/opensourcepos#1126]
### Expected behaviour

It should work.
### Actual behaviour

Whatever Pricing combination I use, it's not working.
### Steps to reproduce the issue

@odiea  @SteveIreland  can you test and confirm ?

**Comment by SteveIreland** [comment]
Yes, I'll check this out tonight to see why it stopped working - the most likely culprit is a mangled merge.

**Comment by odiea** [comment]
The only issue I have with it is If I do not have an item in kit item no discounts are given.

**Comment by SteveIreland** [comment]
Okay, then it might actually be a bug and not a merge error.  I might have failed to test for that scenario since I was focused on Item Kits with an kit item.  I'll have a pull request to fix it tonight.   Thanks!

**Comment by SteveIreland** [comment]
@daN4cat What's the plan for applying this fix?  Is there something you're waiting on me for or are we just waiting for you to free up some time?   No rush ... just wanted to make sure you're not waiting on me for something.

**Comment by daN4cat** [comment]
Is there a PR with this fix?

**Comment by jekkos** [comment]
Fix applied

**Comment by daN4cat** [comment]
Yes, I now see from my laptop. Somehow from the mobile app I couldn't see the PR.

**Comment by daN4cat** [comment]
@odiea please counter check and close if it's all fine.

**Comment by odiea** [comment]
Now no item has to be in Kit Item for the discounts to show. This problem appears to be solved.
