### ISSUE TITLE
Installing on docker directions have some issues.

### ISSUE THREAD

**Issue by thegm90** [jekkos/opensourcepos#1127]
### Installation information

Did you guys' referral link, though I don't know how to get you guys to install as mentioned on the page. Took matters into my own hands, but am having an issues within the read me where it says "Create a new node on DigitalOcean through the Infrastructure > Nodes tab. Fill in a name (ospos) and choose a region near to you. We recommend to choose a node with minimum 1G RAM for the whole stack"

There's no node creation on digital ocean. There is on docker, but when I run the docker install, it has php errors.
![screen shot 2017-02-06 at 11 32 12 am](https://cloud.githubusercontent.com/assets/20656675/22660775/08884964-ec60-11e6-9aed-5157471881ce.png)

**Comment by jekkos** [comment]
You should do the node cluster creaztion in that case

**Comment by thegm90** [comment]
I did create a node, then I made the stack too.
![screen shot 2017-02-06 at 11 36 02 am](https://cloud.githubusercontent.com/assets/20656675/22660917/7bde42c4-ec60-11e6-8010-f15747db6a5d.png)

**Comment by thegm90** [comment]
![screen shot 2017-02-06 at 11 38 03 am](https://cloud.githubusercontent.com/assets/20656675/22660984/bf11cdea-ec60-11e6-8fd2-9994494f00cb.png)
For some reason it doesn't register php.

**Comment by jekkos** [comment]
If the icons is green then your server should be up and running. Try to find the url somewhere hidden in the overview pages of the docker cloud console

**Comment by thegm90** [comment]
Sqlscripts is red is the problem, I've tried re springing it and it won't.

**Comment by jekkos** [comment]
No that doesn't matter. It's a data container that only runs to initialize the mysql container. A little trick I had to do to containerize the initialisation routine

**Comment by thegm90** [comment]
Thanks jekkos! I'll give that a go. Appreciate your knowledge and what you and your team have made. I've gotten it to run easily on the local docker, but want this online for remote access. I'll be making a donation when I get it right!
