### ISSUE TITLE
Add MailChimp integration

### ISSUE THREAD

**Issue by daN4cat** [jekkos/opensourcepos#113]
This feature was something done in a branch of the old PHP-Point-Of-Sale, the original software.
However I never managed to catch up with this at that time and then became obsolete.

It would be really handy to have this feature added. Something to be worked in the future after some basic stuff is done and added to master codeline.

**Comment by jekkos** [comment]
Yes indeed I remember this as well. I'm not certain if this was ever included in a 'free' version? Currently I'm using a custom CI script to do this kind of thing, but I guess that MailChimp offers better delivery rates than one could ever achieve using a self configured VPS.

**Comment by daN4cat** [comment]
Yes, there is still a free version because I merged the work done in GitHub on PHP-Point-Of-Sale before it was then removed. The license under the code was developed was still free, but I'll countercheck,
However that code uses an old version of MailChimp library, we would need a refreshed work. Probably not for a 2.3.3 / 2.4 release but for later.

**Comment by daN4cat** [comment]
Done

**Comment by equinenigeria** [comment]
I need complete guide to using mailchimp integration to send message on ospos. someone please. thank you

**Comment by daN4cat** [comment]
@equinenigeria the integration keeps in sync the customer list with OSPOS as master. It does not add customers to OSPOS from mailchip automatically. No message sending.
