### ISSUE TITLE
Nginx rewrite rule for ospos

### ISSUE THREAD

**Issue by rayhanhd** [jekkos/opensourcepos#1130]
Hello everyone,
I face difficult situation installing ospos in nginx (i tried in apache and it work as expected), is anyone around here could give me the correct nginx rewrite rule?
here's the example of my server block configuration.

        server {
        listen       80;
        server_name  example.com;
        root /usr/local/www/ospos/public;
        index index.php index.html index.htm;

        location / {
                try_files $uri $uri/ /index.php?$query_string;
        }

        error_page      500 502 503 504  /50x.html;
        location = /50x.html {
            root /usr/local/www/nginx-dist;
        }

        location ~ \.php$ {
                try_files $uri =404;
                fastcgi_split_path_info ^(.+\.php)(/.+)$;
                fastcgi_pass unix:/var/run/php-fpm.sock;
                fastcgi_index index.php;
                fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                include fastcgi_params;
        }
    }

**Comment by jekkos** [comment]
Nginx is currently not supported.. I don't really have a lot of experience with it, so can't directly help you out. 

If you find a solution that works then feel free to document it on our wiki.

**Comment by RamkrishnaMondal** [comment]
I believe, this can help:

https://www.nginx.com/blog/converting-apache-to-nginx-rewrite-rules/

**Comment by daN4cat** [comment]
Yes, please let us know even because the performance of nginx is better and on raspberry pi would be a better option.

I would really like to know how it goes.

**Comment by rayhanhd** [comment]
i've tried those link. But the only rule in .htaccess is prevent access to log and anything else.

okay, i'll try harder to find the solution. Thank you,

**Comment by daN4cat** [comment]
I'll check over the weekend and see if I can find a way to help you.

**Comment by daN4cat** [comment]
Check the following:

- https://www.nginx.com/resources/wiki/start/topics/recipes/codeigniter/
- http://www.farinspace.com/codeigniter-nginx-rewrite-rules/
- http://serverfault.com/questions/695521/codeigniter-in-subdirectory-on-nginx-404#695953

**Comment by daN4cat** [comment]
Or even this:

- https://chriskief.com/2013/12/07/configuring-nginx-codeigniter-with-rewrite-rules/

**Comment by daN4cat** [comment]
If you solve it please let us have the nginx (generic) configuration file so we add it to OSPOS master.

**Comment by RamkrishnaMondal** [comment]
Convert .htaccess to ngnix rules online:  http://www.anilcetin.com/

**Comment by RamkrishnaMondal** [comment]
I have created a guide for this in the wiki...... enjoy!

**Comment by daN4cat** [comment]
You mean this: https://github.com/jekkos/opensourcepos/wiki/Local-Deployment-using-LEMP-(Linux,-Nginx,-MariaDB,-PHP7.0-&-Adminer)-on-Ubuntu-16.04

**Comment by RamkrishnaMondal** [comment]
Yes, spent several hours to figure out how to run ospos with LEMP, none of the config files available on internet works out of the box.

**Comment by daN4cat** [comment]
Well done, congrats.
You can now give a try to Raspberry Pi version: https://freevps.us/thread-12733.html
and update the wiki: https://github.com/jekkos/opensourcepos/wiki/Installing-on-Raspberry-PI---Orange-PI-(Headless-OSPOS)

Good for a Sunday afternoon..... :-)

**Comment by daN4cat** [comment]
Maybe @jekkos will even even try to create a Dockers image (Ubuntu 16.04 installation).... who knows.

**Comment by RamkrishnaMondal** [comment]
As I don't have a Raspberry-PI, I can't test it. Your guide with nginx related modifications should work. The `default.conf` file is the key.

**Comment by daN4cat** [comment]
Yep, I've added a link in RPI wiki to your wiki page as the instructions should be pretty similar. Both are debian based so it should work.

I close this as it's solved. Thanks again for the help and I wonder if you noticed any improvement in performance because between PHP7, nginx and MariaDB the combination should be better than an old style LAMP stack.

**Comment by RamkrishnaMondal** [comment]
It's faster than apache+mysql, I have chosen MariaDB not only for speed but also to avoid mysql v5.7 related problems. Please give it a try, at least on a virtual box.

**Comment by jekkos** [comment]
Hmm don't we need latest MySQL fixes to run on the equivalent version of MariaDB as well? Or do they using other settings for the group

@daN4cat good  idea on adding this as an alternative setup, I'm certainly interested will make an issue for adding LEMP stack support.

**Comment by odiea** [comment]
When I was testing different servers it appeared that maria db had no MySQL 5.7 issues. That was why I changed db versions.

**Comment by RamkrishnaMondal** [comment]
I am using v10.x.x of MariaDB which comes with ubuntu 16.04 , have not noticed any issue so far.

**Comment by jekkos** [comment]
Current docker stack is using MariaDb as well. If nginx proves to be faster I might want to change default apache to nginx

**Comment by daN4cat** [comment]
They say that nginx is faster than Apache. Not sure with TravisCI something can be spotted. Anyway, good for the fun at least.

**Comment by daN4cat** [comment]
Some performance comparison Apache vs Nginx on RPI: http://raspberrywebserver.com/raspberrypicluster/comparing-the-performance-of-nginx-and-apache-web-servers.html

**Comment by daN4cat** [comment]
BTW that web page talks of a solution on a cluster of RPI, with a load balancer put on an PC running lubuntu. The web page itself is running off the cluster of RPI with nginx if I got right.

**Comment by RamkrishnaMondal** [comment]
@daN4cat  Time to update 'Server Requirement' under Read Me.

**Comment by daN4cat** [comment]
That's true

**Comment by daN4cat** [comment]
Done

**Comment by RamkrishnaMondal** [comment]
Please check  MariaDB spelling in the READ ME and also add `php-curl `is required to send SMS.

**Comment by daN4cat** [comment]
Fixed

**Comment by RamkrishnaMondal** [comment]
`db_backup `is not working with nginx. Tested with v3.0.2 and v3.1.0 . shows error 500.

**Comment by daN4cat** [comment]
It's a fact of life... no support and all happy.

**Comment by RamkrishnaMondal** [comment]
I found this for you

https://kevindekoninck.com/raspberry-pi-install-nginx-mysql-php/

**Comment by RamkrishnaMondal** [comment]
`backup_db` is actually working with nginx. I have created a new db and it's working.

**Comment by daN4cat** [comment]
Good good

**Comment by RamkrishnaMondal** [comment]
@daN4cat 

Please review this  https://github.com/jekkos/opensourcepos/wiki/Deployment-of-LEMP-on-Raspberry-Pi-3-Model-B

**Comment by daN4cat** [comment]
Looks good well done!
