### ISSUE TITLE
always login

### ISSUE THREAD

**Issue by rminformaticos** [jekkos/opensourcepos#1132]
how can i do? always login when user open new browser session.

(sorry for my bad english im spanish)

**Comment by daN4cat** [comment]
Check the configuration file in config dir. There is a set stating something like 7200. You can set to be infinitive to avoid end of session. I can remember if it's setting to 0 that would do or not. You need to check Code Igniter documentation.

**Comment by rminformaticos** [comment]
in application\config\config.php

set this values:

$config['sess_expiration'] = -1;
$config['sess_time_to_update'] = -1;

and works!

**Comment by daN4cat** [comment]
Good and thanks to feedback the solution here, this would help other people with the same question in the future.
