### ISSUE TITLE
Sales tax by origin, ship to address, etc

### ISSUE THREAD

**Issue by SteveIreland** [jekkos/opensourcepos#1133]
This might be where I actually have to start doing some work on my own fork, but I thought I'd throw this out.

Here in the US the sales tax is not based on the item (although some types of items are tax free), but based on the laws of the individual states - and can be based on the ship to destination, bill to destination, or the point of origin.

Is support for this requirement something that can be added to OSPOS or should I just plan on adding it to my own fork?  The feature will be tax entity based so that I can report city taxes, county taxes, state taxes, etc ... wherever is required.

I hate taxes ... just saying.

**Comment by odiea** [comment]
I would recommend that you just keep it on you own branch.

**Comment by SteveIreland** [comment]
Dang ... being kicked out of the nest already.    Oh well.   :-)

**Comment by odiea** [comment]
No it's not that at all. There are so many new things being work out now that another addition like this might upset some but work out better for others. After all these new updates are worked out you should submit a pull for that later. I think it would be a nice addition mainly for US users.

**Comment by daN4cat** [comment]
We should discuss before close this feature proposals.... I didn't have the time today to read this properly.

**Comment by SteveIreland** [comment]
Okay.  My plan is to add a tax_code to the customer table ... this would be a reference to a tax code table that contains the total tax (the total of all of the associated taxing authority rates) to be charged for a sale.  I would also need to add a table for taxing authority which would contain the tax rate that each taxing authority is demanding.   Then I add a relational table that associates the tax code with the appropriate taxing authorities.

Instead of using the tax rate from the item table I would use the tax rate from the tax code table (which is the sum of the tax rate of all of the taxing authorities involved).  This should be a configuration option as to which to use.

For tax reporting I could still use the sales item taxes table and can break out the tax amount by by taxing authority using the relationship table.

**Comment by kaslak** [comment]
Talking Taxes... I wonder why the program adds taxes - not calculating one tax and then get a new subtotal and calculate the next tax... Is it in the US that you ad different taxes on one Net-subtotal?

If it wasn't that way, one could use TAX-1 for all kind of extra-charges and the TAX-2 for the VAT.

Since the TAX input is per Item, it seems not very rational to me. I either need TAX-1 OR TAX-2. I'm not sure whether this is a country specific issue.

I can only tell, that whatever you add before VAT has to be in the sub-total ... to VAT it then.

BTW I hate taxes too ... and for every country/state different rules ... uh, nightmare!

**Comment by SteveIreland** [comment]
In the US at a distributor level it can touch a lot of the complexities you mention.  For example we have internal taxes for for cigarettes that I guess the government wants to collect taxes on but not make it so obvious to the buyer.  I call those behavior modification taxes.  I'm somewhat familiar with VAT taxes and that in some countries the tax calculation can be cascaded.  Fortunately we don't deal with VAT taxes in the States (yet) so except for internal taxes which are only dealt with by the distributor and not the retailer then OSPOS would only need to deal with a simple sales tax charged by the taxing authorities that are claiming jurisdiction over the sale.

**Comment by kaslak** [comment]
I see, interesting... so you do not have VAT in the US?

**Comment by daN4cat** [comment]
I would love to have a world with just one tax, OSPOS tax calculation would be far simpler. I still have to check what the latest issue is and it requires a lot of inspiration because the rounding issues are all about this 2 tax system for the US. And I don't live in the US!!

**Comment by daN4cat** [comment]
Maybe Mr Trump can spend a bit of more productive time in shooting a: we move to just one Tax. Bingo, OSPOS developers happy!

**Comment by SteveIreland** [comment]
One can only hope!  :-)

**Comment by SteveIreland** [comment]
Interesting about what is there being intended for the US, because it is severely limited.  It restricts the company to sell in only one state and would allow for at most either an additional city tax or county tax.

**Comment by odiea** [comment]
Until recently this has been a fairly basic point of sale. Previous developers would add as needed.

**Comment by SteveIreland** [comment]
And that might be the best way to approach this.  I was looking at the city of Boulder, Colorado as an example of the nastiness of some taxing schemes.

https://bouldercolorado.gov/finance/tax-rates-3

**Comment by odiea** [comment]
Lucky us. Here in Fort Collins Co we have state-county-city and probably more on the way.

**Comment by SteveIreland** [comment]
I am about to start on a feature add for my use.  I've temporarily documented on the Wiki here so that the deciders can take a closer look at what I'm about to do and decide if it's something that would be useful here.  If the decision is "no" then I'll delete the Wiki page.   Just let me know.   Thanks.

https://github.com/jekkos/opensourcepos/wiki/Proposed:-Sales-Tax-by-Customer

**Comment by odiea** [comment]
I assume this would be an App config item that would not interfere with the current tax settings?

**Comment by SteveIreland** [comment]
That's my new immutable rule for any changes. :-)

**Comment by SteveIreland** [comment]
I've rewritten the new tax module a couple of times as I assimilate various types of taxing requirements. The requirement to "not interfere with current tax settings" is going to be a challenge because the current `sale_items_taxes` table is inadequate for for reporting taxes in many state scenarios.  It looks like when the sales tax module is turned on then it would, by necessity, replace the existing tax reporting.  

It will be designed so that when it is enabled it will mirror the old configuration and behavior if VAT taxes are all that's needed but tax sales history will need to come from a different table, currently called `sale_taxes` that will capture both item based taxing (VAT) and customer based taxing (Sales/Use) by item tax category. 

Question:  Do VAT taxes ever use the second tax field or was that an accommodation to provide limited support for sales tax?

**Comment by kaslak** [comment]
Germany für instance uses 7% and 19% for VAT

On Mon Feb 27 14:41:46 2017 GMT+0100, Steve Ireland wrote:
> I've rewritten the new tax module a couple of times as I assimilate various types of taxing requirements. The requirement to "not interfere with current tax settings" is going to be a challenge because the current `sale_items_taxes` table is inadequate for for reporting taxes in many state scenarios.  It looks like when the sales tax module is turned on then it would, by necessity, replace the existing tax reporting.  
> 
> It will be designed so that when it is enabled it will mirror the old configuration and behavior if VAT taxes are all that's needed but tax sales history will need to come from a different table, currently called `sale_taxes` that will capture both item based taxing (VAT) and customer based taxing (Sales/Use) by item tax category. 
> 
> Question:  Do VAT taxes ever use the second tax field or was that an accommodation to provide limited support for sales tax?
> 
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/jekkos/opensourcepos/issues/1133#issuecomment-28272252

-- 
Enjoy! ;) ray / goodking

**Comment by SteveIreland** [comment]
@kaslak thanks for the feedback.  From an earlier post I also recall that you also needed the taxes to cascade, so  I'll incorporate that requirement in this feature.  Sales/Use taxes in the US are additive but I don't believe that is always the same for cigarette taxes which I believe are the US equivalent of a VAT tax.  Retailers are not required to deal with those taxes ... only distributors.

**Comment by daN4cat** [comment]
If you need to rework a generic model we need to list the use cases indeed.
If we need to change for the better let's do that through a DB migration path leveraging an upgrade script.

**Comment by daN4cat** [comment]
However I assume this will be 3.2.0 so in the meantime I'll try to fix what we have for 3.1.0.

**Comment by SteveIreland** [comment]
@daN4cat when do you expect to have a "final" for 3.1.0?  I am in a rush for this change and hope to have it 98% done by the end of this coming weekend (it will at least be functional for my client).  If you want to delay a pull request for it until 3.1.0 is published that will be fine.

**Comment by daN4cat** [comment]
No rush for a 3.1.0 if you are close to deliver it.
But if you are reworking the whole story it does not make sense for me to work more on fixing the corner cases.

Are you building the new logic on top of the models for sale and reporting I changed yesterday?

Please clarify soon because I save my time working on other topics.

**Comment by daN4cat** [comment]
Please also consider the case of tax included that I sense you want to define VAT like it's called in the UK.

**Comment by SteveIreland** [comment]
I will submit the pull request rebased on based on whatever you have merged.  I'm holding off rebasing it until you have assimilated the dining table feature.  Good luck with that!

**Comment by daN4cat** [comment]
@SteveIreland when reworking this taxation story you need to be careful that reports and takings are using the tax calculation leveraging MySQL functions, but sale register, receipt and invoices are using Sale_lib functions and therefore PHP calculations. See #1163 for more, but I fixed a rounding & precision story in Sale_lib `get_taxes()` function.

**Comment by daN4cat** [comment]
The ideal solution would be to use one approach.

**Comment by SteveIreland** [comment]
Yes, I've been closely following your trials and tribulations on the other issue discussions.  I will certainly target one approach.

**Comment by SteveIreland** [comment]
@odiea Do you use more than the first sales tax  value in  your environment?  I'm trying to think about what's required for migration.  If you have any thoughts it would be appreciated.

**Comment by odiea** [comment]
Here my wife just uses the Combined sales tax then breaks it down when tax time comes.

**Comment by meadlin** [comment]
@odiea What happens when each of the the brake down rounds up, but the combined was not enough to cover the rounded totals? That's the issue I had here in Thornton, CO with the state/county/CD/RTD and city.

**Comment by SteveIreland** [comment]
@meadlin The new sales tax system is intended to address the rounding issue that you bring up.  You DO have a worse case scenario which has now become my test case.  The only thing it doesn't test is having a 3 decimal tax percent - but I can tweak it for that.   :-)

**Comment by SteveIreland** [comment]
I would have guessed that OSPOS was a good fit for a thrift store.  I wonder what features are missing?

**Comment by odiea** [comment]
First. Items entry is not acceptable. What we needed was a separate item entry screen with barcoding. Seeing all the daily entries in Items was too much activity for the average Inputter.
Categories with subcategories where label and tag colors are set to that category.
Default Categories and Label or tag colors for the items.
Tag colors needed to be put on sale for a day or 2 or maybe a week with a % off. Set by the manager.

**Comment by meadlin** [comment]
@SteveIreland So far all of my tax rates are 2 decimal, so the 3 will work for me at least.

**Comment by meadlin** [comment]
Not to get too far off topic, but having non-quantified items (services) would be a nice feature too, unless I missed something and it's already there. As it is now I just added the item with a quantity of 1M to not have to worry about updating it.

**Comment by odiea** [comment]
I believe that was covered with the Non Stock Item.

**Comment by meadlin** [comment]
Ok, I was thinking that Non stock was more supposed to be something like direct ship items, but makes a little more sense in a service point view.

**Comment by SteveIreland** [comment]
Correct.  Non-stock items can handle both, but I would think there are additional requirements for direct shipping that aren't yet supported by OSPOS.  And in most (not all) states you'll want to assign service items to a an item tax category that overrides the standard sales tax rate to zero.

**Comment by meadlin** [comment]
There probably are additional requirements, it was just where my mind went when I saw the checkbox. And yea, all of my services are non-taxable, but there are a few categories of services that are taxable.

**Comment by daN4cat** [comment]
I'm aware the focus of this discussion is the US tax breaks down model, but just to reinforce the requirement from the other side of the pond any tax model change needs to work also with the VAT system where sale prices are tax included and the tax is calculated in an inverted way.
So the new tax model should be capable to have two way of working with decimal up to 3 (Canada uses it) and be incremental with up to 3 tax levels (US/CO case).

**Comment by SteveIreland** [comment]
:thumbsup:

**Comment by daN4cat** [comment]
@SteveIreland I read it like "it's all done, no worries dude" 😊

**Comment by daN4cat** [comment]
Of course saved the SQL upgrade script 😂

**Comment by SteveIreland** [comment]
I was pushing to get a pull release out this weekend for this, but the introduction of the rewards changes will require that I rebase it before submitting a pull request for it.  That's my excuse, but I actually could use a bit more testing time.  It comes along with significant changes to the database (adding 4 new tables and changes 4 more) so I'd like to at least feel like I've done everything I could do to insure that I don't break anything.

**Comment by daN4cat** [comment]
OK, you may want to wait for two fixes to Tables and Reward as I spotted a couple of problems.

Please check my other comments so we close what needs to be closed.

**Comment by SteveIreland** [comment]
This change now includes the fix to report the taxes correctly when the same item is included two or more times on the same sale (a.k.a. serialized).

**Comment by SteveIreland** [comment]
I recently discovered that there is at least one country that requires support for a combination of VAT tax and sales/use tax.  However, OSPOS reporting doesn't support that.

I'm thinking that needs to change, but I also don't believe there is a big demand for it.  Does anyone have any thoughts about this?

**Comment by daN4cat** [comment]
Nobody ever asked for that. I would stick to what we have at the moment and wait.
I prefer to start testing the fix sooner than later as it might take a while to prove it all right in all cases.

And thanks a lot for the forthcoming  contribution

**Comment by daN4cat** [comment]
@SteveIreland you went silent, testing the taxation stuff?

**Comment by kaslak** [comment]
Sorry for that. 
Just busy with other stuff.

Will look into it again as soso as my mind is free :)

On Thu Mar 16 22:54:25 2017 GMT+0100, FrancescoUK wrote:
> @SteveIreland you went silent, testing the taxation stuff?
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/jekkos/opensourcepos/issues/1133#issuecomment-28720276

-- 
Enjoy! ;) ray / goodking

**Comment by SteveIreland** [comment]
@daN4cat I was testing and then lost power for a few days due to an ice storm than ran through the area.  That essentially shut me down for this week because of needing to play catch up with the job that pays the bills.  Anyway, I'm close and will go ahead a submit a pull request this coming weekend for it.  If you can then go ahead and merge it I promise to fix whatever issues anyone reports.  :-)

**Comment by daN4cat** [comment]
@SteveIreland I didn't realise you were hit by the ice storm, so no worries and focus on your job first.
When you have time with no hurry look into the tax module.

**Comment by daN4cat** [comment]
@odiea @meadlin I don't have more time today to test, but could you please check the reports are working fine now with regards to taxes?
I know there are many test scenarios to go through....

**Comment by daN4cat** [comment]
All, we need to test this tax functionality as it's the last part before we can deliver 3.1.0 outside a couple of last bug fixes.
Let's put an effort as many complained about this functionality not be up to expectation and we are almost there.

**Comment by meadlin** [comment]
Sorry, was recovering from surgery. I pulled the latest and tried my test case today, and the reports are still incorrect. Was there a DB change as well? or just code?

**Comment by daN4cat** [comment]
DB changed too. You need to run migrate. Make sure it's enabled to admin as you need to see an icon in the main menu in order to access it.

**Comment by meadlin** [comment]
made the DB change but it didn't correct the reports. Both the detailed and summary reports are rounding down.

**Comment by daN4cat** [comment]
@SteveIreland comments?

**Comment by meadlin** [comment]
My setup/test is pretty simple: 2 tax rates (4.75% and 3.75%) and the sale of a single item at $450.00
The sale/receipt is correct in showing $38.26 in tax, but the taxings/detailed/summary reports all show 38.25 in tax.

**Comment by SteveIreland** [comment]
I apologize for the delay in returning to this.  Unfortunately I had to put all of my attention on adding support for work orders to OSPOS ... this is critical to their operations - I simply adapted quotes for this purpose.

I should be able to refocus on taxes this weekend. 

@meadlin Do you have your tax decimals set to 3?  That should result in the tax amounts at the `sales_item_taxes` being stored at the necessary level.  I think the reports at the item level are rounding to two decimal positions at the inappropriate time, but I haven't yet been able to address the reports yet (other than the tax report but I think that my changes were reverted - I just haven't had the time to return to it to take a closer look to determine why.)

**Comment by meadlin** [comment]
@SteveIreland Yes the tax decimals is set to 3.

**Comment by daN4cat** [comment]
@SteveIreland any progress on the tax issue? We should get to an end of this story.

**Comment by SteveIreland** [comment]
Please believe me, there is no one  that wants to get to the end of this story than me!!!

I've been dealing with one crisis after another for the last three weeks. Although the latest crisis isn't resolved yet I am going to put some more time in to it his afternoon.

**Comment by daN4cat** [comment]
@meadlin could you please test with the latest code in master and see if the fixes I made to the reports are working for you?

**Comment by daN4cat** [comment]
There is still an issue between detail sale reports and summary sale reports when the prices are half pence (penny). One side shows a cumulative +1p the other side not.
It's a neverending story.... I will need to relook again at this approximation story

**Comment by daN4cat** [comment]
I believe I fixed this time for the Tax included cases. Sale detailed and summary and receipts are showing all the same correct amounts.

Now the testing is with the US tax system on your side guys.

**Comment by daN4cat** [comment]
@meadlin do you mind to retest with the latest code from master and let me know if you still have the same issue?

**Comment by meadlin** [comment]
:( Just did a pull. Sale/receipt look good. Summary, detailed and takings are all off by the penny. Currently on SHA 3f73e449f0a2650274cbc857d2d7be4e4db745c0

**Comment by daN4cat** [comment]
@meadlin is that the latest latest?

**Comment by odiea** [comment]
I do not appear to be getting his issue after the latest pull. All the Reports appear to be the same amounts.
![2017-07-03 13_47_15-wedidit _ powered by ospos 3 1 0](https://user-images.githubusercontent.com/10962177/27806738-8a528b28-5ff9-11e7-811b-3524c879de5d.png)
![2017-07-03 13_55_00-wedidit _ powered by ospos 3 1 0](https://user-images.githubusercontent.com/10962177/27806740-8cf0144a-5ff9-11e7-8795-fb48af62fcdb.png)

**Comment by daN4cat** [comment]
Good, it could really be a corner case. But I'll try other amounts still with VAT included. If you could test others scenarios with multiple taxes US cases that would help.

**Comment by odiea** [comment]
I had no issues with a single tax on the amount showing differently in any of the Reports either.

**Comment by odiea** [comment]
The only issue I have found so far with Reports is Payment Summary Report . The Selection of teh returns filter does not change the report to show only Returns

**Comment by meadlin** [comment]
![detailedreport](https://user-images.githubusercontent.com/22114210/27807847-d5d75bbc-6000-11e7-9e28-9f78f0fe27fb.png)
![register](https://user-images.githubusercontent.com/22114210/27807850-d5d96038-6000-11e7-8259-1f9aebdd4213.png)
![salesreciept](https://user-images.githubusercontent.com/22114210/27807849-d5d8ca1a-6000-11e7-9fb8-24590fd00458.png)
![summaryreport](https://user-images.githubusercontent.com/22114210/27807848-d5d74b86-6000-11e7-969e-d730ae311365.png)
![takings](https://user-images.githubusercontent.com/22114210/27807846-d5d44f9e-6000-11e7-9a77-8e3a266b56c2.png)

**Comment by daN4cat** [comment]
@odiea I fixed the payment summary report missing return and location filter functionality

**Comment by daN4cat** [comment]
@meadlin how many decimals have you set in the tax (in StoreConfig)?

**Comment by daN4cat** [comment]
@meadlin I tested exactly your scenario using 2 decimals for totals and taxes and works fine with me. The totals are correct in details, summary, takings and receipt.

**Comment by daN4cat** [comment]
The problem appears only if you set to 3 decimals for the tax

**Comment by daN4cat** [comment]
But the mistake seems to be with the sale register and receipt. Probably they should show the 3 decimals for the taxes.

However, to be honest, I don't have any need for this 3 or 4 tax decimals. @SteveIreland if you want to look into that as far as I'm concerned reports are fine and consistent now and with 2 tax decimals all works fine Tax included and not.

**Comment by meadlin** [comment]
Sadly, due to a general information letter from my state, I believe I need 3 decimal tax. It appears I'm required to keep non-rounded tax to the 10th of a cent, on books, then round come tax filing time

**Comment by SteveIreland** [comment]
Open source work is frustrating.  If I could afford to quit and work full time on OSPOS I would.  However, I can't so I shall stay frustrated.  

@meadlin The reporting system isn't modeled to support your requirements so I'm pretty sure there is always going to be a rounding issue when taxes are reported at an item level (as opposed to how they are collected in the real world) - especially when the decimal positions involve a 3 decimal tax rate.

If I"m correct you are not planning on converting to the new Sales tax system because you feel that the taxes for each of your tax jurisdictions need to be computed on each invoice.  However, I think that the rates for the individual jurisdictions can be added up and that single tax rate applied.  Then it simply becomes a back office task to break down the tax collected by individual tax jurisdiction and reported with allowed rounding.  However, I've only read the general guidelines for your location and haven't found anything more specific for your area so I cannot state that with 100% confidence ... it's just what seems to be the generally allowed practice. 

Fortunately (or unfortunately) my client is based in Maryland which only has three tax rates and one state tax jurisdiction so he isn't pushing me in the area of sales tax development (at least not at the moment).  So I haven't been pushed to work on the jurisdictional reporting.

**Comment by meadlin** [comment]
Sadly, closed source work can be just as frustrating...

@SteveIreland I understand there will always be a rounding issue, I'm just hoping to be able to control the cutoff point for the rounding.

I technically have 5 tax rates, that combine down to two. These two taxes go to two different collection entities, so they cannot be combined into one, as each has their own rounding requirements. If my city wasn't a "home rule" city, I could combine all five jurisdictions into a single tax rate and all our lives would be easier. :)

The issue with the back office task, is that when collecting on a combined tax, the individually rounded taxes may add up to be more than the tax collected, with a higher degree of probability on larger purchases. Then I'd have to take profit to pay the under-collected taxes.

**Comment by daN4cat** [comment]
I can see if I find the time to print the taxes with the correctly selected decimals as at the moment it's cut to 2. However I cannot guarantee it will work fine.
Unfortunately this area of work is really time consuming and I can't find anymore all the time required. It's 2 years that I work on the complete overhaul of OSPOS and strange enough I didn't manage to implement all it's needed to get my wife shop switch to the new version. That's how productive those 3 years have been for me, but I'm not frustrated :-)

**Comment by meadlin** [comment]
Totally understandable, life comes first.

**Comment by daN4cat** [comment]
but @meadlin I will make an effort, at least one shot

**Comment by meadlin** [comment]
@daN4cat Nothing else, point me in the right direction in the code and maybe I can help out. I just gotta get the thumbs up from work before I can really do anything.

**Comment by daN4cat** [comment]
@meadlin it's not so trivial as putting your hands on this tax story will be one of the most complicated parts.
I attempted to extend the tax visualisation to 3 decimals, including touching the rounding in tax_lib but I get other approximation errors.
I can't find now the time to really start root causing that as probes into new code @SteveIreland developed and not sure I want to touch instead of him.
This is how far I can go.

**Comment by daN4cat** [comment]
@meadlin I anyway submitted the code to visualise the tax according to the set decimals, not like it used to be.
However I didn't touch the code that does the tax calculation to set the tax value to the selected decimals as that will skew the tax rounding and introduce errors that I don't have time to fix.

So this change is not the complete story but it's a stepping stone in case you or @SteveIreland wants to work on getting tax values correct with 3 decimals.

**Comment by daN4cat** [comment]
As far as I am concerned this can be closed and any additional work for the 3 tax decimals should go under a different issue. Please create it.
