### ISSUE TITLE
#Question

### ISSUE THREAD

**Issue by bayunuraji** [jekkos/opensourcepos#1135]
I use v3.0.1 than try to change to 3.1.0 but the problem doesn't solve
When I do transaction the payment always become minus ( Rp.1000 => -Rp.1000) anyone can help me with this? do I make mistake on setting up something?

**Comment by odiea** [comment]
If you are referring to the receipt Yes it is a negative number. The Amount due is a positive number then the Amount tendered is a negative number.

**Comment by bayunuraji** [comment]
thanks for the explaination @odiea is there any guide for making transaction with this application? how to make the transaction, because after I put number on amount tendered than I klik add payment it's going to another page, payment total are the number I input on the amount tendered, amount due "0" , I can't do anything on the row after it (payment type and amount tendered are locked, than when I click "Complete" going to the receipt and finish transaction.
than when I open the report the problem is I can't see the  profit because it's look like the transaction haven't payed. 
is there anything I should do with this to fixed? I'm sorry if my questions is stupid, because I'm new on this application and I know nothing about programing. thanks

**Comment by bayunuraji** [comment]
Okay the problem is solved, it's happen because I didn't allow tax on customer data... thanks...
