### ISSUE TITLE
adding custom field to sales register table

### ISSUE THREAD

**Issue by bill-goldberg** [jekkos/opensourcepos#1137]
### IMPORTANT IMPORTANT IMPORTANT

Chose what you want to report: New Feature or Bug.
If you remove the template when submitting a Bug your issue will be closed as we cannot help without basic information.

### New Feature / Enhacement

For New Features or Enhacements please remove all the template text and clearly write your proposal.
It's important to state whether you expect the community to implement it or you will contribute the work.
Please bear in mind that we will implement new features only on the current code, there is no support for old versions.

### Issue / Question / Bug

Before submitting an issue please make sure you remove the first section of the template and you tick (add a x between the square brakets) and agree with all the following check boxes:

- [x] Checked the current issues database and no similar issue was already discussed
- [x] Read the README, WHATS_NEW and UPGRADE
- [x] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php5-gd, php-intl and sockets installed)
- [x] Reporting an issue of an unmodified OSPOS installation
- [x] PHP version is at least 5.5 and not 7.x
- [x] MySQL version is 5.5 or 5.6 and not 5.7
- [x] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [x] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [x] Know the name and version of OS, Web server and MySQL and will add to my issue report

### Installation information
Windows 10 x64
Chrome v55
wamp 2.5 x64
apache 2.4
php 5.5
MySQL 5.6

### Steps to reproduce the issue

**Comment by bill-goldberg** [comment]
I have used a custom field as expiry date and i also added it to items module and i tried to add it in sales register but not able to do it .. Can anybody help me

**Comment by bill-goldberg** [comment]
![002](https://cloud.githubusercontent.com/assets/23611136/22853923/271df2c6-f088-11e6-8175-13ba85b220ea.png)
![001](https://cloud.githubusercontent.com/assets/23611136/22853924/271f888e-f088-11e6-958e-cd1d30bb7ec1.png)

**Comment by daN4cat** [comment]
@bill-goldberg you need to look into:

1. libraries/Sale_lib.php (check add_item function for instance, but you need to understand all the xxx_item functions)
2. check sales controller (check functions like _load_sale_data and _reload
3. then of course add it to the view views/register.php (check section  ), besides the header there is a foreach loop that goes through the item rows)

You also need to consider things like receipts and invoices, emails too if required.
Quite a bit of work but a good exercise to get used to the software. If you manage to do all right you are a qualified OSPOS developer after this :-)

**Comment by daN4cat** [comment]
If you wonder: why is it so complicated? Well I agree with you, this is legacy code that we are bit a bit improving and I would prefer to have a better OO design and less touching many things. But it is what it is.

**Comment by bill-goldberg** [comment]
Thank you for your guidance, I will try my best...

**Comment by odiea** [comment]
Instead of adding a new language line I used the following for the Table header. Of course change the custom field number to the 1 you are using.
$this->config->item('custom2_name')

**Comment by SteveIreland** [comment]
Just out of curiosity - what is the purpose of the sales expiration date.  Is this industry specific or is it related  to where you are quoting someone a price and if they don't confirm the sale by that date then the sale is lost.  I ask because I'm adding a quote feature and hadn't considered a "quote expires by date".  But this gives me something consider adding.

**Comment by jekkos** [comment]
See #68

**Comment by jekkos** [comment]
I wonder how quick it would be to generate an REST API using Spring Roo upon the existing database model..

**Comment by SteveIreland** [comment]
Aaah ... seasonal stock.   Thanks.

**Comment by daN4cat** [comment]
BTW @bill-goldberg be prepared that soon or later that work will need to go on your side.
The custom fields will be replaced with what @jekkos pointed earlier, which is #68

**Comment by RamkrishnaMondal** [comment]
@daN4cat @jekkos  I'll request to keep at least 2/3 custom fields even after proposed changes by jekkos, for future customisation.

**Comment by jekkos** [comment]
There will be a migration path ready if you have custom fields in use

**Comment by tenkodoy** [comment]
@bill-goldberg. Please can you give me a step by step instruction on how you were able to let the custom field (in this case expiry date) to show up in Items Column

**Comment by tenkodoy** [comment]
@bill-goldberg  how did you add the expiry dates to the custom fields.
