### ISSUE TITLE
Add better Test Automation / CI support

### ISSUE THREAD

**Issue by daN4cat** [jekkos/opensourcepos#114]
GitHub has a CI (Continuous Integration) support via Travis.

We should build some test automation for a CI story and spot issues / regression quickly.

As Jekkos suggested: leverage selenium / phantomjs setup on travis

**Comment by jekkos** [comment]
Currently there's two tests present for the whole application. This setup uses the node package manager (npm) with selenium webdriver, run from a grunt task.

Current tests include
* One that checks whether a user can login to the application (which works)
* One that checks a giftcard numbering issue (this one fails most of the time)

**Comment by jekkos** [comment]
CI setup has been improved using docker. Now it's a matter of adding some extra test to increase coverage for the project. This progress can be tracked in #305

**Comment by daN4cat** [comment]
Good job, well done!
