### ISSUE TITLE
Financial year selection in config

### ISSUE THREAD

**Issue by RamkrishnaMondal** [jekkos/opensourcepos#1141]
### New Feature / Enhacement

In some countries **financial year**  is different from **calender year**. For example in India it's April 1st to March 31st,  for taxation and other official purpose. 

Can somebody add a **financial year** selector in the config-locale, so that **date-selector** will stick to that ?

**Comment by daN4cat** [comment]
Makes sense.
The best solution would be to make this location / language based. I would need to check if there is a way to automatically do that.

**Comment by SteveIreland** [comment]
In the US some companies work off of what is called a fiscal year which has similar requirements.  So if you don't limit it to a particular language then it might serve additional purposes.  If you go here though, you might want to consider introducing fiscal periods and which would behave similar to monthly periods but point to a different start and end calendar dates.  I don't need it yet, but I thought I'd mention it,

**Comment by daN4cat** [comment]
Yep locale not language, that was a mistake.

**Comment by daN4cat** [comment]
PHP locale support doesn't provide such view of fiscal (or financial) year. I guess the right way would be to add a config item to state the starting day of the financial year so it's fully configurable.

Reference: https://en.wikipedia.org/wiki/Fiscal_year

**Comment by daN4cat** [comment]
This is now implemented in a simple form: financial year start dates are 1st of any month.
They should cover all the cases.

**Comment by daN4cat** [comment]
@RamkrishnaMondal please test, if fine let's close.

@jekkos the Weblate translations need a sync otherwise 3.1.0 will not be fine

**Comment by RamkrishnaMondal** [comment]
Wow! This is perfectly implemented. Only one humble suggestion, if we change 'This Year' & 'Last Year' to 'This Calendar Year' & 'Last Calendar Year' respectively, will eliminate any possible confusion. 
![screenshot from 2017-04-18 23 35 37](https://cloud.githubusercontent.com/assets/14151032/25145857/c9c6ce22-248f-11e7-9244-7866a7698ce6.png)

**Comment by daN4cat** [comment]
@RamkrishnaMondal go to Weblate and edit the English translation. Next round of merges will bring that in.

**Comment by jekkos** [comment]
@daN4cat for the fiscal months there are some translated strings in CI already, we can easily reuse those

**Comment by daN4cat** [comment]
Not that straight forward. In the uk you write 1st of January, but in other languages you don't write like that. It needs a full translation not a composition story I'm afraid.
