### ISSUE TITLE
Barcode Not generating

### ISSUE THREAD

**Issue by innovaerp** [jekkos/opensourcepos#1143]
Hi
Recently we have upgraded php version in our server, for which barcode generate is not working and showing blank. can you please suggest what functions i need to enable to do barcode generation smoothly as like previous time

thanks

**Comment by RamkrishnaMondal** [comment]
v3.0.2 or higher works fine with php 7.0. Which version of OSPOS are you using ?

**Comment by innovaerp** [comment]
Php 5.6.30 upgraded

**Comment by RamkrishnaMondal** [comment]
OSPOS version Please! 
(আরে ভাই, OSPOS কত ভার্সন ব্যাবহার করছেন সেটা বলুন ! )

**Comment by innovaerp** [comment]
OSPOS version 3.0.0

<http://www.softbd.com>

Support Desk / Soft Tech Innovation Ltd.
8801711-272324 / info@softbd.com

Soft Tech Innovation Ltd. *Office*: 880-1611-272324
Sector:14, Road:15, House:92, Uttara, Dhaka. 1230
http://www.softbd.com
*Business Service Wings*: *MUTHOFUN <http://www.muthofun.com/> |  aamarPay
<http://www.aamarpay.com/> | eBiponon <http://www.ebiponon.com/>*

[image: Facebook] <http://www.facebook.com/ishtiaque.sarwar> [image:
Twitter] <http://www.twitter.com/ishtiaquesarwar> [image: Google Plus]
<https://plus.google.com/116320436752203524696> [image: Linkedin]
<http://bd.linkedin.com/pub/a-m-ishtiaque-sarwar/18/32a/b13/> [image: Skype]
<http://htmlsig.com/softbd>

This e-mail message may contain confidential or legally privileged
information and is intended only for the use of the intended recipient(s).
Any unauthorized disclosure, dissemination, distribution, copying or the
taking of any action in reliance on the information herein is prohibited.
E-mails are not secure and cannot be guaranteed to be error free as they
can be intercepted, amended, or contain viruses. Anyone who communicates
with us by e-mail is deemed to have accepted these risks. Company Name is
not responsible for errors or omissions in this message and denies any
responsibility for any damage arising from the use of e-mail. Any opinion
and other statement contained in this message and any attachment are solely
those of the author and do not necessarily represent those of the company.

On Thu, Feb 16, 2017 at 10:06 PM, RamkrishnaMondal <notifications@github.com

**Comment by innovaerp** [comment]
I have resolved the issue by installing GD library in php

<http://www.softbd.com>

Support Desk / Soft Tech Innovation Ltd.
8801711-272324 / info@softbd.com

Soft Tech Innovation Ltd. *Office*: 880-1611-272324
Sector:14, Road:15, House:92, Uttara, Dhaka. 1230
http://www.softbd.com
*Business Service Wings*: *MUTHOFUN <http://www.muthofun.com/> |  aamarPay
<http://www.aamarpay.com/> | eBiponon <http://www.ebiponon.com/>*

[image: Facebook] <http://www.facebook.com/ishtiaque.sarwar> [image:
Twitter] <http://www.twitter.com/ishtiaquesarwar> [image: Google Plus]
<https://plus.google.com/116320436752203524696> [image: Linkedin]
<http://bd.linkedin.com/pub/a-m-ishtiaque-sarwar/18/32a/b13/> [image: Skype]
<http://htmlsig.com/softbd>

This e-mail message may contain confidential or legally privileged
information and is intended only for the use of the intended recipient(s).
Any unauthorized disclosure, dissemination, distribution, copying or the
taking of any action in reliance on the information herein is prohibited.
E-mails are not secure and cannot be guaranteed to be error free as they
can be intercepted, amended, or contain viruses. Anyone who communicates
with us by e-mail is deemed to have accepted these risks. Company Name is
not responsible for errors or omissions in this message and denies any
responsibility for any damage arising from the use of e-mail. Any opinion
and other statement contained in this message and any attachment are solely
those of the author and do not necessarily represent those of the company.

**Comment by daN4cat** [comment]
That's why there is an issue report template but people that ignore it get issues...
