### ISSUE TITLE
Autocomplete not working

### ISSUE THREAD

**Issue by ashaikho** [jekkos/opensourcepos#1144]
### Issue / Question / Bug

Before submitting an issue please make sure you remove the first section of the template and you tick (add a x between the square brakets) and agree with all the following check boxes:

- [x] Checked the current issues database and no similar issue was already discussed
- [x] Read the README, WHATS_NEW and UPGRADE
- [x] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php5-gd, php-intl and sockets installed)
- [x] Reporting an issue of an unmodified OSPOS installation
- [x] PHP version is at least 5.5 and not 7.x
- [x] MySQL version is 5.5 or 5.6 and not 5.7
- [] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [x] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [x] Know the name and version of OS, Web server and MySQL and will add to my issue report

### Installation information
OSPOS v 3.0.2 - 4f5ad57
Apache
Window 7
MySQL 5.6

### Expected behaviour
When I type in the Find/Scan item textbox a list should show filtered according to the entered text

### Actual behaviour
Nothing happens

### Steps to reproduce the issue

**Comment by daN4cat** [comment]
PHP version?

**Comment by daN4cat** [comment]
Installed all the required PHP extensions?

**Comment by odiea** [comment]
I just downloaded the master and this does appear to be an issue. I was testing Takings and found this. Also no items are showing in the list but  it will accept an item number with no dropdown in Register. I made and completed the Sale and it went to a blank page.  Receivings is the same where the find is not working.

**Comment by odiea** [comment]
Also this is what I get when trying to enter an Item Kit.
![2017-02-20 11_25_23-wedidit _ powered by ospos 3 1 0](https://cloud.githubusercontent.com/assets/10962177/23137480/7cc23b14-f75f-11e6-8be8-f720d4994233.png)
