### ISSUE TITLE
Store Config -> Invoice -> $CO

### ISSUE THREAD

**Issue by bill-goldberg** [jekkos/opensourcepos#1150]
### IMPORTANT IMPORTANT IMPORTANT

Chose what you want to report: New Feature or Bug.
If you remove the template when submitting a Bug your issue will be closed as we cannot help without basic information.

### New Feature / Enhacement

For New Features or Enhacements please remove all the template text and clearly write your proposal.
It's important to state whether you expect the community to implement it or you will contribute the work.
Please bear in mind that we will implement new features only on the current code, there is no support for old versions.

### Issue / Question / Bug

Before submitting an issue please make sure you remove the first section of the template and you tick (add a x between the square brakets) and agree with all the following check boxes:

- [] Checked the current issues database and no similar issue was already discussed
- [] Read the README, WHATS_NEW and UPGRADE
- [] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php5-gd, php-intl and sockets installed)
- [] Reporting an issue of an unmodified OSPOS installation
- [] PHP version is at least 5.5 and not 7.x
- [] MySQL version is 5.5 or 5.6 and not 5.7
- [] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [] Know the name and version of OS, Web server and MySQL and will add to my issue report

### Steps to reproduce the issue

**Comment by bill-goldberg** [comment]
What is $CO ?

**Comment by bill-goldberg** [comment]
![g](https://cloud.githubusercontent.com/assets/23611136/23115216/869335f8-f769-11e6-9322-9d19c8bbf584.JPG)

**Comment by daN4cat** [comment]
This is going to change after @SteveIreland commit of his latest work if I got right. That will be in 3.1.0.

**Comment by bill-goldberg** [comment]
Ok but what if i remove it from store config and just left the fields blank?

**Comment by SteveIreland** [comment]
The $CO is translated to the number of records in the `sale_items` table at the time the invoice number is rendered which is currently when the sale is completed.  If you leave it blank then the system will return a blank invoice number.

**Comment by SteveIreland** [comment]
After the pull request for tokens and quotes is in then the following will be in place (this is from the wiki).

**Sales Invoice Format** - This is how the invoice number will be formatted when it is assigned.  There are three codes that you can provide that will be translated to a particular value.  Normally only one is used.
- *$CO or {CO:9}* - This will be replaced with the number of sales records that have an invoice number.
- *$YCO or {YCO:9}* - This will be replaced with the number of sales records with rollover each year.
- *$SCO or {SCO:9}* - This is a count of the number of suspended sales records with an invoice number.
- *{ISEQ:9}* - [Proposed] This will use the "Last invoice number used" configuration value to build the invoice when the sale is complete.  When the sale is complete the value is incremented and replaces {ISEQ}.  If the invoice number should be a fixed number of digits then the number of digits to use can be indicated using the following format {ISEQ:9} with the single numeric digit after the colon representing the number of digits that should be returned.  It can be up to 9 digits long with 0 indicating that the number should be as long as necessary to hold the full value and {xxx:0} and {xxx} will be treated the same.
- *%y* -  The two digit year from the date of sale replaces the value %y.  In fact, there are numerous "%" tokens that are based on current system date and time.  They are listed a http://php.net/manual/en/function.strftime.php

For example, If the value "INV-%y{ISEQ:6}" will render the invoice number INV-17000032 if prior to generation the value of the last invoice number used is 31 and the year of the sale is 2017

**Comment by daN4cat** [comment]
Wouldn't it better to switch to the new token format upgrading the current database with the database upgrade script? Supporting old and new becomes expensive code maintenance wise.

**Comment by SteveIreland** [comment]
I've been strongly discouraged from introducing changes that impact existing installations.

However, the existing tokens are handled internally by simply translating the old tokens to an equivalent new token.  So it's not expensive at all.  All token replacement is based on the new tokens only - at least for invoice and quote formats.

**Comment by bill-goldberg** [comment]
Thankyou @SteveIreland ...

**Comment by dvidic** [comment]
Is there a way to have invoice number as: inv.number/custom name/year? For example: **31/Storage/2017**

**Comment by odiea** [comment]
You can try it out but I believe the INV- has to stay for proper filtering in Takings and Reports.
