### ISSUE TITLE
Weblate Login Problems

### ISSUE THREAD

**Issue by Modding** [jekkos/opensourcepos#1151]
Hi,

i wanted to check if all German Translations are up to date ... and i tried to log me in to my Weblate account at http://weblate.jpeelaer.net . But it always sayed my Password is wrong ... and when i tried to reset my Password no mail was delivered to my Inbox and no eMail in my Spam Folder.

Greetings

Valentin

**Comment by jekkos** [comment]
Ok thanks for reporting this, I tried to upgrade the server yesterday but something might have gone wrong. I'll check tonight and post status here.

**Comment by jekkos** [comment]
I was about to remote the weblate orphan branch as the workflow that goes with it is too complex. Better to use translations directly on the  master branch.

**Comment by jekkos** [comment]
@Modding Email config should be OK now

**Comment by jekkos** [comment]
Tr

**Comment by Modding** [comment]
eMail works, and i updated the german translation again so it is 100% green! THX!
