### ISSUE TITLE
Question: Why qty, price calculation is not updated in real-time.

### ISSUE THREAD

**Issue by nick9822** [jekkos/opensourcepos#1153]
Hi there,

Thanks for such a nice product. While evaluating I came across one issue or question you can say.
Why qty, price is not updated real-time? Please see following screen, Price is 500 and 20 qty so amount should be 10000 but instead its 5000. Amount is getting updated after pressing update icon.

![capture 55](https://cloud.githubusercontent.com/assets/10139291/23138866/c3cf20b0-f7cf-11e6-804a-d1c11e777e1e.png)

If its default behavior, can anyone point where I can automate it by JS or PHP, so every focusout can update the amount?

Thanks,
Nick

**Comment by daN4cat** [comment]
Have type enter after you updated the field?

**Comment by nick9822** [comment]
@daN4cat 
Oh thanks, it worked. So sorry for that.

But how can we make on focusout or TAB press, any idea? It would be great.

Thanks,
Nick

**Comment by daN4cat** [comment]
I would need to check....

**Comment by RamkrishnaMondal** [comment]
@daN4cat   I have seen commercial POS system build on PHP, updates values automatically, without pressing enter or clicking on update button, can't we modify OSPOS that way ?

**Comment by jekkos** [comment]
Sure but this is not a commercial system but a community driven one. Technically it is certainly possible as long as someone has the motivation to pick up the issue and fix it

**Comment by nick9822** [comment]
@jekkos 
Thank you for reply. You have done the great work creating this product. 👍 
I would love to do this feature, if you guide me somewhat.

**Comment by daN4cat** [comment]
@nick9822 many thanks for the contribution, right approach to contribute. Somebody here will pick up and test, I'll see if I can find the time.

**Comment by jekkos** [comment]
See latest commit, should work for both receiving and sales

**Comment by nick9822** [comment]
Thank you for your efforts. Now we have the needed feature running.
