### ISSUE TITLE
Updating from 3.0

### ISSUE THREAD

**Issue by petercstevenson** [jekkos/opensourcepos#1156]
### IMPORTANT IMPORTANT IMPORTANT

Chose what you want to report: New Feature or Bug.
If you remove the template when submitting a Bug your issue will be closed as we cannot help without basic information.

### New Feature / Enhacement

For New Features or Enhacements please remove all the template text and clearly write your proposal.
It's important to state whether you expect the community to implement it or you will contribute the work.
Please bear in mind that we will implement new features only on the current code, there is no support for old versions.

### Issue / Question / Bug

Before submitting an issue please make sure you remove the first section of the template and you tick (add a x between the square brakets) and agree with all the following check boxes:

- [] Checked the current issues database and no similar issue was already discussed
- [] Read the README, WHATS_NEW and UPGRADE
- [] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php5-gd, php-intl and sockets installed)
- [x] Reporting an issue of an unmodified OSPOS installation
- [] PHP version is at least 5.5 and not 7.x
- [] MySQL version is 5.5 or 5.6 and not 5.7
- [] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [] Know the name and version of OS, Web server and MySQL and will add to my issue report

### Installation information

Web install using Docker

### Actual behaviour

I have been using OSPOS successfully using the beta version of 3.0. Today when I tried to log in I received PHP errors. So I redeployed and although I could log in, my database of items was gone. So I applied the 3.0.2_to_3.1.0.sql script and now I get a blank page when I go to the url. Could someone please go over the steps that I need to do to get this working? Or to point me to other bug reports that explain this?

### Steps to reproduce the issue

**Comment by daN4cat** [comment]
Read the FAQ and checked all the points?

**Comment by petercstevenson** [comment]
I have read the FAQ, and it doesn't seem like any of the points apply to me. I have read the README and the WHATS_NEW files and I see that there is an UPDATE.txt file as well. It seems like these instructions are based more for regular installs than for web docker installs. Or perhaps I just do not understand the instructions. For example, step 3 is "Remove all directories". Where do I remove all of the directories? In the main Digital Ocean filesystem? In the web container? In the mysql container? And step 4 is "Install the new OSPOS". Does that mean redeploy?

**Comment by petercstevenson** [comment]
By the way, I have Digital Ocean backups. If there is some way to go back to running the older version of 3.0 that would be just fine. I just need a usable system.

**Comment by petercstevenson** [comment]
This may be off-topic, but what I would really like is to pay someone else to host my database for me. Does anyone offer this service?

**Comment by daN4cat** [comment]
@jekkos is this something you could do?

**Comment by jekkos** [comment]
@petercstevenson Might be a good learning experience to troubleshoot this issue in my case. 

I suppose you have upgraded to the latest docker cloud build image, which is always the master in this case. You're correct in a sense that once you pull latest image from docker hub you need to redeploy the image.

But maybe the update script wasn't tested yet and doesn't work for this pre 3.0 version. Think we need something more robust there that determines what needs to be updated and manages this automically after determining what was already done and what not.

Did you see any errors running the mysql upgrade? Also we might want to enable display_errors in php to see what is going on

**Comment by jekkos** [comment]
I don't believe you're data is lost, it's probably the Items search method returning an error code 500 or so

**Comment by jekkos** [comment]
* You did not upgrade from a stable 3.0 release which means that there might be some statements in the 2.4_to_3.0 script that you need to execute before you can move to latest master build
* Also you might have skipped scripts going from 3.0 to 3.0.2
*  If you want then I could maintain your cloud setup under my account and rollout updates once in a while.

**Comment by petercstevenson** [comment]
There were no errors when I ran the 3.0.2_to_3.1.0.sql script

**Comment by petercstevenson** [comment]
OK, it looks like the problem was that I didn't have php5-gd installed in the web container. I have installed that package and everything seems to be working. I would recommend that the FAQ be updated to say something like "If you unexpectedly receive a blank page (HTTP status 500), then double check php5-gd presence in your php installation" as in my case it wasn't connected with search completion or receipt generation. Also, it would be helpful to have:
a) upgrade instructions for users who are using the web docker install
b) a mailing list that announces new releases
c) a docker web install that can be run without back-end updates that have the potential of breaking the system
