### ISSUE TITLE
unable to increase the quantity in sales

### ISSUE THREAD

**Issue by ganeshthandapani** [jekkos/opensourcepos#1160]
In the sales process there is no option to increase the quantity of particular item.

**Comment by daN4cat** [comment]
Not sure I get this, at all. Are you saying that you cannot write 2, 3, 10 in the cart entity field?

**Comment by ganeshthandapani** [comment]
ya, Thanks for  your feed back, no issues I have fixed that. while modifying i changed the variable name that all. Noe its work fine thanks fro your code.

**Comment by daN4cat** [comment]
Please don't post issues related to code you change, it's your responsibility to sort issues out once you changed something.

The issue template is in place for a reason.

Thanks
