### ISSUE TITLE
Installing 3.0.2 on Azure Platform

### ISSUE THREAD

**Issue by nenuchand** [jekkos/opensourcepos#1161]
I am struggling to install 3.0.2 on Azure platform after the recent change in directory structure . The 3.0.0 version works fine
I have rewritten the htaccess file to web.config  with the following but still im unable to get it up and running.
I have installed the composer component.
I am installing on a WebApp with PHP and Mysql.

Web.config file placed in public folder
`<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <system.webServer>
        <rewrite>
            <rules>
                <rule name="Imported Rule 1" stopProcessing="true">
                    <match url="^(.*)$" ignoreCase="false" />
                        <conditions logicalGrouping="MatchAll">
                            <add input="{REQUEST_FILENAME}" matchType="IsDirectory" negate="true" />
                            <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true" />
                        </conditions>
                        <action type="Rewrite" url="/v302/public/index.php?url={R:1}" appendQueryString="true" />
                </rule>
            </rules>
        </rewrite> 
    </system.webServer>
</configuration>`

**Comment by daN4cat** [comment]
And the problem is?

**Comment by nenuchand** [comment]
I get the error 

The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.

**Comment by daN4cat** [comment]
You need to point to the public direct.

**Comment by nenuchand** [comment]
It am pointing to the public URL in the browser

**Comment by daN4cat** [comment]
@nenuchand please search the Internet for codeigniter composer installations on Azure.
I cannot help because I never dealt with that type of environment.

**Comment by jekkos** [comment]
If you manage to find a solution then feel free to add it to our wiki.

**Comment by daN4cat** [comment]
Any update?

**Comment by nenuchand** [comment]
Will update in another 2 days. Still not completed.
