### ISSUE TITLE
Add/Enhance new item price field

### ISSUE THREAD

**Issue by HugoTrejo** [jekkos/opensourcepos#1162]
Hi,

I'm trying to add a new field for item price, in order to have 2 different prices for items then the user should be able to select which price the sale needs with a check box, this enhacement is for business that sells wholesales products with different price . But I dont know if I just need to add this new column on `ospos_items' table or I need to add extra column in the `ospos_sales_items` table. I understand the process to add new field is:

1. Add new field in table
2. Modify the view file in order to show the new field
3. Edit the controller file defining which price the subtotal needs to add to the total.

Hope you guys can help me.

Regards.

**Comment by SteveIreland** [comment]
Don't forget to pay the usual sacrifice to the CodeIgniter gods.
