### ISSUE TITLE
Should invoicing be enabled by default on a new installation?

### ISSUE THREAD

**Issue by SteveIreland** [jekkos/opensourcepos#1164]
Version: Open Source Point Of Sale Version 3.1.0 - 4f5ad57 (after commit 032bb34)

I was expecting only Sales and Return to be valid Register modes on a new install but found that Sales by Invoice and Quotes were also available.

Then I realized that the Invoice flag was enabled (which is what enables those modes).  So I thought I'd ask if that shouldn't be disabled by default.   I don't know if I inadvertently changed it to default to enabled ... so if I did I'll be happy to change that one back to default to disabled.

**Comment by jekkos** [comment]
Hmm it might be hard to find out which options enable what in ospos. If a default demo or install shows most of the functionality by default, then I think new users will find their way more easily. 
If the number of usecases is limited then I guess  they can always disable this unneeded functionality. Any other opinions here? @daN4cat @odiea

**Comment by daN4cat** [comment]
@jekkos checking the statistics from GA it looks like 97% of the users enabled invoices.

Therefore we can leave it as it is and close.
