### ISSUE TITLE
Return of non-stock items?

### ISSUE THREAD

**Issue by SteveIreland** [jekkos/opensourcepos#1165]
Version: Open Source Point Of Sale Version 3.1.0 - 4f5ad57 (after commit 032bb34)

It doesn't seem to me to make sense to be able to return "non-stock" items.  So if an item is non-stock and the register mode is in "return" then should the non-stock items be filtered out of the selectable items list?

**Comment by jekkos** [comment]
Maybe it does matter for the sale figures at the end of the day?

**Comment by SteveIreland** [comment]
That's a good point.  Even though it's non-stock there really isn't another way to issue a credit through the system if the customer isn't happy with the service and demands a refund.

**Comment by SteveIreland** [comment]
Closing this question ... I got my answer.
