### ISSUE TITLE
Undefined property in Sale_lib.php

### ISSUE THREAD

**Issue by SteveIreland** [jekkos/opensourcepos#1166]
Version: Open Source Point Of Sale Version 3.1.0 - 4f5ad57 (after commit 032bb34)

The following error occurred when I attempted to unsuspend a quote.  Working on a fix for it now,

```
A PHP Error was encountered
Severity: Notice
Message: Undefined property: stdClass::$stock_type
Filename: libraries/Sale_lib.php
Line Number: 736
```

**Comment by SteveIreland** [comment]
I tried to cherry pick a commit but it didn't work the way I wanted (which was I just wanted the commit which contains the change, but it seems to have picked up a few empty commits).

If you want me to redo this just let me know.  My feelings won't be hurt ... much.

**Comment by odiea** [comment]
@SteveIreland  I believe @daN4cat already fixed this in the master.

**Comment by SteveIreland** [comment]
No problem.  "Practice makes perfect."  I think the last thing I read was "try again" - that's why it was resubmitted.

**Comment by daN4cat** [comment]
I part fixed, @SteveIreland had more to add and therefore his was the proper fix!
Shall we consider this closed now?

**Comment by SteveIreland** [comment]
I think it can be closed now.
