### ISSUE TITLE
Create wiki or webpage to document things

### ISSUE THREAD

**Issue by daN4cat** [jekkos/opensourcepos#117]
It would probably a wise idea to create a wiki or webpage to document code, development practices and etc.

More ideas in further comments to this discussion thread....

**Comment by marteserede** [comment]
Good idea... What would be the first step?

**Comment by jekkos** [comment]
Easiest would be to use the github builtin facilities to add documentation to a project. In this case we should just create a gh-pages orphan branch in the repository, containing the markdown documentation.

https://help.github.com/articles/creating-project-pages-manually/

The nice thing about it, is that this can be a community driven process. Anyone that has a fork of the project can edit the pages and then make a pull request to this repository.

I could also try to register a domain name for the project that would then point to the wiki by default.

**Comment by daN4cat** [comment]
I sketched something, but I can't find the time to elaborate more at the moment.
I'm trying to move forward with the EAN8/13 barcode feature.

**Comment by RyanfaeScotland** [comment]
I see the GitHub wiki (https://github.com/jekkos/opensourcepos/wiki) has been updated more recently than this ticket. Is it going to be the go to place for documentation or is there still merit in the gh-pages approach?

Documentation is a great way for people like myself who are new to a project to contribute without running the risk of breaking something they aren't too familiar with yet, something I'd like to do if I can get pointed in the right direction.

**Comment by jekkos** [comment]
Good question. I just did a quick search on the distinction between these two

* wiki pages is made for development/contributors documentation
* gh-pages branch hosts user documentation

So I guess that more general, end user documentation should go in the gh-pages branch, while the technical, contributor docs belongs in the wiki.

**Comment by jekkos** [comment]
Contributions are more than welcome. 

If you'd like to discuss on a new feature that you'd like to build, then just create an issue so we can discuss about it and/or give some directions if needed.

**Comment by RyanfaeScotland** [comment]
Will do thanks. Currently just reading though open issues seeing if there is any existing ones I can help out with. Documentation is always a great help to people (well, those who read it) and if I write it whilst I learn it is a useful reference for myself to come back to when I wonder how I made something happen! 

Will attempt to make the branch when home tonight and get writing (although I think my docs will be more technical based I'll see if I can at least make a start on both).

**Comment by jekkos** [comment]
That would already be a nice contribution. Currently we're lacking some documentation. So if you're willing to help improve that a little bit, then you're more than welcome :+1:

**Comment by RyanfaeScotland** [comment]
Got this branch created today and got as far as issueing the pull request at which point it errors out with 'Sync failed to push local changes. It seems you do not have permission to push your changes to this repository.'

Can I be given these permissions or is there an alternative way for me to get this set up?

**Comment by jekkos** [comment]
Think at first it might be better to send some pull requests through github itself. I'd like to keep the review phase of every change as it allows other contributors to discuss and test modifications before they are integrated. This will hopefully improve overall quality of the project.

**Comment by RyanfaeScotland** [comment]
Oh god yes I wouldn't expect any of my stuff to go in unreviewed!

I'm using the GitHub Desktop tool and got the above message when clicking the Send Pull Request button. I see there is a message saying 'This pull request can be automatically merged.' above the button, perhaps it is because of this it is trying to push but I can't see any way to change it.

**Comment by RyanfaeScotland** [comment]
Ok, the issue might be that I checked out the master, orphan branched in the desktop gui, made and commited changes and am now trying to issue a pull request which is attempting to remerge my branch to master.

What I should probably do is fork here first, check out the fork and then create the orphan branch as described above so when I try to commit I commit to my fork then perhaps the review process will work when issuing pull requests for the fork?

All just theories, can't see any docs that are clear about it.

**Comment by RyanfaeScotland** [comment]
Didn't get a chance to re-try the branch creation as it was out store's opening day on Saturday and Sunday was spent on other matters however I did get a simple user guide written up for using the till so I'll use that as a base once I get the branch set up.

**Comment by jekkos** [comment]
hmm I never did a pull request for an unexsiting branch before. Do you have these modifications in that orphaned branch on github here?

It might be easier to let me pull in your changes and the publish them to the repo in this case.

**Comment by RyanfaeScotland** [comment]
I think they are only local to my computer just now as the pull request is trying to merge automatically, failing when it does so (rightly) due to permissions, and isn't flagging it up for your review.

**Comment by jekkos** [comment]
ok that might be the problem here, pull request is something that's managed by the github platform. maybe you should try to push that branch to your public github repo first. From there I pull these changes in and review + integrate them directly (in case this is a new branch)

**Comment by RyanfaeScotland** [comment]
Will aim to try it tonight and message up when done.

**Comment by RyanfaeScotland** [comment]
Ok @jekkos if you have a moment can you see if it looks like things are set up correctly for the pulling and reviewing on your end? I have a branch set up at https://github.com/RyanfaeScotland/opensourcepos/tree/gh-pages which is based off of a fork of your master and then following the instructions on the first page linked in this issue. 

Looks good from my side so only concern is if I try to do a pull request I get the message "There isn’t anything to compare.
jekkos:master and RyanfaeScotland:gh-pages are entirely different commit histories."

**Comment by jekkos** [comment]
I've created the gh-pages branch on my repo now. I added a standard github template for now, which can be easily edited by collaborators. Think it's easier to pull in my branch first, start editing, and then make a pull request again afterwards.

**Comment by jekkos** [comment]
This branch is live now at http://jekkos.github.io/opensourcepos

I might register a real domain name to point to this page this week. Any suggestions on a tld here?

**Comment by RyanfaeScotland** [comment]
Who does http://www.opensourceposguide.com/ belong to?

Ok, can someone explain the pull request process to me because it still isn't working and it is beginning to hack me off wasting time fighting with this when I could be making actual useful updates.

I deleted my local copy, checked out the repo again, changed to the gh_pages branch, made a simple change to index.html, committed the change. Is that as far as I am meant to go? Is it now up to @jekkos to approve / reject the commit? If I click 'Pull Request' in the top right of the window it looks like it is trying to remerge gh_pages and master which isn't what I want.

I just want to be able to contribute to the project, it really shouldn't be this hard...

**Comment by jekkos** [comment]
Once you have a fresh copy of the gh-pages, you should just issue a pull request of the committed changes you did on your local branch. Make sure that once it asks to do the pull requests, that you select gh-pages branch on both sides. Normally a merge shouldn't be necessary.. 

I haven't really tried the github client itself yet, so I'm not sure how the pull request functionality works. If it doesn't work out with the client then maybe push your changes back to your github repo first. Then make a pull request from there (again after selecting the gh-pages on my and your side)

the guide is something that was set up by another user (Curt). I don't think it's actively maintained so after all it would be better to have one that is maintained by the community instead

**Comment by RyanfaeScotland** [comment]
@jekkos I've now got 2 repos on the go, one for the documentation updates and one for my code updates. I've added a few useful reports to the code one and I've made a simple change to the documentation one. You don't have to pull them but can you see if they are available for doing so into the trunk?
