### ISSUE TITLE
New item is not displayed in "Items" tab even after adding and unable to add item to sale

### ISSUE THREAD

**Issue by sa1dude23** [jekkos/opensourcepos#1172]
Hi,

Even after adding the new item the item is not displayed in items list. When i try to make a sale the items which are added can be seen in search bar of sale screen but the item is unable to add to sale. screenshot attached.
![test item present](https://cloud.githubusercontent.com/assets/26069685/23374510/999030a2-fd4a-11e6-9192-048bdb431155.png)

**Comment by odiea** [comment]
Have you done the database updates or is this a new install. More info is required from the template to try and help you out.

**Comment by sa1dude23** [comment]
It is new install

**Comment by daN4cat** [comment]
Make sure all the php extensions are installed.
Read the FAQ and in specific with 3.0.2 don't use MySQL 5.7 nor PHP7

**Comment by sa1dude23** [comment]
When I try to add new item from Sales Screen the item is added, it is also account for sale, but the item is not displayed in items list.
And Sale entry is also not displayed in sales register

**Comment by daN4cat** [comment]
You are not answering your questions, we cannot help you.

**Comment by sa1dude23** [comment]
All php extensions are installed, except for "php-bcmatch"

**Comment by sa1dude23** [comment]
But version 2.3.4 is working fine! problem is only with v 3.0.2

**Comment by odiea** [comment]
Yes This is a Different updated program.
