### ISSUE TITLE
Configuring SMS

### ISSUE THREAD

**Issue by araalrai** [jekkos/opensourcepos#1173]
How do I setup SMS API? which SMS gateway should be used? I have signed up with smsapi.com but it doesn't work with OSPOS. Any help/comments would be appreicated.

**Comment by daN4cat** [comment]
You need to implement in Sms_lib.php under libraries the code to use smsapi.com.
We don't provide implementation for all the SMS gateways but happy to accept contributions.

**Comment by araalrai** [comment]
Which SMS gateways are currently compatible with the OSPOS?
Thanks

**Comment by daN4cat** [comment]
None in particular but you can find some examples in the library code abovementioned.
You really need to work on this or get somebody to do for you.

**Comment by araalrai** [comment]
Thanks for your reply. I will have a look on the library and see if i can
come up with something.

Another issue i have is "Tax Included" is not calculating properly when you
have two taxes. For example:

Tax 1 @ 5%
Tax 2 @ 7%

Lets say the total price including taxes is $112
The break down should be as follows:
Sub Total: $99.34
Tax1: $5.33
Tax2: $7.33

It should be:
Sub total: $100
Tax1 $5
Tax2 $7

What the program is doing is basicall calculating each tax separately. So
it is taking the total $112 x Tax 1 divided by 100 + Tax 1 = $5.33

Any fix or suggestions so i may fix it would be appreciated.

Thanks

Abdur


On Feb 28, 2017 1:17 PM, "FrancescoUK" <notifications@github.com> wrote:

None in particular but you can find some examples in the library code
abovementioned.
You really need to work on this or get somebody to do for you.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/jekkos/opensourcepos/issues/1173#issuecomment-283163155>,
or mute the thread

**Comment by daN4cat** [comment]
Tax discussion is ongoing in #1163. Please don't mix up topics as we cannot do one issue catches all.
Thanks.

**Comment by araalrai** [comment]
Sure I will posit it there. Thanks

**Comment by jadoux** [comment]
Not sure who's the genius called @araalrai who started a discussion about tax
But anywa, is twilio compatible out of the box, or will it require some editing to php files?

**Comment by odiea** [comment]
It may require some editing but all you can do is try and let us know if it works. Thanks

**Comment by odiea** [comment]
You can enter the your info in configuration messages and see if you can send sms that way.

**Comment by daN4cat** [comment]
Not really, there is no code in the SMS library as it's an empty shell and the integration needs to happen.
However would be good if somebody can add integrations like Twilio as part of OSPOS native integration.

**Comment by odiea** [comment]
@daN4cat Thanks. I have never used that feature but I have seen it was available.

**Comment by odiea** [comment]
@daN4cat here is another one you probably not like :)

What I ended up doing was the following to be able to send a Customer a sms.
In application/helpers/tabular_helper I changed the following under function get_customer_data_row($person, $stats)
```'phone_number' => empty($person->phone_number) ? '' : mailto($person->phone_number, $person->phone_number), ```now I can sms them or clicking the mail button it will send to both their email and phone number. I also created a text box below the phone number that includes the common US carriers addresses.
![2019-06-13 14_26_18-Window](https://user-images.githubusercontent.com/10962177/59466134-c09e3180-8de9-11e9-9526-b968b2fa1abe.png)
![2019-06-13 14_45_28-Window](https://user-images.githubusercontent.com/10962177/59466204-f6dbb100-8de9-11e9-82eb-e37bde40a6d9.png)

**Comment by daN4cat** [comment]
That works in the US or places where you can address somebody's phone using the email.
I bet you get a lot of spam due to that.

**Comment by ashrafwts** [comment]
I have already integrate the SMS Api on SMS_Lib.php. This has worked fine on Sales register also.

**Comment by joshbudu** [comment]
@ashrafwts Can you please share how?
