### ISSUE TITLE
How to edit the created Invoice

### ISSUE THREAD

**Issue by prabakar1978** [jekkos/opensourcepos#1174]
### Issue / Question / Bug

Do we have any option to edit the Invoice and Print again as Invoice

### Expected behaviour
Need to edit the Invoice data especially (Product data and Customer data) after that i want to take it as Invoice printout instead of recipt kind of printout

### Actual behaviour
As of now we are not able to edit Invoice especially (Product data and Customer data) and after that i am not able to take Invoice printout instead it is giving as recipt

### Steps to reproduce the issue

**Comment by SteveIreland** [comment]
In version 3.1, for all intents and purposes an invoice is a completed sale.  The services have  been rendered and all that is pending is payment.  Accountants do not like completed sales or invoices being "changed" without a formal record of such change and those are handled via returns and/or credits - at which point a new invoice will need to be generated that reflects the correction.

In OSPOS, if the agreement for services rendered is not yet finalized then you have the option to suspend a sale.  If you need a document that the user signs off on before providing the services then version 3.1 introduces the notion of a Quote.  When a quote is printed the sale is automatically suspended.  It can then be "unsuspended", modified and then either reprinted as a new quote or completed as a sale by invoice.

**Comment by SteveIreland** [comment]
Should I assume that the response wasn't useful?

**Comment by daN4cat** [comment]
@SteveIreland many times people ask and then disappear. I usually leave a week and then close the case if no replies.

**Comment by JackCameo** [comment]
I've completed sales and then realized I had entered a price incorrectly, is there no way to update a sale? 
Maybe modify to create sale and then admin selects and completes / approves as completes sale.

**Comment by daN4cat** [comment]
No. Return the sale and issue a new one.
