### ISSUE TITLE
Handling items with same EAN numbers

### ISSUE THREAD

**Issue by bill-goldberg** [jekkos/opensourcepos#1175]
### IMPORTANT IMPORTANT IMPORTANT

Chose what you want to report: New Feature or Bug.
If you remove the template when submitting a Bug your issue will be closed as we cannot help without basic information.

### New Feature / Enhacement

For New Features or Enhacements please remove all the template text and clearly write your proposal.
It's important to state whether you expect the community to implement it or you will contribute the work.
Please bear in mind that we will implement new features only on the current code, there is no support for old versions.

### Issue / Question / Bug

Before submitting an issue please make sure you remove the first section of the template and you tick (add a x between the square brakets) and agree with all the following check boxes:

- [x] Checked the current issues database and no similar issue was already discussed
- [x] Read the README, WHATS_NEW and UPGRADE
- [x] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php5-gd, php-intl and sockets installed)
- [x] Reporting an issue of an unmodified OSPOS installation
- [x] PHP version is at least 5.5 and not 7.x
- [x] MySQL version is 5.5 or 5.6 and not 5.7
- [x] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [x] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [x] Know the name and version of OS, Web server and MySQL and will add to my issue report

### Installation information
Windows 10 x64
Google Chrome v56
WAMP 2.5 x64
Apache 2.4
MySQL 5.6
PHP 5.5

### Steps to reproduce the issue

**Comment by bill-goldberg** [comment]
I have 2 items with same EAN numbers but different cost price , unit price, How should i handle this condition?

**Comment by daN4cat** [comment]
Use serialised option

**Comment by bill-goldberg** [comment]
Please explain more about it.

**Comment by daN4cat** [comment]
Edit the item and tick the serialised checkbook. 
Once done try to scan twice the item and the register will show two lines. However the problem of the cost price cannot be solved and the unit price needs to be adjusted manually.

That's what the tool offers at the moment.

**Comment by bill-goldberg** [comment]
Thank You for the Support.

**Comment by bill-goldberg** [comment]
How can i use this serialised option in receivings module?

**Comment by daN4cat** [comment]
I don't think it's supported.

**Comment by daN4cat** [comment]
By the way this story of multiple prices for the same item was discussed in the past. Check the open issues as I think it's still open.
Maybe you can post the number here as reference and so we can close this as duplicate.

**Comment by bill-goldberg** [comment]
then why there is a column for serial number in ospos_receivings_items table ?

**Comment by daN4cat** [comment]
Don't know. I never use that module.

**Comment by hzzg6y** [comment]
Hi,
     I am also facing the same challenge. We have items comes in Batch with price increment over one year.  Last item is at 10 & it is increase to 12 with new batch however EAN is same. Do you think we should add the Batch number as part of index in Item table so that it is unique.. Please advice on direction. This has to do with receiving module ( Inward / GRN ). Scannning item with EAN having multiple prices should prompt for right selection in Sales module. Please just need right direction on how to handle this. 

Rgds,

**Comment by bill-goldberg** [comment]
Please can someone provide some hints or pointers

**Comment by SteveIreland** [comment]
If I have 10 of an item in stock that I originally received at $10 per unit, and then I receive a new shipment of 10 at a cost of $12 per unit then in my mind that doesn't make it a different item, it just means the average cost of the item in  inventory has gone up a bit.   I'll up the price to reflect an appropriate profit margin.    Are there a different set of rules that are required to be applied for some countries or businesses?

If the packaging is different it usually has a different UPC code and that should be a different item.

**Comment by bill-goldberg** [comment]
![snapcrab_noname_2017-3-27_1-23-47_no-00](https://cloud.githubusercontent.com/assets/23611136/24334664/1723ff70-128c-11e7-9feb-54a7370998af.png)

**Comment by bill-goldberg** [comment]
I want to add this "update Item" button in receivings module. So that i can update an existing item during receivng. Please provide help about it.
