### ISSUE TITLE
Can't test the application on local

### ISSUE THREAD

**Issue by pvidaurre** [jekkos/opensourcepos#1176]
OS: Windows 10
web server : Apache 2.3
php : 7.0.2
mysql : 5.6
ospos version : 4f5ad57

I installed, the application on my local machine for a test, but I can't use it because the screen is blocked. I change the language and setting in  database directly
![openpos](https://cloud.githubusercontent.com/assets/930659/23536213/6d3c6928-ff91-11e6-8349-84a4dd32c97e.png)

**Comment by daN4cat** [comment]
Please read the FAQ first.

**Comment by sohailhaider** [comment]
Same issue can't open it, did go through whole FAQ. Can't find any thing missing. gd2.dll is there.

**Comment by daN4cat** [comment]
If it's 3.0.2 it does not work with PHP7.
If it's 3.1.0 it's supported.

**Comment by RamkrishnaMondal** [comment]
> If it's 3.0.2 it does not work with PHP7

I have 3 copies of OSPOS v3.0.2 installed and running with php7 , I don't see any issue at all.

**Comment by odiea** [comment]
Verify that your db looks similar to this.
![2017-03-06 05_14_02-localhost _ 127 0 0 1 _ ospos1 _ ospos_app_config _ phpmyadmin 4 5 1 and 1 more](https://cloud.githubusercontent.com/assets/10962177/23609548/c8b764aa-022b-11e7-8d6f-79648b98de39.png)
Then make sure you copied all the needed files as the wamp wiki states.

**Comment by sohailhaider** [comment]
yeah, it was the problem with cookies, so changed sess_cookie_name from CI config. Now working simultaneously both on local and live.

**Comment by odiea** [comment]
Problem solved. Will close this now.
