### ISSUE TITLE
Unable to execute any reports

### ISSUE THREAD

**Issue by mickday** [jekkos/opensourcepos#1177]
Bug

- [x] Checked the current issues database and no similar issue was already discussed
- [x] Read the README, WHATS_NEW and UPGRADE
- [x] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php5-gd, php-intl and sockets installed)
- [x] Reporting an issue of an unmodified OSPOS installation
- [x] PHP version is at least 5.5 and not 7.x
- [x] MySQL version is 5.5 or 5.6 and not 5.7
- [x] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [x] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [x] Know the name and version of OS, Web server and MySQL and will add to my issue report

OSPOS: 3.0.2
OS: Ubuntu 16.04
Web Server: Apache 2.4.18
MySQL: 5.7.17
PHP: 7.0.15

Whenever I run any summary reports I get no data returned

![image](https://cloud.githubusercontent.com/assets/12095443/23555324/6a5756d4-0020-11e7-9a16-e4279e1d9bf5.png)

If I try to run any detailed reports I get a 500 server error

**Comment by daN4cat** [comment]
Read the FAQ in the readme coming with 3.0.2 and you have the answer...

**Comment by daN4cat** [comment]
Also the bug report template states the same....

**Comment by mickday** [comment]
Got this working with 3.1.0 for GitHub

**Comment by daN4cat** [comment]
Indeed.... but current 3.1.0 has an issue with tax calculation so you are aware of that.
