### ISSUE TITLE
Customer Reward points

### ISSUE THREAD

**Issue by joshua1234511** [jekkos/opensourcepos#1179]
Hi 
I have added the code to add Customer reward points.
Custom packages can be made and assigned to customers.
Points can be  redeemed at the sale
Reports can be checked in detailed sale and specific customer
Database changes and alter added as sql in database folder
https://github.com/jekkos/opensourcepos/pull/1178

**Comment by joshua1234511** [comment]
Screen shots: 
https://www.screencast.com/t/0c6zOJrhC
https://www.screencast.com/t/TPdtnMibkun
https://www.screencast.com/t/ALcw4UtXMta

**Comment by jekkos** [comment]
Nice idea on the screencast. Might want to use this kind of thing in the future to explain on how things work in OSPOS.

**Comment by joshua1234511** [comment]
Thanks. 
yes screen cast is very helpful 
I use it most of the times to explain certain features to client.
As it becomes helpful compared to documentation for those who prefer not to read.

**Comment by daN4cat** [comment]
Good, I merged the code but had no time to test.
So let see if anybody will find the time to test and complaint :-)

**Comment by daN4cat** [comment]
@joshua1234511 I just tested.

When the rewards are disabled in the config, under the customer form the rewards fields are still visible.
Could you please disable them if the user doesn't enable the feature?

**Comment by joshua1234511** [comment]
Yes working on It :

**Comment by joshua1234511** [comment]
https://github.com/jekkos/opensourcepos/pull/1185

**Comment by daN4cat** [comment]
OK, merged.

Let's give some time for people to test the feature and report any issue.

**Comment by joshua1234511** [comment]
okay 👍

**Comment by daN4cat** [comment]
@joshua1234511 there were few regressions that I fixed in detailed reports, also there was no flag to remove the extra reward detail line if the feature was disabled.

BTW, there is a problem with the config, when the submit if clicked there is no pop up notification confirming all is fine. Could you please check into that?

**Comment by daN4cat** [comment]
Also the behaviour of the input boxes is not correct when the checkbox is unticked and submit is clicked. They should stay grey/disabled.

**Comment by daN4cat** [comment]
The notification pop up at config submit time is fixed, however there is another error:

<h4>A PHP Error was encountered</h4>

<p>Severity: Notice</p>
<p>Message:  Undefined index: points_percent</p>
<p>Filename: controllers/Config.php</p>
<p>Line Number: 626</p>

Please check with PHP 5.6 if that could make a difference.

**Comment by odiea** [comment]
I still have no issues with 5.6.

**Comment by daN4cat** [comment]
And latest master?

**Comment by odiea** [comment]
I did a merge before and after I tested and all was ok. I will download the latest and see what that does.

**Comment by odiea** [comment]
I am not getting any errors from the current master. When does this error show?

**Comment by daN4cat** [comment]
When you go to rewards, unchecked the box and submit. The pop up not notification will not show but beneath with the inspector you can see there is that error.

**Comment by odiea** [comment]
No issues here. I am using Mariadb and not Mysql. Pop up shows just fine.

**Comment by odiea** [comment]
I just fired up my vm with the following and I am having no issues there either.

    Server: Localhost via UNIX socket
    Server type: MySQL
    Server version: 5.7.18-0ubuntu0.16.04.1 - (Ubuntu)
    Protocol version: 10
    User: root@localhost
    Server charset: UTF-8 Unicode (utf8)

Web server

    Apache/2.4.18 (Ubuntu)
    Database client version: libmysql - mysqlnd 5.0.12-dev - 20150407 - $Id: b5c5906d452ec590732a93b051f3827e02749b83 $
    PHP extension: mysqli Documentation
    PHP version: 7.0.18-0ubuntu0.16.04.1

**Comment by odiea** [comment]
Here is what I see with both php versions after removing the check mark.
![2017-06-04 09_21_16-program manager](https://cloud.githubusercontent.com/assets/10962177/26762907/5e3d29fc-4907-11e7-9f56-562d53a8ea36.png)

**Comment by daN4cat** [comment]
Thanks @odiea I'll have a better look into this later.

**Comment by daN4cat** [comment]
I close this as in the end I don't use/need. If somebody spots the same issue we will reopen.

**Comment by rtesot** [comment]
Hello @joshua1234511 and all thanks for this. I've seen this had been closed a while back. I've realized that when someone redeems their points the system still calculates the redeemed points as a reward. This should not be the case. Pls assist with this. 
Thank you.

**Comment by BramWerbrouck** [comment]
A question:
Now the reward system is a percentage of the amount. Can this be changed (in the settings) so you can choose if you want a percentage of the amount, of just fixed points

e.g.:

Reward 1    default     upto 100 euro        10 points
Reward 2    silver        upto 200 euro        15 points
Reward 3    gold         upto 300 euro        25 points
...

Also I would like an option to print the rewards on the receipts if you want. Can anyone help me out with this?
