### ISSUE TITLE
Issues with Register and Negative value.

### ISSUE THREAD

**Issue by odiea** [jekkos/opensourcepos#1182]
### IMPORTANT IMPORTANT IMPORTANT

Chose what you want to report: New Feature or Bug.
If you remove the template when submitting a Bug your issue will be closed as we cannot help without basic information.

### New Feature / Enhacement

For New Features or Enhacements please remove all the template text and clearly write your proposal.
It's important to state whether you expect the community to implement it or you will contribute the work.
Please bear in mind that we will implement new features only on the current code, there is no support for old versions.

### Issue / Question / Bug

Before submitting an issue please make sure you remove the first section of the template and you tick (add a x between the square brakets) and agree with all the following check boxes:

- [x] Checked the current issues database and no similar issue was already discussed
- [x] Read the README, WHATS_NEW and UPGRADE
- [x] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php5-gd, php-intl and sockets installed)
- [x] Reporting an issue of an unmodified OSPOS installation
- [x] PHP version is at least 5.5 and not 7.x
- [x] MySQL version is 5.5 or 5.6 and not 5.7
- [x] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [x] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [x] Know the name and version of OS, Web server and MySQL and will add to my issue report

### Expected behaviour
Register should show Complete Sale button.

### Actual behaviour

Register does not show complete Sale button when change due is negative number.
![2017-03-08 04_52_11-wedidit _ powered by ospos 3 1 0](https://cloud.githubusercontent.com/assets/10962177/23703142/a7f9cc3a-03bb-11e7-9861-ff05ab2b4e2a.png)

### Steps to reproduce the issue

**Comment by odiea** [comment]
when I revert this 
~~~
public function is_payment_covering_total()
	{
		$amount_due = $this->get_amount_due();
		// 0 decimal -> 1 / 2 = 0.5, 1 decimals -> 0.1 / 2 = 0.05, 2 decimals -> 0.01 / 2 = 0.005
		$threshold = bcpow(10, -$this->CI->config->item('currency_decimals')) / 2;
		return ($amount_due > -$threshold && $amount_due < $threshold);
	}
~~~
Back to this it works.
~~~
public function is_payment_covering_total()
	{
		$subtotal = 0;
		foreach($this->get_payments() as $payments)
		{
			$subtotal = bcadd($payments['payment_amount'], $subtotal);
		}

		return $subtotal;
	}
~~~

**Comment by daN4cat** [comment]
Yes but doesn't work for other cases.
When do we have negative amount?

**Comment by daN4cat** [comment]
I mean is that a real case?

**Comment by odiea** [comment]
I guess it's a real case. The amount due was .57. They paid 1.00 so the change should be -43. As you can see in the image it is still requesting another payment.

**Comment by daN4cat** [comment]
Ok it needs knowledge of sale or return to decide if negative or positive are fine instead of working with ranges.

**Comment by SteveIreland** [comment]
Is this a bug that was introduced with 3.1.0?

In an overpayment situation the sales should still be able to be competed so that the receipt can be printed so that the cash drawer will be opened so that the change can be refunded to the customer.

Right?

**Comment by daN4cat** [comment]
Yes, I fixed the return case but didn't consider a negative for sale case. As said I need to consider negative for sale and positive for return. So the comparison needs to be changed taking into account the models.

**Comment by SteveIreland** [comment]
"I see!" ... said the blind man.

**Comment by daN4cat** [comment]
This is now fixed and in master.
