### ISSUE TITLE
Question regarding migration

### ISSUE THREAD

**Issue by SteveIreland** [jekkos/opensourcepos#1183]
This is a question regarding "responsibility".  How much responsibility do I have for providing migration tools for existing installations?

The sales tax feature, which is coming this weekend, will work just fine for me and for any new OSPOS installations.  However, upgrades of existing installations will require a bit of thought and effort.

There isn't an "automatic migration" mechanism in place for OSPOS (if there is then I am again clueless).

Two things require migration.

First, @jekkos gave me implicit permission to drop the set of suspended tables (he might not remember that :-) ).  Since I had to add a new `sales_tax` table I thought it would be a good time to do that.  Suspended sales will now be included in the sales tables but will have a `sales_status` field to identify the sale as either Completed or Suspended.  So for someone who upgrades will need to deal with the issue of existing "Suspended sales" data.

Secondly, the reporting of sales taxes should change so that that taxes collected will come from the new table instead of the old one. (Item level sales tax reporting works the same except that it is reported at the appropriate number of decimal positions.) This works fine for new installations, but for existing installations to take advantage of improved tax reporting they would need to populate the `sales_tax` table for historical data.

It's easy enough to do, but I don't have an existing installation to work with on this - so I could never say whether it works or not.  I believe someone would need to commit to it and I'd be happy to work with them on it.

I'm throwing this out here so that someone can provide a bit of direction on this.

Thanks in advance for your feedback.

**Comment by daN4cat** [comment]
The "automatic" migration is done at the moment via SQL upgrade scripts from one version to the following one.
That's the level of migration we keep as promise here.

So any functional upgrade affecting DB needs to come with a SQL script upgrade.

There is no story like "somebody needs to deal with" as that will stop most of the people here.
If we have done that already I'm afraid I need to stop 3.1.0 until we sort the migration story to be a full and proper one.

**Comment by daN4cat** [comment]
No no, I meant to just add to the current SQL script that upgrades from 3.0.2 to 3.1.0

**Comment by daN4cat** [comment]
Please no mixed upgrade stories with one here and one there.

**Comment by SteveIreland** [comment]
What if the data migration cannot be properly done using only an SQL script?

**Comment by daN4cat** [comment]
If you check migration from old php script you can see that even moving fields from tables or combine two fields to one is possible. Not sure what more you would need to do for this tax story.

**Comment by jekkos** [comment]
Agree on the suspended table migration. Been a thorn in the eye to see it being duplicated.

Most of the data migration is indeed done through manual SQL upgrade scripts. I agree with @daN4cat that an automatic procedure should ideally reuse existing scripts to determine what to execute knowing which version to start from. 

So better to either stick with the old system for now, unless there's a real quick solution that enables us to execute upgrade scripts directly. I can't directly find the original ticket for this but it should be robust enough to cope with 

* Upgrading between stable releases
* Upgrading between different commits in git (ideally)

the latter means that we'd have to refine the unit of change to a commit level so that SQL statements aren't executed twice.

**Comment by SteveIreland** [comment]
Okay, thanks.  I have my answer.

**Comment by daN4cat** [comment]
@jekkos yes there is a ticket and I remember I even found a solution to upgrade straight from github. Having all the time of this world.....
