### ISSUE TITLE
Total & Profit are wrong in Sale Summary Report

### ISSUE THREAD

**Issue by TayZaN** [jekkos/opensourcepos#1184]
### IMPORTANT IMPORTANT IMPORTANT

Chose what you want to report: New Feature or Bug.
If you remove the template when submitting a Bug your issue will be closed as we cannot help without basic information.

### New Feature / Enhacement

For New Features or Enhacements please remove all the template text and clearly write your proposal.
It's important to state whether you expect the community to implement it or you will contribute the work.
Please bear in mind that we will implement new features only on the current code, there is no support for old versions.

### Issue / Question / Bug

Before submitting an issue please make sure you remove the first section of the template and you tick (add a x between the square brakets) and agree with all the following check boxes:

- [] Checked the current issues database and no similar issue was already discussed
- [] Read the README, WHATS_NEW and UPGRADE
- [] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php5-gd, php-intl and sockets installed)
- [] Reporting an issue of an unmodified OSPOS installation
- [] PHP version is at least 5.5 and not 7.x
**PHP 7.0**
- [] MySQL version is 5.5 or 5.6 and not 5.7
Server version: 5.5.54-MariaDB-1ubuntu0.14.04.1 **(Ubuntu)**
- [] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
**3.0.0**
- [] Know the name and version of OS, Web server and MySQL and will add to my issue report
**ubuntu0.14.04.1 , Apache2, PHP 7.0**
### Expected behaviour
Below screen capture from Detail Sale Report
<img width="286" alt="screen shot 2017-03-12 at 11 29 12 am" src="https://cloud.githubusercontent.com/assets/23426785/23828831/73e9f6ac-0719-11e7-9ef2-a705bedd45c2.png">

### Actual behaviour
<img width="1192" alt="screen shot 2017-03-12 at 11 35 25 am" src="https://cloud.githubusercontent.com/assets/23426785/23828832/7a066dae-0719-11e7-9a29-5aa60fd1910b.png">

### Steps to reproduce the issue

**Comment by daN4cat** [comment]
There is already an issue open for this and there is no point to open another one.

**Comment by TayZaN** [comment]
Noted. By the way ,some other report also have such issue which not tallying.

**Comment by daN4cat** [comment]
Yes we know.... it's almost done in 3.1.0 just the taxation needs to be fixed to support different US systems.
