### ISSUE TITLE
In Edit Sale the Sale Date Date picker doesn't work

### ISSUE THREAD

**Issue by daN4cat** [jekkos/opensourcepos#119]
From Sales or Sale -> Overview click edit, the Edit Sale pops up.
Click the date picker and nothing happens, at least with Google Chrome it doesn't work.

**Comment by daN4cat** [comment]
From the same view the Customer line shows a number | customer name. Not sure that's on purpose or not.

**Comment by jekkos** [comment]
Yes I've spotted that bug as well, had a look at it but couldn't find a solution directly. I think most of the js plugins are terribly outdated as well.

**Comment by jekkos** [comment]
The | separator in the customer field was chosen as a workaround for the old autocomplete functionality. I think this plugin didn't support to send key-values back and forth. We might consider to upgrade the whole plugin to jquery ui, but that'll take quite some time to test for regression.

**Comment by daN4cat** [comment]
If this doesn't work maybe it's better to remove the icon and leave it as direct date entry in the box.

**Comment by jekkos** [comment]
Yes I noticed this bug as well some time ago but couldn't directly find a solution, so might be easier to remove the icon indeed.

**Comment by jekkos** [comment]
removed in 3e24b9cafff0fb957595494415cb50981c152301
