### ISSUE TITLE
Detailed Report

### ISSUE THREAD

**Issue by shifasiddeqque** [jekkos/opensourcepos#1194]
path: opensourcepos/application/views/reports/specific_input.php
While selecting only sale in reports->detailed->employee window on my browser ,why it is always displaying all 
Please tell me where i need to edit so that while selecting a specific value that may either sale or return type , it should give me that specific result and not everything linked to that employee

Thank you in advance

**Comment by daN4cat** [comment]
It's probably a bug.

**Comment by shifasiddeqque** [comment]
Yes it's a bug
Correction in selecting  name property instead of specified id
. It must target #input_type



Sideeq Shafi





On Mar 22, 2017 2:31 PM, "FrancescoUK" <notifications@github.com> wrote:

It's probably a bug.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/jekkos/opensourcepos/issues/1194#issuecomment-288336936>,
or mute the thread

**Comment by daN4cat** [comment]
If you have a fix please submit a PR. Thanks

**Comment by shifasiddeqque** [comment]
Path : application/views/reports/specific_input.php
#1197  Selecting sale or return Report
Original code
> window.location = [window.location, start_date, end_date, $('#specific_input_data').val(), $("#sale_type").val() || 0].join("/");

Edited One
# window.location = [window.location, start_date, end_date, $('#specific_input_data').val(), $("#input_type").val() || 0].join("/");

**Comment by shifasiddeqque** [comment]
i am very new to Codeigniter, i wanted some help from you please

i wanted only a specific employe to allow returns
Could you please help me on this

Thanks in advance









Thanks & Regards
Shifa Siddeqque

**Comment by daN4cat** [comment]
Thanks, the bug is fixed and in master now.

**Comment by daN4cat** [comment]
With allowing only one employee to carry out returns I'm afraid the current permission schema and rules are not allowing it.
That means you need to add the permission first and then go through the code and add the check.

The way the permissions are granted to piece of functionality at the moment is not great, I must say.
There should be a centralised location to grant permissions not only at controller/model level but even at function level and of course screen widget.
The latter is left to flags to be checked here and there in the code.... in an ideal world with plenty of time to dedicate to this project I would change that function-level part.
Unfortunately we don't have enough time and we got the same type of request in other places, e.g. allow only to selected users to delete a sale.

**Comment by jekkos** [comment]
In java this is typically solved using annotations and a bit of aspect oriented programming. For hiding or showing specific html in the views one could try to make a nested template defining which grants it need to be displayed. haven't checked if something like this exsists in PHP

**Comment by daN4cat** [comment]
Would be good to check as there is a clear need for function level permission granting. I didn't have the time to check myself yet.

**Comment by shifasiddeqque** [comment]
Thank you so much for reverting back , actually i am working in a corporate
office and they are using ospos for a while now.
As i am new joinee i am yet to fully understand ospos.The manager assigned
me this task to give permissions to a specific employee to have a access to
return window..

Could you please tell me where to get more information what i mean  by
saying
 Are there any videos that will help us to understand the project?? .












Thanks & Regards
Shifa Siddeqque

**Comment by daN4cat** [comment]
And do you plan to contribute your work here or would that be something your corporation wants to keep for themselves?

**Comment by jekkos** [comment]
http://symfony.com/doc/current/bundles/SensioFrameworkExtraBundle/annotations/security.html

Is an example on how it could be done in PHP.

**Comment by daN4cat** [comment]
Using annotations. .... I would search if something is available for CI. Somebody must have faced and solved this problem already.

**Comment by shifasiddeqque** [comment]
For now corporation is planning for themselves let it be implemented first









Thanks & Regards
Shifa Siddeqque

**Comment by shifasiddeqque** [comment]
if you get something please do share your work ,

thank you in advance









Thanks & Regards
Shifa Siddeqque

**Comment by daN4cat** [comment]
I don't get, you implement and not share is that what you meant?

**Comment by shifasiddeqque** [comment]
i mean Does anybody know how to implement this??










Thanks & Regards
Shifa Siddeqque

**Comment by shifasiddeqque** [comment]
Could you please help me in understanding the flow of ospos??











Thanks & Regards
Shifa Siddeqque

**Comment by shifasiddeqque** [comment]
Hi Francesco
i need to add a new module  to ospos
for that i have added that new module  in database->ospos_modules
but while selecting that module in employe->permissions-
i get ErrorAdding/updating employee name

Please Help









Thanks & Regards
Shifa Siddeqque
