### ISSUE TITLE
Translation Pt-BR

### ISSUE THREAD

**Issue by arteiro** [jekkos/opensourcepos#1195]
Please download the Portuguese-Brazil weblate translation

**Comment by jekkos** [comment]
Ok there were just two strings added in config_lang. Is this correct? Overall translation percentage is down to 93% now after I did the translation refresh round trip (meaning I used the my Java tool to go to CSV and then back to PHP).

**Comment by jekkos** [comment]
Seems that for the source language weblate is not adding the keys to other languages, this needs to be done manually once.

**Comment by arteiro** [comment]
256/5000
Sorry, I do not understand.
I did the translations pointed out, but I did not have access to the files where they show the inclusions, but if you see any problems, if I pass the files sent to weblate I can fazzer the corrections and mark a more complete translation.
