### ISSUE TITLE
Add proper enumeration support

### ISSUE THREAD

**Issue by daN4cat** [jekkos/opensourcepos#1198]
Currently enumerations are done with strings, or numeric strings.

We should consider adopting a solution like this one: https://github.com/myclabs/php-enum

And convert all the enumerations to use that support.

**Comment by daN4cat** [comment]
Composer package added

**Comment by jekkos** [comment]
hmm too bad that PHP is such a flakey language..

**Comment by SteveIreland** [comment]
It was awesome in it's original incarnation and intent.  I'm scratching my head wondering who thought adding an object oriented facade to it was a good idea.  I can only assume it was intended to keep the young'uns interest.  :smile:

**Comment by SteveIreland** [comment]
Also ... I'm still working on the enum incarnation .... however I'll go ahead and give you a "heads up" on my progress.  I spent way too much time trying to actually use it.  I couldn't figure out the magic formula to find the enum abstract class and it seemed to be failing in the composer definition.  I tried to work my way through the autoload scripts but I ran out of time.

However, after finally giving up it occurred to me that the enum abstract class really doesn't serve OSPOS well so I'm setting up a prototype  of what's needed.  The need to integrate enum with multi-language support in OSPOS is essential and would be sweet if we can figure out how to make it  happen.  So after I get the prototype working the way I want I would like to try to design an abstract class that works better for our purposes.

**Comment by daN4cat** [comment]
@SteveIreland ok I didn't have time to play with the composer package but I'm surprised it doesn't work.
I'll see if I can find the time to give it a try and please hold the horses. I'm not that keen to reinvent the wheel and I would prefer to use existing open source libraries.

**Comment by daN4cat** [comment]
@jekkos the problem is that php is not strongly typed. So the work around is to use classes. It looks like you need to adopt the original OO philosophy where even a simple and basic variable was an object of a defined class.

**Comment by SteveIreland** [comment]
@daN4cat I probably just need a working example of how to do it right.  You might remember that I was fussed at a bit about how I implemented tokens because there is a wrong way (the way I used) and the CodeIgniter way). An example of how to do that correctly would be good too.
