### ISSUE TITLE
CI 3 

### ISSUE THREAD

**Issue by rfulcher** [jekkos/opensourcepos#120]
Are there any plans to upgrade the CI version to 3?  Are there any known issues with doing that?

Thanks

**Comment by jekkos** [comment]
I haven't looked into that yet. Is there any new functionality that could be of use for the project?

**Comment by rfulcher** [comment]
That is a good question.  There is a lot of small things but this post talks about many of them.

http://www.quora.com/What-are-the-differences-between-CodeIgniter-2x-and-3x

Thanks

**Comment by daN4cat** [comment]
I think the point here should be: how much work would be to upgrade to CI3?
If we get more with no impact there is a point to keep up with the latest, assuming CI3 is stable.
But if we are breaking a number of things it's probably better to stabilise some features with this release and upgrade to CI3 in a next release and do just that one.

**Comment by rfulcher** [comment]
Well I have upgraded several project to CI3.  There will be bumps and things that need to be fixed for sure.  It will bread some things just because of some of the conventions that have changed.   So it would not be smooth.  But CI3 is very stable.  If you are close to the next release I would hold off and think about CI3 for the next one.  

Thanks for considering it.

**Comment by daN4cat** [comment]
One benefit for sure would be the group_start() and group_end() for the query statements like ... AND ( ... OR ... OR ... )

**Comment by daN4cat** [comment]
Some other benefit mentioned in #157 discussion (REST API).

**Comment by jekkos** [comment]
Ok i didn't know about the group method. MIght indeed be cleaner to use that instead of hardcoding the query in text. The latter also introduces some more security risks.

**Comment by daN4cat** [comment]
Yes the group statement would be nice indeed. I had a couple of examples in the code where I did all the query in text.

Maybe CI3 is a topic for 2.3.4 / 2.4 (not sure what's next)?

**Comment by jekkos** [comment]
@yllumi I saw that you have a branch with integration of CI3. We currently have #120 opened for this one. Are you able to get it running with that new version?

**Comment by daN4cat** [comment]
I've taken @yllumi ci3 branch and rebased with the latest master + applied changes to config.php and database.php.tmpl that somehow were missing in yllumi upgrades, and pushed everything to my git under a ci3 branch.

Please note that the branch comes with a partial update of the ui look'n'feel, because bootstrap is enabled.

I'll try to finish the changes to other parts like buttons, but I would much appreciate some help with that as UI is not really my strongest point. However if you bare with me I'll do the upgrade.

Please also note that I marked this version 2.4, so we don't risk to mixup versions.

**Comment by daN4cat** [comment]
I forgot to say that everything works and just the UI seems unfinished, but CI3.0.3 seems working.

I would need to review better the changes against the guideline: http://www.codeigniter.com/userguide3/installation/upgrade_300.html

Also there are configuration parameters that probably require a bit of more attention in general.

So more to work....

**Comment by daN4cat** [comment]
I found that the language support doesn't work properly (yet), so more to be fixed.

**Comment by daN4cat** [comment]
I'll probably split out the UI changes to leave the branch with just the CI 3.0.3 upgrade and focus on one step at time. Mixing up the two makes things more difficult.

**Comment by daN4cat** [comment]
Now my ci3 branch does not contain the bootstrap UI changes.
However I didn't have time to test it, so proceed at risk.

The UI part is in another branch bootstrapUI, which is rebased from ci3.

**Comment by jekkos** [comment]
Yes probably best to split out the UI + CI3 changes, so we can test those independently. I will have a look at your branch and read some of the CI upgrade docs next week.

**Comment by daN4cat** [comment]
My ci3 branch is up to date with the latest and I've briefly tested and it seems working (the basics)

**Comment by daN4cat** [comment]
I spotted one issue with ci3, in Items the range selection doesn't work. Something to fix probably in the model. I can see that selecting deleted works fine, because in that case the data range is not used if my memory is correct.

Also I forgot to mention earlier that sessions table would need an upgrade. My current branch uses sessions directory to allow using the same test database between 2.3.3 and "2.4". I would need to change the config to use sessions table and add a script to upgrade the database.

**Comment by daN4cat** [comment]
Checking the upgrade page there are functions that now return NULL instead of FALSE.

One seems being config->item(..) that we use, but testing a bit the code it looks to me like not affecting things too much. However the code is handling the case as per manual. Something we might need to reconsider a bit.

**Comment by daN4cat** [comment]
Pagination seems not working properly either.

**Comment by daN4cat** [comment]
Issue with routes and 404_override, see #265. However that issue is present even with 2.3.x

**Comment by daN4cat** [comment]
From the upgrade guideline (http://www.codeigniter.com/userguide3/installation/upgrade_300.html):

- Step 1 is fine
- Step 2 had an issue, which I fixed with my submission to ci3 (Report.php)
- Steps 3, 4 and 5 seem fine
- Step 6 needs fixing as already reported
- Step 7 is fine
- Step 8 had an issue, which I fixed with my submission to ci3 (removed application/errors)
- Step 9 is fixed in the first part with my submission to ci3 (following the correct indication) and the 404_override needs a check in general.
- Step 10 is probably something requiring a more in deep check, as above-mentioned
- Steps 11 to 20 seem fine (I submitted a fix) but the pagination issue above-mentioned.

**Comment by daN4cat** [comment]
Rebased to latest master including the route fix. So Step 9 is now completed.

**Comment by daN4cat** [comment]
Rebased to latest master including the 404_override fix from 2.3.3. So Step 9 is now completed.

**Comment by daN4cat** [comment]
@jekkos do you want me to push ci3 to jekkos/develop/2.4 and work from there?

It's rebased of your latest master (and it's marked 2.4).

Let me know.

**Comment by jekkos** [comment]
OK sure go ahead. branch is ready.

**Comment by daN4cat** [comment]
OK, done. develop/2.4 now contains my work from ci3 which is the upgrade CI 3.0.3

I have done some more work before pushing the changes. I took the original package CI3.0.3 and I compared all the files and found that application/ was missing quite some changes.

Now all the files should be up to date correctly with CI3.0.3

There are two major issues to solve: pagination and items that doesn't work properly. As soon as you change something every disappears. But if deleted checkbox is selected works.

Maybe you can have a look into these and help to complete the work.
Maybe check the pagination story as you are probably more familiar than me with that?

**Comment by jekkos** [comment]
Ok thanks for the effort. I'll look into the pagination probably tomorrow.

**Comment by daN4cat** [comment]
@jekkos , any progress on the pagination issue?

**Comment by daN4cat** [comment]
I fixed the issues in Items, it's due to the change in input->post(..) that now returns null instead of false.
So I changed to input->post(..) != null in the controller to get true/false since it's a checkbox.

It might be that the same issue affects other parts of the code, so I would need to recheck all the input->post meant to be booleans.

**Comment by daN4cat** [comment]
I made further checks and fixes around the input->post(..) and null.

**Comment by odiea** [comment]
Thanks for all the time your putting in on OSPOS.

**Comment by daN4cat** [comment]
Thanks and be ready for the testing soon :-)

I'll have a look into pagination and I leave as last the sessions DB table change.

**Comment by daN4cat** [comment]
With regards to Pagination, CI3.0.3 introduces an attribute to the a href and removed the spacing between the links.

With the previous version as return from $this->pagination->create_links() you got:

&nbsp;<strong>1</strong>&nbsp;<a href="http://<os pos url>/index.php/items/index/20">2</a>&nbsp;<a href="http://<os pos url>/index.php/items/index/40">3</a>&nbsp;<a href="http://<os pos url>/index.php/items/index/20">&gt;</a>&nbsp;&nbsp;<a href="http://<os pos url>/index.php/items/index/1980">Last &rsaquo;</a>


With CI3.0.3 as return from $this->pagination->create_links() it's:

<strong>1</strong><a href="<os pos url>/index.php/items/index/20" data-ci-pagination-page="2">2</a><a href="<os pos url>/items/index/40" data-ci-pagination-page="3">3</a><a href="<os pos url>/index.php/items/index/20" data-ci-pagination-page="2" rel="next">&gt;</a><a href="<os pos url>/index.php/items/index/1980" data-ci-pagination-page="100">Last</a>


In the view we print the links in the following way:

<div id="pagination"><?= $links ?></div>

The div id pagination is used in manage_table.js.

And here is where I don't know how all the parts fit together and interact :-(

**Comment by daN4cat** [comment]
BTW, I noticed that in 2.3.3 (or .4) the links are not working as it should be.

If instead of `<div id="pagination"><?= $links ?></div>` writes `<p><?php echo $links; ?></p>` the result is different on the ui, links works fine with the latter and you get even 'First' where it's not the case with the former example. The only problem is that of course js script doesn't work properly with no div.

So the pagination and links story is not fine in 2.3.3 too.

**Comment by daN4cat** [comment]
Upgraded to latest CI 3.0.4.

Also fixed the pagination links padding, now using css (might this be an issue with bootstrap later?)

**Comment by odiea** [comment]
I appears it's not quite ready for testing. I am getting this error.
Server error!

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there was an error in a CGI script.

If you think this is a server error, please contact the webmaster.
Error 500
localhost
Apache/2.4.10 (Win32) OpenSSL/1.0.1i PHP/5.5.19

**Comment by daN4cat** [comment]
OK, anything you can read from error_log?

Do you have "application/sessions"?

Maybe try removing .htaccess and give a try.

**Comment by odiea** [comment]
Sorry not much help here. I do not have  "application/sessions" I removed .htaccess and had the same issue.

**Comment by daN4cat** [comment]
ok, you need to have "application/sessions", it's just a temporary thing until I don't fix the sessions DB table.

**Comment by odiea** [comment]
The current version I downloaded did not contain this. Do I need to install a sessions folder?

**Comment by daN4cat** [comment]
no, just create a sessions folder under application

**Comment by daN4cat** [comment]
BTW, do you get the error before having the login page?

**Comment by odiea** [comment]
I created a sessions folder and it contained no info. I get this error as soon as I try to start the program.

**Comment by odiea** [comment]
I was apparently editing the downloaded file and not the htdocs file. I removed  .htaccess  and now I can log into it ok.

**Comment by daN4cat** [comment]
ok :+1: 

I was expecting .htaccess to be a problem because you have a different configuration and when you said no I started checking all the latest submissions code...

**Comment by daN4cat** [comment]
I'll check and see what could be wrong with that .htaccess since I ghave Apache 2.2 and php 5.4

**Comment by odiea** [comment]
The issues so far pagination links in items are not updating. It does display 25 items per page. It will gor from page 1 to page 3 and back to page 2 but not to page 1. Page 1 indicator is always black. I also cannot add a new item. It appears in New item form neither of the buttons are functional. Items kits add works .

**Comment by odiea** [comment]
Pagination in takings also changes from page 1 to 2 to 3 but will not go back to 1. 1 is also always black instead of blue.

**Comment by odiea** [comment]
And yes sessions are showing in the sessions folder now.

**Comment by daN4cat** [comment]
Yes, I know, pagination doesn't work but I hope jekkos can help here because there must be something with js and I don't know what's the interaction there. If I do echo $links you get the links to work properly.

**Comment by odiea** [comment]
Wish I could help but I know notta about programming. It also appears the .htaccess is not needed. It does not appear in any other downloads of ospos.

**Comment by daN4cat** [comment]
I wasn't familiar with the `data-ci-pagination-page` and it's a custom attribute concept introduced with HTML5: https://www.w3.org/html/wg/drafts/html/master/single-page.html#embedding-custom-non-visible-data-with-the-data-*-attributes

**Comment by daN4cat** [comment]
OK, found it.

Using `$('#pagination').removeAttribute('data-ci-pagination-page');` in manage_tables.js before `$('#pagination').html(response.pagination);` remove the data- custom attribute that probably is causing the malfunctioning of the script.

I don't think we need that because no part of the code or javascript uses, but I guess there might better use of it if we wanted.

I could test it adding `?debug=true` after `index.php` because otherwise the minified version is used.

Now I need to remember how to run the node.js script to regenerate the js scripts (grunt).

**Comment by daN4cat** [comment]
Submitted fix to pagination issue with js regenerated.

Now only the sessions table needs a fix and then testing, and of course I need some code review.

**Comment by odiea** [comment]
Same issue with items pagination #1 is still black with no return to 1st page and now no pagination in takings. Still no ability to add a new item. Form shows but buttons do not function. I know your still updating and testing.

**Comment by daN4cat** [comment]
Yep, sorry I pushed the wrong fix.

It's not really fixed removing the custom `data-ci-pagination-page` attribute from the javascript in manage_tables.js.

This time should be fine.

**Comment by odiea** [comment]
Items pagination now working
Takings has no datepicker and no pagination -of course
Add new item button works but with the following error.
Database Error Occurred

Error Number: 1048

Column 'custom5' cannot be null

INSERT INTO `ospos_items` (`name`, `description`, `category`, `supplier_id`, `item_number`, `cost_price`, `unit_price`, `reorder_level`, `receiving_quantity`, `allow_alt_description`, `is_serialized`, `deleted`, `custom1`, `custom2`, `custom3`, `custom4`, `custom5`, `custom6`, `custom7`, `custom8`, `custom9`, `custom10`) VALUES ('have none', '', 'clothing', NULL, NULL, '1.99', '3.50', '2', '', 0, 0, 0, '', '', '', '', NULL, NULL, NULL, NULL, NULL, NULL)

Filename: C:/xampp/htdocs/ospos24/application/models/Item.php

Line Number: 223

**Comment by odiea** [comment]
IT's getting late your time. Go get some sleep.

**Comment by odiea** [comment]
Items has no date picker and it appears to be not saving qty stock when adding a new item.

**Comment by daN4cat** [comment]
Fixes are wrong, I'll revert. They cause a js error and that means I took the wrong way :-1:

**Comment by daN4cat** [comment]
The issue with `custom5` is surely due to `input->post('custom5')` returning null.

I'll check next days all the custom fields on save. I guess we will get some similar issue somewhere else due to that change in CI 3.x.x

**Comment by daN4cat** [comment]
Fix to pagination issue posted by Jekkos. Many thanks!!!!

I can now focus on custom fields issues and sessions table update.

**Comment by jekkos** [comment]
Damned now I lost my comment, can you perhaps get it back from mail notification and repost it in the correct issue number?

**Comment by jekkos** [comment]
The annoying thing is now that we're not upgrade proof.. So that's another reason why I'd like to have that fix included in CI (or have them propose another workaround)

**Comment by daN4cat** [comment]
At least we have a fix. I was really scratching my head as I thought it was a js issue.

I'll test now and great you could help out with this :+1: :+1:

**Comment by daN4cat** [comment]
BTW, re upgrade. Do we need to consider having an upgrade of this tabular views with something better and a bit of the shelf?

A lot seems patched up and I guess jQuery offers some stuff to help here.

**Comment by jekkos** [comment]
Yes I certainly think all that could be accomplished with way less code in a react js component or the like.. We could make something reusable for most screens and leave the view rendering, search, pagination to the client. 

Then the CI view would just consist of spitting out the result rows in JSON format. I think we won't even need any extra server calls once this data is inside the widget (react could use some kind of lazy load for rows not on screen), which would improve performance a lot as well. Might be worth looking into in the future.

**Comment by jekkos** [comment]
Advantage of react would be that it does not require to rewrite the whole app, as it replace the views only (in this case tabular data)

**Comment by daN4cat** [comment]
Yes, we should. For instance I noticed that current manage_table.js could contain the search bar and + / - stuff so we remove from the manage tables.

Once CI3 is sorted I'll look into that. I'll create a new issue too.

**Comment by daN4cat** [comment]
BTW, tested and your fix works perfectly!

**Comment by daN4cat** [comment]
Fixed the custom fields issue on Items . save.

@odiea you have a bit of testing to do to help here.... also jekkos fixed the .htaccess file so you may want to try the new one and see if you still have an issue.

**Comment by jekkos** [comment]
I made a PR for this fix in the CodeIgniter project #4384.

**Comment by odiea** [comment]
Good job guys. No .htaccess issues. Pagination working great in Items and Takings. I can now add an item with no database issues.The only issue I have found so far in Takings is after you change the beginning date a few times it loses all the receipts then you have to go back to the beginning date that you started at then you can start choosing dates again. Hope this makes sense to you..

**Comment by daN4cat** [comment]
@jekkos sounds good, thanks

@odiea I cannot reproduce the Takings issue, any systematic way to reproduce it?

**Comment by daN4cat** [comment]
OK, outside that if everything seems fine I'll go for the sessions table change and finger crossed we are done with upgrade to CI3 (vs 3.0.4).

**Comment by odiea** [comment]
@daN4cat It appears to involve the pagination. If I have more than 1 page say I have 2 pages. I click on the second page and all shows but when I go and chose another date while still in page 2 is when the issue seems to show.

**Comment by odiea** [comment]
I will include 2 images for you to look at. The beginning image then the new date is added.
![2016-01-18 14_59_01-ugly sweater store -- powered by os point of sale](https://cloud.githubusercontent.com/assets/10962177/12403867/4a151894-bdf4-11e5-9311-f785c6433ceb.png)
![2016-01-18 14_59_30-ugly sweater store -- powered by os point of sale](https://cloud.githubusercontent.com/assets/10962177/12403873/5346447e-bdf4-11e5-9871-3c3938566fc6.png)

**Comment by odiea** [comment]
I just tried this on the current version and it does the same thing so it's a carry over problem I never noticed before.

**Comment by daN4cat** [comment]
Many thanks for the report. So this needs to be fixed in 2.3.4. Worth creating a separate issue?

**Comment by odiea** [comment]
It appears no one else has reported or noticed  it so I will leave it up to you. There may be bigger issues to deal with.

**Comment by daN4cat** [comment]
And with this commit I changed even sessions to be stored in the database and added a SQL upgrade from 2.3.4 to 2.4 (2.3.4 has no changes from 2.3.3 at the moment).

So, we should be completed with the upgrade to CI3 (3.0.4).

I even tagged this last commit as CI-3.0.4.

**Comment by daN4cat** [comment]
I leave this open until end of the week, if no comments or more results about test performed against develop/2.4 I will close this issue marked as done.

**Comment by odiea** [comment]
Sorry. Is there a database upgrade involved with this. This is what I received when trying to get to login
A Database Error Occurred

Error Number: 1054
Unknown column 'data' in 'field list'
SELECT `data` FROM `ospos_sessions` WHERE `id` = 'ca22af506bc9d9ed1d229c957b8e282d11a92a4d'
Filename: libraries/Session/drivers/Session_database_driver.php
Line Number: 166

**Comment by daN4cat** [comment]
data is a blob, didn't the script succeeded?

-- alter sessions table
DROP TABLE `ospos_sessions`;

CREATE TABLE `ospos_sessions` (
  `id` varchar(40) NOT NULL DEFAULT '0',
  `ip_address` varchar(45) NOT NULL DEFAULT '0',
  `data` blob,
  `timestamp` int(10) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

**Comment by daN4cat** [comment]
Maybe I should have added data blob NOT NULL

**Comment by odiea** [comment]
I manually added the change and it worked but it now gives errors on previous versions.

**Comment by daN4cat** [comment]
If you use the same table you need to create a ospos_sesssions_2 with the old table schema and then change in config.php to point to sessions_2 instead of session.

**Comment by odiea** [comment]
For now I just changed the earlier version to my backup database

**Comment by odiea** [comment]
I did use your sessions_2 and now its back to working. Can you change or create this in the database script and the config .php so it works automatically?

**Comment by odiea** [comment]
So on your end you don't drop the old session table just create a new session 2 table and change the config on your end to point to session 2.

**Comment by jekkos** [comment]
Ok thanks again for the work here. Indeed I did notice some other issues on the date filtering in items which I fixed in 2.3.4, think this is already merged now.

**Comment by daN4cat** [comment]
Latest 2.3.4 is merged in 2.4 indeed.

**Comment by daN4cat** [comment]
@odiea with 2.4 we are moving forward and I don't think we should retain legacy stuff for experimental cases. For most people I would assume an upgrade and that's it, not having old and new.
Sessions is not a big deal in the end.

Therefore I'm afraid I would not change the script for that purpose.

**Comment by daN4cat** [comment]
Just committed two small changes and bumped the tag CI-3.0.4 to the latest commit.

**Comment by daN4cat** [comment]
Just committed three small changes and bumped the tag CI-3.0.4 to the latest commit.

**Comment by daN4cat** [comment]
BTW, @jekkos in a post in #157 you said:

`Regarding a possible redo of the application, tables might be easier to do using REST + react.js bootstrap table component (providing pagination, bootstrap layout, all sorts of filtering options, by just configuring a couple of things)

https://github.com/AllenFang/react-bootstrap-table`

**Comment by jekkos** [comment]
Yes we might not need full blown rest controllers, spitting out json from the controller or from a ci view directly might be sufficient. But that widget is very interesting indeed.

**Comment by daN4cat** [comment]
Yes, looks fantastic with all the search functionality and etc. And maybe working pagination without CI patching :-)

**Comment by daN4cat** [comment]
But that needs a switch to boostrap, we cannot have the two separate.

**Comment by odiea** [comment]
As the old expression goes "Out with the old In with the new".

**Comment by odiea** [comment]
@jekkos  What the heck is a conuter?

**Comment by daN4cat** [comment]
I bet is a typo -> counter.... I often have the same it's I guess a slight form of dyslexy when typing on a keyboard

**Comment by jekkos** [comment]
My pagination patch is merged now upstream. Once 3.0.5 then we're safe to update again.

**Comment by daN4cat** [comment]
Great, so we don't need to worry about tagging the patch going forward. Let's wait for 3.0.5 to upgrade everything again.
I guess it will take a while, so if no news about issues with CI3 I will close this and create a new issue CI3.0.5 as a reminder referencing this issue.

**Comment by daN4cat** [comment]
OK, I think I can close this issue since no new major issue were created.

If anything new as problem, we can always create a new issue.

**Comment by jekkos** [comment]
Ok thanks again for the work. I noticed one cosmetic bug, havent' checked further but suggestion box in sales seems to have a big font spacing all of a sudden.

**Comment by daN4cat** [comment]
Yes, it looks like the highlighted part of the string is separate by a space and put in bold. Maybe it's because is in bold. Not sure. It's indeed a small user experience bug not a functional one, I'll create a separate issue for that.

**Comment by daN4cat** [comment]
The same is with Items search suggestion. I believe this is a general pattern with the search suggestions.
