### ISSUE TITLE
Installation Help

### ISSUE THREAD

**Issue by ebenezery4** [jekkos/opensourcepos#1200]
I have tried to install this application several times but unable to do so unlike the older versions that has the index.php page just outside the main directory but this version i find it difficult to locate where to go and what to do after editing the config file and renaming the database.php file to reflect my configuration onmy local server i try to follow the installation instruction on the main page by locating the public folder but all i got is a black page and if i tried to use the bin directory and call the installation.php script from my browser i got an htaccess error. i need help on what to do

**Comment by odiea** [comment]
Fill out the needed information requested in the template.

**Comment by ebenezery4** [comment]
Which template please

**Comment by daN4cat** [comment]
The issue template that compared when you create a new issue.
No filled check boxes no answers.

**Comment by ebenezery4** [comment]
I was able to fix my issue Thanks

**Comment by odiea** [comment]
And what was the cause of your issue?

**Comment by ebenezery4** [comment]
i really don;t know but i had to uninstall the xampp version am using and
re install an upgrade version and it works perfectly i have missed a lot
because all the interface of the application has changed compared to when
it was still available on sourceforge.... Thanks

**Comment by daN4cat** [comment]
Aha, so you had xampp.... I guess we should have guessed that using a crystal ball or something down that line...

**Comment by ebenezery4** [comment]
i actually have another issue which is if i login to the app i wouldn't be
able to do anything as if a modal window is blocking the and i dont know
why that is happening screen.  any help regards that issue

**Comment by ebenezery4** [comment]
Also again i was trying to use the app  on a network do i need any special
configuration because after configure my server and i connected all the
system through the ip of my server it works but kind of very slow.

**Comment by daN4cat** [comment]
Read the FAQ

**Comment by ebenezery4** [comment]
Yes i read the faq and i noticed a line talking about directories. and i
made the changes on my htaccess file like this

# if in web root
#RewriteRule ^(.*)$ index.php?/$1 [L]

# if in subdir comment above line, uncomment below one and replace <OSPOS
path> with your path
RewriteRule ^(.*)$ /<antob>/public/index.php?/$1 [L]

because i created a folder inside my htdoc file and i named it antob which
is where the ospos files are but when i tried to reload the application on
the browser i got
Access forbidden!


error


what to do again

**Comment by ebenezery4** [comment]
i read the issues/920 and saw i  made an error on the .htaccess file and
but the issue now is that after login in the interface was showing blur and
i could not do any operation


[image: Inline images 1]

**Comment by daN4cat** [comment]
Read the FAQ again....

**Comment by ebenezery4** [comment]
Thanks i get it working perfectly now

**Comment by daN4cat** [comment]
Good

**Comment by ebenezery4** [comment]
i discovered something and i dont know the cause i noticed that when am
using the application and am not connected to the internet the application
is usually very slow but when i connect to the internet the application run
smoothly and not slow at all. what can i do to that.

**Comment by daN4cat** [comment]
Disable statistics from the Store Configuration and see if that helps.

**Comment by ebenezery4** [comment]
Bingo!!!! It solves the issue perfectly

**Comment by ebenezery4** [comment]
again am trying to play around with the application and i installed bixolon
pos printer and i install the jsprint extension too but under the confiq
store the ticket printer is still disabled i cant select anything  i was
trying to do auto print

**Comment by daN4cat** [comment]
I assume you use Firefox, right?

**Comment by ebenezery4** [comment]
yes i used firefox

**Comment by ebenezery4** [comment]
I have another issue with csv batch upload, i tried to upload a csv file of
about 600 lines but what happened is that the file will upload but the
quantity field will appear to be zero and the file i uploaded has quantity
value

**Comment by daN4cat** [comment]
Please create another issue for that and specify if that's the latest code from master or an earlier version.

**Comment by ebenezery4** [comment]
when adding new stock item using the new item module i saw that there were
some required fields like

Quantity stock

Receiving quantity

that might be where the issue is coming from.

**Comment by ebenezery4** [comment]
please is there any other way round to upload the stock item because
currently am very in need of it .

**Comment by daN4cat** [comment]
Yes there is a way, to fix the bug....
