### ISSUE TITLE
Payment Due Issue

### ISSUE THREAD

**Issue by ishtiaquesarwar** [jekkos/opensourcepos#1202]
Hi
i am using version 3.0.0 and here i have encountered an issue which is completely new that is i can accept payment by cash / card / check but if a customer does not pay full amount or pays partial and remains the rest as due, in that case there is no option to mark it as due and show the same thing from report section.

Can you please guide or help me on this ! how to resolve this issue?

Regards
ishtiaque

**Comment by RamkrishnaMondal** [comment]
Play with the views/sales/form.php and get this. Thanks to daN4cat ... It's a stop_gap_solution for a lazy person like me. LOL!

![screenshot from 2017-04-13 22 39 09](https://cloud.githubusercontent.com/assets/14151032/25019712/349cad38-20a9-11e7-997f-5ca5cc33bc56.png)
