### ISSUE TITLE
Cant upload logo or product images. Please help.

### ISSUE THREAD

**Issue by jessdaddy** [jekkos/opensourcepos#1203]
Just installed version 3.02 using Softaculous. Love the POS! Just one problem I cant seem to solve. I cant upload logo images or product images. I checked permissions for folders. File and ownership are correct. 

When I try to upload, no error is given. But if I check Chrome Console the following errors are present:

Denying load of chrome-extension://pkbffbhglicfngmppdlpmpblfgnkdgio/font/fontawesome-webfont.ttf. Resources must be listed in the web_accessible_resources manifest key in order to be loaded by pages outside the extension.
opensourcepos.min.js?rel=bc5842b19a:5 POST https://kickassbbqsauce.com/ospos/public/config/save_info/ 500 ()

Is there anything else I can check. I saw there was a similar issue last year, but no fix was ever discussed. Please advise.  Thank you very much.

### Issue / Question / Bug

Before submitting an issue please make sure you remove the first section of the template and you tick (add a x between the square brakets) and agree with all the following check boxes:

- [x] Checked the current issues database and no similar issue was already discussed
- [x] Read the README, WHATS_NEW and UPGRADE
- [x] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php5-gd, php-intl and sockets installed)
- [x] Reporting an issue of an unmodified OSPOS installation
- [x] PHP version is at least 5.5 and not 7.x
- [x] MySQL version is 5.5 or 5.6 and not 5.7
- [x] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [x] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [x] Know the name and version of OS, Web server and MySQL and will add to my issue report

### Installation information
Installed with Softaculous through CPanel. 

You are using Open Source Point Of Sale Version 3.0.2 - 4f5ad57. Please visit my	website to learn the latest information about the project

### Expected behaviour
Can upload logo or product images.

### Actual behaviour

Cannot upload images.
### Steps to reproduce the issue

**Comment by jessdaddy** [comment]
Oh, FYI. Same in FF, Edge, IE, SeaMonkey and Chromium if that makes a difference. Thanks

**Comment by jekkos** [comment]
Sorry we don't support third party platforms. Maybe check docker cloud setup if you want to have upload working out of the box. Thanks.

**Comment by jekkos** [comment]
These kind of issues are always setup related. We can only provide support for a managable amout of setups which are described here in the project documentation

**Comment by jnar** [comment]
I, just maged to solve this.  In my case was related to bitnami Wamp not loading php extension php_fileinfo.dll, check this: https://stackoverflow.com/a/40544223

**Comment by daN4cat** [comment]
I will add this php extension check at login time with log dumping to error_log so we get sorted all these extension problems
