### ISSUE TITLE
Idea proposal

### ISSUE THREAD

**Issue by Elhy** [jekkos/opensourcepos#1209]
Hello,

Your application is superb.

Just an idea that could improve it.
Most large customers do not pay their purchase immediately if they place orders.
So it might be interesting if there will be a "pending" payment type with a payment period for each invoice, and also a type of alert to inform that some customers have to make payment for their purchase because the delay is achieved... :)
That way, we can make a sale, and give an invoice to the customer, even if the payment has not yet been made.

And finally, that this application also will have a possibility to create an order form and a pro forma invoice.

It's just an idea.

Elhy

**Comment by daN4cat** [comment]
Discussed few times...

**Comment by daN4cat** [comment]
BTW pro forma invoice should be supported with the latest in master.

**Comment by SteveIreland** [comment]
Sale by Invoice is designed for this purpose ... however OSPOS doesn't provide any payment receivables functionality so you'll need additional software for that.
