### ISSUE TITLE
Items: check deleted and search for an item, no suggestion from deleted items

### ISSUE THREAD

**Issue by daN4cat** [jekkos/opensourcepos#121]
Tested this with Chrome on Windows, Chromium and Firefox on Linux and the same result.
The suggestion doesn't show the deleted items when the deleted check box is selected.
However the search results are correct if one person types enter to the searched word.

It's the suggestion that doesn't work.

**Comment by jekkos** [comment]
Can't reproduce this issue currently (screenshot)

![screenshot from 2015-08-21 12 14 28](https://cloud.githubusercontent.com/assets/576234/9406230/d85f52ac-47fe-11e5-83bb-2a49b89bb823.png)

**Comment by daN4cat** [comment]
I need to check that my code is correct and then try again. I don't know what else to say because I have the issue and I'm using a real database copy for my tests.
I'm searching the first line and if I keep adding A there is nothing shown.

![image](https://cloud.githubusercontent.com/assets/636048/9413083/9295b328-4827-11e5-86af-236632570763.png)

**Comment by daN4cat** [comment]
What is shown in the suggestion are all non-deleted items. In the above test I used Chrome.

**Comment by jekkos** [comment]
So when you choose one and hit search then nothing shows up? Can you try and append ?debug=true after the url? It will load the uncompressed javascript (ready for debug)

And you're absolutely certain that you're using the latest? I can see the is_deleted flag appearing in the debugger in the item module and it's set to 1 in case I check the checkbox. Also double checked that in firebug and it's present there as well . If I uncheck it's set to 0, as it should. Also I get no results in the suggestions when searching for deleted items (just one imac). If I enable the deleted button the suggestion shows up and when I hit search it show the results correctly.

**Comment by daN4cat** [comment]
It's fine, works now. Somehow I didn't upload the newer files in dist and then I made sure javascripts were not cached clearing it completely.

Sorry for the inconvenience caused.
