### ISSUE TITLE
Http Error 500 Wamp

### ISSUE THREAD

**Issue by khan-07** [jekkos/opensourcepos#1210]
- [x] Checked the current issues database and no similar issue was already discussed
- [x] Read the README, WHATS_NEW and UPGRADE
- [x] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php5-gd, php-intl and sockets installed)
- [x] Reporting an issue of an unmodified OSPOS installation
- [x] PHP version is at least 5.5 and not 7.x
- [] MySQL version is 5.5 or 5.6 and not 5.7
- [] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [x] Know the name and version of OS, Web server and MySQL and will add to my issue report

### Installation information

Wamp 3..0.6 64 bit
Php version:5.6.25
Apache version:2.4.23
MySql version:5.7.14

OS; Windows 7

I have read some other threads where people have been instructed to use mysql 5.6 but it is clearly written in the ReadMe that mysql 5.7 is supported.

### Expected behaviour

When i navigate to the **//localhost/opensourcepos-master/public/**, instead of showing me the home/login page it gives an error.

### Actual behaviour

Following error is shown.

localhost is currently unable to handle this request.
HTTP ERROR 500

Thanks in Anticipation

**Comment by odiea** [comment]
Read the issues and the Wiki.
