### ISSUE TITLE
Fresh Install HTTP Error 500

### ISSUE THREAD

**Issue by saurabh261187** [jekkos/opensourcepos#1211]
### Installation information

Running on a Linode with Virtualmin on a primary domain www.nextech.in
Apache/2.4.6
PHP version: 5.6.25
Server type: MariaDB 5.5.52
Followed all Setup instructions and have gone through FAQ

### Expected behaviour

Login screen should be visible.

### Actual behaviour

I see an HTTP Error 500 page when I goto www.nextech.in/public/

Kindly help.

**Comment by odiea** [comment]
With search type in error 500 and see if any of the issues were fixed.

**Comment by daN4cat** [comment]
Read past issues

**Comment by khan-07** [comment]
@saurabh261187 If you find a solution to this problem kindly post your solution here. I have the same issue , i have read multiple threads most of which do not address the issue or if they do, do not work for me.  I have tried running the project using mamp while i am able to login but some pages are unresponsive.

**Comment by daN4cat** [comment]
By the way none of you reports which version you are using.

**Comment by khan-07** [comment]
I was not even able to even open the login page using wamp. So i was not able to see the version either. If it helps, i just downloaded the compressed master branch.

**Comment by daN4cat** [comment]
And what did you download?

**Comment by khan-07** [comment]
Zipped code from this link, [opensourepos](https://github.com/jekkos/opensourcepos). Anyway thanks for the help, i was able to run it using the docker image. I will try running with wamp again and if it works i'll post it as the answer to my thread.

**Comment by daN4cat** [comment]
Please check the wiki page about WAMP and upgrade that one.

**Comment by saurabh261187** [comment]
By the way, OSPOS should be accessed at nextech.in or nextech.in/public ? I am using 3.1.0 . As of now, I havent found a solution.

**Comment by daN4cat** [comment]
Your web root should be public dir
