### ISSUE TITLE
Help Regarding Local Docker Deployment

### ISSUE THREAD

**Issue by khan-07** [jekkos/opensourcepos#1212]
- [x] Checked the current issues database and no similar issue was already discussed
- [x] Read the README, WHATS_NEW and UPGRADE
- [x] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php5-gd, php-intl and sockets installed)
- [x] Reporting an issue of an unmodified OSPOS installation
- [x] PHP version is at least 5.5 and not 7.x
- [x] Know the name and version of OS, Web server and MySQL and will add to my issue report

##Installation Information

Os:Windows 7
Docker Toolbox

After trying wamp and xampp with no or partial success. I have installed the docker toolbox and followed the local install docker instruction. This is my first time using docker. I have run the commands docker-compose install and docker-compose up in unzipped opposesource-master directory.  What do i do next ?Where is the apache and mysql process running ? How do i access the web page ?

**Comment by odiea** [comment]
You must not have had all the extensions enabled in Xampp or Wamp.

**Comment by jekkos** [comment]
No you should not need wamp or whatever, docker should do the install for you.
Once compose is up you can head for localhost url which should show the application.

**Comment by AhsenKh** [comment]
Is there a guide present or if anyone can produce some document on docker? I also have some lack of understanding regarding docker. Most importantly, why my local docker installation requires internet connection to run? My guess is that database is present on cloud.

**Comment by mckaygerhard** [comment]
same for me, all the complete proyect inclusivelly the downloaded files ask for network connection.. i post this prevously and i was silenced

**Comment by mckaygerhard** [comment]
but here if you will use docker, of cource at leas need access docker using a network and please dont tell me you setupd docker in guiindows.. use a real docker under linux

**Comment by AhsenKh** [comment]
I am using docker in Windows 10. Why, what's the concern?

**Comment by jekkos** [comment]
You should be able to run offline once the whole docker image is built. I use it like as my dev setup and often without internet on the train. Maybe also check statistics are disabled in the configuration settings

**Comment by mckaygerhard** [comment]
@jekkos have right in part, and the other fault comes from w-gu-indows poor OS to manager memory in the browser.. let's see with a low end machine with 4G ram and 2Ghz cpu:

* using any OS but in chromium browser version 38 works perfectly
* using poor OS like guindows but lasted google-chrome browser hangs if records are more than 1000+
* using debian with LXDE and firefox 28 browser works but if have 8G ram
* using debian with other desktop like gnomepuach and lasted browser, hangs if are more that 1000

in others hangs mayor export work happened at the cliient side, at the server side, never hangs for me due i used a very older debian lenny with tuned php and hiawatta, apache2 its terrible slower and the sorks web server of the world.. only used to tested the ospos due its the server that used here..

so i cant said any conclusions here due the export of all records depends in many terms of the browser and of the management of the os..

**Comment by AhsenKh** [comment]
@jekkos I had the opportunity to test it offline, and to my surprise, it worked. I didn't know it the whole time. However, here's the catch, it was about 15-20+ time slower for some reason.

I mean, a simple login took around 15 seconds. But when I reconnected to the internet, it went smooth. Why is it so?

**Comment by mckaygerhard** [comment]
happened too as i said.. some resources are took from network, specially in login process its very slow if there's no internet

**Comment by daN4cat** [comment]
Disable statistics from the configuration

**Comment by mckaygerhard** [comment]
new bug for network request: `[Mon Dec 18 10:04:43.651441 2017] [:error] [pid 15482] [client 127.0.0.1:46360] Analytics Host not reachable! Error: Connection refused, referer: http://127.0.0.1/opensourcepos/public/index.php/reports` i nissue #1755 on some reports.. so this issue was valid

**Comment by AhsenKh** [comment]
Hello, one more thing I want to make sure. When I take database backup, it gives me **ospos.sql** file. Now this file is to replace **database>database.sql** if I need to restore the backup during a fresh installation, right? (Fresh installation through xampp **OR** even _docker_).
