### ISSUE TITLE
Employees Authorizations

### ISSUE THREAD

**Issue by corslayth001** [jekkos/opensourcepos#1213]
Hello guys, In advance I would like to thank you for the great work 👍 next I would like to ask you for a new Feature :)  

An option in which the employees can only visualize the items, I mean they can not add or change the information or the stock of the items, I was trying to do it but i haven't got it :(

I can help to contribute with the work

Have a nice day

**Comment by daN4cat** [comment]
Already discussed. Please check current open issues.
