### ISSUE TITLE
STOCK ITEM BATCH  UPLOAD ISSUE

### ISSUE THREAD

**Issue by ebenezery4** [jekkos/opensourcepos#1214]
Hello 
I discovered a bug when trying to bulk upload stock using csv import item module and the issue is i tried to upload a csv file of about 600 lines but what happened is that the file will upload but the quantity field will appear to be zero and the file i uploaded has quantity value.

I am using the latest version of the OSPOS (3.1.0)

**Comment by daN4cat** [comment]
Thank you for the testing and report, this is useful information.

**Comment by SteveIreland** [comment]
@daN4cat If you don't mind I'll pick this one up since it probably is a result of something that I introduced and I need to do something like this form my client anyway - so it's another learning opportunity.

**Comment by SteveIreland** [comment]
@ebenezery4 Just so that I understand the urgency of the situation.  You didn't say that you were testing 3.1.0.   Are you using 3.1.0 in a production environment?

**Comment by ebenezery4** [comment]
yes am using it in a production enironment

**Comment by daN4cat** [comment]
@SteveIreland happy for you to fix. Use a different PR for the fix that will merge straight away.

**Comment by ebenezery4** [comment]
what is different PR if i may ask

**Comment by daN4cat** [comment]
Don't worry, something Steve needs to deal with and understand.

**Comment by odiea** [comment]
This is strange. I just tried this and qtys do not show anywhere but here,
![2017-04-05 15_16_04-open source point of sale _ powered by ospos 3 1 0](https://cloud.githubusercontent.com/assets/10962177/24727367/f7f95706-1a12-11e7-9002-af0e452f22fe.png)

**Comment by SteveIreland** [comment]
Odd ... I ran the same test from a download of the jekkos master 3.1.0 branch that I made yesterday and it works fine ... the current quantity had 100 and inventory tracking updated with a quantity of 100.

I've been working through the logic using the sales tax feature branch and haven't found any data issues (although I am trying to figure how why I'm not getting a Successful message back yet when I repeat the import I properly get the Failed message back.)

So far I have not been able to recreate the issue reported by @ebenezery4.

@ebenezery4  One followup question I have ... is there anything special about the stock location id that you populated the spreadsheet with?  Are you using something other than the default stock location?

I'm anticipating receiving a CSV item file with a couple of thousand items either Thursday or Friday so I will have more data to break the system with.

**Comment by daN4cat** [comment]
@SteveIreland about the no success message I remember something was fixed about that point about a year ago. I see if I can remember what the problem was....

**Comment by odiea** [comment]
I did not get this issues again other than the First time I tried uploading the file and then a refresh showed everything ok.

**Comment by ebenezery4** [comment]
@SteveIreland <https://github.com/SteveIreland> yes i think i made a change
to the stock location id on the spreadsheet i uploaded. i changed it to 2
based on the id of the location i want the the stock to be..because am
uploading to a location named supermat and i checked the id from the
database which is what i used to prepare the spreadsheet.

**Comment by SteveIreland** [comment]
Okay.  I'll try to replicate that scenario tomorrow. I was unable to do anything on this today.

**Comment by ebenezery4** [comment]
ok but what if i uploaded with the default  location id will everything be
ok i mean the qty will appear as it is in the file am uploading

**Comment by ebenezery4** [comment]
Ok this is what i got when i uploaded with the default location id... but
the error message is what i dont know the cause and i have attached the
file am using for the upload incase


[image: Inline images 1]

**Comment by ebenezery4** [comment]
![image](https://cloud.githubusercontent.com/assets/17982781/24797851/0f3b911c-1b8b-11e7-8a6a-f95b153eaadc.png)

**Comment by SteveIreland** [comment]
I was able to replicate the issue when I assigned the stock id to 2 instead of one.  So I'll try to address this issue over the weekend.

**Comment by SteveIreland** [comment]
@jekkos @daN4cat Although I can't find it now, I believe I saw a comment suggesting that there needed to be an item_quantity entry for each item (an possibly each item and location quantity). 

If the item is non-stock would you be opposed to changing the system so that we don't need to have those records.  It would just be a matter of changing any inner joins to outer joins (with, I'm sure, a few surprise nuances).

**Comment by daN4cat** [comment]
And changing where?

**Comment by ebenezery4** [comment]
I there any solution to the error it display while uploading the file
because i noticed that it does not upload all the rows i have in excel.

**Comment by SteveIreland** [comment]
@daN4cat I successfully uploaded about 10,000 items today ... fortunately I didn't need to upload any quantities yet.    It goes rather nice. I took another look at the code and noticed that the upload provides for populating quantities for multiple locations but it appears to assume that the the quantities need to be added as location1, quantity1, location2, quantity2, location3, quantity3, etc and this multiple of stock locations must be at the end of the spreadsheet.  However, the spreadsheet documents a column for picture locked in at column 26.  So, my recommended fix is to move the picture column before the stock column and restore the ability to import multiple stock locations.

**Comment by SteveIreland** [comment]
Since it was a relatively trivial fix I went ahead and submitted a pull request for it.

**Comment by daN4cat** [comment]
Great thanks. I'll check it later and merge.

**Comment by daN4cat** [comment]
Merged the fix

**Comment by daN4cat** [comment]
Thanks @SteveIreland for the help.

**Comment by ebenezery4** [comment]
Ok thanks for the fix. But what do i do now should i go ahead band download
the master file again and resetup without changing the database in order to
get the fix on my system

**Comment by daN4cat** [comment]
You can just change the files I committed to master. No need for db upgrade.

**Comment by ebenezery4** [comment]
Ok thanks

**Comment by bill-goldberg** [comment]
@ebenezery4  your ospos is not running in a browser . I am also trying to make it standalone application
Can you guide me about this?
