### ISSUE TITLE
2 navbar links are gone when site is in Dutch

### ISSUE THREAD

**Issue by IxFail** [jekkos/opensourcepos#1216]
### Issue / Question / Bug

Before submitting an issue please make sure you remove the first section of the template and you tick (add a x between the square brakets) and agree with all the following check boxes:

- [X] Checked the current issues database and no similar issue was already discussed
- [X] Read the README, WHATS_NEW and UPGRADE
- [X] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php5-gd, php-intl and sockets installed)
- [X] Reporting an issue of an unmodified OSPOS installation
- [X] PHP version is at least 5.5 and not 7.x
- [X] MySQL version is 5.5 or 5.6 and not 5.7
- [X] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [X] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [X] Know the name and version of OS, Web server and MySQL and will add to my issue report

### Installation information
Ubuntu: 14.04.1
Apache: 2.4.7 (Ubuntu)
MySQL: 5.5.54
OPOS: Version 3.1.0 - 4f5ad57

When I was setting up a new Ubuntu machine with OPOS I came across the following problem:
2 navbar links are gone when site is in Dutch
### Expected behaviour
Translation of Table & Reward should be shown.

### Actual behaviour
Empty space which is clickable to the page.
DUTCH:
![image](https://cloud.githubusercontent.com/assets/1544552/24714138/f4f4150e-1a27-11e7-81d8-28b75220d084.png)
![image](https://cloud.githubusercontent.com/assets/1544552/24714142/f911571e-1a27-11e7-9806-7bb167f5aa3a.png)

ENGLISH:
![image](https://cloud.githubusercontent.com/assets/1544552/24714150/fd726e4c-1a27-11e7-8f75-85e7c294cef1.png)
![image](https://cloud.githubusercontent.com/assets/1544552/24714154/ff95c4b2-1a27-11e7-9e3b-ea20694fac83.png)

### Steps to reproduce the issue
Set languages to Dutch

**Comment by daN4cat** [comment]
Use Weblate to complete the Dutch translations.
Read the wiki to know how to...
