### ISSUE TITLE
Reports not reporting the profit on a specific customer ### Issue / Question / Bug

### ISSUE THREAD

**Issue by thegm90** [jekkos/opensourcepos#1217]
On this one particular customer, I get no reported profit. What am I doing?
![screen shot 2017-04-05 at 11 15 56 am](https://cloud.githubusercontent.com/assets/20656675/24720323/ababb612-19f1-11e7-8de8-84a60295afbe.jpg)

**Comment by SteveIreland** [comment]
This seems to be a tax configuration or reporting issue. 
What version of OSPOS are you using?  Are you using VAT tax?  Do you have taxes assigned to all of your items?

**Comment by thegm90** [comment]
Hey steve! I'm on 3.1.0 - 4f5ad57. I'm using standard tax, I'm not sure if there is a difference. I do have taxes on all items. That particular customer is tax exempt though.

**Comment by daN4cat** [comment]
There is a new tax rework coming from @SteveIreland so probably something to test for him in that context.

**Comment by thegm90** [comment]
Right on, so it's a known issue then? Sorry I didn't see anything stating.

**Comment by daN4cat** [comment]
The tax part is under rework by @SteveIreland let's wait for him to test and confirm this use case is covered and fine in his branch. I hope I can review that code over the weekend.

**Comment by thegm90** [comment]
Very cool!! Thanks so much fellas, stunning work on the POS :)

**Comment by thegm90** [comment]
Any updates on the tax issue? :)

**Comment by daN4cat** [comment]
@thegm90 now in master and test is more than welcome. If any issue please report that @SteveIreland will look into it and fix.

**Comment by thegm90** [comment]
I'm not understanding, should I update something?

**Comment by daN4cat** [comment]
@thegm90 Take the latest from master, the 3.1.0 that is under work, then make sure you have run all the upgrade steps from the 3.0.2_to_3.1.0.sql script, if you have partially done that already you need to take the upgrade section from the last version you used.
Please use a copy of your database, don't use the original as if you want to go back with the code you won't be able without reverting the database.

**Comment by daN4cat** [comment]
@thegm90 is it fine now?

**Comment by thegm90** [comment]
Sorry for my lack of reply @daN4cat ! My brother is the one who can update this for me, and he's been busy. He will be trying to update out tonight. I'm sure you guys did an awesome job, as you have with everything else. I will report back either way to let you know our findings.

Thank you all for the support and the great software! :)
