### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by shayolz** [jekkos/opensourcepos#1218]
Hello guys, i'm trying this software that seems very good. I'm setting up on my Debian server.

I folowed the guide, i installed the DB and i changed the DB connection info. Then i gone to:

buy/bin/install.php

And this is what the page show:

#!/usr/bin/env php You can install: Translations for CodeIgniter System Messages (translations) CodeIgniter Rest Server (restserver) Codeigniter Matches CLI (matches-cli) CodeIgniter HMVC Modules (jenssegers) (hmvc-modules) Modular Extensions - HMVC (wiredesignz) (modular-extensions-hmvc) Codeigniter Ion Auth (ion-auth) CodeIgniter3 Filename Checker (filename-checker) Usage: php install.php Examples: php translations 3.0.0 php restserver 2.7.2 php matches-cli master php hmvc-modules master php modular-extensions-hmvc codeigniter-3.x php ion-auth 2 php filename-checker master 

I don't know what i must to do, what's the problem?

Thank you

**Comment by shayolz** [comment]
Can someone give me and advice?

Grettings

**Comment by daN4cat** [comment]
There is no installation script.
Read the readme and install instructions before posting an issue.

**Comment by shayolz** [comment]
I'm blocked at poit 7.

7. Go to your point of sale install public dir via the browser
8. LOGIN using
  * username: admin 
  * password: pointofsale

**Comment by daN4cat** [comment]
And read the FAQ

**Comment by peepsnet** [comment]
Browse to http://yourURL.you/installfolder/public
