### ISSUE TITLE
Items available in the database but not showing in the Items Module

### ISSUE THREAD

**Issue by bill-goldberg** [jekkos/opensourcepos#1219]
### IMPORTANT IMPORTANT IMPORTANT

Chose what you want to report: New Feature or Bug.
If you remove the template when submitting a Bug your issue will be closed as we cannot help without basic information.

### New Feature / Enhacement

For New Features or Enhacements please remove all the template text and clearly write your proposal.
It's important to state whether you expect the community to implement it or you will contribute the work.
Please bear in mind that we will implement new features only on the current code, there is no support for old versions.

### Issue / Question / Bug

Before submitting an issue please make sure you remove the first section of the template and you tick (add a x between the square brakets) and agree with all the following check boxes:

- [x] Checked the current issues database and no similar issue was already discussed
- [x] Read the README, WHATS_NEW and UPGRADE
- [x] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php5-gd, php-intl and sockets installed)
- [x] Reporting an issue of an unmodified OSPOS installation
- [x] PHP version is at least 5.5 and not 7.x
- [x] MySQL version is 5.5 or 5.6 and not 5.7
- [x] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [x] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [x] Know the name and version of OS, Web server and MySQL and will add to my issue report

### Installation information
Windows 10 x64
Google Chrome v56
WAMP 2.5 x64
Apache 2.4
MySQL 5.6
PHP 5.5

### Steps to reproduce the issue

**Comment by jekkos** [comment]
Do you have inventory records for these items in your database? Filling up the items table only is not sufficient to have stuff showing in the items page.

**Comment by bill-goldberg** [comment]
Issue here that items has been loaded in DB via Excel Import features from UI.  Then we have taken the DB backup using mysqldump. Added the Foreign key=0 & 1 while restoring on Windows 7 Laptop.    After the restore, Items are not visible in application however in DB we see this items. when i do restore the same on windows 10 ... the items were showing in the module.

**Comment by daN4cat** [comment]
If you don't have the inventory table you won't see the items from the items module.

**Comment by abidalimunnanc** [comment]
bar charts on graphics summery is not showing. summery but summery reports are showing
