### ISSUE TITLE
Column to separate sale/return

### ISSUE THREAD

**Issue by gituncar** [jekkos/opensourcepos#122]
If possible add column on db, for this table to separate regular sales vs return.

`opensourceposweb`.`ospos_sales`
(`sale_time`,
`customer_id`,
`employee_id`,
`comment`,
`invoice_number`,
`sale_id`,
sale_type, 'sale or return'
)

Also add consecutive number to invoice_number on when create some invoice.

**Comment by jekkos** [comment]
Sale or receiving mode is used as a kind of modus operandi, as you could easily add negative amounts to a sale (in sale mode) which in this case would make it a return. You can easily look for negative quantities in either sale_item or receiving_items.

If you want a quick and easy solution for yourself, then just create a database view on top of the exsiting sales and receivings tables that checks whether there's at least one negative amount in a sale_item or receiving_item and shows the sale_type output accordingly.

**Comment by gituncar** [comment]
thanks. I will create db view, on future release, if possible add some view or field to quick separate sale vs return.

**Comment by jekkos** [comment]
Adding a field would mean that most of the existing queries in reporting will need to be redone (they check for negative quantities right now) to keep the logic consistent as a whole.

**Comment by daN4cat** [comment]
I think the logic positive/negative works just fine, redo a lot of work through out the code to split things in two part doesn't make that much sense to me.
