### ISSUE TITLE
Bug : Error 500 after login v3.0.2

### ISSUE THREAD

**Issue by acericonia** [jekkos/opensourcepos#1220]
After fallowing all the steps of installation and login with the default login and password I get a error 500 ans the homepage doesn't display.

I think I already submit this issue at the pass for oldest version and event in the 3.0.2 and this was not fixed event when I search this error and found some answer said that it was fix.

How can I fix this error and why the developer teams don't take this issue seriously.

### Installation information

OS : windows 10 pro 64 bit
SERVER WEB : Xampp with PHP 7.1

**Comment by odiea** [comment]
Check your php.in and make sure all the needed extensions are enabled. I have only been using Xampp and have no issues when the directions are followed. Check the wiki under xampp.

**Comment by acericonia** [comment]
thanks for your replay,

I check all is OK but noting change the error. Can you tell me which version of Xampp you'r using ?

Best regard.

**Comment by odiea** [comment]
I am currently using xampp-win32-7.0.13-1-VC14-installer.exe on Windows 10.

**Comment by daN4cat** [comment]
Php 7 or mysql 5.6 with 3.0.2 are no good.

**Comment by odiea** [comment]
Have you deletes your current history in your browser?

**Comment by acericonia** [comment]
Yes I done deleting all history, cookies and caches in the browser and restart the browser again. Same error. And About php7 you mention @daN4cat when I check the database setting I saw the OSPOS use MySQLi so this will not cause problem with php7 that uses also MySQLi. So I will use the version you indicate @odiea above and maybe downgrade to php 5.6 to see is the error persist and return you back.
