### ISSUE TITLE
Add Custom Fields in Report filters

### ISSUE THREAD

**Issue by imperialjeff** [jekkos/opensourcepos#1222]
### IMPORTANT IMPORTANT IMPORTANT

Chose what you want to report: New Feature or Bug.
If you remove the template when submitting a Bug your issue will be closed as we cannot help without basic information.

### New Feature / Enhacement

For New Features or Enhacements please remove all the template text and clearly write your proposal.
It's important to state whether you expect the community to implement it or you will contribute the work.
Please bear in mind that we will implement new features only on the current code, there is no support for old versions.

### Issue / Question / Bug

Before submitting an issue please make sure you remove the first section of the template and you tick (add a x between the square brakets) and agree with all the following check boxes:

- [x] Checked the current issues database and no similar issue was already discussed
- [x] Read the README, WHATS_NEW and UPGRADE
- [x] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php5-gd, php-intl and sockets installed)
- [x] Reporting an issue of an unmodified OSPOS installation
- [x] PHP version is at least 5.5 and not 7.x
- [x] MySQL version is 5.5 or 5.6 and not 5.7
- [x] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [x] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [x] Know the name and version of OS, Web server and MySQL and will add to my issue report

### Installation information
Ubuntu 16.04 LTS
Firefox 52.0.2 (64-bit)
Apache/2.4.18 (Ubuntu)
mysql  Ver 14.14 Distrib 5.7.17
PHP 5.5

### Expected behaviour
Right now, we're using Custom Field 1 for Size (S, M, L, XL, XXL etc), then Custom Field 2 for Type (Mens' Shirts, Mens' Trousers, Women's Skirts, etc). And we would like to use the other Custom Fields for other product taxonomies. 

It would be perfect if I could, when viewing and generating reports, filter them according to Size and Type (Custom Field).

I'd be willing to edit files, if anyone could point out where in the MVC-structured files I should go, and provide some guidance as to what I should be looking at.

### Actual behaviour
Right now, I can only filter by Sale Type and Stock Location.

### Steps to reproduce the issue

**Comment by daN4cat** [comment]
It will be solved with #68

**Comment by daN4cat** [comment]
It will be solved with  #68
