### ISSUE TITLE
Cannot login to 3.1.0 after git clone

### ISSUE THREAD

**Issue by peepsnet** [jekkos/opensourcepos#1226]
### Issue / Question / Bug

Before submitting an issue please make sure you remove the first section of the template and you tick (add a x between the square brakets) and agree with all the following check boxes:

- [x] Checked the current issues database and no similar issue was already discussed
- [X] Read the README, WHATS_NEW and UPGRADE
- [X] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php5-gd, php-intl and sockets installed)
- [X] Reporting an issue of an unmodified OSPOS installation
- [X] PHP version is at least 5.5 and not 7.x
- [X] MySQL version is 5.5 or 5.6 and not 5.7
- [X] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [X] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [X] Know the name and version of OS, Web server and MySQL and will add to my issue report

### Installation information
I did a "git clone" of the repository to my godaddy hosting account and setup the DB using the database.sql. Varified the database and table

I am not able to login using the username and password provided by default. 

I went into my DB and changed the admin password to MD5(admin) with no luck. 

My phpinfo() tells me I have all the required extensions. 

Tired https://github.com/jekkos/opensourcepos/issues/1132 with no luck

The username and password are said to be incorrect.

Any Ideas

**Comment by daN4cat** [comment]
Md5 hashing is not the correct one and a security risk, we changed few versions ago.

I don't know why you need to fiddle with all of this but I would strongly suggest you to click the docker button on the front page and get all installed on DigitalOcean.

**Comment by peepsnet** [comment]
what is the correct encryption for the password? 

And this is OPEN SOURCE.... Seems just the reason to FIDDLE whit whatever I want

**Comment by SteveIreland** [comment]
@peepsnet 

Try http://randomkeygen.com/

It worked just fine for me.

**Comment by daN4cat** [comment]
@peepsnet sure fiddle as you like but please don't spam here with no real code issues.
