### ISSUE TITLE
Question: Importing Information for Sale Ticket

### ISSUE THREAD

**Issue by lnorton89** [jekkos/opensourcepos#1228]
I was wondering what information is available for importing information for a sale on the fly via CSV / DB. 

We process shipments via UPS Worldship and would like to automatically import shipment information (namely price) into a new sales ticket. UPS is setup to export a CSV after every shipment is processed. 

I did read the wiki and saw no information supporting what I would like to know. Thank you.

**Comment by jekkos** [comment]
There is no direct support for importing sales at this moment. So in this case you'll need to write directly into MySQL or create a REST interface for the sales resource so that it can easily queried
