### ISSUE TITLE
Not to set fixed the Item Price Ver 2.2

### ISSUE THREAD

**Issue by BorloloySD** [jekkos/opensourcepos#1229]
Good day guys!

Before I will upgrade my version on POS for this new one. 
I'd like to know where to set in the code for the Item price can be editable without activating the Items section?

Kindly check this  photo.

thanks
![12](https://cloud.githubusercontent.com/assets/26247640/24893563/fc144438-1eb6-11e7-9846-fc98a9735679.jpg)

**Comment by daN4cat** [comment]
It's a very old version, not sure who can remember that code and help you.

**Comment by BorloloySD** [comment]
I thanks for your quick reply daN4cat, 
I tried to search in the views\sales\register.php
and change like this. It works now. I wish no other reports might affected.

![13](https://cloud.githubusercontent.com/assets/26247640/24895392/b2d24dae-1ec2-11e7-949d-6a379ec08f61.jpg)

**Comment by daN4cat** [comment]
You need to upgrade the database step by step going through all the upgrade scripts.
Have you tried that?

**Comment by daN4cat** [comment]
What I meant is that in phpMyAdmin you run (on a copy of your database first) the upgrade script 2.0_to_2.1.sql, then 2.1_to_2.2.sql, and so on and on one upgrade at the time.
A manual tedious job but there is no other option.
