### ISSUE TITLE
How to view and search by custom fields

### ISSUE THREAD

**Issue by jfico** [jekkos/opensourcepos#123]
If I have created custom fields in the configuration section, and put values for those fields on to items, what do I have to do to be able to see those values from the sales register, and even better to be able to search by the values.  I see code in the php that looks like it should display the custom fields but I can't figure out why it's not.

**Comment by odiea** [comment]
Custom fields only  appear under the Add Item menu. All searches are done for those from there.

**Comment by daN4cat** [comment]
From Items view click on the + by the Search Options. A drop down window will open and the check the Search Custom field checkbox. Once that's done you should be able to search by Custom field content from the Search box.
