### ISSUE TITLE
Summary Payment Report

### ISSUE THREAD

**Issue by odiea** [jekkos/opensourcepos#124]
Is there a way for all the gift cards to be combined into 1 amount instead of all the gift cards showing in the report.

**Comment by daN4cat** [comment]
When I have time I'll look into this. It should be a sum under generic giftcard indeed.
I guess even the daily takings I worked on is affected by this issue. I'll need to test.

**Comment by daN4cat** [comment]
I fixed this, please read #110 and latest commit.

**Comment by odiea** [comment]
Works great. Thanks
