### ISSUE TITLE
Weighing Scale Barcode

### ISSUE THREAD

**Issue by WebShells** [jekkos/opensourcepos#1243]
Dears, 
Is there anyway so the software will scan auto generated barcodes by weighing scales ? 
Trying to make it fit for a grocery shop... 
Any ideas ? 
Thanks in advance....

**Comment by jekkos** [comment]
Actually I did some of this work in the past for a client on a private branch. If I'm not mistaken then quantity was an optional field in the barcode  encoding which would then be prefilled in the register once scanned in

**Comment by WebShells** [comment]
Well, after scanning the barcode 3 values should be input, 
1) item name set as PLU/item# ( if they scan yougurt 1 kg  for autogenerated barcode 000023XXXQTYXXPRICE)
2) Weight or qty will be input
3) Price that was automatically generated depending on scale weight to be copied into price field...
Any help ? Is this what we are talking about ?

**Comment by WebShells** [comment]
....

**Comment by jekkos** [comment]
I'd have  to dig it up, it's based on a rather old version and will probably need polishing. i'm willing to do this if you  then can send a PR with the polished up feature.

**Comment by WebShells** [comment]
Sure, no problem about that, ill edit the code to fit the current version and will share it back... Just need to touch the end of the code in order to know where to start from...

**Comment by WebShells** [comment]
Jekkos... Any updates regarding this ?

**Comment by WebShells** [comment]
Updates ?

**Comment by odiea** [comment]
Don't hold your breath waiting for this one.

**Comment by WebShells** [comment]
Hello Odiea, why ? already jekkos said he did it before... maybe sharing it or giving an idea how it can be done so i can proceed on my own...

**Comment by WebShells** [comment]
Updates :/ ? 
Who can i talk to for paid development ?

**Comment by jekkos** [comment]
Actually what I did at the time was make a websocket talk to a serial device (in this case a scale) and readout the byte stream in the register... once something changed on the scale then quantity was updated in the register. Also this quantity in barcode sounds familiar to me.. think it was somewhere in that branch as well.

I could try to integrate this functionality in upstream however, I'll have to take a closer look first and will probably expect some donation in return.. the DO reference hasn't given me any credit this month so I'll need to pay for weblate hosting myself now.

**Comment by WebShells** [comment]
Hello Jekkos,

Thanks for your reply, can i have any private messaging details ? email ? am ready for the donations required in order to accomplish this feature. 
Kindly share a way to contact you...
Regards

**Comment by jekkos** [comment]
Contact me directly on jeroen DOT peelaerts 
and then at googlemail dot com 
Please confirm so I can delete this message (rather not share my address publicly)

**Comment by SteveIreland** [comment]
Too late ... I have it.

**Comment by jekkos** [comment]
Pull request opened for this one, will cross reference there

**Comment by truchosky** [comment]
hi guys, sorry for bring up this but how do you use it?, where do you configure this ?, the format and that kind of things ?
