### ISSUE TITLE
Adding new filter to 'takings'

### ISSUE THREAD

**Issue by RamkrishnaMondal** [jekkos/opensourcepos#1244]
I am trying to add a new filter "Only_check"  to sales takings, so that i can sort sales with a 'check' . Filter is  showing but when  selected it's not sorting the 'check-sales'. Below is the customised code from sales controller: 

![screenshot from 2017-04-17 11 56 53](https://cloud.githubusercontent.com/assets/14151032/25081196/82121278-2366-11e7-972d-0d83c6c3586a.png)
 
Any help will be appriciated. Thank You!

**Comment by daN4cat** [comment]
@RamkrishnaMondal in master. It was easier to implement than explain how to....

**Comment by daN4cat** [comment]
@RamkrishnaMondal please test and confirm it's fine. If so please close this issue.

**Comment by RamkrishnaMondal** [comment]
Ah, thank you very much ..... it's perfectly working. After going through your code i now understand the work-flow of these filters.

**Comment by RamkrishnaMondal** [comment]
@daN4cat  One problem i can see with this... if a sale has a payment type like 'Cash $200, Check $1000' , the **check** filter not sorting that sale, but if it is like 'Check $1000,Cash $200' ... it is sorting correctly. That means it is only searching the first payment types not 2nd ,3rd types.

**Comment by daN4cat** [comment]
@RamkrishnaMondal it's a sorting issue or finding all payments?

**Comment by RamkrishnaMondal** [comment]
It's a sorting issue. In case of a multi-payment sale, 'Only_check' filter can sort a sale if and only if Check is the first payment type. If check is the 2nd/3rd payment type, it's not recognizing that sale as a "check_transaction".

**Comment by daN4cat** [comment]
@RamkrishnaMondal the filter does not check if exclusively check. It filters payment with a check or with cash.
In the end it's what you want to know, all the checks you received or all the cash you received.

**Comment by RamkrishnaMondal** [comment]
Yes, I want a list of all sales where check is paid as full / part payment. In case of a sale, where customer pays a part in cash and part in check, the filter will include the sale as a check-transaction, **if i add check payment first** and then add cash. if i add cash payment first and then check payment, the filter is not listing that sale as a check-transaction. Hence not getting a full list of check-transactions (full or part).
