### ISSUE TITLE
How to remove heading (domain and app version) from printed receipt 

### ISSUE THREAD

**Issue by rashedk777** [jekkos/opensourcepos#1246]
Please see the image: 
![fullsizerender](https://cloud.githubusercontent.com/assets/13873131/25119052/8b969696-243a-11e7-8f93-ecda92bd1e1b.jpg)

How can I remove "Green Light | Powerder By OSPOS 3.1.0" and "http://localhost...../" parts? 

Thanks

**Comment by daN4cat** [comment]
That's your webprowser printer support that does that. Check the browser setting as that is not an OSPOS issue.
