### ISSUE TITLE
NEGATIVE CASH AMOUNT ON RECEIPT PRINT OUT

### ISSUE THREAD

**Issue by ebenezery4** [jekkos/opensourcepos#1248]
### Bug

Before submitting an issue please make sure you remove the first section of the template and you tick (add a x between the square brakets) and agree with all the following check boxes:

- [X] Checked the current issues database and no similar issue was already discussed
- [X] Read the README, WHATS_NEW and UPGRADE
- [X] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php5-gd, php-intl and sockets installed)
- [] Reporting an issue of an unmodified OSPOS installation
- [X] PHP version is at least 5.5 and not 7.x
- [X] MySQL version is 5.5 or 5.6 and not 5.7
- [] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [X] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [X] Know the name and version of OS, Web server and MySQL and will add to my issue report

### Installation information
OSPOS 3.1.0
WINDOWS BASED OS
XAMPP

### Actual behaviour
WHEN PRINTING OUT RECEIPT AFTER COMPLETION OF PAYMENT A NEGATIVE FIGURE IS DISPLAYED ON THE RECEIPT AS CASH RECEIVED

### Steps to reproduce the issue
![image](https://cloud.githubusercontent.com/assets/17982781/25138899/a1a63da6-2453-11e7-9bd3-32b6d4d8d10f.png)
BEFORE CLICKING ON ADD PAYMENT THE AMOUNT TENDERED SHOW THE ACTUAL AMOUNT TO COLLECT FROM THE CUSTOMER  BUT AFTER CLICKING ON THE ADD PAYMENT THE AMOUNT TENDERED WILL CHANGE TO ZERO  AND IF THE COMPLETE BUTTON IS CLICKED THE ZERO WILL SERVE AS IF THE CUSTOMER IS PAYING NOTHING AND THE CASH ON THE RECEIPT WILL BE NEGATIVE THOUGH AM NOT SURE IF THIS HAS ANY EFFECT ON THE OTHER REPORT GENERATION
![image](https://cloud.githubusercontent.com/assets/17982781/25139063/1653a652-2454-11e7-9dd2-194a5b43a753.png)

**Comment by daN4cat** [comment]
The two pictures are the same. What the issue?

**Comment by ebenezery4** [comment]
sorry the second picture shows 0 as cash tendered after clicking on add payment instead of showing amount collected from the customer.

![image](https://cloud.githubusercontent.com/assets/17982781/25144144/bf3f15f2-2464-11e7-9b62-eea4ecad9945.png)

**Comment by daN4cat** [comment]
It looks all normal to me. 150 is the item price and you got 150 in cash. 0  remaining amount (due). So? ??

**Comment by ebenezery4** [comment]
this is the receipt page the cash is showing negative like -$2000 or -N2000 
![image](https://cloud.githubusercontent.com/assets/17982781/25144617/62a36b20-2466-11e7-874c-f4350dd1f2a1.png)

**Comment by ebenezery4** [comment]
the amount tendered is rendering zero which means the customer did not pay anything so going to the receipt print out the cash will bring negative cash amount 

hope you get what am saying

**Comment by ebenezery4** [comment]
![image](https://cloud.githubusercontent.com/assets/17982781/25145070/f2d71506-2467-11e7-8ac1-826544e797aa.png)

![image](https://cloud.githubusercontent.com/assets/17982781/25145162/44090e7a-2468-11e7-81d0-24f4e7c9f560.png)
check the highlighted  part for clearer information

**Comment by odiea** [comment]
I think he is not liking the visual appearance. It has nothing to do with the way the math is calculated.
Amount tendered can be changed to Amount Due in the register when the payments cover the total.
![2017-04-18 12_05_03-wedidit _ powered by ospos 3 1 0](https://cloud.githubusercontent.com/assets/10962177/25146243/730011ca-2430-11e7-936f-f2d7db0a3c2a.png)
And the Receipt to look like this.
![2017-04-18 12_05_36-wedidit _ powered by ospos 3 1 0](https://cloud.githubusercontent.com/assets/10962177/25146259/8013dc8e-2430-11e7-839b-56e8e0f2e8d6.png)

**Comment by RamkrishnaMondal** [comment]
Lots of new OSPOS users are getting confused with this  '-'  sign, we should think on removing this one.

**Comment by RamkrishnaMondal** [comment]
Good to see that @odiea is also using self implemented 'credit feature'.

**Comment by ebenezery4** [comment]
Am not that bothered with the negative sign though as far if it has nothing to the with the report generation

**Comment by RamkrishnaMondal** [comment]
@ebenezery4  It's only shows on the receipt page, reports are not affected with this.

**Comment by ebenezery4** [comment]
ok that's a relief then thanks

**Comment by daN4cat** [comment]
So you all prefer amount due and then no - sign in the receipt, is that correct?

**Comment by daN4cat** [comment]
@jekkos @SteveIreland any preference on the matter so we change this once forever?

**Comment by odiea** [comment]
It might be less confusing for the new Users.

**Comment by jekkos** [comment]
Maybe we should make it optional then ;)

**Comment by daN4cat** [comment]
Even this... it gets too much. Too many config options, people cannot get it anymore.

**Comment by odiea** [comment]
@daN4cat  I don't think too many have commented on this being an Issue. I will leave it up to your discretion on whether or not to change anything.

**Comment by jekkos** [comment]
I'd opt not to change it, or alternatively provide a receipt template in which amount due  / amount tendered is shown

**Comment by jekkos** [comment]
Actually people should just edit their own template so they can have it the way they want

**Comment by daN4cat** [comment]
I believe amount tendered is correct because you are supposed to write the amount paid and then add the payment. The fact that it's preloaded is a convenience.
The receipt with - is an accountancy approach. You issue a receipt telling your customer that they got a value of 100 and they are therefore short of 100 in cash. From an accountancy point of view and from customer point of view it all makes sense.

Therefore I close this.

**Comment by ebenezery4** [comment]
Please is anyone open for job offer. i have a project i want any intrested
person to take up. reply me via ebenezer.adebayo@gmail.com

Thanks
