### ISSUE TITLE
FAILING TO RUN THE PROJECT ON MY LOCAL MACHINE

### ISSUE THREAD

**Issue by flanchoooo** [jekkos/opensourcepos#1249]
Hi 

Thank you very much for availing this application which I see as something that am going to use for the nex t couple of years on a daily basis. However before I get too excited. I followed all the following steps provided but am failing to get the app running. 

Am getting the following error "You don't have permission to access the requested directory. There is either no index document or the directory is read-protected.

If you think this is a server error, please contact the webmaster.

Error 403"

I am using:
 Xamp Version 3.2.2
Apache Version Apache/2.4.17 
PHP/5.6.23

I have enalbed the following: 
php-gd, php-bcmath, php-intl, php-sockets, php-mcrypt and php-curl
May you kindly assist. 

Thank you inadvance.

**Comment by odiea** [comment]
Check past issues, FAQ, README, wiki and etc. You'll find your answer. Make sure you are pointing to the public folder

**Comment by flanchoooo** [comment]
Thank you.


Worked like magic.
