### ISSUE TITLE
cannot change the quantity of item in sales

### ISSUE THREAD

**Issue by Aravindhanari** [jekkos/opensourcepos#1251]
### Issue / Question / Bug

Before submitting an issue please make sure you remove the first section of the template and you tick (add a x between the square brakets) and agree with all the following check boxes:

- [x] Checked the current issues database and no similar issue was already discussed
- [x] Read the README, WHATS_NEW and UPGRADE
- [x] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php5-gd, php-intl and sockets installed)
- [x] Reporting an issue of an unmodified OSPOS installation
- [x] PHP version is at least 5.5 and not 7.x
- [x] MySQL version is 5.5 or 5.6 and not 5.7
- [x] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [x] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [x] Know the name and version of OS, Web server and MySQL and will add to my issue report

### Expected behaviour
change(editable) the quantity of products in sales,

### Actual behaviour
 Not able to change the quantity

### Steps to reproduce the issue
Try to change the quantity of the product in sales.
![capture](https://cloud.githubusercontent.com/assets/26411001/25180804/0fc10a08-252d-11e7-9a9b-265d107658f8.PNG)

**Comment by RamkrishnaMondal** [comment]
Un-check "Item has a serial no." for that item.

**Comment by Aravindhanari** [comment]
awesome!! thank uu!!

**Comment by radika-insfra** [comment]
awesome!! thank you!
