### ISSUE TITLE
Takings Issue

### ISSUE THREAD

**Issue by flanchoooo** [jekkos/opensourcepos#1254]
Hi 

I would like to thank Jekkos for his quick responses.

I have recommendation, I am currently using this application at my mini grocery store and I realised that my employee can actually delete sales. Can you please remove the feature to update sale or make it configurable in the employees section. .

See attached images 
![capture](https://cloud.githubusercontent.com/assets/27745015/25274419/3f2d8528-2690-11e7-98f7-7195aaf26efa.PNG)

**Comment by daN4cat** [comment]
There is already an issue about this point.

**Comment by daN4cat** [comment]
I might see if I can find the time to make it permission based but when I checked it was a bit of work....

**Comment by flanchoooo** [comment]
Yes, I tried to remove the links but it was a bit of work like you said. 

I was thinking of temporarily  start displaying total sales, profit  and number of items sold on that page extracting data from the `ospos_sales_items` table. 

Let me know what you Think ? @

**Comment by bill-goldberg** [comment]
I think you should try this...
Remove the reports module permission from the employees account
so that they cannot access the takings page

**Comment by daN4cat** [comment]
Addressed by #1539
