### ISSUE TITLE
Login issue _ Solution required

### ISSUE THREAD

**Issue by Aravindkrishna2010** [jekkos/opensourcepos#1255]
### LOGIN ISSUE

I know this is known issue... But I searched for solution. Its not there.
After installation i used  "http://localhost/ospos2/public/ " to login. I inserted username and password.
After login "This page isn’t working" message is displaying. 

###Error Message on page

This page isn’t working

localhost is currently unable to handle this request.
HTTP ERROR 500

### Issue / Question / Bug

DB connected Correctly.
After submission of login form, i can't access any page. Need a solution...

### Expected behaviour
Need a proper instruction. Kindly don't reply as "Already solved issue". Kindly tag me that solved problem.

**Comment by RamkrishnaMondal** [comment]
Please provide   **Installation information**.

**Comment by Aravindkrishna2010** [comment]
1.moving folder into htdocs
2.Created DB, and edited Application-->Config-->Database(DB name,hostname,username,password).
3.imported Database.sql in Created DB.
4.Run
5. Issues(Mentioned above)

**Comment by daN4cat** [comment]
You are not providing the information required.

**Comment by daN4cat** [comment]
And please check past issues, FAQ, wiki, readme as you'll find the answer.
