### ISSUE TITLE
When adding GiftCard as payment, add the customer name automatically (if available)

### ISSUE THREAD

**Issue by daN4cat** [jekkos/opensourcepos#126]
From Sales:

1. a shop assistant selects GiftCard as payment
2. then enters the GiftCard number
3. the customer name is not added automatically (if associated to the GiftCard) forcing the shop assistant to reenter the customer name.

It would be wiser to add automatically the customer name associated to the GiftCard (if available).

**Comment by odiea** [comment]
Why don't we just show the Customers available giftcards when we enter his name in the Customer lookup?

**Comment by daN4cat** [comment]
Usually you have a giftcard number, doing the opposite makes thing quite complicated IMHO.

**Comment by jekkos** [comment]
Kinda tricky as most of the time giftcards are bought by people for other people. So the person paying with the giftcard probably won't be the one that bought it in the first place.

**Comment by daN4cat** [comment]
OK, so why do we bind a customer name to a gift card?

**Comment by jekkos** [comment]
Good point. We don't really use that functionality anyway. It's a good way to keep track of which coupons are still out there but that's about it. This functionality was contributed by someone else before I got into the project.

**Comment by odiea** [comment]
My wife uses the gift card as a way to refund customers (She doesn't do cash back). She requests name and phone number.

**Comment by jekkos** [comment]
Ok then a new setting should be added in config to add the customer depending on the desired use of giftcards

**Comment by daN4cat** [comment]
The way we do, we created a Voucher item and when a customer returns an items we add the voucher  and set the value to make the balance 0. The user retains the Voucher receipt and next time they come around they return the voucher which is deducted from the amount they pay. Any extra is added as normal payment. In case they don't spend all the voucher, we issue another voucher with a new balance.

**Comment by daN4cat** [comment]
Going back to this, it sounds like GiftCards should be gift cards and nominal voucher or refund credit a different item. Or maybe we should combine everything in one "credit" entity and give them different names (subclass)?
What about invoices, don't you have cases for Credit Notes? Let say an item you bought is faulty and it was sold with an invoice, you surely need a CN for that.

In case of refund credit/CN it would be nice to add a link to the original sale receipt / invoice.

Thoughts?

**Comment by odiea** [comment]
For a few weeks Sales Returns would only accept POS numbers. I thought it was a better way to keep track of returns.

**Comment by daN4cat** [comment]
Not sure I get, what do you mean with "For a few weeks Sales Returns would only accept POS numbers"?

**Comment by sanjubaba1515** [comment]
If you want to make any change. 
PLEASE CONTACT ME AT SANJUBABA1515@GMAIL.COM, WHATS APP +919681971515

**Comment by daN4cat** [comment]
I don't think we want this as we agreed that GiftCards are bought by some people as a Gift to others. So no point to popup automatically customer names.

I close.
