### ISSUE TITLE
Taking Issue on live server and localhost

### ISSUE THREAD

**Issue by asadjaved63** [jekkos/opensourcepos#1260]
Hello daN4cat ,jekkos 
dear sir , i m facing issue in takkings , on local server takings working fine.. but on live server no date found
. what the problem can you please tell me..

Localhost

![localhost](http://i.imgur.com/60P2iat.png)

LiveServer
![localhost](http://i.imgur.com/S93zR6s.png)

see video
[video](http://screencast-o-matic.com/watch/cbf3lqX6HZ)

**Comment by daN4cat** [comment]
@asadjaved63 I assume you will contribute purchases and expenses so we can then help you....

**Comment by asadjaved63** [comment]
how can i contribute? @daN4cat

**Comment by jekkos** [comment]
By showing us the source code! ;)

**Comment by asadjaved63** [comment]
I am sending you,and I might not following standardized coding , so kindly review it  before posting...

**Comment by asadjaved63** [comment]
@daN4cat @jekkos  Review it before posting
[Expense](https://www.dropbox.com/s/g4dgknfg0xsxdaw/expense.rar?dl=0)

**Comment by asadjaved63** [comment]
@daN4cat  help me please ...

**Comment by daN4cat** [comment]
check if all the php extensions are installed on your live server, I bet you are missing one of those

**Comment by daN4cat** [comment]
(sorry I was finishing off some code that I just committed to master)

**Comment by daN4cat** [comment]
@asadjaved63 do you have the database tables schema too for the expenses? Thanks

**Comment by daN4cat** [comment]
@asadjaved63 is it working?
