### ISSUE TITLE
Blank white screen in remote server

### ISSUE THREAD

**Issue by rashedk777** [jekkos/opensourcepos#1262]
Here is the project address:

http://rashedkhan.net/pos/public

I placed all folders perfectly and installed database but nothing shows in project's domain.

**Comment by joshua1234511** [comment]
Have you changed the Database configuration ?
Try using the latest version:

**Comment by daN4cat** [comment]
Check php extensions, FAQ, wiki, readme, past issues and you'll find your answer.
