### ISSUE TITLE
I can't import items in Arabic language

### ISSUE THREAD

**Issue by toradoya** [jekkos/opensourcepos#1263]
This is my first pull request so I hope I have done it right, **i think i discovered a bug**

I can import data in English language, but I Cannot import data in Arabic language!!, After several attempts, I was able to import some of the Arabic data, but without the item names!!

I Uploaded CSV File containing dummy Arabic data, so you can test it.
http://www.mediafire.com/file/49oy5dgt5qo8qgf/import_items1.csv

Also, I read FAQ to see if there is a solution for my problem, but found nothing, and I read this issue (STOCK ITEM BATCH UPLOAD ISSUE #1214), as I said it’s not working only with Arabic language

### Issue / Question / Bug

- [a] Checked the current issues database and no similar issue was already discussed
- [a] Read the README, WHATS_NEW and UPGRADE
- [a] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php5-gd, php-intl and sockets installed)
- [a] Reporting an issue of an unmodified OSPOS installation
- [a] PHP version is at least 5.5 and not 7.x
- [a] MySQL version is 5.5 or 5.6 and not 5.7
- [a] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [a] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [a] Know the name and version of OS, Web server and MySQL and will add to my issue report

### Installation information
Windows 10 pro x64
WampServer 2.5 X32
ospos Version 3.1.0 - 4f5ad57
Apache - 2.4.9
PHP-5.5.12
MySQL-5.6.17

### Expected behavior
i want to import Arabic Data, to save my time 

### Actual behavior
i can't import Arabic data

### Steps to reproduce the issue

1.	Download the latest Master of OSPOS & Unzip OSPOS
2.	DownLoad & Install Notepad++ & WampServer 2.5 32 
3.	Go to [C:\wamp\www], & Create new folder named it OSPOS1, then copy OSPOS files to it
4.	Copy all icuXX.dll files to this location [C:\wamp\bin\apache\apache2.4.9\bin]
5.	Edit php.ini file, and change this (;extension=php_intl.dll)  to (extension=php_intl.dll)
6.	Activate Apache Rewrite Modul.

7.	Now Browse to [C:\wamp\www\ OSPOS1\application\config], & edit "database.php" file, write your Database name, Username, and Password.

8.	Go to phpMyAdmin, Create New Database, then Add User and write the same Database name, Username, and Password that you wrote them before, then Import OSPOS Files

9.	Now try to import Arabic data.

**Comment by jekkos** [comment]
This could be an encoding issue. Which editor did you use to edit your file? Think it should be UTF-8 if you want to make it work correctly

**Comment by toradoya** [comment]
i used Excel to edit the file, i filled the "import_items.csv" file with Arabic data then i saved it and uploaded it to OSPOS, but it failed on uploading the data

**Comment by toradoya** [comment]
is there a specific procedure to edit/fill the import file that i don't know!?

**Comment by toradoya** [comment]
?????
