### ISSUE TITLE
Looping after UPGRADE 3.0.0 to 3.1.0

### ISSUE THREAD

**Issue by erfanrocker** [jekkos/opensourcepos#1266]
### IMPORTANT IMPORTANT IMPORTANT

Chose what you want to report: New Feature or Bug.
If you remove the template when submitting a Bug your issue will be closed as we cannot help without basic information.

### New Feature / Enhacement

For New Features or Enhacements please remove all the template text and clearly write your proposal.
It's important to state whether you expect the community to implement it or you will contribute the work.
Please bear in mind that we will implement new features only on the current code, there is no support for old versions.

### Issue / Question / Bug

Before submitting an issue please make sure you remove the first section of the template and you tick (add a x between the square brakets) and agree with all the following check boxes:

- [] Checked the current issues database and no similar issue was already discussed
- [] Read the README, WHATS_NEW and UPGRADE
- [] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php5-gd, php-intl and sockets installed)
- [] Reporting an issue of an unmodified OSPOS installation
- [] PHP version is at least 5.5 and not 7.x
- [] MySQL version is 5.5 or 5.6 and not 5.7
- [] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [] Know the name and version of OS, Web server and MySQL and will add to my issue report

### Steps to reproduce the issue
![image](https://cloud.githubusercontent.com/assets/9877489/25391363/49eefcda-2a00-11e7-9d4d-d70cf5d207ad.png)

After upgrade from 3.0.0 to 3.1.0  can't login & looping. can you help me please

**Comment by daN4cat** [comment]
Installed all the required PHP extensions? Upgraded the database properly? Read the FAQ,  past issues and etc. ?

**Comment by jekkos** [comment]
Issue could be language related.. Which one did you chose?

**Comment by dotcoco** [comment]
I had the same problem few days ago and it was related with the folder languages I made some changes in the translations and I didn't write the last ";"

**Comment by ekardian** [comment]
well im lost with the migration from 3.0.0 to 3.1.0 ( i have all requirements), i cant login, i follow the steps from UPGRADE.txt, but in the section 4 maybe im doing wrong... a tip please. i did all the steps for a normal installation all good/work. I did that for see if was ok, i started again for migrate but witch one i should choice, i've tried different steps like 3.0.2 to 3.1.0.sql .. even from original.sql to database.sql... help plz

**Comment by ekardian** [comment]
![ospos3 1](https://cloud.githubusercontent.com/assets/6296036/25461097/0767af32-2ab5-11e7-97d1-b0d0eaf15091.jpg)

**Comment by odiea** [comment]
In your database under app_config check to see if you have both language and language_code. There should be something in both of them

**Comment by daN4cat** [comment]
@dotcoco that's why we ask if the issue is from an unchanged OSPOS because we cannot guess what people do staring to a issue report with stated: it doesn't work.

**Comment by daN4cat** [comment]
@ekardian which language do you use?

**Comment by ekardian** [comment]
> 
> 
> @ekardian which language do you use?
Spanish, sorry was 4 years XD , the problem was because i changed iin some parts, like the meta calling the js files, i changed for a isalate network for never see the sun of internet, i made it in 2016, i had to migrate manually the item names to another clean  OSPOS and database, and started again, sorry for the late answer, from 2017 never falied me again, just in the .htaccess for a localhost, but fixed now, thx
