### ISSUE TITLE
Stuck on version 3.0.3 - 3.1.0

### ISSUE THREAD

**Issue by guntursulistyo** [jekkos/opensourcepos#1267]
i have stuck on my server,,
start from version 3.0.0 til 3.10 this source cannot be run on my server,
what should i do?

u can access it on
http://pos.netzen.co.id/public
user : admin
pass : pointofsale

![stuck](https://cloud.githubusercontent.com/assets/12862916/25417736/5aef8246-2a70-11e7-943d-0fecfdc67017.png)

can't add item and all

![struck2](https://cloud.githubusercontent.com/assets/12862916/25417775/acf699f8-2a70-11e7-86ed-2f47850f7ec0.png)

**Comment by corslayth001** [comment]
Use the database scripts

**Comment by daN4cat** [comment]
Make sure all required PHP extensions are installed

**Comment by daN4cat** [comment]
Read the FAQ, readme, closed issues and wiki
