### ISSUE TITLE
Categories & Sub Categories feature

### ISSUE THREAD

**Issue by yaxir** [jekkos/opensourcepos#127]
1. please add the categories and sub categories add/update/manage feature with its reports. so one will categories the items/products very precisely.

2. Items / Products Purchase Order and add the quantity to inventory after completing the purchase order.

3. quick price check button

**Comment by RyanfaeScotland** [comment]
Possible duplicate #68 (but with better spelling ;) )

**Comment by jekkos** [comment]
Ok good spot, will add a reference to this issue in #68 and close this one for now.
