### ISSUE TITLE
In latest version when I click "New Item" a modal shows with no form

### ISSUE THREAD

**Issue by rashedk777** [jekkos/opensourcepos#1274]
![capture2](https://cloud.githubusercontent.com/assets/13873131/25480303/0cfca596-2b6a-11e7-8669-894bc2d4101c.PNG)

Please have a look at this picture. Why actually this is happening? Customers, Item Kits and others are okay.

**Comment by odiea** [comment]
Fill out the template before submitting an Issue.

**Comment by rashedk777** [comment]
Sorry I don't get it. Can you please explain.

**Comment by daN4cat** [comment]
Read what's prefilled when you create an issue instead of ignoring it and wiping it out. Got the point?
