### ISSUE TITLE
[SOLVED] FALSE state in the report

### ISSUE THREAD

**Issue by fazlisamat** [jekkos/opensourcepos#1275]
Hi,

I just wonder why the FALSE occurs on every each report.

Please take a look on the image attached. 

I'm just a normal user installed from Softacolous Linux Hosting

![issue_001](https://cloud.githubusercontent.com/assets/28110694/25495532/07e532c6-2bb0-11e7-92bc-8573c6db34e6.png)

**Comment by fazlisamat** [comment]
Issue SOLVED.

3.0.2 not supported by PHP 7
Revert to PHP 5.6

:)

**Comment by daN4cat** [comment]
Or update to 3.1.0 when completed.

**Comment by fazlisamat** [comment]
@daN4cat where to get latest update?

**Comment by odiea** [comment]
https://github.com/jekkos/opensourcepos

**Comment by daN4cat** [comment]
It's not completed yet
