### ISSUE TITLE
In latest version when I click "New Item" an empty dialog box comes

### ISSUE THREAD

**Issue by rashedk777** [jekkos/opensourcepos#1276]
### Issue

Before submitting an issue please make sure you remove the first section of the template and you tick (add a x between the square brakets) and agree with all the following check boxes:

- [x] Checked the current issues database and no similar issue was already discussed
- [x] Read the README, WHATS_NEW and UPGRADE
- [x] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php5-gd, php-intl and sockets installed)
- [x] Reporting an issue of an unmodified OSPOS installation
- [x] PHP version is at least 5.5 and not 7.x
- [x] MySQL version is 5.5 or 5.6 and not 5.7
- [x] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [x] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [x] Know the name and version of OS, Web server and MySQL and will add to my issue report

### Installation information
Latest Version of Wamp Server 
Apache Version- 2.4.9
PHP Version- 5.5.12
MySQL- 5.6.17
### Expected behaviour
When I click "New Item" I should get a modal with a form.

### Actual behaviour
When I click "New Item" I get an empty dialog box (modal). Customers and all other sections are okay though.

Please see the picture 
![capture2](https://cloud.githubusercontent.com/assets/13873131/25507381/7c8bb448-2bcd-11e7-86ba-0495a1b4208d.PNG)

**Comment by daN4cat** [comment]
And have you read the FAQ, readme and wiki?

**Comment by rashedk777** [comment]
Yes, I found nothing

**Comment by daN4cat** [comment]
And all the php extensions are installed, you sure?

**Comment by rashedk777** [comment]
Yes, I checked all

**Comment by daN4cat** [comment]
And a phpinfo() call is returning the correct php extensions being active?

**Comment by odiea** [comment]
Was this a new install or an upgrade from a previous version?

**Comment by meetmec12** [comment]
Same as issue here. I even tried it on a remote sever no luck. I get over lays and rolling icon that takes forvere to load .

**Comment by daN4cat** [comment]
Which setup and language?

**Comment by daN4cat** [comment]
BTW, if you didn't run in full the database upgrade script it might be due to some of the in development additions that could cause that problem.

**Comment by meetmec12** [comment]
It was a new installation in my own case

**Comment by 4mon** [comment]
me too. Only the items form does not appear. the rest yes

**Comment by SakibAliMalik** [comment]
I make a new installation and the same issue on my side
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
items/view:1
