### ISSUE TITLE
ApiGen code documentation

### ISSUE THREAD

**Issue by daN4cat** [jekkos/opensourcepos#1278]
Hi @jekkos 

I added code documentation generated automatically by ApiGen (see https://github.com/ApiGen/ApiGen).
The documentation is saved under docs and if you check my fork: https://dan4cat.github.io/opensourcepos/ you can browse it straight from GitHub.

Read here how to enable that in your repo: https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/

ApiGen is also part of grunt script so we should have fresh code documentation every time we run grunt script.

In general we should improve code following the ApiGen tagging to get better documentation

P.S.: I also added composer step to grunt script, so a grunt run will update composer packages too.

**Comment by jekkos** [comment]
@daN4cat Nice thing this documentation, it's especially useful to get a bit of an overview if the code is self documenting in a way. 

Regarding the composer:update thing: I'd rather have it in a separate target that combines both bower and composer updates together. Perhaps not in the default build step as it might not always be desirable to connect to the internet doing minification builds. If you have no objection then I'll move it to a new 'update' target.

**Comment by jekkos** [comment]
Same thing for the documentation. I guess it takes quite some time to generate and think this is typically something we'd lke a CI environment to do..

**Comment by daN4cat** [comment]
Fine with the change, please change as you prefer.

By the way, I'm not particularly happy with the way composer manages the packages for final release deployment.
Vendor now is bloated by require-dev stuff that we don't want in a production release, there must be a way to make things tidy as this is messy!

**Comment by jekkos** [comment]
Yes indeed, these dev depdencies shouldn't end up in the final release package. Maybe we should just omit them from version control as they're only needed in a dev setup

**Comment by daN4cat** [comment]
Maybe this is the solution? https://getcomposer.org/doc/faqs/should-i-commit-the-dependencies-in-my-vendor-directory.md

**Comment by jekkos** [comment]
Haha i was reading the exact same post. Think it makes sense indeed. The dependencies should be included once in the final download and indeed, I'd prefer to omit the whole thing from VCS as well. 

But that means that if people clone the repo that they will need to install composer first in order to have something working.

**Comment by daN4cat** [comment]
There should be a way to create just a dist version of OSPOS application all inclusive,

**Comment by jekkos** [comment]
Yes in the same way I'd opt to leave out minified JS as well, it's just annoying have these files pop up after each rebase over and over again.. The size of them makes a diff editor choke which is not a pleasant experience imho

**Comment by jekkos** [comment]
https://docs.travis-ci.com/user/deployment/releases/

**Comment by jekkos** [comment]
I think the easiest way to solve this is have travis run 
* One docker run for dwnloading composer pacakges
* One docker run for installing npm dependencies and running grunt
* Then as a final step zip it up and push a release artifact to a download server somewhere

For local environment setup then I'd prefer to do something similar, rely on docker unless people want to go through the pain to install the tooling manually. However that will raise the bar for new devs a bit, but in a VCS view I think this is the correct thing to do.

**Comment by jekkos** [comment]
Hmm it seems that github requires one to tag each release so in that case it might be better to upload these nightly builds elsewhere, perhaps then to the server where weblate is running currenty.

**Comment by daN4cat** [comment]
Github automatically zips the files tagged with a release version when you publish a release. So it's a matter of managing things at github level in my opinion.

Maybe we should keep master stable and tidy and use a development or integration branch for the development and unstable.

**Comment by daN4cat** [comment]
Many people here pulls the master while in development and don't realise is not stable.
Of we branch to an integration we can publish only what stable.
Downside is the overhead....

**Comment by daN4cat** [comment]
OK, I changed Gruntfile.js to separate composer and apigen tasks from default and I created a gendocs.sh script under bin to automatically install composer packages, gen apigen docs and remove composer packages so we commit just the documentation not all the mess under vendor :-)

I believe this will do for the time being. I will need to add a wiki page for this story.

**Comment by jekkos** [comment]
Ok I was just looking into bintray for build artifact hosting. I think github is a bit out of the picture as they require us to tag every commit in git in order to publish an artifact. Also that would make the distinction clear between using unstable and stable or development versions. Currently people download master from github directly, but with this new setup in place they'll need to get it elsewhere. The github repo download will only be for development (as in other projects).

Bintray offers free hosting and has also integration with Travis-CI. Then it's just a matter of updating the .travis.yml to update composer packages and then run bower + grunt, and push the zipped artifact to bintray where it can be downloaded

**Comment by daN4cat** [comment]
Added reference to ApiGen and this issue in the wiki.

**Comment by jekkos** [comment]
@daN4cat I found some references to apigen docs on your github in the wiki, but link seems broken. Do you still have it somewhere or will I remove it ?

**Comment by daN4cat** [comment]
Uhm, forgot about that. It's better to remove any link.
