### ISSUE TITLE
How to set permissions for Items Add and Delete individually

### ISSUE THREAD

**Issue by rashedk777** [jekkos/opensourcepos#1279]
###  Question 

Before submitting an issue please make sure you remove the first section of the template and you tick (add a x between the square brakets) and agree with all the following check boxes:

- [x] Checked the current issues database and no similar issue was already discussed
- [x] Read the README, WHATS_NEW and UPGRADE
- [x] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php5-gd, php-intl and sockets installed)
- [x] Reporting an issue of an unmodified OSPOS installation
- [x] PHP version is at least 5.5 and not 7.x
- [x] MySQL version is 5.5 or 5.6 and not 5.7
- [x] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [x] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [x] Know the name and version of OS, Web server and MySQL and will add to my issue report

### Installation information
Wamp Server Latest,

### Expected behaviour
I want to have an option where I can set permission for Add, Delete, Update sections individually. Is is possible?

### Actual behaviour
When I add an Employee, I set permissions for each sections individually, for example, Items. 

Please see this picture below- 
![capture](https://cloud.githubusercontent.com/assets/13873131/25562199/d7757914-2da0-11e7-83e6-776aad733a6e.PNG)

### Steps to reproduce the issue

**Comment by daN4cat** [comment]
So, have you managed to get your installation to work?

**Comment by rashedk777** [comment]
Actually, I am using my friend's PC now. I haven't got any solution to that problem yet. Thanks.

**Comment by rashedk777** [comment]
Can you please tell me how can I set permissions for Add and Delete separately?

**Comment by daN4cat** [comment]
Search the code for any use of `Employee->has_grant` and see how that's used.
It's not a straight two minutes answer, you need to study the code before you can understand how to add what you need.

**Comment by rashedk777** [comment]
Okay, thank you
