### ISSUE TITLE
Add a direct link to specific_customer report in the customers section

### ISSUE THREAD

**Issue by jekkos** [jekkos/opensourcepos#128]
As the search functionality in sales overview was removed, I'd like to make a customer's sales easily viewable by adding a links in the customer's overview table that directs the user to the specific_customer report.

**Comment by daN4cat** [comment]
Is this still required since you restored the search in Overview/Takings?

**Comment by jekkos** [comment]
Indeed this functionality is now present in the takings overview again, so can be closed.
