### ISSUE TITLE
When I don't give permission of certain section to a user, section's icon get hidden

### ISSUE THREAD

**Issue by rashedk777** [jekkos/opensourcepos#1280]
### Question 

Before submitting an issue please make sure you remove the first section of the template and you tick (add a x between the square brakets) and agree with all the following check boxes:

- [x] Checked the current issues database and no similar issue was already discussed
- [x] Read the README, WHATS_NEW and UPGRADE
- [x] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php5-gd, php-intl and sockets installed)
- [x] Reporting an issue of an unmodified OSPOS installation
- [x] PHP version is at least 5.5 and not 7.x
- [x] MySQL version is 5.5 or 5.6 and not 5.7
- [x] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [x] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [x] Know the name and version of OS, Web server and MySQL and will add to my issue report

### Installation information
Wamp Server Latest

### Expected behaviour
I don't want section's icon to get hidden when permissions are not given for the section. I just want it to be not clickable. Icon should be visisble but not clickable. Is it possible?

### Actual behaviour
When I don't give permission of a certain section to a user, section's icon get hidden. For example I haven't given "Store Config" section's permission to this user and "Store Config" sections got hidden.

![capture](https://cloud.githubusercontent.com/assets/13873131/25562224/d3a6e718-2da1-11e7-86c0-58d8428d88f3.PNG)

### Steps to reproduce the issue

**Comment by jekkos** [comment]
This works as designed, what would you expect then instead?

**Comment by jekkos** [comment]
I currently have no real incentive of changing this. It's not a lot of work to change this if you like, just a matter of changing the module iterator in the header file of the project and adding a disabled attribute as required.

**Comment by daN4cat** [comment]
I prefer the icons to be hidden, in the end you don't want to show what they don't need.
