### ISSUE TITLE
more than just sales .

### ISSUE THREAD

**Issue by meetmec12** [jekkos/opensourcepos#1284]
Is it possible to use this project for a company that receives raw materials and later use it for productions ? If yes , how do you handle used materials , used materials should be deducted from what we have in store . am confused coz this is different from sales . if I use sales for raw materials used, it Will reduce what we have in store by that value but that will also affect profit. Any help pls  .Thanks

**Comment by daN4cat** [comment]
This is an application for retail industry no small business in general. You need to look for another solution or ask somebody to take this and change it for your needs.

**Comment by meetmec12** [comment]
Ok thanks . Any suggestions?

**Comment by daN4cat** [comment]
I'm afraid not.
