### ISSUE TITLE
How to Select 'Requisition' mode in 'Receivings' ?

### ISSUE THREAD

**Issue by RamkrishnaMondal** [jekkos/opensourcepos#1285]
How to Select 'Requisition' mode in 'Receivings' and what is the use case ?

![screenshot from 2017-04-30 05 44 12](https://cloud.githubusercontent.com/assets/14151032/25576746/de137562-2e7e-11e7-95b4-eb5c448c2ae9.png)

![screenshot from 2017-04-30 05 45 52](https://cloud.githubusercontent.com/assets/14151032/25576767/ff71166a-2e7e-11e7-9047-bf456e156340.png)

**Comment by odiea** [comment]
This mode is used to transfer items to a different stock location. You must have more then 1 stock location for this to work.

**Comment by RamkrishnaMondal** [comment]
Got it , thank you.
