### ISSUE TITLE
Bug in Takings 'Filters' 

### ISSUE THREAD

**Issue by RamkrishnaMondal** [jekkos/opensourcepos#1286]
### Expected behaviour
In case of a sale with multiple payment types, the 'cash' or 'check' filter should enlist every sale, part of which is 'cash' or 'check' respectively.

### Actual behaviour
'cash' filter is showing a sale if the first payment type is cash. 'check' filter is also behaving the same way.

### Steps to reproduce the issue
 Make 2 test sales of say $100 each as mentioned below:
1. For the 1st sale, when adding payment, enter cash $60 first and then $40 as check.

 2.For the 2nd sale, add check of $70 first, then cash of $30.

3. Go to takings and select 'cash' filter, it will only show the first sale.

4. Unselect 'cash' filter and select 'check' filter, it will only show  the 2nd sale.

As both the sales contain cash and check payment types, both the filters should show both the sales.

**Comment by daN4cat** [comment]
Fixed and in master.
Thank you for reporting the exact test scenario so now I could spot the issue.

**Comment by RamkrishnaMondal** [comment]
Thank you so much. Working perfectly.
