### ISSUE TITLE
Wiki article for 'Mailchimp', 'Dinner Table' and 'Customer Reward Points'

### ISSUE THREAD

**Issue by RamkrishnaMondal** [jekkos/opensourcepos#1287]
Someone should write articles on how to use these newly added features.
Thank You.

**Comment by daN4cat** [comment]
@jekkos jekyll config is under your control, so you probably need to set it up and allow contribution and etc.

**Comment by jlctmaster** [comment]
Hello, I have created a small article of what I consider describes the characteristic of the [dinner table](https://github.com/jekkos/opensourcepos/wiki/Dinner-Table), if lack content, please let me know.

**Comment by jekkos** [comment]
@jlctmaster thanks for the writeup, was on holiday for a week but now back and good to followup again a bit

**Comment by daN4cat** [comment]
This will need some help and time. I've added a Mailchimp link in the Config Store to know where to the the API Keys. I'll see if I can find the time today to just write some in the wiki about Mailchimp, but I close this issue as it's an open ended story.
