### ISSUE TITLE
Inventory summation out of sync with item quantities

### ISSUE THREAD

**Issue by jekkos** [jekkos/opensourcepos#1288]
### IMPORTANT IMPORTANT IMPORTANT

Chose what you want to report: New Feature or Bug.
If you remove the template when submitting a Bug your issue will be closed as we cannot help without basic information.

### Issue / Question / Bug

Before submitting an issue please make sure you remove the first section of the template and you tick (add a x between the square brakets) and agree with all the following check boxes:

- [x] Checked the current issues database and no similar issue was already discussed
- [x] Read the README, WHATS_NEW and UPGRADE
- [x] Read the FAQ (https://github.com/jeve kkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php5-gd, php-intl and sockets installed)
- [x] Reporting an issue of an unmodified OSPOS installation
- [x] PHP version is at least 5.5 and not 7.x
- [x] MySQL version is 5.5 or 5.6 and not 5.7
- [x] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [x] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [x] Know the name and version of OS, Web server and MySQL and will add to my issue report

### Installation information
Latest master

### Expected behaviour
Always have sum of inventory movements and quantity in sync

### Actual behaviour
Sync can be lost when deleting an item

### Steps to reproduce the issue
Click and delete an item

**Comment by jekkos** [comment]
Made an issue for this, as described in #496

**Comment by daN4cat** [comment]
The work around would be to log the zeroing on delete just to keep history.
However how do you see history if the item is deleted?

In #496 I explained why this is useful and nothing strange and actually avoid statistical errors when reading historical data that actually never was on sale due to faults and similar.
It happens several times per season to my wife that she needs to send back complete series of clothing with cut pattern defects. Even the top brand make such mistake.

**Comment by jekkos** [comment]
Well at least we should make a correction towards zero in the inventory table, next to resetting the quantities.

If you're sending back items then i'd say that you need to do a return. Maybe we should just prevent deleting items with quantities above zero as there's no plain explanation as to where they are going?

**Comment by jekkos** [comment]
I mean if you're sending something back then it means you had it go through receivings and then it ended up in the inventory? So would make sense to do the opposite then and search for the receiving number and return the items that have defects.

**Comment by daN4cat** [comment]
Ok, I was under the impression inventory was fixed when zeroing, if not that indeed should be fixed.

With regards enforcing a business process at business layer it's about people the don't have time for a detail they don't see an immediate value.
So if we want to lock the delete if quantity > 0 then we can implement that but that will cause more questions or people not deleting the item and leave the problem behind.

Shop assistants are not software engineers or analysts I'm afraid.

**Comment by daN4cat** [comment]
Other scenario I forgot is the sale and return. There are cases of brands giving their stock on sale or return basis. When you return you may return quite some stuff and setting quantity 0 to all of the before deleting is really a no go.
I face these scenarios every season and even the statistical part and this is really needed.

**Comment by jekkos** [comment]
Well if you think about the fact that deleting an item never really erases it (just logically), then to me it doesn't make a lot of sense to do it, as it can cause problems afterwards if you have eg sold at least something. Not sure but in some queries deleted items are filtered which can make their sales disappear from reports.. while they're still there. Also if one day you encounter the item again, you won't be able to add it due to the item_number that needs to be unique.

**Comment by jekkos** [comment]
I'd opt to never delete anything , but of course that's personal preference

**Comment by daN4cat** [comment]
In my case items have unique number per season and we don't use receiving. It might be imported via excel sheets or added item by item.
If you never delete something you end up selecting a brand with tons of stuff span acrossed many seasons over years making that filtering unusable.

Going back, what is the problem we are trying to solve?

**Comment by jekkos** [comment]
Just making sure that quantity and inventory count are in sync. Think we need to add an extra statement next to the reset_quantity

**Comment by daN4cat** [comment]
Ok, so that's the bug here to be fixed.

**Comment by jekkos** [comment]
Btw I think that using receiving does give some added value as it's easier to track which items were received together.. same for returning them afterwards. Also easier to check for errors. The stacking up the items in the batch in this screen gives an opportunity to double check whether quantities etc are correct, and would also allow to verify price paid to the supplier before completion

**Comment by jekkos** [comment]
Ok fixed done and can be verified. Sum of inventory movements is always equal to  zero for all stock locations after delete

**Comment by jekkos** [comment]
This query can be used to correct inventory quantities

```
insert into ospos_inventory (trans_user, trans_comment, trans_location, trans_inventory, trans_items) select 11209, 'Inventory autocorrection', 1, (quantity - sum(trans_inventory)) as trans_inventory, item_id from ospos_item_quantities join ospos_inventory on item_id = trans_items
group by trans_items having trans_inventory <> 0
```
