### ISSUE TITLE
Add support to send messages via whatsapp

### ISSUE THREAD

**Issue by lexcorp** [jekkos/opensourcepos#1291]
### New Feature / Enhacement

Add support to send messages via whatsapp

"The php WhatsApp library"

https://github.com/mgp25/Chat-API

**Comment by RamkrishnaMondal** [comment]
There is already an EPIC on this #922 .

**Comment by daN4cat** [comment]
@lexcorp happy for you to implement it and contribute.

**Comment by alarez** [comment]
was this implemented already ?

**Comment by daN4cat** [comment]
@alarez I'm afraid not, but waiting for an owner to take and go. See #922
