### ISSUE TITLE
HOW TO USE BARCODE MACHINE/SCANNER WITH OPEN SOURCE POS

### ISSUE THREAD

**Issue by aterad** [jekkos/opensourcepos#1294]
Hello house,
I am new to opensourcepos, and i must say its a pretty cool stuff.
Please i will like to know how to use or incorporate Barcode machine/scanner with the software.
Will i need to install the barcode software on my laptop to serve as interface with opensourcepos or what?
I am kind of lost.
Please kindly help out house.
Thanks
By the way i am using opensourcepos 2.3.4 version.

**Comment by odiea** [comment]
I do not think this earlier version is supported any longer. Try a more current version.

**Comment by aterad** [comment]
@odiea,
Thanks for your response.
I have now installed 3.01, Please how do i use a barcode scanner on it.
Thanks

**Comment by daN4cat** [comment]
Buy a USB barcone scanner on eBay,  plug it to your USB port and use it in the register. Nothing special it's all supported by your computer nothing related to OSPOS
