### ISSUE TITLE
sales going in minus if stock is 0, I want to restrict the sale if stock is 0

### ISSUE THREAD

**Issue by avinashRAUT** [jekkos/opensourcepos#1295]
How i can control the sale if the stock is zero?  I am trying to make sale if stock is zero it's showing me order successful but stock is going in minus. I want to restrict if the stock to goes in minus if it is zero just want the message that "Stock is not available for this item".

Thanks!

**Comment by daN4cat** [comment]
Fill in the issue template and please don't ignore it.
