### ISSUE TITLE
database.php missing in latest docker images

### ISSUE THREAD

**Issue by thegm90** [jekkos/opensourcepos#1297]
What does everyone else like to use for database back ups? We are using digital ocean on a linux image.

**Comment by odiea** [comment]
I use xampp so I use the export feature in phpMyAdmin.

**Comment by SteveIreland** [comment]
Does anyone use the backup button that's in general config?  Are there issues with it?

**Comment by thegm90** [comment]
Whaaaat?! That's in the app?! Where within is it?

**Comment by SteveIreland** [comment]
It's in the Configuration module under the General configuration tab .... last button at the bottom of the page.

I haven't yet tried to recreate a database from one, but it looks like the normal MySQL backup format.  I'd be interested to know if anyone has used it to recover or migrate their database.

**Comment by thegm90** [comment]
I volunteer as tribute :) we are still trying to update to fix the tax / profit issue I mentioned a few weeks back.

Will report back!

**Comment by thegm90** [comment]
Gave us a full backup with the button(hurray!). We just need to figure out how to execute this back on top of the update. 

Any suggestions for getting out backup back onto our digital ocean droplet?

**Comment by thegm90** [comment]
Did the download, figured out getting the DB on, and if you look at the attached, this is what we are seeing now. If you look at the lines running, you can see the database. Is there database differences from 3.1.0 to the new releaser(that fixes the tax issue)?

src="https://cloud.githubusercontent.com/assets/20656675/25912942/e84b5900-356d-11e7-9854-2518b5127cc6.png">

**Comment by SteveIreland** [comment]
It hasn't yet been set in stone, but I believe that the intent is to include the migration in the 3.1.0 release when deemed final.

The pull request does not introduce any database changes except the `migration` table that is automatically added by the migration module to keep track of the last migration that was run.

**Comment by themichaelmitchell** [comment]
@SteveIreland I am helping @thegm90 with the this (I'm his brother). Thank you for your help so far!

Currently running the latest from master (c4a76ad01ccd962b1b16d9fa21f97d541d9c1d38) in a docker environment.

Backed up the database, completely nuked the server, and started fresh from that commit above. Built it and up'd it, the website reveals a database error seen in the below picture. Issues #294 and #303 had similar issues but there wasn't much info that helped (use the latest master and read the readme).

Is there something that we're suddenly doing wrong? Is there a specific commit that we should be cloning from instead of master?

Thank you for all your help (everyone!), we appreciate it a bunch!

![image](https://cloud.githubusercontent.com/assets/20687946/25934207/56c4160c-35d1-11e7-808c-caf5826e7f40.png)

**Comment by SteveIreland** [comment]
I downloaded and installed that commit level of OSPOS into WAMP and it kicked it off without any problems.  I'm not yet familiar with the installation tools so if there is an issue where it's not setting up the correct configuration (which is what it sounds like) I can't help.   It sounds like a base reference issue of some type.

The two issues that you referenced were for a specific issue in a specific release back in January 2016 which was resolved way back then,  So I doubt if it's the same issue - but it will probably be similar.  If you can identify what was changed back when it was fixed it might provide a clue as to what needs to be corrected.

**Comment by themichaelmitchell** [comment]
If it helps, here is the `docker-compose up` result:

[Pastebin](https://pastebin.com/raw/AJY9894i)

**Comment by jekkos** [comment]
If you're using docker-compose up then you should mount the database.php inside the php container. There might be an issue with the database.php file inside the php container  not having the correct file permissions set.

Can you go into the php container as follows

`docker exec -ti opensourccepos_php_1 /bin/bash`

then check file permissions on database.php

`ls -la /app/application/config/database.php`

does it have the same owner as other filies?

**Comment by jekkos** [comment]
Otherwise you can mount a local database.php into the container to replace it, however I'm not sure what effect that willl give on the readability by the containerized apache process

**Comment by themichaelmitchell** [comment]
@jekkos Thanks a ton for the reply! Poked around in the php container and the database.php file didn't even exist!? Super weird. Checked the ~/github/opensourcepos/application/config folder and database.php existed there. I nuked all the images and containers, recloned the repo, rebuilt the containers, checked the php container again and same thing.

Since all other config files exist in the directory, [I'm assuming this line runs just fine...](https://github.com/jekkos/opensourcepos/blob/master/Dockerfile#L15)

Are you able to recreate this issue? Below is a screenshot of the config dir immediately after the php container is spun up. No trickery, pinky promise.

![image](https://cloud.githubusercontent.com/assets/20687946/25986186/627666e4-36a3-11e7-8edf-33b3968ea0d3.png)

**Comment by themichaelmitchell** [comment]
@jekkos You mentioned mounting the file, do you mean creating a volume directly to the application/config/database.php file from the existing database.php file?

Welp, got it to come up - question is why the database.php file gets destroyed in the first place. Are there logs somewhere in the container/host that would reveal something here?

For those joining us in the future--
I have temp fixed the issue doing the following:
`docker cp ~/path/application/config/database.php opensourcepos_php_1:/app/application/config
docker exec -it opensourcepos_php_1 chown -R www-data:www-data /app/public /app/application
docker-compose stop
docker-compose start`
This copied the sneaky database.php file into the container then set the permissions so apache could read it, then restarted the container. Pretty sure this is a temp fix.

Afterwards:
![image](https://cloud.githubusercontent.com/assets/20687946/25986515/2d5b8afa-36a5-11e7-9299-9d08f6d3dcfb.png)

**Comment by jekkos** [comment]
Hi yes I was just looking into this. Actually previously the database.php was copied during the initial docker image construction using docker cp. This line was removed as the database.php is supposed to be used as it is in the codebase without further modification. This thanks to the dotenv integration I did recently.

However I don't understand why it's not copied from the source during initial image construction. In fact after every commit travis rebuilds the  container and pushes it to docker hub. Need to check where this goed wrong exactly

**Comment by themichaelmitchell** [comment]
Ah, I see that commit now (#28141185a49cadfac683ca7de811930942d46ffa). Thanks for looking into it! Is there any info that I can provide to help out?

**Comment by thegm90** [comment]
Wanted to check in with you guys and see if there are any developments with the database.php?

**Comment by jekkos** [comment]
I checked my latest conrtainer and it does have database.php in it. Did you try remove and redownload the container from docker hub? Do a docker rmi -f jekkos/opensourcepos and then compose up again to see if that resolves the issue?

**Comment by themichaelmitchell** [comment]
Apologies on the delay. After wiping clean the web server (`docker rmi $(docker images` and `docker system purge`), recloning the github project, rebuilding and upping the containers, the database file appears to still be missing. Is there further info that I can provide that could help?

**Comment by jekkos** [comment]
Ok the dev container does seem to have the file. It might be the regular one that has it missing. I'll check later this week.

**Comment by thegm90** [comment]
Hey Jekkos, any news on your findings?

**Comment by jekkos** [comment]
I had another short look and indeed, the file is not in the container, didn't directly understand why. Will need to find some more time to investigate further.

**Comment by jekkos** [comment]
Should be fixed now @thegm90. Can you verify? Thanks!

**Comment by diranetafen** [comment]
HI @jekkos  , I was facing the same issue ( database.php missing in latest docker images)  last week, after your update all is OK now Thanks !
