### ISSUE TITLE
Touchscreen vieuw ?

### ISSUE THREAD

**Issue by spacecabbie** [jekkos/opensourcepos#1299]
I din't find a support forum so i am sorry if this is the wrong place to ask.

I was wondering if on the sales page i can have layout suitable for a Touchscreen.

whith icons where you select a cat like beverages then can select a drink.

Is this posible ?

**Comment by SteveIreland** [comment]
There is already a request in play for this at #401 

I think there are plans to make this happen.

**Comment by spacecabbie** [comment]
It seem exactly what i am looking for i would love to help but unfortunaly i am not a coder :(

**Comment by daN4cat** [comment]
It's a massive job to redesign and reimplement the UI and the controllers for a richer front end. The first step would be to move controllers to REST based APIs and then implement the UI with some more advanced js framework.
I don't know  when that will happen....
