### ISSUE TITLE
person first and last name

### ISSUE THREAD

**Issue by Raoufasker** [jekkos/opensourcepos#1301]
### Issue / Question / Bug

person first and last name not save in data base save first letter from name only and translate to arabic not complete

**Comment by daN4cat** [comment]
Is this a bug or else? Sorry but I don't get it.

**Comment by Raoufasker** [comment]
@daN4cat try to add Customers in arabic language database

**Comment by Raoufasker** [comment]
@daN4cat  notification new Customer add successfully not appear

**Comment by Raoufasker** [comment]
@daN4cat 
![Uploading 1.jpg…]()
![2](https://cloud.githubusercontent.com/assets/28680396/26035187/ab7e8e08-38c8-11e7-8239-47b000825d4b.jpg)
![3](https://cloud.githubusercontent.com/assets/28680396/26035188/ab8a13ae-38c8-11e7-918e-62679e37941c.jpg)

**Comment by daN4cat** [comment]
I can read or write Arabic I'm afraid. We need someone to do that and fix the bug.

**Comment by Raoufasker** [comment]
@daN4cat in ver 3.0.2 this bug not found

**Comment by daN4cat** [comment]
Ok if something comes to my mind I will let you know.

**Comment by daN4cat** [comment]
Can you test the email address and let me know if fine or not?

**Comment by Raoufasker** [comment]
email is ok Can you test notification new Customer add successfully not appear

**Comment by Raoufasker** [comment]
Can you tell me where the code is wrong and I will work on it

**Comment by Raoufasker** [comment]
@daN4cat if fix it thanks alot

**Comment by daN4cat** [comment]
go to ` application/controllers/Persons.php`, try to comment out the content of the function `protected function nameize` and just add a `return $str;` inside.
See if after that everything works fine. If yes that's the issue but we would need to find the correct function that works with arabic too.

**Comment by daN4cat** [comment]
@Raoufasker any update?

**Comment by jekkos** [comment]
Hmm not sure if this nameize is always correct. Sometimes in Belgium use of lowercase letters in surnames can denote a certain ancestor origin.
Also this formatting is now only applied to Persons controller and not to reports, sales, and all other modules.
Might be better to 

* Either clean the data before it goes into the db, so it's consistent everywhere
* Give user the option to enable it ?

**Comment by daN4cat** [comment]
It does before landing in the db

**Comment by daN4cat** [comment]
Yes I can add the option to enable disable it.

Maybe we can consider some schema do manage exceptions like the one you stated. Is valid example some like "de Ranter"?

**Comment by daN4cat** [comment]
Ok, in the Netherlands they have the "van Basten". Similar in German area with the "von Richter". They tend to be old or nobiliar family names.

**Comment by jekkos** [comment]
yes indeed, didn't know the word in english, nobiiliar or that you have aristocratic history..

**Comment by daN4cat** [comment]
This comment has a better solution managing UTF-8 and exceptions: http://php.net/manual/en/function.mb-convert-case.php#92317

**Comment by daN4cat** [comment]
Fixed using a composer library doing exactly what I needed: https://github.com/tamtamchik/namecase

**Comment by daN4cat** [comment]
@Raoufasker could you please check if it works fine with Arabic? It should support UTF-8 properly.

**Comment by daN4cat** [comment]
@Raoufasker any feedback?

**Comment by daN4cat** [comment]
No complaints, I close.
