### ISSUE TITLE
System issue

### ISSUE THREAD

**Issue by mvazquezolmos** [jekkos/opensourcepos#1303]
### IMPORTANT IMPORTANT IMPORTANT

Chose what you want to report: New Feature or Bug.
If you remove the template when submitting a Bug your issue will be closed as we cannot help without basic information.

### Issue / Question / Bug

Before submitting an issue please make sure you remove the first section of the template and you tick (add a x between the square brakets) and agree with all the following check boxes:

- [x] Checked the current issues database and no similar issue was already discussed
- [x] Read the README, WHATS_NEW and UPGRADE
- [x] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php5-gd, php-intl and sockets installed)
- [x] Reporting an issue of an unmodified OSPOS installation
- [x] PHP version is at least 5.5 and not 7.x
- [x] MySQL version is 5.5 or 5.6 and not 5.7
- [x] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [x] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [x] Know the name and version of OS, Web server and MySQL and will add to my issue report

### Installation information
tested with:

tested in Windows 7 x64 and Debian 8
PHP version 5.5.15
Apache 2.4.10
Mysql 5.6.20
tested with OPOS 3.0, 3.0.2  3.1.0, same problem with all versions
no firewall or antivirus installed
I created database using database.sql archive included in database folder
### Expected behaviour
Normal access to system modules

### Actual behaviour
the system dont display data in new item addition or in sales/receivings modules and in configuration module, the system is always charging and system dont give control to the user

other modules like suppliers or gift cards are working fine. system files was not altered in any form except for the database file like readme file says. 
![2017-05-14 06_11_02-open source point of sale _ powered by ospos 3 0 0](https://cloud.githubusercontent.com/assets/28684260/26050286/ab5cb5d4-3923-11e7-98cb-375826641b7b.png)
![2017-05-14 06_11_35-open source point of sale _ powered by ospos 3 0 0](https://cloud.githubusercontent.com/assets/28684260/26050288/ab5ef42a-3923-11e7-86f3-3a48070796e9.png)
![2017-05-14 06_12_10-open source point of sale _ powered by ospos 3 0 0](https://cloud.githubusercontent.com/assets/28684260/26050292/abadf93a-3923-11e7-9b65-d217da8e8f1c.png)
![2017-05-14 06_12_41-open source point of sale _ powered by ospos 3 0 0](https://cloud.githubusercontent.com/assets/28684260/26050290/ab680376-3923-11e7-87b8-cced3d1f31f7.png)
![2017-05-14 06_12_59-open source point of sale _ powered by ospos 3 0 0](https://cloud.githubusercontent.com/assets/28684260/26050289/ab67abe2-3923-11e7-9954-6ac32457a8fe.png)
![2017-05-14 06_13_23-open source point of sale _ powered by ospos 3 0 0](https://cloud.githubusercontent.com/assets/28684260/26050291/ab6b6e3a-3923-11e7-894e-618923b41725.png)

-what can be the problem? I feel is configuration but cant figure the problem by myself. thanks!

**Comment by odiea** [comment]
Appears you do not have all the necessary php extensions enabled. Read the wiki.
