### ISSUE TITLE
Items stock permission missing in Arabic interface

### ISSUE THREAD

**Issue by kmoj86** [jekkos/opensourcepos#1304]
### Issue / Question / Bug

Before submitting an issue please make sure you remove the first section of the template and you tick (add a x between the square brakets) and agree with all the following check boxes:

- [x] Checked the current issues database and no similar issue was already discussed
- [x] Read the README, WHATS_NEW and UPGRADE
- [x] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php5-gd, php-intl and sockets installed)
- [x] Reporting an issue of an unmodified OSPOS installation
- [x] PHP version is at least 5.5 and not 7.x
- [x] MySQL version is 5.5 or 5.6 and not 5.7
- [] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [x] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [x] Know the name and version of OS, Web server and MySQL and will add to my issue report

### Installation information
OSPOS 3.1.0
installed using docker compose file
Ubuntu server

### Expected behaviour
the Arabic interface to include the same permissions as the English one

### Actual behaviour
**when changing the interface to Arabic and navigating to employees permissions page, the checkbox for "stock" under Items section is missing. which results in leaving all users created using the Arabic interface not having permission to access the Items module, because the checkbox wasn't visible, so it's left unchecked. 
the pictures below might explain the issue better:**

![20170515_104141](https://cloud.githubusercontent.com/assets/28702682/26051364/a53a31ee-396a-11e7-9d4d-4e5824fbd196.png)

When switching to English interface:

![20170515_104314](https://cloud.githubusercontent.com/assets/28702682/26051384/b20b13ac-396a-11e7-8d44-c00d7af01e0a.png)

Which results into:

![20170515_124352](https://cloud.githubusercontent.com/assets/28702682/26052186/4a659116-396d-11e7-9359-c365b5a71fc3.jpg)

### Steps to reproduce the issue
the Arabic interface for permissions needs to be fixed.

**Comment by daN4cat** [comment]
Happy for you to help. I would start checking if the translation is in place in the file.

**Comment by kmoj86** [comment]
you're absolutely right!
so apparently if the term is left untranslated then the checkbox doesn't show at all.

after checking the translation files I found that the term "items_stock" is not translated and left blank. but after I typed the translation, the checkbox showed up again with the translation of course and all is good again.

![screenshot from 2017-05-15 15-24-23](https://cloud.githubusercontent.com/assets/28702682/26058485/c60e807a-3986-11e7-818d-0c3660dd2da6.png)

**Comment by daN4cat** [comment]
Read the wiki and use the tool Weblate to complete the translations. The wiki will give you the instructions.

**Comment by kmoj86** [comment]
Already am ;)
but thanks nonetheless

**Comment by daN4cat** [comment]
Good so I close this.
