### ISSUE TITLE
Make travis-CI build and deploy runnable zip artifact

### ISSUE THREAD

**Issue by jekkos** [jekkos/opensourcepos#1305]
I'd like to tidy up the vcs structure by omitting composer, node and bower dependencies. Builds should be downloadable from a hosting site and probably not from github. Also documentation can be generated and deployed along the way

**Comment by jekkos** [comment]
Just pushed a new branch with some modification to travis setup that would upload the zip to bintray after  building it

**Comment by SteveIreland** [comment]
This will be interesting.  I'm always open to try new things, but it feels like you're introducing things faster than I can catch up. :cold_sweat: 

But if you're simplifying then I am jumping on board with both feet!

**Comment by jekkos** [comment]
Well think we should have a better source / binary separation and omit those generated artifacts from the source repository (as they don't belong there)...

So but this means that you'll either get the source (and do the build setup) or get a dist zip that contains all you need to run (but then doesn't contains git information)

**Comment by jekkos** [comment]
Ok the upload from the featue branch seems  to work, but for some reason the folders included in the zip archive are empty. .to be investigated

**Comment by jekkos** [comment]
https://bintray.com/jekkos/opensourcepos/opensourcepos/

**Comment by daN4cat** [comment]
@jekkos what's the status of this task?

**Comment by jekkos** [comment]
I have to pick it up again, I had the  build running on travis and upload seemed to succeed with the build archive, however I couldn't find it on bintray.. will have a further look maybe somewhere this week if time permits

**Comment by hzzg6y** [comment]
Hi,
     Please can you help me to download the uncompressed developer version of this POS.  I don't need any compressed javascript or any tools used to compressed it. I am just looking for developer version with steps to bring up the website locally. Please advice. 

I know I am hijacking the topic.. but any pointers will really help.

Rgds,

**Comment by daN4cat** [comment]
@jekkos last push to close this? (and please fix as per my comment...)

**Comment by jekkos** [comment]
Found some time to wrap this up.. in fact a downloadable artifact is now published to bintray

https://bintray.com/jekkos/opensourcepos/download_file?file_path=opensourcepos.zip

can someone extract and see if it works?
advantage is now that we won't need to merge minified files (they are not in the source code anymore) but built and zipped by travis (as it should)
so devs will still be able to download directly from github, but need to setup the grunt / bower / composer first. Others can pick the zip from bintray (that contains all files needed to run)

**Comment by jekkos** [comment]
I guess we should add the link to the README once verified that it's working.

**Comment by odiea** [comment]
It downloaded and extracted just fine but I get the following error after submitting the login page. I have not had this issue before.
Object not found!

The requested URL was not found on this server. The link on the referring page seems to be wrong or outdated. Please inform the author of that page about the error.

If you think this is a server error, please contact the webmaster.
Error 404
localhost
Apache/2.4.18 (Win32) OpenSSL/1.0.2e PHP/7.0.8

**Comment by jekkos** [comment]
Ok indeed, I found the same issue when starting the docker container from the extracted zip.. not there yet it seems, could be a configuration issue

**Comment by odiea** [comment]
Let me know if you find an answer.

**Comment by odiea** [comment]
Here is the new folder.
![2017-08-03 11_00_59-opensource](https://user-images.githubusercontent.com/10962177/28933702-53cb8f5a-783b-11e7-9552-79910919bf70.png)

Here is the old folder.
![2017-08-03 11_02_04-barcode](https://user-images.githubusercontent.com/10962177/28933717-69b59e00-783b-11e7-861d-b2441bb3f675.png)

**Comment by odiea** [comment]
Don't know if the missing folders make a difference or not.

**Comment by jekkos** [comment]
It's just a minimal set of files to make the app run, in fact application and public should be suffiicient, the rest are development resources

**Comment by jekkos** [comment]
Ok I guess .htaccess files were missing, added them and a new build is underway
