### ISSUE TITLE
Blank page

### ISSUE THREAD

**Issue by rbwilkinson** [jekkos/opensourcepos#1307]
I am not able to get working. 
All files and .htaccess are set. 
Config and Database files are set.
I get no errors reported in my logs.
Just a blank page.

Using Apache2 on Ubuntu 16.04 with Virtualmin.

**Comment by Altoubi** [comment]
Please note that PHP needs to have php-gd, php-bcmath, php-intl, php-sockets, php-mcrypt and php-curl installed and enabled.


You can easily install it by this command:
sudo apt-get install php-****

**Comment by rbwilkinson** [comment]
All components are installed.

Initially no errors but now...
I have just now gotten this error.
**session_start(): Failed to initialize storage module**

**Comment by daN4cat** [comment]
Db is not right. Are you upgrading something preexisting by any chances?

**Comment by rbwilkinson** [comment]
A new installation. Downloaded from github.com

**Comment by rbwilkinson** [comment]
I will try to reinstall for 3rd time if necessary. I am keen to see the advances that have been made.

**Comment by daN4cat** [comment]
Ok so it might be a database configuration issue.

**Comment by rbwilkinson** [comment]
As this is a new installation I surmise that I only need to use database.sql. Correct?

**Comment by rbwilkinson** [comment]
It works. Not sure what went wrong but we are happy.

**Comment by Ramadhan1989** [comment]
i never find the database.sql file on the latest build
