### ISSUE TITLE
On submit double entry

### ISSUE THREAD

**Issue by katrexx** [jekkos/opensourcepos#1309]
(Version: 3.1.0) In all entry modal, by pressing tab button and last selection Submit button then press Enter button from keyboard, that's job dual entry.

**Comment by jekkos** [comment]
Did a fix for this, quite a tedious bug hunt sifting through js code. Can you check if fixed now?

**Comment by jekkos** [comment]
Seems to be an open issue in https://github.com/nakupanda/bootstrap3-dialog/issues/333)(bootstrap-modal project. So probably this can't be fixed in our code but fix has to be done in the library itself.

**Comment by jekkos** [comment]
Think I found a fix though, will clone bootstrap dialog to my own and include that dependency, rebuild, and then let you validate. If it works then I'll submit a PR to the original author so we can swtich dependencies again.

**Comment by jekkos** [comment]
Ok did the fix in the library itself. @katrexx can you verify? This has cost me a bit of time.. specially for you ;)

I'll make the PR to the original repo already so once intergrated there we can point back to their repo

**Comment by odiea** [comment]
I only tried this on Giftcard and it appears the issue has been resolved.

**Comment by jekkos** [comment]
Ok great, thanks for testing @odiea. I close.
