### ISSUE TITLE
sale/manage (Takings): table sorting doesn't work

### ISSUE THREAD

**Issue by daN4cat** [jekkos/opensourcepos#131]
Testing with Chrome at least, the table sorting doesn't work.
It should sort by different fields (e.g. Receipt, Date, Invoice and Customers).

**Comment by daN4cat** [comment]
The following code doesn't seem matching the table fields ordering:

	//Only init if there is more than one row
	if($('.tablesorter tbody tr').length > 1)
	{
		$("#sortable_table").tablesorter(
		{
			sortList: [[1,0]],
			dateFormat: 'dd-mm-yyyy', 
			headers:
			{
			    0: { sorter: 'datetime'},
				8: { sorter: 'invoice_number'}
			}
		});
	}

**Comment by jekkos** [comment]
I've looked into the sorting, indeed column 0 should just be disabled (no data there) and same for the last column. There was another bug in the sale_id identifier for the checkboxes (used for multi delete)

Commit 756b675e2ba6cfe9f2f299ec291a3a4adf64dc6e fixes these issues.

However one issue remains, which is that currently the last (total) row is sorted together with the other rows. I think it should remain on the bottom at all times. Maybe we could change the tablesorter selector to exclude this row (by adding a class on the other ones eg)

**Comment by jekkos** [comment]
This might be a solution as well http://stackoverflow.com/questions/14231081/avoid-disable-some-specific-rows-from-sorting-process-using-jquery-tablesorter-j

Will look into that later, took me quite a bit of time yesterday evening as well so gonna relax a bit as well now..

**Comment by daN4cat** [comment]
That's why the last line was <th> to avoid the sorting and of course make it bold. Anyway if I find the time I'll check the suggestions from the link you provided.

**Comment by jekkos** [comment]
OK did a fix for the totals row position. It should remain at the bottom now. Are there any known problems left related to sorting?

**Comment by jekkos** [comment]
Had to add an addtional bit of code to make it work properly after filtering (e62df579f143eb2ae73f6fda6323ec06b20b1d6f)

**Comment by odiea** [comment]
It appears the table sort quit working.

**Comment by jekkos** [comment]
A force refresh should solve this issue as everything seems to be working ok on my machine. I did correct another bug related to sorting after search, which I will commit later today.

Last issue standing is the tax inclusive calculation. The overview isn't correct in this case and this should be reviewed (will open a new issue for that)

**Comment by daN4cat** [comment]
Tax part, good point. Forgot about that scenario.

**Comment by jekkos** [comment]
Pushed another fix for table sorting after search (which required some rework). Should be working fine now.
