### ISSUE TITLE
How to remove "are you sure you want to submit this? this sale cannot be undone" message

### ISSUE THREAD

**Issue by aterad** [jekkos/opensourcepos#1310]
Question

Hello house,
I am new to opensourcepos 3.0.2 and i must confirm is a wonderful piece.
However, to cut the repetition and time wasted during sales, i will like to know which file to edit or line to comment out to bye pass the 
"are you sure you want to submit this? this sale cannot be undone" message after transaction is completed before proceeding to print out of receipt during sales or return under the SALES module.

Thanks in anticipatation

**Comment by odiea** [comment]
I downloaded and installed 3.0.2 and I cannot duplicate this issue. It goes directly to the receipt screen after pressing the Complete button.

**Comment by aterad** [comment]
Hello Odea,
Yes what i am saying is that, immediately you click complete button,  It prints directly by passing both d cannot be undone notice page and receipt screen page.
Please how do I go about editing this.
Thanks

**Comment by daN4cat** [comment]
That was removed, not sure why you see that. Is it a completely new installation or some mix up of stuff?
