### ISSUE TITLE
Unable to install OSPOS along with standalone Apache, PHP, MariaDb Setup

### ISSUE THREAD

**Issue by bill-goldberg** [jekkos/opensourcepos#1314]
### IMPORTANT IMPORTANT IMPORTANT

Chose what you want to report: New Feature or Bug.
If you remove the template when submitting a Bug your issue will be closed as we cannot help without basic information.

### New Feature / Enhacement

For New Features or Enhacements please remove all the template text and clearly write your proposal.
It's important to state whether you expect the community to implement it or you will contribute the work.
Please bear in mind that we will implement new features only on the current code, there is no support for old versions.

### Issue / Question / Bug

Before submitting an issue please make sure you remove the first section of the template and you tick (add a x between the square brakets) and agree with all the following check boxes:

- [x] Checked the current issues database and no similar issue was already discussed
- [x] Read the README, WHATS_NEW and UPGRADE
- [x] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php5-gd, php-intl and sockets installed)
- [x] Reporting an issue of an unmodified OSPOS installation
- [x] PHP version is at least 5.5 and not 7.x
- [x] MySQL version is 5.5 or 5.6 and not 5.7
- [x] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [x] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [x] Know the name and version of OS, Web server and MySQL and will add to my issue report

### Installation information
windows 10 x64
Apache 2.4.25-win32-VC14
php-7.1.5-Win32-VC14-x86
mariadb-10.2.6-winx64
Firefox v53

### Steps to reproduce the issue

**Comment by bill-goldberg** [comment]
I installed Apache, PHP and MariaDb individually. Put the master.zip (extracted and renamed ospos) in Apache24/htdocs/ , uploaded and configured the database. Also enabled some php extensions like intl, gd, curl, sockets etc from php.ini file. but unable to successfully setup the installation.

Please guide me about this type of installation. Apache and PHP are installed successfully.
![github](https://cloud.githubusercontent.com/assets/23611136/26465433/c4bf39a6-41a8-11e7-919c-a712a3654aa3.jpg)

**Comment by daN4cat** [comment]
The issues under windows are always the same, missing php extension (or impression it's enabled but it is not in reality), web server pointing to the wrong folder (should be public), issue with .htaccess config if you installed in a subfolder.
All discussed again and again....
