### ISSUE TITLE
Giftcard auto numbering stuck on 10

### ISSUE THREAD

**Issue by odiea** [jekkos/opensourcepos#1315]
### IMPORTANT IMPORTANT IMPORTANT

Chose what you want to report: New Feature or Bug.
If you remove the template when submitting a Bug your issue will be closed as we cannot help without basic information.

### New Feature / Enhacement

For New Features or Enhacements please remove all the template text and clearly write your proposal.
It's important to state whether you expect the community to implement it or you will contribute the work.
Please bear in mind that we will implement new features only on the current code, there is no support for old versions.

### Issue / Question / Bug

Before submitting an issue please make sure you remove the first section of the template and you tick (add a x between the square brakets) and agree with all the following check boxes:

- [x] Checked the current issues database and no similar issue was already discussed
- [x] Read the README, WHATS_NEW and UPGRADE
- [x] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php5-gd, php-intl and sockets installed)
- [x] Reporting an issue of an unmodified OSPOS installation
- [x] PHP version is at least 5.5 and not 7.x
- [x] MySQL version is 5.5 or 5.6 and not 5.7
- [x] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [x] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [x] Know the name and version of OS, Web server and MySQL and will add to my issue report

### Installation information
Current Master on Xampp
Store config is set to Generate in series.
![2017-05-26 09_28_45-wedidit _ powered by ospos 3 1 0](https://cloud.githubusercontent.com/assets/10962177/26501222/2fca9310-41f6-11e7-9109-d6e643e7db44.png)

### Expected behaviour

Giftcard auto numbering should get the next available number.
### Actual behaviour

Giftcard auto numbering always shows 10 as the last number.
### Steps to reproduce the issue
Gift Card Issue #65

**Comment by daN4cat** [comment]
@joshua1234511 you recently reworked this part, would you mind to check this issue please?

**Comment by joshua1234511** [comment]
@daN4cat 
Looking into it

**Comment by daN4cat** [comment]
Thanks

**Comment by joshua1234511** [comment]
Issue Fixed 
https://github.com/jekkos/opensourcepos/pull/1327

**Comment by daN4cat** [comment]
@joshua1234511 many thanks, it's merged. @odiea please test and close the issue if all fine. Thanks
