### ISSUE TITLE
Stuck at loading

### ISSUE THREAD

**Issue by ramddansyahreezdan** [jekkos/opensourcepos#1316]
Hello,
Why the screen stuck loading when the menu button choose? How to repair?
I cannot open the store config because it stuck while loading.
I m use OSPOS 3.1.0
![image](https://cloud.githubusercontent.com/assets/12878378/26517796/a7980706-42d2-11e7-9fe5-e028ca36b7f4.jpg)

**Comment by daN4cat** [comment]
Fill in the issue template please.
