### ISSUE TITLE
PHP Fatal error:  session_start():

### ISSUE THREAD

**Issue by the133448** [jekkos/opensourcepos#1317]
### Installation information

I followed the installation instructions on https://github.com/jekkos/opensourcepos/wiki/Installing-on-Raspberry-PI---Orange-PI-(Headless-OSPOS) Exactly. Everything went fine until the last step when I went and  went to http://192.168.0.22/opensourcepos/public/ where I got a error 500 on the page.
After going to the error log this is what I found.

[Sat May 27 16:33:32.361871 2017] [:error] [pid 5891] [client 192.168.0.14:54664:54664] PHP Fatal error:  session_start(): Failed to initialize storage module: user (path: sessions) in /var/www/html/opensourcepos/vendor/codeigniter/framework/system/libraries/Session/Session.php on line 143

**Comment by the133448** [comment]
Well I was editing the local opesourcepos on the pi not the one I moved to var/www Whoops!

**Comment by knichel** [comment]
I get this error after completing a fresh install as well.  I cannot seem to get past it.  Any help would be appreciated.

**Comment by ps011** [comment]
I'm also facing this error. Any help would be appreciated

**Comment by daN4cat** [comment]
Make sure the database is set properly in the config and access rights are correct on db side.

**Comment by wiliamvj** [comment]
I was having this problem, it was just the wrong bank password in config.php

**Comment by mckaygerhard** [comment]
the procedure install perfectly say that the password for db user must be changed, in step 5 of local deploy and step 8 of cloud local deploy here https://github.com/opensourcepos/opensourcepos/wiki/DOCS-USERS-Getting-Started-installations

**Comment by btr-simbu** [comment]
> Make sure the database is set properly in the config and access rights are correct on db side.

It worked after I changed my db user password.
Thank you #daN4cat.
