### ISSUE TITLE
Getting Blank Screen on login after Installation, please help

### ISSUE THREAD

**Issue by neofins** [jekkos/opensourcepos#1319]
![untitled](https://cloud.githubusercontent.com/assets/5234292/26521266/d2e103ac-4301-11e7-8be5-b2d472de66ca.jpg)

I installed opensource-POS as per instruction, on my local machine, (Win7, XAMPP, MySQL 5.6, PHP 5.6.23)
1. I got the login page
2. I used the given id pass ( admin, pointofsale ) to login..
3. Login done
4. I got a directory in URL Bar is ( http://localhost/neofins/public/home )

Issue, the page is blank... I don't know what to do to get the app visible.

**Comment by odiea** [comment]
Read the Wiki and check the Application/Config/database.php has been correctly edited. We assume you are using 3.1.0.

**Comment by neofins** [comment]
![image](https://cloud.githubusercontent.com/assets/5234292/26521345/24243e44-4304-11e7-969c-9fe9421c780f.png)
![untitled](https://cloud.githubusercontent.com/assets/5234292/26521352/43cbcc08-4304-11e7-8bdf-f2d0538fe784.jpg)

Yeah i am using 3.1.0 version on XAMPP... but getting blank screen...

**Comment by odiea** [comment]
I removed the images due to your password being shown. I assume this is a new install and all the necessary php extensions have been enabled.

**Comment by neofins** [comment]
YEAH

**Comment by odiea** [comment]
All I can suggest is to double check everything. I would suggest using the Xampp mysql and not a stand alone version and see how that works. I downloaded and installed 3.1.0  using XAMPP for Windows 5.6.15 with Maria db and I could not duplicate this issue.

**Comment by zeerk212** [comment]
I am also having same problem.. please anyone help me with it.. thanks
