### ISSUE TITLE
Items search by submission time

### ISSUE THREAD

**Issue by odiea** [jekkos/opensourcepos#132]
It would be great to add a date picker to the Items list. That way a person is not lost adding new items on a daily basis.

**Comment by daN4cat** [comment]
Please note that there is no date recorded in Items table. The only tracking is done via inventory, but then you get all the changes you do against an item.

What is the real use case here for a date field in Items?

The only case I can think of where you want to record some time is season in fashion/clothing retailing, like my case.

**Comment by odiea** [comment]
We own a thrift store and enter 800 to 1400 items a day. The employees would get lost trying to add Items then finding the Items to print tags or labels.

**Comment by odiea** [comment]
<iframe src="http://free.timeanddate.com/clock/i4u71ug5/n75/fs12/fcfff/tct/pct/ftb/tt0/tw1/tm1/th2" frameborder="0" width="224" height="17" allowTransparency="true"></iframe>

**Comment by daN4cat** [comment]
This is not coming easily like the sales transition. I'll have a look into what's there but personally I cannot commit any time for this feature at the moment.

You can check with Jekkos is he wants to implement this support for a fee.

**Comment by daN4cat** [comment]
Going back to this, the idea would be like in takings to have a date range so you can narrow down the search to what was inserted in a shorter period of time.

The default would all time, then one can narrow down the search. I asked my wife and indeed knowing what was inserted in a specific day or week would be useful to track down mistakes between orders / deliveries and packing list.

I'll look a bit in the code and see how difficult is to implement this. One issue is that the option bar is full so we would need to have two lines.

**Comment by daN4cat** [comment]
I've done an initial part of this which is more on the front end. Now I need to find a way to narrow down the list of items according to the time range against the inventory table.

**Comment by jekkos** [comment]
A query for the last inventory modification time for any item ? Something like

    select max(trans_date), ospos_items.* from ospos_items join ospos_inventory on trans_items = item_id having max(sale_time) between " . $start_date . " and " . $end_date

**Comment by daN4cat** [comment]
Yes, something down that line. It's working but I need to test it a bit.

**Comment by daN4cat** [comment]
OK in my master and submitted a PR. Please test and see if that fits the bill.

**Comment by odiea** [comment]
Date filtering not working for current date,Tax 1 is now showing in tax 2 when going to edit the item. Items entered today may or may not show up in items unfiltered list but Items added will show in suggestions. Looks like more work for you.

**Comment by jekkos** [comment]
Works fine so far on the other hand, no obvious errors or anything.

Only date filtering seems to be one day off. If I filter with latest day the 16th for an item that shows it's first inventory transaction on that date, then it doesn't appear in the list.

**Comment by daN4cat** [comment]
OK, I need to check the date range correctness. It's probably a time matter because I consider only the date. I guess time is by default set to midnight or down that line.

Not sure about the Tax story. That's less obvious here.

**Comment by daN4cat** [comment]
I found the time to check why the selected range was missing the end date items and fixed.

**Comment by daN4cat** [comment]
In jekkos/master now, this can be closed.
