### ISSUE TITLE
After Login Blank All Pages

### ISSUE THREAD

**Issue by ziko1153** [jekkos/opensourcepos#1323]
### IMPORTANT IMPORTANT IMPORTANT

Chose what you want to report: New Feature or Bug.
If you remove the template when submitting a Bug your issue will be closed as we cannot help without basic information.

### New Feature / Enhacement

For New Features or Enhacements please remove all the template text and clearly write your proposal.
It's important to state whether you expect the community to implement it or you will contribute the work.
Please bear in mind that we will implement new features only on the current code, there is no support for old versions.

### Issue / Question / Bug

Before submitting an issue please make sure you remove the first section of the template and you tick (add a x between the square brakets) and agree with all the following check boxes:

- [x] Checked the current issues database and no similar issue was already discussed
- [x] Read the README, WHATS_NEW and UPGRADE
- [x] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php5-gd, php-intl and sockets installed)
- [x] Reporting an issue of an unmodified OSPOS installation
- [x] PHP version is at least 5.5 and not 7.x
- [x] MySQL version is 5.5 or 5.6 and not 5.7
- [x] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [x] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [x] Know the name and version of OS, Web server and MySQL and will add to my issue report

### Installation information
os version: windows 8.1

apache version: 2.4.25

php version: 5.6.30

### Expected behaviour
after login then go to the home page and see the whole feature

### Actual behaviour
after login can't see any page.all of page shown blank.

### Steps to reproduce the issue

**Comment by daN4cat** [comment]
again and again always the same questions with windows. Please read the wiki and past closed issues. ..

**Comment by ziko1153** [comment]
i was also reading wiki but couldn't solve it.. i am the newbie please bro help me.. or suggest what should i do

**Comment by daN4cat** [comment]
Searched the closed issues. I don't use Microsoft stuff so I won't be able to help you.

**Comment by odiea** [comment]
You did not give much info. Are you using any of the amp's servers. No indication of sql. Try using xampp. Works good for me. Make sure all the needed extensions are setup properly.

**Comment by ziko1153** [comment]
i have spent around 6 hours to solve this issue.. but i am failed.... i am using xampp and read every topics on wiki but not solved.and i assure didn't any change of the original code and also every extensions are setup correctly .. actually why this issue has been occurred?  do  u know?

**Comment by odiea** [comment]
Which version of Xampp?

**Comment by ziko1153** [comment]
xampp--> 3.2.2

**Comment by ziko1153** [comment]
bro give me your  email or any contact pls.. i need this solution as soon as possible,.. please brother help me... please

**Comment by odiea** [comment]
Here is the list of extensions currently enabled in 2.2.2 
Current PHP version: 7.0.8 The following Php modules are enabled !

Array
(
    [0] => Core
    [1] => bcmath
    [2] => calendar
    [3] => ctype
    [4] => date
    [5] => filter
    [6] => hash
    [7] => iconv
    [8] => json
    [9] => mcrypt
    [10] => SPL
    [11] => pcre
    [12] => Reflection
    [13] => session
    [14] => standard
    [15] => mysqlnd
    [16] => tokenizer
    [17] => zip
    [18] => zlib
    [19] => libxml
    [20] => dom
    [21] => PDO
    [22] => bz2
    [23] => SimpleXML
    [24] => xml
    [25] => wddx
    [26] => xmlreader
    [27] => xmlwriter
    [28] => apache2handler
    [29] => openssl
    [30] => curl
    [31] => fileinfo
    [32] => gd
    [33] => gettext
    [34] => intl
    [35] => mbstring
    [36] => exif
    [37] => mysqli
    [38] => pdo_mysql
    [39] => pdo_sqlite
    [40] => sockets
    [41] => Phar
    [42] => ftp
)

**Comment by ziko1153** [comment]
bro all the modules are enabled.bro give me your email or any contact pls.. i need this solution as soon as possible,.. please brother help me... please

**Comment by odiea** [comment]
Sorry I do not give out my email address. Just make sure the extracted program is in the htdocs folder and your database is set correctly. Also if you downloaded it with Edge or Internet Explorer you will need to make sure the file has been unblocked to properly extract it. Also make sure you did not edit the Index.php or the .htaccess files that are in the public folder.

**Comment by ziko1153** [comment]
it is downloaded from firefox and my firewall is disabled on my computer and i downloaded directly from github... so whats wrong with this?

**Comment by odiea** [comment]
I sent you an email to your git address. I do have to go to work now so I will try later to see what is going on.

**Comment by ziko1153** [comment]
the email has not been sent please sent again bro ... i didn't receive yet

**Comment by ziko1153** [comment]
Okay solved it bro ... uninstall XAMPP and install WAMP 3.0.2 version and it runs smoothly.sorry for disturbing bro... extremely sorry
![ospos](https://cloud.githubusercontent.com/assets/14893207/26580582/89fc979a-455a-11e7-8979-f05cab444cc2.png)

**Comment by daN4cat** [comment]
This confirms again my theory that people should read the wiki and stick to what works especially on Windows!

**Comment by odiea** [comment]
Ya. The Windows ampps are kind of a hit and miss proposition with Windows.  I guess it's what ever the User gets working. I do believe the wiki is an important feature that should be read by all users.
