### ISSUE TITLE
Request to be able to add fractional quantities to labor items

### ISSUE THREAD

**Issue by SteveIreland** [jekkos/opensourcepos#1324]
### New Feature / Enhancement

I was asked to allow the number of hours to be entered for labor for a service item and I couldn't sell them on breaking hours into units and charging by the units.

So I need to change the sales item quantity to allow fractions of an hour.  My thought at the moment is to add a new item type of labor and only labor items would allow fractional quantities - everything else would be non decimal.

@jekkos is this something that you would be interested in seeing added to OSPOS or should I just do this in my own branch?

**Comment by odiea** [comment]
Is this something new. When I was fixing cars it was 1.0 or 1.3 or 1.5 or 2.5 is the way we charged for labor.

**Comment by SteveIreland** [comment]
You are absolutely correct.  I was demoing the system and they entered .5.  The system calculated a price based on the fractional quantity entered, but the quantity was refreshed to zero, so I assumed it was a database issue (without actually checking it).  I just now checked it and sure enough decimals are supported for the quantity field.  So it must be a bug it in the system somewhere.  I'll do more testing.   Thanks!

**Comment by RamkrishnaMondal** [comment]
You will need to set 'quantity decimal' to >0 in config to enable fractional quantity.
