### ISSUE TITLE
Alternate description needs to be longer.

### ISSUE THREAD

**Issue by SteveIreland** [jekkos/opensourcepos#1325]
### New Feature / Enhancement

I had assumed that the alternate description was the same length as the item description.  However, the item description is 255 and the alternate description is limited to 30 characters.  I'd like to expand that to 255 characters.

Is this change okay to make to OSPOS?

**Comment by jekkos** [comment]
How much characters can we actually display on the invoice? Might not make a lot  of sense to make the db field a lot larger than that?

**Comment by SteveIreland** [comment]
When I see "alternate" I assume that it is a replacement for the existing description.  The terms, additional, or supplemental would suggest that it should be added to the description.

I was assuming replacement so it should not be adding to the amount of information displayed.

However, if that's not actually how it should be implemented then this might be a change best left to my  branch only - and my earlier pull request should be rejected immediately.

They way I need to use it is that I have a set of service items named "Repair" and the user can add one or more of these repair labor items to the sale and change the description to be the exact repair to be made.  During our tests we found that the system was accepting more than 30 characters but would only print and save 30 characters of the additional description.

**Comment by daN4cat** [comment]
I have no opinion since I don't use this feature.

**Comment by jekkos** [comment]
Well indeed I think it just truncates the description before displaying it to screen..

**Comment by SteveIreland** [comment]
Actually there were three parts to fix this.  The first is that the sales_items.description field had to be changed from VARCHAR(30) to VARCHAR(255).  Then the save method had to be changed to substring the fiield at 255 characters instead of 30.  Then finally the quote view had to be changed so that the entire 255 characters would be displayed instead of being truncated by a too small viewing port.

**Comment by daN4cat** [comment]
So is the conclusion to extend the field to 255?

**Comment by odiea** [comment]
@SteveIreland  Will there be alternate Invoices and Receipts for this update?

**Comment by SteveIreland** [comment]
The way I'm coding it for the client is that it always prints the item name, but will only print the item description if the item is flagged to use alternate descriptions, otherwise it will not print the item description but will only print the item name.  However, if this seems like something that would be useful to OSPOS I'd probably add a system config option that will identify whether or not the item description should be printed on the quote and invoice, or just alternate description if provided, or never.

**Comment by SteveIreland** [comment]
So I should also pay attention to the receipt document too?  I expect that my client will use the receipt printer for part sales and quotes and invoices for repair and service sales - so that won't include item descriptions or alternate item descriptions.  

I'm currently adapting quotes to be used as "Work Orders" which will be used to track repairs as they proceed from what the customer asks for to what was actually done (parts ordered and labor).

**Comment by odiea** [comment]
With your new system can a Quote be changed to a Receipt when repairs are finished to prevent redundant typing of Entries?

**Comment by daN4cat** [comment]
What's the status of this? Being addressed, coming to 3.1.0 or else?

**Comment by SteveIreland** [comment]
I'm already using it in production at my site, but it is wrapped up with the work I was doing for work orders.  However, work orders is NOT a prerequisite for this change, so if you'd like it included in 3.1.0 I can probably do so easily enough this weekend by cherry picking the changes and creating a separate pull request for just that purpose. 

Do you want it in this release?  I'm pretty close to having the tax configuration changes done.

**Comment by daN4cat** [comment]
@SteveIreland it looks not a big change and if you have it already I would include it. I don't need but limiting the alt description doesn't make sense to me. So yes submit this change and we close this.

**Comment by SteveIreland** [comment]
The pull request has been submitted for this.

**Comment by daN4cat** [comment]
I merged but didn't test the alt description. However I found out that the invoice pdf sent over email contain an error in the subtotal line.
Unfortunately the error dump is cut so I can't read the code line number.

**Comment by SteveIreland** [comment]
I've never seen or tried out the PDF.  So I'll start looking into that too.

**Comment by daN4cat** [comment]
That's when you email the invoice as pdf attachment.

**Comment by daN4cat** [comment]
@SteveIreland one fix to go...

**Comment by daN4cat** [comment]
OK, I fixed receipts and invoice and receipt emails.

@SteveIreland no need to work on this. Please check the new tax category issue.
