### ISSUE TITLE
Query: Implementing a new search function that uses autocomplete

### ISSUE THREAD

**Issue by nvk1990** [jekkos/opensourcepos#1326]
###Question###
@jekkos @daN4cat @odiea 

Hi .. I'm trying to implement a sales person functionality in "sales screen" where the operator can select a sales person(Someone from employee list) similar to what he does for selecting a customer. I've implemented the functionality in application\views\sales\register.php that helps in creating a search bar, anchor, form  and the  javascript part in the same file which performs autocomplete. I'm able to redirect it till the controller to query data. I've already added the new model to autoload.php. However, I'm not able to populate the details on the screen.

Could you guys help me with the flow(a high level one will do as well) so that I will try to implement the feature by myself. Sorry if the question seems a bit naive but I've just started learning PHP and would love to contribute :)

**Comment by daN4cat** [comment]
As you said checking the customer search box in register should tell you want to do. Better than that example I don't see what else we could say.
I hope you understand that an ajax call is involved and the model needs to return a list of found strings based on the passed partial term.

**Comment by nvk1990** [comment]
@daN4cat I'm currently looking at the ajax call as well and it looks ok. However, I'm getting the below error in my code flow.

**views\sales\register.php**
`
<?php
		if(isset($salesperson))
		{
		?>
			<table class="sales_table_100">
				<tr>
					<th style='width: 55%;'><?php echo $this->lang->line("sales_salesperson"); ?></th>
					<th style="width: 45%; text-align: right;"><?php echo $salesperson; ?></th>
				</tr>
			</table>

			<?php echo anchor($controller_name."/remove_salesperson", '<span class="glyphicon glyphicon-remove">&nbsp</span>' . $this->lang->line('common_remove').' '.$this->lang->line('salespersons_salesperson'),
								array('class'=>'btn btn-danger btn-sm', 'id'=>'remove_salesperson_button', 'title'=>$this->lang->line('common_remove').' '.$this->lang->line('salespersons_salesperson'))); ?>
		<?php
		}
		else
		{
		?>
			<?php echo form_open($controller_name."/select_salesperson", array('id'=>'select_salesperson_form', 'class'=>'form-horizontal')); ?>
				<div class="form-group" id="select_salesperson">
					<label id="salesperson_label" for="salesperson" class="control-label" style="margin-bottom: 1em; margin-top: -1em;"><?php echo $this->lang->line('sales_select_salesperson'); ?></label>
					<?php echo form_input(array('name'=>'salesperson', 'id'=>'salesperson', 'class'=>'form-control input-sm', 'value'=>$this->lang->line('sales_start_typing_salesperson_name')));?>
					<br/>
				</div>
			<?php echo form_close(); ?>
		<?php
		}
		?>
`

**controllers\Salesperson.php**
`	public function select_salesperson()
	{
		
		$salesperson_id = $this->input->post('salesperson');
		echo "salesperson id is: $salesperson_id";
		if($this->salesperson->exists($salesperson_id))
		{
			$this->sale_lib->set_salesperson($salesperson_id);
			
		}

		$this->_reload();
	}	`

The echo statement always prints the same string I enter from the search box and doesn't get the ID for it. Ex: I search for 'XYZ' and echo prints 'XYZ'. However, for the customer search it correctly returns the person_id of customer from DB. 

Any pointers to what might be the issue?

**Comment by nvk1990** [comment]
@daN4cat @jekkos @odiea I've implemented the sales person functionality along with roles as Operator/Sales that can be edited/added to employees. However, on the sales screen I'm not able to show the search suggestions on the screen as it happens for items/customers. I have debugged the code using firebug and the response returned looks good. Below screenshots are for reference.

![image](https://cloud.githubusercontent.com/assets/28540763/26727307/fee161f6-47c3-11e7-84a4-86335d30ef2f.png)

![image](https://cloud.githubusercontent.com/assets/28540763/26726729/cd83619c-47c1-11e7-98b4-dbf02803c3aa.png)

![image](https://cloud.githubusercontent.com/assets/28540763/26726956/90304656-47c2-11e7-80aa-0c854169b732.png)

![image](https://cloud.githubusercontent.com/assets/28540763/26726750/dc45dc50-47c1-11e7-8548-ef909d2d08a6.png)

![image](https://cloud.githubusercontent.com/assets/28540763/26726769/e7ce2000-47c1-11e7-9458-a7e11bea5ed9.png)

**Comment by daN4cat** [comment]
Commit a Pull Request so I can see what you have done as without checking the code it's just guesswork....
