### ISSUE TITLE
Register tabbing behavior

### ISSUE THREAD

**Issue by SteveIreland** [jekkos/opensourcepos#1328]
### Issue / Question / Bug

I've found, when using the alternate description, that the behavior of the automatic updates when tabbing through the price and quantity results in the use of the tab key to essentially be useless because when I tab out of the price field or tab out of the quantity field then the full page is resubmitted and the cursor is re-positioned on the selection field.

I find it annoying but is this by design or is this a bug?

I think this might be the result of changes made to #1153 but I'm just guessing. 

This is on the latest version of 3.1.0 using Firefox Developer Edition.

**Comment by daN4cat** [comment]
@SteveIreland sounds a bug to me, if you want to fix it you are welcome.

**Comment by jekkos** [comment]
I kind of like to fix these little quirks for some reason, will have a look later this week.

**Comment by jekkos** [comment]
Think the submit triggers once the field blurs.. it might be more defensive to do that only if something was changed (thus by using change handler instead of blur or focusout)

**Comment by jekkos** [comment]
Should be fixed now.
