### ISSUE TITLE
delete url link invoice pdf

### ISSUE THREAD

**Issue by salikur** [jekkos/opensourcepos#133]
i want to delete url link in invoice print pdf. code not found in partial/header.php where is it??
![delete link](https://cloud.githubusercontent.com/assets/14150000/9705013/6ea34860-54e1-11e5-884c-e579387ac130.PNG)

**Comment by salikur** [comment]
http://localhost/opensourcepos-2.3.2/index.php/sales/complete  => how to delete this url link don't show in print pdf invoice or receipt

**Comment by daN4cat** [comment]
I assume you are using a pdf printer driver, correct?

If that's the case, what about checking the settings in the pdf printer driver?
I run a test and I don't see any issue with the pdf printer driver I have:

![image](https://cloud.githubusercontent.com/assets/636048/9712479/ca560c72-5542-11e5-946b-e2db0ea6939d.png)

**Comment by songwutk** [comment]
That's from your browser print setting.

**Comment by daN4cat** [comment]
Is this a browser specific issue?

**Comment by onyema3** [comment]
I don't think so

**Comment by daN4cat** [comment]
The OSPOS software itself doesn't add it, so you should check your configuration on the client side.

**Comment by salikur** [comment]
thanks...this issue solved. just edit header&footer in page setup browser
