### ISSUE TITLE
Unable to login /public/login was not found on this server

### ISSUE THREAD

**Issue by dmiralles** [jekkos/opensourcepos#1331]
### Installation information
Fresh installation on the cloud. Installed over MySQL 5.5 and PHP5. Database.sql file imported.

### Actual behaviour
After installation is completed and database is imported, I'm unable to login the application with credentials provided in the Readme file. admin // pointofsale

### Steps to reproduce the issue
Complete installation and try to log in.

Please, check attached screenshot
![unable to login](https://cloud.githubusercontent.com/assets/12034437/26687032/0fc640de-46ef-11e7-96a1-4ca9e9602d82.jpg)

**Comment by daN4cat** [comment]
Read past and closed issues. This was covered few times.

**Comment by dmiralles** [comment]
Hi, 

I've followed your advices but unfortunately, It is not working for me. 

I'm installing OSPOS on the GCE Cloud -> Linux -> Ubuntu 14.04. 

My configuration is the following:
- MySQL 5.5
- Apache 2.4.7
- PHP 5.5.9

I've used database.sql file imported to DB and I'm connecting properly. 
I've added my encryption key in the config.php, just a test with "test123"

Also, these are the extensions enabled for PHP:
root@ospos-eb-z8dq7-1:/home/davidmifo# php -m
[PHP Modules]
bcmath
bz2
calendar
Core
ctype
curl
date
dba
dom
ereg
exif
fileinfo
filter
ftp
gd
gdcm
gettext
hash
iconv
intl
json
libxml
mbstring
mhash
mysql
mysqli
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
readline
Reflection
session
shmop
SimpleXML
soap
sockets
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xml
xmlreader
xmlwriter
Zend OPcache
zip
zlib
[Zend Modules]
Zend OPcache

I've checked all the issue and it is not clear for me where is the problem. Could you please help me? It's a little bit urgent.

Thank you in advanced.

**Comment by dmiralles** [comment]
mcrypt is also installed as PHP extension

**Comment by daN4cat** [comment]
And have you checked your htaccess file inside public folder?
Is that configured correctly especially if you have a subdir?

**Comment by dmiralles** [comment]
Could you please provide me, some steps to check this information you mention?
I've installed the repo on var/www/html and to access through web-browser I've to enter ip/public to go to login page.

Thanks!

**Comment by daN4cat** [comment]
check the htaccess file in public. Have you opened it?

**Comment by daN4cat** [comment]
The fact that it's a subfolder requires a different rule in that htaccess file. Read the comments in the file...

**Comment by odiea** [comment]
Not Found The requested URL /opensourcepos/public/login was not found on this server. #920. Pay attention how to enable rewrite. I followed these directions on a new 10.04 server install and all worked ok .

**Comment by dmiralles** [comment]
Got it! Thank you so much! This information must be documented in the FAQ section. You'll avoid several questions like this one. :)

**Comment by odiea** [comment]
That is where the information came from.

**Comment by dmiralles** [comment]
I've not seen nothing related to .htaccess on the FAQ.

**Comment by odiea** [comment]
![2017-06-13 07_39_58-jekkos_opensourcepos_ open source point of sale is a web based point of sale sys](https://user-images.githubusercontent.com/10962177/27085112-947df34c-500b-11e7-8718-bf230663bb17.png)
