### ISSUE TITLE
Any way to change origin/destination of order AFTER completing it?

### ISSUE THREAD

**Issue by i92guboj** [jekkos/opensourcepos#1333]
Sorry for the question but, is there an easy way to change the origin or destination of a given order after completing it?

It has happened to me lots of times. After completing an order or requisition, I notice I entered it on the wrong storage location.

What I do now is:
A) I go to reports, search the order and delete it (haven't found another way to delete orders)
B) I enter again the whole order, this time, double-checking origin/destination for the order

With large orders this is tedious.

Let's imagine I have to storage locations called HOME and SHOP. Let's imagine I entered a reception order -wrongly- into HOME, but I want it now moved to SHOP so, is there a way to convert the order so that the destination is not SHOP?

Failing that, is there a way to generate a new order based on the old one so that the stock will move from HOME to SHOP?

If I need to resort to tables, then what do I need to take into account? I understand that the inventory table should need modification but then the stock tables would need to be recalculated taking also into account the already existing rows, right?

Is there any feature planned along this lines?

Thanks!

**Comment by jekkos** [comment]
You'll have to return the order first.

**Comment by i92guboj** [comment]
I don't understand that. Please, care to elaborate a bit more?

I can return the order, yes. Or I can just delete it because it should have never been ordered. From my point of view, and for this concrete case, it makes no difference.

But then I have to re-do manually the order again against the correct store(s).

Am I missing something?

What I am asking is if there's a way to automatically redo the order against the correct store(s) without having to delete it and manually entering all the references again.

Sorry if I am missing your point here and thanks for answering. :)

**Comment by jekkos** [comment]
You can do a requisition from one location to another. You'll need the receiving number and then input it in the order screen after setting mode to requisition. Then delete the items that were correct and move the wrongly inserted to the right location.

**Comment by i92guboj** [comment]
Hello and thank you for your help.

I can't manage to do it though. I've been trying but there's either something obvious that I am missing here, or we are missing each other's point hehe.

So, I'll illustrate with an example, keep in mind I use spanish localization, so the exact English words I'll use to refer to program options might not be exact, but I hope you'll be able to follow me. 

Let's imagine I make a new order. For that, I'll click the "reception" icon, and leave the input mode as "receive" and leave the default store (let's say it's SHOP) selected.

I enter the following references:
ref1
ref2
ref3

And submit the order. So, the stock for ref1, ref2 and ref3 in SHOP increases by 1 for each reference. Order is labeled as RECV 445.

Then, reviewing the report I see that I submitted the order to the wrong storage location. I should have selected HOME instead of SHOP, but didn't notice because I entered the order in a hurry (things happens when you have the shop full of customers and a good lot of packages arrives).

So, I tried what you suggested. I created a new order, selected requisition, from SHOP to HOME.

Then, if I understood you correctly, you can -somehow- enter the order id that you said I would need to do this, (445) to transfer the stock to another storage location. So, I tried to enter in the barcode field "REVC 445", "445", "RECV445" and a few other crazy things to see if that would work. Nothing worked so far.

I can enter the references one by one, and re-do the whole order, but that's not different from just erasing the original order and then creating a new one.

So, I am either missing something obvious or completely misunderstanding your indications. 

Sorry to be so obtuse, and thanks again for your guidance.

**Comment by jekkos** [comment]
Ok normally under requisition you should be able to enter the receiving id. This could be a bug as I recall that it worked in the past.

**Comment by jekkos** [comment]
To be investigated

**Comment by i92guboj** [comment]
Please, double check it. I don't want to trigger unnecessary alarms because of local setup issues. Maybe it's something in my cloned repo.

**Comment by daN4cat** [comment]
@jekkos any chances to push this through?

**Comment by daN4cat** [comment]
@odiea do you have time to test this scenario and confirm if an issue or not? I don't have that much time this week end.

**Comment by odiea** [comment]
For a Return to be found it has to be inputed RECV-space-then the recv number. RECV 12 otherwise it is not found. Requisition only uses Item numbers to transfer from 1 location to the other. So for his issue a requisition would have been fine. He could then add info to comments for an audit trail.

**Comment by daN4cat** [comment]
And requisition still works fine in 3.1.0?

**Comment by daN4cat** [comment]
If yes we close this.

**Comment by odiea** [comment]
Receive input is Item number.
Return input is RECV space number.
Requisition is Item number.
And yes all still works.

**Comment by i92guboj** [comment]
Hi.

I've finally found some time to test this. Yes, it works that way.

However that doesn't address my issue. 

I can undo a reception this way. But I don't see how this is different from just erasing the reception in reports.

What I wanted was to find a way to move a reception from incorrect storage A to correct storage B without having to input all lines one by one again.

I've been trying and returning the RECV number to another storage that's distinct from the original doesn't seem to make any difference. Maybe I am missing something.

**Comment by i92guboj** [comment]
This would be useful not only to correct human errors when entering orders, but also to mimic the served/not served state for a given order. For example, I could then enter the order when I -actually- order the product to my provider, and keep that order in a store called ORDERED. Then, when the packages enter by the door and I have the shop full of customers I'd only need to move the order from that store to SHOP, which would be much quicker.

**Comment by odiea** [comment]
Have you tried using a barcode scanner for returns or Item input.

**Comment by i92guboj** [comment]
I can do the input faster, no doubt. I was just asking whether there's a way to avoid having to duplicate the input.

If all comes down to that, I'll just SQL it and don't bother with the UI mechanics at all. ;)
