### ISSUE TITLE
Print a billing/invoice before complete the sale ?

### ISSUE THREAD

**Issue by kandesmond** [jekkos/opensourcepos#1338]
Hello there,

Is there a way to generate or print a billing/invoice before complete the sale ?

I see there's a feature named "invoice, quote and sale with invoice" but none of them allow me to print it before completing the sale?

I am going to use the POS at a restaurant so it's common and standard thing to generate and print a billing or invoice and show it to the customers when they are ready to pay/check out.

Thanks for your help in advance as always.
Desmond

**Comment by SteveIreland** [comment]
I suppose that the quote and invoice could be adapted for that purpose since the quote can easily be printed before any payments are made (the sale is suspended at that point) and then the final receipt (or invoice for that matter) can be printed after the payment has been processed.

**Comment by kandesmond** [comment]
Steve,

I found the post of https://github.com/jekkos/opensourcepos/issues/352 is the answer to my question.  So my next question is the solution in #352 will be implemented or is it already on the road map already?

thanks for your help as always.
-Desmond

**Comment by odiea** [comment]
Yes the Proforma is now the quote feature. So if you save the Sale as a Quote and print it for the customer it then can be turned into a paid receipt at the register once it is unsuspended.

**Comment by kandesmond** [comment]
Hum ... I didn't see a way or any option to print it as a quote?  Also, am i supposed to add my receipt printer as a ticket printer?  I don't see a way to add my receipt printer as a ticket printer as well.

Thanks
-d

**Comment by kandesmond** [comment]
My current setup is to print the receipt from the firefox

**Comment by odiea** [comment]
Yes I see what you mean. Maybe an appconfig can be added to either use the Invoice format or the receipt format for Quotes.

**Comment by kandesmond** [comment]
Hummm i thought i am just missing a button to click for print out the quote/unsuspended sale ?  Also, may i know what appconfig is?  Thanks

**Comment by odiea** [comment]
For the Quote and Invoice function to work you must enable it under Invoice in store config. Then to use the Quote or Invoice you have to select a customer from the customer list.

**Comment by kandesmond** [comment]
"Invoice" in store config has been set to enable it since day 1 but I just don't see any way to let me print it as a quote .... let me try it again tonight and post some screenshot with some outputs here tonight.

Thanks for your steps.

**Comment by odiea** [comment]
Sale must contain a customer.
![2017-06-13 17_55_19-wedidit _ powered by ospos 3 1 0](https://user-images.githubusercontent.com/10962177/27109693-9b7fb2a6-5061-11e7-835c-2777baef6f52.png)
 Click on Quote button and you will get the following.
![2017-06-13 17_55_42-wedidit _ powered by ospos 3 1 0](https://user-images.githubusercontent.com/10962177/27109710-b3dfdff6-5061-11e7-9087-98bd9e8bf37f.png)

**Comment by kandesmond** [comment]
Oh, no wonder.  I missed the customer info.  So is it possible to have the system to print out a quote without the customers name?  Is it easy to modify the codes to make the system to print without the customer info?

**Comment by kandesmond** [comment]
This POS is going to be for my restaurant to use.  I hope it make senses to you guys why i would like to print it as a quote without the customer info since the customers from restaurant seldom leave their names when they are ready to checkout.

**Comment by jowinlee** [comment]
My simple workaround with that is to simply create a guest customer like "Dine-In Guest"
![guest](https://user-images.githubusercontent.com/6857572/27201898-f4bc9ff4-5251-11e7-87b9-afed9c79b46a.png)

**Comment by kandesmond** [comment]
Yes i guess i will go with that option for now.

Thanks everyone
-d
