### ISSUE TITLE
I'm trying to get this done:  

### ISSUE THREAD

**Issue by xuzo** [jekkos/opensourcepos#1339]
I'm running windows 7 with Xampp, PHP5.6 , I see this in FAQ but I have NO IDEA how to do it! Any simple tutorial on this, no command line, just fix code in certain files manually?

`If a blank page (HTTP status 500) shows after search completion or receipt generation, then double check php5-gd presence in your php installation. On windows check in php.ini whether the lib is installed. On Ubuntu issue sudo apt-get install php5-gd. Also have a look at the Dockerfile for a complete list of recommended packages.`

**Comment by daN4cat** [comment]
Read past closed issues and wiki.
