### ISSUE TITLE
Sale by Quote is no longer being automatically suspended. 

### ISSUE THREAD

**Issue by odiea** [jekkos/opensourcepos#1340]
### IMPORTANT IMPORTANT IMPORTANT

Chose what you want to report: New Feature or Bug.
If you remove the template when submitting a Bug your issue will be closed as we cannot help without basic information.

### New Feature / Enhacement

For New Features or Enhacements please remove all the template text and clearly write your proposal.
It's important to state whether you expect the community to implement it or you will contribute the work.
Please bear in mind that we will implement new features only on the current code, there is no support for old versions.

### Issue / Question / Bug

Before submitting an issue please make sure you remove the first section of the template and you tick (add a x between the square brakets) and agree with all the following check boxes:

- [x] Checked the current issues database and no similar issue was already discussed
- [x] Read the README, WHATS_NEW and UPGRADE
- [x] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php5-gd, php-intl and sockets installed)
- [x] Reporting an issue of an unmodified OSPOS installation
- [x] PHP version is at least 5.5 and not 7.x
- [x] MySQL version is 5.5 or 5.6 and not 5.7
- [x] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [x] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [x] Know the name and version of OS, Web server and MySQL and will add to my issue report

### Installation information
Current OSPOS.
Xampp on Windows 10
### Expected behaviour
Quote was auto suspended unless discarded.

### Actual behaviour
Quote is no longer being auto suspended.

### Steps to reproduce the issue
Try creating a few quotes.

**Comment by SteveIreland** [comment]
I'll download and install a fresh snapshot tonight and check it out.  However, I have to ask, when you mean it's not suspended are you referring to the fact that it is no longer being written to the "suspended sales" tables?  

Quotes are still being suspended in my working branch (i.e. being flagged as suspended in the usual sales tables) ... so I'll check to make sure that something didn't break it in the "master" branch.

**Comment by odiea** [comment]
Previously when a quote was created it had the option on the print screen to discard. If it was not discarded it would then be suspended for future editing. The suspend part is not happening now.

**Comment by SteveIreland** [comment]
Okay.  The way it should be working now is by the time it gets to the print screen it is already "suspended".  The option to "Discard" should delete it from the sales tables and return the user to the sales register.

**Comment by SteveIreland** [comment]
I just wanted to report the results of my simple test.

I downloaded the latest master branch and set up a test environment for it with a fresh database and added a single item and customer.

I was able to prepare a quote and the quote was automatically suspended.

I was able to "unsuspend" the quote, but when I went to prepare an invoice from it the system failed with an undefined variable named `table_status` at line 718 in Sale.php.

I did not have the dinner table feature enabled so I suspect that has something to do with it.

**Comment by odiea** [comment]
Did you try multiple quotes. It appeared it did not show until the 2nd or 3rd try.

**Comment by SteveIreland** [comment]
I did not, but will do that now.

**Comment by SteveIreland** [comment]
I did 10 in a row with no problems - same customer and same item.  They are all showing under suspended sales for that customer.

Any other thoughts as to what might be unique to your setup that is different than mine?  The only configuration option I selected was to enable the Sales tax feature and I added a default state sales tax.

**Comment by SteveIreland** [comment]
What markup are you using for assigning quote numbers?

**Comment by odiea** [comment]
I think I found my issue. I have customer sales tax support enabled. If I do a quote for a person with the sales tax code it suspends just fine but if no sales tax is set or set to 1 for the customer that is when it will not store the quote.
![2017-06-13 17_17_17-wedidit _ powered by ospos 3 1 0](https://user-images.githubusercontent.com/10962177/27108755-55db5f66-505c-11e7-9f90-e0d65b5ce41b.png)
![2017-06-13 17_17_39-wedidit _ powered by ospos 3 1 0](https://user-images.githubusercontent.com/10962177/27108765-5fe0a30e-505c-11e7-8be6-4f74cced65d3.png)

**Comment by odiea** [comment]
It also does not charge Sales tax on the Sale if the Tax Code is set to 1.

**Comment by SteveIreland** [comment]
Okay, I'll take a look at that scenario now.

I just submitted a pull request to fix the the dinner table status error I was encountering.

**Comment by SteveIreland** [comment]
I'm assuming that you did not configure a default origin sales tax code under the general tab to be used for customers that don't have a specific tax code assigned.

**Comment by odiea** [comment]
Of course I did. Gotta figure out how to make things work or break.

![2017-06-13 19_32_06-wedidit _ powered by ospos 3 1 0](https://user-images.githubusercontent.com/10962177/27111689-1a1aee16-506f-11e7-90c9-d220d8d5bb81.png)

**Comment by SteveIreland** [comment]
I can't get it to break.  I'll pound on it some more tomorrow.

**Comment by odiea** [comment]
I do not test with debug or any other aid. I just download the app and try it out. I could not see your error or the errors @daN4cat saw earlier with another issue.

**Comment by odiea** [comment]
I downloaded the latest. Created a new db and everything is working correctly except when I go to discard a Quote it is still appearing in the suspended sales tables.

**Comment by odiea** [comment]
I am assuming that after I create a quote and do not want to accept it then the red button on the below image should remove the quote from the suspended table.
![2017-06-15 02_14_45-open source point of sale _ powered by ospos 3 1 0](https://user-images.githubusercontent.com/10962177/27172001-c5740944-5170-11e7-9057-d6bbc75463a9.png)

**Comment by odiea** [comment]
And I quote you from a previous comment.
"Okay. The way it should be working now is by the time it gets to the print screen it is already "suspended". The option to "Discard" should delete it from the sales tables and return the user to the sales register."

**Comment by odiea** [comment]
The issue of not suspending Sales was due to me enabling the Customer tax.

**Comment by daN4cat** [comment]
So is there a bug or no?

**Comment by odiea** [comment]
Only issue now is It is not discarding the Suspended Sale when pressing the Discard button. The other issues were my not using the Customer Tax properly.

**Comment by odiea** [comment]
Here is the error I am getting after clicking on the discard button in quote
![2017-06-15 15_24_07-wedidit _ powered by ospos 3 1 0](https://user-images.githubusercontent.com/10962177/27202464-f7703350-51de-11e7-8db3-fcc333379778.png)

**Comment by shimul2209** [comment]
without full payment why i don't print any sale invoice page.

**Comment by daN4cat** [comment]
@SteveIreland you need to look into this.

**Comment by odiea** [comment]
This is still an active issue when trying to Discard a Quote. In development mode the php errors show and Quote remains  Suspended. In production the quote will not be discarded.

**Comment by SteveIreland** [comment]
Okay, I'll take a shot at replicating this tonight and if I can then I'll include a fix for it along with with the fix for the discount amounts in a VAT scenario.  I'll try to submit a pull request for it tomorrow night.

**Comment by daN4cat** [comment]
I merged @SteveIreland's change, please test.

**Comment by odiea** [comment]
Tested and now works properly.

**Comment by SteveIreland** [comment]
For the record I need to correct an earlier comment.  The pull request did not include any other fixes because after identifying the cause of the issue, fixing it and testing it I didn't have adequate time to test the other fixes so I elected to create a push request just for this one.

**Comment by daN4cat** [comment]
Good approach I prefer to go one step at time.
