### ISSUE TITLE
TAX Migration Issue

### ISSUE THREAD

**Issue by waynebr76** [jekkos/opensourcepos#1341]
### issue/Question / Bug

Before submitting an issue please make sure you remove the first section of the template and you tick (add a x between the square brakets) and agree with all the following check boxes:

- [x] Checked the current issues database and no similar issue was already discussed
- [x] Read the README, WHATS_NEW and UPGRADE
- [x] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php5-gd, php-intl and sockets installed)
- [x] Reporting an issue of an unmodified OSPOS installation
- [x] PHP version is at least 5.5 and not 7.x
- [x] MySQL version is 5.5 or 5.6 and not 5.7
- [x] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [x] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [x] Know the name and version of OS, Web server and MySQL and will add to my issue report

### Installation information
Open Source Point Of Sale Version 3.1.0 

### Expected behaviour
Running reports should show the tax paid

### Actual behaviour
when running a report on sales prior to the upgrade the tax values differ between versions, the migrate script has been performed but the value are not aligned. For example:

Open Source Point Of Sale Version 3.0.2  shows tax as £40.86 (correct value but
Open Source Point Of Sale Version 3.1.0 shows £57.00

Reports run for sales after the migration shows the correct Tax values

### Steps to reproduce the issue

Run a report for a period prior to migration and check values.

**Comment by jekkos** [comment]
Ok thanks for testing this! We need help. Can you elaborate a bit on the specific configuration settings?
Using tax included or multiple taxes on items? Thanks.

**Comment by waynebr76** [comment]
Hi I am using tax included on my previous and current version

**Comment by waynebr76** [comment]
And it is just a single tax rate

**Comment by daN4cat** [comment]
VAT @ 20% included case. @SteveIreland we need you to finish this tax work since you promised support and bug fixing.....

**Comment by daN4cat** [comment]
The migration probably added the tax on old transactions without taking account the tax included option.

**Comment by waynebr76** [comment]
Thanks is it possible to rectify it once the migration had taken place?

**Comment by daN4cat** [comment]
I hope you created a databse backup

**Comment by waynebr76** [comment]
I do have a backup but didn't test the reports at the time so have a few days of sales in the new system. I guess I will just have to use the old system for historical reports

**Comment by SteveIreland** [comment]
At this point I didn't think the reports have been changed.  However, it's no surprise to me that this came up today.  I've been slammed with sofware issues from all corners today.

Thanks @waynebr76 for giving it try from the tax included side.  The migration can be rerun at any point if you clear the `sales_taxes` table.  During my development and testing I reran it numerous times.  But, of course, if there is an issue in the migration routine then I should fix that first.  And since the migration reuses quite a bit of the standard sales tax calculation there might be an issue there although no one has reported an issue with that .... yet. 

Are the extended amounts and totals for you environment being calculated correctly?

**Comment by waynebr76** [comment]
I'm not sure what you mean by extended amounts but the sales after the migration date Ppear to be adding up. I did also report an issue in that adding a discount at sale won't process and it was suggested that this may also be an issue in the tax update.

**Comment by daN4cat** [comment]
@SteveIreland you need to look into this.

**Comment by SteveIreland** [comment]
Okay

**Comment by daN4cat** [comment]
@SteveIreland could you please look into this? Thanks

**Comment by SteveIreland** [comment]
I addressed the issue where "adding a discount at sale won't process".  Hopefully that is resolved.  I tested numerous times in a VAT tax scenario with discounts after the fix that is already installed and it did what it was supposed to be doing for me.

I've made two failed attempts to start looking at the tax impact on reports (failed in the sense that I started it but had to abandon it to work on something else that seemed more urgent).  Right now I need to get the quote report working.  I'll rebase it to include your latest changes, and make sure I don't accidentally undo any of your corrections and publish it either today or tomorrow.

**Comment by daN4cat** [comment]
@waynebr76 any chance you can retest your issue with the latest code from master and see if it's fine?

**Comment by waynebr76** [comment]
Its going to take a while before I can test it as I have to start from scratch. For some reason I have an issue uploading backups of my existing set up as It fails with errors in the database tables.  Ive got some other issues to resolve first so might be a couple of weeks before I can try again

**Comment by waynebr76** [comment]
Hi I made some time to test, It does look like it is rectified
