### ISSUE TITLE
Hello!. I have a question. Can I take part of your code ?. I will create an opensource cms

### ISSUE THREAD

**Issue by erastus91** [jekkos/opensourcepos#1343]
### IMPORTANT IMPORTANT IMPORTANT

Chose what you want to report: New Feature or Bug.
If you remove the template when submitting a Bug your issue will be closed as we cannot help without basic information.

### New Feature / Enhacement

For New Features or Enhacements please remove all the template text and clearly write your proposal.
It's important to state whether you expect the community to implement it or you will contribute the work.
Please bear in mind that we will implement new features only on the current code, there is no support for old versions.

### Issue / Question / Bug

Before submitting an issue please make sure you remove the first section of the template and you tick (add a x between the square brakets) and agree with all the following check boxes:

- [] Checked the current issues database and no similar issue was already discussed
- [] Read the README, WHATS_NEW and UPGRADE
- [] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php5-gd, php-intl and sockets installed)
- [] Reporting an issue of an unmodified OSPOS installation
- [] PHP version is at least 5.5 and not 7.x
- [] MySQL version is 5.5 or 5.6 and not 5.7
- [] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [] Know the name and version of OS, Web server and MySQL and will add to my issue report

### Steps to reproduce the issue

**Comment by odiea** [comment]
It appears you can not read a template so I will assume they will say no.

**Comment by erastus91** [comment]
do you speak Spanish?. I use google translate

**Comment by odiea** [comment]
Cerveza and Bano is the extent of my Spanish. So no.

**Comment by erastus91** [comment]
ok. For what I read, talks about the complete point of sale. But it says nothing about extracting a piece of code.

**Comment by erastus91** [comment]
Could be taken as part of code developer.

**Comment by daN4cat** [comment]
CMS is not a POS system. CMS would be too generic to build a POS.

**Comment by daN4cat** [comment]
With regards to contribute, please check the list of open issues and see if you want to pick up a feature and develop it.

**Comment by erastus91** [comment]
The feature I would like to take is the controller extension, Secure_controller.php

**Comment by daN4cat** [comment]
I'm not sure I get, what would be that feature since there is already a Secure_controller?
Do you mean a better access control feature or else?

**Comment by erastus91** [comment]
Controller_secure.php if I can occupy it for the cms project?

On the other hand clone this repository and find an error.
Hashes do not match
Footer.php has this hash 4f5ad57
And session_sha1 has 93f24f6

![screenshot_4](https://user-images.githubusercontent.com/6712397/27195721-775558aa-51cd-11e7-8b76-39b96ee1ff63.png)
