### ISSUE TITLE
Change Language to French make php container crash with 500 error code

### ISSUE THREAD

**Issue by diranetafen** [jekkos/opensourcepos#1344]
Hi,
I have succefully BUILD and RUN docker container for opensourcepos.
But I am facing an issue, when i change the language to French the web server crash with 500 error code, and i'm not facing any issue using other language (chinise, German ...)
Please can you help me ?
Thanks in advance

Another thing : How can i view error log of php container, the "docker logs" command show me only access log but not php error.
I appreciated any answer about it.
Sorry for my bad english :-)

**Comment by erastus91** [comment]
speaking spanish?

**Comment by diranetafen** [comment]
@erastus91  No i am speaking French but i try to write my message en english. My problem is when i try to change the language to French the server web (php container) crash with 500 error code

**Comment by erastus91** [comment]
Switch from production to development to see the error

**Comment by daN4cat** [comment]
Most likely some translation is missing. Check the wiki to understand how you can help with the translations using Weblate.

**Comment by diranetafen** [comment]
Thanks for your answers.
@erastus91  how to make this (Switch from production to development to see the error) ?

**Comment by erastus91** [comment]
in the file public/index.php
![screenshot_5](https://user-images.githubusercontent.com/6712397/27201251-9ec55b96-51e2-11e7-965e-5bdd170792e8.png)

**Comment by diranetafen** [comment]
Thanks @erastus91  ; I will try this :-)

**Comment by erastus91** [comment]
You send a catch so we can see the error. The new version includes the French language, you need to indicate the version you have and the commit hash, to follow the error.

**Comment by diranetafen** [comment]
[Version]
![version](https://user-images.githubusercontent.com/18481009/27213842-9091921a-5269-11e7-9d53-e868f42b2bf2.PNG)

[Commit]
I am using the latest commit of the project

[Step to reproduce the error]

Step 1 : connect to web page and change language
![step1](https://user-images.githubusercontent.com/18481009/27213962-2f7caeb4-526a-11e7-9f9d-f0344f871bfb.PNG)

Step 2 : Submit the new language (French)
![step2](https://user-images.githubusercontent.com/18481009/27214013-6ee937d4-526a-11e7-9741-398cfa03e345.PNG)

Step 3 : Page stuck white

![step3](https://user-images.githubusercontent.com/18481009/27214074-b92571dc-526a-11e7-93a2-9d17a02432dc.PNG)

I will Switch from production to development to see the error to see more errors

Thanks in advance ! :-)

**Comment by diranetafen** [comment]
After switch to development mode, the error was displayed : 

![error](https://user-images.githubusercontent.com/18481009/27220676-4f9ab7f6-5286-11e7-9577-17db920a76c3.PNG)

**Comment by diranetafen** [comment]
I have solved my issue ! :-)

In the "/app/application/language/fr/config_lang.php" we have those <<"\\\\\ .....\\\\">>  character : 

![pb1](https://user-images.githubusercontent.com/18481009/27221230-1f2e321c-5288-11e7-89cf-bfce4f9e5645.PNG)
![pb2](https://user-images.githubusercontent.com/18481009/27221231-1f32ad1a-5288-11e7-856a-472e1add2043.PNG)


After remove those <<"\\\\>> and <<\\\\">> my problem was solved. I thing the double quotation ("") cause problem.
But i'm not a developer so you have certainly  a better explanation about this issue !!!

Thanks @erastus91  for your support !

**Comment by jekkos** [comment]
So then this issue also appear in the normal version? Can anyone confirm?

**Comment by jekkos** [comment]
Should be fixed now
