### ISSUE TITLE
Receivings Module issue

### ISSUE THREAD

**Issue by diranetafen** [jekkos/opensourcepos#1347]
I'm facing the following error with the receivings module : 

![issue](https://user-images.githubusercontent.com/18481009/27231587-5b39b6fc-52b3-11e7-9e53-9e844cf49420.PNG)

he have an incoherence between quantity of item in the total at the right side.

Thank you in advance for your answer :-)

**Comment by odiea** [comment]
Would you please test my fork and see if it fixes the issue. To work properly you must run receivings.sql from database.

**Comment by diranetafen** [comment]
@odiea  where can i find this receivings.sql  file ?

**Comment by odiea** [comment]
It is located in the Main directory in the database folder.

**Comment by diranetafen** [comment]
@odiea  I don't see receivings.sql  file name

**Comment by odiea** [comment]
It is a simple script that changes all the 0 to 1 in the items receiving quantity. You can run it .
UPDATE ospos_items SET receiving_quantity = 1 WHERE receiving_quantity = 0;

**Comment by diranetafen** [comment]
Ok i try it now

**Comment by odiea** [comment]
Click on my name and it will take you to my update. It is not in thsi branch.

**Comment by diranetafen** [comment]
![database](https://user-images.githubusercontent.com/18481009/27247483-2b45076c-52f9-11e7-9574-dab287acfd43.PNG)

The issue still present 

![issue2](https://user-images.githubusercontent.com/18481009/27247517-a3d030da-52f9-11e7-8a07-054903095383.PNG)

**Comment by odiea** [comment]
And did you get this from my fork?

**Comment by odiea** [comment]
You will have to download the full branch and test it.

**Comment by diranetafen** [comment]
all the source code ? because i have only take your script and execute it to my current mariadb container (on official repo)

**Comment by odiea** [comment]
Yes I had to change 3 or 4 separate files.

**Comment by diranetafen** [comment]
So i have to use your repository to build new container ?

**Comment by odiea** [comment]
The database had to be updated because 0 * an amount will still be 0.

**Comment by odiea** [comment]
Yes. I did not know your were using a container.

**Comment by diranetafen** [comment]
yes so the command that  i was using previously need to be run on the new build environnement using your repo ?

**Comment by odiea** [comment]
Yes.

**Comment by odiea** [comment]
I am not familiar with using the docker setup.

**Comment by diranetafen** [comment]
Ok i will do it in the morning (currently 01 a.m :-) )
Thank you for your help. I will give you the result

**Comment by odiea** [comment]
Thanks. I would like to have it tested before I ask for a pull request to the Master repo. Goodnight.

**Comment by diranetafen** [comment]
Hi @odiea ! It's working fine thanks for your support !!

![solved](https://user-images.githubusercontent.com/18481009/27253161-8f98cc64-536f-11e7-989e-3d9ceaf2df18.PNG)

**Comment by odiea** [comment]
Glad to hear that.
