### ISSUE TITLE
BLOCKED INTERFACE ON LOGIN

### ISSUE THREAD

**Issue by ebenezery4** [jekkos/opensourcepos#1348]
### IMPORTANT IMPORTANT IMPORTANT

Chose what you want to report: New Feature or Bug.
If you remove the template when submitting a Bug your issue will be closed as we cannot help without basic information.

### New Feature / Enhacement

For New Features or Enhacements please remove all the template text and clearly write your proposal.
It's important to state whether you expect the community to implement it or you will contribute the work.
Please bear in mind that we will implement new features only on the current code, there is no support for old versions.

### Issue / Question / Bug

Before submitting an issue please make sure you remove the first section of the template and you tick (add a x between the square brakets) and agree with all the following check boxes:

- [x] Checked the current issues database and no similar issue was already discussed
- [x] Read the README, WHATS_NEW and UPGRADE
- [x] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php5-gd, php-intl and sockets installed)
- [x] Reporting an issue of an unmodified OSPOS installation
- [x] PHP version is at least 5.5 and not 7.x
- x[] MySQL version is 5.5 or 5.6 and not 5.7
- [] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [x] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [x] Know the name and version of OS, Web server and MySQL and will add to my issue report

### Installation information
OSPOS VERSION 3.1.0 commit hash:4f5ad57
MySQL version is  5.6
PHP version is at least 5.6

OS: WINDOWS

### Actual behaviour
The application displayed a blocked user interface after login in  
![image](https://user-images.githubusercontent.com/17982781/27234620-97797d1c-52b5-11e7-8604-9f0b2a24b040.png)

### Steps to reproduce the issue

**Comment by erastus91** [comment]
https://github.com/jekkos/opensourcepos/issues/1345

**Comment by ebenezery4** [comment]
Which of the previous version should i download?
