### ISSUE TITLE
After Login issue

### ISSUE THREAD

**Issue by asparatu** [jekkos/opensourcepos#135]
After i login.. i get this error "No input file specified." I am using the current version from GitHub, I have used the older version from Source Forge all give the same error message.. When I run it on a Wamp server it works fine, not problems. This is linux server that is using GoDaddy as the host which is resold by another company. I have tried it on my server with linux also, it works but i get other errors.

the website is http://pos.pacificsantas.com

**Comment by jekkos** [comment]
This is a server (setup) config error. Please look in your log files and try to find out the issues that causes this. 

WIll close this as it's not really related to the codebase as such.

**Comment by asparatu** [comment]
I called the Host Provider and they seen nothing wrong with the hosting setup. I checked the error log and there is nothing in error log about it. Only thing I found was a references in http access log file and there is nothing else anywhere..

**Comment by jekkos** [comment]
Seems like a php config problem. Might also be related to user rights on the filesystem. Are you using linux? 

The webserver user should at least have read access to the php files (I guess mode 600)

**Comment by jekkos** [comment]
http://stackoverflow.com/questions/14555996/no-input-file-specified

**Comment by daN4cat** [comment]
Would be good to know what's wrong to add it in a wiki section: installation.

(I was even wondering if there was something unusual in .htaccess when I read this)

**Comment by asparatu** [comment]
Sorry... I have not been able to check it yet. I will tonight..

**Comment by asparatu** [comment]
Hello Jekkos,
    I have figured out why it i was getting that error.. Since this in a subdomain i was getting the  "No input file specified." I tried the solution you gave and did not work, so i looked around and it was combination of two things i had to do.. 

1. You need to change $config['uri_protocol']	= 'AUTO' to $config['uri_protocol']	= 'QUERY_STRING';
This is very important that you do this, if not you get some loop error and the page will never display.

2. add a .htaccess file in root folder of the subdomain with this code:
     <IfModule mod_rewrite.c>
              Options +FollowSymLinks
              RewriteEngine on
              RewriteBase /
              RewriteCond %{REQUEST_FILENAME} !-f
              RewriteCond %{REQUEST_FILENAME} !-d
              RewriteRule ^(.*)$ index.php?/$1 [QSA,L]
    </IfModule>

Thank you,
Shane
