### ISSUE TITLE
Issues with latest updates.

### ISSUE THREAD

**Issue by odiea** [jekkos/opensourcepos#1351]
### IMPORTANT IMPORTANT IMPORTANT

Chose what you want to report: New Feature or Bug.
If you remove the template when submitting a Bug your issue will be closed as we cannot help without basic information.

### New Feature / Enhacement

For New Features or Enhacements please remove all the template text and clearly write your proposal.
It's important to state whether you expect the community to implement it or you will contribute the work.
Please bear in mind that we will implement new features only on the current code, there is no support for old versions.

### Issue / Question / Bug

Before submitting an issue please make sure you remove the first section of the template and you tick (add a x between the square brakets) and agree with all the following check boxes:

- [ x] Checked the current issues database and no similar issue was already discussed
- [x] Read the README, WHATS_NEW and UPGRADE
- [x] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php5-gd, php-intl and sockets installed)
- [x] Reporting an issue of an unmodified OSPOS installation
- [x] PHP version is at least 5.5 and not 7.x
- [x] MySQL version is 5.5 or 5.6 and not 5.7
- [x] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [x] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [x] Know the name and version of OS, Web server and MySQL and will add to my issue report

### Installation information
Todays pull with git

### Expected behaviour
Items and Register should work.

### Actual behaviour

No Items in table and Register displays errors.
### Steps to reproduce the issue
![2017-06-19 15_26_17-wedidit _ powered by ospos 3 1 0](https://user-images.githubusercontent.com/10962177/27306760-22eb407e-5504-11e7-8b89-83d08d7cd023.png)

![2017-06-19 15_26_57-wedidit _ powered by ospos 3 1 0](https://user-images.githubusercontent.com/10962177/27306770-2b199e30-5504-11e7-9de7-f0a6f7d954ba.png)

**Comment by SteveIreland** [comment]
I have a similar issue.  I downloaded the latest 3.1 beta last night and was going to set up 2 or 3 test environments only to discover I couldn't add an item.  I ran out of time to figure out why, but I wasn't even getting a PHP error.

**Comment by odiea** [comment]
I was able to get it working after reverting this commit or just changed it back to the original.
![2017-06-20 07_02_18-show string placeholders if translations are missing 1349 jekkos_opensource](https://user-images.githubusercontent.com/10962177/27334433-8abebd16-5586-11e7-9772-6010cda49ebd.png)

**Comment by daN4cat** [comment]
@jekkos can you please fix?

**Comment by jekkos** [comment]
Ok should be fixed now

**Comment by SteveIreland** [comment]
This fix also resolved the issue I was having with adding a new item. Good job!

**Comment by jekkos** [comment]
Ok really? Changed the behavior a bit when we have missing translations.. Hope this way people get motivated to contribute them as most languages have quite a few missing
