### ISSUE TITLE
Invoice Problem

### ISSUE THREAD

**Issue by OnePlus5** [jekkos/opensourcepos#1352]
Thanks for this wonderful opensource software. Yesterday I've installed this on my Desktop.
So my question is what if customer is paying after few days.(borrowing) or paying less amount of the actual bill. How to create this type of invoices?  And how to track this transactions I mean how can I find how much money they need to pay me.

**Comment by odiea** [comment]
Currently the solution is to export the Invoices to a spreadsheet and track it from there.
