### ISSUE TITLE
English lang issue.

### ISSUE THREAD

**Issue by odiea** [jekkos/opensourcepos#1355]
### IMPORTANT IMPORTANT IMPORTANT

Chose what you want to report: New Feature or Bug.
If you remove the template when submitting a Bug your issue will be closed as we cannot help without basic information.

### New Feature / Enhacement

For New Features or Enhacements please remove all the template text and clearly write your proposal.
It's important to state whether you expect the community to implement it or you will contribute the work.
Please bear in mind that we will implement new features only on the current code, there is no support for old versions.

### Issue / Question / Bug

Before submitting an issue please make sure you remove the first section of the template and you tick (add a x between the square brakets) and agree with all the following check boxes:

- [x] Checked the current issues database and no similar issue was already discussed
- [x] Read the README, WHATS_NEW and UPGRADE
- [x] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php5-gd, php-intl and sockets installed)
- [x] Reporting an issue of an unmodified OSPOS installation
- [x] PHP version is at least 5.5 and not 7.x
- [x] MySQL version is 5.5 or 5.6 and not 5.7
- [x] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [x] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [x] Know the name and version of OS, Web server and MySQL and will add to my issue report

### Installation information
Xampp on Win 10
Ospos current version

### Expected behaviour
Should see suspended

### Actual behaviour

Shows language error
### Steps to reproduce the issue
![2017-06-23 08_11_35-wedidit _ powered by ospos 3 1 0](https://user-images.githubusercontent.com/10962177/27485856-ad9f4870-57eb-11e7-8958-2e7697e5bee9.png)

![2017-06-23 08_05_23-opensourcepos_suspended php at master jekkos_opensourcepos](https://user-images.githubusercontent.com/10962177/27485717-1839e4fc-57eb-11e7-9ccd-56061566aa81.png)
No language support for this .
![2017-06-23 08_06_15-opensourcepos_sales_lang php at master jekkos_opensourcepos](https://user-images.githubusercontent.com/10962177/27485737-2d119e38-57eb-11e7-950d-cbca3f621563.png)

**Comment by daN4cat** [comment]
With or without table enabled I don't see that issue:

![image](https://user-images.githubusercontent.com/636048/27508605-dbfef666-58e0-11e7-9a55-c0792fde280f.png)

**Comment by daN4cat** [comment]
OK, I see it's missing indeed. I checked the code

**Comment by daN4cat** [comment]
Fixed
