### ISSUE TITLE
Support Question

### ISSUE THREAD

**Issue by waynebr76** [jekkos/opensourcepos#1357]
###  Question 

Before submitting an issue please make sure you remove the first section of the template and you tick (add a x between the square brakets) and agree with all the following check boxes:

- [x] Checked the current issues database and no similar issue was already discussed
- [x] Read the README, WHATS_NEW and UPGRADE
- [x] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php5-gd, php-intl and sockets installed)
- [x] Reporting an issue of an unmodified OSPOS installation
- [x] PHP version is at least 5.5 and not 7.x
- [x] MySQL version is 5.5 or 5.6 and not 5.7
- [x] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [x] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [x] Know the name and version of OS, Web server and MySQL and will add to my issue report

### Installation information

Fresh Install from Master

### Expected behaviour
N/A

### Actual behaviour

All of a sudden today my OSPOS has ecountered an issue, the system loads and I can log in but then the page greys out and I just get the processing circle. How do I work out what has broken and how I fix it? I have tried a fresh download of the files and I have the same issue,
### Steps to reproduce the issue

**Comment by odiea** [comment]
You can try deleting your browser history and see if it reloads properly. If you changed languages try changing it back to English

**Comment by waynebr76** [comment]
Thanks I tried deleting browser and this wont work, I have tried a different browser and PC and its the same issue. I am trying to restore the database from a backup but for some reason i'm having issues importing the Items table as i keep getting issues with duplicate primary key. Using a fresh install with no data it works fine but If I switch the database to the existing database then I get the issue.

**Comment by waynebr76** [comment]
I am now getting an issue with the new master download, I  get a 500 error when trying to access OSPOS using the new files, has something changed that I should be updating in the new setup?

**Comment by daN4cat** [comment]
what's the version of OSPOS that you used to create the original database?

**Comment by waynebr76** [comment]
It was 3.0.2, I can access the old version of the site using the old database and the upgrade worked up till last night and not sure what happened. I also cannot load the new OSPOS module I just get a 500 error - the old version 3.0.2 still loads on the same site but from a different folder

**Comment by odiea** [comment]
It appears you will need to do the database updates.

**Comment by waynebr76** [comment]
Hi I did the updates, it was working and not sure why but overnight it stopped working, The database updates wouldnt cause the 500 error would it?

**Comment by odiea** [comment]
1. Have you enabled all the necessary php extensions.
2. Are you accessing it using the localhost/ospos/public.

**Comment by waynebr76** [comment]
I'm accessing it through www. And I believe all extensions are enabled is I'm using the previous version on the same server and this works.

**Comment by odiea** [comment]
All I can suggest now is to read the FAG's and the Wiki.You did not give info on OS or type of web server you are using.

**Comment by odiea** [comment]
Not Found The requested URL /opensourcepos/public/login was not found on this server. #920

**Comment by waynebr76** [comment]
Thanks, I'm using the normal steps for installing it on a Ubuntu 14 04 server. I will check again tomorrow I may just have to stick to the older version as that's working

**Comment by daN4cat** [comment]
You need to change the .htaccess if you installed OSPOS in a subdir, that was discussed various times.

Having said that, 3.1 is not release yet and still under development. Therefore if you plan to use it in production I would say it's not a good idea.

**Comment by SteveIreland** [comment]
NOW you tell me!

**Comment by nileshanand2** [comment]
yum -y install sudo git nano gedit wget curl epel-release net-tools links mlocate net-tools 
rpm -Uvh https://mirror.webtatic.com/yum/el7/webtatic-release.rpm
yum install -y  httpd mariadb mariadb-server net-tools mod_php71w php71w-opcache php71w-fpm php71w-bcmath php71w-cli php71w-common php71w-dba php71w-devel php71w-pdo php71w-pecl-apcu php71w-pecl-imagick php71w-pear php71w-mysql  php71w-tidy php71w-xml php71w-xmlrpc php71w-soap php71w-snmp  php71w-pgsql php71w-mbstring php71w-mcrypt php71w-ldap php71w-intl  php71w-imap php71w-fpm php71w-gd

sed -i 's/^/#&/g' /etc/httpd/conf.d/welcome.conf
sed -i "s/Options Indexes FollowSymLinks/Options FollowSymLinks/" /etc/httpd/conf/httpd.conf
gedit /etc/httpd/conf/httpd.conf &>/dev/null
ServerName
timedatectl
gedit /etc/php.ini &>/dev/null
date.timezone ="Asia/Kolkata"

systemctl start httpd.service mariadb.service php-fpm.service ; systemctl enable httpd.service mariadb.service php-fpm.service
mysql_secure_installation

mysql -u root -p 
create database example; 
grant all privileges on example.* to example@'localhost' identified by 'example'; 
flush privileges; 
exit 

firewall-cmd --permanent --zone=public --add-service=http  ; firewall-cmd --permanent --zone=public --add-service=https ; firewall-cmd --reload

wget https://github.com/opensourcepos/opensourcepos/releases/download/3.1.1/opensourcepos.20170909085348.3.1.1.76a002.zip 
unzip opensourcepos.20170909085348.3.1.1.76a002.zip -d /var/www/html/as

cat <<EOF | sudo tee -a /etc/httpd/conf.d/www.example.com.conf
<VirtualHost *:80>
    ServerAdmin me@example.com
    DocumentRoot "/var/www/html/as/"
    ServerName example.in
    ServerAlias www.example.in
    <Directory "/var/www/html/as/">
        Options Indexes FollowSymLinks
        AllowOverride All
        Order allow,deny
        Allow from all
        Require all granted
    </Directory>
    ErrorLog "/var/log/httpd/www.example.in-error_log"
    CustomLog "/var/log/httpd/www.example.in-access_log" combined
</VirtualHost>
EOF
apachectl configtest
chmod -R 777 /var/www/* && chown apache:apache -R /var/www/html ; apachectl restart 
echo '192.168.0.40  www.example.in' >> /etc/hosts
gedit /var/www/html/as/application/config/database.php &>/dev/null
root
toor
example

gedit /var/www/html/as/application/config/config.php &>/dev/null
3AZ6curM0WOmQkyE7KsAIK7Maqf4Uyxc

gedit /var/www/html/as/public/.htaccess &>/dev/null
#RewriteRule ^(.*)$ index.php?/$1 [L]
RewriteRule ^(.*)$ /var/www/html/as/public/index.php?/$1 [L]

systemctl restart mariadb httpd ; systemctl enable mariadb httpd
http://www.example.in/public/
username: admin
password: pointofsale
