### ISSUE TITLE
sale/manage (Takings): wrong amount due for tax inclusive pricing

### ISSUE THREAD

**Issue by jekkos** [jekkos/opensourcepos#136]
New functionality should be reviewed for tax inclusive pricing.

**Comment by daN4cat** [comment]
Good point.

**Comment by jekkos** [comment]
It seemed that calling the temp table function from the constructor was not a good idea. The function did a check on the tax_included config option which for some reason always returned false in this situation. I moved the create statements to where they're needed and now there's another issue that popped up, which appears once you have multiple items in a sale with tax inclusive pricing. For some reason amount due and change are not correct in this case.

Also the total below seem to be off from time to time, so this will need some further investigation.

**Comment by odiea** [comment]
A Database Error Occurred

Error Number: 1146

Table 'ospos.ospos_sales_items_temp' doesn't exist

SELECT first_name, last_name, email, comment, sale_payment_amount AS amount_tendered, payment_type, invoice_number, sale_time, employee_id, customer_id, comments, sale_id, (sale_payment_amount - total) AS change_due, DATE_FORMAT( sale_time, "%d-%m-%Y" ) AS sale_date, CONCAT(first_name, " ", last_name) AS customer_name, SUM(item_unit_price * quantity_purchased * (1 - discount_percent / 100)) AS amount_due FROM (`ospos_sales_items_temp`) LEFT JOIN `ospos_people` ON `ospos_people`.`person_id` = `ospos_sales_items_temp`.`customer_id` WHERE `ospos_sales_items_temp`.`sale_id` = '78' GROUP BY `sale_id` ORDER BY `sale_time` desc

Filename: C:\xampp\htdocs\tabbed\system\database\DB_driver.php

Line Number: 330
 also nothing is showing in the edit screen.

**Comment by jekkos** [comment]
Should be fixed again in latest commit (forgot to push that one).

**Comment by jekkos** [comment]
Looks the amount due and change due columns were off because the total per item line was used and in this case the total should be summed in both situations. This was probably an issue unrelated to tax inclusive pricing (as the formula for that is applied directly to the temp sale table).

Beside this the payment amounts seem to be off from time to time, which will need some more investigation.

**Comment by jekkos** [comment]
I think I found the last culprit here. The summary was queried using a join of sales_temp with sales_payments. This join already contains the cartesian product of sales with sales_items, which caused the payment amounts to double once there were multiple items in a sale.

I fixed this by just using the sales joined with sales_payments. In this case there's no performance penalty as before (don't need the items in this case) and the group by works correctly cause the tables are matched side by side.

Payment type totals seem to equal sum of the table now, so I'm closing this issue until further notice.

**Comment by daN4cat** [comment]
OK, I put the sales_temp without thinking of the mutliple entries case. I believe the summary_payment might have something similar. Worth checking.

**Comment by jekkos** [comment]
This bug was only related to the summary. The payment amounts coming from the get_all() function should be fine as long as you're not aggregating as they're duplicated as well due to the join between sales and sales_items

in this case there's a separate subquery with group_concat correlated with the outer query on the temp table to show the payment method + amount is correct for every row (but duplicated as wel lin this case)

**Comment by jekkos** [comment]
This is actually the reason that the initial query didn't work well. It tried to join sales, sales_items and sales_payments without creating a new cartesian product for that last match. There wasn't really another way to make it performant enough and this solution (split up between joins of sales, sales_items and sales and sales_payments) looks a bit better to me.

**Comment by daN4cat** [comment]
OK, I'll see if I can find the time over the week-end to check your changes.

Thank you for all the work, sorry if in the end my real contribution was just 20% of the feature.... but the end result looks good and a nice addition to ospos :-)

Thanks agian.
