### ISSUE TITLE
access forbidden error please help me guys

### ISSUE THREAD

**Issue by gg009** [jekkos/opensourcepos#1363]
Access forbidden!

You don't have permission to access the requested directory. There is either no index document or the directory is read-protected.

If you think this is a server error, please contact the webmaster.

Error 403

localhost
Apache/2.4.25 (Win32) OpenSSL/1.0.2j PHP/7.1.6

i am using xampp server  v3.2.2
i imported the database file thats fine 
i also changed the credential of the database.php file to as per my need
but when i am trying to access the project by entering localhost:8080/ospos/public
am getting error like access is forbidden.you dont have permission like this error above mentioned in starting line of the issue or i will get the page is not working please help me what i want to do..please am new to these please guide me

**Comment by odiea** [comment]
Read the Faq's and the Wiki.

**Comment by gg009** [comment]
sir we are doing an project i want to speak with you sir.when you are free
please intimate me sir

**Comment by daN4cat** [comment]
Have you searched the closed issues?
