### ISSUE TITLE
opensourcepos javascript file

### ISSUE THREAD

**Issue by bill-goldberg** [jekkos/opensourcepos#1364]
can i get the opensourcepos.js file ? presently only minified file is available in the source code.

**Comment by daN4cat** [comment]
You can create it, follow the developer instructions.

**Comment by bill-goldberg** [comment]
i want to use latest jquery for this application. what will be the impact after removing this opensourcepos.js file?

**Comment by bill-goldberg** [comment]
Can you please describe it more... i didn't understand  the reply "follow developer instructions"

**Comment by daN4cat** [comment]
Sorry to be blunt and straight but after reading your previous post I recommend you to drop this idea. I'm under the impression that you are a bit confused of this js story.

**Comment by bill-goldberg** [comment]
please tell me what are the steps to create opensourcepos. js uncompressed version
