### ISSUE TITLE
Sales Report to include option for Quotes

### ISSUE THREAD

**Issue by SteveIreland** [jekkos/opensourcepos#1366]
### New Feature / Enhancement

Right now the Sales Detail and Sales Summary reports filter on All, Returns, and Sales.  I would like to add a filter that will include Quotes so that a report that includes all pending quotes (or in my case Work Orders that are in progress) can be generated.

Would it be agreeable to contribute this small change here?

**Comment by daN4cat** [comment]
Yes

**Comment by SteveIreland** [comment]
I started this assuming that it was going to be a trivial add of a filter.  However, I found that it wasn't so trivial due to the use of  temporary tables.  Since there were changes to the SQL statements this weekend I'm going to start over again tomorrow after reviewing the latest changes to Sales.php

**Comment by daN4cat** [comment]
This is done and needs just a bit of testing.

**Comment by odiea** [comment]
I did a little bit of testing. If  a quote has been suspended it does not show up in the Reports until quotes is selected.

**Comment by daN4cat** [comment]
Is that an expected behaviour @SteveIreland ?

**Comment by odiea** [comment]
I believe that is what @SteveIreland intended. It is not considered a Sale until it turns into an Invoice or paid for when it is finished. It's just in limbo as work progresses on it.

**Comment by SteveIreland** [comment]
That is correct. Also, in many situations a quote can be a commitment for a period of time to a certain price.  So it needs to be considered "active" until the quote is no longer valid and is cancelled.  That would be one reason that some businesses might want to report and manage active quotes.
