### ISSUE TITLE
/login not found on this server

### ISSUE THREAD

**Issue by katika** [jekkos/opensourcepos#1368]
### IMPORTANT IMPORTANT IMPORTANT

Chose what you want to report: New Feature or Bug.
If you remove the template when submitting a Bug your issue will be closed as we cannot help without basic information.

### Issue / Question / Bug

Before submitting an issue please make sure you remove the first section of the template and you tick (add a x between the square brakets) and agree with all the following check boxes:

- [x] Checked the current issues database and no similar issue was already discussed
- [x] Read the README, WHATS_NEW and UPGRADE
- [x] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php5-gd, php-intl and sockets installed)
- [x] Reporting an issue of an unmodified OSPOS installation
- [x] PHP version is at least 5.5 and not 7.x
- [] MySQL version is 5.5 or 5.6 and not 5.7
- [] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [x] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [x] Know the name and version of OS, Web server and MySQL and will add to my issue report

### Installation information
php 5.6.30
mariadb 10.0.28
OSPOS 3.0.2
Debian 8.6
Apache 2.4.10

### Expected behaviour
After input admin/pointofsale for login, expect normal processing

### Actual behaviour
End up with " The requested URL /login was not found on this server."

### Steps to reproduce the issue
**apache config:**
ServerAdmin webmaster@localhost
        DocumentRoot /var/www/html/public
        DirectoryIndex index.php index.html

**.htaccess config:**
# if in web root
RewriteRule ^(.*)$ index.php?/$1 [L]

# if in subdir comment above line, uncomment below one and replace <OSPOS path> with your path
#RewriteRule ^(.*)$ ../pos/public/index.php?/$1 [L]

I have carefully check all others issues and solutions for this problem, en vain. apache did not log anything unusual

Any help appreciated

**Comment by daN4cat** [comment]
Please check previous closed issues as this was covered for sure.

**Comment by katika** [comment]
is this issue always related to .htaccess configuration ?

**Comment by daN4cat** [comment]
Do you have ospos under a subdir in html/public root?

**Comment by katika** [comment]
yes, in /var/www/html

**Comment by katika** [comment]
Any suggestions?

**Comment by daN4cat** [comment]
Check some old issues or wiki, I remember somebody said something about Apache configuration and what to pay attention to.

**Comment by katika** [comment]
thanks, i'll check
