### ISSUE TITLE
Add cache breaker mechanism for minfiied javascript file

### ISSUE THREAD

**Issue by jekkos** [jekkos/opensourcepos#137]
Users are seeing a lot of problems during testing after javascript updates. This is due to cached versions of the javascript that have to be force refreshed from the browser. This issue leads to a lot of false bug reports and extra overhead for maintainers.

proposed solution: introduce grunt cache breaker plugin to generate a new, unique minified js file after changes have been applied in one of the scripts. This will cause the browser to fetch the new file instead of loading it from the cache

**Comment by odiea** [comment]
Sounds like a great addition to me.
