### ISSUE TITLE
How can I replace field name: UPC/EAN/ISBN

### ISSUE THREAD

**Issue by bmghandi** [jekkos/opensourcepos#1370]
### Issue / Question / Bug

Before submitting an issue please make sure you tick (add a x between the square brakets with no spaces) and agree with all the following check boxes:

- [x] I checked open and closed issues database and no similar issue was already discussed (please make sure you searched!)
- [x] I read the README, WHATS_NEW and UPGRADE
- [x] I read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php5-gd, php-intl and sockets installed)
- [x] I read the wiki
- [x] I'm reporting an issue of an unmodified OSPOS installation
- [x] I ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql), and migrating function
- [x] I'm aware the latest master could be a development version and therefore not stable
- [x] I know the version of OSPOS and git commit hash (check the footer of your OSPOS), the name and version of OS, Web server, PHP and MySQL and will add them to my issue report

### Installation information

- OSPOS version is: 3.0.2
- OSPOS git commit hash is: 4f5ad57
- PHP version is: 7.x
- MySQL version is: 5.7
- OS and version is: Ubuntu 16.04.1
- WebServer is: Apache 2.4
- Any specific installation package for the LAMP/LEMP stack I used: none

### Expected behaviour
OK

### Actual behaviour
OK

### Steps to reproduce the issue
None

Hi,  I am new to OS POS and thanks to all the developers for the great work.

I have just a very simple question and I hope this is the right place to ask.

In there a way I can easily change the field name: "UPC/EAN/ISBN" to something more intuitive like "BARCODE".  I know this is a very minor issue but I wanted something my employees can easily recognize without any explanation.

Thanks.

**Comment by odiea** [comment]
You can edit application/language/yourlanguage/items_lang.php
And change the following line.
$lang["items_item_number"] = "UPC/EAN/ISBN";
This should get you to where you want to change.
This may alter other tables or line of code.

**Comment by bmghandi** [comment]
Yes, that worked, thanks.  
In the same file, I also changed the line:
$lang["items_number_required"] = "UPC/EAN/ISBN is a required field" accordingly.

**Comment by daN4cat** [comment]
@odiea @jekkos should we change that translation to a generic Barcode one?

**Comment by odiea** [comment]
Thats a tough one. In Items view it is designated as either of the 3 barcode options. If a user is using the item id for barcodes then it does not show in that table view. It would need the option of replacing item_number with item_id to view the items proper barcode.

**Comment by odiea** [comment]
This is the code I was able to use in the Register view that changed that option.
~~~
<?php if(!empty($item['item_number'])) 
	{
     ?>
 <td><?php echo $item['item_number']; ?></td>							 					
<?php
}
else
{
?>
<td><?php echo $item['item_id']; ?></td>
<?php
}
?>
~~~
![2017-07-02 04_44_37-wedidit _ powered by ospos 3 1 0](https://user-images.githubusercontent.com/10962177/27769179-69b55dd2-5ee1-11e7-8ed0-e7c80c2f6666.png)
But with my limited skill I could not get that to change in Table_helper.

**Comment by jekkos** [comment]
In my inventory I hardly have any product without UPC or barcode. There's a couple of generic items that shouldn't have inventory for which we generated barcodes, but that's about it.

**Comment by daN4cat** [comment]
The point here is just a translation, instead of "UPC/EAN/ISBN" simply call it "Barcode". It's a more human (sale assistant) digestible name. Techie stuff is not equal to great user experience (UX).

**Comment by daN4cat** [comment]
Done, old techie acronyms gone forever...
