### ISSUE TITLE
Error Add/Update New Item

### ISSUE THREAD

**Issue by bkrajendra** [jekkos/opensourcepos#1371]
### Issue / Question / Bug
- [x] I'm reporting an issue of an unmodified OSPOS installation
- [x] I checked open and closed issues database and no similar issue was already discussed (please make sure you searched!)
- [x] I read the README, WHATS_NEW and UPGRADE
- [x] I read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php-gd, php-intl, sockets and etc. installed)
- [x] I read the wiki
- [x] I ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql), and migrating function
- [x] I'm aware the latest master could be a development version and therefore not stable
- [x] I know the version of OSPOS and git commit hash (check the footer of your OSPOS), the name and version of OS, Web server, PHP and MySQL and will add them to my issue report

### Installation information

- OSPOS version is: 3.1.0 
- OSPOS git commit hash is: 4f5ad57
- PHP version is:   5.6
-  MariaDB version is:  4.6.5.2
- OS and version is:  Windows 7
- WebServer is:   Apache 2.4
-  XAMPP

### Expected behavior

Adding new entry in Items

### Actual behavior

While adding new entry in Items section I'm getting error
```
Error Add/Update New Item <Item Name>
```

This actually  creates entry in ospos_items table but ospos_items_taxes is not getting updated.

**Comment by daN4cat** [comment]
Which tax configuration?

**Comment by bkrajendra** [comment]
Tax Include, i'm not using latest TAX system (customer tax)

**Comment by daN4cat** [comment]
Tested with latest master using 20% VAT tax included and had no issues in creating a new item.

Please check you installation or write down the exact steps to reproduce the issue

**Comment by pvernekar-cci** [comment]
Unable to add new item.

**Comment by odiea** [comment]
Are these new installs or upgrades?

**Comment by daN4cat** [comment]
Nobody knows... "just doesn't work" and you guess

**Comment by pvernekar-cci** [comment]
@odiea  it is new install

**Comment by odiea** [comment]
I just downloaded it. "Saw my mistake" and had no issues with adding items using Xampp version.
 Windows Version:  Home  64-bit
XAMPP Version: 5.6.15
Control Panel Version: 3.2.2  [ Compiled: Nov 12th 2015 ]

**Comment by pvernekar-cci** [comment]
On mac it doesnt work?

**Comment by odiea** [comment]
Sorry I do not have a Mac. The only suggestion is to re-download the current version from https://github.com/jekkos/opensourcepos and create a new database using database.sql.

**Comment by odiea** [comment]
You do have to remember this is not a Release version it is still in Beta so do not use it for production unless you are willing to put up with Things not working properly.
