### ISSUE TITLE
opensourcepos.min.js

### ISSUE THREAD

**Issue by bill-goldberg** [jekkos/opensourcepos#1379]
I am looking for Opensource developer version code having no minified js ( javascript). I don't need docker image, bower or grunt to be used. I just need the plain source code which I can deploy & use it. 

I am  not able to locate how to get the developer version. Please help or advice on steps or point for documentation for same.

**Comment by jekkos** [comment]
Look no further! the plain source is not in this repository. In fact parts are but other parts are installed by bower!
and these are not included as you'll need to download them yourself. So no other way than to install grunt / bower if you want a dev environment.
