### ISSUE TITLE
###Question Reprint/ Review Customer Receipts?

### ISSUE THREAD

**Issue by thegm90** [jekkos/opensourcepos#1382]
We run a liquidation business, I was curious if you guys are aware of a feature to pull up a specific receipt for reviewing purposes, or to reprint for a customer?

**Comment by thegm90** [comment]
Under receiving, you can review.

**Comment by daN4cat** [comment]
Indeed

**Comment by thegm90** [comment]
I'm so sorry @daN4cat for spamming. Is there a way to search the customer and see? if they came back and didn't remember the date they came, would make it easier.

**Comment by daN4cat** [comment]
Reports -> specific customer

**Comment by thegm90** [comment]
Love it! Thank you
