### ISSUE TITLE
Stop identical items from grouping together so discount can be applied to one item

### ISSUE THREAD

**Issue by esbyrt** [jekkos/opensourcepos#1383]
### Issue / Question / Bug

Before submitting an issue please make sure you tick (add a x between the square brackets with no spaces) the following check boxes:

- [x] I'm reporting an issue of an unmodified OSPOS installation
- [x] I checked open and closed issues database and no similar issue was already discussed (please make sure you searched!)
- [x] I read the README, WHATS_NEW and UPGRADE
- [x] I read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php-gd, php-intl, sockets and etc. installed)
- [x] I read the wiki
- [x] I ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql), and migrating function
- [x] I'm aware the latest master could be a development version and therefore not stable
- [x] I know the version of OSPOS and git commit hash (check the footer of your OSPOS), the name and version of OS, Web server, PHP and MySQL and will add them to my issue report

### Installation information

- OSPOS version is: 3.2.2
- OSPOS git commit hash is: 4f5ad57
- PHP version is:   (e.g. 5.5, 5.6, 7.0, 7.1) 5.6.3
- MySQL or MariaDB version is:   (e.g. MySQL 5.5, MySQL 5.6, MySQL 5.7, MariaDB 10.0, MariaDB 10.1, MariaDB 10.2)  10.0.31
- OS and version is:   (e.g. CentOS 6.9, Ubuntu 16.4, Windows 10) Windows 10
- WebServer is:   (e.g. Apache 2.2, Apache 2.4, Nginx 1.12, Nginx 1.13) Apache 2.4.25
- (If applicable) Installation package for the LAMP/LEMP stack is:   (e.g. WAMP, XAMPP)

**Comment by daN4cat** [comment]
Use the serialised checkbox in the item edit form and each item will be one new line the registry cart. In that way you can apply different discounts.

**Comment by esbyrt** [comment]
Thank you for the quick answer! That did the trick beautifully after I updated my item table.

**Comment by phantomgannon** [comment]
I have a similar problem but need to either prevent the grouping together of the same item or be able to adjust the quantity of serialised items. I have 1000's of items with minor price variations and am struggling to find a quick way to process a pile of 40 items. Is it possible to fund this feature (disable grouping)?

**Comment by jekkos** [comment]
Hi we have the bulk edit feature in the items screen for this. But this ofcourse won't work if you want to apply discounts in bulk.
