### ISSUE TITLE
Stock Location Updates

### ISSUE THREAD

**Issue by BitMari** [jekkos/opensourcepos#1389]
I changed/updated the name of my stock locations but i have noted if i go to permissions there is the old names and now everything is confusing and i cant do anything about it. Any idea how i can resolve this

**Comment by BitMari** [comment]
They are the old and the new location names but yet its still the same location with just a different name

**Comment by daN4cat** [comment]
Yes, there is a problem. If you change name it creates a new entry instead of changing the name

**Comment by jekkos** [comment]
OK actually I rewrote that configuration part in the multistore branch .. but it has only been rebased up to 3.0... could be scheduled for 3.3 release for example

**Comment by jekkos** [comment]
If I remember well then stock location config was then moved to the multistore module itself.. it would allow one to create dozens of locations for ospos all using the same database..

**Comment by daN4cat** [comment]
I fixed this, you can rename the stock location. However there is now the common issue that none of the added entries can be deleted.
