### ISSUE TITLE
What is the best way learn OSPOS ? Contribute Back to community ?

### ISSUE THREAD

**Issue by hemakumar08** [jekkos/opensourcepos#1390]
Hi Everyone,
I am not a PHP developer but have an experience with Web application development. I would like start learning this application and Contribute my knowledge to this community.
To start off what are developement tools that we use in this project..
PHP
Codeigniter
MySQL

Whatare visual developement tools and best practices that are used across the board.
Give us some suggestions.

**Comment by daN4cat** [comment]
Yes those technologies and also js and css + html for the front end.

Read the wiki to understand what's required for the development.

Of course the first step is Github. .....

**Comment by SteveIreland** [comment]
One must also learn the ways of the F-Force.  Difficult to achieve, but a noble goal, it is.

**Comment by uditsingh07** [comment]
you should also go for jQuery, PLsql, TLSql and javascript
