### ISSUE TITLE
An Error Was Encountered The action you have requested is not allowed. 

### ISSUE THREAD

**Issue by robards** [jekkos/opensourcepos#1392]
### Issue / Question / Bug

Before submitting an issue please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] I'm reporting an issue of an unmodified OSPOS installation
- [x] I checked open and closed issues database and no similar issue was already discussed (please make sure you searched!)
- [x] I read the README, WHATS_NEW and UPGRADE
- [x] I read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php-gd, php-intl, sockets and etc. installed)
- [x] I read the wiki
- [?] I ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql), and migrating function
- [x] I'm aware the latest master could be a development version and therefore not stable
- [x] I know the version of OSPOS and git commit hash (check the footer of your OSPOS), the name and version of OS, Web server, PHP and MySQL and will add them to my issue report

### Installation information

- OSPOS version is: 3.0.2
- OSPOS git commit hash is: 4f5ad57
- PHP version is:   (e.g. 5.5, 5.6, 7.0, 7.1) 5.6
- MySQL or MariaDB version is:   (e.g. MySQL 5.5, MySQL 5.6, MySQL 5.7, MariaDB 10.0, MariaDB 10.1, MariaDB 10.2) MySQL 5.5
- OS and version is:   (e.g. CentOS 6.9, Ubuntu 16.4, Windows 10) Raspbian 8 Jessie
- WebServer is:   (e.g. Apache 2.2, Apache 2.4, Nginx 1.12, Nginx 1.13) 2.4.10
- (If applicable) Installation package for the LAMP/LEMP stack is:   (e.g. WAMP, XAMPP)

### Expected behaviour
Go to home page after logging in.

### Actual behaviour
An Error Was Encountered
The action you have requested is not allowed.

### Steps to reproduce the issue
I have a client rpi that I vpn, from remote location, to the server rpi. I let the client sit idle for a few hours then I  get this error. If I "go back" I then can log in and get directed to home page and use as expected. Refreshing does not help.

**Comment by robards** [comment]
I opened a browser on the server, let it sit, and it did do the same thing.

**Comment by daN4cat** [comment]
I've got this issue a couple of times. Not sure if it's a cookies issue or else.

**Comment by robards** [comment]
pi@raspberrypi:~ $ iceweasel
1499880720122	addons.productaddons	ERROR	Request failed certificate checks: [Exception... "SSL is required and URI scheme is not https."  nsresult: "0x8000ffff (NS_ERROR_UNEXPECTED)"  location: "JS frame :: resource://gre/modules/CertUtils.jsm :: checkCert :: line 145"  data: no]
1499893795571	addons.productaddons	ERROR	Request failed certificate checks: [Exception... "SSL is required and URI scheme is not https."  nsresult: "0x8000ffff (NS_ERROR_UNEXPECTED)"  location: "JS frame :: resource://gre/modules/CertUtils.jsm :: checkCert :: line 145"  data: no]
1499949537723	addons.productaddons	ERROR	Request failed certificate checks: [Exception... "SSL is required and URI scheme is not https."  nsresult: "0x8000ffff (NS_ERROR_UNEXPECTED)"  location: "JS frame :: resource://gre/modules/CertUtils.jsm :: checkCert :: line 145"  data: no]
1499949541373	addons.update-checker	WARN	Update manifest for {972ce4c6-7e08-4474-a285-3208198ce6fd} did not contain an updates property

(process:9347): GLib-CRITICAL **: g_path_get_basename: assertion 'file_name != NULL' failed
[Parent 1448] WARNING: waitpid failed pid:9347 errno:10: file /build/firefox-esr-0uegRW/firefox-esr-45.9.0esr/ipc/chromium/src/base/process_util_posix.cc, line 267

pi@raspberrypi:~ $ chromium-browser --incognito --kiosk 172.18.13.251
bootstrap_helper: /usr/lib/chromium-browser/nacl_helper: Cannot open ELF file!  errno=2
[1:1:0712/133040.437505:ERROR:nacl_fork_delegate_linux.cc(315)] Bad NaCl helper startup ack (0 bytes)
[1425:1425:0712/133045.743476:ERROR:sandbox_linux.cc(343)] InitializeSandbox() called with multiple threads in process gpu-process. 
[1:1:0712/170316.930966:ERROR:KeyboardEventManager.cpp(424)] Not implemented reached in static bool blink::KeyboardEventManager::currentCapsLockState()
[1:1:0712/211332.029222:ERROR:KeyboardEventManager.cpp(424)] Not implemented reached in static bool blink::KeyboardEventManager::currentCapsLockState()
[1:1:0713/084510.831115:ERROR:KeyboardEventManager.cpp(424)] Not implemented reached in static bool blink::KeyboardEventManager::currentCapsLockState()
[1:1:0713/084519.035759:ERROR:KeyboardEventManager.cpp(424)] Not implemented reached in static bool blink::KeyboardEventManager::currentCapsLockState()

**Comment by daN4cat** [comment]
Above errors point to an installation/setup issue, nothing to do with OSPOS I'm afraid.

**Comment by robards** [comment]
Hmmmm, any suggestions? When you replicated it was your issue the same? I will be glad to wipe and start over.

**Comment by daN4cat** [comment]
I know that sometimes I login but get an error page. Not sure what happens. I need to test as you said leaving it for some time and debug with inspector to see if it's some cookie or else.

However above errors look different. Also you should follow the rasperry pi installation guideline in the wiki and install nginx, hph7 and mariadb so you have a better performing installation of OSPOS.

**Comment by robards** [comment]
Ok, will do. Trying to test before we install on our LAMP server in our NOC.

**Comment by daN4cat** [comment]
If you have in mind to use LAMP stack, use that and not the LEMP one I suggested.

**Comment by jekkos** [comment]
Probably csrf token expiration? Not sure if the token is time bound in any way

**Comment by daN4cat** [comment]
I get 403 as response. Try to leave the client open for some time and you logged out. You enter the login credentials and you get the error (at least with Chrome).

Request Header

> Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
> Accept-Encoding:gzip, deflate, br
> Accept-Language:en-US,en;q=0.8,it;q=0.6
> Cache-Control:max-age=0
> Connection:keep-alive
> Content-Length:98
> Content-Type:application/x-www-form-urlencoded
> Cookie: csrf_cookie_ospos_v3=888f2c29ad635d04be5658bd423bed62
> DNT:1
> Host: <...removed ...>
> Origin:null
> Upgrade-Insecure-Requests:1
> User-Agent:Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/59.0.3071.109 Chrome/59.0.3071.109 Safari/537.36


Response Header

> Connection:Keep-Alive
> Content-Security-Policy:default-src https: data: 'unsafe-inline' 'unsafe-eval'
> Content-Type:text/html; charset=UTF-8
> Date:Fri, 14 Jul 2017 07:21:42 GMT
> Keep-Alive:timeout=5, max=100
> Referrer-Policy:no-referrer, strict-origin-when-cross-origin
> Server:Apache
> Set-Cookie:csrf_cookie_ospos_v3=eb152c1572bfcf1447577e8178dc9529; expires=Fri, 14-Jul-2017 09:21:42 GMT; Max-Age=7200; path=/
> Strict-Transport-Security:max-age=31536000; includeSubdomains;
> Transfer-Encoding:chunked
> X-Content-Type-Options:nosniff
> X-Xss-Protection:1; mode=block

csrf token is passed but not sure you would need it in a login page? It's clear that it has an expiring date and time

@jekkos could you please check this issue? It probably appeared a couple of months ago.
I would say that this needs to be fixed in 3.1.0

**Comment by jekkos** [comment]
there might be a csrf token sent using POST in this case.. did you omit it perhaps from the request?
maybe the browser should clear it if there's no cookie or whatsoever, so we start with a clean sheet

**Comment by daN4cat** [comment]
You mean the form data?

> csrf_ospos_v3:17640130904255a0ea15b6b8336a4ab2
> username:<...removed...>
> password:<...removed...>
> loginButton:Go

**Comment by daN4cat** [comment]
And last part is this:

> Request URL:https://<... removed..>/login
> Request Method:POST
> Status Code:403 Forbidden
> Remote Address:<...removed...>:443
> Referrer Policy:no-referrer

**Comment by jekkos** [comment]
yes indeed, it's probably duie to the token in the form there

**Comment by jekkos** [comment]
Think I should just add a check to see if there is a session currently and if not remove the token..

**Comment by daN4cat** [comment]
Yep, I leave to you but it should be fixed. You have the info...

**Comment by jekkos** [comment]
Actually there is no csrf token in the login page.. do you get the error when logging in after being redirected because the session timed out? 
Or do you see the erorr when proceeding with an expired session before you are redirected to login? The second would make more sense to me and can be fixed easily

**Comment by jekkos** [comment]
I have pushed a change, token is only added if there is a valid value in the cookie..

**Comment by jekkos** [comment]
Can someone test / :verify

**Comment by daN4cat** [comment]
I can't test until end of the month, but the error is from login page after the session timed out. Basically from any page you are redirected to login, insert the credentials again and you get the error page.

The testing will take some time and test runs.

**Comment by jekkos** [comment]
@robards can you verify and close if OK?

**Comment by robards** [comment]
Is there a nightly build I need to download? Can I upgrade or do I do a fresh install?

**Comment by jekkos** [comment]
Yes just take the latest zip from this repository

**Comment by robards** [comment]
Sorry to be such a noob, I downloaded, extracted and moved all those extracted files to /var/www/html where all files were. Let it sit and it did the same thing. Is there a way I can verify the latest version? The login screen still shows 3.0.2

**Comment by odiea** [comment]
https://github.com/jekkos/opensourcepos Download or Clone

**Comment by robards** [comment]
Yep, That's the one I grabbed.

**Comment by odiea** [comment]
You might have to do a clean install. I just downloaded the current master and here is what I get.
![2017-07-21 06_21_29-microsoft edge](https://user-images.githubusercontent.com/10962177/28463383-55d6028e-6ddd-11e7-8535-766daf31b504.png)
![2017-07-21 06_22_01-microsoft edge](https://user-images.githubusercontent.com/10962177/28463390-5f8e6ff0-6ddd-11e7-81d4-c6f082376075.png)

**Comment by robards** [comment]
Ah, I thought something was up. I will do.

**Comment by daN4cat** [comment]
This looks to me like it's fixed, but I'll test a bit more in the next days as it takes few attempts before can be reproduced.
