### ISSUE TITLE
a lot of errors on first installation

### ISSUE THREAD

**Issue by rmbaba** [jekkos/opensourcepos#1394]
Hello,

I'm using the OSPOS for first time, I'm trying to install it since more than 3 days on local server, it was only giving blank page, after moving to linux webserver I noticed a lot of problems in the error_log which is attached below (Truncated not all the log)

[13-Jul-2017 08:36:11 UTC] PHP Fatal error:  session_start(): Failed to initialize storage module: user (path: sessions) in /var/html/vendor/codeigniter/framework/system/libraries/Session/Session.php on line 143
[13-Jul-2017 08:42:15 UTC] PHP Fatal error:  session_start(): Failed to initialize storage module: user (path: /tmp) in /var/html/vendor/codeigniter/framework/system/libraries/Session/Session.php on line 143
[13-Jul-2017 08:43:18 UTC] PHP Fatal error:  session_start(): Failed to initialize storage module: user (path: /var/html/application/sessions) in /var/html/vendor/codeigniter/framework/system/libraries/Session/Session.php on line 143
[13-Jul-2017 09:25:10 UTC] PHP Fatal error:  Call to a member function result() on boolean in /var/html/application/hooks/load_config.php on line 7
[13-Jul-2017 05:30:46 America/New_York] PHP Fatal error:  Call to a member function real_escape_string() on boolean in /var/html/vendor/codeigniter/framework/system/database/drivers/mysqli/mysqli_driver.php on line 391
[13-Jul-2017 05:38:40 America/New_York] PHP Fatal error:  Call to a member function num_rows() on boolean in /var/html/application/models/Employee.php on line 308
[13-Jul-2017 06:06:08 America/New_York] PHP Fatal error:  Call to a member function row() on boolean in /var/html/application/models/Employee.php on line 311

I tried to fix each file but it was hard to me to handle all errors.

Please note that I worked arround with the sessions problem by modifying the
$config['sess_driver'] to files instead of database &
$config['sess_save_path'] to sys_get_temp_dir() instead of 'sessions' 

Regards

**Comment by daN4cat** [comment]
Have you got a wrong permission set somewhere?

Anyway read open and closed issues, FAQ, read me and wiki.

**Comment by rmbaba** [comment]
Does the system support he PHP 7? as my environment has?

Do you have an online demo for the POS application ?

Regards

**Comment by daN4cat** [comment]
Yes even PHP 7.1. If you read the readme you would have got it.

Demo? Click on the installation button to Ocean cloud and you get all installed for you and working. You'll find it in the readme page in github.

**Comment by rmbaba** [comment]
I followed only this https://github.com/jekkos/opensourcepos/blob/master/README.md#local-install

I don't have others & don't like

**Comment by daN4cat** [comment]
I meant this: https://github.com/jekkos/opensourcepos/blob/master/README.md#cloud-install-using-docker

**Comment by rmbaba** [comment]
Regardless if it's working as well or not via the cloud instructions, How about the manual & local installation?

**Comment by odiea** [comment]
Have you tries using Xampp for a local install?

**Comment by daN4cat** [comment]
That was for the demo request.... by the way this is an open source application so what's available it's available. We are not a commercial software house.

**Comment by rmbaba** [comment]
ODIA: I'm using XAMPP for the installation and after debugging I got the log in the first post.

DAN4CAT: For sure you are not in commercial software, but I've reported in case you are interested to assist me with the installation.

Respectfully,

**Comment by odiea** [comment]
Did you read the wiki about installing xampp?

**Comment by rmbaba** [comment]
I checked the following links

https://github.com/jekkos/opensourcepos/blob/master/README.md#local-install
https://github.com/jekkos/opensourcepos/wiki/OSPOS-using-Xampp-(recommended-for-testing-or-local-use-only).

**Comment by odiea** [comment]
And all the necessary php extensions including sessions are enabled. I have not updated it recently so you may have to read other installation instructions for needed extensions. I think mcrypt  also needs to be enabled. Lots of changes in the last few months.

**Comment by SteveIreland** [comment]
What database did you install and did you create the database and load the tables?  OSPOS is not a "self installing" app.  #1042

**Comment by odiea** [comment]
You extract the program. Place it in htdocs. Go to phpmyadmin create a database. Import database.sql. The edit in config database.php to match what u just installed. You should be ready to go then.

**Comment by rmbaba** [comment]
PS: I tried also to install it under cPanel with the same result.

I'm using the MariaDB & imported via phpmyadmin, there is no issue with the DB as I'm able to browse the tables and select query

**Comment by odiea** [comment]
Did you install the db using database.sql and Not tables.sql?

**Comment by daN4cat** [comment]
@rmbaba which version of MariaDB are you using?

**Comment by rmbaba** [comment]
Here is the version

**Comment by daN4cat** [comment]
And are you using OSPOS 3.1 or 3.0.2?

**Comment by daN4cat** [comment]
Also please check if you public dir has any error.log file. If yes, what's written inside?

**Comment by rmbaba** [comment]
How do I know which version I'm using?

**Comment by odiea** [comment]
@daN4cat This has been the version I have been using. And until this last major update it has given me no issues.
Server: 127.0.0.1 via TCP/IP
Server type: MariaDB
Server version: 10.1.13-MariaDB - mariadb.org binary distribution
Protocol version: 10
User: root@localhost
Server charset: UTF-8 Unicode (utf8)
Web server

Apache/2.4.18 (Win32) OpenSSL/1.0.2e PHP/7.0.8
Database client version: libmysql - mysqlnd 5.0.12-dev - 20150407 - $Id: 241ae00989d1995ffcbbf63d579943635faf9972 $
PHP extension: mysqli Documentation
PHP version: 7.0.8
