### ISSUE TITLE
Tax category error in sale register

### ISSUE THREAD

**Issue by daN4cat** [jekkos/opensourcepos#1396]
@SteveIreland 

now that there is proper support for adding and removing of tax categories, some errors are coming to the surface.
Add a tax category, then if you remove later you get errors in different places like sale register, customer tax editing and etc.

I'm not sure the way it's managed at the moment to remove completely from the database is correct.
If I look at rewards, stock location, tables they use a deleted field to avoid breaking references.

Please check that scenario and fix the errors.

**Comment by jekkos** [comment]
I also found that code isn't foreseen to handle no tax categories at all. Think either we should make it more robust to deal with that or either prevent the user to delete all categories.
For the latter we need to think if this makes sense in a functional way or not. If it does then I'd opt for the first

**Comment by daN4cat** [comment]
Agreed

**Comment by SteveIreland** [comment]
My preferred choice would be to insure that the user is unable to delete a tax category that has an active reference.  I'm not a big fan of the soft delete logic because it introduces the potential for stale data that never goes away or that requires another layer of maintenance to keep clean. (Although admittedly I have written more than my fair share of soft delete logic).

Since deleting a tax category in the real world doesn't make any sense (except for QA purposes) and should therefore be a rare event I don't think it's a change that needs to be added to 3.1 but I don't have a preference myself.  I can add it if you feel it's needed.

Since I hadn't envisioned anyone removing all of the tax categories the idea of preventing the removal of the "Standard" tax category (which I think has a key of zero) makes a good deal of sense to me.

For sales tax, at a minimum, the standard sales tax needs to exist.

**Comment by daN4cat** [comment]
The issue is if you add a 3rd tax category and then remove it you get the errors. That's what happened to me because I tested the add and remove so I created dummy categories. However when I start deleting I've got errors in different places.

**Comment by SteveIreland** [comment]
Okay, I'll explore this scenario tonight.   Thanks.

**Comment by daN4cat** [comment]
@SteveIreland sorry to be a pain but please let's fix this issue over the week end so we release 3.1.0 at the end of the month.

**Comment by SteveIreland** [comment]
Okay.

**Comment by daN4cat** [comment]
@odiea do you mind to test master and confirm?

**Comment by daN4cat** [comment]
Thanks both for the help

**Comment by odiea** [comment]
Was common_unknown left out of the language file. See rounding code.
![2017-07-15 16_38_40-wedidit _ powered by ospos 3 1 0](https://user-images.githubusercontent.com/10962177/28243113-7125e046-697c-11e7-97ae-dd680edf0c6a.png)

**Comment by SteveIreland** [comment]
Good catch.   I'll submit a pull request for that immediately.

**Comment by odiea** [comment]
Just making sure I am testing this correctly.
I had to enable customer Support.
The following table Tax category have a number to the right. What is suppose to be inputed there?
![2017-07-15 17_10_05-wedidit _ powered by ospos 3 1 0](https://user-images.githubusercontent.com/10962177/28243261-c04c07f0-6980-11e7-9e0d-e4ae9fac4d5a.png)

**Comment by SteveIreland** [comment]
That is a number that is optionally used to control the sequence of taxes listed on the invoice.  It is written to the `sales_taxes` table.

**Comment by odiea** [comment]
When I try to add a new Tax Category and press Submit nothing happens. But you can see a new out of sequence Category number shows after I exit then try to add a new Tax Category.
![2017-07-15 17_34_07-wedidit _ powered by ospos 3 1 0](https://user-images.githubusercontent.com/10962177/28243366-14f98086-6984-11e7-8a30-31ecebd368c2.png)

**Comment by SteveIreland** [comment]
I can temporarily recreate the missing "Tax Category 4" if I delete a category, but when the page is reloaded they are resequenced.

**Comment by SteveIreland** [comment]
Did you apply the auto_increment database change to the tax_categories table?

**Comment by odiea** [comment]
SQL query:

This is the error I get when doing the following.

ALTER TABLE `ospos_tax_categories`
  MODIFY COLUMN `tax_category_id` int(10) NOT NULL AUTO_INCREMENT
MySQL said: Documentation

#1062 - ALTER TABLE causes auto_increment resequencing, resulting in duplicate entry '1' for key 'PRIMARY'

BTW here is what the current update db is showing.

ALTER TABLE `ospos_tax_categories`
  MODIFY COLUMN `tax_category_id` int(10) NOT NULL AUTO_INCREMENT;
  
-- long alternate description
  
ALTER TABLE `ospos_sales_items`
  MODIFY COLUMN `description` varchar(255) DEFAULT NULL;
  
-- fix tax category maintenance
  
ALTER TABLE `ospos_tax_categories`
  MODIFY COLUMN `tax_category_id` int(10) NOT NULL AUTO_INCREMENT;

**Comment by odiea** [comment]
This is what I got after dropping the table then re-entering the table then adding the data
Error
SQL query:


INSERT INTO `ospos_tax_categories` ( `tax_category_id`,`tax_category`, `tax_group_sequence` ) VALUES
  (0, 'Standard', 10),
  (1, 'Service', 12),
  (2, 'Alcohol', 11)
MySQL said: Documentation

#1062 - Duplicate entry '1' for key 'PRIMARY'

**Comment by odiea** [comment]
For some reason I had to close phpmyadmin then open it and it then allowed me to enter the above data. Yes it is now accepting new tax categories. I will play with it more tomorrow.

**Comment by SteveIreland** [comment]
I'm glad you figured it out.  I was scratching my head on on that last one trying to understand how that was even possible.

I added a fix to the upgrade script to the last pull request to remove the duplicate ALTER TABLE statement.

**Comment by SteveIreland** [comment]
I was still uncomfortable with the issue that you reported and did a bit more research and I believe I understand the problem now.

When I added the tax_category_id to the `item` table the field (by default) was preloaded with zero and I was going to adopt that as "Standard" tax.  Logically that makes perfect sense to me (and I wasn't using AUTO_INCREMENT at that time).  However, AUTO_INCREMENT apparently doesn't like zero as a key.  So when the first record was added AUTO_INCREMENT behavior saw the zero and assumed it needed to add a key and AUTO_INCREMENT starts with 1.  Then the second record tried to add the next record with a key of 1 and thus the duplicate key.

It's a pain, but to fix this the right way I need to change 1 to be the Standard tax.  1 will need to be the "Standard" tax category.

**Comment by odiea** [comment]
Glad I could help. Keep up the good work.

**Comment by daN4cat** [comment]
It's always tricky when you start with a couple of use cases in mind and then you discover others you didn't cover breaking the toy.... some refactoring time.

**Comment by odiea** [comment]
Just checking to see if I missed something. I did the following db changes.

DELETE FROM `ospos_tax_categories` where tax_category_id in (0, 1, 2, 3);

INSERT INTO `ospos_tax_categories` ( `tax_category_id`,`tax_category`, `tax_group_sequence` ) VALUES
  (1, 'Standard', 10),
  (2, 'Service', 12),
  (3, 'Alcohol', 11);

ALTER TABLE `ospos_items`
  MODIFY COLUMN `tax_category_id` int(10) NOT NULL DEFAULT 1;

UPDATE `ospos_items` SET `tax_category_id` = 1 WHERE `tax_category_id` = 0;
Here is the result when updating a Tax.
![2017-07-16 05_19_11-wedidit _ powered by ospos 3 1 0](https://user-images.githubusercontent.com/10962177/28247082-d970f518-69e6-11e7-92ef-5ca1558d8ab5.png)

**Comment by daN4cat** [comment]
That's the error I was talking about without touching the db just adding and removing categories during my testing.

**Comment by odiea** [comment]
This is also preventing Taxes to be applied to a Sale.

**Comment by SteveIreland** [comment]
I did say that this was going to be a pain.  Sorry ... working on the additional changes this requires now.  Will be publishing soon.

**Comment by odiea** [comment]
Scenario.
I just updated to the Customer Sales Tax.
I have not had the time to Update all the Customers with the new Tax Code.
Is there now a way to then default to the Item Tax or The Default Origin Tax?

**Comment by odiea** [comment]
The Php errors are gone and the default tax code is being used on the customer.

**Comment by SteveIreland** [comment]
Good.  Are you experiencing the same tax code maintenance problem I am - Instead of the green pop-up box it goes to another page to display the message?

**Comment by odiea** [comment]
No that is not showing up. But it now does not update the Tax code to the former tax code. It also appears the tax math is way off. I tried the different rounding options but that didn't change anything probably because I have the same decimal set on  both cash and tax. I sent pic on your pull request.

**Comment by odiea** [comment]
After deleting the new Tax it now reverts back to the old tax but It now uses the liquor tax which I cannot delete From the edit screen. I have tried 3 times to remove it.
![2017-07-16 08_44_47-wedidit _ powered by ospos 3 1 0](https://user-images.githubusercontent.com/10962177/28248533-4670873e-6a03-11e7-9665-e0dd11fdbaf6.png)

**Comment by jekkos** [comment]
Last time I checked I  also found that there were no foreign key constraints between items and tax categories. Might be good to add them for consistency.. 

Also for the delete
- when removing something e that's not 'active', we might consider to use cascading deletes on the database. It will then clean up all entities linked to the category and resolve the problem of having missing references.
- or we disable delete if there are references active (as discussed), but in that case code should be written to check whether it is still ijn use. At first sight this seems harder and a warning with the former approach could be more user friendly if one decides to get rid of the category and everything linked to it as a whole

**Comment by jekkos** [comment]
Actually I'd prefer to  configure the delete behavior on database level. One can easily add an update constraint on items table so that foreign key to the removed category is nulled out on delete.
All tax related entities should then just be removed together with it. Think this will be the easiest and cleanest solution as you guarantee consistent behavior even if you run a delete query on the database directly

**Comment by SteveIreland** [comment]
Do you want these changes in 3.1 or just include them in the Tax changes for 3.2?

I think the latest iteration of the pull request should be close to being finished ... but I can keep working on it.  I'll just need to find time for it and I think I'm going to be  pretty busy this next weekend, but might have time to work on it the following weekend - but then there will probably be another week or two following those changes for the test cycle to complete.

**Comment by jekkos** [comment]
Maybe I'm not sure if this will impact application logic but it could of course, if all is functionally good then maybe we postpone until after the release, unless I find some time to refactor
