### ISSUE TITLE
Receiving Quantity, Reorder level default 1

### ISSUE THREAD

**Issue by bill-goldberg** [jekkos/opensourcepos#1399]
I want to set receiving quantity, reorder level = 1 as default in the new item form.
Please guide me where to look for changing this value.

**Comment by odiea** [comment]
![2017-07-17 06_33_13-update items php changed receiving_quantity to 1 by odiea pull request 1376](https://user-images.githubusercontent.com/10962177/28268036-e733e312-6ab9-11e7-8505-ac9bb265638e.png)

**Comment by daN4cat** [comment]
Exactly, isn't this in master already?

**Comment by odiea** [comment]
Yes it is. That was from my pull request.

**Comment by dvidic** [comment]
Am I missing something. When I receive items via Receivings and enter receiving quantity, item have 0 on stock. On Item info theres a number under receiving quantity, but under stock I get 0.

**Comment by odiea** [comment]
Receiving Quantity under Items is used for multiple items. You purchase a 6 pack of something and want to sell individual items. So the Receiving quantity would be 6 and your cost would be the cost of the six pack divided by 6. When you update the inventory in Receivings you would just enter 1 as the received then it multiplies the qty received by 6.

**Comment by odiea** [comment]
Receiving quantity must be left at 1 or higher. 0*1=0. That is probably why the stock is not updating.
