### ISSUE TITLE
Add unit feature 

### ISSUE THREAD

**Issue by salikur** [jekkos/opensourcepos#140]
Can add unit feature in item? Like Kg (kilograms),pcs,bottle etc. User can set unit name for item. Thanks

**Comment by jekkos** [comment]
Yes there's a private branch that will allow you to do that.

**Comment by asadjaved63** [comment]
It's paid version? Which allows us do that?

**Comment by jekkos** [comment]
Currently unreleased, will need some polishing probably for a fee in return. It has integration with serial for using scale devices. I could setup a demo for you so you can see the added features.

**Comment by daN4cat** [comment]
This is probably a duplicate of #68 or at least they cover the same.

**Comment by daN4cat** [comment]
Close to keep just #68 open as this is just a use case.
