### ISSUE TITLE
Receipt Fonts and Blurry

### ISSUE THREAD

**Issue by sanubari97** [jekkos/opensourcepos#1401]
How can I change the font size. Well i read in issue 613 about adding some line in the receipt.php, but i dont know how exactly. Im really poor with the coding. Please someone tell me what should i type and in which line ?
![tmpdoodle1500371702521](https://user-images.githubusercontent.com/30258590/28311430-3b63ebd4-6be2-11e7-974f-660b26786b30.jpg)

And the text not so readable..

**Comment by daN4cat** [comment]
Have you tried adjusting the margins in your printer driver? It looks to me like the left margin is to wide and makes the printing smaller.

**Comment by sanubari97** [comment]
where should I change it ? I tried in the receipt.css but no result. I tried in the option printer and set it to minimum, it looks better now but the fonts is still like not clearly written.
and I tried the custom margin in the option but I confuse how to use it, bette is minimum but if the receipt.css could work, that will be much better.

**Comment by daN4cat** [comment]
You need to sort it out at printer configuration level in Opera.
Set scale 100 and set margin minimum order none as starting point. Also the fact that you don't have paper size is unusual.
Try to play with that part before touching OSPOS css

**Comment by sanubari97** [comment]
I think the browser print set up is okay. I use another POS to test it and it prints fine .
![photo_20170719_115728](https://user-images.githubusercontent.com/30258590/28360699-d3bc4018-6ca8-11e7-8b6c-e2784833ff04.jpg)

**Comment by ravindug** [comment]
Use Firefox and install jsPrint add on as said in wiki, and install your printer (mine cheap Chinese thermal printer with ECS support) as RAW printer. Thenyou can fix this issue..

**Comment by sanubari97** [comment]
mehh, firefox is slow. And when I click print, nothing happened

**Comment by ravindug** [comment]
install  [jsPrint Firefox Add On](https://addons.mozilla.org/en-US/firefox/addon/js-print-setupl), Firefox is very fast for me works fine..

**Comment by jekkos** [comment]
Not really an ospos issue but rather related to printer / print configuration setup..

**Comment by daN4cat** [comment]
Configuration for receipt font size added and in master.
