### ISSUE TITLE
"docker-compose up" fails on database migration stage (local installation)

### ISSUE THREAD

**Issue by igorokb** [jekkos/opensourcepos#1405]
### Issue / Question / Bug

Before submitting an issue please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] I'm reporting an issue of an unmodified OSPOS installation
- [x] I checked open and closed issues database and no similar issue was already discussed (please make sure you searched!)
- [x] I read the README, WHATS_NEW and UPGRADE
- [x] I read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php-gd, php-intl, sockets and etc. installed)
- [ ] I read the wiki
- [ ] I ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql), and migrating function
- [ ] I'm aware the latest master could be a development version and therefore not stable
- [x] I know the version of OSPOS and git commit hash (check the footer of your OSPOS), the name and version of OS, Web server, PHP and MySQL and will add them to my issue report

### Installation information

- OSPOS version is: **3.1.0**
- OSPOS git commit hash is: **5d49728c74ae8794bdcbc640b88783e7d02b6c77**
- PHP version is:  **7.0.15**
- MySQL or MariaDB version is:   **MariaDB 10.1.21**
- OS and version is:   **Ubuntu**
- WebServer is:  **Apache/2.4.10 (Debian)**
- Docker is: **17.05.0-ce, build 89658be**
- docker-compose: **1.7.0, build 0d7bf73**

docker-compose installation was performed

### Expected behaviour

execution of the line `docker-compose up` successfully ups corresponding docker containers and the OSPOS website is accessible by URL http://localhost/

### Actual behaviour

The host http://localhost/ responds with HTTP 500 due to termination of the mysql docker container.
docker-compose log ends up with the following:

> mysql_1      | /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/database.sql
> mysql_1      | ERROR 1062 (23000) at line 823: Duplicate entry '1' for key 'PRIMARY'
> opensourcepos_mysql_1 exited with code 1

### Steps to reproduce the issue

1. clone the repo
2. run `docker-compose build` and wait for complete building
3. run `docker-compose up` and watch for the log

**Comment by igorokb** [comment]
I am new in OSPOS, so the quick fix worked for me as a temporary solution:
replaced INSERT INTO with INSERT **IGNORE** INTO everywhere where the `ospos_tax_categories` table is been inserted

**Comment by jekkos** [comment]
I wonder whether executing clean database.sql against a newly created schema works then.. @odiea any idea?

**Comment by odiea** [comment]
No idea.

**Comment by daN4cat** [comment]
@jekkos is this a bug or no?

**Comment by jekkos** [comment]
Tried yesterday and can't reproduce. @igorokb does this still occur or not?

**Comment by igorokb** [comment]
@jekkos hi. Haven't tried it since last time. It was just a project of one of our clients where installation was not one of the tasks. Hopefully I provided you with all details you requested including commit hash and steps to reproduce. Cheers
