### ISSUE TITLE
Bootswatch Themes How to add them in OSPOS

### ISSUE THREAD

**Issue by bill-goldberg** [jekkos/opensourcepos#1408]
There are 2 new themes available at bootswatch site...  Please help me about how to add those themes to OSPOS.

**Comment by bill-goldberg** [comment]
2 New themes are Lumen & Simplex

**Comment by jekkos** [comment]
Should be a matter of updating the bower file? Think it went through an alternative repository that needs to update first, I'll have a look if that's feasible.

**Comment by daN4cat** [comment]
No alternative repo it's direct and probably just a matter of adding the paths in the scripting

**Comment by jekkos** [comment]
Right I checked this morning there should be a more generic way to copy these themes ( one that requires less maintenance)

**Comment by jekkos** [comment]
Ok done, can you check if they are available in latest master?
