### ISSUE TITLE
Cannot Add new customers and taxes

### ISSUE THREAD

**Issue by mac10046** [jekkos/opensourcepos#1409]
![image](https://user-images.githubusercontent.com/4290573/28492163-5f795d6a-6f1b-11e7-9baf-4a87e06d149b.png)

![image](https://user-images.githubusercontent.com/4290573/28492159-40a89b62-6f1b-11e7-8ad2-ec6adac49553.png)

**Comment by mac10046** [comment]
solved it ... by correcting the database.sql

I removed the id column from the insert statement and then when to database to change the id as per the insert statement

INSERT INTO `ospos_tax_categories` ( `tax_category`, `tax_group_sequence` ) VALUES
  ('Standard', 10),
  ('Service', 12),
  ('Alcohol', 11);


a error occurs when you execute the database.sql - first I ignored it
this happened because a AUTO_INCREMENT is given on the table and still the insert statement had specified id's starting from 0

**Comment by daN4cat** [comment]
@SteveIreland is this solved with your fix?

**Comment by SteveIreland** [comment]
Yes, the starting key is now 1.

**Comment by odiea** [comment]
I only get this issue with an upgrade and not a clean install. I have tried it twice with the current master.

**Comment by SteveIreland** [comment]
An upgrade from what version?  3.02 or from some random point in the 3.1.0 upgrade stream?   :smile:

**Comment by odiea** [comment]
On my upgrade it was a current database. I reported the issue about the time you introduced the auto incrementing. I had to delete that table then re add it to get the new numbering to work. I just can't seem to find that pull request or maybe it was reported in some issue.

**Comment by SteveIreland** [comment]
The change that starts the tax categories at sequence 1 is in the pull request that's been sitting there for a few days.

**Comment by Waleed616** [comment]
New Items still unable to add. What about this ?
![add item issue](https://user-images.githubusercontent.com/14108786/28498898-4d8e1814-6fc2-11e7-8363-76e2bda10303.JPG)
