### ISSUE TITLE
How to run OSPOS as SaaS platform?

### ISSUE THREAD

**Issue by ishtiaquesarwar** [jekkos/opensourcepos#1411]
Hi
In project description it was described that ospos is a SaaS type project, but i have not found any way to turn it into a SaaS based solution over cloud. Any way out, would appreciate your kind guidance

Regards
ishtiaque

**Comment by daN4cat** [comment]
Click the button deploy on DigitalOcean and you get the cloud based installation.

**Comment by ishtiaquesarwar** [comment]
My plan is not to share the source code with any business but sell the
service on monthly subscription fee. Digital ocean is just a host platform.

Every business will get an username and password for transaction, stock
from a same domain where their database and other information will be kept
separate but operation from one single installation.

How to do that? Does that require additional code work?

Thanks

**Comment by jekkos** [comment]
Cloud based installation is currently not foreseen to run multiple stores through one database. For that you'd need some kind of schema selector on the frontend that then dynamically selects which database to point to.. I would be happy to accept some contribution from you to our main project here as most of the work done around the SaaS story will enable you to make money out of it easily.

**Comment by ishtiaquesarwar** [comment]
How much contribution you are expecting could you please share?

**Comment by jekkos** [comment]
Well if you chose to implement something like this then it would be nice to have that source code change in return.. I had somebody not so long ago presenting me this type of solution but he never sent a PR to enable  it.

**Comment by ishtiaquesarwar** [comment]
Ok I'll be happy to know the budget you require so that I can plan
accordingly

**Comment by daN4cat** [comment]
So you want a multitenancy story.

**Comment by ishtiaquesarwar** [comment]
Yes brother i want a multitenancy system. If possible if a customer signs
online he can enjoy a free trial for few days then paid subscription will
start and there has to be an option to integrate with any other billing
system external so that billing upon not receiving payment can suspend. let
me know if this can be covered ?


Regards,

<http://www.softbd.com>

A.M.Ishtiaque Sarwar / Managing Director
8801711-272324 / ceo@softbd.com

Soft Tech Innovation Ltd. *Office*: 880-1611-272324
Sector:14, Road:15, House:92, Uttara, Dhaka. 1230
http://www.softbd.com
*Consultant:*
Azadi Technologies, Chittagong.

*Skype*: softbd | *GTalk*: ishtiaque.sarwar | *Linked In*: ishtiaquesarwar
<https://bd.linkedin.com/in/ishtiaquesarwar>

*Business Concerns*: *MUTHOFUN <http://www.muthofun.com/> |  aamarPay
<https://www.aamarpay.com/> | Soft Tech Innovation Limited
<http://www.softbd.com>*

[image: Facebook] <http://www.facebook.com/ishtiaque.sarwar> [image:
Twitter] <http://www.twitter.com/ishtiaquesarwar> [image: Google Plus]
<https://plus.google.com/116320436752203524696> [image: Linkedin]
<https://bd.linkedin.com/in/ishtiaquesarwar> [image: Skype]
<http://htmlsig.com/softbd>

This e-mail message may contain confidential or legally privileged
information and is intended only for the use of the intended recipient(s).
Any unauthorized disclosure, dissemination, distribution, copying or the
taking of any action in reliance on the information herein is prohibited.
E-mails are not secure and cannot be guaranteed to be error free as they
can be intercepted, amended, or contain viruses. Anyone who communicates
with us by e-mail is deemed to have accepted these risks. Company Name is
not responsible for errors or omissions in this message and denies any
responsibility for any damage arising from the use of e-mail. Any opinion
and other statement contained in this message and any attachment are solely
those of the author and do not necessarily represent those of the company.

**Comment by daN4cat** [comment]
At the moment we are limited in time, so not sure this will be picked up any time soon.
But if you find somebody helping you with this it would be nice to get the contribution back.
