### ISSUE TITLE
Right side currency symbol is missing.

### ISSUE THREAD

**Issue by sarulyos** [jekkos/opensourcepos#1413]
Right side currency symbol is missing.

Store Config -> Localisation

ver 2.3.4 vs 3.1

![capture2](https://user-images.githubusercontent.com/30383907/28498540-07ffb782-6fca-11e7-8894-7cfb7a3cace1.PNG)
![capture1](https://user-images.githubusercontent.com/30383907/28498541-0ac963e6-6fca-11e7-938b-63ab82753503.PNG)

**Comment by odiea** [comment]
Yes. That went away when the locale helper was implemented.

**Comment by jekkos** [comment]
Just configure your locale that has currency sign on right side, should work well like that

**Comment by daN4cat** [comment]
Sometimes making things more automagic puzzles people :-)
