### ISSUE TITLE
Receiving Page is unable to load. it is throwing following error

### ISSUE THREAD

**Issue by Waleed616** [jekkos/opensourcepos#1414]
Receiving Page is unable to load. it is throwing following error.
![receiving issue](https://user-images.githubusercontent.com/14108786/28498915-b439c0b8-6fc2-11e7-9273-c4cd2dbba4df.JPG)

**Comment by odiea** [comment]
I see you read nothing in the faqs.
If the following error is seen in sales module Message: Class 'NumberFormatter' not found then you don't have php5-intl extension installed. Please check the wiki to resolve this issue on your platform. If you use WAMP, please read issue #949
