### ISSUE TITLE
Wrong Payments Summary Report

### ISSUE THREAD

**Issue by sarulyos** [jekkos/opensourcepos#1415]
Problems encountered when selling item kit, count and amount tendered will double.
![capture](https://user-images.githubusercontent.com/30383907/28501204-3dd75acc-7001-11e7-9a89-53ec3cbe8eeb.PNG)

**Comment by odiea** [comment]
models/reports/summary_payments.php
In payment summary report it appears to be using the item count and not the payment count. After commenting out the bottom line the report look good.
public function getData(array $inputs)
	{
		$this->db->select('sales_payments.payment_type, COUNT(*) AS count, SUM(sales_payments.payment_amount) AS payment_amount');
		$this->db->from('sales_payments AS sales_payments');
		$this->db->join('sales AS sales', 'sales.sale_id = sales_payments.sale_id');
		//$this->db->join('sales_items AS sales_items', 'sales_items.sale_id = sales_payments.sale_id');

**Comment by sarulyos** [comment]
@odiea How to change the font size POS receipt? (very small on paper size A4)
![capture](https://user-images.githubusercontent.com/30383907/28501682-1754b5c0-700b-11e7-8168-67085f364e3f.PNG)

**Comment by odiea** [comment]
I can't really help you on that one other than reading the open and closed issues.

**Comment by sarulyos** [comment]
Thanks

**Comment by daN4cat** [comment]
Fixed the double counting
