### ISSUE TITLE
How to change the font size POS receipt? (very small on paper size A4)

### ISSUE THREAD

**Issue by sarulyos** [jekkos/opensourcepos#1416]
How to change the font size POS receipt? (very small on paper size A4)
![capture](https://user-images.githubusercontent.com/30383907/28501725-2452c432-700c-11e7-8515-5a07bb8e6149.PNG)

**Comment by odiea** [comment]
In views/sales/receipt_default replace the first line with <div id="receipt_wrapper"; style="font-size:110%"> and see if that helps. Adjust "font-size:110%" as necessary.

**Comment by sarulyos** [comment]
Thanks

**Comment by daN4cat** [comment]
It looks like we need to add a configuration for this for the size.

**Comment by odiea** [comment]
I have been working on that as an adjustable config receipt item. My issue again would be in submitting the database change properly. 
I have it using receipt.php with the following code so both receipts were taken care of.
```
<div id="receipt_wrapper" style="font-size:<?php echo $this->config->item('receipt_font_size');?>px";>
<?php $this->load->view("sales/" . $this->config->item('receipt_template')); ?>
</div>
```
If you don't think this is the proper way let me know.

**Comment by SteveIreland** [comment]
Wouldn't you want a separate set of properties for each document type (Ticket, Invoice, and Takings)?

**Comment by odiea** [comment]
It looks to me like most of the issues are around setting up receipt printers. That's why I just chose to do this.

**Comment by SteveIreland** [comment]
Makes sense to me.

**Comment by daN4cat** [comment]
Configuration for receipt font size added.
