### ISSUE TITLE
Why not show list when double-click on Find/Scan Item OR Receipt and Select Customer (Optional)?

### ISSUE THREAD

**Issue by sarulyos** [jekkos/opensourcepos#1417]
![untitled](https://user-images.githubusercontent.com/30383907/28501790-87ac73c4-700d-11e7-97a6-1f863aedff50.png)

**Comment by odiea** [comment]
That no longer works. You have to input the first letter in the item or customer field names now.

**Comment by sarulyos** [comment]
Thanks
