### ISSUE TITLE
Change of french language leads to unavailable app

### ISSUE THREAD

**Issue by dom-madrid** [jekkos/opensourcepos#1418]
- [X] I'm reporting an issue of an unmodified OSPOS installation
- [X] I checked open and closed issues database and no similar issue was already discussed (please make sure you searched!)
- [X] I read the README, WHATS_NEW and UPGRADE
- [X] I read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php-gd, php-intl, sockets and etc. installed)
- [X] I read the wiki
- [X] I ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql), and migrating function
- [X] I'm aware the latest master could be a development version and therefore not stable
- [X] I know the version of OSPOS and git commit hash (check the footer of your OSPOS), the name and version of OS, Web server, PHP and MySQL and will add them to my issue report

### Previous Report - Similar

It looks like error 1344, except it is not a docker install, and was supposedly fixed, which is not the case. Applying manually the content of https://github.com/jekkos/opensourcepos/commit/ff7848dcff03859d6d440ff06069d96554ce2260 fixes the problem.

### Installation information

- OSPOS version is: 3.1.0
- OSPOS git commit hash is: 5d49728c74ae8794bdcbc640b88783e7d02b6c77
- PHP version is: 7.0
- MySQL or MariaDB version is: MySQL 5.7
- OS and version is: Ubuntu 16.04
- WebServer is: Apache 2.4
- (If applicable) Installation package for the LAMP/LEMP stack is:   (e.g. WAMP, XAMPP)

### Expected behaviour

Change language to french in the Store Config, Submit the change, Get the interface in french

### Actual behaviour

Interface crash, application does not change language in real time as it does in the other language (spanish was tested successfully), after logout the application crashes completely.
Solving the problem goes through editing the entries in the database to restore to a working language.

### Steps to reproduce the issue

Change language to french in the Store Config, Submit the change, Try to Get the interface in french
and Crash

**Comment by odiea** [comment]
Here is the error associated with this issue.
![2017-07-23 13_43_49-mozilla firefox](https://user-images.githubusercontent.com/10962177/28502336-4021c028-6fad-11e7-87a2-a28941fa75b1.png)

**Comment by odiea** [comment]
This needs translation updates. Lots of missing names. I changed the following lines and got it to work without crashing. It would be great if you could translate it then submit a pull request.
application/language/fr/config_lang.php.
line 134 $lang["config_jsprintsetup_required"] = "Attention! Cette fonctionnalité ne fonctionnera que si vous avez le plugin FireFox jsPrintSetup installé. Sauvegarder quand même?";
line 44 $lang["config_country_codes_tooltip"] = "Liste des codes de pays séparés par virgules pour la recherche d'adresse";

**Comment by jekkos** [comment]
@dom-madrid you can fix this by updating weblate translations, check wiki for instructions and submit changes so I will integrate them

**Comment by daN4cat** [comment]
Fixed french translation mistakes
