### ISSUE TITLE
Enhancement - Customer Email in Sales Select Customer

### ISSUE THREAD

**Issue by waynebr76** [jekkos/opensourcepos#1419]
When processing a sale and selecting customer it would be a good idea to have the email address appear next to the search results. We have a number of customer with the same first & last name. 

When we currently search we have to either make one of the names more unique by adding the middle initial or select each customer one by one until we get the one with the correct email address. 

Where we live we have quite a few common surnames so this issue happens regular.
![untitled-1](https://user-images.githubusercontent.com/8035455/28523810-d89ed642-7075-11e7-85e3-956890b2b9cc.jpg)
![untitled-2](https://user-images.githubusercontent.com/8035455/28523820-e090930e-7075-11e7-924e-4fbbec14aa44.jpg)

**Comment by odiea** [comment]
Towards the bottom of Issue #744 should give you a hint on how to do that.

**Comment by waynebr76** [comment]
Thanks it looks like the code has changed, so i'm not sure how to do this.

**Comment by odiea** [comment]
After playing with it . Here goes.
application/models/customer.php line 260 Replace it with the following.
			$suggestions[] = array('value' => $row->person_id, 'label' => $row->first_name.' '.$row->last_name.' '.'['.$row->email.']');

**Comment by waynebr76** [comment]
That's great thanks

**Comment by daN4cat** [comment]
Related to #1084 too
