### ISSUE TITLE
Store Config -> General -> Backup

### ISSUE THREAD

**Issue by bill-goldberg** [jekkos/opensourcepos#1422]
I have changed some things in backup_db function. Now its not downloading the zip file instead it is storing the zip file in a public/backup directory.

Now I want to show a message for successful db backup and the path where it is stored.

How to achieve this? Please help me

**Comment by jekkos** [comment]
the original backup button was redirecting the browser to download the zip file. So you'll need to handle an ajax call in case you click the button that then stores the zip in your directory. Echo a json message with the fixed structure and then normally it should be shown as notification. There's plenty of  examples like that  in the codebase

**Comment by bill-goldberg** [comment]
Please give me an example of such ajax call ... where should i check . I echo a json message in the db_backup function but the message is redirecting to a new page (blank page with the echo message).

**Comment by daN4cat** [comment]
Just check any of the config tab implementations and you'll find your answer.... it's not that hard to see.
