### ISSUE TITLE
Where to search for finished Receivings Receipts ?

### ISSUE THREAD

**Issue by bill-goldberg** [jekkos/opensourcepos#1423]
We can see the sales receipts/invoice under the 'takings'.
But what for receivings receipt?
where to look for completed receivings receipt ?

**Comment by odiea** [comment]
Reports Detailed Receiving

**Comment by bill-goldberg** [comment]
but that part doesn't show the actual receipt. It only shows the details of that particular receiving

**Comment by bill-goldberg** [comment]
Ok i got it... Thank you for the information.
You can close this issue now.
