### ISSUE TITLE
HTTP Error 500

### ISSUE THREAD

**Issue by irufaah** [jekkos/opensourcepos#1424]
http://localhost/pos/public/home
it shows a blank page. i am using xamp
This is the error i get
This page isn’t working
localhost is currently unable to handle this request.

**Comment by daN4cat** [comment]
Read past open and closed issues, also FAQ, read me and wiki. Thanks

**Comment by irufaah** [comment]
I don't understand. Can you explain it little briefly.

Sent from my iPhone

On 28 Jul 2017, at 21:27, FrancescoUK <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #1424<https://github.com/jekkos/opensourcepos/issues/1424>.
