### ISSUE TITLE
It would be important to develop credit sales and customer payment module.

### ISSUE THREAD

**Issue by guillermohaad** [jekkos/opensourcepos#1427]
### IMPORTANT IMPORTANT IMPORTANT

1. Chose what you want to report between the sections "New Feature / Enhacement" and "Issue / Question / Bug".
2. Remove just the one of the two sections you don't need 
3. Remove this section as it's just a guideline
4. Fill in all the details as requested by the section you chose

If you remove the complete template when submitting a Bug your issue will be closed as we cannot help without basic information.

### New Feature / Enhacement

*For New Features or Enhacements please clearly write your proposal.
It's important to state whether you expect the community to implement it or you will contribute the work.
Please bear in mind that we will implement new features only on the current code, there is no support for older versions.*

### Issue / Question / Bug

Before submitting an issue please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] I'm reporting an issue of an unmodified OSPOS installation
- [] I checked open and closed issues database and no similar issue was already discussed (please make sure you searched!)
- [] I read the README, WHATS_NEW and UPGRADE
- [] I read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php-gd, php-intl, sockets and etc. installed)
- [] I read the wiki
- [] I ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql), and migrating function
- [] I'm aware the latest master could be a development version and therefore not stable
- [] I know the version of OSPOS and git commit hash (check the footer of your OSPOS), the name and version of OS, Web server, PHP and MySQL and will add them to my issue report

### Installation information

- OSPOS version is:
- OSPOS git commit hash is: 
- PHP version is:   (e.g. 5.5, 5.6, 7.0, 7.1)
- MySQL or MariaDB version is:   (e.g. MySQL 5.5, MySQL 5.6, MySQL 5.7, MariaDB 10.0, MariaDB 10.1, MariaDB 10.2)
- OS and version is:   (e.g. CentOS 6.9, Ubuntu 16.4, Windows 10)
- WebServer is:   (e.g. Apache 2.2, Apache 2.4, Nginx 1.12, Nginx 1.13)
- (If applicable) Installation package for the LAMP/LEMP stack is:   (e.g. WAMP, XAMPP)

**Comment by guillermohaad** [comment]
Hi friends, 
I am new to OSPOS and I like how it looks and I congratulate everyone for putting a grain of sand in this beautiful project.
We should create a module of payment module where we record the payments of customers that are sold to them by credit.
Has anyone developed this module? I can help?

Attached as may be:

![payment ospos grid 2](https://user-images.githubusercontent.com/12921805/28719679-68022364-7370-11e7-812a-e3663f4d1929.png)
![payment ospos module 1](https://user-images.githubusercontent.com/12921805/28719681-68299b24-7370-11e7-8a42-7b2c17345040.png)
![payment ospos new payment 3](https://user-images.githubusercontent.com/12921805/28719680-6804554e-7370-11e7-94fe-525425c44438.png)

Thank you

**Comment by daN4cat** [comment]
The best place for that would be reports. And yes please contribute but first you need to add support for the credit.

**Comment by guillermohaad** [comment]
Thanks @daN4cat for the appreciation, we will start as we are going, if anyone wants to support welcome

**Comment by SteveIreland** [comment]
Wouldn't you want to select a sale from the takings list view to record a payment against the sale?   I know that is where I first tried to find that option.  I would add a payment option in addition to the document display and the update option.

**Comment by daN4cat** [comment]
If you had a credit payment, you can mutate it to another type and it's there already when you edit the sale.  What is currently not there is the ability to change one to many payment types and allocate the amount across them.

**Comment by RamkrishnaMondal** [comment]
Graphical presentation of the above comment by @daN4cat  : 

![screenshot at 2017-08-08 17 47 35](https://user-images.githubusercontent.com/14151032/29071683-5718348a-7c62-11e7-88e7-ebd1b42ae82a.png)

**Comment by guillermohaad** [comment]
ok @RamkrishnaMondal Great be your contribution

**Comment by daN4cat** [comment]
Probably adding due payment to the list will do but I guess you would also like to get it in the filter in Takings like it's for Cash now. Again just a matter of adding one extra entry in a drop down list.

A simple implementation can be achieved with not too much just leveraging what is there already.

**Comment by daN4cat** [comment]
I can add due to the two lists if you want... and you use Takings to get by time range what is still out.

**Comment by RamkrishnaMondal** [comment]
@daN4cat  Here is my Taking filters:
![screenshot from 2017-08-08 23 15 59](https://user-images.githubusercontent.com/14151032/29086329-d8950a92-7c8f-11e7-8ebb-1d7c37f2661c.png)

**Comment by daN4cat** [comment]
What should it call it? "Credit", "Due" or else?

**Comment by RamkrishnaMondal** [comment]
At first i tried the term 'credit', but that was causing problem in takings filter as 'credit card' is already there. 
So i changed it to 'due' as payment type.

**Comment by daN4cat** [comment]
Implemented and in master, "due" is to indicate that customer has a credit and there is a due payment.

There is no reminder or else, just a means to filter from Takings the "Due" payments so somebody can look up outstanding payments.

I guess somebody might want to have a due report with customer list and outstanding, but that's another story.

**Comment by WebShells** [comment]
Jekkos, can my report be used to contribute in this ? in order to list all customers that have debt... ?

**Comment by jekkos** [comment]
Not sure which one you are talking about

**Comment by daN4cat** [comment]
@WebShells please contribute a new report for debt purposes, yes. Thanks

**Comment by RamkrishnaMondal** [comment]
Check out my customization here:
 http://www.tradingmaster.esy.es/public/login

It's on free hosting site, so pages may load slow.

**Comment by mckaygerhard** [comment]
the actual behaviour of the DUE are very unstable, and this does not are usefully to the "credit" sale impelmentation, this due when languaje changes all the sales payments will be broken..

so the solution must be added a id to the new credit payment.. of course the migration will be a pain, but noghit are easy when some features come. 

by now was the only way i found to manange a credit account

**Comment by mckaygerhard** [comment]
i coded a extra table with (in view details) extra field for that due payment, a  list (if was made it) ... but this implies a mini-accounting, so that's the extra table, i explain all here why and some behaviour.. **see the picture at the bottom**.  Ah, was based on the comment of https://github.com/opensourcepos/opensourcepos/issues/24#issuecomment-211098978 (edited in 2017, so rare, i remember a picture a day ago), 

Ah, its not same a due payment, rather than a credit due payment.. so i was named "tocredit"

The code calculates from that extra table how are due, i noted that total of sale are based on the sum of the payments, so its not so simple (in the model) to make this without a great knowledg of php OOP, so i must configure the extra table .. sorry ..  each payment are done based in a mixed key (sale_id, date)
I'm very impressive, the OSPOS architecture implies more logic from the engine rather from the database, and are great that the library will charge all the operations between the model and the bussines(controler/view)
But now lest explain the subsecuents problems of that (and future will be as i said)

now based on my comment previously, i separate payments in a extra table, .. so ight help to those working on  #1428 & #24, and #1869 #221 #353 #371 #565 #652 #710 #824

**IMPORTANT**: i can see that majority of the ERP's softwares always link the accounting with the pos/inventory, the reason implies that now if that change are done the possibility of change the amounts already made wil be not, if a client has due 40$, and a cash of 10$, i cannot change those 40$ in credits (with their respective payments made or not) to 10$.. all the accounting rules will crash..

![payment-credito](https://user-images.githubusercontent.com/1571724/37158887-df6b27a0-22c2-11e8-9bcb-20f847693b63.png)

I dont know if my code are good to a pull but i paste at lease the part of the model and the controller: are easy, with those only a part for the view are need:

in `appication/controllers/Sales.php` controller at the `edit` method, later, at the `save` method 
``` diff
index 6097842..6e02866 100644
--- a/application/controllers/Sales.php
+++ b/application/controllers/Sales.php
@@ -1125,14 +1127,19 @@ class Sales extends Secure_Controller
 		foreach($this->Sale->get_sale_payments($sale_id)->result() as $payment)
 		{
 			$paymentarray = get_object_vars($payment);
 			if( in_array($this->lang->line('sales_tocredit'), $paymentarray) )
 			{
+				$data['payment_tocredit_value'] = $this->xss_clean($value);
+				$data['payment_tocredit_due'] = $this->Sale->get_payment_tocredit($sale_id);
+				if($data['payment_tocredit_due'] < $data['payment_tocredit_value'])
+				{
+					$data['payment_tocredit_label'] = $this->lang->line('sales_tocredit'); //flag to show in sales/form.php, sorry its more easy wheantime.. later can be coded better
+					$payments[$this->lang->line('sales_tocredit')] =  $this->lang->line('sales_tocredit');
+				}
 			}
 			foreach($paymentarray as $property => $value)
 			{
@@ -1224,6 +1229,14 @@ class Sales extends Secure_Controller
 		{
 			$payment_amount = $this->input->post('payment_amount_' . $i);
 			$payment_type = $this->input->post('payment_type_' . $i);
+
+			if(strpos($payment_type, $this->lang->line('sales_tocredit')) > 0)
+			{
+				$payment_tocredit_amount = $this->input->post('payment_tocredit_amount');
+				if($payment_tocredit_amount > 0)
+					$tocredit = TRUE; // flag to make some at update...
+			}
+
 			// remove any 0 payment if by mistake any was introduced at sale time
 			if($payment_amount != 0)
 			{
@@ -1254,7 +1267,15 @@ class Sales extends Secure_Controller
 		if($this->Sale->update($sale_id, $sale_data, $payments))
 		{
-			echo json_encode(array('success' => TRUE, 'message' => $this->lang->line('sales_successfully_updated'), 'id' => $sale_id));
+			if($tocredit)
+			{	i$resulting = $this->Sale->save_payment_tocredit($sale_id, $payment_tocredit_amount);
+				if($resulting !== FALSE)
+				{
+					echo json_encode(array('success' => TRUE, 'message' => $this->lang->line('sales_successfully_updated'), 'id' => $sale_id));
+				}
+				else
+				{
+					echo json_encode(array('success' => FALSE, 'message' => $this->lang->line('sales_unsuccessfully_updated'), 'id' => $sale_id));
+				}
+			}
 		}
 		else
 		{
```

now at `application/models/Sale.php` model just added the methods to wirte and get data from the mini-accounting credits payments:
``` php
index 652ade3..eadad09 100644
--- a/application/models/Sale.php
+++ b/application/models/Sale.php
@@ -1498,5 +1475,56 @@ class Sale extends CI_Model
 		}
 		return COMPLETED;
 	}
+
+	/**
+	 * salva un pago a la vez de credito es decir abona
+	 */
+	public function save_payment_tocredit($sale_id, $amount)
+	{
+			$payment_tocredit = array(
+				'sale_id'			=> $sale_id,
+				'payment_tocredit'	=> date('YmdHns'),
+				'payment_amount'	=> $amount
+			);
+
+			$this->db->insert('sales_payments_tocredit', $payment_tocredit);
+	}
+
+	/**
+	 * obtiene todos los pagos parciales de una venta a credito
+	 */
+	public function get_payments_tocredit($sale_id)
+	{
+		$this->db->select('sale_id, payment_amount, payment_tocredit');
+		$this->db->from('sales_payments_tocredit');
+		$this->db->where('sale_id', $sale_id);
+
+		foreach($this->db->get()->result_array() as $result)
+		{
+			$payments_tocredits[$result['payment_tocredit']] = $result['payment_amount'];
+		}
+		if(count($payments_tocredits) < 1)
+			$payments_tocredits[$sale_id] = 0;
+
+		return $payments_tocredits;
+	}
+
+	/**
+	 * obtiene cuanto llevapagado del credito
+	 */
+	public function get_payment_tocredit($sale_id)
+	{
+		$this->db->select('IFNULL(SUM(payment_amount), 0) as payment_amount');
+		$this->db->from('sales_payments_tocredit');
+		$this->db->where('sale_id', $sale_id);
+
+		foreach($this->db->get()->result_array() as $result)
+		{
+			$payments_tocredits = $result['payment_amount'];
+		}
+
+		return $payments_tocredits + 0;
+	}
+
 }
 ?>
```

HEre just put at the sale details view rude inputs box with CI variables named `$payment_tocredit_amount` and `$payment_tocredit_due` those variables have "total credit" and also "due to pay" respectivelly, and are the problems for me, 

i'm not a CSS/DESIGNER expert so i put rude input box, due i only use CI helper funtions and ospos uses so any direct html tags, that makes difficulty to follow where are each piece:
the rest of the work are using js and ajax calls to made cheks at sale process (if there's one crecit payment must not be overdue due accounting)

**Comment by mckaygerhard** [comment]
i complete a credit mode payment with little payment add system to my cxcteipado here: https://github.com/codeigniterpower/osposweb/tree/osposweb-cxcteipado maybe the printing code are not right (i have to move to "receipt" method in sales)

that work may help some one that work in this feature.. i hope may help someone.

**Comment by izeblood** [comment]
OSPOS 3.3 Need this #1880

**Comment by WebShells** [comment]
@izeblood I was working on this and submitted first pull request, it needs alot of changes and my time is really killing me... Ill try if i can get back to it any soon...

**Comment by mckaygerhard** [comment]
but @WebShells in any w3ay your pull work has many code conduct breaks, event if works cannot merge, never!  XD  **but you have the idea, as i said, take a shot at the osposweb brand cxcteipado**

**Comment by WebShells** [comment]
@mckaygerhard oh really? Never knew that :) LOL

**Comment by mckaygerhard** [comment]
What I meant was that the same thing could be done in a short time, so that's why I quote the "cxcteipado" branch where I maintain the minimum code of conduct although not 100% is the minimum necessary. so "timeless" are not a excuse at all

**Comment by WebShells** [comment]
Mind your own business @mckaygerhard its clear i was very sarcastic and am not waiting any of your feedback :)... Thanks!

**Comment by mckaygerhard** [comment]
that sound sad, i was not sarcastic @WebShells , and i dont like to be as you said! i'm very clear about that! if not i collaborate more if i have my need resources!

**Comment by mckaygerhard** [comment]
sounds like your sarcastic response get back to you right? 

that sound sad, i was not sarcastic @WebShells , and i dont like to be as you said! i'm very clear about that! if not i collaborate more if i have my need resources!

**Comment by mckaygerhard** [comment]
only related but not similar/specific work: see #2080 (will be realted to xpenses)

**Comment by andriux1990** [comment]
Hola @mckaygerhard. Estuve haciendo unas pruebas con osposweb-cxcteipado del enlace https://github.com/codeigniterpower/osposweb/tree/osposweb-cxcteipado despues de la insalacion y luego de hacer la venta al credito. abro ventas diarias y al abrir para agregar el pago tengo esto 
![Screenshot_2019-03-10 Open Source Point of Sale Powered by VenenuX OSPOS 3 2 0](https://user-images.githubusercontent.com/29256343/54103620-b99ef780-4392-11e9-9522-dd70d760896d.png)
Que no se porque lo hace, pero al comentar estas dos lineas 

![Captura de pantalla de 2019-03-10 23-58-16](https://user-images.githubusercontent.com/29256343/54103662-dd623d80-4392-11e9-9e5d-583cfcfacdf8.png)

Ahora si ya se despliega la ventana

![Screenshot_2019-03-10 Open Source Point of Sale Powered by VenenuX OSPOS 3 2 0(2)](https://user-images.githubusercontent.com/29256343/54103698-0a165500-4393-11e9-9177-a7f20233b5b6.png)
Luego hago el abono de 10, dice que es exitoso

![Screenshot_2019-03-10 Open Source Point of Sale Powered by VenenuX OSPOS 3 2 0(3)](https://user-images.githubusercontent.com/29256343/54103719-1d292500-4393-11e9-98d1-6d79bde2921c.png)
Pero al final el abono sin resultados, sigo teniendo el mismo credito

![Screenshot_2019-03-11 Open Source Point of Sale Powered by VenenuX OSPOS 3 2 0](https://user-images.githubusercontent.com/29256343/54103726-22866f80-4393-11e9-8868-46f74d87d6a8.png)
Quiero saber que estoy haciendo mal, agradeceria tu ayuda.
Gracias

**Comment by robysetyaw** [comment]
> i complete a credit mode payment with little payment add system to my cxcteipado here: https://github.com/codeigniterpower/osposweb/tree/osposweb-cxcteipado maybe the printing code are not right (i have to move to "receipt" method in sales)
> 
> that work may help some one that work in this feature.. i hope may help someone.

@mckaygerhard hi dude, can you show me the code from https://github.com/codeigniterpower/osposweb/tree/osposweb-cxcteipado ?  i need installment payment for my client, thanks before

**Comment by andriux1990** [comment]
> > i complete a credit mode payment with little payment add system to my cxcteipado here: https://github.com/codeigniterpower/osposweb/tree/osposweb-cxcteipado maybe the printing code are not right (i have to move to "receipt" method in sales)
> > that work may help some one that work in this feature.. i hope may help someone.
> 
> @mckaygerhard hi dude, can you show me the code from https://github.com/codeigniterpower/osposweb/tree/osposweb-cxcteipado ? i need installment payment for my client, thanks before

For this to work for you, you will need to add the tables to the database.
then carefully add all the additional code to be able to have credit and installment payments
