### ISSUE TITLE
Payment due is not accepted by pos

### ISSUE THREAD

**Issue by saruban** [jekkos/opensourcepos#1429]
We need an option to add due payment in pos.
If a customer pay partial amount from his total amount,  the pos should keep balance payment as due in the particular customers account.  

When i tried to add a partial amount iy doesn't accept it.

**Comment by daN4cat** [comment]
Credit was covered again and again. Please implement it and contribute the feature here.

**Comment by saruban** [comment]
Can you please help to implement it

**Comment by daN4cat** [comment]
No time I'm afraid
