### ISSUE TITLE
Sales tax isn't displaying correctly

### ISSUE THREAD

**Issue by SteveIreland** [jekkos/opensourcepos#1430]
### Issue

I'm preparing to deploy the latest release and was running some tests to confirm that the numbers are computing correctly and found that the sales tax is calculating differently than how it should be.   I'm going to create a branch to fix this and submit it as a pull request.   I suspect it will be questioned because VAT tax is handled differently and I'm certainly going to avoid any impact on the VAT tax calculations (which I'm assuming is as it now should be).

**Comment by SteveIreland** [comment]
Subsequent testing found that the sales tax wasn't actually being calculated incorrectly.  What bit me was that the redefinition of the Round codes.  I used the tax maintenance program to reset the tax code and all is good.

However, I do need to change the display of the tax amounts for sales taxes to be in the currency decimals instead of the tax decimals.  So I think this probably needs to be conditioned to display in currency decimals but only if the sales tax is enabled.. 

I haven't looked at the cash rounding code in a long time and it looks like some of that code has been refactored.  So I'll retest that later this week.  I haven't heard from anyone as to whether they were using it or planning on using it.

**Comment by daN4cat** [comment]
@SteveIreland is this still an issue after I merged your change?

**Comment by daN4cat** [comment]
@SteveIreland ?

**Comment by SteveIreland** [comment]
This was fixed when  you merged one of my pull requests and I've been using it in production so it must be working. 

I'll test the VAT tax cash rounding scenario now.

**Comment by SteveIreland** [comment]
I'm testing from the latest master and there is at least one problem (related to cash rounding) that requires a fix.   Continuing to work on it now.

**Comment by SteveIreland** [comment]
Submitted a pull request for it.

**Comment by daN4cat** [comment]
Merged and in master now.
