### ISSUE TITLE
 Access forbidden!  Error .

### ISSUE THREAD

**Issue by MuneerSM** [jekkos/opensourcepos#1432]
Access forbidden!

You don't have permission to access the requested directory. There is either no index document or the directory is read-protected.
![to sadi](https://user-images.githubusercontent.com/30566639/28751719-b49ae072-752c-11e7-9eb9-82e54ee4d9a4.png)

- [] I'm reporting an issue of an unmodified OSPOS installation

- OSPOS version is: 3.0,2
- OSPOS git commit hash is: 
- PHP version is:    7.1
- MySQL or MariaDB version is:   . MySQL 5.5,
- OS and version is:  Windows 7
- WebServer is:   . Apache 2.2,
- (If applicable) Installation package for the LAMP/LEMP stack is:XAMP
![to sadi](https://user-images.githubusercontent.com/30566639/28751712-88c97756-752c-11e7-9613-767bb81f9b16.png)

**Comment by daN4cat** [comment]
3.0.2 doesn't support PHP7.
