### ISSUE TITLE
Access forbidden! Issue

### ISSUE THREAD

**Issue by Ibnumarjan** [jekkos/opensourcepos#1434]
### IMPORTANT IMPORTANT IMPORTANT
- [X] I'm reporting an issue of an unmodified OSPOS installation
- [] I checked open and closed issues database and no similar issue was already discussed (please make sure you searched!)
- [x] I read the README, WHATS_NEW and UPGRADE
- [x] I read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php-gd, php-intl, sockets and etc. installed)
- [x] I read the wiki
- [] I ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql), and migrating function
- [] I'm aware the latest master could be a development version and therefore not stable
- [] I know the version of OSPOS and git commit hash (check the footer of your OSPOS), the name and version of OS, Web server, PHP and MySQL and will add them to my issue report

### Installation information

- OSPOS version is: 3.0.2
- OSPOS git commit hash is: 
- PHP version is:   5.6.23
- MySQL or MariaDB version is:   10.1.13-MariaDB
- OS and version is:  Windows 7 Enterprice
- WebServer is:   Apache 2.4.17
- (If applicable) Installation package for the LAMP/LEMP stack is:    XAMPP

### Expected behaviour
Should appear Login page

### Actual behaviour
Access forbidden!

You don't have permission to access the requested directory. There is either no index document or the directory is read-protected.
If you think this is a server error, please contact the webmaster.

Error 403
localhost
Apache/2.4.17 (Win32) OpenSSL/1.0.2d PHP/5.6.23

**Comment by daN4cat** [comment]
You didn't check the box for `I checked open and closed issues database and no similar issue was already discussed (please make sure you searched!)`
