### ISSUE TITLE
Issues of Access forbidden!

### ISSUE THREAD

**Issue by Ibnumarjan** [jekkos/opensourcepos#1435]
### Issue / Question / Bug

Before submitting an issue please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [X] I'm reporting an issue of an unmodified OSPOS installation
- [X] I checked open and closed issues database and no similar issue was already discussed (please make sure you searched!)
- [X] I read the README, WHATS_NEW and UPGRADE
- [X] I read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php-gd, php-intl, sockets and etc. installed)
- [X] I read the wiki
- [X] I ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql), and migrating function
- [X] I'm aware the latest master could be a development version and therefore not stable
- [X] I know the version of OSPOS and git commit hash (check the footer of your OSPOS), the name and version of OS, Web server, PHP and MySQL and will add them to my issue report

### Installation information

- OSPOS version is: 3.0.2
- OSPOS git commit hash is: 
- PHP version is:   5.6.23
- MySQL or MariaDB version is:   10.1.13-MariaDB
- OS and version is:   Windows 7 Enterprise
- WebServer is:   Apache 2.4.17
- (If applicable) Installation package for the LAMP/LEMP stack is:   XAMPP

### Expected behavior
should work noraml

### Actual behavior
I don't have sub-directory (localhost/pos)
clean install, no modifications, old ospos version(2.4) working charm in the same xampp stack 

Access forbidden!

You don't have permission to access the requested directory. There is either no index document or the directory is read-protected.
If you think this is a server error, please contact the webmaster.

Error 403
localhost
Apache/2.4.17 (Win32) OpenSSL/1.0.2d PHP/5.6.23

**Comment by Ibnumarjan** [comment]
I don't have sub-directory (localhost/pos)
clean install, no modifications, old ospos version(2.4) working charm in the same xampp stack 

Access forbidden!

You don't have permission to access the requested directory. There is either no index document or the directory is read-protected.
If you think this is a server error, please contact the webmaster.

Error 403
localhost
Apache/2.4.17 (Win32) OpenSSL/1.0.2d PHP/5.6.23

**Comment by odiea** [comment]
Did you try localhost/public?

**Comment by Ibnumarjan** [comment]
Thanks for your reply,

You mean instead of localhost/pos

**Comment by Ibnumarjan** [comment]
in htdocs, I have creaded a folder call pos and copied the OSPOS folder files. So I go to the app typing localhost/pos in Chrome

**Comment by odiea** [comment]
you need to type localhost/pos/public

**Comment by Ibnumarjan** [comment]
I try the above localhost/pos/public.... but it says the following error.
Your system folder path does not appear to be set correctly. Please open the following file and correct this: index.php

**Comment by daN4cat** [comment]
I don't know why all these XAMPP installations have always problems...

**Comment by Ibnumarjan** [comment]
even now I tested with the WAMP, same problem

**Comment by daN4cat** [comment]
@odiea is there anything that can be clearly detailed in the wiki to get this one sorted forever?

**Comment by daN4cat** [comment]
@Ibnumarjan I assume you read current wiki and any issue around this problem that was discussed in the past already.
I'm afraid I can't help outside that.

**Comment by odiea** [comment]
I also got this issue this morning after a merge. I don't think it is xampp related

**Comment by Ibnumarjan** [comment]
Can you point me the correct Wiki page for the particular issue

**Comment by Ibnumarjan** [comment]
Now localhost/pos/public gives the login page, but when i submit after user name and password, home page not loading and gives the following error.

```
This page isn't working

localhost is currently unable to handle this request
HTTP ERROR 500
```

**Comment by daN4cat** [comment]
Is that with the latest master or else? I can't help with Windows based installations as I use Linux CentOS, so in that case I would say check .htaccess file in public dir as that needs to be changed to include the pos subdir otherwise it doesn't work.

**Comment by Ibnumarjan** [comment]
The above problem is with version 3.0.2.

my real path is directly under htdocs, it is pos... So I don't think, in my case i am in sub directory. even though I tested with that (not work)

**Comment by daN4cat** [comment]
Have you checked directory permission and owner?

**Comment by daN4cat** [comment]
If not correct apache will not have access to the directory no matter

**Comment by Ibnumarjan** [comment]
I have checked the director permission and the owner> Full permission for every one and Administrator. I have log in as a Administrator

**Comment by daN4cat** [comment]
There must be some problem with XAMPP recently, see #1394. But I don't use Windows so I don't know how to help.
I assume you checked that your php.ini has all the required PHP extensions enabled, right?

Also please check the database privileges as indicated by #1042

And this guy #1323 in the end solved switching to WAMP 3.0.2.

Search past closed issue you'll find some hint to help you.

**Comment by daN4cat** [comment]
And are you sure MariaDB 10.1 is fine? 3.0.2 does not support MySQL 5.7, I wouldn't that MariaDB 10.1 is the same?

Please check that too.

**Comment by daN4cat** [comment]
Also please check if you public dir has any error.log file. If yes, what's written inside?

**Comment by odiea** [comment]
Yes he definitely needs to use an earlier version of xampp if he is using 3.0.2.

**Comment by odiea** [comment]
I just went to sourceforge and downloaded 3.0.2 runs great on the current version of Xampp I am using. So the earlier version is not required.

**Comment by odiea** [comment]
This was the issue related to either php7 or mysql 5.7.

![2017-08-07 11_50_42-open source point of sale _ powered by ospos 3 0 2](https://user-images.githubusercontent.com/10962177/29039033-f1d9055a-7b66-11e7-8f2b-ab5ff4469cc9.png)

**Comment by odiea** [comment]
Did u download it with windows Internet Explorer or Opera if so you will need to go back to the download right click and check unblock.

**Comment by odiea** [comment]
@daN4cat I have had no issues while using Xampp if like everything else it is set up with proper extensions enabled. I think it is 1 of the easiest local web servers to use.

**Comment by Ibnumarjan** [comment]
I give us XAMPP and installed in WAMP the same story...
And I use only Chrome for download.

**Comment by daN4cat** [comment]
Do you see any error.log file in public dir or elsewhere? If yes what's inside?

**Comment by Ibnumarjan** [comment]
there is no error.log file in public dir

**Comment by daN4cat** [comment]
I'm afraid we run out of ideas here. I would say install some other simple php app from github in that direction and see if it works or not.
Also check stockoverflow website and see if you can find help there.

**Comment by odiea** [comment]
@daN4cat There is a linux version if you ever want to try it out. Like others he can also make a linux server vm.

**Comment by seankelvin** [comment]
May you help me in configuring opensourcepos, I have just downloaded opensourcepos.20181230151427.refactor-tax-config.c6d8e9.zip. Configured but receive error  
Not Found
The requested URL /public/ was not found on this server.
Apache/2.4.23 (Win32) PHP/7.0.10 Server at localhost Port 80

have changed the credencials on database to

**'hostname' => !empty(getenv('MYSQL_HOST_NAME')) ? getenv('MYSQL_HOST_NAME') : 'localhost',
	'username' => !empty(getenv('MYSQL_USERNAME')) ? getenv('MYSQL_USERNAME') : 'root',
	'password' => !empty(getenv('MYSQL_PASSWORD')) ? getenv('MYSQL_PASSWORD') : '',
	'database' => !empty(getenv('MYSQL_DB_NAME')) ? getenv('MYSQL_DB_NAME') : 'ospos',**

have changed htaccess to

# if in web root
# RewriteRule ^(.*)$ index.php?/$1 [L]

# if in subdir comment above line, uncomment below one and replace <OSPOS path> with your path
  RewriteRule ^(.*)$ /<ospos>/public/index.php?/$1 [L]

my directory name is ospos located in www/ospos

**Comment by seankelvin** [comment]
May you help me in configuring opensourcepos, I have just downloaded opensourcepos.20181230151427.refactor-tax-config.c6d8e9.zip. Configured but receive error
Not Found
The requested URL /public/ was not found on this server.
Apache/2.4.23 (Win32) PHP/7.0.10 Server at localhost Port 80

have changed the credencials on database to

'hostname' => !empty(getenv('MYSQL_HOST_NAME')) ? getenv('MYSQL_HOST_NAME') : 'localhost',
'username' => !empty(getenv('MYSQL_USERNAME')) ? getenv('MYSQL_USERNAME') : 'root',
'password' => !empty(getenv('MYSQL_PASSWORD')) ? getenv('MYSQL_PASSWORD') : '',
'database' => !empty(getenv('MYSQL_DB_NAME')) ? getenv('MYSQL_DB_NAME') : 'ospos',

have changed htaccess to

#if in web root
#RewriteRule ^(.*)$ index.php?/$1 [L]
#if in subdir comment above line, uncomment below one and replace with your path
RewriteRule ^(.*)$ /<ospos>/public/index.php?/$1 [L]

my directory name is ospos located in www/ospos

**Comment by daN4cat** [comment]
Why double // before public ? Also if you installed in the root folder ospos there is no reason to touch the .htaccess

**Comment by seankelvin** [comment]
Sorry daN4cat I mistyped. the correct one is as follows:

# if in web root
# RewriteRule ^(.*)$ index.php?/$1 [L]

# if in subdir comment above line, uncomment below one and replace <OSPOS path> with your path
  RewriteRule ^(.*)$ /<ospos>/public/index.php?/$1 [L]

and the directory is

C:\wamp\www\ospos

**Comment by seankelvin** [comment]
Sorry daN4cat I mistyped. the correct one is as follows:

#if in web root
#RewriteRule ^(.*)$ index.php?/$1 [L]
#if in subdir comment above line, uncomment below one and replace with your path
RewriteRule ^(.*)$ /<ospos>/public/index.php?/$1 [L]

and the directory is

C:\wamp\www\ospos

**Comment by daN4cat** [comment]
Again, I don't understand the double /, you need to write ospos between those back slashes:

RewriteRule ^(.)$ /ospos/public/index.php?/$1 [L]

**Comment by seankelvin** [comment]
at the present moment its like as follows, but still says
The requested URL /public/ was not found on this server.

#if in web root
#RewriteRule ^(.)$ index.php?/$1 [L]
#if in subdir comment above line, uncomment below one and replace with your path
RewriteRule ^(.)$ /ospos/public/index.php?/$1 [L]

I have an older master which works fine. now I need one which receives payments for previously done invoices
