### ISSUE TITLE
Foreign Key Constraint Issues

### ISSUE THREAD

**Issue by odiea** [jekkos/opensourcepos#1436]
### Issue / Question / Bug

Before submitting an issue please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] I'm reporting an issue of an unmodified OSPOS installation
- [x] I checked open and closed issues database and no similar issue was already discussed (please make sure you searched!)
- [x] I read the README, WHATS_NEW and UPGRADE
- [x] I read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php-gd, php-intl, sockets and etc. installed)
- [x] I read the wiki
- [x] I ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql), and migrating function
- [x] I'm aware the latest master could be a development version and therefore not stable
- [x] I know the version of OSPOS and git commit hash (check the footer of your OSPOS), the name and version of OS, Web server, PHP and MySQL and will add them to my issue report

### Installation information

- OSPOS version is: Current Master
- OSPOS git commit hash is: 
- PHP version is:   (e.g. 5.5, 5.6, 7.0, 7.1) 7
- MySQL or MariaDB version is:   (e.g. MySQL 5.5, MySQL 5.6, MySQL 5.7, MariaDB 10.0, MariaDB 10.1, MariaDB 10.2)
- OS and version is:   (e.g. CentOS 6.9, Ubuntu 16.4, Windows 10)
- WebServer is:   (e.g. Apache 2.2, Apache 2.4, Nginx 1.12, Nginx 1.13)
- (If applicable) Installation package for the LAMP/LEMP stack is:   (e.g. WAMP, XAMPP)

### Expected behaviour
A receipt is shown

### Actual behaviour
![2017-08-02 09_36_57-database error](https://user-images.githubusercontent.com/10962177/28881817-a02c8500-7766-11e7-99cb-8cc614a4a4c0.png)

### Steps to reproduce the issue
I tried installing the current foreign key constraints.
ALTER TABLE `ospos_customers_points`
  ADD KEY `person_id` (`person_id`),
  ADD KEY `package_id` (`package_id`),
  ADD KEY `sale_id` (`sale_id`),
  ADD CONSTRAINT `ospos_customers_points_ibfk_1` FOREIGN KEY (`person_id`) REFERENCES `ospos_customers` (`person_id`),
  ADD CONSTRAINT `ospos_customers_points_ibfk_2` FOREIGN KEY (`package_id`) REFERENCES `ospos_customers_packages` (`package_id`),
  ADD CONSTRAINT `ospos_customers_points_ibfk_3` FOREIGN KEY (`sale_id`) REFERENCES `ospos_sales_items` (`sale_id`);

This failed on adding sql in Phpmyadmin. I temporarily disabled the check. It installed ok but now I get the above Error when a receipt is shown.

ALTER TABLE `ospos_sales_reward_points`
  ADD KEY `sale_id` (`sale_id`),
  ADD CONSTRAINT `ospos_sales_reward_points_ibfk_1` FOREIGN KEY (`sale_id`) REFERENCES `ospos_sales_items` (`sale_id`);

ALTER TABLE `ospos_customers`
  ADD KEY `package_id` (`package_id`),
  ADD CONSTRAINT `ospos_customers_ibfk_2` FOREIGN KEY (`package_id`) REFERENCES `ospos_customers_packages` (`package_id`);

**Comment by odiea** [comment]
It appears that the add key needs to be removed because the key is already there.

ALTER TABLE `ospos_sales_reward_points`
  ADD KEY `sale_id` (`sale_id`),
  ADD CONSTRAINT `ospos_sales_reward_points_ibfk_1` FOREIGN KEY (`sale_id`) REFERENCES `ospos_sales_items` (`sale_id`);

CREATE TABLE IF NOT EXISTS `ospos_sales_reward_points` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `sale_id` int(11) NOT NULL,
  `earned` float NOT NULL,
  `used` float NOT NULL,
  PRIMARY KEY (`id`),
  KEY `sale_id` (`sale_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;

**Comment by odiea** [comment]
To get the db working properly I had to drop the ospos_sales_reward_points and reinstall the table without the constraints being added back in.

**Comment by SteveIreland** [comment]
I hate constraints of any kind.   :wink:  Free OSPOS!

**Comment by daN4cat** [comment]
When I've added the fk changes I applied those to my database and I have tested, but I can't see any error in passing a sale transaction or adding an item with my current setup.
I'll check more this eve as it might be some test setup that differs between you and me.

**Comment by daN4cat** [comment]
@odiea I cannot reproduce it

**Comment by odiea** [comment]
I will close then .

**Comment by daN4cat** [comment]
found, you need to have a customer added to the sale with reward tier allocated

**Comment by daN4cat** [comment]
Probably it happens because it adds the points before the sale is created...

**Comment by odiea** [comment]
I will try to be more specific next issue.

**Comment by daN4cat** [comment]
OK, found.

I'm going to fix the 3.0.2_to_3.1.0.sql script but in case somebody has done the update already with the mistake they need to run this to fix it:

ALTER TABLE `ospos_sales_reward_points`
  DROP FOREIGN KEY `ospos_sales_reward_points_ibfk_1`;
ALTER TABLE `ospos_sales_reward_points`
  ADD CONSTRAINT `ospos_sales_reward_points_ibfk_1` FOREIGN KEY (`sale_id`) REFERENCES `ospos_sales`(`sale_id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE `ospos_customers_points`
  DROP FOREIGN KEY `ospos_customers_points_ibfk_3`;
ALTER TABLE `ospos_customers_points`
  ADD CONSTRAINT `ospos_customers_points_ibfk_3` FOREIGN KEY (`sale_id`) REFERENCES `ospos_sales`(`sale_id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

**Comment by daN4cat** [comment]
OK, fix in master

**Comment by odiea** [comment]
On the new table I had to remove the 1st 2 lines and all went well. DROP FOREIGN KEY ospos_sales_reward_points_ibfk_1; is not in the table.

ALTER TABLE ospos_sales_reward_points
DROP FOREIGN KEY ospos_sales_reward_points_ibfk_1;
ALTER TABLE ospos_sales_reward_points
ADD CONSTRAINT ospos_sales_reward_points_ibfk_1 FOREIGN KEY (sale_id) REFERENCES ospos_sales(sale_id) ON DELETE RESTRICT ON UPDATE RESTRICT;

**Comment by daN4cat** [comment]
Yes, because you removed the old fk previously that's why you got the error.

**Comment by daN4cat** [comment]
Let me know if it works fine now

**Comment by odiea** [comment]
My original issue was with the following not wanting to update the database without errors.

ALTER TABLE ospos_sales_reward_points ADD KEY sale_id (sale_id), ADD CONSTRAINT ospos_sales_reward_points_ibfk_1 FOREIGN KEY (sale_id) REFERENCES ospos_sales_items (sale_id);
--
I then bypassed the constraints and it installed the Foreign Key but it had the Error when a customer with rewards points had a Sale it was not completed.

After removing the 1st 2 lines of the newly created sql it was properly installed on the original table [ that had no constraints ] and I had no issues in Sales.

**Comment by daN4cat** [comment]
I'm lost.... are you saying that even with the fix I made you still get errors?

The issue was that the FK was pointing to ospos_sales_items where it should have pointed to ospos_sales

**Comment by odiea** [comment]
My grand Daughter is on the computer now. I will send more info later after I text it on a different db..

**Comment by daN4cat** [comment]
No worries, we don't want to disrupt the kids playing with your computer :-)

**Comment by odiea** [comment]
Works great. No issues now.
