### ISSUE TITLE
Tool tip idea

### ISSUE THREAD

**Issue by odiea** [jekkos/opensourcepos#144]
I found a simple tool tip installer for ospos div. Just place this around your ospos div and you get a handy little tooltip.
div class="tooltip" title="This is my div's tooltip message!"
   
/div
Just change the info in the Title and your good to go. I don't know if this can be adapted to the This>line>language or not.
This code is from tooltipster which I could not get to function in OSPOS. Hope this helps someone.

**Comment by jekkos** [comment]
Sounds good. The text for these tooltips could be added easily to the csv files in the translations folder. Then after regenerating the language files, the $this->lang->line(config_tooltip_*¨) can be called to add info to each item in the config module

**Comment by jekkos** [comment]
Duplicate issue (see #35), will close the older one for now.

**Comment by odiea** [comment]
The program currently hat thickbox on it already. If you can geve me some idea on how to use the following code on a single div please let me know.
<?php echo anchor("sales/suspended/width:425",
		"<div class='small_button'><span style='font-size:73%;'>".$this->lang->line('sales_suspended_sales')."</span></div>",
		array('class'=>'thickbox none','title'=>$this->lang->line('sales_suspended_sales')));
		?>
I think I am more interested to get the array part working to see if it can bee added to a current div.

**Comment by daN4cat** [comment]
Was this solved?

I thought it could have been a good addition for one of the next releases.

**Comment by odiea** [comment]
No. I could not get a response on how to apply the tooltip idea. It could be a good addition for some future release.

**Comment by daN4cat** [comment]
OK, so I reopen and as it was marked as enhancement already and we could consider it in the future.

BTW, I noticed that you open and closed other issues. But if you don't leave them open we will never manage to find and see what we can do.

Would you mind to go back and reopen them?

**Comment by odiea** [comment]
I think most of my issues are just personnel preferences and not real issues. But I did reopen them. Glad to see your back.

**Comment by daN4cat** [comment]
I'll have a look later. Thanks.

**Comment by daN4cat** [comment]
Tooltips are part of Bootstrap and they can be added later:

`data-toggle="tooltip" data-placement="left" title="" data-original-title="Tooltip on left"`

**Comment by daN4cat** [comment]
Do we still need tooltips given the latest changes in 3.0?

**Comment by odiea** [comment]
I don't think so. I will close this issue.
