### ISSUE TITLE
Do not show migration module if no migration is needed

### ISSUE THREAD

**Issue by jekkos** [jekkos/opensourcepos#1440]
### New Feature / Enhacement
Would be nice to only show this module when a migration needs to be done. Otherwise it's cluttering up the menubar (which will have already one new module in 3.1)

* Therefore we should find a way to see if migration is required, probably by comparing the db schema version with the version of the code. 
* Idea is to determine which statements have been run and which not so that migration can be done automatically..

**Comment by daN4cat** [comment]
Done and in master.

**Comment by daN4cat** [comment]
Tested both conditions and works as expected.
