### ISSUE TITLE
Add reCaptcha to login page

### ISSUE THREAD

**Issue by daN4cat** [jekkos/opensourcepos#1443]
In order to avoid the obvious and dictionary type of attacks, add reCaptcha to login page.

Can be added using https://github.com/appleboy/CodeIgniter-reCAPTCHA

**Comment by daN4cat** [comment]
Or https://github.com/idindrakusuma/ci-recaptcha

**Comment by jekkos** [comment]
If I remember well then CI already has some simple captcha library builtin, maybe we can leverage that?

**Comment by daN4cat** [comment]
This is now implemented and in master.

To understand what reCAPTCHA is: https://www.google.com/recaptcha/intro/index.html
To use reCAPTCHA, you need to sign up for an API key pair for your site here: http://www.google.com/recaptcha/admin

**Comment by daN4cat** [comment]
Here how it will appear

![image](https://user-images.githubusercontent.com/636048/28994974-5412b5de-79d4-11e7-8d27-9cf320e562a9.png)

**Comment by jekkos** [comment]
Hmm does this require one to have an internet connection?

**Comment by daN4cat** [comment]
It's disabled by default and you can enable it or not :-)
See Store Config General tab.

**Comment by jekkos** [comment]
Ok great addition, offers some protection to brute force login as well

**Comment by daN4cat** [comment]
Indeed, that was the intention here.
