### ISSUE TITLE
Git or Repository Issue?

### ISSUE THREAD

**Issue by odiea** [jekkos/opensourcepos#1444]
I have tries 3 or 4 times in the last 15 or 20 minutes.
![2017-08-05 12_25_08-](https://user-images.githubusercontent.com/10962177/28997741-3bf67cc4-79d9-11e7-814c-693a8ccaa962.png)

**Comment by daN4cat** [comment]
@odiea what's the issue?

**Comment by odiea** [comment]
It appears to me that there are 2 commits after Various fixes. Neither of them will show up after a merge.

**Comment by daN4cat** [comment]
All is fine from this side of the Atlantic. Not sure what's wrong there. Try to reclone everything in a new directory. I remember I had once a problem under windows and I ended up cloning everything again.

**Comment by odiea** [comment]
BTW merges started working just fine this morning.
