### ISSUE TITLE
Your system folder path does not appear to be set correctly. Please open the following file and correct this: index.php

### ISSUE THREAD

**Issue by odiea** [jekkos/opensourcepos#1447]
### Issue / Question / Bug

Before submitting an issue please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] I'm reporting an issue of an unmodified OSPOS installation
- [x] I checked open and closed issues database and no similar issue was already discussed (please make sure you searched!)
- [x] I read the README, WHATS_NEW and UPGRADE
- [x] I read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php-gd, php-intl, sockets and etc. installed)
- [x] I read the wiki
- [x] I ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql), and migrating function
- [x] I'm aware the latest master could be a development version and therefore not stable
- [x] I know the version of OSPOS and git commit hash (check the footer of your OSPOS), the name and version of OS, Web server, PHP and MySQL and will add them to my issue report

### Installation information

- OSPOS version is:
- OSPOS git commit hash is: 
- PHP version is:   (e.g. 5.5, 5.6, 7.0, 7.1)
- MySQL or MariaDB version is:   (e.g. MySQL 5.5, MySQL 5.6, MySQL 5.7, MariaDB 10.0, MariaDB 10.1, MariaDB 10.2)
- OS and version is:   (e.g. CentOS 6.9, Ubuntu 16.4, Windows 10)
- WebServer is:   (e.g. Apache 2.2, Apache 2.4, Nginx 1.12, Nginx 1.13)
- (If applicable) Installation package for the LAMP/LEMP stack is:   (e.g. WAMP, XAMPP)

### Expected behaviour
Should show Login page
**This is a new cloned Instance.**
### Actual behaviour
Your system folder path does not appear to be set correctly. Please open the following file and correct this: index.php

### Steps to reproduce the issue
Do a merge from current master

**Comment by odiea** [comment]
`// Set the current directory correctly for CLI requests
	if (defined('STDIN'))
	{
		chdir(dirname(__FILE__));
	}

	if (($_temp = realpath($system_path)) !== FALSE)
	{
		$system_path = $_temp.DIRECTORY_SEPARATOR;
	}
	else
	{
		// Ensure there's a trailing slash
		$system_path = strtr(
			rtrim($system_path, '/\\'),
			'/\\',
			DIRECTORY_SEPARATOR.DIRECTORY_SEPARATOR
		).DIRECTORY_SEPARATOR;
	}

	// Is the system path correct?
	if ( ! is_dir($system_path))
	{
		header('HTTP/1.1 503 Service Unavailable.', TRUE, 503);
		echo 'Your system folder path does not appear to be set correctly. Please open the following file and correct this: '.pathinfo(__FILE__, PATHINFO_BASENAME);
		exit(3); // EXIT_CONFIG
	}`

**Comment by jekkos** [comment]
you will need to install composer files manually now.. they are not the repo anymore.
so first run `composer install`. Then you need to run grunt.

**Comment by i92guboj** [comment]
I've hit this as well. However, I needed some extra steps to make this work. Something about being "Unable to load the requested language file: language/spanish/form_validation_lang.php"

I looked around, and symlinked the "es" directory to "spanish". That allowed me to start the thing. However, it looks weird. Shot attached.

![image](https://user-images.githubusercontent.com/1565651/29022600-4f79924e-7b6a-11e7-892d-3abd055ede15.png)

**Comment by i92guboj** [comment]
It seems jquery is not in place any longer?

**Comment by daN4cat** [comment]
Run the devinstall script under bin and that will do the job for you

**Comment by i92guboj** [comment]
Ok, thanks, that did the trick. There were a couple of other weird things as well. That sorted everything out.

**Comment by balmohan** [comment]
Install composer and hit
"composer update" command in root dir
Everything will start working.

**Comment by odiea** [comment]
Just install the latest unstable from bintray

**Comment by EricMbuthia** [comment]
I cannot locate any system folder. I did not delete any nor did i rename anything.

**Comment by mckaygerhard** [comment]
@EricMbuthia the system DIRECTORY are part of the framework its just a message, and due the structure of the ospos are away from xpectedin, this happened if you install directly from github diue the very complicated infraestructure (use bower, npm, nodejs etc etc)

to solve install from bintray or download lasted stable 3.1.1 as README said, please read carefully next time..

if you download and install a bintray or stable, so then seems you installed in a subpath under the htdocs directory.. currently the HARDCODED way of the application claims to install in root of the htdocs (by example in the /var/www/html direclty)

**Comment by itachi619** [comment]
Hi, must the owner of the website fix this error/problem? Thanks.

**Comment by dennistsc** [comment]
after i put 127.0.0.1
it show Your system folder path does not appear to be set correctly. Please open the following file and correct this: index.php

ubuntu 20.04
ospos version 3.3.6

anyone can help thanks you

**Comment by creandowebcolombia** [comment]
solucionaron?

**Comment by odiea** [comment]
Download the zip or tar from the Install md page.
