### ISSUE TITLE
Stock no longer decreases when selling

### ISSUE THREAD

**Issue by i92guboj** [jekkos/opensourcepos#1450]
### Issue / Question / Bug

Before submitting an issue please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] I'm reporting an issue of an unmodified OSPOS installation
- [x] I checked open and closed issues database and no similar issue was already discussed (please make sure you searched!)
- [x] I read the README, WHATS_NEW and UPGRADE
- [x] I read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php-gd, php-intl, sockets and etc. installed)
- [x] I read the wiki
- [x] I ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql), and migrating function
- [x] I'm aware the latest master could be a development version and therefore not stable
- [x] I know the version of OSPOS and git commit hash (check the footer of your OSPOS), the name and version of OS, Web server, PHP and MySQL and will add them to my issue report

### Installation information

- OSPOS version is: 3.1.0
- OSPOS git commit hash is: 4f5ad57
- PHP version is:   5.6.31
- MySQL or MariaDB version is: mysql 5.6.36
- OS and version is:  gentoo 
- WebServer is:  2.4.27

### Expected behaviour

Up to now, when I sold something, the stock would decrease (yes, I have checked stock type is still "0" for that concrete item).

### Actual behaviour

Stock doesn't decrease. 

### Steps to reproduce the issue

The only thing I did was, git fetch, git merge, run the latest additions from database/3.0.2_to_3.1.0.sql in my database, and then, as per instructions in some other issue, ran bin/devinstall.sh

Everything seems to work. But I have noticed that the stock is not decreasing when I sell items, which is a BIG issue for me since this is connected to an online shop.

I see no errors in the apache logs, js console or whatever when selling.

From time to time, I see this in js console, but I have no idea if it's related at all.

`opensourcepos.min.js?rel=b0a1d9215d:46 Uncaught TypeError: Cannot read property 'uniqueId' of undefined
    at HTMLTableRowElement.<anonymous> (opensourcepos.min.js?rel=b0a1d9215d:46)
    at HTMLTableRowElement.d.complete (opensourcepos.min.js?rel=b0a1d9215d:4)
    at k (opensourcepos.min.js?rel=b0a1d9215d:4)
    at Object.fireWith [as resolveWith] (opensourcepos.min.js?rel=b0a1d9215d:4)
    at i (opensourcepos.min.js?rel=b0a1d9215d:2)
    at _.fx.tick (opensourcepos.min.js?rel=b0a1d9215d:6)
`

This was working perfectly yesterday. So, I assume it's related to the latest changes. I'll look around, but maybe you have some pointers on where the problem might lie.

Thanks!

**Comment by i92guboj** [comment]
I am reading the commits related to this new HAS_STOCK define. Let's look into applications/models/Sale.php, around line 613. There you have the check that decides wheter the stock will be modified.

This define pandemonium seems not to have taken into account something. The check fails because we are probably comparing a string (or a char) to an integer, or something like that.

By changing both defines (COMPLETED and HAS_STOCK) from 0 to '0' the check works again. But I wouldn't dare to say what the course action would be here. It could be relaxing a bit the php check, or it could be changing the semantics somewhere. Or just redefining the defines as 'string' instead of int.

I am not profficient enough with php and ospos to tell what you should be doing to fix this. But the fact that the old comporisson used '0' and the define is just 0, without quotes, pointed me in that direction.

Changing the defines to '0', fixed this for me, but I have yet to double check that this doesn't screw something else.

**Comment by i92guboj** [comment]
Said otherwise, I wonder why stock_type is treated all around as a string whereas in the database it's a tinyint column.

But, maybe that's just the php way of things, which I am unfamiliar with, as said.

**Comment by odiea** [comment]
Thanks for finding this issue. And here may be the reason it is not working.
Items before
![2017-08-07 12_19_15-wedidit _ powered by ospos 3 1 0](https://user-images.githubusercontent.com/10962177/29040051-e3a85b8a-7b6a-11e7-90d6-e943335d1381.png)
Items after trying to enable .
![2017-08-07 12_19_15-wedidit _ powered by ospos 3 1 0](https://user-images.githubusercontent.com/10962177/29040065-f0fef4f6-7b6a-11e7-9531-80872394c1d0.png)

**Comment by SteveIreland** [comment]
The data type conversion will not be the issue.

I haven't looked (but will do so later this evening) but I'm wondering if some sort of constraint involving the tax_category field on the item table was added.  If so that might cause the behavior that @odiea is reporting if the foreign key value on the item table doesn't correspond to an entry in the tax_category table.  This is just a wild guess and could be totally off base.  If someone else doesn't resolve the issue in the next few hours then I'll chase it down,

**Comment by odiea** [comment]
Something went terribly wrong. @SteveIreland thanks for the feedback.

**Comment by i92guboj** [comment]
@odiea , yes, I also noticed that issue, and the fact @SteveIreland , is that the form issue is algo gone once I change the defines this way:

`define('HAS_STOCK', '0');
define('HAS_NO_STOCK', '1');

define('ITEM', '0');
define('ITEM_KIT', '1');

define('PRINT_ALL', '0');
define('PRINT_PRICED', '1');
define('PRINT_KIT', '2');

define('PRICE_ALL', '0');
define('PRICE_KIT', '1');
define('PRICE_KIT_ITEMS', '2');`

**Comment by odiea** [comment]
The issue with the Items form is 'checked'=>$item_info->item_type === ITEM_KIT)
Should be 'checked'=>$item_info->item_type == ITEM_KIT)

**Comment by daN4cat** [comment]
@SteveIreland there is no FK in the tax part you added. I just added FKs to rewards.

**Comment by daN4cat** [comment]
@odiea so I need to fix that line in item form and you confirm it works fine

**Comment by odiea** [comment]
I can confirm the form shows properly but it still appears that it is not being taken out of Inventory after a Sale.

**Comment by odiea** [comment]
And after 3 Sales within the last 1/2 hr this is how the Items Inventory is showing.
![2017-08-07 12_57_04-wedidit _ powered by ospos 3 1 0](https://user-images.githubusercontent.com/10962177/29041430-10d94d26-7b70-11e7-9e39-e9a2e4354a4b.png)

**Comment by daN4cat** [comment]
It's all probably due to the === because of the replacement from '0' to const. In PHP === is not the same as == and therefore it checks that the type is exactly the label of the const no the value.

I need to fix that, not sure why it was used in the first place because it's not required.

**Comment by i92guboj** [comment]
@daN4cat , that's what I think. And, taking into account ONLY the behavior, just using the right type (that's defining the CONSTs as char '0' instead of int 0 fixes the issue in both the stock and the product form, though I don't claim that's the definitive fix.

I just say that if ($foo === '0') is plainly not the same than define('ZARRO', 0); if ($foo === ZARRO), as you very well said.

**Comment by daN4cat** [comment]
I fixed and it's in master. Please test and confirm it's all fine as I don't have time right now (dinner time....)

**Comment by daN4cat** [comment]
Thanks @odiea for the hint as that sped up the bug fixing.

**Comment by odiea** [comment]
Works now. Sometimes I can do the little stuff.

**Comment by daN4cat** [comment]
yes, just quickly tested and it's fine. However there is another bug in item_kits form. Fixing.

**Comment by daN4cat** [comment]
Fixed

**Comment by SteveIreland** [comment]
Geesh.  No one is leaving me anything to do.   I guess I'll just take a nap.

Good job folks.   Thanks.

**Comment by daN4cat** [comment]
@SteveIreland I leave the XAMPP issues to fix... gooooooood luuuck :-P

**Comment by daN4cat** [comment]
now dinner for me!

**Comment by i92guboj** [comment]
Thanks for the quick fix. It seems to be working so far. I have some other bug in between hands. But first let me iron it a bit.

That's for another issue. :)

**Comment by daN4cat** [comment]
Maybe you want to expand on the js error issue? When do you get it?

**Comment by i92guboj** [comment]
I can't reproduct that consistently, and it might be due to "external interferences", because I sometimes force the loading of this or that jquery version to test things in some other things I am developing.

That's why I didn't report. It might be entirely unrelated to ospos. If I ever find something consistent, I will open an issue about that.

I have some other ospos issue since some weeks ago, but I haven't had the time to look into it and it certainly isn't as severe as this one from yesterday. I am taking some time to see if I can narrow the issue a bit before opening the new issue.

I'll keep you informed ASAP.

Thanks for your interest and all your help :)
