### ISSUE TITLE
how to call item data array to register 

### ISSUE THREAD

**Issue by arrazka** [jekkos/opensourcepos#1452]
I planned adding  1 row to ospos_sales_items after print_option, I naming "currier" in register 
currier is form input text.

how to creat dropdown currier ?
currier [ DHL ]
           [ FEDEX ]
           [ UPS ]
how to save selected dropdown to ospos_sales_items row => currier
how to load currier when mode = return.

thannk

**Comment by daN4cat** [comment]
Just read the code and you'll find similar examples all over the place. That's the best help you can get.
