### ISSUE TITLE
Local Setup with docker

### ISSUE THREAD

**Issue by bill-goldberg** [jekkos/opensourcepos#1454]
do i need to download the zip from here for docker setup?
if wamp etc is installed then will it make an issue with docker setup?
do i need to locate any directory in docker cli ?

docker-compose build => successful
docker-compose up => Error

Can we see the build file location on windows?

**Comment by bill-goldberg** [comment]
do i need to use "docker-compose build" again when once done successfully?

**Comment by SteveIreland** [comment]
Docker creates a container with all of the required stuff installed according the rules of the High Sparrow of OSPOS.

If you are on Windows (as am I) then you'll have a steep learning curve to go through which I am going through myself today.  But Docker will not install your stuff into WAMP. 

If you want it running on WAMP then you might be better off using the download button and then running through the following steps.  This worked for me.  I don't know yet if the High Sparrow approves.  :-)


Change your current directory to root of unzipped download

Run the following commands
	• composer install
	• npm install
	• grunt --force

Change your current direct to go o the  bin subfolder
Run devinstall.sh

**Comment by daN4cat** [comment]
Docker installation on Windows was never tested, so @SteveIreland be the force with you and get it sorted!

**Comment by jekkos** [comment]
Seems to work ok as confirmed by @SteveIreland in the other issue. Will add the clause to ospos.js test file to have it fixed finally
