### ISSUE TITLE
Missing test/ospos.js

### ISSUE THREAD

**Issue by SteveIreland** [jekkos/opensourcepos#1455]
### Issue / Question / Bug

I downloaded the  file opensourcepos.20170807192313 and tried to run a docker-compose build on it and failed in step 12 with a missing test/ospos.js.

I also received an earlier error that required that I change the version number of docker-compose.yml from "2" to "2.1".

This my "return to the docker fold" attempt so be patient.  I'm running on Windows using Hyper-V so I have to work through all of what works and what doesn't.

```
Step 12/12 : RUN sed -i -e "s/\(localhost\)/web/g" test/ospos.js
 ---> Running in 6a540ccf7371
**sed: can't read test/ospos.js: No such file or directory**
ERROR: Service 'php' failed to build: The command '/bin/sh -c sed -i -e "s/\(localhost\)/web/g" test/ospos.js' returned
a non-zero code: 2
```

**Comment by jekkos** [comment]
Ok I thought I fixed that by adding existence check for that file

**Comment by SteveIreland** [comment]
Well, I was running on Windows 10 if that makes a difference.

I removed the statement, reran it and it built successfully and booted up with not problems.

**Comment by jekkos** [comment]
Great so works on Windows 10 then!

**Comment by daN4cat** [comment]
@SteveIreland is this issue fixed now?

**Comment by SteveIreland** [comment]
This issue is resolved.
