### ISSUE TITLE
Can't modify qty field when receiving (on row > 1)

### ISSUE THREAD

**Issue by i92guboj** [jekkos/opensourcepos#1457]
### Issue / Question / Bug

Before submitting an issue please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] I'm reporting an issue of an unmodified OSPOS installation
- [x] I checked open and closed issues database and no similar issue was already discussed (please make sure you searched!)
- [x] I read the README, WHATS_NEW and UPGRADE
- [x] I read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php-gd, php-intl, sockets and etc. installed)
- [x] I read the wiki
- [x] I ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql), and migrating function
- [x] I'm aware the latest master could be a development version and therefore not stable
- [x] I know the version of OSPOS and git commit hash (check the footer of your OSPOS), the name and version of OS, Web server, PHP and MySQL and will add them to my issue report

### Installation information

- OSPOS version is: 3.1.0
- OSPOS git commit hash is: 4f5ad57
- PHP version is:   5.6.31
- MySQL or MariaDB version is: mysql 5.6.36
- OS and version is:  gentoo 
- WebServer is:  2.4.27

### Expected behaviour

When entering new lines on reception/devolution/requisition, I expect to be able to manually modify the quantities on the quantity field.

### Actual behaviour

I can modify the quantity in the first row. But, after that, in the following rows, whatever quantity I enter is reset to 1 when I press enter.

**Some funny facts:**

- I can edit the first line I entered as many times as I wish, even before entering more rows.
- This affect all three receiving modes, but it doesn't affect the selling department. When selling, I can edit quantities without problems in any row.
- Funniest of all: when I erase the first line I entered, then I can freely edit all quantities in the rest of lines. Erasing any other line won't do. (This is what I've been doing to be able to work with this bug during the last few weeks).

I should truly take some kind of php debug course, some day. Suggestions welcome ;)

I've seen some commits in the past two months that are related to receiving quantities, maybe that's where it all started. Can't be sure.

But, I am fairly sure this worked some months ago, since there's a lot of stuff I deal with in batches of 6, 10, 12, etc. and I used a lot that qty-edit feature.

### Steps to reproduce the issue

1. Go into receiving mode
2. Receive something, modify qty, make sure it works
3. Receive some other line, modify qty, it should go back to 1
4. Receive yet one more line, modify qty, it should fail as well
5. Delete the first line you entered, modify qty in the other rows, be amused that it now works

**Comment by SteveIreland** [comment]
This is the same issue that I commented about on another issue.

It can be changed if you enter the quantity and then use the mouse to click on the update button.  But if you try to tab out of the quantity field then the quantity reverts back to the original value.

**Comment by i92guboj** [comment]
Thanks to you, I just discovered that button. Until one minute ago, I had no idea what that little wheel was for :rofl: 

Can you link your issue here? I searched but didn't find anything relevant, sorry if I duplicated the thing.

**Comment by i92guboj** [comment]
I think it might have something to do with the auto-submit "feature", which, by the way, I hate so so much.

I couldn't possibly imagine something that harms any more a POS system than something that makes you have to reach your mouse to be able to get to any arbitrary field. Effectively, this makes it impossible to reach any field at all using your keyboard because when skipping after modifying a field, it automatically gets you into the input ref field.

But it might be just me :tongue: 

In any case, this so called feature, works only sometimes. For example, try this:

1. Enter one line, go to qty, modify and TAB-skip, it works.
2. Enter another line, to to qty, modify and TAB-skip, it works but the qty resets to 1, as per the bug I described above.
3. Now, go back to the first line (the one at the bottom), modify qty, TAB-skip, and **it doesn't work** (it doesn't auto-submit this time).

That's why I think this two might be related. I might be entirely wrong, of course.

**Comment by SteveIreland** [comment]
The other two issues related to this is #1277 and #401 .  My comment was on the former.

**Comment by i92guboj** [comment]
Thank you so much. I will check those.

**Comment by daN4cat** [comment]
It should not be a big problem to solve by yourselves guys, once fixed go for a PR and I merge the change.

**Comment by daN4cat** [comment]
BTW #1199 capture all the improvement requests for Receivings and just in need of some love by somebody eager to get that part improved.

**Comment by odiea** [comment]
I'm a hack but this work around may work for you.
	
application/views/receivings/receiving.php comment out the following bottom line. You will then just press enter in the qty field after entering the new quantity and it should update the total.


/*$('[name="price"],[name="quantity"],[name="discount"],[name="description"],[name="serialnumber"]').change(function() {
		var index = $(this).parents("tr").index() - 1;
		$("#cart_" + index).submit();
	});*/

**Comment by i92guboj** [comment]
@odiea , yes, that makes it all work as it should. Turning off that auto-submit thing is a plus for me. Thanks!!

@daN4cat , I'd truly like to be able to fix this. I'll leave #1199 out until I can properly debug a simple thing like this :rofl:  

My problem is not that much with languages. I've used several dozens during my life and php is nothing special as long as you understand that's loosely typed; my "problem" is with the dynamics of web-based applications. I have no idea how to start debugging this nor which tools should I use, besides var_dump() and things like that. I can learn, no problem with that, it'll just takes time, because nowadays I no longer do programming for a living. So, I have to attend other tasks, and I develop only for myself and my business.

I am open to suggestions on what tools to use to debug this php/CI combo. I can do a decent work debugging in plain gdb or IDEs like qtcreator, but I have no idea what the equivalent would be for web applications to run step-by-step, set breakpoints, etc. (or if there's no equivalent and I need to change the procedure). If not, I'll just do whatever I can when I get the time to do it. :)

**Comment by daN4cat** [comment]
It's more add log points using error_log and read the error.log file :-)
Also use the Google inspector to read HTTP request and responses so you detect any PHP error that might not be printed directly in the html (e.g. modal dialog boxes).
When it comes to javascript, that's a different matter.

Alternative you can use some php debug tool. Can't remember the name from the top of my head but I'll look into it when at home.

However so far so good with the simplistic approach as I use my brain to reason on the action/reaction or cause/effect for some root cause analysis. But that's me...

To profile SQL there is a way to enable SQL tracing with a CI hook I've added so you can see queries and response time. So yet again another "read the log file" story.

**Comment by i92guboj** [comment]
I've found xdebug. There's a vim plugin for it.

I never grew fond on mastodontic IDEs such as eclipse or netbeans. There's a plethora of commercial ones which I won't even consider. The most complex thing I've used proficiently is qtcreator, and I used very concrete parts of it. I guess I just have to get the hang of it. Thanks for the pointers, they'll come in handy. :)

**Comment by jekkos** [comment]
There's the docker compose dev container that has xdebug configured on port 9000 by default.. but then you need to install docker daemon first :)
But then it should just be a matter of launching the container and attach to the process. I use intellij but maybe you don't like that ;)

**Comment by i92guboj** [comment]
I don't like or dislike containers, because they are just one more thing in my TODO list. So I don't have an opinion on them since I only know them by theory. I already have too much new things in this recipe and too little time to work on them.

I know that there's a docker container with ospos preconfigured. But I'll skip that for now, provided there's any other workable path, of course.

Thanks for the pointer though :)

**Comment by SteveIreland** [comment]
I went through the learning curve for Docker for Windows this week and was successful installing OSPOS using Docker, but when I tried to go beyond that to create a development environment I had nothing but problems.  I couldn't even get Docker to pull a basic MySQL as shown in many tutorials.   Because I hate to be defeated by software I'm sure I'll try it again the next time I need a change of pace, but for now I'll just stay with my safe and comfortable WAMP development environment.

**Comment by daN4cat** [comment]
Going back to the issue here, is @odiea patch the one you want to see applied to the code in master?

Comments please....

**Comment by i92guboj** [comment]
Well, that patch sorts **my problem** out.

However, it doesn't address the proper bug, which is the fact that ospos can't modify qty for any row!=1 with the current established autoapply behavior.

That patch serves a different purpose, which is disabling the autoapply feature altogether. That certainly fixes the other issue as a side effect, but changes how the program behaves, which might not be desiderable for everyone. It is desiderable for me, though. I'd even do the same for sales, as well, because this autosave/autoapply feature totally breaks the flow for me when I am entering "manual" lines. I have to pick the mouse one per each field I am going to modify, so, that could be four times if I want to modify discount, quantity and description (worst scenery, of course).

That'd be:

1. pick mouse, click qty
2. skip or enter or clic another field (it doesn't matter, since autosave will rip the focus out)
3. clic price, modify
4. wait for page to reload
5. clic disc, modify
6. wait for page to reload
7. clic desc, modify
8. wait for page to reload

Where it could be just

1. clic qty, modify
2. skip to next field, modify
3. skip to next field, modify
4. skip to next field, modify, enter to save, page reload just once

That's not the most common case, admittedly. But having to modify description and price is quite common for me. So that's still reloading the page two times and having to reach the mouse two times, when reloading once after having modified both fields would suffice. Being able to tab-skip between adjacent fields is a standard feature that even web browsers handle nicely enough. I have no idea why ospos does that differently because that behavior is specially useful in accounting and pos software...

Being that said, I am sure you did it that way for a reason, so I am no one to say what should be done, and I can easily live with that and just patch my local copy. And, in any case, I really doubt it's as simple as just commenting out that block of code. I am sure there will be side effects to consider and this would need some thinking and consideration.

In any case, the most common use case probably involves barcode reading and lines with qty=1, so most people won't even care one way or another.

That's just my view, of course.

**Comment by daN4cat** [comment]
OK, so there are still issues but I'm afraid I don't have time to look into this. Hopefully @jekkos or @SteveIreland can help.

**Comment by SteveIreland** [comment]
I've submitted a pull request that seems to fix this issue.  However, it applies the same solution that is being used for sales.  I figured that's good enough to get this release out the door,

However, I'd like to propose that we add a configuration option for the next release that allows the installer to disable immediate updates for sales and receiving.

**Comment by daN4cat** [comment]
Fix is now in master.

The other point about refresh or not is for a new issue
