### ISSUE TITLE
Unable to load the requested language file: language/indonesian/form_validation_lang.php

### ISSUE THREAD

**Issue by arrazka** [jekkos/opensourcepos#1458]
when setting language to Indonesia in store config : 
localisation : id_ID
cuntry code : id
language ; Indonesia ..

save config ....

than logout ... 

login --> username and password ---> Go 

get error : 

Unable to load the requested language file: language/indonesian/form_validation_lang.php

**Comment by daN4cat** [comment]
Have you downloaded the zip from Github master or pulled the code?

**Comment by arrazka** [comment]
opensourcepos.20170805225340.zip

**Comment by daN4cat** [comment]
Strange, the issue you face is due to code igniter language being missing

**Comment by daN4cat** [comment]
It should be part of the zip buy I can't check that until this evening.

**Comment by daN4cat** [comment]
Is this still an issue @odiea ?

**Comment by daN4cat** [comment]
Ok, I saw #1480

**Comment by daN4cat** [comment]
@arrazka try again in 5/10 min taking the last build from bintray.

**Comment by guillermohaad** [comment]
thank @daN4cat ,
Again download the .zip  opensourcepos.20170818140959.HEAD.92f626.zip , I will install only modifying the database.php with the credentials and follows the same error: Unable to load the requested language file: language / spanish / form_validation_lang.php
Note: I have not changed the default language as it comes.

**Comment by odiea** [comment]
Downloaded opensourcepos.20170820161342.master.5dd7a5.zip and still cannot find language files other then English. I tested with Spanish.

**Comment by jekkos** [comment]
Hm so they are then in the end? Will check but it seemed that I couldn't install them in Travis for some reason

**Comment by odiea** [comment]
![2017-08-21 12_37_36-es](https://user-images.githubusercontent.com/10962177/29533111-971cd3dc-866d-11e7-8761-0af4f2f6d4fc.png)

**Comment by jekkos** [comment]
So the files are there in fact!

**Comment by daN4cat** [comment]
but what about the code igniter ones?

**Comment by odiea** [comment]
Looking back in previous installs the codeigniter only contained the english language same as this one.

**Comment by odiea** [comment]
Good catch.
Current version.
![2017-08-21 14_44_47-language](https://user-images.githubusercontent.com/10962177/29537601-8ff2615a-867f-11e7-917b-451abaf8142b.png)
Previous Version.
![2017-08-21 14_45_43-language](https://user-images.githubusercontent.com/10962177/29537623-9f6b07b8-867f-11e7-8d67-95ce97b1bc02.png)

**Comment by odiea** [comment]
I copied all the folders from the old version into the current version and languages appear to be working properly now.

**Comment by daN4cat** [comment]
Yep, that's the problem everybody is reporting. Something it's still not right.

**Comment by odiea** [comment]
In the github repository it appears that the vendor folder is missing and that is where the codigniter language files are. The vendor folder does show in the new zip files?

**Comment by odiea** [comment]
opensourcepos.20170822070231.master.69b687.zip does not contain the language files.

**Comment by jekkos** [comment]
I'll have to try and install language  files with plain unix commands, will give that another shot later today

**Comment by jekkos** [comment]
Should be fixed now

**Comment by odiea** [comment]
No problem selecting a language now that it is in it's proper location.

**Comment by daN4cat** [comment]
@arrazka can you please check with the latest bintray zip file and see if everything works fine with your selected language?

**Comment by jekkos** [comment]
Ok would be good to have confirmation so we can close

**Comment by daN4cat** [comment]
@arrazka ?
