### ISSUE TITLE
The interface is messy

### ISSUE THREAD

**Issue by lorenzadam** [jekkos/opensourcepos#1459]
### Issue / Question / Bug

Before submitting an issue please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] I'm reporting an issue of an unmodified OSPOS installation
- [x] I checked open and closed issues database and no similar issue was already discussed (please make sure you searched!)
- [x] I read the README, WHATS_NEW and UPGRADE
- [x] I read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php-gd, php-intl, sockets and etc. installed)
- [x] I read the wiki
- [] I ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql), and migrating function
- [x] I'm aware the latest master could be a development version and therefore not stable
- [x] I know the version of OSPOS and git commit hash (check the footer of your OSPOS), the name and version of OS, Web server, PHP and MySQL and will add them to my issue report

### Installation information

- OSPOS version is: 3.1.0
- OSPOS git commit hash is: 4f5ad57
- PHP version is:   7.1.1
- MySQL or MariaDB version is:   (10.1.21-MariaDB)
- OS and version is:   Fedora 25
- WebServer is:   Apache/2.4.25
- (If applicable) Installation package for the LAMP/LEMP stack is:   XAMPP 7.1.1

### Expected behaviour
Interface should be fine 

### Actual behaviour
interface is messy

### Steps to reproduce the issue
do a git clone, edit application/database.php and public/.htaccess (following the README)

**Comment by odiea** [comment]
The new zip files are accessible from the readme Local install. This Git Clone repo needs more programming tools to work properly.

**Comment by lorenzadam** [comment]
Sorry my fault
Thank @odiea , i'll try to install from zip files :D

**Comment by daN4cat** [comment]
To be honest I didn't get the point behind the title of this issue. Which interface? Anyway, closed...
