### ISSUE TITLE
Slow Performance while starting the application

### ISSUE THREAD

**Issue by bill-goldberg** [jekkos/opensourcepos#1460]
### IMPORTANT IMPORTANT IMPORTANT

1. Chose what you want to report between the sections "New Feature / Enhacement" and "Issue / Question / Bug".
2. Remove just the one of the two sections you don't need 
3. Remove this section as it's just a guideline
4. Fill in all the details as requested by the section you chose

If you remove the complete template when submitting a Bug your issue will be closed as we cannot help without basic information.

### New Feature / Enhacement

*For New Features or Enhacements please clearly write your proposal.
It's important to state whether you expect the community to implement it or you will contribute the work.
Please bear in mind that we will implement new features only on the current code, there is no support for older versions.*

### Issue / Question / Bug

Before submitting an issue please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] I'm reporting an issue of an unmodified OSPOS installation
- [x] I checked open and closed issues database and no similar issue was already discussed (please make sure you searched!)
- [x] I read the README, WHATS_NEW and UPGRADE
- [x] I read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php-gd, php-intl, sockets and etc. installed)
- [x] I read the wiki
- [x] I ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql), and migrating function
- [x] I'm aware the latest master could be a development version and therefore not stable
- [x] I know the version of OSPOS and git commit hash (check the footer of your OSPOS), the name and version of OS, Web server, PHP and MySQL and will add them to my issue report

### Installation information
OS : Windows 10 x64
WAMP 2.5 x64
Apache 2.4.9
PHP 5.5.12
MySQL 5.6.17

- OSPOS version is: latest
- OSPOS git commit hash is: 
- PHP version is:   (e.g. 5.5, 5.6, 7.0, 7.1)
- MySQL or MariaDB version is:   (e.g. MySQL 5.5, MySQL 5.6, MySQL 5.7, MariaDB 10.0, MariaDB 10.1, MariaDB 10.2)
- OS and version is:   (e.g. CentOS 6.9, Ubuntu 16.4, Windows 10)
- WebServer is:   (e.g. Apache 2.2, Apache 2.4, Nginx 1.12, Nginx 1.13)
- (If applicable) Installation package for the LAMP/LEMP stack is:   (e.g. WAMP, XAMPP)

**Comment by bill-goldberg** [comment]
i am using this application on my localhost setup. but now this application takes about 1 min when i open the url localhost/opensourcepos.
Any idea what is taking time to load. and how can i improve this from 1 min to few milliseconds

**Comment by bill-goldberg** [comment]
i have a laptop with windows 10 x32 , RAM 2GB, HDD 250GB, CPU i3 1.8GHz.
Is there anything which can be removed from the opensourcepos.js file? to improve performance.

**Comment by bill-goldberg** [comment]
in header.php

<script src="bower_components/jquery/dist/jquery.js"></script>
		<script src="bower_components/jquery-form/jquery.form.js"></script>
		<script src="bower_components/jquery-validate/dist/jquery.validate.js"></script>
		<script src="bower_components/jquery-ui/jquery-ui.js"></script>
		<script src="bower_components/bootstrap/dist/js/bootstrap.js"></script>
		<script src="bower_components/bootstrap3-dialog/dist/js/bootstrap-dialog.min.js"></script>
		<script src="bower_components/jasny-bootstrap/dist/js/jasny-bootstrap.js"></script>
		<script src="bower_components/smalot-bootstrap-datetimepicker/js/bootstrap-datetimepicker.min.js"></script>
		<script src="bower_components/bootstrap-select/dist/js/bootstrap-select.js"></script>
		<script src="bower_components/bootstrap-table/src/bootstrap-table.js"></script>
		<script src="bower_components/bootstrap-table/dist/extensions/export/bootstrap-table-export.js"></script>
		<script src="bower_components/bootstrap-table/dist/extensions/mobile/bootstrap-table-mobile.js"></script>
		<script src="bower_components/moment/moment.js"></script>
		<script src="bower_components/bootstrap-daterangepicker/daterangepicker.js"></script>
		<script src="bower_components/file-saver.js/FileSaver.js"></script>
		<script src="bower_components/html2canvas/build/html2canvas.js"></script>
		<script src="bower_components/jspdf/dist/jspdf.min.js"></script>
		<script src="bower_components/jspdf-autotable/dist/jspdf.plugin.autotable.js"></script>
		<script src="bower_components/tableExport.jquery.plugin/tableExport.min.js"></script>
		<script src="bower_components/chartist/dist/chartist.min.js"></script>
		<script src="bower_components/chartist-plugin-axistitle/dist/chartist-plugin-axistitle.min.js"></script>
		<script src="bower_components/chartist-plugin-pointlabels/dist/chartist-plugin-pointlabels.min.js"></script>
		<script src="bower_components/chartist-plugin-tooltip/dist/chartist-plugin-tooltip.min.js"></script>
		<script src="bower_components/chartist-plugin-barlabels/dist/chartist-plugin-barlabels.min.js"></script>
		<script src="bower_components/remarkable-bootstrap-notify/bootstrap-notify.js"></script>
		<script src="bower_components/js-cookie/src/js.cookie.js"></script>
		<script src="bower_components/blockUI/jquery.blockUI.js"></script>
		<script src="bower_components/bootstrap-tagsinput/dist/bootstrap-tagsinput.js"></script>

are loading while all these are present in opensourcepos.min.js
Can we improve some speed issues by loading only opensourcepos.min.js file?

**Comment by daN4cat** [comment]
Those are not loaded unless you are in debug mode. Please read the PHP code too....

**Comment by daN4cat** [comment]
And WRT js you are focusing on stuff before having an understanding of where the bottleneck is...

**Comment by daN4cat** [comment]
BTW windows 10 and 2GB... not sure that's flying. Have you checked the memory usage?

**Comment by bill-goldberg** [comment]
ok. I have setup this application to my other laptops and they are with 4-8GB RAM and about 3 Ghz CPU .
But still it takes 5-10 seconds when i hit enter after writing url in the address bar.
It should not take more than 500 milliseconds to open up the application once the user hit the enter button or after clicking the bookmark shortcut.

**Comment by daN4cat** [comment]
I run OSPOS on a dual core 2.2GHz, 2Gb VPS with Linux CentOS on the other side of the Atlantic and the login to home page takes < 2s. But that's just running the web server shared with other Web services I'm running.

**Comment by daN4cat** [comment]
So, it's your machine and OS of choice the issue. I would use Linux to get better performance.

**Comment by daN4cat** [comment]
Loading on min.css and min.js is 100ms in total.

**Comment by daN4cat** [comment]
As you can see it's a red herring.

Check with Chrome inspector the timings.

**Comment by bill-goldberg** [comment]
Can you show me the screenshot of Chrome inspector in case of your machine ?

**Comment by bill-goldberg** [comment]
i will compare it with mine.

**Comment by jekkos** [comment]
It could be your internet connection..
Think we are fetching one resource from a cdn check chrome inspector for load times

If it's a server side delay then maybe try to disable statistics

**Comment by bill-goldberg** [comment]
![chrome_ttfb](https://user-images.githubusercontent.com/23611136/29238485-3164bc50-7f54-11e7-8b12-0d84f64c7ac6.jpg)

**Comment by bill-goldberg** [comment]
See how much time it is taking to get the response from the server. Its on localhost [Wamp]

**Comment by daN4cat** [comment]
iPOS,  interesting, I thought we were talking of OSPOS....

**Comment by bill-goldberg** [comment]
i just changed the logo.png what is wrong in this?
