### ISSUE TITLE
when I install source code and visite local site then can see  "You do not have permission to access the module named sales"

### ISSUE THREAD

**Issue by mickymartin** [jekkos/opensourcepos#1463]
thanks for share the source code.
I found resolve oneself.
there is issue at database.sql and instead to table.sql then complate.

**Comment by daN4cat** [comment]
Check under employee and employee edit form the permissions, enable the right permissions to the user with the problem.

**Comment by mickymartin** [comment]
ok! thanks for your help.
I added item in Grunt table then my site can work right away.
