### ISSUE TITLE
Import Items from CSV , importing quantities as 0

### ISSUE THREAD

**Issue by nenuchand** [jekkos/opensourcepos#1469]
### Issue / Question / Bug

- [x] I'm reporting an issue of an unmodified OSPOS installation
- [x] I checked open and closed issues database and no similar issue was already discussed (please make sure you searched!)
- [x] I read the README, WHATS_NEW and UPGRADE
- [x] I read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php-gd, php-intl, sockets and etc. installed)
- [x] I read the wiki
- [] I ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql), and migrating function
- [x] I'm aware the latest master could be a development version and therefore not stable
- [x] I know the version of OSPOS and git commit hash (check the footer of your OSPOS), the name and version of OS, Web server, PHP and MySQL and will add them to my issue report

### Installation information

- OSPOS version is: 3.1.0
- OSPOS git commit hash is: 4f5ad57
- PHP version is:   5.6.30
- MySQL or MariaDB version is:  MariaDB 10.1.21
- OS and version is:   Windows 10
- WebServer is:   Apache/2.4.25 
- (If applicable) Installation package for the LAMP/LEMP stack is: XAMPP

### Expected behaviour

The import from CSV quantities should pick the quantities specified in the csv file 
### Actual behaviour
The quantities are getting imported as 0
![image](https://user-images.githubusercontent.com/20229260/29249017-46721fa2-8044-11e7-9aee-abbde28dce0a.png)
But quantity is 100
![image](https://user-images.githubusercontent.com/20229260/29249023-6d2d04e0-8044-11e7-9f53-74d0cd26c100.png)

### Steps to reproduce the issue
1.Use the default import.csv template .
2.Import items from CSV

**Comment by SteveIreland** [comment]
Okay, thanks for providing the additional information.  Since it seems (based on your comments) that you are actually upgrading from a previous database then there are numerous potential issues.

Have you tried it using a a database created with the database.php script?  If it works with a non upgraded database then we can isolate the problem to an upgrade issue.

**Comment by nenuchand** [comment]
Its a database created  from the database.sql script, its not an upgraded database.

**Comment by SteveIreland** [comment]
Okay I misunderstood.  Then I'll create a fresh database using the database.php script and try it again myself,

**Comment by odiea** [comment]
@SteveIreland  I just checked in the new zip file and the csv files are no longer in the main directory. Is it being stored somewhere else now?

**Comment by SteveIreland** [comment]
Okay, I created a "clean" database and tried the import again.  As you can see it worked.  I didn't make any other configuration changes first.  I deleted the database, recreated it using the database.php script, and then imported the item CSV file.  (I added a second item to the import file just to make sure that it would at least add two items in a row).

![image](https://user-images.githubusercontent.com/23066623/29250877-5e03474e-8018-11e7-8ca2-bc963ba99335.png)

**Comment by SteveIreland** [comment]
@odiea they are still there in the root folder of the zip I downloaded yesterday around 6:00 PM EST.  I'll download it again to confirm they are still there.

**Comment by odiea** [comment]
It appears in the github version but not the new unstable versions. Sorry I did not state that earlier.

**Comment by odiea** [comment]
![2017-08-13 09_24_52-opensourcepos 20170813073406 zip](https://user-images.githubusercontent.com/10962177/29250965-5d09034c-8009-11e7-9437-92a67f0158e6.png)

**Comment by SteveIreland** [comment]
So they didn't magically appear after you ran `docker-compose build`?

**Comment by odiea** [comment]
I have not had to run docker on the unstable builds to get them to work.

**Comment by SteveIreland** [comment]
Interesting.  I had to run docker-compose to get those artifacts installed when I was exploring the docker approach but I'm still trying to sort out the impact of this new process.  I'm now getting a folder called node_modules which has a ton of stuff that I don't believe is necessary for execution but it is a LOT of baggage.

**Comment by odiea** [comment]
@daN4cat or @jekkos  Shouldn't the csv files be included in the new unstable zip builds?

**Comment by jekkos** [comment]
Yes they might be missing, will add them again

**Comment by SteveIreland** [comment]
I downloaded a fresh "unstable" build and ran docker-compose build on it and they were still missing.  So @odiea you were right again. :-)

**Comment by jekkos** [comment]
Also node_modules is needed for grunt to work, in fact it's based on npm package..

**Comment by SteveIreland** [comment]
Okay, thanks.   I believe somewhere in my docker explorations I must have triggered a feature of PHPStorm that exposed that folder so that it appears in my IDE even though it's not in the repository.

**Comment by SteveIreland** [comment]
Back to the original issue, @nenuchand did you change any configuration settings before attempting the import?

**Comment by daN4cat** [comment]
@nenuchand any update?
