### ISSUE TITLE
How to split line company name and company address of customer?

### ISSUE THREAD

**Issue by sarulyos** [jekkos/opensourcepos#1470]
How to split line company name and company address of customer?
![capture1](https://user-images.githubusercontent.com/30383907/29251106-b05c8fbc-8079-11e7-947e-6f0a86e9850e.PNG)
![capture2](https://user-images.githubusercontent.com/30383907/29251107-b063809c-8079-11e7-9695-b4516ae8585c.PNG)

**Comment by daN4cat** [comment]
Customer has already an address, the name of the person is just an "attention to" in that case.
Also you could consider invoices for that case instead of normal receipt. Having full company name is more an invoice case to me.
