### ISSUE TITLE
Issue   OSPOS 3.1.0 /items  modal empty window

### ISSUE THREAD

**Issue by ldchino** [jekkos/opensourcepos#1472]
### Issue / Question / Bug

- [x] I'm reporting an issue of an unmodified OSPOS installation
- [] I checked open and closed issues database and no similar issue was already discussed (please make sure you searched!)
- [x] I read the README, WHATS_NEW and UPGRADE
- [x] I read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php-gd, php-intl, sockets and etc. installed)
- [x] I read the wiki
- [] I ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql), and migrating function
- [] I'm aware the latest master could be a development version and therefore not stable
- [] I know the version of OSPOS and git commit hash (check the footer of your OSPOS), the name and version of OS, Web server, PHP and MySQL and will add them to my issue report

### Installation information

- OSPOS version is: 3.1.0
- OSPOS git commit hash is: 
- PHP version is: 7.0
- MySQL or MariaDB version is:MariaDB 10.1
- OS and version is:   (Linux d85cd8b56911 4.4.0-79-generic #100-Ubuntu SMP Wed May 17 19:58:14 UTC 2017 x86_64 GNU/Linux)
- WebServer is:   (Apache 2.4)

### Expected behaviour

I enter into Item option from the menu

### Actual behaviour

![captura de pantalla 2017-08-15 a las 6 46 19 p m](https://user-images.githubusercontent.com/31052757/29342862-a06eef6a-81ea-11e7-944c-5a6a4e9e0429.png)

### Steps to reproduce the issue
login and then click into items option

**Comment by daN4cat** [comment]
Which language are you using?

**Comment by ldchino** [comment]
Hi, I am using Spanish... In the version in english Is working fine...

**Comment by daN4cat** [comment]
OK, so probably we need help with few missing Spanish translations.

@jekkos are all the latest strings in Weblate and viceversa? Because checking Weblate Spanish is 100% translated.

If that's not the issue then it must be something weird in a translation string.

BTW, here how to help with translations: https://github.com/jekkos/opensourcepos/wiki/Adding-translations

**Comment by daN4cat** [comment]
@ldchino please  try again in 5/10 min taking the last build from bintray. There was an issue with translations.
