### ISSUE TITLE
Unaligned view of all views

### ISSUE THREAD

**Issue by lokesh-sg** [jekkos/opensourcepos#1474]
### IMPORTANT IMPORTANT IMPORTANT

1. Chose what you want to report between the sections "New Feature / Enhacement" and "Issue / Question / Bug".
2. Remove just the one of the two sections you don't need 
3. Remove this section as it's just a guideline
4. Fill in all the details as requested by the section you chose

If you remove the complete template when submitting a Bug your issue will be closed as we cannot help without basic information.

### New Feature / Enhacement

*For New Features or Enhacements please clearly write your proposal.
It's important to state whether you expect the community to implement it or you will contribute the work.
Please bear in mind that we will implement new features only on the current code, there is no support for older versions.*

### Issue / Question / Bug

Before submitting an issue please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [yes] I'm reporting an issue of an unmodified OSPOS installation
- [yes] I checked open and closed issues database and no similar issue was already discussed (please make sure you searched!)
- [yes] I read the README, WHATS_NEW and UPGRADE
- [yes] I read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php-gd, php-intl, sockets and etc. installed)
- [yes] I read the wiki
- [no] I ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql), and migrating function
- [yes] I'm aware the latest master could be a development version and therefore not stable
- [yes] I know the version of OSPOS and git commit hash (check the footer of your OSPOS), the name and version of OS, Web server, PHP and MySQL and will add them to my issue report

### Installation information

- OSPOS version is: 3.1.0 
- OSPOS git commit hash is: - 4f5ad57
- PHP version is:   (e.g. 5.5, 5.6, 7.0, 7.1) 5.6.24
- MySQL or MariaDB version is:   (e.g. MySQL 5.5, MySQL 5.6, MySQL 5.7, MariaDB 10.0, MariaDB 10.1, MariaDB 10.2) MySQL Version:   5.7.14
- OS and version is:   (e.g. CentOS 6.9, Ubuntu 16.4, Windows 10) : Windows 10
- WebServer is:   (e.g. Apache 2.2, Apache 2.4, Nginx 1.12, Nginx 1.13) Apache Version: 2.4.23
- (If applicable) Installation package for the LAMP/LEMP stack is:   (e.g. WAMP, XAMPP)

### Expected behaviour
Expected to be as how the creator made this project.

### Actual behaviour
Please look at the attached image. Every icon and all stuffs in page is un aligned.
![2017-08-16_15-42-18](https://user-images.githubusercontent.com/13021597/29358696-8cd91336-8299-11e7-9ab8-e73c1050caa3.png)

**Comment by daN4cat** [comment]
Download the zip file from bintray. See ReadMe

**Comment by lokesh-sg** [comment]
Based on ReadMe file have installed. This is what it happens have tried to setup multiple times as fresh setup. Everytime its the same.

**Comment by lokesh-sg** [comment]
Version 3.0.2 is working with the same setup. But there are other issues in 3.0.2 Items pages doesn't display any items and Tax value updated in store config is not getting pushed to DB and under reports Detailed reports are not getting generated. I guess all these happens due to MySQL 5.7. Please clarify

**Comment by daN4cat** [comment]
Yes, MySQL5.7 is not supported in 3.0.2
