### ISSUE TITLE
Loss of styling with newest version

### ISSUE THREAD

**Issue by lkwetter** [jekkos/opensourcepos#1475]
### Issue / 
I had a version downloaded at the end of July 17 and installed with xampp that was working great except for the tax rounding display issue mentioned a few days ago. So, I decided to get the latest version, but now it seems to have no styling at all. Everything displays in a line down the side. 

What am I missing here? 
I thought this would be as simple as the first set-up.

### Expected behaviour
Pretty display of icons across the top

### Actual behaviour
Apparent no styling at all

### Steps to reproduce the issue
Fresh install of latest version.

**Comment by odiea** [comment]
Local install is where the newest releases are install unless you have all the necessary tools for thee old github clone or download.

Dowload the latest stable release from github or unstable build from bintray
Create/locate a new mysql database to install open source point of sale into
Execute the file database/database.sql to create the tables needed
unzip and upload Open Source Point of Sale files to web server
Modify application/config/database.php and modify credentials if needed to connect to your database
Modify application/config/config.php encryption key with your own
Go to your point of sale install public dir via the browser
LOGIN using
username: admin
password: pointofsale

**Comment by lkwetter** [comment]
Thanks, I ended up doing getting the stable release. Works

**Comment by Sleepybear** [comment]
I am having this problem with the most recent stable release

> Local install is where the newest releases are ready for install unless you have all the necessary tools for the old github clone or download.
> 
> Download the latest stable release from github or unstable build from bintray
> Create/locate a new mysql database to install open source point of sale into
> Execute the file database/database.sql to create the tables needed
> unzip and upload Open Source Point of Sale files to web server
> Modify application/config/database.php and modify credentials if needed to connect to your database
> Modify application/config/config.php encryption key with your own
> Go to your point of sale install public dir via the browser
> LOGIN using
> username: admin
> password: pointofsale

I am having this issue after doing a clean install of the latest stable build of 3.3.4. There is no styling done at all, and I am not sure what I am missing. 

Here is info from the config page: 
```Extensions & Modules:
» GD: Enabled ✓
» BC Math: Enabled ✓
» INTL: Enabled ✓
» OpenSSL: Enabled ✓
» MBString: Enabled ✓
» Curl: Enabled ✓

User Configuration:
.Browser: Chrome
.Server Software: nginx/1.21.1
.PHP Version: 7.4.21
.DB Version: 5.5.5-10.6.3-MariaDB-1:10.6.3+maria~focal
.Server Port: 81
.OS: Linux 5.4.0-77-generic```

**Comment by daN4cat** [comment]
See #3246
