### ISSUE TITLE
Items Page show 'No Items to Display'

### ISSUE THREAD

**Issue by lokesh-sg** [jekkos/opensourcepos#1476]
### IMPORTANT IMPORTANT IMPORTANT

1. Chose what you want to report between the sections "New Feature / Enhacement" and "Issue / Question / Bug".
2. Remove just the one of the two sections you don't need 
3. Remove this section as it's just a guideline
4. Fill in all the details as requested by the section you chose

If you remove the complete template when submitting a Bug your issue will be closed as we cannot help without basic information.

### New Feature / Enhacement

*For New Features or Enhacements please clearly write your proposal.
It's important to state whether you expect the community to implement it or you will contribute the work.
Please bear in mind that we will implement new features only on the current code, there is no support for older versions.*

### Issue / Question / Bug

Before submitting an issue please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [yes] I'm reporting an issue of an unmodified OSPOS installation
- [yes] I checked open and closed issues database and no similar issue was already discussed (please make sure you searched!)
- [yes] I read the README, WHATS_NEW and UPGRADE
- [yes] I read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php-gd, php-intl, sockets and etc. installed)
- [yes] I read the wiki
- [no] I ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql), and migrating function
- [yes] I'm aware the latest master could be a development version and therefore not stable
- [yes] I know the version of OSPOS and git commit hash (check the footer of your OSPOS), the name and version of OS, Web server, PHP and MySQL and will add them to my issue report

### Installation information

- OSPOS version is:  3.0.2
- OSPOS git commit hash is: 4f5ad57
- PHP version is : 5.6.25
- MySQL or MariaDB version is: MySQL 5.7.14
- OS and version is:   Windows 10
- WebServer is:   Apache 2.4.23
- (If applicable) Installation package for the LAMP/LEMP stack is:   (e.g. WAMP, XAMPP)

### Expected behaviour
Items Page should display all added items.

### Actual behaviour
It doesn't show any items and says 'No items to display' even after changing dates.

### Steps to reproduce the issue
Click on Items
![firefox_2017-08-16_22-11-48](https://user-images.githubusercontent.com/13021597/29374849-869cceea-82d0-11e7-94cf-7ff3fd3d1623.png)

**Comment by odiea** [comment]
Yes. 3.0.2 does has no support for mysql 5.7.

**Comment by lokesh-sg** [comment]
So which version of mysql should I install, please

**Comment by odiea** [comment]
You can try 5.5 or 5.6.

**Comment by lokesh-sg** [comment]
I am getting 500 error if I use 5.6 if again move to 5.7 tool just works fine with the same issue. Could you please advise.

**Comment by lokesh-sg** [comment]
I am getting 500 error if I use 5.6 if again move to 5.7 tool just works fine with the same issue. Could you please advise.

**Comment by daN4cat** [comment]
Then use 3.1 as we are close to release it.
