### ISSUE TITLE
Weblate language not available

### ISSUE THREAD

**Issue by objecttothis** [jekkos/opensourcepos#1482]
### Issue / Question / Bug

Before submitting an issue please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] I'm reporting an issue of an unmodified OSPOS installation
- [x] I checked open and closed issues database and no similar issue was already discussed (please make sure you searched!)
- [x] I read the README, WHATS_NEW and UPGRADE
- [x] I read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php-gd, php-intl, sockets and etc. installed)
- [x] I read the wiki
- [x] I ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql), and migrating function
- [x] I'm aware the latest master could be a development version and therefore not stable
- [x] I know the version of OSPOS and git commit hash (check the footer of your OSPOS), the name and version of OS, Web server, PHP and MySQL and will add them to my issue report

### Installation information

- OSPOS version is: 3.1.0
- OSPOS git commit hash is: 
- PHP version is:   (e.g. 5.5, 5.6, 7.0, 7.1) 5.6.31
- MySQL or MariaDB version is:   (e.g. MySQL 5.5, MySQL 5.6, MySQL 5.7, MariaDB 10.0, MariaDB 10.1, MariaDB 10.2) 5.7
- OS and version is:   (e.g. CentOS 6.9, Ubuntu 16.4, Windows 10) FreeBSD 11.0
- WebServer is:   (e.g. Apache 2.2, Apache 2.4, Nginx 1.12, Nginx 1.13) Apache 2.4
- (If applicable) Installation package for the LAMP/LEMP stack is:   (e.g. WAMP, XAMPP) FAMP

### Expected behaviour
I created a weblate account to complete the Russian translation and submit the Azerbaijani translation that I have previously done but was never merged into the code.

### Actual behaviour
On the weblate opensourcepos project Azerbaijani is not a language that can be selected.  To be more specific this is az_AZ which is different from az_IR (southern Azerbaijani is the same language but written in Farsi script).  Is this a limitation of weblate (not offering Azerbaijani (Azərbaycanca) as a translateable language) or does it just need to be enabled for the project?  I noticed that the weblate interface offers Azerbaijani, just not the project.

**Comment by jekkos** [comment]
Hmm I'll see if I can add this exact language to our project. Of course we still need to map properly with CI language files (which afaik only mention languages wo locale)

**Comment by objecttothis** [comment]
@jekkos by far the most common is Northern Azerbaijani which is a latin-based script (was Cyrillic during the Soviet era), so az_AZ, azerbaijani, or az are just fine.  for the perspective of futureproofing the language translation aspect of ospos, it might be good to refactor the language references to include locale xx_YY where xx is language abbreviation and YY is the locale abbreviation.  British English and American English is a good example of the need in the app for locale to differentiate.

**Comment by jekkos** [comment]
Ok I've added southern Azerbaijani to the languages. I'll see if I can generate the template files already, but maybe we  better postpone a translation until after 3.1.

 Opinions ?

**Comment by objecttothis** [comment]
Do you mean northern Azerbaijani? Southern is Farsi script. Northern is what is spoken in Azerbaijan and it's in Latin script. That's the one we need. As for postponing, I think that's a good idea

**Comment by jekkos** [comment]
Yes I've created both. So you probably want az_AZ I suppose?

**Comment by jekkos** [comment]
Ok it's available in weblate now, you can start translating. Currently all the strings equal english. Maybe it doesn't really matter for me whether we include it in 3.1 or not as other languages are not alwyas completely translated

**Comment by objecttothis** [comment]
Ok I found the Azerbaijani project on the weblate instance but when I go to modify my profile to include Azerbaijani as a language I can translate so that it will show Azerbaijani in the list of strings it doesn't include that language. I think the possible languages in the profile might be a separate setting I. The config of weblate from the language projects.

**Comment by jekkos** [comment]
Hm I see it in the list of languages now and there's a translate button on it... which seems to work at first sight. But indeed you need to subscribe to the language so you will be pinged once new translations are needed :)

**Comment by jekkos** [comment]
Briefly rebuilding weblate indexes.. normally this should be run periodically but I haven't gotten any mail lately

**Comment by objecttothis** [comment]
Yeah az_AZ. I'll look into subscribing to the language and see if it shows me the strings then

**Comment by objecttothis** [comment]
Ok I was able to select Azerbaijani this time. Do you want to make a en_US distinction at this point so that I can start working on that or punt for now? That's also something that can wait for after 3.1.0

**Comment by jekkos** [comment]
Ok I'll configure it.. as you wish. We'll need to change some code to make it selectable in the config screen anyway. It contains some logic to map CI to our weblate translations..

**Comment by jekkos** [comment]
I've added both en_US and en_GB. Currently source language is still english (a third one). Then we'll have to check which will be the source language..

**Comment by objecttothis** [comment]
Super duper. I'll get cracking on Monday. Good night.

**Comment by daN4cat** [comment]
I assume I will need to review all the en_GB ones...
