### ISSUE TITLE
ReCaptcha keys required even when ReCaptcha is not enabled.

### ISSUE THREAD

**Issue by objecttothis** [jekkos/opensourcepos#1484]
### Issue / Question / Bug

Before submitting an issue please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] I'm reporting an issue of an unmodified OSPOS installation
- [x] I checked open and closed issues database and no similar issue was already discussed (please make sure you searched!)
- [x] I read the README, WHATS_NEW and UPGRADE
- [x] I read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php-gd, php-intl, sockets and etc. installed)
- [x] I read the wiki
- [x] I ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql), and migrating function
- [x] I'm aware the latest master could be a development version and therefore not stable
- [x] I know the version of OSPOS and git commit hash (check the footer of your OSPOS), the name and version of OS, Web server, PHP and MySQL and will add them to my issue report

### Installation information

- OSPOS version is:  opensourcepos.20170816205819.HEAD.767b0d
- OSPOS git commit hash is: 
- PHP version is:   (e.g. 5.5, 5.6, 7.0, 7.1) 5.6.31
- MySQL or MariaDB version is:   (e.g. MySQL 5.5, MySQL 5.6, MySQL 5.7, MariaDB 10.0, MariaDB 10.1, MariaDB 10.2) 5.7
- OS and version is:   (e.g. CentOS 6.9, Ubuntu 16.4, Windows 10) FreeBSD 11.0
- WebServer is:   (e.g. Apache 2.2, Apache 2.4, Nginx 1.12, Nginx 1.13) 2.4
- (If applicable) Installation package for the LAMP/LEMP stack is:   (e.g. WAMP, XAMPP) FAMP

### Expected behaviour
In Store Config->General I should be able to submit changes. ReCaptcha key fields should only be required if the ReCaptcha Login checkbox is checked.

### Actual behaviour
ECC is preventing changes if ReCaptcha keys aren't in place even if ReCaptcha login is unchecked.

**Comment by daN4cat** [comment]
I tested but it works fine:

![image](https://user-images.githubusercontent.com/636048/29473374-8ebca25a-844f-11e7-8e18-af57cedc7cdb.png)

**Comment by objecttothis** [comment]
I'll take a look at it.  @daN4cat what build did you test it in?  I'm getting the problem in 20170816205819.HEAD.767b0d.  I'll see if I can figure it out.

**Comment by daN4cat** [comment]
The latest code from master, which is the one in the last zip file. (not it should have master instead of HEAD in the zip name).

**Comment by objecttothis** [comment]
ok, I'll do a clean install with the latest master on Monday and see if I can figure out if it still happens in that build and if so what in my server stack is causing it, or if its something in the code interacting with the server stack differently than other servers.

**Comment by objecttothis** [comment]
Confirmed, this is not an issue in the latest master.  Possibly it was because I was using a HEAD release and not Master.  This issue can be closed... I don't seem to have permissions to do so myself.
