### ISSUE TITLE
Separate en_GB and en_US translations

### ISSUE THREAD

**Issue by objecttothis** [jekkos/opensourcepos#1485]
### New Feature / Enhacement

Currently it appears that the English translation is British English (based on the spelling of Localisation).  While not a big change, I think it would be fairly quick to complete a en_US translation.

Also, this is a separate issue but I notice that the Github issues template that is used misspells Enhancement as Enhacement.

### Installation information

- OSPOS version is: 3.1.0
- OSPOS git commit hash is: 4f5ad57
- PHP version is:   (e.g. 5.5, 5.6, 7.0, 7.1) 5.6.31
- MySQL or MariaDB version is:   (e.g. MySQL 5.5, MySQL 5.6, MySQL 5.7, MariaDB 10.0, MariaDB 10.1, MariaDB 10.2) 5.7
- OS and version is:   (e.g. CentOS 6.9, Ubuntu 16.4, Windows 10) FreeBSD 11.0
- WebServer is:   (e.g. Apache 2.2, Apache 2.4, Nginx 1.12, Nginx 1.13) Apache 2.4
- (If applicable) Installation package for the LAMP/LEMP stack is:   (e.g. WAMP, XAMPP) FAMP

**Comment by jekkos** [comment]
@daN4cat @odiea you don't seem to be that bothered by speaking one grand unified language? We could of course split out the two flavo(u)rs of english if there's enough motivation to do proper translating..

**Comment by odiea** [comment]
I certainly have had no issue. If someone wants to change a word or two I would suggest doing it locally.
Like Takings I use Daily Sales.

**Comment by daN4cat** [comment]
@jekkos is there any way in weblate to make a full copy of en into en_GB and en_US?
I don't fancy going through all the translations to do a 95% copy of it an 5% adjustment to British version (or at least what I understand of it as I'm not a native speaker neither).

**Comment by objecttothis** [comment]
I think the current English translation is British English, so it would just be minor changes to the en_US translation.  I'm OK, if people want to make the source language for future translations British English, but it would be nice for the translator to choose the source language.  For example, when I have my staff (who are native speakers) working on the Azerbaijani and Russian, they will have a better time if they can compare against the Russian when looking at Azerbaijani and vis a versa when looking at the Russian.

**Comment by daN4cat** [comment]
I don't have a problem with the en_GB and en_US, I just don't want to copy 1000 translation lines manually from en to the variants!
Actually the English translation is a mix up, because in British English there is no concept of ZIP code, it's Post Code. But OSPOS has ZIP code.
So indeed it's better to have the two translations done properly.

**Comment by objecttothis** [comment]
I concur.  Let's see if @jekkos can straight clone the English translation to en_GB and en_US so that someone more qualified than I can work on the British English (the best I can do is a bad British accent) while I work on the US English.  I'm guessing that it will be pretty quick, as there aren't going to be a large number of changes.

**Comment by jekkos** [comment]
Both are present in weblate now at least, so translation can start there. Both should be prefilled with existing English translations

**Comment by objecttothis** [comment]
@jekkos I started the en_US weblate but only the bootstrap_tables are there.  I could not find any other files to translate.  Also, could you look into pre-populating both the en_GB and en_US from data in the English source language?  This would make our work a lot easier.

**Comment by objecttothis** [comment]
The same appears to be true for Azerbaijani.  I only see the bootstrap_tables, but no others.

**Comment by jekkos** [comment]
OK I'll have a look tonight.

**Comment by daN4cat** [comment]
@jekkos any chance you manage to get this fixed? I just checked and en_GB has 0% translations .... ooops

**Comment by objecttothis** [comment]
@jekkos thanks for creating the rest of the tables for en_US and en_GB. When you get a chance could you do that for az_AZ  as well?

_Sent from my Android XT1575 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by jekkos** [comment]
Yes I know switched to another branch as I wanted to make en_US standard.. but not without hiccups

**Comment by objecttothis** [comment]
OK, I just went ahead and did the weblate translation for en_US.  It's completed.  I marked a few of them as needs review as there may be good reason to keep them one way.  Here are some examples:

- In the code giftcard is one word, but in US English Gift Card is always two words.
- Cost Price in US English is ambiguous because it is not clear if its the cost price for the customer or for the seller.  In US English the industry term is Wholesale Price.

Suggestions: For the most part I didn't change these because I wanted to see what the consensus was first.
- Our "error" reporting to the user uses differing formats in different parts of the translation.  For example in one place the message "Employee was unsuccessfully updated" but in other places it uses a format like "Items import failed".  There was one other format but I can't remember exactly.  My suggestion is that we use the same general error sentence structure across the board. "Employee was successfully updated" is completely correct but at least in American English we would understand "Employee was unsuccessfully updated" but we would never say it that way.  We would more likely say "Employee update failed"
- Translations that are complete sentences should use punctuation and only first letter of first word capitalized (as well as proper nouns). Currently most of them use multiple capitals throughout the sentence and no punctuation.

**Comment by objecttothis** [comment]
@jekkos, to clarify what I meant by copying over the translations from english to en_US and en_GB was to copy the weblate entries from source to en_US and en_GB.  Don't do en_US though because I just finished that one and it should be ready to put into the source.  I'm sure however @daN4cat would still appreciate populating weblate from english to en_GB.

**Comment by daN4cat** [comment]
Yep, en_GB is still empty. I cannot proceed.

**Comment by jekkos** [comment]
Ok just pulled in last changes from the repo, rebuilding indexes now, should be fine in a minute

**Comment by daN4cat** [comment]
@jekkos nothing on weblate....

**Comment by jekkos** [comment]
Things went awry after I renamed the language folder to be in line with the way we concatenate locale.. was trying to figure out how to fix that yesterday, en us changes are still in weblate but not available in the git

**Comment by jekkos** [comment]
Have to find a way to sync both again as the languages were created under the weblate convention which is en_US vs en-US

**Comment by jekkos** [comment]
Ok think I managed to recover for now, I pushed the work from weblate back now, but I should rename the language folder so we can

**Comment by daN4cat** [comment]
en_GB in weblate is still empty

**Comment by jekkos** [comment]
Translations are prefilled now in weblate..

**Comment by daN4cat** [comment]
I translated en_GB. I also updated some French translations but not completed all, and accepted some Portuguese (Brazilian) suggestions.

**Comment by SteveIreland** [comment]
I'm getting a bit confused so if someone can provide some clarity for me I would appreciate it.  In a recently pulled instance I have en, en-GB, en_US, and en-US.

I think en_US (with the underscore) was probably a mistake.

When I do development should I put my language text statements in en, en-GB, or en-US?  Which is home base?

**Comment by daN4cat** [comment]
en is the Base. BTW I should fix some sentences because during the en-GB translation I found out few mistakes

**Comment by daN4cat** [comment]
@jekkos could you please take Weblate translations and sync master with them?

**Comment by objecttothis** [comment]
Make sure not to overwrite en_US on weblate with either the weblate english or the current master english.  I made corrections and changes from British English when I finished the en_US translation on weblate.

**Comment by SteveIreland** [comment]
How come en_US is not en-US?

**Comment by objecttothis** [comment]
http://codel10n.com/what-is-correct-locale-tag-en_us-vs-en-us/

**Comment by SteveIreland** [comment]
Okay, so that wasn't particularly definitive.  So since both are "standard" then shouldn't we follow the naming convention which seems to already be in place for OSPOS which would be en-US?

**Comment by objecttothis** [comment]
what I gathered from the article is that for Unix POSIX and Java use underscore and for just about everything else use the hyphen

**Comment by SteveIreland** [comment]
But with an application that's deployed to both platforms it's not definitive.  And each browser seems to follow it's own set of conventions.  So I'm still leaning toward thinking the naming convention should be consistent across all languages files within the application.

**Comment by SteveIreland** [comment]
But since there isn't an en-TEXAS I really don't  have any skin in this game.  :-)

**Comment by objecttothis** [comment]
haha, yes voted the state most likely to secede 241 years in a row. we will have to work on that translation later. the standard has less to do with what platform it's deployed on and more to do with what language it's written in. I'm fine with either.

**Comment by jekkos** [comment]
Ok I pushed  latest weblate changes to this repository. So but languages are not yet selectable from the UI, so we still need a change for that. Also I'd have to reconfigure weblate to use en_US as the source language and get rid of  the plain en folder.

**Comment by daN4cat** [comment]
OK, now master contains the support for en-US and en-GB, with en-US being the default language.

Please note that I removed the en and en_US language folders.

@jekkos you need to switch weblate to use en-US as master language.

**Comment by daN4cat** [comment]
I tested a bit more and this seems to work fine with both: en_GB and en_US.

I believe we can close and leave the Weblate fix to @jekkos when he finds the time.
