### ISSUE TITLE
Timezone incorrect.

### ISSUE THREAD

**Issue by objecttothis** [jekkos/opensourcepos#1487]
### Issue / Question / Bug

Before submitting an issue please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] I'm reporting an issue of an unmodified OSPOS installation
- [x] I checked open and closed issues database and no similar issue was already discussed (please make sure you searched!)
- [x] I read the README, WHATS_NEW and UPGRADE
- [x] I read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php-gd, php-intl, sockets and etc. installed)
- [x] I read the wiki
- [x] I ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql), and migrating function
- [x] I'm aware the latest master could be a development version and therefore not stable
- [x] I know the version of OSPOS and git commit hash (check the footer of your OSPOS), the name and version of OS, Web server, PHP and MySQL and will add them to my issue report

### Installation information

- OSPOS version is: 3.1.0
- OSPOS git commit hash is: 4f5ad57
- PHP version is:   (e.g. 5.5, 5.6, 7.0, 7.1) 5.6.31
- MySQL or MariaDB version is:   (e.g. MySQL 5.5, MySQL 5.6, MySQL 5.7, MariaDB 10.0, MariaDB 10.1, MariaDB 10.2) 5.7
- OS and version is:   (e.g. CentOS 6.9, Ubuntu 16.4, Windows 10) FreeBSD 11.0
- WebServer is:   (e.g. Apache 2.2, Apache 2.4, Nginx 1.12, Nginx 1.13) Apache 2.4
- (If applicable) Installation package for the LAMP/LEMP stack is:   (e.g. WAMP, XAMPP) FAMP

### Expected behaviour
Store Config -> Localisation -> Timezone should have the option of Baku written as "(GMT+0400) Baku"

### Actual behaviour
Store Config -> Localisation -> Timezone incorrectly has the option of Baku written as "(GMT+0500) Baku"  A few years ago Azerbaijan changed their laws to no longer participate in daylight savings practices and therefore year-round is on GMT+4

**Comment by jekkos** [comment]
Ok fixed this in the latest master. I guess it was just the label not being correct. Most of the time logic is set in PHP itself (in which I hope it is properly maintained)
