### ISSUE TITLE
Missing additions to database update scripts

### ISSUE THREAD

**Issue by objecttothis** [jekkos/opensourcepos#1488]
### Issue / Question / Bug

Before submitting an issue please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] I'm reporting an issue of an unmodified OSPOS installation
- [x] I checked open and closed issues database and no similar issue was already discussed (please make sure you searched!)
- [x] I read the README, WHATS_NEW and UPGRADE
- [x] I read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php-gd, php-intl, sockets and etc. installed)
- [x] I read the wiki
- [x] I ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql), and migrating function
- [x] I'm aware the latest master could be a development version and therefore not stable
- [x] I know the version of OSPOS and git commit hash (check the footer of your OSPOS), the name and version of OS, Web server, PHP and MySQL and will add them to my issue report

### Installation information
- OSPOS version is: 3.1.0
- OSPOS git commit hash is:  4f5ad57 (latest master as of 8/19)
- PHP version is:   (e.g. 5.5, 5.6, 7.0, 7.1) 5.6.31
- MySQL or MariaDB version is:   (e.g. MySQL 5.5, MySQL 5.6, MySQL 5.7, MariaDB 10.0, MariaDB 10.1, MariaDB 10.2) 5.7
- OS and version is:   (e.g. CentOS 6.9, Ubuntu 16.4, Windows 10) FreeBSD 11.0
- WebServer is:   (e.g. Apache 2.2, Apache 2.4, Nginx 1.12, Nginx 1.13) 2.4
- (If applicable) Installation package for the LAMP/LEMP stack is:   (e.g. WAMP, XAMPP) FAMP

### Expected behaviour
Migration using scripts results in identical database structure and compatible data.

### Actual behaviour
One or more database changes are missing in the update scripts.  for example ospos_app_config is missing the number_locale key/value

### Steps to reproduce the issue
Migrate 2.0.2 to 3.1.0 using database update scripts

**Comment by objecttothis** [comment]
This may be a different issue, because when I look at firebug it shows me that /public/config/save_info/ is returning a HTTP 403 error and it isn't updating the database.  I'll see if I can sort out whether it's my configuration (mod_security, mod_evasive, suhosin and hardened php.ini).  Perhaps someone else can see if they can duplicate the issue on their end.  The hash is 4f5ad57

**Comment by daN4cat** [comment]
Yes, there should be a notification pop up when you submit something.

**Comment by objecttothis** [comment]
ok, i just disabled CSRF protection and it's working now.  I'm also noticing that the CSRF was preventing me from getting to the login screen when using HTTP (worked fine for HTTPS).  After disabling the CSRF in the opensourcepos config file I could get to the login screen but typing my username and password posts a redirect right back to the login screen with no message.  Firebug is showing me a HTTP 307 (temporary redirect) followed by HTTP 303 (Redirect) which explains why CSRF was freaking out.  I'm not sure why these redirects are not happening with HTTPS

**Comment by daN4cat** [comment]
Have you set .htaccess properly? It looks like something coming from a rule not set correctly.

**Comment by objecttothis** [comment]
I'm using the default .htaccess that came with the ospos build.  I'm thinking that this has to do with the security hardening I did on my server.  For example I added to httpd.conf

ServerTokens Full
ServerSignature Off
FileETag None
TraceEnable Off
Header edit Set-Cookie ^(.*)$ $1;HttpOnly;Secure
Header always append X-Frame-Options SAMEORIGIN
Header set X-XSS-Protection "1; mode=block"

which among other things is doing some csrf protection at the apache level.  I'll play around with it and see if I can get it working.  It does not appear that mod_security, mod_evasive or suhosin are causing the issue though.

**Comment by objecttothis** [comment]
As per the FAQ I updated the .htaccess in /public/ and that seems to have corrected the login issues, but I'm still working on the issues with updating.  When I disable the CSRF in config.php and comment out the security directives I now get the toast notification in store config but on Localisation it gives me a red toast notification saying that it was unsuccessful in updating the information.

**Comment by objecttothis** [comment]
OK, I narrowed it down to Store Config->Localisation.  I can successfully submit changes to every other tab in Store Config, but when I submit changes to the localisation tab it pops up a toast notification saying configuration saved unsuccessfully.

Here is the intl configuration from phpinfo, so that shouldn't be the issue.  Can anyone replicate on 3.1.0 hash 4f5ad57?

Internationalization support | enabled
-- | --
version | PECL-3.0.0
ICU version | 58.2
ICU Data version | 58.2

**Comment by jekkos** [comment]
Hm maybe try to debug or check what fails to save specifically, is there a db error message in the output for example? Also enabling display_errors in php ini can help to give more context

**Comment by daN4cat** [comment]
Yes this doesn't sound and usual issue. Also might be due to the database upgrade.

**Comment by objecttothis** [comment]
Good call.  I will make a separate clean install with a fresh database and that will eliminate or point to the database and potentially either leave my FAMP configuration or the software as the culprit.  I'm leaning toward the FAMP stack as the problem, but we will see.

**Comment by objecttothis** [comment]
OK, I installed the latest master on both my data-migrated database and on a clean database.  It saves fine in the clean database which tells me that there is a difference in database structures after running all the migration scripts.  I'll dig into what that was. 

However, I'm still having to turn off CSRF protection in both ospos instances to get it to save the data.  If I don't config/check_number_locale responds with a HTTP 403 (Forbidden).  This is either a problem with my server stack configuration, or with the code.  I'll keep investigating to see if I can figure out what in my configuration could be causing it as I've done a lot of hardening since my 2.0.2 install had been compromised on a shared server due to a lack of Cross Site Script filtering and no CSRF protection on that version.

**Comment by objecttothis** [comment]
ok, I figured it out.  number_locale key/value does not exist in my ospos_app_config table which likely means that whenever it was introduced it was not added to the database update script.  I confirmed this by doing a grep search for number_locale in all the database update scripts and it didn't appear. I looked at the change log in WHATS_NEW.txt and it appears that this functionality may have been added in the 2.3.3 release.  Can someone confirm that?  If so, we will need to update the 2.3.2_to_2.3.3.sql to include adding the missing key/values.  I don't know what other values are missing but I will run a comparison between my migrated data (that I applied all the scripts to) and the clean install data to see what else I can find.  Perhaps someone who can see the commits can look at what key/values were added with that release so that we can add them to the database upgrade file.

**Comment by objecttothis** [comment]
OK, I ran `SELECT `key` FROM pos_dev.ospos_app_config WHERE `key` NOT IN (SELECT `key` FROM pos_alpha.ospos_app_config)` and here are all the keys that appear in the current master of the ospos_app_config table but are not added by database migration scripts.  If I could get some help with identifying at what milestone they were added, I can submit a pull request and update the code myself to make sure they get added at the right milestone.

cash_rounding_code
currency_decimals
default_tax_category
msg_msg
msg_pwd
msg_src
msg_uid
number_locale
quantity_decimals
tax_decimals
thousands_separator

**Comment by objecttothis** [comment]
Also, the reverse MySQL query shows me which key/values were removed or renamed.  We need to figure out at what point this happened to also remove them in the database scripts.  Perhaps if someone can give me access to view commit history I can do the research on it since I probably have the most vested interest in correcting it.

The following were all deleted or renamed in ospos_app_config
default_tax_1_name
default_tax_1_rate
default_tax_2_name
default_tax_2_rate
dinner_table_enable
print_after_sale
smtp_host
smtp_pass
smtp_user

**Comment by daN4cat** [comment]
Have you run the migration from OSPOS itself?

**Comment by daN4cat** [comment]
With regards to msg and smtp pairs, those are optional and saved when you enable them and save in the Store Config. Not everything is really required and the code is protected from NULL row entries in those cases.

**Comment by objecttothis** [comment]
I had not because it was not listed in the /UPGRADE.txt file.  I ran it after seeing your post and it had no bearing on the missing/deleted app_config rows.  I am not yet familiar with the in-app migration functionalities workings but it would be nice to put the contents of all the migration scripts in the /database/ folder into that functionality and have it autodetect the previous version.

**Comment by daN4cat** [comment]
It's not a straight upgrade, that's why @SteveIreland has done it that way. It's related to the tax change. He can explain more. But good point about the missing step in the upgrade instructions.

**Comment by daN4cat** [comment]
With regards to the other config pairs I'll check later what's missing and add it to the upgrade scripts.

**Comment by SteveIreland** [comment]
The migration is about populating the `sales_taxes` table and updating the `tax_type` and `item_tax_amount` field on the `sales_Items_taxes` table.

The background on this is that I needed a place to store general sales tax amounts and and the detail tax amounts used to compute them.

When taxes are calculated at the item level there is often a rounding challenge that is introduced due to needing to calculate taxes at a higher precision at the item level and I bypassed that by storing the tax amounts to be collected on the sales_taxes table.

Operationally this achieved what was needed, but then it introduced the obvious problem of the tax amounts for current reports (where sales tax is always reported at the item level) not balancing to the the actual sales tax that was collected.  I don't believe this is an issue for VAT tax installations, but it might be for customer based sales tax installations .... thus the migration. 

I'll need to check to see if it was ever merged but I know I submitted at least once a fix for the sales tax reports to use the new fields.  But I know I ever came back to change the detail reports to use the `sales_taxes` tax amount for the invoice summary.  I'm sure it is still a total of the line item tax amounts.  Every time I looked at it I was wishing for more denormalization.  :-)

Hopefully this explanation puts the migration in its appropriate context.

**Comment by daN4cat** [comment]
Fixed the SQL scripts and UPGRADE.txt file

**Comment by daN4cat** [comment]
With regards to CSRF it looks more an installation issue rather than an OSPOS one.
It's working fine for many, but we probably need to keep an eye on this story as it might be behind some of the Windows based installation issues too.

**Comment by objecttothis** [comment]
I just ran a comparison of the clean install and the migrated install databases.  Both have the exact same code base.  Here are the changes needed in the appropriate database update scripts so that the data will reflect a clean database install:

- `ospos_giftcards` `record_time` does not exist
- `ospos_giftcards` `value` needs to be updated to not allow null
- `ospos_items` `cost_price` needs to be updated to not allow null
- `ospos_items` `location` was dropped at some point and this data needs to be migrated to whatever it was moved to as it is relied on heavily in mine and I'm sure other's data sets.  I suspect this was replaced by stock locations.  If so, the data migration has a problem because the migration script complains that non-unique values appear in locations, however when item location was stored at the item level there was no constraint requiring unique values, so instead the migration script should be taking one of each value and ignoring duplicates.  I'll see if I can come up with the SQL to fix the migration script.
- `ospos_items` `unit_price` needs to be updated to not allow null
- `ospos_items_columns` needs to get dropped;
- `ospos_receivings` `comment` needs to be updated to not allow null
- `ospos_receivings_items` `discount_percent` needs to be updated to not allow null and make the default '0.00';
- `ospos_receivings_items` `item_unit_price` needs to be updated to not allow null
- `ospos_sales` `comment` needs to be updated to not allow null
- `ospos_sales_items` `discount_percent` needs to be updated to make the default '0.00' instead of 0;
- `ospos_sales_items` `item_unit_price` needs to be changed to a decimal(15,2) instead of a double(15,2)

The only other thing that I am not sure if it has to do with my changes or not but I noticed a mixture of columns in the various tables that have utf8_unicode_ci collation and utf8_general_ci collation where the clean database has only utf8_general_ci collation on text and varchar columns.  If this is a change in the code and not one of my changes then it might be a good idea in one of the migration scripts to change all varchars and text collations from utf8_unicode_ci to utf8_general_ci.  

Again, I'm happy to write the code and submit the pull requests but I need to know what milestones each of these changes were introduced in order to put them into the correct database update script.

BTW, a really cool tool did the database comparison to figure out the differences between the current clean dB structure and the migrated database. http://www.infoom.se/compare-mysql-online/  Here are the MySQL queries for all but #4 above that will need to be entered as generated from the link.

ALTER TABLE `ospos_giftcards` ADD `record_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `ospos_giftcards` MODIFY `value` decimal(15,2) NOT NULL;
ALTER TABLE `ospos_items` MODIFY `cost_price` decimal(15,2) NOT NULL;
ALTER TABLE `ospos_items` MODIFY `unit_price` decimal(15,2) NOT NULL;
DROP TABLE `ospos_items_columns`;
ALTER TABLE `ospos_receivings` MODIFY `comment` text NOT NULL;
ALTER TABLE `ospos_receivings_items` MODIFY `discount_percent` decimal(15,2) NOT NULL DEFAULT '0.00';
ALTER TABLE `ospos_receivings_items` MODIFY `item_unit_price` decimal(15,2) NOT NULL;
ALTER TABLE `ospos_sales` MODIFY `comment` text NOT NULL;
ALTER TABLE `ospos_sales_items` MODIFY `discount_percent` decimal(15,2) NOT NULL DEFAULT '0.00';
ALTER TABLE `ospos_sales_items` MODIFY `item_unit_price` decimal(15,2) NOT NULL;

**Comment by jekkos** [comment]
Ok nice work comparing end results of both. Regarding app config values indeed a value isn't always required. Think the fastest way to retrieve when something was introduced is by using git annotate in an ide. Then you can quickly see the commit and version number linked to the change. 

Think we need to add a version string to our database to have Auto upgrade functional. Then compare with application version so we know which scripts to run. This will be a first step for Auto upgrading the whole app..

**Comment by objecttothis** [comment]
OK, I will set that up in Eclipse. and submit a pull request for the remaining updates. 

I noticed that Steve's tax migration code adds a date-stamp or version stamp when the migrate gets done.  We could use that if we change the code to automatically insert a seed value on a new install and then update the database migration script to add it if it doesn't exist for upgrades.  That would likely be the best solution if we are going to update the code in the "migrate database" functionality to automatically run scripts rather than users needing to manually do them through phpmyadmin or ssh.

I think the benefit of getting automated updating and GUI installer rock solid is that ideally the number of support inquiries from updates, new installs and "im getting this error because I didn't update my .htaccess file" drops... of course that's only if the updater and installer are solid.  I'd be glad to tackle or collaborate on both.

**Comment by daN4cat** [comment]
I just copied and pasted your updates in the upgrade script and tested.
All is working fine except `ospos_items_columns` because that's not an OSPOS table.

I submitted the new upgrade script to master. Thanks again for the time spent in verifying this and contributing a solution.

**Comment by daN4cat** [comment]
Also the change from double to decimal will make the memory consumption of MySQL better and some queries faster.

**Comment by jekkos** [comment]
@daN4cat @objecttothis can we close this one?

**Comment by objecttothis** [comment]
Yes I think we can.

_Sent from my Android XT1575 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
