### ISSUE TITLE
You don't have permission to access /pos/ on this server.

### ISSUE THREAD

**Issue by jsoftwares** [jekkos/opensourcepos#1489]
### Issue / Question / Bug
Dear sir,
I have installed OSPOS 3.0.2 complete on Ubuntu 14.04 LTS and after this when I try to access
192.168.1.10/pos
I get the error page below:

Forbidden

You don't have permission to access /pos/ on this server.

Apache/2.4.7 (Ubuntu) Server at 192.168.1.10 Port 80

I have modified .htacess file to read.... RewriteRule ^(.*)$ /pos/public/index.php?/$1 [L]
and Commented the line above. Kindly let me know what could possibly be the cause of this. Thanks

Before submitting an issue please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] I'm reporting an issue of an unmodified OSPOS installation
- [x] I checked open and closed issues database and no similar issue was already discussed (please make sure you searched!)
- [x] I read the README, WHATS_NEW and UPGRADE
- [x] I read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php-gd, php-intl, sockets and etc. installed)
- [] I read the wiki
- [] I ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql), and migrating function
- [] I'm aware the latest master could be a development version and therefore not stable
- [] I know the version of OSPOS and git commit hash (check the footer of your OSPOS), the name and version of OS, Web server, PHP and MySQL and will add them to my issue report

**Comment by odiea** [comment]
Read the readme or wiki or faqs.
192.168.0.10/pos/**_# public_**
