### ISSUE TITLE
Items view: if searched text contains a ' the search will not work

### ISSUE THREAD

**Issue by daN4cat** [jekkos/opensourcepos#149]
1. Go to Items view
2. Create an item with name containing a '  (e.g. doesn't work)
3. Search for the item, suggestion prompts the item but selecting it doesn't list the item

Same applies if a Supplier has a ' .

It's quite common in certain languages like French, Italian and at times in English to have ' .

**Comment by jekkos** [comment]
This might be a security issue (sql injection). Input sanitization is needed for the search string ($this->db->escape) together with the % signs before or after.

**Comment by daN4cat** [comment]
OK, but it's a serious issue. I tested more and with the database I use for my test which is a copy of a real one it will be a major mis.
Why we limit search boxes that are protected?

**Comment by daN4cat** [comment]
BTW, in model/item and search function I was trying to replace the following:

				$this->db->where("(name LIKE '%" . $search . "%' OR " .
					"item_number LIKE '" . $search . "%' OR " .
					$this->db->dbprefix('items').".item_id LIKE '" . $search . "%' OR " .
					"company_name LIKE '" . $search . "%' OR " .
					"category LIKE '%" . $search . "%')");

with this:

				$this->db->like('name', $search);
				$this->db->or_like('item_number', $search, 'after');
				$this->db->or_like($this->db->dbprefix('items').'item_id', $search, 'after');
				$this->db->or_like('company_name', $search, 'after');
				$this->db->or_like('category', $search);

But it doesn't work at all. Any idea why before I google around in search of a clue?

**Comment by jekkos** [comment]
are there any previous where statements before this one? It's possbily due to the operator precedence of the or_like in this case. The or_like will probably use parentheses or something internally which will cause the complete expression to be evaluated differently.

Try to print a $this->db->last_query() just before the get() so you can see which query is actually written out to the database.

**Comment by daN4cat** [comment]
I'll check with last_query this eve.
BTW I don't see any escape in model/item.php, neither on controller side.

**Comment by jekkos** [comment]
Yes indeed that's something I noticed as well some time ago.

**Comment by daN4cat** [comment]
Therefore I guess I should add something $this->db->escape_like_str($search) or check if like / or_like are doing that already. This is probably connected with #39 issue. Am I right?

**Comment by daN4cat** [comment]
OK, I miss the fact that there is a ( before name in the where. It's a group OR.
Unfortunately we are not using CI3, so we cannot used group_start() and group_end().
A solution would be to extend the core like suggested here: http://stackoverflow.com/questions/6470267/grouping-where-clauses-in-codeigniter

But here we are talking about something else.... so it's off topic.

**Comment by daN4cat** [comment]
The issue is fixed adding $this->db->escape_like_str($search) to the where query I mentioned earlier.

I also fixed the custom fields query because the or_like would not work properly due to the lack of grouping. I used $this->db->escape_like_str($search) also for those.

Once the Print button pull is done I'll push this fix for a merge.
