### ISSUE TITLE
Acceso Prohibido in Windows

### ISSUE THREAD

**Issue by pedrojsaba** [jekkos/opensourcepos#1493]
With Php 5.5, Apache 2.4.

I've access problem. Get this message only load base route.
**************************************************************
¡Acceso prohibido!

Usted no tiene permiso para acceder al directorio solicitado. No existe un documento índice, o el directorio está protegido contra lectura.

Si usted cree que esto es un error del servidor, por favor comuníqueselo al administrador del portal.

Error 403

localhost
Apache/2.4.23 (Win32) OpenSSL/1.0.2h PHP/5.5.38
*****************************************************

**Comment by amrshah** [comment]
You are getting this on the root path of OSPOS? 

Try localhost/YOUR_OSPOS_PATH_HERE/public

Replace YOUR_OSPOS_PATH_HERE with whatever your relevant path is.

**Comment by pedrojsaba** [comment]
http://localhost/opensourcepos/public/login, After login, I get this message:
In http://localhost/opensourcepos/public/home
******************************************
Esta página no funciona

La página localhost no puede procesar esta solicitud ahora.
HTTP ERROR 500

********************************

**Comment by daN4cat** [comment]
You didn't fill in the issue template, so I close.
