### ISSUE TITLE
Profit Not Showing in Reports

### ISSUE THREAD

**Issue by saruban** [jekkos/opensourcepos#1494]
Please check the video, I recorded the issue in our pos.

https://drive.google.com/file/d/0B_An7lWvZlM9ZVJDR21JTm5xaVU/view

Help to fix it. 

Thanks .

**Comment by SteveIreland** [comment]
I couldn't resist the temptation to click on the link even though at first I suspected it was virus.

However, what I received was the following.  Maybe some text describing the issue would be more useful.

![image](https://user-images.githubusercontent.com/23066623/29572703-0f94b402-872b-11e7-9db1-a81c22e744fc.png)

**Comment by RamkrishnaMondal** [comment]
@SteveIreland 
Inspite of that message, i clicked on the download button and the video file got downloaded.

**Comment by SteveIreland** [comment]
I always do what I'm told.  You must be a rebel.  :-)

**Comment by odiea** [comment]
@SteveIreland Like filling out the Template with all the needed info.

**Comment by SteveIreland** [comment]
Exactly!

**Comment by saruban** [comment]
Now its working fine.

**Comment by daN4cat** [comment]
Sometimes not answering is the answer, so people find their own way out.

**Comment by daN4cat** [comment]
@saruban and the solution to your problem was?

**Comment by saruban** [comment]
I tried to add tax in store configuration.  But it didn't help me. After I checked "Tax Inclusive"  in store config, its working fine

**Comment by daN4cat** [comment]
@saruban can you please explain which version you are using and how to reproduce your issue?
Also is that an original OSPOS or modified one?

**Comment by saruban** [comment]
Version is.  3.0.2.  
Original version.  Modified images and icons only.

**Comment by daN4cat** [comment]
And I assume you are not using MySQL5.7 nor PHP7.x, right?

Your comment on another issue was related to the latest 3.1.0 code, so you cannot mixup 3.0.2 with 3.1.0

**Comment by saruban** [comment]
I am using now 3.0.2.  No more 3.0.1. If I confused you by the different versions please sorry.

**Comment by saruban** [comment]
mysql - 5.1.73
PHP version: 5.6.30

**Comment by saruban** [comment]
I like to update items(stocks) as bundle or case.  If we add coca cola bottles as case how can we do this?
If we add 1 case the stock should take this as 24 bottles.  If we sell 1 case, the stocks in the warehouse should detect this and subtract 24 items.

If any related issue here like this, please refer me. or I will open new. 

Thanks .

**Comment by daN4cat** [comment]
Latest master is 3.1.0, we are not too far to release it. Hopefully in a week or two.

**Comment by saruban** [comment]
Can I get to know the new key features only?

**Comment by daN4cat** [comment]
There is a Readme in the github front page.

**Comment by saruban** [comment]
I got it. Thanks. 

What about this ; 

"I like to update items(stocks) as bundle or case. If we add coca cola bottles as case how can we do this?
If we add 1 case the stock should take this as 24 bottles. If we sell 1 case, the stocks in the warehouse should detect this and subtract 24 items.

If any related issue here like this, please refer me. or I will open new. "

**Comment by daN4cat** [comment]
It was discussed in the past, search the open/closed issues.

@SteveIreland adjusted the items_kit for similar purposes, but now I can't remember from the top of my head if he in the end addressed that specific issue.

**Comment by RamkrishnaMondal** [comment]
Just put (Purchase price - tax paid ) as 'Cost Price' and (sales price - tax collected) as 'Retail Price'. You will get correct profit.

**Comment by saruban** [comment]
@RamkrishnaMondal Thanks but it solved and you can check previous comments. 
Can you please help me in this;
"I like to update items(stocks) as bundle or case. If we add coca cola bottles as case how can we do this?
If we add 1 case the stock should take this as 24 bottles. If we sell 1 case, the stocks in the warehouse should detect this and subtract 24 items."

**Comment by RamkrishnaMondal** [comment]
Create an items_kit say, 'Coca Cola Case' and add 24 bottles to it. When you sell one case, ospos will deduct 24 bottles from the stock.

**Comment by saruban** [comment]
It's working. Good method.
In future ,  hope the case or bundle stock items will be added in reports > inventory summary
