### ISSUE TITLE
"Vendor" folder is missing

### ISSUE THREAD

**Issue by ZayanVizier** [jekkos/opensourcepos#1495]
"Vendor" folder is missing

### Installation information

- OSPOS version is: Latest Stable
- OSPOS git commit hash is: 
- PHP version is:   (7.1)
- MySQL or MariaDB version is:   (MariaDB 10.2)
- OS and version is:   (Windows 10)
- WebServer is:   (Apache 2.4)
- Installation package for the LAMP/LEMP stack:   ( XAMPP)

### Expected behaviour
Login Screen

### Actual behaviour
Error on system path

### Steps to reproduce the issue
Please add the vendor folder

**Comment by daN4cat** [comment]
Read the README before posting issues...
