### ISSUE TITLE
Inventory report with item sale quantity, purchase quantity and balance quantity in one report

### ISSUE THREAD

**Issue by ajaykumarji** [jekkos/opensourcepos#1499]
Hi,

 it may possible to add a Inventory report with item sale quantity, purchase quantity and balance quantity in one report. 

I saw balance quantity and value only.

Regards

**Comment by daN4cat** [comment]
This would be better supported once we introduce Reportico, see #1433

**Comment by ajaykumarji** [comment]
Good, you are genius,
and believe you can do it.
