### ISSUE TITLE
highlighting some rows of table in the reports

### ISSUE THREAD

**Issue by bill-goldberg** [jekkos/opensourcepos#1506]
![github](https://user-images.githubusercontent.com/23611136/29606484-12d46856-880c-11e7-810e-7b01902dde25.jpg)

**Comment by bill-goldberg** [comment]
Is there any easy way to highlight the rows of table in the reports module on a particular field value.
Like i added a credit option for payment type... i want to highlight all sales which having the payment_type as credit as i have to collect payment from my customers in future. highlighting will help me to quickly visualize the unpaid sales/receivings

**Comment by jekkos** [comment]
Should be fairly easy using javascript, check the code for the delete logic which contains some kind of highlighting animation as well.

also think bootstrap tables might have something builtin to do that. Just check their api / docs

**Comment by daN4cat** [comment]
maybe @bill-goldberg you could make a contribution one day as it will be appreciated seeing the number of questions and help we gave. Not to mention the whole open source code for free.... what do you think?
