### ISSUE TITLE
strangely slow

### ISSUE THREAD

**Issue by katika** [jekkos/opensourcepos#1507]
### Issue / Question / Bug

Before submitting an issue please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] I'm reporting an issue of an unmodified OSPOS installation
- [x] I checked open and closed issues database and no similar issue was already discussed (please make sure you searched!)
- [x] I read the README, WHATS_NEW and UPGRADE
- [x] I read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php-gd, php-intl, sockets and etc. installed)
- [x] I read the wiki
- [] I ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql), and migrating function
- [x] I'm aware the latest master could be a development version and therefore not stable
- [x] I know the version of OSPOS and git commit hash (check the footer of your OSPOS), the name and version of OS, Web server, PHP and MySQL and will add them to my issue report

### Installation information

- OSPOS version is:3.0.2
- OSPOS git commit hash is: 
- PHP version is:   tested on 5.6.30 and 7.0
- MySQL or MariaDB version is:   MariaDB 10.1.23
- OS and version is:   Debian 9
- WebServer is:  Apache 2.4

### Expected behaviour
expect normal (read fast) load from a  newly(just setup, no items added) installed application. On the same server(VM with 2.8Ghz CPU and 512MB RAM; none fully used as reported by top), i run other applications that are not so slow.

### Actual behaviour
Too too slow to load

### Steps to reproduce the issue
go to ip/public/login. After hit enter, takes a fair amount of time to complete request.

**Comment by katika** [comment]
Please see attached file, screenshoot from chrome network console.
![selection_002](https://user-images.githubusercontent.com/29801120/29606730-11b5cd2c-87e7-11e7-8485-8f2ec4565c9f.jpg)

**Comment by katika** [comment]
From apache logs: "Analytics Host not reachable! Error: Host name lookup failure". Perharps the reason?

**Comment by saruban** [comment]
I am also having the same slow issue. I installed the ospos today and added one product only. 
Some times it's loading very slow. taking 1-3 mins.

**Comment by katika** [comment]
Is it possible to disable request to Google Analytics ?

**Comment by odiea** [comment]
Store config - General uncheck 
Send Statistics and see if that helps.

**Comment by katika** [comment]
Thanks. It works.

**Comment by nwashangai** [comment]
Please I need help I tried this and the app is still slow on network without internet

**Comment by katika** [comment]
Perhaps a LAN problem?

**Comment by daN4cat** [comment]
@nwashangai unckeck send statistics from the configuration tabs and try again.

**Comment by nwashangai** [comment]
I have, and I discovered that the app is trying to load google fonts online too

**Comment by daN4cat** [comment]
That's related to bootstrap themes (bootswatch), you probably need to do something like it's explained here:
- https://stackoverflow.com/questions/33961590/bootstrap-css-without-google-fonts
- https://stackoverflow.com/questions/34772357/bootstrap-css-without-google-fonts-2-bootswatch

Let me know if you find a solution that we may consider it.

**Comment by nwashangai** [comment]
@daN4cat I removed the import statements all the places necessary  just as they specified in the link but was still having same problem, but then I disabled my browser cache and it worked. I don't understand what really happened 
Thanks anyway

**Comment by daN4cat** [comment]
JS and CSS are cached, you just need to reload your page keeping the shift button pressed in your web browser.
