### ISSUE TITLE
Constraint issue in 2.3_to_2.3.1.sql

### ISSUE THREAD

**Issue by objecttothis** [jekkos/opensourcepos#1509]
### Issue / Question / Bug

Before submitting an issue please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] I'm reporting an issue of an unmodified OSPOS installation
- [x] I checked open and closed issues database and no similar issue was already discussed (please make sure you searched!)
- [x] I read the README, WHATS_NEW and UPGRADE
- [x] I read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php-gd, php-intl, sockets and etc. installed)
- [x] I read the wiki
- [x] I ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql), and migrating function
- [x] I'm aware the latest master could be a development version and therefore not stable
- [x] I know the version of OSPOS and git commit hash (check the footer of your OSPOS), the name and version of OS, Web server, PHP and MySQL and will add them to my issue report

### Installation information

- OSPOS version is: 3.1.0
- OSPOS git commit hash is: 
- PHP version is:   (e.g. 5.5, 5.6, 7.0, 7.1) 5.6.31
- MySQL or MariaDB version is:   (e.g. MySQL 5.5, MySQL 5.6, MySQL 5.7, MariaDB 10.0, MariaDB 10.1, MariaDB 10.2) 5.7
- OS and version is:   (e.g. CentOS 6.9, Ubuntu 16.4, Windows 10) FreeBSD 11.0
- WebServer is:   (e.g. Apache 2.2, Apache 2.4, Nginx 1.12, Nginx 1.13) Apache 2.4
- (If applicable) Installation package for the LAMP/LEMP stack is:   (e.g. WAMP, XAMPP)

### Expected behaviour
2.3_to_2.3.1.sql to be run and upgrade the dB properly.

### Actual behaviour
MySQL error `#1452 - Cannot add or update a child row: a foreign key constraint fails (pos_alpha.ospos_grants, CONSTRAINT ospos_grants_ibfk_1 FOREIGN KEY (permission_id) REFERENCES ospos_permissions (permission_id) ON DELETE CASCADE)`

### Steps to reproduce the issue
It seems that this code in the sql is causing the problem.  I'm not sure exactly how to resolve it... It can be bypassed by unchecking the enable foreign key checks in phpmyadmin, but I'm not sure that is a good solution.

`  ADD CONSTRAINT 'ospos_grants_ibfk_1' FOREIGN KEY ('permission_id') REFERENCES ospos_permissions'('permission_id') ON DELETE CASCADE; 

-- add grants for all employees
INSERT INTO 'ospos_grants' ('permission_id', 'person_id') VALUES
('reports_customers', 1),
('reports_receivings', 1), 
('reports_items', 1),
('reports_inventory', 1),
('reports_employees', 1),
('reports_suppliers', 1),
('reports_sales', 1),
('reports_categories', 1),
('reports_discounts', 1),    
('reports_payments', 1),    
('reports_taxes', 1),    
('customers', 1),
('employees', 1),
('giftcards', 1),
('items', 1),
('item_kits', 1),
('receivings', 1),
('reports', 1),
('sales', 1),
('config', 1),
('items_stock', 1),
('sales_stock', 1),
('receivings_stock', 1),
('suppliers', 1);`

**Comment by daN4cat** [comment]
You probably manually deletes something from the database and therefore you get this issue.
I had something similar when I did my dry tests using an existing database. You need to manually fix the gaps.

**Comment by objecttothis** [comment]
@daN4cat I did some more digging and the sql is failing because ospos_permissions.sales_stock and ospos_permissions.receivings_stock do not exist and they should. Since the ospos_permissions table is dropped and then recreated in earlier in the script, this is a matter of those two entries not being created.  I have been vindicated!!!! bwhahahaha

I'll submit the pull request

**Comment by daN4cat** [comment]
I assume this is done and I close now.
