### ISSUE TITLE
Master broken

### ISSUE THREAD

**Issue by objecttothis** [jekkos/opensourcepos#1510]
### Issue / Question / Bug

Before submitting an issue please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] I'm reporting an issue of an unmodified OSPOS installation
- [x] I checked open and closed issues database and no similar issue was already discussed (please make sure you searched!)
- [x] I read the README, WHATS_NEW and UPGRADE
- [x] I read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php-gd, php-intl, sockets and etc. installed)
- [x] I read the wiki
- [x] I ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql), and migrating function
- [x] I'm aware the latest master could be a development version and therefore not stable
- [x] I know the version of OSPOS and git commit hash (check the footer of your OSPOS), the name and version of OS, Web server, PHP and MySQL and will add them to my issue report

### Installation information

- OSPOS version is: 3.1.0 opensourcepos.20170823212937.master.bdc63c.zip
- OSPOS git commit hash is: 
- PHP version is:   (e.g. 5.5, 5.6, 7.0, 7.1) 5.6.31
- MySQL or MariaDB version is:   (e.g. MySQL 5.5, MySQL 5.6, MySQL 5.7, MariaDB 10.0, MariaDB 10.1, MariaDB 10.2) Mysql 5.7
- OS and version is:   (e.g. CentOS 6.9, Ubuntu 16.4, Windows 10) FreeBSD 11.0
- WebServer is:   (e.g. Apache 2.2, Apache 2.4, Nginx 1.12, Nginx 1.13) Apache 2.4
- (If applicable) Installation package for the LAMP/LEMP stack is:   (e.g. WAMP, XAMPP)

### Actual behaviour
After install navigating to /public/ gives 404 errors.
- opensourcepos.20170823204301.master.120b93.zip is working.
- both of them aren't redirecting from the base directory to /public/ for some reason.  Can someone see if their installs are redirecting properly to eliminate my server stack as the problem?  This sort of baffles me because the code is the same.  It's just outside the IfModule statement

**Comment by odiea** [comment]
opensourcepos.20170823212937.master.bdc63c.zip
 
Localhost/redirect/
Access forbidden!

You don't have permission to access the requested directory. There is either no index document or the directory is read-protected.

If you think this is a server error, please contact the webmaster.
Error 403
localhost
Apache/2.4.18 (Win32) OpenSSL/1.0.2e PHP/7.0.8 

localhost/redirect/public.

Works as expected.

**Comment by objecttothis** [comment]
@odiea I think you misunderstood.  opensourcepos.20170823212937.master.bdc63c.zip is the one giving the error which is why I went back to opensourcepos.20170823204301.master.120b93.zip which does work.  Perhaps it's human error, so if others aren't having the problem then that's good.

**Comment by odiea** [comment]
Yes I did misunderstand you but opensourcepos.20170823204301.master.120b93.zip still gives me the same result.

**Comment by objecttothis** [comment]
No longer having an issue with 404 errors but for some reason the redirect isn't working for me.  I'm going to test the redirect on another server to eliminate my server as the cause.

**Comment by odiea** [comment]
I always  got the redirect to show the public folder but that was as far as it got.

**Comment by daN4cat** [comment]
I close this one
