### ISSUE TITLE
Latest Versions of Apache PHP and MySQL/MariaDB 

### ISSUE THREAD

**Issue by bill-goldberg** [jekkos/opensourcepos#1518]
Can you please tell me that the latest versions of AMP stack which can be supported by this application.
I want to use the latest version of AMP stack so that i can get improved performance from this application.

**Comment by objecttothis** [comment]
I am using Apache 2.4.27, MySQL 5.7.19 and PHP 5.6.31 on FreeBSD 11.0

I do not know the status of compatibility with PHP 7.0 and 7.1.  Perhaps someone else has tested it.

**Comment by SteveIreland** [comment]
That is all in the readme under server requirements.

**Comment by daN4cat** [comment]
Indeed.
