### ISSUE TITLE
Remove name of people from code comments and move them to license file

### ISSUE THREAD

**Issue by daN4cat** [jekkos/opensourcepos#152]
Currently there are names of people here and there in the code like:

- Parq 131215
- GARRISON ADDED 5/18/2013
- Ramel
- (maybe more which I can't remember right now)

To keep the code clean and pay correct tribute to those contributors in a more public way I would suggest to clean the code and add those names to the license file under the copyright part.

Any different view?

**Comment by jekkos** [comment]
Sounds good to me.

**Comment by daN4cat** [comment]
This is fixed and it will go in a new PR when the current one is closed.

**Comment by jekkos** [comment]
Found the names in the license file now, will close this one.
