### ISSUE TITLE
Data issue in ospos_giftcards causing problem with upgrade script 2.3_to_2.3.1.sql

### ISSUE THREAD

**Issue by objecttothis** [jekkos/opensourcepos#1522]
### Issue / Question / Bug

Before submitting an issue please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] I'm reporting an issue of an unmodified OSPOS installation
- [x] I checked open and closed issues database and no similar issue was already discussed (please make sure you searched!)
- [x] I read the README, WHATS_NEW and UPGRADE
- [x] I read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php-gd, php-intl, sockets and etc. installed)
- [x] I read the wiki
- [x] I ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql), and migrating function
- [x] I'm aware the latest master could be a development version and therefore not stable
- [x] I know the version of OSPOS and git commit hash (check the footer of your OSPOS), the name and version of OS, Web server, PHP and MySQL and will add them to my issue report

### Installation information

- OSPOS version is: 3.1.0
- OSPOS git commit hash is: 
- PHP version is:   (e.g. 5.5, 5.6, 7.0, 7.1) 5.6.31
- MySQL or MariaDB version is:   (e.g. MySQL 5.5, MySQL 5.6, MySQL 5.7, MariaDB 10.0, MariaDB 10.1, MariaDB 10.2) 5.7
- OS and version is:   (e.g. CentOS 6.9, Ubuntu 16.4, Windows 10) FreeBSD 11.0
- WebServer is:   (e.g. Apache 2.2, Apache 2.4, Nginx 1.12, Nginx 1.13) Apache 2.4
- (If applicable) Installation package for the LAMP/LEMP stack is:   (e.g. WAMP, XAMPP)

### Expected behaviour
Install script to run without errors.

### Actual behaviour
`-- add foreign key to giftcards table
ALTER TABLE 'ospos_giftcards'
  ADD CONSTRAINT 'ospos_giftcards_ibfk_1' FOREIGN KEY ('person_id') REFERENCES 'ospos_people' ('person_id');`

Fails if rows exist with a person_id that doesn't exist in ospos_people.  In my case I had rows in ospos_giftcards with a person_id of 0 which didn't exist in ospos_people.  On a few different occasions we ran into some sort of a bug in 2.0.2 causing this, but never addressed it.  I don't see that anyone else ran into this, so I will resolve it internally, but in case anyone else runs into it, I wanted to report it.  A workaround is to uncheck "Enable Foreign Key Checks" or to run a query to change the rows with an invalid person_id to a valid one.

**Comment by daN4cat** [comment]
Among all the changes you committed, is this now fixed? I've got lost a bit....

**Comment by objecttothis** [comment]
No, it isn't fixed in any of my commits. I fixed it internally because I don't know if the problem is specific to my build or if it's a problem others who are upgrading will experience. For now we can close it and Mark it as won't fix and of other people have the same issue I will work on an SQL script that will properly migrate the faulty entries in ospos_giftcards

_Sent from my Android XT1575 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
