### ISSUE TITLE
Distributor's stock management

### ISSUE THREAD

**Issue by saruban** [jekkos/opensourcepos#1528]
Most of the companies sending their stock through distributors (vehicle). End of the day distributors may return some stocks back to inventory.
Owner should keep updated the out going and incomming stocks which handled by distributors every day.

This feature help almost all people.

**Comment by daN4cat** [comment]
Very specific business case, I can't see how this will "help almost all".

**Comment by odiea** [comment]
Have you tried creating multiple stock locations then use Requisition to transfer stock from the main  location then back to the main location at the end of the day?

**Comment by saruban** [comment]
@daN4cat  Only small retailers don't need this feature.  But agents and companies need this. So people in all industries can use this ospos.

**Comment by saruban** [comment]
@odiea Thanks for the suggestions.  I will check it out now.

**Comment by saruban** [comment]
@odiea how can i use Requisition in ospos.  Any special method to do this? 

Can you please assist me?

**Comment by odiea** [comment]
You will need to have at least 2 locations. Then from the drop down menu you will have the choice to use requisition. It will then give the option of transferring items to and from  locations.

**Comment by odiea** [comment]
Once you create the different locations under store config then you go into the Receivings module and transfer inventory using Receivings.

**Comment by daN4cat** [comment]
Indeed good thought @odiea as it's already there.
