### ISSUE TITLE
i am facing an issue, my sales and store config and recieiving pages are freezing, the module or php extension u have to install is installed on my server.

### ISSUE THREAD

**Issue by shinzu1214** [jekkos/opensourcepos#1529]
i am facing an issue, my sales and store config and receiving pages are freezing, the module or php extension u have to install is installed on my server.

and one more thing, when i uplodaded this ospos on my remote server hosting i gor from godaddy. its giving error there as well, when i login it says unable to handle this request.

**Comment by daN4cat** [comment]
no template being filled in, I close.
