### ISSUE TITLE
Improve the OO design of the code

### ISSUE THREAD

**Issue by daN4cat** [jekkos/opensourcepos#153]
The code is based on a MVC framework provided by CodeIgniter as boiler plate.

There are several classes and functions but there is no real enforcement of good OO rules in it.

Examples would be to use private and protected as much as possible and make public interfaces more under control.

Also members or variables are at time generated and regenerated where one instance from a class level could do.

This would be a slow tidy up of the code step by step to improve the implemenation of intended (and ideal) design.

**Comment by jekkos** [comment]
Maybe in this case we could rewrite most of the codebase and use a new frontend framework, decoupled from the backend. I think this way tons of code can be eliminated by using some of the newer frameworks like reactjs, polymer or angular (and rest based apis). Displaying data in tables can be done way easier than it is now, without using low level jQuery and plain javascript./ html markup

I think the data model suits most of the situations pretty well and this can surely be kept and reused (which would for example facilitate migrating from a older versoin of the application)

**Comment by daN4cat** [comment]
OK, you are probably referring to a more ground up rework that will warp the solution to something newer and better. I was a bit referring to improve the current code.

However it would be good to discuss what could be a better boiler plate for OSPOS going forward.
I'll read about the frameworks you suggest.

I found quite challenging to get my mind around all the js, css, html and view part, and of course the ajax/json connectors...
This is really not my area, I wanted to learn but it's not trivial and I guess there must be an easier way to deal with all of that.

**Comment by daN4cat** [comment]
Started setting some functions to be private. This is just "low level" stuff.

There are things that could be improved with maybe more classes or better code reuse.
There are patterns that can be reused and applied across the code.
