### ISSUE TITLE
Location to stock_location change question

### ISSUE THREAD

**Issue by objecttothis** [jekkos/opensourcepos#1530]
### Question

Before submitting an issue please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [x] I'm reporting an issue of an unmodified OSPOS installation
- [x] I checked open and closed issues database and no similar issue was already discussed (please make sure you searched!)
- [x] I read the README, WHATS_NEW and UPGRADE
- [x] I read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php-gd, php-intl, sockets and etc. installed)
- [x] I read the wiki
- [x] I ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql), and migrating function
- [x] I'm aware the latest master could be a development version and therefore not stable
- [x] I know the version of OSPOS and git commit hash (check the footer of your OSPOS), the name and version of OS, Web server, PHP and MySQL and will add them to my issue report

### Installation information

- OSPOS version is: 3.1.0
- OSPOS git commit hash is: 4f5ad57
- PHP version is:   (e.g. 5.5, 5.6, 7.0, 7.1) 5.6.31
- MySQL or MariaDB version is:   (e.g. MySQL 5.5, MySQL 5.6, MySQL 5.7, MariaDB 10.0, MariaDB 10.1, MariaDB 10.2) MySQL 5.7
- OS and version is:   (e.g. CentOS 6.9, Ubuntu 16.4, Windows 10) FreeBSD 11.0
- WebServer is:   (e.g. Apache 2.2, Apache 2.4, Nginx 1.12, Nginx 1.13) Apache 2.4
- (If applicable) Installation package for the LAMP/LEMP stack is:   (e.g. WAMP, XAMPP)

Prior to the stock_location migration we were using the location field in ospos_items to indicate the location in the store that the item could be found.  It appears that with the stock_location migration, what was migrated from the location field now is supposed to represent multiple store locations and what store that it is located in and no longer where in the store it can be found.

Two questions: 
- Am I understanding correctly that stock location is representing different stores and not different locations in a store?
- Is there a workaround to be able to use it the way that we were using location when it was stored as Item location?  We are currently using category to reflect the category or type of item (e.g., book, gift, music, service, etc)

While the stock location, is a great and needed addition for businesses that have multiple sites, the migration from location to stock_location doesn't account for businesses with single location who were using the location field to indicate where in the store the product could be found.

Thoughts?

**Comment by daN4cat** [comment]
I understand it represent different location for your stock. Could be in a warehouse, stock room, 1st floor of your shop, ground floor of your shop, on a mobile shop... etc.

**Comment by objecttothis** [comment]
The problem is that when searching inventory or selling items you have to know what stock location the item is in to find it.  If not, it doesn't appear in the search results or tells you that you have insufficient stock.

**Comment by objecttothis** [comment]
I ended up migrating location to one of my custom fields so that when the stock migration came it didn't cause problems with not being able to find product.

**Comment by objecttothis** [comment]
this can be closed
