### ISSUE TITLE
return mode not sum up already item in cart 

### ISSUE THREAD

**Issue by arrazka** [jekkos/opensourcepos#1534]
using : 3.1.0 - 4f5ad57

return mode --> scan sale id -> item loaded = 2 line  / product ( this same like in the first sale_mode)
product 1 = item_id =1
product 2 = item_id = 2
scan product 1 (item_id =1) ... cart cleared and only produt 1 in the cart, scan again product 1..  quantity not change still -1. scan product 2 (item_id =2) quantity for product1 (item_id =1) change to  -3.  but when I scan product not part of sale_id ex: product3, cart adding new line product 3, scan again product 3 quantity working well, quantity ++. 

why ?

**Comment by daN4cat** [comment]
@arrazka 
I tested and everything works fine in return mode. Scan multiple times each product and each scan adds -1 to the selected product.
Please check your scanner, barcodes and etc. because you have some mixup with your setup most likely.
