### ISSUE TITLE
PROFIT DETAILS NOT SHOWING IN OSPOS 3.0.2 REPORT MODULE

### ISSUE THREAD

**Issue by aterad** [jekkos/opensourcepos#1536]
Hello house,
Please there is an error in the report module.
the profit column and summary of the generated report has no record. its reading zeros.
Please any solution.
Thanks house
![report](https://user-images.githubusercontent.com/26612432/29769649-2e256ecc-8be3-11e7-95cd-d6218b702d0b.PNG)

**Comment by daN4cat** [comment]
Fixed in 3.1.0
