### ISSUE TITLE
Paper Size and Printer setup

### ISSUE THREAD

**Issue by Ibnumarjan** [jekkos/opensourcepos#1538]
### IMPORTANT IMPORTANT IMPORTANT

1. "Issue / Question / Bug".
4. Fill in all the details as requested by the section you chose

If you remove the complete template when submitting a Bug your issue will be closed as we cannot help without basic information.

### Issue / Question / Bug

Before submitting an issue please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [X] I'm reporting an issue of an unmodified OSPOS installation
- [X] I checked open and closed issues database and no similar issue was already discussed (please make sure you searched!)
- [X] I read the README, WHATS_NEW and UPGRADE
- [X] I read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php-gd, php-intl, sockets and etc. installed)
- [X] I read the wiki
- [X] I ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql), and migrating function
- [X] I'm aware the latest master could be a development version and therefore not stable
- [X] I know the version of OSPOS and git commit hash (check the footer of your OSPOS), the name and version of OS, Web server, PHP and MySQL and will add them to my issue report

### Installation information

- OSPOS version is: 2.4
- OSPOS git commit hash is: 
- PHP version is:   5.6.3
- MySQL or MariaDB version is:   MySQL mysqlnd 5.0.11
- OS and version is:   Windows 10
- WebServer is:  Apache 2.4
- (If applicable) Installation package for the LAMP/LEMP stack is:   XAMPP

### Expected behaviour
Receipt Normal Print without any change

### Actual behaviour
I am using 5.5 x 5.5 continues paper (EPSON LQ310), When receipt print it is comming very small in a left corner of the paper (cannot read,,... very small) but in printer test page or from any other programs it is printing fine. All the printer setups are ok in printer. 

Also, we cannot change the the store config > receipt > ticket printer, it is grayed out (disabled) can not change Show Print Dialog ----upto ---- Margins.... > all are grayed out and disabled
![capture](https://user-images.githubusercontent.com/19687579/29821555-fa571d12-8ce5-11e7-9519-90425ffa4025.JPG)

**Comment by odiea** [comment]
Have you tried using Firefox with the JSPrint plug-in installed?

**Comment by Ibnumarjan** [comment]
No, But I am using Chrome, 
Is there any specific paper size assigned in the system (OSPOS)?

**Comment by odiea** [comment]
Not that I am aware of. Selecting the printer features were designed to be used with jsprint in Firefox.

**Comment by daN4cat** [comment]
@Ibnumarjan I'm afraid that's a printer setup issue and page size selection story. Check your configuration setting in your windows / linux / mac printer driver.

**Comment by jekkos** [comment]
There's something here on the wiki that explains how to use print configuration. Check  

https://github.com/jekkos/opensourcepos/wiki/Receipt-auto-printing
