### ISSUE TITLE
I am now getting the following error when finishing a sale.

### ISSUE THREAD

**Issue by odiea** [jekkos/opensourcepos#154]
Fatal error: Call to private method Barcode_lib::generate_barcode() from context 'Sales' in C:\xampp\htdocs\tabbed\application\controllers\sales.php on line 384

**Comment by daN4cat** [comment]
Yes, I know I'm fixing it. Actually that's fixed and there is another issue with item_kits.

**Comment by odiea** [comment]
Thanks I noticed that also. It appears that only Item barcodes are printing properly.

**Comment by daN4cat** [comment]
Yes.

**Comment by daN4cat** [comment]
I pushed the change that fixes sale & receiving receipt & invoice printing.

Items_kit issue has nothing to do with barcode change I made.
Neither delete works properly. There is some other issue with the table (manage) part.
I'll create a new issue for that.

**Comment by odiea** [comment]
I copied and pasted your new code and both receipts are printing now.

**Comment by daN4cat** [comment]
See even my last push with the fix to the language merge mistake.
The translation of Last in the pagination (e.g. items) disappeared.

**Comment by odiea** [comment]
If your in the same time zone as jekko it's time for you to go to bed too.

**Comment by daN4cat** [comment]
UK/London I go to bed 1 hour later :-)
