### ISSUE TITLE
Windows 7 Installation

### ISSUE THREAD

**Issue by sanubari97** [jekkos/opensourcepos#1540]
### Issue / Question / Bug

Before submitting an issue please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [0] I'm reporting an issue of an unmodified OSPOS installation
- [0] I checked open and closed issues database and no similar issue was already discussed (please make sure you searched!)
- [0] I read the README, WHATS_NEW and UPGRADE
- [0] I read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php-gd, php-intl, sockets and etc. installed)
- [0] I read the wiki
- [0] I ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql), and migrating function
- [0] I'm aware the latest master could be a development version and therefore not stable
- [0] I know the version of OSPOS and git commit hash (check the footer of your OSPOS), the name and version of OS, Web server, PHP and MySQL and will add them to my issue report

### Installation information

- OSPOS version is: 3.0.2
- XAMPP version : 3.2.1
- OSPOS git commit hash is: 
- PHP version is:    7.1
- MySQL or MariaDB version is:   MySQL 5.7,
- WebServer is:   Apache 2.4

### Expected behaviour
Show login menu

### Actual behaviour
This page isn’t working

localhost is currently unable to handle this request.
HTTP ERROR 500

### Steps to reproduce the issue
enter the url http://localhost/ospos302/public/
in chrome browser

**Comment by sanubari97** [comment]
I read and googled, cant resolve the problem..

**Comment by SteveIreland** [comment]
OSPOS 3.0,2 isn't compatible with the platform you are running on.  You will need to install 3.1.0.

**Comment by sanubari97** [comment]
where do I get that ?
