### ISSUE TITLE
need help regarding inventery

### ISSUE THREAD

**Issue by sameeerz** [jekkos/opensourcepos#1541]
i want too add free issues option for example when i receive 10 item of 100 rs (MRP) my price 80 rs each each i get 2 item for  free
so when i sell them for 10 item my profit is 20 rs and for the remaining my profit is 100% 
so how can i implement free issues option and how can i add 2 MRP option because some product i receive at rs 100 and next time it can be 110 but still i have old stock of 100 rs and new stock of 110 rs but i can differentiate in them

**Comment by daN4cat** [comment]
what about filling in the template as requested before submitting something?
