### ISSUE TITLE
been trying to reach you , do you have a python version?

### ISSUE THREAD

**Issue by BitMari** [jekkos/opensourcepos#1542]
Question 

been trying to reach you , do you have a python version?

### Issue / Question / Bug

Before submitting an issue please make sure you tick (add an x between the square brackets with no spaces) the following check boxes:

- [] I'm reporting an issue of an unmodified OSPOS installation
- [x] I checked open and closed issues database and no similar issue was already discussed (please make sure you searched!)
- [x] I read the README, WHATS_NEW and UPGRADE
- [x] I read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php-gd, php-intl, sockets and etc. installed)
- [x] I read the wiki
- [] I ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql), and migrating function
- [x] I'm aware the latest master could be a development version and therefore not stable
- [x] I know the version of OSPOS and git commit hash (check the footer of your OSPOS), the name and version of OS, Web server, PHP and MySQL and will add them to my issue report

**Comment by SteveIreland** [comment]
How about a Cobol version - or even better a Fortran version?

**Comment by daN4cat** [comment]
Maybe we should re-implement OSPOS in Scala.

The answer to the question is: sorry, no. 
And what would be the benefit of Python versus PHP 7.x?
