### ISSUE TITLE
Item_kits manage (table) doesn't work properly

### ISSUE THREAD

**Issue by daN4cat** [jekkos/opensourcepos#155]
1. go to item kits view
2. add few item_kits items
3. select the top checkbox that should select the entire row -> it doesn't work
4. select an item and press delete button, ajax json reply is printed in the screen and item is not delete
5. select item to print barcode and a php error is printed (item_kit id is not passed to the generates_barcode function)

It looks like the item_kits/manage table is broken and not sure that's due to changes made in other parts of the system with js or css or else.

**Comment by odiea** [comment]
When generating barcodes for Item Kits

A PHP Error was encountered

Severity: Warning

Message: Missing argument 1 for Item_kits::generate_barcodes()

Filename: controllers/item_kits.php

Line Number: 115
A PHP Error was encountered

Severity: Notice

Message: Undefined variable: item_kit_ids

Filename: controllers/item_kits.php

Line Number: 120
Once Again Thrift
  :  09.16.15
Barcode shows here
*KIT *
When deleting a kit a new page displays with the following but no deleting is done. I was able to delete an item from the item kit with no issues.
{"success":true,"message":"You have successfully deleted 1 Item Kit(s)"}

**Comment by daN4cat** [comment]
Yes, that's the issue.

**Comment by odiea** [comment]
The last Date when it worked is Sept 4th.

**Comment by daN4cat** [comment]
Thanks for the info that's great help here. I'll go back in history like for the language issue and see what we changed.

**Comment by daN4cat** [comment]
I sorted the first part of the issue and everything works fine with Barcodes Code39/128 are selected.

However I need now to sort out an issue with Ean8 and Ean13 barcodes, because the passed argument for item_kits is not a seed number but a string containing KIT.

**Comment by jekkos** [comment]
I had a look at it, looks like there's no number passed into the barcode lib..

**Comment by daN4cat** [comment]
I fixed everything and going to push the change.

**Comment by jekkos** [comment]
OK great, I'm curious to see what the problem was

**Comment by daN4cat** [comment]
Many different things not right with the table (manage).

**Comment by daN4cat** [comment]
Fix pushed. I tested the table functionality, the search, the barcode generation and the sale accepting the KIT #

**Comment by odiea** [comment]
public function generate_receipt_barcode($barcode_content) is in barcode lib 2 times?

**Comment by daN4cat** [comment]
Thatks. Something went wrong with the rebase. I need to revert that file to the correct version.

**Comment by daN4cat** [comment]
It's now fixed.

**Comment by daN4cat** [comment]
Thanks a lot for testing the changes.

**Comment by odiea** [comment]
It appears to be working now.

**Comment by daN4cat** [comment]
Great and thanks for the confirmation. I hope Jekkos can close the PR merging everything to master.

**Comment by odiea** [comment]
Your Welcome. The changes you made are for the benefit of all.

**Comment by jekkos** [comment]
Ok thanks for the hard work. I will have a look later tonight.

**Comment by jekkos** [comment]
Verified and all good now. Thanks!
