### ISSUE TITLE
Unable to install OSPOS 3.1.0

### ISSUE THREAD

**Issue by softaculous** [jekkos/opensourcepos#1550]
Unable to install ospos 3.1.0 on our test server with php 5.6 and mysql version 5.5. It is giving "Your system folder path does not appear to be set correctly. Please open the following file and correct this: index.php" error while accessing {PATH}/{TO}/{Ospos}/public/index.php

Further we found that vendor directory is missing in the package of 3.1.0

Please let us know what is causing this issue ?

**Comment by odiea** [comment]
https://github.com/jekkos/opensourcepos/releases

**Comment by daN4cat** [comment]
And use the long name zip that is the full installation not the source code ones.

**Comment by daN4cat** [comment]
Also see #1242
