### ISSUE TITLE
Proposed Translation Guidelines

### ISSUE THREAD

**Issue by objecttothis** [jekkos/opensourcepos#1554]
### New Feature / Enhancement

I've noticed there are several inconsistencies in translation style in the en-US translation. While not all guidelines will apply straight to all languages, I'd like to propose a few "Translation Guidelines" to be used and recommended for all translations.  Please feel free to modify, discuss or shoot down:

- Titles follow capitalization rules for title format.  That is first Letter of each word capitalized except unimportant words and no punctuation is used (e.g., not "Change password." but instead "Change Password"). 
- Sentences follow sentence grammar rules for punctuation and capitalization specific to the language (e.g., not "one or more of the has processed sales or you are trying to delete your account" but instead "one or more of the has processed sales or you are trying to delete your account.").
- When sentences reference a field, it is referred to in the exact same format as the field (e.g., not "the title is a required field" but instead "Title is a required field").
- Use a consistent success/failure message format.  Currently, I see "The {field} was successfully updated" and in other places "{field} update successful", but I think we should stick to "{field} update successful" and {field} update failed" style messages.  There are three major reasons for this: Succinct translations, consistency and it allows us to remove dozens of translated lines because we only need one translated line for "update successful" and "update failed"  or "is a required field." and in the code we can call the field name and either update successful or failed.  Of course there will be exceptions where we want to add more information, and for those we can have a separate translation line.
- Gift Card(s) in the translation should be two words.  In the code it is one word, but English and most other languages it is two words.

**Comment by daN4cat** [comment]
Probably this is fine now, agree?

**Comment by daN4cat** [comment]
This is now part of the wiki page dedicated to Translations: https://github.com/jekkos/opensourcepos/wiki/Adding-translations
