### ISSUE TITLE
Item Kits to have their own prices

### ISSUE THREAD

**Issue by Alaa-23** [jekkos/opensourcepos#1556]
### New Feature / Enhancement

*For New Features or Enhancements please clearly write your proposal.
It's important to state whether you expect the community to implement it or you will contribute the work.
Please bear in mind that we will implement new features only on the current code, there is no support for older versions.*

**First, I want to thank you guys for your efforts and great work.
Second, It would be great if there's a way to price a kit with it's own price (other than just applying a discount on the retail price).**

**Comment by SteveIreland** [comment]
When you define an item kit you can create a item that represents the kit and point the kit to that item. That is how to set the price for the kit

See the wiki for more info
