### ISSUE TITLE
Backup no longer works

### ISSUE THREAD

**Issue by SteveIreland** [jekkos/opensourcepos#1557]
### Issue / Question / Bug

In commit bc048841902316752396ab60a5225088afa492 on August 5th a blank line was added prior to the start of the code and this is triggering a failure when clicking on the backup button.

```
Message: Cannot modify header information - headers already sent by (output started at /home/kendosrv/application/libraries/Barcode_lib.php:2)
```

**Comment by SteveIreland** [comment]
I removed the blank line in my"in production" code and the backup started working again.  I can submit a pull request for the fix in about 12 hours if no one wants to jump on it earlier.

**Comment by daN4cat** [comment]
Fixed and in master. Thanks for the bug report.
