### ISSUE TITLE
Link to weblate

### ISSUE THREAD

**Issue by objecttothis** [jekkos/opensourcepos#1569]
Would it be ok to put a link to weblate and a blurb about contributing to the translation into the readme? That would reduce questions about how to contribute to translation. I can submit the pull request but wanted to first make sure it's be ok.

**Comment by daN4cat** [comment]
Yes, good idea.

**Comment by daN4cat** [comment]
This is done and it will be commit to master with the rest of the 3.1.1 release notes. So I close.
