### ISSUE TITLE
sale/complete comes up with a blank page

### ISSUE THREAD

**Issue by Tristan083** [jekkos/opensourcepos#158]
Hi Jekkos,

First of all, I'd like to say... Great App!
I seem to be having a problem completing a sale, the page just literally comes up blank after clicking 'Complete Sale'. Anywhere I went wrong with my configuration that might be causing this? I'm using Windows XP SP3, Apache 2.3 server, PHP 5.4, MySQL 5.6; and, chrome/firefox browser.

**Comment by daN4cat** [comment]
Hi, which version are you using?

**Comment by Tristan083** [comment]
Thank you for the immediate response. I tried both the 2.3.2 and 2.3.3 versions of the app.

**Comment by daN4cat** [comment]
Hi, please try again with the latest 2.3.3 and see if you still get the issue? Not sure about 2.3.2, I cannot go back and test that at the moment.

**Comment by Tristan083** [comment]
Hi daN4cat, I hate to inform you this; but, I had just tried again ver. 2.3.3 and I'm getting the same issue. Would you know of any other pre-requisites (modules) for Apache or PHP that might be causing this?

**Comment by daN4cat** [comment]
are you using windows or linux to run your server?

**Comment by Tristan083** [comment]
I am using Windows XP SP3.

**Comment by daN4cat** [comment]
No idea if there is anything special on Windows, Apache and PHP.

Going back to the scenario here, have you selected print after sale or invoice before completing the sale?

Try one or the other and see if something changes.

**Comment by glassen** [comment]
In my case it was that I needed to install the php5-gd package. This is using a TurnKey LAMP template for server. Without it I got a completely blank page on complete sale.

**Comment by Tristan083** [comment]
Hi glassen. Thank you so much for the solution. enabling php-gd extension package on my php.ini file did the trick! Have a good one!
