### ISSUE TITLE
Takings/Overview: Not all Gift Cards included in totals

### ISSUE THREAD

**Issue by odiea** [jekkos/opensourcepos#159]
When I run Payment summary report or go into Takings/Overview ( I renamed mine to "Daily Sales") how come Gift Cards do not show as a totaled amount? I think we need to let others know that the Print Button in Sales Overview/Takings just prints the on screen display and not a Receipt reprint if a check box is checked. It does show if the gift card amount is Greater Than 0. So using the Gift Card as a way to refund a customer money is not correct?
Another issue I have gotten is I am in  Sales and enter kit 5 upper or lower case and the kit will come up but if I select the item kit by its name it says it cannot add item to sale. Is there a way to add a price to the item kit so that it shows on the barcode. Currently it doesn't.

**Comment by daN4cat** [comment]
With regards to Print button and view, I've created a dedicated #160.
The reason why I moved to the top right was exactly that, no print selected items.

I will check how to create a print view as for receipts and invoices to make the printout looking better.

**Comment by daN4cat** [comment]
With regards to Gift Card total, I see there is a problem when you did a return and refund against a gift card. Total is not shown or not shown correctly.

**Comment by daN4cat** [comment]
With regards to Item kit by name, I've created a dedicated #161.

In general would be better to split issues in different ones.

Therefore the current one stays the GiftCard total one only :-)

**Comment by daN4cat** [comment]
OK, there was a 4th one: Add price to Item Kits barcode #162

**Comment by daN4cat** [comment]
Fixed and in my repo.

I'll do some more work before going for a Pull Request to merge in to jekkos/master

**Comment by odiea** [comment]
I got your new correction but this is what I get when entering giftcards from the menu.
A Database Error Occurred

Error Number: 1066

Not unique table/alias: 'ospos_people'

SELECT * FROM (`ospos_giftcards`) LEFT JOIN `ospos_people` ON `ospos_people`.`person_id`=`ospos_giftcards`.`person_id` LEFT JOIN `ospos_people` ON `ospos_people`.`person_id`=`ospos_giftcards`.`person_id` WHERE `deleted` = 0 ORDER BY `giftcard_number` LIMIT 25

Filename: C:\xampp\htdocs\dan4cat\system\database\DB_driver.php

Line Number: 330

**Comment by daN4cat** [comment]
OK, let me have a look, it might be that something else went in by mistake. Something I was touching for other purposes.

**Comment by daN4cat** [comment]
I don't see the problem, but I don't use xampp which might be a reason here.

Could you please take my latest master and give a try?

Also let me know if you get something similar with Item Kits

**Comment by odiea** [comment]
$this->db->or_like("CONCAT(`first_name`, ' ' , `last_name`)", $this->db->escape_like_str($search)); I see lots of these little characters instead of '. I had to replace it with yesterdays model giftcard.php

**Comment by daN4cat** [comment]
You mean that removing the ` around first_name and last_name in the CONCAT fixed your issue?

That's something I don't remember having added.

What I did was replacing " with ', but probably I need to understand better is that has an effect on windows xampp.

**Comment by odiea** [comment]
Look on your site. That is where I copied the line from. No idea what that marker is. Yes that last change fixed the item_kits name in sales.

**Comment by odiea** [comment]
If you have updated your zip download I will see if that gives the error I was receiving. Maybe a bad merge on my side?

**Comment by daN4cat** [comment]
I need to check other parts of the code to understand better, but I didn't add the ` in CONCAT for sure.

**Comment by daN4cat** [comment]
Could you please take my latest master and give a try?
Sorry for the try and error. I'll see if I can install xampp somewhere and test it.

**Comment by odiea** [comment]
I don't think it's a Xampp problem. I will download and try it.

**Comment by daN4cat** [comment]
Don't know what to say, but I run exactly the code in my master on my test server and everything seems to work fine. That's why I'm puzzled.

**Comment by odiea** [comment]
The download works great. It must have been a bad merge on my side.

**Comment by daN4cat** [comment]
Great :+1: 

Hope you can check now Git Card totals and Item Kit additions.

**Comment by daN4cat** [comment]
Let me know if everything seems fine that I go for PR later.

**Comment by odiea** [comment]
Gift card totals are showing just fine now. I am having issues with adding new item kit or updating a item kit items. The add kit item form disappears ok but the orb (in the search box) just spins until I go out and then refresh or click on items kit menu again then the new item kit shows.

**Comment by daN4cat** [comment]
OK, let me test. Too quick in pushing changes without full test....

**Comment by daN4cat** [comment]
I see, there is a table refresh issue or down that line.

**Comment by daN4cat** [comment]
Found the bug, fixed and testing the fix and other cases where we use the Items kit.

**Comment by daN4cat** [comment]
OK fixed and pushed the fix to my repo.

I tested: add new kit, change a kit, cancel kit change, delete kit, add item from kit, remove item from kit, search by kit and by name, search in Sales by kit and by name, add kit to sales.

All seems fine, but I'm pretty sure I forgot some other corner case... I should really consider working on the test automation because this error&try doesn't suit me well and not that professional.
