### ISSUE TITLE
Takings/Overview: Add proper print view to list of sales

### ISSUE THREAD

**Issue by daN4cat** [jekkos/opensourcepos#160]
Current print button on top right prints the whole page as it stands.

It's wiser to consider a proper print view like for receipts or invoices.

**Comment by odiea** [comment]
I changed common_print from Print to Print List. I think it describes the button function better.

**Comment by daN4cat** [comment]
OK, but the button is outside the table area so it shouldn't be confused with something else.

That said, a correct view is probably worth adding.

**Comment by jekkos** [comment]
Yes probably a matter of adding a specific print css stylesheet for this page, that surpresses the top menu and layouts the table properly.

**Comment by sanjubaba1515** [comment]
If you want to make any change. 
PLEASE CONTACT ME AT SANJUBABA1515@GMAIL.COM, WHATS APP +919681971515

**Comment by daN4cat** [comment]
@ais-one what about having a look into this see your offer in #375 to help?

Just go to sales, then click takings. If you have done some transaction on the day you will see them.

There is a print button on the top right. At the moment that prints the page but it should print a title like "Takings for <date>", the list of transactions and the totals at the bottom.

It will be useful for shops that needs to do a close of the day accounting with takings, z-report from credit card payment machine and etc.

**Comment by ais-one** [comment]
Hi just to confirm, which branch should I fork for this issue #160?
- master
- develop/2.4

**Comment by ais-one** [comment]
I think it would be easier for user if the search options for takings view is default open...

**Comment by daN4cat** [comment]
If the merging from master -> 2.4 -> bootstrapUI is not too much of a pain start with master.

In the end that was not completely finished in 2.3.4. If fine I mark this 2.3.5 instead of 2.4.

**Comment by ais-one** [comment]
1. I think it would be easier for user if the search options for takings view is default open...

2. For the fix, I would like to create two css classes in ospos_print.css
- print_show
- print_hide

To force display or hide of certain HTML elements which will have the following effect when printing:
- Can rename "List Of Sale #" to "Sales" or "Takings For"
- Hide print button
- Display Search Options
- Remove edit, receipt and invoice hyperlink columns

Please comment if this is the desired approach.

**Comment by daN4cat** [comment]
Give a go and let see. If there is some adjustment with something to see gets simpler for everybody.

Thanks for the help!

**Comment by jekkos** [comment]
I think I've added media queries for print in ospos_print css so if you add css in that scope then this should be good. Think merging from old to new shouldn't be that hard at this point (I'll try to make branches up to date tomorrow)

**Comment by daN4cat** [comment]
I'll take the latest commit and test again, but it does not work here.

Also it used to work with description and item kit name, also number if my memory is right.... but I would need to check against a pure 2.4.

**Comment by ais-one** [comment]
The work is in progress, I should finish by today. But I just have one question.

If there is many sales entries, there is  a pagination.

Should we just print the rows showed in the page? if we need to print all the filtered rows instead, then this the current print functionality is a problem because it is a sort of WYSIWYG thing.

The problem is there when the shop has a few hundred sales entries per day...

What would actually be more useful is an export to CSV function.

Any comments on this?

**Comment by odiea** [comment]
I think you are right. It's nice feature to see or to be able to reprint receipts but that is as far as it goes. I believe it is the only report that filter Invoices so an export feature would work better.

**Comment by ais-one** [comment]
Reading up on implementing csv in CI controller now. The Print will be wysiwyg for now.

**Comment by daN4cat** [comment]
Wysiwyg would do as printing. Exporting is not relevant for me because in the shop they keep a book where every day they write cash at opening and closing, staple z reports, daily takings and time people where in and out.
In case of any control they can give the books and show everything is logged. It's a matter of due diligence.

**Comment by daN4cat** [comment]
@ais-one please make sure you have the feature rebased of latest master (v2.4 that I pushed last night).
For instance your PR was not valid anymore because of the decision to skip 2.3.5 and move from 2.3.4 to 2.4 straight away.

And many thanks for the help, much appreciated!

**Comment by ais-one** [comment]
ok noted on this

**Comment by ais-one** [comment]
Hi noted, now working using new master

**Comment by ais-one** [comment]
Would the result below be ok? if yes, I send pull request, 3 files changed.

![print](https://cloud.githubusercontent.com/assets/4284574/13671582/a34941de-e70b-11e5-8b04-4d741ed847dc.png)

**Comment by daN4cat** [comment]
Looks promising, is the first top line something added by the printer driver or by the OSPOS?
I remember some rule to disable that in the receipt. Are you using the same?

Maybe the title would have been good to be "List of Sale - <date range>" and not show the date range in the filters list. What do you think?

**Comment by daN4cat** [comment]
Maybe would be nice to print the page number.

**Comment by daN4cat** [comment]
Please note that in my previous comment something was hidden. I meant to say display the date range next to List of Sale...

**Comment by daN4cat** [comment]
@ais-one how is it going with this print feature? Ready to drop something?

**Comment by ais-one** [comment]
Hi, I would like to commit as per the image above.

Very minimal impact on the code. If I were to move the date range next to List of Sale, it may look better, but I need to add a few more lines.

I was thinking maybe to move the invoices Checkbox to the right.

If this is ok, I submit pull request after I test with many sales to see effect of pagination.

**Comment by daN4cat** [comment]
Yep, move the date range by the title and pull right the chekcboxes. That sounds good to me.

Thanks for the help.

**Comment by daN4cat** [comment]
@ais-one please be aware that there are some updates in master (2.4), therefore please rebase before going for your PR. Hopefully we can get it today as I would like to merge master in bootstrapUI after your change to take the latest in.

**Comment by daN4cat** [comment]
I just tested but it doesn't look like being like in the picture.

I see the search box, the delete button and the print one. Something missing from your commits?

**Comment by daN4cat** [comment]
Sorry my fault, I should have forced a refresh such it uses the correct css. Now looks like in the picture.

**Comment by ais-one** [comment]
whew

**Comment by daN4cat** [comment]
OK, I merged in master but I've done a couple of changes:

- hidden links
- changed print id to be print_button and added style to css file

We can close this.

**Comment by daN4cat** [comment]
Now in 3.0.0 (bootstraUI) too
