### ISSUE TITLE
Cannot add item to sale if searching Kit by its name

### ISSUE THREAD

**Issue by daN4cat** [jekkos/opensourcepos#161]
From odiea:

An issue I have gotten is I am in Sales and enter kit 5 upper or lower case and the kit will come up but if I select the item kit by its name it says it cannot add item to sale.

**Comment by odiea** [comment]
The kit name did appear in the Items drop down list .

**Comment by daN4cat** [comment]
So is this still an issue?

**Comment by daN4cat** [comment]
OK, found the bug and fixed.

It's in my master.
