### ISSUE TITLE
Add price to Item Kits barcode

### ISSUE THREAD

**Issue by daN4cat** [jekkos/opensourcepos#162]
From odiea:

Is there a way to add a price to the item kit so that it shows on the barcode. Currently it doesn't.

**Comment by daN4cat** [comment]
The issue here is that there is no concept of total cost of the Item kit.

Therefore in order to solve this we need to add a total cost of the item kit and then it can be printed.

**Comment by daN4cat** [comment]
Added Kit total price in table view and barcode printout. There is cost and retail, the barcode follows the configuration to decide which one.

Fixed and in my repo.

In the PR it will be available in jekkos/master

**Comment by odiea** [comment]
Yes the barcode now displays the price. Good job.

**Comment by daN4cat** [comment]
:+1:

**Comment by jekkos** [comment]
Curious to look into this feature. Have to say that I'll be moving house coming two weeks, so I might not be on duty that often..

**Comment by daN4cat** [comment]
Even the Item Kits table shows totals for cost and retail price.

**Comment by daN4cat** [comment]
ok, in case I need to fix something, can I push the change in your master or do you prefer I hold the horses?

**Comment by jekkos** [comment]
If it's bugfixes then just go ahead.

**Comment by daN4cat** [comment]
Fix to table refresh cases.

Tested: add new kit, change a kit, cancel kit change, delete kit, add item from kit, remove item from kit, search by kit and by name, search in Sales by kit and by name, add kit to sales.

All seems fine, but I'm pretty sure I forgot some other corner case... I should really consider working on the test automation because this error&try doesn't suit me well and not that professional.

**Comment by odiea** [comment]
Is your current repository up to date and ready to be cloned?

**Comment by daN4cat** [comment]
Yes

**Comment by odiea** [comment]
I get this error after cloning the repository. Why would there be conflicts?

Author:		odiea <oagnew@aim.com>
Date:		54 seconds ago (9/19/2015 8:56:34 AM)
Commit hash:	976121923f28ee2e6a84f05c0f30f610b8d918c6
Parent(s):	461de2f048
Merge branch 'master' of https://github.com/daN4cat/opensourcepos

Conflicts:
	application/models/giftcard.php
	application/models/item_kit.php


Contained in branches: master
Contained in no tag

**Comment by odiea** [comment]
So far the only issue I see in Item kits is when I go into search (in item kits) for a kit number it says it cant find it.

**Comment by daN4cat** [comment]
The search by KIT number wasn't there, it's something I would need to add. I'll look into this next days now I need to stop.

No idea about the merge issue. One thing I did before telling you it's all fine was to amend the commit message because I put the wrong # as reference.

**Comment by odiea** [comment]
OK sounds like a good plan to me.

**Comment by daN4cat** [comment]
Search by Kit number has its own issue so we can close this one once the PR is marged in jekkos/master.
