### ISSUE TITLE
Sales Invoice auto numbering is not working.

### ISSUE THREAD

**Issue by odiea** [jekkos/opensourcepos#163]
So I am back to testing with 2 people on the system. I was able to sell from the same database with no problems at all. I tried sales invoicing and the auto numbering seems  not to be  working. I tried it on 1 terminal only. It appears to be 2 numbers out of sync. Last issued invoice was # 6 and the next number in the Invoice box shows # 5. 5 
invoice_number
varchar(32) utf8_general_ci  Yes  NULL wasn't that the same issue we had with gift card numbering? If you can think of a script to change that info and clean all the null"s out that would be great. It wont let me change it because of some conflict. So I dropped the table and changed its values. It works great for auto numbering but I got this error after removing the check mark.
Error Number: 1048

Column 'invoice_number' cannot be null

INSERT INTO `ospos_sales` (`sale_time`, `customer_id`, `employee_id`, `comment`, `invoice_number`) VALUES ('2015-09-19 18:36:18', NULL, '1', 0, NULL)

Filename: C:\xampp\htdocs\tabbed\system\database\DB_driver.php

Line Number: 330
So I changed this line from null to o but the Invoice numbers are incrementing  even if you don't check the Invoice box.
$invoice_number = $this->sale_lib->is_invoice_number_enabled() ? $invoice_number : 0;

 Would it be less coding to place the initial Invoice number into general config(instead of finding it from the sales that were done) and just updating the number in config after item number was created?
Francesco it appears that I had switched over to a different database and that is what's causing the issues. With your version Invoicing is working great.

**Comment by odiea** [comment]
![2015-09-21 15_38_56-once again thrift -- powered by os point of sale](https://cloud.githubusercontent.com/assets/10962177/10005947/575c77ac-6077-11e5-8075-3ffeb90557d2.png)

**Comment by odiea** [comment]
![2015-09-21 15_39_37-once again thrift -- powered by os point of sale](https://cloud.githubusercontent.com/assets/10962177/10005969/7f3301e2-6077-11e5-903b-92d99b83ceb9.png)

**Comment by odiea** [comment]
So I went in and deleted the prior 2 invoices and the Invoice was created correctly but after I went back into sales and it was down 2 numbers again.  Go figure. The number was at 20 so I deleted 20 and 21 when I went back into sales the number listed was 19.

**Comment by jekkos** [comment]
Ok I did a fix for invoice number increment. I've tested this by using multiple browsers on one machine. One picks up an invoice number, while the other browser completes a sale before the first.

The variables are substituted again once complete() is called for the first browser, which will make both sales succeed with a correct chronologic numbering

**Comment by jekkos** [comment]
I think the numbering really depends on the variable you choose there. $Co is substituted by the number of sales in table having invoice_number not null. So maybe the weird numbering has something to do with that?

**Comment by odiea** [comment]
This could have been the database I was using both yco and co on. That might be the problem.

**Comment by nano-riff** [comment]
I am working with 2.3.4. and have the same issues. Invoice numbers are 2 or 1 below last number, creating a conflict.
I would recommend to have the "last invoice no." be set in "Store Config". Such there is a clear control.
Thanks for helping me out, since now we write the numbers on a paper and the overwrite the "wrong" proposed number each time...

**Comment by odiea** [comment]
If your have access to your database you need to go into it and add a new invoice or 2. OSPOS works from the count of the invoices so if you delete any sales this will create an issue with the auto numbering. Numbers past 100000 work well.

**Comment by daN4cat** [comment]
We really need to remove the delete sale button...

**Comment by odiea** [comment]
Yes we do or change delete to is_deleted like Items.

**Comment by daN4cat** [comment]
I would temporarily remove it "until further notice"

**Comment by odiea** [comment]
Good Idea. Remove all the delete buttons and Indicators would fix this issue.

**Comment by daN4cat** [comment]
Created an issue to remove Sale delete option completely: #382

**Comment by nano-riff** [comment]
I still not perfectly understand the generation of that invoice number. If I understand correctly it just takes the "Count(records)" value + 1 ? 
In my case I have 147 sales records, but the invoice number that is set in a new POS entry is 146...
I think the invoice number generation should be more transparent or clear.
One could also use the unique "sales_id" as invoice number. This would help me perfectly.

**Comment by odiea** [comment]
Yes you need to go into your database and add or cahnge another record thru phpmyadmin or some other way.
