### ISSUE TITLE
Wrong value in sales/complete item total

### ISSUE THREAD

**Issue by glassen** [jekkos/opensourcepos#165]
When adding more than one of an item, the item total on the receipt displayed in sales/complete only shows the total for one item. When reviewing the receipt from Takings, the total is correct. This is using master branch from git, checked out earlier today (latest commit eee7f137e).

**Comment by daN4cat** [comment]
I've just tested with my latest (there is a pending pull request that needs to go in see #164 ) and I don't see the problem you describe in the receipt. Please check if this is a correct test scenario?

![image](https://cloud.githubusercontent.com/assets/636048/9982552/3a7fc7a0-5fd8-11e5-9ec6-8421e8d23ae0.png)

**Comment by glassen** [comment]
Mine shows like this (I've started translating to Swedish as well) but only in sales/complete. It is correct when reviewing from takings. I will try again tomorrow with a clean slate an directly from jekkos repo without my changes to translations.
![screenshot](https://cloud.githubusercontent.com/assets/14387561/9982637/389a9310-5fe3-11e5-8757-ba2a0f93b67a.png)

**Comment by daN4cat** [comment]
Translation are not the issue here.

Could you please take the latest from daN4cat/master (my repo) and give a try?
I'm pending a review before merging it in jekkos/master but mine is working and stable with several fixes.

**Comment by glassen** [comment]
Tried your repo this morning with the same results from sales/complete 
![screenshot 2015-09-21 05 45 39](https://cloud.githubusercontent.com/assets/14387561/9985047/5728b67c-6024-11e5-887e-cce302305ba6.png)

But good results from sales/receipt
![screenshot 2015-09-21 05 47 38](https://cloud.githubusercontent.com/assets/14387561/9985054/7f19b78a-6024-11e5-8dc7-7b24dac3fc4f.png)

I also note that there are decimals in quantity when reviewing the receipt from Takings (also applies to invoices discount and quantity). Also note the date difference on invoice from sales/complete and sales/invoice

![skarmavbild 2015-09-21 kl 05 53 40](https://cloud.githubusercontent.com/assets/14387561/9985101/478436d2-6025-11e5-8b69-35cfa01f981f.png)

![skarmavbild 2015-09-21 kl 05 57 28](https://cloud.githubusercontent.com/assets/14387561/9985120/ac35de46-6025-11e5-96eb-f2931af34886.png)

**Comment by daN4cat** [comment]
I cannot really reproduce this issue. I'll check next days to see if I can find any condition triggering the problem.

With regards to the other two issues about quantity with decimal and invoice date, yes I can see those.
Thank you for spotting those, I'll try and fix next days.

**Comment by odiea** [comment]
Doesn't ospos use the system time clock? It appears that the system time was off and not updated yet. That date I think is the Windows default time if the time clock is off. They may have a bad keep alive battery.

**Comment by daN4cat** [comment]
1/1/1970 is the starting of the times in PHP and similar. It has nothing to do with the clock and etc. The bug is there to be fixed :-)

**Comment by odiea** [comment]
Thanks. Keep up the good work.

**Comment by glassen** [comment]
I have been trying to get correct and incorrect values on my receipts this evening. I noticed that if I:

1. Add one item
2. change the quantity to say three
3. press "Edit Item"
4. add payment
5. complete the sale

Everything is correct, but if I instead:

1. Add one item
2. Add the same item again by searching or scanning barcode
3. Add payment
4. Complete the sale

I get the wrong item total like my previous screenshots. Is this reproducible for someone else?

**Comment by daN4cat** [comment]
Thanks a lot to report the exact test procedure, I will try to reproduce the bug and look into this next days together with the quantity and date bugs.

**Comment by jekkos** [comment]
Do you have serialization enabled on the item? I tried this procedure but couldn't reproduce the bug in the last case.

**Comment by odiea** [comment]
Is this what they are referring to.
![2015-09-24 05_26_24-once again thrift -- powered by os point of sale](https://cloud.githubusercontent.com/assets/10962177/10072223/18b0e698-627d-11e5-8bd5-13cebdd1c429.png)

**Comment by daN4cat** [comment]
yes, that's the case, the total on the right for the 3 items is not correct and should be = Sub Total.

**Comment by jekkos** [comment]
I added some logic some time ago to show this price with discount included or not. There might be an error in there. Think we should consider to add some phpunit tests in the future (just to test models + controllers) for obvious errors like this one.

everything that does not involve screen interaction can be covered and run automatically on travis, would be nice to have.

**Comment by jekkos** [comment]
https://github.com/fmalk/codeigniter-phpunit

**Comment by glassen** [comment]
I appreciate that you are looking into this. I don't feel familiar enough with the code base, nor experienced enough to squash this bug myself. Otherwise I would :)

**Comment by daN4cat** [comment]
I have a fix to the invoice date issue and I also found that the amount due was using a different font compared to the rest of the invoice, and I fixed that too.

I'll push that change for a quick PR.

That solves just one of the 3 issues, totals and decimals still to go.

**Comment by daN4cat** [comment]
The invoice date fix is now in master.

Totals still need fixing.

**Comment by jekkos** [comment]
Ok I had a look and fixed the issue. The error only appeared when adding items mulitple times through the search bar, thus only in case when scanning it multiple times eg.

Problem was that the quantity was updated after the totals calculation in that case, which caused the latter to be incorrect. The code also includes some extra logic for serialized items, for which I have done some retests and which looks ok as far as I can see.

**Comment by glassen** [comment]
Great work! My sincerest thanks since I was not able to solve it myself.

**Comment by glassen** [comment]
This issue is now fixed in my tests. Thank you!
