### ISSUE TITLE
Did I screw up my database ?

### ISSUE THREAD

**Issue by odiea** [jekkos/opensourcepos#166]
After going into takings the default sales for the day show up just fine. If I check cash or change the date the only item that shows up is the first sale from 6 months ago.

**Comment by daN4cat** [comment]
What do you see from Reports/Detail Reports/Sales?

I checked with my test database and see no problems:

![image](https://cloud.githubusercontent.com/assets/636048/9982575/fef84dc8-5fd8-11e5-8dc3-3acf9f43560e.png)

![image](https://cloud.githubusercontent.com/assets/636048/9982579/15b81912-5fd9-11e5-8a56-8ff9db1c48a6.png)

![image](https://cloud.githubusercontent.com/assets/636048/9982583/281d6b0c-5fd9-11e5-8a2c-4db330eb165d.png)

![image](https://cloud.githubusercontent.com/assets/636048/9982588/4d0721a6-5fd9-11e5-93b0-ac5bd3885f36.png)

**Comment by odiea** [comment]
In detailed sales reports I have no issues.

**Comment by daN4cat** [comment]
And do you use my latest master?

**Comment by odiea** [comment]
I changed it back to var char and the list of items shows ok and Invoice numbering is working again! Do you have plans on putting pagination into the Takings list?

**Comment by daN4cat** [comment]
not sure I can follow, why the change in your Database?
I never changed anything around this area in my database and all seems fine.

Pagination in Takings? Not sure. But that's another issue. Please add a request for that.

That said, shall we close this?

**Comment by odiea** [comment]
In Gift cards we found using var char was causing the numbers to not Increment properly so we changed it to Int. I tried the same with Invoice number (I still have an issue with another database that's not auto Incrementing the Invoice numbers. It's always 2 numbers behind what I last had to enter. So Yes I will close it now. Thanks for your help.
