### ISSUE TITLE
Database error on suspend sale

### ISSUE THREAD

**Issue by nhooverapg** [jekkos/opensourcepos#167]
When suspending a sale, the following database error occurred:

A Database Error Occurred

Error Number: 1406

Data too long for column 'description' at row 1

INSERT INTO `ospos_sales_suspended_items` (`sale_id`, `item_id`, `line`, `description`, `serialnumber`, `quantity_purchased`, `discount_percent`, `item_cost_price`, `item_unit_price`, `item_location`) VALUES (1, '1', 1, 'Douglas Fir Cut Your Own Christmas tree', '', 1, '0', '25.00', '41.00', '1')

Filename: /~/models/sale_suspended.php

Line Number: 98

**Comment by odiea** [comment]
description  is set at varchar(30) so I believe it will only hold a max of 32 characters and it looks like your desc is around 39 characters. If you need long descriptions your going to have to change your database settings or use a shorter desc.

**Comment by daN4cat** [comment]
So it sounds like there is a limitation with the database definition with certain fields.

Any list in mind of what should extended?

**Comment by jekkos** [comment]
description is used as an override of the standard item name. in this case it shouldn't indeed bee too long as it's supposed to fit in the item overview on the receipt / invoice.

an extra validation in edit_sale step might also be an option here? I hardly ever encountered a situation that required more than 30 chars for this field.

**Comment by daN4cat** [comment]
yep, probably a sanity check is what we should have.

**Comment by nhooverapg** [comment]
seems to me that if the description field accepts a certain length during the create item process, the suspend sale module should be able to handle that same length, especially since it's a temporary structure- shouldn't have that many records in the suspend sales database at one time.

or, conversely, if the description field should be limited due to fitting in the item overview on the receipt, then it should be restricted on item creation (and this bug would be moot).

in any case, the length of the database fields for the same information should be the same.

**Comment by daN4cat** [comment]
Description in items is a varchar(255) and then in sales_items and sales_suspended_items is a varchar(30). I guess there is no check that the description is truncated for the sales tables.

**Comment by odiea** [comment]
Description in items is a varchar(255) should the description length be change so no other modifications need to be done.

**Comment by daN4cat** [comment]
Not sure, sales and suspended_sales copy the description without any string truncation.

I made a change to limit the description to 30 before it's saved in sales or suspended_sale tables.

I'm going to submit the fix at least in my master.
