### ISSUE TITLE
Items kit view: add search by KIT Id

### ISSUE THREAD

**Issue by daN4cat** [jekkos/opensourcepos#168]
At the moment you can search a Items Kit only by name, contrary to what you can do from the Sales view where you can search by Kit Id (required because of the barcode) and Kit name.

The items kit view should allow searching by KIT Id, hence allowing the barcode scanner to fetch a Kit automatically.

The issue was originally posted in #162

**Comment by odiea** [comment]
If you can setup Issues on your fork let me know and I will send them to you.

**Comment by daN4cat** [comment]
It's better to keep issues here, not in forks because my fork is for my convenience and I keep submitting changes to jekkos/master.

However at certain point I would need to split things because in my wife's version I need to introduce some fields instead of the custom one and add them to the search, reports and sales.

**Comment by daN4cat** [comment]
This is now fixed in my master and ready fora PR

**Comment by odiea** [comment]
Yes it works fine.

**Comment by daN4cat** [comment]
Good
