### ISSUE TITLE
Do we need 10 custom fields?

### ISSUE THREAD

**Issue by daN4cat** [jekkos/opensourcepos#172]
I was just wondering about these custom fields in the items table, do we really need all or let say 5 are enough?

Thoughts?

**Comment by odiea** [comment]
In my version it was easy to use at least 5 of them. Date(no longer needed) Size, condition, color and tag color.

**Comment by daN4cat** [comment]
Thanks for the feedback.
So if we add Color and Size we could reduce some.
I think Condition together with Season would make other two good addition for clothing & vintage (+ your case of course) businesses.

Could you please expand on the Tag color point? What do you identify with that?

**Comment by odiea** [comment]
All Items are Either labeled or tagged. Colored barcode labels or colored tags that are attached to the items. Tags for clothing or most things made from materials such as cotton. I was going to setup a tag color field so I could experiment with Sales off percentages. Say 1 day blue tags are 50% off and red tags are 10% off. The only way the system is going to do this is with a tag_color field to filter. As far as Tax issue it was solved after I removed the zeros. Don't know how they got there either.

**Comment by daN4cat** [comment]
OK, so there are rules attached to colour tag affecting discount depending on day/time.

My wife used the tag colour during Sales time but then discount was all a manual job.

I need to think a bit more about this and rules story.

**Comment by jekkos** [comment]
So in that case you'd assign a label  based on a rule for an item ? Sounds like some kind of 'smart category' feature?

**Comment by odiea** [comment]
I guess it would be adding the Date picker, The percent off and the Tag color to give an automatic percent off at sale time like the current discount feature in General config does.

**Comment by odiea** [comment]
Would it be easier to put Categories on sale?

**Comment by daN4cat** [comment]
Ideally you should have discount rules attached to Items grouping fields (e.g. Category, Tag) and apply it temporary for discounting purposes.

But this needs to be thought through properly, and I have no time now to figure it out correctly.

**Comment by daN4cat** [comment]
#68 covers the issue in a more generic way.

#173 is connected to this as well.

**Comment by jekkos** [comment]
OK thanks for the issue references. Ok to close this one as I'm kind of losing the overview in the issue tracker.

**Comment by daN4cat** [comment]
Close to keep just #68 open as this is just a use case.
