### ISSUE TITLE
Would adding Colour, Size and Season fields to Item of any interest?

### ISSUE THREAD

**Issue by daN4cat** [jekkos/opensourcepos#173]
For my case that is related to a fashion boutique I would need to add in master or a branch Colour, Size and Season fields to Item table.

Also the season will be needed in sale table to keep track of what has been sold by season since some items can be restock season by season and the Item field gets updated.

The three additional fields would need to be added to various reports, so maybe this should be more a branch rather than in master but I want to hear from other people about this variant.

**Comment by odiea** [comment]
In the thrift business the Bigger companies have a lot of different things. Categories,Items,Items descriptions, New Used Size Color and Items price rates different prices for item good bad great and so on. I don't expect this program to get that big but it might benefit others as well.

**Comment by daN4cat** [comment]
As replied in #172 , it might make sense to have Color, Size, Condition, Season and maybe something more and reduce the custom to let say 5.

I believe Category, Description are already part of Items.

If these fields are added I think I should add in the configuration the option to show them or not in Item add/edit, and various report + receipt.
So people can customise views according to their needs without forcing the rest of the world to stand to things they don't need.

Maybe we should define a core set for Items and an extended all optional set.

**Comment by jekkos** [comment]
My idea was to generalize this concept into configurable categories. I have a code branch in which you can define those categories, but only through direct database setup.

In this branch you can assign attributes to a category definition. In this case you would add size, color, etc to the clothing category. Once you select clothing from the dropdown, the input boxes for the added attributes show up.

The code needs some polishing in the sense that I had to figure a way to enter these categories easily in the config screen. I probably should look for some easy to use widget like a datatable with configurable hierarchy. If anyone feels like looking into this then I'll push this branch to github here.

**Comment by daN4cat** [comment]
Sounds like a nice feature, would you like to share it via a different branch?

**Comment by jekkos** [comment]
The branch is not completely up to date with master yet. I'll push it in now and then see if I can merge it with the latest later on.

**Comment by jekkos** [comment]
the feature/quantity units branch contains those modifications. Beside adding the configurable categories, you can also add new units to items, llke kg, m, liters (for bars eg).

Also there's another feature in the register that allows one to do conversion between units, kgs and m in this case, to do a stock taking (could be useful for fabric shops)

**Comment by jekkos** [comment]
This branch superseeds the item_sizes.

**Comment by daN4cat** [comment]
ok, thanks. I'll have a look in the next weeks once some bugs are sorted and KIT search feature too.

**Comment by daN4cat** [comment]
#68 covers the issue in a more generic way.

**Comment by daN4cat** [comment]
Close to keep just #68 open as this is just a use case.
