### ISSUE TITLE
Add option to config page to enable/disable invoicing feature

### ISSUE THREAD

**Issue by odiea** [jekkos/opensourcepos#174]
Is there a way to add Use Sales Invoicing to the general config . Your Invoicing is different than our Invoicing so it would be nice not to show that feature in Sales.

**Comment by daN4cat** [comment]
You mean to disable the invoicing business in general with a config checkbox?

I thought about the same because in my wife's case there is no use and it might confuse things with sale assistants or generate errors (see the invoice numbering story).

**Comment by jekkos** [comment]
What about renaming invoice_number to sale_reference and receiving_reference? 

All the related labels should then be renamed as well. This feature can be thus be used in a more general way (stores may have specific needs to label their sales and receivings using reference numbers coming from suppliers or maybe they require to have their own format next to the regular sale_id's)

**Comment by odiea** [comment]
Now that you have it working properly  I don't see any issues with keeping it the way it is.
