### ISSUE TITLE
Item Kits on Home Page not there

### ISSUE THREAD

**Issue by odiea** [jekkos/opensourcepos#179]
Has anyone noticed that Item Kits doesn't show on the Home Page? Also is it possible to get suspend sale to show on the screen next to Cancel before you hit add payment? 
 I did change desc to 30 and it truncated it ok with no database issues.

**Comment by daN4cat** [comment]
What do you mean not showing on the Home Page? The icon on the top bar?
Have you checked that you have the grants to see everything as user?

Yes, the forced payment before suspending a sale is annoying indeed and I created #180 to cover that issue.

Description truncation to 30 is now fixed and anyway part of #167.

**Comment by odiea** [comment]
When a person first logs onto ospos it displays a home page loaded with the Icons that are shown across the top menu bar. But on the Home page Item kits does not show.

**Comment by daN4cat** [comment]
OK, I've got what you mean. Items kits is not visible from that page indeed.
I'll check what's the issue behind that.

**Comment by odiea** [comment]
On the Home page if you comment out or remove the following it shows fine. 
//if (sizeof(explode('_', $module->module_id)) == 1)//
		//{//

**Comment by daN4cat** [comment]
Yes, the navigation bar is as follow:

		<div id="menubar_navigation">
			<?php
			foreach($allowed_modules->result() as $module)
			{
			?>
			<div class="menu_item">
				<a href="<?php echo site_url("$module->module_id");?>">
				<img src="<?php echo base_url().'images/menubar/'.$module->module_id.'.png';?>" border="0" alt="Menubar Image"></a><br>
				<a href="<?php echo site_url("$module->module_id");?>"><?php echo $this->lang->line("module_".$module->module_id) ?></a>
			</div>
			<?php
			}
			?>
		</div>

No idea why things are different between the two.

**Comment by daN4cat** [comment]
For sure this line if (sizeof(explode('_', $module->module_id)) == 1) has an issue with the fact that Items Kit module is called item_kits, where no other module (e.g. giftcard) has a _ in its name.
I'll try and rename the module to itemkits but I need to check the counter effects of it with various testing. Also the database entry would need a renaming when upgrading to the new version.

**Comment by daN4cat** [comment]
By the way, do we want the home page to be a table view instead of a list view like it is now?
I don't find that handy having the current view like that. Thoughts?

**Comment by daN4cat** [comment]
I went for the removal of the if statement since I don't see point for that and the fix is in my master.

**Comment by odiea** [comment]
I prevented the Icons from loading so it doesn't look to bad. I was thinking about leaving the module list and linking the module name to a help page.

**Comment by jekkos** [comment]
Indeed this check didn't do anything good there. Was a remniscent of the first attempt on implementing subpermissions. Thanks for fixing this.
