### ISSUE TITLE
Since this mornings pulls I am getting this issue

### ISSUE THREAD

**Issue by odiea** [jekkos/opensourcepos#181]
I now have this issue on sale suspend. Your current zip is now giving me that issue after I tried a couple of times. Also the items in sales are not sorting properly. I looked back into my earlier installs 8/14/2015 and the issue is there also. So it's really not new.

![2015-09-27 11_54_24-once again thrift -- powered by os point of sale](https://cloud.githubusercontent.com/assets/10962177/10124284/b3fa301c-650e-11e5-855d-194101dad8d6.png)

**Comment by daN4cat** [comment]
I've got this issue but I thought it was something I messed around so I ended up removing all the invoice numbers from the sales table so to restart from 0.
Only at that point I could use it again. Not sure which condition causes this, but probably the suspend and unsuspend could be one. Another thing could be a refresh of the Sale window or cancel and create a new sale.

I think we need to find the pattern to create this issue as it blocks the functionality if you use invoices.

**Comment by odiea** [comment]
Yep.

**Comment by odiea** [comment]
In controller sales would it help any to include here " is invoice number enabled"? It appears it is finding a random invoice number somewhere. This happens with invoice enabled or disabled.
if ($this->Sale_suspended->invoice_number_exists($invoice_number))
		{
			$this->_reload(array('error' => $data['error']=$this->lang->line('sales_invoice_number_duplicate')));
		}

**Comment by daN4cat** [comment]
No idea, I haven't implemented this invoice business so I have no idea what the logic is.

**Comment by odiea** [comment]
After playing with it some more I have found that if there is already a suspended sale It gives that error but if you unsuspend that sale then suspend another sale it will work.

**Comment by daN4cat** [comment]
And suspending multiple sales will be prevented by this issue with the invoice numbering.

**Comment by jekkos** [comment]
I'll have a look once I find the time

**Comment by odiea** [comment]
In the database under sales_suspended it is storing the current invoice number even if it's not enabled.

**Comment by odiea** [comment]
models\sale_suspended.php
line 50 function save I removed &invoice_number
line 60 I edited out invoice number in the data array

controllers\sales
Comment out line 766
comment out lines 776 thru 781
comment out line 810

I chopped it up but it appears to function properly .

**Comment by jekkos** [comment]
The 'invoice number' feature should of have been named something like 'sale or receiving reference' instead, as it's just a way to assign unqiue refer

it seems that once a sale is suspended, the invoice number is copied along. If the format consists of $CO then the counter is not incremented and so the next sale will have the same invoice_number. 

This situation will stop the suspend as the invoice number is already saved there in the new table. 

* This could be solved by replacing the suspended sales tables with a regular flag in the original table, so the numbering will always be unique
* The fix I'm currently doing is replacing the $CO variable with $SCO on suspend time. This way the numbering will follow what is currently the last number in suspended sales + 1 and should be reassigned once unsuspended

**Comment by odiea** [comment]
I have tested this situation a few times and have found out that if the invoice number is not stored at all that the un-suspended sale will then pickup the next available Invoice number.

**Comment by daN4cat** [comment]
I think assigning a progressive number to something just sketched and suspend is probably not ideal.
Maybe if we avoid the assignment in suspended it will make things easier?

Also, should we make the invoice matter optional from configuration?

**Comment by odiea** [comment]
The only strange thing I have seen so far is after you suspend a sale comments show a 0. Any reason for this?

**Comment by daN4cat** [comment]
Jekkos, any plan to get this bug and #165 sorted?

I tried to work out most but I cannot take the whole lot and no beers :-)

I would like to focus on improving a couple of things and then add the size/colour/season story as that's what I need in the end.

**Comment by odiea** [comment]
A Database Error Occurred

Error Number: 1062

Duplicate entry '73' for key 'invoice_number'

INSERT INTO `ospos_sales_suspended` (`sale_time`, `customer_id`, `employee_id`, `comment`, `invoice_number`) VALUES ('2015-10-08 18:05:51', NULL, '2', '', '73')

Filename: C:\xampp\htdocs\osposmaster\system\database\DB_driver.php

Line Number: 330
I am still getting this error on sale suspend from your current pull.

**Comment by jekkos** [comment]
You will have to drop the unique constraint for the suspended sales table (statement is in the database script I added)

**Comment by daN4cat** [comment]
Is this issue sorted now? Can it be closed?
