### ISSUE TITLE
Improve the date-input field

### ISSUE THREAD

**Issue by marteserede** [jekkos/opensourcepos#183]
There are problems with the validation of datetime values, for example when editing the date of a sale afterwards via the sales-report, since the date and time value is just put in a simple text-field and in the dateformat chosen in the app-config.
It is validated via javascript and the date object might not recognize the given format as valid. furthermore the user can change the format of the date which might result in errors.
Therefore it would be good to implement a date field which works with a date-picker, drop-down-menus or a few small input fields like it is done in Wordpress.
See Pullrequest #169 for more information.

**Comment by daN4cat** [comment]
So we just need to fix the date entry in the sale edit view. I don't remember other direct entry cases.

**Comment by jekkos** [comment]
WIll close this issue (#169)
