### ISSUE TITLE
Undelete item on customer return

### ISSUE THREAD

**Issue by daN4cat** [jekkos/opensourcepos#184]
Scenario:

- a last item is sold setting to 0 the quantity (no restock as it's a seasonal item)
- later the item is deleted by OSPOS admin/stock control user
- within refund /return time the item is part of a customer return
- the item quantity is added to the database but left as deleted

Expected outcome:

- the item is undeleted and with the correct quantity

**Comment by odiea** [comment]
Good scenario. Would it be easier to prevent the item from being deleted if it's still within it's return  period?

**Comment by odiea** [comment]
If the customer returns with a receipt or you can find the receipt in Takings then the time issue would not be a problem. I think that's why I preferred Returns be based on receipts and not on items.

**Comment by daN4cat** [comment]
Made the automatic undelete in case of returned item possible.
