### ISSUE TITLE
Using POS numbers in returns 

### ISSUE THREAD

**Issue by odiea** [jekkos/opensourcepos#186]
When I return an item from a pos number nothing happens it actually decreases the Inventory amount instead of increasing the amount. The only thing it does is shows a negative number in the total amount. I just found out that the Item qty has to be adjusted to a minus manually it's not automatic like selecting an item does. More info for a help file. So here is some early code from Jekko . When you click into the box on returns nothing shows. But you can still search for items or pos tickets.
function item_search()
	{
		$suggestions = array();
		if ($this->sale_lib->get_mode() == 'return') 
		{
			$this->sale_lib->is_valid_receipt($this->input->post('q')) && $suggestions[] = $this->input->post('q');
		} else {
			$suggestions = $this->Item->get_item_search_suggestions($this->input->post('q'),$this->input->post('limit'));
			$suggestions = array_merge($suggestions, $this->Item_kit->get_item_kit_search_suggestions($this->input->post('q'),$this->input->post('limit')));
		}
		echo implode("\n",$suggestions);
	}

**Comment by daN4cat** [comment]
Just to make sure I understand the use case here:

- User goes to Sale Register (view)
- User selects Return from Register Mode drop down
- User types or scan a POS receipt (let say POS 2)
- Items appear in the view but not with negative Qty

If that's the case, I tested with mine and I see:

![image](https://cloud.githubusercontent.com/assets/636048/10186772/91b34b9e-674b-11e5-95bc-3988256c0fce.png)

It looks to me like it's negative. And as the picture says before passing the transaction there is 1 in stock.

The receipt looks good to me:

![image](https://cloud.githubusercontent.com/assets/636048/10186831/f6ca1922-674b-11e5-8ca4-8e65480c0571.png)

And the quantity was before:

![image](https://cloud.githubusercontent.com/assets/636048/10186842/10d39a32-674c-11e5-97cb-619d828e8bec.png)

and after is:

![image](https://cloud.githubusercontent.com/assets/636048/10186862/3022b03a-674c-11e5-9127-e30cc4dff41f.png)

All looks fine to me unless we are talking about a different use case that I'm not aware?

**Comment by odiea** [comment]
I should have looked at the pos numbers first. All the sales I choose to practice with were already returns.

**Comment by daN4cat** [comment]
OK. Good scenario to return a return, I didn't think about that case.
