### ISSUE TITLE
Items: partial suggestion cannot be searched

### ISSUE THREAD

**Issue by daN4cat** [jekkos/opensourcepos#187]
If you start typing an item name, or supplier, or category, you get a list of suggestions but if you ignore them and just type enter you don't get a search result by partial string search typing.

In the old OSPOP (e.g. 1.1) it used to be possible.

**Comment by jekkos** [comment]
For some reason the default submit action for the search form in items module was not triggrered when hitting enter in the search field. This should be default browser behavior. 

When I try to search for the parent form using jquery starting from the search input field I find no results (which might point to a malformed DOM somewhere in the items page).

Currently I've added an explicit key handler on the search field in this case to resolve the issue (however a better fix might be to spot the wrongly positioned element?)

Might have something to do with the fact that the search form contains too much other elements as well.

**Comment by jekkos** [comment]
Think this issue is resolved now in the latest version. Will close this one for now.

**Comment by daN4cat** [comment]
Thanks, I had really no time to catch up with this and close my Barcode issue.
I need to apologise for that but I had a peak of work and then family claimed back more time from me.

I hope to find the time to resume and close that issue and progress a couple of more I need in order to switch the current system to the new version.
