### ISSUE TITLE
A PHP Error was encountered

### ISSUE THREAD

**Issue by 3sprince** [jekkos/opensourcepos#188]
A PHP Error was encountered

Severity: Notice

Message: Only variable references should be returned by reference

Filename: core/Common.php

Line Number: 257

**Comment by odiea** [comment]
Please supply more information. Operating system and OSPOS version.

**Comment by daN4cat** [comment]
And of course a test scenario to reproduce it.

**Comment by daN4cat** [comment]
BTW, do you have the file config.php under application\config directory?
That error comes from Code Igniter (something we use, we don't touch) and that part relates to config.php.

**Comment by 3sprince** [comment]
i short out the error i change a file

**Comment by daN4cat** [comment]
And which file did you change so we can know how to solve this issue next time it pops up?

**Comment by daN4cat** [comment]
I close this, there is no follow up as far as I can see.
