### ISSUE TITLE
how to add a jquery plugin and how to minimise js?

### ISSUE THREAD

**Issue by daN4cat** [jekkos/opensourcepos#190]
I wanted to try a different date time jquery plugin (even to solve the sale edit issue) and although I replaced all the references in the required places (e.g. header.php) I found that if I don't add the ?debug=true the minified version of js is sent over (obviously).

I tried to add the jquery plug in code to opensourcepos.js and then used a webtool to create a min version. However I don't seem to succeed and get a js error.

Jekkos, would you mind to describe what's the correct approach to add a jquery plugin and how to get a correct min.js?

**Comment by jekkos** [comment]
You ca

**Comment by jekkos** [comment]
Maybe you do need to install node package manager (npm) first .. so then you will enter following commands

   npm install --save-dev
   grunt

**Comment by daN4cat** [comment]
Thanks, I'll have a look into it next days.

**Comment by daN4cat** [comment]
Do you use Linux machine to run those commands?

**Comment by jekkos** [comment]
Yes indeed. To install grunt you will first need to install the node package manager. There's a config file present in the project that defines the required dependencies. Then once this install is done (so you have npm on your terminal path), you can run grunt which will minimise the available javascript and add the new files to the header.php

**Comment by daN4cat** [comment]
OK, I'm using Windows for other reasons. I installed the Node.js stuff, but I believe I need some more steps because if I run your gruntfile.js it doesn't work. I'm not familiar with all of this so I need to find my way.

**Comment by jekkos** [comment]
Yes node is like the new package manager for most webdev projects. Think it's worth it to have a look at it as it's quite unevitable these days.

**Comment by daN4cat** [comment]
Yep, got it. As said in the past, I'm learning a bit about of all this as well. So I get stuck where I'm not familiar and then ramp up my knowledge before I can proceed.

That's the beauty of dealing with a open source project in your pastime. You have the time to play and learn with no pressure. At least on my side.

**Comment by jekkos** [comment]
Yes indeed, it brings good opportunities to learn a bit beside the things you do in your daytime job.. Next thing I'd like to add is a DockerFile for ospos, which would ease the setup a lot. It would install a lamp stack automatically, configure the db and setup CI with the correct php / mysql configs so people can test the project without any hassle. Cool thing is that the travis ci setup does somethingsimilar, except that it's not containerized yet. As they moved to docker as well this config could be reused to run integration tests on the project.

**Comment by daN4cat** [comment]
OK, I've got this fine and running now.
