### ISSUE TITLE
Comments and Suspend 

### ISSUE THREAD

**Issue by odiea** [jekkos/opensourcepos#192]
It appears that since the Suspend Button was moved now the comments don't work when you suspend the sale even if you go to add payment then enter a comment and it's then suspend it's not being stored in the unsuspend form . Just 0 shows. If you complete a normal sale it functions properly. Like you said one thing is fixed but it might break other things.

**Comment by jekkos** [comment]
Comments should be save with an ajax call when changing the field itself (jquery.change). Maybe it's just not copied properly to the suspend table? Will need to look into that further.

**Comment by daN4cat** [comment]
Fixed and in my master.

The issue was that for a strange reason the comment was fetched directly from the form instead of using the sale_lib->get_comment like in the rest of the code.

So my changes spotted a bug in the code.

**Comment by odiea** [comment]
It now stores a comment but if there is not a comment it still shows a 0. I don't know why that bothers me.

**Comment by daN4cat** [comment]
OK, the 0 is a different matter. It has been there for ages, at least since late 2011.
I'll have a look and see if there is something I can do to remove it. It's in any comment that has not be filled in, either suspended or completed. It's a constant.

**Comment by daN4cat** [comment]
OK, I fixed the comment with 0 issue and it's in my master. I'm going to do a PR.

**Comment by odiea** [comment]
Thanks for finding and fixing this issue.

**Comment by jekkos** [comment]
Maybe we should also add an update statement that removes these 'empty' comments from the database.

**Comment by odiea** [comment]
That would be a good idea . Makes things look a lot cleaner.

**Comment by daN4cat** [comment]
You mean clean the all the 0's. Yes it sounds a good idea indeed. But we need to make sure it's =0 not LIKE %0% otherwise we might mess up existing comments having a 0 in it (just to state the obvious here)

**Comment by jekkos** [comment]
Yes indeed, only update comments that exactly equal 0.

**Comment by daN4cat** [comment]
odiea, could you please check the latest fix with sale and receiving, with or without suspend for sales?

I tested and it seemed fine with me, I also checked that suspending and unsuspending the other fields are correct. But again, you never know.

If all fine after odiea test we can close this issue.

**Comment by daN4cat** [comment]
I must admit that this 0 issue bugged me for many years but never found the time to fix it.

Just one line of code in the end....

**Comment by odiea** [comment]
Sales test with no comment - ok  test with comment ok. I tested with both sale and return, Invoice on or off. Receiving's also tested good. comments showed ok in reports and item - details - item remarks looked good. I think you got the issue fixed.

**Comment by jekkos** [comment]
Haha same thing, I've seen this 0 appear from time to time.. good job

**Comment by odiea** [comment]
Not a bug but another modification. I moved the logic for
 if ($payments_cover_total)
				{
					echo "<div class='small_button' id='finish_sale_button' style='float:right; margin-top:5px;'><span>".$this->lang->line('sales_complete_sale')."</span></div>";
				}
             ?>
			</div>
to under under the add payment form and now I get a nice complete sale next to the add payment button.

**Comment by daN4cat** [comment]
OK, good. I close this.

I'll check the flow and see if something sensible can be added for the completion, but I think the big change was just allowing the suspend before any payment and fix this comment issue.

**Comment by jekkos** [comment]
I noticed that the 0 kept appearing when suspending a sale. I've changed the null check with an empty() which will return true if the comments are null or false ? 

I have also removed the unique constraint on the invoice number column for suspended sales. I like to keep that column and then do the unique check only when the user tries to complete an unsuspended sale.

Also there was a bit of code that allowed one to resume a sale using it's invoice number (by entering it directly in the search field). I removed this block and in return for that I will try to think of a way to make suspended sales a bit more managable. Currently the list piles up in the popup after some time and users need to scroll through tons of historical data just to find the row to resume.

**Comment by daN4cat** [comment]
I'm not sure somebody wants to suspend many sales. It doesn't make sense to me.
But for your Multi case you want to make sure this is managed properly. You may want to suspend in one POS station and maybe resume from another.

But again not sure you need huge lists.

About the 0, it's strange because I tested that scenario and there was nothing. Anyway, empty() is probably better than == null. Good change.

**Comment by jekkos** [comment]
Database will need to be updated (drop unique key for invoice_number in suspended_sales) before the suspend will work properly (with invoice numbers)

**Comment by jekkos** [comment]
Yes I guess that most of the time sales just need to be cleaned up, which can currently only be done by unsuspending and deleting them. Might be a better idea to add a delete button instead?

**Comment by daN4cat** [comment]
BTW, is #181 solved by those submissions? I'm getting lost about what is what now :-)

**Comment by jekkos** [comment]
Exactly, I didn't find the correct issue number so I posted my comments in the wrong one.
