### ISSUE TITLE
PHP Fatal error:  Can't use method return value in write context in <..>/pos/application/libraries/Sale_lib.php on line 44

### ISSUE THREAD

**Issue by daN4cat** [jekkos/opensourcepos#196]
Hi,

the change from:

    	return $this->CI->session->userdata('comment') != null ? $this->CI->session->userdata('comment') : '';

to

		return empty($this->CI->session->userdata('comment')) ? '' : $this->CI->session->userdata('comment');

Causes an error to me as per title.

**Comment by jekkos** [comment]
when exactly do you get this error? I just completed two sales with added commens without problems. Also in latest version there is no code on line 42 (just a comment line).

**Comment by daN4cat** [comment]
The line 42 is in theory the comment:

// avoid returning a null that results in a 0 in the comment if nothing is set/available

because I just made the change in my test server without that comment and CR it is the changed code.

So in the official code is line 44. I amend the title.

But bottom line that change breaks things for me, and it happens as soon as I try to enter Sales. White screen and an error.log with that line as per title.

**Comment by daN4cat** [comment]
Note: I run my test server on a hosted VPS which is a Linux machine with Apache and MySQL and etc.

**Comment by jekkos** [comment]
Looks like this is a php version issue. I'm running [php 5.5](http://stackoverflow.com/questions/1075534/cant-use-method-return-value-in-write-context) which doest show this issue.

But I agree I should probably just add a false check beside the one that was previously present.

**Comment by daN4cat** [comment]
Yes, this works fine now.
