### ISSUE TITLE
Have you thought about adding a non taxable service item

### ISSUE THREAD

**Issue by odiea** [jekkos/opensourcepos#200]
I think if you did that the service industries could use this program.

**Comment by jekkos** [comment]
would an item with no inventory values qualify as a service item?

**Comment by odiea** [comment]
A labor item would work? I was thinking it could have its own sort Like refund or return so that when the labor is added into the point of sale all labor items would be at the top of the list than parts would be added additionally . Labor Item 30000 mile maintenance or Replace the pump on your washing machine something of that nature. The labor page would get its flat rate hour from config. Kinda like sales tax. Then the qty would be their flat rate time. Just an idea after being in the automotive for 30 yrs.

**Comment by jekkos** [comment]
maybe this labour item can then be defind as a new 'quantity unit', in this case hours, having no entries in the inventory system (as it would not make sense to include these items in eg inventory reports which define stock value)

**Comment by jekkos** [comment]
Some work from the quantity units branch could be reused to accomplish this..

**Comment by odiea** [comment]
Ya and I figured suspended sales could then be used to store saved estimates.

**Comment by jekkos** [comment]
think it might be a good idea to enable/disable inventory tracking for quantity units. for example you define hours as a new quantity, and then have the choice to use inventory or not for items using this specific unit. This switch will then decide whether items having that unit show up in inventory value reports or not. (see 4d900c88d478e16abf66f33c42dee50ca85e798f branch)

**Comment by daN4cat** [comment]
Somehow connected to #68

**Comment by SteveIreland** [comment]
What would need to be added to this in order to be able to flag this as complete?  

In my experience taxing can be a very complicated process and needs a subsystem of it's own since taxing entities have their own set of governing rules.

However, for simple uses limited to one taxing entity we do now have a stock_type field that could be used to influence whether or not an item is taxable or not -  or we could add a flag to categories that would determine whether or not items in a particular category are taxable.

**Comment by odiea** [comment]
Here in Colorado Labor is not taxable. Can you think of a way a non taxable organization can be excluded at POS? Again thanks for this commit.

**Comment by odiea** [comment]
I forgot that the Customer has a non taxable check box.

**Comment by SteveIreland** [comment]
Right, a customer's non-taxable status normally (at least for most tax entities that I'm aware of) overrides an item's taxable status..

**Comment by daN4cat** [comment]
And have we tested if this piece of functionality is still fine? I never tested and neither looked into it, as an obvious never used too.

**Comment by odiea** [comment]
Yes. The sales tax override for customers still works.

**Comment by daN4cat** [comment]
So do we still have this problem?

**Comment by SteveIreland** [comment]
I ran a quick test and this works when the labor items are set up with a zero tax.

**Comment by daN4cat** [comment]
So we can close I understand.
