### ISSUE TITLE
redundant code

### ISSUE THREAD

**Issue by odiea** [jekkos/opensourcepos#201]
In both partial header and home the following line is present but shows again after the icons load. Any reason to keep this line

			
			<img src="<?php echo base_url().'images/menubar/'.$module->module_id.'.png';?>" border="0" alt="Menubar Image" /></a><br />
			<a href="<?php echo site_url("$module->module_id");?>"><?php echo $this->lang->line("module_".$module->module_id) ?></a>
			 - <?php echo $this->lang->line('module_'.$module->module_id.'_desc');?>

**Comment by daN4cat** [comment]
Probably we should search for any <!-- and decide whether it's worth removing it. But this is a minor.

**Comment by odiea** [comment]
I am the one that commented out that line. If you look at the 3rd line it basically says the same thing but includes the language line..
