### ISSUE TITLE
Sales Page Blank

### ISSUE THREAD

**Issue by saurabh261187** [jekkos/opensourcepos#202]
I have just setup a new instance of OSPOS on my webserver. All other functions are OK, however when I click on the 'Sales' register, it is not showing up any information and giving only a BLANK screen. Please let me know what I might be doing wrong.

My setup is Linode with CentOS and Virtualmin LAMP stack.

Any help will be really appreciated.

**Comment by daN4cat** [comment]
Have you checked for any error.log in your pos root directory?

**Comment by saurabh261187** [comment]
This is the error log. What can be wrong here ...

[Mon Oct 12 18:45:51.186587 2015] [fcgid:warn] [pid 31874] [client 117.248.214.128:20515] mod_fcgid: stderr: PHP Fatal error:  Call to undefined function bcsub() in /home/nextechinc/domains/testerp.bikehalt.com/public_html/application/libraries/Sale_lib.php on line 178, referer: http://testerp.bikehalt.com/index.php/items
[Mon Oct 12 18:45:55.577153 2015] [fcgid:warn] [pid 31876] [client 117.248.214.128:20519] mod_fcgid: stderr: PHP Fatal error:  Call to undefined function bcsub() in /home/nextechinc/domains/testerp.bikehalt.com/public_html/application/libraries/Sale_lib.php on line 178
[Mon Oct 12 18:45:57.248996 2015] [fcgid:warn] [pid 31873] [client 117.248.214.128:20523] mod_fcgid: stderr: PHP Fatal error:  Call to undefined function bcsub() in /home/nextechinc/domains/testerp.bikehalt.com/public_html/application/libraries/Sale_lib.php on line 178
[Mon Oct 12 18:46:25.018377 2015] [fcgid:warn] [pid 31874] [client 117.248.214.128:20539] mod_fcgid: stderr: PHP Fatal error:  Call to undefined function bcsub() in /home/nextechinc/domains/testerp.bikehalt.com/public_html/application/libraries/Sale_lib.php on line 178, referer: http://testerp.bikehalt.com/index.php/items
[Mon Oct 12 18:46:32.221307 2015] [fcgid:warn] [pid 31876] [client 117.248.214.128:20541] mod_fcgid: stderr: PHP Fatal error:  Call to undefined function bcmul() in /home/nextechinc/domains/testerp.bikehalt.com/public_html/application/libraries/Receiving_lib.php on line 359, referer: http://testerp.bikehalt.com/index.php/receivings
[Mon Oct 12 18:46:35.727089 2015] [fcgid:warn] [pid 31873] [client 117.248.214.128:20542] mod_fcgid: stderr: PHP Fatal error:  Call to undefined function bcmul() in /home/nextechinc/domains/testerp.bikehalt.com/public_html/application/libraries/Receiving_lib.php on line 359
[Mon Oct 12 18:46:37.044737 2015] [fcgid:warn] [pid 31872] [client 117.248.214.128:20540] mod_fcgid: stderr: PHP Fatal error:  Call to undefined function bcmul() in /home/nextechinc/domains/testerp.bikehalt.com/public_html/application/libraries/Receiving_lib.php on line 359
[Mon Oct 12 18:46:38.133908 2015] [fcgid:warn] [pid 30606] [client 117.248.214.128:20543] mod_fcgid: stderr: PHP Fatal error:  Call to undefined function bcmul() in /home/nextechinc/domains/testerp.bikehalt.com/public_html/application/libraries/Receiving_lib.php on line 359
[Mon Oct 12 18:46:39.070590 2015] [fcgid:warn] [pid 31497] [client 117.248.214.128:20545] mod_fcgid: stderr: PHP Fatal error:  Call to undefined function bcmul() in /home/nextechinc/domains/testerp.bikehalt.com/public_html/application/libraries/Receiving_lib.php on line 359
[Mon Oct 12 18:46:39.948743 2015] [fcgid:warn] [pid 31877] [client 117.248.214.128:20544] mod_fcgid: stderr: PHP Fatal error:  Call to undefined function bcmul() in /home/nextechinc/domains/testerp.bikehalt.com/public_html/application/libraries/Receiving_lib.php on line 359
[Mon Oct 12 18:50:44.000361 2015] [fcgid:warn] [pid 31873] [client 117.248.214.128:20855] mod_fcgid: stderr: PHP Fatal error:  Call to undefined function bcsub() in /home/nextechinc/domains/testerp.bikehalt.com/public_html/application/libraries/Sale_lib.php on line 178, referer: http://testerp.bikehalt.com/index.php/receivings
[Mon Oct 12 18:50:46.043281 2015] [fcgid:warn] [pid 31872] [client 117.248.214.128:20860] mod_fcgid: stderr: PHP Fatal error:  Call to undefined function bcsub() in /home/nextechinc/domains/testerp.bikehalt.com/public_html/application/libraries/Sale_lib.php on line 178, referer: http://testerp.bikehalt.com/index.php/receivings
[Mon Oct 12 20:19:00.039700 2015] [fcgid:warn] [pid 2577] [client 117.248.214.128:21547] mod_fcgid: stderr: PHP Fatal error:  Call to undefined function bcsub() in /home/nextechinc/domains/testerp.bikehalt.com/public_html/application/libraries/Sale_lib.php on line 178
[Mon Oct 12 20:19:54.694950 2015] [fcgid:warn] [pid 645] [client 117.248.214.128:21749] mod_fcgid: stderr: PHP Fatal error:  Call to undefined function bcsub() in /home/nextechinc/domains/testerp.bikehalt.com/public_html/application/libraries/Sale_lib.php on line 178, referer: http://testerp.bikehalt.com/index.php/home
[Mon Oct 12 20:20:47.650089 2015] [fcgid:warn] [pid 31875] [client 117.248.214.128:21786] mod_fcgid: stderr: PHP Fatal error:  Call to undefined function bcsub() in /home/nextechinc/domains/testerp.bikehalt.com/public_html/application/libraries/Sale_lib.php on line 178, referer: http://testerp.bikehalt.com/index.php/customers
[Mon Oct 12 20:20:52.079568 2015] [fcgid:warn] [pid 970] [client 117.248.214.128:21787] mod_fcgid: stderr: PHP Fatal error:  Call to undefined function bcsub() in /home/nextechinc/domains/testerp.bikehalt.com/public_html/application/libraries/Sale_lib.php on line 178, referer: http://testerp.bikehalt.com/index.php/customers
[Mon Oct 12 20:21:24.601383 2015] [fcgid:warn] [pid 643] [client 117.248.214.128:21800] mod_fcgid: stderr: PHP Fatal error:  Call to undefined function bcsub() in /home/nextechinc/domains/testerp.bikehalt.com/public_html/application/libraries/Sale_lib.php on line 178
[Mon Oct 12 20:37:39.913823 2015] [fcgid:warn] [pid 2577] [client 117.248.214.128:22794] mod_fcgid: stderr: PHP Fatal error:  Call to undefined function bcsub() in /home/nextechinc/domains/testerp.bikehalt.com/public_html/application/libraries/Sale_lib.php on line 178, referer: http://testerp.bikehalt.com/index.php/config
[Mon Oct 12 20:41:02.417466 2015] [fcgid:warn] [pid 3093] [client 117.248.214.128:23085] mod_fcgid: stderr: PHP Fatal error:  Call to undefined function bcsub() in /home/nextechinc/domains/testerp.bikehalt.com/public_html/application/libraries/Sale_lib.php on line 178, referer: http://testerp.bikehalt.com/index.php/config
[Mon Oct 12 20:52:52.846505 2015] [fcgid:warn] [pid 3086] [client 117.248.214.128:24077] mod_fcgid: stderr: PHP Fatal error:  Call to undefined function bcsub() in /home/nextechinc/domains/testerp.bikehalt.com/public_html/application/libraries/Sale_lib.php on line 178, referer: http://testerp.bikehalt.com/index.php/home
[Mon Oct 12 22:49:47.895678 2015] [fcgid:warn] [pid 3932] [client 59.95.118.219:15635] mod_fcgid: stderr: PHP Fatal error:  Call to undefined function bcsub() in /home/nextechinc/domains/testerp.bikehalt.com/public_html/application/libraries/Sale_lib.php on line 178, referer: http://testerp.bikehalt.com/index.php/home
[Mon Oct 12 22:50:11.245917 2015] [fcgid:warn] [pid 7102] [client 59.95.118.219:15642] mod_fcgid: stderr: PHP Fatal error:  Call to undefined function bcmul() in /home/nextechinc/domains/testerp.bikehalt.com/public_html/application/libraries/Receiving_lib.php on line 359, referer: http://testerp.bikehalt.com/index.php/receivings

**Comment by daN4cat** [comment]
Which PHP version do you use?

**Comment by saurabh261187** [comment]
Running latest 5.4.16-36.el7_1

**Comment by saurabh261187** [comment]
No. Its a stock install. Funny thing is, I am already running an older version of ospos on the same server. Just wanted to use the new one. Also, I have made no changes to the configuration files. The server also runs wordpress etc among other applications.

**Comment by daN4cat** [comment]
Well, it sounds like it's your server issue: https://bugs.php.net/bug.php?id=43761&edit=1 

Please compile PHP with --enable-bcmath (and do a make distclean before, if needed). BCmath is disabled by default (See Installation section in the bcmath php.net manual pages)

I close this case since it's not an OSPOS issue.
