### ISSUE TITLE
Date picker month selection icons disappeared

### ISSUE THREAD

**Issue by daN4cat** [jekkos/opensourcepos#207]
Icons of the month scroll (left & right) disappeared with the latest changes.

It used to work with the changes I made but something was touched in the merge.

![image](https://cloud.githubusercontent.com/assets/636048/10585210/2812c9c4-768e-11e5-862d-1060646efc6a.png)

![image](https://cloud.githubusercontent.com/assets/636048/10585249/37600676-768e-11e5-9d92-b915060d1d66.png)

**Comment by odiea** [comment]
Have you tried placing all the ui-icons from jquery-ui folder to the images folder it looks like he changed the location to find these images.

**Comment by jekkos** [comment]
My mistake, I think I readded the original jquery-ui stylesheet, while previously I did a find/replace on the background image location urls (so I'll need to do that again). Will fix that later today.

**Comment by jekkos** [comment]
Should be good now. Can someone verify?

**Comment by odiea** [comment]
Just tried it and it works now.
