### ISSUE TITLE
Custom Field 1 to be listed on items table

### ISSUE THREAD

**Issue by donangil** [jekkos/opensourcepos#209]
i want to display Custom Field 1 and value on items table like UPC, Item Name, Custom Field 1, .....how. ty

**Comment by jekkos** [comment]
just adapt the table_helper.php and add an extra coumn in the manage_items_table (or something like that) function. Then echo both table header and row content for the new column.

**Comment by donangil** [comment]
i managed creating a column but as i am not a coder i can not figure out what to write to echo the row content(Custom 1 field)

added to line:283 >>      $CI->lang->line('config_custom1'),		 table_helper.php 	

                      346          $table_data_row.='<td width="14%">'.$item->category.'</td>'; 
added to line:347>>>    $table_data_row.='<td width="14%">What code here</td>';


appreciate if you can help

**Comment by odiea** [comment]
$table_data_row.='<td width="14%">'.$item->custom1.'</td>'; worked for me. If you want to show what the column name is I would suggest going into language / items and add  your fieldname  there such as
$lang["items_custom1"] = "Tag Color"; and change this line to added to line:283 >> $CI->lang->line('items_custom1'), table_helper.php

**Comment by donangil** [comment]
thank you very much worked great.

**Comment by daN4cat** [comment]
What is the content of your custom field 1?

I plan to convert few of them to some like: size, color, season that could be handy for fashion. Also odiea suggested tag color and few others. 

If we create an inventory of commonly used fields we can make them standard part of the code and optionally show them on reports.

**Comment by odiea** [comment]
I have not looked into finding where ospos stores the names of the custom fields that we renamed in config to see if that would show anything different.

**Comment by daN4cat** [comment]
It's in the config table.

**Comment by odiea** [comment]
I don't know enough code to change $CI->lang->line('config_custom1'), to fetch the config custom1 name.

**Comment by donangil** [comment]
I want to use the ospos in a pharmacy store.  And i wanted to use the custom field 1 for shelf # (or shelf name) so when i search within items, it will bring me the shelf # (or shelf name) thus can easily locate where the drug is. Ty, your help worked and i hope this may lead you to new ideas.

**Comment by daN4cat** [comment]
OK, good use case which is more detailed than the location one already supported.

P.S.: My holidays are from tomorrow.

**Comment by odiea** [comment]
So here is the line of code I used to get the info from general config.
$CI->config->item('custom2_name'), I guess we could use this instead of adding to the language files.
