### ISSUE TITLE
Make barcode sheet output adaptable

### ISSUE THREAD

**Issue by jekkos** [jekkos/opensourcepos#21]
Original issue from http://sourceforge.net/p/opensourcepos/support-requests/75

Generating barcode presently creates a barcode which gives the item_id and name from table/database ospos_items.
1) I want to change the item_id to item_number. In other words I would like the barcode when scanned to give the upc number not the item id.
2) I would like to add the price (unit_price) to the barcode. I have not been able to find where I need to change/add this information. Pls help!
(Ori: MClark)

**Comment by yh-sourceforge** [comment]
Yes! I will donate.
