### ISSUE TITLE
Misspelling in en items language should be retrieve not retrive

### ISSUE THREAD

**Issue by odiea** [jekkos/opensourcepos#214]
$lang["items_retrive_item_info"] = "Retrieve Item Info"; I don't know what calls this info in the En Items language. Maybe you should add a safe guard into sale not to sell the item if it has no inventory.

**Comment by jekkos** [comment]
Currently indeed there's just a warning. Maybe a

**Comment by odiea** [comment]
I think that would be a great idea. That way everyone's happy. They can keep the old or use the new.
