### ISSUE TITLE
Sales Report

### ISSUE THREAD

**Issue by Puppet25** [jekkos/opensourcepos#216]
why is it that i get negative payment after it is rendered? i mean it must be positive integer because there is still remaining change

**Comment by odiea** [comment]
would you please post an image of what you are referring to.

**Comment by disearth** [comment]
he is talking about the minus sign as shown in the invoice.  http://prntscr.com/8xeu03

**Comment by odiea** [comment]
My interpretation of that is The amount he owes you is a positive amount - his payment is credited as a negative amount. The change due is now a positive amount that the store now owes him.
