### ISSUE TITLE
Check sale is still missing from the report‏

### ISSUE THREAD

**Issue by jekkos** [jekkos/opensourcepos#22]
Issue copied from [opensourcepos:support-requests] #79 
Payment type needs to be added to payment report.

**Comment by yh-sourceforge** [comment]
Yes! I will donate.

**Comment by jekkos** [comment]
Ok this was fixed in b0aa62b044b1aab98f38bb9384bc6694bd0e57b5. Let me know if it suits your needs.

**Comment by yh-sourceforge** [comment]
Dear Jekkos,

Which bit is for me, pls enlighten!
(im still in ver2.3)

Thank You!
Cheers from : YH Phang
