### ISSUE TITLE
Credit Sales

### ISSUE THREAD

**Issue by disearth** [jekkos/opensourcepos#221]
Have you make something to deal with Credit Sales ?

**Comment by yllumi** [comment]
If you mean is pay later, I agree with it. Specially in my country there is a habit where people take the products first and pay later (mostly in wholesale).

**Comment by yllumi** [comment]
After I browse through other issues, I found this issue is similar with this https://github.com/jekkos/opensourcepos/issues/24.

**Comment by daN4cat** [comment]
I would close this and please refer to #24
