### ISSUE TITLE
Can't add / submit new items

### ISSUE THREAD

**Issue by offgridcrazy** [jekkos/opensourcepos#222]
I have a fresh install of OSPOS on a windows 10 computer. I'm using version 2.3.1 of OSPOS.  I installed the full package of wamp server.  I had no issues getting both installed and set up.  I have added  customers, suppliers, and employee's with no problems.  BUT when I go to add a new item or if I use the item import csv file that I downloaded to do import nothing happens when I hit submit and no item is added to the database. 
Help Please.

**Comment by jekkos** [comment]
maybe be a bit more specific here. Are you using a clean database setup? Maybe try to see what the http response contains (if there's an error message eg paste it here)

**Comment by donluismx** [comment]
THE PROBLEM
Adding a new item, and when I get to the category field and write the first letter, it prompts me this in a tooltip:

A PHP Error was encountered
Severity: Notice
Message: Only variable references should be returned by reference
Filename: core/Common.php
Line Number: 257

Such notice is present all along the site, required form fields validation works, but it doesn't submit anything to the db.

THE SOLUTION

I tried this solution
http://stackoverflow.com/questions/28348879/only-variable-references-should-be-returned-by-reference-codeigniter
and works great, I'm still checking and loving it around trying to find new bugs.

**Comment by odiea** [comment]
Also got this error from Ubuntu server using the following version.
> php -v
PHP 5.6.11-1ubuntu3.1 (cli) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies

**Comment by odiea** [comment]
I updated the current version of ospos with this and there have been no ill side effects. Maybe replace it on the master so this error doesn't show anymore so others can use a newer php version with no problems.
$_config[0] =& $config;
return $_config[0];

**Comment by jekkos** [comment]
Fixed in afa203e73c2eaf87f66dff1112cacf3d80994096. I checked and latest CI version contains this change as well, so no chance for regressions once an upgrade is done.

**Comment by darkjedeye** [comment]
I am having a similar problem, no error, just when i try add a new item, the windo comes up rather small, with no editable items, wether i use ip or url, i will add a screenshot and specs as soon as i am home, but to be clear it is exact same setup as my vm on my desktop, Ubuntu 16.04 latest php and apache2 updates, the only difference is: my vps one(external) is running on port 82 and that is about it... any suggestions? had this issue before, and managed to fix it, but can't remember how.

**Comment by daN4cat** [comment]
Latest PHP means? If it's 8.0 it's not supported.
7.4 is supported by vs 3.3.3 released on 1st Jan.

**Comment by darkjedeye** [comment]
PHP info:
PHP 7.4.13 (cli) (built: Nov 28 2020 06:24:27) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.13, Copyright (c), by Zend Technologies

server details:
OS: Ubuntu 16.04.7 LTS x86_64
 Host: KVM RHEL 7.6.0 PC (i440FX + PIIX, 1996)
 Kernel: 4.4.0-197-generic
 Shell: bash 4.3.48
 CPU: Intel Xeon Silver 4214 (1) @ 2.199GHz
 Memory: 575MiB / 1999MiB

![Capture](https://user-images.githubusercontent.com/29452733/104090041-7b1f4000-527c-11eb-86aa-ecb5271911f1.PNG)

I know it's a small adjustment somewhere or some install / edit i havnen't done somewhere, just can't remember.

**Comment by odiea** [comment]
disable full_group_by in mysql maybe?

**Comment by daN4cat** [comment]
You have an old version of ospos that doesn't support PHP 7.4. As said only 3.3.3 added support to PHP 7.4.

**Comment by darkjedeye** [comment]
Yep, that was it.
