### ISSUE TITLE
Can't enter invoice # when sales register after tick create invoice

### ISSUE THREAD

**Issue by arwah1981** [jekkos/opensourcepos#223]
Any suggestions about this issues?

**Comment by jekkos** [comment]
Is this in the latest version that you're facing this issue?

**Comment by arwah1981** [comment]
I'm using the newest master copy from here,thanks!

**Comment by daN4cat** [comment]
I assume this is a confirmed bug with the latest version. Can we confirm please?

**Comment by odiea** [comment]
Yes it is back to not working again. Mine is 2 invoice numbers <In Takings/overview last Invoice # was 76 # at pos is 74 >behind and it will not let me change invoice numbers.

**Comment by jekkos** [comment]
If I remember well then there was an issue for this some time ago?

**Comment by odiea** [comment]
Yes we did have this issue for quite a while and the last fix you did worked for a while. I have not changed anything as far as co or yco goes. I remember giftcards giving issues because it was a varchar(32) utf8_general_ci  so we changed it ti int(10) and that went away. Could this be the same type of issue? Possible something changed when the suspended sales was updated?

**Comment by odiea** [comment]
in app/views/sales/manage when is the following function suppose to work? I can edited it out and I still get the same response with no error.
$("#update_invoice_numbers").click(function() {
		$.ajax({url : "<?php echo site_url('sales') ?>/update_invoice_numbers", dataType: 'json', success : post_bulk_form_submit });
		return false;
	});

**Comment by odiea** [comment]
Have you ever considered giving sales invoicing it's own int() table that just gets written to when an invoice is created? No more nulls just numbers. Of course sales_id would have to be in it and maybe a field for co yco and sco. This has been a pain in your butt since you took over.

**Comment by jekkos** [comment]
Problem here is that there are too many scenarios in which the invoice number can be used. Custom set invoice numbers shouldn't be overridden and a unique check only makes sense in this specific situation, as we should assume that for a regular incrementing number, it should be automatically unique (even with concurrent users doing sales from their resp. sessions).

Did a quick test on these and looks ok now.

**Comment by odiea** [comment]
The change is allowing for entering a new Invoice number but the highest number entered is not showing. For me its still 2 numbers behind.

**Comment by jekkos** [comment]
You're probably missing two lines in that sequence of numbers, as the $CO is substituted with the current count of sales with invoice number not null. Maybe check with a 
   
     select count(1) from ospos_sales

**Comment by odiea** [comment]
select count(1) from ospos_sales 
count(1)  
397

**Comment by jekkos** [comment]
I've adapted the query should be 
   is not null..

this should be the number you see popping up

**Comment by odiea** [comment]
select count(1) from ospos_sales where invoice_number is not null
count(1)  
93
So is there a way to repair this problem?

**Comment by jekkos** [comment]
Yes that's what the commented code you found was supposed to do.

**Comment by odiea** [comment]
Ok I found the source of the problem. When you go into takings/overview and delete a sale with an invoice then it changes the count thus lowering the count.

**Comment by jekkos** [comment]
yes indeed adding deleted flag would help here. Maybe create another followup issue for that one?
