### ISSUE TITLE
CSV import dropping data after quote (")

### ISSUE THREAD

**Issue by nhooverapg** [jekkos/opensourcepos#224]
Specifically for the description field in the CSV file, if the field contains a quote ("), all data from the quote on (including the quote) is not imported into the database. Adding the quote with the remaining data in the edit item option works.

**Comment by daN4cat** [comment]
Might be a safe guard for security reason to avoid malicious SQL query injection, but it's worth investigating.

Does the issue happen with double quote (") only or single quote (') too?

**Comment by nhooverapg** [comment]
Not sure about single quote, didn't test that. I was using double quotes to mean inches in a couple of my items.

If it is a safe guard, then the edit item module should be running that same safe guard, right? But I was able to add quotes to the description there, they just didn't come in on CSV import. Seemed to me that the edit module was escaping the text, but the CSV wasn't. I poked around in the code a little, but ran out of time before I found anything that was a smoking gun for that.

**Comment by jekkos** [comment]
I'm currently touching this code in scope of 2.4, will look for a fix and then probably backport it.

**Comment by donangil** [comment]
Also the non english characters(İ. Ö. Ç. ş....) are not imported into the database with CSV import.

**Comment by jekkos** [comment]
Special characters not showing correctly is probably an encoding issue. The quote problem might be due to incorrect escaping of the input data. Will look into that later today.

**Comment by jekkos** [comment]
Just did a short test on special characters + quotes. Currently I can't reproduce any of the mentioned issues with my setup

* Which encoding are you using for the csv files? This should be utf-8. Be aware when editing it in a external editor. 
* Regarding the quotes, are you using quotes to delimit your csv column contents? In that case you'll need to escape quote literals used inside of these columns. A decent csv editor should handle this for you.

![screenshot from 2015-11-30 17 29 53](https://cloud.githubusercontent.com/assets/576234/11477518/a9fef852-9788-11e5-9713-ee1dd2fb55c8.png)

**Comment by donangil** [comment]
Thank you. My or excel bad. Solved with another editor.

**Comment by jekkos** [comment]
@nhooverapg For the quote problem, can you perhaps post the import file you were using to reproduce this issue?

**Comment by nhooverapg** [comment]
Ok, so attached is the file. After looking at it directly in a text editor (I had been using LibreOffice to edit), I see the issue. Certain text fields (especially ones with spaces or commas) were getting encapsulated in quotes. Then when the import happened, it was just reading the first part of the description line (6" Wreath Plain) as the total line and ignoring the rest. The import seems to have handled the other quotes in the file correctly (stripping them out I assume).

I had to change the extension on the uploaded file to .txt from .csv to get the uploader to work.
[import_items_problem.txt](https://github.com/jekkos/opensourcepos/files/50401/import_items_problem.txt)

**Comment by jekkos** [comment]
The csv reading is done by an internal php function, so in this case I don't think this issue can qualify as an ospos bug. And indeed I also had the idea that this would probably be an escape issue. Not sure how CSV defines to use escaped characters once you add quotes around your column.

So think this issue can be closed then.
