### ISSUE TITLE
Keycorp RM2000 recipt printer & CD-5000II customer display

### ISSUE THREAD

**Issue by Scotty2013** [jekkos/opensourcepos#225]
Can I run these with opensourcepos?
And if not how hard would it be to get them going on it?
The both run through the com1.
Thanks

**Comment by daN4cat** [comment]
Being opensourcepos a web based application where you interact with it via a standard web browser, the question for yourself would be: can I browse the web using Opera/Netscape/Chrome/Else and print a page using my HW?

Once you succeed with that using let say www.bbc.com (or co.uk) you can consider playing with OSPOS.

That to say that it's a matter to be solved with your machine and OS first.
