### ISSUE TITLE
Change Password option.

### ISSUE THREAD

**Issue by disearth** [jekkos/opensourcepos#227]
Change password option is not available & I think it must be there.

**Comment by jekkos** [comment]
Sure. Feel free to send out a pull request for this enhancement.

**Comment by daN4cat** [comment]
@ais-one is this something you would like to work on?
Ideally we should give an option to logged in users to change their password when they like.
I believe this would be a nice feature to add.

**Comment by ais-one** [comment]
Hi, I will take a look at it, will work on master. This week I am deploying ospos for one customer, its a custom metal workshop

**Comment by daN4cat** [comment]
Yep, master is now the latest vs 3.0.

**Comment by daN4cat** [comment]
@ais-one any update on this?

**Comment by ais-one** [comment]
Hi, I was busy deploying POS the past few days.

For email settings, it is easy and can be added to the config.

But for change of login user password, I have question

I was also looking up the permissions system if I were to create another module for such configuration information.

Currently config permission is a checkbox, so if it is unchecked for a user, that user cannot see the config button.

So the question now is, should I create a module (another menu button) to go into a page where user can change his/her own password? This module will always be available, so I will not put it in the permissions.

**Comment by daN4cat** [comment]
@ais-one what if the user clicks on their name from the top bar? We could add a dialog box with their info and password change option?

However I would give this feature based on permissions, so please add the permission to allow changing password or not. In certain cases like my wife's shop the shop assistant don't change login name for weeks and 2 or 3 people use the same login.

**Comment by daN4cat** [comment]
Maybe just open the employees form but disable the Permissions tab to the user and make the First and Last names readonly. The info and password should be fine.
So you can just reuse the same form, you just need to add some conditionals in the form maybe checking if the current user has admin rights or not could do so you don't need to have more params passed from the controller.

**Comment by ais-one** [comment]
Yes, trying to reduce the number of changes to make it work, I will look into the re-use of employee form...

**Comment by daN4cat** [comment]
@ais-one any news?

**Comment by jekkos** [comment]
@ais-one any update? Otherwise release milestone will be set to post 3.0

**Comment by jekkos** [comment]
I will set this milestone to undefined as it depends on when @ais-one is ready to contribute

**Comment by daN4cat** [comment]
I wanted to find the time and sort this out too... But it's ok to descope at the moment

**Comment by jekkos** [comment]
sure i guess we could still add it to the mainline if not too much effort, however I would want to get remaining bugs out of the way first  ..

**Comment by daN4cat** [comment]
Agreed. We are tidying up now.

**Comment by jlctmaster** [comment]
Hello, I am willing to work on this feature, will someone else be working on it? If not, please assign this improvement to me.

**Comment by daN4cat** [comment]
It's yours.... thanks!

Suggestion is to allow people to click on their name on the too bar and you can open the employee model showing just the password tab so they can change.
Also please add the permission to allow people to change the password or not.
It would be great to add it to 3.1.0 if you are quick in implementing it.

Thanks

**Comment by jlctmaster** [comment]
Ok, sure, thanks for the suggestions

**Comment by jekkos** [comment]
@daN4cat This is nice, since we did the UI overhaul, there's quite some more will to contribute to this project.

**Comment by daN4cat** [comment]
@jekkos I cannot believe we discussed certain features one year ago. But good we are still progressing and actually more people are contributing.

**Comment by jlctmaster** [comment]
Yes, at the moment, I am developing this improvement, however, I have a problem when displaying the modal window when I am in home view, I have been inspecting the code and I do not see that I have to load it to show there, in the Forms where the modal window is used works correctly.

**Comment by jlctmaster** [comment]
Hi, I already did the PR with the improvement, according to the @daN4cat suggestions, however, the only suggestion that did not apply, was to configure that the key change is restricted by permisologia, since this is a basic function that any user should to have.

Greetings.

**Comment by daN4cat** [comment]
@jlctmaster merged and I'm going to give a try now

**Comment by jlctmaster** [comment]
Thanks, I hope to contribute with other characteristics for this project.

**Comment by daN4cat** [comment]
@jlctmaster problem, when I click submit the dialog box doesn't disappear

**Comment by daN4cat** [comment]
Fixing it....

**Comment by daN4cat** [comment]
@jlctmaster please test it through again because I found out few errors and fixed.

**Comment by daN4cat** [comment]
@jlctmaster if you change the user password when in sales or home the pop up green/red doesn't show on submit. Please check the dialog box submit behaviour in all possible views.

**Comment by jlctmaster** [comment]
Ok, I will carry out the corresponding tests and I will mention my observations on them.

**Comment by daN4cat** [comment]
@jlctmaster any news?

**Comment by jlctmaster** [comment]
Sorry, I could not make the corresponding revisions.

**Comment by daN4cat** [comment]
@jlctmaster plans to get this closed over the weekend?

**Comment by jlctmaster** [comment]
Hi @daN4cat , I'm reviewing the reported issues

**Comment by jlctmaster** [comment]
Hello @daN4cat , I already uploaded a new PR where I correct the problem with the alert messages in the whole system, and verify its correct operation.

**Comment by daN4cat** [comment]
@jlctmaster thanks and it was merged in. I'll test more tomorrow.

**Comment by daN4cat** [comment]
This looks fine to me. I close.
