### ISSUE TITLE
Prevent deletions of Sales Invoices

### ISSUE THREAD

**Issue by odiea** [jekkos/opensourcepos#230]
When Sales with Invoices are deleted it prevents Auto invoice numbering from working properly. Adding deleted flag would help here or preventing Sales with Invoice numbers from being deleted.

**Comment by odiea** [comment]
In application/views/sales/manage line 196 you had this option commented out. Was there a reason for this? That was the line of code that was not doing anything.

**Comment by jekkos** [comment]
This was an extra functionality that allowed a user to fix the gap left behind in the numbering sequence for the invoice numbers after deletion. It wasn't really integrated as it only worked for $YCO a
