### ISSUE TITLE
multi stock problem

### ISSUE THREAD

**Issue by hotline007** [jekkos/opensourcepos#232]
after adding 3 stocks when i add an item to stock1 it also added to stock2 and stock3
and when delete it too 

is that normal ? it should be separate stocks ...

**Comment by jekkos** [comment]
That's normal indeed. It's just quantities that are distributed across stocks.

**Comment by hotline007** [comment]
If i want to remove an item in stock1 only without removing it from stock2 how can i do it ?

**Comment by jekkos** [comment]
You can only adapt quantities in each stock separately. The item definitions are global across different stocks. Just set the quantity for that stock to 0.
