### ISSUE TITLE
Bringing back the Customer info in Sales

### ISSUE THREAD

**Issue by odiea** [jekkos/opensourcepos#233]
It would be great if you could give me 1 line of code to add address to customer info. If i have that the other lines should be easy to get.
if(isset($customer))
	{
		$customer_id = $this->input->post("customer");
		echo $this->lang->line("sales_customer").': <b>'.$customer. ' :  '.$customer_id.'</b><br />';
		echo $this->lang->line("sales_customer_address").': <b>'.$customer.'</b><br />';
		echo $this->lang->line("sales_customer_city").': <b>'.$customer. '</b><br />';
		echo $this->lang->line("sales_customer_state").': <b>'.$customer. '</b><br />';
		echo anchor("sales/remove_customer",'['.$this->lang->line('common_remove').' '.$this->lang->line('customers_customer').']');
	}

**Comment by jekkos** [comment]
for address I think you'll need to refer to the column names in the ospos_people table. In this case that'll be $customer->address_1 of $customer->address, maybe check the sql script to see the exact names

**Comment by odiea** [comment]
Well I have had no luck using your suggestion. Yes it is address_1 and people is person_id

**Comment by jekkos** [comment]
maybe the $customer isn't defined here? in that scope shouldn't it be $cust_info or something?

**Comment by odiea** [comment]
Good morning; So here is what I have tried so far with no luck.
                $address = $cust_info->address_1;
		$address_2 = $customer_info->address_2;
	I had to use this line to get the customer_id	$customer_id = $this->input->post("customer");
		
		echo $this->lang->line("sales_customer").': <b>'.$customer. ' :  '.$customer_id.'</b><br />';
		echo $this->lang->line("sales_customer_address").':<b>'.$cust_info->address_1. '</b><br />';
A PHP Error was encountered
Severity: Notice
Message: Undefined variable: cust_info
Filename: sales/register.php
Line Number: 213
A PHP Error was encountered
Severity: Notice
Message: Trying to get property of non-object
Filename: sales/register.php
Line Number: 213
A PHP Error was encountered
Severity: Notice
Message: Undefined variable: customer_info
Filename: sales/register.php
Line Number: 214
A PHP Error was encountered
Severity: Notice
Message: Trying to get property of non-object
Filename: sales/register.php
Line Number: 214

**Comment by cpl2015** [comment]
I use this (in view/sales/receipts.php) to show customer name along with address on printed "Sales Receipt".   Hope this helps. 


<div id="receipt_general_info">
		<?php if(isset($customer))
		{
		?>
		<div id="customer"><?php echo $this->lang->line('customers_customer').":".$customer_info; ?></div>
		<?php
		}
		?>

**Comment by odiea** [comment]
Thanks, I will see if I can get that to work on the Customer screen

**Comment by cpl2015** [comment]
But, it's working fine for me. Customer's name and address etc are showing in a single line, though.

**Comment by odiea** [comment]
This may work for receipts but if I use it in register it still returns undefined variables.

**Comment by odiea** [comment]
Here is what I did to get all the customer info onto the screen but it disappears when an item is added or if I go out of the sale. Only the customer name is retained.
![2015-11-18 18_46_52-once again thrift -- powered by os point of sale](https://cloud.githubusercontent.com/assets/10962177/11260066/cd7ac2ce-8e24-11e5-8783-cd44bfd5d468.png)

if(isset($customer))
	{
			$customer_id = $this->input->post("customer");
			$cust_info = $this->Customer->get_info($customer_id);
			$data['customer'] = $cust_info->first_name.' '.$cust_info->last_name;
			$data['customer_address'] = $cust_info->address_1;
			$data['customer_location'] = $cust_info->city ;
			$data['customer_state'] = $cust_info->state. ', ' .$cust_info->zip;
			$data['account_number'] = $cust_info->account_number;
			$data['customer_info'] = implode("\n", array(
				$data['customer'],
				$data['customer_address'],
				$data['customer_location'],
				$data['customer_state'],
				$data['account_number']));
					
		echo $this->lang->line("sales_customer").': <b>'.$customer. ' :  '.$data['account_number'].'</b><br />';
		echo $this->lang->line("sales_customer_address").': <b>'.$data['customer_address']. '</b><br />';
		echo $this->lang->line("sales_customer_city").': <b>'.$data['customer_location']. '</b><br />';
		echo $this->lang->line("sales_customer_state").': <b>'.$data['customer_state']. '</b><br />';
		echo anchor("sales/remove_customer",'['.$this->lang->line('common_remove').' '.$this->lang->line('customers_customer').']');
	}

**Comment by odiea** [comment]
Here is the working version that does retain the cust_info. The key was the first line. 
$customer_id = $this->sale_lib->get_customer();
			$cust_info = $this->Customer->get_info($customer_id);
			$data['customer'] = $cust_info->first_name.' '.$cust_info->last_name;
			$data['customer_address'] = $cust_info->address_1;
			$data['customer_location'] = $cust_info->city ;
			$data['customer_state'] = $cust_info->state. ', ' .$cust_info->zip;
			$data['account_number'] = $cust_info->account_number;
			
					
		echo $this->lang->line("sales_customer").': <b>'.$customer. ' :  '.$cust_info->account_number.'</b><br />';
		echo $this->lang->line("sales_customer_address").': <b>'.$cust_info->address_1. '</b><br />';
		echo $this->lang->line("sales_customer_city").': <b>'.$cust_info->city. '</b><br />';
		echo $this->lang->line("sales_customer_state").': <b>'.$data['customer_state']. '</b><br />';
		echo anchor("sales/remove_customer",'['.$this->lang->line('common_remove').' '.$this->lang->line('customers_customer').']');

**Comment by onyema3** [comment]
Merci

**Comment by odiea** [comment]
Here is the info to add company name.
$data['company'] = $cust_info->company_name;
echo $this->lang->line("sales_company").': <b>'.$cust_info->company_name.'</b><br />';
Now if someone know's how I can get the person's giftcards to show that would finish up the Customer info.

**Comment by daN4cat** [comment]
Maybe this could be added as part of the re-layout.

**Comment by daN4cat** [comment]
@odiea this looks like #335. Are these the same?

**Comment by odiea** [comment]
Sorry #335 is the more embellished version. This one can be closed.
