### ISSUE TITLE
Fractional 'quantity' is getting auto rounded off to nearest 2nd decimal point after saving.

### ISSUE THREAD

**Issue by cpl2015** [jekkos/opensourcepos#234]
If I sell an item with quantity 1.238 KG , the sales screen is showing the actual quantity entered and also the sales receipts printing the actual quantity. But when I recall that sale from 'Takings' the item quantity showing rounded off to nearest 2nd decimal point (eg, 1.24 KG), and also the sales total is getting changed accordingly and causing a difference in total sale value . How to prevent that ?

**Comment by jekkos** [comment]
reporting has rounding done on database level. Check the temp table query in sale.php and receiving.php models where you will find the number of decimals to be rounded with

**Comment by cpl2015** [comment]
Replacing decimal number in model/sales.php  from 2 to 3/4/5 changes nothing.

**Comment by jekkos** [comment]
There's a constant in a helper class as well that defines how many decimals will be used for the rounding.

**Comment by cpl2015** [comment]
That is only for 'currency'  in currency helper, found nothing for 'quantity' or other decimal points.

**Comment by cpl2015** [comment]
Solved by editing database/ospos.sql file and re-importing tables from that, by default uses 2 decimal points to save the item quantity.
