### ISSUE TITLE
Is OSPOS suited to variable price items?

### ISSUE THREAD

**Issue by RyanfaeScotland** [jekkos/opensourcepos#236]
Hey guys,

Just finished installing OSPOS last night and looking forward to having a proper play around with it over the weekend.

Before I get my hands dirty I wanted to ask a quick question which will hopefully save me a lot of time and give me some guidance on when alterations need made to bend OSPOS to my needs.

Is OSPOS as it stands suitable for variable priced items?

Imagine a used book store. Typically the book 'The Cat in the Hat' sells for £5.00 but I have 3 copies of it each in a different condition: poor, good and great. I'm going to sell the poor one for £3.00, the good one for £5.00 and the great one for £7.00.

Off the top of my head the way I think I would cope with this is enter this into OSPOS as 3 separate items with the same name. I'd then need some sort of unique barcode or ID on each of the books so I know which copy is which. Customer comes over, I enter the ID into the system and it brings up the right version with the right price.

Or would it be better to have 1 item in the system with a selling price of £7.00 and I mark the worse copies as having a discount on this price as they come through the till?

Any other ideas are welcome.

My other question is is this the correct place to raise such questions? I know some projects prefer their GitHub Issues to be related to exactly that, issues with the code base, but I couldn't find any other forum or discussion area for OSPOS users. 

Thanks for your time.

**Comment by cpl2015** [comment]
Well, you can enter/edit the price of an item on the fly when executing sale and also add / edit the discount percentage.
Hope this helps.

**Comment by RyanfaeScotland** [comment]
This may become obvious when I use the software but does this edit the price of the base item or just this sale of it? So I enter the item in the inventory at £7.00 with 3 quantity. My cashier sells the poor copy first and changes it on the fly to £3.00. Will it appear as £3.00 during the next transaction or £7.00?

Thanks for the quick response, would you be kind enough to label this 'issue' as a question?

**Comment by cpl2015** [comment]
The original price remains intact, changes only affect the current sale.
