### ISSUE TITLE
'Suppliers' > 'New Supplier' shows PHP error

### ISSUE THREAD

**Issue by cpl2015** [jekkos/opensourcepos#238]
The picture tells the story : 

![20](https://cloud.githubusercontent.com/assets/15803637/11319311/00f5a838-9098-11e5-82a8-23e18190836f.png)

**Comment by odiea** [comment]
Who's version are you using? The current version from jekkos doesn't seem to show any problems. yllumi does contain a few errors after updating the CI to the current version.

**Comment by cpl2015** [comment]
Getting this error in both yllumi and jekkos 2.3.3

**Comment by odiea** [comment]
Di you upgrade your database? I think its 2.3.2 to 2.3.3 contains the agency name field

**Comment by cpl2015** [comment]
Well, updating database did the job.

Thanks.

**Comment by odiea** [comment]
I figure the OSPOS community should help each other out. Your Welcome.
