### ISSUE TITLE
Disable Invoice check mark after a sale

### ISSUE THREAD

**Issue by odiea** [jekkos/opensourcepos#239]
Is there a way to disable or remove the Invoice enabled check mark automatically after a sale. I have it set so Invoice enabled only shows after a customer name is selected but if the box is enabled it still creates an Invoice plus it's an annoyance to have to uncheck it after a sale.

**Comment by jekkos** [comment]
It used to be like this indeed. I think it was removed on request of someone else, who wanted to add custom numberings to his sales most of the time.

Indeed quite an annoyance for my users as well.
