### ISSUE TITLE
Stock location not working

### ISSUE THREAD

**Issue by odiea** [jekkos/opensourcepos#242]
It appears the ability to add a stock location works but after entering the new information it does not show as a new location anywhere in the program. Earlier I had removed the secondary stock location . In the database it was marked as deleted so I changed it and the new location is now showing up in stock locations but no where else..It does work ok if I create a new empty database but once a new stock location is deleted it quits working..

**Comment by jekkos** [comment]
Ok this part was rewritten in the modifications for the multistore (in which you can add stock locations in the stores module). I'll try to sort that out before the 2.3.3 final release.

**Comment by jekkos** [comment]
Add/delete seems to work ok now. Will close this issue for now
