### ISSUE TITLE
Items Appear in Search Box But Don't Show Details 

### ISSUE THREAD

**Issue by RyanfaeScotland** [jekkos/opensourcepos#245]
Hey folks,

Just upgraded from 2.3.1 to 2.3.3 and I've found now when I search for an item in the Item screen it will appear in the search box but nothing shows when I click the item or hit enter to search for it.

I've found that this only happens for items I previously had in, not new ones that I add.

I further found that as long as I have an entry in the ospos_inventory table then it appears. Previously I only needed an entry in items and item_quantities but I can't see anything in the update SQL that should have changed that.

Maybe not regarded as a bug since you should likely have an entry in all 3 tables for each item anyway but since I mass inserted 6000 items into the item table this isn't the case for me.

I'll likely go write a query that auto inserts records that aren't already present in the ospos_inventory table from the items table but thought I'd raise it up incase it is a sign of an underlying issue (perhaps adding the pic field has broken a query?) and / or anyone else has it.

**Comment by RyanfaeScotland** [comment]
Here is the breaking change:

Inside the item model the search has changed from:

function search($search,$stock_location_id)
	{
		$this->db->from('items');
		$this->db->join('item_quantities','item_quantities.item_id=items.item_id');
		$this->db->where('location_id',$stock_location_id);
		...

to

public function search($search, $filters, $rows=0, $limit_from=0)
	{
		$this->db->from('items');
		$this->db->join('suppliers', 'suppliers.person_id = items.supplier_id', 'left');
		$this->db->join('inventory', 'inventory.trans_items = items.item_id');

and because the join isn't matching anything it's failing to return any records.

Will get my db updated with records and hopefully I'll be up and running again.

**Comment by jekkos** [comment]
Might be solved easily by using a left join on the inventory table.. I'll try to reproduce this and see if that fixes this problem.

**Comment by jekkos** [comment]
The join on inventory is needed here to use the date range search. Normally if you import items using CSV then at least one record should have been created for each item. Wasn't that the case then in your original dataset?

**Comment by RyanfaeScotland** [comment]
Na, sadly the CSV import wasn't working for me off the bat and it was easier for me to create a custom query than it was to figure out what was up.

**Comment by jekkos** [comment]
Ok I must admit that in older version CSV import had some problems. Think there was some rework on this code in 2.3.2 or later.

**Comment by RyanfaeScotland** [comment]
Ok, will try and use it again on the next mass import which should be taking place this weekend.

In the meantime do you have a suggestion for the current issue I'm seeing. A left join might do the job, it would mean you wouldn't get any search results if you are using the date filter and you don't have an entry in the inventory table but this is still better than no results ever.

**Comment by RyanfaeScotland** [comment]
Tried the left join and it brings in all my original items again but now I don't think the new ones are appearing. Only done a quick test by renaming one of them since I see there is a group by name later in the function and I didn't see it returned regadless of date range.

I'll test further when home.

**Comment by RyanfaeScotland** [comment]
new ones aren't appearing that should say (can't edit on phone)

**Comment by jekkos** [comment]
well the search field overrides using a date range in this case. Currently there isn't an easy way to disable the range so once you want to search through all the items, you can just use the search box.

**Comment by jekkos** [comment]
So how does the date range searching behave when adding left join? Does it show any results with  the date filter on?

**Comment by RyanfaeScotland** [comment]
Yeah you get the results that have the inventory entries but not those that
don't.
On 4 Dec 2015 20:34, "jekkos" <notifications@github.com> wrote:
>
> So how does the date range searching behave when adding left join? Does
it show any results with the date filter on?

**Comment by daN4cat** [comment]
The assumption is that when you add/remove/change items you have inventory entries added. If people does database imports without creating inventories add the feature won't work.
If that's the issue here....

**Comment by jekkos** [comment]
Import should create the inventory lines, at least in the latest version. This might have been broken in older versions. So what shall we do with this issue?

**Comment by daN4cat** [comment]
I'm talking of imports done from behind the scenes, stuff happening form let say myPhpAdmin, not from OSPOS application itself.

**Comment by daN4cat** [comment]
A solution would be to create an inventory entry to let say having edited all the items. That will do and solve the issue instead of playing with queries and test corner cases.

**Comment by RyanfaeScotland** [comment]
Hey guys, busy times again so didn't have a chance to chime in.

I'm with @daN4cat though, this isn't a bug or an issue, if people are going to make changes in the DB directly then you can't account for the issues that might occur or be expected to.

However it does look like there is an underlying issue with the lack of technical documentation explaining how things work. Changing a display to rely on a join to another table is a breaking change and would have been good to have been warned about before performing the update.

I think if there was more documentation around the architecture it would make things like this easier to diagnose.

**Comment by daN4cat** [comment]
Agreed, if we could find the time.... this is not my primary job but just a pastime for my wife's business.

So the best documentation at the moment is to search the issues/feature database here or post a question. Unfortunately I couldn't answer earlier otherwise I would have done since I implemented this feature of narrowing down items based on inventory date (on request by @odiea).

**Comment by odiea** [comment]
@daN4cat I do thank you for that feature. My reasoning for that feature was We do have a thrift store currently with over 250000 items. I had to think of a solution for adding Items on a daily basis. The easier it is for employees to add an item then print a barcode the better it is.
