### ISSUE TITLE
oscommerce integration

### ISSUE THREAD

**Issue by boelle** [jekkos/opensourcepos#252]
Will this be possible?

i know a few stores that have a cash register with touch screen and no keyboard...

first they tap a category, then what item, and if atributes/options are avaible on the product they click that and its added to the list.

then they click either cash or credit... cash drawer opens if cash

at the same time they have a website based on oscommerce and would like to melt the 2 together... ie use the oscommerce database for as much they can...

**Comment by jekkos** [comment]
Duplicate issue #92.

**Comment by boelle** [comment]
so this means no?

**Comment by jekkos** [comment]
Sure this is possible. But it will require some analysis / work to integrate it in a proper way.

**Comment by boelle** [comment]
i know 2 webshops that are up as Guinea pigs if you need it

**Comment by jekkos** [comment]
I see you're involved in the opentrv project as well. Can you get me some equipment to improve the heating in my home ?

**Comment by boelle** [comment]
i can try...  is it a UK home?

i just make a few PCB's from time to time so it depends on what CEO says

2015-12-14 0:35 GMT+01:00 jekkos <notifications@github.com>:

**Comment by jekkos** [comment]
OK would be great if you have one or two PCB's that I can try out for the time being. I'm located in Belgium so shipping in EU should not be an issue.

Should I buy a commercial valve and then replace the PCB in it? For example could I replace the PCB in a HoneyWell home expert with an opentrv one? I like to tinker with these kind of things so I'll certainly be able to give some feedback/contributions back if I'm able to get involved this way.

Also if this is too much of a hassle then send me the the address of the pcb fab house and then I can order some myself.

**Comment by boelle** [comment]
personal i use this valve:
http://www.conrad-electronic.co.uk/ce/en/product/570056/FS20-Indivdual-Wireless-Thermostat-Actuator

best is to order it from conrad in belgium so that you are sure to get the
most common adapters for belgium


i know that they are working on a production unit where board and motor etc
are one complete unit, not sure if they make it on this side of new year...
but i can ask

2015-12-14 10:43 GMT+01:00 jekkos <notifications@github.com>:

**Comment by jekkos** [comment]
Ok I read that as well. If I can get one from that production run then that would be even better.

I'll certainly be interested, just because it's open source and I like to decide how to integrate it with other appliances in my home.

**Comment by boelle** [comment]
hehe

for me it started 3-4 years ago as i was looking for something better
too... most stuff was to expensive and closed sourced and did not have what
i needed...

found links to the firmware we put on these?

2015-12-14 11:08 GMT+01:00 jekkos <notifications@github.com>:

**Comment by jekkos** [comment]
Not yet, there seems to be tons of source and it's not really clear what is where. 

We were considering to hack up an existing Honeywell adapter to do the same but as there's already quite some work done on opentrv I think it might be a better idea to try that first.

**Comment by boelle** [comment]
i have asked arround and there is so much info going back and forth

what i have heard is that some of the staff should be in china to
investigate startup of the production run, but not sure as no one could
confirm...

i also asked for a few sample boards.... they will see if they  have a rev7
or early....

i'm personal still on rev1 as they  work for me... most of them are just
set to 20 degree and run all the time... only difference from a normal
thermostat is that at night it will lower temp a few degrees when it gets
dark enough

in our living room they run on schedule so its only hot when we are in
there..

2015-12-14 11:54 GMT+01:00 jekkos <notifications@github.com>:

**Comment by jekkos** [comment]
Ok sounds cool. Can you control them remotely? Through integration with Open energy monitor or something thelike? I'd like to create different zones like two bedrooms don't need to have their temp set at certain times. The feedback system with temperature sounds quite nice. 

Rev7 is AVR based I suppose? Do you have a part that controls your heater as well? Mine has an ebus interface and I'm gonna try to attach a serial device to it to readout the settings and eventually control them as well.

**Comment by boelle** [comment]
No remote control yet... i would have loved that since i use
openenergymonitor too... but no one have done it yet... i'm not a software
person but i have an idea how it could be done

opentrv boards monitor stuff like temp and send its to a opentrv "listner"
board connected to the raspberry pi
this data gets logged to emoncms
emoncms can send commands back so that valves open...

we have a crude on/off control of gas boilers.... there should be an ouput
on the board that you can connect to a relay

2015-12-14 12:08 GMT+01:00 jekkos <notifications@github.com>:

**Comment by boelle** [comment]
some notes about OEM and opentrv... not sure if it helps?

http://www.earth.org.uk/OpenTRV/OpenEnergyMonitorProtocolNotes.txt

2015-12-14 12:08 GMT+01:00 jekkos <notifications@github.com>:

**Comment by boelle** [comment]
did the links giv you any clues?

**Comment by jekkos** [comment]
hm ok so there is basic integration in place? I'm into software alot so once I have a board I could try too look into this part..

**Comment by boelle** [comment]
nope we dont have any integration, it has been talked about a lot but one
one has taken the "job"

i have lots of ideas but not a software man at all

out for shopping

do you need link to the software we load on the boards ?

2015-12-15 15:00 GMT+01:00 jekkos <notifications@github.com>:

**Comment by jekkos** [comment]
yeah sure I'd like to see that.

**Comment by boelle** [comment]
i think its this one: https://github.com/DamonHD/OpenTRV/tree/master/Arduino/V0p2_Main

my idea is like it was written in one of the other links to switch modes.... the valves need an command every 2 min if i remember correct... so plenty of time to switch.... 

i think the argument against this was battery drain....

**Comment by boelle** [comment]
also code space could be an issue here.... so it might be hard

but what you could do... again just a thought....

collect all data like temp, light level, valve open% etc etc in openenergy mode and send it... and listen for new commands....

then switch to opentrv mode and tell the valve how much open it should be...

but i guess there are lot of ways to slice this cake... you want to make sure that if radio to OEM goes away it would still work in standalone

**Comment by jekkos** [comment]
Ok cool once I get a a hold of a board I might try to look into it. We're organising some hackatons from time to time which might be perfect to gather around developing a feature like this.

**Comment by boelle** [comment]
we have a dev list here: http://lists.opentrv.org.uk/listinfo/opentrv-dev

damon (CEO) will add you in as soon you have joined

not sure what's its called in belgium but OpenTRV is defined as a social
enterprise.... part real company and part opensource project.... but no
closed source

we focus mainly on carbon reduction and helping those who cant afford
heating.

i use district heating myself, we burn all our household waste 10 km at the
other side of town... from that they make electricity and also send warm
water in big pipes.... each house simply have a heatexchanger... my
heatexchanger is a combo unit with hot water cylinder for shower etc....
radiators go direct to district heating...

so i'm a special case as i cant simply open valves fully... i will send
back warm water and my bill is 2 parts... energy and flow.. so if i take
out energy at low flow i get a small bill...

i was told that this is the same for condensing gas boilers also...




2015-12-15 16:15 GMT+01:00 jekkos <notifications@github.com>:

**Comment by jekkos** [comment]
Yes I tried to subscribe to the dev list the other day, but was refused the access :(. Good to hear that it's a social project. There might be other persons interested in it at the local makerspace.

Never hear about this kind of heating installation. My heater is a Vaillant condensing burner. It has ebus interface for which I'm planning to do interfacing later on. opentrv the perfect addon for this system.

**Comment by boelle** [comment]
crap... do you have any email adress i can pass on so that you can be added
manual?

its quite common here....

ebus.... hmm.. i have heard about that befoe... not sure where.... i allows
to to control the burner more precise right?

2015-12-15 16:44 GMT+01:00 jekkos <notifications@github.com>:

**Comment by boelle** [comment]
you should have been added now... he could see your join attempt

2015-12-15 16:44 GMT+01:00 jekkos <notifications@github.com>:

**Comment by boelle** [comment]
dinner time... will be back later

2015-12-15 16:44 GMT+01:00 jekkos <notifications@github.com>:

**Comment by jekkos** [comment]
Ok great. Thanks.

**Comment by boelle** [comment]
might be good with short introduction as there are quite a few on the
list.... most are "sleepers" thou

2015-12-15 17:13 GMT+01:00 jekkos <notifications@github.com>:

**Comment by boelle** [comment]
tried to post to the list yet?

sometimes mails are blocked and it needs to be allowed..... this and that you where refused access on the list are just to prevent spammers access... was a problem and i  guess it still is if we remove this extra "security"

**Comment by jekkos** [comment]
OK I just sent a mail to the list. Would be nice if someone could send me some boards to do dev / testing on. Beside that I'm co-organizing a bi annual 'Arduino Jam' here in Belgium in which people team up to work on different projects. I think opentrv might be a good candidate to hack on.

**Comment by boelle** [comment]
Damon can send the boards as i think its him that piles them up

2015-12-16 11:02 GMT+01:00 jekkos <notifications@github.com>:

**Comment by boelle** [comment]
i think i will close this one as it was more opentrv talk... the other issue i have should still say it all

**Comment by jekkos** [comment]
Yes we've gone a little off topic. I think Damon will send me some pcb's later on. In mach we will have another hackaton. Hope I can have them by then so we can hack for a weekend on a feature/improvement of the project.

**Comment by boelle** [comment]
:-)

yeah and i guess it means hacking both the boards software an emoncms

2015-12-17 15:15 GMT+01:00 jekkos <notifications@github.com>:
