### ISSUE TITLE
OSPOS Sale Return

### ISSUE THREAD

**Issue by diganto213** [jekkos/opensourcepos#253]
Dear Expert,

Just wondering how the ospos sale return works ? If I select sale return then how to refer to the receipt which customer want to return 

Thank You

**Comment by odiea** [comment]
The return receipt number would be entered pos 3. The item being returned would then be selected. If the return receipt has multiple items just remove them from the list. I would make a note in comments which would then refer to the returned receipt.

**Comment by diganto213** [comment]
Ok thank you very much.
