### ISSUE TITLE
Sales/item kits

### ISSUE THREAD

**Issue by Semloji** [jekkos/opensourcepos#257]
I have a sale made up of item kit 2 - includes 3 items total R65
Quantity was increased on all 3 in kit to 66 but program did not adjust.
tried tabbing program to get acceptance of new qty but to no avail
defaults back to only 1
If i am selling 66 kits on this invoice is there another way?

john

**Comment by daN4cat** [comment]
Not sure I can follow your test case, are you able to describe better the sequence of actions to regenerate the issue?

**Comment by Semloji** [comment]
Make some stock items, make up kits of stock items, system calls these kits1 kits2 etc.
When making a sale and have now a choice of stock items and kit items, I choose the kit item instead of the stock item and the system asks for a quantity. I change the quantity to 66 of these kits and the new quantity is not accepted, defaulting back to 1.

**Comment by odiea** [comment]
Every individual item Qty in the kit must be changed then the edit button must be pressed for each item. This is a kit with 5 items. So 1st item change qty then edit button. All items must be changed. I have not seen just the kit number show as a single item on the sales screen.
![2016-01-01 04_58_11-once again thrift -- powered by os point of sale](https://cloud.githubusercontent.com/assets/10962177/12070770/f40cec18-b044-11e5-8005-f50805d25db0.png)

**Comment by Semloji** [comment]
Thank you that works
All the best for 2016

**Comment by daN4cat** [comment]
The issue seems closed.
