### ISSUE TITLE
Duplicate entry '#' for key 'invoice_number' when suspending sale

### ISSUE THREAD

**Issue by daN4cat** [jekkos/opensourcepos#259]
I get the error as in subject lne following this sequence:

- go to sale page
- add item to sale making sure "Create Invoice" is not checked:

![image](https://cloud.githubusercontent.com/assets/636048/12051754/88ef5c86-aeff-11e5-8c53-9df9118c80dd.png)

- also make sure there is a number in the invoice box (even if in grey) e.g. 7
- suspend the sale
- start a new sale
- add item to sale making sure Create Invoice is not checked (same conditions as above)
- suspend the sale again and you get the following error:

![image](https://cloud.githubusercontent.com/assets/636048/12051774/e7c92598-aeff-11e5-9e4e-8acc63e55126.png)

**Comment by odiea** [comment]
I tried to reproduce this issue but do not get the same results as you have seen. I have tried up to 6 times of suspending then adding a new sale.

**Comment by daN4cat** [comment]
Do you have the same invoice number between the two sales you are suspending?

**Comment by odiea** [comment]
Yes I do. Are you in your development branch?

**Comment by daN4cat** [comment]
Yes, I used my branch.

**Comment by daN4cat** [comment]
Have you tried to pass a normal sale with no invoice before doing my sequence?
That's something else in the pre-conditions to consider I suppose.

**Comment by odiea** [comment]
This branch is 134 commits behind jekkos:master is what your development branch states. I have tried multiple sales, suspend sale, new sale, unsuspend sale, resuspend sale.

**Comment by daN4cat** [comment]
? My master is up to date, it cannot be.

**Comment by odiea** [comment]
You have 2 branches Master which is up to date and development which is 134 commits behind jekkos:master. I was just wondering if you were working from your development instead of master?

**Comment by daN4cat** [comment]
from master, not sure what development is but I will check and obsolete that.

**Comment by odiea** [comment]
![2015-12-30 08_59_35-ugly sweater store -- powered by os point of sale](https://cloud.githubusercontent.com/assets/10962177/12053197/e3012b7c-aed3-11e5-98b3-82da1a2d9415.png)
![2015-12-30 09_00_03-ugly sweater store -- powered by os point of sale](https://cloud.githubusercontent.com/assets/10962177/12053198/e301b970-aed3-11e5-9c25-bbefd9179866.png)
![2015-12-30 09_00_31-ugly sweater store -- powered by os point of sale](https://cloud.githubusercontent.com/assets/10962177/12053196/e2fd22c0-aed3-11e5-90cf-367336812e73.png)

**Comment by daN4cat** [comment]
OK, this is weird...

**Comment by odiea** [comment]
Have you found out what's causing this issue?

**Comment by daN4cat** [comment]
Not really, I spent time upgrading to CI 3.0.3 and playing with the new UI.

**Comment by odiea** [comment]
Have you downloaded the newest version from jekko to see if that also creates your issue. I use mainly xampp so it's real easy to try different versions.

**Comment by odiea** [comment]
The new ui looks good except for Receivings and Sales.

**Comment by daN4cat** [comment]
Yes, the UI needs to be finished off. It's based on some partial work pulled from another git fork (see #120 for the discussion therad).

Also the language support seems not working properly.

**Comment by odiea** [comment]
Your more than welcome to try my version ospos.25u.com:8080 to see if you cn get the issue to show. I made changes in sales so a customer has to be selected to show invoicing. If you chose my name Otis agnew  it also fills out the customer info. I also changed the location of the finish sale button. I could not find a way around eliminating the Invoicing check mark automatically so I have it showing on the customer screen to see if Invoicing is active or not.

**Comment by daN4cat** [comment]
Tried but I don't see the issue. Also I don't see the check box as I reported so I'm not sure if invoice number changes or not.

Let's wait to jekkos to have a look and try, if he's not able to reproduce I would probably need to reset the database as I did once. But let see...

**Comment by odiea** [comment]
I have not seen the print and invoice boxes greyed out like your pic shows.

**Comment by daN4cat** [comment]
OK, so it must be something with your version because I can see it with my version.... have you changed something in your views?

**Comment by odiea** [comment]
No and I have tried it with multiple versions that I maintain. I even used your version this morning "zip and  git clone " and had no issues.

**Comment by daN4cat** [comment]
ok, so I probably need to reset everything and try again. But I'll do it in the New Year. Now I'm switching off and check everything on the 2nd :-)

**Comment by odiea** [comment]
Happy New year

**Comment by daN4cat** [comment]
You too :+1:

**Comment by jekkos** [comment]
Hay guys happy new year all. Just came across this thread :)

@daN4cat Think you need to drop the unique constraint for invoice_number in suspended_sales table. This db modification should be in the 2.3.3 upgrade script.

**Comment by daN4cat** [comment]
Good one, I haven't ran any db update script in the past couple of months. Must be that.

**Comment by daN4cat** [comment]
Confirm that after having applied:

ALTER TABLE `ospos_sales_suspended`
    DROP KEY `invoice_number`;

everything now works fine.
