### ISSUE TITLE
"Takings" not using proper permission

### ISSUE THREAD

**Issue by lutfiajib** [jekkos/opensourcepos#262]
Any transactions on "Takings" list can delete by any user.
How to protect this?

**Comment by daN4cat** [comment]
Probably Takings should have the same protection as reports/sale

**Comment by lutfiajib** [comment]
Yes. I agree Taking List is good. But
- Not every user can delete the transaction
- Not every user can see another day transaction

**Comment by jekkos** [comment]
OK I've added a check for the reports_sales grant to show/hide the takings button in sales register.
