### ISSUE TITLE
Error on page Ver 2.3.3

### ISSUE THREAD

**Issue by rizqbainy** [jekkos/opensourcepos#267]
A PHP Error was encountered
Severity: Warning
Message: strrchr() expects parameter 1 to be string, array given
Filename: hooks/load_config.php
Line Number: 27

Got this error when opening login page.

**Comment by daN4cat** [comment]
Which version of PHP do you use?

**Comment by daN4cat** [comment]
Do you have directories inside the language you selected?
Because you get that warning due to that.

That said, this needs to be fixed properly in the code and ignore dir and just deal with files.

**Comment by daN4cat** [comment]
Here an explanation that helps: http://stackoverflow.com/questions/12106530/using-codeigniter-directory-map-helper#12107120

**Comment by daN4cat** [comment]
This is now fixed in PR #270

**Comment by rizqbainy** [comment]
Thank you..will try later..
