### ISSUE TITLE
if login page is loaded under https a script is flagged as wrong

### ISSUE THREAD

**Issue by daN4cat** [jekkos/opensourcepos#269]
The culprit is that the following: http://fonts.googleapis.com/css?family=Open+Sans:300,400,700 in login.css doesn't use https and makes the login page unsecure.

It should be https://fonts.googleapis.com/css?family=Open+Sans:300,400,700

**Comment by daN4cat** [comment]
Fix in PR #270

**Comment by jekkos** [comment]
Ok good find. Should be integrated now.
