### ISSUE TITLE
Sales Takings

### ISSUE THREAD

**Issue by odiea** [jekkos/opensourcepos#273]
This will probably be an enhancement. In sales takings if you could replace the Delete button with a print button and remove the Edit column it would be a great feature to reprint a receipt if the cashier needs to.

**Comment by lutfiajib** [comment]
yes. i agree with this. cashier can reprint a receipt. we need this feature. just we need proper permission

**Comment by odiea** [comment]
With a little modification I think I have what I am willing to live with. I removed  some columns and added a print feature to the bottom of the receipt.
![2016-01-05 07_51_04-ugly sweater store -- powered by os point of sale](https://cloud.githubusercontent.com/assets/10962177/12118001/5c0821d6-b381-11e5-9252-8aa1b98f839f.png)

**Comment by jekkos** [comment]
does it print immediately in this case?

**Comment by odiea** [comment]
No. It will only print when I click on the print link. I used your Print from register with no button. I also created a css that does not display the word print on the receipt. So now I can eliminate the print check box and it will reprint the receipt with no problem.

**Comment by odiea** [comment]
This goes at the bottom of the receipt
![2016-01-05 12_50_36-c__xampp_htdocs_noicons_application_views_sales_receipt php - notepad](https://cloud.githubusercontent.com/assets/10962177/12125897/495d7d2c-b3ab-11e5-8f90-cf8e19bb91e8.png)
This goes on the receipt.css
@media print
{
.no-print, .no-print *
 
{
display: none !important; }

}

**Comment by odiea** [comment]
And with the templste version I placed that css into style.css and added to the partial header to prevent the partial header printing on the receipt.
![2016-01-05 13_01_41-c__xampp_htdocs_noicons_templates_cerulean_views_partial_header php - notepad](https://cloud.githubusercontent.com/assets/10962177/12126162/b7032d1c-b3ac-11e5-95a9-b35f82cb6caa.png)

**Comment by odiea** [comment]
Here is what the bottom of the receipt looks like.
![2016-01-05 13_28_59-ugly sweater store -- powered by os point of sale](https://cloud.githubusercontent.com/assets/10962177/12126759/59d49208-b3b0-11e5-8077-a254a6479e55.png)

**Comment by jekkos** [comment]
Look neat.

**Comment by daN4cat** [comment]
To summarise, when a user clicks on receipt link in the takings list the receipt will show a print link at the bottom to print it.

What we want here is to limit delete and edit.

**Comment by odiea** [comment]
No to summarize here there is no delete or edit function any longer and only the ability to view receipts or invoices  which can be printed or reprinted. As per the third comment.

**Comment by daN4cat** [comment]
Probably you want to have a permission to show or remove the delete and edit from Takings.

Wouldn't that be better and make things a bit optional?

**Comment by odiea** [comment]
My thought was to limit the ability to screw thing up by a cashier. A manager or admin can still go to detailed sales and edit the receipt as necessary. So no need to write permissions for a reprint feature available to the cashier.

**Comment by odiea** [comment]
And the bonus is you still get that nice takings view.

**Comment by daN4cat** [comment]
Yes, my point was to move the permission restriction from the whole Takings view to those two items (delete checkbox and edit link).

The cashier that has the permission to access sale can access Takings with restriction and do the print/reprint.

The people that have access to reports/detailed sale can see the delete checkbox and edit link even in Takings.

If fine the change is small on the view itself.

**Comment by odiea** [comment]
With this view the only permissions that would be needed would be the ability for the cashier to view the totals that should be in the cash register.

**Comment by daN4cat** [comment]
I'm getting lost, didn't we want to have the list but no delete & edit? Why now we just want the totals?

I was proposing to move the permission restriction from the whole Takings view to only delete and edit, and that's it.

**Comment by odiea** [comment]
To keep an honest cashier. If the totals are not shown we could use the amount as an end of day register count. The list without the edit and delete would be beneficial for a cashier to have the ability to reprint a receipt when necessary. But your idea would be great too.

**Comment by RamkrishnaMondal** [comment]
I use Google Chrome and never use the 'Print after sale' check-box.  Instead, after completing the sale, I use to go to takings > click on receipt  link > right click on the receipt page and select 'print'. This way I can print any receipt or invoice as many times as I needed.

**Comment by daN4cat** [comment]
This is not as trivial as it seems and before adding options inside controller code I would prefer to focus on the bootstrap part before doing this.
Therefore I marked it for 2.4.

**Comment by daN4cat** [comment]
Remove sale delete is in #382

**Comment by daN4cat** [comment]
Reprint is in #277 .
