### ISSUE TITLE
Ospos Auto Logout

### ISSUE THREAD

**Issue by diganto213** [jekkos/opensourcepos#275]
Dear Experts,

I am noticing Ospos getting auto logout sometime when browsing through different menus and options.

Could you help to understand what is the reason it is getting auto logout and the remedy ?

Thank You

**Comment by daN4cat** [comment]
Which version of OSPOS?

**Comment by jekkos** [comment]
Could be a problem with the duplicated cookies. CI3 should solve this problem in a clean way.

**Comment by diganto213** [comment]
I am using version 2.3.1.

**Comment by daN4cat** [comment]
What about upgrading to the latest 2.3.3 and see if you still have that problem?

**Comment by jekkos** [comment]
Yes would be good to hear if the base64 encoded cookie values solve this issue.

**Comment by diganto213** [comment]
Ok let me try , will update you guys.

**Comment by jekkos** [comment]
Any update yet?

**Comment by daN4cat** [comment]
No updates so I assume this is fine and close.

**Comment by tajammalads** [comment]
I found the solution for this.

Just go to file
../application/config/config.php

then go to "Session Variables" Section
and find "ses_match_ip"
then change value from "TRUE" to "FALSE"

$config['sess_match_ip'] = FALSE;

That's it. :)
