### ISSUE TITLE
Employees can back-up database but can not access Stores' Config page ?

### ISSUE THREAD

**Issue by RamkrishnaMondal** [jekkos/opensourcepos#276]
How to configure ospos, so that my employees can take a back-up of the database at the time of log-out, but can not access Stores' Config page ? 

Currently, they can take a back-up of database if and only if they are allowed to access "Stores' Config" Page.

Any idea ?

**Comment by daN4cat** [comment]
This most likely will require a dedicated permission that is separate from the admin / Store Config one.

**Comment by jekkos** [comment]
Yes currently only admins can do the backup.

**Comment by RamkrishnaMondal** [comment]
Ok... I got it. Closing the question for now.
