### ISSUE TITLE
Employee sales report. 

### ISSUE THREAD

**Issue by arionkosturi** [jekkos/opensourcepos#280]
Hello. For my first time I'm implementing computers in my store. Thank you for the great work and for making it open source.
Anyway, is there any possibility to hide the profit and cost from the employee's sales report? 
Thank you.

**Comment by odiea** [comment]
Are you trying to hide the totals at the bottom of the page or the columns in the report?

**Comment by odiea** [comment]
Download notepad ++ if you don't have it. Go to application/models/reports and open the report you want to edit. I usually copy and paste the line I am going to edit under the current line then comment out the top line for future references.
		//$this->db->select('sum(subtotal) as subtotal, sum(total) as total, sum(tax) as tax, sum(cost) as cost, sum(profit) as profit');
 The new line will look like this and it will only show totals.
$this->db->select('sum(subtotal) as subtotal, sum(tax) as tax, sum(total) as total'); I do not have any experience in changing the columns of the reports. Hope this helps.

**Comment by arionkosturi** [comment]
Thank you very much. I was able to dublicate the reports so I didn't lose dhe original reports
