### ISSUE TITLE
How to add a report to ospos

### ISSUE THREAD

**Issue by odiea** [jekkos/opensourcepos#281]
How the heck do I do it. I would like to create a report for accounts receivable based on Invoices. I tried to add it to Routs,listings reports models. Where does it need to be? Thanks

**Comment by jekkos** [comment]
Think @daN4cat wrote a good explanation on this matter some time ago. Maybe if we can find the issue then we should add it to the wiki.

**Comment by odiea** [comment]
I got the report to show so how do I give it permissions?

**Comment by daN4cat** [comment]
The explanation is here #118. I'll add a page in the wiki with that text.

**Comment by daN4cat** [comment]
wiki added: https://github.com/jekkos/opensourcepos/wiki/How-to-Add-a-new-Report

**Comment by daN4cat** [comment]
OK, we would need to add something about permissions. I guess to create a new permission you need to fiddle with the configuration views/controller.
Then of course use the permission around your report, but I guess you can just copy and paste this from another report and change names or variables or no?

**Comment by odiea** [comment]
Thanks again for your help.

**Comment by daN4cat** [comment]
:+1:
