### ISSUE TITLE
Parse error - Barcode_lib.php on line 3

### ISSUE THREAD

**Issue by joliber2** [jekkos/opensourcepos#282]
Hello there,

I'm getting this error:

Parse error: syntax error, unexpected T_STRING, expecting T_CONSTANT_ENCAPSED_STRING or '(' in /pos/application/libraries/Barcode_lib.php on line 3

Probably with this line of code use emberlabs\Barcode\BarcodeBase;

Thanks for any help.

**Comment by daN4cat** [comment]
Do you have this issue with 2.3.3?

**Comment by joliber2** [comment]
hello, this is an issue with 2.3.2. Is this resolved in 2.3.3?

**Comment by jekkos** [comment]
There were quite some changes done for barcode parsing/generation in 2.3.3 so it might be worth to take a look.
