### ISSUE TITLE
When move ospos of vps and works all ok except sales

### ISSUE THREAD

**Issue by halie412** [jekkos/opensourcepos#285]
hello i move ospos of vps (with export and import database) and move domain, in new location work all ok except sales (sales still blank without error), i test with permissons of apache and other database, and a new and blank installation of ospos and same problem. Somebody know what is happen?

**Comment by daN4cat** [comment]
Have you checked the error.log?

Isn't it the case that you have a php issue like for instance not having included the proper math lib support (see #202)?

**Comment by halie412** [comment]
excuse me, where is error.log?

**Comment by daN4cat** [comment]
in the root of the ospos directory (where you find COPYING, index.php). If there is a PHP issue you shouold get an error file.

**Comment by jekkos** [comment]
Probably the missing php-gd library. Check if you have this package installed.
