### ISSUE TITLE
Upgrade from 2.2.1

### ISSUE THREAD

**Issue by PeteOnza** [jekkos/opensourcepos#287]
Dear staff,
I've downloaded the last version of OSpS. How I have to proceed to update the version 2.2.1
best,

Christian

**Comment by daN4cat** [comment]
You need to run the sql upgrades under database in sequence from 2.2.1_to_2.2.2 to 2.3.2_to_2.3.3

Before doing that on a live database make a copy and give a try on a copy with an test installation of 2.3.3

**Comment by daN4cat** [comment]
I assume this is fine and I close.

**Comment by PeteOnza** [comment]
I'm sorry, I didn't try.
I hope to test the process in the next few days
Best,
Christian
Il 19/gen/2016 09:40, "FrancescoUK" <notifications@github.com> ha scritto:
