### ISSUE TITLE
PHP ERROR

### ISSUE THREAD

**Issue by ssaiifull** [jekkos/opensourcepos#289]
I am facing this problem. I cannot manage to do any operation for this problem. Plz see the attached picture. Thanx
![12](https://cloud.githubusercontent.com/assets/12080104/12397820/ced69f0e-be39-11e5-83d7-254c2bb4cea8.PNG)

**Comment by daN4cat** [comment]
Please use version 2.3.3 because that should be sorted.

**Comment by ssaiifull** [comment]
If i use 2.3.3 , when importing the databases from database folder selection database.sql it shows this error. What should i do ??
![sql error](https://cloud.githubusercontent.com/assets/12080104/12399809/592278b6-be46-11e5-96d4-23f05dc57022.PNG)

**Comment by daN4cat** [comment]
And have you run the update scripts from database folder?

Not sure from which version you are upgrading, but check around.

**Comment by daN4cat** [comment]
It looks like you just took database.sql but not the tables.sql and probably even constraints.sql.

Take the three and everything should be fine.

**Comment by jekkos** [comment]
I did the split up just to make the migration script easier to use. The source directive doesn't work from phpMyAdmin so I guess that's the main problem here. I think that I'll try to reconstruct the database.sql script with a grunt concat task using the two includes as input (will make a separate issue for this)
