### ISSUE TITLE
List of Customers - view

### ISSUE THREAD

**Issue by RamkrishnaMondal** [jekkos/opensourcepos#291]
I wish to see the Customer's first name first in the list of customers. Can any body tell me which file to edit ?

**Comment by daN4cat** [comment]
Go to application/helpers/table_helper.php
Search for the function `get_people_manage_table`, there is an array, if you swap the following

	`$CI->lang->line('common_last_name'),
	$CI->lang->line('common_first_name'),`

will fix your issue.

**Comment by RamkrishnaMondal** [comment]
Swapping the lines brings the first name first, but alphabetical order is not being maintained . Suppose I have 10 customers whose first name starts with 'A' , some of them showing on top of the page1 and some of them on top of the other pages. How to solve that ?

**Comment by daN4cat** [comment]
I think you need to go to `application/views/people/manage.php` and check `function init_table_sorting()`. Try to comment out the lines inside `headers:` and see if something works for you.
However you need to be careful because that impacts not only customer but employees and suppliers view.
