### ISSUE TITLE
Upgrade to CI3.0.5

### ISSUE THREAD

**Issue by daN4cat** [jekkos/opensourcepos#292]
Upgrade to CI 3.0.5 when available such we get the fix related to pagination (current CI 3.0.4 in OSPOS is already patched).

See #120 for more information about the pagination issue.

**Comment by jekkos** [comment]
CI 3.0.5 is released, upgrade can thus be done

http://forum.codeigniter.com/thread-64610.html

**Comment by daN4cat** [comment]
OK, one more in the todo list.

**Comment by daN4cat** [comment]
This is done and in master now.

I tested the pagination in items and works fine, so the fix was part of CI3.0.5.

**Comment by daN4cat** [comment]
Now in 3.0.0 (bootstraUI) too

**Comment by jekkos** [comment]
OK great. Thanks again. I havent found any time thuis weekend to continue work been with family all dat.

**Comment by daN4cat** [comment]
No worries, I'm giving now a bit of a push now because coming week until end of the month I'll be travelling.
