### ISSUE TITLE
Error #1064

### ISSUE THREAD

**Issue by handgun50** [jekkos/opensourcepos#294]
#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'SOURCE tables.sql' at line 14

I don't know how to solve this

**Comment by daN4cat** [comment]
Please read #289.

If you take the latest code from master and marked 2.3.4 you should get a fix to that because now database.sql contains everything in that file without including the other two.

**Comment by handgun50** [comment]
thanks. I update it and it works

**Comment by mrwebinn** [comment]
Hi there I had done all the steps of " opensourcepos " but there was an error when I launch " localhost/opensourcepos/ ''
( The configuration file database.php does not exist. )

Someone Please Help me
Thanks

**Comment by daN4cat** [comment]
Have you read the READ.MD file?
