### ISSUE TITLE
CI3.0.4 upgrade: Search suggestion showing the string with a space

### ISSUE THREAD

**Issue by daN4cat** [jekkos/opensourcepos#295]
From any view having a search box and suggestion (e.g. Sale, Items), whilst typing a partial string the suggestion drop down shows the found strings with the matching part in bold but with a space before and after in practice breaking the string.

The issue was original mentioned in #120 .

**Comment by cpl2015** [comment]
Item names are also showing with a space before and after each and after every letter.

**Comment by daN4cat** [comment]
This is now solved in develop/2.4 and in my bootstrapUI branch too.

Tested and I can close.
