### ISSUE TITLE
Same old database issues using phpmyadmin?

### ISSUE THREAD

**Issue by odiea** [jekkos/opensourcepos#300]
Is there a way to leave the remarks out. This is what causing the installation error?

Error

SQL query: 

-->> This file is autogenerated from tables.sql and constraints.sql. Do not modify directly <<--
--
-- Table structure for table `ospos_app_config`
--

CREATE TABLE `ospos_app_config` (
  `key` varchar(255) NOT NULL,
  `value` varchar(255) NOT NULL,
  PRIMARY KEY (`key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

MySQL said: Documentation 
 #1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-->> This file is autogenerated from tables.sql and constraints.sql. Do not modi' at line 1

**Comment by daN4cat** [comment]
Same issue as #301
