### ISSUE TITLE
Error 1064

### ISSUE THREAD

**Issue by Z-unit11** [jekkos/opensourcepos#301]
Hi,

I am new to PHP. Tried to follow the instructions given here http://www.opensourceposguide.com/guide/gettingstarted/installation

Step 1: Installed Mysql server 5.7 and using Wampserver

The error came once I tried to import database.sql file. Need some help from the experts! see error below:

Error
SQL query:

-->> This file is autogenerated from tables.sql and constraints.sql. Do not modify directly <<--
--
-- Table structure for table `ospos_app_config`
--

CREATE TABLE `ospos_app_config` (
  `key` varchar(255) NOT NULL,
  `value` varchar(255) NOT NULL,
  PRIMARY KEY (`key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
MySQL said: Documentation

#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-->> This file is autogenerated from tables.sql and constraints.sql. Do not modi' at line 1

**Comment by daN4cat** [comment]
Same issue as #300
