### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by Z-unit11** [jekkos/opensourcepos#304]
Need Help please!
Followed in instructions. Successfully imported database. For some reason getting "Internal Server Error" when I go to the page http://localhost/opensourcepos/index.php
Now encountered another issue; here is the error. The error message below appears when click on users tab. 
 
Your privilege table structure seems to be older than this MySQL version!
Please run the mysql_upgrade command(mysql_fix_privilege_tables on older systems) that should be included in your MySQL server distribution to solve this problem!

**Comment by odiea** [comment]
1. Are you migrating from an earlier version?
2. If not did you change the settings under config database to your database and rename the config file.
3. you shold just have to go localhost/opensourcepos and see what that does.

**Comment by Z-unit11** [comment]
1. No
2.Yes, I did.
3.No luck!

**Comment by odiea** [comment]
Are you using the current version from github.com/jekkos/opensourcepos ? If so try to reinstall the database using the database.sql file

**Comment by Z-unit11** [comment]
Using 2.4, let me reinstall the database

**Comment by Z-unit11** [comment]
I think it has something to do with Mysql 5.7. should I use older version? need your advice.

Thanks,

**Comment by odiea** [comment]
You can try it and see. You might also try the current master and see what happens with that.

**Comment by Z-unit11** [comment]
Here what I did so far,

downloaded MySQL 5.5 
Uploaded new master

Now, I am getting the following error
A Database Error Occurred

Error Number: 1146

Table 'ospos2.ospos2_sessions' doesn't exist

INSERT INTO `ospos2_sessions` (`session_id`, `ip_address`, `user_agent`, `last_activity`, `user_data`) VALUES ('69180fe9ca017a485ecbc0ee15cf9bde', '::1', 'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36', 1453763458, '')

Filename: C:\wamp\www\opensourcepos-master\system\database\DB_driver.php

Line Number: 330

**Comment by odiea** [comment]
can you get to the files. If so go into application/config /config and scroll down to sessions and change that from sessions_2 to sessions.

**Comment by Z-unit11** [comment]
looks like its is set as "sessions"
see below
$config['sess_cookie_name']		= 'ci_session';
$config['sess_expiration']		= 0;
$config['sess_expire_on_close']	= FALSE;
$config['sess_encrypt_cookie']	= FALSE;
$config['sess_use_database']	= TRUE;
$config['sess_table_name']		= 'sessions';
$config['sess_match_ip']		= FALSE;
$config['sess_match_useragent']	= FALSE;
$config['sess_time_to_update']	= 120;

**Comment by odiea** [comment]
I guess all I can say is delete or create a new database using just the database.sql script.

**Comment by Z-unit11** [comment]
I actually did that, created new database (named: ospos2). and used database.sql script.

**Comment by odiea** [comment]
And in database config you renamed that database to ospos2. I just downloaded and install 2.4 with no issues.

**Comment by odiea** [comment]
Sorry that should be application/config/database

**Comment by Z-unit11** [comment]
I am really struggling;

here what i did;
$db['default']['hostname'] = 'localhost';
$db['default']['username'] = 'mkhan2';
$db['default']['password'] = 'arsenal';
$db['default']['database'] = 'ospos2';
$db['default']['dbdriver'] = 'mysqli';
$db['default']['dbprefix'] = 'ospos2_';
$db['default']['pconnect'] = FALSE;
$db['default']['db_debug'] = TRUE;
$db['default']['cache_on'] = FALSE;
$db['default']['cachedir'] = '';
$db['default']['char_set'] = 'utf8';
$db['default']['dbcollat'] = 'utf8_general_ci';
$db['default']['swap_pre'] = '';
$db['default']['autoinit'] = TRUE;
$db['default']['stricton'] = FALSE;

**Comment by odiea** [comment]
Maybe @jekkos or @daN4cat can help later. It's after midnight their time. I don't have any other solutions for you. Sorry

**Comment by Z-unit11** [comment]
Thanks @odiea

**Comment by odiea** [comment]
I just noticed this $db['default']['dbprefix'] = 'ospos2_'; It should be 'ospos not ospos_2

**Comment by Z-unit11** [comment]
bingo! it worked

Thanks,

**Comment by daN4cat** [comment]
And the issue was?

**Comment by daN4cat** [comment]
MySQL 5.7, see #630
