### ISSUE TITLE
Add more integration tests

### ISSUE THREAD

**Issue by jekkos** [jekkos/opensourcepos#305]
Travis-ci seems to be more reliable thanks to the new docker setup. This means that now we can add more integration tests that mimic a user in the browser.

https://travis-ci.org/jekkos/opensourcepos

As an example I've added a create_items.js, which simply adds a new item to the item list. After this is done, a couple of asserts can be made to see whether everything is as expected. I think that it will be beneficial if we just add some tests for some common scenarios like making a sale, adding a customer or creating an order.

**Comment by odiea** [comment]
So does this just work on a newly created install or should I see something when I go I to make a sale?

**Comment by daN4cat** [comment]
You'll see the results of automated test cases running. But this is triggered mainly when we submit the code in github I think.

**Comment by odiea** [comment]
Just checking. I didn't know if this was related to ospos or docker ospos.

**Comment by daN4cat** [comment]
I just noticed that in 2.4 tests are failing. No idea why and I will need to investigate later (week-end?) unless you have time to?

**Comment by daN4cat** [comment]
Test seems fine now in develop/2.4. I also merged all the latest I had in my ci3 and from master and committed to develop/2.4. Tests are passing if I got the right view here.

**Comment by jekkos** [comment]
Yes they should now. I tried to add some basic tests and more can be added in the future.

**Comment by daN4cat** [comment]
BTW, I had few merges to sort out between what was develop/2.4 and I had in my branch and what you committed.
Now all is in sync again, but could you please make sure you have now the latest develop/2.4 rebased so we don't overwrite stuff?

**Comment by jekkos** [comment]
Did you get a forced update then or something? I did merge in some changes from 2.3.3 and rebased afterwards..

Most of the time I don't really like the extra overhead when merging between branches, especially when there ie only one or two changes in between.

**Comment by daN4cat** [comment]
I kept rebasing up to a certain point but then it became cumbersome with the risk of missing some change in the whole process if you don't know the complete history.
So I switched to merging to pick up only what really changed.

**Comment by daN4cat** [comment]
I believe this can be closed. The underlay support is in place and adding more test scripts will be an evolutionary story.
