### ISSUE TITLE
Unicode not supported

### ISSUE THREAD

**Issue by mouli39049** [jekkos/opensourcepos#306]
![unicode](https://cloud.githubusercontent.com/assets/16497012/12604301/63934050-c4e0-11e5-8755-fd501730802b.png)
In Print after sale unicode font not supported. Its shows question mark. "���ரிசி" This is in tamil unicode typed in Google Language Bar. Any solution?

**Comment by jekkos** [comment]
There's probably a translation issue along the way. Can you check whether this data is saved correctly in your database? If it is stored correctly in the ospos_sales_items table then try to change the browser page encoding for this receipt to see whether the characters show up correcty.

**Comment by jekkos** [comment]
Did you find a solution here? Might be good to share then :)

**Comment by mouli39049** [comment]
I remove and added again. its working fine. Nothing problem with unicode. Thank you.
