### ISSUE TITLE
Option in Config: Thousands Separator and Decimal Point

### ISSUE THREAD

**Issue by marteserede** [jekkos/opensourcepos#31]
It would be nice to choose in the config if one wants a dot or komma as a decimal point and if there should be a thousands separator. In Indonesia where 100,000.00 Rp are about 10US$ , so the thousand separator is very important.

**Comment by flodef** [comment]
Same here for European currency 😧

**Comment by jekkos** [comment]
integrated in ade913f0e477c1fe848283987c6be931aa2c397d
