### ISSUE TITLE
Forbidden Sales Takings.

### ISSUE THREAD

**Issue by arionkosturi** [jekkos/opensourcepos#310]
Hi. What I'm doing wrong?
You don't have permission to access /< on this server.
I'm trying to access it in the server with my admin user. Where do I change the permissions?

**Comment by daN4cat** [comment]
What about checking Employees and then edit your role? There you find the permissions.

**Comment by arionkosturi** [comment]
No takings permissions on employees. I think I should edit a file but I have no idea where to look

**Comment by jekkos** [comment]
Use the report / sales permission for that.

**Comment by arionkosturi** [comment]
It's not forbidden because of the permissions. It doesnt translate the route sales/manage. Tried to copy the file register.php from a working installation but the same problem.
I can access talkings from inserting manually the address ip/index.php/sales/manage

**Comment by arionkosturi** [comment]
![screenshot_2016-01-29-10-07-12-34](https://cloud.githubusercontent.com/assets/6469301/12697081/6be28c38-c77a-11e5-8944-146e0d455f05.png)

**Comment by daN4cat** [comment]
Which version are you using?

**Comment by arionkosturi** [comment]
2.3.4
Is there any possibility to set the url static in the view?

**Comment by daN4cat** [comment]
Instead of tweaking things I would check what's wrong with your setup. Have you touched something? Have you upgraded or downgraded from another version?

**Comment by arionkosturi** [comment]
I installed my first server used it for my store. On another server I made tests and tweaks to fulfill my specific needs. Never touched the .htaccess
I did upgrade the master server from 2.3.3 to 2.3.4, this fixed the barcode error that other were experiencing.
I'm thinking for a fresh install but don't want to lose my tweaks.

**Comment by arionkosturi** [comment]
The only difference between two servers was wamp version.
Sorry guys.
