### ISSUE TITLE
Problem with generating_languages.php

### ISSUE THREAD

**Issue by handgun50** [jekkos/opensourcepos#311]
I want to help with id translation.
But, after edit the csv and do the generating_languages.php, the translated file get a bit broken (Look at attachment)
This cause some elements like pop up window when want to add items, customers, etc not working when using id language

![id](https://cloud.githubusercontent.com/assets/8114257/12681771/d412c5f4-c6e2-11e5-94b5-ca55c4d92f9d.PNG)

**Comment by jekkos** [comment]
Maybe post the edited csv file so I can see and try to find the issue here?

**Comment by handgun50** [comment]
That thing happens with non-edited csv file and edited csv file. The picture I post above is using non-edited csv file.

**Comment by jekkos** [comment]
I have tried the generate for this language and I'm not seeing these newlines in my generated files. There must be something else causing this issue.

**Comment by daN4cat** [comment]
I saw this issue as well. There is an extra LF added somehow.

**Comment by ais-one** [comment]
@handgun50 what platform are you using, Linux or Windows or OSX? 

I tried generating the files with no problems on the following.
- Windows 8, 32-bit XAMPP (strlen PHP_EOL == 2)
- Ubuntu 15.10, 64-bit XAMPP (strlen PHP_EOL == 1)

Also, looks like you are using Notepad++ to edit.

My file in the Notepad++ below shows Dos\Windows, UTF-8 w/o BOM

**Comment by daN4cat** [comment]
No special cvs, just running the one that is currently in the repo will cause the issue for me.

I'm running the script on my webhost based on linux x86_64 (I think they use CentOS if my memory is not mistaken).

**Comment by jekkos** [comment]
Haven't been able to reproduce this. Is it still present?

**Comment by jekkos** [comment]
Is probably only present in some text editors. at first sight the script might indeed append two newlines at the end, one which is PHP_EOL and one which is \n. Think I'll try and remove the first and replace the latter with PHP_EOL.

**Comment by daN4cat** [comment]
As said already, I just take what is currently in the code, run translation.php from my webhost and the translations show that issue.

No upfront editing of the files.

**Comment by jekkos** [comment]
Is this issue only present in id files? These are the last column in the csv so maybe the newline needs to be stripped from each line.

**Comment by daN4cat** [comment]
I think I spotted with Turkish too. But I need to give a run and send you the files so you can see. I'm on the move now, so cannot do until tomorrow probably.

**Comment by daN4cat** [comment]
But Id is for sure.

**Comment by jekkos** [comment]
Problem could be that the end of line character from the csv is included in the language file output, as it's the last column in most csv files. I've added a str replace call for that but can't seem to reproduce the issue. So would be nice if someone could post a csv and output file with the issue present so I can look at the whitespace characters and compare.

**Comment by jekkos** [comment]
Problem could be that the end of line character from the csv is included in the language file output, as it's the last column in most csv files. I've added a str replace call for that but can't seem to reproduce the issue. So would be nice if someone could post a csv and output file with the issue present so I can look at the whitespace characters and compare.

**Comment by daN4cat** [comment]
Since I can reproduce it's better if you commit the change and I test. There is no special file, it happens with the one we have in master. It's probably the setup that causes this, I don't know to be honest.

**Comment by jekkos** [comment]
I've done  a change that strips newlines from the strings for each language in the csv. It doesn't create a difference in my setup as the id output is ok already. I'll commit the changed script later today so you can test.

**Comment by daN4cat** [comment]
Yes please. Thanks.

**Comment by jekkos** [comment]
Ok I've pushed a possible fix not sure if it's gonna solve this issue (without testing)

**Comment by daN4cat** [comment]
Almost right.... just few weird cases with id where there is an extra \" at the end see:

```
$lang["giftcards_cannot_be_deleted"] = "Tidak dapat menghapus GiftCard terpilih, Satu atau lebih GiftCard yang dipilih memiliki Penjualan.";
$lang["giftcards_cannot_be_deleted"] = "Tidak dapat menghapus GiftCard terpilih, Satu atau lebih GiftCard yang dipilih memiliki Penjualan.\"";
```
```
$lang["common_confirm_search"] = "Anda telah memilih satu atau lebih baris, ini tidak akan lagi dipilih setelah pencarian Anda. Apakah Anda yakin ingin mengirimkan pencarian ini?";
$lang["common_confirm_search"] = "Anda telah memilih satu atau lebih baris, ini tidak akan lagi dipilih setelah pencarian Anda. Apakah Anda yakin ingin mengirimkan pencarian ini?\"";
```
```
$lang["common_welcome_message"] = "Selamat Datang, klik modul di bawah ini untuk memulai";
$lang["common_welcome_message"] = "Selamat Datang, klik modul di bawah ini untuk memulai\"";
```
```
$lang["items_cannot_be_deleted"] = "Tidak dapat menghapus item terpilih, satu atau lebih item yang dipilih memiliki penjualan.";
$lang["items_cannot_be_deleted"] = "Tidak dapat menghapus item terpilih, satu atau lebih item yang dipilih memiliki penjualan.\"";
```
```
$lang["login_welcome_message"] = "SELAMAT DATANG. Silahkan login untuk masuk aplikasi, Isikan Nama Pengguna dan Kata Kunci Anda di bawah ini.";
$lang["login_welcome_message"] = "SELAMAT DATANG. Silahkan login untuk masuk aplikasi, Isikan Nama Pengguna dan Kata Kunci Anda di bawah ini.\"";
```

**Comment by daN4cat** [comment]
It looks like in the original .csv files certain sentences have "" with non-western languages.

You should check the source file to understand.

**Comment by daN4cat** [comment]
I'm trying to remove those " to see what happens rerunning the translation.
Also there are \' in some french files, I remove those \ as well.

**Comment by daN4cat** [comment]
Silly me, you cannot remove the " if there is a , in the sentence..... so that bug needs to be sorted @jekkos

**Comment by jekkos** [comment]
Ok but the return bug is gone then?

**Comment by daN4cat** [comment]
Yes, there is just that new one I described above.

**Comment by jekkos** [comment]
Ok did some cleanup I don't see those extra characters anymore now. Kind of tedious to test it without being able to reproduce

**Comment by daN4cat** [comment]
Let me check, and if fine I've ready the drop for 3.0 with some language fixes.

**Comment by daN4cat** [comment]
@jekkos, not good news, I still the same issue as above with the extra \" in id, on sentences betweet "".

**Comment by jekkos** [comment]
that's weird. I reverted the code that caused this original. Now there's an extra find/replace for every line that contains a return char.

**Comment by jekkos** [comment]
![screenshot from 2016-03-18 11 16 08](https://cloud.githubusercontent.com/assets/576234/13874910/f29f0f94-ecfa-11e5-8496-c1d7e2c70b79.png)

**Comment by jekkos** [comment]
Here on my side there's no difference comparing the newly generated files with the original (the ones generated by the script before my change).

here a screencap that shows the generated file with the latest script with all whitespace and end of line characters highlighted.

**Comment by jekkos** [comment]
This could be something platform or version specific in the end. In this case it was done on ubuntu with php 5.5.9.

Which php version are you using on your host?

**Comment by daN4cat** [comment]
Apache Version	2.4.18
PHP Version	5.5.32
Architecture	x86_64
Linux CentOS

**Comment by jekkos** [comment]
Ok perfect can you give output of this command `php -r "echo ini_get('auto_detect_line_endings');" `

**Comment by daN4cat** [comment]
Result is 0

**Comment by jekkos** [comment]
Ok same here for that result. Should retry with the php function hope this is solved then (here on my local machine all ok now).

**Comment by daN4cat** [comment]
Yep, sorted. It now works fine.

I pushed in 3.0 as well together with a some fixes in translations.

Case closed.
