### ISSUE TITLE
Print invoice before taking payment?

### ISSUE THREAD

**Issue by MaineBaronMoto** [jekkos/opensourcepos#312]
Is there a way that I can print an invoice before taking payment and completing the sale? I'd like to print the invoice, and then suspend the sale until payment is received.

**Comment by odiea** [comment]
Currently OSPOS is not setup for US type of Invoicing.

**Comment by daN4cat** [comment]
The application is more for shops with standard and direct way of selling things (e.g. boutique, groceries, second hand).
What you are asking sounds more a deferred payment and invoice management.
Of course all is possible but then you need to create a new set of functionalities.
It would probably make more sense to produce the invoice and resolve the stock management with OSPOS and manage payments and etc. with some external tool to even re-conciliate payments and etc. It sounds more a customer management system or something like that.

**Comment by daN4cat** [comment]
See #352

**Comment by gauravpolekar** [comment]
Print before sale will be useful for **restaurant** billing, print will be useful as a kitchen copy.

**Comment by SteveIreland** [comment]
Sounds a lot like a work order for invoicing.  A work order is printable but immediately upon printing it goes into a suspended order state.  It can then be recalled and altered before being completed.

**Comment by gauravpolekar** [comment]
How to create work order, Can you please tell the steps or any configuration if required.

**Comment by gauravpolekar** [comment]
Got it, In Configuration we can check 

> Work Order Support
But how to print this
