### ISSUE TITLE
MariaDB

### ISSUE THREAD

**Issue by daN4cat** [jekkos/opensourcepos#313]
Just wondering if anybody used MariaDB instead of MySQL.

Any good? Is the performance better? Anything to share about upgrading OSPOS from MySQL to MariaDB - in theory it should be transparent -?

**Comment by odiea** [comment]
I found Xampp has a new version that has MariaDB. I also ran across this to see if anyone has tried it out yet. Install the APCu PHP cache to speed up PHP. I installed the xampp with mdb on Win 10 with the standard version of ospos and it appeared to be a little snappier. The db install went just as it always has.

**Comment by jekkos** [comment]
I tried in it once on my Synology diskstation. Works as a drop in mysql. So basically you can import your mysql settings which should work fine. However i remember that I did have some trouble with the setup, partly due to the specific migration script supplied by Synology itself.

**Comment by daN4cat** [comment]
From odiea's words it seems performing better.
I would have different things to move from MySQL to MariaDB. I would need to think about.

**Comment by cpl2015** [comment]
Try Laragon on windows. It uses MariaDB by default.

http://sourceforge.net/projects/laragon/

**Comment by daN4cat** [comment]
I don't use Windows to run my web services.
However that link sounds a good option for people that want to install a playground and run ospos.
