### ISSUE TITLE
Add the ability to update a payment type when editing a sale

### ISSUE THREAD

**Issue by daN4cat** [jekkos/opensourcepos#314]
I often face the issue that the shop assistant selects the wrong payment type and then they are not able to fix it with an edit.

There is a similar request here: https://sourceforge.net/p/opensourcepos/discussion/1817181/thread/b4d8a4cc/?limit=25#98a8 

It would be handy to add an edit drop down in the transaction editing to be able to change the payment type.

**Comment by cpl2015** [comment]
If  this feature is implemented, it will also open the door of credit sales.

**Comment by daN4cat** [comment]
Add the ability to change the payment type in the sale edit form.

Few notes:
- it allows just to change the payment type, no amount is touched directly
- if a type is changed for another one already listed, at submission time all is summed up to be one payment type amount
- giftcard cannot be touched, it will be far too complex to change it and I assume the user selected the giftcard on purpose. So amount is visible but not something that can be touched. Also giftcard option is not available as payment type
- if a payment was 0, when submitting it will be removed. In this way we clean up automatically of non-sense

NOTE: from Takings when the edit is finished the table does not update. I didn't fix because I know @jekkos is changing tables so it does not make sense to spend time in fixing something now that will change. There is a manual workaround, just go to the search box and type enter, the table and totals will update.

In general this feature is just to fix some errors that tend to happen like I selected Debit Card instead of Credit Card, or it was Cash instead of Debit Card. Also it's in place to remove 0 payments happened by mistake.
So it's just to fix some common mistake and nothing more like changing the amount paid with one type or another. No that's not implemented and I don't have the intention to add it. Contributions always welcomed.

**Comment by RamkrishnaMondal** [comment]
I have replaced the 'changed' files in my existing 3.0 setup and getting this error:

![screenshot from 2016-04-18 11 47 01](https://cloud.githubusercontent.com/assets/14151032/14595264/97ab667c-055b-11e6-8f10-9f2ce597fe2e.png)

**Comment by daN4cat** [comment]
That's nothing to do with this change as it's about discount. Have you run the database upgrade script?

**Comment by RamkrishnaMondal** [comment]
No........... i have not.

**Comment by RamkrishnaMondal** [comment]
When executing sale getting this.
![screenshot from 2016-04-18 11 58 29](https://cloud.githubusercontent.com/assets/14151032/14595474/2a0ab9ae-055d-11e6-8f25-0f2a56f0e487.png)
 May be some TYPO, as the controller/Sales got changed:

**Comment by RamkrishnaMondal** [comment]
Problem in loading "customer data'..... if i execute a sale without adding a customer, no problem is there.

Good feature addon , I must appreciate.

**Comment by daN4cat** [comment]
Have you updated all the code? There are changes in the models too, probably you didn't update those.

**Comment by RamkrishnaMondal** [comment]
Yes total 7 files. Now downloading new master ... will make a fresh install with new db.

**Comment by RamkrishnaMondal** [comment]
Got this when creating new db for fresh install:
![screenshot from 2016-04-18 13 56 06](https://cloud.githubusercontent.com/assets/14151032/14597935/8241a618-056d-11e6-8838-36224dcb9257.png)

**Comment by daN4cat** [comment]
yep, fixing.

**Comment by RamkrishnaMondal** [comment]
IN WHICH FILE ?

**Comment by daN4cat** [comment]
Please take the latest master as I fixed two things: an issue with customer name in sales/form and the database.sql typo

**Comment by RamkrishnaMondal** [comment]
New install works out of the box now.

**Comment by daN4cat** [comment]
Good. Thanks for the test and issue report. I couldn't test all the possible scenarios.

Test automation needs a fix and improvements.

**Comment by jekkos** [comment]
Yes indeed the tests should be adapted to work with the new layout (probably some missing button ids)

**Comment by daN4cat** [comment]
I tried once to fix a test script but I cannot get is to fetch correct elements. Also the test framework documentation is poor. I don't have that much time to dig in the code to understand how it works.
Maybe you can point me out to something that can help me in getting my mind around that.

**Comment by daN4cat** [comment]
Can anyone see any other problem with this? I would like to close the issue.

@odiea I know you had additional questions, but that goes beyond the initial intention to fix trivial OSPOS user mistakes.
