### ISSUE TITLE
how to make all location quantity be visible under item name

### ISSUE THREAD

**Issue by walterhumphreys** [jekkos/opensourcepos#316]
hi guys wondering is there a way to make all location/ stock quantities be visible under item name insted of just seleted location, example I have 25 items in location A and 30 in location B  is it possible when I'm in register mode, as I pull the item it displays both location at the same time under item name, can it be like if item location > 0 display locations ?
 I'm just saying is it possible

**Comment by jekkos** [comment]
Yes then you will need to loop over all the item quantity entries for that item for every line in the register or receviings module. Then output the found quantity next to the stock location name as is done now.

**Comment by walterhumphreys** [comment]
im a noob with this framework as well with php, im actually coursing php, well i dont know if im wrong with what im about to say , and sorry for my ignorance in advance, but the variables that are declared i just cant find them, for example the create the loop as you did say i need to understand completely everything and there is where im stuck, how can i tell it, 

for item_in_stcok 
if quantity > 0
<?php echo $item['item_location'] ?>
<?php echo $item['in_stock'] ?>
<?php echo $item['stock_name'] ?>
else

quantity == 0;

<?php echo form_hidden($item['stock_name'], $item['item_location'], $item['item_location']); ?>


i know this may have a lot of systaxes errors but is the idea basically of what i need to accomplish,
