### ISSUE TITLE
A Database Error Occurred

### ISSUE THREAD

**Issue by onyema3** [jekkos/opensourcepos#318]
Hi,
After installing the latest master of opos i noticed that on logout when i click ok to backup db i get this error.
A Database Error Occurred
Unsupported feature of the database platform you are using.
Filename: /Applications/MAMP/htdocs/opos/controllers/config.php
Line Number: 193
i'm a novice on php and i don't know what to do.
I'm running opos on mamp pro 3.5

Thanks

**Comment by daN4cat** [comment]
Which version on MySQL and PHP do you use?
Have you checked the MySQL user you have created has all the privileges?

**Comment by onyema3** [comment]
Php 5.4.42 and mysql 5.5.42 and  mysql user has all privileges

**Comment by daN4cat** [comment]
If I check ospos 2.3.4 controllers/config.php line 193 I read the following:     function backup_db()

An error there doesn't sound right to me.

What is the code in your installation at line 193?

**Comment by onyema3** [comment]
function backup_db()

**Comment by daN4cat** [comment]
Hang on, why is the error reported from ../opos/controllers/config.php where it should be ../opos/**application**/controllers/config.php ?

Is your installation correct?

**Comment by onyema3** [comment]
My installation is correct. Every other aspect of ospos is working fine.

**Comment by odiea** [comment]
This error is also received when you try to do a backup in a container. 
Unsupported feature of the database platform you are using.

Filename: /app/controllers/config.php

Line Number: 204

**Comment by daN4cat** [comment]
So is this a docker related thing?

**Comment by daN4cat** [comment]
To be honest I find this backup option on logout a nuisance.
I don't like it at all, but that's my personal view.

**Comment by jekkos** [comment]
No problem to remove it. Think it's not really relevant either :)

**Comment by daN4cat** [comment]
I'll remove.

**Comment by daN4cat** [comment]
Fixed and new PR ready.

Once this is closed, should we push out a 2.3.4 and move to 2.4?
I don't think we will get any more translations and issues are more or less fixed.

Also we made some improvements worth publishing.

**Comment by onyema3** [comment]
Thanks.
Tested and Working

**Comment by odiea** [comment]
Sounds like we have a 2.3.4 as current version. Good work !

**Comment by jekkos** [comment]
If there are no more known bugs left then agree, we could round up and release this last minor.

Might indeed be good to start focusing on 2.4 instead.

**Comment by daN4cat** [comment]
Agreed. (and this is now closed).
