### ISSUE TITLE
Move develop/2.4 to master

### ISSUE THREAD

**Issue by daN4cat** [jekkos/opensourcepos#321]
Since 2.3.4 is out, I believe it's time to move develop/2.4 to master.

I merged the latest master in develop/2.4 so it's just a matter of merging back to master or reverse that last merge and merge develop/2.4 prior to my last merge to master.

**Comment by jekkos** [comment]
I suggest that we merge 2.4 into master and then delete the 2.4 develop branch.

**Comment by daN4cat** [comment]
Ok, I'll do today or tomorrow.

I'll create a bootstrapUI branch soon after to mirror my work out of master with 2.4.
Not sure I've the rights to delete develop/2.4 branch.

**Comment by jekkos** [comment]
Think you have push access so guess that means you should be able to delete branches as well.

    git push origin :develop-2.4

this will delete a branch on the origin repo

**Comment by jekkos** [comment]
Maybe it might be better to have one branch for development, and one with 'stable' code. What do you think? So in this case we would do development on develop and periodically merge to master (once things are tested)

**Comment by daN4cat** [comment]
Sounds sensible

**Comment by jekkos** [comment]
In this case we should just stick with the current way of working and only merge the develop branch to master once things are stable (in this case when we want to tag a release version or have a stable version with no known bugs).

**Comment by daN4cat** [comment]
so you mean I should merge bootstrapUI to develop/2.4 and keep going from there.

**Comment by jekkos** [comment]
yes maybe that will be a good idea

**Comment by jekkos** [comment]
I'll close this one for now.
