### ISSUE TITLE
Bootstrapify Forms with JSX templates

### ISSUE THREAD

**Issue by jekkos** [jekkos/opensourcepos#324]
I'd like to redo the forms for items, suppliers customers and sales using (currently leave most of the employees form intact as it's a little more complex)

* react-bootstrap as building block
* common modal dialog jsx parent component
* specialized form components defining common logic
* jsx processing using grunt
* probably keep jquery validation at first

**Comment by daN4cat** [comment]
@jekkos I'm not sure the react-bootstrap story is a good idea. Please read the comment I put in the UI restyling.

react-bootstrap is redesigning all the UI from HTML to be js only using react-bootstrap. Are we going to rework half of the code on views and controllers with this?
Why not fixing what we have with normal bootstrap and js? Not sure I get the turning upside-down on things now.

**Comment by daN4cat** [comment]
If you want to go for that, please branch off from bootstrapUI so we don't get halfway swamped on that story before we see the full benefits.

Personally I would like to get it a bit out of the way with bootstrap upgrade and js upgrades where necessary and leave fancier stuff for second steps.

**Comment by jekkos** [comment]
I will try this in a separate experimental branch indeed. I was looking into moving the dialog to bootstrap format and wondering whether it wouldn't be quicker to make a component for the forms alone. 

I'll give it a try for one of the forms and see how far I have to go to make it work. Regarding the controllers, in this case it'll be easier to spit out the php object in json encoded form. (in this case eg json_encode($item). This will yield a json object for that form containing all the properties to be shown. Also for saving it back to the server things will be easier and more 'object oriented', as the js object will be manipulated and simply sent back to the sever, in one field (then parsed using json_decode).

**Comment by daN4cat** [comment]
Yes I appreciate the benefits and please don't misinterpret my take as negative or else. It's more a pragmatic point.

In the end the bootstrap after CI3 upgrade has been a big push and effort. So I'm more keen to get to a first end even if not ideal and then we can figure out the next leap.

Once the UI restyling is done I would prefer to focus on more functionality that we would really need in the shop. We are still on the old OSPOS and I'm missing some changes before I can do a first migration (we have 5 years of data to migrate and retain).

**Comment by jekkos** [comment]
Ok maybe it's better indeed to make it work with regular bootstrap first. I've been trying to do this for the items form now yesterday eve and this morning, and have a modal dialog showing, but currently can't properly hide it once I submit the form.

Regarding extra functionality, what I'd really like to solve is the extra categories thing. Some of my users are still using a customized version because of this. I think you're in the same situation with the season , attribute. Would be good if we can come up with a generic solution for this. (will propose something coming week)

**Comment by daN4cat** [comment]
Yes, categories is my first item in the todo after this UI story.
Also @odiea has the same issue since he's using custom fields matching some of mine and some extra (e.g. tag colour).

Indeed a generic solution would be great, my worry is the impact of the current db migration. But I guess the script can safely do.

**Comment by daN4cat** [comment]
The categories should remove the need for custom fields, or at least reduce the list to few.

**Comment by daN4cat** [comment]
@jekkos shall we close this?

**Comment by jekkos** [comment]
I'm not planning to do this any time soon, however it would have been a nice exercise. So yes you can close just get our issue tracker a little cleaned up is not a bad idea.
