### ISSUE TITLE
French Translations to update

### ISSUE THREAD

**Issue by konceptech** [jekkos/opensourcepos#326]
There is some words, sentences not properly translated.
- On the login Page: Nom d\'utilisateur (User Name) should Be: Nom d'utilisateur
- The upper right button is too small to contain french translation
- On every word that contain ' php add a slash
- Gender should be Genre
- Receive mode should be Mode de réception then: Reception and Retour

I can be part of the contribution to tranlate the rest if you need

**Comment by daN4cat** [comment]
Yes please help with the translations. Thanks

**Comment by konceptech** [comment]
Is there a translation file for french?

And where is it located?

**Comment by jekkos** [comment]
check the csv files in translations/ folder of the project. Open in an editor like excel. Then change texts in each file with fr on top. Finallly run
     
     php generate_languages.php

and make a pull request with this repo.

**Comment by daN4cat** [comment]
Please make sure it's standard French, if you want a Canadian French variant it's better to create a new version tagged with fr-CA.

**Comment by daN4cat** [comment]
@jekkos do we want to fix this in a 2.3.5 or have it in 2.4?

**Comment by jekkos** [comment]
I would integrate in develop/2.4 and then merge to master later.

**Comment by daN4cat** [comment]
@konceptech what's the status of French translation?

@jekkos I retag to be 2.3.5 because we could add this to that version since we need to issue one.

**Comment by daN4cat** [comment]
Any news?

**Comment by daN4cat** [comment]
@konceptech I close this because I see no progress.

**Comment by daN4cat** [comment]
@konceptech  any chance you can look into the latest 3.0 and updated French translations?
