### ISSUE TITLE
3 decimals taxes

### ISSUE THREAD

**Issue by konceptech** [jekkos/opensourcepos#327]
The database cant take taxes longer than 3 decimals, for exemple Quebec Taxes are:
TX#1: TPS: 5%
TX#2: TVQ: 9.975%

On ospos_items_taxes table it appears:
TX#1: TPS: 5%
TX#2: TVQ: 9.98%

**Comment by arionkosturi** [comment]
Try changing ospos_items_taxes in phpmyadmin. In thd structure tab, change length value to 15,3

**Comment by daN4cat** [comment]
let us know if the workaround is fine.

**Comment by konceptech** [comment]
That's exactly what i did, it works for the taxes configuration, but in
invoice module, the taxes still 9.98.

**Comment by arionkosturi** [comment]
I think you should check the views. I'm not on PC right now but I'll take a look later.

**Comment by arionkosturi** [comment]
In the reports calculations is all ok or with approximation?

**Comment by konceptech** [comment]
It is with approximation, i think i have the correct the structure tab on
each module.

**Comment by arionkosturi** [comment]
You should change ospos_sales_items_taxes to 15,3

**Comment by arionkosturi** [comment]
Check currency_helper in www/application/helpers and change the decimal point to 3. It will do the job in the sales view and in the receipt. Now should look for a workaround for the reports.

**Comment by arionkosturi** [comment]
In models/reports/summary_taxes also change 2 to 3

**Comment by daN4cat** [comment]
OK, now this is done with my commit:

- Taxes can have up to 3 decimals and configurable in Store Config, Locale tab
- Totals are rounded according to the highest decimal between currency and tax (e.g. currency decimals = 2 and tax decimals = 3, totals decimals = 3)
- In case Tax decimals is 3 currency values are shown with 3 decimals even if the decimals are selected to be 2. This is a trick for the special case.

You need to run the database update script to change the tax decimals from (15,2) to (15,3).

All the conversions are done via locale_helper.php functions, so those can be tweaked in the future if required.

**Comment by daN4cat** [comment]
This is in bootstrap UI (3.0) branch.

It would be nice to have some help with the test of the feature.

**Comment by odiea** [comment]
What I see in Items is cost and sale price inherit the decimal settings of tax. I set currency to 2 and tax to 3 currency shows 3 in items.

**Comment by daN4cat** [comment]
That's the behaviour I implemented for the case. Because it's a special case and there will be too much work to separate things. Therefore when taxes with 3 decimals are required the condition is that everything is shown with 3 decimals on the prices, totals side included. Totals are also rounded to 3 decimals.

There is just one function that does the conversion to values with currencies.

This is a good compromise. It works on which one between currency and taxes have the most decimals takes preference.

**Comment by odiea** [comment]
Ok. I thought that was what it was about.

**Comment by daN4cat** [comment]
For most of the users it will be a match of 2 decimals currency and taxes or 0 for both.

I don't think it makes sense to have princes with no decimals and tax with decimals.
Maybe there could be some issue with the rounding on the totals.

I don't know to be honest, let see how it goes and if somebody wants things with different combination we will need to reconsider things.

**Comment by daN4cat** [comment]
By the way, the case of 2 decimals for currency and 0 decimal for taxes works fine.
So that's an addition with this solution.
For instance we tend to use more 20% or 19% or 5%, where the prices are with 2 decimals.
With this change we can set 0 decimals for taxes and totals are rounded by the currency decimal because it takes preference. So all will work fine.

**Comment by konceptech** [comment]
Everything is working Fine, the only little thing is on invoice, we see
three decimals likely everywhere (subtotals, total)

Most of the time, we see maximum 2 decimal on a invoice.

It should be also interesting to add a locale property to allow rounding to
5 cents when customer pay in cash.

Some countries are avoiding 1, 2 cents, so merchants have to round up or
down depending the total amount.

See sources here:

http://www.revenuquebec.ca/en/entreprises/taxes/tpstvhtvq/perception/calcultaxes.aspx
http://www.fin.gc.ca/1cent/index-eng.asp

<http://ca.linkedin.com/in/takacsnicolas>*Nicolas Takacs*
*Consultant Ti*
Bureau: (514) 907- 4772
nexst.ca

<http://nexst.ca/>
*Téléphonie IP <http://nexst.ca/services/telephonie-ip/> | Sauvegarde en
ligne <http://nexst.ca/services/sauvegarde-en-ligne/> | Solutions réseau et
WiFi <http://nexst.ca/services/reseaux-wifi/> | Simplicité et Efficacité
<http://nexst.ca/a-propos/>*
*Consultez notre blog pour découvrir les dernières nouvelles et
promotions: nexst.ca/blog <http://nexst.ca/blog>*

2016-04-02 15:59 GMT-04:00 FrancescoUK <notifications@github.com>:

**Comment by daN4cat** [comment]
OK, if I got right from the web page you need taxes with 3 decimals but totals and prices just with 2.
So I will remove the rule that if taxes is 3 currency gets to 3 too.

However the rounding needs to be adjusted and what the web says is cases like 0.5 cents, not 5 cents.
What they say >= 0.5c = 1c, < 0.5c = 0c.
So I would need to check how the rounding works in that case, but the rounding can stay at 2 as well provided the behaviour is right, which I assume would be the case as that's standard.

**Comment by konceptech** [comment]
Exact for the first answer.

For the second one: It is >= 5c = 10c, < 5c = 0c

So for example:

Total is 45,86 -» Rounding= 46,90
Total is 45,84 -» Rounding= 46.80

<http://ca.linkedin.com/in/takacsnicolas>*Nicolas Takacs*
*Consultant Ti*
Bureau: (514) 907- 4772
nexst.ca

<http://nexst.ca/>
*Téléphonie IP <http://nexst.ca/services/telephonie-ip/> | Sauvegarde en
ligne <http://nexst.ca/services/sauvegarde-en-ligne/> | Solutions réseau et
WiFi <http://nexst.ca/services/reseaux-wifi/> | Simplicité et Efficacité
<http://nexst.ca/a-propos/>*
*Consultez notre blog pour découvrir les dernières nouvelles et
promotions: nexst.ca/blog <http://nexst.ca/blog>*

2016-04-04 15:27 GMT-04:00 FrancescoUK <notifications@github.com>:

**Comment by daN4cat** [comment]
Yes, I read the 5c story. There are two different parts, one is the rounding of 0.5c due to 3 decimals tax, the other is the 1c phase out so rounding to 5c if cash.

I fix the first, but the 1c phase out is a different matter. Please open another issue for that as that's not 3 decimals for taxes.

**Comment by daN4cat** [comment]
@konceptech ok, take the latest change and see if the 3 decimal for taxes and rouding to 2 as per currency set works fine. I don't have that much time to test now. If fine we close this issue.

**Comment by daN4cat** [comment]
OK, created one issue for Cash rounding. See #447.

**Comment by odiea** [comment]
@daN4cat  Looks good from my house.

**Comment by daN4cat** [comment]
Is the rounding correct with taxes 3 decimal and totals with 0.5c or greater set to 1c?
I'm travelling so no time to test until Wed or Thu.

**Comment by odiea** [comment]
1.99 sale at 7.350% tax total is 2.14 sales tax is .15
With 1 dec currency price shows 2.00 with .1 sales tax  total is 2.1 loss of .04 cents.

**Comment by daN4cat** [comment]
So it's correct. Thanks I close this.

**Comment by odiea** [comment]
If I set the currency decimals to 0 . Item price shows 2.0 but 0 sales tax is charged.

**Comment by daN4cat** [comment]
That's normal is the effect of the rounding to the selected decimal because smaller than 0.5.

**Comment by daN4cat** [comment]
The issue there is that selecting 3 decimals for taxes and 1 decimal for currency does not make sense. But we cannot enforce rules for that because it becomes complex. I prefer to leave to the common sense of the admin.
