### ISSUE TITLE
Translation Date e Date Format selection

### ISSUE THREAD

**Issue by g438** [jekkos/opensourcepos#33]
Congratulations for the work, i am translating the language file in Italian and i have almost completed all but i can not translate the dates (month-day), i found the files in system/language but when i translate them nothing changes and remain in English. Can you explain how to complete the translation and for the change of date format (d / m / Y). Thank You

**Comment by jekkos** [comment]
please when doing translations, use the CSV files in the translations folder. They keep all the languages in one place and adding one language is just a matter of adding a new column. When done adding the new column in every file, you can run a 

    php generate_languages.php 

from the root of the project. After this you will still need to add the language itself in the dropdown of the application/views/config.php file. Add it with a value corresponding the language folder name and all should work ok.

**Comment by g438** [comment]
Hello, i had already done that, the problem is only for the translations of the months and days, that part is not recognized...

**Comment by jekkos** [comment]
ok I was a little too quick here. I suppose the files in system folder can be found on the net elsewhere as well. If you name the folder correctly then they should be picked up by CI to be used as well.

https://github.com/markxeasy/codeigniter-italian

this one already has the language files in his repo. You could add them and make a pull request for the csv and those files so I can merge in the new language.
