### ISSUE TITLE
Anyone else getting this error with the current 2.4 branch?

### ISSUE THREAD

**Issue by odiea** [jekkos/opensourcepos#331]
This is from Sale return.
You are using Open Source Point Of Sale Version 2.4. Please visit my website to learn the latest information about the project

    A PHP Error was encountered

    Severity: Runtime Notice

    Message: Only variables should be passed by reference

    Filename: controllers/Sales.php

    Line Number: 144

    Backtrace:

    File: C:\xampp\htdocs\bootstrap\application\controllers\Sales.php
    Line: 144
    Function: _error_handler	

    File: C:\xampp\htdocs\bootstrap\index.php
    Line: 292
    Function: require_once

**Comment by daN4cat** [comment]
I'll check, might be something I spotted in bootstrapUI and I fixed there. I had a couple of issues with post.

**Comment by arkgnan** [comment]
program still work fine, i just bothered by notice from sale return

**Comment by odiea** [comment]
I could not spot the problem bit when I replaced the current function is_valid_receipt(&$receipt_sale_id) with a previous one it works fine now.
 function is_valid_receipt(&$receipt_sale_id)
	{
		//POS #
		$pieces = explode(' ',$receipt_sale_id);

		if(count($pieces)==2 && strtolower($pieces[0]) == 'pos')
		{
			return $this->CI->Sale->exists($pieces[1]);
		}
		else 
		{
			$sale_info = $this->CI->Sale->get_sale_by_invoice_number($receipt_sale_id);
			if ($sale_info->num_rows() > 0)
			{
				$receipt_sale_id = 'POS ' . $sale_info->row()->sale_id;
				return true;
			}
		}
		return false;
	}

**Comment by daN4cat** [comment]
Fix in jekkos/bootstrapUI branch

**Comment by odiea** [comment]
Thanks for all the work your doing here. I hope you are enjoying it.

**Comment by daN4cat** [comment]
Yes, I like the upgrade to Bootstrap UI and I cannot wait to see the end of it with all the new functionality :-)

**Comment by odiea** [comment]
Please recheck the controller code. After the unfortunate this issue has returned. The old code is visibly present.

**Comment by daN4cat** [comment]
Crash?

**Comment by jekkos** [comment]
Might need to cherry pick this commit into develop/2.4 again then.

**Comment by odiea** [comment]
I thought it was better than saying someone screwed up.

**Comment by daN4cat** [comment]
ok, I need to look into this better. I was travelling the past couple of days, so I did the cherry pick in a hurry.
Having said that, the post issue with CI3 is probably deeper than I thought. I need to recheck everything because here and there it tends to pop up, and I'm worried because it's too volatile.
I mean how come that 1 month ago was fine and now we get more?
Something must have changed to affect this, but I don't know what exactly yet.

**Comment by odiea** [comment]
I know you had to recreate the 2.4 with a backup that might not have had all the current fixes. Apply all the fixes you had and then we will keep an eye on it.

**Comment by daN4cat** [comment]
I regenerated 2.3.4, unless 2.4 was overwritten too?

**Comment by daN4cat** [comment]
Argh...

**Comment by daN4cat** [comment]
Yes 2.4 force pushed removed that. I can only see it in bootstrapUI branch.

I reapplied the fix but now I don't know how many other things have been removed by the force push.
Difficult to say.

Maybe it's time to merge bootstrapUI to 2.4 so we get rid of two. We are not too far with bootstrapUI branch to get it to an end.

**Comment by daN4cat** [comment]
This should fix it (again), please check.

**Comment by odiea** [comment]
Yes 2.4 is back to normal now.

**Comment by daN4cat** [comment]
:+1: :+1: :+1:
