### ISSUE TITLE
identify item id for muliti purse

### ISSUE THREAD

**Issue by walterhumphreys** [jekkos/opensourcepos#333]
hi guys im trying to set and alert on sales mode for exampe if item in stuck is than 25 echo low stuck , im using 3 stock locations, but im having issues to find out item_id, when i use it it days it doesnt existe, itried with $line and it removes the error but yet this aint the item id or numer as well i belive anyone will do it here is the code  of working example

<?php foreach(array_reverse($cart, true) as $line=>$item)
if ($item ['in_stock'] < 50)
echo "please check your inventory";
else 
echo  "WE  ALL CLEAR";?>

this out put correct when there is just one selected item because $line somehow added a item id but isnt the correct item id

and i get this Parse error: syntax error, unexpected '=', expecting :: (T_PAAMAYIM_NEKUDOTAYIM) 

when im using

<?php foreach(array_reverse($cart, true) as item_id=item_id)

						if ($item ['in_stock'] < 50)
	
							echo "please check your inventory";

								else 
	
							echo  "WE ALL CLEAR";
							?>

**Comment by walterhumphreys** [comment]
ok i figured it out, i just added
<?php
if ($item ['in_stock'] < 50)
  echo "please check your inventory";
   else 
   echo  "WE ALL CLEAR";
     ?>
was to be added at line 116'

but my question still remains cause im trying to echo customs fields but i cant get to find the real definition of the item id or item name, im using msql selef custom1 custom2 from opsot_item where item_id = item_id and isnt working this is the reason why i will like to know item id variable, please help

**Comment by daN4cat** [comment]
for the definition of the custom fields you need to look in the app_config table.

**Comment by odiea** [comment]
Closed #209 pertained to this info.So here is the line of code I used to get the info from general config for custom names.
$CI->config->item('custom2_name'), I guess we could use this instead of adding to the language files.

**Comment by walterhumphreys** [comment]
i was searching for that file but i dont find table_helper.php in my files, im using version 2.3.4, im seaching for app_config table as well where do i find these, please

**Comment by daN4cat** [comment]
the config table? In your database!

**Comment by walterhumphreys** [comment]
ok yes that is the to find the name of the custom field and i added the code above $CI->config->item('custom2_name') because in my case is for a pharmacy as well and im using custom1 and custom2 for shelf as well and for lab

**Comment by walterhumphreys** [comment]
Fatal error: Call to a member function item() on a non-object in /home/develop/application/views/sales/register.php on line 198

A PHP Error was encountered
Severity: Notice
Message: Undefined variable: CI

that is what i get

**Comment by daN4cat** [comment]
Why do you call it from a view?

**Comment by walterhumphreys** [comment]
i need to echo the info in register.php cause i need ot to be visible here, is that here i will do someting like  echo base64_decode($item['custom1_name']);

and where do i paste $CI->config->item('custom1_name') i was searching for table_helper.php but isnt in my files or i just cant seem to find it

**Comment by daN4cat** [comment]
table_helper is in helpers/

**Comment by odiea** [comment]
Sorry $CI was probably just good for the items table. You will have to play with the code to get the view you want.

**Comment by walterhumphreys** [comment]
for example description is visible on resgiter.php/ sales mode, i will like to do the same with custom1, where do i define this then echo it on register.php, i tried with mysql but im having a hard time, kinda stuck like 2 weeks on this

**Comment by daN4cat** [comment]
I would need to look into this in more detail but at the moment we are all busy with the UI upgrade which is quite some work.

**Comment by daN4cat** [comment]
not system/helpers, application/helpers.....

**Comment by odiea** [comment]
Go to language-items_lang and put the names of the custom fields there
$lang["items_custom2"] = "Tag Color"; what ever the names of your fields are in items form
Go to  application\libraries\sale_lib
go to app line 311 and you will see item = array($insertkey) 
and enter your custom names like below
'custom1' =>$item_info->custom1, 
Now go to application\views\sales\register  
Add you new columns to table id=register
enter your new lang items line there
You will need to adjust the widths as necessary
You will also need to look for the colspan and adjust those as needed
now you can enter your fields to the their locations using the echo $item. I placed the reorder level here.Replace reorder level with custom1 or custom2. Hope this helps you out.
<?php
if($item['is_serialized']==1)
							{
								echo $item['quantity'];
								echo form_hidden('quantity',$item['quantity']);
							}
							else
							{								
                                echo $item['reorder_level'];
								echo form_hidden('reorder_level',$item['reorder_level']);
						}
						?>

**Comment by walterhumphreys** [comment]
you definitely are my hero thank you so much it worked, im so happy, really grateful ,  i  like this software and daily trying to learn it and understand it better, once again thanks

**Comment by odiea** [comment]
Your welcome. I liked your code too. I changed it a little with if ($item ['in_stock'] < $item['reorder_level']) that way it works off your reorder level.

**Comment by walterhumphreys** [comment]
welcome as well

**Comment by daN4cat** [comment]
@odiea anything we should consider of this as part of the main code?

**Comment by odiea** [comment]
I think the change I made in low stock level warning is about the same.

**Comment by daN4cat** [comment]
See #336
