### ISSUE TITLE
Add payment type change feature to sales edit

### ISSUE THREAD

**Issue by zizango123** [jekkos/opensourcepos#334]
After sales edit option can be a very good enhancement

**Comment by daN4cat** [comment]
There is one, have you checked detail sale report or Takings from Sale?

**Comment by zizango123** [comment]
i have checked it out. But that edit doesn't let you further either add another item to it or alter it.

**Comment by daN4cat** [comment]
so you want a full reedit of the sale to add something later.
Would it better to return the wrong sale and issue a new correct one?
That's what they do in my wife's shop.

**Comment by zizango123** [comment]
That is also a way but it is necessary that i be able to full reedit it so as to retain the sales id. Is there no way this can be done.

**Comment by daN4cat** [comment]
Personally I have no purpose in implementing such thing. There is something I would like to add but it's the payment type change.
Adding a way to fiddle past sales could open scenarios where people add stolen stuff to old transactions or the like.

**Comment by osworx** [comment]
One of the basic merchant principles is, never change an invoice (or any part of it)!
And basically a sale (at the moment when the customer has recived his items) is an invoice.

Whenever you have to change something on that sale/invoice, you have to create a credit note referring to this invoice number.
While the invoice number will be for ever stored and cannot be changed afterwards!

I am sure this is valid everywhere in the world.

**Comment by daN4cat** [comment]
Indeed. Just the payment type would be good because I get weekly requests to adjust something that was a card instead of cash and viceversa.

**Comment by daN4cat** [comment]
This feature is covered by #314 already, hence I close.
