### ISSUE TITLE
Fix sales stock level to work off item reorder level instead of  0 or below.

### ISSUE THREAD

**Issue by odiea** [jekkos/opensourcepos#336]
I don't know what procedure  this error is coming from but it would be nice to have this fixed also.

**Comment by daN4cat** [comment]
Is this a bug or new feature? Not sure I get.

**Comment by odiea** [comment]
Currently the warning does not show unless the items are 0 or below. It would be nice to have the warning show when the items qty is at or below the reorder level. I currently have a way around this that shows the warning when the qty is 2 items below the reorder level.

**Comment by daN4cat** [comment]
Ok, got your point

**Comment by odiea** [comment]
Ok. I got it figured out. The following will show the warning when it reaches the reorder level.
function out_of_stock($item_id,$item_location)
	
	{
		//make sure item exists
		if($this->validate_item($item_id) == false)
        {
            return false;
        }
		$item_info = $this->CI->Item->get_info($item_id);		
		$data['reorder_level'] = $item_info->reorder_level;
		$item_quantity = $this->CI->Item_quantity->get_item_quantity($item_id,$item_location)->quantity;
		$quantity_added = $this->get_quantity_already_added($item_id,$item_location);
		
		if ($item_quantity - $quantity_added <= $data['reorder_level'])
		{
			return true;
		}
		
		return false;
	}

**Comment by jekkos** [comment]
Would be nice to integrate this change in 2.4

**Comment by odiea** [comment]
Feel free to integrate any of my ideas. That's why I post them so others can try or integrate them into OSPOS

**Comment by daN4cat** [comment]
@odiea no chance you can use github and go for a PR so it's easy to integrate?

**Comment by odiea** [comment]
Just let me know how to do this.

**Comment by jekkos** [comment]
If you edit the files directly on your github repo, you should be fine. Then you can make a pr just like that. It's quite easy.

**Comment by jekkos** [comment]
Eg the snippets you paste here, just click edit on the file in your cloned github repo, ofc after choosing the correct branch first. github wil automatically add those changes to a new branch so you can make pr more easily with this repo.

**Comment by odiea** [comment]
https://github.com/odiea/tabbed-dev/tree/tabbed-dev is the branch that contains my changes. If you can use it great.I have to go to work now.

**Comment by odiea** [comment]
So what do I need to do. Start with a virgin copy of ospos then add my snippets to that because all mine are hacked versions.

**Comment by odiea** [comment]
https://github.com/odiea/opensourcepos I forked 2.3.4 and added the reorder info. Let me know if it works out.

**Comment by daN4cat** [comment]
I created the PR and marked this 2.3.5.

**Comment by daN4cat** [comment]
Is this closed? It seems to be in master as 2.3.5

**Comment by jekkos** [comment]
Yes this was fixed beginning of this week.
