### ISSUE TITLE
Keep Need to Re-login during entering sales

### ISSUE THREAD

**Issue by dxchen90** [jekkos/opensourcepos#337]
Hi,

I installed this pos in bluest cloud server.
since the cloud server upgraded, the pos not working well.
i can't enter sales. It keep jump to login page when i enter the barcode.
i using Chrome to launch the site.
anyone have this issue?

**Comment by daN4cat** [comment]
Is the error_log file in ospos installation root saying anything?

**Comment by dxchen90** [comment]
Hi, where can i find the log file.

Sent from Outlook Mobile




On Wed, Feb 17, 2016 at 11:31 PM -0800, "FrancescoUK" <notifications@github.com> wrote:












Is the error_log file in ospos installation root saying anything?

**Comment by jekkos** [comment]
Common issue with pre - ci 3 version. Did you try the version from develop/2.4 yet?

**Comment by dxchen90** [comment]
My version is latest version pos 2.3.4If works like a charm before upgrade hosting to cloud host..
Sent from Outlook Mobile




On Thu, Feb 18, 2016 at 1:34 AM -0800, "jekkos" <notifications@github.com> wrote:












Common issue with pre - ci 3 version. Did you try the version from develop/2.4 yet?

**Comment by jekkos** [comment]
Try version from 2.4 branch and please report back.

**Comment by dxchen90** [comment]
Hi,
I downloaded the branches develop/2.4Removed the previous files from server and put in the 2.4 but end up having this issue.
Database error.Php error was encountered
Please check ou http://whypaymoreonline.com/stock

**Comment by daN4cat** [comment]
Have you run the db upgrade?

**Comment by daN4cat** [comment]
Also use the new template for the database config

**Comment by dxchen90** [comment]
My steps.
Backup file and database
Delete Files
upload new 2.4 files
Upgrade database file.
Goto config/database.php.tmpl change name to database.php
edit the database info.
upload back to the config/
Done.

Tomorrow will try on the window 7 desktop again and see it still logout or not.

Thanks Master for quick support!

**Comment by dxchen90** [comment]
Hello…

After upgrade on 2.4, there is a issue on modifying sales date. after press submit, the bottom part normally shows successful green bar, but this shows red internal server error.

Any idea?

**Comment by daN4cat** [comment]
That's an issue I fixed in bootstrapUI branch. Let me see if I can fix it in 2.4.

**Comment by jekkos** [comment]
Maybe cherry pick that commit from bootstrapUI?

**Comment by daN4cat** [comment]
We'll check later.

**Comment by dxchen90** [comment]
Hello masters.... any update on the bootstrapUI thing?

**Comment by daN4cat** [comment]
Not had time yet. I needed to sort out other issues in bootstrapUI branch.
I'll look for the fix and apply it to develop/2.4

**Comment by daN4cat** [comment]
I committed a change to controllers/Sales.php that fixes the issue.
Please take that file and give a try.

Please also check the suggestion box in Sales register works fine as there was another issue with that, but I don't have the time now to look into that fix.

**Comment by jekkos** [comment]
:+1:

**Comment by dxchen90** [comment]
Hi,

I have tried replaced the file but same issue shows. (internal server error)

**Comment by dxchen90** [comment]
Updates: It works if i change the date from (sales) Takings.

It won’t work when i change from Detailed Report.

Temporary i can still use it.

Thanks for the update!

**Comment by daN4cat** [comment]
Right, there was a further change I made few days later in boostrapUI related to the same issue and fixing things in other place.
I committed in develop/2.4, please take the latest and try again. Sorry for the try & error but I had not that much time today and I don't have later as well to test the changes. So I ask you a favour to be the tester here. Thanks.

**Comment by odiea** [comment]
@daN4cat  2.4 is back to showing the php error on return in register.

**Comment by daN4cat** [comment]
@odiea I just tested the code with my last commit in it and all seems fine and working for me.
I just tested edit from Takings, edit from Detailed Sale report and few edit in Items, Suppliers, Employees and etc.
All seems fine.

**Comment by odiea** [comment]
I just re-downloaded it and I still have those issues. I could not grab the php error image.
![2016-02-22 12_09_10-open source point of sale -- powered by os point of sale](https://cloud.githubusercontent.com/assets/10962177/13229254/3935457e-d95d-11e5-93e0-bbb385bbfa48.png)

**Comment by odiea** [comment]
I just checked the code for 2.4 and the search for returns is back to the old one that was giving php errors not the one where you made the correction.

**Comment by daN4cat** [comment]
I believe this is now fixed, right?

I close meanwhile.
