### ISSUE TITLE
How to add Autocomplete Search for an array

### ISSUE THREAD

**Issue by hoangtu406** [jekkos/opensourcepos#338]
I have idea to make online search and offlline search, I modify  \application\views\sales\register.php
$dataoffline=array("item_id"=>"35", "name"=>"aaaaaaaaaa"); //  I save data to localstorage
if ($olinesearch)
{
$("#item").autocomplete('<?php echo site_url("sales/item_search"); ?>',
    {    	minChars:0,
    	max:100,
    	selectFirst: false,
       	delay:10,
    	formatItem: function(row) {
			return (row.length > 1 && row[1]) || row[0];
		}
    });
}
esle // offline search
{
// how to write code for offline search, what should I put parameters  $dataoffline
}

Please help me to solve this issue.

**Comment by daN4cat** [comment]
You need to search around for js that does that. It's not a 1 min answer I'm afraid.

**Comment by hoangtu406** [comment]
Thanks daN4cat for your answer. I found some script can search inside an array. But I would like to use available search method of Open Source POS. I think there is a way to put array parameter beside. URL.

**Comment by jekkos** [comment]
Will close this one as this one is a little off topic
