### ISSUE TITLE
PHP 7 Compatibility

### ISSUE THREAD

**Issue by nairgh** [jekkos/opensourcepos#339]
A PHP Error was encountered
Severity: 8192
Message: Methods with the same name as their class will not be constructors in a future version of PHP; open_flash_chart has a deprecated constructor
Filename: ofc-library/open-flash-chart.php
Line Number: 63
A PHP Error was encountered
Severity: Warning
Message: Declaration of Customer::save(&$person_data, &$customer_data, $customer_id = false) should be compatible with Person::save(&$person_data, $person_id = false)
Filename: models/customer.php
Line Number: 273
A PHP Error was encountered
Severity: Warning
Message: Declaration of Employee::save(&$person_data, &$employee_data, &$grants_data, $employee_id = false) should be compatible with Person::save(&$person_data, $person_id = false)
Filename: models/employee.php
Line Number: 367
A PHP Error was encountered
Severity: Warning
Message: Declaration of Supplier::save(&$person_data, &$supplier_data, $supplier_id = false) should be compatible with Person::save(&$person_data, $person_id = false)
Filename: models/supplier.php
Line Number: 310
Similarly so many errors

**Comment by jekkos** [comment]
The app is not compatible with php7 yet.

**Comment by daN4cat** [comment]
And why should we?

**Comment by daN4cat** [comment]
We will look into this going forwards.

**Comment by nairgh** [comment]
Happy to see this going. Always my support available. By the way it is a  very useful project. I don't want to see the grey side of this ..

**Comment by daN4cat** [comment]
Would be useful to get some help with this once the bootstrapUI step is completed.

**Comment by daN4cat** [comment]
@ais-one & @nairgh could you please work on this using bootstrapUI branch since you seem to have PHP7 installations?

Of course it has to be at least 5.5 backward compatible, so it should not break things.

**Comment by ais-one** [comment]
Hi I will look into this as well, yes I am working using php7 on both win (32 bit) and linux (64 bit).

I do recall seeing those errors and having a fix. It is definitely a php7 thing.

Will report on fix later.

**Comment by ais-one** [comment]
Btw, php7, I had to use mysqli, I read there is some issue on this too, which issue is this happening? I did not read through to see what was failing.

**Comment by daN4cat** [comment]
mysqli is set in the database config since we moved to CI3.

**Comment by ais-one** [comment]
@nairgh 

What version of PHP are you using, I get the same problem for versions below 7.02 on XAMPP (both windows and linux version).

On 7.02 and above there is now problem. Suggest updating the wiki.

May be related to the following bug on [https://bugs.php.net/bug.php?id=70997](url)

**Comment by ais-one** [comment]
sent pull request on this one, based the fix on feature/BootstrapUI...

**Comment by daN4cat** [comment]
This is solved in 2.4, which is master now.
