### ISSUE TITLE
Add mod_expires config to .htaccess

### ISSUE THREAD

**Issue by jekkos** [jekkos/opensourcepos#340]
After inspecting network resources in chrome developer tools I realised that most of the static assets are reloaded with each request. Static files are not eager to change (except after doing a new deploy) and thus should be cached by the browser.

That's where apache mod_expires comes in. I added a config section in the .htaccess of this project to enable caching for most of the static resources for about a week. This config seems to speed up the application considerably.

**Comment by jekkos** [comment]
Will merge this to bootstrapUI as well now.

**Comment by odiea** [comment]
I do not see this update in either 2.4 or feature/bootstrapui

**Comment by daN4cat** [comment]
it's in develop/2.4

**Comment by jekkos** [comment]
Should be in bootstrapUI now as well.Install mod_expires first in apche using following `sudo a2enmod expires && sudo service apache2 restart`

**Comment by daN4cat** [comment]
Yes it's in bootstrapUI now, I cheery picked it. I can close this now.
