### ISSUE TITLE
which one is the latest

### ISSUE THREAD

**Issue by ramiznazir** [jekkos/opensourcepos#341]
sorry i know its very basic question , i just want to know which version i should use that is latest? should i use master ?

**Comment by odiea** [comment]
The current stable release is 2.3.4 On github it is listed as Master. The others listed are still under development or are obsolete.

**Comment by ramiznazir** [comment]
Thanks
On Feb 21, 2016 4:54 PM, ramiz4148@gmail.com wrote:

Thanks!
On Feb 21, 2016 4:51 PM, "odiea" <notifications@github.com> wrote:
>
> The current stable release is 2.3.4 On github it is listed as Master. The
others listed are still under development or are obsolete.
