### ISSUE TITLE
Replace flash based charts with jqPlot / Chart.js / Chartist

### ISSUE THREAD

**Issue by daN4cat** [jekkos/opensourcepos#342]
Soon or later Flash will not be any longer supported by web browsers, following java support destiny.

We should replace chart flash based with https://github.com/jqPlot/jqPlot/ jQuery plugin which seems rich in chart options and flavours.

Flash issue was also discussed in #50

**Comment by ais-one** [comment]
Another one you can look at is [http://www.chartjs.org/](url)

**Comment by daN4cat** [comment]
Thanks, I'll look into that yes. If my memory is not mistake AdminLte uses it, so better not add more distance for the ones that want AdminLTE in ospos.

**Comment by daN4cat** [comment]
@jekkos I gave a quick try to Chart.js, first I sorted out all the js importing with bower and grunt that were not working that fine. Not sure why Chart.js bower support is not right but never mind it's sorted.

I changed one report as test but I face an issue with Chart.js. It looks like requiring HTML5 and canvas and this line `$("#report_chart").get(0).getContext("2d");` fails because it cannot find any getContext of null.

Here the canvas `<canvas id="report_chart" width="600" height="800"></canvas>`.

I'm not familiar with HTML5 declaration and etc., so I would need to read about. But maybe you can give me some quick hint here to understand the magnitude of the issue or if there is something obvious I missed or can fix.

**Comment by daN4cat** [comment]
OK, I believe I need to check something else first: https://github.com/nnnick/Chart.js/issues/1505

Bower pulled Chart.js 2.0.0-beta and probably the documentation online is for 1.0.0.... mhhh let me check that first!

**Comment by jekkos** [comment]
ok might be easy to inspect the jquery object in a javascript console. There you will see what properties the object has and what could be wrong and needs a fixing.

**Comment by daN4cat** [comment]
Just checked this example: https://github.com/nnnick/Chart.js/blob/v2.0-dev/samples/line.html
I should use that as guideline.

I even noticed that Chart.js requires jQuery 2.x. I don't know if we can upgrade to 2 with no issue?

**Comment by daN4cat** [comment]
I will give a try to jqPlot, it seems more in line with that we have already.

**Comment by jekkos** [comment]
Nice option for charts as well: https://github.com/gionkunz/chartist-js. Also fully responsive.

**Comment by daN4cat** [comment]
Thanks for this. That looks closer to be a straight replacement of the charts we have.
I just wait for your merge into master so I can look into this based on the latest.

I looked into the other options but they were not straight forward as this one, starting from no or little bower support to requiring jQuery 2.
Maybe as first step I could switch to chartist-js and later consider Chart.js if we want something fancier.

**Comment by jekkos** [comment]
Yes doesn't look too complicated and seems to fit exactly what we need. I merged into master but on my local machine this morning. I was busy fixing one last bug, test it locally and then push those changes.

**Comment by daN4cat** [comment]
First experiment with Chartist using real data:

![image](https://cloud.githubusercontent.com/assets/636048/15448464/4b3a6f22-1f5a-11e6-931c-edfde74b0c75.png)

**Comment by daN4cat** [comment]
Here the new charts using Chartist in the end.

The charts are all functional, of course the look'n'feel is now different but there is still more to adjust.
I removed all the flash dependencies so the last piece of the old OSPOS is gone forever.

Probably one of the next steps is to tidy up the styling and add some beautifications, I assume some would like to have the charts a bit smaller. I don't know, give a try and let me know what you think.

**Comment by daN4cat** [comment]
Moved styling of charts to reports.css.

I tried to reduce width and height to let say 80% but I don't find a way to style the chart to be centered.
`text-align: center;` doesn't seem to work.

**Comment by jekkos** [comment]
Ok looks good. I've done some small corrections to the way the data is echo'ed in the view. I changed the custom escape with the bulitin php json encoder (which is probably more secure to use).

**Comment by jekkos** [comment]
Nice work, good to see all these old parts replaced by new ones

**Comment by daN4cat** [comment]
Indeed.

Not sure if we are fine with the size of the charts, but if I set width and height in the options to let say 80% I still don't find the means to center the graph in the view.
Maybe I should search in Chartist issue, but not sure you have any thoughts about how to?

**Comment by daN4cat** [comment]
Also, going forward I should check if there are plugins to reuse for the pie chart to get the tooltips we used to have instead of print the full label and value in one line.

I saw something but it's for bar & line, so it requires work to have it in pie charts.

**Comment by jekkos** [comment]
Will fix the encoding issues later today.

**Comment by daN4cat** [comment]
@jekkos I fixed a couple of things that were not finished from your last changes.

However the introduction of json_encode for the data broke the % calculation in pie charts.
Have you noticed that?

Also lines chart was broken. Please don't revert what's working now and let's find a solution for the pie chart % issue.

**Comment by jekkos** [comment]
Ok I can look into that percentage issue then.

**Comment by daN4cat** [comment]
@jekkos wait for the % issue. Maybe it's better to have a different approach and calculate the % on controller side and pass all the info that can then be displayed in a tooltip like from the example here: https://github.com/gionkunz/chartist-js/issues/353

**Comment by jekkos** [comment]
Yes I think so, was looking how it worked before and found the following in cfacf52a4203ad529a560ae490332c535550c94f 

![screenshot from 2016-05-24 17 35 40](https://cloud.githubusercontent.com/assets/576234/15510056/28c5495c-21d6-11e6-99fe-4315724a8b27.png)

looks more or less the same as in current version.

**Comment by jekkos** [comment]
Otherwise I'll just start another story and leave this for you to finish?

**Comment by daN4cat** [comment]
Yes, I'll finish adding the tooltip to pie chart too.

**Comment by daN4cat** [comment]
With this commit I've added tooltip support to charts and solved the % issue as anyway was better to be implemented as part of the tooltip.

Please check the sales chart and let me know if you like the tooltip when you hover over the circle of the value.

Also I've sorted the currency representation reflecting the correct side according to the local configuration.

**Comment by daN4cat** [comment]
Just few more adjustments around the currency point.

I believe this is completed and can be closed.

**Comment by odiea** [comment]
Yes the tooltips really pop out.

**Comment by daN4cat** [comment]
OK, there is still something to do on the responsiveness side.
So not completely closed yet.

**Comment by daN4cat** [comment]
OK, responsiveness sorted and Summary section placement on different screen sizes.

I believe this is now done. There will be more I suppose but that's an enhancement story not a replacement one.
