### ISSUE TITLE
Freeze when adding employee ver. 2.3.4

### ISSUE THREAD

**Issue by solasoli** [jekkos/opensourcepos#344]
Dear Jekkos, i just installed 2.3.4 and everything was going smoothly, except i have to rename phppos_sessions to ospos_sessiosn because theres an error 1146. 

But my question here are, im unable to add employee with John Doe default Account. Its just freeze, theres no change or notification whatsoever. Could you enlighten and tell me what to do. Thank you Jekkos, you rocks!

**Comment by daN4cat** [comment]
Please don't rename tables and put it back to be phppos_ as prefix.
Then please read #258 as it talks about a script to migrate from phppos to ospos database.

**Comment by daN4cat** [comment]
Please before running any migration script make sure you make a copy of your database.

NOTE: the script may need to be adapted to your phppos needs.

**Comment by daN4cat** [comment]
Please also make sure to take today's 2.3.4 because of this issue #345

**Comment by jekkos** [comment]
Yes might be a duplicated record in your db. Check and add server response for the ajax call.

**Comment by daN4cat** [comment]
There is no follow up. I close.
