### ISSUE TITLE
i downloaded 2.3.4 but it shows it's 2.4?

### ISSUE THREAD

**Issue by ramiznazir** [jekkos/opensourcepos#345]
I downloaded master but still it's showing as I am running 2.4 version. Is version 2.3.4 changed to 2.4 or its mistakenly rename to 2.4 in config file?

**Comment by daN4cat** [comment]
might be the side effect of a force push by @jekkos by mistake the other day.

**Comment by daN4cat** [comment]
If I read correctly the commit history it looks like master has 2.4 now in it.

**Comment by daN4cat** [comment]
I forced pushed the 2.3.4 I had from my repo which was the correct version.

Please retake master as this should be the correct 2.3.4.
