### ISSUE TITLE
Not able to print any inovice & reciept

### ISSUE THREAD

**Issue by disearth** [jekkos/opensourcepos#346]
After completing the sales only a blank screen appears like this..http://prntscr.com/a6head & when try to take print od the reciept the same blank screen occurs.

**Comment by daN4cat** [comment]
Version please?

**Comment by disearth** [comment]
version is 2.3.4 but Invoice is showing perfectly on localhost but not on server http://prntscr.com/a6l7kr

**Comment by daN4cat** [comment]
is the 2.3.4 the version you have taken from github in the past couple of days?

**Comment by disearth** [comment]
Yes...

**Comment by daN4cat** [comment]
Please take again today's version, by mistake another person forced pushed 2.4 in master.

**Comment by daN4cat** [comment]
There is no follow up. I close.
