### ISSUE TITLE
what does reorder do in item?

### ISSUE THREAD

**Issue by ramiznazir** [jekkos/opensourcepos#347]
Can you please elaborate what exactly reorder field does when adding new item?
Thanks in advance. Any help will be highly appreciated.

**Comment by odiea** [comment]
The reorder field in items lets you set the amount of items in your inventory to let you know when your inventory level gets to that point so you can restock that item as needed. You have 25 items. Your reorder level is 5. When you run the low inventory report it should show you it's time to reorder more items.

**Comment by ramiznazir** [comment]
Thanks

**Comment by ramiznazir** [comment]
Can you please also elaborate what does "Taking" shows in Sale Register as almost same result I can also see in sale report.

**Comment by odiea** [comment]
Taking is a quick Daily Sales report that will let you filter Cash sales or Sales Invoicing. It will also let you delete a Sale. Please use caution . If you delete a Sale your Invoicing auto-numbering will get destroyed.

**Comment by ramiznazir** [comment]
If we don't delete even then it's not showing numbering on invoice.  And can you please confirm is there any way to pay half or little amount or customer has to pay whole amount due on time of payment and also what does "receiving quantity" does when we add new item.

**Comment by odiea** [comment]
Currently all payments must be in full to get a proper receipt. Do you have the create invoice checkbox checked for Create Invoice? Receiving quantity is a multiplier. You stock a 6 pack of pop. you would enter 1 for qty stock and 6 in receiving qty. You would then adjust your cost and resale prices as necessary then when you update your items in receivings it will multiply the item qty time receivings qty. It is something you will have to play with to see if you want to use it.

**Comment by ramiznazir** [comment]
I got it but could not understand the cost price in Receiving and in Items . As receiving price is for whole pack as in invoice but in items same price is for each qty of each pack?

**Comment by odiea** [comment]
It's functionality appears to have changed since I last played with it. I would suggest just ignoring this because it is just used in Receivings.

**Comment by ramiznazir** [comment]
Ok thanks you very much mate! I highly appreciate for your help.
