### ISSUE TITLE
Unable to login after installation

### ISSUE THREAD

**Issue by EdenQi** [jekkos/opensourcepos#349]
i can't login after installation. And give a message :  Invalid username/password. But i use the account ( username : admin , passwd : pointofsale ).
So what happened on me, how can i fix this problem.

ps : I think the POS connect to database is failed, so i can't login.

**Comment by EdenQi** [comment]
Or maybe some cache problems.

**Comment by daN4cat** [comment]
check the error_log in your ospos root dir.
Also please state the version you are using.

**Comment by EdenQi** [comment]
sorry, i can't see any error_log in my ospos root dir.My version is 2.3.4,and my system is linux.

**Comment by EdenQi** [comment]
I debug the code (Form_validation.php) 
![image](https://cloud.githubusercontent.com/assets/1366108/13252166/097797e2-da70-11e5-8208-9dfb25c065da.png)

And here have some error .
![image](https://cloud.githubusercontent.com/assets/1366108/13252538/4eb29454-da72-11e5-99a9-0a237d8c19fd.png)

i don't know why.

**Comment by daN4cat** [comment]
Is 2.3.4 a version you took from git last weekend?
If yes please take again what is now in git as 2.3.4.

Also which pho version do you use?

I use Linux as well but php 5.4 and no issues.

**Comment by EdenQi** [comment]
git branch is remotes/origin/feature/bootstrapUI?

and php i used 5.5.30

**Comment by EdenQi** [comment]
i pulled from remotes/origin/feature/bootstrapUI.

and now i got some error message.

![image](https://cloud.githubusercontent.com/assets/1366108/13253332/858ba318-da76-11e5-988d-00452b35dbf3.png)

![image](https://cloud.githubusercontent.com/assets/1366108/13253349/992a9082-da76-11e5-8a3a-b992724b38df.png)

**Comment by EdenQi** [comment]
oh, yes!

I fixed it. 

i'm in.

thanks a lot.

**Comment by daN4cat** [comment]
Yes, you needed to update the database config and even run the db upgrade script.

BTW, bootstrapUI is work in progress so don't expect everything to be final and great yet.
