### ISSUE TITLE
Add page to New Module

### ISSUE THREAD

**Issue by hoangtu406** [jekkos/opensourcepos#350]
I have just inserted one module by :
- Insert record to table module, permissions
- Create image for module

Now I can assign right for user and user can see module.

What should I do next to create a page for this module when user click module ?.

**Comment by daN4cat** [comment]
Have add the routing to routes.php?

**Comment by daN4cat** [comment]
I assume you have created a view and controller besides the model

**Comment by hoangtu406** [comment]
I would like to create a page like item_kits. I looked in routes.php, but I did not see any line describe item_kits page. I copy view , model, controller but I do not know to modify it.
 Could you please show me how to create first blank page. Just simple step, it's still OK.

**Comment by hoangtu406** [comment]
I tried but I still "

404 Page Not Found

The page you requested was not found.

"

**Comment by Halwest01** [comment]
Hi, he asked how to make a new page, i want to add another language, is there a permission to add another language to pos ? i like to add my language .

**Comment by daN4cat** [comment]
fork opensourcepos in your github repository, make the language change and then go for a pull request to this repository to get it integrated after a review/acceptance.

**Comment by Halwest01** [comment]
Thank you very much, i'll slowly translating it and will tell you guys once i finished it :) ! very happy with this project i used to code POS in visual studio, since i found this web-based pos ! i fell in love with it, hope i can make some simple adds ^_^ !

**Comment by daN4cat** [comment]
Sounds great and welcome. Hope you had a look at the bootstrapUI version that is under development
