### ISSUE TITLE
When I press button "Backup" in Store Config then this error occurred

### ISSUE THREAD

**Issue by ramiznazir** [jekkos/opensourcepos#351]
"
A Database Error Occurred

Unsupported feature of the database platform you are using.

Filename: D:\web\htdocs\sale1-2.3.4-1\system\database\drivers\mysqli\mysqli_utility.php

Line Number: 82
"

**Comment by daN4cat** [comment]
Version please

**Comment by ramiznazir** [comment]
2.3.4

**Comment by jekkos** [comment]
This is obviously a configuration issue. Check if your user is allowed to make database dumps using mysqldump. Feature is working fine in a well configured install.

**Comment by daN4cat** [comment]
There is an issue in 2.3.4 when you press the DB Backup button in config.

It's similar to #318. This needs a fix.

**Comment by daN4cat** [comment]
This is one of those weird things.... in bootstrapUI this works fine.

**Comment by odiea** [comment]
This problem is caused by changing to mysqli. $db['default']['dbdriver'] = 'mysql';  If you delete the I it works properly.

**Comment by daN4cat** [comment]
Good catch, that's the change for CI3, not CI2.

**Comment by daN4cat** [comment]
Just tried, and confirmed: it has to be 'mysql' with 2.3.4 and not 'mysqli', the latter is for 2.4 only.

**Comment by daN4cat** [comment]
Root cause spotted, it went in with a PHP7 fix: https://github.com/jekkos/opensourcepos/commit/d0c765ce20eb70fccd24a590cab3ab9233511fd4

**Comment by daN4cat** [comment]
The fix should be revert PHP7 change and issue a 2.3.5.

Only CI3 based will be fine with future PHP versions. I would not fix 2.3.x.

**Comment by daN4cat** [comment]
It's now in master. I marked this 2.3.5 as we may want to add a couple of small things.
