### ISSUE TITLE
printing table before complete sale

### ISSUE THREAD

**Issue by hovalle** [jekkos/opensourcepos#352]
Hi, i have a question. I need to print the table in the sales window but before complete the sale like a quote for a future sale. there's a checkbox that print the sale but after complete the sale how can i accomplish this? Thanks.

**Comment by daN4cat** [comment]
Would this be a print option for suspended sales? Or do you want to discard the sale after the print?

**Comment by hovalle** [comment]
ok what i need to do is like a "proforma invoice" you know. Suppose a customer wants to buy something, but only needs the products price, and not buy the product at the same moment but after.

**Comment by daN4cat** [comment]
Yes I imagined it was a pro forma invoice story, hence my question about suspend it.
There is the option to suspend, what you would need is to print the suspended invoice.

**Comment by hovalle** [comment]
ok, do you have any example on how to to do this?

**Comment by daN4cat** [comment]
Check how invoice printing works and add it to suspend button after the suspend action. Maybe you can add a checkbox indicating if you want to print after the suspend or not.
 In the suspended view you can also add a print button besides the unsuspend so you can reprint it.

**Comment by hovalle** [comment]
Hi daN4cat, i did it!!  i just duplicate the complete function and did some code cleaning and i atached the function to a button with jquery and boom! it worked. Thanks a lot for your help.

**Comment by daN4cat** [comment]
Sounds good. We can close this issue then.

**Comment by daN4cat** [comment]
Not sure you want to contribute your change back?

**Comment by hovalle** [comment]
sure!! but my changes are in spanish, i'm an spanish dude from Guatemala how can i upload the changes??

**Comment by daN4cat** [comment]
what about uploading your code in your fork of ospos in github so you keep changes in sync going forward?

you can post your change and we can have a look at it if you don't want to go for a pull request.

**Comment by hovalle** [comment]
ok my changes where in this files:
views/sales.php in line "#259" in the form/open("sales/cancel_sale") i added between the cancel_sale_button and suspend_sale_button this other button i also added the class "btn-block"
`
<div class='btn btn-sm btn-primary btn-block' id='print_button' style='margin-top: 5px;'>
<span>Imprimir Proforma</span>
</div>
` 
with this jquery action
`$("#print_button").click(function()
    {
    	if (confirm('Desea imprimir la proforma'))
    	{
    		$('#cancel_sale_form').attr('action', '<?php echo site_url("sales/complete_proforma"); ?>');
    		$('#cancel_sale_form').submit();
    	}
    });`

in the Sales.php controller i duplicate the complete function, and instead of load the "sales/receipt" view i load a copy of that view that i called "sales/proforma" like this.
`if ($this->sale_lib->is_invoice_number_enabled() && $this->config->item('use_invoice_template'))
{
    $this->load->view("sales/invoice", $data);
}
else
{
    $this->load->view("sales/proforma", $data);
}
$this->sale_lib->clear_all();`
and i just changed the text within this div.
`<div id="sale_receipt">PROFORMA SIN NINGÚN VALOR COMERCIAL</div>`
here are some screenshots:

[https://www.dropbox.com/s/cy3jbif3njkthsb/proforma1.png?dl=0](url)
[https://www.dropbox.com/s/70qhin2nu8kls7k/proforma2.png?dl=0](url)

**Comment by odiea** [comment]
No luck on viewing your screen shots. Can you please upload the in the git window.

**Comment by hovalle** [comment]
![proforma1](https://cloud.githubusercontent.com/assets/5261181/13327656/7f1bf07e-dbb0-11e5-9ed3-3ff2acb2c07b.png)

![proforma2](https://cloud.githubusercontent.com/assets/5261181/13327673/8b60524e-dbb0-11e5-9bbf-f1085d64c0fd.png)

**Comment by odiea** [comment]
Thanks we can see it now. Looks  good.

**Comment by daN4cat** [comment]
yes, adding in the controller as different function sounds good.
Do you also save the proforma in suspended or does it go lost?

**Comment by daN4cat** [comment]
BTW, it would help if you could improve the Spanish translation. There are new parts that I believe are not translated.

For instance the change I made today, about the company logo in configuration, the buttons don't have Spanish translation.

**Comment by hovalle** [comment]
NO! it lost, i just need the proforma to be printed and that's it. But it's a good idea to save them. To be honest with you i don't know how to do this, i was about to cry doing this, i spend  a week trying to accomplish this task. I don't have so much experience in codeigniter i spend time watching tutorials and finally i did it. about the translation i'll try to do it. Thanks a lot guys.

**Comment by hovalle** [comment]
BTW, you can tell me what parts need to be translated and i'll help you out with pleasure.

**Comment by odiea** [comment]
Thanks. Just installed it in my development program and works just fine. Google translated the wording ok.

**Comment by odiea** [comment]
The only issues I see is it does remove the item from the inventory and the sale does not show up in the Takings view. I suppose we could edit the item issue in the complete_proforma section.

**Comment by hovalle** [comment]
ok, and what happend if i remove this line in the complete_proforma function??
`$data['sale_id'] = 'POS ' . $this->Sale->save($data['cart'], $customer_id, $employee_id, $data['comments'], $invoice_number, $data['payments']);`

**Comment by odiea** [comment]
You will get a whole bunch of php errors.

**Comment by odiea** [comment]
anything edited from that line will give php errors.

**Comment by odiea** [comment]
Until another way is figured out I would suggest doing a sale then returning the sale. A rubber stamp with PROFORMA SIN NINGÚN VALOR COMERCIAL would be ideal.

**Comment by hovalle** [comment]
ok it's done i clean up the complete_proforma function to this:
`function complete_proforma()
	{
		$data['cart'] = $this->sale_lib->get_cart();
		$data['subtotal'] = $this->sale_lib->get_subtotal();
		$data['discounted_subtotal'] = $this->sale_lib->get_subtotal(TRUE);
		$data['tax_exclusive_subtotal'] = $this->sale_lib->get_subtotal(TRUE, TRUE);
		$data['taxes'] = $this->sale_lib->get_taxes();
		$data['total'] = $this->sale_lib->get_total();
		$data['discount'] = $this->sale_lib->get_discount();
		$data['receipt_title'] = $this->lang->line('sales_receipt');
		$data['transaction_time'] = date($this->config->item('dateformat').' '.$this->config->item('timeformat'));
		$data['transaction_date'] = date($this->config->item('dateformat'));
		$data['show_stock_locations'] = $this->Stock_location->show_locations('sales');
		$customer_id = $this->sale_lib->get_customer();
		$employee_id = $this->Employee->get_logged_in_employee_info()->person_id;
		$data['comments'] = $this->sale_lib->get_comment();
		$emp_info=$this->Employee->get_info($employee_id);
		$data['payments'] = $this->sale_lib->get_payments();
		$data['amount_change'] = $this->sale_lib->get_amount_due() * -1;
		$data['amount_due'] = $this->sale_lib->get_amount_due();
		$data['employee'] = $emp_info->first_name.' '.$emp_info->last_name;
		$data['company_info'] = implode("\n", array(
				$this->config->item('address'),
				$this->config->item('phone'),
				$this->config->item('account_number')
		));
		$cust_info = '';
		if($customer_id != -1)
		{
			$cust_info = $this->Customer->get_info($customer_id);
			if (isset($cust_info->company_name))
			{
				$data['customer'] = $cust_info->company_name;
			}
			else
			{
				$data['customer'] = $cust_info->first_name.' '.$cust_info->last_name;
			}
			$data['customer_address'] = $cust_info->address_1;
			$data['customer_location'] = $cust_info->zip . ' ' . $cust_info->city;
			$data['account_number'] = $cust_info->account_number;
			$data['customer_info'] = implode("\n", array(
				$data['customer'],
				$data['customer_address'],
				$data['customer_location'],
				$data['account_number']
			));
		}
		$invoice_number = $this->_substitute_invoice_number($cust_info);
		if ($this->sale_lib->is_invoice_number_enabled() && $this->Sale->invoice_number_exists($invoice_number))
		{
			$data['error'] = $this->lang->line('sales_invoice_number_duplicate');
			$this->_reload($data);
		}
		else
		{

		// if we want to email. .. just attach the pdf in there?
		if ($this->sale_lib->get_email_receipt() && !empty($cust_info->email))
		{
			$this->load->library('email');
			$config['mailtype'] = 'html';
			$this->email->initialize($config);
			$this->email->from($this->config->item('email'), $this->config->item('company'));
			$this->email->to($cust_info->email);

			$this->email->subject($this->lang->line('sales_receipt'));
			if ($this->config->item('use_invoice_template') && $this->sale_lib->is_invoice_number_enabled())
			{
				$data['image_prefix']="";
				$filename = $this->_invoice_email_pdf($data);
				$this->email->attach($filename);
				$text = $this->config->item('invoice_email_message');
				$text = str_replace('$INV', $invoice_number, $text);
				$text = $this->_substitute_customer($text, $cust_info);
				$this->email->message($text);
			}
			else
			{
				$this->email->message($this->load->view("sales/receipt_email",$data, true));
			}
			$this->email->send();
		}
		$data['cur_giftcard_value'] = $this->sale_lib->get_giftcard_remainder();
		$data['print_after_sale'] = $this->sale_lib->is_print_after_sale();
		if ($this->sale_lib->is_invoice_number_enabled() && $this->config->item('use_invoice_template'))
		{
			$this->load->view("sales/invoice", $data);
		}
		else
		{
			$this->load->view("sales/proforma", $data);
		}
		$this->sale_lib->clear_all();
		}

		$this->_remove_duplicate_cookies();
	}`

and clean any reference to sale_id from the proforma view and it works.

**Comment by odiea** [comment]
Thanks I will try it. proforma view? is this the receipt?

**Comment by hovalle** [comment]
yes do you remember i duplicate the sales/receipt view and name it sales/proforma to use it with my own set of texts

**Comment by odiea** [comment]
Thanks I was just checking.

**Comment by odiea** [comment]
Great job. You nailed it this time. No use of sale id or removal of items from inventory.

**Comment by hovalle** [comment]
AWESOME!! thanks guys thumbs up for you too, great POS to work with. I hope you can implement this in a future. cheers!!

**Comment by daN4cat** [comment]
What about helping with the Spanish translation? Can you help?

**Comment by hovalle** [comment]
Sure why not, just tell me how can i help. With pleasure, here is my email
hvom07@gmail.com

2016-02-26 0:54 GMT-06:00 FrancescoUK <notifications@github.com>:

> What about helping with the Spanish translation? Can you help?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jekkos/opensourcepos/issues/352#issuecomment-189136234>
> .
>



-- 
ATT :-)  Herbert Ovalle

**Comment by pablos1rvent** [comment]
@hovalle ¡Hola! Estás todavía por estos lares? ^^

**Comment by hovalle** [comment]
Seguro que si!

**Comment by pablos1rvent** [comment]
@hovalle Escucha, todavía tienes el código entero de la proforma? Molaría hacerlo pull, además de que lo necesito, espero que me puedas ayudar,
Un saludo, Pablo! :point_up_2:

**Comment by hovalle** [comment]
claro que si, pero podría hacerlo mañana a lo largo del día. Ahora mismo no tengo mucho tiempo. Saludos.

**Comment by pablos1rvent** [comment]
Faltaría mas. Si necesitas cualquier tipo de ayuda o cualquier cosa me dices.

Un saludo! :D

**Comment by pablos1rvent** [comment]
@hovalle ¡Hola! Sigues por aquí?

**Comment by pablos1rvent** [comment]
@odiea @daN4cat @jekkos @hovalle Is this with the code outdated? I tried but it gives me a lot of errors :S

**Comment by jekkos** [comment]
Yes it's probably outdated?? You will need to sync with the latest version.. good task to learn a bit of php ;)

**Comment by pablos1rvent** [comment]
@jekkos Well, I'm gonna try to update the code, but I don't promise anything :smiley:

**Comment by pablos1rvent** [comment]
@jekkos Is this necessary? In the code of OSPOS doesn't exist, but in the code of @hovalle is in the last line:
`$this->_remove_duplicate_cookies();`

**Comment by hovalle** [comment]
ok guys i'm sorry i was late with this. i'll share my changes today, i hope so!  :smile: i hope you can integrate this changes in the main branch. i'm helping with the translations too. Ok guys later then.

**Comment by jekkos** [comment]
No you can get rid of it

**Comment by hovalle** [comment]
Hi Guys, this is the final project with the proforma included  https://github.com/hovalle/opensourcepos  
i'll do a pull request but i have to tell you my changes are not dynamic they are in spanish i hope you can integrate this in the main project. Cheers!!

**Comment by pablos1rvent** [comment]
@hovalle ¡Gracias, a lot of thanks to you!

**Comment by hovalle** [comment]
de nada, a proposito puedes escribirme en español.  :D, ojala comprendas lo
que hice cualquier duda estamos a la orden. Saludos.

2016-05-20 15:35 GMT-06:00 Pablo S1rvent <notifications@github.com>:

> @hovalle <https://github.com/hovalle> ¡Gracias, a lot of thanks to you!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/jekkos/opensourcepos/issues/352#issuecomment-220724096>
>



-- 
ATT :-)  Herbert Ovalle

**Comment by pablos1rvent** [comment]
@hovalle Se llama Spanglish xD

Pues vale perfecto, aunque tendré que comparar los archivos actualizados tuyos y los de ahora, están a la última?

**Comment by hovalle** [comment]
si, es la última versión, pero revisalos de cualquier forma. Como buen
informático :D

El 20 de mayo de 2016, 15:42, Pablo S1rvent <notifications@github.com>
escribió:

> @hovalle <https://github.com/hovalle> Se llama Spanglish xD
>
> Pues vale perfecto, aunque tendré que comparar los archivos actualizados
> tuyos y los de ahora, están a la última?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/jekkos/opensourcepos/issues/352#issuecomment-220725380>
>



-- 
ATT :-)  Herbert Ovalle

**Comment by odiea** [comment]
This works out well. What I did was remove the $this->sale_lib->clear_all(); in controller/sales function complete_proforma() and after you print the proforma and go back to the register you can either cancel or suspend the proforma .
