### ISSUE TITLE
nginx  404 not found

### ISSUE THREAD

**Issue by EdenQi** [jekkos/opensourcepos#354]
my system is  LNAMP(Linux, nignx 1.9.7, Apache 2.4.17, PHP 5.5.30).

POS version 2.4

**Comment by EdenQi** [comment]
how can i fix it ?

**Comment by daN4cat** [comment]
nignx and apache, why two web servers?

**Comment by jekkos** [comment]
Please be more specific. Which page were you requesting? Is it nginx or apache sending this error?

**Comment by daN4cat** [comment]
I close this, it's a configuration issue for sure.
