### ISSUE TITLE
How to change Language ?

### ISSUE THREAD

**Issue by Halwest01** [jekkos/opensourcepos#356]
Hello, where can i change language of the pos ? sorry i didn't know where to post this question so i posted it here .

**Comment by ramiznazir** [comment]
In Store Config->Locale you can change language.

**Comment by Halwest01** [comment]
thank you very much , but if i had some employee who wanted to use another language and some wanted English ?! :)

**Comment by daN4cat** [comment]
Not possible at the moment as it's a global settings not by employee. Also the language you chose affects the printing of the receipts/invoices.

**Comment by ramiznazir** [comment]
Its not possible at same time on one server that each employee who is
logged on set language of his/her choice.

**Comment by Halwest01** [comment]
Thank you very much guys for your answer.
