### ISSUE TITLE
div with #feedback_bar not show

### ISSUE THREAD

**Issue by arkgnan** [jekkos/opensourcepos#357]
in v.2.3.4 after save the config we see the green message from div with id #feedback_bar, but it not show in v.2.4

**Comment by daN4cat** [comment]
Right, it might be the side effects of other fixes I cherry picked from bootstrapUI branch. Let me check this issue.

**Comment by daN4cat** [comment]
I checked and there is no change affecting this in 2.4.
I even test it and works fine with me, Not sure what the issue is with your installation.

Please do a clean installation of 2.4 because if you mixed up let say bootstrapUI with 2.4 branches you might face issues.

**Comment by arkgnan** [comment]
i use v2.4 from bootstrapUI branches, feedback_bar div not show and no alert style from bootstrap too, user does not know whether the configuration is saved

**Comment by arkgnan** [comment]
i got same issue from develop/2.4 branch

**Comment by jekkos** [comment]
Works on my machine.. in bootstrapUI branch at least.  Also think that in develop/2.4 should be good.

**Comment by daN4cat** [comment]
it works for me too with bootstrapUI, not sure what's wrong @arkgnan 

What do you see with Google Chrome Inspector?

**Comment by odiea** [comment]
I downloaded 2.4 earlier and the only issue I have is the return php error. All feedback is showing properly.

**Comment by daN4cat** [comment]
The "return error" was fixed again in #331. But that was a minor issue and not affecting the feedback_bar here.

**Comment by arkgnan** [comment]
i don't get these issue from barcode tab, stock and receipt tabs. feedback_bar didn't show only in general and locale tabs

**Comment by arkgnan** [comment]
this is my general_config script
http://pasted.co/98318597

**Comment by odiea** [comment]
I downloaded and installed this script and had no issues with the feedback bar showing at the bottom of the page after hitting submit.

**Comment by arkgnan** [comment]
![not_show](https://cloud.githubusercontent.com/assets/17277219/13341619/e3024cf2-dc6c-11e5-9a9d-9ee582cf0bf8.png)
![show](https://cloud.githubusercontent.com/assets/17277219/13341620/e3046046-dc6c-11e5-9d25-d8aeaf4e23b9.png)
i combine ospos bootstrap with adminlte style, Not sure what the issue with adminlte css

**Comment by odiea** [comment]
![2016-02-25 20_03_40-](https://cloud.githubusercontent.com/assets/10962177/13342045/0a33a02c-dbfb-11e5-87c1-eb7bb8ade1fa.png)
It must be something in your setup.

**Comment by arkgnan** [comment]
what must i do? replace config file in view?

**Comment by odiea** [comment]
I would suggest downloading and do a fresh install of the current version and make sure that it works first. Then try out your mods and see what happens

**Comment by arkgnan** [comment]
what branch i must download?

**Comment by odiea** [comment]
Feature/bootstrapui is still in development but I believe it would be a good one to play around with.

**Comment by arkgnan** [comment]
@odiea i did your sugestion. i download Feature/bootstrapui and doing fresh install. i upload it to web hosting. it work properly. i think the issue is with my xampp. i don't know why...

**Comment by daN4cat** [comment]
Please make sure you use the correct views/partial/footer.php because I made a change a while back to move the feedback_bar to that file. It's even in spacelab template. So if you didn't use the latest bootstrapUI files you might have got the issue you reported.
