### ISSUE TITLE
Setup a license file to contain all the used component licenses

### ISSUE THREAD

**Issue by daN4cat** [jekkos/opensourcepos#359]
If OSPOS is used in a commercial environment all the software licenses need to be collated and connected to the application properly, also be displayed.

I will need to check better how OSS license works for web sites, but it's a legal point that needs to be sorted to protect any commercial installation of OSPOS.

**Comment by jekkos** [comment]
Ok a legal issue but an important one indeed.

**Comment by daN4cat** [comment]
yes, let me deal with this because for other reasons I'm familiar with the matter.

**Comment by jekkos** [comment]
Ok cool. Curious to see how this will be handled.

**Comment by daN4cat** [comment]
Usually on consumer devices, mobile applications and the like you publish a software license (under about or similar). In this file you list all the open source software (OSS) you use with all the copyright statement. Just check any of the application you have on your mobile phone, surely there is a license somewhere listing for example code xyz, license term (e.g. MIT).

I assume web server need to do as well, but I need to check better the case. I'm more familiar with consumer device software and mobile application software.

**Comment by jekkos** [comment]
Shouldn't we notice copyright protection in the footer with a link to the COPYING document as well? I found that a lot of companies are taking the code and changing the footers with their own company name..

I was thinking that we might setup a quick hash that triggers and tracks installs that have footers modify, just a matter of knowing how ospos is used (and if it is rebranded or not). Maybe also add an option in config to collect statistics or not.

**Comment by odiea** [comment]
Indeed. You need to do something to protect your intellectual properties.

**Comment by odiea** [comment]
https://opensource.org/faq#commercial This might be a good read before you implement anything.

**Comment by daN4cat** [comment]
@odiea thank you for the link that's useful info.

I believe there are various parts in this story:

1. OSPOS license displaying
2. OSPOS license enforcing
3. Third party code licenses

First I wanted to sort out 3 as for any commercial use we need to list all the code we use and their licenses. This is standard practice when using Open Source Software in any product, you need to provide a license statement (e.g. check the about section of your Android based phone for instance and you can see a long list of libraries used and their code license).

In the license statement point 1 will be covered.

With regards to 2., I will need to read more and we can discuss better that topic here.

**Comment by daN4cat** [comment]
In my commit:

- Store Config has a License tab to display license files
- COPYING has been modified, please read the key addition. COPYING content must be visible in Store Config License in order to be legally allowed to use OSPOS (we are entitled to claim that because the copyright statement must be visible not only included)
- Third party license files have been created for some key parts, however it would be good to have grunt to be able to generate additional files out of bower components LICENSE files. 
Unfortunately I'm not able to find the means without investigating a lot how to generate those automatically. I'm sorry but I don't have the time to work on that at the moment.

**Comment by odiea** [comment]
Small typo Open Surce Point Of Sale 3.0.0

**Comment by daN4cat** [comment]
Where exactly?

**Comment by daN4cat** [comment]
ok, everypage is not right for sure. A spacing is missing.

**Comment by daN4cat** [comment]
Found the "Surce" typo.

**Comment by daN4cat** [comment]
Fixed.

**Comment by jekkos** [comment]
http://www.softwarefreedom.org/resources/2008/foss-primer.html#x1-80002.2.2

Interesting read on licensing

**Comment by daN4cat** [comment]
Is your suggestion to switch from MIT to BSD? Or to add restrictions? I added some restriction, but maybe BSD is better than MIT as framework.
I skimmed through the text but I need a second reading.
For sure what I don't want is GPL as it's a nightmare, especially GPLv3.

Last point is the enforcement part, that's an issue if we want to prevent re-branding and any removal of original copyright holders.

**Comment by jekkos** [comment]
Yes I've read a bit further on the BSD licensing and I think that the 4 clause license suits our situation best. 

`3. All advertising materials mentioning features or use of this software
   must display the following acknowledgement:
   This product includes software developed by the <organization>.`

This might be a more general way of asking the footer to remain unchanged.

**Comment by jekkos** [comment]
bower licenses

```
{
    "bootstrap-select@undefined": {
        "licenses": [
            "MIT"
        ],
        "homepage": "http://silviomoreto.github.io/bootstrap-select"
    },
    "bootstrap3-dialog@1.35.2": {
        "licenses": "UNKNOWN",
        "homepage": "http://nakupanda.github.io/bootstrap3-dialog/"
    },
    "chartist@undefined": {
        "licenses": "UNKNOWN"
    },
    "bootswatch-dist@3.3.6-flatly": {
        "licenses": [
            "MIT"
        ],
        "homepage": "https://github.com/dbtek/bootswatch-dist"
    },
    "chartist-plugin-axistitle@0.0.1": {
        "licenses": [
            "WTF*"
        ]
    },
    "chartist-plugin-pointlabels@0.0.4": {
        "licenses": [
            "WTF*"
        ]
    },
    "chartist-plugin-tooltip@undefined": {
        "licenses": [
            "MIT*"
        ]
    },
    "file-saver.js@1.20150507.2": {
        "licenses": [
            "LICENSE.md"
        ],
        "homepage": "https://github.com/Teleborder/FileSaver.js"
    },
    "jquery@undefined": {
        "licenses": [
            "MIT"
        ]
    },
    "jquery-form@3.45.0": {
        "licenses": "UNKNOWN"
    },
    "js-cookie@undefined": {
        "licenses": [
            "MIT"
        ]
    },
    "jspdf@1.0.272": {
        "licenses": [
            "MIT"
        ],
        "homepage": "https://github.com/mrrio/jspdf"
    },
    "moment@undefined": {
        "licenses": [
            "MIT*"
        ]
    },
    "tableExport.jquery.plugin@undefined": {
        "licenses": [
            "MIT"
        ]
    },
    "bootstrap@undefined": {
        "licenses": [
            "MIT"
        ],
        "homepage": "http://getbootstrap.com",
        "repository": "git+https://github.com/twbs/bootstrap"
    },
    "bootstrap-daterangepicker@undefined": {
        "licenses": [
            "MIT"
        ],
        "repository": "git+https://github.com/dangrossman/bootstrap-daterangepicker"
    },
    "bootstrap-table@undefined": {
        "licenses": [
            "MIT"
        ],
        "homepage": "https://github.com/wenzhixin/bootstrap-table",
        "repository": "git+https://github.com/wenzhixin/bootstrap-table"
    },
    "html2canvas@0.4.1": {
        "licenses": [
            "MIT"
        ],
        "repository": "git+ssh://git@github.com/niklasvh/html2canvas"
    },
    "jasny-bootstrap@3.1.3": {
        "licenses": [
            "Apache-2.0",
            "Apache*"
        ],
        "repository": "git+https://github.com/jasny/bootstrap"
    },
    "jquery-ui@1.11.4": {
        "licenses": [
            "MIT"
        ],
        "repository": "https://github.com/jquery/jquery-ui"
    },
    "jquery-validation@1.13.1": {
        "licenses": [
            "MIT"
        ],
        "repository": "https://github.com/jzaefferer/jquery-validation",
        "homepage": "http://jqueryvalidation.org/"
    },
    "jspdf-autotable@undefined": {
        "licenses": [
            "MIT"
        ],
        "homepage": "https://github.com/simonbengtsson/jspdf-autotable",
        "repository": "git+https://github.com/simonbengtsson/jsPDF-AutoTable"
    },
    "remarkable-bootstrap-notify@3.1.3": {
        "licenses": [
            "MIT"
        ],
        "homepage": "http://bootstrap-notify.remabledesigns.com/",
        "repository": "https://github.com/mouse0270/bootstrap-notify"
    },
    "smalot-bootstrap-datetimepicker@undefined": {
        "licenses": [
            "Apache 2.0",
            "Apache*"
        ],
        "repository": "https://github.com/smalot/bootstrap-datetimepicker"
    }
}
```

**Comment by jekkos** [comment]
I was trying to find a license checker that scans both npm and bower but currently haven't been able to find one. Maybe we don't need to include the npm licenses as these modules are not shipped in our code? They are only used once a user sets up a full dev environment.

**Comment by daN4cat** [comment]
The most used scanner is called Protex, but we don't need to use it. No need for tools license, just the code or graphic asset we use in the running code.

**Comment by jekkos** [comment]
OK or we could just display the list of licenses based on the json generated with grunt-license-bower? This way we include them all and once a plugin is added it's license and usage is added as well. Shouldn't be too hard to generate a list from that json (just parse it in php and iterate over the items?)

**Comment by jekkos** [comment]
Or maybe I can just add the names of used libraries and links to their repo's as a reference (so one can check license on their site?)

**Comment by daN4cat** [comment]
I was doing exactly the same and I added another plugin to check the license validity as additional step.
I guess the next one is to read the license/LICENSES from the store config, but as an additional step not replacing everything. Probably I need to move to json file format the other files. I'll look into that this eve.

**Comment by daN4cat** [comment]
Licenses read from the grunt generated file.
However the grunt bower-license script is not that much robust, not sure for instance why the version is not read correctly.
Anyway this is the best we can do at the moment.

**Comment by daN4cat** [comment]
@jekkos I noticed you forked `grunt-license-bower` but I checked a bit and the problem is `bower-license` that is used by the other the grunt plugin.

It looks like the version is not read from package.json and in other cases it just looks for the LICENSE file where it should check more options/variants (e.g. LICENSE.md should be acceptable).

**Comment by jekkos** [comment]
yes indeed, I meant to go through that codebase to see why it isn't parsing the version fields properly. I already did a dependency upgrade (as bower-license npm package was quite outdated) hoping that it would improve this behavior already. Will test further on my local setup first. 

I did check some of the bower.json files that are installed by bower install and not all of them seem to have a version tag in it. However most of the time there is a second .bower.json present that does have the version anyway. Need to investigate a bit further where that one comes from and whether we can improve the modules' behavior to take advantage of it.

**Comment by daN4cat** [comment]
Yep, would be nice to get that more robust and contribute back.

**Comment by jekkos** [comment]
I have regenerated the license file after changing the search order for bower.json in bower-json node module. This time most of the version fields are filled in and some missing license types are also resolved.

WIll need to think about an easy way to extend this behavior in the current plugin setup ( bower-license is using bower-json to parse the metadata .. I guess it'd be best to change as little dependencies as possible there)

**Comment by jekkos** [comment]
One very last thing I might want to add is the #624 composer setup. Should be pretty easy to do and composer also includes some functionality to assemble the licenses of used dependencies. 

Should be just a matter of entering a couple of commands to generate the composer.json for CI (and enabling an autoload option in config.php)

**Comment by daN4cat** [comment]
LICENSES file is better now, however we would really need to get the bower plugin to work properly.

**Comment by daN4cat** [comment]
@jekkos there is a problem with the trigger, if I do bower update I get an error stating that it cannot run `grunt genlicense`

**Comment by jekkos** [comment]
think you'll need to run npm install again first? I added a new grunt plugin to make the bower license generation work with the versions filled in

**Comment by daN4cat** [comment]
Yes, I noticed that and I just installed the extra grunt plugin.

**Comment by daN4cat** [comment]
I had now time to run bower update again but despite having installed `grunt-contrib-clean` it still doesn't work and fails in the same way is says `Tasks "[object Object]"` not found.

**Comment by daN4cat** [comment]
Fixed the issue I had with bower update.

**Comment by daN4cat** [comment]
We can close this issue.
