### ISSUE TITLE
how to change receipt configuration

### ISSUE THREAD

**Issue by arkgnan** [jekkos/opensourcepos#360]
I have question. why i can't change receipt config from 'Show Print Dialog' option to bottom. it's like have disable or readonly attribute but i couldn't find in receipt_config.php

**Comment by odiea** [comment]
Are the printer dropdown boxes showing any available printers?
Do you have JS print installed in your web browser as an addon?

**Comment by arkgnan** [comment]
ah my fault... i use chrome and there's no equivalent extension
