### ISSUE TITLE
bootstrapui issues

### ISSUE THREAD

**Issue by odiea** [jekkos/opensourcepos#361]
Bulk update does nothing. 

Items-details-after submit
A Database Error Occurred

Error Number: 1048

Column 'trans_comment' cannot be null

INSERT INTO `ospos_inventory` (`trans_date`, `trans_items`, `trans_user`, `trans_location`, `trans_comment`, `trans_inventory`) VALUES ('2016-02-25 05:34:52', '3', '1', '1', NULL, NULL)

Filename: C:/xampp/htdocs/featureui/application/models/Inventory.php

Line Number: 6

**Comment by daN4cat** [comment]
Agreed, bulk update doesn't work.

However I edited an item and saved with no error.

How do you get the error you reported?

**Comment by odiea** [comment]
click on details and then click submit. I don't recall details ever having a submit button.

**Comment by jekkos** [comment]
I've done some rework on bulk update. But maybe needs some more thorough testing.

**Comment by odiea** [comment]
is this fix on your site?

**Comment by odiea** [comment]
OK it works now but the issue of deleting the tax percent if none is entered is still there. You need to either remove the submit button from details or change it to close else it throws a php error.

**Comment by daN4cat** [comment]
Items / details should not have a submit button indeed.
It's just a log view type of form, so it should be just OK with no action.
Probably the submit is the issue, maybe it's a copy and paste of the inv form.

**Comment by daN4cat** [comment]
I leave to @jekkos to fix since he's working on the forms.

**Comment by jekkos** [comment]
How would you prefer to have the syntax of button configuration? Add a class to show a submit button? like `modal-btn-submit modal-btn-new` to have two buttons and `modal-btn-submit` to have just one?

Currently a submit button is shown by default. I could also do the inverse and add `modal-btn-none` to omit all.

**Comment by daN4cat** [comment]
The details in items does not need a submit. It's should be just an OK if we want to show a button.
Please check 2.3.4, there was no button at all, just the X on the top to close the window.

In general I would consider an OK button for things that are just to view logs.

**Comment by jekkos** [comment]
So a close button as default (so we always have at least one) and then use extra classes that reject this default behavior?

**Comment by daN4cat** [comment]
Yes, a close button will do.

Also please set submit to the right and things like new/delete on the left. So the user sees a constant UX pattern of submit always on the right and does not make a mistake.

It's a detail but it happens.

**Comment by daN4cat** [comment]
I believe this is sorted now, right?

I close if not, please reopen.
