### ISSUE TITLE
Error unable to load...

### ISSUE THREAD

**Issue by ombendot** [jekkos/opensourcepos#363]
Hi, i'm new to OSPOS, recently install through softaculous. I've done some editiing to the store config, employee, customer, items, and suppliers.

Then when I opened Receivings, and Sales this come up : 

An Error Was Encountered

Unable to load the requested file: receivings/receiving.php

Can anyone give an idea how to fix it?

**Comment by daN4cat** [comment]
Version please

**Comment by ombendot** [comment]
sorry its ver 2.3.4

**Comment by daN4cat** [comment]
When you say editing, what do you mean?

Have you changed the code for your needs?

**Comment by ombendot** [comment]
hi,
editing i mean adding data to items, users, customers, supplier, changing store config etc.
never the code.

isit okay to just reinstall?

**Comment by daN4cat** [comment]
BTW, I just noticed that you mention "softaculous", I'm not sure what that script does, so I would do an installation fully under your control first. Take the latest master and reinstall.

**Comment by ais-one** [comment]
Looks like a file is missing, better check to see if the file is present. That one should be in the applications/view. Pretty straight forward. Should close this issue.

**Comment by ombendot** [comment]
thanks, i've uploaded the latest master and reinstall.
everything is back.

thanks for your kind suggestion

**Comment by daN4cat** [comment]
:+1:
