### ISSUE TITLE
Move bootstrapUI to 2.4 branch

### ISSUE THREAD

**Issue by daN4cat** [jekkos/opensourcepos#364]
We are not that far from completing bootstrapUI and maybe we could merge it to 2.4 and keep just one development branch alive to avoid people reporting different issues on different branches, or making mistakes submitting something in one branch and not in another.

In the past days I spent time in fixing issues on 2.4 that were fixed in bootstrapUI and we don't aim to deliver 2.4 as it is.
I want to cut on this and just work on the latest with bootstrapUI.

**Comment by jekkos** [comment]
Regarding these branch I think one positive thing is that we can keep 2.4 as a 'stable' version of our current upgrade (in this case a version based off CI3). 

Regarding the push mistake, I shouldn't have forced without specifying the branch I wanted to push to, so this really was a bad mistake that shouldn't have happened (things could have been even worse), so something I'll certainly try to avoid in the future.

I'm fine with merging the branches but maybe only if we tag the latest HEAD in develop/2.4 at a  point in which CI3 upgrade was working correctly.

**Comment by daN4cat** [comment]
So we should test develop/2.4 to make sure it's fine and tag it with CI3.

After that we can merge bootstrapUI to 2.4, so we can keep one story line.

**Comment by jekkos** [comment]
Yes think that would be best.

**Comment by daN4cat** [comment]
I would prefer not because the number of issues or pseudo-issues will increase.

Also I think CI3 & bootstrapUI change accounts for a version 3. It's in the end a major change so people know that things "are broken" on their side if they kept pulling stuff under the hood without contributing back (I guess many of them!).

**Comment by daN4cat** [comment]
And vs 3 moves with CI3 well.

**Comment by daN4cat** [comment]
Also, can I merge the latest change from develop/2.4 into bootstrapUI branch?

I see a CI2 hack was removed in 2.4.

**Comment by ais-one** [comment]
Can't wait for this to be pushed out, future improvement, you may want to consider using stuff like select2 (has type-ahead), x-editable, and such stuff. But anyway great stuff.

I do see some places where the UI can be improved, like the size of the input boxes, if I do have time to look into it and fix, will send a pull request.

**Comment by daN4cat** [comment]
@ais-one I've updated the sizes in config tabs. I'll apply the same to forms and change the file/image upload in forms to be the same widget I used in config for the company logo and similar.

And I want to finish the sale register restyling too.

**Comment by daN4cat** [comment]
BTW, I merge develop/2.4 changes in features/bootstrapUI

**Comment by ais-one** [comment]
ok, I am currently using features/bootstrapUI, testing out on PHP 7.0.2, so far no issues

**Comment by daN4cat** [comment]
PHP 7 is in #339

**Comment by onyema3** [comment]
The backup button error is still in the features/bootstrapUI version.
Giving me some php gibberish.
See the attached

**Comment by daN4cat** [comment]
Missing the attachment, sorry.

**Comment by ais-one** [comment]
I am trying avatar upload on items, its not uploading, I am trying to find out why. If anyone is working, please let me know.

**Comment by jekkos** [comment]
Did you check file permissions on upload folder?

**Comment by ais-one** [comment]
I set to 777 from uploads recursively, I also used windows xampp, no such luck. I checked the html output, it looks ok, still trying to figure out (I did not work on it yesterday though).

**Comment by odiea** [comment]
I checked and on 2.4 it will upload the img but not display it . On bootstrap it will not upload the image. I checked in the uploads/image folder

**Comment by odiea** [comment]
On 2.3.4 it uploads the image and creates a thumb. On 2.4 it uploads the image but does not create a thumb.

**Comment by ais-one** [comment]
The company_logo upload part is working though...

**Comment by odiea** [comment]
Yes it is but there appears to be no way to remove it to go back to the company name.

**Comment by daN4cat** [comment]
@odiea please create an issue about this point of not able to remove the logo

**Comment by daN4cat** [comment]
@ais_one please create an issue about the items thumb

**Comment by daN4cat** [comment]
Closed because we agreed that bootstrapUI will be 3.0 and what is 2.4 will become master after 2.3.4
