### ISSUE TITLE
[AdminLTE] can't back to previous menu after submit new item

### ISSUE THREAD

**Issue by arkgnan** [jekkos/opensourcepos#368]
hi, i need some help, i combine ospos with adminlte style, and i got issue about submitting in items menu. after create new items or edit the program redirect to controller items/save and show json data

{"success":true,"message":"You have successfully updated item lifebuoy cair","item_id":"7"}

it should be directed to menu (in this case is items menu with new data)

**Comment by daN4cat** [comment]
You are missing the feedback bar.

**Comment by arkgnan** [comment]
feedback bar in footer?

**Comment by daN4cat** [comment]
I don't know what you have done with your installation but it looks like you are not using bootstrapUI branch as it is. So it's difficult to help you. Submit your code in github and point the issue to a change you have made to get help.

**Comment by arkgnan** [comment]
my code is base on https://github.com/cpl2015/opensourcepos. i mixed few script from bootstrapui. i don't know how to using github, i try to submit but it not work (https://github.com/arkgnan/osposadminlte). so i upload the source code in dropbox (https://dl.dropboxusercontent.com/u/49434699/ospos.zip) @daN4cat can you help about my problem in submitting

**Comment by arkgnan** [comment]
can you tell me the function that regulate feedback bar. controller or js function...

**Comment by arkgnan** [comment]
i found post_item_form_submit() in form.php (https://gist.github.com/arkgnan/12d06b4744a7d880810d) and i don't understand hows that function work. i search in any js file but there's no function like that

**Comment by daN4cat** [comment]
@arkgnan please don't use cpl2015 version as it's old and was coming from a branch I had in my repo.
Having said that I have now pushed features/bootstrapUI brach from here to my repo (daN4cat) master. I'll keep the two in sync so people don't need to bother about branches.
In the end the version I want and I'm working on is the CI3 + boostrap one.

**Comment by daN4cat** [comment]
@arkgnan and I'll explain later how to work with Github and submit your code. I'm afraid I have no time right now.

**Comment by arkgnan** [comment]
ok, thank for your support... i'll submit my code to github later.

**Comment by daN4cat** [comment]
ok, you need to instruct yourself a bit about how github works.
I don't know if you use windows or linux, but there is a client tool that you can use and tutorials are good.

First you fork, than you add your changes on it, you commit to your local replica and then push it to your fork repository.

After that, just flag here that you have done and I can have a look.

**Comment by arkgnan** [comment]
hi, i'm done with github. i create new repository and submit the source code. the migration to adminLTE is complete. all dialog with popupbox change to bootstrap modal style. tabs in config using bootstrap tabs style. you can see it on https://github.com/arkgnan/osposAdminLTE
check it if you have spare time

**Comment by ais-one** [comment]
Doesn't AdminLTE clash with bootstrapUI feature? Anyway I will download this and take a test-drive.

It seems to have quite a lot more components, its more for dashboard, but version 2 starts two have simple tables which may eventually lead to CRUD.

**Comment by daN4cat** [comment]
AdminLTE is different from bootstrapUI work indeed.
bootstrapUI is based on boostrap3 + bootswatch theme.
AdminLTE is built on top of boostrap 3 and has more.

Replacing bootswatch flatly one could consider AdminLTE, I suppose. But then you can go further replacing other parts like reports, all the views having tables and etc.

**Comment by daN4cat** [comment]
@arkgnan I'm afraid most of the issues you experience and report are specific to your porting of the old code and specific setup.
Unfortunately we are limited in resources and we cannot keep up with custom or legacy code.
