### ISSUE TITLE
Improve the Customer info in Sales/register

### ISSUE THREAD

**Issue by daN4cat** [jekkos/opensourcepos#369]
We should consider #335 and also a form that pops up reporting the list of all the transaction connected to that customer with totals.

Ideally we should give a score to a customer based on some thresholds, so the shop assistant can apply a discount to the customer at discretion when they are good and loyal ones.

The latter part requires more, so a form with list of transaction together with full customer info will do as first step.

Also a customer discount as per #375 could do to simplify things from management involvement.

**Comment by ais-one** [comment]
This is definitely something useful for CRM purposes. Usually for higher end products/services rather than daily groceries (own opinion). Some questions come to mind...

How should it be displayed?

per transaction? (better not use this because if so, may need pagination and filtering, but for frontline sales staff, it may be too much to handle).

or cumulative spend so far?

benefits should probably be automatically given to avoid errors or disputes? with the CRM information only for reference?

Need to calculate average spend over a period? e.g. $/month?

**Comment by daN4cat** [comment]
#375, discount to be considered here

**Comment by daN4cat** [comment]
My wife has a fashion boutique, so for her this case is normal business. Registered customers that have at least a certain amount get 5%. Good customers get a 10%.
But she tells me that they need to go by memory and something indicating the customer history would help a lot.

As said, extending the register to show more customer info will be a starting point.
Then add a cumulative total of purchases with a raking number against other customers.
A prefixed discount could be added as indication or could be applied to non already discounted items automatically.

**Comment by daN4cat** [comment]
Then the form displaying the historical of the customer purchases could be a second step and should not be so difficult given that we have examples of forms with list like inventory ones.

**Comment by ais-one** [comment]
now working on this.

so you would like to display customer total spend when they search and key in the customer in the sales?

or list historical sales and have total spending at the bottom? (this is more time consuming and complicated due to need for pagination of data)

**Comment by daN4cat** [comment]
I would focus on the first part first, leave the historical for later.

Thanks.

P.S.: I also suggested help with the print in Sales/Takings, that's unfinished stuff. Maybe that before this?

**Comment by jekkos** [comment]
total spent would indeed be nice addition already.

**Comment by jekkos** [comment]
perhaps this could go in 2.3.5 ?

**Comment by ais-one** [comment]
ok in that case, I will do the Sales/Takings first.

I am currently using the feature/BootstrapUI branch.

Once its ok there, I will fork master and merge it to 2.3.5 (but I do not see 2.3.5, should it be 2.4?)

**Comment by jekkos** [comment]
Yes might be better to start the work off 2.3.5. In the end we can merge this feature in latest bootstrap UI which eventually will superseed latest master.

**Comment by daN4cat** [comment]
@jekkos I thought 2.3.5 was minor things. Why do we want to keep going with more functionality?

I would prefer to stop with 2.3.5 to small bits so we don't need a 2.3.6 to sort out something (just in case), and finally go for a 2.4 or better vs 3 with bootstrapUI.
The split in 3 branches should be short lived otherwise it becomes a burden with no end.

For instance I have no time to check if 2.4 with CI3.04 only branch is completely fine. For me bootstrapUI is the one. I would have already merged the two and as said made it vs 3 (too many big changes to say it's a vs 2).

**Comment by jekkos** [comment]
At first I thought that this change would only be a small one (in this case a new query in the model + one extra digit in the view) for customer total. 

But maybe it's a better idea to release 2.3.5 and then merge develop/2.4 to master (as a current stable) and rename bootstrapUI to v3.0 indeed. The latter has become much more than a feature branch and that might make things a little clearer.

I agree that there are too many changes and v3 would be appropriate here.

**Comment by ais-one** [comment]
Just one note, for this project to gain more traction, responsive UI should be include as early as possible. If the UI can be responsive, I am sure there will be much more following.

**Comment by jekkos** [comment]
Yes this rework is one that has to be finished first. All help is welcome as it's quite a lot of things to do. Also I would like to rethink a bit the sales register layout to be usable on smaller devices as well.

**Comment by daN4cat** [comment]
I'm changing the register areas to be panels, but I didn't play too much with the resizing/responsiveness. Probably that's a second step after the big part is over.

**Comment by odiea** [comment]
Everyting is looking good this morning. It appears the only delete function left is in takings. The new date picker for reports is a little strange if you try to manually change the date.

**Comment by daN4cat** [comment]
@odiea you need to get used to the daterangepicker. You have a start and end date, that's why you get a bit puzzled the first couple of times. Anyway the preloaded ranges should do most of the time.
If you want different ones let me know that I can add.

**Comment by odiea** [comment]
No problems just need to play with it some more.

**Comment by daN4cat** [comment]
First part of the customer info with the new sales/register. Post comments here for more (outside the total spent by the customer, which I need to add).
I know the discount is something we wanted, but that requires more changes than some cosmetics ones.

**Comment by odiea** [comment]
That's why I ended up using the following that worked for me.
if(isset($customer))
	{
	$customer_id = $this->sale_lib->get_customer();
    $cust_info = $this->Customer->get_info($customer_id);
    echo $this->lang->line("sales_customer").' : <b>'.$customer. '</b><br />';
    echo $this->lang->line("customers_account_number").' : '.$cust_info->account_number.'</b><br />';
	echo $this->lang->line("customers_company_name").' : '.$cust_info->company_name.'</b><br />';
	echo $this->lang->line('common_phone_number').' : <b>' .$cust_info->phone_number. '</b><br />'; 
	echo $this->lang->line("common_address_1").' : <b>'.$cust_info->address_1. '</b><br />';
    echo $this->lang->line("common_address_2").' : <b>'.$cust_info->address_2. '</b><br />';
	echo $this->lang->line("common_city").' : <b>'.$cust_info->city. '</b><br />';
    echo $this->lang->line("common_state").' : <b>'.$cust_info->state. ', ' .$cust_info->zip.'</b><br />';
   echo $this->lang->line('common_email').' : <b>'.$cust_info->email. '</b><br />'; 
   echo $this->lang->line("common_comments").' : <b>'.$cust_info->comments. '</b><br />';
   echo $this->lang->line('config_default_sales_discount').' : <b>'.$cust_info->default_sales_discount.'</b><br />';
   echo anchor("sales/remove_customer",'['.$this->lang->line('common_remove').' '.$this->lang->line('customers_customer').']');
	}

**Comment by daN4cat** [comment]
ok, but you cannot fit all of that in sales/register. You end up having the Add Payment and Complete buttons in a second page.
Most of the people would love to have everything in one page.

Maybe what I could do is to have a sort of tooltip or dropdown panel showing all the extra?

Something like 2, 3 lines for the extract and extended in the panel?

**Comment by daN4cat** [comment]
Or alternatively I could consider having tabs?

**Comment by daN4cat** [comment]
I'm currently progressing this. I've added customer discount field and total purchase print out. More to implement.

The discount will be applied to what is not already discounted.

**Comment by daN4cat** [comment]
Added customer discount % as per #375 and it's shown in the register when a customer is selected.
It's also used as default discount on selected items once the customer is added.
The discount is not added to previously selected items neither is removed if the customer is removed.
I might add something about that later, we'll see.

Also now the Total spent by the customer is shown in the sales register and in the customer form (as read only field above the discount).

Please note that you need to run the upgrade 2.4 to 3.0 database script to make use of this feature.
