### ISSUE TITLE
On sales delete item count not normalised.

### ISSUE THREAD

**Issue by zizango123** [jekkos/opensourcepos#370]
On delete of a sale the item count that had been sold on that sales is not reflected on the item count.

**Comment by daN4cat** [comment]
What should be the behaviour in this case since the sale is deleted?

Reinstate the item quantity as before the sales or not?

**Comment by daN4cat** [comment]
Also, is it correct to delete a sale? It might have fiscal control implications.

Thoughts?

**Comment by zizango123** [comment]
when a sales is deleted the item quantity as well as the amount should be reinstated. Sales delete is necessary in case of wrong sales either in quantity or amount tendered since reedit of the entire sales is not possible.

**Comment by daN4cat** [comment]
What we do in my wife shop is to return the wrong sale (just scan the receipt barcode), add a comment and issue a new sale. In this way everything is logged.

**Comment by osworx** [comment]
No, a sale is not allowed to delete - never!
What can be done is to create a credit item and a storno - both have to point to the sale (invoice number).
Therefore your locale fiscal department can follow the transactions.

**Comment by daN4cat** [comment]
Yes, that's what I thought that for fiscal reasons you don't want to do that.

So the delete sale feature should be an optional one, such an admin can disable it from the configuration.
But if delete sale is allowed, we need to understand whether we need to reinstate the counting of the stock.

**Comment by odiea** [comment]
You also have to know that deleting a sale in OSPOS will screw up the auto invoicing feature.

**Comment by daN4cat** [comment]
Maybe we should remove the delete button.

**Comment by zizango123** [comment]
instead of removing the delete button it would be much better if the deleted sales are hidden and a report about the deleted sales be added.

**Comment by zizango123** [comment]
instead of removing the delete button it would be much better if the deleted sales are hidden and a report about the deleted sales be added.

**Comment by zizango123** [comment]
instead of removing the delete button it would be much better if the deleted sales are hidden and a report about the deleted sales be added.

**Comment by daN4cat** [comment]
So, add a delete field in the table and hide, not delete-delete. But this feature needs to be configurable as not all the countries are the same. So if delete of sale is not allowed delete features needs to be disabled from admin config.

**Comment by jekkos** [comment]
You mean like adding the deleted flag in the sales table? And filtering on query?

**Comment by daN4cat** [comment]
don't tell me have already.... I'm going by memory at the moment...

**Comment by odiea** [comment]
The only place we have this is in items. Adding a deleted flag should also not wreck the Invoicing.

**Comment by daN4cat** [comment]
Yes, that was the idea. However hiding an invoice is nowhere in the world possible/good idea.

**Comment by odiea** [comment]
Yes I agree with you. Maybe add a new mode for sales editing based on the pos number that really updates the Sale in question.

**Comment by daN4cat** [comment]
I close this because I created an issue to remove Sale delete option completely.
