### ISSUE TITLE
add new payment method

### ISSUE THREAD

**Issue by walterhumphreys** [jekkos/opensourcepos#371]
hi guys im trying to add a new payment method but i cant find array or the template where this is located

**Comment by odiea** [comment]
application\controllers\sales.php  look for 	private function _reload($data=array())
look around line 740. You will need to add this new payment method to sales language and then place your new payment method like the one I am showing. $this->lang->line('sales_cash') => $this->lang->line('sales_cash'),

**Comment by walterhumphreys** [comment]
Ok thanks i found it. Basically what i want to accomplish is add custom payment then when is selected it function as some credit payment example i select customer mark i select custom payment total 200 and i set he paid 100 so when sales is completw it shows all item and 100 as paid bill

**Comment by odiea** [comment]
Currently there is not a way to add partial payments. see #24

**Comment by walterhumphreys** [comment]
ok i see, what im trying to do is simply learn more about this software for example is  amout due is not equal to amount tendered complete sale wont go throu, now im searching for the template that contains these parametors because i will like add 
for payment metod = custom payment
if amount due <= amount tendered
complete sales,

basically that is what i want to do to see first how the system will react, now i need to set the correct script,

then i need to send an alert with client with comments as well for example
if customer has comment output " customer has comment" this what looking foward to do, then add this to register.php with javascript

**Comment by walterhumphreys** [comment]
i see 2.4 im sure it will be something marvelous, thanks

**Comment by daN4cat** [comment]
I believe this is already covered by #24.

**Comment by pedrojsaba** [comment]
I'm interested in this, could you share it with me? We could coordinate some cost

**Comment by daN4cat** [comment]
@pedrojsaba credit payment (due) is already in 3.1. Is that what you need?

**Comment by pedrojsaba** [comment]
after git clone version 3.1, I give this message:
Your system folder path does not appear to be set correctly. Please open the following file and correct this: index.php

**Comment by pedrojsaba** [comment]
After install bower and composer, I can't download publid/dist folder. Please help me to use this version

**Comment by daN4cat** [comment]
Run bin/devinstall.sh

**Comment by pedrojsaba** [comment]
But to Windows, What file run?

**Comment by daN4cat** [comment]
No windows but you can read the script to understand what it does. You can skip the gendocs part, you don't need it.

**Comment by pedrojsaba** [comment]
I can execute commands manually, but not download folder dist.

npm install --only=dev
composer install
php bin/install.php translations develop
bower install

2017-08-24 15:02 GMT-05:00 FrancescoUK <notifications@github.com>:

**Comment by pedrojsaba** [comment]
Finally, I was able to raise the web but I have this error that I have already reported before but there is a clear solution, I have all the files without any mood.
https://github.com/jekkos/opensourcepos/issues/887 - Same Error

**Comment by daN4cat** [comment]
Check php extensions

**Comment by pedrojsaba** [comment]
I had to give up using this development, enabled everything needed and that comes with php still not working

**Comment by odiea** [comment]
Download the stable release from the readme. This will let you know if the php extensions are enabled.

**Comment by pedrojsaba** [comment]
Please share the link. I do not want to download the wrong version.

Thanks.

2017-09-25 12:20 GMT-05:00 odiea <notifications@github.com>:

**Comment by odiea** [comment]
https://github.com/opensourcepos/opensourcepos/releases  3.1.1 is the current stable release.

**Comment by odiea** [comment]
https://github.com/opensourcepos/opensourcepos/releases/download/3.1.1/opensourcepos.20170909085348.3.1.1.76a002.zip

**Comment by odiea** [comment]
All you should have to do is unzip it place it in your directory and update the database config file then see what happens.

**Comment by pedrojsaba** [comment]
This version no have credit sale, or how use this option?

2017-09-25 12:32 GMT-05:00 odiea <notifications@github.com>:

**Comment by odiea** [comment]
Currently no version has a credit sale.

**Comment by pedrojsaba** [comment]
and which version could I use?

2017-09-25 14:38 GMT-05:00 odiea <notifications@github.com>:

**Comment by odiea** [comment]
You can use any version you want but none have credit sales. My last answer to this question.

**Comment by pedrojsaba** [comment]
ok, no problem, thanks !

2017-09-25 14:54 GMT-05:00 odiea <notifications@github.com>:

**Comment by daN4cat** [comment]
@odiea there is due payment that equals to a credit sale.

**Comment by pedrojsaba** [comment]
Hi Francesco, exist a release stable? The version 3.0 run perfect, but 3.1
no work for me.



El 25 sept. 2017 3:01 p. m., "FrancescoUK" <notifications@github.com>
escribió:

@odiea <https://github.com/odiea> there is due payment that equals to a
credit sale.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/opensourcepos/opensourcepos/issues/371#issuecomment-331995238>,
or mute the thread

**Comment by daN4cat** [comment]
3.1.1 works fine. Just use the bintray link @odiea provided and upgrade the database.
That contains the due payment.

**Comment by odiea** [comment]
@daN4cat Sorry That was just another can of worms I did not want to deal with. Thanks

**Comment by pedrojsaba** [comment]
Francesco, is exist due payment. how register payment parcialo or total?

2017-09-25 15:11 GMT-05:00 FrancescoUK <notifications@github.com>:

**Comment by naveen433** [comment]
Hi i am from India.. i am using this in my Coffee shop.. I want to add some custom payment type to the sale.. ex:- In india UPI is most using payment method.. and also some Wallets are working here.. How to add these Wallets to my payment type... any suggestions.. 

Where to tweak the code.. Please suggest.. 

Thanking You..

**Comment by mckaygerhard** [comment]
hi @naveen433 this is a rudimentary form of do that https://gitlab.com/osposweb/osposweb/commit/3ed7d4eff7aa8ec518ae26c26d5a6729030b2800 for more see the brand cxcteipado of same repo

**Comment by naveen433** [comment]
sorry I didn't get you ... dude.. just adding a phrase to payment types..
now we have cash, credit card, Debit card, due, check and giftcard.. now i
want to add one e-wallet or UPI.. How is it possible?..

**Comment by SteveIreland** [comment]
I added UPI to the india-gst branch.  You can look at that for an example.  There are two possible places to add it.  I chose .../helpers/locale_helper.php since I was conditioning the display based on finding India in the country code list.

The other appropriate place is in .../models/Sale.php in the get_payment_options method.

**Comment by naveen433** [comment]
i had download from git and made some changes.. then i try to install.. but
there is no databse.sql file.. i observed previous version database.sql
file it has this warning This file is autogenerated from tables.sql and
constraints.sql. Do not modify directly...

How do i generate database.sql file..

Thanking you
Naveen

**Comment by SteveIreland** [comment]
Please do not add a request to an unrelated open ticket.  Please open a new request following the guidelines.  You haven't provided anywhere near the information needed to provide any assistance.

There is plenty of documentation on the wiki regarding the installing the development branch.  For example, if you are doing a raw installation onto a Windows platform you can use https://github.com/opensourcepos/opensourcepos/wiki/Installing-%22opensourcepos%22-in-windows-and-localhost

If it's too complex then you will be better off using a published release which has already been built.
