### ISSUE TITLE
Removal of Company Logo

### ISSUE THREAD

**Issue by odiea** [jekkos/opensourcepos#372]
It would be great to have a way to remove the Company Logo after it has been uploaded.

**Comment by jekkos** [comment]
I saw there's a delete button but I suppose that it's not working at this moment?

**Comment by daN4cat** [comment]
Delete button appears when you change. But it reverts to the original.
Maybe the plugin has the feature to show the delete button even before.
Don't know I will need to check.

**Comment by jekkos** [comment]
I've fixed this issue. Problem was that the saved image wasn't loaded in the correct node.

**Comment by daN4cat** [comment]
Oh good, thanks a lot. Saved on one from my todo list :+1:

**Comment by daN4cat** [comment]
I can apply the same to items/form and change to the picture loader instead of file.
The code was there just commented out.

**Comment by jekkos** [comment]
The extension is added back again using a globbing operator. So it's php that will resolve the file extension in the end. Will see if I can fix that issue.

**Comment by jekkos** [comment]
Think I got this fixed. Will commit later today. Next thing will be styles and then I'll start to work on tables I suppose.

**Comment by daN4cat** [comment]
The code in Items/form is ready but just commented out. There is just the extension bit to be sorted as for a test it was fixed to .png. Also the remove button feature needs to be added, of course.

**Comment by daN4cat** [comment]
Before moving to tables we need to run a check of what's left out. For sure the styling of the autocomplete search needs to be sorted.
There was this last jQuery issue, but moving to bootstrap-tables will get rid of that.

I'll check all the issues later and see if anything left. On my side after sales/register I need to sort out receiving. Let see if I can get that kicked out this week-end.
