### ISSUE TITLE
Item avatar images not being uploaded in 2.4 version

### ISSUE THREAD

**Issue by ais-one** [jekkos/opensourcepos#373]
From #364 

I am trying avatar upload on items, its not uploading, I am trying to find out why. If anyone has it working out of the box, please let me know.

in form.php

I changed

`<input type="file" id="item_image">`

To

`<input type="file" id="item_image" name="item_image">`

Looking at the result of the controller for items.php

```
    function _handle_image_upload()
    {
        var_dump($_POST);
```

I do not see **item_image**

Looking at the function save()

```
function save($item_id=-1)
{
    $upload_success = $this->_handle_image_upload();
    $upload_data = $this->upload->data();
    var_dump($upload_success);
    var_dump($upload_data);
```

$upload_success is true
but
$upload_data has nothing, no file name, etc.

**Comment by jekkos** [comment]
You should check if there's any difference in the code between 2.4 and 2.3.5. Also are you using bootstrap branch or plain develop/2.4?

**Comment by ais-one** [comment]
Using bootstrap UI branch.

Even if I use the code from 2.3.4 and check the html output produced, both seem ok. I am scratching my head on this also and investigating further, the name="item_image" was missing in bootstrap UI, but even after I add it, there was no effect.

I am also troubleshooting this on and off in my spare time to see what went wrong. You can put this as low priority if you want, I can do the investigation on my side.

**Comment by jekkos** [comment]
The field name was vital to make the upload functionality work. On the other hand the breakage might also be due to the CI3 upgrade. Maybe check their documentation on the upload functionlality, some of it might have changed.

**Comment by jekkos** [comment]
On the other hand, the same setup is used in the config for the company logo upload. Maybe compare the differences between these two to find what is wrong?

**Comment by daN4cat** [comment]
Yes, company logo solution should replace items form one. Time permitting

**Comment by ais-one** [comment]
There is a difference in submission between the views

    items\form.php
    configs\general_config.php

could it be multi-part issue? need to dig further to find out.




I think the following link explains it, let me see if it can be fixed...

http://stackoverflow.com/questions/17718445/jquery-ajax-send-form-with-input-type-file-and-json

**Comment by ais-one** [comment]
Confirm that the problem is the ajax, I have tested a fix will branch and create a pull request, this is fot BootstrapUI

**Comment by ais-one** [comment]
Pull request submitted below.

Also there is a problem with the latest UI, item can never be created or updated because the **supplier** dropdown field cannot use the default 'None'. I have removed the required in the class of the input and now it works, I will create an issue and submit a pull request for it also.

[https://github.com/jekkos/opensourcepos/pull/376](url)

**Comment by daN4cat** [comment]
Good catch with the Ajax fix. I'll try it later and enable the image loader in the form as I added last night but left it commented out.

**Comment by daN4cat** [comment]
I tested and the fix works fine.

**Comment by daN4cat** [comment]
Merged in bootstrapUI brach,
