### ISSUE TITLE
add discount % option to customer

### ISSUE THREAD

**Issue by walterhumphreys** [jekkos/opensourcepos#375]
hi guys i´m trying to add this feature the a customer that i will start giving 10% disc, i tried adding it in form_basic_php for it to appear when adding/ edit customer but i get Message: Undefined property: stdClass::$discount Filename: people/form_basic_info.php.

where will i need to add or modify to accomplish this the coding i will do it, but which are the files i need to modify?

**Comment by ais-one** [comment]
I am now checking the submit javascript in the Items form... cant see the file input fields name...

**Comment by daN4cat** [comment]
bootstrapUI branch: check the manage_tables.js, bottom of the file

**Comment by ais-one** [comment]
There is a difference in submission between the views
- items\form.php
- configs\general_config.php

could it be multi-part issue? need to dig further to find out.

**Comment by ais-one** [comment]
I think the following link explains it, let me see if it can be fixed...

[http://stackoverflow.com/questions/17718445/jquery-ajax-send-form-with-input-type-file-and-json](url)

**Comment by ais-one** [comment]
sorry commented on wrong thread. sorry for the confusion...

**Comment by ais-one** [comment]
Most likely you need to touch the following files below:

- views/customers/form.php (for add / edit)
- controllers/Customers.php
- models/Customer.php

I assumed you added the discount field to the ospos_customer table in the database

Note, the views/people/form_basic_info.php is a view shared by both customer and employees so it displays info from the common table used by both customers and employees - ospos_people.

Your discount should not appear on the view of form_basic_info.php unless you need to make some major changes to the code.

A workaround may be to use another crud system to view and edit customer info :) especially if customer information is customized...

I had customized it to include photo ID upload and some other fields, the management and usage of customer data, I used another CRUD application as I did not want to have too may changes to code base of ospos. I also created a seperate customer registration system.

You just need to understand the following tables:
- ospos_people (auto ID generated here)
- ospos_customer
- ospos_employee

**Comment by ais-one** [comment]
Basically, I understand you are trying to add a feature not in current implementation.

I am also constantly thinking how to either:
- accomodate customization (more flexible but people need to know how customization is done).
- make feature as part of platform (increase bloat, but  useful if it is commonly used).

But need to ensure that:
- as little of the core system is affected.
- not to add additional complication.

Constantly thinking about this, but one way to make everything play nice is to understand the workings of the data, and write/use something else to do what you need to do.

BTW, that per customer discount is going to have impact of sales, cancellation, refund process. So more tables may be affected...

**Comment by daN4cat** [comment]
I have custom things as well, or thought to have ones. But discussing issues and features here I found that in the end those are needed.
So I would always start suggesting the addition and if no negative comments add it to the base Palos for everybody and to even reduce the cost of maintaining and merging things in the future.

I have now an old version of phppos with functionality that it's impossible to merge across with the latest. I prefer reimplement it with the new.

**Comment by walterhumphreys** [comment]
I see what you are saying well i didn't took all what you mentioned in consideration. All i need is to add discount to loyal customer. The gift card is good to me so Mayne the best is add a custom card that instead contain an random amount of money it be a % and I simply relate the card with the customer

**Comment by walterhumphreys** [comment]
I'm also will take a look into what you mention because besides adding % discount to a customer I will like to add more customizations guessing it will take me a good while. CRUD sounds as good choice as well. Cause my biggest goal is partial payments for customers even tho is of the topic jejej

**Comment by ais-one** [comment]
@all

You can look up this thing called lazy mofo datagrid, pretty flexible, you can create a customised entry form if you know what you are doing, other than CRUD.

I have extended the project in github to use Bootstrap, and also include data entry such as photo input, signature input, select2, etc.

**Comment by walterhumphreys** [comment]
I see i will read about it as well .. i added bootrap. Font awesome and few libraries more to pos system so i can use for what i need. Now with theinfo you gave its time.to code. Thanks i really appreciate it

**Comment by daN4cat** [comment]
Customer discount it's something I will most likely add.

Bootstrap is what we are currently doing, if you have done work for that please contribute and let's try to reduce the difference having a common part. In this way we can focus on adding new features more useful.

**Comment by walterhumphreys** [comment]
You guys have a release date for the new version. I added bootsrap framework only so i can use it for front-end purposes. I dont know if the way i did it is exactly what you guys are looking for i used cdn links . If this still useful to you im more than happy to contribute just let me know how

**Comment by ais-one** [comment]
I will make a request to split out the javascript components such as Jquery and sizzlejs.

**Comment by daN4cat** [comment]
The release date is when it's done. The more help the quickest to get it completed. I also upgraded it to CI3.0.4 before Bootstrap, so there are two big steps in it, well three since @jekkos upgraded jQuery vs and he's working on getting the legacy sorted.

**Comment by daN4cat** [comment]
WRT CDN, maybe we can add an option in config to use that or local.
There is no CDN at the moment because some people are using it locally (e.g. development setup)

**Comment by walterhumphreys** [comment]
I added all i needed jquery , bootsrap and few more but now as you said ot will only work for those that are not local. I will take a look into this to see how to contribute i added all files inlcuding custom css sheets, all in the header.php and i have no issues at all everything respond perfect. But maybe what im thinking now is install the library/plugins etx in pos somewhere then call it in the header as well . Theoretically it should work. I will give it a try and let you know if it works. This will be for those local the other with the can links it should be enough

**Comment by daN4cat** [comment]
Please check bower and grunt scripting in ospos since a lot is done automatically.
You can install a plug in from github with bower and grunt will generate everything for you.

Before starting something new leverage that support.  CDN of course is still not in the picture but can be added to the scripts.

**Comment by ais-one** [comment]
I am available to help, whether investigating issues, fixing bugs or implementing new features, or thinking how to make things better.

**Comment by ais-one** [comment]
Ok I will look into those issues later today

**Comment by daN4cat** [comment]
Added the discount % to customers.

See Customer form (new or edit customer) and it's used in the register when a customer is selected.

**Comment by daN4cat** [comment]
Fixed a typo in tables.sql that was affecting database.sql, MySQL DB creation script.
