### ISSUE TITLE
Call Sale method in Controller Sale.php

### ISSUE THREAD

**Issue by hoangtu406** [jekkos/opensourcepos#379]
In Sales Register screen, I create a button Order Offline, I also have an **Sale order Array**.
I create new method **process_Order_offline()** in controller\sales.php ( I follow Complete button process that used path **sales/complete** ) 
Could anyone suggest for me a way to transfer** Sales Order Array ** to method  **process_Order_offline**

**Comment by daN4cat** [comment]
What is the use case behind Order Offline?

**Comment by daN4cat** [comment]
Any update?

If no answers by end of tomorrow I'll close this issue.
