### ISSUE TITLE
Sales add item auto complete issue

### ISSUE THREAD

**Issue by kagarwala** [jekkos/opensourcepos#38]
1. If you do a blank search, it shows up each item twice...If you enter some character then it shows correctly...

2. When you select an item, it shows up the id in the input field..It should show the name instead...

**Comment by jekkos** [comment]
1. Just did a quick test on this and indeed, items do show up twice. Not sure yet how to fix that but this probably doesn't break any functionality so not really a high priority issue I suppose.

2. This is currently a restriction on how the autocomplete jQuery plugin works. The request works in two steps. Firstly the suggestions are parsed from the server. Secondly you will need to submit the correct product id to get a unique result. This is how it's done currently across the applications. Nevertheless the automplete jQuery version is an outdated one and should be upgraded for the whole application.

**Comment by kagarwala** [comment]
1. I haven't set up a dev environment yet, but by looking at the code it seems...While doing a blank search we look for item id and item kit id and then merge the results...That's why the products are added twice...I will confirm it myself once I have debugged it properly...

2.This will be really great if you can upgrade the plugins in any later version...Regarding the issue...I was able to fix it...Use a hidden input field to pass along the itemid to the server...I tested it myself...
But it broke the return functionality, which I think is fixed in  a later version...I will just paste the the changes here...

$("#item").autocomplete('<?php echo site_url("sales/item_search"); ?>',
    {
    	minChars:0,
    	max:100,
    	selectFirst: false,
       	delay:10,
    	formatItem: function(row) {
			return row[1];
		},
		formatResult:function(row){
			return row[1];
		}
    }).result(function(event, data, formatted)
    {
	debugger;
	$("input[name=itemid]:hidden").val(data[0]);
		$("#add_item_form").submit();
    });

**Comment by jekkos** [comment]
indeed you can probably circumvent this issue by posting a hidden field with the chosen item id back to the server. Also duplicate search results might be caused by items being matched on different attributes. For example if both name and description contain the search string then the result might be present twice. Maybe we should use the item id as an index in the result array to avoid this.

**Comment by kagarwala** [comment]
Yes I will debug it...
Can you tell me from where I should download the Stable latest version...??? Because on sourceforge when I download I am still getting an older 2.2 version...

Should I take it from Github...??? Isn't the version in Github in active developemnt?

**Comment by kagarwala** [comment]
Never mind found the latest version on Giihub

**Comment by jekkos** [comment]
I rolled a fix for these issues. The duplicated suggestion was due to the reactivation of a query on the custom search (I removed that again). The other 'bug' was actually a new feature which should work now as well.
