### ISSUE TITLE
Separate jquery, sizzlejs and other libraries from opensourcepos.js

### ISSUE THREAD

**Issue by ais-one** [jekkos/opensourcepos#380]
I was wondering if the above could be done, either that or have a build system to combine the JS files into the dist folder because I do not see the sizzlejs or jquery in the js folder.

**Comment by daN4cat** [comment]
It's done with bower and grunt. Check the scripts in the root dir. Maybe we should add more to the wiki to explain how things work.

**Comment by daN4cat** [comment]
Also to debug js singularly not using min.js you need to add ?debug=true to the URL.

**Comment by daN4cat** [comment]
You get that if you check views/partial/header.php

**Comment by daN4cat** [comment]
BTW, where do you use sizzlejs?

**Comment by ais-one** [comment]
I saw sizzlejs in the opensourcepos.js file.

**Comment by daN4cat** [comment]
Ok, I need to check as I never paid attention to it.

**Comment by daN4cat** [comment]
Not sure what we need to do here because there is already bower & grunt scripting working.

I would close.
