### ISSUE TITLE
how to add time on sales report

### ISSUE THREAD

**Issue by walterhumphreys** [jekkos/opensourcepos#384]
im currently trying to add time beside the detailed sales report, but i just dont find the file i need to add this to,  date("h:i:sa"); at the timestamp

**Comment by daN4cat** [comment]
Is this related to the custom expire time field? What is that you need to do? Print out a time only or else? If printout you may want to consider the date and time format from config. The format you store in your field is up to you. If just a date I would reuse the standard one used to store anything time based in OSPOS. So you are consistent and you just copy and paste any code having already the conversion to your locale set date and time.

**Comment by walterhumphreys** [comment]
Nop that was something i needed at the moment but then i realized it was there already. The date picker it was to make it a lil fancy jeje but useful as well i added it on a custom field i added a class to the array and change a lil bit the php that is in items/ form.php then created a report so i can know which medication is expiring within certain time frame.. now i made it different than the other reports cause i'm still trying how to make it.. so i used mysql insted created a new templete and add all my codes there. Now i'm looking forward to create permissions.

**Comment by daN4cat** [comment]
OK, I close this then.
