### ISSUE TITLE
set datepicker in a custom field

### ISSUE THREAD

**Issue by walterhumphreys** [jekkos/opensourcepos#385]
hi guys i need to set expire date on items, for example i can set expire date on custom3 field, but i need to use datepicker as the input, this is my html and script

 <input type="date" id="datepicker" name='from' size='9' value="" />

 $(function()
                {
                         $( "#datepicker" ).datepicker();
                         $("#icon").click(function() { $("#datepicker").datepicker( "show" );})
                 });

because in the end i will need to create a new report that can generate expire dates by range, but first i need to add custom field datepicker input, which will be the file that i need to edit to accomplish this,

**Comment by walterhumphreys** [comment]
searching i found this
<?php for ($i = 0; $i < 11; $i++) 
{ 
?>
	<?php
	if($this->config->item('custom'.$i.'_name') != NULL)
	{
		$item_arr = (array)$item_info;
		?>
		<div class="field_row clearfix">
			<?php 	
			echo form_label($this->config->item('custom'.$i.'_name').':', 'custom'.$i,array('class'=>'wide')); ?>
			<div class='form_field'>
				<?php echo form_input(array(
					'name'=>'custom'.$i,
					'id'=>'custom'.$i,
					'value'=>$item_arr['custom'.$i])
				);?>
			</div>
		</div>
		<?php 
	}
}
?>

which tells me i need to change the input from text to date, but how i accomplish this to certain custom field only

**Comment by daN4cat** [comment]
What is the purpose of setting a custom field with a time? The expire date perhaps?

I believe we need a generic way to add fields for several purposes, like this idea #68

**Comment by walterhumphreys** [comment]
Yes it was exactly for expired date since is a drugstore im using it on i got it already. In a very manual way thou. Which is bad for me when a new update is available. I red the #173 and it seems like a nice feature but i also believe that all business will have differents requirements. So this has to be modify and personalize for each business as to my personal opinion this is one of the best open source i've ever use i have a few months with it and keep modifying.. at the beggining it was hard to me... CI was new to me now im getting use to it

**Comment by daN4cat** [comment]
The best approach would be to define the extra field name, type and unit. Then show it in Items, sales, reports and etc.
There are many examples where we would need such thing. For my wife's case we need size, colour, season. She has a fashion boutique. Others need weight, or tag colour for item condition, or as your case an expiry date or a location of the item in big drawers.

**Comment by daN4cat** [comment]
Yes, it takes some time to understand how it works but once you get it you can add what you need or change it. However things grew up in different ways with time and with the work on the bootstrap upgrade we are tidying up things and understand what we really need to improve it.

**Comment by walterhumphreys** [comment]
I imagine,  well in my case thanks for 10 custom fields .. i modified the items php form.php and use certain customs fields.. i will be looking forward for create dynamic reports and my biggest challenge partial payments im still wondering which are the templates i need to modify and if the database must be alter as well... im not local so i installed bootstarp and couple jquery and java libraries for maketing things easier for my self

**Comment by walterhumphreys** [comment]
I imagine,  well in my case thanks for 10 custom fields .. i modified the items php form.php and use certain customs fields.. i will be looking forward for create dynamic reports and my biggest challenge partial payments im still wondering which are the templates i need to modify and if the database must be alter as well... im not local so i installed bootstarp and couple jquery and java libraries for maketing things easier for my self

**Comment by daN4cat** [comment]
What do you mean with "I'm not local"?

**Comment by walterhumphreys** [comment]
I meant that i'm using internet connection with my server. I'm not running a xamp for example and keeping it on my local pc. I added i scripts and libraries in header.php

**Comment by daN4cat** [comment]
Yep, the same as mine and everything works fine.

**Comment by daN4cat** [comment]
#68 covers the issue in a more generic way.

**Comment by daN4cat** [comment]
Close to keep just #68 open as this is just a use case.

**Comment by WebShells** [comment]
@walterhumphreys , have you implemented partial payments ? if yes advise please... Thanks
