### ISSUE TITLE
Merge 2.4 branch into master

### ISSUE THREAD

**Issue by daN4cat** [jekkos/opensourcepos#386]
As agreed 2.4 will replace 2.3.5 and be the follow up of 2.3.4.

This is to merge 2.4 branch into master and close 2.4 branch.

**Comment by daN4cat** [comment]
I rebased develop/2.4 of master in my local and then pushed 2.4 to master.

Now up for the testing time.

**Comment by jekkos** [comment]
Ok. Thanks for taking care of this. Will try to do some testing maybe tomorrow.

**Comment by daN4cat** [comment]
Survival kit to the migration:

- make sure the database is configured to be mysqli
- generate an encryption key for the session, use: http://randomkeygen.com/ (you get a code igniter one in one of the boxes)
- run upgrade MySQL script database/2.3.4_to_2.4.sql

**Comment by odiea** [comment]
Ok so do you want me to test the new Master or the old develop/2.4

**Comment by daN4cat** [comment]
master (now 2.4)

**Comment by odiea** [comment]
I downloaded and used my current 2.4 database.
Items search broken in all modules. No drop down suggestions.
Success message in Items and Customer are showing in the upper left corner.
Changing locations search spinner just continues to run.
Lots of search box issues in all modules.
Cannot add an item kit. No search results.
Sales register showing no search suggestions but can find an item number.
After changing  anything in store config. Success message ok but you have to exit out of Store config and then reenter to make any other changes. Submit button dead until you renenter.
Most search features are broken. Not showing expected results.

**Comment by jekkos** [comment]
Did you do a force refresh in browser?

**Comment by odiea** [comment]
Yes I did f5 and ctrl f5 with no change.

**Comment by jekkos** [comment]
maybe ctrl-shift-f5

**Comment by daN4cat** [comment]
nah, I suspect is the usual post issue in CI3... let me check beause I have the same issue.

**Comment by odiea** [comment]
I have tried it in 3 different browsers and get the same issues.

**Comment by daN4cat** [comment]
it doesn't seem so trivial. I merged in master what was develop/2.4 on top of all the rebase and there is nothing special that popped up. Just a database.sql file had an issue with the session table not up to date,

**Comment by daN4cat** [comment]
And everything works on 3.0 (bootstrap... :-( what went wrong on develop/2.4?)

**Comment by daN4cat** [comment]
latest master fixes the issue, I enabled in config.php the Cross Site Request Forgery protection and that was causing the issue. It was blocking any POST so the search suggestion couldn't work.

**Comment by odiea** [comment]
I just tried it and it works great The only issue so far is in Takings - Edit - Submit lower screen shows Internal Error and the screen stays the same so you have to manually close the window..

**Comment by daN4cat** [comment]
ok, checking...

**Comment by daN4cat** [comment]
yep, issue with the customer field... this is something I fixed in 3.0.0

**Comment by daN4cat** [comment]
wrong, it's with the invoice field...

**Comment by daN4cat** [comment]
fixed, it was an issue with the save in Sales, post('invoice_number')

**Comment by odiea** [comment]
That was it. Have a good evening. Gotta give my grandkids computer time now.

**Comment by odiea** [comment]
I will play with it some more tonight to see if anything else breaks. I doubt it will.

**Comment by jekkos** [comment]
So develop/2.4 is merged in master now. I have removed it from this public repo now.

**Comment by daN4cat** [comment]
Yes, develop/2.4 is not needed anymore. It's all in master and I rebased everything of master before submitting it. I just did a final merge to spot a minor diff in the database scheme but all should be fine and just waiting for testing feedback and 2.4 features/issues to be closed.

**Comment by daN4cat** [comment]
We leave this open just for minor defects for few days. Then if no reports I'll close it.

**Comment by odiea** [comment]
The only issues I find so far are in Takings. Invoice filter doesn't work. I can enter a pos number that I see  on the screen but it wont load that Sale. Suggestion shows and I click it and still nothing. Otherwise  I am not finding other issues anywhere.

**Comment by daN4cat** [comment]
Ok, I'll have a look when I finished with the sales register bootstrapisation.

**Comment by jekkos** [comment]
Ok I fixed that issue. Seemed to be a problem with the default form submit behavior. For some reason the enter key didn't trigger the submit and I've added an explicit search call on key enter event now.

**Comment by jekkos** [comment]
Could be a

**Comment by daN4cat** [comment]
Probably I fixed that in bootstrapUI branch version that I reworked last night.
There was something not closed on a table.

I'll see if I can spot again in 2.4 that problem.

**Comment by odiea** [comment]
Takings is working properly this morning.

**Comment by jekkos** [comment]
Ok might be better to fix this problem at the root and then remove the patch I did.

**Comment by jekkos** [comment]
I think it might be good to start sorting out what we can deliver in 2.4 as there's still more than 10 issues open for this version. I'll try to take some time to go through these one by one and see what can be done to finish up.

**Comment by daN4cat** [comment]
There is an issue with sales/register and receipt printing, you cannot go back with the browser because it will show an error. It used to work in 2.3.4. You could get to the receipt, print, and then doing back re-enter the sales/register.

**Comment by daN4cat** [comment]
Created issue #398 for the above, #394 is a suggested workaround.

I close this because the move to master seems fine. Any other issue should have a dedicated issue #.
