### ISSUE TITLE
500 error when completing sale

### ISSUE THREAD

**Issue by skylarmt** [jekkos/opensourcepos#387]
Clicking the "complete sale" button loads this page:
http://localhost/index.php/sales/complete
which is completely blank and sends a HTTP status of 500 (internal server error).
The inventory updates and the sale seems to go through, but going back to the regular sale page brings the transaction back up.

I cannot find anything in any logs about this.

Server version: Apache/2.4.12 (Ubuntu)
Server built:   Jul 24 2015 15:59:11

PHP 5.6.11-1ubuntu3.1 (cli) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies

mysql  Ver 14.14 Distrib 5.6.28, for debian-linux-gnu (i686) using  EditLine wrapper

I installed the application on a clean Lubuntu 15.10 installation yesterday.

**Comment by daN4cat** [comment]
OSPOS version please

**Comment by skylarmt** [comment]
@daN4cat It's a clean install from yesterday, so 2.3.4.

**Comment by daN4cat** [comment]
Do you have any error_log in the root dir of ospos installation?

**Comment by jekkos** [comment]
Did you install php5-gd imaging library? on ubunut `sudo apt-get install php5-gd`

**Comment by skylarmt** [comment]
@daN4cat  No error_log.  @jekkos I'll try that and update this in a couple hours after I have time to try.

**Comment by jekkos** [comment]
If this is really the solution then maybe we should add this instruction to the project's readme :)

**Comment by skylarmt** [comment]
It seems I needed to install the php5-gd package.  It's all working now!
