### ISSUE TITLE
Autocomplete for data array does not work  as for link

### ISSUE THREAD

**Issue by hoangtu406** [jekkos/opensourcepos#388]
Could some one tell me why autocomplete not search letter in a whole string, it only start with begin of string.
That is original search in sales register. It worked perfectly:
```
 $("#item").autocomplete('<?php echo site_url("sales/item_search"); ?>',
    {
    	minChars:0,
    	max:100,
    	selectFirst: false,
       	delay:10,
    	formatItem: function(row) {
			return (row.length > 1 && row[1]) || row[0];
		}
    });
```

But I tried to put an array data, the suggestion of search show match of first letter.
`var cars = ["Saab", "Volvo", "BMW","Toyota"];`

	$("#item").autocomplete(cars ,
		{
			minChars:0,
			max:100,
			selectFirst: false,
			delay:10,
			formatItem: function(row) {
				return (row.length > 1 && row[1]) || row[0];
			}
		}); 
Example: I type "o" on textbox, there is no result, but I type "s", the result show "Saab".
Did I lack something, please help me ?.

**Comment by daN4cat** [comment]
OSPOS version please

**Comment by hoangtu406** [comment]
Wow , wow,
I found the anwser, simply put : matchContains: true,

```
var cars = ["Saab", "Volvo", "BMW","Toyota"];

$("#item").autocomplete(cars ,
    {
        minChars:0,
        max:100,
        selectFirst: false,
        delay:10,
   **     matchContains: true,**
        formatItem: function(row) {
            return (row.length > 1 && row[1]) || row[0];
        }
    }); 

```

**Comment by daN4cat** [comment]
Please note that with 3.0 (Bootstrap) autocomplete changed to the standard jQueryUI one.
The vs up to 2.4 is old, so when upgrading to 3.0 you would need to check that option again.

**Comment by jekkos** [comment]
Yes this is referring to the old plugin. It's hard to find the right documentation for this (you probably won't) and only way to understand it is to read the source (that's what I did in the end).
