### ISSUE TITLE
OSPOS coding style

### ISSUE THREAD

**Issue by daN4cat** [jekkos/opensourcepos#389]
Since between editing of the code stuff gets adjusted, moved, shifted back and forth (and I'm part of it, I cannot call myself out), I was wondering if we could agree on a coding style guideline and do a change to adhere to it.

CI3 has coding style guideline: http://www.codeigniter.com/user_guide/general/styleguide.html

Shall we follow that?

**Comment by jekkos** [comment]
Yes I meant to introduce style guid some time earlier as well. We could perhaps enforce by using some tooling in the automated build that will run after pull requests (jslint, phplint eg)

but more important is define a set of rules we'd like to stick to and after discussion summarize in the wiki.

**Comment by daN4cat** [comment]
That's what I meant to do, shall we use those CI3 style guidelines?

**Comment by jekkos** [comment]
Yes we might use that as a reference. Might be good to see whether they have set up any tooling to enforce this styleguide on the codebase.

**Comment by daN4cat** [comment]
Yep, that would be a good idea.

BTW, we will do this only on 3.0 otherwise the merge 2.4 to 3.0 would be a pain.

**Comment by daN4cat** [comment]
Some of the code style guidelines where implemented. I believe we can close this one.
