### ISSUE TITLE
Add custom code to open cash drawer

### ISSUE THREAD

**Issue by skylarmt** [jekkos/opensourcepos#390]
Basically, I need to be able to run some custom code when a sale completes, in order to open a cash drawer.

Where exactly should I put my code (probably an exec()) so this works?

I know PHP and perused the code a bit, but this project isn't exactly in my job description so I don't have time to get familiar with the codebase.

**Comment by daN4cat** [comment]
Usually you command the cash drawer opening from the receipt printer. At the end of the print the printer sends an electrical pulse to open the drawer. This option can be set from the receipt printer driver.

**Comment by skylarmt** [comment]
I know, but the receipt printer is fubar.  It's easier to use an Arduino with the cash drawer.

**Comment by jekkos** [comment]
It's really not that hard. Complete() in sales handles sales completion. Just add your code in that method.

**Comment by skylarmt** [comment]
Just for future reference in case somebody finds this via Google, that's https://github.com/jekkos/opensourcepos/blob/master/application/controllers/Sales.php
