### ISSUE TITLE
Change "Open Source Point Of Sale" or "Open Source POS" to simply be "OSPOS"

### ISSUE THREAD

**Issue by daN4cat** [jekkos/opensourcepos#391]
It's easier for people to remember something short.

I would suggest to change all the places having the string in extended to simply be OSPOS, a quick and easy name to remember,

OSPOS users will simply use it as a label to know what they are talking about.

**Comment by jekkos** [comment]
I don't mind the fact that we stress that the software is open source by occasionally spelling the acronym out in full. If we just call it ospos all the way then people might lose awareness of the fact that this program is built as a labor of love and that it's contributors have spent countless hours to make it the way it is now.

**Comment by daN4cat** [comment]
My wife asked me once: what is open source? They just understand POS or make sense of a label like OSPOS.

**Comment by jekkos** [comment]
Good thing that the sentence makes people wonder and  google the term..

**Comment by daN4cat** [comment]
Nah, they don't Google for that. They Google for their work related stuff.

**Comment by daN4cat** [comment]
So what do we do with this? Keep it extended or short as acronym?

**Comment by jekkos** [comment]
I would like to keep it extended as it is currently. But we should choose where to use the acroym and where to use the fullout description. In this case using acornym in big is good. and having it spelled out in full in the footer as well.

**Comment by odiea** [comment]
On the navbar have you considered resizing and placing the logo there instead of OSPOS

**Comment by daN4cat** [comment]
Yep, that could be an option we may want to consider indeed.

**Comment by jekkos** [comment]
Yes a better logo would be best I think. I'm not really fond of the current one and neither have the motivation or skils to design a new one.

**Comment by daN4cat** [comment]
I sketched something, but I'll work on it a bit more. Maybe I can ask help from a friend.

**Comment by jekkos** [comment]
I found an interesting site that allows one to generate a logo for ospos. Might be good to try and see if there's something we like.
http://www.designmantic.com/logo-design/samples

**Comment by odiea** [comment]
There's so many to choose from.

**Comment by gzilla** [comment]
I call this project "OPOS" = open pos.
O is open.
เมื่อ 1 เม.ย. 2016 04:12 "jekkos" <notifications@github.com> เขียนว่า

**Comment by daN4cat** [comment]
OK, besides fixing some of the sentences to be short OSPOS here and there (however I left longer one on footers), I fixed some typos/mistakes (there was in one translation still PHP Point of Sale!).
I fixed some missing sentence in translations and removed some unused.

Last but not least, I changed the icon and favicon, see if you like.

**Comment by jekkos** [comment]
Icon is already better than the previous one. Did you get it from that website I suggested? I might want to take a further look if I find the time.

**Comment by daN4cat** [comment]
The website you suggested requires a fee. I had that icon from somewhere I don't know exactly. Added the name under.
