### ISSUE TITLE
After latest pull here is what the barcode looks like in Items and Item Kits

### ISSUE THREAD

**Issue by odiea** [jekkos/opensourcepos#392]
![2016-03-10 18_12_38-generate barcodes](https://cloud.githubusercontent.com/assets/10962177/13690216/e1614086-e6eb-11e5-82a0-7b8bd78db0de.png)

**Comment by odiea** [comment]
I increased the font size to 12 and now it displays properly.

**Comment by daN4cat** [comment]
Yes, I removed some strange tweaking with the font size in the code and you now need to config 12 in store config. So you set the real size.

**Comment by odiea** [comment]
An adjustable font size. Imagine that. Good work.
