### ISSUE TITLE
Please add another change.

### ISSUE THREAD

**Issue by odiea** [jekkos/opensourcepos#394]
I think now we need to add the print feature to the receipt and remove the print checkbox. The receipts can easily be enhanced  to print or return to Sales Register or Takings.

**Comment by odiea** [comment]
Here is the code I used in my receipt. It is mostly there except for the no-print for div.
![2016-03-11 15_47_27-c__xampp_htdocs_tabbed-dev_application_views_sales_receipt php - notepad](https://cloud.githubusercontent.com/assets/10962177/13717717/9de9d664-e7a0-11e5-9d90-7bfb7db47ba0.png)

**Comment by jekkos** [comment]
Ok so no more auto print in this case? At least we could move that option to config and if user disable he can still chose when or when not to print. 

btw github seems to have some new features that allows voting on issues

**Comment by odiea** [comment]
After I thought about it maybe both would be beneficial. The Auto print and if they forget to print then the option is still available when the receipt is shown.

**Comment by odiea** [comment]
I think what I like more is the option to return to where you were or where you want to go instead of pressing the back arrow.

**Comment by daN4cat** [comment]
Yes, some autoreturn would be a good idea after the print.

**Comment by daN4cat** [comment]
In my commit (only vs 3.0 bootstrapUI):

- added buttons to Print, Navigate to Sales or Takings (top right to be inline with the other pages) to receipt and invoice - not visible at printing time using the newly added .print_hide class
- adjusted invoice styling (removed fonts styling and increased bar)

Regenerated dist files which removed a double SWFObject js in min.js that was introduced due to my unclean setup.

**Comment by odiea** [comment]
Looks good. The only issue I have is it does not work with jsprint so you have to select the printer.

**Comment by daN4cat** [comment]
ah ok, it probably needs a check if jsprint. Let me look into that after I finished what I'm doing.

**Comment by odiea** [comment]
ok thanks.

**Comment by daN4cat** [comment]
OK, fixed the jsPrint but I cannot test it because I don't have Firefox installed here.

@odiea could you please test it with receipt, invoice and takings Print buttons and the receipt after a sale with the "print after sale" selected?

Thanks.

**Comment by daN4cat** [comment]
Strange, it should print from Takings no issue. Have you tried from IE? Might be a Firefox issue only. I would need to install browser and plugin to test it.

**Comment by daN4cat** [comment]
Probably is a printer selection story for the specific view?

**Comment by odiea** [comment]
IE and Chrome both show the print dialog box. If jsprint addon is disabled in Firefox it also shows the dialog box.

**Comment by daN4cat** [comment]
Takings printer with jsPrint sorted. Please config the printer in Store Config / receipts

**Comment by daN4cat** [comment]
Fixed an issue with printing of Takings when pagination links are present.

**Comment by daN4cat** [comment]
I think this can be closed now, if everything is fine. right?

Or do we want this in 2.4 too?

**Comment by daN4cat** [comment]
OK, I make #277 the 2.4. I mark this 3.0 and close.

**Comment by jekkos** [comment]
Should be working as well now in 2.4. Would be nice if someone could verify. Then only open issue will be bulk update.

**Comment by daN4cat** [comment]
I just added a comment to print button and then I test.

**Comment by odiea** [comment]
The Invoice still has issues. The item is an apple computer and it has a serial number.
![2016-03-18 12_00_20-christmas sweater store -- powered by os point of sale](https://cloud.githubusercontent.com/assets/10962177/13887463/694d2b20-ed01-11e5-9a55-f26530ae53aa.png)

**Comment by daN4cat** [comment]
@odiea wrong issue.... that's 405
