### ISSUE TITLE
feature/bootstrapUI Reports

### ISSUE THREAD

**Issue by odiea** [jekkos/opensourcepos#395]
I just tried reports and none of them appear to work on the default date. I retry the date and nothing. I try last 7 days and the rows show for that date plus other dates within the report range.

**Comment by daN4cat** [comment]
Yes, I can see. Needs a fix indeed.
Most likely is due to the time because Takings works fine.

**Comment by daN4cat** [comment]
Fixed in my last commit.

**Comment by odiea** [comment]
Yes. It works fine now.

**Comment by daN4cat** [comment]
:+1:
