### ISSUE TITLE
Change Due 	

### ISSUE THREAD

**Issue by dayano** [jekkos/opensourcepos#396]
hi guys

in the bootstrapui version
in sales ...add payment  all ok but  in the ticket dont apear  Change Due dont work 
only  appears $ 0

**Comment by dayano** [comment]
for example 
the total is $60
i pay with  $100

dont show  the change  -40  in the ticket

**Comment by daN4cat** [comment]
@dayano Please try again with the latest commit in features/bootstrapUI.

**Comment by dayano** [comment]
now It's ok

good job
