### ISSUE TITLE
try to make multi app config

### ISSUE THREAD

**Issue by arkgnan** [jekkos/opensourcepos#397]
hi, anyone can help me about ospos code? i try to make multi store in ospos. my first step is changing app_config table, i make key field as field name. after that all the settings changed. in view i found $this->config->item() to get value of previous app_config db. but i don't understand about it, I looked it up on controller, model, libraries, helper but not find any. can you help me understand that coding?
[ospos.zip](https://github.com/jekkos/opensourcepos/files/170271/ospos.zip)

**Comment by arkgnan** [comment]
i understand now, it set on hooks, load_config.php. the script is `$CI->config->set_item( $app_config->key, $app_config->value );`. and how about config->set_item( ) function? where it is set? @daN4cat can you teach me, please

**Comment by arkgnan** [comment]
sorry.. i'm lazyman, i didn't learn hook before. i know about config->item after read codeigniter documentation. in ospos if i want to load value of app_config based on branch_id, how do that? i create session of branch_id after login. i do it in same time when person_id session created. but branch_id session not show in load_config.php.

**Comment by jekkos** [comment]
check out #150 . If you're interested then drop me a line. I might want to integrate it a little sooner in that case.

**Comment by daN4cat** [comment]
In 3.1 please....

**Comment by arkgnan** [comment]
@daN4cat I apologize in advance, according to me, ospos is great program. I feel proud to be able to contribute and I think I can do that by understanding the program line by line.

**Comment by daN4cat** [comment]
@arkgnan no worries, your help is welcomed and appreciated. What I meant is ok for the feature but target 3.1. I believe we first need bootstrap sorted and then we move to New features. You can always start but you need to keep up with 3.0 changes to avoid too big deltas later.

**Comment by jekkos** [comment]
Please bundle in #150
