### ISSUE TITLE
Pushing the back button when in Sales/register (e.g. receipt) leads to error pages

### ISSUE THREAD

**Issue by daN4cat** [jekkos/opensourcepos#398]
Starting with 2.4, after having done some operations with Sales/register (applies to receivings as well), going back with the web browser prompts an error page.

Typical case is when you have the receipt (printed if required), there is no way to go back using the web browser back but the user is forced to press Sales again on the Navigation bar.

There is a workaround request in #394, but would be good to find a robust way to go back to the original page.
It seems that with 2.3.4 everything was fine.

**Comment by daN4cat** [comment]
Maybe adding a js to detect the back button and jump back to sale would do: http://stackoverflow.com/questions/6359327/detect-back-button-click-in-browser

**Comment by odiea** [comment]
@daN4cat  What issues do you have with this option being on the receipt? It doesn't show on the printed receipt and the receipt shows on the screen anyway. This way it's a multifunction receipt.

**Comment by daN4cat** [comment]
I don't think js is required, there is something not working right with the controller.

**Comment by daN4cat** [comment]
@odiea the problem is the user expects everything to be right. In the old phppos you go back and see what you have done. Now you cannot, probably for security reasons but we need to redirect things to a starting page. The controller loads the correct view but the URL stays the old, which is not right.

**Comment by odiea** [comment]
Ok Thanks. I guess when I finish a sale I don't want to see it again on the screen so I want to start with a new sale.

**Comment by daN4cat** [comment]
Indeed, that what should probably happen pushing back button. The user goes to sales/register.
Of course the buttons on the receipt can be added. I'll check into that later.

**Comment by daN4cat** [comment]
There is the workaround with the buttons in the receipt and invoices page.

I think the proper fix to this will be with #401 

Therefore I close this.
