### ISSUE TITLE
Return doesn't work 

### ISSUE THREAD

**Issue by kagarwala** [jekkos/opensourcepos#40]
Hi,
I made a sale. It generated the sale_id. I also added a customer.

1.While returning I typed the full sale_id - POS 1
it wasn't able to show the result in the auto-complete.

2. I searched with customer's name. It wasn't able to show anything.

This might be the reason - 
in auto-complete we format the result for row[1]...But from backend we only send the sale id or customer name. Following piece of code might be the issue...

	function get_search_suggestions($search,$limit=25)
	{
		$suggestions = array();
	
		if (!$this->sale_lib->is_valid_receipt($search)) {
			$this->db->distinct();
			$this->db->select('first_name, last_name, invoice_number, sale_time');
			$this->db->select("DATE_FORMAT( sale_time, '%d-%m-%Y' ) AS sale_date", FALSE);
			$this->db->select("sales.sale_id AS sale_id");
			$this->db->from('sales');
			$this->db->join('people', 'people.person_id = sales.customer_id', 'left');
			$this->db->where("( last_name LIKE '%" . $search . "%' OR ".
					"first_name LIKE '%" . $search . "%' OR " .
					"CONCAT( first_name, last_name ))");
			$this->db->order_by('last_name', "asc");
	
			foreach($this->db->get()->result_array() as $result)
			{
				$suggestions[]="POS ".$result[ 'sale_id' ].'|'.$result[ 'first_name' ].' '.$result[ 'last_name' ]; ///////////// changed to concatenate id
			}
	
		} else {
			$suggestions[]=$search.'|'.$search; ///////////changed to concatenate id
		}
		return $suggestions;
	}

Is this a bug...??? Or I am doing something wrong...I am not testing with barcode scanner...That's why I entered the full sale_id manually...

**Comment by jekkos** [comment]
I suppose it has always been that way. Returning sales is ought to be done with a barcode scanner, as the receipts have the POS sale_id identifier encoded in that barcode. The valid_receipt will only be true if you type in the full POS number. In that case you should get the autocomplete suggestion (probably just one in this case). Haven't got the time to test this now but can you confirm if it works this way?

**Comment by kagarwala** [comment]
I tested it without any of my changes with a new ospos code base.
I made my first sale. The sale_id which showed in receipt was, 'POS 1'

I pasted the same while returning..Auto-complete didn't show up...
There was a JS error too...

But if you just press enter or try to add the sale_id even though auto-complete didn't show up...It is able to add the sale in return...

I guess that's because add_item is working because we entered the complete and valid sale_id...

**Comment by jekkos** [comment]
I just tried to reproduce what you did here and indeed, no suggestion showing up. However from reading the code it looks like there should be at least one. I'll look into once I have my debugger running.

**Comment by kagarwala** [comment]
The code I posted above might fix this issue...I added this to master branch on github and it worked.

Can you please tell me, which branch is the stable one...master/feature ... I am new to Git...

Or should I just stick to a released 2.31 version...???

**Comment by jekkos** [comment]
master is the most current development branch. feature branch contains some modifications I plan to integrate sooner or later (unfinished work)

**Comment by jekkos** [comment]
I did a proper fix in 6faaec5 by changing the javascript parsing on the client side. This fix is better as it give the server more flexibility in what it can send back (we shouldn't require two fields all the time).
