### ISSUE TITLE
Error : Caught exception: You need to spcify a bigger width to properly display this barcode

### ISSUE THREAD

**Issue by diganto213** [jekkos/opensourcepos#400]
I am getting this when I submitting the Requisition in Receiving module. I have tried increasing the barcode width to 350 but no help. Not sure what else to check.

Expert suggestion please.

**Comment by daN4cat** [comment]
Version, exact test case to reproduce... Please

**Comment by diganto213** [comment]
Hi 

Version : 2.3.1
Barcode Conf : Code39, width:350, height: 30
Barcode Content : UPC/EAN

Let me know if you know more details

**Comment by daN4cat** [comment]
Oh man, we are at 2.4 in master. At least update to 2.3.4 first.

**Comment by jekkos** [comment]
Would be nice if we could force milestone selection when creating issues

**Comment by daN4cat** [comment]
Agree, we should check if something is available with GitHub in the sense of enforcing rules at issue submitting time.
