### ISSUE TITLE
database restore data not show up

### ISSUE THREAD

**Issue by dxchen90** [jekkos/opensourcepos#402]
Hi,

I have done a database backup and restore to to new site.
after the restore, the data is not showing up.
I went into old phpmyadmin to backup the _stock and restore the file _stock to new site.
The item name ,price all can view thru phpmyadmin but it not showing up on frontend.
May i know How to make it visible at frontend?
Any developer can lend me a hand? I have messed up the system..:(
Thank you

**Comment by daN4cat** [comment]
Version please?
Also, have you run any update script if you changed the version of ospos?

**Comment by dxchen90** [comment]
version 2.4
I was done update to latest branch today and made a backup from config.Then i was plan to update my item all together by download the _item database.After i done changing all the information on csv, i restore the csv file to _item. It successfully uploaded and show up in database, then i try to delete the old one since it already duplicate. I am not able to delete and it shown error. Then  i go to the frontend item menu, the item information remain the old one and surprisingly  it did not show the duplicate items which database phpmyadmin has show duplicates.
I don know how to fix this, hope you can help me..Thank you





On Wed, Mar 16, 2016 at 12:10 PM -0700, "FrancescoUK" <notifications@github.com> wrote:












Version please?

Also, have you run any update script if you changed the version of ospos?

**Comment by daN4cat** [comment]
Ok, probably I know what happened. You need to restore transactions too, not only items. Transactions table is used to check the date items were created, updated, sold and etc. So without that you can't see your Items.

Btw it's always better to take you database, make a copy and upgrade it with the provided scripts so you retain everything. However if you wanted to start from scratch with but retain your Items, you need to do what I said.

**Comment by dxchen90** [comment]
Alright, please guide what i need to do now.Do i need to restore transaction(sale) first? Means i restore the _sale database to new place first, them only restore _item? Because if i create new database and restore database.sql, i could not restore _item only after that, it shows error.

Sent from Outlook Mobile




On Wed, Mar 16, 2016 at 2:58 PM -0700, "FrancescoUK" <notifications@github.com> wrote:












Ok, probably I know what happened. You need to restore transactions too, not only items. Transactions table is used to check the date items were created, updated, sold and etc. So without that you can't see your Items.



Btw it's always better to take you database, make a copy and upgrade it with the provided scripts so you retain everything. However if you wanted to start from scratch with but retain your Items, you need to do what I said.

**Comment by daN4cat** [comment]
Do you restore the complete database. I got you did only Items table. When you restored the database have you run the update scripts?

**Comment by dxchen90** [comment]
Hi,

I done restore the database things. everything is there, i can search my product at frontend as well. But i couldn’t add new sales entry. it just can’t load the item at the sales pos, so i cannot key in any new sales. Any idea which part i miss out? Database upgraded to 2.4

**Comment by daN4cat** [comment]
OK guy, you are giving info in bit and pieces and this is not very productive.
What about write down exactly your scenario and what you see.
I cannot help in this "here and there" wholly way.

**Comment by dxchen90** [comment]
Hi,

After i restore database, Item is not load in sales register in Find/Scan Item OR Receip.

**Comment by daN4cat** [comment]
Have you tried typing number of your item and then enter?
Do you get something?
If yes, have you tried typing the name of your items and then enter?
Do you get something?

If it's yes and yes, so it's a suggestion issue. However I will check the code because it might be another post issue.

I understand that if you search that item from Items view it works fine, right?

**Comment by daN4cat** [comment]
Also, could you tell me your setup? Webserver is Linux or Windows, which server and which php version?

**Comment by daN4cat** [comment]
And the web browser you use.

**Comment by daN4cat** [comment]
@dxchen90 any update? If no answer by end of today I close.

**Comment by dxchen90** [comment]
Hi,sorry for late reply.

The issue is same as you mentioned.
On item, i can search by typing words and it has drop down.
On Sales, during key in new sales, product is not search while typing words. whereas it can detect by scanning barcode.

**Comment by daN4cat** [comment]
So it's a suggestion issue only.

**Comment by daN4cat** [comment]
Do you get the same issue on the customer search box?

I mean no suggestion but yes if you type name and enter?

**Comment by dxchen90** [comment]
Can you guide me how to bulk edit the item using database?Because i would like to edit barcode in bulk

Sent from Outlook Mobile




On Fri, Mar 18, 2016 at 11:08 AM -0700, "FrancescoUK" <notifications@github.com> wrote:












So it's a suggestion issue only.

**Comment by dxchen90** [comment]
Customer name is working fine, search will come out once key in some words

Sent from Outlook Mobile




On Fri, Mar 18, 2016 at 11:10 AM -0700, "FrancescoUK" <notifications@github.com> wrote:












Do you get the same issue on the customer search box?



I mean no suggestion but yes if you type name and enter?

**Comment by daN4cat** [comment]
This sounds really strange because the code between is the same.

Have you tried the same with different web browsers?

**Comment by daN4cat** [comment]
do you have any item_kit by any chance?

**Comment by dxchen90** [comment]
I tried in safari and chrome, both have same issue.Currently i just create barcode for all item and add sales order by scanning barcode. It might be database issue because I restored it. I will Wait for next update. Thumbs up for great support!

Sent from Outlook Mobile




On Fri, Mar 18, 2016 at 11:16 AM -0700, "FrancescoUK" <notifications@github.com> wrote:












This sounds really strange because the code between is the same.



Have you tried the same with different web browsers?

**Comment by dxchen90** [comment]
Item kit get this.
A Database Error Occurred
Error Number: 1146
Table 'whypaym2_stock2.ospos_item_kits' doesn't exist
SELECT * FROM `ospos_item_kits` ORDER BY `name` ASC LIMIT 50
Filename: models/Item_kit.php
Line Number: 28

Sent from Outlook Mobile




On Fri, Mar 18, 2016 at 11:20 AM -0700, "FrancescoUK" <notifications@github.com> wrote:












do you have any item_kit by any chance?

**Comment by daN4cat** [comment]
here we go, it's an issue with item_kits.

The search suggestion searches items and item_kits and that's why it doesn't work.

**Comment by daN4cat** [comment]
You need to create the table if it doesn't exists. Or add back your item_kits table if you had.

I think the case is closed as it's your installation.

**Comment by dxchen90** [comment]
Noted thank you.


Sent from Outlook Mobile




On Fri, Mar 18, 2016 at 11:24 AM -0700, "FrancescoUK" <notifications@github.com> wrote:












You need to create the table if it doesn't exists. Or add back your item_kits table if you had.



I think the case is closed as it's your installation.
