### ISSUE TITLE
fix notification message on updating item UPC/EAN/ISBN

### ISSUE THREAD

**Issue by Halwest01** [jekkos/opensourcepos#407]
hello, maybe this need a fix (see picture nelow), this happened after i added new item and then updated it and add UPC/EAN/ISBN to it with number "1" in bootstrapUI branch

**Comment by daN4cat** [comment]
What about post your pic directly here? Just copy and paste will do. I don't want to check where the image is among tons of ads.

**Comment by Halwest01** [comment]
![Image of bug](http://oi67.tinypic.com/k020z4.jpg)

sorry i didn't know the correct code to embed image before, here it is :)

**Comment by daN4cat** [comment]
No worries, thanks.

**Comment by ais-one** [comment]
@Halwest01 

I did not manage to get the error (latest pull from BootstrapUI branch), did you edit the code and put in something like die('') in the save function?

**Comment by daN4cat** [comment]
I don't see this issue either:

![image](https://cloud.githubusercontent.com/assets/636048/13906520/06e14bee-eed0-11e5-918e-16669541633e.png)

**Comment by ais-one** [comment]
@Halwest01 did you edit any PHP code or Javascript? that could lead to what you are seeing...

**Comment by Halwest01** [comment]
No i didnt edit anything , just downloaded ospos bootstrapUI and run it gor the first time and i got that , didnt touch anything

**Comment by ais-one** [comment]
@Halwest01 what are you using...

OS, web server & version, php & version, etc...

**Comment by Halwest01** [comment]
Windows , XAMPP v 3.2.2 , PHP/5.6.19  , php version from phpinfo() .

**Comment by daN4cat** [comment]
Anyone managed to reproduce this?

**Comment by jekkos** [comment]
Please be more specific here. Check your javascript console when entering the items page. An error might have occured which causes the form edit to fail.

**Comment by daN4cat** [comment]
I close, no news since a while.
