### ISSUE TITLE
Add CDN support

### ISSUE THREAD

**Issue by daN4cat** [jekkos/opensourcepos#408]
CSS and JS can be loaded from CDNs but at the moment there is no support for it.

We should have an option in config to select local or CDN.

**Comment by jekkos** [comment]
I don't directly see why would need CDN option, as most installations probably won't use more than 1 or 2 users? CDN might be beneficial for large public websites that generate lots of traffic and thus can offload static resources loading to other hosts. In this case I don't really know whether it would be faster/better.

**Comment by jekkos** [comment]
Also we already have minified js/css + caching using mod_expirry which should yield good performance.

**Comment by daN4cat** [comment]
Good point about the caching. I was just wondering that if not local a CDN is faster than pulling from you host provider most likely. But I guess it's debatable.

**Comment by jekkos** [comment]
So in this case cdn would only be useful if we use full source files which isn't the case, unless we set something up ourselves. Ok to close for now?
