### ISSUE TITLE
Better support for alternative bootswatch templates

### ISSUE THREAD

**Issue by daN4cat** [jekkos/opensourcepos#409]
At the moment bootstrap flatly is default template and look and feel for OSPOS 3.

Additional templates can be added and there is an example with spacelab. However templates are still not working properly with grunt scripts, path and etc.
A OSPOS installer should be able to add a template and have it working without big issues.

Would also be nice to make templates part of the distribution and selectable from the config, so to reduce any effort in installing alternatives.

**Comment by jekkos** [comment]
We could make templates installable using npm/bower/grunt.

**Comment by odiea** [comment]
bootstrap.min.css appears to be the only difference when I change the themes.

**Comment by jekkos** [comment]
You're right could'nt directly find the issue

**Comment by daN4cat** [comment]
There is an extra css to style things as you want. But if in the end we just want to change overall template styling just the min.css will do. Login needs to change too probably.

**Comment by jekkos** [comment]
I think login can load the same parameter in the path.. just a matter of adding a config->item in there

**Comment by daN4cat** [comment]
Yes, just set a reminder

**Comment by daN4cat** [comment]
Maybe we should solve this too given the fact that bootswatch-dist is lagging versions behind.
Maybe we should fetch all the bootswatch themes and switch between min.css selecting the theme from the config file and adding the param as dir selector in the header.php

**Comment by daN4cat** [comment]
Made the bootswatch theme support better with all the themes now available and configurable from config.php.
Removed the bootswatch-dist dependency so we now have 3.3.7 themes available.

I moved all the used css to dist, so we don't need to include js and css dir in the distribution.
Not sure we should move fonts to dist or not, but the bootstrap fonts are in dist at least to avoid issues.

style.css is a dummy file so people can retouch what they want, @odiea you need to move your one to dist and then you can remove templates dir unless you changed home.php. You'll have a bit of manual work to use this support.

**Comment by odiea** [comment]
Needs a lot more work. The pull looked bad so does the download. It appears something is not working.
![2016-08-10 05_03_40-new notification](https://cloud.githubusercontent.com/assets/10962177/17551545/07040334-5eb8-11e6-8837-037af6920aea.png)

**Comment by odiea** [comment]
Another one for the test branch.

**Comment by odiea** [comment]
Ad as you would say.
It would be nice to have it as feature that can be enabled/disabled from Store Config

**Comment by jekkos** [comment]
@daN4cat thanks for this addition, think it's great to have theming in ospos 

@odiea yes needs a small dropdown in the config section (that might just read available theme folders in dist/ to make them user selectable).

**Comment by daN4cat** [comment]
At the moment is selecting from config.php. I had no more time for the rest, maybe next days but it works fine as I tested.

@odiea it needs adjustment to your installation, yes.

**Comment by onyema3** [comment]
@daN4cat i think its need more work as it doesn't display well
This is from the latest masters

**Comment by odiea** [comment]
The only adjustment it needs on my end is to revert this commit.

**Comment by onyema3** [comment]
Same here

**Comment by odiea** [comment]
I have 2 installations. The one I play with and the Master that never gets changed except when I do a pull. I always check the later first to see what issues will show.

**Comment by odiea** [comment]
```
For some reason this
<link rel="stylesheet" type="text/css" href=<?php echo 'dist/' . $this->config->item('theme') . '/bootstrap.min.css' ?>/>
is not changing to this which works properly
		<link rel="stylesheet" type="text/css" href="dist/flatly/bootstrap.min.css"/>
```

**Comment by odiea** [comment]
@daN4cat Once this is working it will be a great addition to OSPOS.

**Comment by daN4cat** [comment]
Have you upgraded `config/config.php`?

You should see this in the new one at the top:

/*
 |--------------------------------------------------------------------------
 | Theme
 |--------------------------------------------------------------------------
 |
 | This specifies which theme will be used by OSPOS
 |
 |
 */
 $config['theme'] = 'flatly';

**Comment by odiea** [comment]
This is a new installation and a pull.

**Comment by odiea** [comment]
| This is the version of Open Source Point of Sale you're running
|
|
*/
$config['application_version'] = '3.0.0';

/*
|--------------------------------------------------------------------------
| Theme
|--------------------------------------------------------------------------
|
| This specifies which bootwatch theme will be used by OSPOS
| Available are: cerulean, cosmo, cyborg, darkly, flatly, journal, paper, readable, sandstone, slate, spacelab, superhero, united, yeti
|
*/
$config['theme'] = 'flatly';

/*
|--------------------------------------------------------------------------
| Commit sha1
|--------------------------------------------------------------------------
|
| This is the commit hash for the version you are currently using 
|
|
*/
$config['commit_sha1'] = '$Id: fc6bbbd0560d4e87103265ceb0450b5d7aaa930b $';

/*

**Comment by daN4cat** [comment]
Are you talking about the login issue or about the rest?
I'm referring to the initial issues

**Comment by odiea** [comment]
Both.

**Comment by daN4cat** [comment]
And you have all the files in dist/

**Comment by odiea** [comment]
As I said earlier. When I change this second link to any theme it works.  
The first link is not working for some reason.
```
For some reason this
<link rel="stylesheet" type="text/css" href=<?php echo 'dist/' . $this->config->item('theme') . '/bootstrap.min.css' ?>/>
is not changing to this which works properly
        <link rel="stylesheet" type="text/css" href="dist/flatly/bootstrap.min.css"/>
```

**Comment by odiea** [comment]
This is what I am getting with the inspector. The one with the not found is the one that came with the update. The second one is the one I added to get this to work.
![2016-08-10 07_57_03-](https://cloud.githubusercontent.com/assets/10962177/17556310/28ef6462-5ed0-11e6-85c6-071b0444720b.png)

**Comment by arteiro** [comment]
me or flatly is working

**Comment by jekkos** [comment]
Ok think I solved the login page css issue.

**Comment by onyema3** [comment]
@jekkos welldone! All working now and themes coming up well too!

**Comment by arteiro** [comment]
OK!

**Comment by daN4cat** [comment]
Yep, the double " issue was not popping up as a problem in Chrome. It should be fine now.

Selection from Store Config as next step.

**Comment by arteiro** [comment]
Instead of putting the settings could be on the login page?

**Comment by onyema3** [comment]
@daN4cat Yes and thumbs up for this new addition

**Comment by daN4cat** [comment]
I prefer to have the login page simple because it's the one anyone in the internet would see first. The less you expose the less to secure.

**Comment by onyema3** [comment]
I agree

**Comment by arteiro** [comment]
ok, i agree

**Comment by jekkos** [comment]
I have a little time on my hands now will try to add the dropdown in config section

**Comment by onyema3** [comment]
That would be great!

**Comment by daN4cat** [comment]
One think I didn't test now that comes to my mind, could you please test the invoice email?

**Comment by daN4cat** [comment]
@jekkos not sure but maybe all fonts dir should be moved to dist/fonts as it's used by css files there. However if we do invoice_email.css needs an update

**Comment by jekkos** [comment]
Theming now fully works on my local machine with the dropdown in config module. Please pick your flavors!

@daN4cat I moved fonts to dist/bootswatch/fonts now. I collected all themes in one subfolder as this was easier to iterate the names for the dropdown.

I have also added a fallback if the config value is not yet in the app_config table, by default flatly will be chosen.

**Comment by onyema3** [comment]
GREAT!

**Comment by daN4cat** [comment]
Looks good, thanks

**Comment by odiea** [comment]
@jekkos  Could you check the current Master Partial/Header . It appears the head is 3 times the size of what we currently have.

**Comment by odiea** [comment]
@daN4cat @jekkos  You two have done a great job on this. Thanks.

**Comment by jekkos** [comment]
![schermafdruk van 2016-08-10 22-38-43](https://cloud.githubusercontent.com/assets/576234/17570147/7e15b970-5f4b-11e6-9fed-6120902c5524.png)

**Comment by jekkos** [comment]
size looks quite normal both in chrome (a little smaller)) and FF

**Comment by odiea** [comment]
I guess I did not make myself clear. When you open the program and go to application/views/partial/header.php that head is much larger than the previous head was. This is a shot of the previous head info.
![2016-08-10 14_49_10-c__xampp_htdocs_shit_application_views_partial_header php - notepad](https://cloud.githubusercontent.com/assets/10962177/17570470/c20f614a-5f09-11e6-89df-7a5d62799dda.png)
Now if you go to the same location this is what I am talking about.

**Comment by odiea** [comment]
It also appears that none of the filters are working. Items filter does nothing but Date is working. In Takings it is doing the same thing. Try to change the filter and the only thing that happens is the table refreshes.

**Comment by daN4cat** [comment]
It's bigger because the header_debug has been exploded back in the section. There is no reason to have it since we don't duplicate the headers anymore.

**Comment by daN4cat** [comment]
Filter point to be checked.

**Comment by jekkos** [comment]
@odiea ok I also notice now that the dropdown's content is not showing up (instead the page is immediately refreshed). This issue was present before but only in debug mode (I already had a look at it but couldn't find why it didn't work)

**Comment by odiea** [comment]
There are also issues now with the tables and not being able to export or not remove a checkmark in the table.

**Comment by daN4cat** [comment]
It's a js clash issue most likely

**Comment by jekkos** [comment]
I did think that we used a js file from bootswatch in 3.3.6 which isn't there anymore. This one was copied through the main override. Not sure whether this was the original bootstrap.js or a custom one. Also the load order might be important here

**Comment by jekkos** [comment]
I found that now it works the other way around, filters ok in debug mode but not in the compressed js

**Comment by jekkos** [comment]
I think the problem was that the old bootstrap.js file was left in my bower_components folder. I have deleted it now an regenerated the js. Seems to work ok now

**Comment by daN4cat** [comment]
Yes, that was the problem for sure.

**Comment by daN4cat** [comment]
Tested and works fine now.

**Comment by daN4cat** [comment]
This is done, so I can close.
