### ISSUE TITLE
Make the invoice feature optional from store config

### ISSUE THREAD

**Issue by daN4cat** [jekkos/opensourcepos#410]
Not all the OSPOS users want to see the invoice feature, especially in normal high street shops where a receipt will do.

Make the invoice feature optional and configurable from config.

**Comment by jekkos** [comment]
So in this case add a checkbox in config to show/hide checkbox in sales register?

**Comment by daN4cat** [comment]
Or add a permission, either way will do. It's just to hide it for people that don't need the feature.

**Comment by sgr1875** [comment]
My request would be permission based, because some of my customer who purchase for office prefer in invoice method as the thermal receipt i give me fade away couple of days. so just making it permission of option will be appreciated.

**Comment by daN4cat** [comment]
Permission based means some ospos user can see , some no. Anyway I'll make it permission based.

**Comment by daN4cat** [comment]
Restructured the store config tabs, reorganising things in a more distributed way.
Added translations to tab names that were not translated.

Made the invoice feature optional from the store config.

Permission to enable or disable invoice feature by user can be added later if wanted.
