### ISSUE TITLE
Let's use a Kanban board to manage a bit the development and priorities

### ISSUE THREAD

**Issue by daN4cat** [jekkos/opensourcepos#411]
Not sure how many of you are familiar with Agile development and in specific Kanban (instead of Scrum).

Well we can use a Kanban board with GitHub for free: https://www.zenhub.io/

I just added the plugin (Chrome and Firebox) and can see a board and moved some of the issues to the right phase:

![image](https://cloud.githubusercontent.com/assets/636048/13906581/8eb6442e-eed1-11e5-93ce-2d8b82479a38.png)

If we could all move to this it would be easier to know the stage of issues and manage it in a collaborative way.

If you are not familiar with the Kanban concept just Google for Kanban Board (maybe add Agile methodologies)

**Comment by jekkos** [comment]
Good idea! Github issue tracker is a bit limited in functionality and it would be nice to see priorities and keep track of who's doing what. Scrum is probably not a good fit indeed. Never used kanban before but I think it fits our development flow better.

**Comment by daN4cat** [comment]
Proper Kanban implies certain rules to control bandwitdh usage and maximise throughput. But we are not a company that needs to maximise their business. So state and priority will do.

Also you can select milestone so you can have a selective view of the issues on the board.
I'm sure you'll like it once in action.

**Comment by jekkos** [comment]
I've installed the plugin but it's annoyingly slow :). Can't manage to just load the boards tab in FF here.

**Comment by daN4cat** [comment]
There is something wrong this eve. I found it slow as well. It was like that yesterday and this morning.

**Comment by daN4cat** [comment]
It seems to me like it's in use, am I right?

**Comment by jekkos** [comment]
This support for subtasks might be better integrated (and visible for users that don't have zenhub installed)

https://github.com/blog/1375-task-lists-in-gfm-issues-pulls-comments
