### ISSUE TITLE
Barcode printing

### ISSUE THREAD

**Issue by odiea** [jekkos/opensourcepos#414]
Does the program send any print settings when printing barcodes. I set up the size I need but it changes to 4.88 x 11. The default printer settings are 2.25 x 1.37.

**Comment by daN4cat** [comment]
Barcode is a png image. There is nothing the application does and it's all under the control of your web browser.

**Comment by odiea** [comment]
Hopefully this will help others.
on firefox type in about:config. Search printer. Locate the printer you are looking for. In my case It was an zebra barcode printer. I changed the following
    print_paper_height to 1.37
    print_paper_width to 2.25
    print_paper_size_type 1 to 0
Now jsprint works great. I also adapted the print and auto close buttons.

**Comment by daN4cat** [comment]
Great and thanks for the tip.

**Comment by odiea** [comment]
So the way I have this set is you put your total number of barcodes you want to print for that item into custom_5. If you just want to print 1 barcode for the item it will print 1 barcode using the generate barcode bulk print. If you want to print multiple barcodes for the same item then select that item only and it will print the number of barcodes in custom_5. You should already have your barcode printing setup correctly. This is using jsprint and the screen will disappear after the barcodes are sent to the printer. So I guess it's best to use Firefox with the jsprint addon installed.
[barcode_sheet.zip](https://github.com/jekkos/opensourcepos/files/186803/barcode_sheet.zip)

**Comment by tanakornp** [comment]
For chrome user, I solution from https://qz.io/
I added another page and rebuild bar code by using command ZPL.
It works on my TSC TTP-245.
