### ISSUE TITLE
Can not open items menu

### ISSUE THREAD

**Issue by arkgnan** [jekkos/opensourcepos#416]
i get issue when open items menu
error in items menu
Fatal error: Can't use method return value in write context in D:\xampp\htdocs\opensourcepos-feature-bootstrapUI\application\controllers\Items.php on line 115
Fatal error: Class declarations may not be nested in D:\xampp\htdocs\opensourcepos-feature-bootstrapUI\system\core\Exceptions.php on line 49

**Comment by ais-one** [comment]
can please be more specific? you open to create new item or to edit item, or open item list?

**Comment by arkgnan** [comment]
open items

**Comment by daN4cat** [comment]
I wouldn't that there is something not right with xampp. Anyone else tried that already? Also what else do you have? PHP version?

**Comment by ais-one** [comment]
I have xampp, will try it later and feedback. I am not clear actually about how the poster arrived at the error.

**Comment by arkgnan** [comment]
i use old xampp, v1.7.4... i'll try in hosting and give feedback

On Mon, Mar 21, 2016 at 4:44 PM, Aaron Gong <notifications@github.com>
wrote:

> I have xampp, will try it later and feedback. I am not clear actually
> about how the poster arrived at the error.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/jekkos/opensourcepos/issues/416#issuecomment-199194629>
>



-- 
Best Regards

Dedi Ananto

**Comment by daN4cat** [comment]
Which PHP version do you have in the old setup?

**Comment by arkgnan** [comment]
I just tested it in web hosting, and it work... the issue is about PHP version, my xampp use v5.3.5, and in hosting ospos still not work on php 5.3 and 5.4. it must run on 5.5

**Comment by ais-one** [comment]
Hi,

In another project when move to PHP 5.5 from 5.4, I noticed that json_encode for ajax broke and I had problems.

It looks like the same thing happening here. This software really may need 5.5+ and hopefully can use on 7.x later

**Comment by daN4cat** [comment]
Ok, good that we got to the root cause. I will add a comment in the Read.md stating PHP 5.5+

**Comment by daN4cat** [comment]
Thanks for all the help with this issue.
