### ISSUE TITLE
Impossible to translate to Spanish

### ISSUE THREAD

**Issue by JaiderMengual** [jekkos/opensourcepos#418]
Try installing in Spanish and I am not.

Install in English and try to switch to Spanish and not let me.

In the medu of "receivings" shows the attached error.

[http://www.jmgsoluciones.com/ventas/Error2.jpg](url)
[http://www.jmgsoluciones.com/ventas/Error1.jpg](url)

Please if the link does not work, copy and paste.

**Comment by daN4cat** [comment]
Version please and copy and paste your pictures here, links don't work and could lead to spam or malware.

**Comment by JaiderMengual** [comment]
Editing, attached files.
I can not install in Spanish, nor change the language after installed.

![error 1](https://cloud.githubusercontent.com/assets/17993730/13950524/8143d832-eff9-11e5-980f-b8b70346b01d.jpg)
![error 2](https://cloud.githubusercontent.com/assets/17993730/13950523/8140aeaa-eff9-11e5-97e0-3c845b06198b.jpg)
![error 3](https://cloud.githubusercontent.com/assets/17993730/13950525/81467bfa-eff9-11e5-9312-27d057be2636.jpg)
There are several menus that throw error. (The Deputy)
I'm using the default user to enter.

**Comment by daN4cat** [comment]
Please check the translation files, I don't think Spanish had any update for a long time.

**Comment by jekkos** [comment]
Can't reproduce this bug either. Must be something with your local install.

**Comment by JaiderMengual** [comment]
Downside solved.
The problem was in the databases, one of the tables, exactly:
"CREATE TABLE` ospos_app_config "to create the renowned and so I threw errors.

Thank you very much.

**Comment by daN4cat** [comment]
How did you get to produce that?

**Comment by daN4cat** [comment]
@JaiderMengual any chance you can look into the latest 3.0 and updated Spanish translations?
