### ISSUE TITLE
Two MRP for One product?

### ISSUE THREAD

**Issue by sgr1875** [jekkos/opensourcepos#419]
I am running a supermarket and there is always problem with products will have two mrp in the sense same EAN code but mrp would have changed when scanning will it possible to select mrp? 

eg: Col 100GMS 84.00 (Batch s1901688) (Barcode: 8906055790649)
      Col 100GMS 88.00 (Batch r1901433) (Barcode: 8906055790649)

kindly let me how this can be handled.

**Comment by daN4cat** [comment]
There is not such support, you could either create your own barcode for the case to make a distinction between the two or use the item name adding the batch and select by item name and not barcode.
