### ISSUE TITLE
overview feature permissions

### ISSUE THREAD

**Issue by kynesta** [jekkos/opensourcepos#42]
Hello jekkos,
Just downloaded the ospos-master 2.3.2 and tried it out, noticed that employees with access to only the sales module, can delete sales through the overview feature!?

Secondly, in the items module, when a different location is selected, items and their quantities don't change to selected location.

Keep up the amazing work.

**Comment by kynesta** [comment]
I just did some additional testing with the Overview feature, while editing the sale, i click "delete entire sale" and then click "cancel", the sale is deleted anyway.

**Comment by jekkos** [comment]
Delete upon cancel is fixed now. Also item refresh on different location should be ok.

I don't really see the delete button as a bug. Maybe reformulate the enhancement needed to make it more suitable and consistent with the delete functionality in the reports section.
