### ISSUE TITLE
create employees without any grant access to modules

### ISSUE THREAD

**Issue by arkgnan** [jekkos/opensourcepos#420]
hi, back again... i still test 2.4, and want to ask you guys. whether ospos at your place can create employees without grant access?
ospos in my place can create employees without any grant access to modules, of course the user can't login. if i'm not mistaken, in v.2.3.4 we must choose at least 1 grants

**Comment by jekkos** [comment]
you should have at least a grant to the employees module, in case you want to create new employees yourself or change grants for an existing one.

**Comment by arkgnan** [comment]
i download 2.4 again and run it on xampp 1.7.4 (PHP 5.3). it shouldn't be free of PHP 5.5 issue. but i still can create employees without a grant

**Comment by arkgnan** [comment]
this form.php on employees view. can any one try it on your ospos and tell me it work or not
[https://gist.github.com/arkgnan/9915e6d530192b9641c3](url)

**Comment by jekkos** [comment]
@arkgnan Ok you're right I didn't understand the issue at first. We probably need a validation check to see whether there is at least one grant assigned before submit? Does that make sense?

**Comment by arkgnan** [comment]
yeah, I think it's something stupid to create a user who does not have any access. so there must be a validation to select at least one access. but as I remember once ospos already done that. I do not know why now is not working

**Comment by arkgnan** [comment]
let me know if this issue happens to others... whether as before this just happened to me

**Comment by arkgnan** [comment]
CMIIW, in form.php we create addmethod for validation grant module. next step after addmethod is call it on rules inside $('#employee_form').validate(). we set checkbox name : {module:true}. but i don't find similar code on form.validate. and i create because checkbox name is in array ( grant[] ).  jQuery validator doesn't fully support using field name arrays because it relies on the field names to be unique. in old code i found this code on rules.
`"grants[]" : {
		        		required : function(element) {
							var checked = false;
		            		$("ul#permission_list > li > input:checkbox").each(function() 
		                    {
								if ($(this).is(":checked")) {
								var has_children = false;
								    $("ul > li > input:checkbox", $(this).parent()).each(function() 
								    {
									    has_children = true;
									    checked |= $(this).is(":checked");
								    });
								    if (has_children && !checked) 
									{
										return false;
									}
								}
		            		});
							return !checked; 
		        		},
		        		minlength: 1
				    }`
that's code work to validate checkbox and make us choose at least 1 grant module.

**Comment by arkgnan** [comment]
i fixed it with add rules
`'grants[]':
	{
		required: true,
		minlength: 1
	}`
also in message 
`'grants[]': "<?php echo $this->lang->line('employees_subpermission_required'); ?>",`
when i add rules using custom method in rules like this
`'grants[]':
	{
		module: true
	}`
it's not work, not sure why because nothing wrong with $.validator.addMethod code. could you explain to me why this issue happen

**Comment by jekkos** [comment]
@arkgnan I did a fix for this issue already. Here I just modified the custom validator with one extra line. Could you verify and report if this works for you?

**Comment by jekkos** [comment]
It's the grants field that uses a custom validator which is module in this case. This validator handles all aspects at once (enforce fact that permission with children has at least one child selected)

**Comment by arkgnan** [comment]
thank man.. it work for me.

**Comment by jekkos** [comment]
Merge to bootstrapUI as well.
