### ISSUE TITLE
print invoice prior to sale

### ISSUE THREAD

**Issue by Tristan083** [jekkos/opensourcepos#421]
Hi,

I'm not sure if this has been raised; but, I think it would be a great enhancement to be able to print invoices prior to sales as well as have the option to print invoices for suspended sales. This way the invoice can be printed prior to an actual sale; and, when payment is received, the sale can be pulled either from a suspended sale or sale/register then the sale can be processed and the receipt printed right after.

**Comment by daN4cat** [comment]
This is called pro-forma invoicing.
It's not supported at the moment and it goes in the wish list if somebody wants to pick up and help.

**Comment by jekkos** [comment]
think there was already an issue with custom solution for this? #312

**Comment by jekkos** [comment]
If willing to integrate then we'll need a proper pull request for this.

**Comment by jekkos** [comment]
I'll close this one and refer to #570 now (duplicated issues).
