### ISSUE TITLE
Sales Invoice issues

### ISSUE THREAD

**Issue by odiea** [jekkos/opensourcepos#423]
Step 1. create and suspend an Invoice sale.
Step 2 Create and complete a new Invoice Sale.
Step 3 Go back to Suspended Sale  Unsuspend and complete the sale.
Error about unique Invoice number.

**Comment by jekkos** [comment]
Ok thanks for opening this issue. Think there are two possible usecases here

* invoice number is edited manually and sale is suspended. After unsuspend a proper validation should take place to see whether number is present or not
* invoice number is auto generated. In case of unsuspend the invoice number should be regenerated as it wasn't edited manually.

So for this situation we need to find a way to see whether the user has edited the number or not before suspend. Any other ideas?

**Comment by jekkos** [comment]
Also this isn't really a bug (as I think it's expected behavior) but more of an enhancement. Last fix was the sale suspend giving the duplicated error and thus removing the constraint on that table which fixed it.

**Comment by odiea** [comment]
After a few more tests the invoice number is back to being saved on suspended sales or a new row count is not being done.

**Comment by daN4cat** [comment]
Close?

**Comment by odiea** [comment]
I guess that is up to @jekkos to try to fix again. Maybe we should put some kind of notice not to suspend an Invoice after Invoice has been selected..

**Comment by odiea** [comment]
Is there a way to prevent the Suspend button from working if there is a checkmark in Invoice? I think that would eliminate 1 issue.

**Comment by jekkos** [comment]
My idea was to set the suspended invoice number to null in case it's an autogenerated one. Depending on the state of the invoice number checkbox at unsuspend time a nuimber will be generated or not. If the user has manually changed the invoice number then it will be suspended together with other data. In that case a duplicate check will be done at unsuspend time. Question is whether a user would want to use manual sequences in one way or another? 
If the usecase is not needed then maybe we could just omit the invoice number from suspend completely and warn the user in that case?

**Comment by odiea** [comment]
At this point in time I think it would work if you could save a sale with  invoice enabled without the invoice number then have it get the next available number when it is unsuspended and see how that works out.

**Comment by odiea** [comment]
I think it would be a lot less work for both of you if you just disabled the suspend button if the invoice box is checked

**Comment by jekkos** [comment]
Ok did a fix for this issue. Invoice number is now regenerated if no custom format was used on unsuspend time. This should fix the unique error condition.

**Comment by odiea** [comment]
Suspended Invoicing is working properly now.

**Comment by daN4cat** [comment]
In 3.0 too, so can close this.
