### ISSUE TITLE
check(cheque) payments in Detailed reports (Customer / Sales)

### ISSUE THREAD

**Issue by farissalih87** [jekkos/opensourcepos#424]
I cant see sales with check payments in Detailed reports (Customer / Sales)

**Comment by daN4cat** [comment]
Version please

**Comment by odiea** [comment]
Here is 2.4 Master. Bootstrapui looks similar. No issues as you can see.
![2016-03-23 15_09_00-christmas sweater store -- powered by os point of sale](https://cloud.githubusercontent.com/assets/10962177/14000966/46c7a7f4-f109-11e5-9bf4-fee9048fdb20.png)

**Comment by odiea** [comment]
And here is Detailed Sales report.
![2016-03-23 15_15_29-christmas sweater store -- powered by os point of sale](https://cloud.githubusercontent.com/assets/10962177/14001136/276a2534-f10a-11e5-8c65-42bbe5aff5d0.png)

**Comment by osworx** [comment]
Both looking so terrible poor and old school ..

**Comment by odiea** [comment]
Here is the newer Bootstrap version.
![2016-03-23 15_24_30-ugly sweater store -- powered by os point of sale](https://cloud.githubusercontent.com/assets/10962177/14001431/6cd1d26a-f10b-11e5-8741-42fcfb80b767.png)

**Comment by odiea** [comment]
If you would like to redesign it and submit your changes for review you sure may.

**Comment by farissalih87** [comment]
thanx
