### ISSUE TITLE
Shortcut Key usage

### ISSUE THREAD

**Issue by sgr1875** [jekkos/opensourcepos#425]
in the old version (1.1 yea very old version) i was using the shortcut keys and was working fine.

in common.js
$(window).jkey('f1',function(){
	window.location = 'imacros://run/?m=CASH%20PRINT.iim';
});

$(window).jkey('f2',function(){
	window.location = 'imacros://run/?m=SODEXO%20PRINT.iim';
});

$(window).jkey('f3',function(){
	window.location = 'imacros://run/?m=Credit%20Card.iim';
});

$(window).jkey('f4',function(){
	window.location = 'imacros://run/?m=SUSPEND.iim';
});

$(window).jkey('f5',function(){
window.location = BASE_URL + '/items/index';
});

$(window).jkey('f6',function(){
window.location = BASE_URL + '/sales/index';
});

partial/header.php

<script language="javascript">
// setting module key press
<?php
	$i=0;
    foreach($allowed_modules->result() as $module)
	{ $i++;
?>
$(window).jkey('f<?php echo $i; ?>',function(){    
    window.location = BASE_URL + '/<?php echo $module->module_id;?>';
});
<?php
	}
?>
</script>
<?php
	}
?>

And using the iMacro for firefox and i was able to use but if i try to implement the same in the 2.3.4 version, the function is not working? Am i missing something.

**Comment by ais-one** [comment]
actually, I think we should get rid of reliance on the add-ons tied to a single browser and shortcut keys, and usually F5 is browser refresh, can be confusing.

**Comment by jekkos** [comment]
I think that code is still present and I agree that I'd rather get rid of it.

**Comment by jekkos** [comment]
There's an accesskey html attribute as well, will check if it can be leveraged for this situation.

**Comment by daN4cat** [comment]
Accesskey requires <alt> at least: http://www.w3schools.com/tags/att_global_accesskey.asp

**Comment by jekkos** [comment]
Haven't test this feature, not sure whether it only focuses the element or really allows one to follow the link as well.

**Comment by jekkos** [comment]
Ok I've done a quick test with access keys and this seems to work in ff by hitting shift-alt-key. I don't really use this feature but main advantage is that these key combinations won't interfere with any existing combination as the browser will bind them by itself. 

* Any votes up to remove jquery-key and add shortcuts using these accesskeys?
* Which keys should we choose for which module? Should they be user definable?

**Comment by daN4cat** [comment]
I believe the original poster of the issue wants the F1, F2, etc. keys. No combinations as that's not handy at all.

**Comment by jekkos** [comment]
Ok but problem is that binding those keys using jquery will override default browser functionality. This could be annoying as well for users expecting f5 to be refresh page?

**Comment by odiea** [comment]
Good point. And what happens if a user does not have permission to some of the modules that will use the function keys?

**Comment by daN4cat** [comment]
To be honest, I would leave this completely out.

**Comment by daN4cat** [comment]
Otherwise you end up having mapping of keys, this and that... And the trend is touch screens.

**Comment by ais-one** [comment]
I would prefer to remove this as well. As indicated
1. causes confusion
2. is browser dependent and different browsers have different response
3. too much maintenance for a feature that is not critical, as the trend is really touch screens

**Comment by jekkos** [comment]
Ok gentlenmen, you had your votes. I agree and will remove this (which milestone?)

**Comment by daN4cat** [comment]
2.4 and I will cascade to 3.0

**Comment by jekkos** [comment]
Solved and will close now (functionality removed)

**Comment by jekkos** [comment]
Think this was the last 2.4 issue. Time to release? Or shall I include the HU translation first?

**Comment by daN4cat** [comment]
Maybe you can add the HU translation indeed assuming it's all fine and release 2.4.
So we can finally focus only on 3.0.

**Comment by WebShells** [comment]
A final stable fix was applied to this issue through PR #4532
