### ISSUE TITLE
Decimals in Inventory

### ISSUE THREAD

**Issue by joerony** [jekkos/opensourcepos#429]
I have problem here. Let us say:

I have 10 kilograms of Sugar. I sold 0.5 kilograms. The quantity in the inventory should be 9.5Kgs. But it is still 10Kgs in the inventory. Then, I tried another way. I bought 0.5 kilograms of Beans. Previous quantity is 10 Kilograms in inventory. When the transaction is done, I checked the inventory and the quantity become 11 Kgs. 

Can you help me on this?
Maybe my inventory cannot support decimal.

best regards,
Rony Joe

**Comment by daN4cat** [comment]
Is this the only issue with decimals? And which version are we talking about here?

**Comment by joerony** [comment]
Yes, I got this issue with decimal point in the quantity of inventory. I am using the latest version, OSPOS 2.3.4. Thank you very much for the help.

**Comment by joerony** [comment]
Waiting for your help, I still cannot fix this issue. thanks before.

**Comment by jekkos** [comment]
Think the use of decimals is probably not that consistent right now and will need some review?

**Comment by joerony** [comment]
hmmm sorry before, I do not understand, since the quantity of inventory is really important. Maybe there is another idea for this. should I use "Grams" for the unit instead of "Kilograms"? 1Kg becomes 1000grams, so i input 1000 in the inventory quantity. then if someone buys 0.5Kg, my inventory become 500. But still, I think decimal point is really needed alot, to avoid using 1000 as the quantity. please advice. thank you.

**Comment by freemail624** [comment]
I think you have to alter the tables "ospos_item_quantities" and  "ospos_inventory"
change the type of "quantity" and "trans_inventory" from "int(11)" to "DECIMAL(15,4)"

**Comment by jekkos** [comment]
Yes indeed does that solve this issue here?

**Comment by freemail624** [comment]
I tried this and it works 

![image 3](https://cloud.githubusercontent.com/assets/6794450/14104993/7e13ddfc-f5b1-11e5-9fc9-2b5ed5a62154.png)

**Comment by joerony** [comment]
Yes, it works also for me. Thanks alot for the help, guys. This POS is really good.

**Comment by daN4cat** [comment]
Maybe we should change it in 3.0

**Comment by jekkos** [comment]
Yes change the milestone.  I think this issue needs some more review and a configurable amount of decimals for the whole application

**Comment by jekkos** [comment]
We could apply this column type change in 2.4 but then all inventory details will show quantities having .00 which might not be desirable either

**Comment by jekkos** [comment]
See also #307 in which a user asked to get rid of these decimals

**Comment by daN4cat** [comment]
Yes, my case would be no decimals. The overall decimal story needs to be configurable from 0 to 3 (I assume this is the max range, unless we know of 4 or 5?).
Currently there are some quantity fields that show no decimal and another one that show decimal, it's not consistent.

**Comment by daN4cat** [comment]
And forgot that tax decimals is a different story too.
There are people that requested up to 3 decimals for tax %.

So in summary:

- decimal for quantities (0 - 3)
- decimal for currencies (0 -3)
- decimal for taxation (0 - 3)

Independent configuration from each other, the first one is POS context based, the last two are locale based.

**Comment by freemail624** [comment]
What about using  **floatval($quantity);**   in the view to remove the .0000 
Example:
the quantity with 7.0000 will be 7
and the 7.0500 will be 7.05

**Comment by daN4cat** [comment]
good tip, I'll have a look into as it looks far easier indeed.

**Comment by daN4cat** [comment]
I need to think about this, maybe for quantities is fine indeed but for currencies is probably not.
Not sure about taxation.

**Comment by daN4cat** [comment]
In order to enable the 3 decimals on each of the abovementioned items the first is to change the database schema.
Do we believe 3 decimals is enough here?

**Comment by daN4cat** [comment]
OK, I found this: http://www.unicode.org/cldr/charts/latest/supplemental/detailed_territory_currency_information.html

and 3 decimal digits is really a rarity, just few Arabian speaking countries have it but I doubt they will use OSPOS in short. My bet is that by the time the will adopt it the 3 digit is gone and eaten by the inflation effect.

I would therefore focus on the quantity story at the moment.

**Comment by jekkos** [comment]
If I remember well then there was a request to use taxes up to three decimals precision. Not sure on currency but indeed I guess that 2 decimals would be enough for most usecases.

**Comment by jekkos** [comment]
Issue for 3 decimal tax is #327

**Comment by daN4cat** [comment]
Yes, tax issue was already tagged above.

I'm working on quantity decimals and to be configurable. Mostly done.

**Comment by daN4cat** [comment]
OK, made the quantity decimals configurable (from 0 to 3) and working across forms, reports and etc.

The database needs to be updated, please use the script 2.4_to3.0.sql before using the new feature (if moving from an existing 2.4/3.0 database).

I tested most of it, but not every singular bit and scenario, so some help with the test is much appreciated.

**Comment by daN4cat** [comment]
The decimals can be configured in Store Config under Locale tab.

**Comment by odiea** [comment]
I am getting this error with the database update using phpmyadmin.


Error

SQL query: 


-- alter quantity fields

ALTER TABLE `ospos_items`
 MODIFY COLUMN `reorder_level` decimal(15,3) NOT NULL DEFAULT '0',
 MODIFY COLUMN `receiving_quantity` decimal(15,3) NOT NULL DEFAULT '1'

ALTER TABLE `ospos_item_kit_items`
 MODIFY COLUMN `quantity` decimal(15,3) NOT NULL

ALTER TABLE `ospos_item_quantities`
 MODIFY COLUMN `quantity` decimal(15,3) NOT NULL DEFAULT '0'

ALTER TABLE `ospos_receivings_items`
 MODIFY COLUMN `quantity_purchased` decimal(15,3) NOT NULL DEFAULT '0',
 MODIFY COLUMN `receiving_quantity` decimal(15,3) NOT NULL DEFAULT '1'

ALTER TABLE `ospos_sales_items`
 MODIFY COLUMN `quantity_purchased` decimal(15,3) NOT NULL DEFAULT '0'

I am getting this error with the database update using phpmyadmin.

ALTER TABLE `ospos_sales_suspended_items`
 MODIFY COLUMN `quantity_purchased` decimal(15,3) NOT NULL DEFAULT '0'
MySQL said: Documentation 
 #1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'ALTER TABLE `ospos_item_kit_items`
 MODIFY COLUMN `quantity` decimal(15,3) NOT ' at line 7

**Comment by odiea** [comment]
I had to change it to this and it worked fine. Had to add ; 
ALTER TABLE `ospos_items`
 MODIFY COLUMN `reorder_level` decimal(15,3) NOT NULL DEFAULT '0',
 MODIFY COLUMN `receiving_quantity` decimal(15,3) NOT NULL DEFAULT '1';

ALTER TABLE `ospos_item_kit_items`
 MODIFY COLUMN `quantity` decimal(15,3) NOT NULL;

ALTER TABLE `ospos_item_quantities`
 MODIFY COLUMN `quantity` decimal(15,3) NOT NULL DEFAULT '0';

ALTER TABLE `ospos_receivings_items`
 MODIFY COLUMN `quantity_purchased` decimal(15,3) NOT NULL DEFAULT '0',
 MODIFY COLUMN `receiving_quantity` decimal(15,3) NOT NULL DEFAULT '1';

ALTER TABLE `ospos_sales_items`
 MODIFY COLUMN `quantity_purchased` decimal(15,3) NOT NULL DEFAULT '0';

ALTER TABLE `ospos_sales_suspended_items`
 MODIFY COLUMN `quantity_purchased` decimal(15,3) NOT NULL DEFAULT '0';

**Comment by odiea** [comment]
I am getting php errors when trying to add a new item but update item is ok.

**Comment by daN4cat** [comment]
Ok, thanks for the test, I'll fix the issues later.

**Comment by daN4cat** [comment]
Issues fixed, old code missing sanity checks/default values setting.

**Comment by jekkos** [comment]
Ok thanks for the work. Will give it a try if I can later this weekend.

**Comment by daN4cat** [comment]
I believe with my last commit the decimals in quantity and make it configurable is now completed.

**Comment by daN4cat** [comment]
Even currency is now configurable from 0 to 2 decimals.

**Comment by daN4cat** [comment]
All configurable from Store Config / Locale tab

**Comment by odiea** [comment]
The only issue I have found so far is the way the Inventory count is displayed on the Sales screen with 3 decimal when no decimal is configured.
![2016-04-01 15_32_25-ugly sweater store -- powered by os point of sale](https://cloud.githubusercontent.com/assets/10962177/14220752/4a457e5c-f81f-11e5-8c05-c5d8431d4ca4.png)

**Comment by odiea** [comment]
All other decimal configs appear to work properly.

**Comment by daN4cat** [comment]
I thought to have fixed it. I remember to have changed it. Have you taken all the latest files? I'll check tomorrow again.

**Comment by odiea** [comment]
Yes. I just checked and my last pull got all the updated files.

**Comment by daN4cat** [comment]
Ok, so it's all working fine. Great :-)

**Comment by daN4cat** [comment]
Sorted the tax decimals too and adjusted the totals rounding according to number of decimals.

I close this and if any issue please add it to #327 because this change is related to tax decimals.

**Comment by daN4cat** [comment]
Please help with the test as this is tricky to verify in all possible scenarios and view.

**Comment by odiea** [comment]
What I see in Items is cost and sale price inherit the decimal settings of tax. I set currency to 2 and tax to 3 currency shows 3 in items.

**Comment by daN4cat** [comment]
Have you read #327 comment ? Please continue the posting there...

**Comment by djm777** [comment]
Hi everyone, for me just change quantity_decimals, its work
![locale_helper](https://cloud.githubusercontent.com/assets/19495053/17401026/666f8d26-5a75-11e6-8625-1382a593e854.PNG)

**Comment by djm777** [comment]
the file is in folder: application/helpers/locale_helper

**Comment by daN4cat** [comment]
@djm777 you are using an old version. This work was for 3.0 which is almost ready for release now.

**Comment by djm777** [comment]
@daN4cat, Upss I dont know but this is the view....
in sale register:
![view 1](https://cloud.githubusercontent.com/assets/19495053/17403263/2b948132-5a81-11e6-8e33-b70bce765d8c.PNG)

and...

this is the updated view after sale on inventory:
![view 2](https://cloud.githubusercontent.com/assets/19495053/17403363/8a334ed0-5a81-11e6-9622-005c0d980037.PNG)

**Comment by djm777** [comment]
sorry if I'm out of the version

**Comment by daN4cat** [comment]
Anyway, this problem is solved. Please check the latest code from master.

**Comment by djm777** [comment]
Ok, thanks.
