### ISSUE TITLE
Feature request: Use ESC/POS to send commands to a printer connected

### ISSUE THREAD

**Issue by mikersee** [jekkos/opensourcepos#43]
use ESC/POS commands to send commands direct to the printer, which is connected to the server. It can be used https://github.com/mike42/escpos-php

It allows for send of image, text, barcode, cutting function and etc, allowing to talk natively with the printer. Note that required the printer connected direct to the server, or printer on network .

I think it would be awesome addition for the Php POS program, and would make it perfect for my use and many others uses. 

Hopefully feature get added, and sorry for my English.

**Comment by jekkos** [comment]
The latest version has jsPrint integration which will allow you to print to receipt printers in a frictionless way. What extra benefits would you like to have from using this library specifically?

**Comment by mikersee** [comment]
does jsPrint allow esc/pos commands? Also can it support cutting?

**Comment by jekkos** [comment]
when printing to an epson TM88 IV it doesn't cut the ticket automatically after print. But it's just a matter of pulling it out of the printer when the printing is done. I don't directly see the added value of using esc/pos command directly, barcodes and images are working ok with my setup at this moment.

**Comment by jekkos** [comment]
Maybe this is what you were looking for?
http://www.apipos.com/files/tmt88.html
```
What Printer Driver To Use


There are two Epson TM-T88II printer drivers--a Partial Cut and a No Cut.


Use the EPSON TM-T88II Partial Cut driver. The Partial Cut printer driver automatically cuts whenever a print job is finished.


Partial Cut means it leaves a very tiny piece of the receipt connected. As you lift the receipt, this tiny part easily tears. This feature prevents sales slips from getting caught in the wind, sending cashiers and customers dashing for runaways.

```

**Comment by mikersee** [comment]
Using ESC/POS allows for much faster printing, due to it sending text to the printer, rather than an image. As with the current setup it has to be converted to an image by the operation system, then sent to the printer. This also requires that drivers be installed for the printer on linux, which means if you use ESC/POS, the Raspberry Pi can be used as a POS system, because both Epson and some other POS Printer company don't provide ARM drivers for their products. Another function of using the ESC/POS library, is allows the cash drawer to open. I think its good choice for this program, would make it really useful, the ESC/POS php library is excellent quality make. If you are not willing to add the ESC/POS library as an option for print receipt to your program, I will do it myself, as I am really in need of it. But I don't know much PHP.

**Comment by jekkos** [comment]
I just had a quick look at the library and it seems to be quite low level. The receipt is a html template 
now and it would take quite some time to convert it to esc/pos api line instructions, but as I'm not in need for it myself, I have no real priority to implement it either. Feel free to try and contribute if you have something working.

**Comment by mckaygerhard** [comment]
@phantomgannon please read the recent wiki pages about printing

**Comment by phantomgannon** [comment]
Thanks. I've read the Wiki and got the reciept printing but have got issues. I can print in Firefox and chrome and the printing is very slow. Printing in Internet Explorer is quick as the Epson driver substitutes the fonts for its inbuilt font. Unfortunately the font substituing is not working on Firefox or Chrome. All browsers are the latest versions and upto date.

**Comment by mckaygerhard** [comment]
sorry i use true browsers, not ie! maybe the problem its that u use non-unix OS.. in androit printing are fast and in my linux! oh well i not use "lasted version"... only working "esr"

**Comment by phantomgannon** [comment]
Unfortunately our work PC's are all windows as they require Proprietary software that is windows only. Haven't used IE in years but it seems to be the only browser that can print quickly to the Epson TM-T90. Both Firefox and Chrome don't allow subsitute fonts to work on the printer.

**Comment by mckaygerhard** [comment]
so maybe its better to ask to OS right support, seems are a problem obvously related to that OS, umm seems have a large problematic history! right? about the fonts obviously in that OS are a problem! and for most of linux users too if they dont know about low level install.. currently i dont remenber but now i have many packages of fonts installed to work property! so for solved that i distribute my own iso...
