### ISSUE TITLE
Customer info in Sales

### ISSUE THREAD

**Issue by odiea** [jekkos/opensourcepos#430]
If you enter any search such as zip or phone or a customer that is not in Customers you will get the following error.

![2016-03-27 15_02_53-christmas sweater store -- powered by os point of sale](https://cloud.githubusercontent.com/assets/10962177/14067892/9fd74120-f42d-11e5-8084-4dcb58613609.png)

**Comment by daN4cat** [comment]
Version?

**Comment by odiea** [comment]
Both. Master and feature/bootstrapui

**Comment by jekkos** [comment]
So after clicking the suggestion?

**Comment by odiea** [comment]
enter a number or name not in the customer list. There is no suggestion just that error.

**Comment by jekkos** [comment]
Think it'd be better to move most of this generation logic to separate classes..

**Comment by jekkos** [comment]
Ok did a fix for this issue. It existed in receivings as well. Now there's a check whether a selected id exists before something is added (in case of sales customer or supplier in case of receivings).

**Comment by odiea** [comment]
Sales works fine now but no change in receivings. Did you forget to add that fix?

**Comment by jekkos** [comment]
Indeed looks like I forgot to commit that part, will do so later today.

**Comment by jekkos** [comment]
Should be all good now.

**Comment by daN4cat** [comment]
And all the changes in 3.0 too.

If testing is fine we close.

**Comment by odiea** [comment]
Yes all is well now so I will close this issue.
