### ISSUE TITLE
Receipt Printing

### ISSUE THREAD

**Issue by kasius2319** [jekkos/opensourcepos#431]
I can't automatically print the receipt after "sale completion" , i  try to check and uncheck the "print after sale" option but it doesnt work. Any solution on this.
Browser : latest mozilaa
Ospos version : 2.3.4
Os : windows 7 32 bits

Please help me

**Comment by odiea** [comment]
Have you tried adding the jsprint addon to Firefox? Do you have any printers listed under Store config receipt? You can also download the newer 2.4 master and see if you can print directly from the receipt.

**Comment by kasius2319** [comment]
tq.. the problem was jsprint extension.. i uninstall it and use seamless print extension for instead. Reset the mozilla firefox printer . anda then walla...Tq

**Comment by begench** [comment]
seamless print extension for mozilla worked perfect. thanks
