### ISSUE TITLE
 Item Quantity Changes unable to update the TOTAL payment.

### ISSUE THREAD

**Issue by kasius2319** [jekkos/opensourcepos#434]
I need to press ENTER when updating the item quantity(so that the total payment will updated). How make the total payment automatically updated when the item quantity is increased or decreased without pressing ENTER. Help me

**Comment by jekkos** [comment]
This is currently not foreseen. If we'd like to do that then we'll need to split up the page in components and refresh those that have dependencies on these input fields (in this case totals, error bar, etc). This is not a straightforward task and will probably only be done in scope of a broader rework of this functionality.

**Comment by daN4cat** [comment]
Register redesign is #401
