### ISSUE TITLE
Default behavior in the sales register page got changed in the bootstrap version 

### ISSUE THREAD

**Issue by RamkrishnaMondal** [jekkos/opensourcepos#435]
1. In the previous versions double clicking in the search boxes used to show 'list of items' and 'list of customers' respectively, but now you have to type something to get the list. 

2. 'Cash' used to be the default payment type, but now it is 'Debit card' by default.

**Comment by jekkos** [comment]
1. Functionally, in which case would this be useful? I've looked into that issue but it's not straightforward to fix using jquery-ui autocomplete
2. Issue to be confirmed

**Comment by RamkrishnaMondal** [comment]
1. With that functionality, a sale can be completed without touching the keyboard, but as you have mentioned it it hard to fix, let it remain as it is.
2. As most of the sales are in cash, it  should be the default payment type.  
3. Just noticed that, I can not send any email receipt/ email invoice with the config i used in the older version.  Can you please test the email functionality ? (I am using 'msmtp' with gmail on ubuntu 14.04).
Thanks.

**Comment by daN4cat** [comment]
I tend to disagree on the payment point, here most of the sales are debit card not cash. Therefore the change should be to set the list order.

**Comment by jekkos** [comment]
I just saw that a fork for this project has appeared with some changes related to payment method defintion. Might be interesting to see whether a pr will come up or not.

**Comment by jekkos** [comment]
https://github.com/KotieSmit/opensourcepos/commits/features

**Comment by RamkrishnaMondal** [comment]
@daN4cat  In that case, can you guide me, so that i can change the default payment to CASH for me ?

**Comment by odiea** [comment]
With notepad++ goto application/controller/sales in search type in credit and you should see the following lines I think after line 700. You can change it from there.
$data['payment_options'] = array(
			$this->lang->line('sales_cash') => $this->lang->line('sales_cash'),
			$this->lang->line('sales_credit') => $this->lang->line('sales_credit'),
			$this->lang->line('sales_debit') => $this->lang->line('sales_debit'),
			$this->lang->line('sales_giftcard') => $this->lang->line('sales_giftcard'),
			$this->lang->line('sales_check') => $this->lang->line('sales_check')

**Comment by Hillmax** [comment]
I noticed that when you remove or do not include the boostrap.js or boostrap.min.js link everything works normal

**Comment by odiea** [comment]
@jekkos  I took a look at the KotieSmit project and currently it's not terribly far along.

**Comment by daN4cat** [comment]
@odiea what is cashup? Cash tracking?

**Comment by odiea** [comment]
I had to google it myself. I have never heard it used before.

cash up
 vb 
1.  (Commerce) (intr, adverb) Brit (of cashiers, shopkeepers, etc) to add up the money taken, esp at the end of a working day
2.  (Banking & Finance) (intr, adverb) Brit (of cashiers, shopkeepers, etc) to add up the money taken, esp at the end of a working day

**Comment by odiea** [comment]
I think if you setup your takings with an employee name you would probably get the same without all the extra programming he did. But it would be nice to have a beginning of day cash entry done at the opening of the Sales day. I will add this to a enhancement.

**Comment by daN4cat** [comment]
I asked and it's the cash tracking. Should have a start of the day and end of the day. End of the is takings indeed.

Cash up is a British term, I wasn't aware of it. I asked my wife who told me what's about.

**Comment by odiea** [comment]
I think we are always the last ones to know.

**Comment by daN4cat** [comment]
Please note that with my latest change in sale edit (payment type change) the list of payments mode to Sale model.
The idea is that from that function the list can be loaded from the database, but that's not a trivial change as it might sound.

**Comment by daN4cat** [comment]
This is done.

Payment order is configurable and email setting too. I close.
