### ISSUE TITLE
Hungarian language for bootstrapUI (hu-HU)

### ISSUE THREAD

**Issue by joesalty** [jekkos/opensourcepos#438]
Hi!
I've translated to new language.
[hungarian_language.tar.gz](https://github.com/jekkos/opensourcepos/files/197521/hungarian_language.tar.gz)

**Comment by jekkos** [comment]
The translations are based on which version?

**Comment by joesalty** [comment]
I think the latest. I've downloaded yesterday.

**Comment by joesalty** [comment]
Sorry that I've just uploaded the files here. I never used github before. Just registered to upload my translation.

**Comment by jekkos** [comment]
Don't worry. We might need an updated version of your work for the feature/bootstrapUI branch as well.

**Comment by joesalty** [comment]
The translation is for bootstrapUI, and not for the "regular" version

**Comment by daN4cat** [comment]
Ok, set to 3.0 then. Please note that you will need to keep up with changes as we haven't completed everything yet.

**Comment by daN4cat** [comment]
@jekkos, 2.4 is done. Let's release it and move to 3.0.

**Comment by jekkos** [comment]
ok will do that later today.

**Comment by jekkos** [comment]
Integrated in bootstrapUI now. System files weren't translated but added anyway?

**Comment by daN4cat** [comment]
This seems completed.

By the way, switching to Hungarian to give a try I noticed that not everything gets translated:

- Store Config tabs stay in English
- Form buttons stay in English
- Cards (e.g. Debit Card) stay in English

I'll create a new issue to make sure everything can be translated.

**Comment by daN4cat** [comment]
@joesalty any chance you can look into the latest 3.0 and updated Hungarian translations?

**Comment by daN4cat** [comment]
@joesalty any feedback with regards to Hungarian translations?
