### ISSUE TITLE
Make all the strings in OSPOS translatable

### ISSUE THREAD

**Issue by daN4cat** [jekkos/opensourcepos#439]
As discussed in #438 not everything can be translated in other languages.

For instance the following are not:

- Store Config tabs is English only
- Form buttons stay is English only
- Cards (e.g. Debit Card) stay is English only
- Excel import feedback messages are English only

Probably more testing and verification should check what is not translated and needs a fix.

**Comment by daN4cat** [comment]
Store Config tabs translations sorted.

**Comment by daN4cat** [comment]
Excel import feedback messages translations sorted.

**Comment by daN4cat** [comment]
To be checked:
- account_details.php
- form_count_details.php

**Comment by jekkos** [comment]
NIce and imrpoved way to manage translations 

http://weblate.readthedocs.io/en/latest/admin/continuous.html

**Comment by jekkos** [comment]
However that means we would need to use gnu gettext to manage translations. This could be [easily converted ](http://stackoverflow.com/questions/6242067/converting-codeigniter-language-files-to-po-for-gettext ) using an existing script after which .po files can be loaded using [another addon](https://github.com/Marko-M/codeigniter-gettext).

I kind of like the idea that translators can be notified once something is added/modified. Right now a lot of people just translate once and then afterwards new things are added which leaves the language out of date once again.

**Comment by jekkos** [comment]
Also quite nice to see the github integration [with percentages on the badges for each langague](https://github.com/samaaron/sonic-pi)

**Comment by daN4cat** [comment]
Yes, the badgets is a good idea.
About translations, the idea here was to make sure the strings are all translatable. A different topic is to handle translations better.

**Comment by daN4cat** [comment]
@jekkos I had a look into the button labels translation and the dialog form ones are hacked out of the button name. That's really not scalable for any translation purpose.

I refer to the following: `label: btn_name.charAt(0).toUpperCase() + btn_name.slice(1)`

**Comment by jekkos** [comment]
You're right. This needs to be reworked. We'd better add another data attribute per button on the link with as value the translations?

Something like `data-button-submit="<?php echo $this->lang->line('common_submit')?>'`

**Comment by daN4cat** [comment]
Yes, better to have it as data attribute as you suggested.

**Comment by daN4cat** [comment]
With your change basically the buttons are declared adding extra attributes with translation attached, correct?

Looks fine. I will need to check what else is not translated now.

**Comment by jekkos** [comment]
Yes indeed.. also I added a php include that allows one to use CI translation in static js files (only needed in manage_tables for now)

**Comment by daN4cat** [comment]
I checked the translations and it's almost done, what's left is:

- drop down box writes "nothing selected" (e.g. Items view)
- notification position is in English (Store Config/General)
- payment options order is in English (Store Config/Localisation)
- various barcode drop downs are in English

**Comment by daN4cat** [comment]
I didn't check but it might be some notification message is not translated, especially the errors might take a while to spot. Let's leave them to bug reports...

**Comment by daN4cat** [comment]
I sorted the list above of last translation support, I believe this task is now completed.

**Comment by odiea** [comment]
@daN4cat . Thanks for putting in so much time on this project.

**Comment by daN4cat** [comment]
Yeah for the international community. We love to live in a global village :-)

**Comment by jekkos** [comment]
Ok thanks for taking care of this. It's kind of cool to see what work we've finished since 2.4, looks like a whole different app now.

**Comment by daN4cat** [comment]
Indeed a giant step.
