### ISSUE TITLE
How to track stock with unique serial number?

### ISSUE THREAD

**Issue by jimmykwh** [jekkos/opensourcepos#44]
When create new item, I noticed that is a check box for item with serial number but there is no place to input the serial. During the sales, when the item is selected, it require to input serial number.

Am I missing certain steps to input the serial number or the serial number is for information purpose only and not for detail stock tracking?

**Comment by jekkos** [comment]
serial should be put in the UPC/ISBN field on top of the item. If you put the number there then you should be able to retrieve it again in the register. The serialized item checkbox means that you won't be able to add more than 1 item at a time to the sales register.
