### ISSUE TITLE
E-mail settings

### ISSUE THREAD

**Issue by joesalty** [jekkos/opensourcepos#441]
It would be nice if we can change email settings (smtp, user name, password, etc) at the the store config menu.
Now, I think to other people is hard to find the proper file (system/libraries/email.php).

**Comment by daN4cat** [comment]
Thanks for creating this.

I remember you had another issue too around email. Would you mind to create a new issue for that?

**Comment by daN4cat** [comment]
Sorry I confused people. The email setting issue was mentioned in #435 as well, and there was a mention of an issue with invoice_email.

**Comment by daN4cat** [comment]
@ais-one would you like to work on this too?

**Comment by daN4cat** [comment]
> For email settings, it is easy and can be added to the config.

@ais-one sounds good. Thanks.

**Comment by daN4cat** [comment]
@ais-one any news?

**Comment by daN4cat** [comment]
I'm working on this.

**Comment by daN4cat** [comment]
In my last commit you can now configure the email, so people don't need to worry about what to do where to go.

The configurability options is what CodeIgniter offers: https://www.codeigniter.com/user_guide/libraries/email.html

**Comment by daN4cat** [comment]
@joesalty @RamkrishnaMondal hope you both are happy now.

**Comment by daN4cat** [comment]
Please test, but after having run the database update 2.4 to 3.0 script.

**Comment by odiea** [comment]
Looks like it works ok. I just tried the settings is all without sending email

**Comment by daN4cat** [comment]
I just noticed that there is something to fix in the store config page when it comes to save it.

**Comment by daN4cat** [comment]
Fixed.

**Comment by daN4cat** [comment]
Issue fixed.

**Comment by RamkrishnaMondal** [comment]
@daN4cat  I have already successfully implemented this in my dev machine in April but later i found that actually i don't need to configure email settings in ospos, l if i configure once in php.ini and in sendmail / msmtp. 
Anyway thanks for this add on.

**Comment by daN4cat** [comment]
Now you need to use this config means.

Sounds all fine and I close this.
