### ISSUE TITLE
invoice and receipt emails looks "ugly"

### ISSUE THREAD

**Issue by daN4cat** [jekkos/opensourcepos#442]
In #435 it's stated: `'invoice email' looks ugly with the extra spacing before and after each character. `

Invoice email should be checked and fixed.

**Comment by daN4cat** [comment]
even the receipt email looks inconsistent comparred to the printed one and not formatted correctly as discussed in #474

**Comment by daN4cat** [comment]
OK, fixed the email receipt

**Comment by saurabh261187** [comment]
![github](https://cloud.githubusercontent.com/assets/15091342/14788095/0ebee90a-0b24-11e6-9fb8-b36b2698bdbc.png)

I am now using the latest available version of OSPOS as on today. The PDF attached to the Sales Reciept has some alignment problems. What can be done to rectify this issues ?

**Comment by daN4cat** [comment]
My gutfeeling says that it's a font issue. It should be the font Lato, the same we use in the rest of OSPOS.

I noticed that pdf css selects a different one and probably that's causing the mismatch.

Feel free to fix and send over a change to close this.

**Comment by saurabh261187** [comment]
@daN4cat  , the earlier versions of OSPOS (about 2 years back) sent an email receipt to the customer directly, and had no PDF attached. Is it possible to enable that ?

**Comment by daN4cat** [comment]
Probably pdf is in place to avoid people tweaking invoices to make look like more money went out.
We send invoices in pdf form for that purpose.

I don't need invoice support and I just implemented the option to disable it from store config for that reason.
Therefore I'm out. 

Feel free to contribute it back.

**Comment by RamkrishnaMondal** [comment]
Well I did some research on this.  Solution is use a LOGO for your company. Problem arises only when you don't use a logo.

**Comment by daN4cat** [comment]
Around the invoice look'n'feel there are some other cases to consider see #530, #529

**Comment by daN4cat** [comment]
Is there any plan to do something with this and close? Email version of invoice is probably not that ok because of the font issue.

Receipt was sorted a while ago.

**Comment by jekkos** [comment]
Think it should be sorted as it's a regression indeed.

**Comment by daN4cat** [comment]
@jekkos could you please have a look as it's an invoice story so we close this issue?

**Comment by daN4cat** [comment]
I believe I fixed this issue with emailed invoice in pdf format being "ugly".
The issue appeared due to the company name, which is now always shown whether there is a company logo or not.

@saurabh261187 do you mind to test the latest master?

**Comment by RamkrishnaMondal** [comment]
Seems to be fixed.... thanks.

**Comment by jekkos** [comment]
@daN4cat great job fixing this.. I had a look at it for a couple of hours last week but couldn't find a solution. I remember I spent about an afternoon at first trying to figure out how these fonts were rendered. In the end I had to change something stupid and unrelated like remove a block or something. 
Also I checked history of the template and it didn't change for some time so that left me puzzled as well.

great job.

**Comment by daN4cat** [comment]
BTW it seems that if you add a tab in invoice_email in front of addresses or similar the pdf converter prints garbage. Something to bear in mind, maybe I should add a comment in the file so whoever touches it is aware.

**Comment by jekkos** [comment]
Yes think that'd be good. I also found that the pdf output isn't really reliable (as I think something seemingly unrelated breaks the font rendering in the whole document)

**Comment by daN4cat** [comment]
I didn't completely check but it's probably the <div> that was the issue. I moved the company name in a <pre> and removed the id as it was not styled anyway.

But it's not so obvious and I don't have really the time to understand what's causing it as to me this is not a required feature I just fixed because I noticed something strange whilst working on the send emails part.

**Comment by jekkos** [comment]
Ok no problem once I added it I got quite frustrated as I didn't understand why it broke either. The pre tags were used to render text newlines in html.
