### ISSUE TITLE
Error on item v2.4 - Can't use method return value in write context

### ISSUE THREAD

**Issue by gituncar** [jekkos/opensourcepos#443]
Hi, I have this error on v2.4 on items and receivings

**Fatal error: Can't use method return value in write context in C:\xampp\htdocs\opensourcepos\application\controllers\Items.php on line 123
A PHP Error was encountered

Severity: Compile Error

Message: Can't use method return value in write context

Filename: controllers/Items.php

Line Number: 123

Backtrace:

----

Fatal error: Can't use method return value in write context in C:\xampp\htdocs\opensourcepos\application\controllers\Receivings.php on line 373
A PHP Error was encountered

Severity: Compile Error

Message: Can't use method return value in write context

Filename: controllers/Receivings.php

Line Number: 373

Backtrace:

**Comment by daN4cat** [comment]
PHP version and XAMPP version please?

**Comment by daN4cat** [comment]
Any update?

If no answer by end of tomorrow I'll close this issue.

**Comment by daN4cat** [comment]
Probably this is an issue related to PHP version like in #452.

**Comment by daN4cat** [comment]
But @gituncar could we please know which setup you used?
