### ISSUE TITLE
Croatian language

### ISSUE THREAD

**Issue by JoeSoftDJ** [jekkos/opensourcepos#444]
How I can translate to Croatian language? What to do?

**Comment by joesalty** [comment]
Hi!

Take a look here: 
https://github.com/jekkos/opensourcepos/wiki/Adding-translations

**Comment by daN4cat** [comment]
Indeed, thanks for the link.

Once you have done you either submit the translations to github and go for a pull request (PR) or if you are not familiar with that, once you have translated everything and tested, just post a zip of the translations/*.csv here and one of us will take and integrate.

Please try to translate the latest master version 3.0.0 so we get the latest code translated.

**Comment by JoeSoftDJ** [comment]
thanks i wil.
