### ISSUE TITLE
Invoice, receipt

### ISSUE THREAD

**Issue by JoeSoftDJ** [jekkos/opensourcepos#445]
Did I (and how) change look for invoice and receipt?

**Comment by jekkos** [comment]
I have no clue what this issue is about. Please be a bit more specific

**Comment by daN4cat** [comment]
I assume that @JoeSoftDJ meant to ask how invoice and receipt layout can be changed, which files.

Just go to application/views/items and there you'll find receipt, invoice and email html+php+js files. Also bear in mind that css plays a role, so you need to check css files in css and then you need to regenerate the dist files (running grunt).

**Comment by JoeSoftDJ** [comment]
I thought two things.
First. Is it possible to have several looks invoices/receipt so that it is possible choose'
Secend.  How to do this?
I think it is now more specific.

**Comment by daN4cat** [comment]
So you meant templating invoice and receipt and be able to create and select them. Well that's not a trivial one if that's what you are after.

**Comment by JoeSoftDJ** [comment]
I mean that I can create, and user can choose one.

**Comment by daN4cat** [comment]
More than welcome to add new features. We need help.

**Comment by JoeSoftDJ** [comment]
Give me some advice, how to do that.

**Comment by daN4cat** [comment]
With #678 I submitted a means to support a simple selection of receipt templates.

**Comment by daN4cat** [comment]
OK, invoice templating could have been implemented with a similar approach, but I don't have the need.

**Comment by Dumidu** [comment]
Is there a way we can use a PDF invoice template?
