### ISSUE TITLE
Ajaxify OpensourcePOS

### ISSUE THREAD

**Issue by imskriaz** [jekkos/opensourcepos#446]
Hi,. Since POS need system serve, updated continuously,  It will be great if ajaxify OSPOS. Which will make more efficient.

**Comment by daN4cat** [comment]
More than welcome to contribute, we need help and some concrete example where you would see this being applied of course.

Please bear in mind that table part is under rework (#293) and sales/register + receiving is identified as next (#401).
Probably the diagrams part could be improved merging #342 and #130 and having things more interactive with the change you suggest.

**Comment by jekkos** [comment]
@imskriaz what you mean here is a single page web app? This would require a frontend redesign using a framework like react, ract.js or mithril.js and removal of php serverside view rendering. Also build system would need to be adapted. Not a straightforward change.

**Comment by daN4cat** [comment]
@jekkos where did you read single page web app?

**Comment by jekkos** [comment]
So what is this issue about then, ajaxify what exactly? I think we need to choose to either keep all view state server side as it is now or move completely to the client. If you want to do too much ajax using this  setup then complexity will go up real fast and you'll need to take care of a lot of low level things that you shouldn't need to care about. I've been there and I know that using only jQuery to implement more complex refresh cycles just doesn't work.

**Comment by daN4cat** [comment]
Got the point. I believe past this 3.x milestone we need to rethink the view side of the story.
Use RESTful or WebSocket between a thicker view on client side and controller on server side?
Then if that's the case your proposal to use a different way to design the view/UI side on web client comes into the picture.
All php of the view is removed. But that's a big job for a 4.x probably.

**Comment by jekkos** [comment]
Yes that's exactly what I mean. With simply 'ajaxifying' a whole set of other concerns will rise, like componentization of the screen, binding event handlers after updating dom with new content, defining dependencies between these components.. after all you're tying more logic to the DOM which is not always a good thing. This is one of the reasons why all of these 'frameworks' came to live.

I guess that would be for a 4.x indeed. In 3.x we tackled most of the css and js only, with no real architectural changes.. so good enough for now.

**Comment by daN4cat** [comment]
Agreed.

**Comment by jekkos** [comment]
Closing this issue as it's too vague or has been discussed before.
