### ISSUE TITLE
Switching templates no glyphicons?

### ISSUE THREAD

**Issue by odiea** [jekkos/opensourcepos#448]
When you use the template glyphicons do not show on forms or on the calendar for Takings. No arrows.
Version 3.

**Comment by daN4cat** [comment]
Part of #409 I would say.

**Comment by RamkrishnaMondal** [comment]
@odiea  To show the Glyphicons, put the respective bootstrap.min.css file in the 'dist' folder and call it in the template header.

**Comment by odiea** [comment]
Thanks. I have already done that but I cannot get them to show until I add the bootstrap min css from the main program then add the bootstrap min from the template.

**Comment by daN4cat** [comment]
@odiea see my last commit to master because I fixed the glyphicon path issue.

You need to check what I added in spacelabcss/style.css and add that to your one if you added other styles in your file.

I close this issue.

**Comment by odiea** [comment]
Thanks. I will give it a try.

**Comment by daN4cat** [comment]
You can revert any other change related to copy files in dist and etc.
I also fixed the grunt script file to update spacelab header.php correctly. So now onwards changes in css and js files will be reflected in spacelab. Let me know if there are other problems with templates.
