### ISSUE TITLE
Discount

### ISSUE THREAD

**Issue by jimmykwh** [jekkos/opensourcepos#45]
Is it possible to have further discount on subtotal value after tax?

**Comment by jekkos** [comment]
It depends on what pricing strategy you are using

At this moment discounts are applied on the value before tax (if prices are tax excluded).
If prices are tax inclusive then discounts are applied on the subtotal after tax, indeed.

**Comment by jimmykwh** [comment]
Hi Jekko,

Great to hear from you.

Its the practise in my country; Malaysia, where by custimer ask for round
up total payable. For instance  sub total 3.20,  they will ask for 3 bucks
to settle the bill.

**Comment by jekkos** [comment]
This functionality is currently not foreseen.
