### ISSUE TITLE
Error after updating ospos on localhost.

### ISSUE THREAD

**Issue by disearth** [jekkos/opensourcepos#450]
I have updated database as well as script after that I am getting the attached error.
![screenshot_6](https://cloud.githubusercontent.com/assets/10373819/14293616/fd9e4ce0-fb8a-11e5-94fb-a5f8d3e5073a.png)

**Comment by jekkos** [comment]
Looks like you have misconfigured the session table.. check your config.php file for session table name

**Comment by disearth** [comment]
These are the configration in config file
$config['sess_driver'] = 'database';
$config['sess_cookie_name'] = 'ospos_sessions';
$config['sess_expiration'] = 7200;
$config['sess_save_path'] = 'sessions';
$config['sess_match_ip'] = FALSE;
$config['sess_time_to_update'] = 300;
$config['sess_regenerate_destroy'] = FALSE;

&

This is my table name http://prntscr.com/aojzsb

**Comment by odiea** [comment]
Have you used the 2.3.4 to 2.4 script. That has the latest sessions table.

**Comment by disearth** [comment]
cheers worked !

**Comment by arteiro** [comment]
Mostrando tradução para Olá, não falo ingles, então estou usando o google. Quando instalo localmente funciona tudo - (php 5.6) porém quando coloco em servidor WEB a página de itens http://site/index.php/items aparece em branco, sem nada para descrever. Os outros módulos funcionam normalmente. no log do servidor está este problema: [05-Apr-2016 16:17:23 America/Sao_Paulo] PHP Fatal error: Can't use method return value in write context in /home/site/public_html/venda/application/controllers/Items.php on line 112 linha 112 : 'isdeleted' => !empty($this->input->post('is deleted')) [05-Apr-2016 16:17:38 America/Sao_Paulo] PHP Warning: ini_set() has been disabled for security reasons in /home/site/public_html/venda/index.php on line 70. linha 70 : ini_set('display_errors', 1); PHP 5.4.19 no servidor.
Em vez disso, traduzir Olá, não falo ingles, então estou usando o google. Quando instalo localmente funciona tudo - (php 5.6) porém quando coloco em servidor WEB a página de itens http://site/index.php/items aparece em branco, sem nada para descrever. Os outros módulos funcionam normalmente. no log do servidor está este problema: [05-Apr-2016 16:17:23 America/Sao_Paulo] PHP Fatal error: Can't use method return value in write context in /home/site/public_html/venda/application/controllers/Items.php on line 112 linha 112 : 'is_deleted' => !empty($this->input->post('is_deleted')) [05-Apr-2016 16:17:38 America/Sao_Paulo] PHP Warning: ini_set() has been disabled for security reasons in /home/site/public_html/venda/index.php on line 70. linha 70 : ini_set('display_errors', 1); PHP 5.4.19 no servidor.
Hello, I do not speak English, so I'm using google.
When I install locally everything works - (php 5.6) but when I put on the web server page items http: //site/index.php/items appears blank, with nothing to describe. The other modules function normally.
in the server log is this problem:
[05-Apr-2016 16:17:23 America / Sao_Paulo] PHP Fatal error: Can not use method return value in write context in /home/site/public_html/venda/application/controllers/Items.php on line 112
Line 112: 'isDeleted' => empty ($ this-> input-> post ('is deleted'))
[05-Apr-2016 16:17:38 America / Sao_Paulo] PHP Warning: ini_set () Has Been disabled for security Reasons in /home/site/public_html/venda/index.php on line 70.
70 line: ini_set ('display_errors', 1);
PHP 4.5.19 on the server.

**Comment by jekkos** [comment]
@arteiro looks like a config issue with your hosting provider. I think they're being a bit too restrictive as they are blocking you to change timezoine settings. Try to set tz to default and check whether the error disappears

**Comment by daN4cat** [comment]
Better to update to PHP 5.5 on your server.
