### ISSUE TITLE
currency symbol

### ISSUE THREAD

**Issue by JoeSoftDJ** [jekkos/opensourcepos#451]
I set chek box currency symbol and nothing happend. Curency symbol stay on left side.

**Comment by daN4cat** [comment]
Where exactly do you see this?

**Comment by odiea** [comment]
I tried this on my install and the symbol never switches to the right side. I changed the currency symbol and I still got the same result. Is this language specific?

**Comment by JoeSoftDJ** [comment]
on form sale, receving, item ...

**Comment by odiea** [comment]
It did work on 2.3.3.

**Comment by daN4cat** [comment]
Ok, I wouldn't that with the decimals change I introduced an issue around this feature. I'll test and fix next days.

**Comment by jekkos** [comment]
Correct I think I forgot to add that change when I was upgrading the forms

**Comment by daN4cat** [comment]
The form is an obvious, but I don't understand the rest.

**Comment by jekkos** [comment]
Fixed in master.

**Comment by daN4cat** [comment]
Not completely I'm afraid....

**Comment by daN4cat** [comment]
Also check Items, the symbol is not changing side. Something must be fixed in the locale_helper.php

**Comment by jekkos** [comment]
Symbol should show in the right place now (in tables also)

**Comment by daN4cat** [comment]
All works fine.
