### ISSUE TITLE
Support PHP5.4 (Error after updating ospos on web server)

### ISSUE THREAD

**Issue by arteiro** [jekkos/opensourcepos#452]
Issue discussed in #450 

When I install locally everything works - (php 5.6) but when I put on the web server page items http: //site/index.php/items appears blank, with nothing to describe. The other modules function normally.
in the server log I see this problem:
[05-Apr-2016 16:17:23 America / Sao_Paulo] PHP Fatal error: Can not use method return value in write context in /home/site/public_html/venda/application/controllers/Items.php on line 112
Line 112: 'isDeleted' => empty ($ this-> input-> post ('is deleted'))
[05-Apr-2016 16:17:38 America / Sao_Paulo] PHP Warning: ini_set () Has Been disabled for security Reasons in /home/site/public_html/venda/index.php on line 70.
70 line: ini_set ('display_errors', 1);

PHP 5.4.19 on the server.

**Comment by odiea** [comment]
Please be aware that at least PHP 5.5 is required then double check php5-gd is present. As the Installation states.

**Comment by daN4cat** [comment]
Yes, try to set PHP 5.5

**Comment by arteiro** [comment]
Unfortunately does not have to interfere with the hosting, the provider says only with automatic updates and has not forecast the next. I do not know how I can use on the web. then will only location. Thank you.

**Comment by daN4cat** [comment]
OK. Can you try on your local to set PHP 5.4.19 and see if you get the same issue?
So we understand if the issue is that or something else.

**Comment by arteiro** [comment]
Ok, I installed a version of WAMP with PHP 5.4.16 and it is the same error locally. What do I do?
![erroospos](https://cloud.githubusercontent.com/assets/18253035/14320578/fe30c604-fbeb-11e5-9f26-b1aad0d63de4.jpg)

**Comment by daN4cat** [comment]
We need to think about and see if we can make it to work with PHP 5.4 too.

**Comment by daN4cat** [comment]
But what about the second error ini_set()? In index.php is that present with 5.4?

**Comment by arteiro** [comment]
Yes the error in index.php also 5.4.
So thank you and I hope they can make it work on 5.4 for where lodge some sites slow to update. As I found very good system, I am using the web what works and place the items, and frequently update the data in a parr other BD.
Thank you.
Ps. I made a translation of pt-BR as it becomes part of the official project.

**Comment by daN4cat** [comment]
Thank you for the help with the test. Let see what we can do. And thanks for the translations too.

**Comment by daN4cat** [comment]
I fixed the Items.php line 112 issue with PHP5.4.

However the index.php line 70 related to ini_set() is something different and it's not related to PHP5.4.

@arteiro please take the latest master and test

**Comment by arteiro** [comment]
Hello,
I do not know what they did, the more I copied all the new changes of hours ago about the files on the server as the Portuguese translation is all there, and began to operate the module items even in PHP 5. 4. 19, I think now everything is solved ..
I am attaching two translation files found error. already corrected
Hugs
Thank you
[items.zip](https://github.com/jekkos/opensourcepos/files/210813/items.zip)
