### ISSUE TITLE
show quantity on Receivings reports

### ISSUE THREAD

**Issue by walterhumphreys** [jekkos/opensourcepos#453]
hi, i dont know if maybe im missing something, but i have to doubts 1 in Receivings reports or sales reports what does the count stands for and how can i get to retrieve quantity amount on Receivings reports

**Comment by sgr1875** [comment]
I was about to write about it its there already :)

**Comment by daN4cat** [comment]
Receiving is not that supported / used. Probably you need to investigate a bit and maybe suggest improvements and implement it. That would be highly appreciated.

There is already #404 for improvement suggestion.

**Comment by jekkos** [comment]
Not that hard to add an extra field in that report. Just edit reports controller + detailed_receivings model. Play around with existing code a bit and you'll find out how it works easily.

**Comment by daN4cat** [comment]
... and please send us the change so we integrate.

**Comment by odiea** [comment]
The biggest issue I see is how to pull data from ospos_receivings_items to get more info from the receivings_id because the report is based on just the ospos_receivings table.

**Comment by odiea** [comment]
Never mind . That info is there already.

**Comment by walterhumphreys** [comment]
My bad as well

**Comment by daN4cat** [comment]
So, is the issue the fact that is called count? Or else?

**Comment by walterhumphreys** [comment]
Count is d same quantity as far as i was checking. Because i made the comparison

**Comment by walterhumphreys** [comment]
Count is d same quantity as far as i was checking. Because i made the comparison

**Comment by daN4cat** [comment]
So it's a matter of changing the label. I remember I introduced some time ago count for cases like payments, gift card and etc. It could be that the label has changed in places where it should have been quantity. I'll check and fix.

**Comment by daN4cat** [comment]
Fixed, now it's quantity in most Reports but still some has count because in the end it's a count (e.g. number of times a discount is applied)
