### ISSUE TITLE
data base error after updateing

### ISSUE THREAD

**Issue by walterhumphreys** [jekkos/opensourcepos#454]
Error Number: 1054

Unknown column 'session_id' in 'where clause'

SELECT * FROM (`ospos_sessions`) WHERE `session_id` = '498e2d1993e6847141a40357f8c7a11e'

Filename: libraries/Session.php

Line Number: 229

**Comment by JoeSoftDJ** [comment]
I think you must update database from ver 2.3.X to 3.0

**Comment by daN4cat** [comment]
You are missing the update to 2.4 of the database. Session table changed with Code Igniter 3

**Comment by daN4cat** [comment]
Duplicate of #450

**Comment by walterhumphreys** [comment]
Error Number: 1054

this the error message sorry for didnt posted it

Unknown column 'session_id' in 'where clause'

SELECT * FROM (`ospos_sessions`) WHERE `session_id` = '498e2d1993e6847141a40357f8c7a11e'

Filename: libraries/Session.php

Line Number: 229
