### ISSUE TITLE
Can not add / Change 'Customer Name' from Sale edit page  

### ISSUE THREAD

**Issue by RamkrishnaMondal** [jekkos/opensourcepos#455]

**Comment by daN4cat** [comment]
Version please

**Comment by RamkrishnaMondal** [comment]
Latest Master, downloaded 2 days ago.

**Comment by JoeSoftDJ** [comment]
I can.

**Comment by daN4cat** [comment]
OK, so what is the issue then?

@RamkrishnaMondal could you provide the correct sequence and data you input to reproduce this issue? I don't want that some special character in your language triggers the issue.

**Comment by RamkrishnaMondal** [comment]
I am using English version, no special character at all...... even tried creating new DB. The name in edit page used to show the name along with person id, it's only showing name now.
![screenshot from 2016-04-06 23 24 54](https://cloud.githubusercontent.com/assets/14151032/14327371/9daa0ebc-fc4f-11e5-86fc-bf296c9b11fe.png)

**Comment by RamkrishnaMondal** [comment]
With v2.3.3 with same db....

![screenshot from 2016-04-06 23 33 11](https://cloud.githubusercontent.com/assets/14151032/14327462/0690f72e-fc50-11e5-8c98-5d3a7e47381b.png)

**Comment by daN4cat** [comment]
Got it, there is no suggestion / autocompletion.

@jekkos you may want to look into this since you dealt with the suggestion change.

**Comment by RamkrishnaMondal** [comment]
Even if I change it without suggestion, it is not saving.

**Comment by jekkos** [comment]
All done now. Can you confirm if it works for you?

**Comment by RamkrishnaMondal** [comment]
@jekkos  It's working now. Thank You. 

Please take care of the 'invoice email', I use it a lot.
