### ISSUE TITLE
'Check' Vs 'Cheque'  

### ISSUE THREAD

**Issue by RamkrishnaMondal** [jekkos/opensourcepos#456]
Excepting USA, it's 'cheque' everywhere. Can not understand why OSPOS uses 'check' instead of 'cheque' ? 
http://grammarist.com/spelling/check-cheque/

**Comment by daN4cat** [comment]
Me neither but I didn't bother about it too much.

**Comment by jekkos** [comment]
You can easily correct spelling mistakes by editing csv file on githbub directly and send us pull request

**Comment by daN4cat** [comment]
Maybe the payment story should be changed.

We should have a means to add in the config the list of payments with the translation, so people can name it as they want, order as they want and etc.

It's like the stock location feature, just add a list.

**Comment by daN4cat** [comment]
Of course Giftcard needs to be in as last in the list.

**Comment by jekkos** [comment]
Ok indeed I see every store probably has it's own preference there. Good idea for this enhancement

**Comment by daN4cat** [comment]
Here we go, the payment options order is now available in Store Config localisation.
