### ISSUE TITLE
change default payment

### ISSUE THREAD

**Issue by JoeSoftDJ** [jekkos/opensourcepos#457]
In sale form first peyment (default) is defit card. How I can change default peyment eg. cash?

**Comment by JoeSoftDJ** [comment]
sory in typing, not defit card but correctly debit card.

**Comment by daN4cat** [comment]
See #435 , same topic.

**Comment by JoeSoftDJ** [comment]
thanks

**Comment by daN4cat** [comment]
As discussed in #456 payments should be configurable like stock location.
