### ISSUE TITLE
Decimal separator

### ISSUE THREAD

**Issue by JoeSoftDJ** [jekkos/opensourcepos#458]
I change decimal separator to "," and thousend to ".". But in sale form when I type 1,5 I get error editing item. If I type 1.5 there is no error. Also price in the same form is with dot "." separator not with comma ",". How do I change? On other forms it's correct.

**Comment by daN4cat** [comment]
Do you think you can help us with this issue?

We need help.

**Comment by JoeSoftDJ** [comment]
Yes I would, but sey how. I am noobe.

**Comment by JoeSoftDJ** [comment]
Also I have idea to add. In croatia law we must some extra data in recept and invoice. I would glade do this, but some one must guide me how.

**Comment by daN4cat** [comment]
Currency locale is dealt in application/views/partial/locale_helper.php when it comes to print it out.
See to_currency function for instance..

When it comes to input, you need to go to application/views/sales/register.php (view in sales when you do a sale), or application/views/items/form.php (pop up in Items when you edit or add a new item).

Probably you need to control the way the currency value is input and validated. It would be good to have a function in locale_helper.php to validate the input according to the config. See example to_currency for reading the configuration and know decimal point and thousand point.

**Comment by jekkos** [comment]
@JoeSoftDJ Indeed just add a global parse function for quantity and currency in same file that contains the current helpers. Sonuds like a nice programming exercise

**Comment by daN4cat** [comment]
@JoeSoftDJ now that translations are sorted I leave to you the work on this.

Try to figure out what to do based on what we suggested.

**Comment by jekkos** [comment]
I found that php offers a builtin function to do a parsing of decimals using a configured locale. Maybe we should stick to this for both input/output (instead of having an explicit decimal separator)? Or should we keep this separator and try to do the parsing ourselves?

Actually I'm not really a fan of the latter as there might be special situations we don't know about for exotic locales. Think it's best to stick with system support for these kind of things (easier for us in the end). Same goes for most operating systems.

**Comment by jekkos** [comment]
We might just want to stick using php builtin formatting for currency using the set locale as well

https://akrabat.com/using-phps-numberformatter-to-format-currencies/

**Comment by jekkos** [comment]
The same for timezones. We should just use php to enumerate all possibilities instead of listing them ourselves

**Comment by daN4cat** [comment]
Sorry the link you provided made me laugh, dated 2013 and stating UK and €. uh? That's pure anarchy in today's light. Bloody Brexit crappyness..

**Comment by daN4cat** [comment]
Besides my silly statement it would make sense indeed to revert to php standard locale support provided we don't mixup server configuration, php.ini one and etc. like the guy with the Russian language and excel import issue.

**Comment by jekkos** [comment]
Yes sad story for the UK people .. too bad no politician wants to take responsibility for what they caused?..  This isn't  going to benefit anyone in the end

**Comment by jekkos** [comment]
You're always welcome to grab some beers in Brussels anytime

**Comment by daN4cat** [comment]
Nobody indeed

**Comment by daN4cat** [comment]
Yes I should and maybe look for a job there again. I lived 4 years in Brussels and my wife has family there.

**Comment by jekkos** [comment]
I will try to replace decimal separator, currency symbol, thousands separator with one locale setting for number formatting. Have whipped up some code currently and will test a bit further to see whether this works fine.

Also I might want to check if I can derive the currency symbol position from this locale setting or not . For the config part I'll just add one drop down in replacement of the old ones. To show the user what exactly he can expect from this setting I will add a number formatting example after the dropdown as seen in most OS configuration dialogs.

**Comment by jekkos** [comment]
Do mind that i need to install an extra php extension to enable locale support, being

`sudo apt-get install php5-intl`

I tihnk it might be good to have it installed after all as setting locale correctly will solve some possible bugs with utf-8 import as seen before.. Important here is that we document what is needed to set it up correclty (just to avoid people reporting too many bugs)

**Comment by daN4cat** [comment]
Mhhhh do we really want to do that in 3.0? We will get people reporting that it doesn't work because they don't have that php extension.

**Comment by jekkos** [comment]
I understand the concern.. of course we'll need to mention it explicitly in the upgrade guide. Beside that some basic explanation on howto troubleshoot and then hopefully most users will know what to do? I'll try to finish the patch (prolly tomorrow) so you can first try and see which kind of issues come up...

then we can still decide to include it or not

**Comment by odiea** [comment]
I enabled it in xampp so I will give it a try.

**Comment by jekkos** [comment]
I've added the locale support in latest commit. Also [find a page on the wiki](https://github.com/jekkos/opensourcepos/wiki/Localisation-support) that explains how to set this up correctly. There's a link from a tooltip to this new page.

Lcoale selection will determine the currency symbol by default. This symbol can be overridden by the user afterwards. Currency position is derived from the set locale (and thus the config option is gone now). 

After a user types in the locale code this one will be validated using jquery validate and error will be shown if it's incorrect or unknown.

I have also added a git version string to the footer so people can include it when reporting bugs. In this case we know exactly about which revsion they're talking.

**Comment by jekkos** [comment]
Think we should try to use wiki more often from within the application and so we can cross reference the issues that discuss the topic at hand. Some kind of world wide ospos web (wwow)

**Comment by jekkos** [comment]
One thing the NumberFormatter does it define a formatting mask for a selected locale. This mask can also be edited by hand (but we're currenty not exposing it directly). This is how I currently read out the currency position info.

**Comment by odiea** [comment]
Boy this really screwed up my side. Can you make this configurable?

**Comment by daN4cat** [comment]
Working or not? I don't get it...

**Comment by odiea** [comment]
Yes It is working now.

**Comment by daN4cat** [comment]
I was travelling so didn't have the time to look into this.
I just did a quick test and of course I don't have php5-intl installed on my VPS.
That means I need to recompile Apache and PHP, not big deal but I'm pretty sure a lot of people will complain that their shared web hosting doesn't work nor support this....

Are we really sure we want to pursue this? I make it clear, I will ignore all those complaints as I don't want to spend time with something that I don't fell it's totally usable. Killing your users by over-engineering is not a good approach in my opinion.

**Comment by daN4cat** [comment]
OK, one could argue that the match library is another example that requires customisation, I can't remember if that was in the default build on my VPS but I can look into that later.

**Comment by daN4cat** [comment]
I just fixed a minor thing with a small refactoring, also regen the database scripts as not all were fine.

Recompiled Apache & PHP with intl and all works fine, however now I find that setting en_UK I'm forced to have the thousand separator `,` where I really didn't want and I could remove with the previous setup.

**Comment by jekkos** [comment]
Ok I understand the annoyance but I wanted to make this configuration setting as flexible as possible. I just found it unefficient to rewrite all this formatting / parsing code myself while there is functionality readily available that does it for us. One could argue that there is now less code to maintain because  we can rely on an widely used and tested php extension. Also intl offers support for timezones which we are now maintaining ourselves. Also gettext support is integrated which could be useful for moving to weblate for managing translations later on.

Of course downside is that users might need to reconfigure their setup. For most shared hosting configuration this should just be a matter of enabling it through cpanel or webmin. On the other hand these are not ospos issues and people should in that case talk to their hosting companies.

UNder the hood the formatter uses a formatting mask and if you want I'll re add the decimal separator option as well. Then it's just a matter of setting the attribute on the formatter to enable it or not.

**Comment by daN4cat** [comment]
Maybe the thousand separator reintroduction would be good to have back.
It just keeps the number more compact, although in my case it's just the sum. We don't sell anything worth at least £1000 !!! I wish though.

**Comment by jekkos** [comment]
I have added again the thousands separator option. Hope we can close this one.

**Comment by daN4cat** [comment]
It doesn't work I'm afraid. Unchecked box but I still see the thousand separator.

**Comment by daN4cat** [comment]
Apologies, I forgot to copy a file and that's why it didn't work for me.

It looks all fine and working. I close.
