### ISSUE TITLE
Generate Croatian languages

### ISSUE THREAD

**Issue by JoeSoftDJ** [jekkos/opensourcepos#460]
I translate all csv file in dir translations, then I start generate_languages.php and got  nex error
Greška 404
Oops! That page can’t be found.
Where I made mistake?

**Comment by daN4cat** [comment]
Not sure, it seems a problem with your setup because the guy in #461 just did the Brazilian translation with no issue.

**Comment by JoeSoftDJ** [comment]
I saw that few minute ago and stil don't know. 
OK
I download new version and install again

**Comment by daN4cat** [comment]
Let us know how it goes.

**Comment by daN4cat** [comment]
@JoeSoftDJ sorry, I forgot about this.... please check .htaccess because generate_languages.php is protected. If you run from a non local machine or else your IP will be blocked.

See in .htaccess: 
```
# prevent access to generate_languages.php
<Files generate_languages.php>
 order deny,allow
 deny from all
 allow from 127.0.0.1
 
# My IP(s)
#  allow from xxx.xxx.xxx.xx

</Files>
```

**Comment by daN4cat** [comment]
remove the # in front of allow from xxx.xxx.xxx.xxx and replace xxx with your IP numbers.

**Comment by JoeSoftDJ** [comment]
still not working

**Comment by daN4cat** [comment]
OK, resync with latest master (you'll get the Brazilian translation) and please re-add the Croatian to translations/*.csv files.

Once that's done, zip the content of translations and system/language for Croatian and post it here. I'll do the rest for you.

**Comment by JoeSoftDJ** [comment]
I do not give up eazy. 
I delete .htaccess and rename generete_lenguages.php to gen.php and viola. I got file. 
What next to test them?

**Comment by daN4cat** [comment]
You need to add the language support in config file and then change the language in store config / Locale

**Comment by JoeSoftDJ** [comment]
I do that and error occur 
"Unable to load the requested language file: language/hr/pagination_lang.php"

**Comment by daN4cat** [comment]
you need to match the two, they cannot be different

**Comment by daN4cat** [comment]
it's either all hr or hr-HR

**Comment by JoeSoftDJ** [comment]
I have not dir hr-HR in system/lenguage, only in application/language/

**Comment by daN4cat** [comment]
You need to create one in system/language and copy the files from en (english) and traslate them. They are used too.

**Comment by JoeSoftDJ** [comment]
@daN4cat as you mentioned before
OK, resync with latest master (you'll get the Brazilian translation) and please re-add the Croatian to translations/*.csv files.
Did you thougth that I must copy&paste my translations in new csv file with brazilian translation.

**Comment by daN4cat** [comment]
Yes, I meant: please take the latest code from master (the one I just updated) and add your translation against that one along Portuguese translation as additional column.

I don't have time to merge translations files I'm afraid.

**Comment by JoeSoftDJ** [comment]
Allmost I finis. Then I PR. If problems apper, I will write about,

**Comment by daN4cat** [comment]
OK, resync with master before going for a PR

**Comment by JoeSoftDJ** [comment]
Failed to open PR. Sending translated files.
[croatian.zip](https://github.com/jekkos/opensourcepos/files/211861/croatian.zip)

**Comment by daN4cat** [comment]
OK, committed in master.

I had to copy and paste hr-HR because some Portuguese translations were old and there was a mistake in one line. I hope to have fixed properly with two copy and paste.

Also there were two mistakes in system language causing an error, I fixed those as well.

All is fine at least testing different views and forms. I didn't test with sales and etc.

I close this.

**Comment by JoeSoftDJ** [comment]
I have some question?
How I can correct some translations, besause some of them is incorrect.
Some stay in hungary translations.


2016-04-10 23:51 GMT+02:00 FrancescoUK <notifications@github.com>:

**Comment by daN4cat** [comment]
Take the csv files from traslation and change the last column.
I put in the last on purpose because I spotted that some were not translated.
Once done send it over here and I'll update.

**Comment by jekkos** [comment]
@daN4cat thanks for handling this pr.

**Comment by daN4cat** [comment]
@JoeSoftDJ any news on the translation update? I was under the impression that some Hungarian was popping up instead of Croatian.

**Comment by daN4cat** [comment]
@JoeSoftDJ any chance you can look into the latest 3.0 and updated Croatian translations?

**Comment by JoeSoftDJ** [comment]
yes. temporary I am busy, but in next few day meybe.

2016-06-22 19:05 GMT+02:00 FrancescoUK <notifications@github.com>:

**Comment by daN4cat** [comment]
@JoeSoftDJ have you managed to update your translations? Please check the latest master for a couple of additions.
