### ISSUE TITLE
Tradução pt-BR

### ISSUE THREAD

**Issue by arteiro** [jekkos/opensourcepos#462]
Portugues (Brazilian) translation

**Comment by daN4cat** [comment]
Yes, please just send the zip of translation directory. We will do the rest.

**Comment by daN4cat** [comment]
I mean post it here.

**Comment by arteiro** [comment]
Translation to Portuguese of Brazil pt-BR
[opensourcepos-pt-BR.zip](https://github.com/jekkos/opensourcepos/files/206780/opensourcepos-pt-BR.zip)

**Comment by daN4cat** [comment]
It looks like giftcard_lag.csv was not translated. Could you please check and send just the translations file?

**Comment by daN4cat** [comment]
Also all the files in system are in English not in Portuguese.
You are better checking the changes you sent over.

**Comment by daN4cat** [comment]
OK, I looked back in your repository and found all the system files. It seems like you overwrote those. And I reversed the giftcard translations from the translated file. A bit of a tedious job.

However not all the translations are completed, but I'm afraid that's something I cannot do for you.

**Comment by arteiro** [comment]
Hello,
Sorry not to be so full, I have done translations of appearing on the frontend, pporém continue making improvements in translation. I have some difficulties not speak English then do what I can understand. I'm still making some corrections in grammar, to make it intelligible and command label for públlico Brazilian. I'm using OSPOS for my craft store and I like it a lot, so I decided to collaborate. Soon send more patches. Forgive me if I become boring with requests for help, but I want OSPOS become an excellent and useful program mainly ara quenos retailers like me. I'm still trying to understand how to use github, because I'm not programmed, only curious informatica.Obrigado by force that has provided with this project. Once you correct the faults in translation send comment to you and attachments.
Hugs

**Comment by daN4cat** [comment]
OK, no worries. I included most of your translations, so when you have new ones let me know that I'll integrate them.

**Comment by arteiro** [comment]
I made some corrections and add the missing, just could not generate via generate_languages.php my local server freaked ....
I spot tests and the web was all right. I found some errors in datepicker_lang.php, forgot some lyrics. fix my base, I'm not sending them because I am not programmer as I said. So I hope that my contribution is useful.
Hugs
[opensourcepos-pt-BR.zip](https://github.com/jekkos/opensourcepos/files/209476/opensourcepos-pt-BR.zip)

**Comment by arteiro** [comment]
I continue correcting any error in translation. I hope to help.

**Comment by arteiro** [comment]
Thank you

**Comment by daN4cat** [comment]
You latest translation is now in master. Please take latest master for any more change because I added one translation due to another change. Portuguese translation for that is fine.
