### ISSUE TITLE
A sale can be completed with ZERO value v3.0 

### ISSUE THREAD

**Issue by RamkrishnaMondal** [jekkos/opensourcepos#463]
If I try to sale item(s) with zero value, no 'add payment' button appears, but 'complete' button appears directly and sale can be completed. Is it intentional or a bug ? 

The sale receipt looks like this...
![screenshot from 2016-04-07 00 11 58](https://cloud.githubusercontent.com/assets/14151032/14328686/66cae6ae-fc55-11e5-8dcc-8d31b2186649.png)

**Comment by jekkos** [comment]
This is expected behavior. No more paymente can be added once payment due equals 0. In this case you can just complete the sale.

**Comment by daN4cat** [comment]
Works as per design.

**Comment by jekkos** [comment]
Is there  any usecase that would justify changing this behavior?

**Comment by daN4cat** [comment]
Guys, let's not look for what nobody will ever do....
