### ISSUE TITLE
"datepicker_daysmin_sunday (TBD)"    V3.0

### ISSUE THREAD

**Issue by RamkrishnaMondal** [jekkos/opensourcepos#465]
Please see this image of the 'Sales Taking' page:
![screenshot from 2016-04-07 19 32 00](https://cloud.githubusercontent.com/assets/14151032/14355092/695c2c86-fcfd-11e5-920c-a12c90a35dc8.png)

**Comment by daN4cat** [comment]
I fixed this already but probably I forgot to commit the change. I'll check it later.

**Comment by daN4cat** [comment]
@RamkrishnaMondal could you please check with the latest master because I believe I fixed this yesterday and the code seems in master.

**Comment by RamkrishnaMondal** [comment]
Just downloaded and tested..... issue is fixed now.

Thanks.
