### ISSUE TITLE
Possible bug in Items New Master.

### ISSUE THREAD

**Issue by odiea** [jekkos/opensourcepos#466]
I was playing around with Items. I chose a Date or used a filter where No items to display shows. I clicked on the table sorter and a few items appeared. I then went to edit the Item and it appears to loose its css or something. The  form does not show correctly.

**Comment by daN4cat** [comment]
I can see that just filtering to empty and then clicking the sorter produces a strange view:

![image](https://cloud.githubusercontent.com/assets/636048/14366538/0c8705a4-fd0b-11e5-8baf-53f8f7102a9c.png)

**Comment by daN4cat** [comment]
The clicking edit of the first item:

![image](https://cloud.githubusercontent.com/assets/636048/14366562/35e24562-fd0b-11e5-8fe4-8d85d62c087a.png)

**Comment by daN4cat** [comment]
The same if you click inventory and transactions history.

**Comment by odiea** [comment]
Strange isn't it? I was testing my filter and came across this.

**Comment by daN4cat** [comment]
Not sure why sorting the table brings up those items. It's some js "magic" to be removed.

**Comment by jekkos** [comment]
Don't mind this bug, tables will be reworked anyway (using sorting from bootstrap tables).. wip

**Comment by odiea** [comment]
@jekkos  I do not know where to report on tests on your new table version. The modules that work look great. Items forms are not showing and Item kits also has issues. It does not find the kits and the add item kit doesn't do anything.

**Comment by jekkos** [comment]
@odiea for bootstrap-tables you can report bugs in #293 and otherwise in the specific issues at hand.

Currently sorting is disabled for bootstrap tables. It should be properly handled on the CI side (needs review). I might want to make a new issue for that (and deliver the current without sorting) as the old situation wasn't working properly anyway (it only sorted the current number of rows on screen)

**Comment by daN4cat** [comment]
It would be nice to have a feature in GitHub to move comments to the right issue... please copy & paste your comment that I delete both above once done.

**Comment by daN4cat** [comment]
I believe this issue is sorted in bstables. We should close this.
