### ISSUE TITLE
Unable to get opensourcepos_bower.css

### ISSUE THREAD

**Issue by wxwok** [jekkos/opensourcepos#469]
Git commit: 94e566bb89c1fe1a0640b62031620d4a36b181ad
When I open items page, it reports error from browser's inspector as following:
`GET http://localhost/x/openpos/dist/opensourcepos_bower.css `
I grepped the file name in the source code:
`application/views/partial/header.php:9:		
application/views/partial/header.php:65:		<link rel="stylesheet" type="text/css" href="dist/opensourcepos_bower.css"/>
Gruntfile.js:18:                    'css': 'dist/opensourcepos_bower.css'
Gruntfile.js:40:                    'dist/<%= pkg.name %>.min.css': ['dist/opensourcepos_bower.css', 'css/*.css', '!css/login.css', '!css/invoice_email.css']
templates/spacelab/views/partial/header.php:9:		
templates/spacelab/views/partial/header.php:67:		<link rel="stylesheet" type="text/css" href="dist/opensourcepos_bower.css"/>
`

**Comment by daN4cat** [comment]
Fixed.
