### ISSUE TITLE
The Items page can't be shown for language of Chinese and German

### ISSUE THREAD

**Issue by wxwok** [jekkos/opensourcepos#470]
I tried to set several languages in the menu of "Store Config"'s "Locale". The items page works well under most languages except Chinese and German, means it can't see items page under Chinese and German. 
git commit: 94e566bb89c1fe1a0640b62031620d4a36b181ad

**Comment by daN4cat** [comment]
Fixed and in master.

Please note that the Chinese translation in system/languages/zh are Simplified Chinese coming from: https://github.com/bcit-ci/codeigniter3-translations/tree/develop/language

There is Traditional Chinese too, but I really don't know which one is currently used in the rest of the system.

Please advise and review the Chinese translations. If any changed is requested I can switch the System ones.
