### ISSUE TITLE
PHP errors while using reports php version 7.0

### ISSUE THREAD

**Issue by jwblom** [jekkos/opensourcepos#473]
L.S.
Installed a fresh copy of the the latest version (3.0.0) on a shared hosting server with PHP version 7.0.
Alle seems to work well, exept for the  reports, as soon as I click on the reports, I get numerous errors like:
"A PHP Error was encountered
Severity: 8192
Message: Methods with the same name as their class will not be constructors in a future version of PHP; open_flash_chart has a deprecated constructor
Filename: ofc-library/Open-flash-chart.php
Line Number: 63
Backtrace:
File: /home/u2939p1555/domains/stock.blomware.nl/public_html/application/controllers/Reports.php
Line: 3
Function: _error_handler
File: /home/u2939p1555/domains/stock.blomware.nl/public_html/application/controllers/Reports.php
Line: 3
Function: require_once
Filele: /home/u2939p1555/domains/stock.blomware.nl/public_html/index.php
Line: 292
Function: require_once"

These kind of errors are raised for all of the files from the ofc-library.

And two more errors in the Session.php:

"A PHP Error was encountered
Severity: Warning
Message: session_start(): Cannot send session cache limiter - headers already sent (output started at /home/u2939p1555/domains/stock.blomware.nl/public_html/system/core/Exceptions.php:272)
Filename: Session/Session.php
Line Number: 140
......"

"A PHP Error was encountered
Severity: Warning
Message: session_regenerate_id(): Cannot regenerate session id - headers already sent
Filename: Session/Session.php
Line Number: 625
....."

Clicking on one of the options in the reports menu, even give more errors.

Hope you can sort this out!

Greetings fromThe Netherlands,

Jan Blom

**Comment by daN4cat** [comment]
Another reason to change charts. I need to work on that.

Session issue sounds a CI 3 issue, something to check and report them.

**Comment by jekkos** [comment]
ofc library might need to be upgraded to support php7. Did a quick search and I didn't find any updates on this library so might be better to get rid of it indeed.

**Comment by daN4cat** [comment]
I knew already they don't support it anymore that's why I need to work on that change.

**Comment by jekkos** [comment]
related to #342 #50

**Comment by daN4cat** [comment]
It looks like CodeIgniter will target PHP 7 support with version 4: http://forum.codeigniter.com/thread-62615.html

I'm afraid that we cannot do that much about that.

However with regards to PHP7 error with sessions please read this comment: http://stackoverflow.com/a/34925829/6176637

It might a solution as so far we have no heard of other issues with PHP7. But we never tested properly.

**Comment by daN4cat** [comment]
OK, I need to amend what I just said because I read this: http://stackoverflow.com/a/35800383/6176637

So CodeIgniter 3.0.6 supports PHP 7. Please try the trick suggested in the previous comment and see how it goes.

**Comment by jekkos** [comment]
Just want to reduce the number of open issues a bit.. charts are upgraded now in the mean time and php7 support epic has been opened

**Comment by daN4cat** [comment]
Indeed probably this is not an issue anymore.
