### ISSUE TITLE
No 'success' feedback response when sending email invoice from sale edit page V3

### ISSUE THREAD

**Issue by RamkrishnaMondal** [jekkos/opensourcepos#474]
Earlier this  was working properly (sending ugly looking email is another issue) . Today I have downloaded  another copy and found that, if I click on 'send invoice email'  from sale edit page, neither any success message is showing nor the 'edit form' is getting closed automatically, though it is still sending an ugly looking email successfully.

**Comment by jekkos** [comment]
In this case not only sending receipt is ugly, but invoice as well? Maybe post screencap of the generated pdf if you want. Could be a dompdf issue.

**Comment by RamkrishnaMondal** [comment]
Screenshots : 

![screenshot from 2016-04-10 20 18 42](https://cloud.githubusercontent.com/assets/14151032/14410972/d0f17c94-ff59-11e5-849b-ca6080d69ef4.png)
![screenshot from 2016-04-10 20 18 08](https://cloud.githubusercontent.com/assets/14151032/14410973/d6444230-ff59-11e5-8962-0ae239b7f94d.png)


NOTE: I have changed 'item #' to 'Serial #'

**Comment by daN4cat** [comment]
I don't get any issue in sending email, however I do see the receipt over email looks different and not well formatted.

I believe normal receipt and receipt over email should be the same and I don't see a reason to have different fields and etc., I will change that.

**Comment by RamkrishnaMondal** [comment]
@daN4cat  no issue there if i send email from 'sale register' at the time of executing sale. If I try to send 'email Invoice' from 'sale edit form' (this option is available if 'create invoice' is checked) ... neither 'success' feedback is displayed nor the 'sale edit form' closes itself. Email is sending successfully either ways.

**Comment by RamkrishnaMondal** [comment]
BTW, can't you also add 'send receipt' option at the sale edit page ? In that case, even if the user forgets to check the 'email receipt' check box at the time of executing sale, will be able to send it later.

**Comment by daN4cat** [comment]
email receipt fixed and tagged with #442

**Comment by daN4cat** [comment]
Re button, sounds sensible to have it. However that's not and easy one like for the other buttons and I would need to refactor the code in controller/Sales to get that functionality moved to a reusable function.

I assume we want the same from invoices, right?

**Comment by daN4cat** [comment]
Button to send email is now in #475

**Comment by RamkrishnaMondal** [comment]
Thanks for the fix, hope invoice will also get fixed very soon. The email receipt  looks really good. 'Success' response on 'sale edit page' is also working now, though 'sale edit form' is still not closing automatically after sending the email. 

"I assume we want the same from invoices, right?" --- YES.

**Comment by daN4cat** [comment]
I tried the send invoice from sale edit (form) and I can see the success feedback green bar in the background at the bottom.

So there is no issue "No 'success' feedback response" as far as I can see.

invoice email needs an update yes. But that's in #442 already.

**Comment by daN4cat** [comment]
I put this in pending state to see if somebody else can reproduce because looks ok to me with latest master.
