### ISSUE TITLE
How to add a new table

### ISSUE THREAD

**Issue by odiea** [jekkos/opensourcepos#476]
A Database Error Occurred

Error Number: 1146

I added a new table to play around with but when I try to add info to it I got this error. Does this table have to be setup anywhere else?
Table 'bootstrap.ospos_customer_payments' doesn't exist

INSERT INTO `ospos_customer_payments` (`sale_id`, `payment_type`, `payment_amount`) VALUES (66, 'Debit Card', '4.29')

Filename: C:/xampp/htdocs/master/system/database/DB_driver.php

Line Number: 691

**Comment by RamkrishnaMondal** [comment]
When someone plays with 'payments' table, i feel and hope that we are slowly moving towards implementation of 'Credit Sale' feature. Please don't stop playing.

**Comment by odiea** [comment]
I tried this in an earlier version of 2.4 and it worked just fine. So what does bootstrap have to do with it?

**Comment by daN4cat** [comment]
The only change I made related to DB between 2.4 & 3.0 is the change of decimals.
Other than that nothing that I can think but without seeing your code is difficult to debug.

**Comment by odiea** [comment]
All I tried was recreating the sales payment table and named it customer payments. I the added the lower line to sales/models around line 289 in Public function save. I also added fields to other tables and I got the same result. 
$this->db->insert('sales_payments',$sales_payments_data);
			$this->db->insert('customer_payments',$sales_payments_data);
		}

**Comment by odiea** [comment]
Do not waste any time on this. It works just fine. I must have used some in between updated OSPOS. I just tried on a newer version.
