### ISSUE TITLE
Redo ospos notifications

### ISSUE THREAD

**Issue by jekkos** [jekkos/opensourcepos#478]
This script should give our notifications a better look

http://bootstrap-notify.remabledesigns.com/

**Comment by daN4cat** [comment]
Sounds a nice one. I don't particularly like the notification at bottom of the page.

**Comment by jekkos** [comment]
I have bootstrap notify integrated and replaced all old messages with new ones on my local machine. Will do some more testing and then push later today or tomorrow

**Comment by daN4cat** [comment]
Sounds great!

**Comment by odiea** [comment]
It now appears that the new notification is in the upper right hand corner. Should it be there?

**Comment by RamkrishnaMondal** [comment]
Bootstrap-notify is not working on 'message config'.

**Comment by daN4cat** [comment]
@odiea Yes notification box should display on top right.

**Comment by jekkos** [comment]
I understand that some users might want to have it at the bottom again? I could turn this into a configurable setting (if there's a demand for this)

**Comment by jekkos** [comment]
Check http://bootstrap-notify.remabledesigns.com/ for a demo

**Comment by daN4cat** [comment]
Maybe a config setting would not be a bad idea.

**Comment by daN4cat** [comment]
This seems to work fine now. However I don't know if the intention was to change the Sales register too?
Maybe the notifications there should be moved to the new way?
I'm referring to cases where the quantity is low or negative, when the sale is suspended and so on.

**Comment by daN4cat** [comment]
BTW I just noticed that in message view the notification doesn't work.

**Comment by daN4cat** [comment]
OK, SMS message notifications fixed.

**Comment by daN4cat** [comment]
Probably the Sales register notification change should go with the Sale register redesign #401

**Comment by daN4cat** [comment]
OK to close?

**Comment by daN4cat** [comment]
Fixed an issue with excel import notifications.
