### ISSUE TITLE
#1046

### ISSUE THREAD

**Issue by YWenJr** [jekkos/opensourcepos#481]
can anybody help me with this problem please!!

A Database Error Occurred

Error Number: 1046

No database selected

SELECT `data` FROM `ospos_sessions` WHERE `id` = 'c93bca6327e3e7192cc157e3c94f26369297adca'

Filename: C:/xampp/htdocs/projekenterprise/system/database/DB_driver.php

Line Number: 691

A Database Error Occurred

Error Number: 1046

No database selected

INSERT INTO `ospos_sessions` (`id`, `ip_address`, `timestamp`, `data`) VALUES ('c93bca6327e3e7192cc157e3c94f26369297adca', '::1', 1460482614, '')

Filename: C:/xampp/htdocs/projekenterprise/system/database/DB_driver.php

Line Number: 691

**Comment by odiea** [comment]
Was this issue resolved?
