### ISSUE TITLE
Bugs on "Calc avg. Price (Receiving)" config.

### ISSUE THREAD

**Issue by tanakornp** [jekkos/opensourcepos#482]
When Calc avg. Price (Receiving) was check the data in ospos_app_config.receiving_calculate_average_price = 1

But the calculate function where under 

`if($cur_item_info->cost_price != $item['price'] AND	$this->config->item('receiving_calculate_average_price') == 'receiving_calculate_average_price')`

So the function will not be call even though user enable it in configuration page.
Please change it to
`if($cur_item_info->cost_price != $item['price']	AND	$this->config->item('receiving_calculate_average_price') == 1)`

on the next release.

Anyway, Could anyone tell me which ticket / sale slip printer is fully compatible with OSPOS 3.0?

PS I'm new to github community so if this is not appropriate way to report bugs, then I am sorry for that.

**Comment by daN4cat** [comment]
Fixed.

There are many printers you can use, I use a Star Micronics TSP800 with USB connection.
