### ISSUE TITLE
php error

### ISSUE THREAD

**Issue by dxchen90** [jekkos/opensourcepos#484]
Hi,

Anyone face this issue?
After upgraded Version 3.0. Click Takings > edit> pop out window is blank.
Now i have downgrade back to 2.4
Having issue on receiving.
Fatal error: Can't use method return value in write context in /home2/whypaym2/public_html/stock/application/controllers/Receivings.php on line 373
A PHP Error was encountered

Severity: Compile Error

Message: Can't use method return value in write context

Filename: controllers/Receivings.php

Line Number: 373

Backtrace:

When click item,

Fatal error: Can't use method return value in write context in /home2/whypaym2/public_html/stock/application/controllers/Items.php on line 123
A PHP Error was encountered

Severity: Compile Error

Message: Can't use method return value in write context

Filename: controllers/Items.php

Line Number: 123

Backtrace:

**Comment by daN4cat** [comment]
You need to run the database upgrade script 2.4 to 3.0 in order to solve this issue.

**Comment by dxchen90** [comment]
After run database upgrade, Pop out wouldn't show up during want to edit date on takings.

Sent from Outlook Mobile




On Mon, Apr 18, 2016 at 1:17 AM -0700, "FrancescoUK" <notifications@github.com> wrote:












You need to run the database upgrade script 2.4 to 3.0 in order to solve this issue.

**Comment by daN4cat** [comment]
Do you have all the latest 3.0 from master?

**Comment by dxchen90** [comment]
Yes, download latest master file from web and replace all the files and run database update

Sent from Outlook Mobile




On Mon, Apr 18, 2016 at 5:01 AM -0700, "FrancescoUK" <notifications@github.com> wrote:












Do you have all the latest 3.0 from master?

**Comment by daN4cat** [comment]
Please follow this guideline to report bugs: https://github.com/jekkos/opensourcepos#reporting-bugs

**Comment by daN4cat** [comment]
PHP version?
