### ISSUE TITLE
Item -> List of Item Data Location Sort is not working in Ospos 2.3.2

### ISSUE THREAD

**Issue by diganto213** [jekkos/opensourcepos#49]
Ospos 2.3.1 , in the Items menu List of Item can be sorted using Location filtering but in version 2.3.2 Items cannot be filtered based on the location selection.

Could you give a guideline how to fix it Or is it already being fixed ? Appreciate your help.

Thank You
Digantos

**Comment by jekkos** [comment]
Are you on the latest github version (2.3.2)? A fix was done a couple of days ago for #42. 
Let me know if this solves your issue.

**Comment by diganto213** [comment]
Thanks Jekkos. Yep, I have update latest fix, seems it is working but it create another 2 issues so far I noticed,

1. In the List of Item Page, when I filter by Location, seems it searching forever, the searching ICON keep rotating. But then if I refresh the IE, it shows the filtered item only. So far this is the workaround.
2. In New Item window, when I finished entered the data and submit it, it seemed the new entry does not appear automatically in list unless I refresh OR click the Item menu again.

I running the Ospos 2.3.2 in a public webserver for testing and above is the result.

Hope you can guide here.

Thank You
Digantos

**Comment by jekkos** [comment]
1. The fact that search icon keeps spinning means that the server returned an error (which will cause the search to fail)
2. Aft'er a new item is added also the search method is called to update the rows on screen. So fact that it does not appear might be related to the first issue as well.

Could you perhaps have a look if there is any error sent back from the server and send it to me? You should be able to copy paste the server response after sending the search request (using a tool  like Firebug or so)

**Comment by jekkos** [comment]
Or, maybe, easier, could you give me access to this server so I can debug directly? You can send credentials to me on my mail : webmaster - a t - jpeelaer dot net

**Comment by diganto213** [comment]
Ok. Here you are

http://rmsglobal.com.my/dev/inventory/ospos1.1/

Username : admin
Password: p@55w0rd

**Comment by diganto213** [comment]
Sorry I am sending you the actual username and password in your email..

**Comment by diganto213** [comment]
I have sent  the email. Let me know if any problem accessing it....

**Comment by jekkos** [comment]
Ok I can't succeed logging in, but I think I found a similar problem on my own server. Can you try the fix I committed here above?

**Comment by diganto213** [comment]
Yep, tried adding doing Duplicated cookie but no luck....

**Comment by jekkos** [comment]
Did you add it before or after the last line?

**Comment by diganto213** [comment]
Sorry my mistake. It seemed working. Thank Jekkos.
