### ISSUE TITLE
Error After Installation

### ISSUE THREAD

**Issue by ras1235** [jekkos/opensourcepos#490]
A PHP Error was encountered
Severity: 8192
Message: mysql_connect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead
Filename: mysql/mysql_driver.php
Line Number: 136
Backtrace:
File: /home/sale/public_html/application/controllers/Login.php
Line: 6
Function: __construct
File: /home/sale/public_html/index.php
Line: 292
Function: require_once
A PHP Error was encountered
Severity: Warning
Message: session_start(): Cannot send session cookie - headers already sent by (output started at /home/sale/public_html/system/core/Exceptions.php:272)
Filename: Session/Session.php
Line Number: 140
Backtrace:
File: /home/sale/public_html/application/controllers/Login.php
Line: 6
Function: __construct
File: /home/sale/public_html/index.php
Line: 292
Function: require_once
A PHP Error was encountered
Severity: Warning
Message: session_start(): Cannot send session cache limiter - headers already sent (output started at /home/sale/public_html/system/core/Exceptions.php:272)
Filename: Session/Session.php
Line Number: 140
Backtrace:
File: /home/sale/public_html/application/controllers/Login.php
Line: 6
Function: __construct
File: /home/sale/public_html/index.php
Line: 292
Function: require_once

**Comment by ras1235** [comment]
Pls Help

**Comment by odiea** [comment]
Reporting Bugs

Since OSPOS 3.0.0 is a version under development, please make sure you always run the latest 2.4_to_3.0.sql database upgrade script. Please DO NOT post issues if you have not done that before running OSPOS 3.0. Please also make sure you have updated all the files from latest master.

Bug reports must follow this schema:

    OS name and version running your Web Server (e.g. Linux Ubuntu 15.0)
    Web Server name and version (e.g. Apache 2.4)
    Database name and version (e.g. MySQL 5.6)
    PHP version (e.g. PHP 5.5)
    Language selected in OSPOS (e.g. English, Spanish)
    Any configuration of OSPOS that you changed
    Exact steps to reproduce the issue (test case)

If above information is not provided in full, your issue will be tagged as pending. If missing information is not provided within a week we will close your issue.

**Comment by daN4cat** [comment]
Thanks @odiea I believe we need to enforce this a bit because it's becoming too much of the same story everyday.

By the way I found that the latest GitHub allows now to add a template for the issue report, I will add that so we don't need to repeat this copy and paste too much.

**Comment by odiea** [comment]
Sounds like a good idea to help out the new folks trying the product out.

**Comment by ras1235** [comment]
OS name and version running your Web Server (Centos 6)
Web Server name and version (Apache 2.2.31)
Database name and version (MySQL 5.5.48)
PHP version (PHP 5.5.30)
Language selected in OSPOS (English)
Any configuration of OSPOS that you changed - not changed
Done changes in "database.php" is changed "mysqli"  to "mysql"
pls help only problem with "opensourcepos-2.4"
Please help me.

**Comment by daN4cat** [comment]
Have you run the database upgrade script from your version to 2.4?

**Comment by ras1235** [comment]
I Installed direct 2.4 version not updated from old version. I just downloaded 2.4 version and installed as fresh.

**Comment by ras1235** [comment]
pls help

**Comment by daN4cat** [comment]
If you try the latest master (3.0) from scratch do you get the same?

**Comment by daN4cat** [comment]
It's pretty stable and fully functioning so it's good to go too. We are just adding extra features at the moment.

**Comment by ras1235** [comment]
Is there any apache version problem ?

**Comment by daN4cat** [comment]
It looks more a database configuration. Is the database.php in config fine? Have you changed the driver from msqli to be mysql in the config file?

**Comment by ras1235** [comment]
Yes, I have changed mysqli to mysql

**Comment by daN4cat** [comment]
And what is this saying?

`A PHP Error was encountered
Severity: 8192
Message: mysql_connect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead`

**Comment by daN4cat** [comment]
Why don't you put to be mysqli?

**Comment by osworx** [comment]
``The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead``
Then
``I have changed mysqli to mysql``
Just one question; what does ``deprecated`` mean??
Maybe some have to learn first English.

**Comment by ras1235** [comment]
I Am Using Shared Server hence how can i use it with mysql.. Pls help

**Comment by ras1235** [comment]
how it possible with mysql without mysqli

**Comment by daN4cat** [comment]
Still don't get, what happens if you set mysqli?

**Comment by daN4cat** [comment]
Please report that error not one that is caused by your changes.

**Comment by bkrajendra** [comment]
Just add to above issue .. I think there is little confusion in presenting issue.
I've installed fresh new v3.0.0. I got this error in my instance. But initially i ignored it by disabling php error reporting, thinking that OSPOS is using msql driver. But further I came to know that we can change the driver from database config. Issue gets resolve if dbdriver is changed from database config.

So i guess this is related to database.php file. The line 55 should be:
```
$db['default']['dbdriver'] = 'mysqli';
```
As this file is auto created during installation. Might be its an issue in installscript.

@osworx, deprecated means the given feature or option will be disapproved in further version and eventually be removed.

**Comment by daN4cat** [comment]
There is no install script.

**Comment by odiea** [comment]
mysqli has been the chosen driver I believe it started with 2.4. The following is from the database.php.tmpl file.
$db['default'] = array(
	'dsn'	=> '',
	'hostname' => 'localhost',
	'username' => '',
	'password' => '',
	'database' => '',
	'dbdriver' => 'mysqli',
	'dbprefix' => 'ospos_',
	'pconnect' => FALSE,
	'db_debug' => (ENVIRONMENT !== 'production'),
	'cache_on' => FALSE,
	'cachedir' => '',
	'char_set' => 'utf8',
	'dbcollat' => 'utf8_general_ci',
	'swap_pre' => '',
	'encrypt' => FALSE,
	'compress' => FALSE,
	'stricton' => FALSE,
	'failover' => array(),
	'save_queries' => TRUE
);

**Comment by ras1235** [comment]
I database.php i only changed this line
'dbdriver' => 'mysqli',
to
'dbdriver' => 'mysql',

**Comment by ras1235** [comment]
but in the previous version it ws working well

**Comment by ras1235** [comment]
still i am strugle withthe problem

**Comment by daN4cat** [comment]
Since we updated to Code Igniter 3 that's what is required.

With OSPOS 2.4 and 3.0 we cannot do any different. It's mysqli.

**Comment by ras1235** [comment]
is it possible work with mysql ?
If yes, How can i setup it work with mysql not mysqli
Thanks in advance

**Comment by daN4cat** [comment]
I'm afraid no, it's not possible.
