### ISSUE TITLE
Sale total

### ISSUE THREAD

**Issue by odiea** [jekkos/opensourcepos#492]
In the takings update form how do I get the true amount due to show. If I use amount_due it just gives me the total without taxes added in. I don't want to add taxes if there were some items that were not taxed.

**Comment by daN4cat** [comment]
I will check later what is the situation and give you an answer.

**Comment by odiea** [comment]
On the update form I thought it would be nice to see the Current amount paid and the Total Sale Amount on the form. When the update is made the page is covered.
![2016-04-21 06_09_42-ugly sweater store -- powered by os point of sale](https://cloud.githubusercontent.com/assets/10962177/14708413/fa77aaee-0787-11e6-9923-e646c195cb61.png)

**Comment by RamkrishnaMondal** [comment]
CREDIT SALE:  From the 'Accounting point of view' it is wrong to update a 'sale payment' any time after the sale is executed, better, create a table like this and post any after-sale payment there.... 

For the view either show in a report or create a module say, "Accounts" and call with customer_id and show the sales related to that customer_id as well as 'after-sale payments' with date as a statement and add a button "ADD PAYMENT" there.

-- --------------------------------------------------------

--
-- Table structure for table `ospos_customers_payments`
--

CREATE TABLE `ospos_customers_payments` (
  `payment_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `customer_id` int(10) NOT NULL,
  `employee_id` int(10) NOT NULL,
  `payment_type` varchar(40) NOT NULL,
  `payment_amount` decimal(15,2) NOT NULL,
  `comment` text NOT NULL,
  PRIMARY KEY (`customer_id`,`payment_type`),
  KEY `customer_id` (`customer_id`),
  KEY `employee_id` (`employee_id`),
  KEY `payment_time` (`payment_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Dumping data for table `ospos_customers_payments`
--


-- --------------------------------------------------------


May be someone has a better idea on this.....

**Comment by osworx** [comment]
A Payment is a Payment and every time a Payment is done it is related to an invoice number.
So finally the invoice number can have several 'payments' which has also be recorded from the book keeping department (the Finance will check this).

**Comment by RamkrishnaMondal** [comment]
If you change the credit sale type of payment  to say cash, when getting the payment ...the book-keeper is never going to know the history.....

**Comment by RamkrishnaMondal** [comment]
When a credit sale is executed, in the books of accounts posted as ...

Customer A/C    Dr.   $100
To (Cr.)   Sales A/C    $100

When the customer pays the due, posted as.....

Cash / Bank A/C   Dr.     $100
To  Customer A/C           $100


So you can see the Sales A/C remains untouched when receiving payment from Customer.

**Comment by odiea** [comment]
I do understand the concepts of payments. I am not a programmer this idea was just to be a simple add payment feature that would update the sales payments. The audit trail would be placed in the comments section. Full accounting software can be setup by the user.

**Comment by odiea** [comment]
The main issue I have faced is the need to drop the primary key so that updates can be done on the table else I got a Internal Server Error.

**Comment by odiea** [comment]
Here was my initial attempt that worked after I dropped the primary key. I added ospos_customer_payments and the form updates just fine. I played with the reports and it appeared to use the info ok.
![2016-04-21 13_59_19-localhost _ 127 0 0 1 _ osposnew _ ospos_customer_payments _ phpmyadmin 4 2 11 -](https://cloud.githubusercontent.com/assets/10962177/14722631/a28ae8ae-07c9-11e6-82f3-7e07e05c2316.png)

**Comment by RamkrishnaMondal** [comment]
I am from Accounting background,  involved in my own business.... very new to world of CI and trying hard to learn it.

**Comment by odiea** [comment]
I know how you feel.

**Comment by RamkrishnaMondal** [comment]
In our country credit sales and credit purchases are  very common. During the year, a customer purchases on credit and pays part payments.....before the year ending (31st March) the seller sends a statement showing the whole year's purchases and payments of the customer and the customer must pay the balance due before 31st march.

If you go my way (with corrections, if needed) both the purposes are served.

**Comment by odiea** [comment]
Sounds good. Once my grand children quit spending so much time on my computer I can play with concept  some more.

**Comment by daN4cat** [comment]
BTW, that's why in my change I allowed only the Payment Type change to sort out a trivial mistake that happens often and not allowed any payment amount change.
