### ISSUE TITLE
Php error on discount_percent

### ISSUE THREAD

**Issue by jzonetan** [jekkos/opensourcepos#493]
A PHP Error was encountered

Severity: Notice

Message: Undefined property: stdClass::$discount_percent

Filename: customers/form.php

Line Number: 61

Backtrace:

File: application\views\customers\form.php
Line: 61
Function: _error_handler

File: application\core\MY_Loader.php
Line: 22
Function: _ci_load

File: application\controllers\Customers.php
Line: 64
Function: view

File: posmaster\index.php
Line: 315
Function: require_once

OS name and version running your Web Server  Window: Windows 7 Enterprise Edition Service Pack 1
Web Server name and version : Xamp 5.6.15
Database name and version 
PHP version Apache/2.4.17 (Win32) OpenSSL/1.0.2d PHP/5.6.15 
Language selected in OSPOS :english
Any configuration of OSPOS that you changed : none
Exact steps to reproduce the issue (test case)

**Comment by odiea** [comment]
If this was a new Install of 3.0 you should have used database.sql if not then you need to add the following.If it was an update use 2.4 to 3.0.sql which contains
ALTER TABLE `ospos_customers`
 ADD COLUMN `discount_percent` decimal(15,2) NOT NULL DEFAULT '0.00';

**Comment by jzonetan** [comment]
case solved i thought it was a php error it was really the db error after upgrading 2.4 to 3.0 sql

**Comment by odiea** [comment]
Thanks for the feedback.
