### ISSUE TITLE
Zero quantity fields on item delete

### ISSUE THREAD

**Issue by daN4cat** [jekkos/opensourcepos#496]
It doesn't make that much sense to me to keep quantity values to something not 0 when an item is deleted.

If no objections I would 0 quantity fields when the item is deleted.
I won't touch ordered or reordered levels as those are rules more than actuals.

**Comment by daN4cat** [comment]
I would also add an entry in the inventory tracking when an item is 0'ed and deleted.

**Comment by jzonetan** [comment]
can we right a setting for selling if qty item is 0 then it stop selling

**Comment by daN4cat** [comment]
@jzonetan that's a different matter, please let's not mixup topics.

**Comment by daN4cat** [comment]
Committed feature

**Comment by jekkos** [comment]
Kind of suspicious in a way, once you delete an item while stil having some quantities in stock, you actually make it disappear just like that?

**Comment by daN4cat** [comment]
Nothing suspicious because in case you receive a batch of seasonal products (e.g. 10 dresses) that are faulty and you return them you just click all and delete and automatically reset the fields to avoid having skewed statistical figures later when you fetch historical data.
Otherwise as many times it happened to me people don't 0 but delete the item and then you fetch historical data and see that the quantity don't match.
Historical data is built even on items that are deleted because they don't want to see in the shop stuff it's not in stock anymore but actually you sold.
