### ISSUE TITLE
Connection to ipinfo.com from js

### ISSUE THREAD

**Issue by daN4cat** [jekkos/opensourcepos#497]
I found that the connection to ipinfo.com happens on any page, which I'm not sure should be the case since it's needed only in specific places.

Also the connection to ipinfo.com fails in case the connection is https://, because https://ipinfo.com is a commercial service vs http://ipinfo.com that is free.

Above issues need a solution.

**Comment by jzonetan** [comment]
actually what is the use of that site?

**Comment by jekkos** [comment]
it's a backdoor...

no just kidding .

was used to send the country code to the reverse geocode nominatim. For precise address lookup in customers form. This could be turned into a config option to search in specific countries (or just return results for places all over the world)

**Comment by daN4cat** [comment]
The js should be just valid in the store config view not always.

**Comment by jekkos** [comment]
Yes think it was like that before. With the new grunt setup this has changed. However once the country code is in the sessionStorage the lookup should stop.

**Comment by jekkos** [comment]
I'd prefer to add a countrycode field in the locale config so the user can decide in which countries he wants to search for addresses. MIght be easiest to use a reference to available country codes online as values to chose from.

**Comment by daN4cat** [comment]
Not sure I get the use case here. What is that we need to search with this feature?

**Comment by jekkos** [comment]
It's for the customer form address completion feature. if you type in postal codes or city names then a query will be done towards openstreetmaps. Of course a city name can exist in multiple countries and to fi!lter those search results a countrycode can be sent along.

For example here in belgium we have clients from netherlands as well, so if we type in a postal code we want to search for both  belgian and dutch addresses

**Comment by jekkos** [comment]
If you select a suggestion then other fields will be autofilled like country, state, city, thanks to data from osm

**Comment by daN4cat** [comment]
OK. At the moment it doesn't work for me because of SSL (https://) restriction.

So this is needed only in customer form, not in filling in the shop information in config.

**Comment by jekkos** [comment]
Yes baiscally in all forms that show address fields, among them are employee, supplier and customer

**Comment by bkrajendra** [comment]
I suggest Google Map Location APi is better to get city info and zip codes.

**Comment by jekkos** [comment]
Don't know about google usage terms, think they limit the number of queries and require one to use an API key. OSM is open data and could even be hosted on a separate server.

**Comment by bkrajendra** [comment]
I suggest to remove ipinfo and google font linking from OSPOS. POS is mostly used in store environment where internet connectivity is generally not necessarily used. Both these files are adding delay to  page load if PC is not connected to internet. 
Ive to comment out google font link from bootstrap.min.css as in my case it was taking time due to this. Ipinfo is just used for filling customer details which might be require very rarely or one time for one customer. For POS usage mostly customers are local so city and state info does not chanes.

Sorry for straight response but I'm just relating this to my situation. Things might be different for others.

**Comment by jekkos** [comment]
I've added a config option in which country codes can be configured.

**Comment by jekkos** [comment]
Also ipinfo call is gone now.

**Comment by jekkos** [comment]
Could someone try and test this feature quickly? After entering one or multiple country codes only suggestiosn for that country should show up.

**Comment by daN4cat** [comment]
I'll check it this evening.

**Comment by odiea** [comment]
It does not appear to be as good as the zipcode . I put in a country code and it appears to populate the dropdown with multiple duplicate locations and when I try the 3 letter code it cant seem to find it.

**Comment by daN4cat** [comment]
Briefly checked and adding gb as country code when I type a Post Code (ZIP in US) it pops up a long list with just the first 2 letter, completing the post code doesn't point to anything differemt/
I assume this is a limitation of the nominatim service, but I would need to check on the web side what happens typing the same.

**Comment by daN4cat** [comment]
Not sure, checking the nominatim.org search I get something out of the post code.

**Comment by jekkos** [comment]
Nominatim returns way more fields than what we display in the form, and the mapping between them is defined in the init call. So the problem here is probably that most of these results are remapped to three or four fields causing some loss of information (and duplicates) along the way

**Comment by jekkos** [comment]
I just did a test on nominatim if I enter 2200 herentals, belgium, I get four results

![screenshot from 2016-05-28 10 18 21](https://cloud.githubusercontent.com/assets/576234/15626152/8705293a-24bd-11e6-9f05-9ff9a5b1d69d.png)

**Comment by jekkos** [comment]
Seeing the same number of results in ospos

**Comment by daN4cat** [comment]
If I type a post code from London I get many starting with two letters and nothing if I complete the postcode.

**Comment by daN4cat** [comment]
By the way, I noticed that if you add the code once in Store Config there is no means to change it anymore. Is that normal?

**Comment by jekkos** [comment]
One more css fix. Will close if ok

**Comment by daN4cat** [comment]
The Store Config issue is solved, UK post codes in London are still not fine.
