### ISSUE TITLE
Remove stock location from sale receipt and receipt email

### ISSUE THREAD

**Issue by daN4cat** [jekkos/opensourcepos#498]
I don't think the customer should be in any way informed about the original stock location of the purchased item on their sale receipt or receipt email.

I believe this is more an internal to the shop information rather than something to make public.

If no objection I would remove that information from the receipt and receipt email.

**Comment by jekkos** [comment]
Do mind that for requisitions it is probably the only required information on the receipt.

**Comment by daN4cat** [comment]
But that's not something the customer should be bothered, it's a shopkeeper issue.
I'm afraid this is a bit of non-sense to me.

In case of return the shopkeeper should scan the receipt and item quantity goes back to correct stock location.

The idea is just not to print, not to remove any return functionality.

**Comment by daN4cat** [comment]
I assume that returning from a receipt the quantity is added back to the correct stock location. I didn't test that but I will do.

**Comment by jekkos** [comment]
I mean requisition mode in the receivings. It's just a internal quantity transfer between stocks. Wouldn't make sense if you'd omit origin and destination there

**Comment by daN4cat** [comment]
OK, got your point. Indeed there is an exception to be taken into account.
So in stock transfer the stock location needs to be printed.

Thanks for the hint.

**Comment by daN4cat** [comment]
Requisition is only on receiving and that's not what I intend to change.

I just remove the location indication from the sale part.

**Comment by daN4cat** [comment]
Change to only sale receipts committed.
