### ISSUE TITLE
Make configurable description and serialnumber in receipts

### ISSUE THREAD

**Issue by daN4cat** [jekkos/opensourcepos#499]
Sometimes the description contains information that is used for internal use.
Same thing for serial number, it's not something relevant for a customer.

Make the two configurable from store config.

**Comment by RamkrishnaMondal** [comment]
In our country customer must have an  invoice mentioning the product serial no. on it to claim the warranty from the manufacturer.

**Comment by daN4cat** [comment]
That's why I make it configurable, so you can have it or not :-)

**Comment by daN4cat** [comment]
Change committed with update to scripts and addition to language

**Comment by daN4cat** [comment]
Requires running the database update script 2.4 to 3.0 (although not strictly necessary)
