### ISSUE TITLE
Flash Chart - Unable to open in Android OS

### ISSUE THREAD

**Issue by diganto213** [jekkos/opensourcepos#50]
Hi Jekkos

Seems flash chart is not working in android. Does it support Android OR is there any work around ?

Thank You
Digantos

**Comment by jekkos** [comment]
I haven't tested ospos on android yet. As there is no real responsive support I can imagine that some thing won't work properly. Would be nice to bootstrapify the layout to have a full responsive version for the future.

**Comment by asadjaved63** [comment]
graph is not working on mozila firefox. its only working on google chrome...
