### ISSUE TITLE
Can we have Merge Customer Data/Record (enchancement)

### ISSUE THREAD

**Issue by jzonetan** [jekkos/opensourcepos#500]
I was wondering if we can have this feature

I've created a situation where a customer had/has a transaction before and he/she want to merge his/her all transaction. into one customer account..

**Comment by daN4cat** [comment]
Not sure I get, can you be more concrete in your case with an example?

**Comment by jzonetan** [comment]
sample

Customer Joe bought to our store but the transaction was not listed on his name, then Custome Joe went back to our store and bought again, now customer joe wants to Merge or include his last transaction to his Account so he can monitor how much he purchase to our store...

**Comment by daN4cat** [comment]
It's already there. Go back in the transactions, edit that one adding customer name. Done

**Comment by daN4cat** [comment]
Just push Takings button and select the date of the transaction. Then you 'll get it listed and edit it.

**Comment by jzonetan** [comment]
its renaming the customer name right? but not merging?

**Comment by daN4cat** [comment]
It's assigning a sale to a customer.

From that you can go to reports, detailed customer and list all the transaction by customer getting the total.

**Comment by daN4cat** [comment]
Just to be clear, sales are atomic transactions to customer where you issue a receipt.
There is no case for merging sales to be one big sale, fiscally is not correct.

**Comment by jzonetan** [comment]
well maybe I'll do customized it sorry for trouble, I'm not fluent in English and my grammar is not that good..
