### ISSUE TITLE
[Question] sales model

### ISSUE THREAD

**Issue by arkgnan** [jekkos/opensourcepos#506]
hi, i want asking about get_info function in sales model. the query get from sales_items_temp tables, but i didn't found sales_items_temp tables in database. so, how it work? because i don't see any error in program

**Comment by daN4cat** [comment]
As the _temp suffix says it's a temporary thing (table).

See `public function create_sales_items_temp_table()` in `models/Sale.php` to understand how the table is created.
It's done for performance purposes and to collate all the different information from different tables about sales in one view.

Be careful about touching it in the sense that if you add something you need to test several parts of the code (just look for `create_sales_items_temp_table()` calls).

**Comment by jekkos** [comment]
THe code first checks and creates the temp table before doing any operations on it. If you want to query db directly you'll have to do the same.

**Comment by arkgnan** [comment]
ah i see... create temp table is something new for me. i have another question again, can i asking to you in this issue or i must create new issue? it's about print button. i take example from 'taking' in sales menu. is there print button with event javascript window.print in old version, but in ospos 3 print button using printdoc(), i get this error from chrome developer tool `printdoc is not defined`

**Comment by daN4cat** [comment]
If it's not defined that means that you didn't use all the files from 3.0, especially dist/ ones.

**Comment by arkgnan** [comment]
i search 'printdoc' in opensourcepos.js but didn't find anything

**Comment by daN4cat** [comment]
why don't you use what is in master?
Do a search on all the application/ files to find printdoc. I remember I implemented it but cannot remember exactly where it is from the top of my head.
