### ISSUE TITLE
request to add stock value report in terms of cash value

### ISSUE THREAD

**Issue by trendcnet** [jekkos/opensourcepos#508]
This request is to make every remaining stock quantity to be multiplied by their cost price per each item and then generate total remianing stock value for all items in the stock at any give point in time.

**Comment by RamkrishnaMondal** [comment]
Isn't it already there?
![screenshot from 2016-04-27 20 52 48](https://cloud.githubusercontent.com/assets/14151032/14858207/c61a1c7a-0cbc-11e6-807d-352ba590e4ab.png)

**Comment by trendcnet** [comment]
This is great and a serious well done to the developers. More greece to your elbow.

**Comment by daN4cat** [comment]
Yes Sub Total is quantity * cost price.

I close this one as there is nothing to implement.
