### ISSUE TITLE
Question : Invoice Config

### ISSUE THREAD

**Issue by RamkrishnaMondal** [jekkos/opensourcepos#509]
Under the Invoice config, I can see the following settings. What does they mean & what are the other options available to use ?

![screenshot from 2016-04-27 20 34 40](https://cloud.githubusercontent.com/assets/14151032/14856943/e0644e84-0cb7-11e6-96b0-83901ece42a5.png)

**Comment by jekkos** [comment]
One can only know by looking in the code. I think some kind of tooltip should be added to explain different values. 

$CO: invoice count
$CU: Invoice customer name
$SCO: Suspended invoice number count
$YCO: invoice number for current year
$INV: invoice number itself

**Comment by RamkrishnaMondal** [comment]
Is it possible to configure  Invoice numbering like 2016/1, 2016/2 etc or 2016-17/1, 2016-17/1 like this ?  If yes, Please tell me how can I do this ?

**Comment by jekkos** [comment]
Yes you van combine strftime() variables with $YCO like %y-$YCO

**Comment by RamkrishnaMondal** [comment]
Thanks.......... I will try.

**Comment by pablos1rvent** [comment]
@RamkrishnaMondal Did you found something?

**Comment by RamkrishnaMondal** [comment]
Yes , you can even use any number or text as prefix or suffix. For example: OSPOS $YCO or $YCO / 2016 / OSPOS etc.....

**Comment by daN4cat** [comment]
Would be nice to get some help with the wiki/documentation....
