### ISSUE TITLE
you do not have permission to access the module named Sales (items)

### ISSUE THREAD

**Issue by jag2us** [jekkos/opensourcepos#51]
Am I the only one experiencing this problem, I must check all the categories (items, items_stocks & sales, sales_stocks)  before I can perform the sales.

How to make sales without checking the item and item_stocks

Thanks

**Comment by jag2us** [comment]
can you upload the latest working opensourcepos.zip with restrictions for staffs seeing the items/inventory panel

**Comment by jekkos** [comment]
not sure which version that would be. I will have a look later today to see if I can reproduce this issue.

**Comment by jag2us** [comment]
this is version i download in your database but i got some errors from creating transaction
-- phpMyAdmin SQL Dump
-- version 3.3.9
-- http://www.phpmyadmin.net
--
-- Host: localhost
-- Generation Time: Apr 08, 2011 at 04:27 PM
-- Server version: 5.1.54
-- PHP Version: 5.3.3

**Comment by jag2us** [comment]
thats why i was requesting a stable 2.3.1.zip because the only problem i got there is i want to make my staff not able to see the inventory(items, items_stock). 
i must check/grant permission first to items, items_stock and sales in the same time before making some transactions if i check only the sales, the error is you do not have permission to access the module named sales (items).
i'll just check this trend time to time thank you

**Comment by jekkos** [comment]
just download latest zip here and all will be fine.

**Comment by jag2us** [comment]
thanks it's working, i'll just testing it for some bugs/errors again.
if your system will work good to my shop for several days.
i'll drop by to your donation page, thank you for being responding and helpful again.

**Comment by jekkos** [comment]
Glad to hear that ospos is working out for you. I put in a lot of work on the project so a donation is a good motivator to keep investing time in it. 

If you have any specific feature request for your shop then don't hesitate to let me know, we might be able to work something out.

**Comment by jag2us** [comment]
ok i'll let you know, in the same time i'll share this to others and let's make some business.

**Comment by jag2us** [comment]
ok i'll let you know, in the same time i'll share this to others and let's make some business.

**Comment by jag2us** [comment]
ok i'll let you know, in the same time i'll share this to others and let's make some business.

**Comment by jag2us** [comment]
ok i'll let you know, in the same time i'll share this to others and let's make some business.

**Comment by diganto213** [comment]
Just want to know how I can contribute to your effort
.

**Comment by mrshahrozkhan** [comment]
I installed the latest Version 2.3.1 But having the same issue what should i need to do ?

**Comment by jekkos** [comment]
Should be fixed in the latest github version now. This issue appears due to a misconfiguration of the interface itself.
