### ISSUE TITLE
after configuring version 3.0 of ospos, the error below is what am getting when trying to access the login page.

### ISSUE THREAD

**Issue by trendcnet** [jekkos/opensourcepos#512]
Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at admin@example.com to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.
Apache/2.4.9 (Win32) PHP/5.5.12 Server at localhost Port 80

**Comment by jekkos** [comment]
Check your server log and post content please

**Comment by daN4cat** [comment]
Is it an upgrade or a fresh new installation?

**Comment by trendcnet** [comment]
I did both fresh and upgrade from version 2.3.2 as well.

all other versions when configured, as never give such problem, am using wamp server 2.5

**Comment by trendcnet** [comment]
may be i should try and use bitnami stack for windows

**Comment by RamkrishnaMondal** [comment]
Yes, Bitnami is hassle free. Works out of the box.

**Comment by daN4cat** [comment]
Ok, maybe is an error with php and what you compiled for the math library. Do you see any error_log in ospos root directory?

**Comment by daN4cat** [comment]
No updated. Close

**Comment by prince90617** [comment]
i  got the same error. please  help me to figure this out

**Comment by odiea** [comment]
Please submit the needed info from the temples.

**Comment by daN4cat** [comment]
@odiea got mystic.... temples :-)

**Comment by odiea** [comment]
Ya I hope the gods of ospos fix this issue.

**Comment by erfanrocker** [comment]
![image](https://cloud.githubusercontent.com/assets/9877489/23558672/08f5c14a-0067-11e7-9095-6ebed026cd8d.png)
After Upgrade from 3.0.0 to 3.0.2  Can't Login

**Comment by daN4cat** [comment]
Run db upgrade script?

**Comment by erfanrocker** [comment]
@daN4cat how to db upgrade script? I am new about it

**Comment by shaikhabdulqadir** [comment]
I am also facing this problem.. can anyone help us?

**Comment by odiea** [comment]
More info on what you are trying to upgrade from and to.
