### ISSUE TITLE
Payments Summary Report is incorrect

### ISSUE THREAD

**Issue by kpokorney** [jekkos/opensourcepos#513]
The Payments Summary Report is incorrect because the value being reported for payment_type=Cash is actually the amount that was tendered, not the sales amount. This bug is easy to repeat by just processing any cash transaction with an amount tendered greater than the total sales price (see attached PDF).
[Payments_Summary_Report_Bug.pdf](https://github.com/jekkos/opensourcepos/files/239439/Payments_Summary_Report_Bug.pdf)
I have tested the Payments Summary Report  using credit/debit/check payment types, and the same problem occurs. So the bug of reporting the amount tendered instead of the sales amount is independent of the payment type.

**Comment by odiea** [comment]
You appear to be using quite an old version. Please use the current version so bugs can be found and repaired.

**Comment by RamkrishnaMondal** [comment]
If the report shows 'amount tendered' as payment, it should also show 'amount refunded' column , so that users don't get confused.

**Comment by daN4cat** [comment]
I confirm the issue. The reported cash is the tendered one not the amount due.

**Comment by jekkos** [comment]
Ok to change labels to amount tendered?

**Comment by daN4cat** [comment]
Maybe show both tendered and due?

**Comment by jekkos** [comment]
Ok but a sale can have split payments eg if a sale 97 eur is paid with 50 cash + 50 credit card where should the amount due be shown? One should then sort the payments in time and calculate as follows

payment type | amount tendered | amount due
cash | 50 | 97-50 = 47
credit card | 50 | 97-100 =  -3

not really an easy one to add.

**Comment by daN4cat** [comment]
In general I made the strong assumption that amount due and returned is only cash. That's how it works in Takings and I put the comment in that code

**Comment by jekkos** [comment]
Ok but sometimes customers ask to charge them more on debit card, to have them return the amount due in cash. It's sometimes easier than going to an atm just to get some cash..

**Comment by daN4cat** [comment]
Agreed, so you returned cash as I said earlier.

Maybe instead of amount due we should add an amount returned, which will have a value only for cash.

In this was a person that does the maths see that it matches the Total. Now the Total in the summary doesn't match the sum of the tendered.

**Comment by daN4cat** [comment]
I briefly checked the returned cash point but it requires quite some work.
In the end details are visible in Takings if necessary.
