### ISSUE TITLE
low inventory reports

### ISSUE THREAD

**Issue by walterhumphreys** [jekkos/opensourcepos#514]
i got a question, i have 3 stcok locations a,b,c  now when im requesting lown inventory report how can i sort it just for A location only, can you give me a hint

**Comment by odiea** [comment]
Currently you could run the report then sort it by stock location. I don't know if this is helpful or not?

**Comment by walterhumphreys** [comment]
not really the other report allows me to sort but it show count and reoder level, i can select more than cero etc, but it has the item toltal plus reorder leven, low inventory report has item count once os under reorder level, i will just like to be able to select stock location as wel in reorder level, im trying to find that same sorting that the other report has and then apply it to low inventory reports

**Comment by daN4cat** [comment]
I would wait for the new tables work to come in and sort this.

**Comment by daN4cat** [comment]
This is sorted with the latest vs 3.0.0, you can sort the low inventory by location by just clicking the last field in the header.

Therefore I close this one.
