### ISSUE TITLE
How to change invoice layout?

### ISSUE THREAD

**Issue by arteiro** [jekkos/opensourcepos#518]
One question, as was done the layout of the invoice and receipt and how can I change them so that it looks like the Brazilian standard.

**Comment by arkgnan** [comment]
change the layout in view. for receipt or invoice sale you can check on view->sales->receipt.php or invoice.php

**Comment by daN4cat** [comment]
This is a similar request to #445

**Comment by arteiro** [comment]
Ok,
Thanks
