### ISSUE TITLE
exporting low inventory report

### ISSUE THREAD

**Issue by jag2us** [jekkos/opensourcepos#52]
i found out that when exporting the low inventory report all items will be seen, 
can you make additional column for exporting name as "suppliers" so that if a user wants to sort the items by suppliers
just like what you did in your items section if put a category in search bar all items in that category can be seen.
sort: suppliers, items(category)
additional column: suppliers

**Comment by jag2us** [comment]
in addition, the tax 1 and 2 is not working and not appearing in the sales receipt.

**Comment by jekkos** [comment]
indeed I noticed this as well, I already have another fix for this (not on master branch yet). Will try to merge that tonight.

**Comment by jag2us** [comment]
case close about tax, how about sorting out the items by suppliers in Reports (inventory summary)

**Comment by jekkos** [comment]
I will make this as enhancement then. Feel free to contribute or offer a donation for a requested feature. Code doesn't come falling from the sky.
