### ISSUE TITLE
can't import item from csv

### ISSUE THREAD

**Issue by arkgnan** [jekkos/opensourcepos#520]
i got this error when import item
`Most items imported. But some were not, here is list of their CODE (1): 1`

this issue is because do_excel_import function in controller items in if condition `if(!$invalidated && $this->Item->save($item_data)) `, when i debug i got error from item->save(), 

`<p>You must use the "set" method to update an entry.</p><p>Filename: models/Item.php</p><p>Line Number: 231</p>`

i use csv file from master

**Comment by arkgnan** [comment]
does anyone encountered a problem like this?

**Comment by jekkos** [comment]
This error typically occurs when you want to import an item with item_number that is already in the database. Check the item id and it's item_number to see if it's present in your db and remove it from the excel / db to make the rest work.

**Comment by daN4cat** [comment]
maybe be any conflict should be ignored and just reported but not stop the import.

**Comment by arkgnan** [comment]
my db is empty, it fresh install and i want to add item from import feature

**Comment by jekkos** [comment]
@daN4cat I do think this is currently the case. Import continues and the number of rows in error are reported in the end. I did the test on empty db and the example file works w/o issues.

**Comment by daN4cat** [comment]
OK, moved to pending.

@arkgnan we need the exact scenario to reproduce your issue.

@jekkos have you tested with bootstrap-tables or master?

**Comment by arkgnan** [comment]
this is my mistake.

1. i change the number of column. but after i change script for my csv column still can not import. it because my second mistake.
2. location_id in csv different with my location_id in database.

this issue has solved for me. sorry and thanks for your support.
i download master today. my master is about a month ago. i see new feature for sms-api. how do i use it?

**Comment by jekkos** [comment]
Ok guess this one is solved then.

**Comment by likozhang** [comment]
import file work for now ?

**Comment by daN4cat** [comment]
@likozhang use 3.0 is pretty stable and it was tested ok

**Comment by likozhang** [comment]
yeah, i was test
very Great, but you must delete template csv at front folder
because i can download template at import csv (lol)

**Comment by sirajomusa19** [comment]
I am stuck with importing items into ospos. Could someone kindly post the csv format as I couldnt get it anywhere on app. I appreciate your kind assistance.

**Comment by jekkos** [comment]
You should be able to download the template from the import window. There is a link there which you can click .

**Comment by sirajomusa19** [comment]
I thank you a lot. I have found it.
