### ISSUE TITLE
Disallow modal window from closing on click

### ISSUE THREAD

**Issue by pablos1rvent** [jekkos/opensourcepos#521]
Hi guys. I have a question, I need to disallow modal window closes when it's clicked outside or ESC or enter. Is there any function that does that? And how can I remove?

I found on "opensourcepos.js" Line 23157 that execute the modal but I don't know how to remove that.

Thanks!

**Comment by bkrajendra** [comment]
As per the bootstrap Modal docs and behaviour this should be done to prevent modal close.

```
$('#myModal').modal({backdrop: 'static', keyboard: false})  ;
```

or

```
<button data-target="#myModal" data-toggle="modal" data-backdrop="static" data-keyboard="false">
    Open Modal
 </button>
```

Here {keyboard: false} also prevent closing by ESC key!

**Comment by pablos1rvent** [comment]
Wow, a lot of thanks my friend! :dancer:

**Comment by pablos1rvent** [comment]
@bkrajendra Well, I tried that but in OSPOS is very strange to find the correct ID, all works with PHP and Jquery and I'm looking for a line in the JS to disable the backdrop. 

I don't know how to do it :S

**Comment by pablos1rvent** [comment]
Okey I found it:

To fix the ESC key and the backdrop, you need to find in "opensourcepos.min.js" and find :
`closeByBackdrop:false,closeByKeyboard:false,`

![captura](https://cloud.githubusercontent.com/assets/17593856/15011965/2c627a76-11f5-11e6-8715-d2b0f2d13833.PNG)
remember that I modified the JS, you have a different js or minified!!

To fix the Enter Submit (if anyone find this post searching) yo need to comment this line on the same file (dist/opensourcepos.min.js) this line:


`	var init = function(selector) {
		return $(selector).click(function(event) {
			var buttons = [];
			var dialog_class = 'modal-dlg';
			$.each($(this).attr('class').split(/\s+/), function(classIndex, className) {
				var width_class = className.split("modal-dlg-");
				if (width_class && width_class.length > 1) {
					dialog_class = className;
				}
				var btn_class = className.split("modal-btn-");
				if (btn_class && btn_class.length > 1) {
					var btn_name = btn_class[1];
					var is_submit = btn_name == 'submit';
					buttons.push({
						id: btn_name,
						label: btn_name.charAt(0).toUpperCase() + btn_name.slice(1),
						cssClass: is_submit ? 'btn-primary' : (btn_name == 'delete' ? 'btn-danger' : ''),
						**//hotkey: is_submit ? 13 : undefined, // Enter.**
						action: submit(btn_name)
					});
				}
			});

			!buttons.length && buttons.push({
				id: 'close',
				label: 'Close',
				cssClass: 'btn-primary',
				action: function(dialog_ref) {
					dialog_ref.close();
				}
			});

			var $link = $(event.target);
			$link = $link.is("a") ? $link : $link.parents("a");
			BootstrapDialog.show({
				cssClass: dialog_class,
				title: $link.attr('title'),
				buttons: buttons,
				message: (function() {
					var node = $('<div></div>');
					$.get($link.attr('href'), function(data) {
						node.html(data);
					});
					return node;
				})
			});

			event.preventDefault();
		});
	};`

//hotkey: is_submit ? 13 : undefined, // Enter. <--

**Comment by philipborbon** [comment]
For anyone looking for this, a simple CSS solution could do the trick:

Put this in the `application/views/partial/header.php`.
```html
<style type="text/css">
.modal-open .modal {
    pointer-events: none;
}

.modal-open .modal-dialog {
    pointer-events: auto;
}
</style>
```
