### ISSUE TITLE
:bug

### ISSUE THREAD

**Issue by jekkos** [jekkos/opensourcepos#523]

**Comment by daN4cat** [comment]
OK, must be a critical bug to something really secret....

**Comment by daN4cat** [comment]
To bug, or not to bug: that is the question

**Comment by odiea** [comment]
The suspense is ?

**Comment by daN4cat** [comment]
We need to set it to pending because we don't know version nor test case to reproduce it.

**Comment by daN4cat** [comment]
This issue is bugging us.....

**Comment by jekkos** [comment]
was playing around with the zenhub thing, looks like i created an issue by accident.

**Comment by daN4cat** [comment]
Oh bugger.... 😃
