### ISSUE TITLE
Bug on delete status

### ISSUE THREAD

**Issue by pablos1rvent** [jekkos/opensourcepos#525]
Hey guys, when I select a item and I delete it, automatically converts all the table the column to "1". It's a bug on default, any solution?

**Comment by jekkos** [comment]
Version please?

**Comment by pablos1rvent** [comment]
3.0.0

Greetings

**Comment by pablos1rvent** [comment]
https://gyazo.com/665aa171fbf44c53142f9cdea8222024

![665aa171fbf44c53142f9cdea8222024](https://cloud.githubusercontent.com/assets/17593856/14991013/b5b48daa-115f-11e6-9cc8-580d199bd104.gif)

**Comment by RamkrishnaMondal** [comment]
Wow! good idea of presentation with a GIF .

**Comment by jekkos** [comment]
Issue is solved in bootstrap taboes branch. @dan4cat why not merge into master so we van focus on fixing bugs in the latest and greatest only?

**Comment by daN4cat** [comment]
Because reports is broken and we will get those reported bugs....

**Comment by pablos1rvent** [comment]
@jekkos What is Bootstrap Taboes Branch? And how can I fix it?

**Comment by jekkos** [comment]
It's not really broken, I just disabled edit in detailed tables. And as it's a dev version I suppose that bug reports are a good thing.. Community can help to speed up and improve stability.  Now bugs are reported that have been fixed which isn't good either.

**Comment by pablos1rvent** [comment]
Okey perfect. Thanks! Now, I need to update the files or something?

**Comment by odiea** [comment]
To expand on this issue. I just deleted an item and now no items will show in the items table. Version 3.0

**Comment by odiea** [comment]
Apparently it deleted all the items. They come back after I select deleted in filters. Maybe we need a bulk update for deleted items.

**Comment by bkrajendra** [comment]
Actually delete is like soft delete here. It just makes deleted flag 0 or 1.
1) there should be option to delete entire or selected Item
2) There should be a way to restore it back if its a soft delete.
5) Also there should be hard delete which will delete item permanently from DB.

This is not happening currently. It only soft deletes.

**Comment by jekkos** [comment]
Ok I backported the fix from bootstrap tables to master branch for you guys now.

@bkrajendra undelete is definitely possible using deleted checkbox in the items form. Check the deleted filter and then uncheck the deleted checkbox. The item should appear in the list again.

There are quite some issues with real delete here. If eg a sale record is linked to an item you'll need to delete that as welll to keep constraints valid. This might fiscally not be correct (as you're making money disappear) and thus logical delete might be more appropriate.

**Comment by bkrajendra** [comment]
Thanks @jekkos .. i missed it.

**Comment by odiea** [comment]
Yes that appears to have fixed it. I found it was easier to drop the deleted table then re add it instead of going thru each item.

**Comment by pablos1rvent** [comment]
WOW it works!!! Thanks a lot of again to all, this is awesome! Where can I donate? :D

**Comment by odiea** [comment]
You can go to the front page <>code. Under the Code you will see a button so you can Donate to this project.
