### ISSUE TITLE
MySql server Crashing multiple times.

### ISSUE THREAD

**Issue by bkrajendra** [jekkos/opensourcepos#526]
Recently Im getting this issue frequently.
Ive installed OSPOS on my friends store, on Windows 7 32 bit, 2GB RAM - Pentium PC. (XAMPP)
xampp-win32-5.5.19-0-VC11
With latest mysql server and PHP 5.5. 

Everything is working fine, but suddenly application shows database error when in between transaction.

After investigation I came to know that mysql server stopped unexpectedly.
Ive gone through logs n came to know that my DB might be corrupt.
This happened 3 time and I have to reinstall mysql everytime.
AS earlier two time it was test run, it was ok.
But now 3rd time it happened when it was in real transaction.
Now MySQL server does not opens n throws error. WIndows event manager also shows application crash error for mysql.

I'm not getting why this happening frequently.
WHat could be the reason? Is it due to low system config.?
Or due to OLD, never updated windows 7.

Or is there's any thing in my Inventory list (any character or special character) that is causing this error.
I'm having More than 550 product list with "(, ) -" symbols in product name.

I'm not getting actually what is the problem. Ive lost entire day transaction due to this problem.
Please help. Ive attached Log file here

[mysql_error.txt](https://github.com/jekkos/opensourcepos/files/247525/mysql_error.txt)

**Comment by bkrajendra** [comment]
OS name and version running Web Server  - Windows 7 Ultimate , Pentium 4. 2GB RAM
Web Server name and version - Apache 2.4.17
Database name and version - MySql  4.5.1
PHP version (e.g. PHP 5.6.14)
Language selected in OSPOS - English
Any configuration of OSPOS that you changed - NA
Browser Used - Google Chrome 50+
Exact steps to reproduce the issue - 
-->Page becomes Unresponsive while adding items to cart or searching on Sales register screen
-->Page Has to close forcefully
-->Reopening shows database connectivity error.
-->This already closed/crashes Mysql, reopening mysql shows error.

**Comment by jzonetan** [comment]
can you change your browser like firefox or opera seems chrome has a glitch i used both chrome and firefox and im telling you in my experience i had/have difficulties in chrome sometimes it lags

**Comment by jzonetan** [comment]
also try to reinstall its OS something in the log bothers me...

**Comment by jekkos** [comment]
Not sure what is going on here.. this is definitely a problem with your setup.

2016-04-28 14:16:37 1844 [Note] InnoDB: Database was not shutdown normally!

seems you db process is being killed  leaving the transaction log in an inconsistent state?
Do you have any kind of antivirus running that accidentally kill the db process from time to time

**Comment by daN4cat** [comment]
I close this as not OSPOS. Other dedicated forums can help you better.

**Comment by bkrajendra** [comment]
Sorry ive reopened it. 
My server crashed 4th times. Most tedious is recovering from .ibd files. :(
Just one question.... my mysql "ibdata1" inside data folder is huge about 77MB
is it normal.?
This is the file which getting corrupt .. as per the log...
```
2016-05-04 15:53:16 3116 [ERROR] InnoDB: Database page corruption on disk or a failed
2016-05-04 15:53:16 3116 [ERROR] InnoDB: Space 0 file D:\xampp\mysql\data\ibdata1 read of page 515.
```

I'll post these error logs to SO database forum and post the follow up links here..
Thanks all!
