### ISSUE TITLE
White spaces in invoices 

### ISSUE THREAD

**Issue by pablos1rvent** [jekkos/opensourcepos#529]
Hey Guys, when I make a new invoice, this is what happen to my invoice on the right:

![33989e113edc3da4ad8026a18e665041](https://cloud.githubusercontent.com/assets/17593856/15042381/a090d7ca-12c3-11e6-861f-89b718c862c7.png)

Also I want to reduce the space on each row, there is a lot of space between the lines :S 

Thanks!

**Comment by pablos1rvent** [comment]
Okey I fix it deleting from the views/sales/invoice.php this line:

`		 	<h5>
			 	<textarea rows="5" cols="6"><?php echo nl2br($this->config->item('payment_message')); ?></textarea>
			  	<textarea rows="5" cols="6"><?php echo $this->lang->line('sales_comments'). ': ' . (empty($comments) ? $this->config->item('invoice_default_comments') : $comments); ?></textarea>
		  	</h5>`

This work for me because I don't need that lines.

I hope this may help you.

Greetings :3

**Comment by daN4cat** [comment]
Maybe there is a smarter way, adding an if checking if that value is set. If not do nothing, if yes leave as it is.

**Comment by daN4cat** [comment]
And the solution is to make it with an if or remove the code?

**Comment by pablos1rvent** [comment]
Sorry for that

**Comment by jekkos** [comment]
I did a fix for this, problem was due to a missing colspan.

**Comment by pablos1rvent** [comment]
@jekkos @daN4cat Well the fastest solution for me and my customers was remove the code, jekkos fix the problem :D

**Comment by daN4cat** [comment]
Better to use now the proper fix so you reduce the difference with the master code.

**Comment by jekkos** [comment]
Maybe learn to work with git a little bit, this will ease your life keeping up with upstream changes.

**Comment by pablos1rvent** [comment]
@jekkos I will do that ^^ Thanks :D
