### ISSUE TITLE
Question :  item  payment_message in invoice?

### ISSUE THREAD

**Issue by RamkrishnaMondal** [jekkos/opensourcepos#530]
I can see there is a field on Invoice view file, item(' payment_message'),  just above the comment field, What is the use of that ?

**Comment by pablos1rvent** [comment]
I think that is useless, I scan all the files and only I get that line in the invoice.php. 

Maybe is for future purposes because this is open source.

`$this->config->item('payment_message')`

I deleted that line for get more space.

Greetings!

**Comment by odiea** [comment]
When Invoice template is used placing a comment in Sales will over ride the default Invoice comment.
