### ISSUE TITLE
Sales on payment

### ISSUE THREAD

**Issue by mobilemediatechnology** [jekkos/opensourcepos#532]
![screen shot 2016-05-06 at 8 54 33 pm](https://cloud.githubusercontent.com/assets/7312668/15075111/da446b94-13cc-11e6-9c47-6049b1520275.png)
hey jekkos, thx for ospos, but i have same question.

just like the picture on above, on sales payment method when we choose payment type like debit or credit card, why does't have card number input kolom ?

**Comment by daN4cat** [comment]
Because it's sensitive data and ospos doesn't deal with money transactions.
