### ISSUE TITLE
Question: How to add a new controller

### ISSUE THREAD

**Issue by pablos1rvent** [jekkos/opensourcepos#533]
Hey guys. I want to create a new controller called "repairs".

The thing is that I have a repair-computers shop and I want to create a new controller to the app.

This Issue also is similar to #73 but that doesn't solve for me.

I don't know If there is any guide here to do that but I would be very grateful if this can be possible with a easy way.

Sorry for my english and I hope you can help me.

Greetings!

**Comment by daN4cat** [comment]
Check what was done for the SMS (messages).

**Comment by RamkrishnaMondal** [comment]
Well, I also have a Computer repair shop, but can't understand what are you trying to do. Please describe in details, what are you expecting to do with the new module "Repairs" ?

**Comment by daN4cat** [comment]
Even if I don't have a computer repair shop I was wondering about the same, what is the use case here?

**Comment by pablos1rvent** [comment]
The new module that I want is for people that give me a computer for repair, and give budget for her repair. I mean, I need a double invoice for me and for her (Spanish Laws) and I need to create custom inputs like:

1. Items to repair
2. Customer
3. Problem
4. Status (When my repairman fix any thing, I need to call the customer) 

Is basically done in PHP but I don't know how to put in a new module.

I found one thing, but I think I'm gonna create other mode in Sales, is more effective.

Greetings and thanks anyway!
