### ISSUE TITLE
installation in 1and1 problem

### ISSUE THREAD

**Issue by jasus23** [jekkos/opensourcepos#535]
I installed the OSPOS files on the server and modified the database.php file to successfully connect the software with my database. However, when  I Try to Configure the store only a Blank page comes up or when I go to new item, a smaller window version of the index page comes up making it impossible for me to add new items. 

My page: pos.masterteq.com
Apache version: 2.2.19
MySQL5.5
PHP 5.6

**Comment by daN4cat** [comment]
Is yours a new fresh installation or an upgrade?

**Comment by daN4cat** [comment]
Also which version of OSPOS?

**Comment by jasus23** [comment]
Yes, it is a fresh install and the ersio is: Open Source Point Of Sale Version	2.3.4  Thank you!

**Comment by jasus23** [comment]
Yes, it is a fresh install and the ersio is: Open Source Point Of Sale Version 2.3.4 Thank you!

**Comment by daN4cat** [comment]
That's an old version.

**Comment by daN4cat** [comment]
I suggest you to take the latest master so you get the new version and it will be easier to upgrade to the final one later.
Master is pretty stable and fully functioning.

**Comment by jasus23** [comment]
I upgraded to the version you recommended and it works perfectly now! Thank you very much for all your help

**Comment by rminformaticos** [comment]
hi jaus23 im trying to install ospos on 1and1 server, can help me???

Thx
