### ISSUE TITLE
miscellaneous

### ISSUE THREAD

**Issue by walterhumphreys** [jekkos/opensourcepos#536]
hi guys im using the system for a drugstore i was wondering what exactly will i need to create for the following,, i need to ad feature where i can add all debts to the system so it can discount it from the system as well, example i have to buy bags, pay rent and others bills, i need to register this to system so at in the end when i generate a montly report lets says 3000$ i need it to discount 800$ for bills so it shows at the end u sold 3000 miscellaneous bills 800 total 2800

**Comment by daN4cat** [comment]
You need an accounting software. OSPOS is a stock management and sale register. Please don't confuse the two.

**Comment by daN4cat** [comment]
Something like this could do in terms of accounting: http://webzash.org/

Probably what you would like to have is some connector to register revenues, direct tax and cost of sales.

What you call debt is operating cost (opex) which is the fix cost to run your business.

**Comment by daN4cat** [comment]
BTW, at certain point I might consider to create a connector to that tool. But first I need to install that tool and see how fits in the picture. I don't want too manual work to happen.
One of my current issue is that we need to manage with google sheets supplier invoices, payment deadlines and petite cash/expenditures . Somehow I cannot find an open source to manage purchasing, they tend to build more tools to manage accounts (clients) for invoicing, payment reconciliations and etc.
