### ISSUE TITLE
Bootstrap tables Issues in Items Module

### ISSUE THREAD

**Issue by odiea** [jekkos/opensourcepos#537]
A PHP Error was encountered

Severity: Warning
Message: Missing argument 1 for Items::generate_barcodes()
Filename: controllers/Items.php
Line Number: 242
Backtrace:
File: C:\xampp\htdocs\bstables\opensourcepos\application\controllers\Items.php
Line: 242
Function: _error_handler
File: C:\xampp\htdocs\bstables\opensourcepos\index.php
Line: 315
Function: require_once
A PHP Error was encountered
Severity: Notice
Message: Undefined variable: item_ids
Filename: controllers/Items.php
Line Number: 247
Backtrace:
File: C:\xampp\htdocs\bstables\opensourcepos\application\controllers\Items.php
Line: 247
Function: _error_handler
File: C:\xampp\htdocs\bstables\opensourcepos\index.php
Line: 315
Function: require_once

**Comment by odiea** [comment]
Table sorting looks good. It actually sorts from the beginning to the end of the table instead of just the rows showing on the form.

**Comment by odiea** [comment]
Bulk edit in Items no longer works. Modal shows but nothing happens after submit except warning.

**Comment by jekkos** [comment]
I know this is because I changed the id field name to make the sorting work. But consequently it broke the regular update functionality (will fix later today). Okay to close the bigger issue? Is there anything else open at this moment?

**Comment by odiea** [comment]
I think the only issue might be the question I just asked.

**Comment by jekkos** [comment]
Should be fixed now..

**Comment by daN4cat** [comment]
I still get the error.

**Comment by jekkos** [comment]
Forgot to regen the dist files.. will do so and push again

**Comment by jekkos** [comment]
Should be good now.

**Comment by RamkrishnaMondal** [comment]
Please see #507

**Comment by odiea** [comment]
Items now creating barcodes.
