### ISSUE TITLE
Boot Strap Tables Issues in Item Kits

### ISSUE THREAD

**Issue by odiea** [jekkos/opensourcepos#538]
A PHP Error was encountered

Severity: Warning

Message: Missing argument 1 for Item_kits::generate_barcodes()

Filename: controllers/Item_kits.php

Line Number: 137

Backtrace:

File: C:\xampp\htdocs\bstables\opensourcepos\application\controllers\Item_kits.php
Line: 137
Function: _error_handler

File: C:\xampp\htdocs\bstables\opensourcepos\index.php
Line: 315
Function: require_once
A PHP Error was encountered
Severity: Notice
Message: Undefined variable: item_kit_ids
Filename: controllers/Item_kits.php
Line Number: 142
Backtrace:
File: C:\xampp\htdocs\bstables\opensourcepos\application\controllers\Item_kits.php
Line: 142
Function: _error_handler

File: C:\xampp\htdocs\bstables\opensourcepos\index.php
Line: 315
Function: require_once

**Comment by jekkos** [comment]
Should be fixed now in latest

**Comment by daN4cat** [comment]
The same here, still get the error.

**Comment by jekkos** [comment]
OK try again with debug=true or with regenerated js.

**Comment by odiea** [comment]
On my last pull it now has working barcodes.
