### ISSUE TITLE
Excel Export

### ISSUE THREAD

**Issue by saurabh261187** [jekkos/opensourcepos#539]
The Inventory Summary / Low Inventory summary export feature is not working in version 3.0. After selecting export to excel, it is showing the output on the screen itself. Kindly check this issue.

**Comment by odiea** [comment]
It appears that none of the reports are exporting to excel.

**Comment by jekkos** [comment]
I never really looked into this part. It could have been broken since long.

I might consider to replace the option in the reports with the bstables plugin for export (which offers quite some extra formats as well). What do you think?

**Comment by odiea** [comment]
If there is a temporary fix for the current version that would be good. Then once the bstables get updated then I would suggest that option. It sounds like it could add additional features.

**Comment by jekkos** [comment]
Think the excel export is not compatible with bootstrap tables. Will put the fix in current master but this functionality will remain broken in bootstrap tables. Might best to swtich to the new export for the latter.

**Comment by jekkos** [comment]
Should be fixed now in master.

**Comment by jekkos** [comment]
Ok to close this issue both for master and bstables?

**Comment by ishtiaquesarwar** [comment]
is this problem sorted out later. i am facing the same error. any hope for a solution or reference?
