### ISSUE TITLE
On "Sale return": item list is not displaying when type item name.

### ISSUE THREAD

**Issue by M-Shahbaz** [jekkos/opensourcepos#54]
Hey,
    I noticed when return a sale item then the items are not showing in the drop down list like displaying in the sale on typing partial name or item no.

Can you guide me how to fix ?

Regards,

**Comment by jekkos** [comment]
have a look in the sales.php controller, method add()
first a check is done to see whether it is a valid receipt..
maybe the first numbers correspond to an invoice number already in the system?

will try to reproduce this later today and let you know.

**Comment by jekkos** [comment]
which branch are you currently using?

**Comment by M-Shahbaz** [comment]
I am using master branch.

**Comment by jekkos** [comment]
Maybe this is what you're look at: if you want to add new items in return of others, you should first enter a valid receipt code in the item number field in return mode. Adding new items should be done in sale mode, so quantities are added up correctly.

I think there's still a possibility to add items directly in return, although it's not really recommended and I don't directly see a usecase for it. It would be better to go for a combined return/sale mode ticket if you want to take back items and sell new ones instead.

**Comment by jekkos** [comment]
Fixed in 46f6824199b6e2a8a707608c92ce5436561a290f
