### ISSUE TITLE
BootStrap Tables Reports.

### ISSUE THREAD

**Issue by odiea** [jekkos/opensourcepos#540]
Currently in some reports it is doing an excel download even if no is checked. This appears to be confined to the summary reports.

**Comment by jekkos** [comment]
Should be fixed now in master.

**Comment by jekkos** [comment]
In bootstrap tables the input view is not showing export to excel anymore (as discussed in #507 and #539). This is now replaced with a bstables extension that enables export to many formats on the table itself.

**Comment by bkrajendra** [comment]
I found Bootstrap Table library very useful. See if it can be incorporated here.
http://issues.wenzhixin.net.cn/bootstrap-table/index.html#extensions/export.html
It has export support in built.

**Comment by jekkos** [comment]
Check boostrap tables branch for that :)

**Comment by jekkos** [comment]
Export has been integrated you can test and give some feedback or fix issues.

**Comment by odiea** [comment]
And where is this new feature. I see no change except nothing is exporting again.

**Comment by jekkos** [comment]
in bstables branch there should be no more export option (at least for the summary reports). I might need to remove one extra view for the low_inventory. There should be an extra button on the right top side of the table that shows export format options. Try to add debug=true and see if it changes anything?

**Comment by odiea** [comment]
I am finding the new dropdown in most modules except Reports.

**Comment by jekkos** [comment]
You're right I still need to enable it in the reports view.

**Comment by jekkos** [comment]
Export in master should work as it was before.

**Comment by odiea** [comment]
In Master the excel export is not working under Inventory Reports.

**Comment by RamkrishnaMondal** [comment]
In detailed reports- Sales, clicking on any table header row, refreshes the table but, after refresh clicking on 'Details' (plus sign) shows wrong sale data.

**Comment by jekkos** [comment]
@odiea Ok could be the same bug in another view for inventory reports. 
@RamkrishnaMondal Ok will look into that later today

**Comment by odiea** [comment]
@jekkos  If you have the export feature built into the table view you might consider removing the excel export at the beginning of the Report.

**Comment by jekkos** [comment]
I removed this option in the input screen in bstables branch. Also I have rerouted the inventory to show the report directly, thus omiting the intermediate screen. I think it shouldn't be too hard to add the remaining filters to the clientside filtering of the table.

**Comment by jekkos** [comment]
Ok no I'd like to correct that last statement. Date filtering is quite essential in limiting the result set size for the reports. It might not be performant at all to do everything clientside in that case.

**Comment by RamkrishnaMondal** [comment]
@jekkos  

>  Also I have rerouted the inventory to show the report directly, thus omiting the intermediate  screen.

 


Still shows the 'excel export' intermediate screen in inventory and low inventory.

**Comment by RamkrishnaMondal** [comment]
Just downloaded the latest Bstables version, Inventory summary report is not working.

**Comment by odiea** [comment]
I second that issue.

**Comment by jekkos** [comment]
Should be fixed now in latest commit.

**Comment by jekkos** [comment]
Also I think there's a bug in sales register with item suggestions. It shows categories but doesn't do anything once you select them. Will check if this problem is also present in master.

**Comment by odiea** [comment]
Receivings does the same thing.

**Comment by odiea** [comment]
In 3.0 it appears that there is no excel for Detailed Reports.

**Comment by jekkos** [comment]
I just checked in 2.4 and no export in detailed either. Think it has always been that way. Ok to close this issue?
