### ISSUE TITLE
Filter inventory_low with Supplier 

### ISSUE THREAD

**Issue by pablos1rvent** [jekkos/opensourcepos#543]
Hey guys, I need to filter the inventory_low with the supplier

Hope you can help me,
Thanks.

**Comment by pablos1rvent** [comment]
Okey, I

**Comment by daN4cat** [comment]
The proper way is to contribute back not come ask what you like and no help. If we all do that this software will die.

**Comment by pablos1rvent** [comment]
Sorry for that
