### ISSUE TITLE
Nginx 404 Not Found

### ISSUE THREAD

**Issue by rayhanhd** [jekkos/opensourcepos#546]
i successfully installed the program.

i can open localhost/ospos/

and it came up with login page, after i tried login with admin as user and pointofsale as password, it came up with 404 error.

thanks for your help.

**Comment by pablos1rvent** [comment]
Show config.php

I think maybe is the mod_rewrite

**Comment by daN4cat** [comment]
Any update on the matter?

If not I'll close this over the week end.

**Comment by bkrajendra** [comment]
Make sure you are following rewrite rules. or check how your server is configured to work with routes.
check this for help: https://www.nginx.com/blog/creating-nginx-rewrite-rules/
I hope this helps.

**Comment by daN4cat** [comment]
No update, no feedback and this points to something more an installation issue. I close.

**Comment by rayhanhd** [comment]
yup, theres problem with mod_rewrite on nginx.
so, i switch to apache instead.

**Comment by truchosky** [comment]
I have problem with nginx too, i tried the typical config (https://www.nginx.com/resources/wiki/start/topics/recipes/codeigniter/), index page is working but inmediatly after log in error 404 appears

**Comment by mckaygerhard** [comment]
define the missing hardcoded rewrite only index.php as index page and problem gone.. another problem due apache2 only pre-config

**Comment by truchosky** [comment]
my bad, I didnt read documentation, I solved only adding two lines to .vhost file,


`location / {
		try_files $uri $uri/ /index.php;
	}

	location /opensourcepos {
		try_files $uri $uri/ /opensourcepos/public/index.php;
	}

	location ~* ^.+.(jpg|jpeg|gif|css|png|js|ico|xml)$ {
		expires  15d;
	}
	
	location ~ \.php$ {
	    try_files $uri =404;
            include /etc/nginx/fastcgi_params;
            fastcgi_pass unix:/var/lib/php7.0-fpm/web11.sock;
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            #fastcgi_intercept_errors on;

	}
`

**Comment by daN4cat** [comment]
Added a link to this issue in the wiki page related to Nginx

**Comment by jekkos** [comment]
Ok could it be useful to add this nginx config to the code itself?

**Comment by daN4cat** [comment]
If you find a way of testing it....

**Comment by Shalta** [comment]
Yep , Its awesome truchosky  thank q so much, i don't not found problem in nginx , right now your way is totally useful. +1:

**Comment by discapacidad5** [comment]
> mal, no leí la documentación, resolví solo agregar dos líneas al archivo .vhost,
> 
> `location / { try_files $uri $uri/ /index.php; }`
> 
> ```
> location /opensourcepos {
> 	try_files $uri $uri/ /opensourcepos/public/index.php;
> }
> 
> location ~* ^.+.(jpg|jpeg|gif|css|png|js|ico|xml)$ {
> 	expires  15d;
> }
> 
> location ~ \.php$ {
>     try_files $uri =404;
>         include /etc/nginx/fastcgi_params;
>         fastcgi_pass unix:/var/lib/php7.0-fpm/web11.sock;
>         fastcgi_index index.php;
>         fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
>         #fastcgi_intercept_errors on;
> 
> }
> ```
> 
> ``
install everything following the instructions and I get the same error I see this information but I do not know where I should paste the have not put all the complete information where I should place this data.

**Comment by gengyunxiang** [comment]
> pointofsale

Nginx NOOOO!!!!
Apache OK!!!
Solve the login 404 problem ospos and opensourcepos

**Comment by AhmadManzoor** [comment]
@truchosky can you please share your nginx file
i am haing issue
"File not found" 
```

server {
  # Example PHP Nginx FPM config file
  listen 80 ;
  listen [::]:80 ;
#  root /var/www/html;
   root /home/ubuntu/rgarments/;
  # Add index.php to setup Nginx, PHP & PHP-FPM config
  index index.php index.html index.htm index.nginx-debian.html;

  server_name garments.zariyat.com;

  location / {
    try_files $uri $uri/ /rgarments/index.php ;
  }

  # pass PHP scripts on Nginx to FastCGI (PHP-FPM) server
  location ~ \.php$ {
    include snippets/fastcgi-php.conf;

    # Nginx php-fpm sock config:
    fastcgi_pass unix:/run/php/php7.0-fpm.sock;
#    fastcgi_index index.php;
#        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    # Nginx php-cgi config :
    # Nginx PHP fastcgi_pass 127.0.0.1:9000;
  }

  # deny access to Apache .htaccess on Nginx with PHP, 
  # if Apache and Nginx document roots concur
  location ~ /\.ht {
    deny all;
  }
} #
 End of PHP FPM Nginx config example
```
my files are in /home/ubuntu/rgarments

**Comment by truchosky** [comment]
if I understand correct your ospos files are in /home/ubuntu/rgarments/, you just need:

location / {
		try_files $uri $uri/ /index.php;
	}

**Comment by AhmadManzoor** [comment]
Thanks, got it working.
