### ISSUE TITLE
Permission to access the module

### ISSUE THREAD

**Issue by itecfx** [jekkos/opensourcepos#55]
The logic to check for access to a specific module does not work correctly. I get "You do not have permission to access the module named Sales (items)"

It seems that the join is not right in module.php
$this->db->join('permissions','permissions.permission_id=modules.module_id');

**Comment by jekkos** [comment]
Can you describe how I can reproduce this issue?

**Comment by jekkos** [comment]
Can't be reproduced, closing this issue now until further information is received to reproduce it.

**Comment by itecfx** [comment]
Hello, I just created a new user and grant access to the Sales module only. After I logged in with the new user the module is not accessible.

**Comment by jekkos** [comment]
you have to check at least one inventory entry underneath the sales module to have access to the parent as well. Maybe the user interface doesn't make this too intuitive at this moment.
