### ISSUE TITLE
bstables: select one customer, delete it and all the customers are deleted

### ISSUE THREAD

**Issue by daN4cat** [jekkos/opensourcepos#552]
Using latest bootstrap-tables branch,

1. Select one customer (I tested twice selecting the last customer in the list)
2. Delete the customer
3. All customers are deleted (checked in the database and they have all deleted = 1

**Comment by daN4cat** [comment]
This happens in Suppliers as well, probably Employees too but I don't dare to test that :-)

**Comment by jekkos** [comment]
Should be fixed now..

**Comment by daN4cat** [comment]
Yes fixed.
