### ISSUE TITLE
bstables: in items change the rows per page, select all items in the page and bulk edit the form is not right

### ISSUE THREAD

**Issue by daN4cat** [jekkos/opensourcepos#553]
As already reported once:

1. go to Items
2. make sure many are listed
3. select the number of rows to be let say 10
4. select all the items in the list with the top checkbox
5. do a bulk edit
6. the form opens showing

![image](https://cloud.githubusercontent.com/assets/636048/15223417/3aec080a-186c-11e6-83da-6e8cf69b3f3b.png)

It might require to do the selection of different number of rows few times before you can reproduce the issue.

**Comment by jekkos** [comment]
This bug is probably also present in master... some thorough testing going on here ;)

**Comment by daN4cat** [comment]
I never noticed this in master....

**Comment by jekkos** [comment]
I'll look into this tomorrow.

**Comment by odiea** [comment]
I have tried over 20 times to reproduce this issue and all I ever get is the following.
![2016-05-12 14_36_49-ugly sweater store -- powered by os point of sale](https://cloud.githubusercontent.com/assets/10962177/15229637/2d71ae86-184f-11e6-9134-fb08acdd94c7.png)

**Comment by daN4cat** [comment]
Maybe this is something that happens with Chrome?

**Comment by jekkos** [comment]
I've tried to reproduce this one this morning. I've only seen it happen 2 times in the ten attempts I did. Also it isn't very clear in which situation it exactly occurs. I've added a log statement that prints the url requested for the dialog in the console. I have a feeling that it might be wrong at a certain point for some reason.

**Comment by daN4cat** [comment]
The console log prints out this when happens: "getting data from undefined"

**Comment by jekkos** [comment]
Ok and at other times the bulk edit url is shown properly?

**Comment by daN4cat** [comment]
Yes it looks like that.

**Comment by daN4cat** [comment]
I have the feeling that this is due to a similar issue as in #554 , I mean that if I change the number of rows and quickly do checkbox all and do bulk edit I get it straight away.
It's probably due to this background network traffic and so on.
In my case latency is higher because I use a remote web service, so it's hosted and not local as maybe some of you use. That's why it's easier to reproduce.

When I get the console log as earlier mentioned I also get the following: "Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/."

**Comment by jekkos** [comment]
It's probably also better for bulk update to refresh all rows at once in comparison with one call per row as it is now. In that case I'll need to rework the response handling code in manage_tables.

Haven't seen the sync xhr request warning in firefox since a while tho. When exactly does it appear?

**Comment by daN4cat** [comment]
#554 was the root cause and it's now fixed. At least I cannot reproduce, but I know it was happening due to the several refresh requests.

XHR was happening when I was getting the issue and after the "undefined" log print.

**Comment by daN4cat** [comment]
I reopen because actually there is this issue that many row refresh are pending and if you updated 100 rows the browser page gets stuck and from the inspector you can see that there are a number of pending GET requests.

Somehow there should be a general upgrade and one refresh for the batch at the end. The way is done now is too slow.

**Comment by daN4cat** [comment]
#432 captures already the bulk edit story. I copy and paste the above over there and close this to avoid duplicates.
