### ISSUE TITLE
bstables: in items, select all the rows with the top checkbox and delete them, click page 2 no table header

### ISSUE THREAD

**Issue by daN4cat** [jekkos/opensourcepos#554]
In items, making sure many items are available so there is pagination.

1. From page 1
2. Select all the items with the top checkbox
3. Delete all the items
4. The page will be shown empty
5. Now click page 2
6. the page will be shown with no table header:

![image](https://cloud.githubusercontent.com/assets/636048/15223602/3be0560c-186d-11e6-9fcf-56ad9bcfc7c7.png)

**Comment by jekkos** [comment]
This is because there's no complete table refresh after delete. Things looked much smoother in that case but it might not be the best option. Will do the refresh anyway after that fancy animation (that should update pagination links as well)

**Comment by daN4cat** [comment]
It seems a bit more than that, any page you select is missing the header. So it's gone completely once you have deleted the complete page.

**Comment by jekkos** [comment]
Just added the refresh and it's a bit better now, header shows but without labels.

**Comment by jekkos** [comment]
Ok found the bug. The selector just took all 'checked' rows, so in case you chose to select the header then that row would vanish as well.

I fixed it but still wondering whether we should do full refresh after delete or not. I tried but then there's a glitch with the feedback bar which doesn't look good either. On the other hand I was planning to replace that one any time soon.

**Comment by jekkos** [comment]
I checked and in the old version there's no full refresh either. So maybe just delete from the dom without full refresh?

**Comment by jekkos** [comment]
Can't make up my mind here.. I'll add full refresh for now so behavior is the same as in search (showing a loading screen).. it also shows the empty table warning properly (in the other case there's just no text left)

**Comment by jekkos** [comment]
Refresh seems to break delete in detailed reports... Seems to be something that only applies if you use serverside pagination. Will add a fallback in that case

**Comment by jekkos** [comment]
Should be good now in latest merge commit.

**Comment by daN4cat** [comment]
Almost done, once the delete happened the refresh works.
However when the page is refreshed, if you click the top checkbox to let say delete the next batch it gets unchecked. You try a second time and gets uncheked. A third time seems fine.

**Comment by jekkos** [comment]
Were there any rows left in your table?

**Comment by jekkos** [comment]
I just tried and seems to work fine as long as there are rows left

**Comment by daN4cat** [comment]
I have something like 11000 rows... and I can reproduce it systematically

**Comment by daN4cat** [comment]
Here what happens:

![20160512-221646_capture](https://cloud.githubusercontent.com/assets/636048/15230795/7b2ad9be-188f-11e6-9090-81dc965290bd.gif)

**Comment by jekkos** [comment]
I'm having a hard time reproducing this. The screencap isn't very clear. So after delete you can't use the select all as it automatically unselects again? Tried in two different browsers to no avail.

**Comment by jekkos** [comment]
Btw the checkbox selected state is managed by bootstrap tables.. so could be a bug in their code.

**Comment by daN4cat** [comment]
Yes, that's what happens and it looks time based unless related to the large number of entries. As said I have about 11000.

**Comment by daN4cat** [comment]
I need to find a way to get a bigger gif, I need to check the config params.

**Comment by daN4cat** [comment]
Tried the latest but still see the problem. This time bigger animated gif:

![20160513-083200_capture](https://cloud.githubusercontent.com/assets/636048/15241080/8c4ebdfe-18e5-11e6-866f-4af4803d4f5a.gif)

**Comment by daN4cat** [comment]
Those are the number of attempts I need to make before the checkbox stays checked.
It's basically like bouncing back to unchecked state, not sure if that's due to some background loading or else. I will try to check with the inspect view what goes on.

**Comment by daN4cat** [comment]
I just checked the inspect / Network and basically that happens whilst data is still fetched from the background.

Therefore to reproduce this you need to have a lot of items as I have.

**Comment by daN4cat** [comment]
It seems like there are many of the same requests happening in window of 3 or 4 sec):

GET /pos3/index.php/items/search?order=asc&limit=20&offset=0&start_date=2010-01-01&end_date=2016-05-13&stock_location=1&filters%5B%5D= HTTP/1.1
Host: www.<removed>.com
Connection: keep-alive
Accept: application/json, text/javascript, */*; q=0.01
X-Requested-With: XMLHttpRequest
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36
Content-Type: application/json
DNT: 1
Referer: https://www.<removed>.com/pos3/index.php/items
Accept-Encoding: gzip, deflate, sdch
Accept-Language: en-US,en;q=0.8,it;q=0.6
Cookie: whostmgrrelogin=no; whostmgrsession=%3aCjMO5d_qitrnmLH0C215xt9pTN6yRcL0MAXLFj1blUoPezDFS0xDTzDWxnw5epoE%2c8ca7b6f012a8b4abacaa7d7ea07d573e737c88c3435ac35fe2c6a7a9f79c5711; timezone=Europe/London; _pk_id.3.7434=b7629d41a93eb455.1447688206.39.1449068438.1449068430.; _pk_id.2.7434=ae96725688a08c49.1448019840.6.1449068571.1449068509.; miconfig1=0; pos2_session=a%3A4%3A%7Bs%3A10%3A%22session_id%22%3Bs%3A32%3A%224dbbb6b65618cce9d7b06155a08ec874%22%3Bs%3A10%3A%22ip_address%22%3Bs%3A13%3A%22194.78.35.195%22%3Bs%3A10%3A%22user_agent%22%3Bs%3A109%3A%22Mozilla%2F5.0+%28Windows+NT+6.1%3B+WOW64%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F47.0.2526.106+Safari%2F537.36%22%3Bs%3A13%3A%22last_activity%22%3Bi%3A1451936403%3B%7D3428141a0989d2a926030f2192ad41680cd5c30b; AjaXplorer=4a6933b7ab9bb23181c4b4206230bd3d; my_session=srhtjiaOJr66Yz0FvxPsVTwklWmrQQ9O%2BYGTKY79GYttw3DgUjHx7ZvJn6GR8W9UBcXICXO7eMo1zmMwJPDXtj0%2Bwi%2B%2Fa%2B9Z1RaJM4VjlOAN3B3JIjik9hAufHzG8eRqOv0ClzedNxDB2VCIJpXHTMWDqYoK21a6QG7UWLa%2FO18BNzjn72rlwX8vrPC%2Bt9Iy0JjYRC9aGovjJ%2BrVkdw1xCwCFHnRnJslOJ7vYH3RX2RCRUB8cFUGmSc12TlHuKgKSQY%2Fcz5qz1zis9ACJyt6XgKrxamllcMuzGPhsxsQzIvBU3Oz7kMK%2FeS9SGiD3rVX1kobz7%2BAWM9RksVoDeVThKnZNq4SCldzD4RFandyESHt%2Fh7%2Fiz9F%2BSKmOFiW5cI46zwWkeYtR5C7IUnF9yP6KeP91rp%2FPfH2rs1KfetiZoQTsZSlR88S6iIMtAg9LQmlA2E7sqFRzPem9ptP5w8PofytOYGn%2BhK%2BBumcp7o707xIJfQsmscBbKNVmxxk9K0MEiPE0yw4sbP73aGUyeTeAwpS8C%2Fy8g%2BJjD4SniD7v1ZSY377iLbkSQWAmlUJh6YCEfTXRNWSC0k%2FenHML08%2Bw2d4bS%2FYyFORYE2bUirbDj4bXSn4musriC2omDJOgi7d; Drupal.tableDrag.showWeight=0; PHPSESSID=ab44744cf0e840ecc9ed8a6f49e137ce; mail_sessid=961b523bd186bc3689e7551c86c42ba6; language=en; has_js=1; bb2_screener_=1463072915+81.99.217.180; ospos_session=1467ccd1a42f2a55dfa2b28b89eaddd360587f93



HTTP/1.1 200 OK
Date: Fri, 13 May 2016 07:39:45 GMT
Server: Apache
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
Content-Encoding: gzip
Vary: Accept-Encoding
Set-Cookie: ospos_session=1467ccd1a42f2a55dfa2b28b89eaddd360587f93; expires=Fri, 13-May-2016 09:39:48 GMT; Max-Age=7200; path=/; httponly
X-Content-Type-Options: nosniff
Keep-Alive: timeout=5, max=95
Connection: Keep-Alive
Transfer-Encoding: chunked
Content-Type: text/html; charset=UTF-8

{"total":11163,"rows":[{"items.item_id":"596","item_number":"8033425988082","name":"DRESS PAILLETTES\/SIL&#8230;","category":"DRESS","company_name":null,"cost_price":"\u00a361.12","unit_price":"\u00a3165.00","quantity":"0","tax_percents":"-","item_pic":"","inventory":"<a href=\"https:\/\/www.<remove>.com\/pos3\/index.php\/items\/inventory\/596\" class=\"modal-dlg modal-btn-submit\" title=\"Update Inventory\"><span class=\"glyphicon glyphicon-pushpin\"><\/span><\/a>","stock":"<a href=\"https:\/\/www.<remove>.com\/pos3\/index.php\/items\/count_details\/596\" class=\"modal-dlg\" title=\"Inventory Count Details\"><span class=\"glyphicon glyphicon-list-alt\"><\/span><\/a>","edit":"<a href=\"https:\/\/www.<remove>.com\/pos3\/index.php\/items\/view\/596\" class=\"modal-dlg modal-btn-submit\" title=\"Update Item\"><span class=\"glyphicon glyphicon-edit\"><\/span><\/a>"},{"items.item_id":"597","item_number":"8033425988099","name":"DRESS PAILLETTES\/SIL&#8230;","category":"DRESS","company_name":null,"cost_price":"\u00a361.12","unit_price":"\u00a3165.00","quantity":"0","tax_percents":"-","item_pic":"","inventory":"<a href=\"https:\/\/www.<remove>.com\/pos3\/index.php\/items\/inventory\/597\" class=\"modal-dlg modal-btn-submit\" title=\"Update Inventory\"><span class=\"glyphicon glyphicon-pushpin\"><\/span><\/a>","stock":"<a href=\"https:\/\/www.<remove>.com\/pos3\/index.php\/items\/count_details\/597\" class=\"modal-dlg\" title=\"Inventory Count Details\"><span class=\"glyphicon glyphicon-list-alt\"><\/span><\/a>","edit":"<a href=\"https:\/\/www.<remove>.com\/pos3\/index.php\/items\/view\/597\" class=\"modal-dlg modal-btn-submit\" title=\"Update Item\"><span class=\"glyphicon glyphicon-edit\"><\/span><\/a>"},{"items.item_id":"598","item_number":"8033425988105","name":"DRESS PAILLETTES\/SIL&#8230;","category":"DRESS","company_name":null,"cost_price":"\u00a361.12","unit_price":"\u00a3165.00","quantity":"0","tax_percents":"-","item_pic":"","inventory":"<a href=\"https:\/\/www.<remove>.com\/pos3\/index.php\/items\/inventory\/598\" class=\"modal-dlg modal-btn-submit\" title=\"Update Inventory\"><span class=\"glyphicon glyphicon-pushpin\"><\/span><\/a>","stock":"<a href=\"https:\/\/www.<remove>.com\/pos3\/index.php\/items\/count_details\/598\" class=\"modal-dlg\" title=\"Inventory Count Details\"><span class=\"glyphicon glyphicon-list-alt\"><\/span><\/a>","edit":"<a href=\"https:\/\/www.<remove>.com\/pos3\/index.php\/items\/view\/598\" class=\"modal-dlg modal-btn-submit\" title=\"Update Item\"><span class=\"glyphicon glyphicon-edit\"><\/span><\/a>"},{"items.item_id":"599","item_number":"8058186040381","name":"PULLOVER, JACQUARD&#8230;","category":"TOP","company_name":null,"cost_price":"\u00a351.86","unit_price":"\u00a3140.00","quantity":"0","tax_percents":"-","item_pic":"","inventory":"<a href=\"https:\/\/www.<remove>.com\/pos3\/index.php\/items\/inventory\/599\" class=\"modal-dlg modal-btn-submit\" title=\"Update Inventory\"><span class=\"glyphicon glyphicon-pushpin\"><\/span><\/a>","stock":"<a href=\"https:\/\/www.<remove>.com\/pos3\/index.php\/items\/count_details\/599\" class=\"modal-dlg\" title=\"Inventory Count Details\"><span class=\"glyphicon glyphicon-list-alt\"><\/span><\/a>","edit":"<a href=\"https:\/\/www.<remove>.com\/pos3\/index.php\/items\/view\/599\" class=\"modal-dlg modal-btn-submit\" title=\"Update Item\"><span class=\"glyphicon glyphicon-edit\"><\/span><\/a>"},{"items.item_id":"600","item_number":"8058186040398","name":"PULLOVER, JACQUARD&#8230;","category":"TOP","company_name":null,"cost_price":"\u00a351.86","unit_price":"\u00a3140.00","quantity":"0","tax_percents":"-","item_pic":"","inventory":"<a href=\"https:\/\/www.<remove>.com\/pos3\/index.php\/items\/inventory\/600\" class=\"modal-dlg modal-btn-submit\" title=\"Update Inventory\"><span class=\"glyphicon glyphicon-pushpin\"><\/span><\/a>","stock":"<a href=\"https:\/\/www.<remove>.com\/pos3\/index.php\/items\/count_details\/600\" class=\"modal-dlg\" title=\"Inventory Count Details\"><span class=\"glyphicon glyphicon-list-alt\"><\/span><\/a>","edit":"<a href=\"https:\/\/www.<remove>.com\/pos3\/index.php\/items\/view\/600\" class=\"modal-dlg modal-btn-submit\" title=\"Update Item\"><span class=\"glyphicon glyphicon-edit\"><\/span><\/a>"},{"items.item_id":"601","item_number":"8058186040404","name":"PULLOVER, JACQUARD&#8230;","category":"TOP","company_name":null,"cost_price":"\u00a351.86","unit_price":"\u00a3140.00","quantity":"0","tax_percents":"-","item_pic":"","inventory":"<a href=\"https:\/\/www.<remove>.com\/pos3\/index.php\/items\/inventory\/601\" class=\"modal-dlg modal-btn-submit\" title=\"Update Inventory\"><span class=\"glyphicon glyphicon-pushpin\"><\/span><\/a>","stock":"<a href=\"https:\/\/www.<remove>.com\/pos3\/index.php\/items\/count_details\/601\" class=\"modal-dlg\" title=\"Inventory Count Details\"><span class=\"glyphicon glyphicon-list-alt\"><\/span><\/a>","edit":"<a href=\"https:\/\/www.<remove>.com\/pos3\/index.php\/items\/view\/601\" class=\"modal-dlg modal-btn-submit\" title=\"Update Item\"><span class=\"glyphicon glyphicon-edit\"><\/span><\/a>"},{"items.item_id":"602","item_number":null,"name":"CHOCOLATE BAG&#8230;","category":"CHOCOLATES","company_name":null,"cost_price":"\u00a32.30","unit_price":"\u00a36.00","quantity":"0","tax_percents":"-","item_pic":"","inventory":"<a href=\"https:\/\/www.<remove>.com\/pos3\/index.php\/items\/inventory\/602\" class=\"modal-dlg modal-btn-submit\" title=\"Update Inventory\"><span class=\"glyphicon glyphicon-pushpin\"><\/span><\/a>","stock":"<a href=\"https:\/\/www.<remove>.com\/pos3\/index.php\/items\/count_details\/602\" class=\"modal-dlg\" title=\"Inventory Count Details\"><span class=\"glyphicon glyphicon-list-alt\"><\/span><\/a>","edit":"<a href=\"https:\/\/www.<remove>.com\/pos3\/index.php\/items\/view\/602\" class=\"modal-dlg modal-btn-submit\" title=\"Update Item\"><span class=\"glyphicon glyphicon-edit\"><\/span><\/a>"},{"items.item_id":"603","item_number":null,"name":"CHOCOLATE BAG&#8230;","category":"CHOCOLATES","company_name":null,"cost_price":"\u00a33.48","unit_price":"\u00a38.00","quantity":"0","tax_percents":"-","item_pic":"","inventory":"<a href=\"https:\/\/www.<remove>.com\/pos3\/index.php\/items\/inventory\/603\" class=\"modal-dlg modal-btn-submit\" title=\"Update Inventory\"><span class=\"glyphicon glyphicon-pushpin\"><\/span><\/a>","stock":"<a href=\"https:\/\/www.<remove>.com\/pos3\/index.php\/items\/count_details\/603\" class=\"modal-dlg\" title=\"Inventory Count Details\"><span class=\"glyphicon glyphicon-list-alt\"><\/span><\/a>","edit":"<a href=\"https:\/\/www.<remove>.com\/pos3\/index.php\/items\/view\/603\" class=\"modal-dlg modal-btn-submit\" title=\"Update Item\"><span class=\"glyphicon glyphicon-edit\"><\/span><\/a>"},{"items.item_id":"605","item_number":"2000005332425","name":"TERMINUS TROUSERS&#8230;","category":"TROUSERS","company_name":null,"cost_price":"\u00a342.00","unit_price":"\u00a3126.00","quantity":"0","tax_percents":"-","item_pic":"","inventory":"<a href=\"https:\/\/www.<remove>.com\/pos3\/index.php\/items\/inventory\/605\" class=\"modal-dlg modal-btn-submit\" title=\"Update Inventory\"><span class=\"glyphicon glyphicon-pushpin\"><\/span><\/a>","stock":"<a href=\"https:\/\/www.<remove>.com\/pos3\/index.php\/items\/count_details\/605\" class=\"modal-dlg\" title=\"Inventory Count Details\"><span class=\"glyphicon glyphicon-list-alt\"><\/span><\/a>","edit":"<a href=\"https:\/\/www.<remove>.com\/pos3\/index.php\/items\/view\/605\" class=\"modal-dlg modal-btn-submit\" title=\"Update Item\"><span class=\"glyphicon glyphicon-edit\"><\/span><\/a>"},{"items.item_id":"606","item_number":"2000005332418","name":"TERMINUS TROUSERS&#8230;","category":"TROUSERS","company_name":null,"cost_price":"\u00a342.00","unit_price":"\u00a3126.00","quantity":"0","tax_percents":"-","item_pic":"","inventory":"<a href=\"https:\/\/www.<remove>.com\/pos3\/index.php\/items\/inventory\/606\" class=\"modal-dlg modal-btn-submit\" title=\"Update Inventory\"><span class=\"glyphicon glyphicon-pushpin\"><\/span><\/a>","stock":"<a href=\"https:\/\/www.<remove>.com\/pos3\/index.php\/items\/count_details\/606\" class=\"modal-dlg\" title=\"Inventory Count Details\"><span class=\"glyphicon glyphicon-list-alt\"><\/span><\/a>","edit":"<a href=\"https:\/\/www.<remove>.com\/pos3\/index.php\/items\/view\/606\" class=\"modal-dlg modal-btn-submit\" title=\"Update Item\"><span class=\"glyphicon glyphicon-edit\"><\/span><\/a>"},{"items.item_id":"607","item_number":"8002535078570","name":"BLACK TROUSERS&#8230;","category":"TROUSERS","company_name":null,"cost_price":"\u00a369.60","unit_price":"\u00a3155.00","quantity":"0","tax_percents":"-","item_pic":"","inventory":"<a href=\"https:\/\/www.<remove>.com\/pos3\/index.php\/items\/inventory\/607\" class=\"modal-dlg modal-btn-submit\" title=\"Update Inventory\"><span class=\"glyphicon glyphicon-pushpin\"><\/span><\/a>","stock":"<a href=\"https:\/\/www.<remove>.com\/pos3\/index.php\/items\/count_details\/607\" class=\"modal-dlg\" title=\"Inventory Count Details\"><span class=\"glyphicon glyphicon-list-alt\"><\/span><\/a>","edit":"<a href=\"https:\/\/www.<remove>.com\/pos3\/index.php\/items\/view\/607\" class=\"modal-dlg modal-btn-submit\" title=\"Update Item\"><span class=\"glyphicon glyphicon-edit\"><\/span><\/a>"},{"items.item_id":"608","item_number":null,"name":"TAILORING","category":"TAILORING","company_name":null,"cost_price":"\u00a38.00","unit_price":"\u00a38.00","quantity":"0","tax_percents":"-","item_pic":"","inventory":"<a href=\"https:\/\/www.<remove>.com\/pos3\/index.php\/items\/inventory\/608\" class=\"modal-dlg modal-btn-submit\" title=\"Update Inventory\"><span class=\"glyphicon glyphicon-pushpin\"><\/span><\/a>","stock":"<a href=\"https:\/\/www.<remove>.com\/pos3\/index.php\/items\/count_details\/608\" class=\"modal-dlg\" title=\"Inventory Count Details\"><span class=\"glyphicon glyphicon-list-alt\"><\/span><\/a>","edit":"<a href=\"https:\/\/www.<remove>.com\/pos3\/index.php\/items\/view\/608\" class=\"modal-dlg modal-btn-submit\" title=\"Update Item\"><span class=\"glyphicon glyphicon-edit\"><\/span><\/a>"},{"items.item_id":"609","item_number":null,"name":"DIVERS JEWELLERY&#8230;","category":"JEWELLERY","company_name":null,"cost_price":"\u00a35.00","unit_price":"\u00a39.60","quantity":"0","tax_percents":"-","item_pic":"","inventory":"<a href=\"https:\/\/www.<remove>.com\/pos3\/index.php\/items\/inventory\/609\" class=\"modal-dlg modal-btn-submit\" title=\"Update Inventory\"><span class=\"glyphicon glyphicon-pushpin\"><\/span><\/a>","stock":"<a href=\"https:\/\/www.<remove>.com\/pos3\/index.php\/items\/count_details\/609\" class=\"modal-dlg\" title=\"Inventory Count Details\"><span class=\"glyphicon glyphicon-list-alt\"><\/span><\/a>","edit":"<a href=\"https:\/\/www.<remove>.com\/pos3\/index.php\/items\/view\/609\" class=\"modal-dlg modal-btn-submit\" title=\"Update Item\"><span class=\"glyphicon glyphicon-edit\"><\/span><\/a>"},{"items.item_id":"610","item_number":"5414712359588","name":"BALLROOM DRESS&#8230;","category":"DRESS","company_name":null,"cost_price":"\u00a3113.75","unit_price":"\u00a3305.00","quantity":"0","tax_percents":"-","item_pic":"","inventory":"<a href=\"https:\/\/www.<remove>.com\/pos3\/index.php\/items\/inventory\/610\" class=\"modal-dlg modal-btn-submit\" title=\"Update Inventory\"><span class=\"glyphicon glyphicon-pushpin\"><\/span><\/a>","stock":"<a href=\"https:\/\/www.<remove>.com\/pos3\/index.php\/items\/count_details\/610\" class=\"modal-dlg\" title=\"Inventory Count Details\"><span class=\"glyphicon glyphicon-list-alt\"><\/span><\/a>","edit":"<a href=\"https:\/\/www.<remove>.com\/pos3\/index.php\/items\/view\/610\" class=\"modal-dlg modal-btn-submit\" title=\"Update Item\"><span class=\"glyphicon glyphicon-edit\"><\/span><\/a>"},{"items.item_id":"611","item_number":"5414712359595","name":"BALLROOM DRESS&#8230;","category":"DRESS","company_name":null,"cost_price":"\u00a3113.75","unit_price":"\u00a3305.00","quantity":"0","tax_percents":"-","item_pic":"","inventory":"<a href=\"https:\/\/www.<remove>.com\/pos3\/index.php\/items\/inventory\/611\" class=\"modal-dlg modal-btn-submit\" title=\"Update Inventory\"><span class=\"glyphicon glyphicon-pushpin\"><\/span><\/a>","stock":"<a href=\"https:\/\/www.<remove>.com\/pos3\/index.php\/items\/count_details\/611\" class=\"modal-dlg\" title=\"Inventory Count Details\"><span class=\"glyphicon glyphicon-list-alt\"><\/span><\/a>","edit":"<a href=\"https:\/\/www.<remove>.com\/pos3\/index.php\/items\/view\/611\" class=\"modal-dlg modal-btn-submit\" title=\"Update Item\"><span class=\"glyphicon glyphicon-edit\"><\/span><\/a>"},{"items.item_id":"612","item_number":"5414712359601","name":"BALLROOM DRESS&#8230;","category":"DRESS","company_name":null,"cost_price":"\u00a3113.75","unit_price":"\u00a3305.00","quantity":"0","tax_percents":"-","item_pic":"","inventory":"<a href=\"https:\/\/www.<remove>.com\/pos3\/index.php\/items\/inventory\/612\" class=\"modal-dlg modal-btn-submit\" title=\"Update Inventory\"><span class=\"glyphicon glyphicon-pushpin\"><\/span><\/a>","stock":"<a href=\"https:\/\/www.<remove>.com\/pos3\/index.php\/items\/count_details\/612\" class=\"modal-dlg\" title=\"Inventory Count Details\"><span class=\"glyphicon glyphicon-list-alt\"><\/span><\/a>","edit":"<a href=\"https:\/\/www.<remove>.com\/pos3\/index.php\/items\/view\/612\" class=\"modal-dlg modal-btn-submit\" title=\"Update Item\"><span class=\"glyphicon glyphicon-edit\"><\/span><\/a>"},{"items.item_id":"613","item_number":"5414712359618","name":"BALLROOM DRESS&#8230;","category":"DRESS","company_name":null,"cost_price":"\u00a3113.75","unit_price":"\u00a3305.00","quantity":"0","tax_percents":"-","item_pic":"","inventory":"<a href=\"https:\/\/www.<remove>.com\/pos3\/index.php\/items\/inventory\/613\" class=\"modal-dlg modal-btn-submit\" title=\"Update Inventory\"><span class=\"glyphicon glyphicon-pushpin\"><\/span><\/a>","stock":"<a href=\"https:\/\/www.<remove>.com\/pos3\/index.php\/items\/count_details\/613\" class=\"modal-dlg\" title=\"Inventory Count Details\"><span class=\"glyphicon glyphicon-list-alt\"><\/span><\/a>","edit":"<a href=\"https:\/\/www.<remove>.com\/pos3\/index.php\/items\/view\/613\" class=\"modal-dlg modal-btn-submit\" title=\"Update Item\"><span class=\"glyphicon glyphicon-edit\"><\/span><\/a>"},{"items.item_id":"614","item_number":"5414712361154","name":"BOBO DRESS -&#8230;","category":"DRESS","company_name":null,"cost_price":"\u00a3102.19","unit_price":"\u00a3275.00","quantity":"0","tax_percents":"-","item_pic":"","inventory":"<a href=\"https:\/\/www.<remove>.com\/pos3\/index.php\/items\/inventory\/614\" class=\"modal-dlg modal-btn-submit\" title=\"Update Inventory\"><span class=\"glyphicon glyphicon-pushpin\"><\/span><\/a>","stock":"<a href=\"https:\/\/www.<remove>.com\/pos3\/index.php\/items\/count_details\/614\" class=\"modal-dlg\" title=\"Inventory Count Details\"><span class=\"glyphicon glyphicon-list-alt\"><\/span><\/a>","edit":"<a href=\"https:\/\/www.<remove>.com\/pos3\/index.php\/items\/view\/614\" class=\"modal-dlg modal-btn-submit\" title=\"Update Item\"><span class=\"glyphicon glyphicon-edit\"><\/span><\/a>"},{"items.item_id":"615","item_number":"5414712361161","name":"BOBO DRESS -&#8230;","category":"DRESS","company_name":null,"cost_price":"\u00a3102.19","unit_price":"\u00a3275.00","quantity":"0","tax_percents":"-","item_pic":"","inventory":"<a href=\"https:\/\/www.<remove>.com\/pos3\/index.php\/items\/inventory\/615\" class=\"modal-dlg modal-btn-submit\" title=\"Update Inventory\"><span class=\"glyphicon glyphicon-pushpin\"><\/span><\/a>","stock":"<a href=\"https:\/\/www.<remove>.com\/pos3\/index.php\/items\/count_details\/615\" class=\"modal-dlg\" title=\"Inventory Count Details\"><span class=\"glyphicon glyphicon-list-alt\"><\/span><\/a>","edit":"<a href=\"https:\/\/www.<remove>.com\/pos3\/index.php\/items\/view\/615\" class=\"modal-dlg modal-btn-submit\" title=\"Update Item\"><span class=\"glyphicon glyphicon-edit\"><\/span><\/a>"},{"items.item_id":"616","item_number":"5414712361178","name":"BOBO DRESS -&#8230;","category":"DRESS","company_name":null,"cost_price":"\u00a3102.19","unit_price":"\u00a3275.00","quantity":"0","tax_percents":"-","item_pic":"","inventory":"<a href=\"https:\/\/www.<remove>.com\/pos3\/index.php\/items\/inventory\/616\" class=\"modal-dlg modal-btn-submit\" title=\"Update Inventory\"><span class=\"glyphicon glyphicon-pushpin\"><\/span><\/a>","stock":"<a href=\"https:\/\/www.<remove>.com\/pos3\/index.php\/items\/count_details\/616\" class=\"modal-dlg\" title=\"Inventory Count Details\"><span class=\"glyphicon glyphicon-list-alt\"><\/span><\/a>","edit":"<a href=\"https:\/\/www.<remove>.com\/pos3\/index.php\/items\/view\/616\" class=\"modal-dlg modal-btn-submit\" title=\"Update Item\"><span class=\"glyphicon glyphicon-edit\"><\/span><\/a>"}]}

**Comment by jekkos** [comment]
The problem might indeed be that the refresh is done multiple times and that the call for that function should change position. Think there should be only one call to search after the delete is done so this is probably wrong anyway.

**Comment by daN4cat** [comment]
Yes, there are multiple calls and during that time I experience the issue.
One call should be enough if it's the same and then the undelete should not be a major worry.

**Comment by jekkos** [comment]
Refresh only happens after last row's animation has ended

**Comment by daN4cat** [comment]
Tested and it's now fixed.
