### ISSUE TITLE
bstables: in suppliers, giftcard and employee sorting doesn't work

### ISSUE THREAD

**Issue by daN4cat** [jekkos/opensourcepos#555]
My condition is several entries and so there is pagination, so not sure that makes a difference.

Click any column header and there is no sorting of the table.

**Comment by daN4cat** [comment]
The same in Employees, Customer works fine.

**Comment by daN4cat** [comment]
Items and Item_kits are fine, Giftcard has the same issue no sorting.

**Comment by jekkos** [comment]
Should be fixed now in latest commit

**Comment by daN4cat** [comment]
Tested and indeed fixed.
