### ISSUE TITLE
bstables: Takings prints the table from page 2 leaving page 1 with just the filters

### ISSUE THREAD

**Issue by daN4cat** [jekkos/opensourcepos#558]
To reproduce this issue a lot of rows are required so one page is exceeded.
With few rows the taking is always printed in page 1.

Also it would be probably good to reduce the font size so the rows fit better the page.

**Comment by jekkos** [comment]
So once there is a second page then the first isn't printed correctly? Need to make a data set with sufficient sales to reproduce this.

**Comment by daN4cat** [comment]
Yes, it seems to be like that. At least that's the why I reproduce it.

**Comment by jekkos** [comment]
Just did a quick test and with pagination all pages seems to print fine.

**Comment by daN4cat** [comment]
Have you used different browsers? I use Chrome. But I'll try again later.

**Comment by jekkos** [comment]
Just tried with firefox and print previewed takings on multiple pages.. will test with chrome then as well.

**Comment by daN4cat** [comment]
It's still there.

Page 1:

![image](https://cloud.githubusercontent.com/assets/636048/15421658/712dcbb4-1e6c-11e6-8da6-58db45f18b88.png)

Page 2:

![image](https://cloud.githubusercontent.com/assets/636048/15421675/8642d2ba-1e6c-11e6-8598-88540381b676.png)

**Comment by jekkos** [comment]
seems like chrome doesn't want to fit first table part in the page and wraps to the second

**Comment by jekkos** [comment]
might help to play a little with css before print to see what is causing this bug

**Comment by jekkos** [comment]
Can't reproduce anymore. This bug might have been fixed by hiding columns with no title in #563.

![screenshot from 2016-05-24 17 08 08](https://cloud.githubusercontent.com/assets/576234/15509139/bf6d2888-21d2-11e6-94e2-3b8ae16ee8a7.png)

**Comment by daN4cat** [comment]
Still there.

**Comment by daN4cat** [comment]
If you have by any chance removed one field you won't get it.

**Comment by jekkos** [comment]
![screenshot from 2016-05-25 08 12 18](https://cloud.githubusercontent.com/assets/576234/15529821/74319ee8-2250-11e6-8949-2cc28c8ed719.png)

Tried again this morning and can't reproduce. It seems that there's a bit less space for the text on your screencap than on mine. It might have something to do with the kind of data that you're printing.

If you find the time then maybe it might be easier to have a look yourself? The print preview resizes correctly if I switch paper sizes. Even when I increase zoom level everything fits into the first page.

**Comment by daN4cat** [comment]
Yes, the table doesn't resize and touching margins changes it. But this is strange, it should be responsive and resize the table according to the output media size.

**Comment by jekkos** [comment]
I could try to add the responsive table plugin for bstables and see if it changes anything.

**Comment by daN4cat** [comment]
Maybe would be a good idea. To simulate try to leave the table in full (no removed columns) and narrow the margins. That is the issue in the end. Thanks for looking into this.

**Comment by jekkos** [comment]
I've added the mobile (responsive) addon for bstables.. maybe retest not sure if it fixes the issue

**Comment by jekkos** [comment]
but tables are responsive now anyway

**Comment by daN4cat** [comment]
I'll do next days, I have some travelling from tomorrow.

**Comment by daN4cat** [comment]
OK, tested but I'm afraid the problem is still there. The only workaround is to change the margins to fit the table in or remove one column from Takings view.

So the responsiveness somehow doesn't apply to the printing view?

**Comment by jekkos** [comment]
ok so I might just be able to fix it by adding a different margin css rule for the print stylesheet?

**Comment by jekkos** [comment]
I think the mobile plugin overrides some of the default behavior for horizontal resize but that's about it.

**Comment by daN4cat** [comment]
It might explain why instead of resizing I get the scroll horizontal bar in a case in Items. I didn't want to create a bug, but it could be a counter effect of the plugin.

**Comment by jekkos** [comment]
Maybe just get rid of the repsonsive plugin again? It doesn't seem to help beside adding a horizontal scrollbar on resize

**Comment by daN4cat** [comment]
I can remember, but the horizontal scrollbar is added when you set a different language like Spanish.
Was it like that before adding the plug in?

**Comment by daN4cat** [comment]
@jekkos can you please remove the mobile plugin so we test again? I would do but since I don't have the fix to bstable js I risk to wipe it in committing a regen of dist files.

**Comment by daN4cat** [comment]
I don't see this problem anymore. I close.

**Comment by jekkos** [comment]
Ok I had just removed the mobile plugin.. not sure if it's still needed then?

**Comment by daN4cat** [comment]
No need as I tested removing it by myself too, but I didn't test with a mobile phone if it makes a difference in other views and etc.

**Comment by jekkos** [comment]
OK so leave it in there then with the -horizontal scrollbar? I'll undelete it in that case
