### ISSUE TITLE
bstables: Takings totals last row needs finishing off

### ISSUE THREAD

**Issue by daN4cat** [jekkos/opensourcepos#559]
The last Totals row doesn't seem complete, the Amount due total is always zero and on the left side there is a check box that probably should not be displayed (but might be a bootstrap-tables limitation):

![image](https://cloud.githubusercontent.com/assets/636048/15267832/ed0d83de-19c4-11e6-8555-47029033d2ac.png)

**Comment by jekkos** [comment]
Should be fixed in latest

**Comment by daN4cat** [comment]
Tested and all fine now. I close.
