### ISSUE TITLE
Currency Symbol not updating

### ISSUE THREAD

**Issue by M-Shahbaz** [jekkos/opensourcepos#56]
I changed the currency symbol in app config but it wasn't effecting and still showing '$'.
After going through the code I found this in (application\helpers\currency_helper.php):

$currency_symbol = $CI->config->item('currency_symbol') ? $CI->config->item('currency_symbol') : '$';
$currency_symbol = $currency_symbol == '$' && $escape ? '\$' : '$'; 

I think this causing the symbol to make it always '$'.
So I commented the second line and currency symbol changes in the app everywhere.

**Comment by jekkos** [comment]
Indeed this was already fixed in 6e7176
