### ISSUE TITLE
Merge bootstrap-tables branch into master

### ISSUE THREAD

**Issue by daN4cat** [jekkos/opensourcepos#560]
I believe it's time to merge bootstrap-tables branch into master so we can progress other parts whilst fixing the remaining bugs.

I put on hold few things to avoid having too much to merge or rebase.

**Comment by RamkrishnaMondal** [comment]
Detailed reports still have bug.
'Delete' in sales Takings still have bug, it deletes whole page(s). I tried to delete 3 sales, it deleted 3 pages x 10 rows.

**Comment by daN4cat** [comment]
Please create new issues otherwise it gets messy.

**Comment by RamkrishnaMondal** [comment]
Ok

**Comment by jekkos** [comment]
Currently only issue left is #558.

**Comment by daN4cat** [comment]
Maybe you can merge to master and fix the print issue there as it's mainly fine now.
In this way we can continue with other features without affecting bootstrap-tables work.

**Comment by jekkos** [comment]
Yes I'll do the merge then today or tomorrow. WIl look into this last issue as well. Was also trying to get the tests working again.

**Comment by jekkos** [comment]
I'm happy to announce that after about one month and a half of development and bugfixing that bootstrap tables is merged in master!

**Comment by daN4cat** [comment]
Well done! Thanks

**Comment by daN4cat** [comment]
Would be good to delete bootstrap-tables branch now.
