### ISSUE TITLE
bstables: buy jekkos a beer for all the work he has done about this great change!

### ISSUE THREAD

**Issue by daN4cat** [jekkos/opensourcepos#562]
Not a code issue, but it's another kind of issue.

I believe the introduction of bootstrap-tables in OSPOS is a great addition, we will have more flexibility in adding columns, filtering, export and more to come.

It's a lot of work done for free and I believe it's honest to at least pay a beer to jekkos for all the good work he has done.

There is a button on the front page of https://github.com/jekkos/opensourcepos with "Donate" written on it.

According to this website (dated 2012/2013) the cost of a beer in Belgium was 1.50Euro: http://budgettraveller.org/cheapest-beer-in-europe-check-my-europe-cheap-beer-index/

Let's assume it's now 2E, but PayPal takes a cut (10% or 20% can't remember) so probably 5E would be good, yes two beers anyway are better than one.

A small amount for some of us, maybe a bigger amount for some others but let's click that button to say thank you.

**Comment by pablos1rvent** [comment]
In Spain we have a "caña" that costs 50cents or 0.5€ and with 2€ you have a tapa+caña (tapa = whatever you want of the menu). 

I'm gonna donate to this because is great and my business is going well with this. I hope this will be better with updates and the contributions of us.

Thanks!

**Comment by jekkos** [comment]
@daN4cat Thanks a bunch for the donation! Didn't expect something like that to come from your side as you're already contributing more than enough in code and community support. Next time the beer is on me ;)

**Comment by daN4cat** [comment]
@jekkos you deserve it.

**Comment by jekkos** [comment]
Think we're getting closer to a new release.. Will try to see what is marked as 3.0 so we can decide on remaining scope.

**Comment by jekkos** [comment]
Release party would be a nice to have as well ;)

**Comment by pablos1rvent** [comment]
@jekkos 
![fiesta](https://cloud.githubusercontent.com/assets/17593856/15391514/cb2a963e-1dc1-11e6-90b3-91a61dcc2e79.jpg)

**Comment by pablos1rvent** [comment]
just kidding hahaha

**Comment by jekkos** [comment]
@pablos1rvent Is that a famlily photo of yours?

**Comment by pablos1rvent** [comment]
@jekkos hahaha very funny
