### ISSUE TITLE
BStables Detailed Reports Table views for last 3 reports

### ISSUE THREAD

**Issue by odiea** [jekkos/opensourcepos#564]
Under Detailed reports only the first 2 reports shows a table view. If it's a detailed report it seems like more info should show.

**Comment by daN4cat** [comment]
yes, you mean that Customers, Discounts and Employees are showing nothing.

**Comment by RamkrishnaMondal** [comment]
I  can also confirm the bug in detailed reports.

**Comment by odiea** [comment]
Yes. Those reports are not showing tables.

**Comment by odiea** [comment]
Detailed Sales Report Using update when I try to update the first row nothing happens when I change the payment method the other rows update just fine.

**Comment by jekkos** [comment]
Should be fixed now in latest

**Comment by daN4cat** [comment]
All looks good to me, even the sale update is fine on any line (just took a random set, first and last lines included).

**Comment by RamkrishnaMondal** [comment]
@daN4cat  Please try to edit a sale on other pages except page 1, looks like the old bug backs again :thinking_face:
