### ISSUE TITLE
updates Portuguese

### ISSUE THREAD

**Issue by arteiro** [jekkos/opensourcepos#567]
Good morning annex updates Portuguese  for some fields ..
[translations.zip](https://github.com/jekkos/opensourcepos/files/268403/translations.zip)

**Comment by daN4cat** [comment]
@arteiro can you please take the latest master and translate that before I look into your update? Thanks

**Comment by arteiro** [comment]
OK,
I downloaded the latest files today:
[translations.zip](https://github.com/jekkos/opensourcepos/files/272982/translations.zip)

**Comment by daN4cat** [comment]
Translations now in master.
