### ISSUE TITLE
Gift card sort

### ISSUE THREAD

**Issue by odiea** [jekkos/opensourcepos#57]
Sorting Gift card number does not work.
 You have to give permission for stock under Item not to get #55 error.
Are you going to implement a barcode print feature?

**Comment by jekkos** [comment]
If I disable stock permission under items, I'm still able to access sales and receivings without any problem. Regarding the sort issue, you mean you can't sort on the giftcard number column?

**Comment by odiea** [comment]
Yes the Gift card number column cannot be sorted. I get the following 
error unles I check stock under sales.

**Comment by jekkos** [comment]
Regarding the stock under sales, that is supposed to work like that. If you would have multiple stocks then you have control over which user can sell from which stock. You will need to check at least one stock to be able to sell at least any item. 

So functionally it makes sense. From a user perspective, maybe the parent item should be disabled automatically as well when none of it's children are enabled. I looked into doing this but there's quite some code needed to fix that (and to me that wasn't worth the effort at that time)

**Comment by odiea** [comment]
I totally agree with you. Is there a way to just List Sales that would 
then give permission to both settings? I believe people would get 
confused with the current settings.

**Comment by odiea** [comment]
Or make stock under sales a required field.

**Comment by jekkos** [comment]
Giftcard number sort fixed in 86eb39
