### ISSUE TITLE
BSTables : Detailed Reports - Sales shows wrong details data after refresh 

### ISSUE THREAD

**Issue by RamkrishnaMondal** [jekkos/opensourcepos#571]
Go to Detailed Reports > Sales > click on date header, table rows will refresh > now click on '+' icon to see details of a sale >  will show wrong sale data.

**Comment by odiea** [comment]
I also see that happening. And Occasionally the modal does not work when trying to update.

**Comment by jekkos** [comment]
I've done a fix for this. Problem is that the details are stored as json array in the page itself. There was no way to reassociate each detail with the correct row number. This is fixed only for sale and receivings reports now.

For the other specific reports I temporarily disabled sorting because they don't use object literals to buildup the table. Therefore it's a bit harder to reassociate details after sort was done.. I might want to look into this later.

**Comment by RamkrishnaMondal** [comment]
After the fix, detailed reports-customers .... showing error, other reports working fine.

**Comment by daN4cat** [comment]
Yes, I get the same.

**Comment by daN4cat** [comment]
Fixed detailed customer error with my commit

**Comment by RamkrishnaMondal** [comment]
Yes, working now.

**Comment by daN4cat** [comment]
What about the original issue, is that now fixed?

**Comment by RamkrishnaMondal** [comment]
Yes, that is also fixed now.

**Comment by daN4cat** [comment]
So we can close?

**Comment by RamkrishnaMondal** [comment]
Yes.

**Comment by odiea** [comment]
After sorting the table the update modal does not work.

**Comment by odiea** [comment]
After sorting the table the update modal does not work.

**Comment by jekkos** [comment]
Should be fixed now in latesst

**Comment by daN4cat** [comment]
The issue related to sorting seems fixed and I verified in this view the removal of a column and then edit and here it seems fine.

However I noticed that there is an unnamed checkbox related to the edit icon:

![image](https://cloud.githubusercontent.com/assets/636048/15421588/17cf0d80-1e6c-11e6-8efc-cb08a7221784.png)

That should be like in the other tables: not visible.

**Comment by jekkos** [comment]
That fix isn't applied to detailed tables yet.. correct indeed.

**Comment by daN4cat** [comment]
Tested and confirm it's fixed.
