### ISSUE TITLE
Sales / Receivings: Hit enter when quantity / price fields are focuesd does not call update

### ISSUE THREAD

**Issue by jekkos** [jekkos/opensourcepos#572]
Hitting enter would normally cause the whole page to be refreshed in earlier versions. This seems to be broken due to changes in the DOM in the latest bstables branch.

**Comment by bkrajendra** [comment]
I needed similar feature, I used following code to resolve this:
```php
echo form_input(array('name'=>'quantity','onChange'=>"document.getElementById('cart_".$line."').submit();", 'class'=>'form-control input-sm', 'value'=>to_quantity_decimals($item['quantity']), 'tabindex'=>$tabindex));
```

I just added onChange attrib for form_input
Use this onchange for other fields in receiving.php and register.php
I hope this is what u r looking for.

**Comment by daN4cat** [comment]
But that change works everytime you change a value, not when you type enter.
People might want to change quantity and discount and then press enter on the last or push update button.

**Comment by jekkos** [comment]
I think change triggers differently depending on the type of control you use it with. Maybe we want the enter key indeed (just like before?)

**Comment by jekkos** [comment]
Should be fixed now in master.

**Comment by daN4cat** [comment]
Tested and confirm it's fixed.
