### ISSUE TITLE
Issue on Excel Export Reports

### ISSUE THREAD

**Issue by pablos1rvent** [jekkos/opensourcepos#573]
![1696439847029db86a36f55fad302f8c](https://cloud.githubusercontent.com/assets/17593856/15387767/09abbf36-1daf-11e6-98fc-c3f15aaebb58.png)
When I press "No" in the excel export and press "Enviar" or "Send" in the reports automatically exports me and don't show me the whole page. 
If I change the new files by the old ones doesn't export clicking yes or no.

Anyone can prove this or is this only for me?

**Comment by daN4cat** [comment]
This is not applicable anymore with bootstrap-tables introduction.
So please be patient that @jekkos merges the code in master and the issue is gone.
