### ISSUE TITLE
Taking update does nothing

### ISSUE THREAD

**Issue by odiea** [jekkos/opensourcepos#575]
This is happening in the new Master. Since my latest pull In takings- update the payment type and it does not change.

**Comment by odiea** [comment]
This appears to be happening to the top row . If I update a lower row it works fine and occasionally then the top row will update after updating a lower row.

**Comment by jekkos** [comment]
Can't reproduce this issue (at least not for the top row). Maybe post screencap showing the problem (like animated gif or so)

**Comment by jekkos** [comment]
@odiea This is probably the last bstables bug. Tried again in chrome and ff and seems to be working fine. Can you reproduce? Otherwise I will close.

**Comment by daN4cat** [comment]
There is still the bulk edit one that blocks everything if you do something on let say 100 rows.

**Comment by odiea** [comment]
The first row is updating properly but the last row does not update. It displays it does but nothing changes.

**Comment by jekkos** [comment]
@daN4cat wasn't there an issue for that? It'll take quite a bit of work to fix that as that refresh routine is quite generic (used in detailed tables, for updating regular rows and bulk update all together).

**Comment by odiea** [comment]
It now appears the Takings update no longer works on any row.

**Comment by jekkos** [comment]
Just did a quick test and works fine here..?

**Comment by jekkos** [comment]
Ok I think I found the issue

**Comment by daN4cat** [comment]
This is fixed. I close.
