### ISSUE TITLE
ospos zip file issues

### ISSUE THREAD

**Issue by odiea** [jekkos/opensourcepos#576]
I am also getting this error when after downloading the master and while extracting it.

![2016-05-19 15_37_16-](https://cloud.githubusercontent.com/assets/10962177/15410571/af5ed62a-1dd7-11e6-8c3e-242da5a047f4.png)

**Comment by jekkos** [comment]
How do you extract this zip exactly? In a new folder every time? The zip itself is generated from github so there shouldn't be any duplicated files in the archive

**Comment by daN4cat** [comment]
indeed, I don't see what we could do about this.

**Comment by odiea** [comment]
I extract it from the site into another new directly. Here are the results from 7zip and Windows. I think if this is happening to new people there might be a trust issue.
![2016-05-20 06_36_59-opensourcepos-master zip](https://cloud.githubusercontent.com/assets/10962177/15427926/9f1d676c-1e55-11e6-9c35-2d06dbaaf53b.png)
![2016-05-20 06_38_35-downloads](https://cloud.githubusercontent.com/assets/10962177/15427932/a5a4cee0-1e55-11e6-9abd-0fe57c950018.png)

**Comment by odiea** [comment]
Could this be the issue.
![2016-05-20 06_45_13-opensourcepos_application_language at master jekkos_opensourcepos](https://cloud.githubusercontent.com/assets/10962177/15428062/7c30ad80-1e56-11e6-9594-a38a977ad994.png)

**Comment by daN4cat** [comment]
I see, it's pt-BR and pt-Br

**Comment by daN4cat** [comment]
And I don't have it in my local repo, so no idea how that went in yesterday as I have just pt-BR....

**Comment by daN4cat** [comment]
The problem is that I don't get in my repo, so I don't know how I can remove pt-Br. The files customers_lang.php are exactly the same

**Comment by daN4cat** [comment]
@jekkos do you get the two subdirs? If yes, can you please remove pt-Br?

**Comment by daN4cat** [comment]
Fixed.

**Comment by odiea** [comment]
Works great now. Thanks @daN4cat . I guess it's the little things that bother me.

**Comment by daN4cat** [comment]
You were correct and apologies for me fretting in closing it. I should have paid more attention.
