### ISSUE TITLE
How to sort items differently in the receipt

### ISSUE THREAD

**Issue by djm777** [jekkos/opensourcepos#577]
Sir, Could you give litt'l bit help how to un-sort items description, default is 1,2,3,4,5,...etc..I want to make ...5,4,3,2,1. So the first input item transaction is on the top. Big thanks
![unsort](https://cloud.githubusercontent.com/assets/19495053/15438472/91cdc1a0-1ef6-11e6-9519-895a7695f986.jpg)

**Comment by hoangtu406** [comment]
I think you should open **receipt.php** in ../application/ view/ sales/receipt.php.
Find line 70 : **foreach(array_reverse($cart, true) as $line=>$item)**
Change it to : **foreach($cart as $line=>$item)**
Hope this will help you.

**Comment by daN4cat** [comment]
If you use invoice you need to apply the same there.

**Comment by djm777** [comment]
@hoangtu406 thanks to you, its worked......
