### ISSUE TITLE
Database / Server optimisation. 

### ISSUE THREAD

**Issue by arionkosturi** [jekkos/opensourcepos#579]
Hi. I've been using ospos for 5 months now. 
Now I'm facing a problem. Database speed. 
In the end of the day, when I view detailed raports of the sales,  it takes 13 second. Its not a problem for daily reports but I cant make monthly or yearly reports. 
Can I do something to optimise MySql or Server Upgrades? 
Thank You.

**Comment by daN4cat** [comment]
Maybe you can explain your setup first.

**Comment by arionkosturi** [comment]
Running OSPOS 2.4,  on a supermicro server,  Intel Core 2 Quad, 4GB DDR3. 
I dont know if I need to add more RAM and a SSD or it should work fine for a 5 month businnes?

**Comment by daN4cat** [comment]
And what about the rest, OS, webserver?

**Comment by odiea** [comment]
If you are running a Linux server you can try these options in this closed issue.
MariaDB #313

**Comment by arionkosturi** [comment]
WAMP on Windows 7 32bit. Is this normal?

**Comment by odiea** [comment]
It is ok for a test machine but for a production machine I would suggest Ubuntu server with my previous suggestion. It's a night and day difference. My better test machine is running Ubuntu Linux 14.04.3.

**Comment by daN4cat** [comment]
I believe you got the answer.

**Comment by pablos1rvent** [comment]
I'm running 1and1 and also the speed is not the best, Is there any way to improve this?
And CodeIgniter can support full AJAX in all of her pages or will be a disaster? :computer: 
@daN4cat

**Comment by jekkos** [comment]
Some mysql tuning might help as well.. Phpmyadmin gives a good overview on the parameters to tune.

Also enable slow queries log to show which queries take too much time + enable apache mod_expiry will give a lot of performance gain

**Comment by jekkos** [comment]
I felt quite some speed difference when using mysql on a machine with 8gigs of ram and tuned settings..

**Comment by daN4cat** [comment]
See #951 for improvements.
