### ISSUE TITLE
printing problem after 10 items sale

### ISSUE THREAD

**Issue by sardinur** [jekkos/opensourcepos#581]
Dear Master Jekkos, I have problem with printing Im using latest version 2.3.4 of ospos and running on xampp 5.6.8 for ubuntu after more than 10 items sale the printing cannot complish the right margin always cropped.. its happened with all the browser (etc: firefox, opera, chrome, safari). Please help.... for my little shop. Bravo. for you
![display cut](https://cloud.githubusercontent.com/assets/19500473/15454205/ebbfd3e0-205b-11e6-8f2a-27d4a560e17e.jpg)

**Comment by sardinur** [comment]
safari browser not included. lol

**Comment by odiea** [comment]
You might consider upgrading to 3.0.0 and resetting your printers under config/receipt. I also have had better luck using firefox with the jsprint addon.

**Comment by sardinur** [comment]
is that long way to go? How is it? (@odiea)

**Comment by odiea** [comment]
I do believe that 2.3.4 is no longer supported. The new version 3.0.0 is the current. I would suggest a fresh install on a test computer to see if that helps your printing problem. If you have adjusted the print settings in all of your browsers and you are still getting this issue then I would suggest the newest so the main programmers can work on a current issue not an old issue.

**Comment by sardinur** [comment]
I Try to download ospos 3.0.0 but only ver 2.4 I got.. could you give the link for download ver: 3.0.0 ? Big Thanks Bro..

**Comment by odiea** [comment]
https://github.com/jekkos/opensourcepos. Click on the clone or download button.

**Comment by pablos1rvent** [comment]
I think maybe your separation with your Total and Jumlah is too much, is that the issue?

**Comment by sardinur** [comment]
@pablos1rvent: and "OSpos Master" could you guys help? How to solve this problem, coz I've beentrying to install the latest ospos (ver.3.0.0) but not running smoothly, thanks before....

**Comment by sardinur** [comment]
Ok. Welldone. Bravo......
