### ISSUE TITLE
Error generating translation files

### ISSUE THREAD

**Issue by arteiro** [jekkos/opensourcepos#582]
generating bootstrap_tables_lang.csv... generating common_lang.csv... generating config_lang.csv...
Notice: Undefined offset: 3 in C:\www\opensourcepos-pt-BR\index.php on line 58

Notice: Undefined offset: 4 in C:\www\opensourcepos-pt-BR\index.php on line 58

Notice: Undefined offset: 5 in C:\www\opensourcepos-pt-BR\index.php on line 58

Notice: Undefined offset: 6 in C:\www\opensourcepos-pt-BR\index.php on line 58

Notice: Undefined offset: 7 in C:\www\opensourcepos-pt-BR\index.php on line 58

Notice: Undefined offset: 8 in C:\www\opensourcepos-pt-BR\index.php on line 58

Notice: Undefined offset: 9 in C:\www\opensourcepos-pt-BR\index.php on line 58

Notice: Undefined offset: 10 in C:\www\opensourcepos-pt-BR\index.php on line 58

Notice: Undefined offset: 11 in C:\www\opensourcepos-pt-BR\index.php on line 58

Notice: Undefined offset: 12 in C:\www\opensourcepos-pt-BR\index.php on line 58

Notice: Undefined offset: 13 in C:\www\opensourcepos-pt-BR\index.php on line 58

Notice: Undefined offset: 13 in C:\www\opensourcepos-pt-BR\index.php on line 58
generating customers_lang.csv... generating datepicker_lang.csv... generating employees_lang.csv... generating error_lang.csv... generating giftcards_lang.csv... generating items_lang.csv... generating item_kits_lang.csv... generating login_lang.csv... generating messages_lang.csv... generating module_lang.csv... generating receivings_lang.csv... generating reports_lang.csv... generating sales_lang.csv... generating suppliers_lang.csv...

**Comment by daN4cat** [comment]
something is wrong with the .csv files, open them with excel and save again if they all look fine.

**Comment by jekkos** [comment]
Notice: Undefined offset: 13 in C:\www\opensourcepos-pt-BR\index.php on line 58

Don't know if 'index.php' is supposed to be there

**Comment by arteiro** [comment]
I created a folder and rename the file to index.php generate_languages.php for easy access. then when I want new file generation only access the folder and not have to type the file name. But in the beginning everything was ok, and now appears this NOTICE? although generate the files normally. If it is not a problem, disregard the question presented. Thank you
