### ISSUE TITLE
Look up is too slow in V 3

### ISSUE THREAD

**Issue by aelhofy** [jekkos/opensourcepos#583]
hello 

when entering item number, supplier name or customer name the lookup is too slow

OSPOS V3
Windows 
Nginx 1.9.10
PHP Version 5.5.31

**Comment by daN4cat** [comment]
You may want to read #579

**Comment by aelhofy** [comment]
You are right, just shifted to small Ubuntu vm with 1 GB ram and there is a huge difference, it works at light speed :)

**Comment by daN4cat** [comment]
See #951 for improvements.
