### ISSUE TITLE
Arabic Files

### ISSUE THREAD

**Issue by aelhofy** [jekkos/opensourcepos#584]
Hello

I made an Arabic language files  for ver 2.4 and V 3.0, how I can share with you?

**Comment by daN4cat** [comment]
Yes, as long as you translated the latest .csv files from the dir translations.

**Comment by daN4cat** [comment]
We just merge 3.0 no older.

**Comment by aelhofy** [comment]
sorry, I translated the files directly, is there a way to use it?

**Comment by daN4cat** [comment]
You need to copy and past your translations in those files adding a new column for your language on each file.

**Comment by aelhofy** [comment]
Hello
the provided csv files is not supporting utf-8, when open in MS-Excel and write arabic text then close and re-open it appears like ?????

**Comment by daN4cat** [comment]
There are Chinese translation in them, so it's an issue with the way you open and edit them.

**Comment by daN4cat** [comment]
@aelhofy any update?

**Comment by aelhofy** [comment]
I added the Arabic translation in the csv files attached 
[translations.zip](https://github.com/jekkos/opensourcepos/files/375907/translations.zip)
