### ISSUE TITLE
A PHP Error was encountered

### ISSUE THREAD

**Issue by MBISEES** [jekkos/opensourcepos#585]
I am using OSPOS V3.
when completing SALE  i face this error
when complete sale it give an error message  below
"Fatal error: Class 'emberlabs\Barcode\Code128' not found in /home/u-......../public_html/application/libraries/Barcode_lib.php on line 79"
then the illustration of an issue is:

A PHP Error was encountered

Severity: Error

Message: Class 'emberlabs\Barcode\Code128' not found

Filename: libraries/Barcode_lib.php

Line Number: 79

Backtrace:
.......................................................................................................................
please assist me

**Comment by daN4cat** [comment]
Can you please check if you have dir and code in application/views/barcodes?

**Comment by MBISEES** [comment]
yes i have checked.please check the attachement of snapshot of the directory
![barco](https://cloud.githubusercontent.com/assets/9624306/15468019/653659b8-20ea-11e6-8e41-5132618885ff.JPG)

**Comment by odiea** [comment]
It appears the code 128 file is empty. Please check the zip file and extract it again.

**Comment by MBISEES** [comment]
Which dir is contained code 128 file? Please help me to locate

**Comment by MBISEES** [comment]
Okay  it seems that code 128 contained 0kb. Maybe it is empty. I will check it and upload it again

**Comment by MBISEES** [comment]
thanks for the help am looking for a cup of coffee to support this useful project

**Comment by jekkos** [comment]
There's a donate button on the front page's readme if you want to contribute with a donation feel free. Thanks!
