### ISSUE TITLE
Show Item kits name in receipts instead of items

### ISSUE THREAD

**Issue by morgansson** [jekkos/opensourcepos#586]
Is there a possibility of showing the item kits names in the Sales Register and Receipt instead of the detailed items name?

I think this is an issue because, lets say I'm selling drinks (IE: Gin Tonic, which use 0.133 of a Gin bottle, and 0.051 of a tonic water bottle), thats perfectly fine. 

The thing is, I don't want those numbers to show up neither on the sales register, nor the receipt I give to people.

Is there any possibility of implementing this?

I've seen this functionality on a VERY SIMILAR php software.

**Comment by daN4cat** [comment]
Sure it's possible to implement it.

**Comment by morgansson** [comment]
Excellent!

**Comment by daN4cat** [comment]
Just to be clear I didn't mean I'll do, you asked if it's possible and I said yes it's possible.

**Comment by morgansson** [comment]
Yes I fully understood that :)

I will try to get it working from my side.

Although if you have any recommendation to do so, it will be very appreciated.

Thank you!

**Comment by daN4cat** [comment]
I would need to check the code to tell you how. One of the next days.

**Comment by sonnysk76** [comment]
Hello, Me again.
What I have now is disabled the print and screen information for items that are components and not products as it.
For the receipt print 
opensourcepos/application/views/sales/receipt.php
Row 71
Add an if.
if ($item['price']>0) {
Row 93
}

This way it only print the items that have sale price.

To do this on the sales screen, modify this file the same way adding the if ($item['price']>0) {
application/views/sales/register.php
Row 123

It may can give you a hint to get what you need.

**Comment by odiea** [comment]
So the idea here is to enter the Item kit with the full cost Item then enter other cost items so they can be removed from Inventory. Works well. I hope this does help others.

**Comment by jekkos** [comment]
also see #200 and wiki page on item kits
