### ISSUE TITLE
Current master graphical reports issues

### ISSUE THREAD

**Issue by odiea** [jekkos/opensourcepos#587]
Sales Summary shows nothing but the totals. Supplier and Taxes show the following issue.Employees Summary Report also has issues.
![2016-05-23 13_34_57-ugly sweater store -- powered by os point of sale](https://cloud.githubusercontent.com/assets/10962177/15482268/f371c1e4-20eb-11e6-9a7d-d98a3f8ac3ce.png)

**Comment by jekkos** [comment]
- [x] Fix suppliers report
- [x] Fix employees report
- [x] Fix suppliers report
- [ ] Center charts properly and apply 80% scaling
 * [ ] pie chart
 * [ ] bar chart
 * [ ] hbart chart
 * [ ] line chart
- [ ] Fix hover tooltips in pie chart

**Comment by daN4cat** [comment]
I fixed lines too. There is already #342 for this feature I would close this because was a bug.
