### ISSUE TITLE
Variable pricing for one item?

### ISSUE THREAD

**Issue by colinmcparland** [jekkos/opensourcepos#588]
Hi there, I was wondering if it is possible to add multiple instances of one item to a sale and price them all individually?  Currently, having multiple instances of one item 'stacks' them all into one item and assigns a group price.  Thanks for your help!

**Comment by daN4cat** [comment]
What would be the use case to do differently?

**Comment by jekkos** [comment]
You can use serialized items in that case. Each item 'instance' will add to the register and can have it's own price
