### ISSUE TITLE
Adding new item in V3

### ISSUE THREAD

**Issue by aelhofy** [jekkos/opensourcepos#589]
While using Google Chrome to add an item the dialog is not closed upon clicking submit despite that the item has been added also if submit is clicked many times then an item it added per each click, all added items have the same name and details,  item name shall be unique, isn't it?

this problem does not exist when using Firefox.

OS: Ubuntu 16.04
Web Server: Nginx 1.10
Php: PHP 7
Browser: Chrome & Firefox on windows 10

**Comment by daN4cat** [comment]
We don't support PHP 7 yet
