### ISSUE TITLE
Quantity stock zero on edit item

### ISSUE THREAD

**Issue by M-Shahbaz** [jekkos/opensourcepos#59]
Quantity stock show zero on edit an item even quantity is greater than zero.

No. of Quantity is not picking up in the edit item form.

**Comment by jekkos** [comment]
Yes indeed, a ternary condition was wrong for the quantity field. I inverted it in 49e4567. Can you check if this works?

**Comment by M-Shahbaz** [comment]
Fixed, 

Thanks
