### ISSUE TITLE
Support PHP7

### ISSUE THREAD

**Issue by daN4cat** [jekkos/opensourcepos#591]

**Comment by odiea** [comment]
The latest xampp server comes with php 7 and Mariadb. I have had no issues with this.
On Ubuntu server I had to use the following version of php7 to get it to work. I believe the only issue I have had so far is with the current version of mysql and not Php7. Even 2.3.4 works great on Php7.
http://tecadmin.net/install-php-7-on-ubuntu/

**Comment by daN4cat** [comment]
Thanks @odiea, once 3.0.0 is out we should upgrade to PHP 7.0 and run some thorough testing with the help of the community here.
It's already good news you didn't spot issues but I remember we had some problem in a model with MySQL queries.

**Comment by onyema3** [comment]
I can also confirm that  OSPOS 3.0.0 is working fine with PHP 7.0.10
So far no issues with mine.

**Comment by daN4cat** [comment]
We should checked everything, receipts, invoices, sending emails, all the reports, item_kits, giftcard, all the forms (e.g. check inventory in Items, adding a new GiftCard), searching, adding, deleting.
Many cases and we will find a broken one for sure.

**Comment by jekkos** [comment]
We could deploy a public instance and then call for testing to report remaining problems?

**Comment by jekkos** [comment]
Anybody using PHP7 without issues yet?

**Comment by odiea** [comment]
Yes I have had issues since the the update for tables in reports.

**Comment by SteveIreland** [comment]
I've been testing with PHP 7 and had an issue with reports that I thought was odd ... the summary data for detail reports wouldn't display properly.  But it might not necessarily be related to PHP 7 because here were some recent changes to the table_helper program that might have introduced the issue.

The resolution was to reset the array as shown below in the `transform_headers()` function. 

```php
foreach($array as $element)
	{
                reset($element);
		$result[] = array('field' => key($element),
			'title' => current($element),
```

**Comment by odiea** [comment]
This only appeared while I was using php7. Your fix worked great.
Before
![2017-01-08 04_19_31-wedidit _ powered by ospos 3 0 1](https://cloud.githubusercontent.com/assets/10962177/21749351/6572d990-d55a-11e6-9580-a7b4c2ddb7df.png)
After
![2017-01-08 04_19_55-wedidit _ powered by ospos 3 0 1](https://cloud.githubusercontent.com/assets/10962177/21749354/73003724-d55a-11e6-9998-774de0695ebe.png)

**Comment by daN4cat** [comment]
I'll try to incorporate this later as confirmed it's valid.

**Comment by odiea** [comment]
Other than the tables issues I have had no problem with php7. This now lets the tables show properly. Steve had issues with his branch so I think he deleted it and will resubmit it at a later date.

**Comment by SteveIreland** [comment]
I submitted a new pull request (after rebuilding everything from scratch).  I did a quick run through and it's significantly more functional than my earlier version, but will continue to test and debug and will respond to any suggestions.  Thanks to all for your patience.

**Comment by daN4cat** [comment]
How do we plan to validate PHP7?
It looks like we need to have @SteveIreland to release his latest changes, merge to master and then do a full testing.
Hopefully we get people to help here because I don't have that much time to work on a proper setup to PHP7 and MySQL5.7.

**Comment by odiea** [comment]
After @SteveIreland  update for php 7 in the Reports tables I again am having no issues with it.

**Comment by daN4cat** [comment]
Good, so let's wait for @SteveIreland to complete the last changes as per my review and then marge to master.

**Comment by odiea** [comment]
https://en.oxforddictionaries.com/definition/marge

**Comment by daN4cat** [comment]
Somehow I intended to be a smooth process, so marge would have helped...

**Comment by daN4cat** [comment]
@onyema3 up for some testing of the latest master including support for MySQL5.7 and PHP7? Help is needed....

**Comment by daN4cat** [comment]
It seems to be fine according to the various feedback I read so we can declare that OSPOS works with PHP7 now and close this issue.
