### ISSUE TITLE
List of Customers - Display Company

### ISSUE THREAD

**Issue by nicksti** [jekkos/opensourcepos#594]
The List of Customers does not allow us to see the company a customer is associated with and the search box does not search by company.

**Comment by jekkos** [comment]
This is an open source project and simple things like that can be easily modified. Please take a bit of time to figure out how it works and try to find a solution yourself. Code doesn't come falling out of the sky.

**Comment by daN4cat** [comment]
Please contribute back if you implement the feature, in this way we can make it better.
