### ISSUE TITLE
Unique Serial Numbers

### ISSUE THREAD

**Issue by blhf** [jekkos/opensourcepos#595]
How can I make the serial numbers unique for each item sold? for example if Equipment A Serial # is 0000001 when you input Equipment B with the same serial as Equipment there should be a prompt msg that the serial is already used before or you input it twice in the same document. this is very helpful since mostly the setup of serial number is unique.

**Comment by blhf** [comment]
hi @daN4cat  wondering if editing the code would be hard to got this kind of functionality.

**Comment by daN4cat** [comment]
There is a similar functionality for invoices, the numbering is unique so you can see how is done and take inspiration from that.

**Comment by blhf** [comment]
I'm still studying php though. hope we can find someone whos gonna take charge with this issue. 
Thanks.

**Comment by daN4cat** [comment]
@blhf if you don't insert any serial number your numbering is unique anyway.

You can then go to Store Config and Barcode tab, select the option generate if empty and then go back to Items view. Do multiple selection and click generate barcodes. Now you get unique numbers with codes in the fields updated.

**Comment by blhf** [comment]
@daN4cat Hi thanks for your reply. :+1:  actually we cannot use that function because there is an assigned serial number for the items, like cellphone that have a unique IMEI.

**Comment by daN4cat** [comment]
If serial numbers are already assigned to your items, by definition they are unique and you should not have a risk of conflict. So not sure why you need this in the end.

**Comment by blhf** [comment]
Got your point though. But with the help of your system we can track to where the item with serial number was sold or if it was returned.  E.G Samsung S7 with IMEI: 172938172983 can be bought but later on need to be replaced because of some issue but still under warranty. Serial number is assigned on the box that is where we are gonna barcode it when we sold it.

**Comment by daN4cat** [comment]
But consumer electronics product boxes have their own barcode.
I close this because I don't think there is anything to add.
Tracking of items can be done checking the inventory history.

**Comment by blhf** [comment]
ok thanks anyway.
