### ISSUE TITLE
bstables: hovering over an item avatar picture doesn't pop up the zoomed image anymore

### ISSUE THREAD

**Issue by daN4cat** [jekkos/opensourcepos#596]
With the old tables in Items the feature used to work, hovering over the avatar picture you could see the zoomed in version of the picture in a pop window.

**Comment by jekkos** [comment]
Should be fixed now.

**Comment by daN4cat** [comment]
Now works, but is there anyway to show the image on the left side of the mouse and not right?
Not sure it's my case but when I hover the picture the magnified one open on the right and therefore goes half out of screen.

**Comment by daN4cat** [comment]
OK, I fixed the image width and placement. It's now on the left of the mouse and 200px max.

I close.
