### ISSUE TITLE
Secure OSPOS against XSS, CSFR and SQL injection

### ISSUE THREAD

**Issue by daN4cat** [jekkos/opensourcepos#597]
Currently OSPOS is partially secured against different types of attack.

The code should be reviewed and secured against:

- XSS (Cross Site Scripting) using xss_clean() on input and output (to view) data
- CSFR (Cross Site Forgery) enabling csfr_protection but reviewing and updating Ajax parts
- SQL injection using $this->db->escape() on database input

**Comment by daN4cat** [comment]
It's worth noting that `$config['base_url'] = '';` in config should always be set in production servers to prevent attacks, see: https://github.com/bcit-ci/CodeIgniter/issues/3292

**Comment by jekkos** [comment]
Okay will verify and test the first XSS fixes later this week. Personally I think it would be good to try and define a consistent way to handle this issue in ospos. Would be nice if we could just escape the data array before passing it to the view. Think we'll have to go through each view one by one.

* Is data in the default $data array escpaed properly? And what about arrays? 
* Always need to escape other function output (direct call to functions that read from db)
* Try to define a clear coding pattern across the views to handle XSS properly

**Comment by daN4cat** [comment]
The idea is to escape data going to views from controllers. I'm going one by one. If you check what I have done in Config and Giftcard I checked views and fixed Controllers and in case of config I sanitised the configuration loading too.

**Comment by daN4cat** [comment]
I checked not only load of view but also json encoding too.

**Comment by jekkos** [comment]
OK thanks. For config we might eg add our own custom escape function, something like

`$this->config->escaped_config('item')`

**Comment by daN4cat** [comment]
Not sure I get. Is the concern that the config is not reloaded by the same function when changed? For sure I need to check that. Or do we have concerns that an out of memory could corrupt config memory and go out of boundary?
BTW this discussion should be move to #39.

**Comment by jekkos** [comment]
OK csrf is done now.. We should try to stick to form_open() in CI as it wil automatically append the csrf token to a request. I have also proxied the standard jquery post in our application to read the token and send it along with every request.

Idea is that this token lives in the sandbox defined by ospos' domain and thus can't be grabbed by javascript running in another tab or domain. We need the token to let the server verify that the request is coming from the proper sandbox, in this case ospos itself. 

I did some basic testing and all seems fine, however some extra testing effort on this one is always welcome.

**Comment by daN4cat** [comment]
Thanks for this, I will test.

**Comment by daN4cat** [comment]
If no issues I would close this set of security improvements.
I know we should test, but unless somebody find the time to help us we need to rely on the manual tests and code reviews done so far.

**Comment by daN4cat** [comment]
@likozhang since you are good at doing some thorough testing, would you like to look into this and help?

**Comment by jekkos** [comment]
Yes I planned to do some testing here but currently on holidays in France... so I won't have too much time this week

**Comment by daN4cat** [comment]
Enjoy your holidays, don't worry about this until your return.

**Comment by daN4cat** [comment]
All children items are close, therefore I close this one too.
