### ISSUE TITLE
Prevent SQL injection attacks

### ISSUE THREAD

**Issue by daN4cat** [jekkos/opensourcepos#598]
Sanity check variables used in any SQL query to protect OSPOS from SQL injection attacks with $this->db->escape().

See http://stackoverflow.com/questions/1615792/does-codeigniter-automatically-prevent-sql-injection

More: http://www.roytuts.com/prevent-sql-injection-in-codeigniter/ or https://arjunphp.com/prevent-sql-injection-codeigniter/

**Comment by daN4cat** [comment]
I believe this is done.

I checked all the models and changed the code to make sure it's escaped.
I also took the opportunity to refactor some of the model code and use more CI Query Builder functions.
Added some comments, made code consistent and reduce the unnecessary redundancies.

**Comment by jekkos** [comment]
OK indeed, I double checked CI docs and it states that one should try to use as active record as much as possible becuase it handles the escaping by default (using prepared statements). When doing concatenation we probably need to use the db->escape manually.

I might want to do a pentest using sqlmap on ospos once we think we have finished fixing these bugs to see if there's something left.

**Comment by daN4cat** [comment]
I finished. We should run a test if you have something setup for that.

**Comment by daN4cat** [comment]
Just done few further adjustments.

**Comment by jekkos** [comment]
I'll try to do the test with a tool for this coming days

**Comment by daN4cat** [comment]
Sounds good. Maybe you can explain me what kind of tools are required to perform those tests, I didn't have the time to investigate that topic.

**Comment by jekkos** [comment]
Last week I attended a classroom on 'ethical hacking'. .think it's time to put this new acquired knowledge into practice

**Comment by daN4cat** [comment]
good, so have fun now :-P

**Comment by jekkos** [comment]
Following command can be used to test for injection problems and will crawl ospos urls to try and fuzz form data

`sqlmap --crawl 3 -u http://localhost/index.php/home --forms --batch --cookie ospos_session=0286181a77784771a10f7fdf790825abf0e0a7e8 --crawl-exclude logout`

**Comment by jekkos** [comment]
sqlmap can't find any vulnerabilitties using this way of crawling. However I think that it did not correctly identifiy all forms and their possible values in the application (as some are builtup dynamically). I might want to continue the test a bit and try to enumerate all possible POST urls using burpsuite first, then feed this list into sqlmap for analysis.

**Comment by daN4cat** [comment]
I would close this one as some test is done and we can always find better ways to test or other people to help with this.
