### ISSUE TITLE
Prevent CSFR attacks

### ISSUE THREAD

**Issue by daN4cat** [jekkos/opensourcepos#599]
Enable CSFR protection from CI and update Ajax to use CSFR protection.

See http://www.codeigniter.com/user_guide/libraries/security.html#cross-site-request-forgery-csrf

AJAX + CSRF protection in CI https://arjunphp.com/ajax-csrf-protection-in-codeigniter/

**Comment by jekkos** [comment]
I haven't really investigated what this csrf protection actually does. As you noticed in the xss issue the CI protection isn't really worth a lot so not sure how they propose to handle these kind of issues.

**Comment by daN4cat** [comment]
XSS got improved in CI and according to the blog CSRF should work. But it's work checking CI issues to see if everything is fine indeed.

**Comment by daN4cat** [comment]
@jekkos I assign this to you because CSFR support is in CI3 (read the ljnks from my first post), starting from config.php, but it requires changes in the js / ajax side to use the secure token in the transactions.
You are more familiar than me with that kind of stuff.

**Comment by jekkos** [comment]
Ok I'll look into it the coming days

**Comment by daN4cat** [comment]
In Ajax calls the token is valid only once, so it needs to be fetched everytime we need to make an ajax call (e.g. search autocompletion).

See a comment here: http://stackoverflow.com/a/37757857/6176637

**Comment by daN4cat** [comment]
Worth evaluating this option too: https://ericlbarnes.com/2011/03/17/codeigniter-csrf-protection-with-ajax/

**Comment by jekkos** [comment]
Ok thanks for pointing that out. I won't have a lot of time this week as I'm on a training .. and have some holidays planned the two weeks after, but I'll see where I can find some time.

**Comment by jekkos** [comment]
Think some kind of aspect or proxy around the standard jquery ajax calls could give an easy solution here

**Comment by jekkos** [comment]
Ok see explanation in epic #597

**Comment by jekkos** [comment]
Ok I oversaw some issues with async dialog validation, will try to fix this now

**Comment by daN4cat** [comment]
Yes, Items edit form doesn't work. You cannot submit.

**Comment by jekkos** [comment]
OK did the necessary fixes to make jquery validation callbacks work.. problem is that for ajax callbacks that call submit on their own, there is no general easy way to update the token (beside overriding each success response call)

currently the update is done in the complete() callback which fires after the success..

**Comment by jekkos** [comment]
Ok I've simplified the approach a bit more

**sending tokens**
* for $.post (without form) a proxied version adds the token field from the cookie to the request
* for form_open() the token is added automatically by CI
* for jquery validation the tokens is added through inheritance of the data field

**receiving (and updating) tokens**
* for all ajax calls there's now one catch all, which is the jQuery dataFilter callback. Didn't know this one existed but it comes in nicely here

the whole setup just comes down to fetching the token after each type of request and reinjecting it in the next POST to the server. Once one token is outofdate then request will be answered with status 403.

**Comment by daN4cat** [comment]
So far it seems to be working fine, even checked excel import.

A little bit more testing it's needed though.

**Comment by daN4cat** [comment]
I believe we can close this one.

Support is added and it's what comes with CI, so far everything seems to be working fine.
