### ISSUE TITLE
How to sort to the last POS of the database

### ISSUE THREAD

**Issue by pablos1rvent** [jekkos/opensourcepos#600]
Hello guys, well, I can't explain very well in English but, I'm editing the sales manager and I need to sort that when I press to the button "Sales" 
![2991f3de176e511c6f3fbfe3093a6014](https://cloud.githubusercontent.com/assets/17593856/15612603/cc6504c0-242f-11e6-85b8-482927f7b14b.png)
Convert this:
![e4d687154b10e9ed6e40339a29ec6214](https://cloud.githubusercontent.com/assets/17593856/15612668/0651aeb8-2430-11e6-9f38-c7ffced82396.png)

To this by default pressing Sales button

![c6e0f3e2f562e10875b23d750748618a](https://cloud.githubusercontent.com/assets/17593856/15612626/e361bc40-242f-11e6-9812-6ca66feeca28.png)

I edit this:

0 to 1 (Desc to Asc)
![b4c120bfe0dfe4cab3b59b71d21a817a](https://cloud.githubusercontent.com/assets/17593856/15612833/a62ce6a0-2430-11e6-8347-b86e0cbd056f.png)

Now, the results are like this:
![6f954aa4571f80a8adc189727bd51464](https://cloud.githubusercontent.com/assets/17593856/15612854/bd725192-2430-11e6-944e-43aeffb58db9.png)

How can I go to the 2nd page without pressing it?

Thanks!

**Comment by daN4cat** [comment]
It looks like you are using an old 3.0 version. Tables changed completely, so please upgrade to that otherwise you spend time on something that is gone already.

**Comment by pablos1rvent** [comment]
@daN4cat Yeah, I download this maybe 20 days ago, the thing is that I updated a lot of things, I'm gonna try

**Comment by pablos1rvent** [comment]
OH sh*t the new update is AWESOME, we have an old version but we update a lot D:

**Comment by daN4cat** [comment]
Well, the cost of doing custom changes is that you need to be prepared to keep up with changes and merge them otherwise you risk to be left behind.
So merge often to reduce the risk. 20 days is a lot considering what was introduced in the last month.

**Comment by pablos1rvent** [comment]
Yup, 20 days is a lot of time. Well the new tables are awesome but I think in the next POS that I edit to other company here will have the new updates ^^
