### ISSUE TITLE
Categories Summary Report : Not showing properly 

### ISSUE THREAD

**Issue by RamkrishnaMondal** [jekkos/opensourcepos#603]
Most of the parts are black and the size of the chart is too big.

![screenshot from 2016-05-28 21 48 45](https://cloud.githubusercontent.com/assets/14151032/15628473/efe42df4-251f-11e6-8ec5-e255b49abb1c.png)

**Comment by RamkrishnaMondal** [comment]
This is with old version of ospos-3 with same db.

![screenshot from 2016-05-28 22 19 42](https://cloud.githubusercontent.com/assets/14151032/15628597/75305936-2522-11e6-8f4a-1673dce7303c.png)

**Comment by daN4cat** [comment]
How many categories do you have?

**Comment by RamkrishnaMondal** [comment]
Lots of categories  for computer hardware and repair shop.

**Comment by daN4cat** [comment]
I need a number to test the issue.

**Comment by RamkrishnaMondal** [comment]
Do you mean the version number ? If yes, it is latest master, just downloaded yesterday.

**Comment by daN4cat** [comment]
I meant the number of categories you have because I need to test your issue. I have 10 and I don't see the problem.

**Comment by daN4cat** [comment]
OK, it's an open issue with Chartist when there are > 15 values in the pie chart: https://github.com/gionkunz/chartist-js/issues/451

I'll see if there is a solution in any of the comments.

**Comment by daN4cat** [comment]
Colours issue fixed, it's now random and not capped to 15 colours.

Size of the chart is 80% the same as for the others.

**Comment by RamkrishnaMondal** [comment]
Thanks for fixing the colours issue  but 'category names' are still overlapping, this was not happening when we were using flash...i think, need some more fixation to make it perfect.

**Comment by daN4cat** [comment]
Hover with the mouse over the slices and you get a pop up with a description.

**Comment by daN4cat** [comment]
With regards to the arrows, that issue is open in Chartist: https://github.com/gionkunz/chartist-js/issues/224

If you have something in mind about to solve it I'm happy to implement. I'm not a strong UI side developer, I tend to deal more with middleware and overall system architecture.
So I need some creating help from somebody to explain me a algorithmic way to add those lines.

**Comment by RamkrishnaMondal** [comment]
Ok, i'll try if i can do something and let you know if i get some workaround. .

**Comment by daN4cat** [comment]
Another option would be to increase the distance between slice and label: http://jsbin.com/hofimu/1/edit?js,output but then we would need to add a legend otherwise it's not easy to read.

**Comment by RamkrishnaMondal** [comment]
Best solution would be adding arrows...specially in case of categories with small percentages.

**Comment by RamkrishnaMondal** [comment]
Or we can use 'Bar Chart' instead of 'Pie Chart'

https://jsfiddle.net/api/post/library/pure/

**Comment by nestorochoa** [comment]
So no arrows in chartist?

**Comment by daN4cat** [comment]
The issue is still open in chartist. If you have time to come up with a solution that would be great.
