### ISSUE TITLE
bstables: edit entry changing some field, submit and the row is not updated

### ISSUE THREAD

**Issue by daN4cat** [jekkos/opensourcepos#604]
It seems that we had a regression with regards to this feature.

The data is updated in the database but the table row doesn't refresh.

Visible in Employees, Customers, Suppliers, Giftcard, Items Kit

**Comment by jekkos** [comment]
Have updated this code once more and seems well on my local machine.

**Comment by daN4cat** [comment]
I'll test this next days.

**Comment by jekkos** [comment]
Ok this bug was still there. Also see #575. Should be fixed now.

**Comment by daN4cat** [comment]
This is fixed. I close.
