### ISSUE TITLE
How to add distributor ?

### ISSUE THREAD

**Issue by imranwe** [jekkos/opensourcepos#608]
how to add a distributor person on sale invoice and in report filter with distributor

**Comment by daN4cat** [comment]
With distributor I guess you mean supplier, or you mean that you are a distributor?

**Comment by imranwe** [comment]
i am distributor and i have many supplier and  i need to check the stock given to the supplier

**Comment by daN4cat** [comment]
This is a point of sale software, mainly for shops so not sure this fits your needs.

**Comment by imranwe** [comment]
ok thanks........
