### ISSUE TITLE
Database import 2.3.1_to_2.3.2.sql

### ISSUE THREAD

**Issue by mickday** [jekkos/opensourcepos#61]
last two import statements are incorrect, should be:

ALTER TABLE `ospos_customers`
    ADD COLUMN `company_name` varchar(255) DEFAULT NULL;

ALTER TABLE `ospos_giftcards`
    MODIFY `person_id` int(10) DEFAULT NULL;

**Comment by jekkos** [comment]
Indeed I haven't tested the upgrade but should do so any time soon. Have corrected this in the script now (check ffc42b7)
