### ISSUE TITLE
Custom Controller

### ISSUE THREAD

**Issue by waynebr76** [jekkos/opensourcepos#610]
I originally posted this on source forge but was advised to post it here. if anyone can help thanks

Hi I have a custom controller that I used in earlier versions of OSPOS. I have now upgraded to version 2.4 and when I try to access the controller I get a page not found (404) error. How do I enable this controller in the latest version? the script in the controller synchronises my stock with my website.

**Comment by daN4cat** [comment]
Which version are you upgrading from?

**Comment by waynebr76** [comment]
Hi I am upgrading from versionow 2.3.2

**Comment by daN4cat** [comment]
Maybe the issue with accessing your controller is due to the fact that controller names changed to be with capital letters and base class is different. Check one old and one new of any other controller and spot the difference.

**Comment by daN4cat** [comment]
We upgraded to Code Igniter 3.0 starting with 2.4.

**Comment by waynebr76** [comment]
Hi thanks for the response, my fie wouldn't hve changed, does code igniter 3 reject it if it is not a capital letter?

**Comment by daN4cat** [comment]
Code Igniter, Upgrading from 2.2.x to 3.0.x https://www.codeigniter.com/userguide3/installation/upgrade_300.html

**Comment by daN4cat** [comment]
That's what I followed when I upgraded 2.4 (and 3.0) to use CI3.

**Comment by waynebr76** [comment]
Thanks I'm still getting an error but it looks like it is opening the page so it must be the code in my script

**Comment by odiea** [comment]
Closing this due to it's age.
