### ISSUE TITLE
Remaining value is wrong when giftcard payment is entered twice

### ISSUE THREAD

**Issue by jekkos** [jekkos/opensourcepos#611]
Did a quick test on 2.4 and suppose it's still present in 3.0. When using giftcards twice the amount due isn't correctly calculated.

**Comment by odiea** [comment]
Are you using the same gift card twice on the same sale or how are you doing this?

**Comment by jekkos** [comment]
Yes my parents juist showed me this bug. Problem is rather that payment field is not disappearing which makes a user think he needs to add one more after which remaining is miscalculated

**Comment by odiea** [comment]
I can't replicate this issue. if I enter a gift card with enough funds it goes to the finish sale. If I enter a gift card with not enough funds and then add another card iw works properly too. Version 3

**Comment by odiea** [comment]
This is what I get if I enter a low value giftcard twice on the same sale. The first amount shows 0 balance.  Negative values have always shown funny. Sometimes it would even show a % sign.
![2016-05-31 17_50_41-microsoft edge](https://cloud.githubusercontent.com/assets/10962177/15694177/aa02c72e-2758-11e6-985c-e6e376f92508.png)

**Comment by jekkos** [comment]
Think this issue is fixed in 3.0 as the giftcard value field is disabled now once the amount is paid.

**Comment by jekkos** [comment]
Was fixed in 69c1af5
