### ISSUE TITLE
How to make "Cash" as default value in Sales and receiving

### ISSUE THREAD

**Issue by Ibnumarjan** [jekkos/opensourcepos#612]
I would like to know how can I make "Cash" instead of "Debit Card" as default value? since we mostly deal with Cash sales. 

Also, Let me know how can I make the print of a sales directly after printer button clicked, without going to print preview screen or print dialog.

Please guide me. Thanks

**Comment by odiea** [comment]
Go to application/models/sales and change the order of the following then save. For the print issue you can use Firefox with the JSPrint addon.

public function get_payment_options($giftcard = TRUE)
	{
		$payments = array(
			$this->lang->line('sales_debit') => $this->lang->line('sales_debit'),
			$this->lang->line('sales_credit') => $this->lang->line('sales_credit'),
			$this->lang->line('sales_cash') => $this->lang->line('sales_cash'),
			$this->lang->line('sales_check') => $this->lang->line('sales_check')
		);
				if($giftcard)
		{
			$payments[$this->lang->line('sales_giftcard')] = $this->lang->line('sales_giftcard');
		}
		return $payments;
	}

**Comment by Ibnumarjan** [comment]
Thanks odiea, first part works......great.... (default payment type: cash)

in reference to firefox, can i make this as app in firefox, which i do in chrome.not going to browser bar. if so i can switch to firefox with the above your idea. please!!!!!!!!!!!!

**Comment by daN4cat** [comment]
Use Firefox with jsprint and that will solve your problem.
You need to configure jsprint from Store Config once installed in Firefox.

**Comment by Ibnumarjan** [comment]
I installed jsprint and now when print from the sales receipt (clicking print button) nothing happen. I mean,nothing print also not showing print dialog (which i would like ...)

**Comment by odiea** [comment]
In your first post you said you did not want the print dialog to show. You can remove or disable the jsprint and you should be back to where you began.

**Comment by odiea** [comment]
Go to Store config/receipt. See if you have any printers selected. Choose a different printer then hit submit. Now go back to receipt and choose the printer you want. Hit submit. Go to Takings and retry printing a receipt.

**Comment by odiea** [comment]
You will also have to go to firefox addons - select the jsprint feature and place the computer ip address into it so that it gives permission to use from your local computer.

**Comment by Ibnumarjan** [comment]
Sorry for the late reply, @odiea, thanks, it works.....
by the way there is way to achieve this chrome, the problem with firefox is I can make the app like a desktop app (without url bars, tabs etc).

**Comment by odiea** [comment]
I have not tried that yet. Google is your friend.

**Comment by Ibnumarjan** [comment]
Thanks .......for the the supports all... specially to @odiea ..

if any one need, the same with chrome (silent print) the following method works for me.

[https://mycartpos.zendesk.com/hc/en-us/articles/200868343-Enable-kiosk-printing-print-automatically-for-Google-Chrome-on-Windows](url)
