### ISSUE TITLE
Custom font and font size in Sales receipt

### ISSUE THREAD

**Issue by Ibnumarjan** [jekkos/opensourcepos#613]
I would like to change the font size of the (bigger) Total value, I try to change through inner css but not works.

please help

**Comment by odiea** [comment]
It appears that receipt.css really does nothing when changes are made to it.

**Comment by daN4cat** [comment]
You need to rebuild the min.css file after having changed the receipt.css. A means to test it before creating the min.css is to add ?debug=true at the end of the url line. That forces to use the singolar js and vas files. But bower component is required.

**Comment by odiea** [comment]
All these new upgrades kinda took the fun out of playing with it.

**Comment by odiea** [comment]
It appears he can still add a style in the receipt itself to get a larger and bolder font.

**Comment by Ibnumarjan** [comment]
Sorry, it doesn't work, please guide me how to achive !!!

`<td colspan="3" style='text-align:right;border-top:2px solid #000000; font-size:200%;'><?php echo $this->lang->line('sales_sub_total'); ?></td>`

**Comment by daN4cat** [comment]
Inline styling should work.

**Comment by odiea** [comment]
Try it with the double quote.
style="text-align:right;border-top:2px solid #000000; font-size:200%;"

**Comment by daN4cat** [comment]
@Ibnumarjan which file are you changing that style? Because if I try from the Inspector adding the style inline works perfectly.

**Comment by Ibnumarjan** [comment]
Thanks, Inline css works in receipt.php, 

but not in throgh receipt.css file.

Once again thanks all for the support

**Comment by sanubari97** [comment]
please tell me how to do that specifically ? I know nothing about the coding.
just the font size. how should I type it ?
I'm in the latest ver. and nothing happened in css.
