### ISSUE TITLE
[question] How to create a PDF with the invoice and save it to the server

### ISSUE THREAD

**Issue by pablos1rvent** [jekkos/opensourcepos#617]
Well, I found this on "Sales.php"

![395127d43b57c619e7b5719944e2022c](https://cloud.githubusercontent.com/assets/17593856/15773199/f4d19f18-2975-11e6-8bf1-17984729a569.png)

![2993782c1c2ed001fd439f8f8cf37b56](https://cloud.githubusercontent.com/assets/17593856/15774544/3824a95c-297d-11e6-8aeb-869bed9a7ab7.png)

 and I was looking for create an automated PDF that save it to the server or to the web browser, with that code I can create that?

Greetings

**Comment by jekkos** [comment]
Invoices are saved to server temp storage when they are emailed to a customer. Check /tmp on your linux host to find those generated PDFs.

So it shouldn't be too hard to put them in any location you want. Think it's dompdf that loads up an html view and outputs a pdt in the temp folder.

**Comment by pablos1rvent** [comment]
@jekkos Yeah, I code on Windows with XAMPP and for my business Linux, but is a shared hosting, do you mean that my pdf's are saved automatically? 

I create a new function that does the PDF and save it automatically with the API on Dropbox, I think I can share it and pull but don't useful for most people, what do you think?

**Comment by jekkos** [comment]
Ok to share if you think the code is generic enough (like you should have dropbox api configuration in config tab, etc)
