### ISSUE TITLE
db restore issue

### ISSUE THREAD

**Issue by Ibnumarjan** [jekkos/opensourcepos#618]
I took the db backup from Store Config> General tab's Dababase Backup button. When I try to resore through phpmyadmin, the following error appear. How can I sort out this and I desperatly need the backup to be restore? Please help me.

`Error
SQL query:

CREATE TABLE `ospos_customers` (
  `person_id` int(10) NOT NULL,
  `company_name` varchar(255) DEFAULT NULL,
  `account_number` varchar(255) DEFAULT NULL,
  `taxable` int(1) NOT NULL DEFAULT '1',
  `discount_percent` decimal(15,2) NOT NULL DEFAULT '0.00',
  `deleted` int(1) NOT NULL DEFAULT '0',
  UNIQUE KEY `account_number` (`account_number`),
  KEY `person_id` (`person_id`),
  CONSTRAINT `ospos_customers_ibfk_1` FOREIGN KEY (`person_id`) REFERENCES `ospos_people` (`person_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
MySQL said: Documentation

#1215 - Cannot add foreign key constraint `

**Comment by Ibnumarjan** [comment]
Can anyone support on the above issue please

**Comment by odiea** [comment]
You can try to open the db with notepad plus then add the following line above the first create table. Creat a new database with this and your backup.
SET FOREIGN_KEY_CHECKS = 0;

**Comment by odiea** [comment]
add this below the constraint SET FOREIGN_KEY_CHECKS = 1;

**Comment by Ibnumarjan** [comment]
Thanks @odiea it works. But do we have to add each backup like this, is there any update for this issue.

this is what i did according to your suggestion.....

`CREATE TABLE `ospos_app_config` (
  `key` varchar(255) NOT NULL,
  `value` varchar(255) NOT NULL,
  PRIMARY KEY (`key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
  SET FOREIGN_KEY_CHECKS = 0;`

**Comment by odiea** [comment]
Currently that is the way I get the backup to work. Where ever you place that to make it work is fine.
