### ISSUE TITLE
Sale lib Invoice issue

### ISSUE THREAD

**Issue by odiea** [jekkos/opensourcepos#619]
It appears that the following was removed of left out of the current version of OSPOS
function clear_all()
$this->set_invoice_number_enabled(FALSE);

**Comment by jekkos** [comment]
You mean the invoice enbaled clear out? DIdn't we include that in 2.4?

**Comment by odiea** [comment]
Yes . It was in 2.4 but went missing somewhere along the line.

**Comment by jekkos** [comment]
Issue fixed in latest. Can someone confirm so I can close?

**Comment by odiea** [comment]
The clear out is working properly now.
