### ISSUE TITLE
Receiving Quantity under the new item dialogue box?

### ISSUE THREAD

**Issue by Ufordinner** [jekkos/opensourcepos#62]
Can you please explain to me the field "receiving quantity" in version 2.3.1?
  It is a third field... different from "Quantity Stock" and "Reorder Level".
I have reviewed how it operates, for example I added an item with 2 quantity
and sold those two items yet the "receiving quantity" field still shows 2.
It is almost as if it is acting as a record of the last amount received?  I
am not quite sure.  It is not impacted by selling product.  Thanks so much!

**Comment by odiea** [comment]
Receiving qty is used as a multiplier for the Receivings module. Say you received a 12 pack of soda.In Items you would add 12 to quantity stock and receiving qty of 12. When you go to update the item in Receivings you would then choose a qty of 1 and it will automatically multiply it by 12 to increase your inventory. This is what I have seen it do.

**Comment by jekkos** [comment]
indeed thanks for the explanation odiea.
