### ISSUE TITLE
Sales Taking Cash added up incorrect

### ISSUE THREAD

**Issue by shaz1** [jekkos/opensourcepos#620]
I have noticed that when viewing your sales through takings and you can select the date range once your sales list goes on to the next page then the cash total is added incorrectly. If all sales fit on 1 page (max 100) then the figure is correct. im not sure why it is miscalculating but think it has something to with amount tendered and not taking into account the change due on the other pages,

**Comment by jekkos** [comment]
The total does not change when switching between pages. So how can it be wrong on page 2? 

You always see the total payment amounts of the whole resultset below the takings table..

**Comment by jekkos** [comment]
Or maybe you mean that the total is wrong once pagination kicks in.. let me check that

**Comment by jekkos** [comment]
Ok I just did a quick test for both situations and all seems fine. Also pagination parameters are not taken into account for the totals calculation, so they should be of no influence there either.

**Comment by jekkos** [comment]
Did a quick retest today and still can't reproduce. Table fits fine in my first page. Did you test on windows? It might be something os dependent perhaps?

**Comment by daN4cat** [comment]
This looks to be fine. I close.
