### ISSUE TITLE
(Question)  How to migrate all data from OSPOS 2.0 version to last version of OSPOS?

### ISSUE THREAD

**Issue by bunhin** [jekkos/opensourcepos#621]
Hi all,

I believe this is a very late question, but i need some guidelines to solve my issue here. (i am sorry if this is not a right place to submit this question).

I  have installation of OSPOS 2.0 version at a small shop with about 3 years data of product, customer, supplier and transaction, and need to migrate into the last version of OSPOS 2.4 or 3.0. I check the database update script and the upgrade guide, but there is no database update script from 2.0

If there is not a script, then i plan to install the last version and import the data into new install of last version, but i am not sure how to do with the right way, Would you please share the right way to do it it.

Regards,
Bun

**Comment by sonnysk76** [comment]
Yo can export the databases directly from phpmyadmin, as SQL, then in the new installation run this SQL instead of the SQL bundled with the new version, this would work as long as the databases have the same structure, I don't know if something changed,  you can try, also it works as backup for your information.

**Comment by bunhin** [comment]
Hi Sonny, thank you for response,
"...this would work as long as database have the same structure.." i believe the database tables has been changed quite a lot between version 2.0  and 2.4 or 3.0, that is why database update script required, if deploying sql exported from 2.0 database, new field or table is not created and caused error.  The update script for database available starting from 2.2.1_to_2.2.2,  but not available from 2.0 to 2.2.1 ( i dont know whether it is required from 2.0 to 2.2.1 or not),

**Comment by daN4cat** [comment]
@jekkos are you aware of any db change from 2.0 to 2.2? I didn't follow the evolution from from 2.0 as I'm on an old PHPPOS 1.1.

**Comment by jekkos** [comment]
Indeed sql scripts are missing for versions between 2.0 and 2.2. I found this post on the sourceforge site


 ```
All,

My apologies, but it appears that there were a few database modifications in the last code release that didn't have an accompanying update SQL file; which I believe is what's causing all the problems. I'm working on getting one up in the repository and will release 2.1.1 with the update.

Sorry for the inconvenience.

Tom
 ```

**Comment by jekkos** [comment]
> For those that downloaded version 2.1.0, please run the below in your database (throught phpMyAdmin for example) to fix these issues. If you chose a custom prefix on the tables, you'll have to change that here before running the code.

> ALTER TABLE ospos_items
ADD custom1 VARCHAR(25) NOT NULL,
ADD custom2 VARCHAR(25) NOT NULL,
ADD custom3 VARCHAR(25) NOT NULL,
ADD custom4 VARCHAR(25) NOT NULL,
ADD custom5 VARCHAR(25) NOT NULL,
ADD custom6 VARCHAR(25) NOT NULL,
ADD custom7 VARCHAR(25) NOT NULL,
ADD custom8 VARCHAR(25) NOT NULL,
ADD custom9 VARCHAR(25) NOT NULL,
ADD custom10 VARCHAR(25) NOT NULL;

> ALTER TABLE ospos_giftcards ADD person_id INT NOT NULL ;

> Tom

**Comment by jekkos** [comment]
Don't tthink there were any other db changes between 2.1 and 2.2

**Comment by daN4cat** [comment]
Maybe we should add a 2 to 2.1 db upgrade script

**Comment by daN4cat** [comment]
Added upgrade script starting from 2.0, of course based on forum history as it's not easy to go back and test this without spending some significant amount of time.

**Comment by bunhin** [comment]
Thanks  for all responses and solution, so i will run all upgrade script until last version hope it will work

**Comment by daN4cat** [comment]
Make sure to backup your database before you start!
