### ISSUE TITLE
Sales/Receiving  Screen and Item Search

### ISSUE THREAD

**Issue by Ibnumarjan** [jekkos/opensourcepos#622]
We have almost 2000 items and some of the branded items we entered with thier particular barcode and other items with our own item code with 4 digit number (starting from 1000). 

Now when we enter any 4 digit items  through sales/receiving screens, instead of item_number, it is searching by item_id (auto generated id)... is it possible to search the items without item_id?

Please help..

**Comment by daN4cat** [comment]
Version?
