### ISSUE TITLE
Item Kits at point of sale

### ISSUE THREAD

**Issue by odiea** [jekkos/opensourcepos#623]
I noticed that If an Item kit is entered there is no warning about low or out of stock Inventory. Is there a way to correct this?

**Comment by daN4cat** [comment]
It looks like item kits are getting a bit of prime time here in recent weeks. We should list what we want more that is not implemented.

For the specific, yes it's all doable and it goes in the todo list.

**Comment by jekkos** [comment]
Yes would be more managable to make an epic with sub stories to wrap this all up

**Comment by daN4cat** [comment]
I'll work on that later.

**Comment by odiea** [comment]
I will close this and hopefully users will use #625.

**Comment by daN4cat** [comment]
I prefer to keep the different topics open, #625 is just an umbrella.

**Comment by odiea** [comment]
Ok.

**Comment by daN4cat** [comment]
@odiea is the latest master fixing this? If yes please close.

**Comment by odiea** [comment]
No. Currently there are no warnings at all for low or out of stock items on the Register.

**Comment by daN4cat** [comment]
You need to convince @SteveIreland to look into this too...

**Comment by SteveIreland** [comment]
@odiea @daN4cat  Isn't this complete now?

**Comment by daN4cat** [comment]
I didn't check, but I trust you guys and mark it done.
