### ISSUE TITLE
Item Kits improvement

### ISSUE THREAD

**Issue by daN4cat** [jekkos/opensourcepos#625]
This is an holder to several Item Kits improvement ideas that have been floating around and shuould be considered as input to improve the Item Kits concept and support.

**Comment by odiea** [comment]
1. I noticed that If an Item kit is entered there is no warning about low or out of stock Inventory. Is there a way to correct this? Also is there a way to add the Item name with the low or out of stock warning.
2. #586 sonnysk76 had a good tip to display the Item kit major item on the receipt while other items from the kit can be removed from inventory. I would suggest just using the receipt portion of his tip so that other low Inventory items can be seen at POS.

**Comment by RamkrishnaMondal** [comment]
We run a computer shop and sell assembled desktops, will be very helpful if the invoice shows the price of the whole desktop (as item kit) instead of individual components's prices. Though for the warranty purpose, we shall need the name  and serial no of each individual components to be printed on the invoice.

**Comment by odiea** [comment]
If I purchase a custom computer I would like to see the price of all the parts I paid for individually on the receipt. That way I know why the total cost is what it is. That is what Kit pricing is for.  At time of sale you then enter the serial number of the Items sold.

**Comment by sgr1875** [comment]
me too same issue, i am running a super market i always throw in combo offers its always been tricky :)

**Comment by SteveIreland** [comment]
I've started the Item Kits documentation page on the opensourcepos wiki here and will continue to flesh it out over the next 2 or 3 days before I start doing any coding.

This issue and  and #200 will be my guide.  I assume that issue #1043 should just be left open until the changes are complete.

[Item Kits wiki page](https://github.com/jekkos/opensourcepos/wiki/Item-Kits)

**Comment by SteveIreland** [comment]
Can this be added to the 3.1.0 milestone?  Unless something happens that stops me I expect to have it coded up by 1/3/2017 and ready for testing.

**Comment by SteveIreland** [comment]
@odiea One other question regarding this.  When adding items to a sale the last item added is always shown at the top.  That is normal and perfectly understandable.  However, it seems that on the invoice the items are listed in the same sequence instead of showing the first item at the top of the list and the last item added at the bottom of the list.  I haven't seen this anywhere I've worked before, but it could be an industry specific thing.  I haven't checked the receipt yet, but I'm guessing it's in the same reverse sequence.

Can I change the invoice and receipt to list them in the line number sequence (sequence entered)?

If not then I'll need to add a configuration option to print the in either entered sequence or reverse sequence.

Thanks..

**Comment by odiea** [comment]
The current Invoice is based on the European feature to show proof that a person or Company paid their Taxes I believe, where here in the USA it is a request for payment. I do not believe the listed order of Items or Services would be an issue but @daN4cat or @jekkos  would know more about that.

**Comment by SteveIreland** [comment]
Thanks.  That tidbit of information explains the design of the sales component for me.  For now I'll go ahead and add a config option that controls the invoice sequence item sequence until I hear from @daN4cat or @jekkos.  I'm less concerned about the receipt sequence but if it turns out to be a trivial change then I'll go ahead and add support for sequence options.

**Comment by odiea** [comment]
I know here in the automotive field we always had our labor listed first then our items listed second. I think it would be easier to create a receipt configured that way. So if the lines were set entering the labor then the items that way it would work better for service industries.

**Comment by odiea** [comment]
I think I discussed with @jekkos about being able to create a labor item or maybe group labor items then group Items themselves separately. But that is another issue.

**Comment by SteveIreland** [comment]
I added an item type to the item table to distinguish between non-stock, stock, and kit items.  So it will be simple enough to group items by item type on the receipt and invoice.  So I'll add that as a sequence option.

**Comment by daN4cat** [comment]
Order of the list is not an issue. It probably happened that it's stored in code in a certain way and when you go through the list to display the content it's listed in that order.
A lot it's legacy functionality and since it's working you don't touch it as there are more important things to do. That's the principle here :-)

**Comment by odiea** [comment]
I changed the one I use in Register and Receipt to foreach($cart as $line=>$item) instead of the reverse_array. It appears more like a cash register tape.

**Comment by SteveIreland** [comment]
Yes, I saw that reverse_array too.  I haven't touched that code yet.  I just now finished my first pass at debugging my changes to the Item, Item Kits, and Item Kit Items maintenance programs.  I've also added the config option for sequencing invoices (and apparently receipts by either Standard (which is what is installed now), Entry sequence, by Item Type,Item Name (which will list non-stock first followed by stock items) and also Category which will sort by Item Category, Item name).

I've made my first pass at adding support for sequencing to the invoice - but I haven't test to see what the impact of those changes were to the receipt but it does look like there is an impact, so I'm sure I have some recovery to do there.

My "vacation" has come to an end so I'm not going to be as productive as I've been over the last few days.  

I now expect to submit a pull request sometime next weekend, but it will depend on how well my debugging goes during the week.  I'm also debugging issues related to the MySQL 5.7 changes.  When I am feeling "prematurely" confident then I'll catch up my development branch with the latest changes to master, give it another brief test and then submit the pull request.

**Comment by jekkos** [comment]
WIth invoice sequencing you mean the order in which items are listed? Or do you refer to invoice numbering itself?

**Comment by SteveIreland** [comment]
I meant the sequence in which items are listed on the invoice, so I should have used the term "invoice line sequence".

**Comment by SteveIreland** [comment]
I made progress on this over the weekend.  There are a few more rules that I want to add but I went ahead and submitted a pull request.  The changes are on the mysql_5.7 pull request.  I resubmitted the pull request just to see if I'd get the same Travis build error that I encountered last time.  As far as the mysql_5.7 changes this should be a lot cleaner.  It also includes that array reset that added to fix the PHP 7 issue.

**Comment by odiea** [comment]
I downloaded your 5.7 branch. Works great with 5.7 and php 7. Graphical Reports showing some issues and Stock report has no grant. Little stuff that needs attention. Looks like a great addition. I know you said you weren't done with it.
Thanks.

**Comment by SteveIreland** [comment]
Thanks for the feedback @odiea .  I also encountered the stock report issue but had so many other issues that I didn't have time to explore it, but since it happened to you it will be next on my list.  I haven't done a deep dive yet into the graphical reports so I don't know much about those - but I'll do that as soon as I make sure that there are no inventory updates for non-stock items.

**Comment by odiea** [comment]
I also get this when adding a kit at the Register.
![2017-01-09 12_14_51-wedidit _ powered by ospos 3 0 2](https://cloud.githubusercontent.com/assets/10962177/21779537/65d5c97c-d665-11e6-8e3e-74a0dc52b70c.png)
If you can explain further how the discount on item kits is suppose to work. I did a 10% discount on the kit and nothing changes on the kit display or the register.
I am using my current database with the db upgrade that already has kits.

**Comment by odiea** [comment]
It appears that the table for Items is reporting incorrect info.
Items table.
Sales receipt.
The Item in update modal.

![2017-01-09 12_25_24-wedidit _ powered by ospos 3 0 2](https://cloud.githubusercontent.com/assets/10962177/21779960/0ab86de0-d667-11e6-9e23-1d2729d957cb.png)
![2017-01-09 12_26_10-wedidit _ powered by ospos 3 0 2](https://cloud.githubusercontent.com/assets/10962177/21779965/106cfe2c-d667-11e6-9128-f4b6a21a4d89.png)

![2017-01-09 12_30_02-wedidit _ powered by ospos 3 0 2](https://cloud.githubusercontent.com/assets/10962177/21780068/669b8214-d667-11e6-93d4-6a5c34591b5e.png)

**Comment by odiea** [comment]
The following tables are from the same database. Your version shows the OSPOS. The -8 for replace ign coil was after selling the labor a second time. You can see the difference in the tables.
![2017-01-09 12_43_15-wedidit _ powered by ospos 3 0 2](https://cloud.githubusercontent.com/assets/10962177/21780587/69d5f660-d669-11e6-8674-1cb94063ee51.png)
![2017-01-09 12_44_26-wedidit _ powered by ospos 3 0 2](https://cloud.githubusercontent.com/assets/10962177/21780597/70d14eec-d669-11e6-8ef0-538dacc82e26.png)

**Comment by odiea** [comment]
line 105 in models/item.php  $this->db->select('max(item_quantities.quantity) as quantity'); I changed sum to max and all appears to be better.

**Comment by odiea** [comment]
Models/Sale.php
166-169 payments.sale_payment_amount AS amount_tendered,
 (payments.sale_payment_amount - IFNULL(ROUND($sale_total, $decimals), ROUND($sale_subtotal, $decimals))) AS change_due,
" . '
payments.payment_type AS payment_type
Sum and Max were removed now takings shows correctly.

Summary reports . Max was removed and reports now work.

**Comment by SteveIreland** [comment]
I played around with the stock report this afternoon.  Apparently this was new with 3.0.2 and possibly accidentally introduced before it was ready?

I found that I after I had manually added a record into the permissions table for that option (`reports_stocks`) I was able to get past the security block, but immediately found that I received a page not found error on  `.../reports/summary_items_stock/...`

It's not available as an option in an earlier version that I have running.

**Comment by odiea** [comment]
I now see that with the current database.sql stocks report is added but there are no stock reports available yet in models/reports.

**Comment by SteveIreland** [comment]
What's the preferred procedure for setting up for multi-languages?  I've added several new literals to the English language tables.  Is it preferred that I create a non-translated entry in each of the language files (with the English translation) or just add the them to the English version only?  I see indications of both approaches in play.

**Comment by jekkos** [comment]
@odie some reporting part  was redone for stock before 3.0.2.. not sure if this is a bug in the current version or only present in Steve's PR? If yes  then we should probably make a ticket for that.

**Comment by odiea** [comment]
I just downloaded the current master and the Stock Reports do not show like they do in Steve's version.
I will also note that if you download the master from IE it will not load properly. 
![2017-01-13 16_59_13-wedidit _ powered by ospos 3 0 2](https://cloud.githubusercontent.com/assets/10962177/21949726/c892eb40-d9b1-11e6-955d-d6e146462562.png)

**Comment by odiea** [comment]
Maybe this is the cause for some people saying they are having issues. The page shows nothing when you go to it.
![2017-01-13 17_04_52-downloads](https://cloud.githubusercontent.com/assets/10962177/21949827/90c52d44-d9b2-11e6-8de8-eb48eb8d401c.png)

**Comment by SteveIreland** [comment]
I'm still working through the entire system to resolve any issues I stumble across using MySQL 5.7 and PHP 7 as the test platform.  I want to reiterate that I submitted the pull request just to see if it passed the Travis test (because my last one failed it).

I'm not yet clear on why my branch shows the stock report but the master doesn't. I sync'd it with the master just before submitting the pull request, but it now sounds like it was something I somehow introduced.  I'll make sure it's gone before submitting another pull request.

Thanks for all of the feedback.

**Comment by odiea** [comment]
Let me know when you are closer and I will down load your fork again and give it a try.

**Comment by SteveIreland** [comment]
I've put some more work into it this weekend and submitted another pull request. 

I ended up splitting the item_type into both a stock_type and item_type field so that I had the option to treat kits as stock or a service items.

**Comment by odiea** [comment]
Same issues with takings and items qty not showing correctly. I am now unable to add an Item kit. It will not accept items but it does create the kit.

**Comment by SteveIreland** [comment]
Ack!  I'll have that fixed tonight and resubmit.  I also saw where there was a conflict on the push and will check to see what that's about.  I made some last second changes that I thought were innocuous - but apparently not.   Sorry.

**Comment by odiea** [comment]
I am just downloading your version from your git web if that makes any difference.

**Comment by odiea** [comment]
Here is the database.
![2017-01-16 08_00_32-192 168 0 13 _ localhost _ ospos1 _ ospos_item_kits _ phpmyadmin 4 5 4 1deb2ubun](https://cloud.githubusercontent.com/assets/10962177/21987759/ff6748a2-dbc1-11e6-920d-7093ba8b7dc8.png)
and here is the kit table.
![2017-01-16 08_00_52-wedidit _ powered by ospos 3 0 2](https://cloud.githubusercontent.com/assets/10962177/21987773/0e434a38-dbc2-11e6-9bc1-ef13ce297b8b.png)

**Comment by odiea** [comment]
Another thing that bothers me is in Items you check if for kit then that item cannot be added to a different kit.

**Comment by SteveIreland** [comment]
I don't think I've added any validation yet. I proposed it in the Wiki, but your comment is the first and I'm more than happy to not add any validation.  The way it is now certainly provides more flexibility.  I'll wait until someone complains that "they shouldn't be allowed to do that" before adding any validation.

**Comment by odiea** [comment]
Possibly something not correct with the seq. I can add to or update an Item kit now.
$item_kit_items = array();
				foreach($this->input->post('item_kit_qty') as $item_id => $quantity)
				{
                    $seq = $this->input->post('item_kit_seq[' . $item_id . ']');
					$item_kit_items[] = array(
						'item_id' => $item_id,
						'quantity' => $quantity
                        //'kit_sequence' => $seq
					);
				}

**Comment by SteveIreland** [comment]
I've fixed the issue with the item kit maintenance but haven't uploaded it yet.  Francesco suggested a couple of improvements to my pull request so I'm working on that now.

**Comment by odiea** [comment]
On your item kit form was the following on purpose or an accident?
~~~
$("#item_kit_items").append("<tr>" +
                    "<td><a href='#' onclick='return delete_item_kit_row(this);'><span class='glyphicon glyphicon-trash'></span></a></td>" +
                    "<td><input class='quantity form-control input-sm' id='item_seq_" + ui.item.value + "' name=item_kit_seq[<?php echo $item_kit_item['item_id'] ?>] value='0'/></td>" +
                    "<td>" + ui.item.label + "</td>" +
                    "<td><input class='quantity form-control input-sm' id='item_qty_" + ui.item.value + "' name=item_kit_qty[" + ui.item.value + "] value='1'/></td>" +
                    "</tr>");
~~~
After I changed the item seq to the same as item qty it works now.
~~~
$("#item_kit_items").append("<tr>" +
                    "<td><a href='#' onclick='return delete_item_kit_row(this);'><span class='glyphicon glyphicon-trash'></span></a></td>" +
                    "<td><input class='quantity form-control input-sm' id='item_seq_" + ui.item.value + "' name=item_kit_seq[" + ui.item.value + "]  value='0'/></td>" +
                    "<td>" + ui.item.label + "</td>" +
                    "<td><input class='quantity form-control input-sm' id='item_qty_" + ui.item.value + "' name=item_kit_qty[" + ui.item.value + "] value='1'/></td>" +
                    "</tr>");
~~~

**Comment by SteveIreland** [comment]
Yes, that was one of the corrections I've made.  Git is giving me trouble, so that's where I've spent the last few hours - trying various ways to rebase the branch.   It might be quicker just to restart from scratch.  Frustrated.

**Comment by odiea** [comment]
Sorry to hear that. Hope you get it all straightened out.

**Comment by SteveIreland** [comment]
After restarting from scratch I just finished recovering the vast majority of my changes.  I need to confirm that all of my attempts to rebase didn't lose any commits ... so after I confirm that I didn't lose anything I'll submit another pull request.  At the latest it will be Sunday of this week.

**Comment by daN4cat** [comment]
Even this one will need a thorough testing.

**Comment by SteveIreland** [comment]
I agree with you 101%

**Comment by odiea** [comment]
Minor issue with the way Detailed Sales Report configures tax.
This is present in all versions. Maybe you can see the problem.
![2017-01-29 06_56_55-wedidit _ powered by ospos 3 0 2](https://cloud.githubusercontent.com/assets/10962177/22404617/ec2b2c2e-e5f1-11e6-94fc-e916917af6d8.png)
![2017-01-29 06_58_01-wedidit _ powered by ospos 3 0 2](https://cloud.githubusercontent.com/assets/10962177/22404619/f8b4f704-e5f1-11e6-974f-4afd5ca748e9.png)

**Comment by daN4cat** [comment]
@odiea is this issue with @SteveIreland's changes or not? Not sure I follow...

**Comment by odiea** [comment]
No I just noticed it using this version. When I switched to a different version it also shows Taxes incorrectly.

**Comment by daN4cat** [comment]
@odiea can you please create a new issue so we don't mix up things? Thanks

**Comment by daN4cat** [comment]
@SteveIreland when I create a new item kit I get an error:

```
A PHP Error was encountered

Severity: Notice

Message: Undefined property: stdClass::$kit_item_id

Filename: controllers/Item_kits.php

Line Number: 113

```

Please look into that.

**Comment by SteveIreland** [comment]
I just now saw your message but wasn't able to recreate it.  However, when I was testing it I found related issue that I'm sure has something to do with your issue.  I'll have it fixed tomorrow.

**Comment by odiea** [comment]
So far I have not been able to replicate this either in recently downloaded Master or updated branch.

**Comment by daN4cat** [comment]
I'll test again this evening

**Comment by SteveIreland** [comment]
I just realized that I didn't "prime the pump" on the new line_sequence configuration option - so the next time I commit a change I will changes tables.php to initialize it with a "0" to default to Entry sequence.

**Comment by daN4cat** [comment]
I can systematically reproduce it.

**Comment by SteveIreland** [comment]
Okay, I'll take a closer look.  When you encounter this issue are you adding the item kit with our without a selected kit item - or does it happen regardless?

**Comment by daN4cat** [comment]
I just click "New Item Kit" button and on the modal dialog I get that error on top.
I just have a pre-existing item kit in the list no more.

**Comment by odiea** [comment]
It appears that with a new download and a new database I can't replicate your issue and after selecting all different Date Time you can't replicate my issue?

**Comment by odiea** [comment]
@daN4cat Have you downloaded and tried the latest Master. I have had no issues with this. Maybe you got a bad pull.

**Comment by SteveIreland** [comment]
@odiea the issue appears in development mode but not production mode.

**Comment by daN4cat** [comment]
Good. So a bit of more testing and let see if we can close this Epic.

**Comment by daN4cat** [comment]
The New Items Kit issue is fixed.

**Comment by daN4cat** [comment]
@SteveIreland I need to reopen this because there is an issue.

When an admin removes the permission to use Items_kit even because they might not need it, the Item edit modal box still shows the "Item Type" radio that should be visible only for kit cases.
Please add the permission check in the Item modal view.

Not sure about the "Stock type" option, that's new.

**Comment by SteveIreland** [comment]
Can we consider leaving it there?  It provides some flexibility for additional modules that might provide additional types of items.  Setting the item type to "Kit" doesn't force a dependency to Item Kits.  

However, if the permission is disabled then I can see where items of type Kit shouldn't be excluded from item selection for orders - which it is now because Item Kits are listed at the bottom of the item selection.   So if you're okay with this then that is the change I would prefer to make ... but will do as directed. 

Stock type has nothing to do with kits and everything to do with service items which are non-stock items.

**Comment by SteveIreland** [comment]
Rethinking that.  

I'm assuming that Item Kits permissions for a specific employee only means that the particular employee cannot maintain Kit items ... right?   So that shouldn't affect how items are selected for orders because that employee should still be able to place an order for that item.

So the appropriate action would be to not allow the unauthorized employee to be able to select a Kit as an item type.  So if the employee is not authorized then the kit item type should not be included as an option.

**Comment by daN4cat** [comment]
What I want to avoid is people fiddling with stuff that is not relevant.

In my wife's case there is no kit concept and having something not required opens the matter to questions, fiddling and etc.

I'll fix it at item edit modal later.

**Comment by daN4cat** [comment]
Testing more I can see that the Bulk edit has nothing of the two options, was that intentional or an oversight?

@SteveIreland in case you are reworking the two modals, I would prefer to have the "Stock Type" at the bottom as one of the check boxes and state something like "Non stock type" and somebody checks the box if it's yes. I don't think people using non-stock items need to create 100 of them, so a scroll down won't harm.

With regards to Item being part or not of a Kit again it's better to move it down and show it if the Item Kits permission allows it as it should be restricted in my opinion.

**Comment by SteveIreland** [comment]
ok

**Comment by SteveIreland** [comment]
@daN4cat The bulk edit is an oversight on my part ... I've never looked (much less touched) the bulk edit.  I'll take a look.

On an earlier point ... since you essentially don't want the user to even be aware of non-stock items and kit items unless they explicitly request those features then what do you think about adding a configuration option for enabling non-stock support?  If that option is selected then the non-stock feature would be visible, otherwise it would default to stock internally and not be visible.  Also, I'll go ahead and change it so that if the user isn't enabled for Item Kit access then I'll hide that field as you recommended.

**Comment by SteveIreland** [comment]
And just to be clear, you're saying that the rule is that if the user isn't authorized to kit items, they cannot only NOT maintain them but they cannot sell them either.... right?

**Comment by daN4cat** [comment]
I would say hide what needs to be hidden.

With regards to permissions it's a good point. Do we want cases where we hide the edit but we can add?
It's like suppliers and customers. We allow the addition but not the edit.
Maybe have a permission with two sub permissions would be better. One edit and one add. What do you think?
This point should be considered more in general I believe. ...

**Comment by daN4cat** [comment]
@SteveIreland can this be closed?

**Comment by SteveIreland** [comment]
I believe it can be closed.

**Comment by daN4cat** [comment]
@SteveIreland I closed but I noticed that nothing of those options were added to bulk edit. I suppose it's fine like that.
I don't consider a bug but up to you to decide.
