### ISSUE TITLE
Receiving invoice number can not be changed

### ISSUE THREAD

**Issue by donangil** [jekkos/opensourcepos#626]
I can not create custom recieving invoice number. Is this a known issue ?
v3.0

**Comment by odiea** [comment]
Yes it appears that custom Invoice number can not be used with Receivings.

**Comment by jekkos** [comment]
Did a fix for this issue in receivings module. Custom number overrides should be properly saved now.

**Comment by jekkos** [comment]
Can someone confirm if ok now?

**Comment by odiea** [comment]
Receiving Invoice number can now be customized and clear out of check mark is working.

**Comment by odiea** [comment]
Reports Detailed Receivings the Invoice numbering on Update  works correctly and it checks for duplicate numbering.

**Comment by jekkos** [comment]
OK thanks for the test.
