### ISSUE TITLE
Demo Installation 

### ISSUE THREAD

**Issue by RamkrishnaMondal** [jekkos/opensourcepos#632]
Just did a demo installation for testing....

http://ospos.pe.hu

Please note that the favicon is replaced by the hosting provider for advt, as it is a free hosting site.

**Comment by onyema3** [comment]
Nice..
is this in your repo??

**Comment by RamkrishnaMondal** [comment]
I am afraid ... no.

**Comment by onyema3** [comment]
Can you share??? :)

**Comment by RamkrishnaMondal** [comment]
Just customized .... need some testing, I also wish to add some more .... then i will upload it to my repo.

**Comment by onyema3** [comment]
Cool....Good Job keep it up!
