### ISSUE TITLE
Backup_db confirmation on Logout

### ISSUE THREAD

**Issue by RamkrishnaMondal** [jekkos/opensourcepos#634]
I was trying to restore the old ospos functionality of db backup confirmation at log out. Working fine on a 15 days old version of ospos 3 but when i tried this on a newer master downloaded yesterday , it's not working. Even I can not logout.

Head Section:

```
<script type="text/javascript">

		function logout(logout)
		{
			logout = logout && <?php echo $backup_allowed;?>;
			if (logout && confirm("<?php echo $this->lang->line('config_logout'); ?>"))
			{
				window.location = "<?php echo site_url('config/backup_db'); ?>";
			}
			else
			{
				window.location = "<?php echo site_url('home/logout'); ?>";
			}
		}
</script>

```

Body Section:

```
<a  href="javascript:logout(true)">
<?php echo $this->lang->line('common_logout') ?></a>
```

**Comment by jekkos** [comment]
Backup on logout prompt was removed from the code some time ago...

**Comment by daN4cat** [comment]
Check with the inspector and see if there is any js error reported when you load your page. That might block your js to work properly.

**Comment by RamkrishnaMondal** [comment]
@daN4cat  Firebug shows this. How to fix that ?

![screenshot from 2016-06-10 19 34 06](https://cloud.githubusercontent.com/assets/14151032/15966871/93f68b7c-2f42-11e6-8006-ea4127fb1f17.png)

**Comment by bkrajendra** [comment]
I was also in need of backup, this really needed as i'm going into many problems from beginning of installation ..!
@RamkrishnaMondal 
Here I'll suggest autobackup a better solution, which can be achieved through cron job or schedule task (Linux, windows).
As i'm currently working on windows I found few simple solutions.:
create a batch file with following content in it:dbupdate.bat
```
set SAVESTAMP=%DATE:/=-%@%TIME::=-%
set SAVESTAMP=%SAVESTAMP: =%.sql
mysql ospos > D:\backup\%SAVESTAMP% --user=mysqluser --password=pass
```
(make sure mysql should be in PATH ENV variables)

After this run following command to create schedule task in windows:
```
schtasks /create /sc minute /mo 20 /tn "OSPOS DB Update" /tr D:\backup\dbupdate.bat
```
This will execute batch script every 20 mnts. We do have to deal with deleting too old backups.
I've not tried this yet... but hope this is useful !

**Comment by RamkrishnaMondal** [comment]
@bkrajendra 
Thanks for the references.
Anyway my actual question was specific to the above java script...I have found the solution.
You can check here     http://www.ospos.pe.hu

**Comment by onyema3** [comment]
Nice. Waiting to see it in your repo
