### ISSUE TITLE
Receivings/return

### ISSUE THREAD

**Issue by arteiro** [jekkos/opensourcepos#635]
in receivings / return requires single invoice number but has no field to enter

**Comment by odiea** [comment]
It does appear that Invoicing on receiving Returns gets disabled.

**Comment by daN4cat** [comment]
So is it a bug?

**Comment by odiea** [comment]
I don't know if this is a bug or a built in feature from olden days.
To enable Invoicing on Receiving returns go to application/views/receivings/receiving.php
Around line 310 remove words before the following so it looks like this.
if ($this->config->item('invoice_enable') == TRUE) then Invoicing shows properly.

**Comment by daN4cat** [comment]
Shouldn't be invoices for Returns and not for Receive?

**Comment by odiea** [comment]
I think both should have the ability to have Invoicing on Receiving or Returns.

**Comment by odiea** [comment]
Plus little tweaks like this will keep End Users coming back. It appears OSPOS is getting more popular now.

**Comment by daN4cat** [comment]
But Receiving is when you get items from people/suppliers. You don't really issue invoices for those cases, the other end issues invoices or credit notes.
Or are there other cases for Receiving?

**Comment by bkrajendra** [comment]
Receiving does need kind of invoice receipt to be printed for reference. Also there is need of an extra field called Supplier reference number. So that every purchase can be related to stock inward.

**Comment by daN4cat** [comment]
I can understand supplier invoice reference, not issue invoices on receiving something. A receiving note might be desirable as confirmation of stock acceptance.

**Comment by daN4cat** [comment]
I believe that filed should be renamed reference and have it in receive as in return.
In this way could be an invoice, a return code received from the supplier and etc.
Invoice is misleading as there is no invoice issued in the end.

**Comment by jekkos** [comment]
I agree on this one. There's no 'invoice' template in receivings anyway. It was initially added to allow a user to add a custom reference number to the receipt so maybe it'd be better to rename it to reference after all.

**Comment by jekkos** [comment]
Here in Belgium invoices are  only made when you sell products to a client and thus need to  officially need to declare that your customer paid vat which you need to pay back.

**Comment by daN4cat** [comment]
Since I need to work on Receiving Controller next I will make it reference and not invoice.

**Comment by odiea** [comment]
Thanks. That should clear up any confusion in Receivings.

**Comment by daN4cat** [comment]
Changed Receving invoice number to be reference.

Please note that this change requires running the database update script 2.4 to 3.0.

**Comment by daN4cat** [comment]
I believe this is now done.

@jekkos I noticed that Report Detailed Receiving doesn't update the line when editing a Receiving and saving it. Could you please check the issue?

**Comment by daN4cat** [comment]
@odiea have you tested this feature? Is this fine?

**Comment by odiea** [comment]
Other than your issue it appears to be working good. Item kits are showing and all Items in the kit now show.
Report Detailed Receiving doesn't update the line when editing a Receiving and saving it.

**Comment by odiea** [comment]
It also is accepting reference numbers now.

**Comment by daN4cat** [comment]
OK, I close.
