### ISSUE TITLE
enter to update qty instead of "update" button

### ISSUE THREAD

**Issue by sgr1875** [jekkos/opensourcepos#636]
i am using ospos in supermarket and my guys are complaining that they to update by pressing the update button, whereas previously just press enter button in the qnty will do the magic. how can i modify this like previous one?

**Comment by jekkos** [comment]
This issue was fixed in master branch not so long ago. Which version are you using?

**Comment by sgr1875** [comment]
3.0.0 jekkos

**Comment by sgr1875** [comment]
Thanks jekkos i download and updated it again and the problem is resolved thanks again :+1:
