### ISSUE TITLE
Not able to add customer

### ISSUE THREAD

**Issue by sgr1875** [jekkos/opensourcepos#637]
Hi Jekkos i just upgraded to the latest master i just realized am unable to add new customer or edit customer discount

**Comment by sgr1875** [comment]
when i enabled the development mode i am getting this error

A PHP Error was encountered

Severity: Notice

Message: Undefined property: stdClass::$discount_percent

Filename: customers/form.php

Line Number: 61

Backtrace:

File: F:\xampp\htdocs\pos\application\views\customers\form.php
Line: 61
Function: _error_handler

File: F:\xampp\htdocs\pos\application\core\MY_Loader.php
Line: 22
Function: _ci_load

File: F:\xampp\htdocs\pos\application\controllers\Customers.php
Line: 75
Function: view

File: F:\xampp\htdocs\pos\index.php
Line: 315
Function: require_once

**Comment by daN4cat** [comment]
Run the dv upgrade script 2.4 to 3.0.

**Comment by sgr1875** [comment]
thanks a lot its working fine now
