### ISSUE TITLE
Sales and invoice emailing/printing

### ISSUE THREAD

**Issue by daN4cat** [jekkos/opensourcepos#639]
Since I'm working on Sales Controller for the XSS clean task (#39) I'm reading through the code and tidy it up a bit. 

I noticed during the testing and reading of the code that an invoice is not printed/emailed if "Use Invoice Template" option in Store Config is not selected.
I would have expected that if the invoice option is selected in Sales Register with a valid invoice number you should get the invoice not the receipt.

Has that been always like that? Or should it be different?

@jekkos was it implemented in that way on purpose?

**Comment by odiea** [comment]
If I remember correctly Invoice template was an option. The receipt has a place holder for Receipt or something else but that never seemed to work. div id="sale_receipt"><?php echo $receipt_title; ?></div.
Maybe if Invoice is selected the receipt should show Invoice ?

**Comment by daN4cat** [comment]
It looks to me like we should have:

*Sales Register*

- Print checkbox
- Email checkbox (appears if Customer has an email address set)
- Receipt or Invoice:
  -- Default is Receipt
  -- Invoice checkbox appears if Store Config has Invoicing enabled
  -- if Invoice checkbox is selected it's Invoice (and number to be setup appears or it's enabled)
  -- Invoice Templating is optional and according to Store Config setting

*Store Config*

- Enable Invoicing checkbox
- Sales Invoice Format
- Use Invoice Template checkbox
- Text input for the Invoice Templating

**Comment by daN4cat** [comment]
Also Takings should enable the Invoice icon only if it's an invoice not in case of receipt

**Comment by odiea** [comment]
Just an idea.
I added this to app/controlllers/sales in private function load sale data and now the Title changes.

if ($sale_info['invoice_number'] > 0)
		{
	    $data['receipt_title'] = $this->lang->line('sales_invoice');
		}
		else
		{
			$data['receipt_title'] = $this->lang->line('sales_receipt');
		}

**Comment by daN4cat** [comment]
@jekkos what was the intended behaviour?

**Comment by jekkos** [comment]
Customers here sometimes ask for an invoice after a sale is completed. So maybe disable only if there's no vat eligible customer linked to that sale? 

The 'use invoice template' option was added to allow shopkeepers to use the 'invoice' number formatting without having to print the invoice template which is more like a reference number in that case (as in receivings)

**Comment by jekkos** [comment]
Maybe the option name is a little confusing. If a shopkeeper likes to use custom reference numbers for sales but no invoices then he should disable 'use invoice template'

**Comment by daN4cat** [comment]
OK, I leave to you guys as I'm not sure I get what is the policy there.

I've finished with Sales Controller XSS clean. I want to refactor a bit the code, and create one method to Send Invoice and one method to Send Receipt so those can be reused. I can see that there is duplicate code but the condition for the Invoice will stay as it is.

**Comment by odiea** [comment]
My idea was if you did not want to use the Invoice template then the Receipt would show it is an Invoice instead of a receipt. Nothing more.

**Comment by daN4cat** [comment]
When Invoice is selected in Sales register and Invoice is produced without dependency on Invoice Template selection.

I refactored several other parts of the code to add clean functions for email send for Receipts and Invoice.

Also the emails sent notification is showing in the Receipt and Invoice views.

Takings is showing the invoice icon only if there is an invoice number set.
Receipt is shown always and I changed the glyphicon.

Both open the invoice or receipt view and one person can print or send email.

I hope you liked it, it has more features and looks handy now.

**Comment by jekkos** [comment]
OK sounds great! Resending email receipt after sale is definitely a nice addition. Will try to check it out tomorrow on the train to work.

**Comment by daN4cat** [comment]
Sales Controller should be refactored a bit more because there is a redundant code when loading data from Sale_lib to $data.
Probably it would be better to have a get_all in Sale_lib that loads everything in a $data array.
But I need to put together three functions code to make sure we get all is needed. I will think about that later.

**Comment by odiea** [comment]
It now appears that you are over riding the Use Invoice Template in Config. If so should you remove that option in Invoice Config?

**Comment by odiea** [comment]
Everything so far looks great. Thanks and keep up the great work.

**Comment by daN4cat** [comment]
Re Use Invoice Template is a good question, because I didn't get exactly how it used to work beside disabling the invoice feature in Sales register. I left there until we don't find really a need for that, but I need to check the code a bit more.

**Comment by daN4cat** [comment]
Removed Use Invoice Template in Store Config and across the code and database.

I no issues I can close this.

**Comment by RamkrishnaMondal** [comment]
Found no issue so far.

**Comment by daN4cat** [comment]
It seems all fine and so I close.
