### ISSUE TITLE
Sales->Returns oddity (release 2.3.2)

### ISSUE THREAD

**Issue by cruzades** [jekkos/opensourcepos#64]
This project is awesome. But for some reason, when selecting Sales->Register Mode->(Return), and double clicking on "Find/Scan Item OR Receipt" entry box, it doesn't display the list of my items, it does when in 'Sale' mode

**Comment by jekkos** [comment]
Is this a regression with respect to older versions?
Anyway there was already a similar issue with explanation in #54

**Comment by cruzades** [comment]
Hi, thanks for pointing me into sales.php..

here are what I did:
sales.php
line 66
	
	function item_search()
	{
		$suggestions = array();
		if ($this->sale_lib->get_mode() == 'Return') // change 'return' into 'Return'
		{
......

sales.php		
line 202
		if ($mode=='return') {
			$quantity = -1;
		} else {		
			$quantity = 1;
		} 
		//$quantity = ($mode=='return')? -1:1; // split this into long if statement
		$item_location = $this->sale_lib->get_sale_location();

		if($mode == 'Return' && $this->sale_lib->is_valid_receipt($item_id_or_number_or_item_kit_or_receipt)) // change 'return' into 'Return'
...

with this.. items are now showing upon double-clicking.. and how it is supposed to work how it should be working, though search tru invoice number is not, at least it worked as expected.

Regards,

**Comment by jekkos** [comment]
the mode value posted back is lowercase, so what this fix does it make return behave as it was sale mode.. the code will jump into another if-branch and you will probably end up with broken receipt number return functionality

**Comment by jekkos** [comment]
Fixed again in 46f6824199b6e2a8a707608c92ce5436561a290f
