### ISSUE TITLE
Barcode Auto Generate

### ISSUE THREAD

**Issue by likozhang** [jekkos/opensourcepos#640]
Barcode Content
Item Id/Name   UPC/EAN/ISBN   Generate if empty
if i check generate if empty, when generate barcode will show error location id

i think great if had fiture to add default code like 
x is set type definition to generate

Tshirt as x(TS) generate to TS01,TS02,TS03,TS(n) ...
Pants as x(PA) Generate to PA01,PA02,PA03, PA(n)...

thankyou sir... great job i hope you can add this fiture

and i was test printer fiture
dosent work at win 10, crome and mozilla or IE

**Comment by daN4cat** [comment]
Version?

**Comment by likozhang** [comment]
@daN4cat V 3.0

**Comment by likozhang** [comment]
![image](https://cloud.githubusercontent.com/assets/6987941/15993423/2d75acd2-3110-11e6-94c5-662cb359839d.png)
![image](https://cloud.githubusercontent.com/assets/6987941/15993433/5648e1f6-3110-11e6-973b-a8fe76af20cf.png)

**Comment by jekkos** [comment]
did you come from an older ospos version? Location_id field is definitely not present in ospos_items table so if this query is still in our current codebase than that might be a problem.

**Comment by jekkos** [comment]
This might be a bug indeed. in Items controller, 

check function generate_barcodes get_multple is called (which is a join over three tables) and this comment below

`// remove from item any suppliers table info to avoid save failure because of unknown fields
// WARNING: if suppliers table is changed this list needs to be upgraded, which makes the matter a bit tricky to maintain
`

**Comment by daN4cat** [comment]
I can reproduce this issue.

I'll have a loon into it.

**Comment by daN4cat** [comment]
I need to figure out a better way to do that save instead of unset fields.
I have something in mind to give a try.

**Comment by daN4cat** [comment]
Fixed

**Comment by likozhang** [comment]
okey, thankyou
i will test this fixed fiture

**Comment by likozhang** [comment]
![barcode error](https://cloud.githubusercontent.com/assets/6987941/16126151/2d3ff844-3421-11e6-9faf-5747a0a9714e.jpg)
![mass barcode error](https://cloud.githubusercontent.com/assets/6987941/16126152/2d42a0d0-3421-11e6-8b35-bd8e9972296e.jpg)

i get error again when choose multiple file to auto generate and when check UPC/EAN/ISBN  and Generate if empty at configuration - > barcode

if UPC/EAN/ISBN  empty at item product can add auto generate if empty?

**Comment by daN4cat** [comment]
I tested with multiple lines and it's fine.

**Comment by daN4cat** [comment]
OK, I see the issue....

**Comment by likozhang** [comment]
yeep, work well if check id and auto generate
error when check UPC/EAN

**Comment by daN4cat** [comment]
trying to remember what was the logic there for the case....

**Comment by likozhang** [comment]
public function generate_barcodes($item_ids)
	{
		$this->load->library('barcode_lib');

		$item_ids = explode(':', $item_ids);
		$result = $this->Item->get_multiple_info($item_ids, $this->item_lib->get_item_location())->result_array();
		$config = $this->barcode_lib->get_barcode_config();

		$data['barcode_config'] = $config;

		// check the list of items to see if any item_number field is empty
		foreach($result as &$item)
		{
			$item = $this->xss_clean($item);
			
			// update the UPC/EAN/ISBN field if empty / NULL with the newly generated barcode
			if(empty($item['item_number']) && $this->Appconfig->get('barcode_generate_if_empty'))
			{
				// get the newly generated barcode
				$barcode_instance = Barcode_lib::barcode_instance($item, $config);
				if($item['item_number']!=null){
					$item['item_number'] = $barcode_instance->getData();
				}
				else{
					$item['item_number'] = $item['item_id'];
				}

				
				$save_item = array('item_number' => $item['item_number']);

				// update the item in the database in order to save the UPC/EAN/ISBN field
				$this->Item->save($save_item, $item['item_id']);
			}
		}
		$data['items'] = $result;

		// display barcodes
		$this->load->view('barcodes/barcode_sheet', $data);
	}

**Comment by likozhang** [comment]
```
 if($item['item_number']!=null){
                $item['item_number'] = $barcode_instance->getData();
            }
            else{
                $item['item_number'] = $item['item_id'];
            }

```

i add to falidate if item_number null

**Comment by daN4cat** [comment]
Agreed, but that rule should be in the barcode_lib. I remember it was thought like that but don't get why is not working in that way.

**Comment by likozhang** [comment]
lol, i recomended add this function at auto generate `if($item['item_number']!=null){
					$item['item_number'] = $barcode_instance->getData();
				}
				else{
					$item['item_number'] = substr($item['name'],0,2).$item['item_id'];
				}`

**Comment by likozhang** [comment]
when i try this dont error, but this value is null for the default

**Comment by daN4cat** [comment]
I believe I fixed it. Try again with the latest master please.

**Comment by likozhang** [comment]
Thankyou... because isset -> !empty

**Comment by daN4cat** [comment]
Yes in php empty is not exactly the opposite of isset as it covers more cases.

**Comment by daN4cat** [comment]
BTW, thank you for the help with the testing. This was a bug left there for some time and good we now fixed :+1:
