### ISSUE TITLE
Upload image (max size) at NEW ITEM

### ISSUE THREAD

**Issue by likozhang** [jekkos/opensourcepos#643]
i add item, when image too large image upload failed ??
how **size** for image upload, and i hope you can give progress upload, so user can see how percentage the upload progress, dont want to unknown information

THANKYOU SIR (GOOD JOB)

**Comment by likozhang** [comment]
`private function _handle_image_upload()
	{
		$this->load->helper('directory');
		$map = directory_map('./uploads/item_pics/', 1);
		// load upload library
		$config = array('upload_path' => './uploads/item_pics/',
			'allowed_types' => 'gif|jpg|png',
			'max_size' => '100',
			'max_width' => '640',
			'max_height' => '480',
			'file_name' => sizeof($map) + 1
		);
		$this->load->library('upload', $config);
		$this->upload->do_upload('item_image');           
		
		return strlen($this->upload->display_errors()) == 0 || !strcmp($this->upload->display_errors(), '<p>'.$this->lang->line('upload_no_file_selected').'</p>');
	}`

i found this ???
max_size : 100 = 100kb ?

**Comment by likozhang** [comment]
can you add

**Comment by likozhang** [comment]
DONE

**Comment by daN4cat** [comment]
And the solution was to change 100 to a different number?

**Comment by likozhang** [comment]
i thnk to large is not good to, make product table runing slowly
maybe 1MB is best value max 3MB

**Comment by daN4cat** [comment]
1MB of picture for a small avatar sounds a lot.

**Comment by likozhang** [comment]
@daN4cat Accepted & reasonable
