### ISSUE TITLE
Sales Payment Type Order

### ISSUE THREAD

**Issue by likozhang** [jekkos/opensourcepos#646]
Can i set Payment Type Order (Cash at first) Debit Card second and Credit Card thrid 
thankyou master

**Comment by likozhang** [comment]
![image](https://cloud.githubusercontent.com/assets/6987941/16017346/96f4d494-31c9-11e6-9684-3e5629fb077e.png)

**Comment by daN4cat** [comment]
See `get_payment_options` in application/models/Sale.php:

> 		$payments = array(
> 			$this->lang->line('sales_debit') => $this->lang->line('sales_debit'),
> 			$this->lang->line('sales_credit') => $this->lang->line('sales_credit'),
> 			$this->lang->line('sales_cash') => $this->lang->line('sales_cash'),
> 			$this->lang->line('sales_check') => $this->lang->line('sales_check')
> 		);

change the order of the lines there

**Comment by likozhang** [comment]
Thank you very much

**Comment by daN4cat** [comment]
@likozhang wait, don't change I'm about to commit a change that allows the configuration of the payment order.

**Comment by onyema3** [comment]
Great!

**Comment by daN4cat** [comment]
Here we go, the payment options order is now available in Store Config localisation.

**Comment by likozhang** [comment]
@daN4cat fast and AMAZING 
THANKS A LOOTTT

**Comment by daN4cat** [comment]
It was asked before many times. I made it a simple fix. The best option would be to make the list of payment types completely configurable and extensible.
