### ISSUE TITLE
Email at Sales (i check send to email, and dont sent) 

### ISSUE THREAD

**Issue by likozhang** [jekkos/opensourcepos#647]
![image](https://cloud.githubusercontent.com/assets/6987941/16017841/eed20536-31cb-11e6-8cce-193e1854311e.png)
 
i check the email check
i dont get email ??, how to solve this mr

**Comment by RamkrishnaMondal** [comment]
It's a bug.

**Comment by likozhang** [comment]
@daN4cat

**Comment by likozhang** [comment]
@RamkrishnaMondal maybe have some little error

**Comment by daN4cat** [comment]
It works fine. Please check you email configuration set in your PHP.

**Comment by daN4cat** [comment]
Also please make sure you click complete and when in the receipt/invoice view you should get a notification bar with sent or not sent.

**Comment by likozhang** [comment]
@daN4cat sorry mr, you mean php in cpanel ?

**Comment by likozhang** [comment]
@RamkrishnaMondal what configuration, i hope i can solve this problem too

**Comment by daN4cat** [comment]
Check the open tickets, search a bit...

**Comment by daN4cat** [comment]
See #519

**Comment by HamidCh** [comment]
@likozhang how did you deployed it on cpanel?
Any addition work was done?
