### ISSUE TITLE
QUESTION (Sales Recipt for small printer for Cashier)

### ISSUE THREAD

**Issue by likozhang** [jekkos/opensourcepos#648]
![image](https://cloud.githubusercontent.com/assets/6987941/16018148/57f3fb68-31cd-11e6-87f1-7525aca36b8c.png)
https://images-na.ssl-images-amazon.com/images/I/41B1BI6zkdL._SX342_.jpg

the print out result line will be long or auto fit the page ?
who have the printout test

thank you...

**Comment by likozhang** [comment]
![image](https://cloud.githubusercontent.com/assets/6987941/16018289/1b0f454e-31ce-11e6-88f3-40c327618bc8.png)
i was try to set the print page margin 
i think this will work

**Comment by daN4cat** [comment]
Yes, that's the solution.
