### ISSUE TITLE
Export in file (*.css, *.xml, *.json ) of the tables does not work.

### ISSUE THREAD

**Issue by AdAvAn** [jekkos/opensourcepos#649]
_Linux: version 4.4.0-x86_64-linode63 (maker@build) (gcc version 4.7.2 (Debian 4.7.2-5) ) 
    Web Server: Apache/2.4.10 (Debian) + nginx/1.8.0 (front)
    Database name and version (. MySQL 5.5.44)
    PHP version ( PHP 5.6.20-0 )
    Language selected in OSPOS (English)_

I installed the latest version of the master, nothing happens when trying to export data tables in any of the available files.

Any idea why I can not export improved in agent?
Many thanks for any response.

**Comment by likozhang** [comment]
wich file u use to export ?

**Comment by AdAvAn** [comment]
I tried everything and they do not work

**Comment by likozhang** [comment]
![image](https://cloud.githubusercontent.com/assets/6987941/16061121/ace260fe-32b5-11e6-9272-e3964763db72.png)
try to download from template at hyperlink

**Comment by AdAvAn** [comment]
This screen imports OSPOS database, I want to export the contents of the table, as shown in my screenshot
![scr](https://cloud.githubusercontent.com/assets/13752342/16061469/bfbe2ec6-3295-11e6-92fd-63758e040aa8.jpg)

**Comment by likozhang** [comment]
lol, amazingly
try to rename download file to the end .csv
download(1)

add download(1).csv

i think @daN4cat this is oter type of bug ?

**Comment by likozhang** [comment]
https://github.com/jekkos/opensourcepos/issues?utf8=%E2%9C%93&q=export

i think this known as bug 
must be patient to wait v3.0

**Comment by RamkrishnaMondal** [comment]
Tested with latest master ...

Working on : Item Kits, Suppliers
Not-working on: Customers, Items, Sales Takings

**Comment by jekkos** [comment]
This is standard bootstrap tables functionality. Do you see any mesage in your error console (firebug or inspector?)

**Comment by RamkrishnaMondal** [comment]
@jekkos    After your commits export file working every where except items. Firebug shows this...
![screenshot from 2016-06-15 22 53 29](https://cloud.githubusercontent.com/assets/14151032/16090266/61ffe83a-334c-11e6-8331-2a2a7e303c60.png)

**Comment by jekkos** [comment]
Think this is an issue with the bstables plugin. Could you drop a db dump here so I can reproduce?

**Comment by daN4cat** [comment]
I confirm the issue, nothing happens if you select any of the export options.
I tried without selecting items and with items selected and nothing.

The console points to some js error:

opensourcepos.min.js?rel=70829b0891:33 Uncaught INVALID_CHARACTER_ERR: DOM Exception 5
c @ opensourcepos.min.js?rel=70829b0891:33
d @ opensourcepos.min.js?rel=70829b0891:33
tableExport @ opensourcepos.min.js?rel=70829b0891:36
c @ opensourcepos.min.js?rel=70829b0891:15
(anonymous function) @ opensourcepos.min.js?rel=70829b0891:15
dispatch @ opensourcepos.min.js?rel=70829b0891:4
q.handle @ opensourcepos.min.js?rel=70829b0891:4

**Comment by daN4cat** [comment]
People based ones and Giftcard works fine, by Item Kit doesn't work too with the same error.

**Comment by odiea** [comment]
It works for good for me. No errors showing on any of the exports.

**Comment by odiea** [comment]
Here is the error I get when I set pagination above 25.
![2016-06-17 05_29_11-new notification](https://cloud.githubusercontent.com/assets/10962177/16149296/1269e0d0-344d-11e6-874b-e2448c911818.png)

**Comment by jekkos** [comment]
Probably related to [this issue in bootstrap tables](https://github.com/wenzhixin/bootstrap-table/issues/189). Will need to change the base64 code to fix this

**Comment by daN4cat** [comment]
@jekkos it sounds that error indeed.

**Comment by jekkos** [comment]
I've added a new base64 dependency to fix this issue with utf-8. Can someone retest

**Comment by AdAvAn** [comment]
Yes, export error - fixed.
Thank you so much.

The only problem is, the downloaded file looks like this: "Unknown", the file name is not (* .css, * .xml, * .json). It would be much easier if the files have names: "Unknown.css" or "Unknown.xml" ...

**Comment by daN4cat** [comment]
It works in Customers, Suppliers, Employee, Giftcard but doesn't work in Items and Item kits.

I also agree about the file name, there is no name nor extension. It would be great to have the name of the controller and as extension the selected format.

**Comment by daN4cat** [comment]
I agree the anonymous file is not good.

It would be good to renamed it to the controller name and have as extension the selected file format.

**Comment by jekkos** [comment]
I don't know exactly if this can be handled without modifying the plugin itself... maybe create another issue or will we leave this one open? It's not really a bug afaik

**Comment by AdAvAn** [comment]
You're right, I'll create a new case. Error of this topic - closed.

Thank you
