### ISSUE TITLE
Gift Card Issue

### ISSUE THREAD

**Issue by odiea** [jekkos/opensourcepos#65]
Gift card auto increment is not working past the number 10. It stays on 10 after that value is reached. I also noticed after going into phpmyadmin and deleting the gift cards and starting over that the gift card number selected to edit shows the gift card_id in the Gift card edit screen and not the gift card number.

**Comment by jekkos** [comment]
Trying to write a selenium test to reproduce this issue. Stil have some work on the general setup of this thing but it might be beneficial to improve the project's quality for the future.

**Comment by jekkos** [comment]
Issue fixed in ca05583e
