### ISSUE TITLE
portuguese Brazil

### ISSUE THREAD

**Issue by arteiro** [jekkos/opensourcepos#650]
@daN4cat - last translation portuguese Brasil . 
[translations.zip](https://github.com/jekkos/opensourcepos/files/314021/translations.zip)

**Comment by jekkos** [comment]
Ok translations updated in latest master.

**Comment by daN4cat** [comment]
@arteiro  any chance you can look into the latest 3.0 and updated Brazilian translations?

**Comment by arteiro** [comment]
Ok I will do this today!

**Comment by daN4cat** [comment]
Wait, I'm adding something with translations. Let's do over the weekend.

**Comment by arteiro** [comment]
Okay. Now only have a fix in the file!
[receivings_lang.zip](https://github.com/jekkos/opensourcepos/files/329914/receivings_lang.zip)

**Comment by daN4cat** [comment]
OK, I can integrate that.

**Comment by arteiro** [comment]
OK, On Monday I see the files again and do. Hugs.

**Comment by daN4cat** [comment]
@arteiro take the latest master and add your translations. I've done with my code changes.

**Comment by daN4cat** [comment]
receiving_lang change is in master now

**Comment by arteiro** [comment]
Done, hugs.
[translations.zip](https://github.com/jekkos/opensourcepos/files/331976/translations.zip)

**Comment by daN4cat** [comment]
In master now.

**Comment by daN4cat** [comment]
@arterio I'm afraid there some more translations to sort out. Check the last commits to see which files.

**Comment by arteiro** [comment]
Ok @daN4cat

**Comment by arteiro** [comment]
@daN4cat , What does "Amazon" to you because I can not translate this word?

**Comment by arteiro** [comment]
Affected two files. Attachment
[translations.zip](https://github.com/jekkos/opensourcepos/files/333582/translations.zip)

**Comment by daN4cat** [comment]
Amazon is not used at all. It must be something left from some old stuff??
I don't know to be honest

**Comment by daN4cat** [comment]
OK, done and in master now.
