### ISSUE TITLE
Sale Type (Whole Sale & Retail)

### ISSUE THREAD

**Issue by likozhang** [jekkos/opensourcepos#653]
just a suggestion
what if there are additional Fiture for wholesale sales
in the case of scenario

store (retail and wholesale)
Pls sell items with a retail price of 100 to customer
whel sell items with price 80 to customer and min item is 3 or 2

![image](https://cloud.githubusercontent.com/assets/6987941/16061608/06c160f0-32b8-11e6-8f29-e589a225d317.png)

Sale Type :
[default Retail]
[Whole Sale]

**Comment by odiea** [comment]
You can do that now by giving your customer a percent discount.

**Comment by daN4cat** [comment]
Having complex rules to apply certain discount policies is not a trivial thing.

**Comment by sgr1875** [comment]
I too wish something like this or some thing like cost price billing. becos i have few friends we run super market when we exchange stock we bill each at cost price only.

**Comment by jekkos** [comment]
Think we kind of discussed this type of discount feature before. #375 #45 #261

**Comment by migosih** [comment]
hi @eatrisno  do you have the code /project folder that cointains the wholesale & retail.I'm unable to find it here.Thanks in advance.

**Comment by eatrisno** [comment]
Hi @migosih I believe this thread is outdated now, I hope that you found what you are looking for 
for the wholesale project, I end up using a percentage

**Comment by migosih** [comment]
@eatrisno   nope not yet or can you remember which release version had the price toggle as the one you displayed?
