### ISSUE TITLE
Hi Jekkos, I need some modification and customization of the OSPOS modules

### ISSUE THREAD

**Issue by feverfly** [jekkos/opensourcepos#656]
Hi Jekkos, I need some modification and customization for the OSPOS modules, Please discuss with me in the email for how much you would charge for the work. 
My Email address is feverfly_01@yahoo.com. Thank you @jekkos!

**Comment by jekkos** [comment]
Ok great, I will contact you on this email so we can discuss further.

**Comment by feverfly** [comment]
Hi Jekkos,
My name is Padraic, nice to meet you. I am a graphic designer and know a little bit PHP script and little MySQL knowledge. I am going to join a currency exchange shop as a partner. I have been looked for an open source system that could suite for my use and OSPOS functions are pretty much suitable for my usage. However, all of the POS systems were designing for retail business which good for selling products and services, therefore I asked your help to customize the functions with service charge. Attached please find the phase one modification requirement.

Regards,
Padraic 

    On Wednesday, June 15, 2016 10:41 PM, jekkos <notifications@github.com> wrote:
 

 Ok great, I will contact you on this email so we can discuss further.—

**Comment by eaace** [comment]
Hi Jekkos, invoices generated from sales in OSPOS display less digits in item view, but full totals are OK. Is there a way to modify this? Attached is a screenshot - the sales amounts on the far right should have 5 digits. Instead they are truncated.
![os_pos_invoice](https://user-images.githubusercontent.com/30861148/29485781-85adddaa-84e0-11e7-8748-50493ddb7f7d.jpg)

**Comment by andycole27** [comment]
jekkos i will like you to contact me on my email so that we discuss a project and how much you are going to charge

**Comment by andycole27** [comment]
my email is rtofaig@gmail.com
