### ISSUE TITLE
Notification at Send email Sale Receipt

### ISSUE THREAD

**Issue by likozhang** [jekkos/opensourcepos#658]
dont get notification when send email 
sended or eror ???

**Comment by daN4cat** [comment]
Version?

**Comment by likozhang** [comment]
lastest

**Comment by jekkos** [comment]
I have looked into this this morning, indeed the notification is not always shown but that can be due to a misconfiguration. Try to set the position in the config first explicitly. 

I will push a little rework of this later today.

**Comment by daN4cat** [comment]
@jekkos it's not shown in email sending case or it's that a general point? Not sure I get.

@likozhang also please make sure the email is configured properly, do you get the email and not the notification or none of the two?

**Comment by daN4cat** [comment]
Is this an issue in the end?

**Comment by jekkos** [comment]
@daN4cat I think the notification wasn't showing at first after clicking the send receipt button. Need to retest to see what was the actual cause there. I have some lcoal changes for this part will probably finish that tomorrow. I will use this issue as a reference.

**Comment by daN4cat** [comment]
The email send happens on receipt/invoice page load if enabled.
The notification is sent to the page itself so not sure it's a loading timing issue? But it should work fine. Anyway let me know what you found.

**Comment by jekkos** [comment]
have verified and seems to be working.. if not the reopen.
