### ISSUE TITLE
Receiving error from latest pull.

### ISSUE THREAD

**Issue by odiea** [jekkos/opensourcepos#659]
![2016-06-16 17_26_11-microsoft edge](https://cloud.githubusercontent.com/assets/10962177/16136429/91948b0a-33e7-11e6-9337-e6185bb8415a.png)

**Comment by odiea** [comment]
Something to do with the following line. Old line gives no error.
if(count($pieces) == 2 && preg_match('/(RECV|KIT)/', $pieces[1]);

**Comment by odiea** [comment]
if(count($pieces) == 2 && preg_match ('/(RECV|KIT)/' , $pieces[1])) works if it looks like this.

**Comment by odiea** [comment]
Return on item kits is also working properly now. Showing all items in the kit with no errors.

**Comment by gfxgee** [comment]
:+1:  nice bro, thanks

**Comment by jekkos** [comment]
Ok pushed that change a little too fast. Should be good now in latest.

**Comment by odiea** [comment]
I do not see any current commits about this issue. Receiving_lib looks the same.

**Comment by jekkos** [comment]
Should be done now, my push failed as I had some github issues.
