### ISSUE TITLE
 Undefined property: stdClass::$category Filename: items/form.php Line Number: 38

### ISSUE THREAD

**Issue by whispers16** [jekkos/opensourcepos#66]
I'm trying to submit a product, but firstable it shows me a php error that says:
Undefined property: stdClass::$category
Filename: items/form.php
Line Number: 38

second: even though it shows that problem, I can fill out the fields, but I can't submit the form, It actually verifies the fields (if I did't complete it properlly ) but It doesn't allow me to submit it.

Can you help mee! please!

**Comment by d0n601** [comment]
I'm getting the same issue on a fresh installation

**Comment by odiea** [comment]
What Version are you using? I just downloaded the one from ospos 2.3.1 Installed a new database and had no problems adding a new item in Add Item. If you are updating your older version did you use the database update?

**Comment by jekkos** [comment]
Yeah the category column was accidentaly removed from the database.sql script, I added it back again in b2a37b7d.

**Comment by odiea** [comment]
If you would like to try out the most current version it is at https://github.com/jekkos/opensourcepos. The only bug I have found is Gift card auto incrementing will not go past 10 so you have to add a number each time. The author is working on that problem.

**Comment by whispers16** [comment]
Perfect, I added the column to the db and  that worked for me! thank you!
