### ISSUE TITLE
action after deleteing item in item product

### ISSUE THREAD

**Issue by likozhang** [jekkos/opensourcepos#661]
i get notification sucessfull deleteing item
and at table show no item 

and after refresh the page ????

**Comment by daN4cat** [comment]
It works fine, not sure what the problem is that you are trying to point out here.

Please clarify the scenario and issue.

**Comment by likozhang** [comment]
case : restore deleted item from item product, select 2 or more product in filter deleted
and press delete button ,

when i want to undelete a product, i must open the product and check the delete product check box

 i think this button must be restore or, undelete ???

**Comment by likozhang** [comment]
![snapshot_2016-6-18_17-33-37](https://cloud.githubusercontent.com/assets/6987941/16170386/27c14106-357b-11e6-80c0-672d34376aea.jpg)
![snapshot_2016-6-18_17-35-14](https://cloud.githubusercontent.com/assets/6987941/16170387/27c2fd7a-357b-11e6-9c82-94e28942c0bb.jpg)
![snapshot_2016-6-18_17-35-36](https://cloud.githubusercontent.com/assets/6987941/16170388/27c346d6-357b-11e6-9f6d-9f8c33ff3a5c.jpg)


i hope you understand

**Comment by likozhang** [comment]
my lecture said, try milion error test, also try client data test ,lol

**Comment by daN4cat** [comment]
Are you sure you have taken all the latest code from master including the files that are in dist?

That issue was fixed a couple of days ago, see #627

**Comment by likozhang** [comment]
owh, this code at 17/06
i will close this issue, thankyou

**Comment by likozhang** [comment]
i will test again, hopefully work :+1:

**Comment by odiea** [comment]
I just tested in current version and the issue is there. Appears to be no is deleted filter.

**Comment by likozhang** [comment]
@daN4cat its work, great..

**Comment by daN4cat** [comment]
@odiea I don't get the scenario. I tried adding is deleted in filters and then go to last page, select all and deleted again and the page is refreshed.

Was that the test case?

If that doesn't work for you please make sure you have the latest dist/ files

**Comment by odiea** [comment]
The test I was doing was go to Items- delete an item-Item is deleted and filter for Items shows that Item number being deleted. Now go to Sales  and Enter the deleted Item id and In sales the Item shows on the Register. It seems like if it is deleted the Item should not be available for sale.

**Comment by daN4cat** [comment]
OK, that's what I just fixed in #664. Please check that issue and my fix.

**Comment by odiea** [comment]
@daN4cat  Yes this is fixed now. Keep up the good work.
