### ISSUE TITLE
Sales register allowing adding a deleted product by Item Id

### ISSUE THREAD

**Issue by likozhang** [jekkos/opensourcepos#664]
try to delete item in ITEM product with id 1

go to sale, and add item with id 1

congrats,

**Comment by likozhang** [comment]
maybe, give notification this is deleted item, you still can bla bla bla

**Comment by daN4cat** [comment]
If you deleted you deleted and don't want to get hundred of notifications/possibilities popping up.

I would not change it is at the moment also because once you deleted the quantity is 0.

**Comment by likozhang** [comment]
no, i will give you use case, i think u dont understand what i mean

**Comment by likozhang** [comment]
![snapshot_2016-6-18_17-33-37](https://cloud.githubusercontent.com/assets/6987941/16170437/ec8c8ddc-357c-11e6-82bf-2843fa3cb2cc.jpg)
![snapshot_2016-6-18_17-35-14](https://cloud.githubusercontent.com/assets/6987941/16170438/ec8cc3ba-357c-11e6-9f15-718f5ada2f43.jpg)
![snapshot_2016-6-18_17-35-36](https://cloud.githubusercontent.com/assets/6987941/16170439/ec8cfca4-357c-11e6-954b-b01946182d44.jpg)
![snapshot_2016-6-18_17-42-29](https://cloud.githubusercontent.com/assets/6987941/16170440/ec916f14-357c-11e6-9497-7449be73e733.jpg)
![snapshot_2016-6-18_17-43-14](https://cloud.githubusercontent.com/assets/6987941/16170441/ec92fe9c-357c-11e6-85cc-ee72b0a1a929.jpg)
![snapshot_2016-6-18_17-44-15](https://cloud.githubusercontent.com/assets/6987941/16170442/ec948b54-357c-11e6-817d-c6ac5c35565b.jpg)
![snapshot_2016-6-18_17-46-11](https://cloud.githubusercontent.com/assets/6987941/16170444/ecb9adf8-357c-11e6-8cec-7c2a8f5b5a4b.jpg)
![snapshot_2016-6-18_17-46-58](https://cloud.githubusercontent.com/assets/6987941/16170446/ecba8020-357c-11e6-9522-62e94f94d465.jpg)
![snapshot_2016-6-18_17-48-11](https://cloud.githubusercontent.com/assets/6987941/16170445/ecb9dd5a-357c-11e6-8d9a-0a66cff6d8ba.jpg)

**Comment by daN4cat** [comment]
OK, that's not correct.

**Comment by likozhang** [comment]
i had another eror

**Comment by daN4cat** [comment]
OK, but that happens only with the item id not using the barcode

**Comment by likozhang** [comment]
can you set id sugest like search product name ? so this error can be fixed ?

product name will show when product not deleted ?

**Comment by daN4cat** [comment]
This is fixed and in master now.

Please test a bit and confirm we can close. Thanks for spotting this out, good testing :+1:

**Comment by daN4cat** [comment]
I close this based on #661 testing feedback.
