### ISSUE TITLE
Barcode in ITEM KIT

### ISSUE THREAD

**Issue by likozhang** [jekkos/opensourcepos#665]
Case : Scan barcode from ITEM KIT, barcode item kit, generate by ID
ID = 1 (Packet (item B,item C))

Item product ID = 1 (item A)

goto Sale , scan id = 1
item add = item product with id 1

how to fix this ?

sugest, : Code Packet using Alphabet  P1

**Comment by daN4cat** [comment]
Thanks for the test and use case report, it sounds a good one to be analysed.

**Comment by likozhang** [comment]
yeep, barcode scanner will work only for item product, dosent work for item kit

**Comment by daN4cat** [comment]
The Items kit never got too much attention, I improved a bit a while ago but in recent time people asked for more.

We collect all the input first and then see what to do.

**Comment by jekkos** [comment]
Yes maybe add it to the list, no problem is someone else wants to improve this, I don't really use it.

**Comment by jekkos** [comment]
Ok no this is actually a regression. In previous versoins item kit barcodes were generated as KIT+id. After bstables upgrade this has become just the regular id which clashes with items.

**Comment by odiea** [comment]
In application/controllers/item_kits . Replace old result with new result. Works for me. I jut updated the code with the missing parts of the old code.

public function generate_barcodes($item_kit_ids)
$result[] = array('name' => $item_kit->name, 'item_id' => urldecode('KIT '.$item_kid_id), 'item_number' => urldecode('KIT '.$item_kid_id),
							'cost_price' => $item_kit->total_cost_price, 'unit_price' => $item_kit->total_unit_price);

**Comment by jekkos** [comment]
@odiea Ok thanks for the workaronud. Think your solution is better indeed. Gonna adapt my fix to revert to what you suggest here.

**Comment by daN4cat** [comment]
Fixed the typos.

**Comment by Alaa-23** [comment]
What if I want to add items kit's barcode from my own, not the OSPOS generated one?
