### ISSUE TITLE
Question ? Error ? Sale Item with id

### ISSUE THREAD

**Issue by likozhang** [jekkos/opensourcepos#666]
i dont know this known or not before.

Case :
$id = your item id (1 in my case);

go to sales, add your item with id = $id;

in my case , i add item with id 1 and press enter

1 item in cart...

and than add item with id 1a enter
and than add item with id 1[space] enter
add item with id 1xaojdoasjdopsaj enter

congrats,, your item 4 kind with 1 id 1name

Bug ?

**Comment by daN4cat** [comment]
Good one, indeed adding a trailer to the item id number causes that.
The point here is: is it an error or better user experience because any mistype is ignored?

@jekkos @odiea what do you think about this?

**Comment by daN4cat** [comment]
@likozhang many thanks for all this thorough testing, very good :+1: well done!

@odiea you found a buddy to help you.

**Comment by odiea** [comment]
@daN4cat  Yes I have and he is doing a much better job then I have done recently. @likozhang  Thanks for the help and keep up the good work.

**Comment by jekkos** [comment]
Ok it's a sort of undefined behavior. It might be misleading if someone eg mistypes a number then mistakenly another item could be added to the register. Might be better to throw an exception in case there's no exact match?

**Comment by daN4cat** [comment]
To be honest, about this I don't have a bit issue with the extra bits.
What should we do?

@jekkos do you want to look into this or we deprioritise?

**Comment by jekkos** [comment]
It's not really an urgent one I agree, more cosmetic so ok to deprioritize. I might look into it eventually..

**Comment by jekkos** [comment]
Problem exists due to a bug (or feature?) in MySQL. Issued query is following

`SELECT *
FROM `ospos_items`
WHERE `item_id` = '2c'
AND `deleted` =0`

which shouldn't give any result but MySQL strips away the character behind the 2 whiich does lead to [some rows in the resultset.](http://stackoverflow.com/questions/15715719/why-does-mysql-return-rows-that-seemingly-do-not-match-the-where-clause)

**Comment by jekkos** [comment]
Should be fixed now. Replaced the where clause in this query with a like which compares both fields as strings and prevents dropping invalid character

**Comment by odiea** [comment]
This is not working well. Before this I could enter a item id manually and it would work. Now that doesn't work. I get the unable to add item to sale. It appears to be a hit and miss now. Some work and others don't even when I use the dropdown list some do not work now.

**Comment by daN4cat** [comment]
I put a comment on the change, I'm convinced the LIKE is correct as it will give a lot of false positives.

I would revert this for the time being as it's not a critical issue.

**Comment by odiea** [comment]
I reversed this commit  and all is working back to normal.

**Comment by onyema3** [comment]
Is it in masters?

**Comment by odiea** [comment]
No it is in my version on my server. You may wait and see if jekkos reverses it or just look at the commit and change it on the one you are using.

**Comment by onyema3** [comment]
@odiea  Thanks

**Comment by odiea** [comment]
@onyema3  Were you having similar issues with this last commit with Items in the Sales Register?

**Comment by onyema3** [comment]
Yes but not all the time

**Comment by jekkos** [comment]
Ok no idea why it does not work correctly. I changed the like clause with `		$this->db->where('CAST(item_id AS CHAR) = ', $item_id);`and now don't seem to find any obvious problems searching items. @odiea could you give that a try (change the like clause at line 10 in Item.php model with this one and see if it works for you?)

**Comment by jekkos** [comment]
If it doesn't then I'll revert otherwise we might stick to that latter solution

**Comment by odiea** [comment]
$this->db->where('CAST(item_id AS CHAR) = ', $item_id); appears to be back to normal.

**Comment by daN4cat** [comment]
Applied the suggested fix and in master.
I couldn't test it so countercheck to make sure it's all fine with different search criteria (even adding an extra char at the beginning or/and end of the searched/scanned item).

**Comment by freemail624** [comment]
You can test this one, It works good with me

    `public function exists($item_id, $ignore_deleted = FALSE, $deleted = FALSE)
	{
		if(is_numeric($item_id)){
			$this->db->from('items');
			$this->db->where('item_id', $item_id);
			if($ignore_deleted == FALSE)
			{
				$this->db->where('deleted', $deleted);
			}
			return ($this->db->get()->num_rows() == 1);
		}
		return false;
	}`

**Comment by jekkos** [comment]
is numeric check could be a solution as well, might be a bit cleaner indeed?

**Comment by odiea** [comment]
I tried with the first example in this issue and now I get "cannot add item to sale". If I use just the item_id it works properly.

**Comment by daN4cat** [comment]
This seems to work to me. I close.
