### ISSUE TITLE
index.php/sales/manage Search & Time filter

### ISSUE THREAD

**Issue by likozhang** [jekkos/opensourcepos#667]
![snapshot_2016-6-18_18-11-14](https://cloud.githubusercontent.com/assets/6987941/16170549/ccca4b84-3580-11e6-98a0-bde73590bb7a.jpg)
![snapshot_2016-6-18_18-13-47](https://cloud.githubusercontent.com/assets/6987941/16170550/cccecc36-3580-11e6-96b1-54f82671137f.jpg)
![snapshot_2016-6-18_18-15-53](https://cloud.githubusercontent.com/assets/6987941/16170551/ccd1f140-3580-11e6-86c4-6bc43b94b763.jpg)

**Comment by likozhang** [comment]
https://github.com/jekkos/opensourcepos/issues/654 search for customer name

**Comment by daN4cat** [comment]
@jekkos probably this goes indeed together with #654 that does weird things

**Comment by likozhang** [comment]
https://github.com/jekkos/opensourcepos/pull/669
i'm try to fix this,

**Comment by daN4cat** [comment]
OK, I looked into this better and it's not strictly related to bstable.

The point is that it was a design decision to make it by date or by search box. Probably date range needs to be always part of the search criteria.

**Comment by likozhang** [comment]
yeep, add filter in search condition, and counting the total at footer

**Comment by daN4cat** [comment]
This is now fixed and I applied the same logic to Items.

I'll close later if all fine.

**Comment by odiea** [comment]
Date picker only.

![2016-06-19 05_08_57-new notification](https://cloud.githubusercontent.com/assets/10962177/16176971/31bd95f4-35dc-11e6-844b-884369a0c5d6.png)

Search Box with last name

![2016-06-19 05_09_39-ugly sweater store -- powered by os point of sale](https://cloud.githubusercontent.com/assets/10962177/16176972/391c678a-35dc-11e6-98ef-09be3a5d54d2.png)

Search box with last name removed

![2016-06-19 05_10_09-ugly sweater store -- powered by os point of sale](https://cloud.githubusercontent.com/assets/10962177/16176973/3ebb2ab4-35dc-11e6-8ab6-913d522bacbd.png)

After this Takings has to be reloaded for anything else to show. My last pull was 11 minutes ago.

**Comment by daN4cat** [comment]
Yes, but that's #654 issue.

**Comment by daN4cat** [comment]
This one is fixed, the Takings issue with customer name is a different matter.
