### ISSUE TITLE
Sales

### ISSUE THREAD

**Issue by lrsilvatcf** [jekkos/opensourcepos#67]
Hello,
We are just starting to use your POS for our inventory and sales management. We LOVE everything you currently have and really want to roll this out for full use with our employees. We are a security camera company that sells and leases our cameras out.

I have a couple of requests and would like to donate to aid to their completion:

1. In your sales, can you have Estimate, Sales, and Return (i.e. for customer estimates that we can then go back, edit if necessary, and then change to a sale once its made?) For reporting have these estimates show up under the customers, so we know who has had a quote and we can complete sale by meeting up with customer again.

I think as of now, we can utilize the sale and return function for our leased equipment. But i have a problem with my returns. I have reduced the description of the item as it was previously giving me an error when I completed a sale, but when I tried to return the item, it would not let me edit and complete the transaction as it gave me the error that it was too long again.
http://tcf-s.com/stk/index.php/sales/edit_item/1
 
2.Can you filter by Category in Sales to a customer? We have to have each of our categories filled in our excel sheet, i.e. NVR, CAMERA, HARDWARE, SOFTWARE before completing to customer. Is there a way to populate the categories so we know we have items from each selection?

**Comment by lrsilvatcf** [comment]
This is the error message I receive when I try to return the item:
Error Number: 1265

Data truncated for column 'item_id' at row 1

INSERT INTO `ospos_sales_items` (`sale_id`, `item_id`, `line`, `description`, `serialnumber`, `quantity_purchased`, `discount_percent`, `item_cost_price`, `item_unit_price`, `item_location`) VALUES (23, '05/05/2015', 1, 'DAHUA 2MP 30X OPTICAL ZOOM, 1080P, BUILT-IN 100M IR NETWORK IP CAMERA - 24V - OEM\r\n', '', '-1', '0', '769.00', '769.00', '2')

Filename: C:\inetpub\wwwroot\stk\system\database\DB_driver.php

Line Number: 330

**Comment by odiea** [comment]
Item_id is an auto incrementing numeric field to keep track of the items that are entered. You might want to pick another field to put that into like custom 1

**Comment by lrsilvatcf** [comment]
I did what you said as of now, as I think after messing with inventory I may have screwed that up. I am hoping this error is fixed. Testing it now since I cleared.

**Comment by lrsilvatcf** [comment]
This is what I am hoping to add for Categories in Sales portion: Hope this helps as we want to get away from our excel asap!!!!!!!!!!!!

![excel](https://cloud.githubusercontent.com/assets/12257148/7486013/d201457c-f363-11e4-9c14-02639e12bfa9.png)
![sales](https://cloud.githubusercontent.com/assets/12257148/7486012/d2000f86-f363-11e4-847a-de083667974f.png)

**Comment by jekkos** [comment]
So you would like to have some kind of category dropdown that does some prefiltering on the item search query? Is this request comparable with issue #69 ?

**Comment by lrsilvatcf** [comment]
Sir,
 I believe it could be the same as #69, As our excel, we can see each Category. NVR, CAMERAS, CAMERA MOUNTS, HARDWARE, SOFTWARE etc. we will have all of our items in within our categories, but how its set up here in the excel. We can correlate as we can see the categories and know we have everything.

**Comment by lrsilvatcf** [comment]
I would like to donate for this, an estimate query, and the new issue I opened up. Please let me know possible turn around time and/or acceptable payment method.

**Comment by jekkos** [comment]
Mostly I handle donations through paypal. Can you give me your mail address so we can continue conversation there?

**Comment by lrsilvatcf** [comment]
lrsilva@tcf-s.com
