### ISSUE TITLE
Undeleting an Item from Item Update

### ISSUE THREAD

**Issue by odiea** [jekkos/opensourcepos#672]
I am able to delete an Item in Item update but when I go back to remove the check mark in Item update nothing happens. The check mark remains there.

**Comment by odiea** [comment]
It now appears nothing can be updated when you select deleted filter then try to edit an item.

**Comment by odiea** [comment]
There is something in the new code it does not like. When I remove  $deleted = FALSE and comment out //$this->db->where('deleted', $deleted); Update works properly again.

public function exists($item_id, $deleted = FALSE)
	{
		$this->db->from('items');
		$this->db->where('item_id', $item_id);
		$this->db->where('deleted', $deleted);

		return ($this->db->get()->num_rows() == 1);
	}

**Comment by daN4cat** [comment]
Ok, I'll have a look. Thanks for the issue report.

**Comment by daN4cat** [comment]
Fixed. If fine I'll close this issue it later.

**Comment by odiea** [comment]
Now in normal Items view, no filters, no items will update. A tough nut to crack?

**Comment by daN4cat** [comment]
I don't get, what is the issue?

**Comment by odiea** [comment]
Now in normal Items view, no filters, # **no items will update**.  Go to Items. Select Update. Update an Item.  Nothing happens is the issue. Is there a way to call the original code from Items 
public function exists($item_id)
	{
		$this->db->from('items');
		$this->db->where('item_id', $item_id);
		
		return ($this->db->get()->num_rows() == 1);
	}
and have sales call the new code
public function exists($item_id, $deleted = FALSE)
	{
		$this->db->from('items');
		$this->db->where('item_id', $item_id);
		$this->db->where('deleted', $deleted);

		return ($this->db->get()->num_rows() == 1);
	}

**Comment by daN4cat** [comment]
OK, got the problem. Silly me I made it changeable only if deleted....

**Comment by daN4cat** [comment]
OK, this time should be fine. A bit of a sleepy Sunday....

**Comment by odiea** [comment]
Works Great now. I give you permission to take the rest of the day off. Happy Fathers Day if you are one.

**Comment by daN4cat** [comment]
Good, I close then.

Yes I'm, 7 year old boy.
