### ISSUE TITLE
Ench : Control Key

### ISSUE THREAD

**Issue by likozhang** [jekkos/opensourcepos#675]
can php in CI using control key ?
ex: press 1 to sale, 2 to item, and another ?

i think this idea will make code to complex

**Comment by sgr1875** [comment]
it was there from 3.0.0 disabled :( i wish i get it back

**Comment by daN4cat** [comment]
It has nothing to do with PHP and CI, it's a javascript thing on the front end part.

Anyway this was discussed, search the database of issues.
