### ISSUE TITLE
deleted table at sales

### ISSUE THREAD

**Issue by likozhang** [jekkos/opensourcepos#677]
index.php/sales/manage
how if staff delete the table, admin want to see, what item will be deleted

**Comment by daN4cat** [comment]
You cannot delete a db table.

If you refer to bulk delete then you can always add a log of the delete action in the inventory so you know who did what like when you add an item, change and item and etc.
It would be probably a nice addition to show in the item log that action.

**Comment by odiea** [comment]
I think he wants to know how to locate a deleted sales after someone deletes it in Takings.

**Comment by daN4cat** [comment]
Indeed, it's sales not items...

**Comment by likozhang** [comment]
lol you know what i mean, thanks
can you help me show item filter deleted item like at item?

**Comment by onyema3** [comment]
How can one locate a deleted sale after it is deleted from takings??

**Comment by odiea** [comment]
Currently the Sale is no longer in the database. So I believe there is no way to view or restore the Sale at the moment.

**Comment by likozhang** [comment]
@odiea you mean if staff do delete acton at takings
admin dont know what to do next ?

**Comment by daN4cat** [comment]
sales are completely wiped from database, so when they are gone they are gone.

Probably we should adopt a deleted field as for the rest and never really remove a sale, which would make more sense to me.

**Comment by onyema3** [comment]
I agree

**Comment by daN4cat** [comment]
I close this as duplicate of #682.
