### ISSUE TITLE
Sales register right panel bottom part not showing correctly

### ISSUE THREAD

**Issue by daN4cat** [jekkos/opensourcepos#680]
The right panel in register on the bottom part is not showing anymore as it used to be.
Please fix it, see part in red rectangle.

![image](https://cloud.githubusercontent.com/assets/636048/16210948/a3ae1822-3736-11e6-9bc7-fa956cc04f5b.png)

**Comment by jekkos** [comment]
What you mean exactly with not showing correctly? All the checbkoxes are there? Only thing I did is use bootstrap grid (and no html tables) for the layout and input addon to show the invoice number.

**Comment by jekkos** [comment]
![screenshot from 2016-06-21 08 10 57](https://cloud.githubusercontent.com/assets/576234/16219591/bdc3f7d0-3787-11e6-998b-50fecd4732d6.png)

**Comment by jekkos** [comment]
This is how it looked first.. One can only use invoice number field if the other checkbox is enable so those two kind of belong together (that's why I omit the label to save some space)

**Comment by jekkos** [comment]
OK I agree there's more padding to the edges and it's not aligned to the box above, will have a look there

**Comment by daN4cat** [comment]
Yes, I meant the padding indeed. The rest is fine.

Thanks.

**Comment by daN4cat** [comment]
I'm afraid the padding is still not right....

![image](https://cloud.githubusercontent.com/assets/636048/16222267/1f1ffc66-378f-11e6-9b4c-6687a8de5fbc.png)

**Comment by jekkos** [comment]
![screenshot from 2016-06-21 16 27 27](https://cloud.githubusercontent.com/assets/576234/16233010/2209aaa6-37cd-11e6-9fa9-3922934a0308.png)
Looks all good now.

**Comment by daN4cat** [comment]
Is that after a new commit?

**Comment by daN4cat** [comment]
Yes, it's fine. I close
