### ISSUE TITLE
Q: database relation / diagram ?

### ISSUE THREAD

**Issue by gfxgee** [jekkos/opensourcepos#681]
is there any sir? thanks :+1:

**Comment by daN4cat** [comment]
If you produced one please send it over so we add it to the wiki

**Comment by gfxgee** [comment]
lol . this what i got base from the database provided :laughing: it so messy :sob: i dont know how to arrange it 

![schema](https://cloud.githubusercontent.com/assets/8316409/16223470/f5bbb996-37cf-11e6-9c49-8cc11bea8820.png)

**Comment by daN4cat** [comment]
Well, it's people, items and transactions (sale or receiving).
See if reasoning around those three topic you can organise it better.

**Comment by gfxgee** [comment]
still , idk how it looks, looks better i think , haha thanks for your topic sir
![schema 2](https://cloud.githubusercontent.com/assets/8316409/16226080/61682fc4-37dc-11e6-9f41-6311a0470c4c.png)

**Comment by daN4cat** [comment]
Looks goo, well done. I forgot that there is a Location concept too.

BTW permissions & grants should be more second level after people.
