### ISSUE TITLE
bstables: some tables and fields are not updated on change

### ISSUE THREAD

**Issue by daN4cat** [jekkos/opensourcepos#683]
**Suppliers**

- edit a row and change in the form Company name or Agency, Submit and the fields are not updated

**Detailed Receivings Report**

- edit a row and change any parameter, Submit and the row is not updated

**Comment by onyema3** [comment]
@daN4cat it updates you have to leave Suppliers and come back before you
see the updated field

**Comment by daN4cat** [comment]
The table row should update, try to change the phone number for instance and see what happens.

**Comment by onyema3** [comment]
It updates on my setup

**Comment by onyema3** [comment]
Its only the Agency Name that doesn't update instantly

**Comment by odiea** [comment]
On my setup company name or agency name do not update the row. Phone and name work ok.

**Comment by odiea** [comment]
It shows after a manual refresh.

**Comment by daN4cat** [comment]
I might know why, Receivings and Suppliers Controllers are missing get_row, or not using the right one.

I'll check and fix it after dinner time.

**Comment by daN4cat** [comment]
Fixed. I close if confirmed ok.

**Comment by odiea** [comment]
Yes. The rows now update immediately. Thanks

**Comment by onyema3** [comment]
Working very well now
