### ISSUE TITLE
BUG: Sales

### ISSUE THREAD

**Issue by likozhang** [jekkos/opensourcepos#686]
use laster program, search item with name apple
search in ITEM, or ITEM KIT
where this data come from ?

**Comment by daN4cat** [comment]
Sorry this test scenario is too vague, please explain it better.

**Comment by odiea** [comment]
I am having no issues here. I type in a known name and it appears. I type in un unknown name and it shows nothing.

**Comment by likozhang** [comment]
![snapshot_2016-6-23_6-4-53](https://cloud.githubusercontent.com/assets/6987941/16286717/73ce75f6-3908-11e6-9dd0-7f85550614ba.jpg)
![snapshot_2016-6-23_6-3-23](https://cloud.githubusercontent.com/assets/6987941/16286715/73cd74ee-3908-11e6-97de-0e5649d39083.jpg)
![snapshot_2016-6-23_6-3-44](https://cloud.githubusercontent.com/assets/6987941/16286714/73cc9128-3908-11e6-8bdd-305af8e9c082.jpg)
![snapshot_2016-6-23_6-4-32](https://cloud.githubusercontent.com/assets/6987941/16286716/73ce2bdc-3908-11e6-8d0b-0661743dc361.jpg)

in case : Staff delete the transaction after customer buy an item
this transaction will be deleted too from report

**Comment by daN4cat** [comment]
We talked about this in #677

**Comment by daN4cat** [comment]
The only bug I see is writing that 2 sales were deleted instead of 1.

**Comment by daN4cat** [comment]
Besides the bug of showing 2 instead of 1 the rest of the discussion is now in #682.

**Comment by daN4cat** [comment]
I checked the Sales Controller and there a simple count() of passed item_ids.
So this issue originates from bstables and what's passed. It's probably counting the first row too, which is the titles one.

**Comment by daN4cat** [comment]
BTW, I also noticed that once 1 sale is deleted the summary stays with the old total instead of being 0.

**Comment by daN4cat** [comment]
@jekkos if you review the Item delete, could you check this issue of the wrong count too?

**Comment by jekkos** [comment]
Will check tomorrow

**Comment by jekkos** [comment]
Ok did a fix for this one, row count should be equal to the actual number of selected rows.

**Comment by jekkos** [comment]
Ok I close
