### ISSUE TITLE
Import items in UTF-8 encoding

### ISSUE THREAD

**Issue by AdAvAn** [jekkos/opensourcepos#687]
After the import of the items with *.csv file, names in UTF-8 as "Кеды синие" transformed on "______ ____".

**Server config:**
```
Linux: version 4.4.0-x86_64-linode63 (maker@build) (gcc version 4.7.2 (Debian 4.7.2-5) ) 
Web Server: Apache/2.4.10 (Debian) + nginx/1.8.0 (front)
Database name and version (MySQL 5.5.44)
PHP version ( PHP 5.6.20-0 )
Language selected in OSPOS (English)
```

<img width="560" alt="screen shot 2016-06-21 at 22 25 53" src="https://cloud.githubusercontent.com/assets/13752342/16243626/d59acd38-3800-11e6-84ed-6163bac3f4b1.png">

<img width="1218" alt="screen shot 2016-06-21 at 22 26 08" src="https://cloud.githubusercontent.com/assets/13752342/16243629/db2d57ca-3800-11e6-96c3-6970c029fbc1.png">

**Comment by daN4cat** [comment]
@AdAvAn you get that only with cvs import, right? It's to understand what to check.

**Comment by AdAvAn** [comment]
Yes, it is true only of the * .csv file. If you enter via interface is working correctly.

<img width="592" alt="screen shot 2016-06-21 at 23 01 15" src="https://cloud.githubusercontent.com/assets/13752342/16244453/bd03d7c0-3804-11e6-9bbc-0cea9c6a519a.png">

**Comment by daN4cat** [comment]
The import function uses fgetcsv and there is a note in the manual: http://php.net/manual/en/function.fgetcsv.php

> Note:
> Locale setting is taken into account by this function. If LANG is e.g. en_US.UTF-8, files in one-byte encoding are read wrong by this function.

Another comment:

> Note that fgetcsv() uses the system locale setting to make assumptions about character encoding.
> So if you are trying to process a UTF-8 CSV file on an EUC-JP server (for example),
> you will need to do something like this before you call fgetcsv():
> setlocale(LC_ALL, 'ja_JP.UTF8');

So I would check first what your system locale settings are.
Otherwise we need to force setting a locale according to the selected language but I would prefer to leave to your environment setting if possible.

**Comment by jekkos** [comment]
Cant this locale be set in php.ini?

**Comment by daN4cat** [comment]
.htaccess , see http://stackoverflow.com/a/5075654/6176637

**Comment by daN4cat** [comment]
otherwise we would need to add in the import functions something like: `setlocale(LC_ALL, 'nl_NL');`

**Comment by daN4cat** [comment]
But there are issues:

> Warning
> The locale information is maintained per process, not per thread. If you are running PHP on a multithreaded server API like IIS, HHVM or Apache on Windows, you may experience sudden changes in locale settings while a script is running, though the script itself never called setlocale(). This happens due to other scripts running in different threads of the same process at the same time, changing the process-wide locale using setlocale().

**Comment by AdAvAn** [comment]
I tried to add  `SetEnv   LC_ALL  it_IT.UTF-8` at .htaccess, but this solution worked for me.

**Comment by daN4cat** [comment]
You need to select your correct language not `it_IT` because that's Italian.

**Comment by daN4cat** [comment]
If it's Russian set `ru_RU.UTF-8`

**Comment by AdAvAn** [comment]
Oh, of course, it is necessary to enter `ru_RU.UTF-8`, I'm sorry.
OK, I checked indicating `ru_RU.UTF-8`, the import fails.

**Comment by daN4cat** [comment]
Fails means exactly....

**Comment by AdAvAn** [comment]
OK, I checked again and found the following error: on my server is not installed localization _"**ru_RU.utf8**"_, this can be verified: _"#locale -a"_.
Localization can be set: _"# dpkg-reconfigure locales"._

Check your php supports localization _"ru_RU.utf8"_ may be creating a "test.php" file and add the lines:
```
setlocale (LC_ALL, "ru_RU.utf8");
echo strftime ( '% A,% d% B% G');
```

After starting "http://mysite.com/test.php" date and time to be displayed in this format, **"Среда, 22 Июнь 2016"** instead of on **"Wednesday, 22 June 2016".** means php is working correctly.

I tried to remove the line `"setlocale (LC_ALL," ru_RU.utf8 ");" `and add `"SetEnv LC_ALL ru_RU.UTF-8" `in the _".htaccess",_ when you run "http://mysite.com/test.php" I get the date in the format on "Wednesday, 22 June 2016", so change will have in the file ".htaccess" does not solve the problem, at the while "setlocale (LC_ALL," ru_RU.utf8 ");" - It is working correctly.

**Comment by jekkos** [comment]
Ok so problem was that you did not have that locale installed on your system.. thanks for the feedback here I remember that I had to do something similar to have properly dates formatted in dutch.

**Comment by jekkos** [comment]
We might want to add this to the setup / support section for future reference

**Comment by AdAvAn** [comment]
Additionally, it is important!

I noticed that MS Excel by default saves files are not in UTF-8 format!
I have translated my (* .csv) file in the format **"UTF 8 Unicode"**, removed from the server all the settings localization, which I described in a previous post, as well as being the string `"SetEnv LC_ALL ru_RU.UTF-8"` from the ".htaccess" - data import was successful.

It can be concluded that the cause of the error - **is not correct encoding format (* .csv).**
It is necessary to to make sure that the imported csv file in "UTF 8 Unicode" format

**Comment by daN4cat** [comment]
Adding setlocale in PHP is a tricky story as per above comment. Strange that .htaccess solution doesn't work.

**Comment by AdAvAn** [comment]
In comments to http://stackoverflow.com/a/5075654/6176637, it is written:

_But these settings only take effect for CGI and FastCGI versions of PHP at best, not for the usual mod_php installation._

In any case, the problem was in the encoding of the imported csv file.
Thank you for your help in finding solutions.

**Comment by daN4cat** [comment]
All good discussion captured here for future reference :+1:
