### ISSUE TITLE
Search by cetagories in sales register

### ISSUE THREAD

**Issue by asadjaved63** [jekkos/opensourcepos#69]
Sir, I want custom search options means cetagories search,and custom search in sales register like item search.. Would you help me like that system?

**Comment by jekkos** [comment]
you mean extend the search functionality in sales module only? In this case for custom fields and categories?

**Comment by asadjaved63** [comment]
yes sir i means to say like that something

**Comment by jekkos** [comment]
Would it be sufficient to add all the items belonging to a category to the search suggestion box? Or do you prefer to have a new UI dropdown to do the prefiltering?

**Comment by asadjaved63** [comment]
Both are ok , I would prefer suggestion box in sales modules and selected item add into sales register through autocomplete same like( Find/Scan Item OR Receipt) hope you understand what i can say

**Comment by jekkos** [comment]
Ok that shouldn't be too much work , will let you know once I get there.

**Comment by donangil** [comment]
Is it possible to get inventory report by categories? Also when you get inventory report it lists items in each stores which is nice but how about getting the total stock amount in all stores not seperately.

**Comment by daN4cat** [comment]
The best is to install Reportico (http://sourceforge.net/projects/reportico/) and get that external web app to run the reports you like. You can create your own reports with that tool.
