### ISSUE TITLE
Ambigue In Indonesian Language

### ISSUE THREAD

**Issue by likozhang** [jekkos/opensourcepos#691]
![snapshot_2016-6-23_0-19-22](https://cloud.githubusercontent.com/assets/6987941/16276368/3797344a-38d8-11e6-8199-887009090f6c.jpg)

**Comment by daN4cat** [comment]
@likozhang Indonesian translations haven't been touched for some time.
If you speak Indonesian, please go to translations/ dir and translate all the .csv files so we can update.

To test your translations once edited the .csv files you need to run generate_languages.php

**Comment by daN4cat** [comment]
@likozhang any chance you contribute the translations in Indonesian back? Take the last master please.
