### ISSUE TITLE
Don't autoload Sms library if just used in Message controller

### ISSUE THREAD

**Issue by daN4cat** [jekkos/opensourcepos#693]
The Sms library should be loaded only when needed in Messages Controller, not being autoloaded.

Also Sms should be renamed to Sms_lib to be consistent with the rest of the libraries.

**Comment by daN4cat** [comment]
Changes in my latest commit, this will break a bit of code to somebody but it was necessary.

**Comment by daN4cat** [comment]
No complaints, I close.

**Comment by onyema3** [comment]
@daN4cat i'm still having issues sending sms.
my sms api goes like this
$url = "http://smslauncher.com/index.php?option=com_spc&comm=spc_api&username=$username&password=$password&sender=$originator&recipient=$phone&message=$message&dr=1";

Is there an issue here??
Your input will be appreciated. Thanks

**Comment by daN4cat** [comment]
I fixed something about a similar problem calling a urlencode or similar functionality. I don't have access to the code now so I go by memory. Please check a bit what's there....

**Comment by daN4cat** [comment]
I mean there should be that function call in the lib code example.

**Comment by onyema3** [comment]
I will check but please if you have the time kindly check and help.
Thanks

**Comment by daN4cat** [comment]
Your url string is like the first example, so it should be fine.
You need to check for a PHP example using smslauncher.com as it might be the way the URL call is made.

The issue I was referring earlier was related to message: `$message = rawurlencode($message);`

I hope you didn't remove that before your url string composition.

**Comment by onyema3** [comment]
No i didn't
There is no example there just http://www.smslauncher.com/#api

**Comment by daN4cat** [comment]
I would get in touch with their support and ask for help. In the end of they want to make business they need to help with such queries.
