### ISSUE TITLE
Quirk After removing receiving lang

### ISSUE THREAD

**Issue by odiea** [jekkos/opensourcepos#694]
After removing $lang["recvs_invoice_number"] = "Invoice #"; The receipt looks like this.
![2016-06-23 14_05_19-jump list for google chrome](https://cloud.githubusercontent.com/assets/10962177/16318284/ab299998-394b-11e6-87fc-debac987a27f.png)

**Comment by daN4cat** [comment]
Is that receiving receipt? There should be no invoice but reference.

**Comment by onyema3** [comment]
That's normal receipt

**Comment by daN4cat** [comment]
Fixed and in master.
