### ISSUE TITLE
Change look of Reports listing

### ISSUE THREAD

**Issue by gfxgee** [jekkos/opensourcepos#695]
New report listing look.

**Comment by gfxgee** [comment]
nevermind, now i know the error, why is this message doesn't show up in the page ,
` id:"2"
message:"<p>The image you are attempting to upload doesn't fit into the allowed dimensions.</p>"
success:false`

**Comment by daN4cat** [comment]
So the issue is that the notification doesn't show up.

**Comment by gfxgee** [comment]
sir, where can i find this `show_report()` function? yup, that error doesnt display sir ,but still submits the dialog

**Comment by daN4cat** [comment]
We need to fix the notification.

The layout of the reports page looks a nice idea, would you contribute it to master?

**Comment by gfxgee** [comment]
yes sir, i am glad to help and contribute, but i dont know how , thanks sir. :+1:

**Comment by daN4cat** [comment]
ok, send the new reports page layout here, it should be just one view file.
I'll do the rest.

**Comment by gfxgee** [comment]
listing.php

`<?php $this->load->view("partial/header"); ?>

<?php
if(isset($error))
{
	echo "<div class='alert alert-dismissible alert-danger'>".$error."</div>";
}
?>
<div class="row">
	<div class="col-md-3">
		<div class="panel panel-primary">
		  	<div class="panel-heading">
		    	<h3 class="panel-title"><?php echo $this->lang->line('reports_graphical_reports'); ?></h3>
		  	</div>
			<div class="list-group">
			   <?php
						foreach($grants as $grant) 
						{
							if (!preg_match('/reports_(inventory|receivings)/', $grant['permission_id']))
							{
								show_report('graphical_summary',$grant['permission_id']);
							}
						}
						?>
			 </div>
		</div>
	</div>
	<div class="col-md-3">
		<div class="panel panel-primary">
		  	<div class="panel-heading">
		    	<h3 class="panel-title"><?php echo $this->lang->line('reports_summary_reports'); ?></h3>
		  	</div>
			<div class="list-group">
			   <?php 
					foreach($grants as $grant) 
					{
						if (!preg_match('/reports_(inventory|receivings)/', $grant['permission_id']))
						{
							show_report('summary',$grant['permission_id']);
						}
					}
					?>
			 </div>
		</div>
	</div>

	<div class="col-md-3">
		<div class="panel panel-primary">
		  	<div class="panel-heading">
		    	<h3 class="panel-title"><?php echo $this->lang->line('reports_detailed_reports'); ?></h3>
		  	</div>
			<div class="list-group">
			  <?php 			
					$person_id = $this->session->userdata('person_id');
					show_report_if_allowed('detailed', 'sales', $person_id);
					show_report_if_allowed('detailed', 'receivings', $person_id);
					show_report_if_allowed('specific', 'customer', $person_id, 'reports_customers');
					show_report_if_allowed('specific', 'discount', $person_id, 'reports_discounts');
					show_report_if_allowed('specific', 'employee', $person_id, 'reports_employees');
				?>
			 </div>
		</div>
	</div>
	<?php if ($this->Employee->has_grant('reports_inventory', $this->session->userdata('person_id')))
	{ ?>
	<div class="col-md-3">
		<div class="panel panel-primary">
		  	<div class="panel-heading">
		    	<h3 class="panel-title"><?php echo $this->lang->line('reports_inventory_reports'); ?></h3>
		  	</div>
			<div class="list-group">
			 <?php 
				show_report('', 'reports_inventory_low');
				show_report('', 'reports_inventory_summary');
			?>
			 </div>
		</div>
	</div>
	<?php 
	}
	?>
</div>

<?php $this->load->view("partial/footer"); ?>`

report_helper.php

`if (!empty($report_label) && $report_label != $lang_key .  ' (TBD)')
	{
		?>
			<a class="list-group-item" href="<?php echo site_url('reports/' . $report_prefix . preg_replace('/reports_(.*)/', '$1', $report_name));?>"><?php echo $report_label; ?></a>
		<?php 
	}`

**Comment by gfxgee** [comment]
[listing.php.txt](https://github.com/jekkos/opensourcepos/files/331337/listing.php.txt)

![ss](https://cloud.githubusercontent.com/assets/8316409/16330561/b224e032-3a1c-11e6-85fa-bb7ca518c238.png)

**Comment by daN4cat** [comment]
Mhh the listing.php doesn't match what you showed above with each entry being in one line.
It still shows with bullet points.

**Comment by daN4cat** [comment]
OK, probably you meant to change show_report too... let me check

**Comment by daN4cat** [comment]
It's ok now.

**Comment by onyema3** [comment]
Is it in masters?

**Comment by odiea** [comment]
@gfxgee  Reports listing looks nice.

**Comment by daN4cat** [comment]
I will submit the change soon.

**Comment by RamkrishnaMondal** [comment]
![screenshot from 2016-06-24 21 33 28](https://cloud.githubusercontent.com/assets/14151032/16343179/51789788-3a53-11e6-8a65-651072966d29.png)

**Comment by RamkrishnaMondal** [comment]
BTW, Inventory Reports  are not working in current master.

**Comment by RamkrishnaMondal** [comment]
![screenshot from 2016-06-24 22 26 24](https://cloud.githubusercontent.com/assets/14151032/16344544/b91303ea-3a5a-11e6-9c74-edd9fe8a029c.png)

**Comment by RamkrishnaMondal** [comment]
![screenshot from 2016-06-24 22 26 03](https://cloud.githubusercontent.com/assets/14151032/16344548/c04f8a5c-3a5a-11e6-89ae-03c023af33ea.png)

**Comment by daN4cat** [comment]
I renamed this issue as it was getting confusing and created a new one for the original.

In my commit the new look for reports listing page in line with flatly theme.

**Comment by onyema3** [comment]
@RamkrishnaMondal when will your modifications be ready in your fork?

**Comment by odiea** [comment]
@daN4cat  Report listing looks great.

**Comment by daN4cat** [comment]
Sounds ok, so I close.
