### ISSUE TITLE
Loading avatar bigger than the allowed size doesn't result in any notification error

### ISSUE THREAD

**Issue by daN4cat** [jekkos/opensourcepos#696]
Error is not reported:

`{"success":false,"message":"<p>The image you are attempting to upload doesn't fit into the allowed dimensions.</p>","id":"2"}
`
![image](https://cloud.githubusercontent.com/assets/8316409/16325871/94214e18-39f4-11e6-96c2-2040eaf4bd1a.png)

**Comment by daN4cat** [comment]
@gfxgee you original issue with avatar loading is here now.

**Comment by daN4cat** [comment]
I noticed that in Items there is no way to report an error message. I tried changing the normal message at submit to be response: false instead of true and it didn't show up.

@jekkos any idea what could be?

**Comment by jekkos** [comment]
Not direclty.. guess we'll need to debug that a little further

**Comment by jekkos** [comment]
On the other hand, notifications are handled by the same code in every page.. Maybe something else went broke there that prevents the js from running?

**Comment by daN4cat** [comment]
Probably, I wondered about the same as well. Unless the picture loading causes something?

**Comment by daN4cat** [comment]
Also I noticed that we used to have in Items form another button to keep inputting new items but it went removed. The js code is still there.

**Comment by daN4cat** [comment]
I just committed a change to strip any html tag from the error string, we don't need the `<p> </p>`

**Comment by gfxgee** [comment]
thank you for transferring sir :+1:

**Comment by jekkos** [comment]
@daN4cat Indeed I think it was never added again after bootstrap upgrade... will make an issue for that

**Comment by jekkos** [comment]
Should be fixed now in latest

**Comment by daN4cat** [comment]
Fixed indeed.
