### ISSUE TITLE
Could you fix for PHP 7?

### ISSUE THREAD

**Issue by sitthykun** [jekkos/opensourcepos#697]
A PHP Error was encountered
Severity: Warning
Message: Declaration of Customer::save(&$person_data, &$customer_data, $customer_id = false) should be compatible with Person::save(&$person_data, $person_id = false)
Filename: models/customer.php
Line Number: 0

**Comment by daN4cat** [comment]
It seems like you are not using the latest in master, vs 3.0.

Because that's fixed in 3.0. So I close here.
