### ISSUE TITLE
Issues with last commit

### ISSUE THREAD

**Issue by onyema3** [jekkos/opensourcepos#699]
After the last couple of changes, takings doesn't show up any info whatever the date filter is

**Comment by onyema3** [comment]
Suppliers too have the same problem

**Comment by onyema3** [comment]
suspended sales too doesn't show up too

**Comment by onyema3** [comment]
Gift card page doesn't even load

**Comment by odiea** [comment]
Lots of issues with this last commit. Please fix.

**Comment by gfxgee** [comment]
this too, in items module ,inventory tracking :sob: 

![image](https://cloud.githubusercontent.com/assets/8316409/16357155/397a1f8e-3b21-11e6-8ed0-9d7cf83c889b.png)

**Comment by odiea** [comment]
Bulk edit in Items also does not work.

**Comment by daN4cat** [comment]
Fixing, it's due to the button translation change....

**Comment by daN4cat** [comment]
It should be fixed, please countercheck all the possible buttons and small icons opening dialog boxes.

I tried myself what I supposed are all, but a second sanity check is needed.

**Comment by daN4cat** [comment]
@jekkos loves to leave behind booby traps :+1: :-1:

**Comment by onyema3** [comment]
daN4cat you are a life saver. Thanks

**Comment by daN4cat** [comment]
I guess I can close.

**Comment by jekkos** [comment]
Thanks all for the swift testing feedback. You're doing a better job than me.

**Comment by daN4cat** [comment]
Ah no, don't say that please...
