### ISSUE TITLE
Add Image to Sales/Estimate

### ISSUE THREAD

**Issue by lrsilvatcf** [jekkos/opensourcepos#70]
We would like to upload a simple .jpg or .png file to the sales. We are a security company and we have inital cad drawings of the site location and where their cameras are going to be placed. 

Could be this performed?

**Comment by jekkos** [comment]
You can add images to items in the latest version. However those can't currently be viewed from the sales module. Do you need multiple images per item (so per sale) or does one image per item suffice?

**Comment by lrsilvatcf** [comment]
This would most likely be a different image. We would upload our final schematic to the customer along with the sales estimate.

examples would be like a PDF file, or JPG of the final drawing of where their products would go and how they would be wired in the facility

**Comment by jekkos** [comment]
I don't really think that ospos was meant to do these kind of things, as you're selling services and no real products.
