### ISSUE TITLE
Gone button to include new customer?

### ISSUE THREAD

**Issue by arteiro** [jekkos/opensourcepos#700]
Gone button to include new customer?

**Comment by daN4cat** [comment]
Where?

I can see it in Customer view and Sales Register view.

**Comment by arteiro** [comment]
Submit button of the form, it is only with the close button.

**Comment by arteiro** [comment]
Looking better, all forms are only with close button within the code does not appear the function to send the data, only <? Php echo Form_Close (); ?>.
![form](https://cloud.githubusercontent.com/assets/18253035/16381590/9f46a1d8-3c53-11e6-9fe3-574e2a7c7b8d.jpg)

**Comment by odiea** [comment]
Is this self inflicted or a possible translation issue? I have no issues. Maybe a bad pull. Try downloading the latest and see if you still have the issue.

**Comment by daN4cat** [comment]
I reloaded all the latest master and set Portuguese Brazilian as language and can see the buttons and translated:

![image](https://cloud.githubusercontent.com/assets/636048/16384273/2f2f4d00-3c80-11e6-8b23-f2b03a773697.png)

![image](https://cloud.githubusercontent.com/assets/636048/16384299/473e4388-3c80-11e6-8ede-abb86960d09e.png)

**Comment by daN4cat** [comment]
@arteiro please retake the latest code from master dist/ dir included and try again because it's all fine.

**Comment by arteiro** [comment]
Actually occurred problem decompressing a file. it's OK
