### ISSUE TITLE
 Warning: require_once

### ISSUE THREAD

**Issue by Bothric** [jekkos/opensourcepos#701]
Warning: require_once(/var/www/html/POS/system/core/CodeIgniter.php): failed to open stream: Permission denied in /var/www/html/POS/index.php on line 315

Fatal error: require_once(): Failed opening required '/var/www/html/POS/system/core/CodeIgniter.php' (include_path='.:/usr/share/php') in /var/www/html/POS/index.php on line 315

**Comment by daN4cat** [comment]
Check your files and directories permission, this is an issue with your installation.
