### ISSUE TITLE
Unable to restore backup of older version of OSPOS

### ISSUE THREAD

**Issue by ManjuprasadB** [jekkos/opensourcepos#703]
OS: Debian
How Can i view Backup older version of ospos in a new opsos installation.
I tried using PHPmyadmin to restore the older sql files but it gave error 1054 on viewing the reports.

Please ADD feature where we can safely view only reports of Taxes and sales and Current Stock.
And Backup and restore Instruction in case of system failure and data loss.

**Comment by jekkos** [comment]
Currently the only way is to load this dump and run the needed upgrade scripts to make it work with that version.

**Comment by jekkos** [comment]
I know that in CI there is a mechanism that allows to do automatic migration on database, might be interesting to look into if you feel like solving this problem for us

**Comment by ManjuprasadB** [comment]
i am new to linux and all can, you  which upgrade script to run if  and how to run.
do i run it from OS cmd or PHPmyadmin.

**Comment by jekkos** [comment]
From which version to which are you upgrading? Just check the database folder and you'll quickly see which scripts you need. You can run them from command line or phpmyadmin. Maybe add a `use ospos` statement first to select your database first.

**Comment by ManjuprasadB** [comment]
25 days old.

**Comment by onyema3** [comment]
Run the 2.4 to 3.0 upgrade script

**Comment by ManjuprasadB** [comment]
i am sorry to ask a stupid question "but how??" 
How do i run the script can someone give example

**Comment by ManjuprasadB** [comment]
is it like this
mysql> CREATE DATABASE ospos;
mysql> USE ospos
mysql> source \home\user\Desktop\2.4_to_3.0.sql;

**Comment by jekkos** [comment]
yes indeed correct.

**Comment by ManjuprasadB** [comment]
IT Worked Thankz
