### ISSUE TITLE
Sale will not appear in Report or Takings when Amount Tendered is negative?

### ISSUE THREAD

**Issue by usergroup81** [jekkos/opensourcepos#707]
I came across a scenario where Sale is not accounted for in Reports or Takings:

1. Customer returns 1 item for $30
2. Customer also purchase an item at $10
3. **Register Mode** is set to **Sale** instead of Return
4. Complete the sale with **Amount Tendered negative $20**.

Now check **Takings** and run a **detailed sales report**, the POS ID will not show up in either. 

However, if I switch **Register to Return** instead of Sale, it will appear and be accounted for. Is this by design where such a transaction should always be in Return mode or it will be omitted?

**Comment by odiea** [comment]
The way it appears to work is you make your sales first then dropdown to returns and enter your returns. If you start with returns then add a sale it does not report that correctly.

**Comment by odiea** [comment]
I see now there are issues with sale returns and sales on a single receipt. You are correct the info also does not show on Takings as it should.

**Comment by usergroup81** [comment]
Thanks @odiea your suggestion of completing the sale operation to include add payment first and then switching register mode to return for the same receipt works.

**Comment by odiea** [comment]
The easiest way to show this issue is to do an item exchange. The receipt show properly but the sale does not show in takings or Detail Sales Report.

**Comment by usergroup81** [comment]
Got it, so the issue occurs when completing an item exchange as a sale instead of a return. Thanks!

**Comment by odiea** [comment]
An item exchange starting in sales then return or an item exchange starting in return then sales does not show in Takings or Detailed Sales possibly because the Amount is 0.

**Comment by odiea** [comment]
Here is what Takings looks like after varies Sales with Returns. I cannot view the other missing Sales.
![2016-06-28 16_52_17-ugly sweater store -- powered by os point of sale](https://cloud.githubusercontent.com/assets/10962177/16435077/bd3a5fec-3d50-11e6-9bff-0aceedb0c7bd.png)

**Comment by odiea** [comment]
Here is Detailed Sales
![2016-06-28 16_54_44-ugly sweater store -- powered by os point of sale](https://cloud.githubusercontent.com/assets/10962177/16435186/55f47d1c-3d51-11e6-8b29-ed8097d1513e.png)

**Comment by odiea** [comment]
Currently it appears that we need to make a separate return sale then a regular sale to make sales show in takings

**Comment by odiea** [comment]
Here is the view from the database.
![2016-06-28 17_08_37-settings](https://cloud.githubusercontent.com/assets/10962177/16435421/16df4222-3d53-11e6-9d91-753d6b74c2d8.png)

**Comment by odiea** [comment]
And finally here is the view of the database from Sales Items.
![2016-06-28 17_12_15-localhost _ 127 0 0 1 _ ospos _ ospos_sales_items _ phpmyadmin 4 2 11 - microso](https://cloud.githubusercontent.com/assets/10962177/16435493/9dbcad34-3d53-11e6-993a-db20cfa69299.png)

**Comment by daN4cat** [comment]
It's probably due to the fact that a negative amount number is a return and positive amount number is a sale.

What is what in that case? Is it more a return or more a sale?

**Comment by odiea** [comment]
I guess it's a combination of both. So for now what recommend that a return be done on a separate pos?

**Comment by usergroup81** [comment]
What works for me at the moment is to complete the transaction as a Return if the amount is negative. This way, the POS is listed in Sales/Returns/Takings. I guess it would make sense to close it out as a Return since it's a negative amount.

**Comment by daN4cat** [comment]
I need to understand why it's not listed, it doesn't sound right to me if it's in the end a Sales register transition.

**Comment by odiea** [comment]
Perplexing isn't it.

**Comment by odiea** [comment]
It works fine in 2.3.3. Is it  possible its a bstables  issue.

**Comment by daN4cat** [comment]
IT looks like something is not right with sales_items_temp table.

The search function in method doesn't report all the sales removing any filtering, so there must be something wrong with the queries.

**Comment by daN4cat** [comment]
This will take some time to debug....

**Comment by jekkos** [comment]
I'll be back on duty next week, will try to close some of these bugs then.

**Comment by daN4cat** [comment]
I will check as well, probably the temp table needs some improvements/review.

**Comment by odiea** [comment]
For some reason I can add a sale with 0 amount tendered and it shows fine in Takings.
![2016-07-02 11_34_51-microsoft edge](https://cloud.githubusercontent.com/assets/10962177/16541747/2b20c906-4049-11e6-9b24-c6ca6a039aee.png)

**Comment by daN4cat** [comment]
OK, I probably found the issue.

The table ospos_sales_payments does not contain a payment for the inverted case. I need now to understand how come that a payment is not recorded in case of sale with negative number that had a return.

**Comment by daN4cat** [comment]
Of course there is no payment because the button is disabled and doesn't allow to add one as it's negative.

**Comment by daN4cat** [comment]
It has to do with the way register works.

It's probably better to consider another way of managing the flow, to add always any type of payment in and out so we even detail in negative how the amount due was paid. And that would solve other issues in calculating correctly the cash in/out.

**Comment by daN4cat** [comment]
I believed this is now fixed:

All transactions appear in Reports and Takings.
Sales Register behaves differently when an amount is negative because there is no negative payment as that's an amount due.

Please check the Sales Register, Sales Reports and Takings for a check and to verify it all makes sense.

I also improved the sales_items_temp table to make more reuse of it and reduce joins in various part of the code, especially in various Reports.

**Comment by odiea** [comment]
You have done a great job with this, Thanks. Below is the only thing I have noticed so far.
![2016-07-03 08_09_19-ugly sweater store -- powered by os point of sale](https://cloud.githubusercontent.com/assets/10962177/16545904/b4d19c1e-40f5-11e6-9f74-989f2b326108.png)
![2016-07-03 08_09_46-ugly sweater store -- powered by os point of sale](https://cloud.githubusercontent.com/assets/10962177/16545906/b91e9f42-40f5-11e6-8c5c-eef45161779a.png)

**Comment by daN4cat** [comment]
Yes there are no payments in those cases. That's correct.

**Comment by usergroup81** [comment]
Thank you gents for debugging this and providing a fix. Awesome work!

**Comment by daN4cat** [comment]
The other thing you should try is returning something and sale something qothower value. Now either sequence there is just amount due reported, no payments allowed in sales register.
There was a big around that as well.
Also you could complete the sale without having a view for comments, print or email receipt.
It was not a scendere I tested at the time I changed the sales register.

**Comment by odiea** [comment]
Here is the way the Register looks now after doing an exchange of items.
![2016-07-03 09_52_49-microsoft edge](https://cloud.githubusercontent.com/assets/10962177/16546317/094b21a8-4104-11e6-8a1a-4bb2cea0bdac.png)

**Comment by daN4cat** [comment]
This looks like done, I close.

**Comment by odiea** [comment]
@daN4cat  Thanks for updating the temp table. It made it easier to add the sales.deleted column. I am including the sales models so you can critique it if and when you ever get a break. It appears to be working .
Thanks Odiea


[Sale.txt](https://github.com/jekkos/opensourcepos/files/345241/Sale.txt)

**Comment by daN4cat** [comment]
That's #682 right? I have just adjusted something in sale model, you may want to update your code.
Sorry if I retouched it again but I wanted to finish it a bit more cleanly.

**Comment by odiea** [comment]
Thanks for all your work.

**Comment by daN4cat** [comment]
I need to reopen this because it's not completed.
There are two issues:
- receipt doesn't report `change due` but `check remainder`
- editing the sale changes the amount due to be a positive number and different from the negative module

**Comment by daN4cat** [comment]
I fixed previous comment issues. I believe this never worked properly even in the past.
In case of returns where an item of smaller value is purchased and some cash is returned things never worked correctly because there is no real payment but the transaction if feasible.

**Comment by daN4cat** [comment]
It was a bit tricky to fix all the cases, but hopefully now it's fine.

**Comment by daN4cat** [comment]
@odiea @usergroup81 does the last change look good to you? If fine I would close.

**Comment by odiea** [comment]
Here is Takings and Detailed Sales. 

![2016-07-10 12_32_51-microsoft edge](https://cloud.githubusercontent.com/assets/10962177/16715361/98a63d1a-469a-11e6-9c07-87fbfd730264.png)
![2016-07-10 12_33_34-microsoft edge](https://cloud.githubusercontent.com/assets/10962177/16715362/9d83f4f8-469a-11e6-8eec-ee33e484aa66.png)

**Comment by odiea** [comment]
The 0 ones are exchanges. 906 is a normal Sale. 908 is a return with a smaller item purchased.

**Comment by odiea** [comment]
![2016-07-10 12_47_49-wedidit _ powered by ospos 3 0 0](https://cloud.githubusercontent.com/assets/10962177/16715436/a3ac248e-469c-11e6-83fd-2d558fa118b1.png)

**Comment by daN4cat** [comment]
It looks good right? Or am I missing something even this time?

The change due of 908 is the result of a negative total, so basically the customer gets an item in exchange and some cash back.

OK, there might be a detail there, the total in Takings should be Cash: -$9.66. Is the total payments showing the correct cash amount with a negative?

**Comment by odiea** [comment]
The Payment Type does not show when you do a return or exchange.
Debit Card: $33.29 from Takings.
From Detailed Sales
Subtotal: $20.01
Total: $21.49
Tax: $1.48
Cost: -$5.00
Profit: $25.01

**Comment by odiea** [comment]
On a return when the number is 0 or lower the payment option is blocked out so no payment type is reported.

**Comment by daN4cat** [comment]
Indeed there is no payment coming in just change due.

**Comment by daN4cat** [comment]
Unless we want to change the behaviour and log any payment in (positive) and out (negative) and turn to complete only if it's 0.
Then there is no change due unless we want to turn the negative payment (out) in change due?

**Comment by odiea** [comment]
1. It would be nice to see both types of payments in Takings and Reports.
2. Payment type for 0 would be $this->lang->line(sales_return) ?

**Comment by odiea** [comment]
At the end of the day if you use Takings as the Daily result then the till would be off by not reporting a cash out payment.

**Comment by daN4cat** [comment]
At the moment change due total is deducted from cash payments because the assumption is that change due is always cash.
That's why when you select in filters cash you see the transactions with change due too.

**Comment by odiea** [comment]
So it's just the payment type that is not showing on anything 0 or below?

**Comment by daN4cat** [comment]
Yes, just the payment type because there was no payment by the customer since it's an exchange or return with money back.

**Comment by daN4cat** [comment]
No further on this after almost a month, I close.
