### ISSUE TITLE
Export to email address

### ISSUE THREAD

**Issue by paulkinobunga** [jekkos/opensourcepos#71]
Instead of exporting to excel I would love to get the low inventory via email. Is this possible

**Comment by jekkos** [comment]
This is certainly possible by editing the code. The excel can be generated and then attached to an email which should be sent to the selected email address. Suppose this would take about 2-3 hours to develop.

**Comment by paulkinobunga** [comment]
Ok I would love to try this out. Just wondering if you can offer any assistance incase I get stuck.

**Comment by jekkos** [comment]
Yes give it a try ... I think you can leverage quite a bit of existing functionality.
First you will need to edit the input form for the report submission. Add an autocomplete box there with a query for customers with an email address (or maybe you just want to send it to the logged in user's address?).

Then it's a matter of using the existing export to excel functionality to store a temp file on the filesystem. You can look at the invoice generation for an example on how to attach this generated file to an email (think it's in the sales.php controller under send_invoice)
