### ISSUE TITLE
Add again the new button functionality in items form

### ISSUE THREAD

**Issue by jekkos** [jekkos/opensourcepos#712]
Functionality was left out after bootstrap upgrade and should be reimplemented (using new way of adding buttons with data attributes). Reason was that at that time there was no way of tranlating a button text in #439

**Comment by jekkos** [comment]
Functionality is now restored

**Comment by daN4cat** [comment]
Fixed indeed, I just adjusted the button order in a couple of forms to retain the Submit always on the right first place.
