### ISSUE TITLE
Close button in form_count_detail (Items Inventory Count Details) doesn't work

### ISSUE THREAD

**Issue by daN4cat** [jekkos/opensourcepos#714]
There was a submit button in Inventory Count Details form (invoked from Items, icon button in the middle) and I changed to close.
The button appears fine but clicking on it is not effective,

It should close the form with no action.

**Comment by daN4cat** [comment]
This is fixed, thanks. I close.

**Comment by odiea** [comment]
In Spacelab I get this now. 
![2016-07-04 10_28_35-start](https://cloud.githubusercontent.com/assets/10962177/16566504/52d7b6e6-41d2-11e6-80b1-f3d9a7546102.png)

**Comment by daN4cat** [comment]
Have you updated the dist/ files?

**Comment by odiea** [comment]
I did a normal pull from OSPOS. That should have been included?

**Comment by daN4cat** [comment]
OK, let me check one thing...

**Comment by daN4cat** [comment]
try again with the new `templates/spacelab/views/partial/header.php` in master

**Comment by odiea** [comment]
I tried and got the same results.

**Comment by daN4cat** [comment]
And if try the default one do you get the same result or is it working fine?

**Comment by odiea** [comment]
Yes the default is working fine and I am having no issues with other forms not working properly.

**Comment by odiea** [comment]
I replaced the spacelab header with the main header and added the spacelab stuff and it works fine now.

**Comment by daN4cat** [comment]
Could please post here your new header for spacelab?

**Comment by odiea** [comment]
This is the one I am currently using.

[header.txt](https://github.com/jekkos/opensourcepos/files/346755/header.txt)

**Comment by jekkos** [comment]
I've refactored the headers a bit will push in a minute.. they're using includes now for the js

**Comment by jekkos** [comment]
Should be fixed now

**Comment by daN4cat** [comment]
@odiea could you please check and confirm the latest master is fine with spacelab?

**Comment by odiea** [comment]
Spacelab appears to be working correctly. No issues so far.
