### ISSUE TITLE
Error Forbidden 403

### ISSUE THREAD

**Issue by fanghaujen** [jekkos/opensourcepos#715]
Hi,

I am using ospos version 3.0
I try to reload the form for item and i see in my browser, the item picture doesnt appear. After I trace, i found out, i got the error 403, because folder item_pics/ cannot be accessed.
How to make this folder can be accessed by xampp?

Thanks

Regards
Wira

**Comment by onyema3** [comment]
I think its a permission issue. Please check

**Comment by odiea** [comment]
Re download the most current version or todays version and see if anything changed with all the updates.

**Comment by fanghaujen** [comment]
I solve the issues.. I havent changed in config php, remove index.php in index_page..
Thanks all
