### ISSUE TITLE
Item Edit Submit button doesn't work 

### ISSUE THREAD

**Issue by onyema3** [jekkos/opensourcepos#716]

**Comment by daN4cat** [comment]
Same issue with update customer.

**Comment by jekkos** [comment]
Yes indeed same problems there.. looking for a solution now

**Comment by daN4cat** [comment]
Extra one, sale edit when typing an invoice the check_invoice_number fails.
Basically all the forms that have ajax have an issue.
I assume you will work on a generic solution for all.

**Comment by odiea** [comment]
Why does the unsuspend sales form have a submit button?

**Comment by jekkos** [comment]
Yes indeed trying to find  a generic solution here.. I have to hook into jquery validate at some point.. after two clicks on submit the form works again

**Comment by jekkos** [comment]
@odiea will take care of that button as well

**Comment by jekkos** [comment]
Should be all fine now

**Comment by daN4cat** [comment]
It's fine indeed.
