### ISSUE TITLE
Enable auto print in chrome

### ISSUE THREAD

**Issue by jekkos** [jekkos/opensourcepos#717]
Will try to find a way to enable auto print in chrome (as done now in FF). Might want to check out kiosk mode and add some specific js to use printer settings configured in ospos.

**Comment by agungwizz** [comment]
yes I also try to print a report on the Firefox browser is the result:
![ospos3](https://cloud.githubusercontent.com/assets/19369660/16570466/ecc722d0-426f-11e6-9d37-20c005852270.png)
The Selected Printer Could Not Found

**Comment by sgr1875** [comment]
jekkos may be i am wrong but i am using the kiosk feature in the chrome and it auto prints for me.

"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --kiosk --kiosk-printing http://localhost/pos/

this is how my shortcut looks like. if i am understood it wrong sorry

**Comment by daN4cat** [comment]
The kiosk mode is the solution, so far I couldn't find a chrome plugin or js allowing you the silent printing. I read about fancy solutions like adding a custom URI chrome that invokes an executable to print the provided URL/page.

By the way, to make the kiosk mode effecting you need to close all the chrome apps and restart otherwise it doesn't work.

**Comment by jekkos** [comment]
Ok I read about this mode as well.. but how can one select the correct printer in that case? I was looking for some APIs and found that there is something available in chrome apps but it seems to be related to google cloud

**Comment by sgr1875** [comment]
i dont have any other stuff running only our pos and this is the only app available on that machine. 

so far no issues i encountered .

**Comment by sgr1875** [comment]
no jekkos it takes the default printer and just sends it.

**Comment by jekkos** [comment]
Ok fine I need to try that out.. this might currently be sufficient but it would still be nice to have chrome enumerate and select the configured printer.

**Comment by jekkos** [comment]
Will postpone to 3.1 as basic functionality can be configured outside of ospos. I'll try to look into the printer selection after I have some other bugs sorted

**Comment by daN4cat** [comment]
I agree but so far I couldn't see that much. So it requires some investigation and forum surfing.

**Comment by odiea** [comment]
Here is an article about this feature. Seems to explain it pretty well.
https://mycartpos.zendesk.com/hc/en-us/articles/200868343-Enable-kiosk-printing-print-automatically-for-Google-Chrome-on-Windows

**Comment by odiea** [comment]
Here is another one I found. Maybe you can use it? I have not tested it myself.
http://codeembed.com/source/ff/8366/chrome%2Fcontent%2Foptions.xul#
