### ISSUE TITLE
Item Name No

### ISSUE THREAD

**Issue by agungwizz** [jekkos/opensourcepos#719]
![ospos](https://cloud.githubusercontent.com/assets/19369660/16570328/40a60c98-426d-11e6-8249-fd7affe00d3a.png)
Hello
Item Name incomplete ...
I've been looking at the source code/query but does not Found

Thank You
Best Regard

**Comment by daN4cat** [comment]
Please use the latest code, that issue was fixed a couple of weeks ago.

**Comment by agungwizz** [comment]
Ok thanks,  that issue was fixed

**Comment by daN4cat** [comment]
Glad to hear it's solved. Next time before creating an issue please check the latest code first and then the open & closed issues to see if anything like your issue was already discussed.
