### ISSUE TITLE
Always facing error

### ISSUE THREAD

**Issue by asadjaved63** [jekkos/opensourcepos#72]
Fatal error: Call to a member function result_array() on a non-object in C:\xampp\htdocs\POS\application\models\reports\inventory_sum.php on line 36

whenever I tried my own function always Give me this error result_array() on a non-object in please help me....... I'm very very thanks, full.. tell me where I do change in already developed modules 
..... Help me

My code is
 MODEL =inventory_sum.php
--------------------------------------------
<?php
<?php
require_once("report.php");
class Inventory_sum extends Report
{
	function __construct()
	{
		parent::__construct();
	}
	
	public function getDataColumns()
	{
		return array($this->lang->line('reports_Total Quantity'), $this->lang->line('reports_Total_Cost'), $this->lang->line('reports_Total_unit_price'));
	}
	
	public function getData(array $inputs)
	{
		$this->db->select('sum(quantity), sum(quantity * cost_price), sum(quantity * unit_price)');
	    $this->db->from('items');		
        $this->db->join('item_quantities','items.item_id=item_quantities.item_id');
		$this->db->where('items.deleted', 0);
		
	return $this->db->get()->result_array();

	}
	
	public function getSummaryData(array $inputs)
	{
		return array();
	}
}
?>
--------------------------------------------------
 controllers
function inventory_sum($export_excel=0)
	{
		$this->load->model('reports/Inventory_sum');
		$model = $this->Inventory_sum;
		$tabular_data = array();
		$report_data = $model->getData(array());
		foreach($report_data as $row)
		{
			$tabular_data[] = array($row['sum(quantity)'], $row['sum(quantity * cost_price)'], $row['description'], $row['sum(quantity * unit_price)']);
		}

		$data = array(
			"title" => $this->lang->line('reports_inventory_sum_report'),
			"subtitle" => '',
			"headers" => $model->getDataColumns(),
			"data" => $tabular_data,
			"summary_data" => $model->getSummaryData(array()),
			"export_excel" => $export_excel
		);

		$this->load->view("reports/tabular",$data);	
	}
------------------------------------------------------------------------
language English  

$lang['reports_inventory_sum'] = ' Inventory Sum';
$lang['reports_Total Quantity'] = 'Total Quantity';
$lang['reports_Total_Cost'] = 'Total_Cost';
$lang['reports_Total_unit_price'] = 'Total_unit_price';

**Comment by jekkos** [comment]
Looks like the database query is not giving back anything useful. Try to see what query is being executed ($this->db->last_query()) and run it directly on your db.
