### ISSUE TITLE
Delete in Items doesn't work

### ISSUE THREAD

**Issue by daN4cat** [jekkos/opensourcepos#721]
Not sure this is due to the latest bstable or not, I reapplied the fix for the last page deleted and etc.,

The Delete in Items doesn't work anymore in master.

Maybe @jekkos you want to have a look into the latest changes from bs table 1.11.0 and what's the issue?

**Comment by odiea** [comment]
I am able to delete an item. Nothing changes on the screen. When I go to deleted items it shows there ok and then when I go back it is gone from the table. So it appears it is not updating the table as it use to.

**Comment by daN4cat** [comment]
Indeed, the table is no refreshed, nor get any notification.

**Comment by jekkos** [comment]
I noticed this bug as well this morning, will have a look

**Comment by jekkos** [comment]
Ok should be fixed now. the $.post call wasn't properly proxied.

**Comment by daN4cat** [comment]
OK, still related to csrf change.

**Comment by onyema3** [comment]
Working now

**Comment by odiea** [comment]
The item is deleted and the row shows color now. Did it ever update the tables view after deleting?

**Comment by odiea** [comment]
Now table view is updating.

**Comment by daN4cat** [comment]
This is fixed. I close.
