### ISSUE TITLE
Spacelab questions.

### ISSUE THREAD

**Issue by odiea** [jekkos/opensourcepos#722]
I answered too quickly. You might want to add something to reduce the font size. It is more noticeable when you see the  customer name in Sales. 

* {
   font-size: 13px;
   /*line-height: 1.5;*/
}

**Comment by daN4cat** [comment]
You can add that to `templates/spacelab/css/style.css`and if it's overwritten by any reason just add at the end !important and should be the one in use.

**Comment by odiea** [comment]
I think I am recommending that something like this should be added to Style.css. Currently it looks like below.

![2016-07-06 05_05_08-microsoft edge](https://cloud.githubusercontent.com/assets/10962177/16615962/5b8efce8-4337-11e6-952d-bc3d8f747978.png)

**Comment by daN4cat** [comment]
OK, so I need to add that for you.

**Comment by odiea** [comment]
If you think the oversized text looks fine then leave it alone. I just made a suggestion.

**Comment by daN4cat** [comment]
Not sure... ospos.css which is loaded by all the headers has the following:

.wrapper
{
	font-size: 14px;
}

and the first `div` in `header.php` `<body>` is `<div class="wrapper">`

So where is exactly that you need a bigger font size?

**Comment by daN4cat** [comment]
OK, I gave a try and touched it from Inspector and indeed looks better with 13, 12 would be too small for many most likely.

I'll change and see if nobody complains :-)

**Comment by odiea** [comment]
Everything looks good with the normal ospos but when you switch to a template that is when the font size changes and to me it looks a little funky.

**Comment by daN4cat** [comment]
Done.

**Comment by odiea** [comment]
I will close this . Thanks

**Comment by jekkos** [comment]
The only difference between those headers currently is just one css file, right?

Why don't we then just define the path to that file as an application config record?

**Comment by jekkos** [comment]
In that case we can get rid of the file itself and use a generic one that can load any theme

**Comment by odiea** [comment]
It looks like 2 if the style.css is kept.

<link rel="stylesheet" type="text/css" href="templates/spacelab/css/bootstrap.min.css? 
		
		<link rel="stylesheet" type="text/css" href="templates/spacelab/css/style.css"/>

**Comment by jekkos** [comment]
Yes I just thought about the theming, think it just comes down to copying all different css sheets in their own folder and adding a config option to select the folder you want to load from

the build isn't impacted as these sheets are already separated from the minifcation, think it's quite easy to do

**Comment by jekkos** [comment]
then in this case flatly style.css and bootstrap.min.css should move to templates/flatly folder.. need a new grunt task to copy those from bower_components/

**Comment by jekkos** [comment]
Also I wonder whether we need to keep the other files that are now present in the templates dir? Was there anything specifically done for the footer / login files? I think we won't need them anymore.. I'll have a look later (first finish the locale stuff)

**Comment by daN4cat** [comment]
There is an issue about make OSPOS managing themes better.

**Comment by odiea** [comment]
It appears that all that needs to be done is get rid of the template folder then change the bootstrap.min.cc in the dist folder. The style.css is nice to change little bits of the look. Like the topbar looks better to me with the style.cc invoked. So if you can add a template config to Store config that would work great.

**Comment by daN4cat** [comment]
#409 please...
