### ISSUE TITLE
New setup for testing OSPOS.

### ISSUE THREAD

**Issue by odiea** [jekkos/opensourcepos#724]
I just updated my xampp setup. With this new version I am having no errors and it is twice as fast. 

xampp-win32-7.0.8-0-VC14-installer.exe

XAMPP Apache + MariaDB + PHP + Perl

Apache Version  Apache/2.4.18 (Win32) OpenSSL/1.0.2e PHP/7.0.8  
Apache API Version  20120211  
Server Administrator  postmaster@localhost  
Hostname:Port  localhost:80  
Max Requests  Per Child: 0 - Keep Alive: on - Max Per Connection: 100  
Timeouts  Connection: 300 - Keep-Alive: 5  
Virtual Server  No  
Server Root  C:/xampp/apache  
Loaded Modules  core mod_win32 mpm_winnt http_core mod_so mod_access_compat mod_actions mod_alias mod_allowmethods mod_asis mod_auth_basic mod_authn_core mod_authn_file mod_authz_core mod_authz_groupfile mod_authz_host mod_authz_user mod_autoindex mod_cgi mod_dav_lock mod_dir mod_env mod_headers mod_include mod_info mod_isapi mod_log_config mod_cache_disk mod_mime mod_negotiation mod_proxy mod_proxy_ajp mod_rewrite mod_setenvif mod_socache_shmcb mod_ssl mod_status mod_version mod_php7  

Server: 127.0.0.1 via TCP/IP
•Server type: MariaDB
•Server version: 10.1.13-MariaDB - mariadb.org binary distribution
•Protocol version: 10
•User: root@localhost
• Server charset:  UTF-8 Unicode (utf8)

**Comment by jekkos** [comment]
Do you think maria db is worth is over mysql?

**Comment by odiea** [comment]
I don't really know where the improvement is coming from. Some articles say php7 is faster and I think Maria db is faster.

**Comment by daN4cat** [comment]
I read Maria DB is faster over MySQL

**Comment by daN4cat** [comment]
Probably the best way to check the performance (having time) would be to check the time in displaying a Low Inventory always having the same (large) dataset.

It's the slowest part of OSPOS although I tried to optimise it to become acceptable after the XSS clean introduction.

**Comment by odiea** [comment]
@daN4cat My test database only has 100 items in it. If you have phpmyadmin and can export a large database I will try it out with that.
