### ISSUE TITLE
Add drop down filed in New Gift Card form

### ISSUE THREAD

**Issue by akashneelh** [jekkos/opensourcepos#725]
Dear All,

I just want to add a dropdown field in the new gift card form and put two text values in the drop down list. Please guide how to do that. I have already inserted a new text field in ospos_gifcard table named as 'Reason'.

Pls help.

**Comment by daN4cat** [comment]
Is the purpose to just add a comment or something else?

If it's a comment that you need you can check similar cases in Items where there is a description field that does exactly the same.
For the example you need to check `views/items/form.php, controllers/Items.php and models/Item.php`

To implement your case with Giftcard you need to work on: `views/giftcards/form.php, controllers/Giftcards.php and models/Gitcard.php`

If you implement something new it wuld be nice to contribute it back to the project.

**Comment by akashneelh** [comment]
Thanks for your reply !
 
Adding comment is ok,but I need two predefined values as a drop down list & same needs to be inserted in ospos_giftcard table against gift card detail. Pls help how to design these. I tried to follow the same method like there is an option in Customer module to choose between male & Femaile in gender selection.

Request your early response pls!!

**Comment by daN4cat** [comment]
If you check Items there is Suppliers field that is a drop down, so identify that part in the form.php to understand how to display it. In controllers/Items.php you need to check when the form queries the controller to fetch the data.
I guess I should draw some sequence diagram to understand how this is achieved, but I don't have that much time at the moment to do that, so you need to find your way.

**Comment by akashneelh** [comment]
ok...let me try & revert you  back

**Comment by akashneelh** [comment]
Yes I have done this.. But will you ps help me how to change Giftcard Number field to a free text field so that we can put Gift card number manualy (ex.. GV001). in the New Giftcard form?

**Comment by akashneelh** [comment]
Done the above query too. Now I am able to add a text filed in the gift card number. But ,I  am facing an error in Sales screen while adding gift card as a payment type. Error coimg.. "Must enter numeric value for amount tendered". Pls help how to resolve this.

**Comment by akashneelh** [comment]
Thnks did it myself, removed the validation from ...\application\controllers\sales.php file and it worked
