### ISSUE TITLE
Inventory does not support decimal quantities

### ISSUE THREAD

**Issue by jekkos** [jekkos/opensourcepos#726]
Found a bug while testing #458. Inventroy trans_inventory column is of type int(11) and thus does not support decimals.

**Comment by daN4cat** [comment]
Probably at the time I converted all the fields to have decimal this was unintentionally skipped.

This must be fixed in 3.0 to be in line with the rest.

**Comment by daN4cat** [comment]
I can have a look at this later.

**Comment by daN4cat** [comment]
Database change fixed, script 2.4 to 3.0 needs to be run in order to change the field to be decimal (15,3)

**Comment by daN4cat** [comment]
@likozhang any chance to help with the testing of this too?

**Comment by jekkos** [comment]
Tested and found ok. Will close
