### ISSUE TITLE
Sales Tax not retaining in database

### ISSUE THREAD

**Issue by odiea** [jekkos/opensourcepos#727]
Since the latest pull Sales tax loses tax 1 name and tax 2 always defaults to 0.00. Now I go into Items update and sales tax 1 is in sales tax 2. I go to the database and there is no name for sales tax 1 even after I save it.

![2016-07-07 15_26_18-wedidit -- powered by os point of sale](https://cloud.githubusercontent.com/assets/10962177/16670391/378a9c5a-4457-11e6-9c6b-07ab7e640a22.png)

![2016-07-07 15_27_06-wedidit -- powered by os point of sale](https://cloud.githubusercontent.com/assets/10962177/16670403/4c2d733a-4457-11e6-9b86-446766dab8c7.png)

**Comment by odiea** [comment]
Here is an image of my database. I changed the tax name in the database when I go to store config I get the following.
![2016-07-07 15_33_33-localhost _ 127 0 0 1 _ ospos1 _ ospos_app_config _ phpmyadmin 4 5 1 - microsof](https://cloud.githubusercontent.com/assets/10962177/16670665/8006bb02-4458-11e6-8605-3940a1345427.png)

**Comment by odiea** [comment]
I just downloaded the latest. Created a new database and the issue persists.

**Comment by odiea** [comment]
After I reverted the changes it is working properly now.

**Comment by odiea** [comment]
@jekkos  Would you please make changes in a new branch before updating the master so it can be tested.

**Comment by onyema3** [comment]
Odiea is right, sales tax is not stored in the database

**Comment by jekkos** [comment]
@daN4cat already found the culprit through the first code review, it was the empty check in the tax decimal output that caused this issue. Should be fine now.

I suppose I didn't take enough time to test everything through. Might indeed be better in that case to use a new branch in such situation. Will keep that in mind next time.

I have the feeling that there are more users rebasing off master on a daily basis which is good as bugs are reported and hopefully fixed more quickly.

**Comment by daN4cat** [comment]
@jekkos not sure I get. This is working now right? If you refer to my small change in the code from this morning I moved the empty to the common function as the same applies to all fields.

**Comment by jekkos** [comment]
@daN4cat Indeed I readded this empty check I think this morning as it broke the tax decimal save, thanks for pointing that out.
