### ISSUE TITLE
Error when using barcode for multiple sales

### ISSUE THREAD

**Issue by elijahkato** [jekkos/opensourcepos#728]
Hello Jekkos, I must admit that you are doin a great work here and i appreciate your efforts. 

I installed the latest version 3.00 of the OSPOS on windows 10 runnig Xampp v5.5.30, Apache 2.4.4, MySql 5.5.32 and PHP 5.5.3. Everything works fines but when i enter sales using my barcode scanner it gives me error saying i dont have permission to view this document. Please can u help with the fix. Thanks in advance

**Comment by daN4cat** [comment]
Have you checked if you have the right permissions allocated to your name under Employees/ edit ?

**Comment by daN4cat** [comment]
No replies, I close.
