### ISSUE TITLE
Detailed Sales not showing correctly

### ISSUE THREAD

**Issue by odiea** [jekkos/opensourcepos#729]
![2016-07-08 15_36_49-wedidit -- powered by os point of sale](https://cloud.githubusercontent.com/assets/10962177/16702240/033d0be2-4522-11e6-956f-82ecb4454413.png)
![2016-07-08 15_37_11-wedidit -- powered by os point of sale](https://cloud.githubusercontent.com/assets/10962177/16702244/06fcfe36-4522-11e6-8147-26d9de05efca.png)

**Comment by odiea** [comment]
My tax is set at 7.4% 
![2016-07-08 15_41_15-wedidit -- powered by os point of sale](https://cloud.githubusercontent.com/assets/10962177/16702317/72b57900-4522-11e6-924b-4c0aee94db92.png)

**Comment by daN4cat** [comment]
I revert a change I made and I don't understand how that could have impacted the config "included_tax", but here you go better to revert and get this fixed.

Please check again and if fine I close this issue.

**Comment by odiea** [comment]
It is working properly now. Close this issue.

**Comment by daN4cat** [comment]
Good, thanks and apologies for the regression but whilst sorting out the return/exchange with cash back I realised something was wrong.
