### ISSUE TITLE
Add Customer service details for repair jobs

### ISSUE THREAD

**Issue by paulkinobunga** [jekkos/opensourcepos#73]
I would love to use this to create a system for managing a cellphone repair shop. Along with the customer information, I would love to add information about the device. i,e
device name
model of device
problem.

after save I would love to redirect to sales page and add items needed for the repair job. how can i go about this

**Comment by jekkos** [comment]
Just use the custom fields to store thos attributes. Then add items in sales the regular way. Maybe check opensourcpeos guide online they provide some more info on this.

**Comment by paulkinobunga** [comment]
well I did. But custom attributes work for items only not customers. Correct me if am wrong. Thanks

**Comment by jekkos** [comment]
What you'd want here is associate a customer with the products he bought?
Currently there is a sales overview screen where you can query for customers and see all the finished sales over the applicaiton's history. You might be able to work around this issue in this way.

The search normally does accept customer names as well, give it a try and let me know.
