### ISSUE TITLE
Add Shutdown Button

### ISSUE THREAD

**Issue by ManjuprasadB** [jekkos/opensourcepos#730]
I am Using OSPOS on Raspberry Pi I want to add an shutdown button on webpage to shutdown Raspberry pi which will run shutdown script

**Comment by daN4cat** [comment]
Do you want to shutdown on logout or have a button on the login page to shutdown?

Besides I didn't look into how to trigger the shutdown for the case, have you searched how to?

**Comment by ManjuprasadB** [comment]
I want to have a button on login page which will run a script to shutdown Raspberry pi like "shutdown -h now" and have an option weather to shutdown on logout.

**Comment by daN4cat** [comment]
OK, but do you have some implementation skills or do you expect us to do for you?

**Comment by ManjuprasadB** [comment]
I have just recently (4 months) started learning about linux, python, Mysql with Raspberry PI.
I am noob, IF you provide guidelines i am willing to lean and do that myself.

**Comment by jekkos** [comment]
Ok nice, you will need to add a script with setuid root to power off the raspi. You can easily call that fro php using `shell_exec` function. Add this in a controller then make the button do a `$.get` for that controller function and you're done

**Comment by daN4cat** [comment]
You missed: have fun and good luck :+1:
