### ISSUE TITLE
OSPOS 3.0.0 Release

### ISSUE THREAD

**Issue by daN4cat** [jekkos/opensourcepos#731]
Hi,

is it time to wrap up and release OSPOS 3.0.0?

As far as I can see there are just two bugs open and the rest is completed with just some testing to perform.

Would be good to push 3.0.0 out of the door after so many months of really hard work as this version was a complete overhaul. Can't think of how many things we changed... I guess the release list will be long!

Also summer holiday season is at the doors, end of next week I'm off for a two week in a sunnier place to enjoy some rest.

**Comment by odiea** [comment]
Good for you. Please leave your computer at home.

**Comment by daN4cat** [comment]
We may need to consider a refresh of translations before we release.

**Comment by konceptech** [comment]
How can i help with french translations without having to push/pull

**Comment by daN4cat** [comment]
Post the csv files from the translation folder with French translated here

**Comment by sonnysk76** [comment]
I have to perform a few spanish updates/translation,  for this weekend should be completed.

**Comment by daN4cat** [comment]
Sounds good. Please use the latest csv files from master because I've added German yesterday

**Comment by daN4cat** [comment]
By the way I would put on hold the release because I would like to sort out another aspect before we release 3.0.0.

**Comment by jekkos** [comment]
Ok so currently all what is left is the security improvements testing?

**Comment by daN4cat** [comment]
+ Arab translation and there is this issue with the scan.

Ha yes, we haven't closed the license one. I'll recheck next days what you said at that time.

**Comment by jekkos** [comment]
Ok and what about the theming? Will we leave it for later? In my opinion this should just be a matter of setting the path to the bootstrap css using a variable in the config section. Bootswatch templates can just be installed using bower (probably no more need for the templates folder).

**Comment by daN4cat** [comment]
If it's easy let's close that too. The template folder I don't know. We need to deal with the custom css.

**Comment by daN4cat** [comment]
Arab translation is hopefully sorted pending verification.

Bootswatch template is 3.3.6 where bootstrap is 3.3.7 and in Github is 3.3.7. The Bootswatch-dist is lagging behind one version and I created an issue but not sure it will be picked up. I'm afraid I would need to fork it, update and point our bower.json to our fork to get the latest.

I still need to check better this license story, but I understand you just get the list in gruntfile?

**Comment by aelhofy** [comment]
Bootswatch template is now 3.3.7, kindly check the below link 

https://bootswatch.com/flatly/bootstrap.css

Arabic is OK now

**Comment by daN4cat** [comment]
Thanks I knew already. What we use to upgrade OSPOS dependencies is stuck to bootswatch 3.3.6 that's why I created an issue but no feedback yet in bootswatch-dist.

**Comment by daN4cat** [comment]
Maybe we should sort out #409 too to get the latest bootswatch and allow multiple theme support.

**Comment by jekkos** [comment]
Yes I guess that's a necessary one to get theming working. I need to have a look at how the packaging is done exactly so we can download all those themes and collect them in one parent folder all together. I already had a quick look at the bootswatch-dist project today to see how we can upgrade to newer versions ourselves (might fork that one later on as well).

**Comment by daN4cat** [comment]
I had something in mind, I'll try it later or tomorrow and see if it works with no big issues.

**Comment by jekkos** [comment]
See my  last comment in #359 .. think we're getting close to finish line now.

**Comment by RamkrishnaMondal** [comment]
@jekkos @daN4cat  

I have modified the 'login.php' and 'login.css' files to get a cleaner look like below , if you wish you can cherry pick and add these files to upstream. A link to the COPYING file also added...so that, one can read the 'Copyright Notice' even before loging into the OSPOS.

![screenshot from 2016-08-11 19 35 45](https://cloud.githubusercontent.com/assets/14151032/17595519/02a63966-600b-11e6-8039-c1e678142931.png)

[login.zip](https://github.com/jekkos/opensourcepos/files/413651/login.zip)

**Comment by daN4cat** [comment]
Thanks for the suggestion. I have implemented the part with the different input types.
The rest of the style I prefer to stay as per original and the copyright statement & link doesn't work is you use the .htaccess we added as it will block the direct reading of it.

**Comment by RamkrishnaMondal** [comment]
Well, we can take a screenshot of the COPYING file , place it to 'images' folder and link it to login page.

**Comment by daN4cat** [comment]
Time to write the release notes?

**Comment by jekkos** [comment]
I'll try to draft them this week.

**Comment by daN4cat** [comment]
@jekkos I drafted already something. Please check and upgrade.

I would like to get this pushed out by the week end and then have the (real) celebration beer together next week.
I assume we should post even a picture here :-)

**Comment by daN4cat** [comment]
@odiea we'll buy a beer for you and drink in your absence, unless you want to fly over from Colorado to Brussels next week :-)

**Comment by odiea** [comment]
I would like to do that but too much going on here. Take my beer and you 2 enjoy it. Grandson has football playoffs so I can't miss that.

**Comment by daN4cat** [comment]
football = american football I guess, you know us, Europeans, read football =soccer :-)

**Comment by odiea** [comment]
He played soccer when he was younger but he thought American football was more fun once we told him he did not have to be a gentle giant anymore.

**Comment by odiea** [comment]
14 yrs old 6ft 2 195 lbs. He eats us out of house and home.

**Comment by daN4cat** [comment]
oh wow, 14 y/s 6ft, he's really tall!

**Comment by odiea** [comment]
He's the ladd standing next to my 5 ft wife.
https://www.facebook.com/nancy.agnew.92

**Comment by odiea** [comment]
And no he did not get his height from my side of the family.

**Comment by jekkos** [comment]
Cool pic there. @daN4cat I'll try to review a bit tomorrow and finalize. Looking forward having a beer after all this hard work.

**Comment by odiea** [comment]
@jekkos thanks. I will delete these posts in an hour. Hope there were enough donations so you 2 can at least have a pitcher of warm beer.

**Comment by daN4cat** [comment]
@odiea probably too many American steaks...

@jekkos 7 months of work!

@odiea a pitcher of Belgian beer can be dangerous, not sure you can stand to a pitcher of Leffe for instance. Belgium is a country of 100 beers but they tend to be strong.

**Comment by odiea** [comment]
@daN4cat I know our weak 6% beer is not dangerous. When I am in Honduras I do enjoy a bottle or 2 of Salva Vida. No weak beers there either.

**Comment by alvin101** [comment]
@daN4cat you come to Roatan I will buy you a Salva a big one, a caguama

**Comment by daN4cat** [comment]
@alvin101 I checked where Roatan is (apologies for my ignorance) and WOW, it looks a beautiful place. Is where you live?
You are now tempting me not only thanks to hinting me of that place but even for the Salva beer offer!
BTW, how do you fly to Roatan?

**Comment by daN4cat** [comment]
Actually I've just checked and all the bootstrapisation story started in Dec 2015, so it's 10 months of work.

**Comment by alvin101** [comment]
@daN4cat Roatan has an international airport, but I find it a better value to fly to San Pedro Sula and take a bus to La Ceiba where you catch the Galaxy Wave ferry to the Island.

**Comment by daN4cat** [comment]
I fixed the last bug, fixed README typo and Release note typo, added the Tag 3.0.0 and pushed the Release button.

It's official Release 3.0.0 is out now.
