### ISSUE TITLE
Gift Card Remaining Balance not showing properly at sales register

### ISSUE THREAD

**Issue by odiea** [jekkos/opensourcepos#732]
After entering a giftcard and accepting  the payment the remaining value is not the correct amount on the screen.

![2016-07-10 15_47_57-wedidit _ powered by ospos 3 0 0](https://cloud.githubusercontent.com/assets/10962177/16716301/f6446620-46b5-11e6-9bd5-7757d65a2d80.png)
![2016-07-10 15_48_34-wedidit _ powered by ospos 3 0 0](https://cloud.githubusercontent.com/assets/10962177/16716303/f9b211b8-46b5-11e6-8c0e-86a2d1dd21eb.png)

**Comment by odiea** [comment]
This is the original receipt directly from the Sale and giftcard balance is showing correctly.
![2016-07-10 15_54_09-wedidit _ powered by ospos 3 0 0](https://cloud.githubusercontent.com/assets/10962177/16716321/aa807c64-46b6-11e6-9b3c-7f46a81d6ff0.png)
This is the receipt from Takings. No Giftcard info.
![2016-07-10 15_53_21-wedidit _ powered by ospos 3 0 0](https://cloud.githubusercontent.com/assets/10962177/16716334/e3853478-46b6-11e6-98d3-d5b4132cdd65.png)

**Comment by daN4cat** [comment]
OK, something missing there for the remaining amount report and Giftcard Number.
However I'm not sure it's that easy to report the balance on a reprint because we should keep track of balance across the time. I'm afraid that functionality was never there.

**Comment by odiea** [comment]
Yes You are correct about the stored receipt not retaining the gift card balance.

**Comment by daN4cat** [comment]
I believe to have fixed all the amount reporting issues.

I cannot fix the giftcard remaining amount historical, that would require storing transaction values that are not there. It's a different issue.

**Comment by odiea** [comment]
Here is an easy fix.
$lang["giftcards_remaining_balance"] = "Giftcard %1 remaining value is $%2";
$data['warning'] = $this->lang->line( 'giftcards_remaining_balance', $giftcard_num, number_format($new_giftcard_value,2) );

**Comment by daN4cat** [comment]
There must be some issue with your locale config and the change introduced recently. By the way I spotted a typo with the error message that I need to fix.

**Comment by daN4cat** [comment]
I fixed the typo with my last commit, it has nothing to do with the number issue.

That issue is due to `to_currency($new_giftcard_value, TRUE)`, which boils down to the new currency converted/formatter.

**Comment by daN4cat** [comment]
I assigned to @jekkos for him to check that point in `Controller/Sales line 219`.

**Comment by daN4cat** [comment]
When I test everything is fine on my side:

![image](https://cloud.githubusercontent.com/assets/636048/16774386/a342b400-4853-11e6-8bbb-fd8d774363b6.png)

**Comment by daN4cat** [comment]
Here the Giftcard value after the transaction:

![image](https://cloud.githubusercontent.com/assets/636048/16774443/d98fbb02-4853-11e6-8a4f-d0c7b5348ead.png)

**Comment by onyema3** [comment]
Same here too.
Thanks

**Comment by daN4cat** [comment]
@odiea can you please retest and confirm it's still an issue with you?

**Comment by odiea** [comment]
Maybe it does not like the US settings.

![2016-07-12 13_27_15-wedidit _ powered by ospos 3 0 0](https://cloud.githubusercontent.com/assets/10962177/16780610/a04374de-4834-11e6-9167-2e5cb829c2c3.png)
![2016-07-12 13_27_47-wedidit _ powered by ospos 3 0 0](https://cloud.githubusercontent.com/assets/10962177/16780612/a42800c4-4834-11e6-9756-233921ef5110.png)
![2016-07-12 13_28_37-jump list for notepad](https://cloud.githubusercontent.com/assets/10962177/16780620/a9ca24d0-4834-11e6-84a9-238416756838.png)

**Comment by odiea** [comment]
After I change it to this it shows just fine.
number_format($new_giftcard_value,2)

**Comment by odiea** [comment]
It must be the language. You can see the difference. First image is GB second is US.
![2016-07-12 13_37_25-wedidit _ powered by ospos 3 0 0](https://cloud.githubusercontent.com/assets/10962177/16780908/02de9604-4836-11e6-90e0-3a973c8b2d8f.png)
![2016-07-12 13_38_32-wedidit _ powered by ospos 3 0 0](https://cloud.githubusercontent.com/assets/10962177/16780924/07458f36-4836-11e6-9202-c4c341b7f631.png)

**Comment by daN4cat** [comment]
Yep, Jekkos should look into this because it's related to the locale change.

**Comment by odiea** [comment]
It appears that if you use the $ sign your screwed. en_au does it and when I change the en_GB to a dollar sign it does it.

**Comment by daN4cat** [comment]
OK, I will check if I can find the time the influence of adding $.

**Comment by jekkos** [comment]
I'll check next week. Still on holidays will leave for a  trip to the mountains today

**Comment by jekkos** [comment]
I guess the problem is that $ is being interpreted by the preg_replace function in MY_Lang.php

**Comment by jekkos** [comment]
Shoudl be fixed now in latest master

**Comment by odiea** [comment]
It is working properly now so I will close this issue.
