### ISSUE TITLE
Modules is not working when langage is set to French

### ISSUE THREAD

**Issue by konceptech** [jekkos/opensourcepos#735]
![ospos-bug-lang-employee](https://cloud.githubusercontent.com/assets/17205399/16783780/8d6de7f8-4853-11e6-9f62-798d5d93bead.PNG)
On:  Version 3.0.0 - 1c4e5093bfbc

When UI Language is in french, somes modules are not loading properly, see attachement.

Modules concerned: Customers, Suppliers, Employees.

**Comment by daN4cat** [comment]
Probably this is due to some translation being empty or similar. It would be better to review all the French translation and make sure it's all cvs files are filled in, run translation_language script and try again.
However I will give a try later on to see what's the issue there.

**Comment by jekkos** [comment]
Probably some kind of js escape error that breaks bstable load

**Comment by jekkos** [comment]
Ok think I fixed this one.. was an escape problem indeed.

**Comment by konceptech** [comment]
Simple ask, in the build checkups, is it possible to loop tests for each langages?

**Comment by daN4cat** [comment]
Doable as you can select UI parts to chose new language and then check on translation on each page, but it's always a matter of time.
