### ISSUE TITLE
Include a System Info page in Store Config

### ISSUE THREAD

**Issue by konceptech** [jekkos/opensourcepos#737]
This will be nice to quickly post an issue, and having all the details at one place and properly formatted.

Like a phpinfo does, having several info about the server, php version, DB type, git hash, modules loaded, ...

**Comment by daN4cat** [comment]
Maybe we can use this: https://github.com/phpsysinfo/phpsysinfo

**Comment by daN4cat** [comment]
Alternative suggestions: http://stackoverflow.com/questions/4577433/how-to-get-system-info-in-php

**Comment by odiea** [comment]
I added this to a new tab just for a quick check of the php being used. Is this enough to help diagnose php issues.
```
<?php
echo 'Current PHP version: ' . phpversion();
echo "<pre>";
      print_r(get_loaded_extensions());
      echo "<pre/>";
?>
```
The result.
![2016-08-16 06_06_04-](https://cloud.githubusercontent.com/assets/10962177/17698293/8c66e424-6377-11e6-9679-e997012632e0.png)

**Comment by daN4cat** [comment]
I read in forum that for security reasons it's not a good idea to display phpinfo in web pages.

Therefore I close this issue as it's not something we should not implement.
