### ISSUE TITLE
Detailed Sales Report : Price

### ISSUE THREAD

**Issue by agungwizz** [jekkos/opensourcepos#738]
![ospos price in detailed sales report](https://cloud.githubusercontent.com/assets/19369660/16791401/bd643666-48e8-11e6-81a1-320b0fece386.png)

Detailed Sales Report : Price
i am need update sub total to price unit 
Regard

**Comment by daN4cat** [comment]
You mean changing Subtotal to be price unit?

**Comment by agungwizz** [comment]
Yes

**Comment by daN4cat** [comment]
And what are we supposed to do here, not sure I get what you are after. Us to implement for you, you to implement this, something else?

**Comment by agungwizz** [comment]
yes changing Subtotal to be price unit, header and content
