### ISSUE TITLE
Scan error in Sales

### ISSUE THREAD

**Issue by Modding** [jekkos/opensourcepos#739]
I have a barcode scanner which scans the EAN code on the product and presses Enter after every scan. Sometimes it is impossible to scan it is the right EAN Code and it displays:

> Unable to add item to sale

and if i scan again a blank page with following text comes:

> 
> An Error Was Encountered
> 
> The action you have requested is not allowed.
> 

But sometimes it adds the Product to the Cart.

**Comment by Modding** [comment]
looks like this is a Firefox Issue. on Chrome it works

**Comment by daN4cat** [comment]
This looks like being an issue with your setup.

**Comment by Modding** [comment]
I also made a video:
https://www.youtube.com/watch?v=gCSlrsFFBH0

**Comment by daN4cat** [comment]
Can you please scan your barcode in notepad and attach the text file here?
It could be something to do with your scanner that appends something causing a problem.

**Comment by daN4cat** [comment]
also can you please see if there is any error_log file in your OSPOS installation dir?

**Comment by bkrajendra** [comment]
Im also getting this strange problem.
If you add Item#1 through scanner its get added in sales..
If you scan next item#2, the previous item gets deleted from sales....

This is not frequently but observed some time only..
Im little out of time to debug the problem! (tried on both FF n Chrome)

**Comment by daN4cat** [comment]
Deleting the previous sounds very unusual. I believe I need to look for a scan and test a bit.

**Comment by Modding** [comment]
I have scanned the Barcode to gedit (notepad on linux) and its only as espected the Numbers and a press on Enter. I also debugged it via USB Listen and its only a HID (Keyboard) 

But my error is only in FF and not in Chrome.

Greetings 

Valentin

**Comment by jekkos** [comment]
You should check for special invisible characters at the end of the barcode itself, they might not be directly visible in gedit. You can make them visible in notepad++ tho.

It could be a timing issue in firefox (ajax complete not called yet before the next request is submitted). But I should be able to reproduce before I can confirm (and I don't have a scanner here currently)

**Comment by Modding** [comment]
As i sayed i have testet it with multiple programms like a Keylogger. There is no other charakter like the NUMBER and the Enter.

**Comment by jekkos** [comment]
Ok then maybe it's a timing issue. If you wait a little longer before you do the second scan, then does it work?

**Comment by jekkos** [comment]
@Modding could you try to reproduce by opening the inspector window in FF (F12) and wait until all requests are finished before entering the next item? In that case, do you see the error?

**Comment by jekkos** [comment]
I could add a safeguard here to check whether there are no pending ajax requests when submitting the form to make sure csrf tokens are up to date in all forms.

**Comment by Modding** [comment]
https://youtu.be/DbU28pmpx-g

**Comment by jekkos** [comment]
OK I can clearly see the error. Weird does not seems to be a direct timing issue. I should be inspecting the network tab in FF inspector panel to understand what is going on here.

**Comment by Modding** [comment]
https://youtu.be/rjs_w5uxWeA

**Comment by daN4cat** [comment]
@jekkos is this solved?

**Comment by jekkos** [comment]
From the video it looks like the csrf token is not updated after the first refresh. .However when testing this locally without a scanner there is no issue, so I still don't know what caused this.

I might need to see what exactly is sent / received from the server. @Modding can you click the plus icon next to the add request once a request is sent/received? I will need to inspect both sent form fields and received cookie header from the server to see if the csrf token is sent correctly before you get the 403 forbidden.

**Comment by daN4cat** [comment]
@odiea have you tested the latest OSPOS with Firfox and spotted any issue?
If no issues and no updates from @Modding I would suggest to close.

**Comment by odiea** [comment]
@daN4cat I could not test with a scanner. I Had no manual entry issues.

**Comment by daN4cat** [comment]
OK, thanks. Let's wait until tomorrow then we can close if no complaints.

**Comment by freemail624** [comment]
I also has the same problem 
scan the first item is ok ,but scan the second item it give me this error "The action you have requested is not allowed."
but manually adding item no problem 
this only happen when using barcode scanner with firefox but in google chrome work good without error
i test this with the last Version 3.0.0 - 84033699675e.

**Comment by daN4cat** [comment]
@freemail624 so this happens on a second scan using FF.

@jekkos are you able to reproduce this?

**Comment by daN4cat** [comment]
@freemail624 we might need more help from you in case we need to debug the issue.

**Comment by jekkos** [comment]
I haven't been able to reproduce it (no scanner available here) but might want to give it a try once I have.

**Comment by daN4cat** [comment]
Yes, this needs to be solved before the final release because it's the second report.

**Comment by freemail624** [comment]
after scan the first item
![after scan the first item](https://cloud.githubusercontent.com/assets/6794450/17649392/280d84a0-623d-11e6-924c-a90f8fd87d91.jpg)
after scan the second item
![after scan the second item](https://cloud.githubusercontent.com/assets/6794450/17649394/3a2d726c-623d-11e6-92af-da99de80211b.jpg)

**Comment by daN4cat** [comment]
@freemail624 btw are you using the latest content from dist dir?

**Comment by freemail624** [comment]
Yes I downloaded a fresh copy today and test it then I put my comment here in this issue

**Comment by daN4cat** [comment]
Unusual, the error at the top in the red bar says that style.css is not in dist, but actually it is. That's why I was asking my question.

**Comment by freemail624** [comment]
In the config file I disabled csrf_protection
 $config['csrf_protection'] = False; 
and test scan the barcode it works good
I enable it again then i added sales/add to csrf_exclude_uris 
$config['csrf_exclude_uris'] = array('sales/add');
and it works also
These links helped me
[codeigniter-csrf-error-the-action-you-have-requested-is-not-allowed](http://stackoverflow.com/questions/21214612/codeigniter-csrf-error-the-action-you-have-requested-is-not-allowed)
[csrf](https://www.codeigniter.com/user_guide/libraries/security.html#cross-site-request-forgery-csrf)

**Comment by daN4cat** [comment]
@freemail624 you should not do that at all. The issue with the scanner needs to be solved not with workarounds compromising the security.

**Comment by jekkos** [comment]
Yes disable csrf is a workaround but not a good fix. I'll need to get a hold of a scanner before I can test this issue properly (as I already tried to reproduce it to no avail)

**Comment by daN4cat** [comment]
@Jekkos you should consider a local and non local setup as latencies might play a role.

**Comment by jekkos** [comment]
Still haven't found any opportunity to test with a real scanner.. is this bug still blocking?

**Comment by jekkos** [comment]
@freemail624 from the screencaps it indeed looks like the csrf token isn't updated between requests. Might be a concurrency issue in that case.

**Comment by jekkos** [comment]
Any way latency shouldn't really be an issue as that test was done locally with more than 6 minutes in between..

**Comment by odiea** [comment]
I think I found the correct issue this time. @daN4cat  thanks for the notice.
http://stackoverflow.com/questions/21214612/codeigniter-csrf-error-the-action-you-have-requested-is-not-allowed

**Comment by jekkos** [comment]
@freemail624 One thing I notice is that directly after the add there's another call for the autocomplete function on that field, which isn't logical at all. I tried to reproduce this locally but was never able to reproduce this situation.

Fact is that the response for this autocompete is updating the csrf token, and FF has [http pipelining](https://en.wikipedia.org/wiki/HTTP_pipelining) disabled by default which will ensure that responses are parsed in the same order as how their requests were sent. So in this case the second request might update the token with a wrong value.

I will set a higher delay for the autocomplete (it's set to 10ms now, default is 300) and would like to ask you if you can test whether the solves anything.

**Comment by jekkos** [comment]
Also I added a return false after the submit which might just cancel that second request completely.

**Comment by freemail624** [comment]
Yes you are right , Now it is working good with firefox after your changes
Thanks very much

**Comment by daN4cat** [comment]
@Modding can you please test it too?
