### ISSUE TITLE
How to replace thickbox js with twitter bootstrap modals

### ISSUE THREAD

**Issue by paulkinobunga** [jekkos/opensourcepos#74]
How can I go about replacing thickbox js with twitter bootstrap modals

**Comment by jekkos** [comment]
I guess the application will need some rework.. It might be better to overhaul the complete DOM in this case

**Comment by paulkinobunga** [comment]
ok. I also noticed once twitter bootstrap is added the bootstrap jquery conflicts with the older version jquery in the system. I recommend adding twitter bootstrap as an enhancement in a future release. What do you think

**Comment by jekkos** [comment]
I think current jQuery version is at 1.8.3. It might be further upgraded once the old autocomplete script is upgraded as well. I have done some effort to go up from 1.3 earlier already.

Sure that would be a very nice enhancement. But as I'm not really into webdesign I don't really feel up to this task. If you do than feel more tha

**Comment by paulkinobunga** [comment]
Ok. I will be glad to.
