### ISSUE TITLE
Add Payment Error

### ISSUE THREAD

**Issue by Modding** [jekkos/opensourcepos#740]
If a product or more is scanned right and if i press add Payment the Amount 0,00 is displayed. And you see in the screenshot i cant go further.
![bug](https://cloud.githubusercontent.com/assets/6986957/16809446/a93b5a74-4920-11e6-9d4b-80bb63cc8afc.png)
But if the amount is higher it displays the right amount and the money wich is payed too much and i can go further.
![nobug](https://cloud.githubusercontent.com/assets/6986957/16809627/4a7ccde6-4921-11e6-9408-dbf423b4f90a.png)

**Comment by Modding** [comment]
looks like it cant take amounts with numbers after the ,

**Comment by daN4cat** [comment]
Please explain exactly how to reproduce this. I can't really get how you got there and what the problem is.

**Comment by daN4cat** [comment]
@Modding please we need a reply otherwise we close because I haven't heard anybody else flagging a similar issue.

**Comment by Modding** [comment]
I made you a Video
https://www.youtube.com/watch?v=nFltAWxfan8

**Comment by Modding** [comment]
Server description:
Raspberri PI 3 (My Development system)
OS: Raspberrian
Kernel: Linux version 4.4.13-v7+ 
Server version: Apache/2.4.10 (Raspbian)
PHP: PHP 5.6.22-0+deb8u1

**Comment by Modding** [comment]
I have found the issue ... when you take the locale de_DE you have the numbers like 1.000,99 and the software cant interpret the , (comma).

**Comment by daN4cat** [comment]
OK, good feedback. This is something @jekkos needs to look into.

**Comment by jekkos** [comment]
Probably a missing parse function around that quantity, thanks for reporting this will look into it as soon as I can

**Comment by jekkos** [comment]
I did a fix for this, can you please test and confirm if this works for you?

**Comment by Modding** [comment]
PERFECT! Works!
