### ISSUE TITLE
fatal error on sales module!

### ISSUE THREAD

**Issue by Hashhu** [jekkos/opensourcepos#741]
Message: Class 'NumberFormatter' not found

Filename: helpers/locale_helper.php

Line Number: 29

how to remove this error?

**Comment by odiea** [comment]
You have to enable or Install sudo apt-get install php5-intl or what ever version of php you are using

**Comment by odiea** [comment]
xampp/php/php.ini the following code.

;extension=php_intl.dll remove the ; then restart apache. This worked for me.

**Comment by Hashhu** [comment]
iam using WAMP how to edit these settings in wamp ?Odiea

**Comment by Hashhu** [comment]
i got this line in wamp server and its without ; on my wamp settings. 
so now what to do next ?

**Comment by jekkos** [comment]
Check config page localisation -> locale and open tooltip in browser
