### ISSUE TITLE
Add again location dropdown in the report input screen

### ISSUE THREAD

**Issue by marcofa** [jekkos/opensourcepos#742]
in the "summary items" report it would be necessary to choose the "locations"
can you help me to make the change?

**Comment by jekkos** [comment]
I think we have indeed lost the location dropdown field in the report input section after moving to bootstrap. I just did a quick compare with an older version and it's missing in the code

**Comment by jekkos** [comment]
WIth locations do you mean stock locations or just a custom item attribute? the former should be available in the current version, I mistakenly thought that it was removed.

**Comment by jekkos** [comment]
I've added location dropdown in the input screens for all summary reports. Can you quickly test if everything works fine?

**Comment by odiea** [comment]
Graphical Items Summary Report.

![2016-07-20 12_54_02-wedidit _ powered by ospos 3 0 0](https://cloud.githubusercontent.com/assets/10962177/16999071/62a9fd8c-4e79-11e6-88d0-78f1bad6b510.png)

**Comment by jekkos** [comment]
Ok sorry about that, did a fix forgot to add the location_id in the summary section there

**Comment by odiea** [comment]
It works correctly now.

**Comment by jekkos** [comment]
Ok thanks for testing, I close.
