### ISSUE TITLE
New German Language created

### ISSUE THREAD

**Issue by Modding** [jekkos/opensourcepos#743]
Hi,
i altered the de-CH language and created de.

Can i Upload the change?

Greetings

Valentin

**Comment by daN4cat** [comment]
Thanks for the work.
I suppose you changed the .csv files under translations folder, if so zip those files and post the zip here that we will update the code. I assume this is German from Germany, or somewhere else?

**Comment by Modding** [comment]
i made a new folder for the application/language folder ... i think this is wrong ... and allover again

**Comment by Modding** [comment]
With wich editor you are editing the csv files? Because OpenOffice doesnt takethe commas right.

**Comment by Modding** [comment]
I hope that works. I edited it with LibreOffice

**Comment by Modding** [comment]
https://musiker.cloud/index.php/s/OWU9PTpJnSCFhOy

**Comment by Modding** [comment]
de is german from Germany ... yes

**Comment by daN4cat** [comment]
Please add the zip here because I don't click random links.

**Comment by Modding** [comment]
Sorry i cant ... Github always says it dont support my file.

**Comment by daN4cat** [comment]
OK, so what about adding the csv files or is that limited too?

**Comment by Modding** [comment]
[translations.zip](https://github.com/jekkos/opensourcepos/files/365963/translations.zip)

**Comment by Modding** [comment]
it is another Firefox problem

**Comment by daN4cat** [comment]
Translations added.

**Comment by daN4cat** [comment]
@Modding can you please check the config_lang.php last line and translate Theme in German. You can also just copy the translation here and I can add it to the file.

**Comment by Modding** [comment]
$lang["config_theme"] = "Aussehen";

**Comment by Modding** [comment]
I think in this context it would be more suitible:


$lang["config_theme"] = "Design";

**Comment by daN4cat** [comment]
OK
