### ISSUE TITLE
Item exchange feature

### ISSUE THREAD

**Issue by mubashirsiddique** [jekkos/opensourcepos#745]
I want to implement Item exchange feature. Could anyone please help me to indicate what modules should I address to have an impact of an Item Exchange operation.

**Comment by daN4cat** [comment]
Do you mean a customer returns an item and you exchange it for a new one?
It's already supported. In Sales register select from the dropdown Return, scan the receipt or input the item name, once the item(s) are added move back to sale and sell the replacement item.
Keep going as a normal sale with receipt and etc. Job done.

**Comment by mubashirsiddique** [comment]
yes, exactly.

**Comment by daN4cat** [comment]
So nothing to implement, it's already there.
