### ISSUE TITLE
Question: Use OSPOS simultaneously on two networked systems

### ISSUE THREAD

**Issue by elijahkato** [jekkos/opensourcepos#746]
Please, can i use OSPOS 3.0 simultaneously on two networked systems for sales. Like two cashiers working.

**Comment by odiea** [comment]
Yes you can. I tested that and it works.

**Comment by odiea** [comment]
You use 1 computer as the server then go to the ip address with your browser from a different computer.

**Comment by elijahkato** [comment]
Thanks, I will give it a try.
