### ISSUE TITLE
inventory reports issue.

### ISSUE THREAD

**Issue by MBISEES** [jekkos/opensourcepos#748]
ospos v3.0
hosted to online server.
it is running well. but it cannot generate inventory reports. starting download and fail. 
tried to look download url it looks like this 

> http://error.hosta.eu/403.php?

/> 
please can you suggest annything?

**Comment by daN4cat** [comment]
Tried Low Inventory and Summary Inventory, clicked download CSV and works fine to me.
Could you please explain exactly how to reproduce this and if you are using the latest version or else?

**Comment by MBISEES** [comment]
error 403 in my web host is FORBIDDEN ACCESS

**Comment by MBISEES** [comment]
Page is forbidden 403
The page you are trying to access is private and not accessible with additional permissions.

**Comment by MBISEES** [comment]
thanks it seem there is problem in my server

**Comment by daN4cat** [comment]
Yep, I thought about the same too when I read the other messages.
