### ISSUE TITLE
php error 

### ISSUE THREAD

**Issue by nsk123456** [jekkos/opensourcepos#749]
A PHP Error was encountered
Severity: Warning
Message: Declaration of Employee::save(&$person_data, &$employee_data, &$grants_data, &$employee_id = false) should be compatible with Person::save(&$person_data, &$supplier_data, $person_id = false, &$employee_id = false)
Filename: models/employee.php
Line Number: 367

**Comment by jekkos** [comment]
I guess you are using php 7? Please read setup requirement carefully in README of this project.

Also read section on reporting bugs. We are missing data and so we can't help you with just this erorr report.

**Comment by nsk123456** [comment]
YES IM USING PHP 7..... IS THERE A WAY CAN RECTIFY THIS ERROR MESSAGE ON PHP 7???

**Comment by jekkos** [comment]
Please read server requirements section in the readme. Php 7 is not yet supported. I will close this issue.
