### ISSUE TITLE
Automatic purchase orders for all low inventory

### ISSUE THREAD

**Issue by paulkinobunga** [jekkos/opensourcepos#75]
How can I go about creating automatic purchase orders for low inventory

**Comment by jekkos** [comment]
What do you mean with purchase orders exactly? Do you just want to zero out the quantities in this case? Or add a whole new functionality to do this?

**Comment by paulkinobunga** [comment]
The receiving. here you called them receivings

**Comment by jekkos** [comment]
Ok there is no such functionality for now. You can ofcourse always do this directly using an SQL query.

**Comment by paulkinobunga** [comment]
am not very good at sql. I would appreciate any help on how to archieve this. Thank you
