### ISSUE TITLE
printer issue

### ISSUE THREAD

**Issue by elijahkato** [jekkos/opensourcepos#751]
Hello @jekkos 
I must say weldone thus far. Please i am using a Veeda thermal printer for printing receipts. After printing the first sale, the second sale prints continuously without stopping until I turn off the printer. It has happened frequently. I tried using chrome, Iexplorer and firefox with js addon enabled. Please can you help me fix this.

Thank you

**Comment by elijahkato** [comment]
I think i was left alone to solve my problem myself.. I have successfully configured my printer.. Thanks for the Silence

**Comment by odiea** [comment]
Sorry but the 2 major contributors are currently on a well needed holiday. If you could contribute back  your findings and share with us it may help others.  This is a community based program.

**Comment by elijahkato** [comment]
So sorry i didnt know.. I got the solution from this link.. it helped alot. [http://news.nexpresslibrary.org/go-live/configure-your-receipt-printers/]

**Comment by odiea** [comment]
Thanks for contributing your solution.
