### ISSUE TITLE
Add comment field with payment type 

### ISSUE THREAD

**Issue by akashneelh** [jekkos/opensourcepos#754]
Dear Team,

I have configured three types of payment types 1) Advance 2) Cash 3) Card. Against advance , I hav putting some additional information in comment box while saving the bill. Pls guide how to add comment with Advance payment in receipt print out . It is required only with Advance ,not with cash or card.   example for ....  Advance (NV002 taken on 16-aug-16) : 20000
                                                                                          Cash:  10000

                                                                                            Total: 30000

I am able to print it in adding some codes in views/receipt.php page at the bottom line,but not able to add it with Advance field ..
code added in the page

<?php
		foreach($payments as $payment_id=>$payment)
	{ ?>
		<tr>
		<td colspan="2" style="text-align:right;"><?php echo $this->lang->line('sales_payment'); ?></td>
		<td colspan="2" style="text-align:right;"><?php $splitpayment=explode(':',$payment['payment_type']); echo $splitpayment[0]; ?> </td>
		<td colspan="2" style="text-align:right"><?php echo to_currency( $payment['payment_amount'] * 1 ); ?>  </td>
		
		
	    </tr>
	<?php
	}
	?>
	<td colspan="8" style="text-align:right;"><?php echo $this->lang->line(''). '' .(empty($comments) ? $this->config->item('Money Receipt') : $comments); ?></td>
    <tr><td colspan="6">&nbsp;</td></tr>
    <tr><td colspan="6">&nbsp;</td></tr>

Pls help...

**Comment by akashneelh** [comment]
Any help guys?

**Comment by jekkos** [comment]
So you want to show a default comment once you select a specific payment type? You can do this easily by populating the comments field in the sales controller's _reload function with the desired text once you add a payment' for that specific type.

If you want to populate the comments field immediately after changing the selection (thus before clicking the add payment button), then you'll need to store the comments in a json object in the page. Next add a jquery change listener for the payment type dropdown and lookup the comment using the payment type text as a key in the json object. 

Hope this is more or less what you need.
