### ISSUE TITLE
Errors in Reports and Sales Module (dated : 21-07-2016)

### ISSUE THREAD

**Issue by mohsin5855** [jekkos/opensourcepos#755]
Fatal error: Class 'NumberFormatter' not found in C:\xampp\htdocs\opensourcepos-master\application\helpers\locale_helper.php on line 29

![Uploading image.png…]()

**Comment by odiea** [comment]
Please read the readme.

FAQ

    If a blank page (HTTP status 500) shows after search completion or receipt generation, then double check php5-gd presence in your php installation. On windows check in php.ini whether the lib is installed. On Ubuntu issue sudo apt-get install php5-gd. Also have a look at the Dockerfile for a complete list of recommended packages.

    If the following error is seen in sales module Message: Class 'NumberFormatter' not found then you don't have php5-intl extension installed. Please check the wiki to resolve this issue on your platform.

ca
