### ISSUE TITLE
not calculate tax

### ISSUE THREAD

**Issue by marcofa** [jekkos/opensourcepos#759]
I installed version 3.0, in sales is not taken into account the calculation of taxes, whether they are made in general, that the individual item level

**Comment by odiea** [comment]
See issue #733 to see if this pertains to your issue. It is towards the bottom of the issue.

**Comment by jekkos** [comment]
Sorry for the slow response, my dev laptop os' is screwed up and so I currently have no means to debug this issue. Was trying to fix the former yesterday but didn't get far enough

**Comment by marcofa** [comment]
![2016-07-25_090949](https://cloud.githubusercontent.com/assets/20449443/17088005/b500733c-5247-11e6-9d71-be36d927c723.png)

this is general configuration not have tax (bonus)



![2016-07-25_090709](https://cloud.githubusercontent.com/assets/20449443/17088019/f28dfbb6-5247-11e6-94ad-3dc5f6c8be29.png)

configuration items have tax (bonus) 

![2016-07-25_090854](https://cloud.githubusercontent.com/assets/20449443/17088026/22806480-5248-11e6-9407-6d20343b4ae0.png)

i sell this item ,but not calculate tax(bonus)


before in the old version this is right

**Comment by jekkos** [comment]
Found the culprit, will commit a fix later today

**Comment by jekkos** [comment]
Ok should be fixed now (at least locally). Forgot to reference this issue in the commit properly

**Comment by odiea** [comment]
If you have updated the Master the tax is showing but not the correct amount.
![2016-07-25 11_06_37-wedidit _ powered by ospos 3 0 0](https://cloud.githubusercontent.com/assets/10962177/17110049/15a87ae4-5258-11e6-96f7-5c82fd3e9765.png)

**Comment by jekkos** [comment]
OK I have only tested the behavior with less precision .. guess I need to increase it overall.

**Comment by jekkos** [comment]
OK this case is now rounded using default numberformatter half even mode. In this case result will thus be 4,11

`Rounding mode to round towards the "nearest neighbor" unless both neighbors are equidistant, in which case, round towards the even neighbor. `

**Comment by odiea** [comment]
Working great now.

**Comment by jekkos** [comment]
OK great thanks for the patience and testing effort once again. Wish I could have solved this sooner but just couldn't find the time.

**Comment by odiea** [comment]
No problem I see everything got working for you.

**Comment by jekkos** [comment]
Well more or less, got the environment set up on another machine now. I tried to upgrade ubuntu on my regular laptop but that kind of screwed it up.. Will need to find something to fix that later.
