### ISSUE TITLE
Cannot modify header information

### ISSUE THREAD

**Issue by asadjaved63** [jekkos/opensourcepos#76]
hi
       sir, whenever I try to change Company name from Config after save PHP error, occurs 
A PHP Error was encountered
Severity: WarningMessage: Cannot modify header information - headers already sent by (output started at /home/theheadcom/public_html/baresham/system/core/Exceptions.php:185)Filename: libraries/Session.php
 and when I change manual Company name change from database error disappear ... please tell me how to fix this problem.... thanks in advance....
![download](https://cloud.githubusercontent.com/assets/12225271/7626418/3e0aab22-fa22-11e4-9864-661fd753dd09.png)

**Comment by asadjaved63** [comment]
![untitled](https://cloud.githubusercontent.com/assets/12225271/7633121/a6257ff4-fa6b-11e4-9b52-a49a46f806c1.png)

**Comment by asadjaved63** [comment]
Sir sometime error occurs automatically and if we turn it back it
disappears.. Sometime there is no error.. It keeps on coming and going
randomly..

**Comment by asadjaved63** [comment]
How to fix tell me??

**Comment by jekkos** [comment]
It seems that php has already sent a partial response to the client while the code tries to add information to the headers (probably doing the duplicate cookie check). Have you added any custom code in this routine (like echo, var_dump statements?) In that case remove this and retry.

**Comment by asadjaved63** [comment]
I fixed it... There are whitespace generated... Just remove extra space.

**Comment by jekkos** [comment]
Was this something you caused or is it in the code itself?

**Comment by asadjaved63** [comment]
It's already in code... Whenever I try to upload on server... These errors
occurs

**Comment by jekkos** [comment]
Can you show exactly where you fixed this? MIght be good to do apply it to the codebase here as well.

**Comment by asadjaved63** [comment]
I will upload picture after some time... Sorry I'm in university now

**Comment by asadjaved63** [comment]
How to show? what you prefer upload picture or just code with references?

**Comment by jekkos** [comment]
just the code you changed (file + line number)

**Comment by asadjaved63** [comment]
1: Go to application\controllers/config.php
2: Remove the Space after closing PHP tag 
line # 209

**Comment by jekkos** [comment]
OK thanks I applied this in 7c0f88487271f93fb5839ac31e9218cd32e1a669
