### ISSUE TITLE
Pop Up of Change After Tendering the transaction

### ISSUE THREAD

**Issue by leominojr** [jekkos/opensourcepos#762]
Hello Guys,

I would like to show my appreciation about the POS its very good. But is it okay that I'll request if there's any way that when the transaction is being tendered. It will pop up a modal shows the change and a close button?

**Comment by odiea** [comment]
You can use the following post #557.

**Comment by jekkos** [comment]
Indeed please refer to #557. Feel free to submit a pr for review once you have added this functionaltiy.
