### ISSUE TITLE
Suppliers Report.... 

### ISSUE THREAD

**Issue by mohsin5855** [jekkos/opensourcepos#763]
How Supplier Report Shows Data, My Suppliers Summary Report not showing any record...

Can you please tell me the Steps, how supplier reports get data.
Advance Sorry for this Silly Query....

**Comment by alvin101** [comment]
Just my two cents worth... But sorry to not help the issue.

I think in the design of things that Supplier Reports of any kind belong to the accounting system.  A POS or cash register needs to be simple. A report of sales, returns, and cash reconciliation.

I think a good design in a POS would be to pick a good ERP like frontaccounting and maintain a connect-ability.

**Comment by jekkos** [comment]
Think the supplier report here just aggregates sales of products that have a linked supplier. This way one can quickly see which brand you have sold most during a certain period. If no supplier is selected in any item then I guess this report won't show alot.

**Comment by jekkos** [comment]
@alvin101 indeed a REST api would be nice to have here. But his has been discussed in other issues before #615
