### ISSUE TITLE
Slow searching items on Sales

### ISSUE THREAD

**Issue by jzonetan** [jekkos/opensourcepos#765]
its weird i have great delay on other computer for searching items i was been push to transfer ospos in different pc due i need to fix the pc for maintenance mode...

**Comment by jekkos** [comment]
How many records do you currently have? You might consider to switch to mariadb which should be faster by default (better query optimizer).

Also check you performance statistics in phpMyAdmin. Database performance depends largely on the used configuration and specs of the server it's running on.

**Comment by jekkos** [comment]
Can't really consider this as an ospos issue as it's probably setup related.

**Comment by jzonetan** [comment]
more than 10,000 records already been in pos registered..... seems my laptop specs is not that fast anyways problem solved
