### ISSUE TITLE
How items or any table data loading on a view by using controller and model?

### ISSUE THREAD

**Issue by ipasa** [jekkos/opensourcepos#768]
I want's to understand the application architecture. I am not understand how a table load data using controller and model. i see that here use bootstrap-table plugin, But how this plugin load data from model that i'm not understand. If there any tutorial that helps me to solve this problem that is great for me. And thank you very much @jekkos for this amazing script.

**Comment by jekkos** [comment]
Tables are loaded by the search() method in each controller. The load is triggered through the bootstrap-tables initializer separately for every controller. Just check your network tab in FF or chrome inspector and then you'll see the ajax calls for this URL going out.

**Comment by ipasa** [comment]
Thank you very much @jekkos . I'm understand how data loaded and work.
