### ISSUE TITLE
Upgrade 2.3.4 to 3.0 using wamp server

### ISSUE THREAD

**Issue by odiea** [jekkos/opensourcepos#769]
Hi @jekkos ,

Not sure where I'm supposed to ask questions at?? I'm new to OpenSourcePos, I downloaded the program, and installed it locally using the steps outlined on here. Its working great, but the version I installed is 2.3.4. I'm confused as to how to update to the new 3.0 version? I cannot find anywhere showing me how to do it. Also in ver 2.3.4, when I try and do a backup, I get the following message below:

A Database Error Occurred

Unsupported feature of the database platform you are using.

Filename: C:\wamp\www\opensourcepos\system\database\drivers\mysqli\mysqli_utility.php

Line Number: 82

Can anyone help me to fix this and let me know how to upgrade to the new version.

Thank you in Advance!

**Comment by odiea** [comment]
What I have done in the past is launch phpmyadmin. Select your current database click on the export feature export it. Now create a new database with a different name. Select it then import your old database. Now you can run the upgrades on your test database and see how it works out. If all is ok then you can try it on your old database or change the name in application/config/database to your new database.

**Comment by odiea** [comment]
Yes you will. That is why I am suggesting you use phpmyadmin now.

**Comment by bowhunter26** [comment]
I still cant figure out how to do all this. I'm totally new to php and all, and have no idea what I'm doing. Can someone maybe connect via Remote Control (TeamViewer) and set up this update for me? =)

**Comment by bowhunter26** [comment]
I hope I didn't loose all my stuff??  =(

**Comment by odiea** [comment]
Are you using ospos 3.0 and getting this error?

**Comment by bowhunter26** [comment]
I'm not sure if I did it right. I ran the script in the order 2.3.4 - 2.4 and then 2.4 - 3.0, is that the only thing I'm supposed to do?

**Comment by odiea** [comment]
As far as updating the database you should be good. Now you need to download and install opensourcepos 3.0 unzip it and place it in your www directly if that is what wamp uses. Edit the database config with the required info and you should be good to go. Good luck. Off to bed now.

**Comment by bowhunter26** [comment]
Ok, I got the opensourcePOS 3 extracted to the www directory. Now what do I need to do to edit the database config?

**Comment by onyema3** [comment]
goto Application/Config/ and edit config.php with your database parameters

**Comment by onyema3** [comment]
Sorry Application/Config and edit the database.php

**Comment by bowhunter26** [comment]
I'm confused, as too what I'm supposed to do?  Go to import, then Application/Config, and import the database file?

**Comment by bowhunter26** [comment]
I figured it out, and it working great!!  Thanks @onyema3 !!

**Comment by onyema3** [comment]
You're welcome! Enjoy
