### ISSUE TITLE
on live server error

### ISSUE THREAD

**Issue by asadjaved63** [jekkos/opensourcepos#77]
hello sir,
             on localhost its working very fine... whenever i try to upload on server side,, there are man issue ,after sometime web page not found.... whats is problm help me please... im very thanksfull to you...

**Comment by paulkinobunga** [comment]
thats probably n htaccess problem.

**Comment by paulkinobunga** [comment]
or a directory write permission problem

**Comment by asadjaved63** [comment]
Sir sometime error occurs automatically and if we turn it back it
disappears.. Sometime there is no error.. It keeps on coming and going
randomly..

**Comment by asadjaved63** [comment]
How to fix tell me
