### ISSUE TITLE
Enter does not always update sale line

### ISSUE THREAD

**Issue by bowhunter26** [jekkos/opensourcepos#771]
When I scan an item, the item comes up on the sale list. When I adjust the price the hit enter, the price goes to $0.00. Also if the price does adjust on say item A, and if I scan another item (B) and adjust that price on (B), the price on (A) changes to ) $0.00. Also entering in a negative (-) price does the same thing. Just upgraded to version 3. This did not happen on version 2.3.4. I'm currently down because of this and cannot complete any transaction. Please help! =)

**Comment by odiea** [comment]
What does it do when you click on update?

**Comment by onyema3** [comment]
The update button works fine here

**Comment by onyema3** [comment]
use the update button instead

**Comment by bowhunter26** [comment]
Yes, that works!  Thank you @onyema3 !  I didn't have this issue in 2.3.4, I would just hit enter and that worked.

**Comment by daN4cat** [comment]
Enter should work, this is a bug if not.

**Comment by onyema3** [comment]
@daN4cat  Enter doesn't work

**Comment by odiea** [comment]
@daN4cat Enter only appears to work on the first item entered. After that it does not work in changing the price.

**Comment by jekkos** [comment]
Indeed I think I noticed this issue some time ago as well

**Comment by jekkos** [comment]
Did a fix for this one. Could you verify if it works ok now?

**Comment by odiea** [comment]
Working great here. Happy Bday.

**Comment by bowhunter26** [comment]
How do I go about updating?
