### ISSUE TITLE
Email Sending Problem on Receipt

### ISSUE THREAD

**Issue by ipasa** [jekkos/opensourcepos#772]
I am using version:3.0.0 and the commit number:1c4e5093bfbcec9a5e41f250c9723e58559c253b.
I am install this version on amazon aws instance. When i send a email using gmail SMTP, there occurs an error(Image-1)

![1](https://cloud.githubusercontent.com/assets/2878902/17277531/dd1843d0-5766-11e6-8751-4273cba4c49d.png)

this is my log file when this error occur.

![2](https://cloud.githubusercontent.com/assets/2878902/17277530/dd179016-5766-11e6-85cf-50db83ebd55b.png)

and this is my configuration on store_config/email.
![3](https://cloud.githubusercontent.com/assets/2878902/17277532/dd1dc490-5766-11e6-8621-2d116c5ef7bf.png)

I am also edit my php.ini file on server, set SMTP host & PORT. So i am not understand what is the problem and how to configure this application to send email.

**Comment by onyema3** [comment]
Try port 465 and Encryption SSL

**Comment by daN4cat** [comment]
I wouldn't that Gmail stops SMTP from AWS, AWS is used for spamming purposes and hacking stuff. I blocked all the AWS IP address range from my htaccess to avoid the continuous scanning of my website from AWS.

**Comment by ipasa** [comment]
@daN4cat Any suggestion how can i send email to my customer. How to configure email setting to send email ?

**Comment by daN4cat** [comment]
@ipasa have you tried what @onyema3 suggested?

**Comment by onyema3** [comment]
@ipasa also check this
http://easymail7.com/tutorials/use-amazon-ses-smtp/

**Comment by daN4cat** [comment]
@ipasa any news otherwise I close this issue.

**Comment by petercstevenson** [comment]
I seem to be having the same problem. Should I open another issue? I have tried both an unencrypted smtp server using port 2525 and an SSL-encrypted server using port 465. I am not using gmail; the SSL server is s8-vancouver.accountservergroup.com. Also I have only used the Store Config Email settings; I have not tried changing the php.ini file. Should I?

**Comment by petercstevenson** [comment]
Also, trying to get this to work seems to have flagged my email address as spam. Now it is blocked :(

**Comment by jekkos** [comment]
That's probably the reason why it isn't working. Your smtp server might have been blacklisted.

**Comment by daN4cat** [comment]
@petercstevenson have you sorted this?

**Comment by petercstevenson** [comment]
Sorry, I was having problems getting the ospos software up and running. I tried sending emails again through ospos and I received the error message. My smtp server is no longer blocked, and I have asked ospos to be whitelisted. However, this may not have happened yet. Is there a log somewhere that might give more detailed information about the error?

**Comment by onyema3** [comment]
What email settings are you using?

**Comment by onyema3** [comment]
user port 465 and ssl encryption in your email settings

**Comment by onyema3** [comment]
![email](https://cloud.githubusercontent.com/assets/12876751/18352829/d7cec310-75d7-11e6-96e5-61a9db3bc220.png)

**Comment by petercstevenson** [comment]
Yes, I have been using port 465 and SSL encryption.

**Comment by daN4cat** [comment]
I'll check the email setup in the code and see if something more needs to be exposed in order to be able to send emails.
Another reason could be that your web host is blocking email traffic, but you should check from the server logs or ask them for info about.

**Comment by daN4cat** [comment]
BTW, this is the email configuration and sending code: https://github.com/jekkos/opensourcepos/blob/master/application/libraries/Email_lib.php

Not sure any of this could cause a problem:

```
			'mailtype' => 'html',
			'useragent' => 'OSPOS',
			'validate' => TRUE,
```

**Comment by petercstevenson** [comment]
Thank you, @daN4cat. I have sent this link to the email host (site5) and once I am sure that ospos is whitelisted I will test again.

**Comment by daN4cat** [comment]
Documentation of the email class is here: http://www.codeigniter.com/user_guide/libraries/email.html?highlight=email

BTW, mailtype cannot be an issue. Maybe there is a timeout problem, do you get the error message after 5 seconds?

**Comment by petercstevenson** [comment]
I don't think this is a timeout issue. The error message comes right away, even if I set the timeout for 60 seconds.

**Comment by daN4cat** [comment]
So it must some local block in your hosting.
Let me know if your web host provider replies to your query and what they said.

**Comment by daN4cat** [comment]
@petercstevenson I might know where your problem is coming from. Have you set any email address in your Store Config? Because if you didn't that's the reason why sending emails fails.
I need to improve this error reporting as it's not that obvious.

**Comment by daN4cat** [comment]
If that's not the reason of the failure I added a logging to error_log in case of email sending failure, so check the root if any files appears after you tried to send an email.

**Comment by petercstevenson** [comment]
I had my email set in Store Config, so it isn't that. Where do I find the error log?

**Comment by daN4cat** [comment]
In the root of Palos installation, where you see application, system, etc. dirs

**Comment by petercstevenson** [comment]
I looked around in my Digital Ocean server, and it seems like the application was installed in /var/lib/docker/aufs/mnt/[long_hexidecimal_number]/app/

Does that sound right? If so, I do not see any new files, changes, or logs.

**Comment by daN4cat** [comment]
ok, I will need to check why the error log is not created.
It might be because it's marked production and not development anymore that we can't see the file.

**Comment by daN4cat** [comment]
What you can try to do is edit index.php and change the following lines:

```
//	define('ENVIRONMENT', isset($_SERVER['CI_ENV']) ? $_SERVER['CI_ENV'] : 'development');
	define('ENVIRONMENT', isset($_SERVER['CI_ENV']) ? $_SERVER['CI_ENV'] : 'production');
```

to be

```
	define('ENVIRONMENT', isset($_SERVER['CI_ENV']) ? $_SERVER['CI_ENV'] : 'development');
//	define('ENVIRONMENT', isset($_SERVER['CI_ENV']) ? $_SERVER['CI_ENV'] : 'production');
```

and try to send an email again and see if the error_log file is created.

**Comment by jekkos** [comment]
@petercstevenson You should look inside the containers themselves. First list currently running containers using `docker ps`. Then open a shell inside the php one (which probably holds the log file)

**Comment by petercstevenson** [comment]
None of the containers listed in `docker ps` or `docker-cloud container ps` have php listed anywhere. Do you mean the web server?
I have tried editing the index.php file in the web server container as instructed and tried sending an email again. Still no log file in the container. Do I need to redeploy the server to make the changes take effect?

**Comment by jekkos** [comment]
Yes the web server indeed. Can you perhaps just add the debugger statement in the email sending code somewhere? In this case that would be in the Sales controller (receipt method) so that the application prints out the debugger info when sending email? 

I might want to add that functionality by default (eg when specifying ?debug=true)

**Comment by daN4cat** [comment]
@jekkos the sending error at the moment is logged in the error_log, however in composer branch I don't know anymore where the error_log file is supposed to be.
With master it used to be in OSPOS root. I'll check more about this issue later.

**Comment by petercstevenson** [comment]
I have heard back from my provider, and they said that they have fixed the problem on their end. However, I still have the same problem. They also said to make sure that the emails need to be sent out using full SMPT authorization (https://kb.site5.com/email/smtp-authentication-at-site5/). However, this shouldn't be a problem with OSPOS, should it?

**Comment by daN4cat** [comment]
@petercstevenson I read like you need to have username and password for your SMTP account as means to authenticate you. And that is supported yes.

Also make sure you have the correct mail server name, encryption (TSL/SSL) and port are correct.
But it looks like SSL & 465 are supported reading a bit the online documentation, so check the mail server.
Another way to test your configuration is to check using a mobile phone application where you set manually the configuration and test it works fine.

**Comment by daN4cat** [comment]
If mobile phone email client works and OSPOS with the same setting doesn't, please go to application/libraries/Email_lib.php and in line 16 you can find  `'validate' => TRUE,`, try to set it FALSE and let me know if that makes a difference.
If that's the case I will add it to the Store Config set of params.

**Comment by daN4cat** [comment]
@petercstevenson have you managed to succeed? Did you need to change the value of the flag I mentioned?

**Comment by daN4cat** [comment]
@petercstevenson I would really close this knowing only if I need to add that boolean to the Store Config or not.

We are just two issues away and few translations to release 3.0.0.

**Comment by petercstevenson** [comment]
It still doesn't work. And I have had no problems with using different clients (including on my mobile phone) to send emails

**Comment by gkapaino** [comment]
bro... can i have authority to put this system online? or only for local?

**Comment by gkapaino** [comment]
the how should i record loan transaction?

**Comment by daN4cat** [comment]
@petercstevenson have you tried to change the flag I mentioned earlier?

**Comment by petercstevenson** [comment]
Yes, I changed it. Will it update OSPOS right away or do I need to update something manually (restart apache, redeploy the container, etc)?

**Comment by daN4cat** [comment]
Just refresh the page where you are and click send email again.

**Comment by daN4cat** [comment]
@petercstevenson I move this out of the picture because we cannot hold 3.0.0 release forever.
Unless you can provide some feedback and I don't get more complaints I consider this a specific issue with your installation.

**Comment by petercstevenson** [comment]
I'm sorry, I have been waiting for further instruction on debugging this problem. I have tried all of the suggestions so far and I still have the problem. Is there any more information on where I might be able to find the error_log?

**Comment by jekkos** [comment]
Hm I think I wrote somewhere that there is currently no sending email support in docker container. The needed configuration is not done. However it could be solved by mapping the required ports to the host container in this case.

**Comment by jekkos** [comment]
Think I'll try to add sendmail to the container and see if that does anything

**Comment by daN4cat** [comment]
@jekkos thanks, I really cannot see what else could be. I'm trying to sort out the other bug at the moment so we close this release.

**Comment by jekkos** [comment]
@petercstevenson I have just added sendmail to the docker container. Can you try and test with the latest version to see if it works now? (I did not test myself yet)

**Comment by daN4cat** [comment]
@jekkos it looks like I need to learn a bit more of dockers packaging. Indeed without sendmail support it cannot work if things are properly sandboxed.

**Comment by petercstevenson** [comment]
It still does not work. This is not a critical bug for me (I just save the receipt as a PDF and then email it) so if this waits until a later release I don't mind.

**Comment by jekkos** [comment]
I think with this sendmail setup you should connect to an external smtp. What configuration are you using currently? Local connections will probably not work (as there is no smtp in the container)

**Comment by petercstevenson** [comment]
I'm not sure what you mean. I have attached  a screenshot. Is there more setup information that you need from me?
![screenshot](https://cloud.githubusercontent.com/assets/21316584/19498092/37c82780-9544-11e6-8350-69d5638f21e6.png)

**Comment by daN4cat** [comment]
@petercstevenson please select sendmail from the protocol list and give a try.

**Comment by petercstevenson** [comment]
Still does not work

**Comment by daN4cat** [comment]
@petercstevenson this seems to be a Docker on AWS issue, see: http://stackoverflow.com/questions/26215021/configure-sendmail-inside-a-docker-container

Probably you need to follow those suggestions to get the issue sorted but it's beyond OSPOS as application.

**Comment by petercstevenson** [comment]
OK, if this is not going to work out-of-the-box then it should be noted somewhere in the documentation. I can add it to the wiki but I think that the best place to is at the end of the Cloud Install Using Docker section on the main github page.
