### ISSUE TITLE
XAMPP Recommended Version

### ISSUE THREAD

**Issue by leominojr** [jekkos/opensourcepos#773]
Hello Good Day,

I'm still getting problems installing ospos in my local server 
![capture](https://cloud.githubusercontent.com/assets/9472129/17301777/6d5b7f22-584b-11e6-94cb-6d0818fb2fe7.PNG)
What xampp version do you recommend to fix these errors. All times I add customer it doesn't displays the entire form only the modal.

**Comment by daN4cat** [comment]
Please read the FAQ first: https://github.com/jekkos/opensourcepos#faq
