### ISSUE TITLE
Supported Thermal Printer?

### ISSUE THREAD

**Issue by asakpke** [jekkos/opensourcepos#774]
What are the supported thermal printers if we goes with Linux?

**Comment by odiea** [comment]
I would think that most printers that work with Linux would work with OSPOS. All you do is try.

**Comment by asakpke** [comment]
Does anybody knows the list of thermal printer that are supported on Linux Mint/Ubuntu/Debian?

**Comment by daN4cat** [comment]
I'm afraid no

**Comment by ashishkaushik** [comment]
https://www.amazon.in/gp/product/B010Q2IG84/ref=ask_ql_qh_dp_hza

Will this work with OSPOS ?

**Comment by asakpke** [comment]
@ashishkaushik It should work on following OS as mentioned at your given link, you just need drivers and some printer settings. 
Operating System: win 2000, win 2003, win XP, win vista, win 7, win 8, win 10, Linux
