### ISSUE TITLE
Enter does not update receive line

### ISSUE THREAD

**Issue by sweet3025** [jekkos/opensourcepos#775]
Hi, I am using version 3
When I scan an item, the item comes up on the receive list. When I adjust the price and hit enter, Enter only appears to work on the first item entered. After that it does not work in changing the price.

BTW    The update button works fine here.

A similar issue was in sales Line. 
Issue #771

**Comment by onyema3** [comment]
That was fixed, take the latest masters and try again

**Comment by sweet3025** [comment]
Thanks for your quick reply. Yes, it was fixed for the **sales module**. The bug is still there in the **Receive module**.

**Comment by odiea** [comment]
Thanks for reporting this. We have a tendency to just test the modules we use most frequently.

**Comment by onyema3** [comment]
True, just tested and receiving still has the bug

**Comment by odiea** [comment]
If you cant wait for the commit you can go to application/views/receivings/receiving.php and replace line 491 with the fix for register.
$(this).parents("tr").prevAll("form:first").submit();

**Comment by onyema3** [comment]
@odiea you beat me to it....that the fix

**Comment by jekkos** [comment]
You're right receivings module is often overlooked. Will add the fix there as well.

**Comment by daN4cat** [comment]
Fixed and in master.

**Comment by sweet3025** [comment]
Awesome Support :+1:
