### ISSUE TITLE
Fatal error: Can't use method return value in write context in C:\wamp\www\opensourceposmaster\application\helpers\locale_helper.php on line 67

### ISSUE THREAD

**Issue by CTO1966** [jekkos/opensourcepos#776]
A PHP Error was encountered
Severity: Compile Error
Message: Can't use method return value in write context
Filename: helpers/locale_helper.php
Line Number: 67
Backtrace:
67 code is 
if (empty($config->item('thousands_separator')))

please fixed this issue

**Comment by odiea** [comment]
You can use notepad ++ and open application/helpers/locale_ helper and replace line 67and 68 with the following and see if it changes anything.
$sep = $config->item('thousands_separator');
	if (empty($sep))
I got the idea from here http://stackoverflow.com/questions/17139264/cant-use-function-return-value-in-write-context

**Comment by CTO1966** [comment]
Thank You for your Ripley 
Line 67 i use your code($sep = $config->item('thousands_separator');
if (empty($sep)) ) -Login page now open but - sale page link new error 

Fatal error: Class 'NumberFormatter' not found in C:\wamp\www\opensourceposmaster\application\helpers\locale_helper.php on line 29
A PHP Error was encountered
Severity: Error
Message: Class 'NumberFormatter' not found
Filename: helpers/locale_helper.php
Line Number: 29
Backtrace:

29 code is 
 {
    return to_decimals($number, 'currency_decimals', \NumberFormatter::CURRENCY);
}

please fixed this issue

**Comment by daN4cat** [comment]
@CTO1966 please read the FAQ: https://github.com/jekkos/opensourcepos#faq

**Comment by daN4cat** [comment]
Also please note that PHP 5.5 is required and in any case recommended as 5.4 is obsolete and not supported.

**Comment by CHRISBAAH** [comment]
public function get_many_by()
    {
        $where = & func_get_args();
        $this->_set_where($where);

        return $this->get_all();
    }


THE ABOVE CODE BRINGS THE ERROR BELOW, any ideas?
A PHP Error was encountered
Severity: Compile Error

Message: Cannot use result of built-in function in write context

Filename: core/MY_Model.php

Line Number: 182

Backtrace:
