### ISSUE TITLE
Can't add Item/Customer/Supplier

### ISSUE THREAD

**Issue by Muazm87** [jekkos/opensourcepos#778]
Can't add Item/Customer/Supplier.

When I click on New Item a new box opens up with a blue Header "New Item" and the footer "New" & "Submit" nothing inbetween.

**Comment by daN4cat** [comment]
Version of your web server, php and etc. please.

Also make sure you read the readme before coming here to ask for help.

**Comment by RodolfoLopez** [comment]
I had this issue, also an error on the Config/Localization page: 
> Class 'NumberFormatter' not found

(witch is mentioned on the Readme.md)
Both of them where 'fixed' once I installed/enabled the php-intl extention, by uncommenting it on php.ini:
` ;extension=php_intl.dll`
and reloading the server.

Now I can add items properly.

**Comment by daN4cat** [comment]
Good. @jekkos @odiea what did I say a month ago about all the issues report about that change? Lost the count of people flagging it....

**Comment by odiea** [comment]
So should this commit be reverted and added to a future release or should the requirements be the first thing a person should read about on the ft page ?

**Comment by daN4cat** [comment]
What's done is done. We just need to live with it or improve the template of issues posting. Maybe that makes more sense to avoid the repetition of the same question.

**Comment by jekkos** [comment]
Yes indeed think that would be a first step in the right direction.
