### ISSUE TITLE
Enhancement for Github Issues.

### ISSUE THREAD

**Issue by odiea** [jekkos/opensourcepos#779]
https://github.com/blog/2111-issue-and-pull-request-templates

**Comment by daN4cat** [comment]
Added the issue report template, please check and let me know if looks fine or else.

**Comment by odiea** [comment]
Looks god but I would also note that the following extensions need to be installed.
Is php5-intl extension in php.ini enabled.
Is php5-gd installed.

**Comment by daN4cat** [comment]
That's in the FAQ

**Comment by odiea** [comment]
Apparently not a lot of people have been reading the Faqs.

**Comment by daN4cat** [comment]
That's why is a checkbox.

**Comment by odiea** [comment]
I take it the template is not live yet?

**Comment by daN4cat** [comment]
It's live, there is no other way.

**Comment by daN4cat** [comment]
Let's continue on #786
