### ISSUE TITLE
Skip confirm dialog when saving a sale

### ISSUE THREAD

**Issue by katkevelaers** [jekkos/opensourcepos#784]
When saving a sale I'd like to bypass the confirm dialog and go directly to printing the receipt.  Can you tell me where I can do that?
Thx

**Comment by daN4cat** [comment]
Use Firefox and jsprinter, you can configure jsprinter in Config Store and print straight your receipt without additional clicks

**Comment by katkevelaers** [comment]
Thanks for your reply, but when I use firefox and jsprinter, nothing is
printed at all, that's why I wanted to use Chrome.

**Comment by daN4cat** [comment]
Have you configured jsprinter properly and even in Store Config?

With Chrome you can avoid the print dialog only if you run it in kioskmode, there is #717 covering that.

**Comment by katkevelaers** [comment]
Yes, I did, but it is the dialog box that asks me to confirm saving the
sale, before moving on to printing.  I do run Chrome in Kiosk mode and that
works fine.  I use it in Dutch so maybe I don't use the right translations,
but when finishing a sale I first click 'pay', than 'confirm' and then a
dialog box pops up to ask the user to confirm again.  Only after clicking
in that box, the printing process starts. It is that step I would like to
skip.
Thanks again,
Katelijne

**Comment by odiea** [comment]
This sounds like an earlier version. What version are you using?

**Comment by katkevelaers** [comment]
I'm using
2.3.4

**Comment by daN4cat** [comment]
Maybe it's better to upgrade to 3.0.0 as you'll get better support.
We are not that far from releasing it, just few things to finish off and test.

**Comment by jekkos** [comment]
@katkevelaers dutch (flemish) speaker? Coincidentally having a business around Leuven? Might indeed be better to upgrade to 3.0 first.

**Comment by katkevelaers** [comment]
thanks i will!

**Comment by daN4cat** [comment]
@jekkos it looks like this Kat rings a bell...

**Comment by katkevelaers** [comment]
@jekkos .... yes indeed

**Comment by jekkos** [comment]
Always interesting to know how this system is being used ( and in which context ) .. If in need of anything then feel free to drop me a line

**Comment by katkevelaers** [comment]
Thx!  Will do.
