### ISSUE TITLE
Enhancement for Github Issues using the provided Template.

### ISSUE THREAD

**Issue by odiea** [jekkos/opensourcepos#786]
Before submitting an issue please make sure you tick and agree all the following check boxes:

- [ ] Checked the current issues database and no similar issue was already discussed
- [ ] Read the README, WHATS_NEW and UPGRADE
- [ ] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas
- [ ] Reporting an issue of an unmodified OSPOS installation
- [ ] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [ ] PHP version is at least 5.5 and not 7.x
- [ ] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [ ] Know the name and version of OS, Web server and MySQL and will add to my issue report

### Steps to reproduce the issue

**Comment by odiea** [comment]
To get this template to work properly you must start a new issue at the bottom of the template you must press the button then you can fill out the form. After filling out the form I guess then you make an additional comment

**Comment by daN4cat** [comment]
You can even fill in the template straight away adding x between the square brackets to get it checked. Maybe I should add that hint?

**Comment by odiea** [comment]
I think I was expecting the form to appear like the Completed form above with the  submit button at the bottom of the completed form.

**Comment by daN4cat** [comment]
Unfortunately it doesn't look like, but I'll read more the help. However the example in the guide looks the same. Happy to find a better way if you have any suggestion.

**Comment by odiea** [comment]
Your doing a great job. Thanks. You can only work with what you got.
