### ISSUE TITLE
Item update form did not recognize Arabic numbers script as Numbers

### ISSUE THREAD

**Issue by aelhofy** [jekkos/opensourcepos#788]
Before submitting an issue please make sure you tick (add a x between the square brakets) and agree all the following check boxes:

- [x] Checked the current issues database and no similar issue was already discussed
- [x] Read the README, WHATS_NEW and UPGRADE
- [x] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas
- [x] Reporting an issue of an unmodified OSPOS installation
- [ ] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [x] PHP version is at least 5.5 and not 7.x
- [x] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [x] Know the name and version of OS, Web server and MySQL and will add to my issue report

IMPORTANT: If you remove the template when submitting an issue your issue will be closed.

### Installation information
Bitnami LAMP 5.6.24-0 (64-bit) (ubuntu 14.04, Apache, Mysql  and PHP 5.6)

Localization is the ar-EG (and any Arabic local)

### Expected behaviour
when click on update item and update description for example and then click submit it shall update normally 

### Actual behaviour

when click submit even without make any changes form validation errors appears and telling cost, retail price...etc must be a number while actually they are but the numbers appears in Arabic script as per Localization

### Steps to reproduce the issue

- make Localization ar-EG
- Got to Items and click edit then just click submit (without even modify any thing), then red error messages will appears telling that cost, retail price...etc must be a number

the following link show how Arabic numbers script looks like:

https://en.wikipedia.org/wiki/Hindu%E2%80%93Arabic_numeral_system

**Comment by jekkos** [comment]
Just did a quick test and indeed, when setting the ar_EG locale javascript validation fails on the number format

**Comment by daN4cat** [comment]
@jekkos can you solve it easily and test it or is it a difficult one?

**Comment by jekkos** [comment]
It will be a matter of adapting the jquery validation rule to pass for arabic characters.. will try to solve that later today.

**Comment by jekkos** [comment]
I'll solve this by doing numeric validation on the server side using numberformatter (as for arabic some special characters are used instead of digits). This was the primary reason to include php-intl.. it should support parsing and validation of those exotic locales out of the box.

Only disadvantage is that the validation is a little slower in the items forms as there are four extra ajax calls done when hitting the submit button.

**Comment by aelhofy** [comment]
Could it help if we convert the input to text and take out the special characters (is it thousands seprator and decimal point?) and then convert it again to number and validate at client side

**Comment by jekkos** [comment]
I think I have a solution ready, I might push to a separate branch for you to test first.

**Comment by jekkos** [comment]
Can someone that preferably undestands arabic confrim that the validation is working now?

**Comment by aelhofy** [comment]
Hello as a someone

Just now tested it and it seems working

Thanks
