### ISSUE TITLE
Can you please remove "bower_components" from gitignore?

### ISSUE THREAD

**Issue by debrajn** [jekkos/opensourcepos#789]
Hi,

Can you please remove "bower_components" from gitignore? So, that I can debug the site and try to get better solution.

Thanks
Deb

**Comment by odiea** [comment]
You did not fill out the template so I will close this issue.

**Comment by daN4cat** [comment]
In any case we don't commit bower_components to our master, so it stays in gitignore

**Comment by jekkos** [comment]
You can use the docker container to load up the dependencies, check the wiki section and development setup for that.

**Comment by jekkos** [comment]
And indeed it doesn't make sense for us to commit all the source to this repo

**Comment by debrajn** [comment]
Thank you Jekkos for your support. My requirement was just to work with without minified js and css. "bower_components" contains all the js and css where we can view the source code. Anyway if it's not possible to provide then not an issue I will manage.

Thank you

**Comment by daN4cat** [comment]
Install npm, grunt and bower and you get all those components on your pc.
