### ISSUE TITLE
[Question] Date and Time 

### ISSUE THREAD

**Issue by MexasPT** [jekkos/opensourcepos#791]
Hi,
I need to know how to add time in reports . Currently the reports show only the date and needed some help to change the current code.
Example : Date + Time = 11/11/2016 20:30

Thanks

![date_time](https://cloud.githubusercontent.com/assets/17734465/17538044/b5ef0bce-5e99-11e6-9109-afd963325717.png)

**Comment by odiea** [comment]
You did not fill out the template so I will close this issue.
