### ISSUE TITLE
[Question] Date and time

### ISSUE THREAD

**Issue by MexasPT** [jekkos/opensourcepos#792]
Before submitting an issue please make sure you tick (add a x between the square brakets) and agree all the following check boxes:
- [x] Checked the current issues database and no similar issue was already discussed
- [x] Read the README, WHATS_NEW and UPGRADE
- [x] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas
- [ ] Reporting an issue of an unmodified OSPOS installation
- [ ] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [x] PHP version is at least 5.5 and not 7.x
- [x] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [x] Know the name and version of OS, Web server and MySQL and will add to my issue report

IMPORTANT: If you remove the template when submitting an issue your issue will be closed.
### Installation information

OS - Linux
Web server - Apache

OSPOS Version 2.4.0
### Expected behaviour

Show date with time
### Actual behaviour

Help!
I need to know how to add time in reports . Currently the reports show only the date and needed some help to change the current code.
Example : Date + Time = 11/11/2016 - 20:30

Thanks
### Steps to reproduce the issue

Reports -> Generate a report

![date_time](https://cloud.githubusercontent.com/assets/17734465/17546808/c72980b2-5edb-11e6-87f2-bb6e9edad59d.png)

**Comment by daN4cat** [comment]
@MexasPT it's probably better to consider 3.0.0 as it's quite mature and have many more features than the old 2.x

**Comment by MexasPT** [comment]
Can I upgrade or i have to install it again?

**Comment by daN4cat** [comment]
There is an upgrade script 2.4 to 3.0.

**Comment by daN4cat** [comment]
I mean database one.
