### ISSUE TITLE
Error em receivings

### ISSUE THREAD

**Issue by arteiro** [jekkos/opensourcepos#797]
Um erro no Banco de Dados aconteceu

Error Number: 1054

Unknown column 'reference' in 'field list'

INSERT INTO `ospos_receivings` (`supplier_id`, `employee_id`, `payment_type`, `comment`, `reference`) VALUES ('3', '1', 'Dinheiro', 'te', '')

Filename: C:/www/OSPOS/system/database/DB_driver.php

Line Number: 691

**Comment by daN4cat** [comment]
Run the database script update 2.4 to 3.0
