### ISSUE TITLE
Delete Entire Sale 

### ISSUE THREAD

**Issue by diganto213** [jekkos/opensourcepos#80]
Hello Jekkos,

It seems Delete Entire Sale option under Sales Overview does not update the original product inventory back. 

Is there any reason or it is a bug ?

Thank You

**Comment by jekkos** [comment]
The functionality should be foreseen and I think this issue has been raised and tackled in the past. But if it's not behaving as expected then an extra code check won't hurt I guess.

**Comment by diganto213** [comment]
Yep sure.
