### ISSUE TITLE
Most of the functions / tabs under 'Config Module' are not working/

### ISSUE THREAD

**Issue by RamkrishnaMondal** [jekkos/opensourcepos#801]
![screenshot from 2016-08-12 00 46 15](https://cloud.githubusercontent.com/assets/14151032/17601612/9f9844ce-6026-11e6-9b46-538753ed1272.png)

**Comment by RamkrishnaMondal** [comment]
Sales and Receiving modules are also showing error...
![screenshot from 2016-08-12 00 51 16](https://cloud.githubusercontent.com/assets/14151032/17601687/01768444-6027-11e6-9ce5-26275862bb66.png)
![screenshot from 2016-08-12 00 51 31](https://cloud.githubusercontent.com/assets/14151032/17601691/056773e2-6027-11e6-89da-937279513bae.png)

**Comment by onyema3** [comment]
php intl extension not installed

**Comment by RamkrishnaMondal** [comment]
Yea..... that was the problem... thanks.
