### ISSUE TITLE
How to get bower components for local install

### ISSUE THREAD

**Issue by aelhofy** [jekkos/opensourcepos#802]
Before submitting an issue please make sure you tick (add a x between the square brakets) and agree all the following check boxes:

- [x] Checked the current issues database and no similar issue was already discussed
- [x] Read the README, WHATS_NEW and UPGRADE
- [x] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas
- [x] Reporting an issue of an unmodified OSPOS installation
- [ ] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [x] PHP version is at least 5.5 and not 7.x
- [x] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [x] Know the name and version of OS, Web server and MySQL and will add to my issue report

IMPORTANT: If you remove the template when submitting an issue your issue will be closed.

### Installation information
Bitnami ubuntu lamp 5.6

### Expected behaviour
To have all those assets mentioned in header.php  in a local folder

### Actual behaviour
There is no folder with those assets mentioned in header.php

### Steps to reproduce the issue

Make a local install

**Comment by daN4cat** [comment]
https://github.com/jekkos/opensourcepos/wiki/Development-setup
