### ISSUE TITLE
Cash Drawer

### ISSUE THREAD

**Issue by jowinlee** [jekkos/opensourcepos#803]
Before submitting an issue please make sure you tick (add a x between the square brakets) and agree all the following check boxes:

- [x] Checked the current issues database and no similar issue was already discussed
- [x] Read the README, WHATS_NEW and UPGRADE
- [x] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas
- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [x] PHP version is at least 5.5 and not 7.x
- [x] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [x] Know the name and version of OS, Web server and MySQL and will add to my issue report

IMPORTANT: If you remove the template when submitting an issue your issue will be closed.

### Steps to reproduce the issue

**Comment by daN4cat** [comment]
@jowinlee and the question or issue is?

**Comment by jowinlee** [comment]
Is it possible to add a function for auto open cash drawer after a sale?

**Comment by jowinlee** [comment]
Btw, Im sorry, I've failed to mention it

**Comment by daN4cat** [comment]
Usually the cash drawer pulse cable is connected to the receipt printer.
It's under the control of the printer, so the printer driver not OSPOS can configure the opening of the cash drawer.

**Comment by izeblood** [comment]
@daN4cat How about opening a cash drawer in sales module? The value of the transactions, including due/change of amount will not be appear in printing...so it is significant if we can add buttons to open cash drawer in sales module before clicking complete button
