### ISSUE TITLE
Customer name is not appearing on Receipt and Invoice

### ISSUE THREAD

**Issue by aelhofy** [jekkos/opensourcepos#804]
Before submitting an issue please make sure you tick (add a x between the square brakets) and agree all the following check boxes:

- [x] Checked the current issues database and no similar issue was already discussed
- [x] Read the README, WHATS_NEW and UPGRADE
- [x] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas
- [x] Reporting an issue of an unmodified OSPOS installation
- [ ] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [x] PHP version is at least 5.5 and not 7.x
- [x] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [x] Know the name and version of OS, Web server and MySQL and will add to my issue report

IMPORTANT: If you remove the template when submitting an issue your issue will be closed.

### Installation information
ubuntu 14.04.5 , php 5.5 and mysql

 OSPOS 3.0.0 - 1c4e5093bfbc

### Expected behaviour
Customer name is appearing on sale after selection

### Actual behaviour
Customer name is not appearing on sale after selection

### Steps to reproduce the issue

[prints.zip](https://github.com/jekkos/opensourcepos/files/416149/prints.zip)
make a sales and select a customer

**Comment by odiea** [comment]
Have you altered your Receipt or Invoice or made other alterations to the program? Here is what the English version looks like. No issues here. The names appear properly.
![2016-08-12 14_52_36-action center](https://cloud.githubusercontent.com/assets/10962177/17636842/0c0c314e-609d-11e6-969d-0a2198711ee5.png)
![2016-08-12 14_54_09-program manager](https://cloud.githubusercontent.com/assets/10962177/17636845/0f45ff16-609d-11e6-8d0b-39efa205d847.png)

**Comment by odiea** [comment]
If you changed the receipt_default you should go back and make sure the following is there and properly changed.
if(isset($customer))
		{
		?>
			<div id="customer"><?php echo $this->lang->line('customers_customer').": ".$customer; ?></div>
		<?php
		}
		?>
```

**Comment by aelhofy** [comment]
I did not change any thing

This un-modified installation except that the theme direction is from right to left

**Comment by odiea** [comment]
From what I can see in this image is the appearance of the customer name with the : in front of it instead of behind it like the rest of the image shows. I would open receipt_default and make sure it is still there.
![2016-08-12 19_38_34-microsoft edge](https://cloud.githubusercontent.com/assets/10962177/17640754/6910b686-60c4-11e6-8939-e6531e4d8b3e.png)

**Comment by aelhofy** [comment]
I checked without  theme converted to right to left and same result customer is not appearing, no code changes.
Now using:
OSPOS 3.0.0 - 84033699675e

**Comment by daN4cat** [comment]
What is the customer name?

**Comment by aelhofy** [comment]
Bob

**Comment by daN4cat** [comment]
Just first name? It's important to know to simulate the same test case.

I assume English is the selected language.

**Comment by aelhofy** [comment]
it is the default customer, arabic is selected, however it is the case even with english selected

**Comment by aelhofy** [comment]
I tried with name written in Arabic and language is Arabic it is OK

**Comment by daN4cat** [comment]
So it's some sort of combination that doesn't work. I'll try later standard installation and English but @odiea already said it's fine. So you need to tell us which combination is not fine.

**Comment by jekkos** [comment]
Maybe it's the right to left that breaks css for the customer field?

**Comment by daN4cat** [comment]
I tested and I can see the customer name, so must be something peculiar with @aelhofy "alchemy".

I wouldn't treat this as a bug because the standard code works fine.

**Comment by aelhofy** [comment]
I tested with every thing English and actually the name is not appearing on sales on the first place so it is not printed

![screenshot from 2016-08-13 15 09 10](https://cloud.githubusercontent.com/assets/3656317/17643110/5727b81c-6168-11e6-90a4-c59f55f4e0bc.png)

**Comment by daN4cat** [comment]
Yes, but still with a reversed UI.

**Comment by aelhofy** [comment]
I added one more customer, written in English and every thing is fine , the problem is with the customer I imported only , I hope there is no problem with import

**Comment by daN4cat** [comment]
This looks like being an issue with your installation. It might be that the first char in the name is a \n so you don't see the name.

**Comment by intermilis** [comment]
I found this issue when i import customer from csv. But it can be resolved by edit the customer and save, without change anything.

**Comment by daN4cat** [comment]
@intermilis what is exactly the issue you see?

**Comment by daN4cat** [comment]
BTW, import of csv files from Mac proved to be problematic, I wouldn't it's a similar case?

**Comment by intermilis** [comment]
I still checking this problem. Once  i found the cause, i will share.

**Comment by Saiuke** [comment]
How can I show the costumer account number right below the costumer name in the receipt? Assuming, of course, that I have to modify the default_receitp.php.

**Comment by mckaygerhard** [comment]
default_receip its your view?

**Comment by Saiuke** [comment]
Yeah... But, already got it. Thanks.
Just added this line after the line 39 in the receipt_default.php:

`<div id="customer"><?php echo $this->lang->line('customers_account_number').": ".$customer_account_number; ?></div>`

Turns out my first aproach was correct all the time. It was some sort of typping error or something.
