### ISSUE TITLE
Is there a way to limit nominatim.init suggestions.

### ISSUE THREAD

**Issue by odiea** [jekkos/opensourcepos#805]
Before submitting an issue please make sure you tick (add a x between the square brakets) and agree all the following check boxes:

- [x] Checked the current issues database and no similar issue was already discussed
- [x] Read the README, WHATS_NEW and UPGRADE
- [x] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas
- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [x] PHP version is at least 5.5 and not 7.x
- [x] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [x] Know the name and version of OS, Web server and MySQL and will add to my issue report

IMPORTANT: If you remove the template when submitting an issue your issue will be closed.

### Installation information
Multiple lamp and wamp servers
Open Source Point Of Sale Version 3.0.0 - 1c4e5093bfbc.

### Expected behaviour
Limit suggestions because now there are 2 to 3 of the same suggestion when entering zip code

### Actual behaviour
Multiple suggestions of the with same name .
The same suggestions are shown 2 to 3 times.

### Steps to reproduce the issue
Enter a Zip code in Customer form.

**Comment by odiea** [comment]
![2016-08-12 18_35_16-greenshot](https://cloud.githubusercontent.com/assets/10962177/17640383/b7fd2fb2-60bb-11e6-98eb-012ffec46063.png)

**Comment by jekkos** [comment]
I guess that's because sometimes information is filtered out, which results in duplicate locations. Maybe an extra step should be added in the end do remove those duplicates.

Also did you configure a country code as search results seem to contain addresses in both germany and usa?

**Comment by odiea** [comment]
I did not enter a country code with this setup so changing that to us did lower the results.
![2016-08-13 05_04_28-greenshot](https://cloud.githubusercontent.com/assets/10962177/17642849/9e72d1b6-6113-11e6-97f6-455211f3773f.png)

**Comment by daN4cat** [comment]
I didn't know that you had Tom Jones as customer, @odiea . Does he sing "It's Not Unusual" when he comes to your shop :-)

**Comment by odiea** [comment]
That and more when tony bennet shows to do his thing. Sometimes it tough coming up with a test name.

**Comment by jekkos** [comment]
I'm considering to add lodash library to do this filtering in an easy way. It has a lot of utility functions that facilitate working with javascript collections, arrays, .. among them the _.uniq function that filters an array for duplicates.

**Comment by jekkos** [comment]
I've done this fix locally will test later on today

**Comment by jekkos** [comment]
Should be resolved now.

**Comment by odiea** [comment]
No suggestions are showing now.

**Comment by jekkos** [comment]
Ok suggestions should be showing again (merge issue), but there are still duplicates. I didn't test thoroughly but will have a further look tomorrow

**Comment by odiea** [comment]
No Suggestions are still not showing.

**Comment by jekkos** [comment]
Ok I retested on my local seems to be fine now?

**Comment by odiea** [comment]
Still not working here.

**Comment by jekkos** [comment]
Any errors in js console?

**Comment by jekkos** [comment]
OK no think the push didn't work.. will push the real version later today.

**Comment by odiea** [comment]
This is with ?debug=true. No bower components are found.
![2016-08-30 04_02_42-new notification](https://cloud.githubusercontent.com/assets/10962177/18085146/1a5f047e-6e67-11e6-9411-9ec01ee33e75.png)
Otherwise.
![2016-08-30 03_58_21-](https://cloud.githubusercontent.com/assets/10962177/18085181/41e6471e-6e67-11e6-9337-04a162a1ab79.png)

**Comment by odiea** [comment]
Nomination is working great now. Thanks
