### ISSUE TITLE
What are the benefits of changing from development to production?

### ISSUE THREAD

**Issue by odiea** [jekkos/opensourcepos#808]
Before submitting an issue please make sure you tick (add a x between the square brakets) and agree all the following check boxes:

- [x] Checked the current issues database and no similar issue was already discussed
- [x] Read the README, WHATS_NEW and UPGRADE
- [x] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas
- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [x] PHP version is at least 5.5 and not 7.x
- [x] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [x] Know the name and version of OS, Web server and MySQL and will add to my issue report

IMPORTANT: If you remove the template when submitting an issue your issue will be closed.

### Installation information
This is a question for the seasoned users of OSPOS. Are there any benefits if you change from development to production server after you setup OSPOS?

### Expected behaviour
Ok

### Actual behaviour
Ok

### Steps to reproduce the issue

**Comment by daN4cat** [comment]
The master version is production not development. The debug flag is off and the only means to enable on a view is adding ?debug=true .
Is there something that you noticed that makes you think differently?

**Comment by odiea** [comment]
No in Index.php there is a way to change it. So I was just checking to see if there are any benefits for the user to do it.
```
	define('ENVIRONMENT', isset($_SERVER['CI_ENV']) ? $_SERVER['CI_ENV'] : 'development');

switch (ENVIRONMENT)
{
	case 'development':
		error_reporting(-1);
		ini_set('display_errors', 1);
	break;

	case 'testing':
	case 'production':
		ini_set('display_errors', 0);
		if (version_compare(PHP_VERSION, '5.3', '>='))
		{
			error_reporting(E_ALL & ~E_NOTICE & ~E_DEPRECATED & ~E_STRICT & ~E_USER_NOTICE & ~E_USER_DEPRECATED);
		}
		else
		{
			error_reporting(E_ALL & ~E_NOTICE & ~E_STRICT & ~E_USER_NOTICE);
		}
	break;

	default:
		header('HTTP/1.1 503 Service Unavailable.', TRUE, 503);
		echo 'The application environment is not set correctly.';
		exit(1); // EXIT_ERROR
}

**Comment by daN4cat** [comment]
I will check better, but I don't think we have enabled development mode.

**Comment by odiea** [comment]
To me it appears that it's only value is to suppress the display of errors.

**Comment by aelhofy** [comment]
as per CodeIgniter

https://codeigniter.com/user_guide/installation/index.html

"One additional measure to take in production environments is to disable PHP error reporting and any other development-only functionality. In CodeIgniter, this can be done by setting the ENVIRONMENT constant, which is more fully described on the security page"

**Comment by daN4cat** [comment]
Indeed, that's what I found but more in specific here: https://codeigniter.com/user_guide/general/environments.html

I would need to add to .htaccess the following:

```
# set the website environment to be production not development
SetEnv CI_ENV production
```

after having tested it of course.

**Comment by daN4cat** [comment]
Or alternatively I could change the define to be default production instead of development.

**Comment by daN4cat** [comment]
SetEnv in .htaccess is problematic and depends on the LAMP setup.

I will change the index.php to be default production and not development if not CI_EVN is set.
That makes more sense here and master should contain production code and leave the development issues to developers.

BTW, good catch @odiea that is a security issue that I should have addressed during the security review a while back.

**Comment by daN4cat** [comment]
Fixed and in master.

**Comment by daN4cat** [comment]
I close this as I heard no complaints about the change. I'll add a note in the FAQ about how to re-enable the development mode.
