### ISSUE TITLE
when hit enter after updating invoice number every thing is flashed

### ISSUE THREAD

**Issue by aelhofy** [jekkos/opensourcepos#809]
Before submitting an issue please make sure you tick (add a x between the square brakets) and agree all the following check boxes:

- [x] Checked the current issues database and no similar issue was already discussed
- [x] Read the README, WHATS_NEW and UPGRADE
- [x] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas
- [x] Reporting an issue of an unmodified OSPOS installation
- [ ] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [x] PHP version is at least 5.5 and not 7.x
- [x] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [x] Know the name and version of OS, Web server and MySQL and will add to my issue report

IMPORTANT: If you remove the template when submitting an issue your issue will be closed.

### Installation information
ubuntu 14.04.5 + php 5.5 &  OSPOS 3.0.0 - 84033699675e

### Expected behaviour

when hit enter after updating invoice number nothing should happen 

### Actual behaviour
when hit enter after updating invoice number every thing is flashed and the sale is empty

### Steps to reproduce the issue
change invoice number and hit enter

**Comment by odiea** [comment]
Yes pressing enter after selecting create Invoice is giving issues. If you do not press enter and then press the complete button it works ok just use the auto generated one or enter a custom number and not press enter just use the complete sale button  it works just fine.

**Comment by aelhofy** [comment]
The auto generated invoice number is the lasted used number and can not be used because it will be a duplicate and will give error.

The work around by not hiting enter is good temperarry solution till this has been fixed.

**Comment by odiea** [comment]
I am not getting the auto generated Invoice issue you appear to have. The next sale goes back to that number and it works fine. If at any time you delete a sale that will cause the auto generated Invoice issue. Yes there is a problem if you press enter after selecting Create Invoice.

**Comment by daN4cat** [comment]
That's another reason why a sale should not be deleted

**Comment by aelhofy** [comment]
No sales is deleted 

On August 16, 2016 8:34:44 AM GMT+03:00, FrancescoUK <notifications@github.com> wrote:
>That's another reason why a sale should not be deleted
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/jekkos/opensourcepos/issues/809#issuecomment-240005361

--
Best Regards

Ahmed

**Comment by jekkos** [comment]
Apparantly this form control was inside the cancel form and thus hitting enter would submit it by default. Will close the tag a little sooner so that it does nothing.

**Comment by jekkos** [comment]
Should be fixed now with my latest push. Give it a try and let me know if OK.

**Comment by onyema3** [comment]
@Jekkos, you new comit might have broken something. Here are the views i'm getting and i can't seem to access another tab in store cofig
![login](https://cloud.githubusercontent.com/assets/12876751/18066394/317f001e-6e30-11e6-9445-33e95cb17784.jpg)
![welcome](https://cloud.githubusercontent.com/assets/12876751/18066414/4660fd2a-6e30-11e6-99ec-f4871aea0c29.jpg)

**Comment by odiea** [comment]
No working well.
![2016-08-29 14_42_03-new notification](https://cloud.githubusercontent.com/assets/10962177/18066730/ded2acdc-6df6-11e6-9538-11b64e9f2735.png)

**Comment by onyema3** [comment]
Same here
![untitled](https://cloud.githubusercontent.com/assets/12876751/18066925/6c8d03e8-6e32-11e6-8522-38e75c1a34ca.jpg)

**Comment by jekkos** [comment]
Ok let me look into it

**Comment by jekkos** [comment]
Should be fixed now, sorry about that, once again had the wrong node plugin in my build pipeline which broke the links to the assets

**Comment by onyema3** [comment]
Fixed

**Comment by onyema3** [comment]
There is a typo on the login page
![untitled](https://cloud.githubusercontent.com/assets/12876751/18067707/db6096ec-6e35-11e6-89ea-1f00962dd9a2.jpg)

**Comment by jekkos** [comment]
Typo should be gone now.

**Comment by aelhofy** [comment]
No every thing seems OK

**Comment by daN4cat** [comment]
@aelhofy If you switch to English and test the new js does it work fine?

**Comment by aelhofy** [comment]
I am not able to login at all screen stuck , I have to put the old files to change language and then  test

**Comment by aelhofy** [comment]
with English it is OK

**Comment by jekkos** [comment]
I guess there are some issues with russian and arabic right now. Will look into that and close this issue for now
