### ISSUE TITLE
Store credit using gift cards

### ISSUE THREAD

**Issue by odiea** [jekkos/opensourcepos#81]
Is there any way for a store return to have it accept a 0 value giftcard. It will not accept a value of 0.001 so I have to give the customer an extra penny. Also I get the following error when gift card value is 0
Giftcard 16 remaining value is %2.00!. Hope you can help

**Comment by jekkos** [comment]
line 164 in sales.php

    if ( $cur_giftcard_value <= 0 )

here just change this line to 

    if ( $cur_giftcard_value < 0 )

**Comment by odiea** [comment]
That worked. Thanks
application\controller\sales.php is where this file is located if someone else wants to use giftcards as a store credit..
