### ISSUE TITLE
Invoice Number to be latest one + 1

### ISSUE THREAD

**Issue by aelhofy** [jekkos/opensourcepos#810]
Before submitting an issue please make sure you tick (add a x between the square brakets) and agree all the following check boxes:
- [x] Checked the current issues database and no similar issue was already discussed
- [x] Read the README, WHATS_NEW and UPGRADE
- [x] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas
- [x] Reporting an issue of an unmodified OSPOS installation
- [ ] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [x] PHP version is at least 5.5 and not 7.x
- [x] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [x] Know the name and version of OS, Web server and MySQL and will add to my issue report

IMPORTANT: If you remove the template when submitting an issue your issue will be closed.
### Installation information

ubuntu 14.04.5 + php 5.5 & OSPOS 3.0.0 - 84033699675e
### Enhancement Required

invoice number to be the latest one used + 1
### Actual behaviour

only latest one used is shown

**Comment by aelhofy** [comment]
I thing I made it , modification attached for your kind validation
[view-sales-form-modification.zip](https://github.com/jekkos/opensourcepos/files/422399/view-sales-form-modification.zip)

**Comment by odiea** [comment]
I think what you need to do is using phpmyadmin check your database ospos_sales and check for missing Invoice numbers it's possible that with the changes you made some of them were deleted.

**Comment by aelhofy** [comment]
As usual you assumed that I did some modifications.

I confirm it is not the case ; however I will check again

**Comment by jekkos** [comment]
Modifications in the sense of a deleted sale?

**Comment by aelhofy** [comment]
Never done as I remember; any way I will check again
-- 
Thanks

Ahmed

**Comment by daN4cat** [comment]
I never paid too much attention to this part because I don't use/need, but it looks like in my case you need to do a +2 jump to get it to work.
I'll see if I can find the time over the week-end to test it more.

**Comment by odiea** [comment]
On my test unit What I did was use my oldest records and replace their blank Invoice numbers with the missing numbers and remember 0 is the first number.

**Comment by odiea** [comment]
@aelhofy I am not accusing you of anything just this accident occasionally happens.

**Comment by aelhofy** [comment]
@odiea thanks for explanation

**Comment by jekkos** [comment]
Currently invoice number is found by counting number of sales with invoice numbers not set to null. If you delete a sale with an invoice number in between then the numbering will have a gap as well. In this case you can only delete the last sale if you want to keep the sequence correct. Think this is more of an enhancement as it should work fine as long as you don't delete any sales (which causes problems anyway)

**Comment by daN4cat** [comment]
@odiea with the latest invoice changes is this still an issue?

**Comment by odiea** [comment]
Yes it is. I deleted a sale with an Invoice number. I created an invoice and got the Unique number warning. I then edited a different sale and added an invoice number to it and the issue went away. I guess it is still using the invoice count to create the next invoice.

**Comment by SteveIreland** [comment]
It is there if you use the invoice count token for determining the next invoice number to use.  I feel the better approach is to use the new "last used invoice number" token.  Using the new approach doesn't introduce the database anomalies in the invoice number scheme.

**Comment by daN4cat** [comment]
ok, so this is solved.

**Comment by odiea** [comment]
Maybe I am doing something wrong here. This is the last invoice used. I then changed the value to 418
![2017-07-08 06_48_18-wedidit _ powered by ospos 3 1 0](https://user-images.githubusercontent.com/10962177/27985563-3a30c114-63aa-11e7-88f7-f56998c07b24.png)
Here is what I get when trying to enter a new Invoice.
![2017-07-08 06_51_00-wedidit _ powered by ospos 3 1 0](https://user-images.githubusercontent.com/10962177/27985575-5f9285d2-63aa-11e7-8c22-1371fe08dfaf.png)

**Comment by odiea** [comment]
This will be solved if the default Sales Invoice format is set to INV-%y{ISEQ:6}. I read the wiki!

**Comment by daN4cat** [comment]
So we can close
