### ISSUE TITLE
Could not edit Store Configuration: Blank form

### ISSUE THREAD

**Issue by payudara** [jekkos/opensourcepos#811]
Before submitting an issue please make sure you tick (add a x between the square brakets) and agree all the following check boxes:

- [x] Checked the current issues database and no similar issue was already discussed
- [x] Read the README, WHATS_NEW and UPGRADE
- [x] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas
- [x] Reporting an issue of an unmodified OSPOS installation
- [ ] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [ ] PHP version is at least 5.5 and not 7.x
- [x] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [x] Know the name and version of OS, Web server and MySQL and will add to my issue report

IMPORTANT: If you remove the template when submitting an issue your issue will be closed.

### Installation information
OSPOS v3 hosted in shared hosting service
PHP Version 5.6.24 with '--enable-intl=shared' on Linux (My hosting provider said it's the same as php_intl.dll)
Web server: Apache
User agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36

Source files from the master file were copied to the hosting server. Created database and populate 
it with supplied database.sql (no error). I also configured config,php and database.php as instructed. 

I could log in and perform some tasks but could not edit barcode, Stock, Receipt, Invoice, Email, Message, etc. Also i could not add an item. (Details as written below).

Error log shows many entry like this: [16-Aug-2016 01:03:28 America/New_York] PHP Fatal error:  Class 'NumberFormatter' not found in /home/coctagco/public_html/ospos/application/helpers/locale_helper.php on line 29. I don't know if it is related to the above issues.

I asked my hosting provider to activate php_intl.dll and they replied ok.

### Expected behaviour

1. Can edit barcode, Stock, Receipt, Invoice, Email, Message etc in Store Configuration.
2. Can add item

### Actual behaviour

1. Could not edit barcode, Stock, Receipt, Invoice, Email, Message
2. No submit button under barcode, Stock, Receipt, Invoice, Email, and Message tabs. There's one under Information and General tabs but not in other tabs.
3. Obviously can not edit configuration
4. Could not add item since it shows blank form with new and submit button only, 

It's seemed that MySQL was not a problem since i can log in and add employees. 

### Steps to reproduce the issue
Login as usual and go to Store Configuration

**Comment by jekkos** [comment]
I think you'll need to check phpinfo() to see whether this extension is really enabled. The error says it's not loaded.

You can enable the option when compiling but you still need to add the module to php.ini to enable it.

**Comment by payudara** [comment]
The issues have been solved after installing php5_intl.dll extension as requested via my hosting provider's support ticket. So shared intl was not the same as php5_intl.dll. I don't know why they said so in the beginning.

I hope this solution will help others. Cheers.
