### ISSUE TITLE
sale register did not add item by typing item name

### ISSUE THREAD

**Issue by rajashani99** [jekkos/opensourcepos#812]
Before submitting an issue please make sure you tick (add a x between the square brakets) and agree all the following check boxes:

- [x] Checked the current issues database and no similar issue was already discussed
- [x] Read the README, WHATS_NEW and UPGRADE
- [x] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas
- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [x] PHP version is at least 5.5 and not 7.x
- [x] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [x] Know the name and version of OS, Web server and MySQL and will add to my issue report

IMPORTANT: If you remove the template when submitting an issue your issue will be closed.

### Installation information
ops version = 3.0
wamp server = 3.0.5
os = windows 7 (32 bit)

### Expected behavior
in sale register when i enter product/item name for sale which is already stored in my item table
it says "Unable to add item to sale"
even it did not search any product name which is already added in items

### Actual behavior
but when i use bar code scanner it detected that product while without bar code scanner it is not adding any product in sale register

in my country some products don't have bar code on product packing then we sale that product using manually type that item name this features works in all your previous version

### Steps to reproduce the issue

**Comment by odiea** [comment]
Currently you have to use the suggested Item from the dropdown menu that matches the item you entered. Click on that item and it should appear in the Register.

**Comment by odiea** [comment]
Please specify the language you are using to see if that is what is creating these errors.

**Comment by jekkos** [comment]
Issue is duplicate of #812

**Comment by odiea** [comment]
Are you also using the conversion mentioned in Issue #798

**Comment by rajashani99** [comment]
the problem is suggested Item from the drop down menu is not appearing even drop down box is not appearing


________________________________

**Comment by rajashani99** [comment]
i am using English language

**Comment by daN4cat** [comment]
See #813

**Comment by paktech1** [comment]
the item is not adding to sales because the item_number remains null after adding the item to inventory.

i am able to fix this issue using mysql trigger:

CREATE TRIGGER item_trig BEFORE INSERT ON ospos_items 
FOR EACH ROW
     SET new.item_number =(select MAX(item_id) + 1 from ospos_items);
