### ISSUE TITLE
Sale register and Receving is not suggesting anything  for items nor customrs [OSPOS 3.0.0 - 84033699675e]

### ISSUE THREAD

**Issue by aelhofy** [jekkos/opensourcepos#813]
Before submitting an issue please make sure you tick (add a x between the square brakets) and agree all the following check boxes:

- [x] Checked the current issues database and no similar issue was already discussed
- [x] Read the README, WHATS_NEW and UPGRADE
- [x] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas
- [x] Reporting an issue of an unmodified OSPOS installation
- [ ] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [x] PHP version is at least 5.5 and not 7.x
- [x] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [x] Know the name and version of OS, Web server and MySQL and will add to my issue report

IMPORTANT: If you remove the template when submitting an issue your issue will be closed.

### Installation information
OSPOS 3.0.0 - 84033699675e
Apache 2 , Mysql 5.6 and php 5.5
ubuntu 14.04.05

### Expected behaviour
when typing some letters of customer name or item it is not suggesting anything , however when I type say complete item code and hit enter it is added 

### Actual behaviour
when typing some letters of customer name or item it is suggesting customer or items that matching entered text 

### Steps to reproduce the issue

Fresh installation of OSPOS 3.0.0 - 84033699675e and search items or customers

**Comment by rajashani99** [comment]
same problem is here :-(

**Comment by daN4cat** [comment]
Using the latest master works fine for me.

Are you using the latest code?

**Comment by aelhofy** [comment]
Yes it is the latest code just 15 mine before submitting the issue

**Comment by daN4cat** [comment]
It's working fine with Chrome, are you using FF?

**Comment by aelhofy** [comment]
Yes for me FF on ubuntu

**Comment by daN4cat** [comment]
Can you please try Chromium?

**Comment by daN4cat** [comment]
It's a problem with Firefox.

**Comment by aelhofy** [comment]
Chromium did not work for me

**Comment by daN4cat** [comment]
Probably something wrong with yesterday's js plugin upgrade. I'll revert that and test it again.
It has nothing to do with the browser, cached js was puzzling things.

**Comment by daN4cat** [comment]
It's an issue with bootstrap-select 1.11.0. I'm trying to understand what is missing or wrong with that new version.

**Comment by rajashani99** [comment]
i am also using latest master work i think problem is in any js script

**Comment by daN4cat** [comment]
Yes, please read what I just said.

**Comment by daN4cat** [comment]
I've created the issue in bootstrap-select: https://github.com/silviomoreto/bootstrap-select/issues/1475 but meanwhile I revert the plugin to version 1.10.0, regen dist and commit the change to master.
