### ISSUE TITLE
Creating Loans for Customers

### ISSUE THREAD

**Issue by cakirhal** [jekkos/opensourcepos#814]
Before submitting an issue please make sure you tick (add a x between the square brakets) and agree all the following check boxes:

- [ x] Checked the current issues database and no similar issue was already discussed
- [ x] Read the README, WHATS_NEW and UPGRADE
- [ x] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas
- [ x] Reporting an issue of an unmodified OSPOS installation
- [ x] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [ x] PHP version is at least 5.5 and not 7.x
- [ x] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [ x] Know the name and version of OS, Web server and MySQL and will add to my issue report

IMPORTANT: If you remove the template when submitting an issue your issue will be closed.

### Expected behaviour

I expect this software has the capability of storing loans for customers.

### Actual behaviour

 While processing a sale, we can choose a customers and type the amount of money. Actually, it seems not possible to complete a sale without cash.

**Comment by jekkos** [comment]
Please refer to #24
