### ISSUE TITLE
unable to add new customers , employee, and supplies when uploaded to hosted server

### ISSUE THREAD

**Issue by philkiangai** [jekkos/opensourcepos#815]
Before submitting an issue please make sure you tick (add a x between the square brakets) and agree all the following check boxes:

- [ ] Checked the current issues database and no similar issue was already discussed
- [ ] Read the README, WHATS_NEW and UPGRADE
- [ ] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas
- [ ] Reporting an issue of an unmodified OSPOS installation
- [ ] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [ ] PHP version is at least 5.5 and not 7.x
- [ ] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [ ] Know the name and version of OS, Web server and MySQL and will add to my issue report

IMPORTANT: If you remove the template when submitting an issue your issue will be closed.

### Steps to reproduce the issue

**Comment by daN4cat** [comment]
Read your error_log and also make sure all php extensions are installed, including sockets support.

**Comment by josemoreta** [comment]
I want to install a module in ospos 3. as I do this.

**Comment by odiea** [comment]
https://codeigniter.com/user_guide/general/welcome.html is a good place to start.
