### ISSUE TITLE
Error in new versions after implementation of the new issue with security and copyright.

### ISSUE THREAD

**Issue by arteiro** [jekkos/opensourcepos#816]
Updated to the file version in 16/08 and tried again today but is not working, then the login gives 500 error and the page is blank. I do not know what happens, someone could help.
locally settings are:

Use xampp on windows 10

Current PHP version: 5.6.19
PHPINFO   
array
(
    [0] => Core
    [1] => bcmath
    [2] => calendar
    [3] => ctype
    [4] => date
    [5] => ereg
    [6] => filter
    [7] => ftp
    [8] => hashed
    [9] => iconv
    [10] => json
    [11] => mcrypt
    [12] => SPL
    [13] => odbc
    [14] => pcre
    [15] => Reflection
    [16] => session
    [17] => Standard
    [18] => mysqlnd
    [19] => tokenizer
    [20] => zip
    [21] => zlib
    [22] => libxml
    [23] => gift
    [24] => RFQ
    [25] => bz2
    [26] => SimpleXML
    [27] => wddx
    [28] => xml
    [29] => xmlreader
    [30] => xmlwriter
    [31] => apache2handler
    [32] => openssl
    [33] => curl
    [34] => fileinfo
    [35] => gd
    [36] => gettext
    [37] => intl
    [38] => imap
    [39] => mbstring
    [40] => exif
    [41] => mysql
    [42] => mysqli
    [43] => pdo_mysql
    [44] => pdo_sqlite
    [45] => XMLRPC
    [46] => xsl
    [47] => Phar
    [48] ​​=> mhash
)

**Comment by daN4cat** [comment]
You need to add Socket support

**Comment by arteiro** [comment]
Thanks, worked on localhost, now I have to talk to my hosting to release there. Thank you.

**Comment by arteiro** [comment]
My hospagem eta with php version: 5.4.19 is not working. that although recent has been updated, with no provision for new atualizaçõe. Thanks, I'll have to wait to be able to use the web, I will be locally yet.

**Comment by chandrawg** [comment]
i have same problem. my php version 5.6.21.
after login error 500. and i enable extension=php_sockets.dll. i can login and menu is appear. but everytime i click reports, error 500 is appear. and menu in configuration is not function.
i already uncomment extension=php_gd2.dll. please help. thanks.

**Comment by odiea** [comment]
Did you restart your server?

**Comment by chandrawg** [comment]
yes already restart

**Comment by odiea** [comment]
Did you download the Master or the Composer version. If it is the composer version yes it is error prone if it is the Master one of the other programmers may know what's going on but they are in Europe and the time zone is different. They will eventually read this.

**Comment by chandrawg** [comment]
i download from this 
![untitled](https://cloud.githubusercontent.com/assets/21230424/17953159/9322d2b8-6aa3-11e6-8924-88d0c9310d17.jpg)

**Comment by odiea** [comment]
You do have the master so you will have to wait for them to figure out this new bug.

**Comment by odiea** [comment]
I am testing with this version of xampp-win32-7.0.8-0-VC14-installer.exe and I am having no issues after uncommenting the needed extensions. If you have time you might try it out and see if it helps.

**Comment by chandrawg** [comment]
already fixed after uncomment extension=php_intl.dll. but now i have
problem with discount price. discount is not summing in total price.

**Comment by odiea** [comment]
There are a few ways to do that. Set your discount rate in config hit submit t save. That will be an auto discount. Far a manual discount you enter the discount rate at the Register the hit update. You can also give each customer an update percent the click update at the register.

**Comment by chandrawg** [comment]
i use discount percentage on sales cashier. but the total not include discount.

**Comment by daN4cat** [comment]
@chandrawg create a new issue , please don't add comments on a unrelated one.
