### ISSUE TITLE
i cant access to config

### ISSUE THREAD

**Issue by lisandro404** [jekkos/opensourcepos#817]
i have a local installation.
i can`t access to config>barcode or config>stock or  config>recipt or  config>invoice or  config>email or  config>message or  config>licence.
Why?

![image](https://cloud.githubusercontent.com/assets/21233756/17956556/1246948c-6a61-11e6-904c-dd6771129a94.png)

Thanks.

**Comment by daN4cat** [comment]
Read the FAQ? Also make sure PHP has Sockets installed.
