### ISSUE TITLE
Password Security

### ISSUE THREAD

**Issue by gustavo81988** [jekkos/opensourcepos#822]
is it ok to use md5 for password encryption? it's well known that md5 is insecure. Maybe something like bcrypt would be better.

**Comment by daN4cat** [comment]
I will check this because md5 is indeed not the correct thing to do.

**Comment by daN4cat** [comment]
Use bcrypt for password hashing: http://stackoverflow.com/questions/4795385/how-do-you-use-bcrypt-for-hashing-passwords-in-php

**Comment by jekkos** [comment]
Ok indeed maybe we should change the hashing algorithm, md5 is very easy to crack. Also an upgrade procesdure should be foreseen (to convert from md5 to bcrypt in this case). Maybe use salting to increase hash strength

**Comment by jekkos** [comment]
http://stackoverflow.com/questions/1533744/how-to-upgrade-a-password-storage-scheme-change-hashing-algorithm

**Comment by jekkos** [comment]
Shall we include this change in 3.0 or not? Think all other work is done now.

**Comment by gustavo81988** [comment]
Doesn't Seem Too Hard. I say yes. Talkin about security can i send a pull request with a captcha?

**Comment by daN4cat** [comment]
You mean captcha on login page? That would be good, but with reCaptcha vs2 (I'm not a Robot) if possible as the numbers are cumbersome.

**Comment by daN4cat** [comment]
@jekkos yes in 3.0 because we changed many things about security and this one needs to be changed too.

**Comment by jekkos** [comment]
@gustavo81988 pull requests are welcome. Do you mean adding captcha once a password is mistyped a couple of times? Would be good as there is no brute force protection right now

**Comment by gustavo81988** [comment]
Yes, Recaptcha in the login screen would be great for brute force. Maybe after  5 unsuccessful attempts.

**Comment by gustavo81988** [comment]
Guys i  have implemented a great feature that helps a lot to manage multiple installations on the cloud and I would love to show it  to you. Maybe we can schedule a hangout if you have time.

**Comment by jekkos** [comment]
@gustavo81988 sounds great. Lets schedule that hangout. When do you have time?

**Comment by gustavo81988** [comment]
from 20:00 GMT-4 onwards

**Comment by jekkos** [comment]
OK I'm currently at CEST so 6 hours difference.. I fear it'll be too late then here.. If there's any time you can schedule it at 17 or 18pm your time then that would be great.

**Comment by jekkos** [comment]
What did you use to do this thing Chef or Ansible?

**Comment by gustavo81988** [comment]
Yeah 18 it's fine. Send a pm at my gmail account gustavo81988@gmail.com

**Comment by gustavo81988** [comment]
None of that. I handle logins with a codeigniter hook so i can have multiple OSPOS installations with a single source code but multiple databases.

**Comment by jekkos** [comment]
OK so this would allow to run multiple stores from one instance

**Comment by gustavo81988** [comment]
Yes and also features a subscription system to handle payments for every client.

**Comment by onyema3** [comment]
Can i join this chat?

**Comment by jekkos** [comment]
sure post your email

**Comment by onyema3** [comment]
onyema@ifende.com

**Comment by daN4cat** [comment]
I will remove the comments related to multiple installation. Please save anything as I want to keep this thread focus on Security story.

**Comment by jekkos** [comment]
Ok captcha can also be implemented using builtin CI captcha lib. Might be easier to do it like this.

**Comment by jekkos** [comment]
Just wanted to say that the multistore in this case was a load hook that assigned a database name according to a logged in user. This way multiple schema's can be used from one install and thus no data is shared between instances.

**Comment by onyema3** [comment]
Is this something you plan to implement?

**Comment by sooorajjj** [comment]
Can i join this chat too ? 
mail : sooorajjj@gmail.com

**Comment by jekkos** [comment]
I have done this modification. Old hashes are upgraded once a user logs in. Standard php functionality is now used to verify the hashes.

**Comment by onyema3** [comment]
Do we need to run a database upgrade script??

**Comment by daN4cat** [comment]
@onyema3 yes

**Comment by onyema3** [comment]
2.4 to 3.0 again?

**Comment by onyema3** [comment]
I tried it and it gave me some errors so i just ran just this

ALTER TABLE `ospos_employees`
 ADD COLUMN `hash_version` int(1) NOT NULL DEFAULT '2';

UPDATE `ospos_employees` SET `hash_version` = 1; 

and i'm good

**Comment by jekkos** [comment]
Yes indeed you need to upgrade db first. Just made another commit that fixes the employee creation and thus creates it with the new hashing strategy

**Comment by onyema3** [comment]
Great
