### ISSUE TITLE
Can't log in after fresh install

### ISSUE THREAD

**Issue by petercstevenson** [jekkos/opensourcepos#825]
Before submitting an issue please make sure you tick (add a x between the square brakets) and agree all the following check boxes:

- [x ] Checked the current issues database and no similar issue was already discussed
- [x] Read the README, WHATS_NEW and UPGRADE
- [ x] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas
- [x ] Reporting an issue of an unmodified OSPOS installation
- [x] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [x] PHP version is at least 5.5 and not 7.x
- [x] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [x] Know the name and version of OS, Web server and MySQL and will add to my issue report

IMPORTANT: If you remove the template when submitting an issue your issue will be closed.

### Installation information

Just did a fresh install using Docker and Digital Ocean according to the Cloud Install using Docker: https://github.com/jekkos/opensourcepos

### Expected behaviour

When I tried logging in the first time I expected to be able to use OSPOS

### Actual behaviour

When I tried logging in the first time I got a blank white screen

### Steps to reproduce the issue

The instructions on https://github.com/jekkos/opensourcepos

**Comment by mccawk** [comment]
To tag onto the original issue - I am experiencing the same thing (build docker container according to the instructions).

1) updating file application/config/config.php
$config['log_threshold'] = 4;
2) Hit the web site http://localhost/ (blank screen - 500 error response)
3) Check the log - tail /app/application/logs/log-2016-08-29.php
INFO - 2016-08-29 17:57:28 --> Model Class Initialized
INFO - 2016-08-29 17:57:28 --> Controller Class Initialized
ERROR - 2016-08-29 17:57:28 --> Severity: Error --> Call to undefined function Racecore\GATracking\Client\Adapter\socket_create() /app/application/libraries/src/Racecore/GATracking/Client/Adapter/Socket.php 26

**Comment by jekkos** [comment]
Sockets support was not yet included but should be fine now with my last push. Wait until the automatic build is done and then try to redeploy the stack. First terminate the current one to make sure it pulls the latest image from docker hub.

**Comment by jekkos** [comment]
I just did a fresh deploy with the latest commit and deploys fine again.

**Comment by petercstevenson** [comment]
Thank you, this has fixed it. Now I need to figure out if I can recover my old data.

**Comment by jekkos** [comment]
The data is stored in a docker volume..Think it can be accessed by using docker cloud cli tool directly.

**Comment by jekkos** [comment]
There might have been an easier way to redeploy the web image only but I haven't found that yet

**Comment by petercstevenson** [comment]
Thanks. When I was messing around with it earlier today I ended up restoring one of my Digital Ocean backups. So I only ended up losing a few days worth of data. Next time I will file a report before touching anything. Well, hopefully there won't be a next time :) It's awfully stressful to have my POS system stop working all of a sudden.

**Comment by jekkos** [comment]
Ok nice to hear some people are using the cloud install. Took me quite some time to make it work that way :+1:

**Comment by daN4cat** [comment]
@petercstevenson you shouldn't use 3.0.0 for real and live use because it's not officially released yet.
It's good for beta testing only.

**Comment by petercstevenson** [comment]
Oh, thank you. You are right; I definitely want to be using the stable version. Is there a different script for the stable version? Or is the cloud install only for 3.0.0?

**Comment by daN4cat** [comment]
Cloud install is only 3.0.0, but we are not too far from closing it.

**Comment by petercstevenson** [comment]
Once it is closed, will it stay available or will the cloud system move 
over to the new development version?

**Comment by daN4cat** [comment]
We will need to look into that, to have a 3.0.0 with cloud installation stable.

**Comment by petercstevenson** [comment]
That would certainly be helpful for me. Using a testing version is too stressful for me.
