### ISSUE TITLE
Unable to launch app 

### ISSUE THREAD

**Issue by senseitebbayo** [jekkos/opensourcepos#826]
I just downloaded OSPOS to try it out. i have done everything as per the instructions but i get this on the index page 

An Error Was Encountered

Unable to load the requested file: helpers/form_helper.php

I dont know codeigniter (yet) so i dont know how to start debugging this. php5.5.30 on xamp

Before submitting an issue please make sure you tick (add a x between the square brakets) and agree all the following check boxes:

- [x] Checked the current issues database and no similar issue was already discussed
- [x] Read the README, WHATS_NEW and UPGRADE
- [x] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas
- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [x] PHP version is at least 5.5 and not 7.x
- [x] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [ ] Know the name and version of OS, Web server and MySQL and will add to my issue report

IMPORTANT: If you remove the template when submitting an issue your issue will be closed.

### Steps to reproduce the issue

**Comment by jekkos** [comment]
It might have been deleted by a virus scanner? Which system do you use?

**Comment by senseitebbayo** [comment]
I dont think so. I think there is a problem withthe master branch on github. look at https://github.com/jekkos/opensourcepos/tree/master/application/helpers you will notice form_helper.php is also missing

**Comment by daN4cat** [comment]
Not sure where this form_helper.php story comes from, @jekkos is that something you added with the latest code because I don't have memory of that file.

**Comment by daN4cat** [comment]
I checked the code and there is no trace of form_helper usage in the code.

@senseitebbayo please do a clean installation in a new directory without mixing some old code with it.

**Comment by senseitebbayo** [comment]
Ok. Can you point me to where i can download a zip file with the correct contents?
Thanks

**Comment by daN4cat** [comment]
@senseitebbayo just wait a bit because we are fixing a couple of issues. The vs 3.0.0 is in beta testing so not final yet.

BTW the link you provided is the correct one and I don't understand how come you get that error.

**Comment by senseitebbayo** [comment]
Ok not a problem. not sure how I got the error either. 
Do you know when this will come out of beta?

**Comment by odiea** [comment]
I did a clean install of current ospos3.0 with a new or old database I had no Issues.

**Comment by jekkos** [comment]
form_helper is actually a CI system file.. not sure why it would be missing in any download, we didn't really tocuh it.

**Comment by odiea** [comment]
I found this issue. I don't know if it will help. Towards the bottom of the page.
http://stackoverflow.com/questions/21214612/codeigniter-csrf-error-the-action-you-have-requested-is-not-allowed

**Comment by daN4cat** [comment]
@odiea post to the wrong issue?

**Comment by odiea** [comment]
Sorry I thought it had the link for form_helper in it. I will remove it.

**Comment by senseitebbayo** [comment]
Ok thanks. I will download this again. I would like to ask if there is any documentation on the code?
