### ISSUE TITLE
Block UI visable on sales & item kits stays empty

### ISSUE THREAD

**Issue by ErwinVorenhout** [jekkos/opensourcepos#827]
- [x] Checked the current issues database and no similar issue was already discussed
- [x] Read the README, WHATS_NEW and UPGRADE
- [x] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas
- [x] Reporting an issue of an unmodified OSPOS installation
- [ ] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [x] PHP version is at least 5.5 and not 7.x
- [x] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [x] Know the name and version of OS, Web server and MySQL and will add to my issue report

IMPORTANT: If you remove the template when submitting an issue your issue will be closed.

### Installation information

Open Source Point Of Sale Version 3.0.0 - 4f5ad57
PHP Version 5.6.20-0+deb8u1

### Expected behaviour

Creating a item kit, and a new sale

### Actual behaviour

when I add a  new item kit, it enters the record in the database but it isn't visable under item kits.
Also when I go to sales the page get blocked

**Comment by daN4cat** [comment]
Is this issue happening with the original code from master or have you touched something?

**Comment by ErwinVorenhout** [comment]
Its a fresh install from 5 minutes ago

Item kit issue: 

opensourcepos.min.js?rel=16b34f66f6:5 GET http://146.185.181.21/index.php/item_kits/search?order=asc&offset=0&limit=25 500 (Internal Server Error)

**Comment by daN4cat** [comment]
I see, I'm sure @jekkos will look into this.

**Comment by ErwinVorenhout** [comment]
PHPinfo: http://146.185.181.21/phpinfo.php

**Comment by daN4cat** [comment]
No worries, we don't need that info. I removed the link as it's not safe to publish it in clear,

**Comment by odiea** [comment]
I did a clean install of current ospos3.0 with a new or old database I had no Issues.

**Comment by odiea** [comment]
When you go to Receivings or Sales you see no footer and you get the following as expected. The Add Item modal does not work.
![2016-08-30 15_18_00-new notification](https://cloud.githubusercontent.com/assets/10962177/18107523/8613f1a8-6ec5-11e6-8275-f7d9d8448d60.png)

**Comment by odiea** [comment]
Something with his setup is borked.

**Comment by jekkos** [comment]
I get an error 500 when visiting this page.. From the source it looks like the footer isn't loaded properly, which might be causing the lock up here.

**Comment by odiea** [comment]
Yes I get the same loading the modal.
![2016-08-30 16_20_53-windows dvd player](https://cloud.githubusercontent.com/assets/10962177/18109405/55f62e42-6ece-11e6-904d-58a722122571.png)

**Comment by ErwinVorenhout** [comment]
@odiea  I've tried installing it on multiple webservers,
I just tried installing it in WAMP but still having the same issues.

**Comment by ErwinVorenhout** [comment]
PHP error log is throwing the following error:

PHP Fatal error:  Class 'NumberFormatter' locale_helper.php on line 10

**Comment by ErwinVorenhout** [comment]
Found the problem:

php_intl.dll was missing and I had to copy my icu files to the apache bin folder.

**Comment by odiea** [comment]
Glad you found it. Please read the Faqs because they are helpful.
FAQ
•If a blank page (HTTP status 500) shows after search completion or receipt generation, then double check php5-gd presence in your php installation. On windows check in php.ini whether the lib is installed. On Ubuntu issue  sudo apt-get install php5-gd . Also have a look at the Dockerfile for a complete list of recommended packages.
•If the following error is seen in sales module  Message: Class 'NumberFormatter' not found  then you don't have  php5-intl  extension installed. Please check the wiki to resolve this issue on your platform.
•You are getting following error  Message: Can't use method return value in write context  saying that you are probably using PHP7 which is not completely supported yet. Check your hosting configuration to verify whether you have a supported PHP version installed

**Comment by HamidCh** [comment]
@ErwinVorenhout  Can you please guide me in detail that how to get out of this??
![problem](https://cloud.githubusercontent.com/assets/14938392/18205659/039385ee-70d8-11e6-9a28-8329de35634e.png)

**Comment by HamidCh** [comment]
@ErwinVorenhout Can you please guide me that how to get out of this?
 ![image](https://cloud.githubusercontent.com/assets/14938392/18205682/1f9ea1a6-70d8-11e6-81df-513360489f43.png)

**Comment by daN4cat** [comment]
@HamidCh check your error_log in the installation root dir

**Comment by HamidCh** [comment]
Where Can I find that?

**Comment by daN4cat** [comment]
In your ospos installation root directory.

**Comment by HamidCh** [comment]
This is the error
![image](https://cloud.githubusercontent.com/assets/14938392/18208978/9751203a-70e6-11e6-9401-98544a83c63f.png)

**Comment by daN4cat** [comment]
what the error_log says?

**Comment by HamidCh** [comment]
I couldn't access that. I don't know where can I find the log. I have installed mamp and deployed the project in its htdocs folder. So can you please tell me where is the log? I am new to php so I don;t know things.

**Comment by onyema3** [comment]
/Applications/MAMP/logs/

**Comment by odiea** [comment]
Goto PHP.ini and make sure all the needed modules are not commented out. this means php5-gd ,php-intl and sockets.

**Comment by HamidCh** [comment]
I want to make changes to footer but when I change my footer the Block UI activates. How to get rid of it?

**Comment by onyema3** [comment]
You cannot change the footer.

**Comment by HamidCh** [comment]
I just want to add some links. Original content will stay there. :(

**Comment by daN4cat** [comment]
Read the License file
