### ISSUE TITLE
CSS problem in firefox

### ISSUE THREAD

**Issue by zhu-jianhua** [jekkos/opensourcepos#83]
hi,guys!this is problem,how to adjust?thanks millions!
![2015-05-25-135408_1176x444_scrot](https://cloud.githubusercontent.com/assets/10820567/7792491/8b68e00c-02e5-11e5-8b6a-f43e8dfe8521.png)

**Comment by jekkos** [comment]
Please be a little more specific when posting issues. What is wrong / not working? To me this looks like a cosmetic issue (text overlap with images?).
