### ISSUE TITLE
Product name do not show in the invoice!

### ISSUE THREAD

**Issue by ahadmosharraf** [jekkos/opensourcepos#830]
Before submitting an issue please make sure you tick (add a x between the square brakets) and agree all the following check boxes:

- [ ] Checked the current issues database and no similar issue was already discussed
- [ ] Read the README, WHATS_NEW and UPGRADE
- [ ] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas
- [ ] Reporting an issue of an unmodified OSPOS installation
- [ ] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [ ] PHP version is at least 5.5 and not 7.x
- [ ] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [ ] Know the name and version of OS, Web server and MySQL and will add to my issue report

IMPORTANT: If you remove the template when submitting an issue your issue will be closed.

### Steps to reproduce the issue
In my invoice the product name won't appear!

Please see the screenshot here: http://prntscr.com/ccituf

**Comment by odiea** [comment]
You used the template but did not fill out the needed info.
