### ISSUE TITLE
Cannot log on after latest updates. Does not accept passwords that are previuosly stored. Must run update db script.

### ISSUE THREAD

**Issue by odiea** [jekkos/opensourcepos#832]
Before submitting an issue please make sure you tick (add a x between the square brakets) and agree all the following check boxes:

- [x] Checked the current issues database and no similar issue was already discussed
- [x] Read the README, WHATS_NEW and UPGRADE
- [x] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas
- [x] Reporting an issue of an unmodified OSPOS installation
- [ ] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [x] PHP version is at least 5.5 and not 7.x
- [x] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [x] Know the name and version of OS, Web server and MySQL and will add to my issue report

IMPORTANT: If you remove the template when submitting an issue your issue will be closed.

### Actual behaviour
Github Users. Database needs to be updated for current commit

### Steps to reproduce the issue

**Comment by daN4cat** [comment]
Have you ran the database upgrade:

-- upgrade employees table
ALTER TABLE `ospos_employees`
 ADD COLUMN `hash_version` int(1) NOT NULL DEFAULT '2';

UPDATE `ospos_employees` SET `hash_version` = 1;

**Comment by odiea** [comment]
No I will try that. That did it. I guess I saw there was no need to update the tables.

**Comment by daN4cat** [comment]
Ha, @odiea, you failed on point 5:

Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)

**Comment by odiea** [comment]
I just made a note of that and will reopen this Issue with current info.

**Comment by jekkos** [comment]
Ok thanks for testing thiis feature that fast... it's because my train got stuck in a tunnel that I found the time to test a bit more thoroughly now .. 

Some unit tests for this kind of thing would be nice to have in the future (might be easier with composer in the end)

**Comment by daN4cat** [comment]
Shall we close? I did the db upgrade and logged in and everything looks working fine for me.

**Comment by odiea** [comment]
Leave it up for a couple of days so Bozos like me won't complain about this issue.
