### ISSUE TITLE
blank page if no internet connection

### ISSUE THREAD

**Issue by chandrawg** [jekkos/opensourcepos#833]
how to use point of sale 3.0 without internet connection ? after login only white screen. this is my error log and console.

![consolechrome](https://cloud.githubusercontent.com/assets/21230424/18196293/30a95996-7123-11e6-85a2-a94382a91a06.jpg)
![error log](https://cloud.githubusercontent.com/assets/21230424/18196294/30b90ec2-7123-11e6-800e-90b384870e8a.jpg)

**Comment by daN4cat** [comment]
Something to look into.

**Comment by onyema3** [comment]
Yeah, i just turned off my wifi and after login a blank page comes up

**Comment by jekkos** [comment]
Think we need some kind of circuit breaker around the sockets addon

**Comment by daN4cat** [comment]
@jekkos yep

**Comment by daN4cat** [comment]
Fixed, @onyema3 please test with wifi switched off.

**Comment by onyema3** [comment]
on it

**Comment by onyema3** [comment]
Great.. fixed

**Comment by daN4cat** [comment]
@onyema3 I fixed in a different way the issue. Would you mind to test again with the latest code in master? I cannot reproduce the issue you have and that's why I'm asking for you to test. Thanks.

**Comment by onyema3** [comment]
i'm on it

**Comment by onyema3** [comment]
Working without internet.

**Comment by daN4cat** [comment]
Perfect! Thank you for the help with the testing.

**Comment by onyema3** [comment]
You're always welcome!
