### ISSUE TITLE
employee can not change quantity without items permission

### ISSUE THREAD

**Issue by chandrawg** [jekkos/opensourcepos#834]
hi, my employee can not change sale quantity if items permission not checked. error message "Error editing item". i think employee do not need items permission for change quantity in sale process. 
![sales](https://cloud.githubusercontent.com/assets/21230424/18203376/46290674-7149-11e6-9747-91ff9c941dde.jpg)

**Comment by jekkos** [comment]
Your employee needs at least a grant for the stock location linked to the sales module.

**Comment by jekkos** [comment]
I just tried myself with grant given for one stock location in sales and no grants on items module.. works fine.

**Comment by jekkos** [comment]
@chandrawg Can you confirm the exact usecase here?

**Comment by chandrawg** [comment]
already give permission on stock location Sales "Process sales and returns". but when employe change quantity in sales process, error appear "error editing item". in employee setting i just check  sales and one of location. 
![salespermission](https://cloud.githubusercontent.com/assets/21230424/18221951/eb525d46-71ba-11e6-9b27-ac77c6596dc0.jpg)

**Comment by chandrawg** [comment]
i give permission to all stock location, without items permission still can not change quantity on sale.

**Comment by jekkos** [comment]
AFAIK there are no checks in edit_item in sales module beside when changing stock source location.

**Comment by jekkos** [comment]
I tried again and can't reproduce. There must be something else causing this error message. Normally it is only shown if the quantity, discount or price for the updated row does not validate. Permissions settings can't result in this type of error

**Comment by chandrawg** [comment]
but if i check items permission, employee can change quantity without any error.

**Comment by chandrawg** [comment]
any update ?

**Comment by odiea** [comment]
I just tested this issue and Jekkos is correct. Does not appear to be an issue. I can change qty at sale and also set a discount with no problems.
![2016-09-08 15_46_16-wedidit _ powered by ospos 3 0 0](https://cloud.githubusercontent.com/assets/10962177/18368134/9e97c5de-75db-11e6-8537-fb854eee10df.png)

**Comment by chandrawg** [comment]
please try add new employee (not admin) and just check sale permission in
one stock location.

**Comment by odiea** [comment]
This is what this cashier has access to.

![2016-09-09 02_47_56-microsoft edge](https://cloud.githubusercontent.com/assets/10962177/18381131/f9cddb62-7637-11e6-8ea9-f626b39fb579.png)

**Comment by daN4cat** [comment]
And if you do a sale transaction do you get the error as per original message?
We should try with qty more than 1, 1 (qty goes to 0) and 0 (negative sale case)

**Comment by chandrawg** [comment]
if i adjust new sales via barcode or type the item name again, quantity can adjusted without error. but if i change direct to quantity, error is appear.

**Comment by daN4cat** [comment]
@chandrawg you mean that changing the value in the box Qty. generates the issue.
@odiea do you have time to try from your cashier view the specific scenario?

**Comment by chandrawg** [comment]
yes when changing the value in the box Qty, error is appear. but if i rescan the product, the quantity is adjust without error.

**Comment by onyema3** [comment]
I tried this scenario in cashiers mode and everything is working fine

**Comment by daN4cat** [comment]
Hi, I tested this:

![image](https://cloud.githubusercontent.com/assets/636048/18395710/a122530a-76b7-11e6-8c23-060c63bfc0ad.png)

**Comment by onyema3** [comment]
Exactly what I tested and no errors

**Comment by odiea** [comment]
Yes. My testing was done in Cashier mode. No problem editing qty or Discount and Item kits also worked properly.

**Comment by onyema3** [comment]
![sales](https://cloud.githubusercontent.com/assets/12876751/18395856/7839457e-76b8-11e6-9644-38c887b24868.png)

**Comment by daN4cat** [comment]
![20160909-180334_capture](https://cloud.githubusercontent.com/assets/636048/18395906/b9ffc244-76b8-11e6-9e68-6c39fae23b96.gif)

**Comment by daN4cat** [comment]
@chandrawg are you using the latest code? Anything special that we haven't tried already?

**Comment by chandrawg** [comment]
i just reinstall with latest code and still can't change quantity. please check image below 
![ospos](https://cloud.githubusercontent.com/assets/21230424/18405101/c1d77084-7721-11e6-9572-b8d563c8d38c.gif)

**Comment by daN4cat** [comment]
Thanks I tried the same and still works for me, there must something else:

![image](https://cloud.githubusercontent.com/assets/636048/18408729/21dbf376-772f-11e6-8b7a-f8f8ed0ac2c6.png)


![20160910-081550_capture](https://cloud.githubusercontent.com/assets/636048/18408732/4495d03a-772f-11e6-9f54-745546b29b8a.gif)

**Comment by jekkos** [comment]
Only difference I see is the currency / locale settings

**Comment by jekkos** [comment]
@chandrawg tell me what locale / currency symbol did you fill in?

**Comment by daN4cat** [comment]
Not only, he has 4 stock locations, I didn't try that. Maybe there is something related to that?

**Comment by odiea** [comment]
It appears to be the International currency symbol but how did he get 3 decimal for currency?

**Comment by chandrawg** [comment]
this is my locale setting
![local](https://cloud.githubusercontent.com/assets/21230424/18411037/deed3048-77a1-11e6-97fc-ae1621e0e3cf.jpg)

**Comment by odiea** [comment]
Will you change your currency decimal to 2 and see if that changes anything.

**Comment by chandrawg** [comment]
@odiea already try it but still error

**Comment by chandrawg** [comment]
the trouble maker is thousand separator. if unchecked, everything is normal.

**Comment by odiea** [comment]
Glad you figured that out. Do you need the thousand separator? If so then more programming may be needed.

**Comment by chandrawg** [comment]
yes i need it because idr have to many digit :)

**Comment by daN4cat** [comment]
Ok, so we now know the root cause. Thousand separator with the quantity.

**Comment by jekkos** [comment]
Beside composer branch let's consider this the last open bug before the release?

**Comment by daN4cat** [comment]
So it looks (and in composer there is an issue with invoice pdf but let's leave it to that issue).

**Comment by jekkos** [comment]
Currently trying to reproduce this nice little bug. .I have configured following

locale: id, thousands separator: on, currency symbol: Rp
but no problem whatsoever I can update quantities just fine.

**Comment by daN4cat** [comment]
@jekkos quantities must be 0, that's the issue

**Comment by daN4cat** [comment]
@jekkos can we give a kick and sort this one so we merge composer and release 3.0?

**Comment by jekkos** [comment]
Think I found the culprit here, will push the fix later today

**Comment by jekkos** [comment]
@chandrawg Can you verify if it's ok?

**Comment by daN4cat** [comment]
Tested and seems to work fine now.

**Comment by chandrawg** [comment]
work fine. thanks very much

**Comment by mo300** [comment]
i steel have the same issue in admin the quantity is OK and i can complete sale but i create new employee the quantity is zero and employee can't sale ... can any one help of that... or is there is a new released OSPOS working on @jekkos  

this image for employee the quantity is zero but in admin is ok

![image](https://user-images.githubusercontent.com/25662498/46427690-56090200-c742-11e8-9a6f-030ffb1730b2.png)

**Comment by odiea** [comment]
Both of your images are showing the quantity as 1. This may be a language specific issue because I have not had an issue with the current 3.2.3.

**Comment by mo300** [comment]
yes it's the language  @odiea and the stoke, i made 3 stokes and it's work fine, but when you create new employee and choose the stokes for employee it's unchecked them by it self ... but finally it's work.. thanks so much
