### ISSUE TITLE
Currency Symbol Doesn't show in Emailed Invoice

### ISSUE THREAD

**Issue by onyema3** [jekkos/opensourcepos#839]
Before submitting an issue please make sure you tick (add a x between the square brakets) and agree all the following check boxes:

- [X] Checked the current issues database and no similar issue was already discussed
- [X] Read the README, WHATS_NEW and UPGRADE
- [X] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas
- [X] Reporting an issue of an unmodified OSPOS installation
- [X] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [X] PHP version is at least 5.5 and not 7.x
- [X] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [x] Know the name and version of OS, Web server and MySQL and will add to my issue report

IMPORTANT: If you remove the template when submitting an issue your issue will be closed.

### Installation information
New installation of OSPOS 3.0.0 Open Source Point Of Sale Version 3.0.0 - 4f5ad57.
Apache Version	2.2.31
PHP Version	        5.5.34
MySQL Version	5.6.31
Architecture	        x86_64
Operating System	linux

### Expected behaviour
Currency Symbol shows in emailed invoice

### Actual behaviour
Currency symbol doesn't show in emailed invoice

### Steps to reproduce the issue
Change currency to ₦

**Comment by onyema3** [comment]
I think it has something to do with my currency symbol because once you change the symbol to $ it shows in the emailed invoice.

**Comment by jekkos** [comment]
Might be an encoding issue.

**Comment by onyema3** [comment]
can it be fixed easily?

**Comment by jekkos** [comment]
The token is wrong in the final PDF I suppose? Might be hard to fix in that case

**Comment by jekkos** [comment]
There used to be a separate accessible invoice view used as input for the PDF, which you could check first to see if it appears there as well; but that controller method was deleted some time ago by @daN4cat

**Comment by jekkos** [comment]
If the currency sign is wrong in that view then it might be easier to fix. But if it is a PDF font issue then it might take some more time.

**Comment by onyema3** [comment]
In Takings invoice view everything shows fine but once it is emailed the
currency symbol dissappears in the PDF

**Comment by daN4cat** [comment]
@onyema3 the pdf generation part is tricky. I once tried to touch it to adjust the code and suddenly without understanding why it didn't work. On the other hand I fixed another bug that was a bit annoying.

It could be a font issue indeed unless there is something related to UTF-8? I don't know as I'm just guessing here but I'm sorry no help from me because I don't need invoices and I already improved that area few times.

**Comment by onyema3** [comment]
awww, so sad :(
Jekkos are you willing to help?

**Comment by jekkos** [comment]
I have already done a quick check yesterday and restored the debug view, which shows the currency sign correctly. So in this case it is probably a DOMPDF issue. This might make it an expensive bug.. I've spent quite some time fighting with DOMPDF before and never really understood why it does or doesn't work.

**Comment by jekkos** [comment]
On the other hand I was planning to move to composer managed DOMPDF dependency in the other branch.. but not sure if that will fix the issue after all.

**Comment by daN4cat** [comment]
@jekkos is that the only pdf support we can get? I believe bstables export pdf so it could be an option to reuse? But I guess that's us not php.

**Comment by daN4cat** [comment]
BTW I spotted that DOMPDF is licensed under LGPL and we didn't add the license in the list. Something to sort out.
We should restructure a bit 3rd party libraries location, I hope with composer branch we get this sorted.

**Comment by daN4cat** [comment]
And there is a newer version of DOMPDF here: https://github.com/dompdf/dompdf with Composer support.
Maybe we should update it to the latest?

**Comment by daN4cat** [comment]
Worth investigating: _PDF documents internally support the following fonts: Helvetica, Times-Roman, Courier, Zapf-Dingbats, & Symbol. These fonts only support Windows ANSI encoding. In order for a PDF to display characters that are not available in Windows ANSI you must supply an external font._

**Comment by jekkos** [comment]
I think DOMPDF includes some of those font files. Indeed idea was to reorganise the external PHP dependencies and eventually add those licenses as well. Composer seems to have a license command that generates a json for the installed deps

**Comment by onyema3** [comment]
Looks like a font issue
https://github.com/dompdf/dompdf/issues/1123
and also a guide to enabling unicode
https://github.com/dompdf/dompdf/wiki/UnicodeHowTo

**Comment by daN4cat** [comment]
@onyema3 that's probably something you can play with and let us know how it goes.

**Comment by onyema3** [comment]
Lol....where do I begin from?

**Comment by daN4cat** [comment]
Install MBString support in PHP , see UnicodeHowTo wiki

**Comment by onyema3** [comment]
Will give it a shot

**Comment by daN4cat** [comment]
Good, DOMPDF_UNICODE_ENABLED is already true in dompdf_config.inc.php

**Comment by onyema3** [comment]
Yes, I checked

**Comment by onyema3** [comment]
Still not working with all these.
I bumped into this on the net while searching for a solution:

Anything prior to 0.6.x has limited support for characters outside
iso-8859-1 encoding. The Euro is supported in 0.5.x by using the
appropriate Windows ANSI character code (&#0128;), but otherwise you have
to jump through some PDF encoding hoops.

The 0.6.0 release has better support for "special" characters. The default
encoding is based on Windows ANSI (one of the few recognized by the PDF 1.3
spec). You can enable better character support by loading a Unicode-based
font and enabling Unicode in dompdf and specifying that encoding in your
document.

Updating DOMPDF might hold the key to solving this

**Comment by daN4cat** [comment]
Version is 0.6.*

**Comment by onyema3** [comment]
Add that code where you would normally want the symbol to appear. For ₦ try:

<span style="font-family: DejaVu Sans;">&#x20A6;</span>

*Note: in dompdf 0.6.0 or newer*

**Comment by jekkos** [comment]
I have installed DOMPDF 0.6 in composer branch now. Did a quick test and pdf generation seems ok. However didn't try to change this in the template (it's not showing the currency symbol by default)

**Comment by daN4cat** [comment]
Latest DOMPDF in GitHub is 0.7.*, so it might be that they fixed something with that.
I'll try to update the code in master to the latest.

**Comment by jekkos** [comment]
Ok no I added 0.7 to composer branch. Maybe save yourself the effort and just test that branch instead?

**Comment by daN4cat** [comment]
@onyema3 I've updated the html to pdf support Dompdf to 0.7.0 in master. I just did a smoke test but I seem to fail to send emails for some other reason.
So please test and let me know if it works, if not I'll revert the commit to master.

I don't have more time today to spend on this.

@jekkos thanks, I saw you added it to composer. I will need to switch to that branch and test.

**Comment by onyema3** [comment]
@dan4cat, i just tested it.
Still same the currency symbol still not showing

**Comment by jekkos** [comment]
I did a fix in composer branch, works fine now. 
![schermafdruk van 2016-09-07 17-08-15](https://cloud.githubusercontent.com/assets/576234/18317352/216fde10-751e-11e6-95bd-84b37e4ac9e5.png)

acknowledgments and / or donations are welcome. ;). ( I need to pay for hosting + cellular internet subscription to fix these bugs while on the train to work )

**Comment by onyema3** [comment]
Great...
Update masters.......

**Comment by onyema3** [comment]
@jekkos, i just chipped in a little something for the trouble via paypal

**Comment by daN4cat** [comment]
Fix in master now.

**Comment by jekkos** [comment]
@daN4cat thanks for the merge .. should be good now

**Comment by jekkos** [comment]
@onyema3 thanks for the contribution!

**Comment by onyema3** [comment]
I can confirm this fix.
Thanks
