### ISSUE TITLE
Some pages not loading fully

### ISSUE THREAD

**Issue by ClinsBlinkz** [jekkos/opensourcepos#840]
Before submitting an issue please make sure you tick (add a x between the square brakets) and agree all the following check boxes:

- [x] Checked the current issues database and no similar issue was already discussed
- [x] Read the README, WHATS_NEW and UPGRADE
- [x] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas
- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [x] PHP version is at least 5.5 and not 7.x
- [x] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [x] Know the name and version of OS, Web server and MySQL and will add to my issue report

IMPORTANT: If you remove the template when submitting an issue your issue will be closed.

### Installation information
It installed properly. I installed the latest version, I believe 3.0 with this link https://github.com/jekkos/opensourcepos/archive/master.zip
Everything installed properly (Kudos, the new design is awesome)

### Expected behaviour
I expected when i click on store cofig int the menu bar, that the page would load properly and I would be able to do my configurations.

### Actual behaviour
The page loads but a dark overlay covers it and it keeps loading as my mouse indicates so. Here is an attached screenshot. It does so for hours. The application is so beautiful I wish it would just load properly.
![capture](https://cloud.githubusercontent.com/assets/8158349/18255031/c141f122-739c-11e6-8cc1-b0d3f2bd9e87.PNG)

### Steps to reproduce the issue
I used chrome and firefox (Latest versions as of today 05th of August 2016) and the issue persisted.
Seems like a css or js issue. 
I really would love help from you.

**Comment by daN4cat** [comment]
@ClinsBlinkz see if #827 can help, pay attention to what needs to be installed in PHP. Please also check error_log.

**Comment by ClinsBlinkz** [comment]
Thanks. I am currently running xampp v3.2.1
php requirements are ok... and i couldn't see an error_log file.

**Comment by onyema3** [comment]
is php_intl.dll intalled?

**Comment by ClinsBlinkz** [comment]
Thanks. I thought xampp installs all the needed php files to run php.
I really don't know. How do I check? Please..

**Comment by onyema3** [comment]
Check your php.ini and uncomment it

**Comment by odiea** [comment]
Start the xampp control panel.
Next to apache you will see config.
click on it.
Choose the php.ini to edit.
Scroll down about midway and you will see a list of extensions. Uncomment the needed ones.

**Comment by odiea** [comment]
Look at #827 for the needed modules. Restart the apache server then give it a try.

**Comment by Altoubi** [comment]
I`m also have same problem !
i am using WampServer 2.4.9

**Comment by odiea** [comment]
If we get any feedback from anyone we will know that the heck is going on with xampp and wampp.

**Comment by odiea** [comment]
Yes not uncommenting extension=php_intl.dll appears to be the issue. Just tested on fresh xampp server.

**Comment by daN4cat** [comment]
We should add in the wiki the config setup for all these servers otherwise we keep going in circles.

**Comment by ClinsBlinkz** [comment]
Thanks guys, the php extentions were commented. I uncommented them and it worked... 
I appreciate the support.

**Comment by Altoubi** [comment]
its keep not working in both case commented/uncommented  extension=php_intl.dll

iam using wampp server

**Comment by daN4cat** [comment]
Read the FAQ from the README.md?

**Comment by Altoubi** [comment]
![untitled](https://cloud.githubusercontent.com/assets/12825416/18342696/2383d474-75c1-11e6-9f6d-253dc2f96040.png)
yes, but same problem

php.ini


extension=php_bz2.dll
extension=php_curl.dll
extension=php_com_dotnet.dll
extension=php_fileinfo.dll
extension=php_gd2.dll
extension=php_gettext.dll
extension=php_gmp.dll
extension=php_intl.dll
extension=php_imap.dll
;extension=php_interbase.dll
extension=php_ldap.dll
extension=php_mbstring.dll
extension=php_exif.dll      ; Must be after mbstring as it depends on it
extension=php_mysql.dll
extension=php_mysqli.dll
;extension=php_oci8.dll      ; Use with Oracle 10gR2 Instant Client
;extension=php_oci8_11g.dll  ; Use with Oracle 11gR2 Instant Client
extension=php_openssl.dll
;extension=php_pdo_firebird.dll
extension=php_pdo_mysql.dll
;extension=php_pdo_oci.dll
;extension=php_pdo_odbc.dll
;extension=php_pdo_pgsql.dll
extension=php_pdo_sqlite.dll
;extension=php_pgsql.dll
extension=php_shmop.dll

**Comment by Altoubi** [comment]
I try it on online server and it same problem !!!! 


@jekkos

**Comment by ClinsBlinkz** [comment]
@Altoubi if you've done that on your local server, do a fresh install and new db, restart your system if possible. Worked for me. Your php.ini settings are ok as I see here.

**Comment by jekkos** [comment]
@Altoubi did you try docker install? Should work fine

**Comment by Altoubi** [comment]
@jekkos i use this setps https://github.com/jekkos/opensourcepos#local-install

**Comment by daN4cat** [comment]
Probably the math library is missing, now I can't remember from the top of my head the correct name.

**Comment by daN4cat** [comment]
@Altoubi should be extension=php_bcmath.dll
