### ISSUE TITLE
Possible header changes

### ISSUE THREAD

**Issue by odiea** [jekkos/opensourcepos#843]
```
This is the first thing I do with a new download. I believe it looks better.
<style type="text/css">
		html {
			overflow: auto;
		}
.navbar-nav {
float:none;
margin:0 auto;
display: block;
text-align: center;

}

.navbar-nav>li {
display: inline-block;
float:none;
}
	</style>

Then change <ul class="nav navbar-nav navbar-right"> to <ul class="nav navbar-nav">

**Comment by jekkos** [comment]
screen shot of how it looks like?

**Comment by odiea** [comment]
I will get a screen shot later. The navbar icons are just aligned center instead of right aligned and when you change permissions for employees those navbar icons align center.

**Comment by daN4cat** [comment]
OK, personally I prefer right align as that's the old design too.

**Comment by odiea** [comment]
![2016-09-07 15_08_46-wedidit _ powered by ospos 3 0 0](https://cloud.githubusercontent.com/assets/10962177/18328663/0d8fc04c-750d-11e6-8b31-eeaaa10b92fc.png)

**Comment by odiea** [comment]
Here is how it looks with the OSPOS removed and with less permissions.
![2016-09-07 16_02_47-wedidit _ powered by ospos 3 0 0](https://cloud.githubusercontent.com/assets/10962177/18330248/afa25e88-7514-11e6-85e9-71503c17c5f7.png)

**Comment by odiea** [comment]
The old design also had the larger powered by in the navbar.
![2016-09-07 16_05_05-open source point of sale -- powered by os point of sale](https://cloud.githubusercontent.com/assets/10962177/18330300/f82810e4-7514-11e6-9bef-52755739d8ac.png)
