### ISSUE TITLE
please help! I want to completely disable the function, csrf_set_hash

### ISSUE THREAD

**Issue by duonghien201089** [jekkos/opensourcepos#845]
please help! I want to completely disable the function, **csrf_set_hash**. When you edit anything on the footer are locked

![2222](https://cloud.githubusercontent.com/assets/16084308/18339601/acaa6746-75ca-11e6-94f3-3d39e44e10ff.png)

**Comment by daN4cat** [comment]
Please use the template and read previous cases similar to your one.

I close.

**Comment by daN4cat** [comment]
Also I suggest to read the license file COPYING.
