### ISSUE TITLE
How to display images in this???

### ISSUE THREAD

**Issue by duonghien201089** [jekkos/opensourcepos#846]
#How to display images in this? Thanks all

![xxxxxxx](https://cloud.githubusercontent.com/assets/16084308/18345196/a0c942fc-75e4-11e6-833f-f112e0a56034.png)

**Comment by duonghien201089** [comment]
please help me!!!!!!!!!!!

**Comment by daN4cat** [comment]
Let us know if you find a solution.

**Comment by duonghien201089** [comment]
Yes I have received your copyright notice, I will adhere to copyright

**Comment by daN4cat** [comment]
Good
