### ISSUE TITLE
Customer form fields are not visible & Loading new page issue

### ISSUE THREAD

**Issue by fahadrasheed** [jekkos/opensourcepos#847]
Customer Module:
when i click on new customer a new form open but have no fields .please help me.as sson as possible.
![customer](https://cloud.githubusercontent.com/assets/22078314/18352834/d1b8f9b6-7594-11e6-893b-2303071e7ae5.jpg)
Receivings Module:
when i click on receiving .page start loading and u can not perform anything.kindly solve my problem plz.
![receivings](https://cloud.githubusercontent.com/assets/22078314/18352923/31374d48-7595-11e6-9117-074ca58a2fc7.jpg)

**Comment by fahadrasheed** [comment]
sorry i didnot see the old thread...bcz i am new in this form thats why

**Comment by daN4cat** [comment]
@fahadrasheed the issue template that you decided to remove says check existing cases.
