### ISSUE TITLE
Barcode scanner missing digits

### ISSUE THREAD

**Issue by petercstevenson** [jekkos/opensourcepos#849]
### New Feature or Enhacement

For new Features or Enhacements please remove all the template text and clearly write your proposal.
It's important to state whether you expect the community to implement it or you will contribute the work.
Please bear in mind that we will implement new features only on the current code, there is no support for old versions.

### Issue, Question or Bug

Before submitting an issue please make sure you remove the first section of the template and you tick (add a x between the square brakets) and agree with all the following check boxes:

- [x] Checked the current issues database and no similar issue was already discussed
- [] Read the README, WHATS_NEW and UPGRADE
- [x] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php5-gd, php-intl and sockets installed)
- [] Reporting an issue of an unmodified OSPOS installation
- [] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [] PHP version is at least 5.5 and not 7.x
- [] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [] Know the name and version of OS, Web server and MySQL and will add to my issue report

IMPORTANT: If you remove the template when submitting an issue your issue will be closed.

### Installation information

Web installation

### Expected behaviour

Barcode scanner should enter in number as read

### Actual behaviour

Barcode scanner often misses digits, especially repeated digits (i.e. 53336 might end up as 5336)

### Steps to reproduce the issue

When I try searching for an item using my barcode scanner, it often misses the digits. At first I thought that this was a hardware problem, but if I try using the scanner on a text file, it works every time. My scanner is a Gullor USB Automatic Handheld Laser Barcode Scanner.

**Comment by jekkos** [comment]
Maybe the scanner emits some extra control characters? Maybe enable this in notepad++ and check the output?

**Comment by jekkos** [comment]
Or reconfigure the scanner's timing and see if that helps?

**Comment by petercstevenson** [comment]
I am starting to think that this is a hardware issue again. The issue doesn't seem like it is the control characters, it seems like it is the timing. I just tried using this scanner on another online search page, and it started missing digits again. And unfortunately, the scanner doesn't have configurable timing. I have ordered another barcode scanner and if it works when it arrives then I guess this can be closed.

**Comment by daN4cat** [comment]
Have you tried different barcode types?

**Comment by daN4cat** [comment]
Is this still an issue?

**Comment by petercstevenson** [comment]
The barcode scanner arrived without a cable and my cable didn't work so I still haven't been able to test it out. I will close this for now assuming that it is a hardware problem and will let you know if the problem persists.

**Comment by petercstevenson** [comment]
The cable arrived and this issue seems to be resolved.

**Comment by daN4cat** [comment]
Good
