### ISSUE TITLE
Add decimal support for quantities

### ISSUE THREAD

**Issue by alex4108** [jekkos/opensourcepos#85]
Allow my item quantities to be accurate up to at least 3 decimal points so that exact weights of product can be entered during sales

**Comment by jekkos** [comment]
think this is already implemented. You can configure decimal separator in the config screen.
not sure whether it is applied in

**Comment by joerony** [comment]
it doesn't work in quantity of inventory, chief. Do you have any idea for this?

**Comment by daN4cat** [comment]
You have already open #429, no need to duplicate.
