### ISSUE TITLE
Taxes not shown in receipt

### ISSUE THREAD

**Issue by petercstevenson** [jekkos/opensourcepos#850]
### New Feature or Enhacement

For new Features or Enhacements please remove all the template text and clearly write your proposal.
It's important to state whether you expect the community to implement it or you will contribute the work.
Please bear in mind that we will implement new features only on the current code, there is no support for old versions.

### Issue, Question or Bug

Before submitting an issue please make sure you remove the first section of the template and you tick (add a x between the square brakets) and agree with all the following check boxes:

- [x] Checked the current issues database and no similar issue was already discussed
- [] Read the README, WHATS_NEW and UPGRADE
- [x] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php5-gd, php-intl and sockets installed)
- [] Reporting an issue of an unmodified OSPOS installation
- [] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [] PHP version is at least 5.5 and not 7.x
- [] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [] Know the name and version of OS, Web server and MySQL and will add to my issue report

IMPORTANT: If you remove the template when submitting an issue your issue will be closed.

### Installation information

Web install

### Expected behaviour

Taxes should show up in receipts

### Actual behaviour

There is no subtotal or taxes shown in receipt

### Steps to reproduce the issue

If I make a sale and try printing a receipt, it shows the prices before tax for each item, and then it shows the total after tax as a total. But no where does it show the taxes or the subtotal.

**Comment by jekkos** [comment]
Might be an issue in the print css. I have never enabled this option for the receipt anyway.

**Comment by daN4cat** [comment]
@odiea do you have this problem?

**Comment by odiea** [comment]
I am not using a receipt printer just a standard laser printer so it looks good on my end.
![2016-09-10 04_52_44-new notification](https://cloud.githubusercontent.com/assets/10962177/18409958/a50dd84e-7712-11e6-9e9a-8fee43c76a22.png)

**Comment by odiea** [comment]
On Store config does he have show taxes enabled?
![2016-09-10 04_55_45-](https://cloud.githubusercontent.com/assets/10962177/18409977/f7ac0288-7712-11e6-8acb-d2598cf25dc4.png)

**Comment by odiea** [comment]
Here is a shot with tax included.
![2016-09-10 05_14_27-new notification](https://cloud.githubusercontent.com/assets/10962177/18410095/90eaee4e-7715-11e6-8974-cfa283976099.png)

**Comment by odiea** [comment]
This is what it looks like when show taxes is not checked.
![2016-09-10 06_15_19-new notification](https://cloud.githubusercontent.com/assets/10962177/18410365/1409c04a-771e-11e6-8572-0c575db322b6.png)

**Comment by petercstevenson** [comment]
The show taxes button was not checked in the Store Config. Thank you; that fixed the problem. I wonder if it might be worth just enabling that by default, or having it set up such that it is enabled whenever taxes are entered.

**Comment by daN4cat** [comment]
We welcome help with the wiki and user manual if you feel like contributing...

**Comment by onyema3** [comment]
What kinda help?

**Comment by daN4cat** [comment]
User manual one. If people could write a section we can copy to the wiki.

Also we should write a bit how to install OSPOS on Windows based systems as we keep having the same questions.
