### ISSUE TITLE
Enhancement request - Categories section, and drop-down select in Items. 

### ISSUE THREAD

**Issue by dawzilla** [jekkos/opensourcepos#851]
Hello,

I am hoping you can help me with this enhancement request. I would like a categories menu (perhaps a switchable on-off feature in Settings) so that I can create categories first, then under the Items menu when inputting new data, select the Category as a drop-down: perhaps an input field with a drop-down beside, for creating a quick new category or selecting?

Reason being is i feel this simple and yet important feature without it in place can make adding items manually quite laborious and open to human error. Also if you have long category names its quite convoluted to add them each time.

Maybe the categories top menu and separate area doesn't need to exist, but could exist in the mysql as a separate table and the items menu data input area could offer previous categories, so as to free up space in the top menu?

Please Please Please implement it.

**Comment by jekkos** [comment]
See also #68. This might be the next new feature after 3.0. @dawzilla Maybe a little pledge can help
