### ISSUE TITLE
A PHP Error was encountered

### ISSUE THREAD

**Issue by syeipto** [jekkos/opensourcepos#852]
aku install PHP dari alamat : [opensourcepos](https://github.com/jekkos/opensourcepos)

*Ini bagian errornya 

A PHP Error was encountered
Severity: Warning
Message: parse_url(/customers/view/-1/width:400/random:1473541168618) [function.parse-url]: Unable to parse URL
Filename: core/URI.php
Line Number: 219

Mohon solusinya...

**Comment by daN4cat** [comment]
Use the template
