### ISSUE TITLE
No receivings in detailed report

### ISSUE THREAD

**Issue by petercstevenson** [jekkos/opensourcepos#853]
### New Feature or Enhacement

For new Features or Enhacements please remove all the template text and clearly write your proposal.
It's important to state whether you expect the community to implement it or you will contribute the work.
Please bear in mind that we will implement new features only on the current code, there is no support for old versions.

### Issue, Question or Bug

Before submitting an issue please make sure you remove the first section of the template and you tick (add a x between the square brakets) and agree with all the following check boxes:

- [x] Checked the current issues database and no similar issue was already discussed
- [] Read the README, WHATS_NEW and UPGRADE
- [x] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php5-gd, php-intl and sockets installed)
- [] Reporting an issue of an unmodified OSPOS installation
- [] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [] PHP version is at least 5.5 and not 7.x
- [] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [] Know the name and version of OS, Web server and MySQL and will add to my issue report

IMPORTANT: If you remove the template when submitting an issue your issue will be closed.

### Installation information

Web install

### Expected behaviour

Receivings should show up in Detailed Receivings Report

### Actual behaviour

Detailed Receivings Report is always empty

### Steps to reproduce the issue

1. Create a receiving
2. Click on Detailed Reports -> Receivings

**Comment by agungwizz** [comment]
Hi...
Check your date setting...
Thank you

**Comment by petercstevenson** [comment]
Thank you, @agungwizz. It does seem to be a time zone issue. There appears to be three different times being used in ospos. The date in the top header of the screen is always set to the correct time regardless of what time zone I manually set. The receipts, on the other hand, seem to reflect the time zone set in Store Config. Finally, the detailed receivings report seems to be always set to GMT-1. The reason why I couldn't find my receivings last night was because the date was set 7 hours ahead so it would have been reflected in the next day's report.

**Comment by daN4cat** [comment]
The wall clock time is based on the web browser location. It's client side generated not server side.

It's strange that the receiving receipts are not printed according to the timezone set in the Store Config, that should not be the case.

Could you please countercheck it is really the issue?
@odiea have you noticed anything similar?

**Comment by petercstevenson** [comment]
BTW, the detailed sales report lists the correct time. It seems like it is just an issue for the receivings.

**Comment by odiea** [comment]
No issues here when running the Detailed Receivings report or with the receipt. The receipt image shows the clock time as displayed. The Report shows the clock time also.

![2016-09-11 11_09_01-](https://cloud.githubusercontent.com/assets/10962177/18419062/7f8dd05c-7810-11e6-931f-cb3f0eaaf4fc.png)
![2016-09-11 11_10_30-new notification](https://cloud.githubusercontent.com/assets/10962177/18419064/8a7072cc-7810-11e6-8d56-a73824956af5.png)

**Comment by petercstevenson** [comment]
More peculiar behaviour:

1. I create a new receiving now (11:08 AM).
2. A receivings receipt is displayed giving the correct time (RECV 11)
3. I go to Detailed Receivings Report and the time is given as 6:08 PM
4. I click on RECV 11 to look at the actual receipt and the receipt is now listed as 6:08 PM

So somewhere in there the date got changed. @odiea are you in GMT?

**Comment by odiea** [comment]
I am in GMT-7:00 Mountain Time USA

**Comment by daN4cat** [comment]
Is this still an issue?

**Comment by petercstevenson** [comment]
It is not fixed for me but it seems like no one else has been able to recreate it.

**Comment by daN4cat** [comment]
And have you set the timezone in your server and not changed in php configuration?

All the timing set in the transactions are based on server one used by php.
The wall clock is local to your browser and has nothing to do with the transactions.

Search criteria by date are preset with the server date/time.

I would assume that people will set the same time across as having a server with one timezone and a web browser client with another doesn't make too much sense to me.

**Comment by jekkos** [comment]
@petercstevenson You are running the docker setup, right? Might be a bug then because of this 

`RUN echo "date.timezone = \"UTC\"" > /usr/local/etc/php/conf.d/timezone.ini`

Timezone is set to UTC in php.ini upon initialization. I'll try to see whether I can add a parameter to configure that properly in the stack file.

**Comment by daN4cat** [comment]
Yes he uses docker. Good to have found a tester for that :-)

**Comment by jekkos** [comment]
I think his first intention was to just be a user, so I surely appreciate the feedback. Normally these kind of issues would not be solved in the project (as this is pure setup related) but docker kind of changes that idea (they call it devops these days). I have no other choice than add support for that as well.

**Comment by daN4cat** [comment]
Yes, it's not pure software coding issue but deployment one.
Anyway nowadays you start from concept to deployment, so this fits the picture anyway since it was added as part of the OSPOS concept.

**Comment by jekkos** [comment]
I have done a fix for this in docker-cloud.yml. Timezone is now configurable as an environment variable. You should redeploy the stack by adding the new env parameter with the correct timezone filled in. Before that you should run this command to update the file inside the container

`docker-cloud container exec web-1 sed -i "s/UTC/\${PHP_TIMEZONE}/g" /usr/local/etc/php/conf.d/timezone.ini`

**Comment by jekkos** [comment]
Only run that command if you don't want to redeploy completely, it should adapt the file and thus load the new enviroment variable that you add in the stack yml file

**Comment by jekkos** [comment]
It seems that docker cloud was updated and that redeploying to a latest image version has become easier. Go to stacks tab and click redeploy. It will ask whether you want to keep data or not. After this action you should be on the latest image.

After that you will still need to add the timezone variable to the stack configuration. The container itself should have the correct parameter for datetime after redeploy.

**Comment by daN4cat** [comment]
so this is now on @petercstevenson to test

**Comment by petercstevenson** [comment]
How is the environment variable set? I have tried adding `PHP_TIMEZONE=America/Vancouver` to the stack file, but that didn't seem to work. I also tried `PHP_TIMEZONE='America/Vancouver'`

**Comment by daN4cat** [comment]
Maybe this can help: https://www.inmotionhosting.com/support/website/php/setting-the-timezone-for-php-in-the-phpini-file? I didn't check the docker thingy myself, so not sure that URL applies correctly for the case but give a read.

**Comment by jekkos** [comment]
Normally if the php.ini file is updated then it  should pick up this value directly from the stack file. I double checked the value set by checking phpinfo()

**Comment by daN4cat** [comment]
(@jekkos with regards to your DevOps comment above, the concept of DevOps is that the team that develops even deploys and maintains too, that's why Development + Operations -> DevOps
Indeed having added the docker and etc. is a means to package your development and automate the deployment. Once you have done you maintain :-) ).

**Comment by petercstevenson** [comment]
I did some more testing. `echo $PHP_TIMEZONE` gives me America/Vancouver, so I know that's not the problem. However, `date` gives me UTC. I tried `export TZ=America/Vancouver` which changed `date` to the correct time, but it still didn't change the situation in OSPOS. This was all done in the web container.

**Comment by petercstevenson** [comment]
Am I supposed to reassign this? Or is there more testing that I can do?

**Comment by daN4cat** [comment]
Probably @jekkos needs to do something more here.

**Comment by jekkos** [comment]
Ok can you check phpinfo in this case? I need to know whether the setting was picked up correctly. I tested this on a local docker compose and it seemed to work. Maybe you can check whether the timezone file is present in the container, it should be at /usr/local/etc/php/conf.d/timezone.ini

if it is present then try following command in the web container

```
cat << EOF > /var/www/html/phpinfo.php
<?php echo phpinfo(); ?>
EOF
```
then search for date.timezone  and check it's value.

**Comment by petercstevenson** [comment]
Thanks, @jekkos. I have followed your instructions and everything seems to be correctly set to America/Vancouver. It seems that OSPOS must be getting the wrong time from somewhere else

**Comment by daN4cat** [comment]
We can close then.

**Comment by petercstevenson** [comment]
Wait, why did you close this? It seems like this is still a bug. Somewhere something is set to UTC but we just don't know where yet.

**Comment by jekkos** [comment]
@petercstevenson So you say that phpinfo now has the correct value for date.timezone? But you see a wrong timestamp where exactly? You mean the receivings bug is still there?

**Comment by petercstevenson** [comment]
The bug is still there. phpinfo shows the correct timezone but the receiving are still getting recorded in UTC.

**Comment by daN4cat** [comment]
@petercstevenson do you have the same problem in sale?

**Comment by petercstevenson** [comment]
No, the detailed sales report gives the correct time

**Comment by daN4cat** [comment]
Right Detailed Receiving. I looked into the wrong thing, receipt.
I'll check the code of receiving against sale one to see if there is any issue there.

**Comment by jekkos** [comment]
This is not a docker related bug per se, it just surfaces because he's using it.
Sales is using a php generated timestamp while receivings is relying on a database current_timestamp. php and mysql are running in separate containers and timezone is only configured on the php side. This might cause the time to be wrong for the mysql container causing this issue.

I would like to have a consistent date generation here and stick with php timezone config. However the fact that mysql is not inserting a correct date might need to be fixed as well (as other functionality might depend on it).

**Comment by daN4cat** [comment]
Indeed and that's why I said I need to check the code for the detail receiving report as it might a bug there.

**Comment by daN4cat** [comment]
@petercstevenson could you please check with the latest code in master? I fixed something in Receivings but I'm not 100% sure and I don't have means to test your case. So please help with the test.

**Comment by petercstevenson** [comment]
The MySQL container is now crashing with exit code 7. Do I need to upgrade my server again to > 1 gb RAM?

**Comment by petercstevenson** [comment]
Upgrading my server didn't help. Is there some way to use an earlier commit until this is resolved? I need to have a working system for my store tomorrow

**Comment by jekkos** [comment]
No I tried to add an optimized mysql config file but it didn't seem to work so I removed it again in my latest commit. Try to redeploy with the latest now and should be fine.

**Comment by petercstevenson** [comment]
Thanks. The MySQL container is no longer crashing. However, I now get this error message on the login page: 
![screenshot from 2016-10-13 05 07 50](https://cloud.githubusercontent.com/assets/21316584/19348492/09a7e8e4-9103-11e6-957e-d662326522e0.png)

And this error after logging in:

![screenshot from 2016-10-13 05 09 43](https://cloud.githubusercontent.com/assets/21316584/19348558/60b7d144-9103-11e6-95e9-12584945c7b6.png)
![screenshot from 2016-10-13 05 09 48](https://cloud.githubusercontent.com/assets/21316584/19348559/60b9cb20-9103-11e6-85c6-2707a09b2cdf.png)

**Comment by petercstevenson** [comment]
BTW the only script update that I have done is upgrade employees table. Do I also need to run the alter config table portion of the 2.4 to 3.0 script?

**Comment by petercstevenson** [comment]
OK, I took the plunge and ran the alter table portion of the 2.4 to 3.0 script and OSPOS is back running again in time for opening hours.

**Comment by jekkos** [comment]
That was due to the compose upgrade. Indeed the database needed one extra language key. Sorry for the inconvenience there. 
The code won't change that much from what will be released this or next week. Two translations need to be done and after that release notes will be written.

**Comment by jekkos** [comment]
Pushed another fix for this. The receivings registration will now take the php time instead of mysql local time (which might be wrong) so should be set correctly.

**Comment by petercstevenson** [comment]
Fixed - thank you
