### ISSUE TITLE
Clean Setup Process

### ISSUE THREAD

**Issue by Modding** [jekkos/opensourcepos#855]
Install process:
It would be good for some users to NOT Use the Command line and phpMyAdmin for installing the Software. You could Take php Snippets like this to install your Software:

http://www.effiziente-webprogrammierung.info/php-scripts/setup-wizard-installer#downloadlizenz

Greetings 

Valentin

**Comment by jekkos** [comment]
There's a docker cloud install that does not require you to install anything (at least not locally). One thing that might need to be improved there is database upgrades. The web image can be automatically redeployed once there is a new version on docker hub (after each commit). Think this request was already made in another issue so will close as it's not specific enough.
