### ISSUE TITLE
Overlay Issue after Login.

### ISSUE THREAD

**Issue by sonnysk76** [jekkos/opensourcepos#856]
### New Feature or Enhacement

For new Features or Enhacements please remove all the template text and clearly write your proposal.
It's important to state whether you expect the community to implement it or you will contribute the work.
Please bear in mind that we will implement new features only on the current code, there is no support for old versions.

### Issue, Question or Bug

Before submitting an issue please make sure you remove the first section of the template and you tick (add a x between the square brakets) and agree with all the following check boxes:

- [1] Checked the current issues database and no similar issue was already discussed
- [1] Read the README, WHATS_NEW and UPGRADE
- [1] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php5-gd, php-intl and sockets installed)
- [1] Reporting an issue of an unmodified OSPOS installation
- [] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [1] PHP version is at least 5.5 and not 7.x
- [1] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [1] Know the name and version of OS, Web server and MySQL and will add to my issue report

IMPORTANT: If you remove the template when submitting an issue your issue will be closed.

### Installation information
Windows 10 / XAMPP  / PHP 5.6.23

### Expected behaviour
After login, go to home page, and have access to the different modules.

### Actual behaviour
After login, go to home page, a modal like overlay shows and lock the application (on Firefox). on Chrome, blank page

### Steps to reproduce the issue
Installation without modification, only the database setup.

To avoid this condition: I modify opensourcepos.js, as follows:
JQuery blockUI plugin.
Line 11218,  showOverlay:true  to false.

did the same modification to opensource.min.js.  

now working.

**Comment by sonnysk76** [comment]
Point Of Sale Versión 3.0.0 - 4f5ad57.

**Comment by sonnysk76** [comment]
Point Of Sale Versión 3.0.0 - 4f5ad57.

**Comment by daN4cat** [comment]
If you need to do that means you are breaching the license.

**Comment by daN4cat** [comment]
@sonnysk76 please read the OSPOS License, read COPYING file or the front page here.
If you don't agree with the License agreement you cannot use OSPOS and we ask you to remove it.

**Comment by sonnysk76** [comment]
Hello.
I think that there is an issue.
Is a fresh installation with the latest commit,  the only modification is the specific local database information.

I don't know why the overly is shown, and then the program don't go further.

I have read the COPYING file, and no modification was made to the footer, information show as it.

Maybe the feature to verify the licence is not working as supposed.

Have a great day.

**Comment by daN4cat** [comment]
@sonnysk76 it works fine.

Please make sure you have everything enabled in your php.ini, read the FAQ in the README.md

**Comment by jekkos** [comment]
Did you change language to french? Try english..

**Comment by jekkos** [comment]
Think french and arabic are not supported

**Comment by sonnysk76** [comment]
Tried English and Spanish.
I'll try on Ubuntu, later today,

**Comment by vimkaf** [comment]
Has anyone found a solution to this issue, this is my first install and i am getting the overlay after login, i have not edited any files only the config/database.php
