### ISSUE TITLE
Route issue login - error 500 - home

### ISSUE THREAD

**Issue by sonnysk76** [jekkos/opensourcepos#857]
### New Feature or Enhacement

For new Features or Enhacements please remove all the template text and clearly write your proposal.
It's important to state whether you expect the community to implement it or you will contribute the work.
Please bear in mind that we will implement new features only on the current code, there is no support for old versions.

### Issue, Question or Bug

Before submitting an issue please make sure you remove the first section of the template and you tick (add a x between the square brakets) and agree with all the following check boxes:

- [1] Checked the current issues database and no similar issue was already discussed
- [1] Read the README, WHATS_NEW and UPGRADE
- [1] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php5-gd, php-intl and sockets installed)
- [] Reporting an issue of an unmodified OSPOS installation
- [] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [1] PHP version is at least 5.5 and not 7.x
- [1] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [1] Know the name and version of OS, Web server and MySQL and will add to my issue report

IMPORTANT: If you remove the template when submitting an issue your issue will be closed.

### Installation information
Windows 10 / XAMPP / PHP 5.6.23
Point Of Sale Versión 3.0.0 - 4f5ad57.

### Expected behaviour
Go from login page to home page, in one step, and log off from home page and go to login page in one step.

### Actual behaviour
After login with valid user and password the browser show an error 500 page, press enter and redirects to home page.
The same happens when log off, show an  error 500 page, press enter and redirects to login page.

### Steps to reproduce the issue
happens everytime using chrome, firefox or IE.

**Comment by daN4cat** [comment]
Are you reporting an issue of something you modified?

**Comment by daN4cat** [comment]
Solved in #859
