### ISSUE TITLE
The localhost page isn’t working  localhost is currently unable to handle this request. HTTP ERROR 500

### ISSUE THREAD

**Issue by kuhen** [jekkos/opensourcepos#858]
Why the page is not loading even after I activate the rewrite module?

![image](https://cloud.githubusercontent.com/assets/12994415/18468039/d0a82d00-79d4-11e6-8e0f-e914c9ccced8.png)

**Comment by daN4cat** [comment]
Your report is too vague, please use the issue report template as that provides information that could help.
Meanwhile I close this issue.

**Comment by daN4cat** [comment]
Fixed see #859 #862
