### ISSUE TITLE
Error 500 at login if a non-english language is selected.

### ISSUE THREAD

**Issue by LordNeoZ** [jekkos/opensourcepos#859]
### Issue, Question or Bug

Before submitting an issue please make sure you remove the first section of the template and you tick (add a x between the square brakets) and agree with all the following check boxes:

- [x] Checked the current issues database and no similar issue was already discussed
- [x] Read the README, WHATS_NEW and UPGRADE
- [x] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php5-gd, php-intl and sockets installed)
- [x] Reporting an issue of an unmodified OSPOS installation
- [] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [x] PHP version is at least 5.5 and not 7.x
- [x] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [x] Know the name and version of OS, Web server and MySQL and will add to my issue report

IMPORTANT: If you remove the template when submitting an issue your issue will be closed.

### Installation information
Windows 10 x64
WAMP 2.5
PHP 5.5.12 (even tho i also have PHP 5.6.13 and the same error occurs)
Apache 2.4.9

### Expected behaviour
When login, you should be redirected at home with the user selected language

### Actual behaviour
Error 500 occurs, refreshing gets you into the admin panel correctly and without any further issue.

### Steps to reproduce the issue
Install and configure other language than "en" and login

### Current solution
Replaced "current_theme()" in line 35 in application/controllers/Login.php for this
	$this->tracking_lib->track_event('Stats', 'Language', $this->config->item('lang'));

And so far i don't have any issue, but i don't know if it breaks something else, because I just started using it like 6 hours ago.

### PHP Error Log
[13-Sep-2016 08:54:15 America/New_York] PHP Fatal error:  Call to undefined function current_language() in C:\wamp\www\proyectos\openphppos\application\controllers\Login.php on line 35

[13-Sep-2016 08:54:15 America/New_York] PHP Stack trace:

[13-Sep-2016 08:54:15 America/New_York] PHP   1. {main}() C:\wamp\www\proyectos\openphppos\index.php:0

[13-Sep-2016 08:54:15 America/New_York] PHP   2. require_once() C:\wamp\www\proyectos\openphppos\index.php:316

[13-Sep-2016 08:54:15 America/New_York] PHP   3. call_user_func_array:{C:\wamp\www\proyectos\openphppos\system\core\CodeIgniter.php:514}() C:\wamp\www\proyectos\openphppos\system\core\CodeIgniter.php:514

[13-Sep-2016 08:54:15 America/New_York] PHP   4. Login->index() C:\wamp\www\proyectos\openphppos\system\core\CodeIgniter.php:514

**Comment by petercstevenson** [comment]
I seem to have this problem even though it is in English

**Comment by daN4cat** [comment]
Fixed and in master.

**Comment by dikangalam212** [comment]
when i login username : admin, password: pointofsale. this message appear. please help me. i instal in localhost. i change database.php already
![ospos issue](https://user-images.githubusercontent.com/29680584/28549390-ddbd4b98-7103-11e7-953a-aeae3443e4e8.png)

**Comment by odiea** [comment]
Nice pic but we have no idea of what you are using. Please read the wiki and the faqs then submit an issue filling out the template.
