### ISSUE TITLE
Need report on Payment Type

### ISSUE THREAD

**Issue by imskriaz** [jekkos/opensourcepos#86]
Hi Admin,

Is it possible to display report on payment types.

**Comment by odiea** [comment]
Under reports have you tried running the payment summary report?

**Comment by imskriaz** [comment]
Thanks for prompt reply. I have tried, but that is only available in summary and graphical, Is it possible to get a detailed report on payment.

**Comment by odiea** [comment]
The only option at this time  would be the Detailed Sales Report. It shows the payment and payment type.

**Comment by imskriaz** [comment]
It would be nice if we can get report on payment mode. Like, List out the payment taken by credit card.

**Comment by jekkos** [comment]
Yes indeed, feel free to make a pull request for this new functionality. Should not be too hard to build.
