### ISSUE TITLE
MySQL crashes weekly

### ISSUE THREAD

**Issue by petercstevenson** [jekkos/opensourcepos#860]
### New Feature or Enhacement

For new Features or Enhacements please remove all the template text and clearly write your proposal.
It's important to state whether you expect the community to implement it or you will contribute the work.
Please bear in mind that we will implement new features only on the current code, there is no support for old versions.

### Issue, Question or Bug

Before submitting an issue please make sure you remove the first section of the template and you tick (add a x between the square brakets) and agree with all the following check boxes:

- [x] Checked the current issues database and no similar issue was already discussed
- [] Read the README, WHATS_NEW and UPGRADE
- [x] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php5-gd, php-intl and sockets installed)
- [] Reporting an issue of an unmodified OSPOS installation
- [] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [] PHP version is at least 5.5 and not 7.x
- [] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [] Know the name and version of OS, Web server and MySQL and will add to my issue report

IMPORTANT: If you remove the template when submitting an issue your issue will be closed.

### Installation information
Web installation

### Expected behaviour

Once the server is running, it should keep running indefinitely

### Actual behaviour

The server crashed early Monday morning and I think that it has actually done this every Monday morning since installation.

### Steps to reproduce the issue

Do the web install and wait.

I received the following error from Docker when the server went down:

mysql-1: Container stopped with exit code 137

in 'FEEDBACK' is disabled.
2016-09-08T01:36:22.908069753Z 160908 1:36:22 [Note] Server socket created on IP: '::'.
2016-09-08T01:36:22.915206419Z 160908 1:36:22 [Warning] 'proxies_priv' entry '@% root@mysql-1' ignored in --skip-name-resolve mode.
2016-09-08T01:36:22.932309429Z 160908 1:36:22 [Note] mysqld: ready for connections.
2016-09-08T01:36:22.932349259Z Version: '10.0.26-MariaDB-1~jessie' socket: '/var/run/mysqld/mysqld.sock' port: 3306 mariadb.org binary distribution

**Comment by jekkos** [comment]
Can you check kernel ring buffer output once mysql crashes? It's probably some cronjob causing an out of memory condition on the hosting setup... which will kill the process using most memory at that very moment (prolly mysql)..

* One option might be upgrading to VPS with more RAM (at least 1gig)
* Tuning mysql settings using customized my.cnf (more advanced using virtualization)
* Disabling cronjob causing the oom condition

**Comment by jekkos** [comment]
Maybe I might need to supply a good default mysql memory configuration together with the docker image..

**Comment by petercstevenson** [comment]
The only one of your suggestions that I was able to carry out without further instructions was upgrading the server. I did this (1 GB of RAM) and the problem seems to be solved. MySQL was also crashing almost every time that I redeployed the system, and this seems to be solved now as well. The only other clue that I can give you is Digital Ocean did show a big spike in CPU usage when MySQL crashed. If you want any further debugging information, you will need to give more more in-depth step-by-step instructions. Otherwise the Cloud Install Using Docker instructions should be changed to indicate that you need to get the 1 GB of RAM Droplet and we can close this.

**Comment by daN4cat** [comment]
Good testing and hints!

**Comment by jekkos** [comment]
This might be due to automatic updates being launched by cron which is probably eating up too much memory. You could check crontab to see if there's anything in there and disable that for the time being?

I do agree that this PHP-MySQL probably needs at least 1Gig of RAM. This is also the case with a bare install so I guess that the docker version will require the same. I'll update the instructions later oN.

**Comment by petercstevenson** [comment]
When I log into the digital ocean console, `crontab -l` gives me "no crontab for root". When I log into the mysql container, `crontab -l` gives me "crontab: command not found"

**Comment by jekkos** [comment]
OK it might be a regular out of memory condition due to mysql configuration. I did some optimization once using mysqltuner which advises some specific settings taking the host's configuration into account. I might want to do this again for a mysql running in docker container on DO 1G setup.

**Comment by petercstevenson** [comment]
Unless there is any other testing that someone wants me to do as far as I am concerned this is fixed. I have had no problems since upgrading to 1 GB of RAM.
