### ISSUE TITLE
Web install needs additional documentation

### ISSUE THREAD

**Issue by petercstevenson** [jekkos/opensourcepos#861]
The installation instructions for the web install are good and are pretty straightforward. However, it has been a challenge to learn how to do things like run update scripts, etc. This is something that I would like to help with. I can start with instructions on how to make sure that the database scripts are updated. To start with, can someone confirm that the script that should be run to make sure that everything is up-to-date is 2.4_to_3.0.sql?

**Comment by daN4cat** [comment]
Thanks, good initiative!

Yes, if you upgrade from 2.4 that's the script.

If you have a fresh install you need to run database script (I'm going by memory, far from laptop).

Please check with @odiea for installation and user manual. He sent me something the other day but had no time to review it completely yet.

**Comment by petercstevenson** [comment]
OK, so if I am running 3.0 already then I just need to run database.sql to be up-to-date?

**Comment by daN4cat** [comment]
No no, to update it's always 2.4 to 3.0. But that's because we are developing 3.0.

**Comment by jekkos** [comment]
If you're rebasing from master directly then I guess you will need to incrementally apply parts of the 2.4 to 3.0 script once statements are added. I'm aware that better mechanisms exist to handle these upgrade and might want to look into that in the future.

**Comment by jekkos** [comment]
For example builtin CI migration support or liquibase could be options here

**Comment by petercstevenson** [comment]
I am now thoroughly confused. I installed ospos 3.0 through the web install and have been redeploying periodically to get the new commits. When there was the issue with not being able to log in, I ran the following commands taken from issue  #832:

ALTER TABLE ospos_employees
ADD COLUMN hash_version int(1) NOT NULL DEFAULT '2';

UPDATE ospos_employees SET hash_version = 1;

I have not run any other scripts. It is not clear to me whether the database is up-to-date or how to update it if it isn't.

**Comment by daN4cat** [comment]
If you take under development code you are forced to keep up with the evolution of the matter.
I'm not sure it makes sense to have a document describing small steps.

Maybe after 3.0.0 we should consider more frequent and small drop increasing the last digit. Or a different means of continuous deployment and automatic upgrade.

**Comment by jekkos** [comment]
Yes it's been too long since we did a release..Hope to get this one out soon.

**Comment by jekkos** [comment]
* I'll add db upgrade instructions to the wiki for docker cloud installations 
* Also autoredeploy is a nice feature as it will pull for new changes on travis and deploy those automatically so that you're always on the latest version!
* Automatic db upgrade would be nice to have 
 - this could be done by adding sql incrementally to the sqlscript docker image (docker only solution)
 - or by using CI_Migration functionality, which basically converts sql into php code (will suit all types of installations)

**Comment by compasssites** [comment]
I feel the web install instructions for installing online (on our own domains/subdomains) need more elaboration. There are issues and roadblocks in the steps of connecting/pointing to the domain/subdomain. I am stuck actually in the last step of config.

**Comment by jekkos** [comment]
I have added some documentation on autoredeploy + manual db upgrade in the wiki. WIll close this issue unless there is something I forgot to add.

**Comment by petercstevenson** [comment]
Thanks, @jekkos. I was not able to redeploy just the web container. The way that I have been doing this is to redeploy the entire stack. Is it possible to set this up in such a way that the url does not change after every redeploy?

**Comment by jekkos** [comment]
Well changing url could be fixed by using a dns entry.. I need to look into that myself but this should be added to the documentation (as it's a common thing to do)

**Comment by petercstevenson** [comment]
Here are my more detailed instructions that work with the Digital Ocean console:

1. Log into Digital Ocean Console through these instructions: https://www.digitalocean.com/community/tutorials/how-to-use-the-digitalocean-console-to-access-your-droplet I have tried this with both Abrowser (Firefox-based) and Chromium (Chrome-based) and the scroll bar doesn't seem to work with Abrowser, so for me Chromium is the preferred browser for this
2. Install docker-cloud CLI if you have not yet done so: Enter `docker run dockercloud/cli -h`
7. Next you need to find out the exact names of your MySQL container. You can find it under "Containers" in the Docker web UI or you can find it out by running the command `docker run -it -v ~/.docker:/root/.docker:ro --rm dockercloud/cli container ps` You are looking for the name in the left-most column called "NAME"
8. To log into the container, enter `docker run -it -v ~/.docker:/root/.docker:ro --rm dockercloud/cli exec [container name] /bin/bash
9. Enter `mysql -u root -ppointofsale`
10. Enter `use ospos`

**Comment by jekkos** [comment]
Ok thanks alot for this I'll add it to the wiki.

**Comment by daN4cat** [comment]
I can see the instruction was added to the wiki, I close this issue.

**Comment by petercstevenson** [comment]
Thank you. I will try to work more closely with the wiki directly from now on.

**Comment by daN4cat** [comment]
That would be great because we cannot keep up in just two.
