### ISSUE TITLE
Master may be corrupted?

### ISSUE THREAD

**Issue by odiea** [jekkos/opensourcepos#862]
### New Feature or Enhacement

For new Features or Enhacements please remove all the template text and clearly write your proposal.
It's important to state whether you expect the community to implement it or you will contribute the work.
Please bear in mind that we will implement new features only on the current code, there is no support for old versions.

### Issue, Question or Bug

Before submitting an issue please make sure you remove the first section of the template and you tick (add a x between the square brakets) and agree with all the following check boxes:

- [x] Checked the current issues database and no similar issue was already discussed
- [x] Read the README, WHATS_NEW and UPGRADE
- [x] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php5-gd, php-intl and sockets installed)
- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [x] PHP version is at least 5.5 and not 7.x
- [x] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [x] Know the name and version of OS, Web server and MySQL and will add to my issue report

IMPORTANT: If you remove the template when submitting an issue your issue will be closed.

### Installation information
Dowloaded latest Master

### Expected behaviour
Login to Home

### Actual behaviour
No login after Login page.

### Steps to reproduce the issue

**Comment by odiea** [comment]
Here is what I get after logging in to Latest Master.
![2016-09-13 13_23_53-](https://cloud.githubusercontent.com/assets/10962177/18488305/0931d2f8-79b6-11e6-8fa1-25b64ca6cba8.png)

**Comment by daN4cat** [comment]
I'm far from my laptop, it might be that a change I made in login is causing an issue. I can check tomorrow if I find the time but I'm travelling at the moment.

**Comment by odiea** [comment]
After I comment out this line it logs in just fine.
//$this->tracking_lib->track_event('Stats', 'Language', current_language());

**Comment by odiea** [comment]
After changing to $this->tracking_lib->track_event('Stats', 'Language', $this->config->item('language')); it works fine.

**Comment by odiea** [comment]
Also reported in #859

**Comment by daN4cat** [comment]
Correct, that's the fix. I merge the change from composer and forgot that composer had a change with language. I'll fix it later. Thanks for the help.

**Comment by daN4cat** [comment]
Fixed and in master

**Comment by odiea** [comment]
@daN4cat @jekkos Thanks for all your help keeping this program alive.
