### ISSUE TITLE
Switching to Turkish language grays out the page

### ISSUE THREAD

**Issue by donangil** [jekkos/opensourcepos#863]
![lang_tr](https://cloud.githubusercontent.com/assets/15213138/18508561/46b35292-7a7d-11e6-87d0-41966218d273.jpg)
### Issue, Question or Bug

Before submitting an issue please make sure you remove the first section of the template and you tick (add a x between the square brakets) and agree with all the following check boxes:

- [x] Checked the current issues database and no similar issue was already discussed
- [] Read the README, WHATS_NEW and UPGRADE
- [] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php5-gd, php-intl and sockets installed)
- [x] Reporting an issue of an unmodified OSPOS installation
- [] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [x] PHP version is at least 5.5 and not 7.x
- [x] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [x] Know the name and version of OS, Web server and MySQL and will add to my issue report

IMPORTANT: If you remove the template when submitting an issue your issue will be closed.

### Installation information
Clean Installation
OSPOS Version 3.0.0 - 4f5ad57
PHP v5.6.18
Mysql v5.7.11

### Expected behaviour
Store Config >> Localisation >> Turkish Language should switch the OSPOS language to Turkish.

### Actual behaviour
Store Config >> Localisation >> Turkish Language makes the page gray out and freeze.

### Steps to reproduce the issue
Store Config >> Localisation tab >> Change to Turkish >> Submit

**Comment by daN4cat** [comment]
Are you using the latest master code?

**Comment by donangil** [comment]
yes

**Comment by odiea** [comment]
Yes he is correct. Another language giving issues.

**Comment by sonnysk76** [comment]
I have the overlay issueafter login with the latest master using Spanish.
But it happens only on Firefox and IE.
Chrome works ok.

**Comment by daN4cat** [comment]
I will check next few days the root cause.

**Comment by aelhofy** [comment]
same for arabic

**Comment by daN4cat** [comment]
@donangil can you check #848 and work on the Turkish translation? I think that if you complete them you'll get things to work again.

**Comment by donangil** [comment]
Did work on Turkish. How it will be merged to master?

**Comment by daN4cat** [comment]
@donangil have you checked #848? That's the automatic way you can do it. Speak with @jekkos for more details.

**Comment by donangil** [comment]
yes did modifications  on weblate website @jekkos . Ty

**Comment by daN4cat** [comment]
@donangil good, but when I check here: http://weblate.jpeelaer.net/languages/tr/ I still can see work to do in terms of reviews and checks.
Not sure that's required before I push is done automatically, but let's get 100% green.

**Comment by daN4cat** [comment]
@donangil you need to translate the following: You are using Open Source Point Of Sale Version in Turkish leaving "Open Source Point Of Sale" in it as specified by the License.

Here the translation link: http://weblate.jpeelaer.net/translate/ospos/common/tr/?checksum=1095d166d4fb3510a33f7e2234b41db1

**Comment by donangil** [comment]
what happened to my translations. Looks like i did nothing. Lost?

**Comment by daN4cat** [comment]
Please post in #848

**Comment by jacksz** [comment]
@daN4cat this is still a problem in arabic and weblate for arabic seem to be 100%?
