### ISSUE TITLE
Inventory report

### ISSUE THREAD

**Issue by amd64bit** [jekkos/opensourcepos#865]
### Issue, Question or Bug

When change admin password and save, Inventory report is not appear
Because field "permission_id" with value "reports_inventory" in Table: "ospos_grants" is lost

I apologize for not being word-perfect in English

**Comment by daN4cat** [comment]
Are you reporting an issue with the latest OPSOS from master?

**Comment by amd64bit** [comment]
Yes, i use latest OPSOS from master at 15/09/2016

**Comment by daN4cat** [comment]
Just tested and I don't see this issue.

Are you testing a new installation or something you updated?

**Comment by odiea** [comment]
Works fine here too

**Comment by amd64bit** [comment]
OK, i will try latest update again, Thank you

**Comment by amd64bit** [comment]
i found it, please change default language (English) to Russian, Thai, French, Chinese or etc. 
Before change admin password,  Because permission tab is lost Inventory checkbox on other language, When submit field "permission_id" with value "reports_inventory" in Table: "ospos_grants" is lost and inventory report not appear.

in >> opensourcepos\application\views\reports\listing.php check reports_inventory value if return null inventory report not appear

if ($this->Employee->has_grant('reports_inventory', $this->session->userdata('person_id')))
		{
		?>
			<div class="panel panel-primary">
				<div class="panel-heading">
					<h3 class="panel-title"><?php echo $this->lang->line('reports_inventory_reports'); ?></h3>
				</div>
				<div class="list-group">
				<?php 
					show_report('', 'reports_inventory_low');
					show_report('', 'reports_inventory_summary');
				?>
				</div>
			</div>
		<?php 
		}

I apologize for my English

**Comment by daN4cat** [comment]
@amd64bit thanks for spotting that out.
I tried French and I can see the problem because if you see: https://github.com/jekkos/opensourcepos/blob/master/application/language/fr/reports_lang.php you can see that `$lang["reports_inventory"] = "";` is empty.

Therefore to get it to work people need to work on their translations, see #848 and please help out so you sort out this problem.

**Comment by amd64bit** [comment]
I was delighted of any help. i can translations with Thai language and i will to create an account in weblate.jpeelaer.net
