### ISSUE TITLE
error 500 (http)............. how can i solve it ?

### ISSUE THREAD

**Issue by gkapaino** [jekkos/opensourcepos#869]
### New Feature or Enhacement

For new Features or Enhacements please remove all the template text and clearly write your proposal.
It's important to state whether you expect the community to implement it or you will contribute the work.
Please bear in mind that we will implement new features only on the current code, there is no support for old versions.

### Issue, Question or Bug

Before submitting an issue please make sure you remove the first section of the template and you tick (add a x between the square brakets) and agree with all the following check boxes:

- [] Checked the current issues database and no similar issue was already discussed
- [] Read the README, WHATS_NEW and UPGRADE
- [] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php5-gd, php-intl and sockets installed)
- [] Reporting an issue of an unmodified OSPOS installation
- [] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [] PHP version is at least 5.5 and not 7.x
- [] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [] Know the name and version of OS, Web server and MySQL and will add to my issue report

IMPORTANT: If you remove the template when submitting an issue your issue will be closed.

### Steps to reproduce the issue

**Comment by daN4cat** [comment]
Read the existing closed issues.

**Comment by gkapaino** [comment]
i didnt understand what ur meaning

**Comment by daN4cat** [comment]
No MySQL 5.7

**Comment by gkapaino** [comment]
HOW SHOULD I GET MYSQL 5.7

**Comment by daN4cat** [comment]
No MySQL 5.7 support at the moment.

**Comment by gkapaino** [comment]
so what can i solve it

**Comment by gkapaino** [comment]
please friend please help me

**Comment by gkapaino** [comment]
[image: Inline image 1]

**Comment by daN4cat** [comment]
Use MySQL 5.5 or 5.6

**Comment by gkapaino** [comment]
ok let me try.. i will inform u

**Comment by gkapaino** [comment]
sorry bro.. can u send me link of wamp that support mysql 5.5 or 5.6? cuz
me im using latest wamp... or other software that can run a system

**Comment by arteiro** [comment]
https://www.apachefriends.org/pt_br/download.html

**Comment by alvin101** [comment]
I like the Uniform Server better  http://www.uniformserver.com/

**Comment by gkapaino** [comment]
thanx... let me try... i will let u know

**Comment by gkapaino** [comment]
still the same problem after installing xammp

[image: Inline image 1]

what can i do?

**Comment by daN4cat** [comment]
Which problem? There is no image in your replies.

**Comment by odiea** [comment]
Start Apache and Mysql.
From Apache select Config.
Edit the Php.ini file to uncomment the following extensions.Extensions are about halfway down.
[bcmath]
; Number of decimal digits for all bcmath functions.
; http://php.net/bcmath.scale
bcmath.scale=0
extension=php_gd2.dll
extension=php_intl.dll
extension=php_sockets.dll
Now Apache should be ready to go.

**Comment by gkapaino** [comment]
thanx a lot ..... it work...

**Comment by gkapaino** [comment]
please send a me a link to pay some amount

**Comment by arteiro** [comment]
see the readme, let's take a few beers pros parents coksa, hehehehe

**Comment by gkapaino** [comment]
DONT WORRY

**Comment by gkapaino** [comment]
MY ACCOUNT IS VALID ONLY IN USD NOT IN EURO.... WHAT CAN I DO???

**Comment by gkapaino** [comment]
THEN DO YOU HAVE HOSPITAL MANAGEMENT SYSTEM?

**Comment by daN4cat** [comment]
You can select what currency you want, just go to Store Config and select Locale tab and set Euro symbol instead of us dollar. Also tick to show it on the right.

Hospital management, what do you mean with that? Hotel or really hospitals?
OSPOS is for retailers in general, but it's agnostic of its use so you have to check if fine for you.

**Comment by gkapaino** [comment]
Hospital system

**Comment by gkapaino** [comment]
OK I will try to send money

**Comment by daN4cat** [comment]
Ok, you meant currency for the payment. I thought you were asking about setting the currency in OSPOS. 😁

**Comment by gkapaino** [comment]
yaah for payment

**Comment by gkapaino** [comment]
sorry friend.... i cant change footer name open source point of sale....
once i change i cant click its loading........
can u help me??

[image: Inline image 1]

**Comment by gkapaino** [comment]
then if i want to remove Currency Symbol to display none what should i do?

**Comment by daN4cat** [comment]
Read the license

**Comment by gkapaino** [comment]
thanx

**Comment by gkapaino** [comment]
i can't buy a this system for full authorize?

**Comment by gkapaino** [comment]
HOW SHOULD I REMOVE CURRENCY ($) AND TO PUT NO CURRENCY SYMBOLS?

**Comment by daN4cat** [comment]
Go to Store config and in locale tab remove currency symbol. Does it work or no?

**Comment by daN4cat** [comment]
MySQL 5.7 see #630

**Comment by alvin101** [comment]
@gkapaino  If you want to donate some cash to this great project.  Click here https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=MUN6AEG7NY6H8

**Comment by gkapaino** [comment]
it doesnt work

**Comment by gkapaino** [comment]
when i save it will return into $

**Comment by gkapaino** [comment]
ok let try

**Comment by gkapaino** [comment]
should i put online this system? or only local

**Comment by gkapaino** [comment]
i failed to donate some by due to my back account authorize only for
dollar.... and not euro.... so what should i do? or there are other way to
donate?

**Comment by gkapaino** [comment]
how can i add this features?
- EXPENSES
-TRIAL BALANCE
-OPENING STOCK
-CLOSING STOCK
-

**Comment by daN4cat** [comment]
@gkapaino get in touch with @jekkos for all your questions.

**Comment by gkapaino** [comment]
please answer my questions

**Comment by gkapaino** [comment]
the how should i record loan transaction

**Comment by gkapaino** [comment]
where i can  see register log on ospos 3.0?

**Comment by gkapaino** [comment]
HELLO FRIEND U DIDN'T RECEIVE MY TEXT OR? U CANT GIVE ME SUPPORT

**Comment by daN4cat** [comment]
@gkapaino this is an open source project, we have our own jobs and this is a past time thingy.
If you are after something professional with chat/phone support then it's better to look for something else. With open source solutions you need to learn how to find your own way. That's the philosophy here.
