### ISSUE TITLE
Can't access sales module

### ISSUE THREAD

**Issue by curthauta** [jekkos/opensourcepos#87]
Someone emailed me this bug.  I haven't tested this with the latest Github code.  I could reproduce this error with the Sourceforge code though.

If you create an employee and give them access to the Sales module, when you log in as them, you can see the Sales module icon, but when you click on it, you get this error message: "You do not have permission to access the module named Sales (items)".  Instead of going to "/index.php/sales", it goes to "/index.php/no_access/sales/items".

If you give them access to the Sales module and the Items->stock module, you no longer get the error message.  Of course, you might not want to give sales people access to the Items module.  If you give them access to the Sales module and the Items module, but not the Items->stock module, you still get the error message.

**Comment by jekkos** [comment]
Yes there has been some discussion about this issue. I think it is indeed present in the sourceforge versions, but was solved later on (but not published back again). 

Actually it would be more clear to the user if he wasn't able to enable the sales or receivings without selecting at least one stock location. It actually doesn't make a lot of sense to grant permission to the module without being able to sell or receive anything at all.

**Comment by jekkos** [comment]
There used to be validation in place to prevent users from doing this, but was probably broken after upgrading jquery validate. Should be all good again in fc5f0978203c87d9437b2da89c2c45b03bb1383d
