### ISSUE TITLE
search by custom field in sales page

### ISSUE THREAD

**Issue by hovalle** [jekkos/opensourcepos#873]
### Issue, Question or Bug

Before submitting an issue please make sure you remove the first section of the template and you tick (add a x between the square brakets) and agree with all the following check boxes:

- [x] Checked the current issues database and no similar issue was already discussed
- [x] Read the README, WHATS_NEW and UPGRADE
- [x] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php5-gd, php-intl and sockets installed)
- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [x] PHP version is at least 5.5 and not 7.x
- [x] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [x] Know the name and version of OS, Web server and MySQL and will add to my issue report

IMPORTANT: If you remove the template when submitting an issue your issue will be closed.

Hi guys, i have a question. how can i search for items in sales screen, not just for "name, item_number, company_name or category" i would like to include for example custom2 or custom1 to the query. i modified the query with no results in models/items.php with no results, like this:

> if ($filters['search_custom'] == FALSE)
			{
				$this->db->where("(name LIKE '%" . $this->db->escape_like_str($search) . "%' OR " .
								"custom1 LIKE '%" . $this->db->escape_like_str($search) . "%' OR " .
								"item_number LIKE '" . $this->db->escape_like_str($search) . "%' OR " .
								$this->db->dbprefix('items').".item_id LIKE '" . $this->db->escape_like_str($search) . "%' OR " .
								"company_name LIKE '%" . $this->db->escape_like_str($search) . "%' OR " .
								"category LIKE '%" . $this->db->escape_like_str($search) . "%')");
			}

am i editing the right file? thanks.

### Steps to reproduce the issue

**Comment by daN4cat** [comment]
Version of OSPOS?

**Comment by hovalle** [comment]
hi Guys i'm using v.3.0.0. But i have to say that i just did it i modified the "item.php model" inside the "get_search_suggestions function" and it's working great, what i did was duplicate this query 

> //busca por el custom2 
		$this->db->select('item_id, custom2');
		$this->db->from('items');
		$this->db->where('deleted', $filters['is_deleted']);
		$this->db->like('custom2', $search);
		$this->db->order_by('custom2', 'asc');
		$by_name = $this->db->get();
		foreach($by_name->result() as $row)
		{
			$suggestions[] = array('value' => $row->item_id, 'label' => $row->custom2);
		}

and added my custom2

 now i have another question. how can i concatenate two terms in this search for example as i'm typing "hard drive" i would like to see in the autocomplete sometthing like this "hard drive : samsung" where hard drive is the name and samsung is the custom2. is that posible?

**Comment by odiea** [comment]
Towards the bottom of the page #744. See if this helps.

**Comment by hovalle** [comment]
it works guys, thank you so much!

**Comment by daN4cat** [comment]
Good

**Comment by hovalle** [comment]
hi @daN4cat just one little more question how can i get the id of the element in the autocomplete list in the item search just like the sale search?

![sales](https://cloud.githubusercontent.com/assets/5261181/18801804/47e650ca-81a2-11e6-83cc-5b6288bcfa9c.png)

![items](https://cloud.githubusercontent.com/assets/5261181/18801843/78e7d89c-81a2-11e6-90b1-a2ab92d8dc88.png)
