### ISSUE TITLE
Items Data not Show

### ISSUE THREAD

**Issue by faruqi** [jekkos/opensourcepos#874]
### New Feature or Enhacement

For new Features or Enhacements please remove all the template text and clearly write your proposal.
It's important to state whether you expect the community to implement it or you will contribute the work.
Please bear in mind that we will implement new features only on the current code, there is no support for old versions.

### Issue, Question or Bug

Before submitting an issue please make sure you remove the first section of the template and you tick (add a x between the square brakets) and agree with all the following check boxes:

- [x] Checked the current issues database and no similar issue was already discussed
- [x] Read the README, WHATS_NEW and UPGRADE
- [x] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php5-gd, php-intl and sockets installed)
- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [ ] PHP version is at least 5.5 and not 7.x
- [x] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [x] Know the name and version of OS, Web server and MySQL and will add to my issue report

IMPORTANT: If you remove the template when submitting an issue your issue will be closed.

### Installation information
4f5ad57
Wampserver 3.0.6 64 bit x64 – Apache 2.4.23 – PHP 5.6.25/7.0.10 – MySQL 5.7.14 
windows 10 X64

### Expected behaviour

items data does not appear and when query report always HTTP ERROR 500

### Actual behaviour
![error](https://cloud.githubusercontent.com/assets/1875466/18656200/6ba34422-7f19-11e6-9a3c-d7dcf2ca66c3.PNG)

the data has been entered in the database

**Comment by daN4cat** [comment]
Are you upgrading or is this a new installation?

**Comment by JupiterAZ** [comment]
First and foremost thanks for your excellent work on OSPOS. I am new to the project and I just completed a install of the master from a download a couple days ago to test the POS for a retail store I am opening up. I downloaded the files and installed them manually. I am experiencing the same issue reported as faruqi. Looking at the database I can see that the data is there in the _items table but the query fails to find anything.

**Comment by jekkos** [comment]
Did you read through the template? Double check php / mysql versions? Certain you don't have mysql 5.7 installed (which is unsupported)?

If you want something that works right away then try the docker cloud install.. by using this service you contribute something back to the project as well :+1:

**Comment by jekkos** [comment]
Readme clearly states that Mysql 5.7 is not supported so I will close

**Comment by faruqi** [comment]
Thanks

**Comment by daN4cat** [comment]
See #630
