### ISSUE TITLE
Questions about the current database structure.

### ISSUE THREAD

**Issue by odiea** [jekkos/opensourcepos#875]
There seems to be a contradiction here. In the update should the 1 have ' ' around it.

This is from database.sql
CREATE TABLE `ospos_employees` (
  `username` varchar(255) NOT NULL,
  `password` varchar(255) NOT NULL,
  `person_id` int(10) NOT NULL,
  `deleted` int(1) NOT NULL DEFAULT '0',
  `hash_version` int(1) NOT NULL DEFAULT '2',
  UNIQUE KEY `username` (`username`),
  KEY `person_id` (`person_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Dumping data for table `ospos_employees`
--
This is from the 2.4 to 3.0 sql update

INSERT INTO `ospos_employees` (`username`, `password`, `person_id`, `deleted`, `hash_version`) VALUES
('admin', '$2y$10$vJBSMlD02EC7ENSrKfVQXuvq9tNRHMtcOA8MSK2NYS748HHWm.gcG', 1, 0, 2);

ALTER TABLE `ospos_employees`
 ADD COLUMN `hash_version` int(1) NOT NULL DEFAULT '2';

UPDATE `ospos_employees` SET `hash_version` = 1;

**Comment by daN4cat** [comment]
You mean in the last line of your comment?

It's an integer and should be fine.

**Comment by odiea** [comment]
No. In the database.sql hash_version is 2 in 2.4 3.0 the hash version is 2 but the update changes it to 1. Which one should it be?

**Comment by jekkos** [comment]
That's how it's supposed to be, good catch, people will have their passwords hashed with md5 in the database before upgrade. The hash in the script is using bcrypt which is version 2. Upgrading the hash can only happen once the plaintext password is in memory which is at login time. So at that moment version 1 is bumped to 2.

**Comment by odiea** [comment]
Ok just checking.
