### ISSUE TITLE
Recover sale Data

### ISSUE THREAD

**Issue by ManjuprasadB** [jekkos/opensourcepos#877]
I have forgotten my login and password 
But i want to recover my sales data how do i do that.
i am using Network Install on raspberry pi

**Comment by daN4cat** [comment]
You can always use phpMyAdmin and access your MySQL database and copy and paste the default password hash on top of yours so you have a means to enter again your account.

Unless you mean you forgot your RasperryPi password?

**Comment by ManjuprasadB** [comment]
Thankz it worked i forgot my ospos login password
