### ISSUE TITLE
Xprinter Issue

### ISSUE THREAD

**Issue by jsoftwares** [jekkos/opensourcepos#878]
Hi all I successfully installed this good software, but I have a challenge with printing. The printer prints not just the portion of the receipt but it prints alot more white spaces that could print 7 more receipt just after printing the receipt.

I'd be glad if anyone can help me with what to do.
### New Feature or Enhacement

For new Features or Enhacements please remove all the template text and clearly write your proposal.
It's important to state whether you expect the community to implement it or you will contribute the work.
Please bear in mind that we will implement new features only on the current code, there is no support for old versions.

### Issue, Question or Bug

Before submitting an issue please make sure you remove the first section of the template and you tick (add a x between the square brakets) and agree with all the following check boxes:

- [] Checked the current issues database and no similar issue was already discussed
- [] Read the README, WHATS_NEW and UPGRADE
- [] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php5-gd, php-intl and sockets installed)
- [] Reporting an issue of an unmodified OSPOS installation
- [] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [] PHP version is at least 5.5 and not 7.x
- [] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [] Know the name and version of OS, Web server and MySQL and will add to my issue report

IMPORTANT: If you remove the template when submitting an issue your issue will be closed.

### Steps to reproduce the issue

**Comment by daN4cat** [comment]
It's a printer configuration issue.

Which paper size have you configured?
Have you set any margins?
Which web browser do you use?

You see, if you don't fill in the template we cannot help you.

**Comment by jsoftwares** [comment]
Thank you. The paper size is 58mm according to the printer. I did not cnfigure anything related to the paper size on the software. 
I did not set any margins. (show print dialog, print browser header, print footer, ticket printer, invoice printer, takings printer, and all the margin top, left, right, button are all greyed out so I cannot even change anything there.)
I use google chrome browser.

Thanks

**Comment by daN4cat** [comment]
You should check the printer size you set in the driver configuration.
Also Google Chrome is more tricky to setup printer margins and etc.
So play with that stuff, not more we can help here as that is not an OSPOS issue.

Please check Store Config as there is a receipt format for smaller printers. The default prints longer strings and etc.
