### ISSUE TITLE
Return Policy

### ISSUE THREAD

**Issue by markhoof** [jekkos/opensourcepos#879]
### Question

Is it possible to increase the length of characters allowed in the Return Policy? When I fill this section out, it cuts the number of characters down to what appears to be a predefined length.  I have been unable to increase the amount of characters thus far. Any help would be greatly appreciated. 

Before submitting an issue please make sure you remove the first section of the template and you tick (add a x between the square brakets) and agree with all the following check boxes:

- [x] Checked the current issues database and no similar issue was already discussed
- [x] Read the README, WHATS_NEW and UPGRADE
- [x] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php5-gd, php-intl and sockets installed)
- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [x] PHP version is at least 5.5 and not 7.x
- [x] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [x] Know the name and version of OS, Web server and MySQL and will add to my issue report

IMPORTANT: If you remove the template when submitting an issue your issue will be closed.

### Steps to reproduce the issue

**Comment by daN4cat** [comment]
How long? Any idea?

I had a similar issue in the past, I'll review this to make sure it's long enough.

**Comment by daN4cat** [comment]
Currently return policy can be max ~255 char long.
It's constrained by:

```
CREATE TABLE `ospos_app_config` (
  `key` varchar(255) NOT NULL,
  `value` varchar(255) NOT NULL,
  PRIMARY KEY (`key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```

So to have a longer return policy string we need to change the size of value.
Maybe we can shorten key to 50 (at the moment the longest is 27) as I doubt we ever need 255 and extent value to 500.

Is that ok? Any objections?

**Comment by daN4cat** [comment]
The fix is in composer branch, in the db upgrade script 2.4 to 3.0, but you just need to run the following against your database to have a longer policy:

```
ALTER TABLE `ospos_app_config`
 MODIFY COLUMN `key` varchar(50) NOT NULL,
 MODIFY COLUMN `value` varchar(500) NOT NULL;
```

**Comment by markhoof** [comment]
Excellent. The fix works. Much appreciated!
