### ISSUE TITLE
I could not set the store .. the cursor is loading and you can not make changes

### ISSUE THREAD

**Issue by dixon22ma** [jekkos/opensourcepos#880]
I could not set the store .. the cursor is loading and you can not make changes

![error](https://cloud.githubusercontent.com/assets/2453563/18812413/5f1891cc-82a1-11e6-8976-8eaa66270f4d.jpg)

**Comment by daN4cat** [comment]
Read the FAQ? Make sure you have all the required PHP libraries.

**Comment by dixon22ma** [comment]
hello, thanks for your response corrected my mistakes display.
I will continue reviewing this selling point is excellent, anything is the notify.
