### ISSUE TITLE
show id instead of the name in search input on item view

### ISSUE THREAD

**Issue by hovalle** [jekkos/opensourcepos#881]
### New Feature or Enhacement

For new Features or Enhacements please remove all the template text and clearly write your proposal.
It's important to state whether you expect the community to implement it or you will contribute the work.
Please bear in mind that we will implement new features only on the current code, there is no support for old versions.
### Issue, Question or Bug

Before submitting an issue please make sure you remove the first section of the template and you tick (add a x between the square brakets) and agree with all the following check boxes:
- [x] Checked the current issues database and no similar issue was already discussed
- [x] Read the README, WHATS_NEW and UPGRADE
- [x] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php5-gd, php-intl and sockets installed)
- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [x] PHP version is at least 5.5 and not 7.x
- [x] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [x] Know the name and version of OS, Web server and MySQL and will add to my issue report

hi @daN4cat just one little more question how can i get the id of the element in the autocomplete list in the item search just like the sale search?

![sale](https://cloud.githubusercontent.com/assets/5261181/18818548/14acc82c-8339-11e6-8a37-e15e8987f0b5.png)

![item](https://cloud.githubusercontent.com/assets/5261181/18818549/1abbb9a8-8339-11e6-96bc-8b8d5741fdf8.png)

**Comment by jekkos** [comment]
You mean server side or client side? This is a standard jquery-ui widget for which you can find documentation online.. A key - value is returned from the server and only the key is sent back once selected

**Comment by hovalle** [comment]
ok, i need to show the id just like the search in sales page, when you select an item it shows the id, I need the same behavior in the search of the items page. the problem is that i customized the info in the list holding the name in every product like this
`item-name [custom1 : custom2]`

and when i hit enter i have no results because i'm sending the entire string to the query and obviously that string doesn't exist, this...
`item-name [custom1 : custom2]`

but if i send the item-id it works, and that's why i need the same behavior that the sales search has. I hope you understand what i mean, thanks.

**Comment by daN4cat** [comment]
You need to remove what you don't need in the controller search function.

**Comment by hovalle** [comment]
i don't understand, that's the way to show the id number instead of the name of item when i select any item in the list?

**Comment by daN4cat** [comment]
You show from one side and when you select the item you search for it for the full info from the db. In that function to pick up the item you need to remove the extra bits. Now without code in front of me I cannot tell you the exact name if the function. Read the controller code.

**Comment by hovalle** [comment]
i still don't get it sorry, i think i'm not explaining good. Ok when you search for a product in the sales page a list is shown right, in that list appears the name of the product and when you start moving through that list you can see the item id in the search input instead of the name. i would like to know f that same behavior can be applyed in the list in items page

**Comment by jekkos** [comment]
standard table search uses bootstrap tables functionality and thus not the jquery autcomplete. This is different and if you want to get the id then you'll need to hook into the search result parser attached to that table

**Comment by hovalle** [comment]
ok, any example on how to achieve that?

**Comment by odiea** [comment]
Put the checkmark back in the id column to see the Item_id.
