### ISSUE TITLE
Trying the master, and fail

### ISSUE THREAD

**Issue by rnld26** [jekkos/opensourcepos#882]
I'm testing the master one, and i got this... why?
![screen shot 2016-09-26 at 11 00 47 pm](https://cloud.githubusercontent.com/assets/22451842/18841946/a2178472-843d-11e6-9993-268604e12fd9.png)
![screen shot 2016-09-26 at 11 00 58 pm](https://cloud.githubusercontent.com/assets/22451842/18841957/a842d0e0-843d-11e6-8941-d6b43deea089.png)
![screen shot 2016-09-26 at 11 01 14 pm](https://cloud.githubusercontent.com/assets/22451842/18841963/a9df5c20-843d-11e6-93d3-1cad774eaca8.png)
![screen shot 2016-09-26 at 11 01 43 pm](https://cloud.githubusercontent.com/assets/22451842/18841967/ac29a058-843d-11e6-959e-535080954994.png)
![screen shot 2016-09-26 at 11 01 54 pm](https://cloud.githubusercontent.com/assets/22451842/18841971/b0ec4294-843d-11e6-950b-dcc73c0551d1.png)

1. The dialog box is nothing to show except the button (customer, items)
2. The block screen show up, and cursor show waiting icon when receiving, sale, reports, store config menu opened, nothing hapened, just keep loading..

would you give me solution?

**Comment by daN4cat** [comment]
Hi, unfortunately we keep repeating the same.
There is a template to report issues that states clearly a set of things people should check.
There is a purpose for that because if you read the FAQ and past closed issue you could see that most likely you are missing the required PHP extensions, not to say that MySQL5.7 is not supported and neither PHP7 (at the moment, but planned for the future).

**Comment by rnld26** [comment]
i'm so sorry, can you change my issue become a question.. i'm actually using the 2.4 version, but now trying version 3.0..
this is my php info

![screen shot 2016-09-27 at 7 12 41 am](https://cloud.githubusercontent.com/assets/22451842/18856144/94bff76a-8482-11e6-8023-ed454b5fc0d7.png)
![screen shot 2016-09-27 at 7 13 10 am](https://cloud.githubusercontent.com/assets/22451842/18856145/9c18e670-8482-11e6-8380-5840e65824a4.png)
![screen shot 2016-09-27 at 7 13 26 am](https://cloud.githubusercontent.com/assets/22451842/18856153/a5e03046-8482-11e6-8476-e1cfa5e71064.png)
![screen shot 2016-09-27 at 7 13 35 am](https://cloud.githubusercontent.com/assets/22451842/18856156/aabcbd32-8482-11e6-82fb-a5144a5cbdd3.png)

what do i missing?

work fine in supplier
![screen shot 2016-09-27 at 7 19 42 am](https://cloud.githubusercontent.com/assets/22451842/18856178/dde90d14-8482-11e6-8858-79e3b4b434fd.png)


but not in items
![screen shot 2016-09-27 at 7 19 57 am](https://cloud.githubusercontent.com/assets/22451842/18856187/ee19408c-8482-11e6-9506-d8a4edd765a7.png)

thanks.. sorry once again..

**Comment by odiea** [comment]
Start Apache and Mysql.
From Apache select Config.
Edit the Php.ini file to uncomment the following extensions.Extensions are about halfway down.
[bcmath]
; Number of decimal digits for all bcmath functions.
; http://php.net/bcmath.scale
bcmath.scale=0
extension=php_gd2.dll
extension=php_intl.dll
extension=php_sockets.dll
Now Apache should be ready to go.

**Comment by daN4cat** [comment]
And make sure you run the do upgrade script

**Comment by rnld26** [comment]
![screen shot 2016-09-27 at 1 12 06 pm](https://cloud.githubusercontent.com/assets/22451842/18862202/b2074d14-84b4-11e6-88ab-2a1d03f20737.png)
![screen shot 2016-09-27 at 1 12 29 pm](https://cloud.githubusercontent.com/assets/22451842/18862205/b704ae92-84b4-11e6-999c-f3a967b3a094.png)

i still cannot open the form.. receiving, sales, store config.. :(
yes i do run the exact script
path /xampp/xamppfiles/etc/php.ini

**Comment by daN4cat** [comment]
Ran the database upgrade script 2.4 to 3.0?

**Comment by rnld26** [comment]
PActually i create new database, import from master data ospos 3.0.0/database/database.sql..
Its like the change that i make at php.ini is not work..
Is there another way to make sure  the extension is running?

**Comment by rnld26** [comment]
Solved thanks

**Comment by HamidCh** [comment]
How?
