### ISSUE TITLE
Sale Module and Problem after restarting ..

### ISSUE THREAD

**Issue by rnld26** [jekkos/opensourcepos#887]
Question 
Sorry for my bad english

1. I'm using opensourcepos since februari 2016.. And now trying version 3.0.0.. I'm working on to add some feature on Sale Module, the idea is to choose the employee who served the customer before we complete the sale, why i add this feature because to give commission to employee base on how many served that the employee do.. is that a problem? or not allowed for me to do that?
2. The problem is since using version 3.0.0, every time i restarted my pc, and open the apps againt, the blockUI blockoverlay class show off, and i cannot do anything on the screen, the solution is i must copy all the data from here againt and drop the old database and create the new one, and the apps work fine.. can you tell me why?

i'm using mac os x el capitan, mamp apache and mysql server..
PHP 5.6.25
MYSQL 5.6.28

![screen shot 2016-10-03 at 5 31 27 pm](https://cloud.githubusercontent.com/assets/22451842/19035136/cdd11f0c-8991-11e6-89d3-1711abc53bd9.png)

**Comment by daN4cat** [comment]
Read the FAQ in the README and the COYPING (License) file.

**Comment by daN4cat** [comment]
The database can be upgraded, no issue about that.

**Comment by rnld26** [comment]
![screen shot 2016-10-03 at 6 09 26 pm](https://cloud.githubusercontent.com/assets/22451842/19035586/90bf1b7a-8994-11e6-8eba-322cb339f8f8.png)

i'm just modified sale models, views, controllers so far.. only sale.. nothing else..

**Comment by odiea** [comment]
Do the required database upgrades then try the following.
Start Apache and Mysql.
From Apache select Config.
Edit the Php.ini file to uncomment the following extensions. Extensions are about halfway down.
bcmat appears to be enabled in this version of Xampp.
[bcmath]
; Number of decimal digits for all bcmath functions.
; http://php.net/bcmath.scale
bcmath.scale=0

extension=php_gd2.dll
extension=php_intl.dll
extension=php_sockets.dll
Now Apache should be ready to go.

**Comment by daN4cat** [comment]
He's using a MAC, he needs to check the php configuration in apache and rebuild it with the required extensions: bcmath, gd2, intl and soekctes.

**Comment by daN4cat** [comment]
No further, I close this issue.
