### ISSUE TITLE
Adding translation for a new word

### ISSUE THREAD

**Issue by deepshah** [jekkos/opensourcepos#888]
### Question

I am working on an enhancement and it uses a word ('table') not present in the translation files currently. What is the recommended way to add it to the translations. I see weblate is being used, but could not find where to suggest new words.

Also, do translations need to be present in all languages? Does it throw an error if I use `$this->lang->line('config_table')` but config_table is present only in some languages. Or does it default to a particular language?

**Comment by daN4cat** [comment]
If the string is defined but there is no translation you get printed a string like `config_table_TBD`.

Just give a try to print in a view a string where there is no translation and you'll see.

**Comment by daN4cat** [comment]
The process to add to Weblate is something @jekkos can clarify.
At the moment just work on the functionality and add what you need in English language + your one at least. The translation can be sorted later.

**Comment by jekkos** [comment]
Adding it in english should normally suffice. The process hasn't been tested yet but english is marked as the base language. Once a new string in english is detected by weblate it should offer to port it to other languages (I hope).

**Comment by jekkos** [comment]
New strings should just be added in the code. Then this change needs to be pulled in by weblate and loadpo target should be run to reindex the translations. I just did this for the two new strings and they are available for translation now

@daN4cat think we can get rid of the translation script + csv's after all now.

**Comment by daN4cat** [comment]
@jekkos ok, I'll do.

**Comment by daN4cat** [comment]
Shall we close this issue too?
