### ISSUE TITLE
Display Customer address on selection

### ISSUE THREAD

**Issue by ashishkaushik** [jekkos/opensourcepos#89]
While calling set customer while making sales how can I display complete address as well instead if just Firstname and Lastname.

**Comment by jekkos** [comment]
Just adapt the register.php view to show the additional fields that you wish to show. I think this will require at max 5 lines of code :)

**Comment by odiea** [comment]
Where does the variable &customer come from?
if(isset($customer))
	{
		echo $this->lang->line("sales_customer").': <b>'.$customer.'</b><br />';
		echo $this->lang->line("customers_customer_address_1").': <b>'.$customer.'</b><br />';
		echo anchor("sales/remove_customer",'['.$this->lang->line('common_remove').' '.$this->lang->line('customers_customer').']');
	}
