### ISSUE TITLE
I want to remove ITEM KITS , RECEIVING and similar modules from header but not through permission. Please guide me systematically .

### ISSUE THREAD

**Issue by mzulkifel** [jekkos/opensourcepos#891]
Hi Admin , I want to remove item kits , receiving from header .
But I could not do it since it is in PHP loop .
Please guide me .

**Comment by odiea** [comment]
Just go to employees and uncheck the permissions for those modules that should do it.

**Comment by mzulkifel** [comment]
It is still visible if a new role with certain permission are given ,  inside  insert new employee  page .

**Comment by odiea** [comment]
You cannot remove the permission check boxes in the employees form. Just give the employee what he needs. Prevent him from accessing Employees then.

**Comment by daN4cat** [comment]
A sysadmin role where you can enable or disable features visible to other users is not implemented yet.

A quick removal from the code just requires going to application/views/employees/form.php and from line 80 `foreach($all_modules as $module)` just add a check to those two modules and avoid adding them to the UI.
Something like `if($module->module_id == <..module to remove..>) continue;`

You need to search for the module_ids you want to exclude. I don't remember them by heart,

**Comment by daN4cat** [comment]
No further, I assume this was good enough. I close.
