### ISSUE TITLE
Editable Receivings

### ISSUE THREAD

**Issue by petercstevenson** [jekkos/opensourcepos#892]
It would be very helpful for me to be able to edit past receivings. Is there some way to do this or should this be filed as an enhancement request?

**Comment by jekkos** [comment]
Receivings themselves are editable, their items are not.

You can always return a receiving and then adapt what was wrong. This is the only correct way and it's the same as with sales module. This way of working has been discussed thoroughly in the past.

**Comment by jekkos** [comment]
You can edit through the detailed report. If you want to change received items then just make the return
