### ISSUE TITLE
Need Help Moving mysql files to new computer (old computer won't run mysql anymore)

### ISSUE THREAD

**Issue by justmark123** [jekkos/opensourcepos#893]
### Issue, Question or Bug

Before submitting an issue please make sure you remove the first section of the template and you tick (add a x between the square brakets) and agree with all the following check boxes:

- [x] Checked the current issues database and no similar issue was already discussed
- [x] Read the README, WHATS_NEW and UPGRADE
- [x] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php5-gd, php-intl and sockets installed)
- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [x] PHP version is at least 5.5 and not 7.x
- [x] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [x] Know the name and version of OS, Web server and MySQL and will add to my issue report

IMPORTANT: If you remove the template when submitting an issue your issue will be closed.

### Installation information
I need to move all the mysql files to a new computer because my computer died and mysql will not run on it anymore (it was an old windows xp box). 

How can I "import" the files from one computer to another if I can't open mysql on the original computer to export them as sql files?

I am using wamp 2

### Expected behaviour
mysql should run

### Actual behaviour
mysqld.exe error. mysql server won't start.

### Steps to reproduce the issue
mysqld.exe error happens every time I boot up the computer.

**Comment by daN4cat** [comment]
What about searching in stackoverflow for help?

**Comment by odiea** [comment]
Not an OSPOS issue.
