### ISSUE TITLE
Custom Report

### ISSUE THREAD

**Issue by markhoof** [jekkos/opensourcepos#894]
It would be a nice feature to be able to create custom reports, or make sections of specific reports permission based. For example, in the Inventory Report, I am attempting to remove the cost and pricing information.  Is this possible to do? 

Before submitting an issue please make sure you remove the first section of the template and you tick (add a x between the square brakets) and agree with all the following check boxes:
- [x] Checked the current issues database and no similar issue was already discussed
- [x] Read the README, WHATS_NEW and UPGRADE
- [x] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php5-gd, php-intl and sockets installed)
- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [x] PHP version is at least 5.5 and not 7.x
- [x] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [x] Know the name and version of OS, Web server and MySQL and will add to my issue report

**Comment by daN4cat** [comment]
You can create your custom reports coding them, just look at the Summary reports in vs 3.0.1 as I made a big rework. Having additional ones on the model side should not be a big problem.
However for more advance features it's probably better to use an external dedicated tool like Reportico and query your database creating the templates you want.
