### ISSUE TITLE
Installation Information

### ISSUE THREAD

**Issue by HamidCh** [jekkos/opensourcepos#895]
### Installation information
I need to know if I have to make changes to some particular files while deploying it online on cpanel? Which changes should i make in database.php file?

**Comment by odiea** [comment]
No template.

**Comment by HamidCh** [comment]
Then kindly guide me How to deploy it on cpanel?

**Comment by alvin101** [comment]
These things where learned many years ago by most of us.  I think we need to call for some volunteers to help with the wiki here.  It would not hurt to help newbee's to find resources on these things.

**Comment by daN4cat** [comment]
@alvin101 agree and we need help too with the replies. So if you have a reply to help @HamidCh that would be great.

**Comment by alvin101** [comment]
@HamidCh I have started a wiki page to help you and others with these things, however google in many cases is your best friend here. I have not much time to add to the wiki at the moment. So google how to use cpanel and other questions. Help me add to the wiki page what you learn.

**Comment by HamidCh** [comment]
Yeah I will tell you the details when I'll be successful to deploy it. Can anyone of you please tell me if there is any check which is preventing it from uploading to cpanel?

**Comment by daN4cat** [comment]
What do you mean with uploading with panel? Which feature exactly the file browser or something else?

**Comment by HamidCh** [comment]
I am uploading ospos to my cpanel against a subdomain on my website say pos.mywebsite.com. But when I setup the whole pos then just a blank white page loads and nothing else. Meanwhile when I upload an older version of ospos than it works fine? Version of my php is 5.4 i think. Is there any possibility that this version is not supported by ospos 3.0 ir code igniter.

**Comment by daN4cat** [comment]
are you using latest master? If yes the subdomain needs to point to the public dir

**Comment by HamidCh** [comment]
I have a woocommerce store in my public_html folder so I have pointed my subdomain to public_html/pos and have put all the masterpos files there. Database.php file is configured properly.

**Comment by alvin101** [comment]
if it is a subdomain, then it would be something like pos.mywebsite.com if it is a sub file folder in your public html folder then it would be something like mywebsite.com/pos 

I have seen some web host just put a subfolder (of the same name) in you public folder when you create a subdomain. But ether way works, subdomain or subfolder.  In addition you can run this script to see what version of php you are using, 

`<?php // Show all information, defaults to INFO_ALL phpinfo(); ?>` 

more info here: https://github.com/jekkos/opensourcepos/wiki/General-information-about-webservers,-php-scripts,-and-mysql-data-base's

**Comment by HamidCh** [comment]
Can you please tell me that does master pos supports php 5.4 or not?

**Comment by alvin101** [comment]
The read me says, PHP version 5.5 or newer is recommended but PHP 7.x is not fully supported yet. And in releases it says OpenSourcePos 2.4 is the latest release. Until a new release is posted the current code is in development.

If you are trying the current dev code then you are at your own risk.  But no harm in trying. Developers need testers, try different versions of php and report back. This is how we get to a new release.

If you want a trouble free system (mostly) then stick to the current release.

**Comment by alvin101** [comment]
The Uniform Server Zero XI provides switching between PHP versions 5.2, 5.3, 5.4, 5.5, 5.6 or 7.0  Help the dev team by trying the dev code on The Uniform Server http://www.uniformserver.com/ZeroXI_documentation/php.html

**Comment by daN4cat** [comment]
Current master is almost release version. There is just one big left but it's a corner case.
So master can be safely used.
Please note that with composer change your pos subsiding webroot needs to point to public subdir.

**Comment by HamidCh** [comment]
I've added a wiki for local deployment using mamp. I hope it will help others.

**Comment by onyema3** [comment]
Where is the wiki?

**Comment by HamidCh** [comment]
https://github.com/jekkos/opensourcepos/wiki

**Comment by onyema3** [comment]
thanks

**Comment by daN4cat** [comment]
Good, thanks for the help

**Comment by alvin101** [comment]
@HamidCh Good tutorial, thanks
