### ISSUE TITLE
insert bulk record into ospos_items table database not update into item view

### ISSUE THREAD

**Issue by AshishDL** [jekkos/opensourcepos#898]
### Steps to reproduce the issue

When i insert bulk of record into items ospos_table database.data has not update into item module tabular format...

![items](https://cloud.githubusercontent.com/assets/22575454/19213881/cc574858-8d93-11e6-8451-fad9b4536e66.png)

**Comment by daN4cat** [comment]
What do you mean with under bulk data? Excel import or else?

**Comment by AshishDL** [comment]
when i insert manually record into items table...it would not update item view side.....

**Comment by daN4cat** [comment]
MySQL 5.7 not supported yet.

**Comment by AshishDL** [comment]
@daN4cat ..I use MySQL 5.6..Is It..Ok?.

**Comment by daN4cat** [comment]
Yes, it's fine

**Comment by AshishDL** [comment]
Thank you...

**Comment by AshishDL** [comment]
@daN4cat i have one dout..that have you use ajax into POS application

**Comment by daN4cat** [comment]
AJAX is used yes and what is the concern?

**Comment by AshishDL** [comment]
the reason behind to asked you about ajax because if we have huge data in database. it will help to increase autosearch speed to find particuler data**[like we have search item option in POS application].**.But as you said that ajax is used.so..i could not find other option to increase speed for item search quickly..if you have please please inform... ??

**Comment by daN4cat** [comment]
As said I'm working on it and AJAX has nothing to do with this story.

**Comment by AshishDL** [comment]
k..thanks..
