### ISSUE TITLE
Error And Updating Item

### ISSUE THREAD

**Issue by AshishDL** [jekkos/opensourcepos#899]
Steps to reproduce the issue

When i add new item it Will give Error..Kindly Inform ...PFB Screen
![imggg](https://cloud.githubusercontent.com/assets/22575454/19213960/5b62f810-8d96-11e6-9403-0501aa3e947e.png)

**Comment by daN4cat** [comment]
Are you using MySQL 5.7? Please clarify versions otherwise we cannot help.

**Comment by AshishDL** [comment]
Yes..i m using 5.7

**Comment by daN4cat** [comment]
So you haven't read the README right?
