### ISSUE TITLE
Reports View

### ISSUE THREAD

**Issue by odiea** [jekkos/opensourcepos#90]
When listing reports Tax is shown after the Total is there a way Tax can be shown before Total ? To me it would look better to see it included before the total amount.

**Comment by jekkos** [comment]
Yes, just a matter of swapping the order in the arrays defined in controllers/reports.php

    $tabular_data[] = array($row['sale_date'], to_currency($row['subtotal']), to_currency($row['total']), to_currency($row['tax']),to_currency($row['profit']));

should change to 

    $tabular_data[] = array($row['sale_date'], to_currency($row['subtotal']), to_currency($row['tax'], to_currency($row['total'])),to_currency($row['profit']));

**Comment by jekkos** [comment]
For detailed sales reports try to change the following in models/reports/detailed_sales.php instead

    $this->db->select('sum(subtotal) as subtotal, sum(total) as total, sum(tax) as tax, sum(profit) as profit');

to
        $this->db->select('sum(tax) as tax, sum(subtotal) as subtotal, sum(total) as total, sum(profit) as profit');
