### ISSUE TITLE
Switching to Arabic language grays out the page

### ISSUE THREAD

**Issue by jacksz** [jekkos/opensourcepos#900]
### New Feature or Enhacement

For new Features or Enhacements please remove all the template text and clearly write your proposal.
It's important to state whether you expect the community to implement it or you will contribute the work.
Please bear in mind that we will implement new features only on the current code, there is no support for old versions.

### Issue, Question or Bug

Before submitting an issue please make sure you remove the first section of the template and you tick (add a x between the square brakets) and agree with all the following check boxes:

- [x] Checked the current issues database and no similar issue was already discussed
- [x] Read the README, WHATS_NEW and UPGRADE
- [x] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php5-gd, php-intl and sockets installed)
- [x] Reporting an issue of an unmodified OSPOS installation
- [] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [x] PHP version is at least 5.5 and not 7.x
- [x] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [x] Know the name and version of OS, Web server and MySQL and will add to my issue report

IMPORTANT: If you remove the template when submitting an issue your issue will be closed.

### Installation information
OSPOS installed as is, version 3.0.0 4f5ad57.

linux server PHP Version 5.6.23-pl0-gentoo 
mysql 5.0.11
### Expected behaviour
![lol2](https://cloud.githubusercontent.com/assets/14059965/19225313/bd5a6ea6-8ea2-11e6-8823-a13f1578f749.png)

### Actual behaviour
grayed out page where UI blocker is active.. 
![lol](https://cloud.githubusercontent.com/assets/14059965/19225306/90eabe5c-8ea2-11e6-9e7e-9ea4c9ad98f7.png)

### Steps to reproduce the issue
Choosing arabic as a language 

### Weblate
weblate arabic is a 100%? so i dont know why the issue still there according to other issues

**Comment by odiea** [comment]
Open Source Point Of Sale Version is not in the footer so it was not properly translated.

**Comment by jacksz** [comment]
do you mean OSPOS 3.0.0 - 4f5ad57?

**Comment by jacksz** [comment]
yes

**Comment by daN4cat** [comment]
OK fixed, try the latest master or just replace your /application/language/ar-EG/common_lib.php file with the one from master.

**Comment by jacksz** [comment]
It's working great now, thank you.
