### ISSUE TITLE
what is this problem

### ISSUE THREAD

**Issue by dxchen90** [jekkos/opensourcepos#901]
A PHP Error was encountered
Severity: 8192
Message: mysql_connect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead
Filename: mysql/mysql_driver.php
Line Number: 136
Backtrace:
File: /home2/whypaym2/public_html/stock/application/controllers/Secure_area.php
Line: 12
Function: __construct
File: /home2/whypaym2/public_html/stock/application/controllers/Home.php
Line: 8
Function: __construct
File: /home2/whypaym2/public_html/stock/index.php
Line: 292
Function: require_once

**Comment by daN4cat** [comment]
OSPOS version?
Using old application/config/database.php?

**Comment by dxchen90** [comment]
Version 2.4
use bluhost, i upgrade php version to 5.6, then download latest ospos and upload to it, not working, then restore back to last use version. then become like this already.

**Comment by daN4cat** [comment]
If you are upgrading from 2.4 to 3.0.0 you need to take the new database.php.tmpl file and copy the fields value from your old one into new one.
Also remember to make a copy of your database and then upgrade from 2.4 to 3.0 running database/2.4_to_3.0.sql script

**Comment by dxchen90** [comment]
this is the what from new database.php.tmpl file.

I fill in back the details and save it back to config folder? am i right?

<?php
defined('BASEPATH') OR exit('No direct script access allowed');

/*
| -------------------------------------------------------------------
| DATABASE CONNECTIVITY SETTINGS
| -------------------------------------------------------------------
| This file will contain the settings needed to access your database.
|
| For complete instructions please consult the 'Database Connection'
| page of the User Guide.
|
| -------------------------------------------------------------------
| EXPLANATION OF VARIABLES
| -------------------------------------------------------------------
|
|	['dsn']      The full DSN string describe a connection to the database.
|	['hostname'] The hostname of your database server.
|	['username'] The username used to connect to the database
|	['password'] The password used to connect to the database
|	['database'] The name of the database you want to connect to
|	['dbdriver'] The database driver. e.g.: mysqli.
|			Currently supported:
|				 cubrid, ibase, mssql, mysql, mysqli, oci8,
|				 odbc, pdo, postgre, sqlite, sqlite3, sqlsrv
|	['dbprefix'] You can add an optional prefix, which will be added
|				 to the table name when using the  Query Builder class
|	['pconnect'] TRUE/FALSE - Whether to use a persistent connection
|	['db_debug'] TRUE/FALSE - Whether database errors should be displayed.
|	['cache_on'] TRUE/FALSE - Enables/disables query caching
|	['cachedir'] The path to the folder where cache files should be stored
|	['char_set'] The character set used in communicating with the database
|	['dbcollat'] The character collation used in communicating with the database
|				 NOTE: For MySQL and MySQLi databases, this setting is only used
| 				 as a backup if your server is running PHP < 5.2.3 or MySQL < 5.0.7
|				 (and in table creation queries made with DB Forge).
| 				 There is an incompatibility in PHP with mysql_real_escape_string() which
| 				 can make your site vulnerable to SQL injection if you are using a
| 				 multi-byte character set and are running versions lower than these.
| 				 Sites using Latin-1 or UTF-8 database character set and collation are unaffected.
|	['swap_pre'] A default table prefix that should be swapped with the dbprefix
|	['encrypt']  Whether or not to use an encrypted connection.
|
|			'mysql' (deprecated), 'sqlsrv' and 'pdo/sqlsrv' drivers accept TRUE/FALSE
|			'mysqli' and 'pdo/mysql' drivers accept an array with the following options:
|
|				'ssl_key'    - Path to the private key file
|				'ssl_cert'   - Path to the public key certificate file
|				'ssl_ca'     - Path to the certificate authority file
|				'ssl_capath' - Path to a directory containing trusted CA certificats in PEM format
|				'ssl_cipher' - List of *allowed* ciphers to be used for the encryption, separated by colons (':')
|				'ssl_verify' - TRUE/FALSE; Whether verify the server certificate or not ('mysqli' only)
|
|	['compress'] Whether or not to use client compression (MySQL only)
|	['stricton'] TRUE/FALSE - forces 'Strict Mode' connections
|							- good for ensuring strict SQL while developing
|	['ssl_options']	Used to set various SSL options that can be used when making SSL connections.
|	['failover'] array - A array with 0 or more data for connections if the main should fail.
|	['save_queries'] TRUE/FALSE - Whether to "save" all executed queries.
| 				NOTE: Disabling this will also effectively disable both
| 				$this->db->last_query() and profiling of DB queries.
| 				When you run a query, with this setting set to TRUE (default),
| 				CodeIgniter will store the SQL statement for debugging purposes.
| 				However, this may cause high memory usage, especially if you run
| 				a lot of SQL queries ... disable this to avoid that problem.
|
| The $active_group variable lets you choose which connection group to
| make active.  By default there is only one group (the 'default' group).
|
| The $query_builder variables lets you determine whether or not to load
| the query builder class.
*/
$active_group = 'default';
$query_builder = TRUE;

$db['default'] = array(
	'dsn'	=> '',
	'hostname' => 'localhost',
	'username' => '',
	'password' => '',
	'database' => '',
	'dbdriver' => 'mysqli',
	'dbprefix' => 'ospos_',
	'pconnect' => FALSE,
	'db_debug' => (ENVIRONMENT !== 'production'),
	'cache_on' => FALSE,
	'cachedir' => '',
	'char_set' => 'utf8',
	'dbcollat' => 'utf8_general_ci',
	'swap_pre' => '',
	'encrypt' => FALSE,
	'compress' => FALSE,
	'stricton' => FALSE,
	'failover' => array(),
	'save_queries' => TRUE
);

**Comment by daN4cat** [comment]
Yes, fill it and of course rename it to be database.php

**Comment by dxchen90** [comment]
Do i need to replace the old config file from 2.4 to the new 3.0 folder?

**Comment by dxchen90** [comment]
when updating database,
i got this error,


Error
SQL query:


ALTER TABLE `ospos_receivings`
 DROP KEY `invoice_number`,
 CHANGE COLUMN `invoice_number` `reference` varchar(32) DEFAULT NULL,
 ADD KEY `reference` (`reference`);

MySQL said:  <https://box6072.bluehost.com:2083/cpsess4956265735/3rdparty/phpMyAdmin/url.php?url=http%3A%2F%2Fdev.mysql.com%2Fdoc%2Frefman%2F5.5%2Fen%2Ferror-messages-server.html>#1054 - Unknown column 'invoice_number' in 'ospos_receivings’

**Comment by daN4cat** [comment]
Have you upgraded already to 3.0?

**Comment by daN4cat** [comment]
Because it looks like your database was upgraded or it's very old, pre 2.4

**Comment by dxchen90** [comment]
i go to phpmyadmin, then choose on the database name, import the 2.4-3..0. is this the correct way?

**Comment by dxchen90** [comment]
i run again the 2.3.4 - 2.4 and 2.4-3.0 , it still shows the same error.

**Comment by dxchen90** [comment]
Hi,

I try to make a clean installation.
Install a new database. import database.sql, then run 2.4-3.0, it shows the same error.

**Comment by dxchen90** [comment]
Update*

I deleted all the old files and upload back the latest master file.
i go to my  website example.com/stock/ it shows all the files, when i access public folder, it load something with the ospos logo, but there is error code on top.

A PHP Error was encountered

Severity: Warning

Message: Invalid argument supplied for foreach()

Filename: hooks/load_config.php

Line Number: 47

Backtrace:

File: /home2/whypaym2/public_html/stock/application/hooks/load_config.php
Line: 47
Function: _error_handler

File: /home2/whypaym2/public_html/stock/application/hooks/load_config.php
Line: 22
Function: load_langauge_files

File: /home2/whypaym2/public_html/stock/public/index.php
Line: 315
Function: require_once

**Comment by daN4cat** [comment]
Please use the latest code from master because the typo `langauge` was something I fixed the other day.
Besides make sure you have all the files from application folder uploaded, same from vendor and public.

Also please check the .htaccess file in public/ because if you use a subdomain (pos.myweb.com) that redirects to www.myweb.com/pos you need to change something in .htaccess to work properly.

**Comment by dxchen90** [comment]
hi,

i install it in example.com/stock
inside the stock folder.
do i need to change the .htaccess ? the .htaccess file is in my server public folder right?

**Comment by daN4cat** [comment]
Yes check the .htaccess file in public/ under your stock dir.

Again if your subdomain redirects it has to redirect to public singolare.

**Comment by dxchen90** [comment]
My stock dir do not have .htaccess file, it only all the files extracted from the master download.

i not installing in the hosting root. do you mean i need to find the .htacess file in the hosting root?

**Comment by dxchen90** [comment]
This is the error i have now…


A PHP Error was encountered

Severity: Warning

Message: Invalid argument supplied for foreach()

Filename: hooks/load_config.php

Line Number: 49

Backtrace:

File: /home2/whypaym2/public_html/stock/application/hooks/load_config.php
Line: 49
Function: _error_handler

File: /home2/whypaym2/public_html/stock/application/hooks/load_config.php
Line: 22
Function: load_language_files

File: /home2/whypaym2/public_html/stock/public/index.php
Line: 315
Function: require_once

**Comment by jekkos** [comment]
Did you run the upgrade script?

**Comment by jekkos** [comment]
The langauge key is missing in your database that's why you're seeing this error. You might not have run the latest database.sql.

**Comment by dxchen90** [comment]
I got error when run the 2.4-3.0 sql.
I cannot upgrade even i do a clean installation.






On Mon, Oct 10, 2016 at 7:40 PM +0800, "jekkos" <notifications@github.com> wrote:












The langauge key is missing in your database that's why you're seeing this error. You might not have run the latest database.sql.

**Comment by daN4cat** [comment]
Maybe we should add IGNORE to each of the MySQL upgrade statements so the script doesn't stop and continues.

**Comment by onyema3** [comment]
Maybe

**Comment by dxchen90** [comment]
How to add the IGNORE? Or should i wait for new release?






On Tue, Oct 11, 2016 at 8:42 PM +0800, "FrancescoUK" <notifications@github.com> wrote:












Maybe we should add IGNORE to each of the MySQL upgrade statements so the script doesn't stop and continues.

**Comment by daN4cat** [comment]
It's not a good idea to use IGNORE, as of MySQL 5.7.4 it's deprecated https://dev.mysql.com/doc/refman/5.7/en/alter-table.html

**Comment by daN4cat** [comment]
@dxchen90 you need to probably do something from command line forcing the script to run with --force or similar.

**Comment by dxchen90** [comment]
how to do it? can send me the code here?

**Comment by daN4cat** [comment]
Web search engines are your friend....

https://dev.mysql.com/doc/refman/5.5/en/mysql.html

> mysql --force db_name < 2.4_to_3.0.sql

(I didn't try myself but it should work according to the --force option description)

**Comment by dxchen90** [comment]
i am getting this error,

#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'mysql --force whypaym2_stock2 < 2.4_to_3.0.sql' at line 1

**Comment by daN4cat** [comment]
ok, maybe you need username and password. Have you read the link I provided you?
Something like:

> mysql --user=user_name --password=your_password --force db_name < 2.4_to_3.0.sql

and I assume you are executing the command from the database dir, if not add the database/ before the script.

**Comment by daN4cat** [comment]
@dxchen90 issue solved?

**Comment by dxchen90** [comment]
no, i hire freelance to help me. still working on it.

**Comment by daN4cat** [comment]
OK, they can do for you. I close.
