### ISSUE TITLE
 core/MY_Lang.php

### ISSUE THREAD

**Issue by jamil2012** [jekkos/opensourcepos#902]
i have problem:
A PHP Error was encountered
Severity: Runtime Notice
Message: Declaration of MY_Lang::line() should be compatible with that of CI_Lang::line()
Filename: core/MY_Lang.php
Line Number: 93
Backtrace:
File: /home5/crunlock/public_html/tb505/index.php
Line: 292
Function: require_once

My server:
Apache	2.2.31
PHP	5.4.24
MySQL	5.5.51

**Comment by daN4cat** [comment]
Which OSPOS version are you talking about?

**Comment by daN4cat** [comment]
Also are you upgrading or using just the latest?

**Comment by jamil2012** [comment]
OSPOS version 2.4

**Comment by jamil2012** [comment]
Help me please.

**Comment by daN4cat** [comment]
Nobody complained about 3.4 for a long time, so not sure what you have done.
Is this something you modified or else?

**Comment by jamil2012** [comment]
a few days ago presented the error, I have not changed any files.

**Comment by daN4cat** [comment]
I don't know, to be honest I have no idea what happened to your installation and it's not an OSPOS application issue but some configuration or database corruption or setup...

therefore I close.
