### ISSUE TITLE
When i Click on Email Button it will not work

### ISSUE THREAD

**Issue by AshishDL** [jekkos/opensourcepos#903]
Steps to reproduce the issue

Dear Team,Please find bellowed mentioned

![email](https://cloud.githubusercontent.com/assets/22575454/19246456/12f32b0e-8f44-11e6-94f5-aad0e053f0a8.png)

When i click on Email Button it will not pop any page or it would not redirect any link

**Comment by daN4cat** [comment]
Tested and works fine. It's your setup issue I'm afraid.

**Comment by AshishDL** [comment]
k...
