### ISSUE TITLE
missing index.php

### ISSUE THREAD

**Issue by LoverreVI** [jekkos/opensourcepos#905]
i've trying to run this with no success,
also i've notice that someone deleted index.php on the main folder (missing index.php on opensourcepos/index.php << gone)
also i have an issue with 403 forbidden, everyone keep telling me to change "deny" to "allow" on conf, but there's nothing got "deny"ed on my httpd.conf,, pls help,
p.s can anyone give me a link for a proper wamp installation that met all the requirement for this opensourcepos? pls, this is frustrating, im new to php, wamp, xampp things, 

thank you.

**Comment by LoverreVI** [comment]
<URGENT>CONFIRMED, someone did something on the latest master source code, it won't run on me, but when i used the master source code from uhh a week ago, it runs fine

**Comment by daN4cat** [comment]
@LoverreVI master uses composer, which enhances the security too.

You now need to point to public subdir, which contains index.php.

**Comment by LoverreVI** [comment]
@daN4cat thank you kindly sir, sorry about the dumb question, this is not my in my area of expertise lol
and now im completely lost :p
so basicly,
 i just need to blatantly point an address of index.php which was located in any of the subdir?

p.s. again, pls don't get mad at me, 
im new to this php and CI framework which i had no idea about
and im a bit dumb

**Comment by daN4cat** [comment]
the subdir is called public.

So it's http://www.myweb.com/pathtopos/public/index.php

**Comment by LoverreVI** [comment]
thank you, 

p.s pls don't close this thread, i'll ask here if i had another problem coming up,
its better than spamming over the issues page with some of my sill question(s).
thank you.

**Comment by daN4cat** [comment]
@LoverreVI can we close this please?
