### ISSUE TITLE
Can't return smaller amount of products

### ISSUE THREAD

**Issue by Modding** [jekkos/opensourcepos#906]
When i go to Sales and go to Return and scan a Reciept.

Than i want to return only one Piece from a bigger amount like:

6 PCs of Product 1 and the Customer only want to return 1 i cant change the Amount. It always says Error in changing Artikle.

Greetings Valentin

**Comment by daN4cat** [comment]
I tried:
- select from Sale register Return from the drop down
- returned a POS ## from Sales that had 2 items (shown as -2)
- set quantity -1 as that's what I wanted to return and press enter
- all the amounts adjust automatically after the enter
- selected payment return method
- completed the return
- everything works fine.

Please check exactly how you reproduced the issue as it's unclear to me.

**Comment by daN4cat** [comment]
Also please check that your item is not deleted or similar cases.

**Comment by odiea** [comment]
The first few time I tried it I did get the following error but after trying some more it did work properly.

![2016-10-12 17_31_51-settings](https://cloud.githubusercontent.com/assets/10962177/19331823/2bd1752a-90a4-11e6-9546-3af4720ea8e8.png)

**Comment by daN4cat** [comment]
@Modding any update?

**Comment by Modding** [comment]
https://www.youtube.com/watch?v=MNi0JEmwGrw

**Comment by daN4cat** [comment]
OK, but what's the quantity of items after having sold 7? 0 or something else?
Also, can you tell me what's the message in the red bar saying as I cannot read German?

**Comment by daN4cat** [comment]
And is that issue happening with the latest master?

**Comment by Modding** [comment]
The Quantity after sold 7 is ~ 30 - 40 Enough is in the stock. And the Error message is "Error in changing Artickle"

**Comment by daN4cat** [comment]
@Modding is that the latest master or something older?

**Comment by Modding** [comment]
This is the Master wich is 1 Week old

**Comment by odiea** [comment]
It does not appear to be the new composer version. I do not see his address pointing to the public folder.

**Comment by Modding** [comment]
It looks like there is only this error if the Casher hasnt enough rights. 

I think its a rights Problem, because with ADMIN it works.

**Comment by daN4cat** [comment]
OK, can you figure out which permission?

**Comment by daN4cat** [comment]
@Modding any news? I checked the code and I can't understand how a employer right could limit this, but I want to make sure it's really the case first.
