### ISSUE TITLE
No item to display

### ISSUE THREAD

**Issue by Rebelion** [jekkos/opensourcepos#907]
Ospos ver : 3.0.0 - 4f5ad57
OS : Windows 10 x86
Web Server : Apache 2.4.23
Database ver: MySQL 5.7.14
PHP ver : PHP 5.6.25
Language : English (en_US)
Any configuration of OSPOS that I changed : Nothing, just some changing on **General Store Configuration**

I'm running fresh instalation of OSPOS. The problem is after I log in. Every I add new item, or export from excel, it won't show in Items Tab, it say "**No item to display**". So I check on my database and the data is there. Is any of you can show me how to fix it?

note : I already run the sql update script "2.4_to_3.0.sql" and it is show an error.
![ospos - items](https://cloud.githubusercontent.com/assets/1285388/19337069/a42f43ac-913b-11e6-8642-b6de532dfafe.jpg)
![phpmyadmin - items](https://cloud.githubusercontent.com/assets/1285388/19337070/a433e2cc-913b-11e6-9ead-95a1f90387ab.jpg)
![phpmyadmin - update sql error](https://cloud.githubusercontent.com/assets/1285388/19337071/a435bae8-913b-11e6-863b-6f251957ddfa.jpg)

**Comment by daN4cat** [comment]
MySQL 5.7 is not supported yet.

**Comment by Rebelion** [comment]
Thanks for the feed back, I will try the compatible version of MySQL (5.6).
