### ISSUE TITLE
Item-Kits vs Ingredients

### ISSUE THREAD

**Issue by reenenlaurie** [jekkos/opensourcepos#91]
So I'm trying to create a case-study for a Pizza place.  So initially I created "Margarita" as an item, and Regina etc. but the problem is Regina is not a stock unit.  It's a completed assembled product.  So for stock keeping purposes a Margarita is a base, cheese, sauce and herbs, but for sales it's just a Margarita.

Now I can create an Item-Kit called Margarita which is 1 base, 1 cheese (2x?), 1 sauce and 1 herbs, but then I can't set a customized price for my Margarita.  I have to just use the sum of the ingredients value as the price, but that might be more (or less) than what I really want to ask for the product.  (And I don't want the customer to see "1x Base, 1x Cheese, 1x Sauce, 1x Herbs".

So what is the proposed solution for this?

**Comment by jekkos** [comment]
Well I suppose you'll have to adapt the code + database model (as usual) to allow for a pricing override for the item kits in this case. Luckily this is still an opensource project!

Also the receipt will need to be adapted to grasp exactly what a Margarita is made of.
