### ISSUE TITLE
customer specific discounts and item kits 

### ISSUE THREAD

**Issue by jacksz** [jekkos/opensourcepos#910]
### New Feature or Enhacement

For new Features or Enhacements please remove all the template text and clearly write your proposal.
It's important to state whether you expect the community to implement it or you will contribute the work.
Please bear in mind that we will implement new features only on the current code, there is no support for old versions.

### Issue, Question or Bug

Before submitting an issue please make sure you remove the first section of the template and you tick (add a x between the square brakets) and agree with all the following check boxes:

- [x] Checked the current issues database and no similar issue was already discussed
- [x] Read the README, WHATS_NEW and UPGRADE
- [x] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php5-gd, php-intl and sockets installed)
- [x] Reporting an issue of an unmodified OSPOS installation
- [] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [x] PHP version is at least 5.5 and not 7.x
- [x] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [x] Know the name and version of OS, Web server and MySQL and will add to my issue report

IMPORTANT: If you remove the template when submitting an issue your issue will be closed.

### Installation information
master installation github
php 5.6
mysql 5.0.11

### Expected behaviour
if you add customer first and then add items , the discount works.
![sda](https://cloud.githubusercontent.com/assets/14059965/19362745/872404fa-9190-11e6-87b4-d8921845971b.png)

### Actual behaviour
if you add items and then add customer the discount doesnt work
![sda2](https://cloud.githubusercontent.com/assets/14059965/19362981/53f1ac6c-9191-11e6-82ed-46087cb5b848.png)

### Item kits 
with item kits it wont work either way (the two ways specified above)
![sda3](https://cloud.githubusercontent.com/assets/14059965/19363122/dc8559f2-9191-11e6-915a-f40b00952b61.png)

### Steps to reproduce the issue
1-if you add items and then add customer the discount doesnt work
2-discount doesnt work with item kits

**Comment by odiea** [comment]
Currently it does not work on Item kits. Not a lot of users so not much extra written for it.
The first sale without a customer is correct. The registered item was not told it had a discount available. You will need to enter the % manually or delete the item then re-add the item.

**Comment by jekkos** [comment]
Yes indeed the usecase probably foreseen in the inital implementation. Consider this a bug or enhancement?

**Comment by daN4cat** [comment]
I noticed this and I wanted to address. It's probably a bug because discount should be applied in both cases before or after having added an item.

With regards to item kits, that's an enhancement.

**Comment by daN4cat** [comment]
OK, now the customer discount is applied when the customer is selected after having added the items.
Please test to confirm is all fine.
Please note that there is no case for reset the discount if the customer is removed, that feature would require keeping memory of what was added and when. A complex feature.

**Comment by odiea** [comment]
Looks good to me. It applied the discount after the customer was selected and an item was already in the register. Good work.

**Comment by daN4cat** [comment]
Thanks. Forgot to say that the discount is applied to items with 0 discount only. If something is already discounted there is no additional discount.

**Comment by jacksz** [comment]
its fixed ,thanks .

**Comment by daN4cat** [comment]
OK Item kits was working only if you added the customer after having added the item kit.
With my last commit it works even if the customer is set first and item kit loaded second, the customer discount is applied automatically.

I believe this can be closed now as both issues are sorted.
