### ISSUE TITLE
Error on wamp

### ISSUE THREAD

**Issue by gituncar** [jekkos/opensourcepos#912]
Error 

Fatal error: Can't use method return value in write context in C:\xampp\htdocs\opensourcepos\application\controllers\Items.php on line 123
A PHP Error was encountered

Severity: Compile Error

Message: Can't use method return value in write context

Filename: controllers/Items.php

Line Number: 123

Backtrace:

**Comment by daN4cat** [comment]
Using MySQL5.7? If yes, it's not supported yet.
Also we don't support PHP7 yet.
