### ISSUE TITLE
Labels and Milestones,

### ISSUE THREAD

**Issue by alvin101** [jekkos/opensourcepos#914]
Just a quick note,

I would like to see a description of the meaning of Labels and Milestones, either in readme or wiki.

**Comment by daN4cat** [comment]
Milestones are releases (e.g. 3.0.0), labels are way to categorise the reported issues, requests or questions.

**Comment by daN4cat** [comment]
I assume the question was answered, correct @alvin101 ?

**Comment by alvin101** [comment]
> I assume the question was answered, correct

@daN4cat no not really, I think it would be good to spell it out in readme or wiki, labels mean different things to different people like Epic. and how this project uses these terms.  But we can close this....

**Comment by daN4cat** [comment]
OK, needs to be added to the wiki.

**Comment by daN4cat** [comment]
Added to the wiki: https://github.com/jekkos/opensourcepos/wiki/Milestones-and-Label

further refinements welcomed.
