### ISSUE TITLE
403 Forbidden problem in new installation

### ISSUE THREAD

**Issue by Altoubi** [jekkos/opensourcepos#915]
Hi, I`m trying to  make new install with latest changes, but it look like there are no index.php and no system folder, when i try to install it show me error 403 Forbidden! even it on main root / or in sub folder.

i changed folder path in .htaccess file. and this error shows in both localhost and online webhost

please guide me 

### Issue, Question or Bug

- [x] Checked the current issues database and no similar issue was already discussed
- [] Read the README, WHATS_NEW and UPGRADE
- [x] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php5-gd, php-intl and sockets installed)
- [] Reporting an issue of an unmodified OSPOS installation
- [x] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [x] PHP version is at least 5.5 and not 7.x
- [] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [] Know the name and version of OS, Web server and MySQL and will add to my issue report

IMPORTANT: If you remove the template when submitting an issue your issue will be closed.

### Steps to reproduce the issue

**Comment by daN4cat** [comment]
Point your webroot to be the public dir.

**Comment by Altoubi** [comment]
can you explain, i didn't get you

**Comment by daN4cat** [comment]
Check public/ you'll find index.php there. So your web root needs to be there.
Not sure what your installation is because you ignore all those questions in the issue template.

**Comment by zhumingyu** [comment]
@daN4cat sorry,i got the same problem.is there any wrong?
![2017-05-29-155642_486x239_scrot](https://cloud.githubusercontent.com/assets/10820548/26541251/86987f02-4487-11e7-8f5b-7a65d3723c12.png)

**Comment by daN4cat** [comment]
@zhumingyu since you are using a subdir you need to check the .htaccess under public and set the rules to use the subdir.

By the way, I'm not sure you want to set +Indexes, probably you may want to state -Indexes.

**Comment by zhumingyu** [comment]
thks
