### ISSUE TITLE
Low Inventory Report gives incorrect quantity

### ISSUE THREAD

**Issue by petercstevenson** [jekkos/opensourcepos#916]
### New Feature or Enhacement

For new Features or Enhacements please remove all the template text and clearly write your proposal.
It's important to state whether you expect the community to implement it or you will contribute the work.
Please bear in mind that we will implement new features only on the current code, there is no support for old versions.

### Issue, Question or Bug

Before submitting an issue please make sure you remove the first section of the template and you tick (add a x between the square brakets) and agree with all the following check boxes:

- [x] Checked the current issues database and no similar issue was already discussed
- [x] Read the README, WHATS_NEW and UPGRADE
- [x] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php5-gd, php-intl and sockets installed)
- [] Reporting an issue of an unmodified OSPOS installation
- [] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [] PHP version is at least 5.5 and not 7.x
- [] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [] Know the name and version of OS, Web server and MySQL and will add to my issue report

IMPORTANT: If you remove the template when submitting an issue your issue will be closed.

### Installation information

Web docker install

### Expected behaviour

Low Inventory Report gives the same quantity information as the Items search

### Actual behaviour

Low Inventory Report does not give the same information as the Items search

### Steps to reproduce the issue

I am not really sure. This may have happened when I added a second stock location. Right now I have many items that the Low Inventory Report lists as having a quantity of 0 in both of my stock locations but if I search for the item under Items it lists that I have some in stock in one of my stock locations. This has happened to some items but not others and I have not been able to figure out what is different about them or to recreate the problem by creating new items.

**Comment by daN4cat** [comment]
We need to have the test case clear otherwise we might spend too much time figuring out hypothetical scenarios.

**Comment by petercstevenson** [comment]
OK, I will try harder to duplicate it. Clearly the Low Inventory Report and the Items list point to different numbers for the quantities, so I thought that you might be able to look there.

**Comment by petercstevenson** [comment]
Either my database is corrupted or there is something very buggy about the stock locations. When I went to the Stock page in Store Config I got this page:
![screenshot from 2016-10-20 14 01 30](https://cloud.githubusercontent.com/assets/21316584/19577859/dd959bcc-96cd-11e6-977f-e83c80b52e1a.png)
I could not click on Submit because of this error message. When I changed the name of Stock Location 1, I could press submit:
![screenshot from 2016-10-20 14 01 45](https://cloud.githubusercontent.com/assets/21316584/19577899/08294adc-96ce-11e6-91ce-6724ea4618b9.png)
Sometimes that would work properly. Sometimes, however, instead of changing the name of the stock location, it would add a new stock location:
![screenshot from 2016-10-20 14 04 31](https://cloud.githubusercontent.com/assets/21316584/19577933/3c81b2e2-96ce-11e6-82ce-6d5b63980688.png)
So now I have three stock locations, and they all show up when I look at an item. However, when I go to the Low Inventory Report, all of the deleted stock locations show up and I have 10,000 lines!
![screenshot from 2016-10-20 14 08 58](https://cloud.githubusercontent.com/assets/21316584/19578054/d0f2913a-96ce-11e6-9562-8899ea663aff.png)

**Comment by jekkos** [comment]
Yes I know that this part is not of the best quality at this moment. However this part has been reworked already in a private branch. Not sure what I'm about to do with it yet but currently I'm not going to dive into this code as aside from some weird creation / renaming bugs stock location functionality should work OK.

**Comment by jekkos** [comment]
I have set this to wontfix for now as I think the design of the stock location mgmt isn't right and so it could be replaced as a whole by multistore later on.

**Comment by jekkos** [comment]
See also #150

**Comment by petercstevenson** [comment]
If I am able to delete the extra stock locations and have OSPOS work with only one, that would be fine. At this point the biggest problem for me is that deleted stock locations are not reflected in the low-inventory report.

**Comment by daN4cat** [comment]
That's a bug, it should not show that.

**Comment by daN4cat** [comment]
Issue is fixed.

**Comment by petercstevenson** [comment]
Thanks, the Low Inventory Report issue seems fixed. If I could delete the rest of the stock locations then things would run smoothly again. It appears that the main issue is that Stock location 1 cannot be named a previously-used name (including its current name). But perhaps this will need to wait until the whole stock location system is revamped.
