### ISSUE TITLE
Item(ID=0) does not display image

### ISSUE THREAD

**Issue by Buluc-Celik** [jekkos/opensourcepos#921]
### Issue, Question or Bug

Before submitting an issue please make sure you remove the first section of the template and you tick (add a x between the square brakets) and agree with all the following check boxes:

- [x] Checked the current issues database and no similar issue was already discussed
- x[] Read the README, WHATS_NEW and UPGRADE
- [x] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php5-gd, php-intl and sockets installed)
- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [x] PHP version is at least 5.5 and not 7.x
- [x] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [x] Know the name and version of OS, Web server and MySQL and will add to my issue report
Version 2.4.0

IMPORTANT: If you remove the template when submitting an issue your issue will be closed.

### Expected behaviour
For all items with image, image should be shown on the Items page

### Actual behaviour
For the item with ID = 0, image is not shown, it is because table_helper.php has the following line:
if (!empty($item->pic_id))
and empty considers value 0 as empty.

### Steps to reproduce the issue

**Comment by daN4cat** [comment]
@jekkos should it be `if(isset($item->pic_id))`?
I don't know what the logic for that check was... better you check and change as you remember more of it.

**Comment by jekkos** [comment]
Could be correct indeed. Id=0 might be missing.. But on the other hand I wonder whether images aren't numbered starting from 1. I need to double check.

**Comment by Buluc-Celik** [comment]
Yes they start from 0 as well. Also, I  fixed it on local with isset as well.

**Comment by daN4cat** [comment]
@jekkos I need to assign to you this item pic stories because I won't be able to find the time to debug. I hope you can sort it out so we can close this release.

**Comment by daN4cat** [comment]
I believe I fixed this. See my last commit to master.

**Comment by jekkos** [comment]
Image loading looks resolved now. Also I have no issues loading the first uploaded image. So I guess we can close then?
