### ISSUE TITLE
The localhost page isn’t working.  localhost is currently unable to handle this request. HTTP ERROR 500

### ISSUE THREAD

**Issue by 520521mayuan** [jekkos/opensourcepos#923]
### New Feature or Enhacement

For new Features or Enhacements please remove all the template text and clearly write your proposal.
It's important to state whether you expect the community to implement it or you will contribute the work.
Please bear in mind that we will implement new features only on the current code, there is no support for old versions.

### Issue, Question or Bug

Before submitting an issue please make sure you remove the first section of the template and you tick (add a x between the square brakets) and agree with all the following check boxes:

- [x] Checked the current issues database and no similar issue was already discussed
- [x] Read the README, WHATS_NEW and UPGRADE
- [x] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php5-gd, php-intl and sockets installed)
- [x] Reporting an issue of an unmodified OSPOS installation
- [] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [x] PHP version is at least 5.5 and not 7.x
- [x] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [x] Know the name and version of OS, Web server and MySQL and will add to my issue report

IMPORTANT: If you remove the template when submitting an issue your issue will be closed.

### Expected behaviour

when sale the goods,complete the tickets through click the "complete" button.

### Actual behaviour

got this error prompt:

The localhost page isn’t working

localhost is currently unable to handle this request.
HTTP ERROR 500

### Steps to reproduce the issue

1. click "sales"
2. Add new item
3. click "Add Payment
4. click "Complete"

**Comment by jzonetan** [comment]
can you provide screenshoots?

**Comment by 520521mayuan** [comment]
As the follow shows:

![open source point of sale powered by ospos 3 0 0](https://cloud.githubusercontent.com/assets/7332357/19502306/a1ddab0a-95de-11e6-841f-68e9a00397ba.png)
![open source point of sale powered by ospos 3 0 0-2](https://cloud.githubusercontent.com/assets/7332357/19502316/ac657d96-95de-11e6-95d9-92e2ebf518dc.png)
![final](https://cloud.githubusercontent.com/assets/7332357/19502317/b3cc8d54-95de-11e6-82da-ab6c422e5938.png)

**Comment by 520521mayuan** [comment]
- os:   Linux debian 4.6.0-1-amd64

- mysql: mysql  Ver 14.14 Distrib 5.6.30

- apache: Apache2/2.4.23 (Debian)

- php: php 5.6.26-1 (cli)

- ospos: 3.0.0

**Comment by martadinata666** [comment]
Try enable php error message at php.ini

![2016-10-19-100856_734x50_scrot](https://cloud.githubusercontent.com/assets/2433562/19504392/19a219e6-95e4-11e6-98f8-c5a423a96984.png)

**Comment by 520521mayuan** [comment]
cat /var/log/apache2/error.log
`
[Wed Oct 19 11:30:55.402457 2016] [autoindex:error] [pid 20713] [client ::1:44420] AH01276: Cannot serve directory /var/www/html/opensourcepos/public/uploads/item_pics/: No matching DirectoryIndex (index.html,index.cgi,index.pl,index.php,index.xhtml,index.htm) found, and server-generated directory index forbidden by Options directive, referer: http://localhost/opensourcepos/public/items
`

**Comment by daN4cat** [comment]
Items is not in public. You have some setup configured issue.

**Comment by 520521mayuan** [comment]
I setup the openpos according the official tips step by step.  And I'm not do other operations.

**Comment by daN4cat** [comment]
Have you added pictures to your items?

**Comment by 520521mayuan** [comment]
yeah. the file structure is like this:

![tmp1](https://cloud.githubusercontent.com/assets/7332357/19508194/694da228-960a-11e6-9d2a-e70575fd400a.png)

and the items like this:

![tmp2](https://cloud.githubusercontent.com/assets/7332357/19508262/ce9b4ae0-960a-11e6-9462-ff6c98c762ee.png)

**Comment by daN4cat** [comment]
OK, you see you have a problem already accessing the pictures from item list.
So that's the issue here.

Thanks for the report and test, it's probably something that wasn't tested with latest dir layout change (due to composer).

**Comment by jekkos** [comment]
Indeed I guess this is a real bug.

**Comment by daN4cat** [comment]
@jekkos I need to assign to you this item pic stories because I won't be able to find the time to debug. I hope you can sort it out so we can close this release.

**Comment by daN4cat** [comment]
I found the time to check this, it's a public and subdir ownership and permission story.

@520521mayuan please make sure the public and subdirs are owned by the server user and permissions are 755 through out public dir.

**Comment by daN4cat** [comment]
@520521mayuan can you please confirm that I close this issue?
I tested different conditions yesterday and found those are the real issue nothing to do with paths in OSPOS.

**Comment by 520521mayuan** [comment]
I'm sorry for the tardy reply. I can't check it  now. I will take a close look at it as soon as possible. Thanks!

**Comment by 520521mayuan** [comment]
my file permission was already 755. 

![1](https://cloud.githubusercontent.com/assets/7332357/19582431/d018e00a-9766-11e6-97e8-1e9709022fbb.png)

So, it's not fix it up.

**Comment by 520521mayuan** [comment]
I think it's the module of apache2 should enable for this function. my enabled modules as following:

`ls /etc/apache2/mods-enabled/`

access_compat.load
alias.conf
alias.load
auth_basic.load
authn_core.load
authn_file.load
authz_core.load
authz_host.load
authz_user.load
autoindex.conf
autoindex.load
deflate.conf
deflate.load
dir.conf
dir.load
env.load
filter.load
mime.conf
mime.load
mpm_prefork.conf
mpm_prefork.load
negotiation.conf
negotiation.load
php5.conf
php5.load
rewrite.load
setenvif.conf
setenvif.load
status.conf
status.load

Is other module necessary?

**Comment by 520521mayuan** [comment]
@daN4cat any suggestions?

**Comment by daN4cat** [comment]
Try setting 777 and see if it works.

**Comment by 520521mayuan** [comment]
Not work. Got the same error.

**Comment by 520521mayuan** [comment]
I think it's the module of apache2 should enable for this function. my enabled modules as following:

ls /etc/apache2/mods-enabled/

access_compat.load
alias.conf
alias.load
auth_basic.load
authn_core.load
authn_file.load
authz_core.load
authz_host.load
authz_user.load
autoindex.conf
autoindex.load
deflate.conf
deflate.load
dir.conf
dir.load
env.load
filter.load
mime.conf
mime.load
mpm_prefork.conf
mpm_prefork.load
negotiation.conf
negotiation.load
php5.conf
php5.load
rewrite.load
setenvif.conf
setenvif.load
status.conf
status.load

Is other module necessary?

**Comment by 520521mayuan** [comment]
@martadinata666 There is no significant information even I make the display_errors=On.

**Comment by daN4cat** [comment]
Please understand that this is a setup issue, so you need to find your own way searching with Google or on Stackoverflow for hints, tips or help.
We don't have answers to all the possible issues of this world....

**Comment by jekkos** [comment]
Things are getting a little mixed up here. Solution to the initial problem might have been found in the FAQ. Please read the template as I'm sure that error code 500 on receipt generation is something that's been covered in the past.

The other bug regarding item pic upload was already tackled in #917

**Comment by jekkos** [comment]
Regarding setup, I think the most straightforward way to deploy now is docker cloud as it has all required dependencies preinstalled. 

Only thing that currently does not work is sending receipt through email.

**Comment by daN4cat** [comment]
Yep, you are right, the ticket issue could be something else. I was referring to the item avatar picture issue early on.

**Comment by 520521mayuan** [comment]
thanks @jekkos @daN4cat a lot. It's worked now. As @daN4cat say, this is not the code bug, it's a setup problem. And thanks for @jekkos reminding me that the FAQ is a key clue for resolve my problem. The following package is necessary for the pos system:

php5-gd
php-bcmath

`sudo aptitude install php5-gd php-bcmath`

That's all. Thanks again.

**Comment by daN4cat** [comment]
Good, but I somehow assumed you read the FAQ already. Anyway sorted....

**Comment by odiea** [comment]
Another reason why they should include the phpinfo. Less wasted time.

**Comment by gfidelia** [comment]
I have the same problem at login. I have just installed op pos. I followed all the steps. But at the login screen a got an err 500 message. 
Please Help.
![image](https://user-images.githubusercontent.com/20665665/27835852-6b56d8ba-60a2-11e7-97a6-f1d1712f68bd.png)

**Comment by febiramadhan192** [comment]
@gfidelia hallo, i have the same problem, that because on xampp not yet enable 2 php extentions,
follow the intructions on link : https://github.com/opensourcepos/opensourcepos/wiki/OSPOS-using-Xampp-(recommended-for-testing-or-local-use-only).

**Comment by mckaygerhard** [comment]
@gfidelia  and @febiramadhan192  i understand the README are coplety vage, but the wiki has more recomended installation methods: https://github.com/opensourcepos/opensourcepos/wiki/DOCS-USERS-Getting-Started-installations 

if try to use unsuported methods **we need the webserver logs for analize the problem**, with **only "see" we cannot "adivinate" the problem, please understand us** so the php info and modules also are need it.. inclusivelly if the template issue dont explain clarelly

**Comment by georgegoldman** [comment]
> Try enable php error message at php.ini
> 
> ![2016-10-19-100856_734x50_scrot](https://cloud.githubusercontent.com/assets/2433562/19504392/19a219e6-95e4-11e6-98f8-c5a423a96984.png)

thanks so much
