### ISSUE TITLE
item search performance slow in sales register with huge data in ospos_items table

### ISSUE THREAD

**Issue by AshishDL** [jekkos/opensourcepos#924]
Steps to reproduce the issue

when i insert huge data into ospos_table while i went to view side and search item in sales module .it will take too much time to find item..
so please inform How i can improve item search performance fastly...

![sampleee](https://cloud.githubusercontent.com/assets/22575454/19569801/ace01678-9714-11e6-823a-5a37e46da0f0.png)

**Comment by daN4cat** [comment]
You are not telling us where you run OSPOS. Local machine, remote machine, OS, PHP config and etc.

**Comment by AshishDL** [comment]
Sir,,I run ospos on remote machine.

**Comment by hzzg6y** [comment]
Ashish runs OSPOS on CentOS 7 - VPS with 1GB RAM & 256000+ items database. We  see that the performance is quite slow.  We are using Cpanel.    We basically need some pointer or hint on Scannning efficiency as when the number of items increases, search & display of item is taking long time. Hence any pointer on improving the scanning efficiency on item_ospos table will much appreciated.

**Comment by hzzg6y** [comment]
Ashish runs OSPOS on CentOS 7 - VPS with 1GB RAM & 256000+ items database. We  see that the performance is quite slow.  We are using Cpanel.    We basically need some pointer or hint on Scannning efficiency as when the number of items increases, search & display of item is taking long time. Hence any pointer on improving the scanning efficiency on item_ospos table will much appreciated.

**Comment by jekkos** [comment]
First problem is that you're using shared hosting. You probably have no control over your database  settings in any way. 

I might advice to use cloud install (docker or native) in which customized mysql configs are pobbile and for only $10 a month on DO I think you getting a lot in return (1GB RAM, 30GB disk, you can even run your own cloud storage in parallel and get docker autoredeploy for free). Only issue so far is that email doesn't currently work.

Next some database tuning is needed. You should enable slow query log in mysql. Next you can use mysqltuner perl script to optimize memory settings for your specific configuration.

One thing you can do is check the explain plan in phpmyadmin for this specific query. Some indexes might help speeding up this query. If you want you can provide the exact query + execution plan here. Currently I don't have the urge to look into this myself.

**Comment by daN4cat** [comment]
@AshishDL @hzzg6y item search is a simple MySQL query against items table, so the time here is all about the database setup.
You can always try MariaDB which is a one-to-one replacement to MySQL and seems more efficient, but you need to make sure your VPS setup is good.

**Comment by hzzg6y** [comment]
Thanks for response.  We are not using Shared hosting. We are using dedicated cloud VPS server having Cpanel in it from Rackspace. Yes.. I will get you the below soon.. 

1. Slow query log in mysql
2. Install Mysqltuner perl script.
3. Execution plan to see the cost of query. 

MariaDB is just the fork of Mysql hence I don't see  any difference it will make.

**Comment by daN4cat** [comment]
I use VPS too, dedicated and all works fine. I have a large database too.
With regards to MariaDB I can see you are "up to date" with the matter.

**Comment by daN4cat** [comment]
I reopen this because I found the time to look better into the code and sequence of search.

There is indeed space to improve as to retrieve the item from the database the code has three queries.
It should be reduced to two or maybe one, not sure.

This is legacy code, so this change will take a bit because I'm not sure what else depends on what and needs so code reading.

Because I'm working on the database performance in 3.0.1 I believe this will be a good addition.

**Comment by SteveIreland** [comment]
@daN4cat  Since you are working in this arena should I avoid touching the search function in Item.php?  Will you modify the code tomake the group by statement 5.7 compliant?

**Comment by daN4cat** [comment]
Please make your changes, don't worry. Thanks

**Comment by AshishDL** [comment]
@daN4cat ....i don't understant that **There is indeed space for improvements as to retrieve**please can you brief?

**Comment by daN4cat** [comment]
The search based on scanned number can be optimised, I will look into this next days.

**Comment by AshishDL** [comment]
k..Thank you.......

**Comment by daN4cat** [comment]
I invite everybody to take latest master as I improved the item scan time. Although it's still not optimal it's still a good improvement. 
To go further will imply more changes that will be problematic as requiring a lot of rework and not sure about how more we could improve.

**Comment by jekkos** [comment]
Maybe a combined index on item_id and item_number will improve the query result further. Will need to check against a bigger dataset but as they are now combined using OR my guess is that this might further improve execution time.

**Comment by jekkos** [comment]
From [mysql docs](http://dev.mysql.com/doc/refman/5.7/en/cast-functions.html#function_cast) ` If you convert an indexed column using BINARY, CAST(), or CONVERT(), MySQL may not be able to use the index efficiently. `

**Comment by jekkos** [comment]
It might be the case that the fix for #666 actually caused [a performance issue](http://stackoverflow.com/questions/16786063/mysql-comparison-of-integer-value-and-string-field-with-index)

**Comment by jekkos** [comment]
It might be better to cast the $îtem_id to an integer in PHP instead of having the query change the datatype.

**Comment by daN4cat** [comment]
Good one, I will look into this later and remove the MySQL cast and see if the performance is better.

**Comment by jekkos** [comment]
I did a quick test and indeed, the cast will make mysql do a full table scan. The query should be executed exactly like this

`explain select * from ospos_items where item_id = 635841641831 or item_number = '635841641831'` with the latter between quotes as it's a varchar type. In this case primary key and index on item_number are combined and explain query goes through only two rows. Couldn't get any faster than that.

Not sure how CI exactly substitutes the $item_id variable. In this case it should be an int once and a string in the other case.

**Comment by jekkos** [comment]
So in this case we'd better strip the $item_id in php, first cast it to int, and second time cast it as a string. Then check output of `$this->db->last_query().`

**Comment by jekkos** [comment]
I have further optimized this query. I think we should review other parts of the application as there might be similar issues elsewhere. Once a query is done on int field with string type, there will be full table scans. I wasn't aware of this and am pretty sure there are other cases that can be optimized.

**Comment by jekkos** [comment]
Maybe receivings should be reviewed as well. I've gotten some complaints about performance issues when entering items there as well on 2.4. I think we know now how to solve this.

**Comment by daN4cat** [comment]
I measured a bit with the latest change and it's now 3 times faster as it can use the indexes correctly.
Overall from original to latest it's about 4 times faster.

With regards to optimisations probably Item search needs to be optimised as well, the time range filter is not indexed and moreover it's a cast to DATE. That's is probably slowing down things.

**Comment by jekkos** [comment]
Yes I think we should run a profiler to see which queries are taking too much time. I found this hook and enabled it which gives me a nice view on which queries are run on every request. [Quite interesting to see.](http://jigarjain.com/blog/saving-all-db-queries-in-codeigniter/)

**Comment by daN4cat** [comment]
Looks good, just trying.

**Comment by daN4cat** [comment]
Added the database logging hook capability to the code and it's enabled from a config.php flag.

**Comment by prince90617** [comment]
We have a OSPOS application running on local machine. from few days, we are facing some issue with the application. i.e When internet slow down our application start responding slow. Is there any js or css script that requires internet. Please help us. Any help would be appreciated.

**Comment by mckaygerhard** [comment]
hi @prince90617 fortunatelly the tracking was removing recently.. was a button that suppost to "remove send statictis" but the true was that each page inclusivelly deselecting that option still send.. now that crap was removed finally. that responds due you cited "whe internet slow down", and again i was right!

**Comment by mckaygerhard** [comment]
hi @prince90617 fortunately the tracking was removing recently.. was **a button that suppose to "remove send statictis" but the true was that each page inclusivelly deselecting that option still send.. now that crap was removed finally**. that responds due you cited "whe internet slow down", **and again i was right!**

**Comment by daN4cat** [comment]
@mckaygerhard as usual you are misleading and casting wrong information and negativity. Please move on and shut your mouth.

**Comment by daN4cat** [comment]
@prince90617 inside bootstrap css there is a part loading fonts from Google font library.
That has an effect as another user reported.
With regards to statistics, if you disabled it AND you followed the license you don't have any issue from that side.
However if you are using 3.2.0 I would suggest to update to the latest version, which is stable and just few days far from be released. We are just waiting for language translations to be completed before we can release.
