### ISSUE TITLE
Logo vs Business Name in Receipt

### ISSUE THREAD

**Issue by petercstevenson** [jekkos/opensourcepos#925]
My logo includes my business name, which I think is pretty common. The current standard receipt template places the logo directly above the business name, which looks funny due to the duplication of the title. One solution could be to have an option of whether to include the business name in the receipt.

![mozilla](https://cloud.githubusercontent.com/assets/21316584/19577382/f9a20136-96cb-11e6-869b-0dabc30cc9fa.jpg)

**Comment by odiea** [comment]
~~~
If you don't mind editing both receipts you can use this option which is working for me. I just added an else clause that changes when the company name is used. 

<div id="receipt_header">
		<?php
		if ($this->Appconfig->get('company_logo') != '') 
        { 
        ?>
			<div id="company_name"><img id="image" src="<?php echo base_url('uploads/' . $this->Appconfig->get('company_logo')); ?>" alt="company_logo" /></div>			
		<?php
		}
		else 
		{
		?>
		<div id="company_name"><?php echo $this->config->item('company'); ?></div>
		<?php
		}
		?>
		<div id="company_address"><?php echo nl2br($this->config->item('address')); ?></div>
		<div id="company_phone"><?php echo $this->config->item('phone'); ?></div>
		<div id="sale_receipt"><?php echo $receipt_title; ?></div>
		<div id="sale_time"><?php echo $transaction_time ?></div>
	</div>

**Comment by odiea** [comment]
I see you are using docker so this might be an issue to update the receipts.

**Comment by jekkos** [comment]
You can copy this new template to the web container using `docker cp` command. I think it should just show up in the dropdown afterwards?

**Comment by jekkos** [comment]
If desired I can add an extra volume to allow for persistent custom receipts in docker

**Comment by petercstevenson** [comment]
@jekkos, I'm not sure what you meant about the copying the template to the web container, but I did edit the receipt file by hand and it now works. Presumably this will get lost next time I redeploy, though.

**Comment by daN4cat** [comment]
So there should be an option to do not print the company_name.
It has to be optional because logo could be a trading name and company name could be the legal one.
For instance that's my wife's business case, the shop has a name but the LTD is something else and the receipt has to contain the LTD name.

**Comment by daN4cat** [comment]
Done
