### ISSUE TITLE
#923 issue

### ISSUE THREAD

**Issue by 520521mayuan** [jekkos/opensourcepos#927]
### New Feature or Enhacement

For new Features or Enhacements please remove all the template text and clearly write your proposal.
It's important to state whether you expect the community to implement it or you will contribute the work.
Please bear in mind that we will implement new features only on the current code, there is no support for old versions.

### Issue, Question or Bug

Before submitting an issue please make sure you remove the first section of the template and you tick (add a x between the square brakets) and agree with all the following check boxes:

- [] Checked the current issues database and no similar issue was already discussed
- [] Read the README, WHATS_NEW and UPGRADE
- [] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php5-gd, php-intl and sockets installed)
- [] Reporting an issue of an unmodified OSPOS installation
- [] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [] PHP version is at least 5.5 and not 7.x
- [] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [] Know the name and version of OS, Web server and MySQL and will add to my issue report

IMPORTANT: If you remove the template when submitting an issue your issue will be closed.

### Steps to reproduce the issue

As #923 say

**Comment by jekkos** [comment]
Please don't create duplicate issues. 

We will not guarantee any delivery or ETA for a fix as all this work is done on a voluntary basis.

**Comment by daN4cat** [comment]
Especially because it's a setup issue not a software bug.....

**Comment by jekkos** [comment]
Yes that as well. Think we have invested more than enough time in making setup less painful through docker and I'm not motivated to keep answering questios about any other possible shared hosting configuration problem out there

**Comment by 520521mayuan** [comment]
I'm so sorry for creating the duplicate sites. It's because i think if the report is closed and the others could not see what i say.

**Comment by 520521mayuan** [comment]
I'm so sorry for creating the duplicate sites. It's because i think if the report is closed and the others could not see what i say.

**Comment by alvin101** [comment]
@520521mayuan Persons watching this project will get a copy of your post closed or not.  Persons that really watch a project know how to click the closed link near the top of the default issues page. And you can come back later and delete your posts to help clean up the issues section...

**Comment by 520521mayuan** [comment]
Got it. Thanks a lot.
