### ISSUE TITLE
SMS Issue..

### ISSUE THREAD

**Issue by jroske** [jekkos/opensourcepos#928]
I am attempting to setup with sms messaging. I am using bulksms.com for my provider. I have placed the following url in the sms_lib.php library:

$url = "http://usa.bulksms.com/eapi/submission/send_sms/2/2.0?username=$username&password=$password&msidn=$phone&message=$message";

I cannot get this to work. If I actually put my actual username and password along with the phone number I am sending the message to (msidn) with a short message, into the browser the message will come thru to the phone but not using the above command line in ospos even though ospos says the message was sent. Bulksms.com never sees the message and it does not arrive at the mobile phone. 

I then downloaded the updated master files. OSPOS quit functioning all together.. It gave me an error:
"An Error Was Encountered
Unable to load the requested language file: language/english/pagination_lang.php"

I'm not familiar with the coding structure and I have not programmed in over 30 years.
I can be contacted directly at joesmowerservice@gmail.com

Please HELP!!!

### Issue, Question or Bug

Before submitting an issue please make sure you remove the first section of the template and you tick (add a x between the square brakets) and agree with all the following check boxes:

- [X] Checked the current issues database and no similar issue was already discussed
- [X] Read the README, WHATS_NEW and UPGRADE
- [X] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php5-gd, php-intl and sockets installed)
- [X] Reporting an issue of an unmodified OSPOS installation
- [X] Started with 3.0 Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [X] PHP version is at least 5.5 and not 7.x
- [X] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report.. You are using Open Source Point Of Sale Version 3.0.0 - 4f5ad57
- [X] Know the name and version of OS, Web server and MySQL and will add to my issue report
        Windows10, WAMP Server, Apache 2.4.18, php 5.6.19, MySQL 5.7.11

IMPORTANT: If you remove the template when submitting an issue your issue will be closed.

### Steps to reproduce the issue

**Comment by daN4cat** [comment]
See #472 if can be of any help.

**Comment by daN4cat** [comment]
especially pay attention to `$message = rawurlencode($message);` point that needs to happen before the $url =

**Comment by RamkrishnaMondal** [comment]
Please check / save  'username' and 'password' for your Sms-api in 'message' tab under 'stores-config'.

**Comment by daN4cat** [comment]
@jroske any news?

**Comment by jroske** [comment]
I have tried all of the above. I have an engineer working on it for me. I run a business, have a 6ohr/wk job and three kids and a wife. Not much time to figure it out. I would also like to have a workorder module created for my shop.
