### ISSUE TITLE
how to tick Print after sale and Create Invoice by default

### ISSUE THREAD

**Issue by hendranata** [jekkos/opensourcepos#929]
### New Feature or Enhacement

For new Features or Enhacements please remove all the template text and clearly write your proposal.
It's important to state whether you expect the community to implement it or you will contribute the work.
Please bear in mind that we will implement new features only on the current code, there is no support for old versions.
### Issue, Question or Bug

Before submitting an issue please make sure you remove the first section of the template and you tick (add a x between the square brakets) and agree with all the following check boxes:
- [] Checked the current issues database and no similar issue was already discussed
- [] Read the README, WHATS_NEW and UPGRADE
- [] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php5-gd, php-intl and sockets installed)
- [] Reporting an issue of an unmodified OSPOS installation
- [] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [] PHP version is at least 5.5 and not 7.x
- [] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [] Know the name and version of OS, Web server and MySQL and will add to my issue report

IMPORTANT: If you remove the template when submitting an issue your issue will be closed.
### Steps to reproduce the issue

how to tick Print after sale and Create Invoice by default  when create a new sales?

**Comment by odiea** [comment]
For the invoice part you can go to application/libraries/sale_lib and comment out the last line.
~~~
public function clear_all()
	{		
		$this->clear_mode();
		$this->empty_cart();
		$this->clear_comment();
		$this->clear_email_receipt();
		$this->clear_invoice_number();
		$this->clear_giftcard_remainder();
		$this->empty_payments();
		$this->remove_customer();
		//$this->set_invoice_number_enabled(FALSE);
	}

**Comment by hendranata** [comment]
Ok will try later

**Comment by hendranata** [comment]
@odiea

It is not working

**Comment by odiea** [comment]
That line was added because we all got tired of unchecking the Invoice. I will check later and see what has changed. You may have to also comment out //$this->clear_invoice_number();

**Comment by hendranata** [comment]
@odiea 
here is mine:

public function clear_all()
        {
                $this->set_invoice_number_enabled(FALSE);
                $this->clear_mode();
                $this->empty_cart();
                $this->clear_comment();
                $this->clear_email_receipt();
                $this->clear_invoice_number();
                $this->clear_giftcard_remainder();
                $this->empty_payments();
                $this->remove_customer();
        }

the Create Invoice still not checked by default

**Comment by odiea** [comment]
You did not comment out $this->set_invoice_number_enabled(FALSE); Comment out means I looks like the following. It has // in front of it. Try that and see what happens.
//$this->set_invoice_number_enabled(FALSE);

**Comment by odiea** [comment]
Try that first before commenting out $this->clear_invoice_number();

**Comment by hendranata** [comment]
both are not working.

public function clear_all()
        {
                //$this->set_invoice_number_enabled(FALSE);
                $this->clear_mode();
                $this->empty_cart();
                $this->clear_comment();
                $this->clear_email_receipt();
                //$this->clear_invoice_number();
                $this->clear_giftcard_remainder();
                $this->empty_payments();
                $this->remove_customer();
        }


create invoice still unchecked

**Comment by hendranata** [comment]
anyway after try again and again it works. thanks
