### ISSUE TITLE
Filter sales summary by date and time

### ISSUE THREAD

**Issue by jlctmaster** [jekkos/opensourcepos#932]
### New Feature or Enhacement

For new Features or Enhacements please remove all the template text and clearly write your proposal.
It's important to state whether you expect the community to implement it or you will contribute the work.
Please bear in mind that we will implement new features only on the current code, there is no support for old versions.
### Issue, Question or Bug

Before submitting an issue please make sure you remove the first section of the template and you tick (add a x between the square brakets) and agree with all the following check boxes:
- [X] Checked the current issues database and no similar issue was already discussed
- [X] Read the README, WHATS_NEW and UPGRADE
- [X] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php5-gd, php-intl and sockets installed)
- [] Reporting an issue of an unmodified OSPOS installation
- [] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [X] PHP version is at least 5.5 and not 7.x
- [X] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [X] Know the name and version of OS, Web server and MySQL and will add to my issue report

IMPORTANT: If you remove the template when submitting an issue your issue will be closed.
### Installation information

SO Debian 8
PHP Version 5.6.24 
MySQL Version 5.5.52
OSPOS Version 3.0.0
### Expected behaviour

Expected records according to the filter selected date time display
### Actual behaviour

Only shows records date information regardless of time sent
### Steps to reproduce the issue

In the Object daterangepicker (file daterangepicker.php) enable the options to display the selection of time and send the format expected correctly to apply the changes, however, the results do not show the information according to filtering.

Boostrap-Table Records 

![captura de pantalla de 2016-10-22 19 23 08](https://cloud.githubusercontent.com/assets/2789271/19623164/1f63f3d0-988d-11e6-93f4-d4eb59586ef2.png)

Object DateRangePicker 

![captura de pantalla de 2016-10-22 19 26 10](https://cloud.githubusercontent.com/assets/2789271/19623168/700868a2-988d-11e6-85f1-de12bb226556.png)

Boostrap-Table Records After Filter 

![captura de pantalla de 2016-10-22 19 27 15](https://cloud.githubusercontent.com/assets/2789271/19623172/90cf01f4-988d-11e6-88d4-5358e39d1e7f.png)

Should show the register 1

That another file should be modified to take me the desired filter.
Thank you.

**Comment by daN4cat** [comment]
@jlctmaster is this something you changed and would like to contribute or else? Not sure I get what you are after.

**Comment by jlctmaster** [comment]
Hi @daN4cat. 

Yes, I improved the module to filter by date and time format, but only in 24-hour format, if possible I would like to contribute

**Comment by daN4cat** [comment]
Not sure this is really required and to get it to work properly you need to change few things in the model and temporary tables.
We decided in the past to just stick to day and Takings is the summary of the day view.

**Comment by jlctmaster** [comment]
The need arises because the software install in a nightclub and the closing cash must necessarily take into account the filter date and time as it begins its workday from 5:00 PM to 3:00 AM reports must be filtered in a range of 2 days, but in a specific time interval.

**Comment by daN4cat** [comment]
Got your point, maybe this should be a configurable feature.

If you have the change go for a Pull Request, but please make sure it's done against the latest master as I optimised few things in the temp table.
For your case you would also need to add a sale_time index as at the moment there is only sale_date.

**Comment by jlctmaster** [comment]
Ok, I will create a new branch and publish the changes there, so that you review your improvement and if you like, you publish it on the master branch

Greetings.

**Comment by jlctmaster** [comment]
Hello @daN4cat 

I have already improved the source to publish, if you can create a new branch that call feature/datetime_reports and give me access to post there, to upload the changes and you check, for merge with the master branch if you like.

Thank you.

**Comment by daN4cat** [comment]
You can go for a Pull Request, so we can review the code and merge if fine.

**Comment by daN4cat** [comment]
I set 3.1.0 as target as we leave 3.0.1 for just minor fixes and performance improvements.

**Comment by jlctmaster** [comment]
Hello @daN4cat 

I already made the pull request, please check it.

Greetings.

**Comment by daN4cat** [comment]
Sounds good, I'll have a look into it later. Thanks

**Comment by jlctmaster** [comment]
Hello,

In what they can review the last commit that realizes for this new feature.

Greetings.

**Comment by daN4cat** [comment]
@jlctmaster please rebase your PR with the latest master because Release 3.0.1 is now out.
I created a 3.0.2 release label but I will not touch master unless something is really required to issue a 3.0.2.
I prefer to go for a 3.1 with all the new PR in it.

**Comment by jlctmaster** [comment]
Ok I Will close the PR

**Comment by jlctmaster** [comment]
Hello, 

I have already generated a new pull request based on the latest changes applied to the master branch of the original project.

Please, check it.

**Comment by daN4cat** [comment]
@jlctmaster I'll have a look into this later.

**Comment by daN4cat** [comment]
@jlctmaster please read my comment in #1023. You need to take the latest master, test and fix as it doesn't look like working fine with me.
Also make sure you test with different date & time formats as I wouldn't that could be an issue.

**Comment by odiea** [comment]
Takings tables quit working for me.

**Comment by daN4cat** [comment]
Yep, there is a bug. Let me see...

**Comment by daN4cat** [comment]
Fixed and in master

**Comment by odiea** [comment]
Is there a db update that needs to be done? After I remove the checkmark all tables show properly.

**Comment by daN4cat** [comment]
Not strictly, if you check the box in Store Config it creates automatically the entry in the database.

BTW, I found other two errors and fixed. In the end it seems to work fine with date & time, but we probably need to test throughout.

**Comment by daN4cat** [comment]
Mhhh just spotted a funny one, the end time is always 23:59:58... why 58?

**Comment by odiea** [comment]
I also noticed that nothing shows when you use the default time. You have to change it to get the tables to show.

**Comment by odiea** [comment]
Also summary reports are not working again. Nothing shows on the screen. Must be an older version.

**Comment by daN4cat** [comment]
@odiea I tested and summary report is working for me. Try the latest master code please.

**Comment by odiea** [comment]
Tested and works fine after your commit.

**Comment by jlctmaster** [comment]
Hi, thanks for the support, let me review with the main branch the errors you have reported.

Greetings.

**Comment by odiea** [comment]
Here are the Date Time settings I am using.
![2017-01-30 15_46_07-wedidit _ powered by ospos 3 1 0](https://cloud.githubusercontent.com/assets/10962177/22445162/678cabe2-e703-11e6-9fa6-47b2f4dbf395.png)

**Comment by daN4cat** [comment]
@jlctmaster could you please look into this issue please?

**Comment by jlctmaster** [comment]
Hi, yes I can look at this problem, however, check the configuration and it has been working for me, I am trying to replicate the error case to examine why they reported that it does not work for them.

Greetings.

**Comment by daN4cat** [comment]
Thanks

**Comment by daN4cat** [comment]
@jlctmaster it looks like Takings doesn't show the transaction of the day. Can you please check that?

**Comment by jlctmaster** [comment]
Hello, I have already reviewed and corrected the reported error, also create a PR to upload the changes, please check it.

Greetings

**Comment by jlctmaster** [comment]
Hello @daN4cat, I made a new PR for the field translation. Please check it out.

**Comment by daN4cat** [comment]
The issue in Takings is fixed.

**Comment by daN4cat** [comment]
The issue in reports is fixed too.
