### ISSUE TITLE
Class 'NumberFormatter' not found ? php_intl is enabled

### ISSUE THREAD

**Issue by tanakornp** [jekkos/opensourcepos#934]
### Issue, Question or Bug

Before submitting an issue please make sure you remove the first section of the template and you tick (add a x between the square brakets) and agree with all the following check boxes:

- [x] Read the README, WHATS_NEW and UPGRADE
- [x] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php5-gd, php-intl and sockets installed)
- [x] Reporting an issue of an unmodified OSPOS installation
- [x] PHP version is at least 5.5 and not 7.x
- [x] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [x] Know the name and version of OS, Web server and MySQL and will add to my issue report

IMPORTANT: If you remove the template when submitting an issue your issue will be closed.

### Installation information
Windows 10 Pro
WAMP 2.5
APACHE 2.4.9
MYSQL 5.6.17
PHP 5.5.12
OSPOS 3.0.0

### Expected behaviour

I know that this problem was addressed in FAQ, however my php-intl extension is already loaded on WAMP. I have also double check in php.ini as well 
`[intl]
intl.default_locale = en
intl.error_level = E_WARNING

extension=php_gd2.dll
extension=php_gettext.dll
extension=php_gmp.dll
extension=php_intl.dll
extension=php_imap.dll`

Web should display normally

In same server, I have OSPOS 3.0.0 (release back in May/June) still works fine.

### Actual behaviour

Fatal error: Class 'NumberFormatter' not found 

### Steps to reproduce the issue

Any page that have currency sign. ( item/view and payment pane of sale/receiving)

**Comment by jekkos** [comment]
Please read FAQ. Install php-intl extension. Beside having it in your config file you also need the library to be physically present in your installation. There's enough resources on the net to help you out there

**Comment by daN4cat** [comment]
@tanakornp have you solved this issue?
It looks like WAMP has some issue with php_intl.dll as the same problem is reported in #949

**Comment by daN4cat** [comment]
Please also check this:

http://stackoverflow.com/questions/16372888/intl-extension-php-intl-dll-with-wamp
http://stackoverflow.com/questions/1451468/intl-extension-installing-php-intl-dll

It looks like there is something unusual with the path.

**Comment by nick9822** [comment]
This solved my issue in my case.
http://stackoverflow.com/a/16372984/4688775
This read as
```
I had the same problem a few days ago.

You have to copy all the files (all files starts with icu*):

icudt.dll
icudt46.dll
icuin.dll
icuin46.dll
icuio.dll
icuio46.dll
icule.dll
icule46.dll
iculx.dll
iculx46.dll
icutest.dll
icutest46.dll
icutu.dll
icutu46.dll
icuuc.dll
icuuc46.dll
From:

<wamp_installation_path>/bin/php/php5.4.3/
To:

<wamp_installation_path>/bin/apache/apache2.2.22/bin/
And you also need to enable intl in php.ini file (uncomment this line):

;extension=php_intl.dll
And restart the server. It should works fine.

Of course, you need to replace the folder names with your own.
```
