### ISSUE TITLE
The "Item Kits" function issue

### ISSUE THREAD

**Issue by 520521mayuan** [jekkos/opensourcepos#935]
### New Feature or Enhacement

For new Features or Enhacements please remove all the template text and clearly write your proposal.
It's important to state whether you expect the community to implement it or you will contribute the work.
Please bear in mind that we will implement new features only on the current code, there is no support for old versions.

### Issue, Question or Bug

Before submitting an issue please make sure you remove the first section of the template and you tick (add a x between the square brakets) and agree with all the following check boxes:

- [x] Checked the current issues database and no similar issue was already discussed
- [x] Read the README, WHATS_NEW and UPGRADE
- [x] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php5-gd, php-intl and sockets installed)
- [x] Reporting an issue of an unmodified OSPOS installation
- [] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [x] PHP version is at least 5.5 and not 7.x
- [x] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [x] Know the name and version of OS, Web server and MySQL and will add to my issue report

IMPORTANT: If you remove the template when submitting an issue your issue will be closed.

### Installation information

- os: Linux debian 4.6.0-1-amd64

- mysql: mysql Ver 14.14 Distrib 5.6.30

- apache: Apache2/2.4.23 (Debian)

- php: php 5.6.26-1 (cli)

- ospos: 3.0.0

### Expected behaviour

I can add the Cost Price and the Retail Price In Item Kits module.

### Actual behaviour

The Cost Price and the Retail Price can't edit in "New Item Kit".

### Steps to reproduce the issue

1. Click the "Item Kits" button.

2. Click the "New Item Kits" button.

3. Can't add "Cost Price and "Retail Price".

I'm frustrate that what the Item Kits function is? How to add the Cost Price and the Retail Price?

**Comment by 520521mayuan** [comment]
![1](https://cloud.githubusercontent.com/assets/7332357/19671203/aa9f728a-9a9f-11e6-91b4-1c04360d2971.png)

**Comment by odiea** [comment]
Item Kits has no real function except to add pre priced items to be sold with a single name.

**Comment by 520521mayuan** [comment]
Thanks a lot @odiea. Got it.
