### ISSUE TITLE
Using the opensourcepos only in localhost

### ISSUE THREAD

**Issue by 520521mayuan** [jekkos/opensourcepos#937]
### New Feature or Enhacement

For new Features or Enhacements please remove all the template text and clearly write your proposal.
It's important to state whether you expect the community to implement it or you will contribute the work.
Please bear in mind that we will implement new features only on the current code, there is no support for old versions.

### Issue, Question or Bug

Before submitting an issue please make sure you remove the first section of the template and you tick (add a x between the square brakets) and agree with all the following check boxes:

- [x] Checked the current issues database and no similar issue was already discussed
- [x] Read the README, WHATS_NEW and UPGRADE
- [x] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php5-gd, php-intl and sockets installed)
- [x] Reporting an issue of an unmodified OSPOS installation
- [] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [x] PHP version is at least 5.5 and not 7.x
- [x] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [x] Know the name and version of OS, Web server and MySQL and will add to my issue report

IMPORTANT: If you remove the template when submitting an issue your issue will be closed.

### Installation information

- os: Linux debian 4.6.0-1-amd64

- mysql: mysql Ver 14.14 Distrib 5.6.30

- apache: Apache2/2.4.23 (Debian)

- php: php 5.6.26-1 (cli)

- ospos: 3.0.0

### Expected behaviour

I can use the system normally if the host is not connected to internet.

### Actual behaviour

When I unplug the network cable, can't display the login page though waiting for long time.

![t](https://cloud.githubusercontent.com/assets/7332357/19716805/46797066-9b90-11e6-8efa-645059fcd44e.png)

### Steps to reproduce the issue

**Comment by daN4cat** [comment]
Have you changed something in the code?

**Comment by daN4cat** [comment]
Which theme are you using?

**Comment by 520521mayuan** [comment]
I not modify the code except the necessary config file.

 How to check out what the theme is using? It should be the default.

**Comment by 520521mayuan** [comment]
![test](https://cloud.githubusercontent.com/assets/7332357/19719548/088fbf32-9b9d-11e6-83b2-3fd108839ed3.png)

**Comment by 520521mayuan** [comment]
It's solved. 

Firstly, disable google-chrome extension: Proxy SwitchyOmega (in my case), perhaps the other extension should be turn off if you have the same issue.

secondly, comment out: opensourcepos/vendor/ins0/google-measurement-php-client/src/Racecore/GATracking/Client/Adapter/Socket.php line 32-36,68-72, seems like

```
32:  /*if (!socket_connect($connection, $endpoint['host'], $port)) {
33:            $errorcode = socket_last_error();
34:            $errormsg = socket_strerror($errorcode);
35:           throw new Exception\EndpointServerException('Analytics Host not reachable! Error: ' . 36: $errormsg);
36:        }
37: */

```

```
68:         /*if (!socket_write($this->connection, $header) || !socket_write($this->connection, 69: $payloadString)) {
69:             $errorcode = socket_last_error();
70:             $errormsg = socket_strerror($errorcode);
71:            throw new Exception\EndpointServerException('Server closed connection unexpectedly. 72: Error: ' . $errormsg);
73:         }
74: */

```
That's all.

**Comment by 520521mayuan** [comment]
Why cut the second items in my answer? Is something wrong?

**Comment by daN4cat** [comment]
Because that should not be the issue as it was fixed. You might be using something not from the latest master.

**Comment by daN4cat** [comment]
@520521mayuan please read my last comment in #965 and give a try without commenting out the code.
