### ISSUE TITLE
How do i create receipt in different language

### ISSUE THREAD

**Issue by AshishDL** [jekkos/opensourcepos#941]
Steps to reproduce the issue

How do i create receipt in different language

![image](https://cloud.githubusercontent.com/assets/22575454/19777121/67c2310e-9c94-11e6-8eb1-46cff31c44c1.png)

**Comment by daN4cat** [comment]
Store Config, Localisation tab and select a different language. All is adjusted accordingly.

**Comment by AshishDL** [comment]
ya i know but in that list don't have language which i want..so how can i do it.if i want to add other language?

**Comment by daN4cat** [comment]
What about reading the wiki? https://github.com/jekkos/opensourcepos/wiki/Adding-translations

Please make an effort and read the documentation before firing issues, I noticed that you easily post requests here instead of reading what's already available. This is the last one I reply of this kind.

**Comment by AshishDL** [comment]
Sorry for inconvenience..i will Work on it,,,
