### ISSUE TITLE
Sales enhancement

### ISSUE THREAD

**Issue by jacksz** [jekkos/opensourcepos#944]
### New Feature or Enhacement

sometimes selling services arise the need for taking an advance/deposit and when the work is done take the rest 
so i propose adding  "remaining" or "unpaid" field in sales so that it can pass this issue 

example to clarify things "when a customer comes and wants to buy and build a pc , i need a deposit first and then build and when am done i take the rest of the money and add it to that bill"

or adding paid and subtracting from item value (item value - paid amount= unpaid/remaining) and leave remaining/unpaid field automatic  

adding tags so you can track  unpaid invoices would be great but one step at a time

**Comment by daN4cat** [comment]
See #24

**Comment by jacksz** [comment]
@odiea did you implement this in your own version?

**Comment by odiea** [comment]
Yes I have.  I will transfer the register.php over to the new version and see if it works out of the box.

**Comment by odiea** [comment]
Currently as far as keeping track of payments I have been uploading the Invoices to a spreadsheet.

**Comment by jacksz** [comment]
nice , can i have a copy of that?

**Comment by odiea** [comment]
No it is not. I have changed it quite a bit since the one I have on my profile. I will attach a copy later this afternoon after I test it. Got to go to work now had to watch my grandsons American ft ball game.

**Comment by odiea** [comment]
@jacksz 
I think this will work. I am no programmer so it is pretty basic.
I have included @hovalle Proforma if you want to print estimates. After you hit complete the proforma receipt will show. You then can go back to register and either cancel the Proforma or suspend it.
Register.php and proforma.php go into application/views/sales.
Sales.php goes into application/controller/sales.
You should rename the original files if these do not work for you.
This is all in English. 
This works only after a Customer is selected and the Invoice box is checked. I moved the Invoice box into the customer window and also removed the print after sale check box. I figured if it was going to show on the screen I would just use that print instead.
Of course you will need to unzip it first. Hope this helps.
[ospos stuff.zip](https://github.com/jekkos/opensourcepos/files/560175/ospos.stuff.zip)

**Comment by odiea** [comment]
In application/models/Sale.php I added this line to the payment options above the giftcard clause.
$payments[$this->lang->line('sales_invoice')] = $this->lang->line('sales_invoice');
I then added a line in language/sales $lang["sales_invoice"] = "Invoice"; So Invoice appears in the payment dropdown.

**Comment by odiea** [comment]
So do not use this yet. I am having issues after adding the Invoice box into the customer window. I will work on it and resend the files.

**Comment by jacksz** [comment]
nice , thank you :+1:

**Comment by odiea** [comment]
I had some issues with the invoice where if you deleted a payment you would then have to start over. This new register fixes that problem and is more OSPOS like. There is less customer info also. If you want more then just copy it over to this one. You can also in sales returns credit a gift card but is has
 to have a value of .01 or higher. I did not want to break any giftcard programming.
[register.zip](https://github.com/jekkos/opensourcepos/files/563172/register.zip)

**Comment by odiea** [comment]
This version also has a glitch so if I were you I would revert back to the original. I am finding that if I click or double click in adding Items to the register the warning just shows and nothing works.

**Comment by jacksz** [comment]
@odiea sorry i was busy past 2 weeks  
hmm i like the idea of the performa maybe i can make it as uploading raw data to the db and have a search bar and view

**Comment by odiea** [comment]
I found what was causing my issues. If you want to try these your more than welcome to. It contains the register where Invoice now shows in Customer info on the register. The register and controller now have the proforma buttons if you kept the proforma receipt it should work for you.
[New ospos.zip](https://github.com/jekkos/opensourcepos/files/587282/New.ospos.zip)

**Comment by jacksz** [comment]
@odiea do you use unpaid for sales only? or you use it for suppliers too?

**Comment by odiea** [comment]
Currently just playing with Sales.

**Comment by jacksz** [comment]
i played around with payment option and did unpaid and substitute it with "cash" and changed cash with debit card

and now it can track "unpaid" 

![fd1](https://cloud.githubusercontent.com/assets/14059965/20524311/026f2cd0-b0cb-11e6-9064-ef29db5d1af7.png)

![fd2](https://cloud.githubusercontent.com/assets/14059965/20524321/0fd23a16-b0cb-11e6-8924-f321db407619.png)

**Comment by odiea** [comment]
Great idea for basic charges. Now if you change checks to paid  and edit it in takings when paid you can keep track of the unpaid.

**Comment by jacksz** [comment]
exactly and you can edit that transaction back to cash when paid and even can print again 

![s1](https://cloud.githubusercontent.com/assets/14059965/20549139/dd4dc630-b13a-11e6-8271-2dc8d7aba479.png)

![s2](https://cloud.githubusercontent.com/assets/14059965/20549138/dd4677b8-b13a-11e6-9555-6c03fd78490b.png)

**Comment by daN4cat** [comment]
Oh good, that function is becoming handy for other purposes too... glad it helps here.

**Comment by odiea** [comment]
application/models/sale.php line 642 public function get_payment_options($giftcard = TRUE)
should show the payment types. Then you will need to add it to sales language. Have fun.
