### ISSUE TITLE
No Items to Display after 2.3.4 to 3.0 update

### ISSUE THREAD

**Issue by gripitoy** [jekkos/opensourcepos#945]
- [x] Checked the current issues database and no similar issue was already discussed
- [x] Read the README, WHATS_NEW and UPGRADE
- [x] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php5-gd, php-intl and sockets installed)
- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [x] PHP version is at least 5.5 and not 7.x
- [x] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [x] Know the name and version of OS, Web server and MySQL and will add to my issue report

IMPORTANT: If you remove the template when submitting an issue your issue will be closed.

### Installation information
Running LAMP on a Raspberry Pi running Raspbian Jessie.
commit hash: 4f5ad57
Apache 2.4.10
MySQL 5.5.44
PHP 5

I've been using opensourcepos for sometime now since 2.2 versions. I updated the software with no problems up to 2.3.4. Current version in use is 2.3.4, ran the 2.3.4_to_2.4.sql then 2.4_to_3.0.sql, all went fine and no errors. Modified the database.php and config.php accordingly. I can login, make a sale, generate a report.

When I click on ITEMS, it show NO ITEMS TO DISPLAY and the search won't return any result. But on the sale module, all works fine, products shows up. When I clicked on NEW ITEM under the ITEMS module, an error appears at the top of the pop-up window. Something about”Undefined properpty: stdClass::$pic_id on line 192 and 193 on controllers/Items.php. Two red box appears with the same content on that page.

A fresh install however works just fine, so I know all the files I have are working fine.

### Steps to reproduce the issue
export database from a 2.3.4 install with quite enough transaction
create new database
import 2.3.4 database.sql
run 2.3.4_to_2.4 sql
run 2.4_to_3.0 sql
login to new 3.0 installation, add new item.

**Comment by daN4cat** [comment]
You need to move your old uploads to public/ subdir.
Try that and let us know if fixed the issue that we add to the installation notes / wiki / FAQ.

**Comment by gripitoy** [comment]
I don't have any pictures/avatar of any of my items.
When I click on Items link in the older version, it displays all of my available products in an alphabetical order, version 3.0 will just say NO ITEMS TO DISPLAY.

**Comment by daN4cat** [comment]
Sorry, mixup things this morning... a bit sleepy today :-(

OK, have you added items manually to your DB using things like phpMyAdmin?
Because if you did that you are missing history of your items with date and that might be a reason why you cannot see them.

**Comment by daN4cat** [comment]
Also, please make sure you use PHP5.5 at least, better 5.6 as 5.5 is deprecated now.

**Comment by gripitoy** [comment]
MAMP 4.0.6
PHP 5.6.27
MySQL 5.6.33
Apache 2.2.31
Hi, I've recreated the steps above using MAMP and it's behaving in the same way. Items are still not displayed and i'm getting the same error. I'm sure I have not added items manually but I might have edited some values way way back. 

Attached a screenshot of the error. Hope it helps.
![screen shot 2016-10-30 at 12 29 48 am](https://cloud.githubusercontent.com/assets/23132794/19831261/3f1efcc8-9e38-11e6-8253-530c22cf9b5b.png)

**Comment by daN4cat** [comment]
OK, that's something that went wrong during the database upgrade and it's not your mistake.

It looks like Items table is missing the pic_id column. This morning I read it like it couldn't find the picture pointed by the content of the pic_id field.

It's strange it looks like in 2.3.2 avatar feature was added and the column in Items table was called item_pic.
Somehow got changed of name but the database update script didn't reflect it. I got involved with 2.4 so no idea what happened in the past.

Anyway, run this from myPhpAdmin:

```
ALTER TABLE `ospos_items` 
  CHANGE COLUMN `item_pic` `pic_id` int(10) DEFAULT NULL;
```

and let me know if that fixed your issue.

**Comment by gripitoy** [comment]
That fixed it for me! Thank you very much!

**Comment by daN4cat** [comment]
OK, good. I probably need to go back in history and fix some database script....

**Comment by daN4cat** [comment]
And great that you spotted this! Many thanks.

**Comment by daN4cat** [comment]
I need to fix the database script.

You must have upgraded from something like 2.3.1 at least in the past.

**Comment by gripitoy** [comment]
Yes I have, i've been using this since july 2015.

**Comment by daN4cat** [comment]
Probably `2.3.1_to_2.3.2.sql` should have had:

```
-- add pic_id column to items table
ALTER TABLE `ospos_items` 
   ADD COLUMN `pic_id` int(10) DEFAULT NULL;
```

@jekkos do you remember something, because going back in history it looks like between 2.3.1 and 2.3.2 database.sql add the addition of pci_id field but the upgrade script was not correct.

**Comment by daN4cat** [comment]
To fix this issue properly I would need to change that upgrade script.

**Comment by daN4cat** [comment]
OK, I decided to change `2.3.2_to_2.3.3.sql` with the updated I suggested. It seems more sensible to me to do in that way.
