### ISSUE TITLE
Errors & Page Block Rules on Sales/Receiving/Store Config pages

### ISSUE THREAD

**Issue by Geekynik** [jekkos/opensourcepos#949]
Dear all,
I find it difficult to edit the above pages simply because certain page block rules have been enabled on them. Besides that I also run into errors on loading these pages.
Find attached files for details and please let's resolve this.

Thanks
![open source point of sale powered by ospos 3 0 0](https://cloud.githubusercontent.com/assets/20142197/19829432/a1e395f8-9dd9-11e6-860c-5298c48f9bae.png)
![ospos 3_0_0 - localhost_opensourcepos_public_config](https://cloud.githubusercontent.com/assets/20142197/19829434/afb863d4-9dd9-11e6-9916-c28ad3837ca9.png)
![ospos 3_0_0 - localhost_opensourcepos_public_receivings](https://cloud.githubusercontent.com/assets/20142197/19829435/afc302a8-9dd9-11e6-80c4-055a3dd25933.png)
![ospos 3_0_0 - localhost_opensourcepos_public_sales](https://cloud.githubusercontent.com/assets/20142197/19829436/afc66736-9dd9-11e6-9769-2f718044b487.png)

**Comment by daN4cat** [comment]
Read the FAQ first thing...

**Comment by Geekynik** [comment]
FAQ on which page please?

**Comment by daN4cat** [comment]
End of README file

**Comment by Geekynik** [comment]
The issues are with this particular error because I have ensured all socket
modules, php_bcmath, php5-gd, php-intl.dll extensions are all okay.
But what I now get is this date/timezone and NumberFormatter error below.





Severity: Warning

Message: date(): It is not safe to rely on the system's timezone settings.
You are *required* to use the date.timezone setting or the
date_default_timezone_set() function. In case you used any of those methods
and you are still getting this warning, you most likely misspelled the
timezone identifier. We selected the timezone 'UTC' for now, but please set
date.timezone to select your timezone.

Filename: libraries/Email.php

File: C:\Program Files
(x86)\Ampps\www\opensourcepos\application\libraries\Email_lib.php
Line: 11
Function: Libraries

Please kindly provide some help.
thanks.

**Comment by Geekynik** [comment]
File: C:\Program Files
(x86)\Ampps\www\opensourcepos\application\libraries\Email_lib.php
Line: 11
Function: library

File: C:\Program Files
(x86)\Ampps\www\opensourcepos\application\controllers\Sales.php
Line: 13
Function: library

File: C:\Program Files (x86)\Ampps\www\opensourcepos\public\index.php
Line: 315
Function: require_once

**Comment by daN4cat** [comment]
PHP version?

**Comment by Geekynik** [comment]
PHP version 5.6

**Comment by Geekynik** [comment]
PHP version 5.5

**Comment by daN4cat** [comment]
And are you using the latest master? The issue you are facing should be related to php-intl.dll.

**Comment by Geekynik** [comment]
And yes I'm using the latest master. How do I get the issue with
php-intl.dll solved?
Please assist.

Thanks

**Comment by daN4cat** [comment]
Rub phpinfo and make sure it's active.

**Comment by Geekynik** [comment]
Hi,

My good friend thanks for all the wonderful support okay. But it looks very
frustrating indeed having employed all the solutions you have kindly
proffered so far.
Yet nothing has changed...I mean the problem still persist.
Don't know what else to do now...Feeling frustrated...

**Comment by daN4cat** [comment]
Unfortunately I don't know how to help you more because I don't use Windows based installation.

In the FAQ we wrote about that issue: https://github.com/jekkos/opensourcepos#faq and as it says read this wiki and try some alternative setup:

https://github.com/jekkos/opensourcepos/wiki/Local-Deployment-using-MAMP-for-Windows
https://github.com/jekkos/opensourcepos/wiki/OSPOS-using-Xampp-(recommended-for-testing-or-local-use-only).

Many people that had problems under Windows sorted out the issue and wrote those help pages.

**Comment by daN4cat** [comment]
And here #934 there was a similar report but no feedback if it was solved. You may want to ask @tanakornp how they solved it...

**Comment by daN4cat** [comment]
Please also check this:

http://stackoverflow.com/questions/16372888/intl-extension-php-intl-dll-with-wamp
http://stackoverflow.com/questions/1451468/intl-extension-installing-php-intl-dll

It looks like there is something unusual with the path.

**Comment by tanakornp** [comment]
You'll need to copy some files from php directory to apache.
http://stackoverflow.com/a/18044239

**Comment by daN4cat** [comment]
Indeed, I found that comment now. Thanks for the help, I'll add this issue link in FAQ

**Comment by Geekynik** [comment]
Thing is I have both versions of the OSPOS application. 2.4.0 and 3.0.0
Version 2.4.0 works perfectly while the issues that I'm having has to do
with version 3.0.0


*Please is it possible for me to use the version 2.4.0 database to run
version 3.0.0?*

*Although I tried it but i got errors on the login page as shown in the
image file attached here.*

*Any solutions???*

**Comment by Geekynik** [comment]
I really love to use the latest version 3.0.0
Please assist

**Comment by daN4cat** [comment]
Please come to GitHib and read the comments because we gave you the solution.
We cannot support if you don't make an effort in reading what we write :-(

**Comment by tanakornp** [comment]
Database 2.4 > 3.0 => read FAQ.
NumberFormatter => move bunch of icu* files (check link above)

**Comment by Geekynik** [comment]
Alright

**Comment by Geekynik** [comment]
Hurray it has finally WORKED!!!!
I had to switch to XAMPP server and then reconfigure php.ini files...and
now everything works perfectly as I wanted it.
Thanks so much for the immense support...Like I said I want to donate some
token towards sustaining the project towards future upgrades.
Please send me the link to where I can make my donation.
God bless

*And one more thing please...
*Can this latest version 3.0.0 be deployed online and across mobile
devices?*
Thanks,
Nick

**Comment by onyema3** [comment]
https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=MUN6AEG7NY6H8

**Comment by daN4cat** [comment]
Glad it's all sorted and yes that's the link that you can find in the GitHub project front page too.

Hope it will fund next round of beers with @jekkos in Brussels.

Last week we had three each, to celebrate 3.0.0 release.
We need to be careful to do not increase the major version too much :-)

**Comment by Geekynik** [comment]
😇😀
Alright thanks. I will make sure the donation is able to fund the next
round of beers in Brussels...

**Comment by jekkos** [comment]
Ok actually some should go to dan4cat in this situation for sure as he helped you out? @daN4cat do you have a paypal account? You could add donate button of your own.

**Comment by onyema3** [comment]
yes @daN4cat <https://github.com/daN4cat> should add his donate button. He
has been a of great value to this project

**Comment by Geekynik** [comment]
Alright great people!
Will do as appropriate...
