### ISSUE TITLE
Unable to load the requested language file: language/en/form_validation_lang.php

### ISSUE THREAD

**Issue by RamkrishnaMondal** [jekkos/opensourcepos#954]
Just tried the latest master....

![screenshot from 2016-11-03 10 32 50](https://cloud.githubusercontent.com/assets/14151032/19956343/567730ee-a1b1-11e6-87ed-62cfd70a0639.png)

**Comment by RamkrishnaMondal** [comment]
This was due to old db used...... closing the issue.

**Comment by onyema3** [comment]
How did you migrate the old db to 3.0.1?

**Comment by onyema3** [comment]
My ospos 3.0.0 db is giving this error with 3.0.1

**Comment by daN4cat** [comment]
I don't see anything in your posting. Using emails doesn't always work with posting pictures

**Comment by kdkrun** [comment]
Dear RamKrishnaMondal,
I like your SMS feature and Template. I'm using your master files in my POS. How I upgrade to new release of ospos 2.4 without losing SMS feature and New Template of yours. Please advise.

**Comment by onyema3** [comment]
Sms is a standard feature of ospos now. So just use the new masters and
execute all the database update scripts and you're good to go

**Comment by daN4cat** [comment]
I suggest to take the latest master as it's stable and we are close to release 3.0.1.
There are major performance improvements with the way the software uses the database from 3.0.0.
There is no DB layout upgrade from 3.0.0 to 3.0.1 (at least at the moment none).

To upgrade from 2.4 to 3.0.0, as @onyema3 stated, you need to use the upgrade script database/2.4_to_3.0.sql. But I suggest to read UPGRADE.txt as first thing.
Also please pay attention to the following: `PHP needs to have php-gd, php-bcmath, php-intl and php-sockets installed and enabled.`

@onyema3 have you managed to use the latest 3.0.1?

**Comment by onyema3** [comment]
Not yet but in the next couple of days I'll surely try it out.

**Comment by daN4cat** [comment]
OK, let me know if you find the performance of searches better vs 3.0.0.

**Comment by onyema3** [comment]
Will surely do

**Comment by onyema3** [comment]
@daN4cat is there a difference between the database of 3.0.0 and 3.0.1?
With my old database it was throwing up errors but with a virgin database
everything is just fine.

**Comment by onyema3** [comment]
When i say old database i mean the 3.0.0 database

**Comment by daN4cat** [comment]
What error do you get?
There is no change to database between 3.0.0 and 3.0.1.

BTW, do you have a database that was upgraded through different versions?

**Comment by onyema3** [comment]
Yes, my database was upgraded from 2.3.2 to 3.0.0

**Comment by onyema3** [comment]
@login
![login](https://cloud.githubusercontent.com/assets/12876751/20069033/3775dc3c-a51b-11e6-9ad3-6c7df02f8340.jpg)
after login
![afterlogin](https://cloud.githubusercontent.com/assets/12876751/20069055/47ddd14c-a51b-11e6-98e7-51c61a83c3d0.jpg)

**Comment by daN4cat** [comment]
It looks like something was not updated of language changes.

Try running the following (or check that your database has those two value):

INSERT INTO `ospos_app_config` (`key`, `value`) VALUES
('language', 'english'),
('language_code', 'en');

**Comment by daN4cat** [comment]
Maybe it's better if you do a manual check.

**Comment by onyema3** [comment]
ok

**Comment by onyema3** [comment]
This is what i can see
![db](https://cloud.githubusercontent.com/assets/12876751/20070282/1a937926-a520-11e6-979a-65b88ab103d6.jpg)

and the query gave this error
![query](https://cloud.githubusercontent.com/assets/12876751/20070291/20332840-a520-11e6-83c4-72acd893351d.jpg)

**Comment by daN4cat** [comment]
OK, do this:

> DELETE FROM `ospos_app_config` WHERE `key` = 'language';

and run again

> INSERT INTO ospos_app_config (key, value) VALUES
> ('language', 'english'),
> ('language_code', 'en');

**Comment by onyema3** [comment]
The first statement error
![eror](https://cloud.githubusercontent.com/assets/12876751/20070655/8bcdbc2c-a521-11e6-8879-80201f59b16c.jpg)

**Comment by daN4cat** [comment]
Maybe the comment here is removing something... try with this again

```
DELETE FROM `ospos_app_config` WHERE `key` = 'language';

INSERT INTO `ospos_app_config` (`key`, `value`) VALUES
('language', 'english'),
('language_code', 'en');
```

**Comment by onyema3** [comment]
That was successful but now more errors followed by invalid username/password.
The errors below

A PHP Error was encountered

Severity: Notice

Message: Undefined property: stdClass::$hash_version

Filename: models/Employee.php

Line Number: 309

Backtrace:

File: /Applications/MAMP/htdocs/ospos3.0.1/application/models/Employee.php
Line: 309
Function: _error_handler

File: /Applications/MAMP/htdocs/ospos3.0.1/application/controllers/Login.php
Line: 61
Function: login

File: /Applications/MAMP/htdocs/ospos3.0.1/application/controllers/Login.php
Line: 21
Function: run

File: /Applications/MAMP/htdocs/ospos3.0.1/public/index.php
Line: 315
Function: require_once

A PHP Error was encountered

Severity: Notice

Message: Undefined property: stdClass::$hash_version

Filename: models/Employee.php

Line Number: 317

Backtrace:

File: /Applications/MAMP/htdocs/ospos3.0.1/application/models/Employee.php
Line: 317
Function: _error_handler

File: /Applications/MAMP/htdocs/ospos3.0.1/application/controllers/Login.php
Line: 61
Function: login

File: /Applications/MAMP/htdocs/ospos3.0.1/application/controllers/Login.php
Line: 21
Function: run

File: /Applications/MAMP/htdocs/ospos3.0.1/public/index.php
Line: 315
Function: require_once

**Comment by daN4cat** [comment]
It looks like you never properly upgraded to the official 3.0.0 release...

Run this:

```
ALTER TABLE `ospos_employees`
 ADD COLUMN `hash_version` int(1) NOT NULL DEFAULT '2';

UPDATE `ospos_employees` SET `hash_version` = 1;
```

**Comment by daN4cat** [comment]
But to be on the safe side you should rerun manually statement by statement all the 2.4_to_3.0.sql.

If one gives an error, move to the next as it's likely that it's fine.

**Comment by onyema3** [comment]
You are the man!! that did it.
So what's the correct upgrade path?

**Comment by daN4cat** [comment]
Well, you should have run 2.4_to_3.0.sql always.... as said make sure now to run one SQL statement at the time manually from that file so you are on the safe side.

**Comment by onyema3** [comment]
Ok.  thanks

**Comment by RamkrishnaMondal** [comment]
@onyema3  As daN4cat stated, you always need to run 2.4 to 3.0.sql script.

@kdkrun Just  backup your old "sms_lib.php" file and replace the default "sms_lib.php" in 3.01 installation with your old one...that's it.

**Comment by onyema3** [comment]
Thanks. We sorted it out yesterday

**Comment by kdkrun** [comment]
@daN4cat @RamkrishnaMondal So what About Template, Is that same as in Ram ospos Master
