### ISSUE TITLE
Design Tool

### ISSUE THREAD

**Issue by daN4cat** [jekkos/opensourcepos#955]
Due to the fact that we have now a design/ folder, I was wondering if we could agree on some design tool to use for things like UML diagrams.

I found this web based one https://www.draw.io/ interesting and I will give it a go.

@jekkos give a try and if you agree we can use it as tool to edit designs and add it to the wiki in a Arch & Design section.

**Comment by jekkos** [comment]
I had a quick look and it looks quite complete. Nice tool. Think we should try it at least. For ERD I wil stick to mysql workbench as it can autogenerate sql script.

**Comment by daN4cat** [comment]
Sure, ERD is not part of the picture.
That tools is for class diagrams, sequence diagrams and the like when we find the time....
