### ISSUE TITLE
[BUG] .htaccess and apache 2.4, can't install

### ISSUE THREAD

**Issue by i92guboj** [jekkos/opensourcepos#957]
### BUG

ospos wont' even install with apache 2.4 due to incorrect .htaccess clause. "Order" exists no longer.

### Issue / Question / Bug

- [x] Checked the current issues database and no similar issue was already discussed
- [x] Read the README, WHATS_NEW and UPGRADE
- [x] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php5-gd, php-intl and sockets installed)
- [x] Reporting an issue of an unmodified OSPOS installation
- [x] PHP version is at least 5.5 and not 7.x
- [x] MySQL version is 5.5 or 5.6 and not 5.7
- [x] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [x] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [x] Know the name and version of OS, Web server and MySQL and will add to my issue report

### Installation information

ospos version 3.0, git hash picked from plain text file opensourcepos/.git/packed-refs (know nothing about git, so please, forgive me if that's not the correct hash), I just cloned the repo on 2016/11/04
dd66496ccc3b0c5752900efbcf7a069a9f0f1790 refs/tags/3.0.0

OS is Gentoo amd64, it's up to date rolling release
web server is apache 2.4.23
mysql is 5.6.34

### Expected behaviour

Installation should start when I open the public folder in my browser.

### Actual behaviour

Instead, after creating the db and setting up the database.php file, when I go into the public directory in my vhost, it gives me error 500. In the apache log I can read this:

[Fri Nov 04 08:39:28.828335 2016] [core:alert] [pid 11536:tid 139907175524096] [client 127.0.0.1:48754] /home/i92guboj/www/ospos/opensourcepos/.htaccess: Invalid command 'Order', perhaps misspelled or defined by a module not included in the server configuration

This is the typical error you get when migrating an already running web site to apache 2.4.

I tried to manually tweak a couple htaccess files, but that didn't work, I don't know if there's something else...

### Steps to reproduce the issue

git clone the repo
create ospos db in mysql with utf8-bin collation
rename and configure database.php
setup vhost if you haven't already
go to vhost/public
see error 500

### Note: I am surprised no one else reported this, maybe there's something basic I am not seeing here...

Thanks!

**Comment by daN4cat** [comment]
I doubt it has something to do with Apache 2.4 because I run OSPOS on Apache 2.4 and it works fine.

**Comment by daN4cat** [comment]
See here: https://httpd.apache.org/docs/trunk/upgrading.html

```
Access control
In 2.2, access control based on client hostname, IP address, and other characteristics of client requests was done using the directives Order, Allow, Deny, and Satisfy.

In 2.4, such access control is done in the same way as other authorization checks, using the new module mod_authz_host. The old access control idioms should be replaced by the new authentication mechanisms, although for compatibility with old configurations, the new module mod_access_compat is provided.
```

Make sure your Apache has `mod_access_compat` included.

**Comment by i92guboj** [comment]
I have to respectfully disagree. It for sure has to do with 2.4. I've seen this dozens of times and I've migrated quite a few sites.

Yes, I know I can enable access_compat, but I'd rather update .htaccess if possible. I will try to iron out the .htaccess file(s) myself. But I think ospos should really provide alternative configurations for 2.4 since access_compat is being phased out, and mention this issue in the README file(s). I am completely sure I am not the only one having this issue. There are lots of access_compat-less installs of apache 2.4 out there, specially taking into account that mixing the new syntax with the old one provided by this module is not a cakewalk. One less module in my server also means one less target for attackers to enjoy.

Thanks for all the insight :)

http://httpd.apache.org/docs/2.4/mod/mod_access_compat.html

**Comment by jekkos** [comment]
@i92guboj Thanks for the thorough explanation. Would you mind to send us a PR once you have upgraded the .htaccess files? I wasn't aware of this mod being deprecated.

**Comment by daN4cat** [comment]
Agree, please send over a change and that will solve the problem.
So far nobody complained about this issue and I'm sure many use 2.4.
But better to be up to date that backward compatible, I agree.

**Comment by i92guboj** [comment]
Sure. When/if I fix it I will submit a diff if that's ok for you, so you can review the changes. I'll take a bit though, since I've hit another showstopper and I have to recompile php as well to add support for bcmath, which ospos also needs it seems.

**Comment by daN4cat** [comment]
Please read the FAQ for what PHP requires so you avoid try & errors.

Please check also the .htaccess in the / as of course the one in /public (used as web root).
I tried to find a way to automatically forward from / to /public but the Rewrite rules I tried didn't work.
I'm not a big expert of .htaccess so if somebody can solve that I would be glad!

**Comment by i92guboj** [comment]
I am no expert in this myself. In which regards web servers, I just go walking around whatever I find in my way, so I can't be of little help with that. It's just coincidence that I've been hitting similar issues these last few months, so I had that one fresh.

I'll try to take a look though.

As for the FAQ, you are right, however all the things about php are scattered around that's why I missed that one. It would be nice if a single line summed up that we need php with intl, sockets and bcmath enabled, besides explaining what particular problem will arise from missing each one of them. But that's just how my brain works, not a big issue, since the info is there as you noted, so if anyone hits the same issue s/he should be able to solve by reading a bit deeper as I did. :)

For now, I enabled the access mod, just to get it working first. Once I know php and apache are ready to go, I'll disable it again and starting hacking the htaccess files. 

Thanks for all the assistance!

**Comment by daN4cat** [comment]
Fair point, I've updated the README.md: https://github.com/jekkos/opensourcepos#server-requirements

**Comment by daN4cat** [comment]
@i92guboj how is it going with MySQL5.7 support?

**Comment by daN4cat** [comment]
@i92guboj how is it going with the .htaccess change for Apache 2.4?

**Comment by i92guboj** [comment]
[ospos-htaccess-2.2_to_2.4.diff.txt](https://github.com/jekkos/opensourcepos/files/574706/ospos-htaccess-2.2_to_2.4.diff.txt)

**Comment by i92guboj** [comment]
With this, I was able to open and use ospos while having access_compat disabled, haven't tested thoroughly, but I think it's close enough. I have left the old stuff commented out and added some notes to clarify a couple of things.

I think that you could make this the default, and add a second .htaccess_apache-2.2_and_below file, maybe that would be easier for people to understand, don't know...

**Comment by daN4cat** [comment]
Thanks for that but I don't know which file you patched because none of them are from latest master.

**Comment by daN4cat** [comment]
Anyway I understand that the change is all about commenting out:

```
#  Order allow,deny
#  Deny from all
#  Satisfy all
```

and replace them with

`Require all denied`

**Comment by daN4cat** [comment]
With regards to `Satisfy All`, here you can find the indication: http://stackoverflow.com/questions/5081747/htaccess-order-allow-deny-deny-from-all-confused

By the way, if the `Require all denied` is the change here I will do by myself.

**Comment by i92guboj** [comment]
Yes. I think it is simple enough. However I would recommend cheching the security implications with someone who actually knows what s/he's doing ;)

Thanks for the link and for all the assistance!

**Comment by daN4cat** [comment]
OK, made the change and committed to master.
The way I structured it supports Apache 2.2 and Apache 2.4 automatically.

@i92guboj please give a try before I close this.

**Comment by i92guboj** [comment]
This works for me, with and without access_compat enabled. So, I think this can be safely closed. Thanks for the quick solution!
