### ISSUE TITLE
data not insert into database from view

### ISSUE THREAD

**Issue by AshishDL** [jekkos/opensourcepos#960]
###  Enhacement

![submit button](https://cloud.githubusercontent.com/assets/22575454/20033182/3fee2424-a3c1-11e6-9475-85286cc84ad1.png)

Steps to reproduce the issue
When i click on submit button data would not store into database..i debug that code..it call to directly body tag..?.Please help me for above issue

**Comment by daN4cat** [comment]
Not sure I get, what's that feature?
