### ISSUE TITLE
Receipt Issues in Takings

### ISSUE THREAD

**Issue by odiea** [jekkos/opensourcepos#966]
### Issue / Question / Bug

Before submitting an issue please make sure you remove the first section of the template and you tick (add a x between the square brakets) and agree with all the following check boxes:

- [x] Checked the current issues database and no similar issue was already discussed
- [x] Read the README, WHATS_NEW and UPGRADE
- [x] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php5-gd, php-intl and sockets installed)
- [x] Reporting an issue of an unmodified OSPOS installation
- [x] PHP version is at least 5.5 and not 7.x
- [x] MySQL version is 5.5 or 5.6 and not 5.7
- [x] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [x] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [x] Know the name and version of OS, Web server and MySQL and will add to my issue report

### Installation information
Current version

### Expected behaviour
Make a sale from Register finish and complete Sale . Receipt stays in same window. Go to Takings reprint a Sale . A new window or tab should not be created for receipt.

### Actual behaviour
Go to Takings reprint a Sale . A new window or tab is created allowing for new windows or tabs every time a receipt is reprinted.

### Steps to reproduce the issue

**Comment by daN4cat** [comment]
Yes, I made this change.
I thought it would have been nicer to open the receipt in a new window such you don't lose the Takings listing.

Is this a bad User Experience?

**Comment by odiea** [comment]
It appears that if you do not close the new window you can end up with 30 or 40 windows if you keep using the takings to view previous receipts.

**Comment by onyema3** [comment]
@odiea i see what you mean

**Comment by daN4cat** [comment]
OK, I'll revert that change.

**Comment by jekkos** [comment]
Wasn't this feature there for a long time already? I think it was kind of useful as the takings screen can be very slow to load

**Comment by odiea** [comment]
If you both like this then can you make it a Store config for receipt.

**Comment by daN4cat** [comment]
I added the other day because I was tired to go back and set again the date range to more than a day.

But maybe I can indeed make it configurable, or maybe not. Don't know.

**Comment by odiea** [comment]
I still have the issue of having to reset the date in takings using this feature.

**Comment by daN4cat** [comment]
Maybe the receipt should open in a pop up window leaving the Takings view open in the background?

**Comment by jekkos** [comment]
Popup can be problematic as its blocked by most browsers..

**Comment by jekkos** [comment]
I would vote to stay with the tabs :+1:

**Comment by daN4cat** [comment]
So two votes to leave the feature as it is, @odiea to remove and @onyema3 what's your vote?
This is the election week... with surprises.

**Comment by onyema3** [comment]
i'm with @odiea

**Comment by odiea** [comment]
The other option would be to use a different way to call the receipt and just have a close button on it or when called from takings the buttons act like the items 'readonly' buttons.

**Comment by daN4cat** [comment]
Change reverted, see latest code in master.
