### ISSUE TITLE
Employee on receipt based on who is logged in? (ASK)

### ISSUE THREAD

**Issue by rnld26** [jekkos/opensourcepos#967]
### Installation information
OS X El Capitan
PHP 5
Web server Apache 
MySQL 5.6

### Expected behaviour
- First employee do sale
- Second employee logged in and check sale on sale->taking and view a receipt that first employee created.
- The employee name on the receipt should be the First Employee

### Actual behaviour
- The employee name on the receipt is second employee that logged in

### Steps to reproduce the issue
- Create a sale
- Log out
- Log in with different employee
- Go to Sale->Taking
- Check the name of employee on the receipt that another employee made..

![screen shot 2016-11-12 at 22 52 29](https://cloud.githubusercontent.com/assets/22451842/20220573/a99e968a-a860-11e6-92f1-86b85cd0f8de.png)

![screen shot 2016-11-12 at 22 50 12](https://cloud.githubusercontent.com/assets/22451842/20220520/6ad34982-a860-11e6-9186-55c8dbb0773a.png)

Code of earlier version

![screen shot 2016-11-12 at 22 53 11](https://cloud.githubusercontent.com/assets/22451842/20220603/c81467c0-a860-11e6-8553-a91f470ad503.png)
----------------------------
So i add some change

Sale_lib
![screen shot 2016-11-12 at 23 15 46](https://cloud.githubusercontent.com/assets/22451842/20221465/0b38e820-a864-11e6-9c1e-61e2fbc7c5a1.png)

Sales controller : _load_sale_data
![screen shot 2016-11-12 at 23 16 19](https://cloud.githubusercontent.com/assets/22451842/20221485/1e10c954-a864-11e6-8dfa-f6657dc855b1.png)

Sale model
![screen shot 2016-11-12 at 23 16 42](https://cloud.githubusercontent.com/assets/22451842/20221494/27d656fc-a864-11e6-902f-ca20223061ac.png)

**Comment by daN4cat** [comment]
Thanks for this report, can you please make a change and submit a Pull Request so we merge this?

**Comment by odiea** [comment]
What am I doing wrong? With these changes all I get is a blank employee on the receipt. 

~~~
I placed this in Sale_lib

public function get_employee()
	{
		if(!$this->CI->session->userdata('employee_id'))
		{
			$this->set_employee(-1);
		}
		
		return $this->CI->session->userdata('employee_id');
	}
		
		public function set_employee($employee_id)
		{
			$this->CI->session->set_userdata('employee_id', $employee_id);
		}
	
I place the following in Controller _load_sale_data

		$employee_info = $this->Employee->get_info($this->sale_lib->get_employee());

I placed this in Sale model

public function get_employee($sale_id)
	{
		$this->db->from('sales');
		$this->db->where('sale_id', $sale_id);
		return $this->Employee->get_info($this->db->get()->row()->employee_id);
	}
~~~

**Comment by rnld26** [comment]
yes sorry i forgot you also need to add this at Sale_lib : copy_entire_sale 
![screen shot 2016-11-13 at 12 15 23](https://cloud.githubusercontent.com/assets/22451842/20235845/4e0f3808-a8d1-11e6-9484-954ee534360c.png)

**Comment by rnld26** [comment]
@daN4cat yes i can, thanks

**Comment by daN4cat** [comment]
Good good

**Comment by odiea** [comment]
That did it. Thanks for the contribution.

**Comment by daN4cat** [comment]
OK, given that was tested and I had a bit of time I fixed this.
It's now in master.

Thanks for the issue report and fix contribution.

**Comment by odiea** [comment]
@daN4cat I know you committed this but should @rnld26 get his name in the contributors hall of fame?

**Comment by daN4cat** [comment]
If they give me the line I'll add it to COPYING file

**Comment by rnld26** [comment]
I'm sorry, i have tried to put it at pull requerst, but I'm confused how to put it there.. @daN4cat @odiea can help?

**Comment by rnld26** [comment]
Oo it's on master already thanks @daN4cat

**Comment by rnld26** [comment]
@daN4cat is it possible to add more field at sales_items_temp temporary table?
i've tried but it wont show up. 
it's fine at earlier version POS.

example 
- Sale model
![screen shot 2016-11-17 at 23 00 56](https://cloud.githubusercontent.com/assets/22451842/20396648/6fbe0ba4-ad19-11e6-997d-73809f82463c.png)

I tried to add unit_price field from items table 

- Specific_employee model
![screen shot 2016-11-17 at 23 09 01](https://cloud.githubusercontent.com/assets/22451842/20396807/0eb055e6-ad1a-11e6-914a-4080010048e3.png)

- Reports controller
![screen shot 2016-11-17 at 23 09 22](https://cloud.githubusercontent.com/assets/22451842/20396870/328e5300-ad1a-11e6-8b14-cae48ab01bb9.png)

- Result at Specific Employee Reports
![screen shot 2016-11-17 at 23 14 55](https://cloud.githubusercontent.com/assets/22451842/20397065/e3fc10dc-ad1a-11e6-9047-61aa28157570.png)

Can you help? what am i doing wrong? @daN4cat @odiea @jekkos

**Comment by daN4cat** [comment]
Add the new field in getDataColumns() too otherwise how do you expect to be shown if there is no description?

**Comment by rnld26** [comment]
@daN4cat may I put down my full name at license in addition to the existing name now?

**Comment by daN4cat** [comment]
Sure please do

**Comment by rnld26** [comment]
thanks
