### ISSUE TITLE
wrong dialog title for item import

### ISSUE THREAD

**Issue by TayZaN** [jekkos/opensourcepos#969]
### Issue / Question / Bug

Before submitting an issue please make sure you remove the first section of the template and you tick (add a x between the square brakets) and agree with all the following check boxes:

- [] Checked the current issues database and no similar issue was already discussed
- [] Read the README, WHATS_NEW and UPGRADE
- [] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php5-gd, php-intl and sockets installed)
- [] Reporting an issue of an unmodified OSPOS installation
- [] PHP version is at least 5.5 and not 7.x
- [] MySQL version is 5.5 or 5.6 and not 5.7
- [] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [] Know the name and version of OS, Web server and MySQL and will add to my issue report

### Expected behaviour
Item >> Excel Import >> dialog title should be "Import **items** from Excel sheet"

### Actual behaviour
It showing "Import **customers** from Excel sheet"

### Steps to reproduce the issue
Item >> Excel Import >> Check Dialog Title
I am not familiar with github , I manually update myself as the following, please ignore or delete my submitting if already reported, I search but cannot find and just submit. 

item > manage.php > line 62
`title='<?php echo $this->lang->line('customers_import_items_excel'); ?>'>`
to
` title='<?php echo $this->lang->line('items_import_items_excel'); ?>'>`

**Comment by daN4cat** [comment]
Thanks for the report

**Comment by daN4cat** [comment]
@TayZaN I just checked and this was fixed long time ago. I'm afraid you are not using the latest code.

**Comment by TayZaN** [comment]
I c, below link is latest code for item page ? 
https://github.com/jekkos/opensourcepos/blob/master/application/views/items/manage.php

**Comment by odiea** [comment]
I see the tool tip on Items excel button currently says Import customers instead of Import Items. You are correct.

**Comment by daN4cat** [comment]
Apologies, I completely missed this one. Fixing....

**Comment by daN4cat** [comment]
Fixed
