### ISSUE TITLE
sales "takings"

### ISSUE THREAD

**Issue by jacksz** [jekkos/opensourcepos#973]
### Issue / Question / Bug

Before submitting an issue please make sure you remove the first section of the template and you tick (add a x between the square brakets) and agree with all the following check boxes:

- [x] Checked the current issues database and no similar issue was already discussed
- [x] Read the README, WHATS_NEW and UPGRADE
- [x] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php5-gd, php-intl and sockets installed)
- [x] Reporting an issue of an unmodified OSPOS installation
- [x] PHP version is at least 5.5 and not 7.x
- [x] MySQL version is 5.5 or 5.6 and not 5.7
- [x] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [x] Know the name and version of OS, Web server and MySQL and will add to my issue report

### Installation information
master installation github
php 5.6
mysql 5.0.11

### Expected behaviour
4 names referenced by language and not different name in each language 

### Actual behaviour
![capture](https://cloud.githubusercontent.com/assets/14059965/20287160/f2f4b652-aadb-11e6-9897-b7a6247709cd.JPG)

![cap](https://cloud.githubusercontent.com/assets/14059965/20287165/f88ffaae-aadb-11e6-8f78-5594ed247142.png)

### Steps to reproduce the issue
choose these steps in two different languages
1-make a sale 
2- go to sales "takings"
you will find "cash" and equivalent name in other languages  will be treated as different things in "takings"

**Comment by odiea** [comment]
Have you checked the different languages that you tested with to see if they are properly translated? I tried with es and saw no issues. I believe takings also uses public function get_payment_options($giftcard = TRUE) as it should.

**Comment by jacksz** [comment]
hmm es? you mean Spanish right? 
this is the path public/sales/manage

![3w](https://cloud.githubusercontent.com/assets/14059965/20292211/cf546c4e-aafc-11e6-8a6a-a3a35e334901.JPG)

![2q](https://cloud.githubusercontent.com/assets/14059965/20292252/315e4770-aafd-11e6-8064-13ec14eccc12.png)

**Comment by odiea** [comment]
Here is what I am showing from the current master switching between 2 languages. 
![2016-11-15 05_58_54-new notification](https://cloud.githubusercontent.com/assets/10962177/20306709/04c32d1a-aaf9-11e6-9282-384146196053.png)

**Comment by daN4cat** [comment]
Yes, it stores the string in the selected language.
There is no support for language switching, it was not part of the original design for this feature.

**Comment by daN4cat** [comment]
See #978
