### ISSUE TITLE
Handling different environments.

### ISSUE THREAD

**Issue by deepshah** [jekkos/opensourcepos#974]
### New Feature / Enhacement

What is the best way to manage environment specific variables? Code Igniter suggests this- https://www.codeigniter.com/user_guide/libraries/config.html#environments.
But it requires setting the environment (development/production) in the .htaccess file which is under version control. Is there a way round this? I am thinking of implementing phpdotenv (https://github.com/vlucas/phpdotenv).

**Comment by daN4cat** [comment]
phpdotenv looks an interesting idea. Maybe you can work on that addition and contribute to the project?

**Comment by daN4cat** [comment]
But that support needs to be added using composer so it's added to the vendor directory

**Comment by jekkos** [comment]
Indeed dotenv  is quite easy to use and allows one to customize environment variables while keeping them out of vcs

**Comment by daN4cat** [comment]
@jekkos maybe you can just pull the composer stuff and commit for later use?
That will easy the contribution.

**Comment by deepshah** [comment]
I'll look into it

**Comment by jekkos** [comment]
@deepshah what settings do you exactly to configure as env variable?

**Comment by deepshah** [comment]
These are the ones I suggest:

ENVIRONMENT: production/testing/development

'db_log_enabled' => (ENVIRONMENT !== 'production')
'encryption_key'

Database:
'hostname'
'username'
'password'
'database'
'db_debug' => (ENVIRONMENT !== 'production')

**Comment by jekkos** [comment]
Ok makes sense to use dotenv for that. You can easily install the dependency using composer. Just hit 

```
curl -s http://getcomposer.org/installer | php
php composer.phar require vlucas/phpdotenv
```

**Comment by jekkos** [comment]
The database config file will be similar as it is in docker now. There the credentials are filled in using getenv() function. Think we should update the setup instructions to take this into account. In this case users will need to add the dotenv file with their production password in that case.

**Comment by jekkos** [comment]
@deepshah  You can send PR for this once finished would be much appreciated!

**Comment by deepshah** [comment]
Can you explain this- "The database config file will be similar as it is in docker now. " I have not used Docker yet, so did not understand it.

**Comment by jekkos** [comment]
@deepshah I mean that for docker I have done a modification in the database.php that fetches username, password and database name fro the environment.

Now we can instead just use the dotenv configuration files instead and remove the database.php template. This one will be left unmodified.

**Comment by deepshah** [comment]
I have made the changes:
https://github.com/jekkos/opensourcepos/pull/979

**Comment by daN4cat** [comment]
@deepshah please rebase your PR with the latest master because Release 3.0.1 is now out.
I created a 3.0.2 release label but I will not touch master unless something is really required to issue a 3.0.2.
I prefer to go for a 3.1 with all the new PR in it.

**Comment by deepshah** [comment]
Rebased it

**Comment by daN4cat** [comment]
@deepshah can you please change this support as discussed in #979 ?
We cannot make this part of the production code so it will stay as config.php.env and .env file for the people that want to use it for development & testing purposes.
The encryption key can be left as you implemented in your config.php.env as that will not be overridden by the code (it detects it's already assigned and skips).
