### ISSUE TITLE
Suppliers Module New Field Adding 

### ISSUE THREAD

**Issue by ishtiaquesarwar** [jekkos/opensourcepos#977]
Hi 
I want to add suppliers few information like below 

Suppliers Total bill amount 
Paid Amount 
Due Amount 
Payment date 
Note 

How to do this? 

Thanks in advance

**Comment by jekkos** [comment]
Adapt search query in Supplier to add the fields you need. In table_helper you need to add those fields to both the table body and header. It should show automatically in the module after that.
