### ISSUE TITLE
Auto-create invoices

### ISSUE THREAD

**Issue by ogalfano** [jekkos/opensourcepos#980]
### New Feature / Enhacement

Hello,

Thanks for making this possible, I want to start using OSPOS with my store but testing it I see there is no option to auto-create invoices, so I have to do the check mark every time I do a sale. Also, it would we good if there is an option to do an autoincrement on the invoice number, just like the sales receipt.
I wish I could help you doing that but I barely know what php is. I guess supporting you trough paypal will be the best.

Thanks, 
Oscar

**Comment by jekkos** [comment]
Invoice autoincrement should be in place. I guess a tooltip or some sort could help there. 
Also search the issues to enable invoice auto check. There's an easy solution posted by @odiea not so long ago. Just add one line of code in sale_lib if I'm not mistaken.

**Comment by jekkos** [comment]
There's different variables for invoice increment, search the issues for $CO and $SCO

**Comment by odiea** [comment]
In sale_lib I think just comment out set invoice did the trick. You may have to log out then login back in and try a few invoices.
public function clear_all()
	{
		$this->set_invoice_number_enabled(FALSE);
		$this->clear_mode();
		$this->clear_table();
		$this->empty_cart();
		$this->clear_comment();
		$this->clear_email_receipt();
		$this->clear_invoice_number();
		$this->clear_giftcard_remainder();
		$this->empty_payments();
		$this->remove_customer();
	}

**Comment by ogalfano** [comment]
@odiea thanks for your help, after trying a lot finally make it happen. 

Now just another question. Is there any way to change the starting invoice number? My store used to have hand preprinted invoices so I'd like to keep the number secuence? I tryed changing invoice_number on PhpMyAdmin in a first empty invoice but didnt work

Thank you

**Comment by odiea** [comment]
Currently Invoice numbers are created by the number of invoices in the database + 1. You can use custom Invoice numbers but they have to be manually entered.

**Comment by odiea** [comment]
You can try to entice Jekkos with a bounty to set it as a seed value instead of a count.

**Comment by jekkos** [comment]
Adding a feature like that shouldn't be too hard I guess. But as I don't need it myself it's not a priority currently.

**Comment by odiea** [comment]
If you decide to use this built in function never ever delete a sale with an invoice. It will mess up the Invoice count so you will get duplicate invoice number errors.

**Comment by kaslak** [comment]
@ogalfano could you post your solution (Auto-create invoices)? Would be helpful

**Comment by SteveIreland** [comment]
I didn't realize that the invoice number was based on the number of records in the file.  If that's still the case then would anyone have a problem with my including a change as part of the item kit fix?

**Comment by odiea** [comment]
There have been a few requests for this. Maybe you can help it out.

**Comment by daN4cat** [comment]
@SteveIreland feel free to improve but as separate step after MySQL5.7, PHP7 and Item_kits. Please check with @jekkos and @odiea what they think about this. Personally I don't use invoices, and if I remember right I even made it optional from Store Config.

**Comment by SteveIreland** [comment]
@daN4cat A good chunk of this is resolved in the quote-invoice branch, so I'm a bit confused as to why this shouldn't be closed.  If there is still a small piece missing I'm happy to slip it in before 3.1 is released.

**Comment by daN4cat** [comment]
@SteveIreland probably a mistake from my side during some tidy up time.

**Comment by daN4cat** [comment]
@SteveIreland can this be closed now?

**Comment by SteveIreland** [comment]
Yes, this should be closed.  If @ogalfano finds that it's not working as needed then I'll be happy to revisit this under a new issue.

**Comment by daN4cat** [comment]
Closed but @ogalfano et al please test.

@odiea will not be our lead tester for a couple of months as he's enjoying some time off in an isolated corner of this world. Lucky him...

**Comment by SteveIreland** [comment]
No @odiea?!?!  Not good ... not good at all.   Okay I think I understand.  Since he seems to be awake at all hours of the day then he must need to hibernate for two months so that he can stay awake for 10.

**Comment by daN4cat** [comment]
Indeed I always wondered how come that living in Colorado he could write at normal EU/UK times...
