### ISSUE TITLE
Translation mistake

### ISSUE THREAD

**Issue by ogalfano** [jekkos/opensourcepos#981]
### New Feature / Enhacement

Hello,

Again me. I have to use OSPOS in Spanish (i'm based in Latin America) and it looks like that there is a small mistake in the spanish translation. 

When printing out an invoice, in spanish it says "Tarjeta de Credito" but the right translation could be "Factura de Venta" or just "Factura".

If you need any help translating to Spanish, I could help you

![image](https://cloud.githubusercontent.com/assets/23526851/20408373/33c893b6-ace3-11e6-8474-37e472dfdbf1.png)

Thanks, 
Oscar

**Comment by jekkos** [comment]
@ogalfano You can correct that one yourself in our code by signing in on our Weblate instance. Just create yourself an account, look for the string you want to fix and submit it. 

It will be merged in the code afterwards

**Comment by jekkos** [comment]
Check the  wiki for further instructions on weblate.
