### ISSUE TITLE
Barcode not Scanning

### ISSUE THREAD

**Issue by ishtiaquesarwar** [jekkos/opensourcepos#982]
Hi

I took print of barcodes stored in items and when i attempted to scan them its not working but the scanner can scan all other barcodes generated. The Scanner is a brand new Honeywell MS5145 LS USB, it can detect other bar codes but it cannot detect the barcodes i have taken print and not appearing in system sales register.

How to get it done so that once i scan on any barcode of my system the sales register would detect that

thanks
ishtiaque

**Comment by rnld26** [comment]
Depending on the paper and printer you use, if you use plain paper, printer ink typically will spread, so difficult to read with a barcode scanner. And use barcode printers surely help

**Comment by ishtiaquesarwar** [comment]
But when barcode are scanned it works with system? 
I took print on sticker paper, it looks good as a printed barcode 
but my system cannot detect this barcode but that scanner can scan other barcode (not generated from my system)

thanks

**Comment by daN4cat** [comment]
I'm afraid it has little to do with OSPOS as the produced barcodes are standard and they were tested.
You can even take a mobile phone bar code scanner application, use your camera and you will see that the barcode format is recognised.
Probably you need to set your bar code scanner to recognise the format you selected, whether it's Code 39 or Code 128. Not sure as you are not giving us too many details about the barcode format you use.

**Comment by ishtiaquesarwar** [comment]
I have used EAN 8 and selected bar code content Item ID/Name

thanks

A.M.Ishtiaque Sarwar
Managing Director
*Soft Tech Innovation Ltd*

*Consultant:*
NARRI Consortium (8 International NGO's)
Azadi Technologies, Chittagong.
Sagarika Samaj Unnayan Sangstha,

*Business Concerns*: *MUTHOFUN <http://www.muthofun.com/> |  aamarPay
<https://www.aamarpay.com/> | eBiponon <http://www.ebiponon.com/>* |

*C*: 880-1711-272324 | 880-1611-272324
*E*: ceo@softbd.com | info@softbd.com
*W*: www.softbd.com | www.softbd.net

*Skype*: softbd | *GTalk*: ishtiaque.sarwar | *Linked In*: ishtiaquesarwar
<https://bd.linkedin.com/in/ishtiaquesarwar>

DISCLAIMER: This email (including any attachments) is intended only for use
by the named addressee(s) and may contain private, confidential and/or
privileged material. Any reliance, dissemination, distribution, review,
copy or other use of this email by person(s) who are not the intended
recipient is prohibited. If you have received this email in error, please
notify the sender immediately by email and permanently delete the email and
any copies (including print-outs). E-mail transmission cannot be guaranteed
to be secure or error-free as information could be intercepted, corrupted,
lost, destroyed, arrive late or incomplete, or contain viruses. The sender
therefore does not accept liability for any errors or omissions in the
contents of this message, which arise as a result of e-mail transmission.

**Comment by daN4cat** [comment]
EAN8 is not that common and a short format.
Make sure you test the scanner with some EAN8 sample that you may find on the Internet googling around.
Also as said use a mobile phone app to scan barcodes and see if they work.
