### ISSUE TITLE
(Question) how to add more field at sales_items_temp table and display it at specific employee report?

### ISSUE THREAD

**Issue by rnld26** [jekkos/opensourcepos#983]
### Installation information
OS X El Capitan
PHP 5
Web server Apache
MySQL 5.6

is it possible to add more field at sales_items_temp temporary table?
i've tried but did not show up. 
it's fine at earlier version POS.

example 
I have added one field at items table named 'commission'
![screen shot 2016-11-18 at 18 34 56](https://cloud.githubusercontent.com/assets/22451842/20428715/1d494380-adbd-11e6-9261-4fd2f735da12.png)

![screen shot 2016-11-18 at 18 50 30](https://cloud.githubusercontent.com/assets/22451842/20429121/3db3965a-adbf-11e6-8264-f2e45c612d30.png)

- Sale model (public function create_temp_table())
![screen shot 2016-11-18 at 18 37 56](https://cloud.githubusercontent.com/assets/22451842/20428866/0f14a15a-adbe-11e6-9fdf-6bb93805100c.png)

I tried to add commission field from items table 

- Specific_employee model (public function getData(array $inputs))
![screen shot 2016-11-18 at 18 39 49](https://cloud.githubusercontent.com/assets/22451842/20428869/1373f3f4-adbe-11e6-9c79-f7d8f86202aa.png)

- Reports controller (public function specific_employee($start_date, $end_date, $employee_id, $sale_type)
![screen shot 2016-11-18 at 18 41 25](https://cloud.githubusercontent.com/assets/22451842/20428902/396cbc26-adbe-11e6-9539-2d69cd22caef.png)

- Result at Specific Employee Reports
![screen shot 2016-11-18 at 18 46 59](https://cloud.githubusercontent.com/assets/22451842/20428974/93f1f33c-adbe-11e6-85d5-346595c22d11.png)

Commision Field at report is empty..

Can you help? what am i doing wrong?

**Comment by jekkos** [comment]
Try $row instead of $drow or something? Looks like the second query you're refering to does not carry all the fields you are displaying. I think you'll need to add the commission field in the correct one.

**Comment by daN4cat** [comment]
@rnld26 check in `Controller/Reports.php` this function: `public function get_detailed_sales_row($sale_id)`

Since you removed comment to have commission it would make sense to do a search in all files for that keyword and see where it is used....

**Comment by daN4cat** [comment]
BTW, commission on the answer = 10% :-)

**Comment by rnld26** [comment]
ok thanks @jekkos

**Comment by rnld26** [comment]
i used wrong array actually haha thanks @jekkos @daN4cat

**Comment by rnld26** [comment]
One more question, how to migrate database from 2.3.3 to 3.0.0?

**Comment by onyema3** [comment]
Run the database upgrade scripts

**Comment by rnld26** [comment]
Yes i know, but i dont know which script should be run first?

**Comment by onyema3** [comment]
Run from the version you are upgrading  from

**Comment by daN4cat** [comment]
Yes, you need to do all the steps in sequence from 2.3.3 to 3.0.0:

- 2.3.4_to_2.4.sql
- 2.4_to_3.0.sql
