### ISSUE TITLE
Item not showing in the items page after populating the ospos_items table using phpmyadmin

### ISSUE THREAD

**Issue by jnverma** [jekkos/opensourcepos#984]
Before submitting an issue please make sure you tick (add a x between the square brakets) and agree all the following check boxes:

- [x] Checked the current issues database and no similar issue was already discussed
- [x] Read the README, WHATS_NEW and UPGRADE
- [x] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas
- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [x] PHP version is at least 5.5 and not 7.x
- [x] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [x] Know the name and version of OS, Web server and MySQL and will add to my issue report

IMPORTANT: If you remove the template when submitting an issue your issue will be closed.

### Installation information
localhost
PHP 5.6
MySQL 5.7
Apache 2.4

**Comment by jekkos** [comment]
You should use the import functionality for that. You will need entries in ospos_item_quantities and ospos_inventory as well. Importing directly into the db isn't a supported usecase unless you know what you are doing.

**Comment by daN4cat** [comment]
Well, you should not have used the phpMyAdmin to populate the table and in general is never a good idea unless you go for a full import/upgrade script.

The fact is that you have items that have no history in inventory tables, so there is no date to filter the range.

**Comment by daN4cat** [comment]
OK, same time posting....

**Comment by odiea** [comment]
MySQL 5.7. same issues I faced using MySQL 5.7.

**Comment by daN4cat** [comment]
Ha, goooood one. Missed that.

No MySQL5.7. yes see #630

**Comment by jnverma** [comment]
Thank you for your support
