### ISSUE TITLE
Item Import Template Issue

### ISSUE THREAD

**Issue by jnverma** [jekkos/opensourcepos#985]
Before submitting an issue please make sure you tick (add a x between the square brakets) and agree all the following check boxes:

- [x] Checked the current issues database and no similar issue was already discussed
- [x] Read the README, WHATS_NEW and UPGRADE
- [x] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas
- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [x] PHP version is at least 5.5 and not 7.x
- [x] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [x] Know the name and version of OS, Web server and MySQL and will add to my issue report

IMPORTANT: If you remove the template when submitting an issue your issue will be closed.

### Installation information
localhost
PHP 5.6
MySQL 5.7
Apache 2.4

### Steps to reproduce the issue

**Comment by jnverma** [comment]
I tried to import items csv using the import template but its showing an error and not updating the items list
![error](https://cloud.githubusercontent.com/assets/22275104/20453574/e387ecbc-ae4f-11e6-94b4-10f89551d94e.jpg)
![csv](https://cloud.githubusercontent.com/assets/22275104/20453587/40101400-ae50-11e6-8c1d-37c4c216630d.jpg)

**Comment by daN4cat** [comment]
The UPC / bar code column in the spreadsheet is not right. That needs to be the correct varicose number.

**Comment by daN4cat** [comment]
@jnverma could please avoid attaching github.txt file and copy and paste it straight in your first question/comment?

I did already twice for you but that's the last time.

**Comment by jnverma** [comment]
Thanks for your support... but all the barcode numbers in the excel file are real and unique, they are 13 digit EAN numbers starting from 890 and i have checked it on other versions of MySQL but same error

**Comment by daN4cat** [comment]
OK, but what you shown in the picture doesn't look correct.
Have you opened the csv file with a simple text editor and checked what value is set? Stuff like E+12 is not right.

Also if you attach your test file here I can use and see what's wrong, that surely will help.

**Comment by odiea** [comment]
I recall there were also import issues if the same item name was used but that may have been corrected by now..

**Comment by daN4cat** [comment]
I need that file to understand exactly what the problem is without speculating too much with hypothetical scenarios.

**Comment by jnverma** [comment]
[List of Products - Import Template.zip](https://github.com/jekkos/opensourcepos/files/601467/List.of.Products.-.Import.Template.zip)

please help me...

**Comment by daN4cat** [comment]
I don't have straight away, but have you tried to replace the y with a 1? I guess you mean to set the boolean but it's 0 or 1 usually.
Give a try and let me know otherwise you need to wait for a bit as I'm busy doing something else.

**Comment by jnverma** [comment]
I did it , replaced y to 1 but still same error, i am waiting until you have some time for this

**Comment by daN4cat** [comment]
I took your file and imported in my installation and it's fine, no errors.

So that means that you have those items already in your database and import fails because it cannot duplicate the Barcodes.

I believe the best for you would be to start again from scratch with a new database and import the items.

**Comment by jnverma** [comment]
Can you provide me the details of your server installation so that i could make the same changes to my localhost like the mysql version or php version

**Comment by jnverma** [comment]
is it okay to use WAMP 2.5 with apache 2.4, MySQL 5.6, PHP 5.5 ?

**Comment by daN4cat** [comment]
I use a VPS, and remote and based on linux.

@odiea can help you with Windows based installations as he's more familiar.
But please read the documentation in the wiki as there are already existing suggestions: https://github.com/jekkos/opensourcepos/wiki

**Comment by roby1thecoder** [comment]
hello , I'm getting  same  error am using ospos 3.3.2. and also tested on ospos 3.3.3
First the  file format of the csv when i download  i don't see the column for quantity.
I tried  to  follow the manual but  does not show  exactly how  to  go about the quantity  column position. please I will appreaciate any help.Thanks
[import_items (35).xlsx](https://github.com/opensourcepos/opensourcepos/files/6122356/import_items.35.xlsx)

**Comment by roby1thecoder** [comment]
I understood the problem and fixed, I didn't understand the new template and the values have  to in and restriction of the data  format and type, the manual given online is old probably is  for ospos v3.0 and below, the new one 3.3.2 and 3.3.3 the database has changed . I had to go through the Items controller and understand  what data are passed in and how are handled, the errors happens and data restriction  and the whole process to  figure out how it works. I think new manual should be updated incase someone runs into the same problem due to wrong input or format. The next feature  i think expiry date  notification  and damaged product control and report will be good.
Thanks all.

**Comment by jgbalam8402** [comment]
hello , I'm getting same error am using ospos 3.3.2. and also tested on ospos 3.3.3
First the file format of the csv template when I download from the import link , i don't see the column for quantity.
I tried to follow the manual but does not show exactly how to go about the quantity column position. please I will appreaciate any help.Thanks

**Comment by azizssh** [comment]
I am using openpos with XAMPP stack on Windows 10 and here is the template I used to import .csv files into the POS:

**Mandatory Headers*:** 
- Item Name (must value)
- Description (optional value)
- Category (must value)
- Cost Price (optional value)
- Unit Price (must value)
- Reorder Level (optional value)
- HSN (optional value)

*** Those headers must be present in csv. Optional value means you can leave it empty if you don't have it. The order it appears in the csv doesn't matter.**

_Optional Headers:_ 
- Barcode (can have empty or duplicate values if you checked 'Allow duplicate barcodes' in your settings)
- Supplier ID, Allow Alt Description, Item Has Serial Number, item_image - not tested by me, I assume the values are optional for these headers

I used Excel for making the csv

The way I found out about the right csv structure was by looking into htdocs/application/controllers/items.php, there's a function called do_csv_import() . You can look into its implementation to get better idea how importing is done.

I'm also attaching a csv file which has only required fields, you can extend if you want, don't remove it however.
[import_items.csv](https://github.com/opensourcepos/opensourcepos/files/6719054/import_items.csv)

**Comment by daN4cat** [comment]
When you click import you get a link from the pop up dialog box to a template csv file you can use.
No need to reinvent the wheel.

**Comment by azizssh** [comment]
> No need to reinvent the wheel.

Agree here. My comment was made to let people know what is the bare minimum info needed to successfully import a csv.

**Comment by daN4cat** [comment]
Sounds good, thanks for the contribution and sorry for my straight comment.

**Comment by bubblesqueak24** [comment]
Upload does not allow zero's, you have to put a price and a value for everything
