### ISSUE TITLE
Show custom field in sales register

### ISSUE THREAD

**Issue by Eddper** [jekkos/opensourcepos#987]
### Question

Hello there. Could you help me with this? I need show the custom field 1 of  products in the "register sales module". Thank you I use the 2.4 version.

**Comment by daN4cat** [comment]
2.4 is old, use 3.0.1

**Comment by Eddper** [comment]
Thanks for reply. I will try, but I have problems to run the last version on my server. That's the reason I am using the 2.4 version, Just want show a custom field at sales register like description product.

**Comment by jekkos** [comment]
@Eddper This is something that will be tackled in 3.1. Will announce when it's testable for the community. We might want to ask for some community funding to cover some expenses we have for the project.

**Comment by jekkos** [comment]
see also #68

**Comment by Eddper** [comment]
Thank you jekkos for reply.
