### ISSUE TITLE
Items are not shown in the list

### ISSUE THREAD

**Issue by christod1980** [jekkos/opensourcepos#988]
### IMPORTANT IMPORTANT IMPORTANT

Chose what you want to report: New Feature or Bug.
If you remove the template when submitting a Bug your issue will be closed as we cannot help without basic information.

### New Feature / Enhacement

For New Features or Enhacements please remove all the template text and clearly write your proposal.
It's important to state whether you expect the community to implement it or you will contribute the work.
Please bear in mind that we will implement new features only on the current code, there is no support for old versions.

### Issue / Question / Bug

Before submitting an issue please make sure you remove the first section of the template and you tick (add a x between the square brakets) and agree with all the following check boxes:

- [] Checked the current issues database and no similar issue was already discussed
- [] Read the README, WHATS_NEW and UPGRADE
- [] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php5-gd, php-intl and sockets installed)
- [x] Reporting an issue of an unmodified OSPOS installation
- [x] PHP version is at least 5.5 and not 7.x
- [x] MySQL version is 5.5 or 5.6 and not 5.7
- [] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [x] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [x] Know the name and version of OS, Web server and MySQL and will add to my issue report

### Installation information
Open Source Point Of Sale Version 3.0.0 - 4f5ad5
WampServer Version 3.0.6 64bit
Apache 2.4.23
PHP version 5.6.25
MySQL 5.7.14
OSPOS language: English

### Expected behaviour
Under Items tab, After inserting an "Item" to the db this should be shown in the "Items" list

### Actual behaviour
Under the "Items" tab, the added items are not shown, while the items are stored in the ospos database items table

### Steps to reproduce the issue
1.Under "Items" tab, add new item by pressing the button "New Item"
2.After filling the required information and pressing the "Submit" button, the item is saved in the database under ospos_items table, but the insterted item is not shown in the Items list
![gui](https://cloud.githubusercontent.com/assets/12895044/20457925/c4c22646-aea7-11e6-84c1-0029432812f5.PNG)
![db](https://cloud.githubusercontent.com/assets/12895044/20457927/c890861e-aea7-11e6-9486-b50298fc9210.PNG)

**Comment by daN4cat** [comment]
The check list in the issue template is there for a reason.
If people ignore it misses that MySQL5.7 is not supported yet.... and we are tired to repeat it!
See #630

**Comment by christod1980** [comment]
Hi,
I have tested it with MySQL Version 	5.5.52-cll on a hosting place, but again the items don't show.
Please advice

Thanks,

Christodoulos

**Comment by christod1980** [comment]
Hi,

I have tested it with MySQL Version 	5.5.52-cll and again the Item list does not show.
Please advice.

Thanks,

Chris

**Comment by christod1980** [comment]
Hi, 
I also tested in my hosting with the following specifications that meet the requirements and again the item list does not show:
Apache Version 	2.4.23
PHP Version 	5.6
MySQL Version 	5.5.52-cll

With the above configuration, when i press the "New Item" the form is empty, and again all the already imported items do not show in the list

I am attaching the related screenshot
![capture](https://cloud.githubusercontent.com/assets/12895044/20462602/3c959046-af33-11e6-8cc5-9a9be416f73a.PNG)

Please advice

Chris

**Comment by daN4cat** [comment]
Have you read the rest of the installation requirement?
Do you have all the php extentions?
