### ISSUE TITLE
Vertical Navigation of Modules

### ISSUE THREAD

**Issue by bill-goldberg** [jekkos/opensourcepos#990]
### IMPORTANT IMPORTANT IMPORTANT

Chose what you want to report: New Feature or Bug.
If you remove the template when submitting a Bug your issue will be closed as we cannot help without basic information.

### New Feature / Enhacement

For New Features or Enhacements please remove all the template text and clearly write your proposal.
It's important to state whether you expect the community to implement it or you will contribute the work.
Please bear in mind that we will implement new features only on the current code, there is no support for old versions.

### Issue / Question / Bug

Before submitting an issue please make sure you remove the first section of the template and you tick (add a x between the square brakets) and agree with all the following check boxes:

- [x] Checked the current issues database and no similar issue was already discussed
- [x] Read the README, WHATS_NEW and UPGRADE
- [x] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php5-gd, php-intl and sockets installed)
- [x] Reporting an issue of an unmodified OSPOS installation
- [x] PHP version is at least 5.5 and not 7.x
- [x] MySQL version is 5.5 or 5.6 and not 5.7
- [x] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [x] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [x] Know the name and version of OS, Web server and MySQL and will add to my issue report

### Installation information
WAMP 2.5 localhost
PHP 5.5
MySQL 5.6
Apache 2.4

### Steps to reproduce the issue

**Comment by bill-goldberg** [comment]
What should i do to make the modules list vertically aligned ?

**Comment by daN4cat** [comment]
We use Bootstrap 3 based Bootswatch themes: https://github.com/thomaspark/bootswatch

Check there how to change the orientation of the navigation bar.

**Comment by daN4cat** [comment]
See https://github.com/thomaspark/bootswatch/issues/599

**Comment by rjiansevilla** [comment]
Where I can edit the navigation? like changing the flat icons? thanks

**Comment by daN4cat** [comment]
@rjiansevilla public/images/menubar

**Comment by cmthai** [comment]
![Untitled2](https://user-images.githubusercontent.com/119729029/207033970-5316370a-0ed9-4361-9e71-b989cf432189.jpg)
![Untitled](https://user-images.githubusercontent.com/119729029/207033977-b26e2f70-a82a-431e-877f-1a92f7d0a9bb.jpg)
