### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by acericonia** [jekkos/opensourcepos#992]
Hey,

First I fresh install the v3.0.0 and went I login I'm not redirected to the home but login and the page is empty, I have to write manually domain.com/home to access the home page.

Second : I can access the configuration page to setup my pos. the page is blocked and went I check I have ERROR 500. I already saw the other report of this error. but I don't find how to fixe it and they just redirect me to other numbers issues.

Env.

windows 10
xampp with php 5.6.24
![ospos](https://cloud.githubusercontent.com/assets/10333576/20463926/d538a31a-af3d-11e6-8f2d-c41873527d12.png)

localhost.

Thanks for your attention.

**Comment by daN4cat** [comment]
Check the README and FAQ, make sure all the php extensions are installed and working.

**Comment by acericonia** [comment]
Thanks for your answers but I check all extensions and works good. I download again and I will turn you back if I see the same bug.

Best regard,
Sawers

**Comment by daN4cat** [comment]
So is this still a problem?
Many people with Windows have constant issue with php extensions because they don't restart the webserver or not configure php correctly.

**Comment by acericonia** [comment]
Thanks for your point of view, but I know what I'doing and restart the webserver is the first thinks to do and I done multiple time.
