### ISSUE TITLE
change currency symbol location and sales quantity

### ISSUE THREAD

**Issue by hotline007** [jekkos/opensourcepos#993]
hi 
when I change the language to Arabic . currency symbol shows in the right side of the number
how can i put it in the left side ?

and the second thing how can i enable change item quantity in sale register ?

<a href='https://postimg.org/image/j74klubt5/' target='_blank'><img src='https://s12.postimg.org/j74klubt5/Capture.png' border='0' alt='postimage'/></a>

**Comment by daN4cat** [comment]
Check the configuration in Store Config, Locale tab.

**Comment by hotline007** [comment]
i Checked the configuration but still can't change the currency symbol location to the left side

**Comment by daN4cat** [comment]
Please switch to English and see if you can reproduce the issue.

Also please fill in the issue report template as the info you are giving are too vague.

**Comment by hotline007** [comment]
@daN4cat this is the standard item info with English localisation 

<a href="https://postimg.org/image/yjkose14r/" target="_blank"><img src="https://s17.postimg.org/yjkose14r/1.png" alt="1"/></a>

after changing the language into Arabic the currency symbol goes to the right side 

<a href="https://postimg.org/image/uohapthyz/" target="_blank"><img src="https://s17.postimg.org/uohapthyz/2.png" alt="2"/></a>

it should still in the left like $ and i checked  localisation tab and found no option to make it left

**Comment by daN4cat** [comment]
Is it going the opposite because it expects to be written right to left?

**Comment by hotline007** [comment]
yes it's going to opposite because of the rtl

**Comment by odiea** [comment]
It appears that the choice of left or right went missing.
![2016-11-21 06_48_24-wedidit _ powered by ospos 3 0 1](https://cloud.githubusercontent.com/assets/10962177/20484919/b2476520-afb6-11e6-8c91-6bbef537f5ec.png)

**Comment by daN4cat** [comment]
So you need to solve the RTL problem. Something was already discussed in another issue see #798 .
We cannot work on everything, so you either work on that and contribute to the project or you find somebody to do for you.

**Comment by daN4cat** [comment]
@odiea is locale based now. No need for that.

**Comment by odiea** [comment]
That's what I thought too.
