### ISSUE TITLE
SMS Sending Problem

### ISSUE THREAD

**Issue by ishtiaquesarwar** [jekkos/opensourcepos#995]
Hello
I have tried to setup SMS config for my system as per given config. I have setup API username, password and sender id (numeric sender id)

changed the URL parameters from application/libraries/Sms.php to below one

**$url = "http://clients.muthofun.com:8901/esmsgw/sendsms.jsp?username=$username&password=$password&dst=$phone&msg=$message&dr=1&unicode=1&clientsmsid=10001&groupname=&senderid=$originator&scheduletime=0";**

But actual API URL parameter suggested by gateway provider is as below:

**$send_url="http://clients.muthofun.com:8901/esmsgw/sendsms.jsp?user=xxxx&password=xxxx&mobiles=0000000&sms=test&unicode=1&clientsmsid=10001&groupname=&senderid=01844016400&scheduletime=0";**

It is showing message sent but none of them are sent actually. Can you please guide / suggest how to make it workable.

Regards
Ishtiaque

**Comment by daN4cat** [comment]
Not sure what the question is, but maybe you should set in Sms.php the following:

`$url = "http://clients.muthofun.com:8901/esmsgw/sendsms.jsp?user=$username&password=$password&mobiles=$phone&sms=$message&unicode=1&clientsmsid=10001&groupname=&senderid=$originator&scheduletime=0";`

BTW I suggest to ask your gateway provider to use https connection not http. If they support https change it in your URL above.

**Comment by ishtiaquesarwar** [comment]
The question was i have set the parameters as per instructions but still
it's not working but shows sms sent

**Comment by daN4cat** [comment]
The examples you gave didn't match. So try the one I gave you and let me know.

Also try the same with a web browser without the $ variables using some precoded stuff and see what happens.

I cannot work out all the specific things by each gateway provider, it's not possible.

**Comment by ishtiaquesarwar** [comment]
Yes FrancescoUk the url you have suggested worked finally

thanks you :)

A.M.Ishtiaque Sarwar
Managing Director
*Soft Tech Innovation Ltd*

*Consultant:*
NARRI Consortium (8 International NGO's)
Azadi Technologies, Chittagong.
Sagarika Samaj Unnayan Sangstha,

*Business Concerns*: *MUTHOFUN <http://www.muthofun.com/> |  aamarPay
<https://www.aamarpay.com/> | eBiponon <http://www.ebiponon.com/>* |

*C*: 880-1711-272324 | 880-1611-272324
*E*: ceo@softbd.com | info@softbd.com
*W*: www.softbd.com | www.softbd.net

*Skype*: softbd | *GTalk*: ishtiaque.sarwar | *Linked In*: ishtiaquesarwar
<https://bd.linkedin.com/in/ishtiaquesarwar>

DISCLAIMER: This email (including any attachments) is intended only for use
by the named addressee(s) and may contain private, confidential and/or
privileged material. Any reliance, dissemination, distribution, review,
copy or other use of this email by person(s) who are not the intended
recipient is prohibited. If you have received this email in error, please
notify the sender immediately by email and permanently delete the email and
any copies (including print-outs). E-mail transmission cannot be guaranteed
to be secure or error-free as information could be intercepted, corrupted,
lost, destroyed, arrive late or incomplete, or contain viruses. The sender
therefore does not accept liability for any errors or omissions in the
contents of this message, which arise as a result of e-mail transmission.

**Comment by daN4cat** [comment]
Good.
