### ISSUE TITLE
Not seeing Profits

### ISSUE THREAD

**Issue by tenkodoy** [jekkos/opensourcepos#997]
In the sales reports, profits are not showing

**Comment by daN4cat** [comment]
This is too vague to be answered.

**Comment by tenkodoy** [comment]
![profit](https://cloud.githubusercontent.com/assets/10381510/20492822/20b0d634-b00e-11e6-875f-4e7d9d34f165.JPG)

Please see the attached and notice what i was talking about

**Comment by daN4cat** [comment]
Which version of OSPOS are you using? Is that the last? Do you have tax set or not?
It's still too vague, how can I understand what the problem is without describing how to reproduce it?

**Comment by tenkodoy** [comment]
I'm using 3.0.0 and haven't set tax. I expected profit to show when sales report is pulled up. but it is just showing $0

**Comment by daN4cat** [comment]
Please try the latest code from master, 3.0.1. I fixed few things around how totals were calculated and etc.

**Comment by tenkodoy** [comment]
Ok...i will try that

**Comment by daN4cat** [comment]
Please let me know how it goes. I tried with no taxes and it seems fine, but if not on your side you need to tell me exactly your setup and what you entered in your item.

**Comment by tenkodoy** [comment]
I seem not to find the 3.0.1 master around here. could you please help me with the link and let me test that one to see

**Comment by daN4cat** [comment]
From https://github.com/jekkos/opensourcepos, see the green button "Clone or Download", click that and do Download. You'll get the latest code that is a 3.0.1 release candidate.

**Comment by daN4cat** [comment]
@tenkodoy have you managed to sort it out? Is it fine with the latest version?

**Comment by tenkodoy** [comment]
It turns out the I had both the 3.0 and 3.01. The latter doesnt show but the previous shows

**Comment by daN4cat** [comment]
Sorry is 3.0.1 not showing the profit? Can you please tell me what you set in the item exactly as price, cost and tax? Also do you have the check in Store config for tax included or not?
I need to know how to reproduce this. Thanks for the help.

**Comment by tenkodoy** [comment]
3.0.1 is not showing the profit...i set the cost to be $25 and selling price as $26. no tax on it

**Comment by daN4cat** [comment]
@tenkodoy I would have appreciated a bit of more help with this to be honest, at least to say exactly how to reproduce because it's a combination of what you set in the item and what in the Store config.

After testing all the possible combinations I found the one that causes that issue:

- item tax needs to be empty (NULL) and Store Config option needs to be no Tax included.

**Comment by tenkodoy** [comment]
i have checked and it turns out it was because i was not assigning taxes that was why the profits weren't showing. it's working now

**Comment by daN4cat** [comment]
Indeed, It's what I found as well. I'm not sure I want to touch this to cover the condition of NULL tax and tax  not included in total. It's a bit of a non-sense.
So I close.
