### ISSUE TITLE
weird error coming from 3.0.1 forbiden access

### ISSUE THREAD

**Issue by jzonetan** [jekkos/opensourcepos#999]
- [] Checked the current issues database and no similar issue was already discussed
- [x] Read the README, WHATS_NEW and UPGRADE
- [x] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php5-gd, php-intl and sockets installed)
- [] Reporting an issue of an unmodified OSPOS installation
- [x] PHP version is at least 5.5 and not 7.x
- [x] MySQL version is 5.5 or 5.6 and not 5.7
- [x] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [x] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [x] Know the name and version of OS, Web server and MySQL and will add to my issue report

### Installation information
clean install
fresh installation 3.0.1
windows 7 32bit arch
wampserver 3

### Expected behaviour

just running fine
### Actual behaviour
giving a 403 forbiden access from this

the older versions never had issues just this new version 3.0.1 and my server configurations are all granted so the only thing in my mind maybe an htaccess error something that it prevent me to view the pages

**Comment by daN4cat** [comment]
Are you pointing your OSPOS webroot to the public/ directory?

**Comment by jzonetan** [comment]
Yes i installed 3.0.0 its running fine but the 3.0.1 is giving me forbidden
access

**Comment by daN4cat** [comment]
Bye the way, what about this point in the checklist?

`Reporting an issue of an unmodified OSPOS installation`

**Comment by daN4cat** [comment]
Are you reporting something from modified code?

**Comment by jzonetan** [comment]
ohh sorry for that i dint read thru that.. i downloaded the master it always work like the way than using svn and this is the only version that i encounter this problem... other installation works perfeclty

**Comment by daN4cat** [comment]
Which Apache version do you use?

**Comment by daN4cat** [comment]
Also, do you use a subdir before pointing to oasis/public on your website?

**Comment by jzonetan** [comment]
Nope, its pointed on the htdocs/www/ospos folder that i created

Apache version: 2.4.17
Php version: 5.6.15
Mysql Version: 5.7.9

all 2 versions installed on my server V2+ and V3.0.0 were all run
smooth no restrictions

V3.0.1 the only version that i installed that had a issue

**Comment by jzonetan** [comment]
Problem Solved for this issue i forgot that its not the old uses "system' path that uses its a ospos/public (folder) i went to recheck the installation page... and boom i need to go the subdir(public) 

now my issue is that i can't login even importing the db or the default db.sql uses
